IMPACT: Bbox_3.h File Reference
Bbox_3.h File Reference
#include "rfc_basic.h"
#include <cmath>
Classes
class Bbox_3
Functions
bool do_overlap (const Bbox_3 &bb1, const Bbox_3 &bb2)
std::ostream & operator<< (std::ostream &os, const Bbox_3 &b)
std::istream & operator>> (std::istream &is, Bbox_3 &b)
bool do_overlap_eps (const Bbox_3 &bb1, const Bbox_3 &bb2, const double eps)
bool do_overlap_strict (const Bbox_3 &bb1, const Bbox_3 &bb2)
template<class InIter >
Bbox_3 get_Bbox_3 (InIter first, InIter last)
Function Documentation
bool do_overlap (const Bbox_3 & bb1, const Bbox_3 & bb2) inline
Definition at line 75 of file Bbox_3.h.
References Bbox_3::xmax(), Bbox_3::xmin(), Bbox_3::ymax(), Bbox_3::ymin(), Bbox_3::zmax(), and Bbox_3::zmin().
{
   return !(bb1.xmax() < bb2.xmin() || bb2.xmax() < bb1.xmin() ||
            bb1.ymax() < bb2.ymin() || bb2.ymax() < bb1.ymin() ||
            bb1.zmax() < bb2.zmin() || bb2.zmax() < bb1.zmin());
 }
bool do_overlap_eps (const Bbox_3 & bb1, const Bbox_3 & bb2, const double eps) inline
Definition at line 97 of file Bbox_3.h.
References Bbox_3::xmax(), Bbox_3::xmin(), Bbox_3::ymax(), Bbox_3::ymin(), Bbox_3::zmax(), and Bbox_3::zmin().
{
   // check for emptiness ??
   if (bb1.xmax()+eps < bb2.xmin() || bb2.xmax()+eps < bb1.xmin())
     return false;
   if (bb1.ymax()+eps < bb2.ymin() || bb2.ymax()+eps < bb1.ymin())
     return false;
   if (bb1.zmax()+eps < bb2.zmin() || bb2.zmax()+eps < bb1.zmin())
     return false;
   return true;
 }
bool do_overlap_strict (const Bbox_3 & bb1, const Bbox_3 & bb2) inline
Definition at line 109 of file Bbox_3.h.
References Bbox_3::xmax(), Bbox_3::xmin(), Bbox_3::ymax(), Bbox_3::ymin(), Bbox_3::zmax(), and Bbox_3::zmin().
 {
   // check for emptiness ??
   if (bb1.xmax() <= bb2.xmin() || bb2.xmax() <= bb1.xmin())
     return false;
   if (bb1.ymax() <= bb2.ymin() || bb2.ymax() <= bb1.ymin())
     return false;
   if (bb1.zmax() <= bb2.zmin() || bb2.zmax() <= bb1.zmin())
     return false;
   return true;
 }
template<class InIter > Bbox_3 get_Bbox_3 (InIter first, InIter last)
Definition at line 122 of file Bbox_3.h.
{
   Bbox_3  box;
   while (first != last) {
     box += first->bbox();
     ++first;
   }
   return box;
 }
std::ostream& operator<< (std::ostream & os, const Bbox_3 & b) inline
Definition at line 83 of file Bbox_3.h.
References Bbox_3::xmax(), Bbox_3::xmin(), Bbox_3::ymax(), Bbox_3::ymin(), Bbox_3::zmax(), and Bbox_3::zmin().
{
   return os << b.xmin() << ' ' << b.ymin() << ' ' << b.zmin() << ' '
             << b.xmax() << ' ' << b.ymax() << ' ' << b.zmax();
 }
std::istream& operator>> (std::istream & is, Bbox_3 & b) inline
Definition at line 89 of file Bbox_3.h.
{
   double xmin, ymin, zmin, xmax, ymax, zmax;
   is >> xmin >> ymin >> zmin >> xmax >> ymax >> zmax ;
   b = Bbox_3(xmin, ymin, zmin, xmax, ymax, zmax);
   return is;
 }