IMPACT: ZoomInterface Class Reference
ZoomInterface Class Reference
Detailed Description
Definition at line 183 of file basic_actions.h.
#include <basic_actions.h>
Public Member Functions
ZoomInterface (FluidAgent *ag, BurnAgent *bag, const std::string fb_mdot_alp, double z)
void init (double t)
void run (double t, double dt, double alpha)
Public Member Functions inherited from Action
Action (void *p=0, const char *name=NULL)
Action (int n, const char **at, int *i=NULL, void *p=0, const char *name=NULL)
Action (int n, const std::string at[], int *i=NULL, void *p=0, const char *name=NULL)
virtual ~Action ()
virtual void declare (Scheduler &)
virtual void finalize ()
virtual const char * name ()
void set_name (const char *name)
virtual void print (FILE *f)
virtual void print_toposort (FILE *f)
virtual void schedule ()
Private Attributes
FluidAgent * fagent
BurnAgent * bagent
int b_rb_alp_hdl
int fb_rhof_alp_hdl
int fb_mdot_alp_hdl
int rhos_hdl
double zoom
Additional Inherited Members
Protected Types inherited from Action
enum { IN =1, OUT =2, INOUT =3 }
Protected Member Functions inherited from Action
int get_dataitem_handle (int i)
int get_dataitem_handle_const (int i)
int get_dataitem_handle (const std::string str)
void set_attr (int n, const std::string at[], int *id=NULL)
void set_attr (int n, const char *at[], int *id=NULL)
void set_io (int n, const int *io)
void set_io (const char *io)
int get_io (int i)
Protected Attributes inherited from Action
const char * action_name
char ** attr
int * idx
int count
void * usr_ptr
std::vector< int > inout
Constructor & Destructor Documentation
ZoomInterface::ZoomInterface (FluidAgent * ag, BurnAgent * bag, const std::string fb_mdot_alp, double z)
Definition at line 676 of file basic_actions.C.
References Action::INOUT, Action::set_attr(), and Action::set_io().
                         :
                Action(0, (const char**)NULL, NULL, NULL, "ZoomInterface"),
                fagent(fag), bagent(bag), zoom(z)
 {
   int io[] = {INOUT};
   set_io( 1, io);
   std::string.data[1];
  .data[0] = fb_mdot_alp;
   set_attr(1,.data);
 }
Member Function Documentation
void ZoomInterface::init (double t) virtual
Reimplemented from Action.
Definition at line 690 of file basic_actions.C.
References b_rb_alp_hdl, bagent, COM_get_dataitem_handle(), fagent, fb_mdot_alp_hdl, fb_rhof_alp_hdl, FluidAgent::fluidBufB, Action::get_dataitem_handle(), BurnAgent::iburn_ng, and rhos_hdl.
{
   fb_mdot_alp_hdl = get_dataitem_handle( 0);
   rhos_hdl        = COM_get_dataitem_handle(bagent->iburn_ng+".rhos");
   //  b_rb_alp_hdl = COM_get_dataitem_handle( bagent->iburn_ng+".rb_alp");
   b_rb_alp_hdl = COM_get_dataitem_handle( bagent->iburn_ng+".rb");
   fb_rhof_alp_hdl = COM_get_dataitem_handle( fagent->fluidBufB+".rhof_alp");
 }
void ZoomInterface::run (double t, double dt, double alpha) virtual
Reimplemented from Action.
Definition at line 698 of file basic_actions.C.
References b_rb_alp_hdl, COM_call_function(), fb_mdot_alp_hdl, MAN_DEBUG, RocBlas::mul, rhos_hdl, and zoom.
{
   if (zoom <= 1.0) return;
   MAN_DEBUG(2, ("Rocman: ZoomInterface::run() with t:%e dt:%e zoom:%e.\n", t, dt, zoom));
   //  double z = zoom - 1;
   //  COM_call_function( RocBlas::mul_scalar, &b_rb_alp_hdl, &z, &b_rb_alp_hdl);
   //  Rocman should just pass in the normal mdot
   //  COM_call_function( RocBlas::axpy, &b_rb_alp_hdl, &fb_rhof_alp_hdl, &fb_mdot_alp_hdl, &fb_mdot_alp_hdl); (zoom)
   COM_call_function( RocBlas::mul, &b_rb_alp_hdl, &rhos_hdl, &fb_mdot_alp_hdl);
   // Sets mass flux to 0.0 on burned out faces
   // BurnOutFilter(bflag,0.0,mass_flux);
   // or BurnOutFilter(bflag,mass_flux_insulation,mass_flux);
   //  z = zoom / z;
   //  COM_call_function( RocBlas::mul_scalar, &b_rb_alp_hdl, &z, &b_rb_alp_hdl);
 }
Member Data Documentation
int ZoomInterface::b_rb_alp_hdl private
Definition at line 191 of file basic_actions.h.
Referenced by init(), and run().
BurnAgent* ZoomInterface::bagent private
Definition at line 190 of file basic_actions.h.
Referenced by init().
FluidAgent* ZoomInterface::fagent private
Definition at line 189 of file basic_actions.h.
Referenced by init().
int ZoomInterface::fb_mdot_alp_hdl private
Definition at line 191 of file basic_actions.h.
Referenced by init(), and run().
int ZoomInterface::fb_rhof_alp_hdl private
Definition at line 191 of file basic_actions.h.
Referenced by init().
int ZoomInterface::rhos_hdl private
Definition at line 191 of file basic_actions.h.
Referenced by init(), and run().
double ZoomInterface::zoom private
Definition at line 192 of file basic_actions.h.
Referenced by run().
The documentation for this class was generated from the following files:
basic_actions.h
basic_actions.C