IMPACT: SolverUtils::GeoPrim::CLine Class Reference
SolverUtils::GeoPrim::CLine Class Reference
Detailed Description
Definition at line 1320 of file GeoPrimitives.H.
#include <GeoPrimitives.H>
Public Member Functions
CLine ()
CLine (const CPoint &p1, const CPoint &p2)
CLine (const CLine &l)
CLine (const CPoint &p1, const CVector &v1)
CLine (const CVector &v1)
CLine & move (const CPoint &p1)
bool operator== (const CLine &l) const
bool has_point (const CPoint &p2) const
CVector & slope ()
const CVector & slope () const
CPoint & point ()
const CPoint & point () const
Protected Attributes
CPoint p
CVector v
Friends
double Distance (const CPoint &p, const CLine &l)
double Distance (const C3Point &p, const CLine &l)
Constructor & Destructor Documentation
SolverUtils::GeoPrim::CLine::CLine () inline
Definition at line 1327 of file GeoPrimitives.H.
     {};
SolverUtils::GeoPrim::CLine::CLine (const CPoint & p1, const CPoint & p2) inline
Definition at line 1329 of file GeoPrimitives.H.
       : p(p1),v(p1,p2)
     {};
SolverUtils::GeoPrim::CLine::CLine (const CLine & l) inline
Definition at line 1332 of file GeoPrimitives.H.
       : p(l.p), v(l.v)
     {};
SolverUtils::GeoPrim::CLine::CLine (const CPoint & p1, const CVector & v1) inline
Definition at line 1335 of file GeoPrimitives.H.
       : p(p1),v(v1)
     {};
SolverUtils::GeoPrim::CLine::CLine (const CVector & v1) inline
Definition at line 1338 of file GeoPrimitives.H.
       : p(0,0,0),v(v1)
     {};
Member Function Documentation
bool SolverUtils::GeoPrim::CLine::has_point (const CPoint & p2) const inline
Definition at line 1351 of file GeoPrimitives.H.
References SolverUtils::GeoPrim::CVector::normalize(), SolverUtils::GeoPrim::TOL, SolverUtils::GeoPrim::CVector::unit(), and v.
Referenced by SolverUtils::GeoPrim::CLineSegment::has_point().
     {
       CVector v2(p2,p);
       v2.normalize();
       double r = v2 * v.unit();
       return( (fabs(r - 1.0) < TOL) ||
               (fabs(r + 1.0) < TOL) );
     };
CLine& SolverUtils::GeoPrim::CLine::move (const CPoint & p1) inline
Definition at line 1341 of file GeoPrimitives.H.
     {
       p = p1;
       return(*this);
     };
bool SolverUtils::GeoPrim::CLine::operator== (const CLine & l) const inline
Definition at line 1346 of file GeoPrimitives.H.
References p, and v.
     {
       return( (p == l.p)  &&
               (v == l.v) );
     };
CPoint& SolverUtils::GeoPrim::CLine::point () inline
Definition at line 1367 of file GeoPrimitives.H.
     {
       return(p);
     };
const CPoint& SolverUtils::GeoPrim::CLine::point () const inline
Definition at line 1371 of file GeoPrimitives.H.
     {
       return(p);
     };
CVector& SolverUtils::GeoPrim::CLine::slope () inline
Definition at line 1359 of file GeoPrimitives.H.
References v.
     {
       return(v);
     };
const CVector& SolverUtils::GeoPrim::CLine::slope () const inline
Definition at line 1363 of file GeoPrimitives.H.
References v.
     {
       return(v);
     };
Friends And Related Function Documentation
double Distance (const CPoint & p, const CLine & l) friend
Definition at line 38 of file GeoPrimitives.C.
   {
     double u = (((p.x() - l.p.x())*l.v.x() + (p.y() - l.p.y())*l.v.y() +
                  (p.z() - l.p.z())*l.v.z())/l.v.mag2());
     CPoint p2(l.p.x()+(u*l.v.x()),l.p.y()+(u*l.v.y()),l.p.z()+(u*l.v.z()));
     CVector v(p,p2);
     return(v.mag());
   }
double Distance (const C3Point & p, const CLine & l) friend
Definition at line 48 of file GeoPrimitives.C.
   {
     double u = (((p.x() - l.p.x())*l.v.x() + (p.y() - l.p.y())*l.v.y() +
                  (p.z() - l.p.z())*l.v.z())/l.v.mag2());
     C3Point p2(l.p.x()+(u*l.v.x()),l.p.y()+(u*l.v.y()),l.p.z()+(u*l.v.z()));
     C3Vector v(p,p2);
     return(v.Mag());
   }
Member Data Documentation
CPoint SolverUtils::GeoPrim::CLine::p protected
Definition at line 1324 of file GeoPrimitives.H.
Referenced by SolverUtils::GeoPrim::Distance(), and operator==().
CVector SolverUtils::GeoPrim::CLine::v protected
Definition at line 1325 of file GeoPrimitives.H.
Referenced by SolverUtils::GeoPrim::Distance(), has_point(), operator==(), and slope().
The documentation for this class was generated from the following file:
GeoPrimitives.H