IMPACT: ComputeFaceCenters Class Reference
ComputeFaceCenters Class Reference
Detailed Description
Definition at line 142 of file basic_actions.h.
#include <basic_actions.h>
Public Member Functions
ComputeFaceCenters (BurnAgent *ag, const std::string b_nc, const std::string b_cnts, const std::string b_nrml="")
void init (double t)
void run (double t, double dt, double alpha)
Public Member Functions inherited from Action
Action (void *p=0, const char *name=NULL)
Action (int n, const char **at, int *i=NULL, void *p=0, const char *name=NULL)
Action (int n, const std::string at[], int *i=NULL, void *p=0, const char *name=NULL)
virtual ~Action ()
virtual void declare (Scheduler &)
virtual void finalize ()
virtual const char * name ()
void set_name (const char *name)
virtual void print (FILE *f)
virtual void print_toposort (FILE *f)
virtual void schedule ()
Private Attributes
BurnAgent * agent
int b_nc_hdl
int b_cnts_hdl
int b_nrml_hdl
int SURF_n2f
int SURF_fn
Additional Inherited Members
Protected Types inherited from Action
enum { IN =1, OUT =2, INOUT =3 }
Protected Member Functions inherited from Action
int get_dataitem_handle (int i)
int get_dataitem_handle_const (int i)
int get_dataitem_handle (const std::string str)
void set_attr (int n, const std::string at[], int *id=NULL)
void set_attr (int n, const char *at[], int *id=NULL)
void set_io (int n, const int *io)
void set_io (const char *io)
int get_io (int i)
Protected Attributes inherited from Action
const char * action_name
char ** attr
int * idx
int count
void * usr_ptr
std::vector< int > inout
Constructor & Destructor Documentation
ComputeFaceCenters::ComputeFaceCenters (BurnAgent * ag, const std::string b_nc, const std::string b_cnts, const std::string b_nrml = "")
Definition at line 371 of file basic_actions.C.
References Action::IN, Action::OUT, Action::set_attr(), and Action::set_io().
                                                               :
                    Action(0, (const char**)NULL, NULL, NULL, "ComputeFaceCenters"), agent(ag)
 {
   int io[] = {IN, OUT};
   set_io( 2, io);
   std::string.data[3];
  .data[0] = b_nc;
  .data[1] = b_cnts;
  .data[2] = b_nrml;
   set_attr(3,.data);
 }
Member Function Documentation
void ComputeFaceCenters::init (double t) virtual
Reimplemented from Action.
Definition at line 385 of file basic_actions.C.
{
 /*
   b_nc_hdl = get_dataitem_handle(0);
   if (COM_get_dataitem_handle(agent->get_surface_window()+".centers") > 0)
     b_cnts_hdl = get_dataitem_handle(1);
   else
     b_cnts_hdl = -1;
   load_rocsurf();
   SURF_n2f = COM_get_function_handle( "SURF.interpolate_to_centers");
 */
 }
void ComputeFaceCenters::run (double t, double dt, double alpha) virtual
Reimplemented from Action.
Definition at line 398 of file basic_actions.C.
References agent, Action::attr, b_cnts_hdl, b_nc_hdl, b_nrml_hdl, COM_call_function(), COM_get_dataitem_handle(), COM_get_function_handle(), Action::get_dataitem_handle(), Agent::get_surface_window(), load_rocsurf(), MAN_DEBUG, SURF_fn, and SURF_n2f.
{
   // ???????????
 /*
   double a = 0.0;
   int level = 1;
   agent->obtain_bc(&a, &level);
 */
   b_nc_hdl = get_dataitem_handle(attr[0]);
   b_cnts_hdl = -1;
   if (COM_get_dataitem_handle(agent->get_surface_window()+".centers") > 0){
     b_cnts_hdl = get_dataitem_handle(1);
   }
   b_nrml_hdl = -1;
   if(COM_get_dataitem_handle(agent->get_surface_window()+".normals") > 0){
     b_nrml_hdl = get_dataitem_handle(2);
   }
   // ?????????????
 //  double zero = 0.0;
 //  agent->obtain_bc(&zero);
   if (b_cnts_hdl >= 0 || b_nrml_hdl >= 0) {
     load_rocsurf();
     MAN_DEBUG(2, ("Rocman: ComputeFaceCenters::run() with t:%e dt:%e b_cnts_hdl:%d b_nrml_hdl:%d.\n", t, dt, b_cnts_hdl, b_nrml_hdl));
     if(b_cnts_hdl >= 0){
       SURF_n2f = COM_get_function_handle( "SURF.interpolate_to_centers");
       COM_call_function( SURF_n2f, &b_nc_hdl, &b_cnts_hdl);
     }
     if(b_nrml_hdl >= 0){
       SURF_fn  = COM_get_function_handle( "SURF.compute_element_normals");
       COM_call_function( SURF_fn, &b_nc_hdl,  &b_nrml_hdl);
     }
   }
 }
Member Data Documentation
BurnAgent* ComputeFaceCenters::agent private
Definition at line 149 of file basic_actions.h.
Referenced by run().
int ComputeFaceCenters::b_cnts_hdl private
Definition at line 150 of file basic_actions.h.
Referenced by run().
int ComputeFaceCenters::b_nc_hdl private
Definition at line 150 of file basic_actions.h.
Referenced by run().
int ComputeFaceCenters::b_nrml_hdl private
Definition at line 150 of file basic_actions.h.
Referenced by run().
int ComputeFaceCenters::SURF_fn private
Definition at line 151 of file basic_actions.h.
Referenced by run().
int ComputeFaceCenters::SURF_n2f private
Definition at line 151 of file basic_actions.h.
Referenced by run().
The documentation for this class was generated from the following files:
basic_actions.h
basic_actions.C