IMPACT: Action Class Reference
Action Class Reference
Detailed Description
Definition at line 17 of file Action.h.
#include <Action.h>
Public Member Functions
Action (void *p=0, const char *name=NULL)
Action (int n, const char **at, int *i=NULL, void *p=0, const char *name=NULL)
Action (int n, const std::string at[], int *i=NULL, void *p=0, const char *name=NULL)
virtual ~Action ()
virtual void declare (Scheduler &)
virtual void init (double t)
virtual void run (double t, double dt, double alpha)
virtual void finalize ()
virtual const char * name ()
void set_name (const char *name)
virtual void print (FILE *f)
virtual void print_toposort (FILE *f)
virtual void schedule ()
Protected Types
enum { IN =1, OUT =2, INOUT =3 }
Protected Member Functions
int get_dataitem_handle (int i)
int get_dataitem_handle_const (int i)
int get_dataitem_handle (const std::string str)
void set_attr (int n, const std::string at[], int *id=NULL)
void set_attr (int n, const char *at[], int *id=NULL)
void set_io (int n, const int *io)
void set_io (const char *io)
int get_io (int i)
Protected Attributes
const char * action_name
char ** attr
int * idx
int count
void * usr_ptr
std::vector< int > inout
Member Enumeration Documentation
anonymous enum protected
Enumerator
IN
OUT
INOUT
Definition at line 20 of file Action.h.
 { IN=1, OUT=2, INOUT=3 };
Constructor & Destructor Documentation
Action::Action (void * p = 0, const char * name = NULL)
Definition at line 15 of file Action.C.
                                        : action_name(name), attr(NULL),
                                      idx(NULL), count(0), usr_ptr(p)
 {
 }
Action::Action (int n, const char ** at, int * i = NULL, void * p = 0, const char * name = NULL)
Definition at line 25 of file Action.C.
References action_name, and set_attr().
                                                                         : action_name(name), count(n), usr_ptr(p)
 {
   set_attr(n, at, id);
   if (action_name == NULL) action_name = (char*)typeid(*this).name();
 }
Action::Action (int n, const std::string at[], int * i = NULL, void * p = 0, const char * name = NULL)
Definition at line 30 of file Action.C.
References action_name, and set_attr().
                                                                              : action_name(name), count(n), usr_ptr(p)
 {
   set_attr(n, at, id);
   if (action_name == NULL) action_name = (char*)typeid(*this).name();
 }
Action::~Action () virtual
Definition at line 36 of file Action.C.
References attr, count, and idx.
 {
   for (int i=0; i<count; i++) free(attr[i]);
   delete [] attr;
   delete [] idx;
 }
Member Function Documentation
void Action::declare (Scheduler & sched) virtual
Reimplemented in PhysicsAction, SchedulerAction, ActionG, ActionF, ActionE, ActionD, ActionC, ActionB, and ActionA.
Definition at line 64 of file Action.C.
References attr, count, idx, IN, inout, OUT, Scheduler::reads(), and Scheduler::writes().
Referenced by Scheduler::add_action().
{
   //CmiAssert(count>0);
   for ( int i=0; i<count; ++i) {
     if ( inout[i] & IN)
       sched.reads(this, attr[i], idx[i]);
     if ( inout[i] & OUT)
       sched.writes(this, attr[i], idx[i]);
   }
 }
virtual void Action::finalize () inline virtual
Reimplemented in UserSchedulerAction, and SchedulerAction.
Definition at line 38 of file Action.h.
Referenced by Scheduler::finalize_actions().
 { /* printf("Rocman: Action %s finalized. \n", name()); */ }
int Action::get_dataitem_handle (int i) protected
Definition at line 80 of file Action.C.
References attr, COM_assertion_msg, and COM_get_dataitem_handle().
Referenced by InterpolateBase::init(), SetValueDouble::init(), LoadTransfer_FS::init(), CopyValue::init(), LoadTransfer_FSc_ALE::init(), LoadTransferOnly_FSc_ALE::init(), GetDeformedMesh::init(), GetDeformedMesh_ALE::init(), MeshMotionTransfer_SF::init(), ComputeFluidLoad_ALE::init(), DeformationVelTransfer_SF::init(), ComputeMeshMotion::init(), MeshMotionTransferISS::init(), TransferSolidDensity::init(), FluidPropagateSurface::init(), TransferBurnRate_FS_ALE::init(), MassTransfer_SF_ALE::init(), MassTransfer::init(), TemperatureTransfer_SF::init(), ZoomInterface::init(), HeatTransfer_FS::init(), ComputeBurnPane::init(), RemeshInit::init(), ComputePconn::init(), SolidPropagateSurface_ALE::init(), and ComputeFaceCenters::run().
{
   COM_assertion_msg ( attr[i]!=NULL, (std::string("DataItem \"")
                               +"\" does not exist").c_str());
   int hdl = COM_get_dataitem_handle( attr[i]);
   COM_assertion_msg ( hdl>0, (std::string("DataItem \"")+attr[i]
                               +"\" does not exist").c_str());
   return hdl;
 }
int Action::get_dataitem_handle (const std::string str) protected
Definition at line 89 of file Action.C.
References COM_assertion_msg, and COM_get_dataitem_handle().
{
   int hdl = COM_get_dataitem_handle( str);
   COM_assertion_msg ( hdl>0, (std::string("DataItem \"")+str
                               +"\" does not exist").c_str());
   return hdl;
 }
int Action::get_dataitem_handle_const (int i) protected
Definition at line 97 of file Action.C.
References attr, COM_assertion_msg, and COM_get_dataitem_handle_const().
Referenced by InterpolateBase::init(), LoadTransfer_FSc_ALE::init(), LoadTransferOnly_FSc_ALE::init(), and ComputeFluidLoad_ALE::init().
{
   int hdl = COM_get_dataitem_handle_const( attr[i]);
   COM_assertion_msg ( hdl>0, (std::string("DataItem \"")+attr[i]
                               +"\" does not exist").c_str());
   return hdl;
 }
int Action::get_io (int i) inline protected
Definition at line 60 of file Action.h.
References inout.
Referenced by InterpolateBase::init().
 { return inout[i]; }
virtual void Action::init (double t) inline virtual
Reimplemented in Reset_du_alp, SolidPropagateSurface_ALE, ComputePconn, CopyBflagFromBurn, CopyBurnFromParentMesh, RemeshInit, ComputeBurnPane, ComputeRhofvf, HeatTransfer_FS, ZoomInterface, TemperatureTransfer_SF, MassTransfer, MassTransfer_SF_ALE, TransferBurnRate_FS_ALE, FluidPropagateSurface, TransferSolidDensity, ComputeFaceCenters, ComputeMeshMotion, MeshMotionTransferISS, DeformationVelTransfer_SF, ComputeFluidLoad_ALE, MeshMotionTransfer_SF, SurfDiver, GetDeformedMesh_ALE, UserSchedulerAction, BCInitInvoker, GetDeformedMesh, GMInvoker, SchedulerAction, LoadTransferOnly_FSc_ALE, BCInvoker, DummyPrint, LoadTransfer_FSc_ALE, Extrapolate_Central, CopyValue, Extrapolate_Linear, LoadTransfer_FS, SetValueDouble, DummyAction, and InterpolateBase.
Definition at line 36 of file Action.h.
Referenced by Scheduler::init_actions().
 { /* printf("Rocman: Action %s init. \n", name());*/ }
virtual const char* Action::name () inline virtual
Reimplemented in PhysicsAction.
Definition at line 39 of file Action.h.
References action_name.
Referenced by InterpolateBase::init(), print(), SchedulerAction::print(), UserSchedulerAction::print(), print_toposort(), Scheduler::reads(), Scheduler::set_name(), and Scheduler::writes().
 { return action_name; }
void Action::print (FILE * f) virtual
Reimplemented in PhysicsAction.
Definition at line 74 of file Action.C.
References name().
Referenced by Scheduler::print_helper(), and readsdv().
 {
   fprintf(f, "node: { title:\"%s\" label:\"%s\"}\n", name(), name());
 }
virtual void Action::print_toposort (FILE * f) inline virtual
Reimplemented in UserSchedulerAction, and SchedulerAction.
Definition at line 42 of file Action.h.
References name().
 { fprintf(f, "%s ", name()); }
virtual void Action::run (double t, double dt, double alpha) inline virtual
Reimplemented in Reset_du_alp, SolidPropagateSurface_ALE, ComputePconn, CopyBflagFromBurn, CopyBurnFromParentMesh, RemeshInit, ComputeBurnPane, ComputeRhofvf, HeatTransfer_FS, ZoomInterface, TemperatureTransfer_SF, MassTransfer, MassTransfer_SF_ALE, TransferBurnRate_FS_ALE, FluidPropagateSurface, TransferSolidDensity, ComputeFaceCenters, PhysicsAction, ComputeMeshMotion, MeshMotionTransferISS, DeformationVelTransfer_SF, ComputeFluidLoad_ALE, SurfDiverAfterRemeshing, MeshMotionTransfer_SF, SurfDiver, GetDeformedMesh_ALE, UserSchedulerAction, BCInitInvoker, GetDeformedMesh, GMInvoker, SchedulerAction, LoadTransferOnly_FSc_ALE, BCInvoker, Interpolate_Central, Interpolate_Constant, DummyPrint, Interpolate_Linear, LoadTransfer_FSc_ALE, Extrapolate_Central, CopyValue, Extrapolate_Linear, LoadTransfer_FS, SetValueDouble, DummyAction, and InterpolateBase.
Definition at line 37 of file Action.h.
Referenced by Scheduler::run_actions().
 {/* printf("Action %s runs. \n", name()); */}
virtual void Action::schedule () inline virtual
Reimplemented in UserSchedulerAction, and SchedulerAction.
Definition at line 43 of file Action.h.
 {}                      // do nothing
void Action::set_attr (int n, const std::string at[], int * id = NULL) protected
Definition at line 53 of file Action.C.
References attr, count, and idx.
Referenced by Action(), BCInitInvoker::BCInitInvoker(), BCInvoker::BCInvoker(), ComputeBurnPane::ComputeBurnPane(), ComputeFaceCenters::ComputeFaceCenters(), ComputeFluidLoad_ALE::ComputeFluidLoad_ALE(), ComputeMeshMotion::ComputeMeshMotion(), ComputePconn::ComputePconn(), ComputeRhofvf::ComputeRhofvf(), CopyBflagFromBurn::CopyBflagFromBurn(), CopyBurnFromParentMesh::CopyBurnFromParentMesh(), CopyValue::CopyValue(), DeformationVelTransfer_SF::DeformationVelTransfer_SF(), DummyPrint::DummyPrint(), Extrapolate_Central::Extrapolate_Central(), Extrapolate_Linear::Extrapolate_Linear(), FluidPropagateSurface::FluidPropagateSurface(), GetDeformedMesh::GetDeformedMesh(), GetDeformedMesh_ALE::GetDeformedMesh_ALE(), GMInvoker::GMInvoker(), HeatTransfer_FS::HeatTransfer_FS(), Interpolate_Central::Interpolate_Central(), Interpolate_Constant::Interpolate_Constant(), Interpolate_Linear::Interpolate_Linear(), LoadTransfer_FS::LoadTransfer_FS(), LoadTransfer_FSc_ALE::LoadTransfer_FSc_ALE(), LoadTransferOnly_FSc_ALE::LoadTransferOnly_FSc_ALE(), MassTransfer::MassTransfer(), MassTransfer_SF_ALE::MassTransfer_SF_ALE(), MeshMotionTransfer_SF::MeshMotionTransfer_SF(), MeshMotionTransferISS::MeshMotionTransferISS(), RemeshInit::RemeshInit(), Reset_du_alp::Reset_du_alp(), SolidPropagateSurface_ALE::SolidPropagateSurface_ALE(), TemperatureTransfer_SF::TemperatureTransfer_SF(), TransferBurnRate_FS_ALE::TransferBurnRate_FS_ALE(), TransferSolidDensity::TransferSolidDensity(), and ZoomInterface::ZoomInterface().
 {
   int i;
   count = n;
   attr = new char *[count];
   for (i=0; i<count; i++) attr[i] = strdup(at[i].c_str());
   idx = new int[count];
   for (i=0; i<count; i++) idx[i] = id?id[i]:0;
 }
void Action::set_attr (int n, const char * at[], int * id = NULL) protected
Definition at line 43 of file Action.C.
References attr, count, and idx.
 {
   int i;
   count = n;
   attr = new char *[count];
   for (i=0; i<count; i++) attr[i] = strdup(at[i]);
   idx = new int[count];
   for (i=0; i<count; i++) idx[i] = id?id[i]:0;
 }
void Action::set_io (int n, const int * io) inline protected
Definition at line 56 of file Action.h.
References count, and inout.
Referenced by BCInitInvoker::BCInitInvoker(), BCInvoker::BCInvoker(), ComputeBurnPane::ComputeBurnPane(), ComputeFaceCenters::ComputeFaceCenters(), ComputeFluidLoad_ALE::ComputeFluidLoad_ALE(), ComputeMeshMotion::ComputeMeshMotion(), ComputePconn::ComputePconn(), ComputeRhofvf::ComputeRhofvf(), CopyBflagFromBurn::CopyBflagFromBurn(), CopyBurnFromParentMesh::CopyBurnFromParentMesh(), CopyValue::CopyValue(), DeformationVelTransfer_SF::DeformationVelTransfer_SF(), DummyPrint::DummyPrint(), Extrapolate_Central::Extrapolate_Central(), Extrapolate_Linear::Extrapolate_Linear(), FluidPropagateSurface::FluidPropagateSurface(), GetDeformedMesh::GetDeformedMesh(), GetDeformedMesh_ALE::GetDeformedMesh_ALE(), GMInvoker::GMInvoker(), HeatTransfer_FS::HeatTransfer_FS(), Interpolate_Central::Interpolate_Central(), Interpolate_Constant::Interpolate_Constant(), Interpolate_Linear::Interpolate_Linear(), LoadTransfer_FS::LoadTransfer_FS(), LoadTransfer_FSc_ALE::LoadTransfer_FSc_ALE(), LoadTransferOnly_FSc_ALE::LoadTransferOnly_FSc_ALE(), MassTransfer::MassTransfer(), MassTransfer_SF_ALE::MassTransfer_SF_ALE(), MeshMotionTransfer_SF::MeshMotionTransfer_SF(), MeshMotionTransferISS::MeshMotionTransferISS(), RemeshInit::RemeshInit(), Reset_du_alp::Reset_du_alp(), SetValueDouble::SetValueDouble(), SolidPropagateSurface_ALE::SolidPropagateSurface_ALE(), TemperatureTransfer_SF::TemperatureTransfer_SF(), TransferBurnRate_FS_ALE::TransferBurnRate_FS_ALE(), TransferSolidDensity::TransferSolidDensity(), and ZoomInterface::ZoomInterface().
   { inout.clear(); inout.insert( inout.end(), io, io+n); if (count==0) count=n; }
void Action::set_io (const char * io) protected
void Action::set_name (const char * name) inline
Definition at line 40 of file Action.h.
References action_name.
Referenced by Agent::Agent().
 { action_name = strdup(name); }
Member Data Documentation
const char* Action::action_name protected
Definition at line 21 of file Action.h.
Referenced by Action(), Extrapolate_Central::Extrapolate_Central(), Extrapolate_Linear::Extrapolate_Linear(), Interpolate_Central::Interpolate_Central(), Interpolate_Constant::Interpolate_Constant(), Interpolate_Linear::Interpolate_Linear(), name(), set_name(), and SetZero::SetZero().
char** Action::attr protected
Definition at line 22 of file Action.h.
Referenced by InterpolateBase::backup(), declare(), Extrapolate_Central::Extrapolate_Central(), Extrapolate_Linear::Extrapolate_Linear(), get_dataitem_handle(), get_dataitem_handle_const(), InterpolateBase::init(), Extrapolate_Linear::init(), Extrapolate_Central::init(), ComputeMeshMotion::init(), HeatTransfer_FS::init(), ComputeRhofvf::init(), Interpolate_Central::Interpolate_Central(), Interpolate_Constant::Interpolate_Constant(), Interpolate_Linear::Interpolate_Linear(), SetValueDouble::run(), Extrapolate_Linear::run(), CopyValue::run(), Extrapolate_Central::run(), Interpolate_Linear::run(), Interpolate_Central::run(), ComputeFaceCenters::run(), set_attr(), and ~Action().
int Action::count protected
Definition at line 24 of file Action.h.
Referenced by declare(), set_attr(), set_io(), and ~Action().
int* Action::idx protected
Definition at line 23 of file Action.h.
Referenced by declare(), set_attr(), and ~Action().
std::vector<int> Action::inout protected
Definition at line 27 of file Action.h.
Referenced by declare(), get_io(), and set_io().
void* Action::usr_ptr protected
Definition at line 25 of file Action.h.
The documentation for this class was generated from the following files:
Action.h
Action.C