IMPACT: Element_vectors_k_const< Value > Class Template Reference
Element_vectors_k_const< Value > Class Template Reference
This is a helper class for accessing elemental data.
Detailed Description
template<class Value>
class Element_vectors_k_const< Value >
Definition at line 294 of file Element_accessors.hpp.
#include <Element_accessors.hpp>
Public Types
typedef unsigned int Size
Public Member Functions
Element_vectors_k_const ()
Default constructor.
void set (const Value *p, Element_node_enumerator &ene, int strd)
initialize the accessor with a pointer and a specific stride.
void set (const DataItem *a, Element_node_enumerator &ene)
initialize the accessor from an attribute assiciated with a pane.
const Value & operator() (int i, int j) const
const Value & operator() (int i) const
const Value & operator[] (int i) const
Protected Attributes
const DataItem * _attr
union {
int _offset
const Value * _vs
};
Member Typedef Documentation
template<class Value> typedef unsigned int Element_vectors_k_const< Value >::Size
Definition at line 296 of file Element_accessors.hpp.
Constructor & Destructor Documentation
template<class Value> Element_vectors_k_const< Value >::Element_vectors_k_const () inline
Definition at line 299 of file Element_accessors.hpp.
 : _attr(NULL), _vs(NULL) {}
Member Function Documentation
template<class Value> const Value& Element_vectors_k_const< Value >::operator() (int i, int j) const inline
Definition at line 326 of file Element_accessors.hpp.
References Element_vectors_k_const< Value >::_attr, Element_vectors_k_const< Value >::_offset, Element_vectors_k_const< Value >::_vs, COM_assertion, and DataItem::size_of_components().
Referenced by Element_vectors_k< Value >::operator()(), Element_vectors_k_const< Value >::operator[](), and Element_vectors_k< Value >::operator[]().
{
     if ( _attr) {
       COM_assertion( _attr->size_of_components()>1);
       const DataItem *aj = _attr+j+1;
       return reinterpret_cast<const Value*>
         (aj->pointer())[_offset*aj->stride()];
     }
     else
       return _vs[j];
   }
template<class Value> const Value& Element_vectors_k_const< Value >::operator() (int i) const inline
Definition at line 337 of file Element_accessors.hpp.
References Element_vectors_k_const< Value >::operator()().
Referenced by Element_vectors_k_const< Value >::operator()().
 { return operator()(i,0); }
template<class Value> const Value& Element_vectors_k_const< Value >::operator[] (int i) const inline
Definition at line 339 of file Element_accessors.hpp.
References Element_vectors_k_const< Value >::operator()().
 { return operator()(i,0); }
template<class Value> void Element_vectors_k_const< Value >::set (const Value * p, Element_node_enumerator & ene, int strd) inline
Definition at line 302 of file Element_accessors.hpp.
References Element_vectors_k_const< Value >::_attr, Element_vectors_k_const< Value >::_vs, and Element_node_enumerator::id().
Referenced by Window_manifold_2::elements_to_nodes(), and Element_vectors_k< Value >::set().
{
     _attr = NULL;
     _vs = &p[(ene.id()-1)*strd];
   }
template<class Value> void Element_vectors_k_const< Value >::set (const DataItem * a, Element_node_enumerator & ene) inline
Definition at line 308 of file Element_accessors.hpp.
References Element_vectors_k_const< Value >::_attr, Element_vectors_k_const< Value >::_offset, Element_vectors_k_const< Value >::_vs, COM_assertion, COM_get_sizeof(), DataItem::data_type(), Pane::id(), Element_node_enumerator::id(), DataItem::is_elemental(), DataItem::pane(), DataItem::pointer(), DataItem::size_of_components(), strd, and DataItem::stride().
{
     COM_assertion( a->is_elemental() && a->pane()->id());
     COM_assertion( sizeof(Value)==COM_get_sizeof( a->data_type(),1));
     int ncomp = a->size_of_components();
     int strd = a->stride();
     if ( ncomp<=strd) {
       const Value *p = reinterpret_cast<const Value*>(a->pointer());
       _attr = NULL;
       _vs = &p[(ene.id()-1)*strd];
     }
     else {
       _attr = a;
       _offset = ene.id()-1;
     }
   }
Member Data Documentation
union { ... }
template<class Value> const DataItem* Element_vectors_k_const< Value >::_attr protected
Definition at line 342 of file Element_accessors.hpp.
Referenced by Element_vectors_k_const< Value >::operator()(), and Element_vectors_k_const< Value >::set().
template<class Value> int Element_vectors_k_const< Value >::_offset
Definition at line 344 of file Element_accessors.hpp.
Referenced by Element_vectors_k_const< Value >::operator()(), and Element_vectors_k_const< Value >::set().
template<class Value> const Value* Element_vectors_k_const< Value >::_vs
Definition at line 345 of file Element_accessors.hpp.
Referenced by Element_vectors_k_const< Value >::operator()(), and Element_vectors_k_const< Value >::set().
The documentation for this class was generated from the following file:
Element_accessors.hpp