IMPACT: MassTransfer Class Reference
MassTransfer Class Reference
Detailed Description
Definition at line 172 of file basic_actions.h.
#include <basic_actions.h>
Public Member Functions
MassTransfer (FluidAgent *ag, BurnAgent *bag, const std::string b_rhos, const std::string b_rb, const std::string f_mdot)
void init (double t)
void run (double t, double dt, double alpha)
Public Member Functions inherited from Action
Action (void *p=0, const char *name=NULL)
Action (int n, const char **at, int *i=NULL, void *p=0, const char *name=NULL)
Action (int n, const std::string at[], int *i=NULL, void *p=0, const char *name=NULL)
virtual ~Action ()
virtual void declare (Scheduler &)
virtual void finalize ()
virtual const char * name ()
void set_name (const char *name)
virtual void print (FILE *f)
virtual void print_toposort (FILE *f)
virtual void schedule ()
Private Attributes
FluidAgent * fagent
BurnAgent * bagent
int f_mdot_hdl
int b_rhos_hdl
int b_rb_hdl
int fb_mdot_hdl
Additional Inherited Members
Protected Types inherited from Action
enum { IN =1, OUT =2, INOUT =3 }
Protected Member Functions inherited from Action
int get_dataitem_handle (int i)
int get_dataitem_handle_const (int i)
int get_dataitem_handle (const std::string str)
void set_attr (int n, const std::string at[], int *id=NULL)
void set_attr (int n, const char *at[], int *id=NULL)
void set_io (int n, const int *io)
void set_io (const char *io)
int get_io (int i)
Protected Attributes inherited from Action
const char * action_name
char ** attr
int * idx
int count
void * usr_ptr
std::vector< int > inout
Constructor & Destructor Documentation
MassTransfer::MassTransfer (FluidAgent * ag, BurnAgent * bag, const std::string b_rhos, const std::string b_rb, const std::string f_mdot)
Definition at line 634 of file basic_actions.C.
References bagent, BurnAgent::iburn_all, Action::IN, Action::OUT, BurnAgent::parentWin, Agent::register_use_dataitem(), Action::set_attr(), and Action::set_io().
                                          :
                    Action(0, (const char**)NULL, NULL, NULL, "MassTransfer"),
                    fagent(fag), bagent(bag)
 {
   int io[] = {IN, IN, OUT};
   set_io( 3, io);
   std::string.data[3];
  .data[0] = b_rhos;
  .data[1] = b_rb;
  .data[2] = f_mdot;
   set_attr(3,.data);
   bagent->register_use_dataitem( bagent->iburn_all, ".rhos", bagent->parentWin, ".rhos");
 }
Member Function Documentation
void MassTransfer::init (double t) virtual
Reimplemented from Action.
Definition at line 652 of file basic_actions.C.
References b_rb_hdl, b_rhos_hdl, COM_get_dataitem_handle(), f_mdot_hdl, fagent, fb_mdot_hdl, FluidAgent::fluidBufB, and Action::get_dataitem_handle().
{
   b_rhos_hdl = get_dataitem_handle( 0);
   b_rb_hdl = get_dataitem_handle( 1);
   f_mdot_hdl = get_dataitem_handle( 2);
   fb_mdot_hdl = COM_get_dataitem_handle( fagent->fluidBufB+".mdot");
 }
void MassTransfer::run (double t, double dt, double alpha) virtual
Reimplemented from Action.
Definition at line 660 of file basic_actions.C.
References b_rb_hdl, b_rhos_hdl, COM_call_function(), RocBlas::copy_scalar, f_mdot_hdl, fb_mdot_hdl, MAN_DEBUG, and RocBlas::mul.
{
   MAN_DEBUG(2, ("Rocman: MassTransfer::run() with t:%e dt:%e.\n", t, dt));
   double zero = 0.0;
   COM_call_function( RocBlas::copy_scalar, &zero, &f_mdot_hdl);
   COM_call_function( RocBlas::mul, &b_rhos_hdl, &b_rb_hdl, &fb_mdot_hdl);
   // Sets mass flux to 0.0 on burned out faces
   // BurnOutFilter(bflag,0.0,mass_flux);
   // or BurnOutFilter(bflag,mass_flux_insulation,mass_flux);
 //  debug_print(fagent->fluidBufB+".mdot", 102, 0);
 //  debug_print(bagent->iburn_ng+".rb", 102, 0);
 }
Member Data Documentation
int MassTransfer::b_rb_hdl private
Definition at line 180 of file basic_actions.h.
Referenced by init(), and run().
int MassTransfer::b_rhos_hdl private
Definition at line 180 of file basic_actions.h.
Referenced by init(), and run().
BurnAgent* MassTransfer::bagent private
Definition at line 179 of file basic_actions.h.
Referenced by MassTransfer().
int MassTransfer::f_mdot_hdl private
Definition at line 180 of file basic_actions.h.
Referenced by init(), and run().
FluidAgent* MassTransfer::fagent private
Definition at line 178 of file basic_actions.h.
Referenced by init().
int MassTransfer::fb_mdot_hdl private
Definition at line 180 of file basic_actions.h.
Referenced by init(), and run().
The documentation for this class was generated from the following files:
basic_actions.h
basic_actions.C