IMPACT: SolverUtils::FEM::SolverAgent Class Reference
SolverUtils::FEM::SolverAgent Class Reference
Detailed Description
Definition at line 11 of file SolverAgent.H.
#include <SolverAgent.H>
Public Member Functions
const FEM::SolutionData & Solution () const
FEM::SolutionData & Solution ()
const Mesh::UnstructuredMesh & Mesh () const
Mesh::UnstructuredMesh & Mesh ()
void ReadMeshFromStream (std::istream &Istr)
void WriteMeshToStream (std::ostream &Ostr)
void ReadCoordsFromStream (std::istream &Istr)
void WriteCoordsToStream (std::ostream &Ostr)
void ReadSolnMetaFromStream (std::istream &Istr)
void WriteSolnMetaToStream (std::ostream &Ostr)
void CreateSoln ()
void ReadSolnFromStream (std::istream &Istr, const std::string &name)
void WriteSolnToStream (std::ostream &Ostr, const std::string &name)
std::ostream & ReportMeshToStream (std::ostream &Ostr)
~SolverAgent ()
Private Attributes
Mesh::UnstructuredMesh mesh
FEM::SolutionData soln
Constructor & Destructor Documentation
SolverUtils::FEM::SolverAgent::~SolverAgent () inline
Definition at line 135 of file SolverAgent.H.
 {};
Member Function Documentation
void SolverUtils::FEM::SolverAgent::CreateSoln () inline
Definition at line 46 of file SolverAgent.H.
References SolverUtils::FEM::SolutionData::Create(), Mesh(), and Solution().
Referenced by COM::TestModule::InitSolver(), and COM::TransferSolver::Setup().
     {
       Solution().Create(Mesh());
     };
const Mesh::UnstructuredMesh& SolverUtils::FEM::SolverAgent::Mesh () const inline
Definition at line 19 of file SolverAgent.H.
References mesh.
Referenced by SolverUtils::AgentToPane(), CreateSoln(), SolverUtils::CreateSolutionFromPane(), COM::TestModule::InitSolver(), COM::TransferSolver::NElem(), COM::TransferSolver::NNodes(), SolverUtils::PaneToAgent(), ReadCoordsFromStream(), ReadMeshFromStream(), SolverUtils::FEM::FDSolverAgent::ReceiveCoords(), SolverUtils::FEM::FDSolverAgent::ReceiveMesh(), SolverUtils::FEM::FDSolverAgent::SendCoords(), SolverUtils::FEM::FDSolverAgent::SendMesh(), COM::TransferSolver::Setup(), COM::TestModule::Step(), SolverUtils::UpdateAgentCoordinatesFromPane(), WriteCoordsToStream(), WriteMeshToStream(), and SolverUtils::WriteVTKToStream().
 { return(mesh); };
Mesh::UnstructuredMesh& SolverUtils::FEM::SolverAgent::Mesh () inline
Definition at line 20 of file SolverAgent.H.
References mesh.
 { return(mesh); };
void SolverUtils::FEM::SolverAgent::ReadCoordsFromStream (std::istream & Istr) inline
Definition at line 30 of file SolverAgent.H.
References Mesh(), and SolverUtils::Mesh::UnstructuredMesh::nc.
     {
       Istr >> Mesh().nc;
     };
void SolverUtils::FEM::SolverAgent::ReadMeshFromStream (std::istream & Istr) inline
Definition at line 21 of file SolverAgent.H.
References SolverUtils::Mesh::UnstructuredMesh::con, Mesh(), and SolverUtils::Mesh::UnstructuredMesh::nc.
Referenced by COM::TestModule::InitSolver().
     {
       Istr >> Mesh().nc;
       Istr >> Mesh().con;
     };
void SolverUtils::FEM::SolverAgent::ReadSolnFromStream (std::istream & Istr, const std::string & name) inline
Definition at line 50 of file SolverAgent.H.
References SolverUtils::FEM::SolutionData::ReadFieldFromStream(), and Solution().
     {
       Solution().ReadFieldFromStream(Istr,name);
     };
void SolverUtils::FEM::SolverAgent::ReadSolnMetaFromStream (std::istream & Istr) inline
Definition at line 38 of file SolverAgent.H.
References SolverUtils::FEM::SolutionData::Meta(), SolverUtils::FEM::SolutionMetaData::ReadFromStream(), and Solution().
     {
       Solution().Meta().ReadFromStream(Istr);
     };
std::ostream& SolverUtils::FEM::SolverAgent::ReportMeshToStream (std::ostream & Ostr) inline
Definition at line 58 of file SolverAgent.H.
References SolverUtils::Mesh::UnstructuredMesh::con, SolverUtils::Mesh::GetCoordinateBounds(), mesh, SolverUtils::Mesh::UnstructuredMesh::nc, SolverUtils::Mesh::Connectivity::Nelem(), SolverUtils::Mesh::GenericElement::ShapeOK(), and SolverUtils::Mesh::NodalCoordinates::Size().
     {
       Mesh::IndexType number_of_nodes = mesh.nc.Size();
       Ostr << "Number of nodes: " << number_of_nodes << std::endl;
       std::vector<double> bounds(6,0.0);
       Mesh::GetCoordinateBounds(mesh.nc,bounds);
       Ostr << "Mesh Bounds: (" << bounds[0] << "," << bounds[1]
            << ") (" << bounds[2] << "," << bounds[3]
            << ") (" << bounds[4] << "," << bounds[5] << ")" << std::endl;
       Mesh::Connectivity::iterator ci = mesh.con.begin();
       bool bump_node_indices_plus1 = false;
       if(bump_node_indices_plus1){
         while(ci != mesh.con.end()){
           std::vector<Mesh::IndexType>::iterator ii = ci->begin();
           while(ii != ci->end())
             (*ii++)++;
           ci++;
         }
         ci = mesh.con.begin();
       }
       Mesh::IndexType ntet  = 0;
       Mesh::IndexType nhex  = 0;
       Mesh::IndexType npyr  = 0;
       Mesh::IndexType npris = 0;
       Mesh::IndexType ntri  = 0;
       Mesh::IndexType nquad = 0;
       while(ci != mesh.con.end()){
         Mesh::IndexType esize = ci->size();
         Mesh::GenericElement el(4);
         bool known_element_type = false;
         switch(esize){
         case 3:
           ntri++;
           break;
         case 4:
           if(el.ShapeOK(*ci,mesh.nc))
             ntet++;
           else
             nquad++;
           break;
         case 5:
           npyr++;
           break;
         case 6:
           npris++;
           break;
         case 8:
           nhex++;
           break;
         case 10:
           ntet++;
           break;
         case 20:
           nhex++;
           break;
         default:
           assert(known_element_type);
         }
         ci++;
       }
       Mesh::IndexType number_of_elements = mesh.con.Nelem();
       Ostr << "Number of elements: " << number_of_elements
            << std::endl;
       if(ntet > 0)
         Ostr << "Number of tetrahedra: " << ntet << std::endl;
       if(npyr > 0)
         Ostr << "Number of pyramids:   " << npyr << std::endl;
       if(npris > 0)
         Ostr << "Number of prisms:     " << npris << std::endl;
       if(nhex > 0)
         Ostr << "Number of hexahedra:  " << nhex << std::endl;
       if(ntri > 0)
         Ostr << "Number of triangles:  " << ntri << std::endl;
       if(nquad > 0)
         Ostr << "Number of quads:      " << nquad << std::endl;
       return(Ostr);
     };
const FEM::SolutionData& SolverUtils::FEM::SolverAgent::Solution () const inline
Definition at line 17 of file SolverAgent.H.
References soln.
Referenced by SolverUtils::AgentToPane(), CreateSoln(), SolverUtils::CreateSolutionFromPane(), COM::TestModule::InitSolver(), ReadSolnFromStream(), ReadSolnMetaFromStream(), SolverUtils::FEM::FDSolverAgent::ReceiveSoln(), SolverUtils::FEM::FDSolverAgent::ReceiveSolnMeta(), SolverUtils::RegisterSolver(), SolverUtils::RegisterSolverInto(), SolverUtils::FEM::FDSolverAgent::SendSoln(), SolverUtils::FEM::FDSolverAgent::SendSolnMeta(), COM::TransferSolver::Setup(), COM::TestModule::ValidateDataItemAddress(), WriteSolnMetaToStream(), WriteSolnToStream(), and SolverUtils::WriteVTKToStream().
 { return(soln); };
FEM::SolutionData& SolverUtils::FEM::SolverAgent::Solution () inline
Definition at line 18 of file SolverAgent.H.
References soln.
 { return(soln); };
void SolverUtils::FEM::SolverAgent::WriteCoordsToStream (std::ostream & Ostr) inline
Definition at line 34 of file SolverAgent.H.
References Mesh(), and SolverUtils::Mesh::UnstructuredMesh::nc.
     {
       Ostr << Mesh().nc;
     };
void SolverUtils::FEM::SolverAgent::WriteMeshToStream (std::ostream & Ostr) inline
Definition at line 26 of file SolverAgent.H.
References SolverUtils::Mesh::UnstructuredMesh::con, Mesh(), and SolverUtils::Mesh::UnstructuredMesh::nc.
     {
       Ostr << Mesh().nc << std::endl << Mesh().con;
     };
void SolverUtils::FEM::SolverAgent::WriteSolnMetaToStream (std::ostream & Ostr) inline
Definition at line 42 of file SolverAgent.H.
References SolverUtils::FEM::SolutionData::Meta(), Solution(), and SolverUtils::FEM::SolutionMetaData::WriteToStream().
     {
       Solution().Meta().WriteToStream(Ostr);
     };
void SolverUtils::FEM::SolverAgent::WriteSolnToStream (std::ostream & Ostr, const std::string & name) inline
Definition at line 54 of file SolverAgent.H.
References Solution(), and SolverUtils::FEM::SolutionData::WriteFieldToStream().
     {
       Solution().WriteFieldToStream(Ostr,name);
     };
Member Data Documentation
Mesh::UnstructuredMesh SolverUtils::FEM::SolverAgent::mesh private
Definition at line 14 of file SolverAgent.H.
Referenced by Mesh(), and ReportMeshToStream().
FEM::SolutionData SolverUtils::FEM::SolverAgent::soln private
Definition at line 15 of file SolverAgent.H.
Referenced by Solution().
The documentation for this class was generated from the following file:
SolverAgent.H