IMPACT: SolidPropagateSurface_ALE Class Reference
SolidPropagateSurface_ALE Class Reference
Detailed Description
Definition at line 272 of file basic_actions.h.
#include <basic_actions.h>
Public Member Functions
SolidPropagateSurface_ALE (SolidAgent *ag, const std::string p_rb, const std::string a_vbar, double z)
void init (double t)
void run (double t, double dt, double alpha)
Public Member Functions inherited from Action
Action (void *p=0, const char *name=NULL)
Action (int n, const char **at, int *i=NULL, void *p=0, const char *name=NULL)
Action (int n, const std::string at[], int *i=NULL, void *p=0, const char *name=NULL)
virtual ~Action ()
virtual void declare (Scheduler &)
virtual void finalize ()
virtual const char * name ()
void set_name (const char *name)
virtual void print (FILE *f)
virtual void print_toposort (FILE *f)
virtual void schedule ()
Private Attributes
SolidAgent * sagent
double zoom
int p_rb_hdl
int b_rb_hdl
int p_pmesh_hdl
int p_vm_hdl
int p_vbar_hdl
int a_vbar_hdl
int p_cnstr_hdl
int p_pos_hdl
int MAP_reduce_maxabs
int PROP_propagate
int PROPCON_find_intersections
int PROPCON_constrain_displacements
Additional Inherited Members
Protected Types inherited from Action
enum { IN =1, OUT =2, INOUT =3 }
Protected Member Functions inherited from Action
int get_dataitem_handle (int i)
int get_dataitem_handle_const (int i)
int get_dataitem_handle (const std::string str)
void set_attr (int n, const std::string at[], int *id=NULL)
void set_attr (int n, const char *at[], int *id=NULL)
void set_io (int n, const int *io)
void set_io (const char *io)
int get_io (int i)
Protected Attributes inherited from Action
const char * action_name
char ** attr
int * idx
int count
void * usr_ptr
std::vector< int > inout
Constructor & Destructor Documentation
SolidPropagateSurface_ALE::SolidPropagateSurface_ALE (SolidAgent * ag, const std::string p_rb, const std::string a_vbar, double z)
Definition at line 916 of file basic_actions.C.
References Action::IN, Action::OUT, Action::set_attr(), and Action::set_io().
                                                                    :
             Action(0, (const char**)NULL, NULL, NULL, "SolidPropagateSurface"),
             sagent(fag), zoom(z)
 {
   int io[] = {IN, OUT};
   set_io( 2, io);
   std::string.data[2];
  .data[0] = p_rb;
  .data[1] = a_vbar;
   set_attr(2,.data);
 /*
   fagent->register_new_dataitem( fagent->propBufAll, ".vm", 'n', COM_DOUBLE, 3, "m/s");
   fagent->register_new_dataitem( fagent->propBufAll, ".rb", 'e', COM_DOUBLE, 1, "m/s");
 */
 }
Member Function Documentation
void SolidPropagateSurface_ALE::init (double t) virtual
Reimplemented from Action.
Definition at line 935 of file basic_actions.C.
References a_vbar_hdl, COM_get_dataitem_handle(), COM_get_function_handle(), COM_get_window_handle(), Agent::get_communicator(), Agent::get_coupling(), Action::get_dataitem_handle(), Coupling::get_rocmancontrol_param(), load_rocmap(), load_rocon(), load_rocprop(), MAP_reduce_maxabs, p_cnstr_hdl, p_pmesh_hdl, p_pos_hdl, p_rb_hdl, p_vbar_hdl, p_vm_hdl, RocmanControl_parameters::PROP_fom, PROP_propagate, SolidAgent::propBuf, SolidAgent::propBufAll, PROPCON_constrain_displacements, PROPCON_find_intersections, sagent, and SolidAgent::withALE.
{
   if (sagent->withALE == 0) return;
   p_rb_hdl = get_dataitem_handle( 0);
   a_vbar_hdl = get_dataitem_handle( 1);
   std::string propBuf = sagent->propBufAll;
   int PROP_fom = sagent->get_coupling()->get_rocmancontrol_param()->PROP_fom;
   if (!PROP_fom) propBuf = sagent->propBuf;
   p_vbar_hdl = COM_get_dataitem_handle( propBuf+".vbar");
   p_pmesh_hdl = COM_get_dataitem_handle( propBuf+".pmesh");
   p_vm_hdl = COM_get_dataitem_handle( propBuf+".vm");
   p_cnstr_hdl  = COM_get_dataitem_handle( propBuf+".cflag");
   p_pos_hdl    = COM_get_dataitem_handle( propBuf+".positions");
   //p_cnstr_type = COM_get_dataitem_handle( propBuf+".cnstr_type");
   load_rocprop(sagent->get_coupling()->get_rocmancontrol_param(), sagent->get_communicator());
   load_rocon(sagent->get_coupling()->get_rocmancontrol_param(), sagent->get_communicator());
   PROP_propagate = COM_get_function_handle("PROP.propagate");
   if(COM_get_window_handle("PROPCON") >= 0){
     PROPCON_find_intersections = COM_get_function_handle("PROPCON.find_intersections");
     PROPCON_constrain_displacements = COM_get_function_handle("PROPCON.constrain_displacements");
   }
   else {
     PROPCON_find_intersections = -1;
     PROPCON_constrain_displacements = -1;
   }
   load_rocmap();
   MAP_reduce_maxabs = COM_get_function_handle("MAP.reduce_maxabs_on_shared_nodes");
 }
void SolidPropagateSurface_ALE::run (double t, double dt, double alpha) virtual
Reimplemented from Action.
Definition at line 967 of file basic_actions.C.
References a_vbar_hdl, COM_call_function(), RocBlas::copy_scalar, RocBlas::div_scalar, Agent::get_communicator(), Agent::get_coupling(), Coupling::initial_start(), MAP_reduce_maxabs, RocBlas::neg, p_pmesh_hdl, p_rb_hdl, p_vbar_hdl, PROP_propagate, sagent, SolidAgent::withALE, and zoom.
 {
   if (sagent->withALE == 0) return;
   int rank = 0;
   MPI_Comm mycomm = sagent->get_communicator();
   MPI_Comm_rank(mycomm,&rank);
   if(!rank)
     std::cout << "Rocman: SolidPropagateSurface_ALE::run() with t:"<< t
               <<  "dt:" << dt << " zoom:" << zoom << std::endl;
   if ( !sagent->get_coupling()->initial_start() && zoom>0)
   {
     COM_call_function( RocBlas::neg, &p_rb_hdl, &p_rb_hdl);   // Flip the sign of burn rate
     double dtz = dt*zoom;
     COM_call_function( PROP_propagate, &p_pmesh_hdl, &p_rb_hdl, &dtz, &p_vbar_hdl);
   if(!rank)
     std::cout << "Rocman: Rocprop done" << std::endl;
     COM_call_function( RocBlas::div_scalar, &p_vbar_hdl, &dt, &p_vbar_hdl);
       // Update shared nodes for the whole surface
     COM_call_function( MAP_reduce_maxabs, 1, &a_vbar_hdl);
   }
   else {
     double dtz = 0;
     COM_call_function( RocBlas::copy_scalar, &dtz, &a_vbar_hdl);
   }
 }
Member Data Documentation
int SolidPropagateSurface_ALE::a_vbar_hdl private
Definition at line 280 of file basic_actions.h.
Referenced by init(), and run().
int SolidPropagateSurface_ALE::b_rb_hdl private
Definition at line 280 of file basic_actions.h.
int SolidPropagateSurface_ALE::MAP_reduce_maxabs private
Definition at line 282 of file basic_actions.h.
Referenced by init(), and run().
int SolidPropagateSurface_ALE::p_cnstr_hdl private
Definition at line 281 of file basic_actions.h.
Referenced by init().
int SolidPropagateSurface_ALE::p_pmesh_hdl private
Definition at line 280 of file basic_actions.h.
Referenced by init(), and run().
int SolidPropagateSurface_ALE::p_pos_hdl private
Definition at line 281 of file basic_actions.h.
Referenced by init().
int SolidPropagateSurface_ALE::p_rb_hdl private
Definition at line 280 of file basic_actions.h.
Referenced by init(), and run().
int SolidPropagateSurface_ALE::p_vbar_hdl private
Definition at line 280 of file basic_actions.h.
Referenced by init(), and run().
int SolidPropagateSurface_ALE::p_vm_hdl private
Definition at line 280 of file basic_actions.h.
Referenced by init().
int SolidPropagateSurface_ALE::PROP_propagate private
Definition at line 283 of file basic_actions.h.
Referenced by init(), and run().
int SolidPropagateSurface_ALE::PROPCON_constrain_displacements private
Definition at line 284 of file basic_actions.h.
Referenced by init().
int SolidPropagateSurface_ALE::PROPCON_find_intersections private
Definition at line 284 of file basic_actions.h.
Referenced by init().
SolidAgent* SolidPropagateSurface_ALE::sagent private
Definition at line 278 of file basic_actions.h.
Referenced by init(), and run().
double SolidPropagateSurface_ALE::zoom private
Definition at line 279 of file basic_actions.h.
Referenced by run().
The documentation for this class was generated from the following files:
basic_actions.h
basic_actions.C