IMPACT: IRAD::Sys::fdostream Class Reference
IRAD::Sys::fdostream Class Reference
Detailed Description
Definition at line 63 of file FDUtils.H.
#include <FDUtils.H>
Public Member Functions
fdostream ()
fdostream (int fd)
int FD ()
int Init (int _fd)
Protected Attributes
Sys::fdoutbuf buf
Constructor & Destructor Documentation
IRAD::Sys::fdostream::fdostream () inline
Definition at line 67 of file FDUtils.H.
 : std::ostream(0) {};
IRAD::Sys::fdostream::fdostream (int fd) inline
Definition at line 68 of file FDUtils.H.
References buf.
                          : std::ostream(0), buf(fd) {
         rdbuf(&buf);
       }
Member Function Documentation
int IRAD::Sys::fdostream::FD () inline
Definition at line 71 of file FDUtils.H.
References buf, and IRAD::Sys::fdoutbuf::FD().
 { return(buf.FD()); };
int IRAD::Sys::fdostream::Init (int _fd) inline
Definition at line 72 of file FDUtils.H.
References buf, IRAD::Sys::fdoutbuf::FD(), and IRAD::Sys::fdoutbuf::Init().
Referenced by SolverUtils::FEM::FDSolverAgent::FDSolverAgent(), and SolverUtils::FEM::FDSolverAgent::Init().
 { buf.Init(_fd); rdbuf(&buf); return(buf.FD());};
Member Data Documentation
Sys::fdoutbuf IRAD::Sys::fdostream::buf protected
Definition at line 65 of file FDUtils.H.
Referenced by FD(), fdostream(), and Init().
The documentation for this class was generated from the following file:
FDUtils.H