IMPACT: DataItem Class Reference
DataItem Class Reference
A DataItem object is a data member of a window.
Detailed Description
It can be associated with a window, a pane, nodes, or elements. An dataitem can be a vector of length size_of_items() with size_of_components() components.
Definition at line 28 of file DataItem.hpp.
#include <DataItem.hpp>
Public Types
enum Copy_dir { COPY_IN, COPY_OUT }
typedef unsigned char Shorter_size
One byte unsighed int.
typedef unsigned int Size
Unsighed int.
Public Member Functions
void set_size (int nitems, int ngitems=0) throw (COM_exception)
Set the size of items and ghost items.
void * allocate (int strd, int cap, bool force) throw (COM_exception)
Allocate memory for the dataitem.
int deallocate () throw (COM_exception)
Deallocate memory if it was allocated by allocate().
void copy_array (void *buf, int strd, int nitem, int offset=0, int direction=COPY_IN) throw (COM_exception)
void append_array (const void *from, int strd, int nitem) throw (COM_exception)
Identity
const std::string & name () const
Obtain the name of the dataitem.
std::string fullname () const
Obtain the full name of the dataitem including window name suitable for printing out error messages.
int id () const
Obtain the id (or index) of the dataitem.
DataItem * parent ()
Parent dataitem used by this object.
const DataItem * parent () const
DataItem * root ()
Root of use-inheritance.
const DataItem * root () const
Physical address
const void * pointer () const
Obtain a constant pointer to the physical address.
void * pointer () throw (COM_exception)
Obtain a modifiable pointer to the physical address.
const void * get_addr (int i, int j=0) const throw (COM_exception)
Obtain the address of the jth component of the ith item, where 0<=i<size_of_items.
void * get_addr (int i, int j=0) throw (COM_exception)
Protected Types
enum {
STATUS_NOT_INITIALIZED =0, STATUS_SET =1, STATUS_SET_CONST =2, STATUS_USE =3,
STATUS_ALLOCATED =4
}
Protected Member Functions
void set_pointer (void *p, int strd, int cap, int offset, bool is_const) throw (COM_exception)
Set the physical address of the dataitem values.
void inherit (DataItem *a, bool clone, bool withghost, int depth=0) throw (COM_exception)
Inherit from parent. If depth>0, then the procedure is for the subcomponents.
Protected Attributes
Pane * _pane
Pointer to its owner pane.
DataItem * _parent
Parent dataitem being used.
std::string _name
Name of the dataitem.
int _id
Id field data.
Shorter_size _loc
Location.
int _ncomp
Number of components.
COM_Type _type
Base data type of the dataitem.
std::string _unit
Unit of the dataitem.
int _nitems
Size of total items. Default value is -1.
int _ngitems
Size of ghost items.
int _gap
Gap between the IDs of real and ghost items.
Shorter_size _status
Indicating whether it has been initialized.
void * _ptr
Physical address of the dataitem.
int _strd
Stride.
int _nbytes_strd
Number of bytes of the stride.
int _cap
Capacity.
Static Protected Attributes
Keywords
static const char * _keywords [COM_NUM_KEYWORDS]
List of keywords.
static const char _keylocs [COM_NUM_KEYWORDS]
Default locations.
static const COM_Type _keytypes [COM_NUM_KEYWORDS]
Default data types.
static const int _keysizes [COM_NUM_KEYWORDS]
Default sizes.
Private Member Functions
DataItem (const DataItem &a)
Disable copy constructor and copy operator.
DataItem & operator= (const DataItem &)
Constructors and destructors
DataItem ()
Default constructor.
DataItem (Pane *pane, const std::string &name, int id, Shorter_size loc, int type, const int ncomp, const std::string &unit)
Create an dataitem with name n in window w.
DataItem (Pane *pane, DataItem *parent, const std::string &name, int id)
Inherit an dataitem from another.
~DataItem ()
Destructors.
DataItem (Pane *pane, int i)
Constructor for keywords. The default nitems for keywords is 0.
Access methods
const Pane * pane () const
Obtain a constant pointer to the owner pane of the dataitem.
Pane * pane ()
Obtain a modifiable pointer to the owner pane of the dataitem.
const ComponentInterface * window () const
Obtain a constant pointer to the parent window of the dataitem.
ComponentInterface * window ()
Obtain a modifiable pointer to the parent window of the dataitem.
Shorter_size location () const
Obtain the location of the dataitem.
bool is_windowed () const
Checks whether the dataitem is associated with the window.
bool is_panel () const
Checks whether the dataitem is associated with a pane.
bool is_elemental () const
Checks whether the dataitem is associated with an element.
bool is_nodal () const
Checks whether the dataitem is associated with a node.
COM_Type data_type () const
Obtain the data type of each component of the dataitem.
const std::string & unit () const
Obtain the unit of the dataitem.
int size_of_components () const
Obtain the number of components in the dataitem.
int size_of_items () const
Obtain the number of items in the dataitem.
int maxsize_of_items () const
Obtain the maximum allowed number of items in the dataitem.
int size_of_ghost_items () const
Obtain the number of ghost items in the dataitem.
int maxsize_of_ghost_items () const
Obtain the maximum allowed number of items in the dataitem.
int size_of_real_items () const
Obtain the number of real items in the dataitem.
int maxsize_of_real_items () const
Obtain the maximum allowed number of real items in the dataitem.
bool empty () const
Check whether the number of items of the dataitem is zero.
int capacity () const
Obtain the capacity of the array.
int stride () const
Obtain the stride of the dataitem in base datatype.
int stride_in_bytes () const
Obtain the stride of the dataitem in bytes.
int status () const
Obtain the status of the dataitem.
bool initialized () const
Returns whether the array for the dataitem has been set or allocated.
bool size_set () const
Returns whether the size for the dataitem has been set.
bool allocated () const
Returns whether the array for the dataitem has been set or allocated.
bool is_const () const
Returns whether the array is set to be read-only.
bool is_staggered () const
Check how the dataitem values are organized.
static int get_sizeof (COM_Type type, int count=1)
static bool compatible_types (COM_Type t1, COM_Type t2)
static bool is_digit (char c)
Member Typedef Documentation
typedef unsigned char DataItem::Shorter_size
Definition at line 30 of file DataItem.hpp.
typedef unsigned int DataItem::Size
Definition at line 31 of file DataItem.hpp.
Member Enumeration Documentation
anonymous enum protected
Enumerator
STATUS_NOT_INITIALIZED
STATUS_SET
STATUS_SET_CONST
STATUS_USE
STATUS_ALLOCATED
Definition at line 293 of file DataItem.hpp.
        { STATUS_NOT_INITIALIZED=0, STATUS_SET=1, STATUS_SET_CONST=2,
          STATUS_USE=3, STATUS_ALLOCATED=4 };
enum DataItem::Copy_dir
Enumerator
COPY_IN
COPY_OUT
Definition at line 257 of file DataItem.hpp.
 { COPY_IN, COPY_OUT };
Constructor & Destructor Documentation
DataItem::DataItem () inline
Definition at line 37 of file DataItem.hpp.
Referenced by DataItem().
     : _pane(NULL), _parent(NULL), _id(-1), _loc(0), _ncomp(0), _type(0),
       _nitems(-1), _ngitems(0), _gap(0), _status(STATUS_NOT_INITIALIZED),
       _ptr(NULL), _strd(0), _nbytes_strd(0), _cap(0) {}
DataItem::DataItem (Pane * pane, int i) inline protected
Definition at line 44 of file DataItem.hpp.
     : _pane(pane), _parent(NULL), _name( _keywords[i]), _id(i),
       _loc(_keylocs[i]), _ncomp(_keysizes[i]), _type(_keytypes[i]),
       _unit( i<=COM_NC3?"m":""), _nitems(0), _ngitems(0), _gap(0),
       _status(STATUS_NOT_INITIALIZED), _ptr(NULL), _strd(0),
       _nbytes_strd(0), _cap(0) {}
DataItem::DataItem (Pane * pane, const std::string & name, int id, Shorter_size loc, int type, const int ncomp, const std::string & unit) inline
Parameters
pane pointer to its owner pane object.
name dataitem name.
id dataitem index.
loc location ('w', 'p', 'n', or 'e').
type base data type.
ncomp number of components.
unit unit of the dataitem.
Definition at line 60 of file DataItem.hpp.
     : _pane(pane), _parent(NULL), _name( name), _id(id), _loc(loc),
       _ncomp(ncomp), _type(type), _unit(unit), _nitems(-1), _ngitems(0),
       _gap(0), _status(STATUS_NOT_INITIALIZED), _ptr(0), _strd(0),
       _nbytes_strd(0), _cap(0) {}
DataItem::DataItem (Pane * pane, DataItem * parent, const std::string & name, int id)
Parameters
pane pointer to its owner pane object.
parent parent dataitem (for supporting inheritance).
name dataitem name.
id dataitem index.
Definition at line 45 of file DataItem.C.
References _cap, _loc, _name, _nbytes_strd, _ncomp, _ngitems, _nitems, _parent, _status, _strd, _type, _unit, append_frame, COM_ERR_DATAITEM_NOTEXIST, DataItem(), fullname(), name(), root(), and STATUS_NOT_INITIALIZED.
   : _pane( pane), _id(id), _gap(0), _status(0)
 {
   if ( !parent)
     throw COM_exception( COM_ERR_DATAITEM_NOTEXIST,
                          append_frame(fullname(), DataItem::DataItem));
   _name = name.size()?name:parent->name();
   _parent = NULL; _status = STATUS_NOT_INITIALIZED;
   DataItem *root = parent->root();
   _loc=root->_loc; _ncomp=root->_ncomp; _type=root->_type;
   _cap = root->_cap; _strd = root->_strd; _nbytes_strd = root->_nbytes_strd;
   _unit=root->_unit; _nitems = root->_nitems; _ngitems = root->_ngitems;
 }
DataItem::~DataItem () inline
Definition at line 78 of file DataItem.hpp.
References _cap, _id, _loc, _nbytes_strd, _ncomp, _ngitems, _nitems, _pane, _parent, _ptr, _status, _strd, _type, deallocate(), and STATUS_NOT_INITIALIZED.
               {
     if (!_parent) deallocate();
     _pane=NULL; _parent=NULL; _id=-1; _loc=0; _ncomp=0; _type=0;
     _nitems=-1, _ngitems=0; _status=STATUS_NOT_INITIALIZED; _ptr=NULL;
     _strd=0; _nbytes_strd=0; _cap=0;
   }
DataItem::DataItem (const DataItem & a) private
Member Function Documentation
void * DataItem::allocate (int strd, int cap, bool force) throw (COM_exception)
The dataitem must be a root if the dataitem is to be allocated. If from is not NULL, copy its value to the newly allocated array.
Definition at line 327 of file DataItem.C.
References _cap, _ptr, _status, _strd, append_frame, cap, CATCHBADALLOC_APPEND, CATCHEXP_APPEND, COM_ERR_INVALID_CAPACITY, COM_ERR_INVALID_STRIDE, COM_ERR_OUT_OF_MEMORY, COM_ERR_RESIZE, copy_array(), get_sizeof(), max(), min(), set_pointer(), and strd.
Referenced by Connectivity::allocate(), inherit(), Pane::reinit_dataitem(), and Connectivity::set_pointer().
 {
   int nitems=size_of_items(), ncomp=size_of_components();
   if ( strd!=1 && strd<ncomp)
     throw COM_exception( COM_ERR_INVALID_STRIDE,
                          append_frame( fullname(), DataItem::allocate));
   if ( cap<nitems)
     throw COM_exception( COM_ERR_INVALID_CAPACITY,
                          append_frame( fullname(), DataItem::allocate));
   if ( !force && (_parent || _status==STATUS_SET || _status==STATUS_SET_CONST))
     throw COM_exception( COM_ERR_RESIZE,
                          append_frame( fullname(), DataItem::allocate));
   try {
     int type = data_type();
     // Go ahead to allocate for the dataitem if it was not initialized
     // and not inherited or it is forced to overwrite previously set address.
     int nold, old_cap;
     if ( _status == STATUS_NOT_INITIALIZED || force)
     { nold = -1; old_cap = 0; }
     else {
       old_cap = _cap;
       nold = old_cap*get_sizeof(type, std::max(_strd,ncomp));
     }
     int nnew = cap*get_sizeof(type, std::max(strd,ncomp));
     // if the capacity is not big enough or the stride is changed.
     if ( nold < nnew || strd != _strd) {
       // Deallocate the old array and copy values to the new one
       char *old_ptr = (char*)_ptr;
       int  old_strd = _strd;
       if ( nnew) {
         _ptr = new char[nnew];
         std::fill_n( (char*)_ptr, nnew, 0);
         if (_ptr==NULL)
           throw COM_exception( COM_ERR_OUT_OF_MEMORY,
                                append_frame( fullname(), DataItem::allocate));
       }
       else _ptr = NULL;
       _cap = cap; _strd = strd; _nbytes_strd = get_sizeof( data_type(), strd);
       // Copy data from old array to the new.
       if ( old_cap && _ptr) {
         if ( _ncomp ==1 || _id<0) // Copy for connectivity and for scalars
           copy_array( old_ptr, old_strd, std::min(old_cap,_cap));
         else { // loop through individual components
           for ( int i=1; i<=ncomp; ++i) {
             DataItem *ai = this+i;
             char *old_ptr_i = (char*)ai->_ptr; old_strd=ai->_strd;
             old_cap = ai->_cap;
             ai->set_pointer( _ptr, _strd, _cap, i-1, false);
             ai->copy_array( old_ptr_i, old_strd, std::min(old_cap,_cap));
             // Delete the individual components
             if ( ai->_status == STATUS_ALLOCATED && old_ptr_i)
               delete [] old_ptr_i;
           }
         }
       }
       else {
         if ( _ncomp >1 && _id>=0) for ( int i=1; i<=ncomp; ++i) {
           this[i].set_pointer( _ptr, _strd, _cap, i-1, false);
         }
       }
       // Delete the old array for all components
       if ( _status == STATUS_ALLOCATED && old_ptr) delete [] old_ptr;
       _status = STATUS_ALLOCATED;
       if ( _parent) _parent=NULL; // Break inheritance.
     }
   }
   CATCHEXP_APPEND(DataItem::allocate) CATCHBADALLOC_APPEND(DataItem::allocate);
   return _ptr;
 }
bool DataItem::allocated () const inline
Definition at line 227 of file DataItem.hpp.
References _status, and STATUS_ALLOCATED.
 { return _status==STATUS_ALLOCATED; }
void DataItem::append_array (const void * from, int strd, int nitem) throw (COM_exception)
Definition at line 316 of file DataItem.C.
References append_frame, COM_ERR_APPEND_ARRAY, and strd.
Referenced by ComponentInterface::append_array().
 {
   if ( !is_panel() && !is_windowed() || size_of_ghost_items())
     throw COM_exception( COM_ERR_APPEND_ARRAY,
                          append_frame(fullname(), DataItem::append_array));
   int offset = size_of_items();
   copy_array( const_cast<void*>(from), strd, nitem, offset);
   set_size( offset+nitem);
 }
int DataItem::capacity () const inline
Definition at line 207 of file DataItem.hpp.
References _cap, _status, and root().
Referenced by Pane::init_done(), maxsize_of_items(), and Pane::reinit_dataitem().
 { return _status?_cap:root()->_cap; }
bool DataItem::compatible_types (COM_Type t1, COM_Type t2) static
Definition at line 513 of file DataItem.C.
References COM_BYTE, COM_CHAR, COM_CHARACTER, COM_DOUBLE, COM_DOUBLE_PRECISION, COM_FLOAT, COM_INT, COM_INTEGER, COM_LONG, COM_REAL, COM_SHORT, COM_UNSIGNED, COM_UNSIGNED_CHAR, COM_UNSIGNED_LONG, COM_UNSIGNED_SHORT, and get_sizeof().
Referenced by Pane::inherit().
{
   if (t1 == t2) return true;
   if ( DataItem::get_sizeof( t1, 1) != DataItem::get_sizeof( t2, 1))
     return false;
   switch( t1) {
   case COM_CHAR:
   case COM_CHARACTER:
   case COM_UNSIGNED_CHAR:
   case COM_BYTE:
   case COM_SHORT:
   case COM_UNSIGNED_SHORT:
     return true; // size matching
   case COM_INT:
   case COM_INTEGER:
   case COM_UNSIGNED:
   case COM_LONG:
   case COM_UNSIGNED_LONG:
     return t2 == COM_INT || t2 == COM_INTEGER || t2 == COM_UNSIGNED ||
       t2 == COM_UNSIGNED_LONG || t2 == COM_LONG;
   case COM_FLOAT:
   case COM_REAL:
     return t2 == COM_FLOAT || t2 == COM_REAL;
   case COM_DOUBLE:
   case COM_DOUBLE_PRECISION:
     return t2 == COM_DOUBLE_PRECISION || t2 == COM_DOUBLE;
   default:
     return false;
   }
 }
void DataItem::copy_array (void * buf, int strd, int nitem, int offset = 0, int direction = COPY_IN) throw (COM_exception)
Definition at line 231 of file DataItem.C.
References append_frame, COM_ERR_DATAITEM_CONST, COM_ERR_INVALID_SIZE, COM_ERR_INVALID_STRIDE, COM_ERR_NULL_POINTER, get_sizeof(), min(), and strd.
Referenced by allocate(), and Pane::inherit().
 {
   if (direction==COPY_IN) {
     if ( is_const())
       throw COM_exception( COM_ERR_DATAITEM_CONST,
                            append_frame( fullname(), DataItem::copy_array));
     if ( _status==STATUS_NOT_INITIALIZED && _parent)
     { _cap = root()->_cap; _strd = root()->_strd; _nbytes_strd=root()->_nbytes_strd; }
   }
   int nitems=size_of_items(), ncomp=size_of_components();
   if ( n ==0) { if ( direction==COPY_IN) return; else n = nitems; }
   if ( strd==0) strd=ncomp;
   if ( !buf && n)
     throw COM_exception( COM_ERR_NULL_POINTER,
                          append_frame( fullname(), DataItem::copy_array));
   // strd must be either 1 or at least as large as _strd
   if ( strd!=1 && strd<ncomp)
     throw COM_exception( COM_ERR_INVALID_STRIDE,
                          append_frame( fullname(), DataItem::copy_array));
   if ( offset<0 || n+offset>_cap)
     throw COM_exception( COM_ERR_INVALID_SIZE,
                          append_frame( fullname(), DataItem::copy_array));
   int basesize = get_sizeof( data_type());
   char *ptr0 = (char*)pointer();
   if (offset) ptr0 += offset*ncomp*basesize;
   if ( _strd == strd && (_strd == ncomp || n==_cap && strd==1) ) {
     // two arrays have the same layout
     if ( direction == COPY_IN)
       std::memcpy( ptr0, buf, n*ncomp*basesize);
     else
       std::memcpy( buf, ptr0, n*ncomp*basesize);
   }
   else if ( _strd>1 && strd>1) {
     // the components are stored contiguously in both arrays
     char *p_buf=(char*)buf;
     char *p_att = ptr0;
     int strd_att_in_bytes = _nbytes_strd;
     int strd_buf_in_bytes =  strd*basesize;
     int vecsize = ncomp*basesize;
     for ( int i=0, ni=std::min(n, nitems); i<ni; ++i) {
       if ( direction == COPY_IN)
         std::memcpy( p_att, p_buf, vecsize);
       else
         std::memcpy( p_buf, p_att, vecsize);
       p_buf += strd_buf_in_bytes;
       p_att += strd_att_in_bytes;
     }
   }
   else {
     // layouts of two arrays are very different from each
     char *p_buf=(char*)buf;
     char *p_att = ptr0;
     int strd_att_in_bytes = _nbytes_strd;
     int strd_buf_in_bytes =  strd*basesize;
     int step_att_in_bytes= (_strd==1?_cap:1)*basesize;
     int step_buf_in_bytes = (strd==1?n:1)*basesize;
     for ( int i=0, ni=std::min(n, nitems); i<ni; ++i) {
       for ( int j=0, offset_buf=0, offset_att=0; j<ncomp; ++j) {
         if ( direction == COPY_IN)
           std::memcpy( p_att+offset_att, p_buf+offset_buf, basesize);
         else
           std::memcpy( p_buf+offset_buf, p_att+offset_att, basesize);
         offset_buf += step_buf_in_bytes;
         offset_att += step_att_in_bytes;
       }
       p_buf += strd_buf_in_bytes;
       p_att += strd_att_in_bytes;
     }
   }
 }
COM_Type DataItem::data_type () const inline
Definition at line 174 of file DataItem.hpp.
References _type.
Referenced by Rocblas::acos(), Rocblas::add(), Rocblas::add_scalar(), Rocblas::axpy(), Rocblas::axpy_gen(), Rocblas::axpy_scalar(), Rocblas::calc(), Rocblas::calcDot(), COM::COM_base::call_function(), Rocblas::copy(), Rocblas::copy_scalar(), Rocblas::div(), Rocblas::div_scalar(), Rocblas::dot_MPI(), Rocblas::dot_scalar_MPI(), Rocblas::gen2arg(), ComponentInterface::get_dataitem(), COM::COM_base::get_f90pointer(), Pane::inherit(), Rocblas::limit1(), Rocblas::maxof_scalar(), Rocblas::mul(), Rocblas::mul_scalar(), Rocblas::neg(), Rocblas::rand(), Rocblas::rand_scalar(), Rocblas::reduce_MPI(), Rocblas::reduce_scalar_MPI(), Element_node_vectors_k_const< Value >::set(), Element_vectors_k_const< Value >::set(), COM::COM_base::set_f90pointer(), COM::COM_base::set_member_function_helper(), Rocblas::sqrt(), Rocblas::sub(), Rocblas::sub_scalar(), Rocblas::swap(), and write_attr_CGNS().
 { return _type; }
int DataItem::deallocate () throw (COM_exception)
Return 0 if deallocation is successful.
Definition at line 455 of file DataItem.C.
References _id, _ncomp, _ptr, _status, CATCHEXP_APPEND, STATUS_ALLOCATED, and STATUS_NOT_INITIALIZED.
Referenced by Pane::reinit_dataitem(), and ~DataItem().
{
   try {
     // Deallocate dataitem and set individual components to not initialized.
     if ( _status != STATUS_ALLOCATED) return -1; // failed
     _status = STATUS_NOT_INITIALIZED;
     if ( _ptr) { delete [] (char*)_ptr; _ptr = NULL; }
     if ( _ncomp>1 && _id>=0)
       for ( int i=1; i<=_ncomp; ++i)
         { this[i]._ptr = NULL; this[i]._status = STATUS_NOT_INITIALIZED; }
   }
   CATCHEXP_APPEND(DataItem::deallocate);
   return 0;
 }
bool DataItem::empty () const inline
Definition at line 204 of file DataItem.hpp.
References _nitems, and root().
Referenced by COM::COM_base::clone_dataitem(), and COM::COM_base::use_dataitem().
 { return root()->_nitems<= 0; }
std::string DataItem::fullname () const
Definition at line 64 of file DataItem.C.
References ComponentInterface::name(), name(), and window().
Referenced by Rocblas::acos(), Rocblas::add(), Rocblas::axpy(), Rocblas::axpy_gen(), Rocblas::calc(), Rocblas::calcDot(), Rocblas::copy(), DataItem(), Rocblas::div(), Rocblas::dot_MPI(), Rocblas::gen2arg(), Pane::inherit(), Pane::init_done(), Rocblas::limit1(), Rocblas::mul(), Rocblas::neg(), Rocblas::rand(), Rocblas::reduce_MPI(), Rocblas::reduce_scalar_MPI(), Pane::reinit_dataitem(), Rocblas::sqrt(), and Rocblas::sub().
 { return window()->name()+"."+name(); }
const void * DataItem::get_addr (int i, int j = 0) const throw (COM_exception)
This function is recursive and relatively expensive, and hence should be used only for performance-insenstive tasks.
Definition at line 67 of file DataItem.C.
References append_frame, COM_ERR_INDEX_OUT_OF_BOUNDS, and COM_ERR_INVALID_DIMENSION.
Referenced by Connectivity::get_addr().
{
   if ( _parent) return root()->get_addr( i,j);
   if ( j>=_ncomp) throw COM_exception( COM_ERR_INVALID_DIMENSION);
   if ( _ncomp>1) return this[j+1].get_addr( i);
   // Check that i is between 0 and size_of_items-1.
   if ( i<0 || i>=size_of_items())
     throw COM_exception( COM_ERR_INDEX_OUT_OF_BOUNDS, append_frame
                          ( fullname(), DataItem::get_addr));
   return  ((char*)_ptr)+i*_nbytes_strd;
 }
void* DataItem::get_addr (int i, int j = 0) throw (COM_exception) inline
Definition at line 139 of file DataItem.hpp.
References COM_ERR_DATAITEM_CONST, and is_const().
{
     if ( is_const()) throw COM_exception( COM_ERR_DATAITEM_CONST);
     return (void*)(((const DataItem*)this)->get_addr(i,j));
   }
int DataItem::get_sizeof (COM_Type type, int count = 1) static
Definition at line 470 of file DataItem.C.
References COM_assertion, COM_BOOL, COM_BYTE, COM_CHAR, COM_CHARACTER, COM_COMPLEX, COM_DOUBLE, COM_DOUBLE_COMPLEX, COM_DOUBLE_PRECISION, COM_F90POINTER, COM_FLOAT, COM_INT, COM_INTEGER, COM_LOGICAL, COM_LONG, COM_LONG_DOUBLE, COM_METADATA, COM_MPI_COMMC, COM_MPI_COMMF, COM_OBJECT, COM_REAL, COM_SHORT, COM_STRING, COM_UNSIGNED, COM_UNSIGNED_CHAR, COM_UNSIGNED_LONG, COM_UNSIGNED_SHORT, and COM_VOID.
Referenced by compatible_types(), COM::COM_base::get_f90pntoffsets(), and COM::COM_base::get_sizeof().
{
   switch (type) {
   case COM_CHAR:
   case COM_UNSIGNED_CHAR:
   case COM_BYTE:
   case COM_BOOL:
   case COM_CHARACTER:      return count;
   case COM_UNSIGNED_SHORT:
   case COM_SHORT:          return count*sizeof(short);
   case COM_INT:
   case COM_INTEGER:
   case COM_LOGICAL:
   case COM_UNSIGNED:       return count*sizeof(int);
   case COM_UNSIGNED_LONG:
   case COM_LONG:           return count*sizeof(long int);
   case COM_FLOAT:
   case COM_REAL:           return count*sizeof(float);
   case COM_DOUBLE_PRECISION:
   case COM_DOUBLE:         return count*sizeof(double);
   case COM_LONG_DOUBLE:    return count*sizeof(long double);
   case COM_COMPLEX:        return count*2*sizeof(float);
   case COM_DOUBLE_COMPLEX: return count*2*sizeof(double);
   case COM_MPI_COMMC:      return count*sizeof(MPI_Comm);
   case COM_MPI_COMMF:      return count*sizeof(int);
   case COM_F90POINTER:     return count*64;
   case COM_METADATA:
   case COM_VOID:           return sizeof(void*)*count;
   case COM_OBJECT:         return sizeof(COM_Object*)*count;
   case COM_STRING:         return count;
   default:  COM_assertion(false); return -1;
   }
 }
int DataItem::id () const inline
Definition at line 97 of file DataItem.hpp.
References _id.
Referenced by Rocblas::axpy_gen(), Rocblas::calc(), Rocblas::calcDot(), Rocblas::copy(), Pane::dataitem(), ComponentInterface::dataitem(), ComponentInterface::delete_dataitem(), Rocblas::gen2arg(), Pane_ghost_connectivity::get_ents_to_send(), Pane_ghost_connectivity::get_node_total_order(), Pane::inherit(), Rocblas::rand(), ComponentInterface::set_size(), Rocblas::swap(), and write_attr_CGNS().
 { return _id; }
void DataItem::inherit (DataItem * a, bool clone, bool withghost, int depth = 0) throw (COM_exception) protected
Definition at line 408 of file DataItem.C.
References _cap, _loc, _ncomp, _strd, _type, _unit, allocate(), CATCHBADALLOC_APPEND, CATCHEXP_APPEND, get_sizeof(), and root().
Referenced by Connectivity::inherit(), ComponentInterface::inherit(), Pane::inherit(), and RFC_Pane_base::read_rocin().
 {
   DataItem *root = parent->root();
   _loc=root->_loc; _ncomp=root->_ncomp; _type=root->_type;
   _cap = root->_cap; _strd = root->_strd;
   _nbytes_strd = get_sizeof( _type, _strd); _unit=root->_unit;
   if ( !clone) {
     _parent = parent;
     // Inherit individual components
     if ( _ncomp>1 && _id>=0) try {
       for ( int i=1; i<=_ncomp; ++i) {
         this[i].inherit( parent+i, clone, withghost, 1);
       }
     } CATCHEXP_APPEND(DataItem::inherit);
   }
   else {
     _parent = NULL;
     // Set size
     if ( withghost) {
       _nitems = parent->size_of_items();
       _ngitems = parent->size_of_ghost_items();
     }
     else {
       _nitems = parent->size_of_real_items();
       _ngitems = 0;
     }
     if ( depth>0) return;
     // Allocate and copy from parent if parent was initialized.
     try {
       if (parent->initialized()) allocate( _ncomp, _cap, true);
       else deallocate();
     }  CATCHEXP_APPEND(DataItem::inherit) CATCHBADALLOC_APPEND(DataItem::allocate);
     // Set pointer for individual components if allocated.
     if ( _ncomp>1 && _id>=0) try {
       for ( int i=1; i<=_ncomp; ++i) {
         this[i].inherit( parent+i, clone, withghost, 1);
         if (allocated())
           this[i].set_pointer( _ptr, _strd, _cap, i-1, false);
       }
     } CATCHEXP_APPEND(DataItem::inherit);
   }
 }
bool DataItem::initialized () const inline
Definition at line 221 of file DataItem.hpp.
References _status, and root().
Referenced by Pane::init_done().
 { return _status||root()->_status; }
bool DataItem::is_const () const inline
Definition at line 230 of file DataItem.hpp.
References _status, root(), and STATUS_SET_CONST.
Referenced by COM::COM_base::call_function(), get_addr(), Connectivity::is_const(), and pointer().
 { return root()->_status==STATUS_SET_CONST; }
static bool DataItem::is_digit (char c) inline static
Definition at line 241 of file DataItem.hpp.
Referenced by ComponentInterface::ComponentInterface(), ComponentInterface::dataitem(), ComponentInterface::delete_dataitem(), ComponentInterface::new_dataitem(), and Pane::reinit_dataitem().
 { return c>='0' && c<='9'; }
bool DataItem::is_elemental () const inline
Definition at line 169 of file DataItem.hpp.
References _loc.
Referenced by Element_vectors_k_const< Value >::set().
 { return _loc == 'e'; }
bool DataItem::is_nodal () const inline
Definition at line 171 of file DataItem.hpp.
References _loc.
Referenced by Element_node_vectors_k_const< Value >::set().
 { return _loc == 'n'; }
bool DataItem::is_panel () const inline
Definition at line 167 of file DataItem.hpp.
References _loc.
 { return _loc == 'p'; }
bool DataItem::is_staggered () const inline
It returns true if the components of the dataitem associated with
Definition at line 235 of file DataItem.hpp.
References size_of_components(), and stride().
 { return stride()!=size_of_components(); }
bool DataItem::is_windowed () const inline
Definition at line 165 of file DataItem.hpp.
References _loc.
Referenced by Rocblas::acos(), Rocblas::axpy(), Rocblas::axpy_gen(), Rocblas::calc(), Rocblas::calcChoose(), Rocblas::calcDot(), Rocblas::copy_helper(), Rocblas::dot_MPI(), Rocblas::gen2arg(), Pane::inherit(), Rocblas::neg(), Pane::Pane(), Rocblas::rand(), Rocblas::reduce_MPI(), Pane::reinit_dataitem(), ComponentInterface::set_size(), and Rocblas::sqrt().
 { return _loc == 'w'; }
Shorter_size DataItem::location () const inline
It is encoded as follows: 'w' for windowed dataitem, 'p' for panal dataitem, 'n' for nodal dataitem, and 'e' for elemental dataitem.
Definition at line 163 of file DataItem.hpp.
References _loc.
Referenced by ComponentInterface::get_dataitem(), COM::COM_base::get_f90pointer(), Pane::inherit(), COM::COM_base::set_f90pointer(), and write_attr_CGNS().
 { return _loc; }
int DataItem::maxsize_of_ghost_items () const
Reserved for Roccom3.1
Definition at line 135 of file DataItem.C.
References _cap, _id, _loc, _ngitems, _nitems, _pane, _parent, COM_CONN, COM_NC, Pane::dataitem(), Pane::ignore_ghost(), and maxsize_of_ghost_items().
Referenced by maxsize_of_ghost_items().
 {
   if ( _pane->ignore_ghost())
     return 0;
   else if ( _loc == 'n' && _id != COM_NC)
     return _pane->dataitem(COM_NC)->maxsize_of_ghost_items();
   else if ( _loc == 'e' && _id != COM_CONN)
     return _pane->dataitem(COM_CONN)->maxsize_of_ghost_items();
   else if ( _parent)
     return _parent->maxsize_of_ghost_items();
   else
     return _nitems<=0 ? 0 :_ngitems + (_cap-_nitems);
 }
int DataItem::maxsize_of_items () const
Reserved for Roccom3.1
Definition at line 107 of file DataItem.C.
References _id, _loc, _pane, _parent, capacity(), COM_CONN, COM_NC, Pane::dataitem(), Pane::ignore_ghost(), maxsize_of_items(), and maxsize_of_real_items().
Referenced by maxsize_of_items().
 {
   if (_pane->ignore_ghost())
     return maxsize_of_real_items();
   if ( _loc == 'n' && _id != COM_NC)
     return _pane->dataitem(COM_NC)->maxsize_of_items();
   else if ( _loc == 'e' && _id != COM_CONN)
     return _pane->dataitem(COM_CONN)->maxsize_of_items();
   else if ( _parent)
     return _parent->maxsize_of_items();
   else
     return  capacity();
 }
int DataItem::maxsize_of_real_items () const
Reserved for Roccom3.1
Definition at line 161 of file DataItem.C.
References _id, _loc, _ngitems, _nitems, _pane, _parent, COM_CONN, COM_NC, Pane::dataitem(), and maxsize_of_real_items().
Referenced by maxsize_of_items(), and maxsize_of_real_items().
 {
   if ( _loc == 'n' && _id != COM_NC)
     return _pane->dataitem(COM_NC)->maxsize_of_real_items();
   else if ( _loc == 'e' && _id != COM_CONN)
     return _pane->dataitem(COM_CONN)->maxsize_of_real_items();
   else if ( _parent)
     return _parent->maxsize_of_real_items();
   else
     return _nitems<=0 ? 0 : _nitems - _ngitems;
 }
const std::string& DataItem::name () const inline
Definition at line 90 of file DataItem.hpp.
Referenced by COM::COM_base::call_function(), ComponentInterface::ComponentInterface(), DataItem(), ComponentInterface::delete_dataitem(), fullname(), io_pane_dataitem(), Pane::new_dataitem(), and Pane::reinit_dataitem().
 { return _name; }
DataItem& DataItem::operator= (const DataItem &) private
const Pane* DataItem::pane () const inline
Definition at line 149 of file DataItem.hpp.
Referenced by Pane::dataitems(), Pane::delete_dataitem(), Rocblas::gen2arg(), Pane::inherit(), Pane::init_done(), Pane::Pane(), Pane::reinit_dataitem(), Element_node_vectors_k_const< Value >::set(), and Element_vectors_k_const< Value >::set().
 { return _pane; }
Pane* DataItem::pane () inline
Definition at line 151 of file DataItem.hpp.
References _pane.
 { return _pane; }
DataItem* DataItem::parent () inline
It determines the the meta-data of the dataitem. If the array of this dataitem is not set, then this dataitem also uses the pointer of its parant.
Definition at line 102 of file DataItem.hpp.
References _parent.
 { return _parent;  }
const DataItem* DataItem::parent () const inline
Definition at line 103 of file DataItem.hpp.
References _parent.
 { return _parent; }
const void* DataItem::pointer () const inline
Definition at line 127 of file DataItem.hpp.
Referenced by Rocblas::axpy_gen(), Rocblas::calc(), Rocblas::calcDot(), COM::COM_base::call_function(), Rocblas::gen2arg(), Pane_ghost_connectivity::get_cpanes(), Pane_ghost_connectivity::get_ents_to_send(), COM::COM_base::get_f90pointer(), Pane_ghost_connectivity::get_node_total_order(), ComponentInterface::inherit(), Pane::inherit(), io_pane_dataitem(), Connectivity::pointer(), Rocblas::reduce_MPI(), Element_node_vectors_k_const< Value >::set(), Element_vectors_k_const< Value >::set(), COM::COM_base::set_f90pointer(), Pane_connectivity::size_of_cpanes(), and write_attr_CGNS().
 { return _status?_ptr:root()->_ptr; }
void* DataItem::pointer () throw (COM_exception) inline
Definition at line 129 of file DataItem.hpp.
References _ptr, _status, COM_ERR_DATAITEM_CONST, is_const(), and root().
{
     if ( is_const()) throw COM_exception( COM_ERR_DATAITEM_CONST);
     return _status?_ptr:root()->_ptr;
   }
DataItem* DataItem::root () inline
The basic properties of the dataitem (location, data type, number of components, and unit) are copied from the root during inheritance and hence later changes in the root (by renewing the root) will not be reflected in sub-dataitem. Other types of information (sizes, pointer, stride, and capacity) always use those of the root dataitem.
Definition at line 111 of file DataItem.hpp.
References _parent.
Referenced by capacity(), DataItem(), empty(), inherit(), initialized(), is_const(), pointer(), Connectivity::root(), stride(), and stride_in_bytes().
                     {
     DataItem *a=this;
     while ( a->_parent) a=a->_parent;
     return a;
   }
const DataItem* DataItem::root () const inline
Definition at line 116 of file DataItem.hpp.
References _parent.
{
     const DataItem *a=this;
     while ( a->_parent) a=a->_parent;
     return a;
   }
void DataItem::set_pointer (void * p, int strd, int cap, int offset, bool is_const) throw (COM_exception) protected
Definition at line 190 of file DataItem.C.
References append_frame, cap, COM_ERR_INVALID_CAPACITY, COM_ERR_INVALID_STRIDE, get_sizeof(), and strd.
Referenced by allocate(), and Connectivity::set_pointer().
 {
   int nitems=size_of_items(), ncomp=size_of_components();
   // Check whether received a local variable
   // const long int stackSize = 2097152; // 2MB
   // long int dist = std::abs(((long int)p) - (long int)(&nitems));
   // if ( p && dist <= stackSize)
   //   throw COM_exception( COM_ERR_INVALID_ADDR,
   //                     append_frame( fullname(), DataItem::set_pointer));
   if ( p && strd!=1 && strd<ncomp)
     throw COM_exception( COM_ERR_INVALID_STRIDE,
                          append_frame( fullname(), DataItem::set_pointer));
   if ( p && cap<nitems)
     throw COM_exception( COM_ERR_INVALID_CAPACITY,
                          append_frame( fullname(), DataItem::set_pointer));
   _cap = cap;
   _strd = strd;
   int basesize = get_sizeof( data_type(), 1);
   _nbytes_strd = basesize*strd;
   if ( _status == STATUS_ALLOCATED) deallocate();
   if ( p && offset) {
     if ( strd==1)
       _ptr = ((char*)p) + (offset*cap)*_nbytes_strd;
     else // Staggerred
       _ptr = ((char*)p) + offset*basesize;
   }
   else
     _ptr = p;
   _status = is_const?STATUS_SET_CONST:STATUS_SET;
   if ( ncomp >1 && _id>=0) for ( int i=1; i<=ncomp; ++i) {
     this[i].set_pointer( _ptr, _strd, _cap, i-1, is_const);
   }
 }
void DataItem::set_size (int nitems, int ngitems = 0) throw (COM_exception)
Can be changed only if the dataitem is a root.
Definition at line 173 of file DataItem.C.
References append_frame, COM_assertion, COM_CONN, COM_ERR_CHANGE_INHERITED, and COM_NC.
Referenced by ComponentInterface::append_array(), Pane::reinit_dataitem(), and Connectivity::set_pointer().
 {
   if ( _parent)
     throw COM_exception( COM_ERR_CHANGE_INHERITED,
                          append_frame( fullname(), DataItem::set_size));
   COM_assertion( (_loc!='n'||_id==COM_NC) && (_loc!='e'||_id==COM_CONN));
   _nitems = nitems; _ngitems = ngitems;
   if ( _ncomp>1) {
     // Set sizes for each individial component
     for ( int i=1; i<=_ncomp; ++i) {
       this[i]._nitems = nitems; this[i]._ngitems = ngitems;
     }
   }
 }
int DataItem::size_of_components () const inline
Definition at line 180 of file DataItem.hpp.
References _ncomp.
Referenced by Rocblas::acos(), Rocblas::axpy(), Rocblas::axpy_gen(), Rocblas::calc(), Rocblas::calcChoose(), Rocblas::calcDot(), Rocblas::copy_helper(), ComponentInterface::dataitem(), Pane::dataitems(), ComponentInterface::delete_dataitem(), Pane::delete_dataitem(), Rocblas::dot_MPI(), Rocblas::gen2arg(), ComponentInterface::get_dataitem(), COM::COM_base::get_f90pntoffsets(), Pane::inherit(), is_staggered(), Rocblas::neg(), Element_node_vectors_k_const< Value >::operator()(), Element_vectors_k_const< Value >::operator()(), Pane::Pane(), Rocblas::rand(), Rocblas::reduce_MPI(), Pane::reinit_dataitem(), Element_node_vectors_k_const< Value >::set(), Element_vectors_k_const< Value >::set(), COM::COM_base::set_f90pointer(), Rocblas::sqrt(), and write_attr_CGNS().
 { return _ncomp; }
int DataItem::size_of_ghost_items () const
Definition at line 121 of file DataItem.C.
References _id, _loc, _ngitems, _pane, _parent, COM_CONN, COM_NC, Pane::dataitem(), Pane::ignore_ghost(), and size_of_ghost_items().
Referenced by Connectivity::size_of_ghost_elements(), size_of_ghost_items(), and write_attr_CGNS().
 {
   if ( _pane->ignore_ghost())
     return 0;
   else if ( _loc == 'n' && _id != COM_NC)
     return _pane->dataitem(COM_NC)->size_of_ghost_items();
   else if ( _loc == 'e' && _id != COM_CONN)
     return _pane->dataitem(COM_CONN)->size_of_ghost_items();
   else if ( _parent)
     return _parent->size_of_ghost_items();
   else
     return _ngitems;
 }
int DataItem::size_of_items () const
Definition at line 93 of file DataItem.C.
References _id, _loc, _nitems, _pane, _parent, COM_CONN, COM_NC, Pane::dataitem(), Pane::ignore_ghost(), size_of_items(), and size_of_real_items().
Referenced by ComponentInterface::append_array(), Rocblas::axpy_gen(), Rocblas::calc(), Rocblas::calcDot(), Rocblas::gen2arg(), Rocblas::get_stride(), Pane::inherit(), Pane::init_done(), Pane::reinit_dataitem(), Connectivity::size_of_elements(), size_of_items(), and write_attr_CGNS().
 {
   if ( _pane->ignore_ghost())
     return size_of_real_items();
   else if ( _loc == 'n' && _id != COM_NC)
     return _pane->dataitem(COM_NC)->size_of_items();
   else if ( _loc == 'e' && _id != COM_CONN)
     return _pane->dataitem(COM_CONN)->size_of_items();
   else if ( _parent)
     return _parent->size_of_items();
   else
     return _nitems<=0 ? 0 : _nitems;
 }
int DataItem::size_of_real_items () const
Definition at line 149 of file DataItem.C.
References _gap, _id, _loc, _ngitems, _nitems, _pane, _parent, COM_CONN, COM_NC, Pane::dataitem(), and size_of_real_items().
Referenced by Pane_ghost_connectivity::finalize_pconn(), Pane_ghost_connectivity::get_cpanes(), Pane_ghost_connectivity::get_ents_to_send(), Pane::inherit(), size_of_items(), Connectivity::size_of_real_elements(), size_of_real_items(), and write_attr_CGNS().
 {
   if ( _loc == 'n' && _id != COM_NC)
     return _pane->dataitem(COM_NC)->size_of_real_items();
   else if ( _loc == 'e' && _id != COM_CONN)
     return _pane->dataitem(COM_CONN)->size_of_real_items();
   else if ( _parent)
     return _parent->size_of_real_items();
   else
     return _nitems<=0 ? 0:_nitems - _ngitems - _gap;
 }
bool DataItem::size_set () const
Definition at line 81 of file DataItem.C.
References _id, _loc, _nitems, _pane, _parent, COM_CONN, COM_NC, Pane::dataitem(), and size_set().
Referenced by ComponentInterface::append_array(), Pane::reinit_dataitem(), and size_set().
 {
   if ( _loc == 'n' && _id != COM_NC)
     return _pane->dataitem(COM_NC)->size_set();
   else if ( _loc == 'e' && _id != COM_CONN)
     return _pane->dataitem(COM_CONN)->size_set();
   else if ( _parent)
     return _parent->size_set();
   else
     return _nitems>=0;
 }
int DataItem::status () const inline
Definition at line 217 of file DataItem.hpp.
References _parent, _status, and STATUS_USE.
Referenced by ComponentInterface::get_status().
   { if ( _parent) return STATUS_USE; else return _status; }
int DataItem::stride () const inline
Definition at line 210 of file DataItem.hpp.
References _status, _strd, and root().
Referenced by ComponentInterface::append_array(), Rocblas::calcDot(), Rocblas::get_stride(), Pane::inherit(), io_pane_dataitem(), is_staggered(), Pane::reinit_dataitem(), Element_node_vectors_k_const< Value >::set(), Element_vectors_k_const< Value >::set(), and write_attr_CGNS().
 { return _status?_strd:root()->_strd; }
int DataItem::stride_in_bytes () const inline
Definition at line 213 of file DataItem.hpp.
References _nbytes_strd, _status, and root().
   { return _status?_nbytes_strd:root()->_nbytes_strd; }
const std::string& DataItem::unit () const inline
Definition at line 177 of file DataItem.hpp.
References _unit.
Referenced by ComponentInterface::get_dataitem(), and write_attr_CGNS().
 { return _unit; }
const Window * DataItem::window () const
Definition at line 62 of file DataItem.C.
References _pane, and Pane::window().
Referenced by Rocblas::axpy_gen(), Rocblas::calc(), Rocblas::calcDot(), COM::COM_base::call_function(), Rocblas::copy(), fullname(), Rocblas::gen2arg(), ComponentInterface::inherit(), Rocblas::rand(), Rocblas::swap(), and Rocout::write_dataitem_internal().
 { return _pane->window(); }
Window * DataItem::window ()
Definition at line 61 of file DataItem.C.
References _pane, and Pane::window().
 { return _pane->window(); }
Member Data Documentation
int DataItem::_cap protected
Definition at line 300 of file DataItem.hpp.
Referenced by allocate(), capacity(), DataItem(), inherit(), maxsize_of_ghost_items(), and ~DataItem().
int DataItem::_gap protected
Definition at line 291 of file DataItem.hpp.
Referenced by size_of_real_items().
int DataItem::_id protected
Definition at line 279 of file DataItem.hpp.
Referenced by deallocate(), id(), maxsize_of_ghost_items(), maxsize_of_items(), maxsize_of_real_items(), size_of_ghost_items(), size_of_items(), size_of_real_items(), size_set(), and ~DataItem().
const char DataItem::_keylocs static protected
Initial value:
=
  { 'n', 'n', 'n', 'n', 'e', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'p'}
The locations of keywords.
Definition at line 303 of file DataItem.hpp.
const COM_Type DataItem::_keysizes static protected
Initial value:
=
  { 3, 1, 1, 1, 0, 0, 1, 2, 1, 1, 0, 0, 0 }
The sizes of keywords.
Definition at line 305 of file DataItem.hpp.
const COM_Type DataItem::_keytypes static protected
Initial value:
=
  { COM_DOUBLE, COM_DOUBLE, COM_DOUBLE, COM_DOUBLE, COM_METADATA,
    COM_METADATA, COM_INT, COM_INT, COM_INT, COM_INT, COM_METADATA,
    COM_METADATA, COM_METADATA }
The datatypes of keywords.
Definition at line 304 of file DataItem.hpp.
const char * DataItem::_keywords static protected
Initial value:
=
  { "nc", "1-nc", "2-nc", "3-nc", "conn", "mesh",
    "pconn", "ridges", "1-ridges", "2-ridges", "pmesh", "data", "all" }
The names of the keywords.
Definition at line 302 of file DataItem.hpp.
Shorter_size DataItem::_loc protected
'w' for windowed dataitem, 'p' for panal dataitem, 'n' for nodal dataitem, 'e' for elemental dataitem
Definition at line 280 of file DataItem.hpp.
Referenced by DataItem(), inherit(), is_elemental(), is_nodal(), is_panel(), is_windowed(), location(), maxsize_of_ghost_items(), maxsize_of_items(), maxsize_of_real_items(), size_of_ghost_items(), size_of_items(), size_of_real_items(), size_set(), and ~DataItem().
std::string DataItem::_name protected
Definition at line 278 of file DataItem.hpp.
Referenced by DataItem().
int DataItem::_nbytes_strd protected
Definition at line 299 of file DataItem.hpp.
Referenced by DataItem(), stride_in_bytes(), and ~DataItem().
int DataItem::_ncomp protected
Definition at line 285 of file DataItem.hpp.
Referenced by DataItem(), deallocate(), inherit(), size_of_components(), and ~DataItem().
int DataItem::_ngitems protected
Definition at line 290 of file DataItem.hpp.
Referenced by DataItem(), maxsize_of_ghost_items(), maxsize_of_real_items(), Connectivity::size_of_elements(), Connectivity::size_of_ghost_elements(), size_of_ghost_items(), Connectivity::size_of_ghost_nodes(), Connectivity::size_of_nodes(), Connectivity::size_of_real_elements(), size_of_real_items(), Connectivity::size_of_real_nodes(), and ~DataItem().
int DataItem::_nitems protected
Definition at line 289 of file DataItem.hpp.
Referenced by DataItem(), empty(), maxsize_of_ghost_items(), maxsize_of_real_items(), size_of_items(), size_of_real_items(), size_set(), and ~DataItem().
Pane* DataItem::_pane protected
Definition at line 275 of file DataItem.hpp.
Referenced by maxsize_of_ghost_items(), maxsize_of_items(), maxsize_of_real_items(), pane(), Connectivity::size_of_elements(), size_of_ghost_items(), Connectivity::size_of_ghost_nodes(), size_of_items(), Connectivity::size_of_nodes(), size_of_real_items(), Connectivity::size_of_real_nodes(), size_set(), window(), and ~DataItem().
DataItem* DataItem::_parent protected
Definition at line 276 of file DataItem.hpp.
Referenced by DataItem(), maxsize_of_ghost_items(), maxsize_of_items(), maxsize_of_real_items(), Connectivity::parent(), parent(), root(), size_of_ghost_items(), size_of_items(), size_of_real_items(), size_set(), status(), and ~DataItem().
void* DataItem::_ptr protected
Definition at line 297 of file DataItem.hpp.
Referenced by allocate(), deallocate(), pointer(), and ~DataItem().
Shorter_size DataItem::_status protected
Definition at line 295 of file DataItem.hpp.
Referenced by allocate(), allocated(), capacity(), DataItem(), deallocate(), initialized(), is_const(), pointer(), status(), stride(), stride_in_bytes(), and ~DataItem().
int DataItem::_strd protected
Definition at line 298 of file DataItem.hpp.
Referenced by allocate(), DataItem(), inherit(), stride(), and ~DataItem().
COM_Type DataItem::_type protected
Definition at line 286 of file DataItem.hpp.
Referenced by data_type(), DataItem(), inherit(), and ~DataItem().
std::string DataItem::_unit protected
Definition at line 287 of file DataItem.hpp.
Referenced by DataItem(), inherit(), and unit().
The documentation for this class was generated from the following files:
DataItem.hpp
DataItem.C