IMPACT: Normal_set Class Reference
Normal_set Class Reference
Detailed Description
Definition at line 78 of file Overlay_primitives.h.
#include <Overlay_primitives.h>
Public Types
typedef Normal_set Self
typedef Vector_3 Value
typedef unsigned int Size
Public Member Functions
Normal_set (HEdge h)
Normal_set (HEdge h, Size)
const Value & operator[] (Size i) const
Size size_of_edges () const
Size size_of_nodes () const
Protected Attributes
Vertex_set vs
std::vector< HEdge > hs
Member Typedef Documentation
typedef Normal_set Normal_set::Self
Definition at line 80 of file Overlay_primitives.h.
typedef unsigned int Normal_set::Size
Definition at line 82 of file Overlay_primitives.h.
typedef Vector_3 Normal_set::Value
Definition at line 81 of file Overlay_primitives.h.
Constructor & Destructor Documentation
Normal_set::Normal_set (HEdge h) inline explicit
Definition at line 84 of file Overlay_primitives.h.
References hs, HEdge::next_l(), and s.
                                 : vs(h), hs(vs.size_of_nodes()) {
     for ( unsigned int i=0, s=hs.size(); i<s; ++i)
     { hs[i] = h; h = h.next_l(); }
   }
Normal_set::Normal_set (HEdge h, Size) inline
Definition at line 88 of file Overlay_primitives.h.
References hs, HEdge::next_l(), and s.
                              : vs(h,0), hs(vs.size_of_nodes()) {
     for ( unsigned int i=0, s=hs.size(); i<s; ++i)
     { hs[i] = h; h = h.next_l(); }
   }
Member Function Documentation
const Value& Normal_set::operator[] (Size i) const inline
Definition at line 97 of file Overlay_primitives.h.
References RFC_Pane_overlay::get_normal(), hs, Vertex_set::pane(), and vs.
   { return vs.pane()->get_normal(hs[i], vs[i]); }
Size Normal_set::size_of_edges () const inline
Definition at line 99 of file Overlay_primitives.h.
References Vertex_set::size_of_edges(), and vs.
Referenced by Overlay_primitives::get_projdir().
 { return vs.size_of_edges(); }
Size Normal_set::size_of_nodes () const inline
Definition at line 100 of file Overlay_primitives.h.
References Vertex_set::size_of_nodes(), and vs.
 { return vs.size_of_nodes(); }
Member Data Documentation
std::vector< HEdge> Normal_set::hs protected
Definition at line 104 of file Overlay_primitives.h.
Referenced by Normal_set(), and operator[]().
Vertex_set Normal_set::vs protected
Definition at line 103 of file Overlay_primitives.h.
Referenced by operator[](), size_of_edges(), and size_of_nodes().
The documentation for this class was generated from the following file:
Overlay_primitives.h