IMPACT: Vector_2< Type > Class Template Reference
Vector_2< Type > Class Template Reference
Detailed Description
template<class Type>
class Vector_2< Type >
Definition at line 182 of file mapbasic.h.
#include <mapbasic.h>
Public Member Functions
Vector_2 ()
Vector_2 (Type t)
Vector_2 (Null_vector)
Vector_2 (Type a, Type b)
Type & operator[] (const int i)
const Type & operator[] (const int &i) const
Type x () const
Type y () const
Vector_2 & operator+= (const Vector_2 &v)
Assign operators.
Vector_2 & operator-= (const Vector_2 &v)
Vector_2 & operator*= (const Type t)
Vector_2 & operator/= (const Type t)
Vector_2 operator+ (const Vector_2 &v) const
Arithmatic operators.
Vector_2 operator- (const Vector_2 &v) const
Vector_2 operator* (const Type t) const
Vector_2 operator/ (const Type t) const
Type operator* (const Vector_2 &v) const
Vector_2 operator- () const
Type squared_norm () const
Type norm () const
Vector_2 & normalize ()
Vector_2 & neg ()
bool operator== (const Vector_2 &p) const
bool operator!= (const Vector_2 &p) const
bool operator< (const Vector_2 &v) const
bool is_null () const
Protected Attributes
Type _x
Type _y
Constructor & Destructor Documentation
template<class Type> Vector_2< Type >::Vector_2 () inline
Definition at line 184 of file mapbasic.h.
Referenced by Vector_2< T >::operator*(), Vector_2< T >::operator+(), Vector_2< T >::operator-(), and Vector_2< T >::operator/().
 {}
template<class Type> Vector_2< Type >::Vector_2 (Type t) inline explicit
Definition at line 185 of file mapbasic.h.
 : _x(t), _y(t) {}
template<class Type> Vector_2< Type >::Vector_2 (Null_vector) inline
Definition at line 186 of file mapbasic.h.
 : _x(0), _y(0) {}
template<class Type> Vector_2< Type >::Vector_2 (Type a, Type b) inline
Definition at line 187 of file mapbasic.h.
 : _x(a), _y(b) {}
Member Function Documentation
template<class Type> bool Vector_2< Type >::is_null () const inline
Definition at line 242 of file mapbasic.h.
 { return _x==0&&_y==0; }
template<class Type> Vector_2& Vector_2< Type >::neg () inline
Definition at line 229 of file mapbasic.h.
                   {
     _x = -_x; _y = -_y; return *this;
   }
template<class Type> Type Vector_2< Type >::norm () const inline
Definition at line 221 of file mapbasic.h.
 { return std::sqrt(*this * *this); }
template<class Type> Vector_2& Vector_2< Type >::normalize () inline
Definition at line 223 of file mapbasic.h.
{
     Type s=squared_norm();
     if ( s != Type(0)) { s=std::sqrt(s); _x/=s; _y/=s; }
     return *this;
   }
template<class Type> bool Vector_2< Type >::operator!= (const Vector_2< Type > & p) const inline
Definition at line 236 of file mapbasic.h.
   { return x()!=p.x() || y()!=p.y(); }
template<class Type> Vector_2 Vector_2< Type >::operator* (const Type t) const inline
Definition at line 209 of file mapbasic.h.
   { return Vector_2(_x*t, _y*t); }
template<class Type> Type Vector_2< Type >::operator* (const Vector_2< Type > & v) const inline
Definition at line 213 of file mapbasic.h.
   { return _x*v._x + _y*v._y; }
template<class Type> Vector_2& Vector_2< Type >::operator*= (const Type t) inline
Definition at line 199 of file mapbasic.h.
   { _x*=t; _y*=t; return *this; }
template<class Type> Vector_2 Vector_2< Type >::operator+ (const Vector_2< Type > & v) const inline
Definition at line 205 of file mapbasic.h.
   { return Vector_2(_x+v._x, _y+v._y); }
template<class Type> Vector_2& Vector_2< Type >::operator+= (const Vector_2< Type > & v) inline
Definition at line 195 of file mapbasic.h.
   { _x+=v._x; _y+=v._y; return *this; }
template<class Type> Vector_2 Vector_2< Type >::operator- (const Vector_2< Type > & v) const inline
Definition at line 207 of file mapbasic.h.
   { return Vector_2(_x-v._x, _y-v._y); }
template<class Type> Vector_2 Vector_2< Type >::operator- () const inline
Definition at line 216 of file mapbasic.h.
   { return Vector_2(-_x, -_y); }
template<class Type> Vector_2& Vector_2< Type >::operator-= (const Vector_2< Type > & v) inline
Definition at line 197 of file mapbasic.h.
   { _x-=v._x; _y-=v._y; return *this; }
template<class Type> Vector_2 Vector_2< Type >::operator/ (const Type t) const inline
Definition at line 211 of file mapbasic.h.
   { return Vector_2(_x/t, _y/t); }
template<class Type> Vector_2& Vector_2< Type >::operator/= (const Type t) inline
Definition at line 201 of file mapbasic.h.
   { _x/=t; _y/=t; return *this; }
template<class Type> bool Vector_2< Type >::operator< (const Vector_2< Type > & v) const inline
Definition at line 239 of file mapbasic.h.
Referenced by Point_2< T >::operator<().
   { return _x<v._x || _x==v._x && _y<v._y; }
template<class Type> bool Vector_2< Type >::operator== (const Vector_2< Type > & p) const inline
Definition at line 233 of file mapbasic.h.
   { return x()==p.x() && y()==p.y(); }
template<class Type> Type& Vector_2< Type >::operator[] (const int i) inline
Definition at line 188 of file mapbasic.h.
 { return i==0?_x:_y; }
template<class Type> const Type& Vector_2< Type >::operator[] (const int & i) const inline
Definition at line 189 of file mapbasic.h.
 { return i==0?_x:_y; }
template<class Type> Type Vector_2< Type >::squared_norm () const inline
Definition at line 219 of file mapbasic.h.
Referenced by Vector_2< T >::normalize().
 { return *this * *this; }
template<class Type> Type Vector_2< Type >::x () const inline
Definition at line 191 of file mapbasic.h.
Referenced by leftturn(), Vector_2< T >::operator!=(), Point_2< T >::operator!=(), Point_2< T >::operator+(), Point_2< T >::operator+=(), Point_2< T >::operator-(), Point_2< T >::operator-=(), operator<<(), Vector_2< T >::operator==(), Point_2< T >::operator==(), and rightturn().
 { return _x; }
template<class Type> Type Vector_2< Type >::y () const inline
Definition at line 192 of file mapbasic.h.
Referenced by leftturn(), Vector_2< T >::operator!=(), Point_2< T >::operator!=(), Point_2< T >::operator+(), Point_2< T >::operator+=(), Point_2< T >::operator-(), Point_2< T >::operator-=(), Vector_2< T >::operator==(), Point_2< T >::operator==(), and rightturn().
 { return _y; }
Member Data Documentation
template<class Type> Type Vector_2< Type >::_x protected
Definition at line 245 of file mapbasic.h.
Referenced by Vector_2< T >::is_null(), Vector_2< T >::neg(), Vector_2< T >::normalize(), Vector_2< T >::operator*(), Vector_2< T >::operator*=(), Vector_2< T >::operator+(), Vector_2< T >::operator+=(), Vector_2< T >::operator-(), Vector_2< T >::operator-=(), Vector_2< T >::operator/(), Vector_2< T >::operator/=(), Vector_2< T >::operator<(), Vector_2< T >::operator[](), and Vector_2< T >::x().
template<class Type> Type Vector_2< Type >::_y protected
Definition at line 245 of file mapbasic.h.
Referenced by Vector_2< T >::is_null(), Vector_2< T >::neg(), Vector_2< T >::normalize(), Vector_2< T >::operator*(), Vector_2< T >::operator*=(), Vector_2< T >::operator+(), Vector_2< T >::operator+=(), Vector_2< T >::operator-(), Vector_2< T >::operator-=(), Vector_2< T >::operator/(), Vector_2< T >::operator/=(), Vector_2< T >::operator<(), Vector_2< T >::operator[](), and Vector_2< T >::y().
The documentation for this class was generated from the following file:
mapbasic.h