IMPACT: Scheduler Class Reference
Scheduler Class Reference
Detailed Description
Definition at line 14 of file Scheduler.h.
#include <Scheduler.h>
Classes
struct ActionItem
Public Member Functions
Scheduler ()
Scheduler.
virtual ~Scheduler ()
virtual void add_action (Action *)
void reads (Action *, const char *attr, int idx)
void writes (Action *, const char *attr, int idx)
virtual void schedule ()
void init_actions (double t)
void restarting (double t)
void run_actions (double t, double dt)
void finalize_actions ()
void set_alpha (double alpha)
void print (const char *fname)
char * print (FILE *f, const char *container_name)
void printDDG (FILE *f)
bool isEmpty ()
const char * name ()
void set_name (const char *name)
Protected Types
typedef vector< ActionItem * > ActionList
Protected Member Functions
void buildDDG ()
Protected Attributes
std::string scheduler_name
ActionList actions
ActionList roots
ActionList sort
double alphaT
int scheduled
int inited
Private Member Functions
void topological_sort ()
void sanityCheck ()
void print_helper (FILE *f, ActionItem *aitem)
void print_toposort (FILE *f)
void printActions ()
Friends
class SchedulerAction
class UserSchedulerAction
Member Typedef Documentation
typedef vector< ActionItem* > Scheduler::ActionList protected
Definition at line 39 of file Scheduler.h.
Constructor & Destructor Documentation
Scheduler::Scheduler ()
Definition at line 19 of file Scheduler.C.
References scheduler_name.
                     : alphaT(-1), scheduled(0), inited(0)
 {
   scheduler_name = "Scheduler";
 }
virtual Scheduler::~Scheduler () inline virtual
Definition at line 20 of file Scheduler.h.
 {}
Member Function Documentation
void Scheduler::add_action (Action * action) virtual
Reimplemented in UserScheduler.
Definition at line 24 of file Scheduler.C.
References actions, and Action::declare().
Referenced by UserScheduler::add_action(), and main().
 {
   ActionItem *aitem = new ActionItem(action);
   actions.push_back(aitem);
   // call back action
   action->declare(*this);
 }
void Scheduler::buildDDG () protected
Definition at line 62 of file Scheduler.C.
References actions, COM_assertion, Scheduler::ActionItem::hasOutput(), Scheduler::ActionItem::input, Scheduler::ActionItem::n_read(), Scheduler::ActionItem::output, Scheduler::ActionItem::read_attr, Scheduler::ActionItem::read_idx, and roots.
Referenced by schedule(), and UserScheduler::schedule().
 {
 #if 0
    ActionList pool;
    pool = actions;
    while (pool.size()!=0) {
      // find one leaf with no output or output already fullfiled
      ActionList::iterator act = pool.end()-1;
      for (; act>=pool.begin(); act--)
      {
        if ((*act)->fullfilled()== 1) {
 //printf("FOUND LEAF: %s\n", (*act)->name());
          break;
        }
      }
      if (act < pool.begin()) {   // error with loop
        printf("Loop detected!\n");
        COM_assertion(false);
      }
      ActionItem *item = *act;
      pool.erase(act);           // don't use iterator act afterwards
      if (item->n_read() == 0) {    // this is a tree root
        roots.push_back(item);
      }
      else
        for (unsigned int i=0; i<item->n_read(); i++) {
          if (item->input[i] == NULL) {
            // find matching input actions for item from pool
            ActionList::iterator a = pool.end()-1;
            for (; a>=pool.begin(); a--)  {
              int inIdx = (*a)->hasOutput(item->read_attr[i], item->read_idx[i]);
              if (inIdx != -1) {     // set up double link
 //printf("updated output of %s for %s %d\n", (*a)->name(), item->read_attr[i], item->read_idx[i]);
                item->input[i] = *a;
                (*a)->output[inIdx] = item;
                break;                   // only do once
              }
            }
            if (a < pool.begin()) { // a read without any matching write
              printf("Error: can not find matching input for action %s of attr:%s index:%d. \n", (*a)->name(), item->read_attr[i], item->read_idx[i]);
            }
          }       // end of for i
      }
    }    // end of while
 #else
    //  make links
    ActionList pool;
    pool = actions;
    unsigned int idx = 1;
    while (idx<pool.size()) {
      ActionItem *item = pool[idx];
      // search all input
      for (unsigned int i=0; i<item->n_read(); i++) {
        for (int j=idx-1; j>=0; j--)  {
          ActionItem *aitem = pool[j];
          int inIdx = aitem->hasOutput(item->read_attr[i], item->read_idx[i]);
          if (inIdx != -1) {
            item->input[i] = aitem;
            aitem->output[inIdx] = item;
          }
        }
      }
      idx ++;
    }
    //  identify root nodes
    for (idx=0; idx<pool.size(); idx++) {
      ActionItem *item = pool[idx];
      int isroot = 1;
      for (unsigned int i=0; i<item->n_read(); i++)
        if (item->input[i] != NULL) {
          isroot = 0;
          break;
        }
      if (isroot) roots.push_back(item);
    }
 #endif
 }
void Scheduler::finalize_actions ()
Definition at line 334 of file Scheduler.C.
References Scheduler::ActionItem::action(), COM_assertion_msg, Action::finalize(), scheduled, and sort.
Referenced by SchedulerAction::finalize(), UserSchedulerAction::finalize(), Coupling::finalize(), Agent::finalize(), and main().
 {
   COM_assertion_msg(scheduled, "ERROR: Scheduler has not been scheduled when calling finalize_actions.\n");
   if (sort.size()==0) return;
   // do at reversed order
   ActionList::iterator aitem;
   for (aitem = sort.end()-1; aitem>=sort.begin(); aitem--)
   {
     ActionItem *item = *aitem;
     item->action()->finalize();
   }
 }
void Scheduler::init_actions (double t)
Definition at line 307 of file Scheduler.C.
References Scheduler::ActionItem::action(), COM_assertion_msg, Action::init(), inited, scheduled, and sort.
Referenced by SchedulerAction::init(), UserSchedulerAction::init(), Coupling::init(), Agent::init_bcinitaction(), Agent::init_callback(), Agent::init_gmactions(), Agent::init_subscheduler(), and main().
 {
   COM_assertion_msg(scheduled, "RROR: Scheduler has not been scheduled.\n");
   if (inited) return;
   inited = 1;
   // do at sorted order
   ActionList::iterator aitem;
   for (aitem = sort.begin(); aitem!=sort.end(); aitem++)
   {
     ActionItem *item = *aitem;
     item->action()->init(t);
   }
 }
bool Scheduler::isEmpty () inline
Definition at line 33 of file Scheduler.h.
Referenced by Agent::init_callback(), and Agent::obtain_gm().
 { return actions.size() == 0; }
const char* Scheduler::name () inline
Definition at line 34 of file Scheduler.h.
Referenced by print(), and Scheduler::ActionItem::print().
 { return scheduler_name.c_str(); }
void Scheduler::print (const char * fname)
Definition at line 227 of file Scheduler.C.
References IMPACT::ExampleProgram::f().
Referenced by main(), SchedulerAction::print(), UserSchedulerAction::print(), Agent::print(), and printActions().
 {
   FILE *f = fopen(fname, "w");
   fprintf(f, "graph: { title: \"DependenceTree\" \n\
         display_edge_labels: yes \n\
         layoutalgorithm: tree   \n\
         scaling: maxspect   \n\
         node.color     : green   \n\
         node.textcolor : black   \n\
         node.bordercolor: black \n\
         node.borderwidth: 1    \n\
         edge.color     : blue   \n\
         edge.arrowsize : 7   \n\
         edge.thickness : 2   \n\
         edge.fontname:\"helvO08\"  \n\
         node.label: \"no type\" \n");
   print(f, "scheduler");
   fprintf(f, "} \n");
   fclose(f);
 }
char * Scheduler::print (FILE * f, const char * container_name)
Definition at line 191 of file Scheduler.C.
References actions, name(), print_helper(), and roots.
 {
   if (actions.size() == 0) return NULL;
   std::string sched_name = container_name;
   sched_name = sched_name + "-" + name();
   fprintf(f, "graph: { title: \"%s\" label: \"%s\" \n\
         status: folded \n\
         display_edge_labels: yes \n\
         layoutalgorithm: tree   \n\
         scaling: maxspect   \n\
         color :  white           \n\
         node.color     : lightblue   \n\
         node.textcolor : black   \n\
         node.bordercolor: black \n\
         node.borderwidth: 1    \n\
         edge.color     : lightblue   \n\
         edge.arrowsize : 7   \n\
         edge.thickness : 2   \n\
         edge.fontname:\"helvO08\"  \n\
         node.label: \"no type\" \n", sched_name.c_str(), sched_name.c_str());
   unsigned int i;
   for (i=0; i<actions.size(); i++)
     actions[i]->print_flag = 0;
   for (i=0; i<roots.size(); i++) {
     print_helper(f, roots[i]);
   }
   fprintf(f, "}\n");
   return strdup(sched_name.c_str());
 }
void Scheduler::print_helper (FILE * f, ActionItem * aitem) private
Definition at line 177 of file Scheduler.C.
References Scheduler::ActionItem::action(), Scheduler::ActionItem::input, Scheduler::ActionItem::n_read(), Scheduler::ActionItem::n_write(), Scheduler::ActionItem::name(), Scheduler::ActionItem::output, Action::print(), Scheduler::ActionItem::print_flag, Scheduler::ActionItem::read_attr, and Scheduler::ActionItem::read_idx.
Referenced by print().
 {
   unsigned int i;
   if (aitem->print_flag == 1) return;
   aitem->print_flag = 1;
   aitem->action()->print(f);
   for (i=0; i<aitem->n_read(); i++) {
     if (aitem->input[i])
       fprintf(f, "edge: { sourcename: \"%s\" targetname: \"%s\" label: \"%s,%d\"}\n", aitem->input[i]->name(), aitem->name(), aitem->read_attr[i], aitem->read_idx[i]);
   }
   for (i=0; i<aitem->n_write(); i++)
     if ( aitem->output[i]) print_helper(f, aitem->output[i]);
 }
void Scheduler::print_toposort (FILE * f) private
Definition at line 285 of file Scheduler.C.
References sort.
Referenced by SchedulerAction::print_toposort(), and schedule().
 {
   for (unsigned int i=0; i<sort.size(); i++)  sort[i]->action()->print_toposort(f);
 }
void Scheduler::printActions () private
Definition at line 170 of file Scheduler.C.
References actions, and print().
Referenced by schedule().
 {
   for (unsigned int i=0; i<actions.size(); i++)
     actions[i]->print(stdout);
   printf("\n");
 }
void Scheduler::printDDG (FILE * f)
void Scheduler::reads (Action * a, const char * attr, int idx)
Definition at line 32 of file Scheduler.C.
References actions, and Action::name().
Referenced by ActionB::declare(), ActionC::declare(), Action::declare(), ActionD::declare(), ActionE::declare(), and ActionG::declare().
 {
   // FIXME: locate this action, doing linear search now
   ActionList::iterator aitem;
   for (aitem = actions.begin(); aitem != actions.end(); aitem++)
     if ((*aitem)->action() == a) break;
   if (aitem == actions.end()) {
     printf("ERROR: action '%s' not registered to scheduler. \n", a->name());
     exit(1);
   }
   (*aitem)->read_attr.push_back(strdup(attr));     // copy the string
   (*aitem)->read_idx.push_back(idx);
   (*aitem)->input.push_back(NULL);
 }
void Scheduler::restarting (double t) inline
Definition at line 26 of file Scheduler.h.
Referenced by Coupling::init().
 { inited = 0; }          // clear init state for restarting
void Scheduler::run_actions (double t, double dt)
Definition at line 322 of file Scheduler.C.
References Scheduler::ActionItem::action(), alphaT, COM_assertion_msg, Action::run(), scheduled, and sort.
Referenced by Agent::init_callback(), main(), Agent::obtain_bc(), Agent::obtain_gm(), SchedulerAction::run(), UserSchedulerAction::run(), Coupling::run(), Agent::run_bcinitaction(), and Coupling::run_initactions().
 {
   COM_assertion_msg(scheduled, "RROR: Scheduler has not been scheduled when calling run_actions.\n");
   // do at sorted order
   ActionList::iterator aitem;
   for (aitem = sort.begin(); aitem!=sort.end(); aitem++)
   {
     ActionItem *item = *aitem;
     item->action()->run(t, dt, alphaT);
   }
 }
void Scheduler::sanityCheck () private
Definition at line 290 of file Scheduler.C.
References actions, COM_assertion_msg, Scheduler::ActionItem::input, Scheduler::ActionItem::n_read(), Scheduler::ActionItem::n_write(), and Scheduler::ActionItem::output.
Referenced by schedule().
 {
   // make sure all input and output are not null
   ActionList::iterator aitem;
   for (aitem = actions.begin(); aitem!=actions.end(); aitem++)
   {
     ActionItem *item = *aitem;
     unsigned int i;
     COM_assertion_msg(item->n_read() == item->input.size(), "ERROR: Scheduler::sanityCheck failed.\n");
     for (i=0; i<item->n_read(); i++)
       COM_assertion_msg(item->input[i] != NULL, "ERROR: Scheduler::sanityCheck failed at 2.\n");
     COM_assertion_msg(item->n_write() == item->output.size(), "ERROR: Scheduler::sanityCheck failed at 3.\n");
     for (i=0; i<item->n_write(); i++)
       COM_assertion_msg(item->output[i] != NULL, "ERROR: Scheduler::sanityCheck failed at 4.\n");
   }
 }
void Scheduler::schedule () virtual
Reimplemented in UserScheduler.
Definition at line 145 of file Scheduler.C.
References actions, buildDDG(), COM_assertion_msg, print_toposort(), printActions(), sanityCheck(), scheduled, and topological_sort().
Referenced by main(), and SchedulerAction::schedule().
 {
   //   MAN_DEBUG(1, ("Scheduler::schedule called.\n"));
   COM_assertion_msg(!scheduled, "ERROR: Scheduler has already been scheduled.\n");
   // schedule all sub-schedulers
   for (unsigned int i=0; i<actions.size(); i++)
     actions[i]->action()->schedule();
   // debugging
   printActions();
   buildDDG();
   sanityCheck();
   topological_sort();
   printf("Topological sort:\n");
   print_toposort(stdout);
   printf("\n");
   scheduled = 1;
 }
void Scheduler::set_alpha (double alpha) inline
Definition at line 29 of file Scheduler.h.
Referenced by Agent::init_callback(), Agent::obtain_bc(), Agent::obtain_gm(), UserSchedulerAction::run(), and Coupling::run_initactions().
 { alphaT = alpha; }
void Scheduler::set_name (const char * name) inline
Definition at line 35 of file Scheduler.h.
References Action::name().
Referenced by Agent::add_bcaction(), and Agent::Agent().
 { scheduler_name = name; }
void Scheduler::topological_sort () private
Definition at line 251 of file Scheduler.C.
References Scheduler::ActionItem::action(), actions, Scheduler::ActionItem::input, s, and sort.
Referenced by schedule().
 {
   ActionList pool;
   pool = actions;
   while (1) {
     ActionList::iterator aitem = pool.begin();
     for (; aitem!=pool.end(); aitem++) {
       if ((*aitem)->n_read() == 0) { break; }
       // check every input
       int flag = 1;
       for (unsigned int i=0; i<(*aitem)->n_read(); i++) {
         ActionItem *in = (*aitem)->input[i];
         // search in sort
         ActionList::iterator s;
         for (s = sort.begin(); s!=sort.end(); ++s)
           if ((*s)->action() == in->action()) break;
         if (s == sort.end()) { flag = 0; break; }
       }
       if (flag) break;
     }
     if (aitem != pool.end()) {
       sort.push_back(*aitem);
       pool.erase(aitem);
     }
     else
       break;
   }
   if (pool.size() != 0) {
     printf("ERROR in sorting!\n");
     exit (1);
   }
 }
void Scheduler::writes (Action * a, const char * attr, int idx)
Definition at line 47 of file Scheduler.C.
References actions, COM_assertion, and Action::name().
Referenced by ActionA::declare(), ActionB::declare(), ActionC::declare(), Action::declare(), and ActionF::declare().
 {
   // locate this action
   ActionList::iterator aitem = actions.begin();
   for (; aitem != actions.end(); aitem++)
     if ((*aitem)->action() == a) break;
   if (aitem == actions.end()) {
     printf("ERROR: action '%s' not registered to scheduler. \n", a->name());
     COM_assertion(false);
   }
   (*aitem)->write_attr.push_back(strdup(attr));   // copy the string
   (*aitem)->write_idx.push_back(idx);
   (*aitem)->output.push_back(NULL);
 }
Friends And Related Function Documentation
friend class SchedulerAction friend
Definition at line 16 of file Scheduler.h.
friend class UserSchedulerAction friend
Definition at line 17 of file Scheduler.h.
Member Data Documentation
ActionList Scheduler::actions protected
Definition at line 63 of file Scheduler.h.
Referenced by add_action(), UserScheduler::add_action(), buildDDG(), print(), printActions(), reads(), sanityCheck(), schedule(), topological_sort(), and writes().
double Scheduler::alphaT protected
Definition at line 67 of file Scheduler.h.
Referenced by run_actions().
int Scheduler::inited protected
Definition at line 70 of file Scheduler.h.
Referenced by init_actions().
ActionList Scheduler::roots protected
Definition at line 64 of file Scheduler.h.
Referenced by UserScheduler::add_action(), buildDDG(), and print().
int Scheduler::scheduled protected
Definition at line 69 of file Scheduler.h.
Referenced by finalize_actions(), init_actions(), run_actions(), schedule(), and UserScheduler::schedule().
std::string Scheduler::scheduler_name protected
Definition at line 37 of file Scheduler.h.
Referenced by Scheduler().
ActionList Scheduler::sort protected
Definition at line 65 of file Scheduler.h.
Referenced by UserScheduler::add_action(), finalize_actions(), init_actions(), print_toposort(), run_actions(), and topological_sort().
The documentation for this class was generated from the following files:
Scheduler.h
Scheduler.C