IMPACT: RFC_Window_overlay Class Reference
RFC_Window_overlay Class Reference
A window is a collection of panes.
Detailed Description
Definition at line 338 of file RFC_Window_overlay.h.
#include <RFC_Window_overlay.h>
Classes
class Feature_0
struct Feature_1
Public Types
typedef RFC_Window_overlay Self
typedef RFC_Window_derived
< RFC_Pane_overlay > Base
typedef
MAP::Simple_manifold_2::Edge_ID Edge_ID
typedef std::list< Feature_0 > Feature_list_0
typedef std::list< Feature_1 > Feature_list_1
Public Types inherited from RFC_Window_base
typedef RFC_Window_base Self
typedef COM::Window Base
typedef COM::DataItem DataItem
typedef RFC_Pane_base Pane
typedef std::map< int, Pane * > Pane_set
Public Member Functions
RFC_Window_overlay (COM::Window *b, int color, const char *pre=NULL)
virtual ~RFC_Window_overlay ()
bool is_same_node (const Node &v1, const Node &v2)
Check whether given two vertices correspond to the same physical point.
void create_overlay_data ()
void delete_overlay_data ()
void determine_counterparts ()
void unmark_alledges ()
HEdge get_an_unmarked_halfedge () const
void evaluate_normals ()
void print_features ()
Dump out the 0- and 1-features in Tecplot format into files <name>f0.plt, <name>f1.plt, respectively.
void detect_features ()
The main entry of feature detection.
bool snap_on_features () const
Feature_list_0 & flist_0 ()
Feature_list_1 & flist_1 ()
const Feature_list_0 & flist_0 () const
const Feature_list_1 & flist_1 () const
void remove_feature_1 (Feature_1 &f)
Remove a false strong curve.
Feature_list_0::iterator remove_feature_0 (Feature_list_0::iterator i)
Remove the given 0-feature from the list.
Public Member Functions inherited from RFC_Window_derived< RFC_Pane_overlay >
const Pane & pane (const int pid) const
Get a reference to the pane with give id pid.
Pane & pane (const int pid)
std::pair< Pane *, int > get_primary (Pane *p, int vid)
Get a handle to the primary copy of a node contained in the pane p with local id vid.
std::pair< const Pane *, int > get_primary (const Pane *p, int vid) const
void panes (std::vector< Pane * > &ps)
Get a vector of local panes contained in the window.
void panes (std::vector< const Pane * > &ps) const
Public Member Functions inherited from RFC_Window_base
RFC_Window_base (Base *b, int c, MPI_Comm)
Construct an object with base b and color c.
virtual ~RFC_Window_base ()
Default destructor.
std::string name () const
The name of the window.
const RFC_Pane_base & pane (const int pid) const
RFC_Pane_base & pane (const int pid)
const COM::Window * base () const
Get a reference to the base COM::Window object.
int color () const
The color of the window for overlay or for data transfer (BLUE or GREEN).
int size_of_nodes () const
Get the total number of nodes contained the window.
int size_of_faces () const
Get the total number of faces contained the window.
int size_of_primary_nodes () const
Get the total number of nodes contained the window.
Bbox_3 get_bounding_box () const
Get the bounding box of the window.
int size_of_panes () const
Number of local panes in the window.
const DataItem * dataitem (const char *f) const
Retrieve an dataitem object from the base using the dataitem name.
void export_window (RFC_Window_base *) const
void write_tec_ascii (const char *prefix) const
Ouptut a mesh in Tecplot format.
void write_tec_sub (const char *prefix) const
Ouptut a subdivision of a mesh in Tecplot format.
void new_sdv_dataitems (const std::string &wname) const
New dataitems.
void read_sdv (const char *prefix, const char *format=NULL)
Read in local panes in native binary format or using Rocin.
void write_sdv (const char *prefix, const char *format=NULL) const
Write out panes in native binary format or using Rocout.
void build_pc_tables ()
Build the pane connectivity table.
Protected Member Functions
void reduce_normals_to_all (MPI_Op)
virtual SURF::Pane_manifold_2 * init_pane_manifold (int pane_id)
Vector_3 get_tangent (const HEdge &h)
float comp_angle_defect (const Node &v)
Compute the angle defect of a vertex.
float cos_face_angle (const HEdge &h, const HEdge &hopp)
Compute the cosine of the face angle (dihedral angle) at an edge.
float cos_face_angle (const HEdge &h)
Compute the cosine of the face angle (dihedral angle) at an edge.
float cos_edge_angle (const HEdge &h1, const HEdge &h2)
Compute the cosine of the edge angle at a vertex between two incident feature edges.
float cos_edge_angle (const Feature_1 &f1, Feature_1::const_iterator it, bool isloop)
Compute the cosine of the edge angle at a vertex in a given feature curve.
bool is_strong_ad (const Node &v)
Determine whether a vertex is strong (either theta-strong or relatively strong) in angle defect.
bool is_rstrong_ea (const Feature_1 &f1, Feature_1::const_iterator hprev, Feature_1::const_iterator hnext, float cos_ea, bool isloop)
Determine whether a vertex is relatively strong in edge angle within a give feature.
bool check_false_strong_1 (Feature_1 &)
Determine whether a curve is false strong.
void subdiv_feature_curve (const Feature_1 &f1, Feature_list_1 &new_flist, int &dropped)
Subdivide a feature curve by splitting it at 0-features.
void merge_features_1 (const Node &v, Feature_1 &f1, Feature_1 &f2)
Merge two feature curves into one at vertex v.
void identify_features_0 ()
Identify the 0-features.
Protected Member Functions inherited from RFC_Window_derived< RFC_Pane_overlay >
RFC_Window_derived (COM::Window *b, int c, MPI_Comm comm)
A constructor.
virtual ~RFC_Window_derived ()
A destructor.
void init ()
Private Member Functions
void init_feature_parameters ()
Read in the control file for feature detection.
void set_feature_0 (const Node &v) const
void set_on_feature (const Node &v) const
bool is_feature_0 (const Node &v) const
bool is_on_feature (const Node &v) const
bool is_feature_1 (const HEdge &h) const
void unset_strong_edge (const HEdge &h)
void dump_strong_edges (const std::vector< std::pair< float, HEdge > > &, const std::vector< std::pair< float, HEdge > > &)
Dump out the strong edges in Tecplot format into file <name>s1.plt.
void normalize (Vector_3 &v)
Miscellaneous Helpers.
Private Attributes
float _cos_uf
float _cos_lf
float _rf
float _cos_weakend
float _ud
float _ld
float _rd
float _cos_ue
float _cos_le
float _re
int _min_1f_len
int verb
std::string out_pre
Feature_list_0 _f_list_0
Feature_list_1 _f_list_1
std::map< Node, int > _f0_ranks
bool _long_falseness_check
bool _strong_ended
bool _snap_on_features
Static Private Attributes
static const float r2d =180./3.1415926535
Additional Inherited Members
Protected Types inherited from RFC_Window_derived< RFC_Pane_overlay >
typedef RFC_Window_derived
< RFC_Pane_overlay > Self
typedef RFC_Window_base Base
typedef RFC_Pane_overlay Pane
Protected Types inherited from RFC_Window_base
enum { SDV_OFF, SDV_BINARY, SDV_HDF, SDV_CGNS }
Static Protected Member Functions inherited from RFC_Window_base
static std::string get_sdv_fname (const char *prefix, int pane_id, const int format=SDV_BINARY)
static const char * get_prefix_base (const char *prefix)
static int get_sdv_format (const char *format)
Protected Attributes inherited from RFC_Window_base
Base * _base
A reference to its base COM::Window object.
Pane_set _pane_set
The set of panes contained in the window.
int _verbose
int _color
MAP::Pane_communicator _map_comm
Static Protected Attributes inherited from RFC_Window_base
static const char * _bufwin_prefix = "buf_"
Member Typedef Documentation
typedef RFC_Window_derived<RFC_Pane_overlay> RFC_Window_overlay::Base
Definition at line 342 of file RFC_Window_overlay.h.
typedef MAP::Simple_manifold_2::Edge_ID RFC_Window_overlay::Edge_ID
Definition at line 343 of file RFC_Window_overlay.h.
typedef RFC_Window_overlay RFC_Window_overlay::Self
Definition at line 341 of file RFC_Window_overlay.h.
Constructor & Destructor Documentation
RFC_Window_overlay::RFC_Window_overlay (COM::Window * b, int color, const char * pre = NULL)
Definition at line 31 of file RFC_Window_overlay.C.
References RFC_Window_base::build_pc_tables(), COM_PMESH, determine_counterparts(), Window_manifold_2::init(), init_feature_parameters(), and RFC_Window_derived< RFC_Pane_overlay >::panes().
   : Base(b, color, MPI_COMM_SELF), out_pre(pre?pre:""),
     _long_falseness_check(true) {
   init_feature_parameters();
   vector< Pane*> pns; panes(pns);
   vector< Pane*>::iterator pit=pns.begin(), piend=pns.end();
   for ( ; pit != piend; ++pit) {
     (*pit)->_window = this;
   }
   Window_manifold_2::init(b->dataitem(COM::COM_PMESH));
   // Preprocess pane connectivity.
   std::cout << "Building pane connectivity..." << std::flush;
   build_pc_tables();
   // Determine the counterpart for border edges of all panes.
   determine_counterparts();
   std::cout << "Done" << std::endl;
 }
RFC_Window_overlay::~RFC_Window_overlay () virtual
Definition at line 56 of file RFC_Window_overlay.C.
{
   for (int i=_pms.size()-1; i>=0; --i)
     _pms[i] = NULL;
 }
Member Function Documentation
void RFC_Window_overlay::normalize (Vector_3 & v) inline private
Definition at line 488 of file RFC_Window_overlay.h.
Referenced by evaluate_normals().
   { if (v != Vector_3(0,0,0)) v = v / std::sqrt( v*v); }
Member Data Documentation
float RFC_Window_overlay::_cos_le private
Definition at line 493 of file RFC_Window_overlay.h.
float RFC_Window_overlay::_cos_lf private
Definition at line 491 of file RFC_Window_overlay.h.
float RFC_Window_overlay::_cos_ue private
Definition at line 493 of file RFC_Window_overlay.h.
float RFC_Window_overlay::_cos_uf private
Definition at line 491 of file RFC_Window_overlay.h.
float RFC_Window_overlay::_cos_weakend private
Definition at line 491 of file RFC_Window_overlay.h.
std::map<Node,int> RFC_Window_overlay::_f0_ranks private
Definition at line 500 of file RFC_Window_overlay.h.
Feature_list_0 RFC_Window_overlay::_f_list_0 private
Definition at line 498 of file RFC_Window_overlay.h.
Referenced by evaluate_normals(), and flist_0().
Feature_list_1 RFC_Window_overlay::_f_list_1 private
Definition at line 499 of file RFC_Window_overlay.h.
Referenced by evaluate_normals(), and flist_1().
float RFC_Window_overlay::_ld private
Definition at line 492 of file RFC_Window_overlay.h.
bool RFC_Window_overlay::_long_falseness_check private
Definition at line 501 of file RFC_Window_overlay.h.
int RFC_Window_overlay::_min_1f_len private
Definition at line 494 of file RFC_Window_overlay.h.
float RFC_Window_overlay::_rd private
Definition at line 492 of file RFC_Window_overlay.h.
float RFC_Window_overlay::_re private
Definition at line 493 of file RFC_Window_overlay.h.
float RFC_Window_overlay::_rf private
Definition at line 491 of file RFC_Window_overlay.h.
bool RFC_Window_overlay::_snap_on_features private
Definition at line 504 of file RFC_Window_overlay.h.
Referenced by snap_on_features().
bool RFC_Window_overlay::_strong_ended private
Definition at line 502 of file RFC_Window_overlay.h.
float RFC_Window_overlay::_ud private
Definition at line 492 of file RFC_Window_overlay.h.
std::string RFC_Window_overlay::out_pre private
Definition at line 497 of file RFC_Window_overlay.h.
const float RFC_Window_overlay::r2d =180./3.1415926535 static private
Definition at line 506 of file RFC_Window_overlay.h.
int RFC_Window_overlay::verb private
Definition at line 495 of file RFC_Window_overlay.h.
The documentation for this class was generated from the following files:
RFC_Window_overlay.h
RFC_Window_overlay.C
RFC_Window_overlay_fea.C
RFC_Window_overlay_IO.C