IMPACT: Pane Class Reference
Pane Class Reference
A Pane object contains a mesh, pane dataitem, and field variables.
Detailed Description
Mesh data include nodal coordinates and element connectivity.
Definition at line 25 of file Pane.hpp.
#include <Pane.hpp>
Classes
class Connectivity_friend
class DataItem_friend
Public Types
enum OP_Init {
OP_SET =1, OP_SET_CONST, OP_ALLOC, OP_RESIZE,
OP_DEALLOC
}
enum Inherit_Modes { INHERIT_USE =0, INHERIT_CLONE, INHERIT_COPY }
typedef std::vector< DataItem * > DataGroup
Vector of dataitems.
typedef std::vector
< Connectivity * > Cnct_set
Vector of connectivities.
typedef unsigned int Size
Unsighed int.
Public Member Functions
Constructor and destructor
Pane (ComponentInterface *w, int i)
Create a pane in window w with ID i.
Pane (Pane *p, int i)
Create a pane by copying from dataitem descriptions from another pane.
virtual ~Pane ()
Default destructor.
Initialization
void init_done () throw (COM_exception)
Finalize the initialization of a pane.
Identification
const ComponentInterface * window () const
Obtain a constant pointer to its owner window object.
ComponentInterface * window ()
Obtain a pointer to its owner window object.
int id () const
Get the ID of the pane.
int dimension () const
Dimension of the pane.
bool is_unstructured () const
Is mesh of the pane unstructured?
bool is_mixed () const
Does the pane contain more than one type of elements?
bool is_structured () const
Is mesh of the pane structured?
Mesh management
Size size_of_nodes () const
Get the total number of nodes in the pane (including ghost nodes).
Size maxsize_of_nodes () const
Get the maximum number of real nodes in the pane (excluding ghost nodes).
Size size_of_ghost_nodes () const
Get the number of ghost nodes.
Size maxsize_of_ghost_nodes () const
Get the maximum number of real nodes in the pane (excluding ghost nodes).
Size size_of_real_nodes () const
Get the number of real nodes in the pane (excluding ghost nodes).
Size maxsize_of_real_nodes () const
Get the maximum number of real nodes in the pane (excluding ghost nodes).
Size size_of_elements () const
Get the total number of elements in the pane (including ghost elements).
Size maxsize_of_elements () const
Get the maximum number of elements allowed in the pane (including ghost elements)
Size size_of_ghost_elements () const
Get the total number of ghost elements.
Size maxsize_of_ghost_elements () const
Get the maximum number of elements allowed in the pane (including ghost elements)
Size size_of_real_elements () const
Get the number of real elements in the pane (excluding ghost elements).
Size maxsize_of_real_elements () const
Get the maximum number of real elements allowed in the pane (excluding ghost elements).
double * coordinates ()
Get the pointer to the values of the coordinates.
double * x_coordinates ()
Get the pointer to the values of the x-coordinates, if the coordinates are staggered.
double * y_coordinates ()
Get the pointer to the values of the y-coordinates, if the coordinates are staggered.
double * z_coordinates ()
Get the pointer to the values of the z-coordinates, if the coordinates are staggered.
const double * coordinates () const
Get a constant pointer to the values of the coordinates.
const double * x_coordinates () const
Get a constant pointer to the values of the x-coordinates, if the coordinates are staggered.
const double * y_coordinates () const
Get a constant pointer to the values of the y-coordinates, if the coordinates are staggered.
const double * z_coordinates () const
Get a constant pointer to the values of the z-coordinates, if the coordinates are staggered.
int * pane_connectivity ()
Get a pointer to the values of the pane connectivity.
const int * pane_connectivity () const
Get a const pointer to the values of the pane connectivity.
bool ignore_ghost () const
void set_ignore_ghost (bool ignore)
Structured meshes
Size size_of_ghost_layers () const
Dimension of the pane.
Size size_i () const
Get the number of nodes in i-dimension if the mesh is structured.
Size size_j () const
Get the number of nodes in j-dimension if the mesh is structured.
Size size_k () const
Get the number of nodes in k-dimension if the mesh is structured.
DataItem management
void dataitems (std::vector< DataItem * > &as)
Obtain all the dataitems of the pane.
void dataitems (std::vector< const DataItem * > &as) const
Obtain all the dataitems of the pane.
DataItem * dataitem (const std::string &a)
Obtain the dataitem from given name.
const DataItem * dataitem (const std::string &a) const
Obtain the dataitem from given name.
DataItem * dataitem (int i)
Obtain the dataitem from its ID.
const DataItem * dataitem (int i) const
Obtain the dataitem from its ID.
Connectivity management
void connectivities (std::vector< Connectivity * > &es)
Obtain all the element connectivities of the pane.
void connectivities (std::vector< const Connectivity * > &es) const
Connectivity * connectivity (Size i) throw (COM_exception)
Obtain the connectivity table containing the element with the given ID.
const Connectivity * connectivity (Size i) const throw (COM_exception)
void elements (std::vector< Connectivity * > &es)
Obtain all the element connectivities of the pane.
void elements (std::vector< const Connectivity * > &es) const
void refresh_connectivity () throw (COM_exception)
Update offsets and sizes of connectivity of an unstructured mesh.
Protected Member Functions
DataItem * new_dataitem (const std::string &aname, int aid, const char loc, const int type, int ncomp, const std::string &unit) throw (COM_exception)
void insert (DataItem *attr) throw (COM_exception)
Insert an dataitem onto the pane.
void delete_dataitem (int id) throw (COM_exception)
Delete an existing dataitem with given id.
void reinit_dataitem (int aid, OP_Init op, void **addr, int strd, int cap) throw (COM_exception)
const Connectivity * connectivity (const std::string &a) const throw (COM_exception)
Obtain the connectivity with the given name.
Connectivity * connectivity (const std::string &a, bool insert=false) throw (COM_exception)
void reinit_conn (Connectivity *con, OP_Init op, int **addr, int strd, int cap) throw (COM_exception)
DataItem * inherit (DataItem *from, const std::string &aname, int mode, bool withghost) throw (COM_exception)
Inherit an dataitem from another pane onto the current pane:
void set_size (DataItem *a, int nitems, int ng) throw (COM_exception)
Set the size of an dataitem.
void set_size (Connectivity *con, int nitems, int ng) throw (COM_exception)
Set the size of a connectivity table.
Protected Attributes
ComponentInterface * _window
Point to the parent window.
int _id
Pane id.
DataGroup _attr_set
Set of dataitems.
Cnct_set _cnct_set
Set of element connectivity.
bool _ignore_ghost
Whether the ghosts were ignored.
Private Member Functions
Pane (const Pane &)
Pane & operator= (const Pane &)
Member Typedef Documentation
typedef std::vector<Connectivity*> Pane::Cnct_set
Definition at line 28 of file Pane.hpp.
typedef std::vector<DataItem*> Pane::DataGroup
Definition at line 27 of file Pane.hpp.
typedef unsigned int Pane::Size
Definition at line 29 of file Pane.hpp.
Member Enumeration Documentation
enum Pane::Inherit_Modes
Enumerator
INHERIT_USE
INHERIT_CLONE
INHERIT_COPY
Definition at line 31 of file Pane.hpp.
 { INHERIT_USE=0, INHERIT_CLONE, INHERIT_COPY };
enum Pane::OP_Init
Enumerator
OP_SET
OP_SET_CONST
OP_ALLOC
OP_RESIZE
OP_DEALLOC
Definition at line 30 of file Pane.hpp.
 { OP_SET=1, OP_SET_CONST, OP_ALLOC, OP_RESIZE, OP_DEALLOC};
Constructor & Destructor Documentation
COM_BEGIN_NAME_SPACE Pane::Pane (ComponentInterface * w, int i)
Definition at line 16 of file Pane.C.
References _attr_set, and COM_NUM_KEYWORDS.
                             :
   _window(w), _id(i), _ignore_ghost(false)
 {
   _attr_set.resize( COM_NUM_KEYWORDS);
   DataItem *as = new DataItem[COM_NUM_KEYWORDS];
   for ( int i=0; i<COM_NUM_KEYWORDS; ++i) {
     // Call constructor in placement form.
     _attr_set[i] = new (&as[i]) DataItem_friend(this, i);
   }
 }
Pane::Pane (Pane * p, int i)
Definition at line 28 of file Pane.C.
References _attr_set, COM_NUM_KEYWORDS, INHERIT_USE, DataItem::is_windowed(), DataItem::pane(), and DataItem::size_of_components().
                            :
   _window(p->_window), _id(id), _ignore_ghost(false)
 {
   int n = p->_attr_set.size();
   _attr_set.resize( n, NULL);
   // First allocate for keywords
   DataItem *as = new DataItem[COM_NUM_KEYWORDS];
   for ( int i=0; i<COM_NUM_KEYWORDS; ++i) {
     _attr_set[i] = new (&as[i]) DataItem( this, p->_attr_set[i], "", i);
   }
   for ( int i=COM_NUM_KEYWORDS; i<n; ) {
     DataItem *ap=p->_attr_set[i];
     if ( ap==NULL || ap->pane()==NULL) { ++i; continue; }
     int ncomp=ap->size_of_components();
     // Allocate for dataitem and its components
     as = new DataItem[ncomp+(ncomp>1)];
     // Call constructor at the dataitem and its individual components
     for ( int k=0, nk=(ncomp==1)?0:ncomp; k<=nk; ++k,++i)
       _attr_set[i] = new (&as[k]) DataItem( this, &ap[k], "", i);
     // Inherit window dataitems from dummy pane
     if ( ap->is_windowed())
       reinterpret_cast<DataItem_friend*>(as)->inherit( ap, INHERIT_USE, true);
   }
 }
Pane::~Pane () virtual
Definition at line 58 of file Pane.C.
References _attr_set, _cnct_set, COM_DATA, and delete_dataitem().
             {
   delete [] _attr_set[0];  // Delete all keywords
   delete_dataitem( COM_DATA); // Delete all user-defined dataitems.
   for ( Size i=0,n=_cnct_set.size(); i<n; ++i)
     delete _cnct_set[i];  // Delete all connectivity tables.
 }
Pane::Pane (const Pane &) private
Member Function Documentation
void Pane::connectivities (std::vector< Connectivity * > & es) inline
Definition at line 236 of file Pane.hpp.
Referenced by connectivities(), and elements().
   { es = _cnct_set; }
void Pane::connectivities (std::vector< const Connectivity * > & es) const inline
Definition at line 239 of file Pane.hpp.
References connectivities().
   { const_cast<Pane*>(this)->connectivities
       ( (std::vector<Connectivity*> &)es); }
Connectivity * Pane::connectivity (Size i) throw (COM_exception)
Definition at line 82 of file Pane.C.
References COM_assertion, COM_assertion_msg, Connectivity::index_offset(), and Connectivity::size_of_elements().
Referenced by connectivity(), ComponentInterface::copy_array(), ComponentInterface::get_array(), ComponentInterface::get_parent(), ComponentInterface::get_size(), ComponentInterface::get_status(), Element_node_enumerator::next(), Element_node_enumerator_uns::next(), and ComponentInterface::set_size().
 {
   if ( i>size_of_elements()) {
     // if i is not a valid element ID, it must be one past the last ID
     COM_assertion( i-1==size_of_elements());
     return NULL;
   }
   // i must be either a valid element ID
   COM_assertion_msg( i>=1, "ElementID out of bounds");
   Cnct_set::iterator it=_cnct_set.begin();
   for ( ; it != _cnct_set.end(); ++it) {
     Connectivity *c=*it;
     if ( i>c->index_offset() && i<=c->index_offset()+c->size_of_elements())
       return c;
   }
   return NULL;
 }
const Connectivity* Pane::connectivity (Size i) const throw (COM_exception) inline
Definition at line 245 of file Pane.hpp.
References connectivity().
   { return const_cast<Pane*>(this)->connectivity( i); }
const Connectivity* Pane::connectivity (const std::string & a) const throw (COM_exception) inline protected
Definition at line 274 of file Pane.hpp.
References connectivity().
   { return const_cast<Pane*>(this)->connectivity( a); }
Connectivity * Pane::connectivity (const std::string & a, bool insert = false) throw (COM_exception) protected
Definition at line 103 of file Pane.C.
References append_frame, COM_ERR_INVALID_DATAITEM_NAME, COM_ERR_PANE_NOTEXIST, connectivity(), and Connectivity::get_size_info().
 {
   if ( _id == 0) {
     throw COM_exception( COM_ERR_PANE_NOTEXIST, append_frame
                          (_window->name()+"."+a, Pane::connectivity));
   }
   Cnct_set::iterator it=_cnct_set.begin();
   for ( ; it != _cnct_set.end(); ++it) {
     if ( a==(*it)->name()) return *it;
   }
   if ( insert) {
     const int *size_info=Connectivity::get_size_info(a);
     if ( size_info) {
       Connectivity *c = new Connectivity(this, a, -1-int(_cnct_set.size()),
                                          size_info);
       _cnct_set.push_back( c);
       return _cnct_set.back();
     }
     else
       throw COM_exception( COM_ERR_INVALID_DATAITEM_NAME, append_frame
                            (_window->name()+"."+a, Pane::connectivity));
   }
   return NULL;
 }
double* Pane::coordinates () inline
It returns NULL if the coordinates are staggered.
Definition at line 149 of file Pane.hpp.
References _attr_set, and COM_NC.
 { return (double *)_attr_set[COM_NC]->pointer(); }
const double* Pane::coordinates () const inline
Definition at line 161 of file Pane.hpp.
References _attr_set, and COM_NC.
   { return (const double *)_attr_set[COM_NC]->pointer(); }
DataItem * Pane::dataitem (const std::string & a)
Definition at line 131 of file Pane.C.
References _window, ComponentInterface::dataitem(), and DataItem::id().
Referenced by ComponentInterface::ComponentInterface(), ComponentInterface::copy_array(), dataitem(), ComponentInterface::dataitem(), ComponentInterface::get_array(), ComponentInterface::get_parent(), ComponentInterface::get_size(), ComponentInterface::get_status(), ComponentInterface::inherit(), inherit(), DataItem::maxsize_of_ghost_items(), DataItem::maxsize_of_items(), DataItem::maxsize_of_real_items(), RFC_Pane_base::read_rocin(), Pane_connectivity::size_of_cpanes(), DataItem::size_of_ghost_items(), DataItem::size_of_items(), DataItem::size_of_real_items(), DataItem::size_set(), and write_attr_CGNS().
{
   DataItem *w_attr = _window->dataitem(a);
   if ( w_attr==NULL) return NULL;
   return dataitem( w_attr->id());
 }
const DataItem* Pane::dataitem (const std::string & a) const inline
Definition at line 221 of file Pane.hpp.
References dataitem().
   { return const_cast<Pane*>(this)->dataitem(a); }
DataItem * Pane::dataitem (int i)
Definition at line 139 of file Pane.C.
References _attr_set, and DataItem::id().
                  {
   if ( (int)_attr_set.size() <= i) return NULL;
   DataItem *p_attr = _attr_set[ i];
   if ( p_attr==NULL || p_attr->id () != i) return NULL;
   return p_attr;
 }
const DataItem* Pane::dataitem (int i) const inline
Definition at line 228 of file Pane.hpp.
References dataitem().
   { return const_cast<Pane*>(this)->dataitem(i); }
void Pane::dataitems (std::vector< DataItem * > & as)
Definition at line 148 of file Pane.C.
References _attr_set, COM_NUM_KEYWORDS, DataItem::pane(), and DataItem::size_of_components().
Referenced by dataitems(), ComponentInterface::dataitems(), and write_attr_CGNS().
{
   as.reserve( _attr_set.size()-COM_NUM_KEYWORDS);
   for ( int i=COM_NUM_KEYWORDS, size=_attr_set.size(); i<size; ++i) {
     DataItem *a = _attr_set[i];
     if ( a==NULL || a->pane()==NULL) continue;
     as.push_back( a);
     int ncomp = a->size_of_components();
     if ( ncomp>1) i+=ncomp;
   }
 }
void Pane::dataitems (std::vector< const DataItem * > & as) const inline
Definition at line 215 of file Pane.hpp.
References dataitems().
   { const_cast<Pane*>(this)->dataitems((std::vector<DataItem*>&)as); }
void Pane::delete_dataitem (int id) throw (COM_exception) protected
Definition at line 223 of file Pane.C.
References COM_assertion, COM_DATA, COM_NUM_KEYWORDS, DataItem::pane(), and DataItem::size_of_components().
Referenced by ComponentInterface::delete_dataitem(), and ~Pane().
{
   if ( id == COM_DATA) { // Delete all user-defined dataitems.
     for ( Size i=COM_NUM_KEYWORDS,n=_attr_set.size(); i<n; ++i) {
       DataItem *a=_attr_set[i];
       if ( a==NULL || a->pane()==NULL) continue;
       int ncomp = a->size_of_components();
       delete [] a; // Delete dataitem and its individual components
       if (ncomp>1) i+=ncomp;
     }
     _attr_set.resize( COM_NUM_KEYWORDS);
   }
   else {
     DataItem *a = _attr_set[id]; COM_assertion(a);
     int ncomp = a->size_of_components();
     delete [] a; // Delete the dataitem and its components.
     // Reset its pointers in _attr_set.
     for ( int i=id+((ncomp>1)?ncomp:0); i>=id; --i) _attr_set[i] = NULL;
     if ( id+ncomp+(ncomp>1) ==int(_attr_set.size()))
       _attr_set.resize( id);
   }
 }
int Pane::dimension () const inline
Definition at line 81 of file Pane.hpp.
References _cnct_set.
Referenced by Pane_node_enumerator::dimension(), Element_node_enumerator::dimension(), Element_node_enumerator::Element_node_enumerator(), Pane_node_enumerator::next(), Element_node_enumerator::next(), Pane_node_enumerator::Pane_node_enumerator(), Element_node_enumerator::size_of_corners(), Element_node_enumerator::size_of_edges(), Element_node_enumerator::size_of_faces(), Element_node_enumerator::size_of_nodes(), Element_node_enumerator::type(), and write_attr_CGNS().
   { return _cnct_set.empty()?0:_cnct_set[0]->dimension(); }
void Pane::elements (std::vector< Connectivity * > & es) inline
Kept for backward compatibility
Definition at line 250 of file Pane.hpp.
References connectivities().
Referenced by write_attr_CGNS().
 { connectivities(es); }
void Pane::elements (std::vector< const Connectivity * > & es) const inline
Definition at line 251 of file Pane.hpp.
References connectivities().
   { connectivities(es); }
int Pane::id () const inline
Definition at line 78 of file Pane.hpp.
References _id.
Referenced by Rocblas::gen2arg(), ComponentInterface::inherit(), ComponentInterface::reinit_conn(), ComponentInterface::reinit_dataitem(), Element_node_vectors_k_const< Value >::set(), Element_vectors_k_const< Value >::set(), and write_attr_CGNS().
 { return _id; }
bool Pane::ignore_ghost () const inline
Definition at line 184 of file Pane.hpp.
References _ignore_ghost.
Referenced by DataItem::maxsize_of_ghost_items(), DataItem::maxsize_of_items(), Connectivity::size_of_elements(), DataItem::size_of_ghost_items(), DataItem::size_of_items(), and Connectivity::size_of_nodes().
 { return _ignore_ghost; }
DataItem * Pane::inherit (DataItem * from, const std::string & aname, int mode, bool withghost) throw (COM_exception) protected
Definition at line 434 of file Pane.C.
References append_frame, CATCHBADALLOC_APPEND, CATCHEXP_APPEND, COM_ALL, COM_assertion, COM_assertion_msg, COM_CONN, COM_DATA, COM_ERR_DATAITEM_NOTEXIST, COM_ERR_GHOST_LAYERS, COM_ERR_INCOMPATIBLE_TYPES, COM_MESH, COM_NC, COM_NUM_KEYWORDS, COM_PCONN, COM_PMESH, COM_RIDGES, DataItem::compatible_types(), DataItem::copy_array(), DataItem::data_type(), dataitem(), DataItem::fullname(), DataItem::id(), DataItem::inherit(), DataItem::is_windowed(), DataItem::location(), DataItem::pane(), DataItem::pointer(), Connectivity::pointer(), DataItem::size_of_components(), DataItem::size_of_items(), DataItem::size_of_real_items(), and DataItem::stride().
Referenced by ComponentInterface::inherit().
 {
   if ( from==NULL)
     throw COM_exception( COM_ERR_DATAITEM_NOTEXIST, append_frame
                          (_window->name()+"."+aname,Pane::inherit));
   switch (from->id()) { // Process keywords
   case COM_ALL:
     inherit( from->pane()->dataitem( COM_PMESH), "", mode, withghost);
     inherit( from->pane()->dataitem( COM_DATA), "", mode, withghost);
     return dataitem( COM_ALL);
   case COM_MESH:
     inherit( from->pane()->dataitem( COM_NC), "", mode, withghost);
     inherit( from->pane()->dataitem( COM_CONN), "", mode, withghost);
     inherit( from->pane()->dataitem( COM_RIDGES), "", mode, withghost);
     return dataitem( COM_MESH);
   case COM_PMESH:
     inherit( from->pane()->dataitem( COM_NC), "", mode, withghost);
     inherit( from->pane()->dataitem( COM_CONN), "", mode, withghost);
     inherit( from->pane()->dataitem( COM_RIDGES), "", mode, withghost);
     inherit( from->pane()->dataitem( COM_PCONN), "", mode, withghost);
     return dataitem( COM_PMESH);
   case COM_DATA: {
     // Loop through all dataitems
     std::vector<DataItem*> &atts=from->pane()->_attr_set;
     for ( int i=COM_NUM_KEYWORDS,n=atts.size(); i<n; ++i) {
       DataItem *a = atts[i];
       if ( a==NULL || a->pane()==NULL) continue;
       if ( !a->is_windowed() || _id==0)
         inherit( a, "", mode, withghost);
       int ncomp= a->size_of_components();
       if ( ncomp>1) i+= ncomp;
     }
     return dataitem( COM_DATA);
   }
   case COM_CONN: {
     if ( _id==0) return dataitem(COM_CONN);
     if (mode != INHERIT_COPY) {
       // Clean up the current connectivity tables
       for ( Size i=0; i<_cnct_set.size(); ++i) delete _cnct_set[i];
       _cnct_set.clear();
       if ( mode==INHERIT_USE) {
         ((DataItem_friend*)_attr_set[COM_CONN])->inherit( from, false, withghost);
         // Check that if structured meshes, the nodal coordinates
         // was also used.
         COM_assertion( !is_structured() || _attr_set[COM_NC]->parent() &&
                        _attr_set[COM_NC]->parent()->pane() == from->pane());
       }
       // Inherit individual connectivity tables
       std::vector<Connectivity*>::iterator it=from->pane()->_cnct_set.begin();
       std::vector<Connectivity*>::iterator iend=from->pane()->_cnct_set.end();
       for ( ; it != iend; ++it) {
         _cnct_set.push_back( new Connectivity( this, *it, (*it)->name(),
                                                -_cnct_set.size()-1));
         ((Connectivity_friend*)_cnct_set.back())->inherit(*it, mode, withghost);
       }
       // Set _ignore_ghost
       _ignore_ghost = !withghost;
       if ( _ignore_ghost && is_structured() && size_of_ghost_layers())
         throw COM_exception(COM_ERR_GHOST_LAYERS, append_frame
                             (_window->name()+"."+aname,Pane::inherit));
       if ( mode == INHERIT_USE) return dataitem( COM_DATA);
     }
     // Continue to copy mode
     // Do not copy connectivity tables for structured meshes.
     const std::vector<Connectivity*> &es = from->pane()->_cnct_set;
     COM_assertion_msg( es.size() == _cnct_set.size(),
                        "Number of connectivity tables do not match");
     // Loop over the connectivity tables to copy each table
     for ( int i=0, ni=_cnct_set.size(); i<ni; ++i) {
       const Connectivity *conn=es[i];
       int n=withghost?conn->size_of_items():conn->size_of_real_items();
       _cnct_set[i]->copy_array( const_cast<int*>(conn->pointer()),
                                 conn->stride(), n);
     }
     refresh_connectivity();
     return dataitem( COM_DATA);
   }
   default: ;
   }
   std::string str = aname.size()?aname:from->name();
   // If from is a keyword and target is the same, then the current
   // dataitem must have the same ID. Otherwise, must find from name.
   DataItem *a=(from->id()<COM_NUM_KEYWORDS && aname.empty())?
     dataitem(from->id()) : _window->dataitem(str);
   if ( mode != INHERIT_COPY) {
     if ( _id == 0) {
       if ( a==NULL || a->size_of_components()!=from->size_of_components()) {
         // New dataitem only if it does not exist or the sizes do not match
         try {
           a=_window->new_dataitem( str, from->location(), from->data_type(),
                                     from->size_of_components(), from->unit());
           if ( from->is_windowed())
             ((DataItem_friend*)a)->inherit( from, mode, withghost);
         } CATCHEXP_APPEND(Pane::inherit);
       }
       else try {
         ((DataItem_friend*)a)->inherit( from, mode, withghost);
       } CATCHEXP_APPEND(Pane::inherit) CATCHBADALLOC_APPEND(Pane::inherit);
       if ( mode == INHERIT_USE || !from->is_windowed()) return a;
     }
     else {
       COM_assertion( a);
       a = _attr_set[a->id()];
       try {
         ((DataItem_friend*)a)->inherit( from, mode, withghost);
       } CATCHEXP_APPEND(Pane::inherit) CATCHBADALLOC_APPEND(Pane::inherit);
       if ( mode == INHERIT_USE) return a;
     }
   }
   else {
     // Copy an dataitem only if it exists in the target window.
     if ( a) a = _attr_set[a->id()];
     else return a;
     if ( !DataItem::compatible_types( from->data_type(), a->data_type()))
       throw COM_exception( COM_ERR_INCOMPATIBLE_TYPES, append_frame
                            (from->fullname()+" and "+a->fullname(),
                             Pane::inherit));
   }
   if ( (_id==0) != (from->is_windowed())) return a;
   // Continue to copy dataset
   if ( !withghost && is_structured() && size_of_ghost_layers())
     throw COM_exception(COM_ERR_GHOST_LAYERS, append_frame
                         (_window->name()+"."+aname,Pane::inherit));
   // count is the number of panes, nodes, or elements to loop through
   int count = withghost?from->size_of_items():from->size_of_real_items();
   int s_nc = from->size_of_components();
   const Pane *src_pane = from->pane();
   COM_assertion_msg( from->location() == a->location(),
                      (std::string("Location of dataitems ")+
                       from->fullname()+" and " +a->fullname()+
                       " do not match during copying.").c_str());
   // loop through components of source's data
   if ( count) for ( int j=(s_nc>1), nj=s_nc-(s_nc==1); j<=nj; ++j) {
     // src_data points to source data for current component
     const DataItem *src_data = src_pane->dataitem( from->id()+j);
     // dest_data points to dest data for current component
     DataItem *dest_data = dataitem( a->id()+j);
     if ( dest_data->pointer() && src_data->pointer()) {
       COM_assertion_msg( withghost && dest_data->size_of_items()==src_data->size_of_items() ||
                          !withghost && dest_data->size_of_real_items()==src_data->size_of_real_items(),
                          (std::string("Number of items of dataitems ")+
                           from->fullname()+" and " +a->fullname()+
                           " do not match during copying.").c_str());
       try {
         dest_data->copy_array( const_cast<void*>(src_data->pointer()),
                                src_data->stride(), count);
       } CATCHEXP_APPEND(Pane::inherit);
     }
   }
   return a;
 }
void Pane::init_done () throw (COM_exception)
Definition at line 68 of file Pane.C.
References _attr_set, _window, append_frame, DataItem::capacity(), COM_ERR_INVALID_CAPACITY, DataItem::fullname(), DataItem::initialized(), ComponentInterface::last_dataitem_id(), DataItem::pane(), s, and DataItem::size_of_items().
{
   _attr_set.resize( _window->last_dataitem_id()); // Shrink the array.
   // Loop through the dataitems to initialize the unitialized ones to NULL
   for ( int i=0, s=_attr_set.size(); i<s; ++i) {
     DataItem *a = _attr_set[i];
     if ( a==NULL || a->pane()==NULL) continue;
     if ( a->initialized() && a->size_of_items()>a->capacity())
       throw COM_exception( COM_ERR_INVALID_CAPACITY,
                            append_frame(a->fullname(), Pane::init_done));
   }
 }
void Pane::insert (DataItem * attr) throw (COM_exception) protected
Definition at line 207 of file Pane.C.
References COM_assertion, and s.
{
   COM_assertion( attr->pane()==this);
   // Determine id of the new dataitem
   int id = attr->id();
   // Resize _attr_set and delete existing dataitem with the id
   if ( int(_attr_set.size())<=id) { // resize _attr_set
     int s = attr->size_of_components();
     _attr_set.resize( id+s+(s>1), NULL);
   }
   if ( _attr_set[id]==NULL) _attr_set[id] = attr;
   else COM_assertion( attr == _attr_set[id]);
 }
bool Pane::is_mixed () const inline
Definition at line 89 of file Pane.hpp.
References _cnct_set.
 { return _cnct_set.size()>1; }
bool Pane::is_structured () const inline
Definition at line 92 of file Pane.hpp.
References _cnct_set.
Referenced by Element_node_enumerator::Element_node_enumerator(), Element_node_enumerator::id(), refresh_connectivity(), size_i(), size_j(), size_k(), Element_node_enumerator::vertex(), and write_attr_CGNS().
   { return _cnct_set.size()==1 && _cnct_set[0]->is_structured(); }
bool Pane::is_unstructured () const inline
Definition at line 85 of file Pane.hpp.
References _cnct_set.
Referenced by Element_node_enumerator::Element_node_enumerator(), Pane_node_enumerator::next(), Pane_node_enumerator::Pane_node_enumerator(), and write_attr_CGNS().
   { return _cnct_set.size()!=1 || !_cnct_set[0]->is_structured(); }
Size Pane::maxsize_of_elements () const inline
Definition at line 128 of file Pane.hpp.
References _attr_set, and COM_CONN.
   { return _attr_set[COM_CONN]->maxsize_of_items(); }
Size Pane::maxsize_of_ghost_elements () const inline
Definition at line 136 of file Pane.hpp.
References _attr_set, and COM_CONN.
   { return _attr_set[COM_CONN]->maxsize_of_ghost_items(); }
Size Pane::maxsize_of_ghost_nodes () const inline
Definition at line 112 of file Pane.hpp.
References _attr_set, and COM_NC.
   { return _attr_set[COM_NC]->maxsize_of_ghost_items(); }
Size Pane::maxsize_of_nodes () const inline
Definition at line 104 of file Pane.hpp.
References _attr_set, and COM_NC.
   { return _attr_set[COM_NC]->maxsize_of_items(); }
Size Pane::maxsize_of_real_elements () const inline
Definition at line 144 of file Pane.hpp.
References _attr_set, and COM_CONN.
   { return _attr_set[COM_CONN]->maxsize_of_real_items(); }
Size Pane::maxsize_of_real_nodes () const inline
Definition at line 120 of file Pane.hpp.
References _attr_set, and COM_NC.
   { return _attr_set[COM_NC]->maxsize_of_real_items(); }
DataItem * Pane::new_dataitem (const std::string & aname, int aid, const char loc, const int type, int ncomp, const std::string & unit) throw (COM_exception) protected
Definition at line 161 of file Pane.C.
References append_frame, COM_assertion, COM_ERR_INVALID_DATAITEM_NAME, and DataItem::name().
Referenced by ComponentInterface::new_dataitem().
 {
   if ( loc == 'c' && id() != 0) {
     // check if connectivity table exists, make sure it is not dummy pane
     std::string::size_type pos = aname.find( ":");
     std::string conn = aname.substr(pos, aname.size());
     Connectivity *con = connectivity( conn,false);
     if (con == NULL)
       throw COM_exception( COM_ERR_INVALID_DATAITEM_NAME,
                          append_frame(aname, Pane::new_dataitem));
   }
   // Insert the object into both the set and the map.
   DataItem *atts;
   if ( aid>=int(_attr_set.size()))
     atts = new DataItem[ncomp+(ncomp>1)]; // Allocate memory
   else {
     atts = dataitem(aid); COM_assertion( atts);
     // Call destructors
     for ( int i=0, n=ncomp+(ncomp>1); i<n; ++i) atts[i].~DataItem();
   }
   DataItem *a = new (atts) DataItem( this, aname, aid, loc,
                                        type, ncomp, unit);
   insert( a);
   // Create an object for each individual component
   if ( ncomp>1) for ( int i=1; i<=ncomp; ++i) {
     char buf[10];
     std::sprintf( buf, "%d-", i);
     std::string newname = std::string( buf)+a->name();
     DataItem *ai = new (&atts[i]) DataItem( this, newname, aid+i,
                                               loc,  type, 1, unit);
     insert( ai);
   }
   if ( _id && loc == 'w') { // Inherit window dataitem
     reinterpret_cast<DataItem_friend*>(a)->
       inherit( _window->dataitem( aid), INHERIT_USE, true);
   }
   return a;
 }
Pane& Pane::operator= (const Pane &) private
int* Pane::pane_connectivity () inline
Definition at line 177 of file Pane.hpp.
References _attr_set, and COM_PCONN.
   { return (int*)_attr_set[COM_PCONN]->pointer(); }
const int* Pane::pane_connectivity () const inline
Definition at line 181 of file Pane.hpp.
References _attr_set, and COM_PCONN.
   { return (const int *)_attr_set[COM_PCONN]->pointer(); }
void Pane::refresh_connectivity () throw (COM_exception)
Definition at line 650 of file Pane.C.
References _attr_set, _cnct_set, _window, append_frame, COM_CONN, COM_ERR_INVALID_SIZE, COM_NC, is_structured(), ComponentInterface::name(), Connectivity::set_offset(), Connectivity::size_of_elements(), Connectivity::size_of_ghost_elements(), size_of_ghost_nodes(), and size_of_nodes().
{
   int nelems = 0, ngelems = 0;
   // Set the number of elements
   if ( !_attr_set[COM_CONN]->parent()) {
     // Loop through the connectivity table
     Cnct_set::iterator it=_cnct_set.begin();
     for ( ; it != _cnct_set.end(); ++it) {
       Connectivity_friend *con = (Connectivity_friend*)*it;
       con->set_offset( nelems);
       nelems += con->size_of_elements();
       ngelems += con->size_of_ghost_elements();
     }
     if ( nelems<0 || ngelems<0)
       throw COM_exception( COM_ERR_INVALID_SIZE, append_frame
                            ( _window->name(), Pane::refresh_connectivity));
     _attr_set[COM_CONN]->set_size(nelems, ngelems);
   }
   // Set the number of nodes for structured meshes
   if ( is_structured() && !_attr_set[COM_NC]->parent()) {
     _attr_set[COM_NC]->set_size(_cnct_set[0]->size_of_nodes(),
                                 _cnct_set[0]->size_of_ghost_nodes());
   }
 }
void Pane::reinit_conn (Connectivity * con, OP_Init op, int ** addr, int strd, int cap) throw (COM_exception) protected
Definition at line 383 of file Pane.C.
References addr, append_frame, cap, COM_ERR_ALLOC_STRUCTURED, COM_ERR_PANE_NOTEXIST, and strd.
 {
   // Assign default value for cap and strd
   if ( op!=OP_DEALLOC) {
     if ( cap==0) {
       // Default value for capacity is the number of items for set_array
       // but the large of the current capacity and the the number of items plus some buffer.
       if ( op==OP_SET || op==OP_SET_CONST) cap = con->size_of_items();
       else {
         if ( con->capacity()==0)
           cap = con->size_of_items();
         else if ( con->size_of_items()<=con->capacity())
           cap = con->capacity();
         else
           cap = con->size_of_items()+con->size_of_items()/5;  // Current size pluse 20% more
       }
     }
     if ( strd==0 || strd<0 && con->stride()==0)
       // Default value for stride is number of components
       strd = con->size_of_components();
     else if ( strd<0)
       strd = con->stride();
   }
   if ( op == OP_SET || op == OP_SET_CONST) {
     if ( !id())
       throw COM_exception( COM_ERR_PANE_NOTEXIST,
                            append_frame(con->fullname(),Pane::reinit_conn));
     if ( *addr && cap==0 && !con->is_structured())
       *addr = NULL; // Enforce the array to be a NULL pointer
     ((Connectivity_friend*)con)->set_pointer( *addr, strd, cap,
                                               op==OP_SET_CONST);
   }
   else {
     if ( con->is_structured())
       throw COM_exception( COM_ERR_ALLOC_STRUCTURED,
                            append_frame(con->fullname(),Pane::reinit_conn));
     void *p=NULL;
     if ( op==OP_DEALLOC)
     { con->deallocate(); p=NULL; }
     else
       p = con->allocate( strd, cap, op==OP_ALLOC);
     if ( addr) *addr = (int*)p;
   }
 }
void Pane::reinit_dataitem (int aid, OP_Init op, void ** addr, int strd, int cap) throw (COM_exception) protected
Definition at line 248 of file Pane.C.
References addr, DataItem::allocate(), append_frame, cap, DataItem::capacity(), COM_ALL, COM_assertion, COM_CONN, COM_DATA, COM_ERR_DATAITEM_NOTEXIST, COM_ERR_INVALID_SIZE, COM_ERR_PANE_NOTEXIST, COM_ERR_WAS_INITIALIZED, COM_MESH, COM_NC, COM_NUM_KEYWORDS, COM_PCONN, COM_PMESH, COM_RIDGES, DataItem::deallocate(), DataItem::fullname(), DataItem::is_digit(), DataItem::is_windowed(), DataItem::name(), DataItem::pane(), DataItem::set_size(), DataItem::size_of_components(), DataItem::size_of_items(), DataItem::size_set(), strd, and DataItem::stride().
Referenced by ComponentInterface::reinit_dataitem().
 {
   switch ( aid) {
   case COM_CONN: {
     COM_assertion( op != OP_SET && op != OP_SET_CONST);
     // loop through the connectivity
     for ( int i=0, n=_cnct_set.size(); i<n; ++i) {
       if ( !_cnct_set[i]->is_structured())
         reinit_conn( _cnct_set[i], op, NULL, strd, cap);
     }
     if ( addr) *addr = NULL;
     return;
   }
   case COM_MESH: {
     COM_assertion( op != OP_SET && op != OP_SET_CONST);
     reinit_dataitem( COM_NC, op, NULL, strd, cap);
     reinit_dataitem( COM_CONN, op, NULL, strd, cap);
     reinit_dataitem( COM_RIDGES, op, NULL, strd, cap);
     if ( addr) *addr = NULL;
     return;
   }
   case COM_PMESH: {
     COM_assertion( op != OP_SET && op != OP_SET_CONST);
     reinit_dataitem( COM_NC, op, NULL, strd, cap);
     reinit_dataitem( COM_CONN, op, NULL, strd, cap);
     reinit_dataitem( COM_RIDGES, op, NULL, strd, cap);
     reinit_dataitem( COM_PCONN, op, NULL, strd, cap);
     if ( addr) *addr = NULL;
     return;
   }
   case COM_DATA: {
     COM_assertion( op != OP_SET && op != OP_SET_CONST);
     // Loop through the dataitems
     for ( int i=COM_NUM_KEYWORDS, n=_attr_set.size(); i<n; ++i) {
       DataItem *a = _attr_set[i];
       if ( a==NULL || a->pane()==NULL) continue;
       if ( !a->is_windowed() || _id==0)
         reinit_dataitem( i, op, NULL, strd, cap);
       int ncomp= a->size_of_components();
       if ( ncomp>1) i+= ncomp;
     }
     return;
   }
   case COM_ALL: {
     COM_assertion( op != OP_SET && op != OP_SET_CONST);
     reinit_dataitem( COM_PMESH, op, NULL, strd, cap);
     reinit_dataitem( COM_DATA, op, NULL, strd, cap);
     return;
   }
   default: ;
   }
   DataItem *a = dataitem( aid);
   if ( a==NULL)
     throw COM_exception( COM_ERR_DATAITEM_NOTEXIST,
                          append_frame(a->fullname(), Pane::reinit_dataitem));
   // If _id is 0, then handle only window dataitems.
   if ( !a->is_windowed() && !_id) {
     if (op == OP_SET || op == OP_SET_CONST)
       throw COM_exception( COM_ERR_PANE_NOTEXIST, append_frame
                            ( _window->name(), Pane::reinit_dataitem));
     else
       return;
   }
   int errcode;
   void *p;
   int ncomp = a->size_of_components();
   if ( op==OP_DEALLOC) {
     // Deallocate if was allocated by Roccom
     errcode = a->deallocate();
     p = NULL;
   }
   else {
     COM_assertion( op==OP_SET_CONST||op==OP_SET||op==OP_ALLOC||op==OP_RESIZE);
     // If size is not yet set
     if ( !a->size_set()) {
       if ( a->is_windowed())
         a->set_size(1);  // Change the default size of window dataitems to 1
       else // Throw an exception for other types of dataitems
         throw COM_exception( COM_ERR_INVALID_SIZE,
                              append_frame(a->fullname(), Pane::reinit_dataitem));
     }
     // Assign default value for cap and strd
     if ( cap==0) {
       // Default value for capacity is the number of items for set_array
       // but the large of the current capacity and the the number of items.
       if ( op==OP_SET || op==OP_SET_CONST) cap = a->size_of_items();
       else {
         if ( a->capacity()==0)
           cap = a->size_of_items();
         else if ( a->size_of_items()<=a->capacity())
           cap = a->capacity();
         else
           cap = a->size_of_items()+a->size_of_items()/5;  // Current size pluse 20% more
       }
     }
     if ( (op == OP_SET || op == OP_SET_CONST) && *addr && cap==0)
       *addr = NULL; // Enforce the array to be a NULL pointer
     // Make the dataitem itself set to NULL if operating on its components.
     if ( DataItem::is_digit(a->name()[0])) {
       int icomp=std::atoi( a->name().c_str());
       if ( dataitem(aid-icomp)->initialized())
         throw COM_exception(COM_ERR_WAS_INITIALIZED,
                             append_frame(a->fullname(), Pane::reinit_dataitem));
     }
     if ( strd==0 || strd<0 && a->stride()==0)
       // Default value for stride is number of components
       strd = ncomp;
     else if ( strd<0)
       strd = a->stride();
     if ( op == OP_SET || op == OP_SET_CONST) {
       ((DataItem_friend*)a)->set_pointer(*addr, strd, cap,
                                           0, op==OP_SET_CONST);
       p = *addr;
     }
     else {
       p = a->allocate( strd, cap, op == OP_ALLOC);
       if ( addr) *addr = p;
     }
     errcode=0;
   }
 }
void Pane::set_ignore_ghost (bool ignore) inline
Definition at line 186 of file Pane.hpp.
References _ignore_ghost.
 { _ignore_ghost = ignore; }
void Pane::set_size (DataItem * a, int nitems, int ng) throw (COM_exception) protected
Definition at line 613 of file Pane.C.
References append_frame, COM_assertion_msg, COM_CONN, COM_ERR_INVALID_SIZE, COM_ERR_PANE_NOTEXIST, and COM_NC.
Referenced by ComponentInterface::set_size(), and set_size().
{
   if ( nitems<ng)
     throw COM_exception( COM_ERR_INVALID_SIZE,
                          append_frame(a->fullname(),Pane::set_size));
   // Get the corresponding dataitem object.
   if ( !a->is_windowed() && !_id)
     throw COM_exception(COM_ERR_PANE_NOTEXIST,
                         append_frame(a->fullname(),Pane::set_size));
   if ( a->is_nodal()) {
     COM_assertion_msg( a->id() == COM_NC,
                        (std::string("Cannot set size for nodal dataitem ")+
                         a->fullname()+". Must use the nc dataitem").c_str());
     _attr_set[COM_NC]->set_size( nitems, ng);
   }
   else if ( a->is_elemental()) {
     COM_assertion_msg( a->id() == COM_CONN,
                        (std::string("Cannot set size for elemental dataitem ")+
                         a->fullname()+". Must use the conn dataitem").c_str());
     _attr_set[COM_CONN]->set_size( nitems, ng);
   }
   else {
     dataitem(a->id())->set_size( nitems, ng);
   }
 }
void Pane::set_size (Connectivity * con, int nitems, int ng) throw (COM_exception) protected
Definition at line 642 of file Pane.C.
References append_frame, COM_ERR_INVALID_SIZE, and set_size().
{
   if ( !con->is_structured() && nitems<ng)
     throw COM_exception( COM_ERR_INVALID_SIZE,
                          append_frame(con->fullname(),Pane::set_size));
   con->set_size( nitems, ng);
 }
Size Pane::size_i () const inline
Definition at line 198 of file Pane.hpp.
References _cnct_set, and is_structured().
Referenced by Element_node_enumerator::Element_node_enumerator(), Element_node_enumerator::id(), Element_node_enumerator::next(), Element_node_enumerator_str_2::next(), Element_node_enumerator::operator[](), Element_node_enumerator_str_2::operator[](), Pane_node_enumerator::Pane_node_enumerator(), Element_node_enumerator::vertex(), and write_attr_CGNS().
   { return !is_structured()?0:_cnct_set[0]->size_i(); }
Size Pane::size_j () const inline
Definition at line 201 of file Pane.hpp.
References _cnct_set, and is_structured().
Referenced by Element_node_enumerator::Element_node_enumerator(), Pane_node_enumerator::Pane_node_enumerator(), Element_node_enumerator::vertex(), and write_attr_CGNS().
   { return !is_structured()?0:_cnct_set[0]->size_j(); }
Size Pane::size_k () const inline
Definition at line 204 of file Pane.hpp.
References _cnct_set, and is_structured().
Referenced by Pane_node_enumerator::Pane_node_enumerator(), and write_attr_CGNS().
   { return !is_structured()?0:_cnct_set[0]->size_k(); }
Size Pane::size_of_elements () const inline
Definition at line 124 of file Pane.hpp.
References _attr_set, and COM_CONN.
Referenced by Element_node_enumerator::Element_node_enumerator().
   { return _attr_set[COM_CONN]->size_of_items(); }
Size Pane::size_of_ghost_elements () const inline
Definition at line 132 of file Pane.hpp.
References _attr_set, and COM_CONN.
   { return _attr_set[COM_CONN]->size_of_ghost_items(); }
Size Pane::size_of_ghost_layers () const inline
Get the number of ghost layers for structured mesh
Definition at line 194 of file Pane.hpp.
Referenced by Pane_node_enumerator::Pane_node_enumerator(), and write_attr_CGNS().
   { return _cnct_set.empty()?0:_cnct_set[0]->size_of_ghost_items(); }
Size Pane::size_of_ghost_nodes () const inline
Definition at line 108 of file Pane.hpp.
References _attr_set, and COM_NC.
Referenced by refresh_connectivity(), Connectivity::size_of_ghost_nodes(), and write_attr_CGNS().
   { return _attr_set[COM_NC]->size_of_ghost_items(); }
Size Pane::size_of_nodes () const inline
Definition at line 100 of file Pane.hpp.
Referenced by Pane_node_enumerator::Pane_node_enumerator(), refresh_connectivity(), Connectivity::size_of_nodes(), and write_attr_CGNS().
   { return _attr_set[COM_NC]->size_of_items(); }
Size Pane::size_of_real_elements () const inline
Definition at line 140 of file Pane.hpp.
References _attr_set, and COM_CONN.
Referenced by write_attr_CGNS().
   { return _attr_set[COM_CONN]->size_of_real_items(); }
Size Pane::size_of_real_nodes () const inline
Definition at line 116 of file Pane.hpp.
References _attr_set, and COM_NC.
Referenced by Connectivity::size_of_real_nodes(), and write_attr_CGNS().
   { return _attr_set[COM_NC]->size_of_real_items(); }
const ComponentInterface* Pane::window () const inline
Definition at line 73 of file Pane.hpp.
Referenced by DataItem::window().
 { return _window; }
ComponentInterface* Pane::window () inline
Definition at line 75 of file Pane.hpp.
References _window.
 { return _window; }
double* Pane::x_coordinates () inline
Definition at line 152 of file Pane.hpp.
References _attr_set, and COM_NC1.
 { return (double *)_attr_set[COM_NC1]->pointer(); }
const double* Pane::x_coordinates () const inline
Definition at line 165 of file Pane.hpp.
References _attr_set, and COM_NC1.
   { return (const double *)_attr_set[COM_NC1]->pointer(); }
double* Pane::y_coordinates () inline
Definition at line 155 of file Pane.hpp.
References _attr_set, and COM_NC2.
 { return (double *)_attr_set[COM_NC2]->pointer(); }
const double* Pane::y_coordinates () const inline
Definition at line 169 of file Pane.hpp.
References _attr_set, and COM_NC2.
   { return (const double *)_attr_set[COM_NC2]->pointer(); }
double* Pane::z_coordinates () inline
Definition at line 158 of file Pane.hpp.
References _attr_set, and COM_NC3.
 { return (double *)_attr_set[COM_NC3]->pointer(); }
const double* Pane::z_coordinates () const inline
Definition at line 173 of file Pane.hpp.
References _attr_set, and COM_NC3.
   { return (const double *)_attr_set[COM_NC3]->pointer(); }
Member Data Documentation
DataGroup Pane::_attr_set protected
Definition at line 297 of file Pane.hpp.
Referenced by coordinates(), dataitem(), dataitems(), init_done(), maxsize_of_elements(), maxsize_of_ghost_elements(), maxsize_of_ghost_nodes(), maxsize_of_nodes(), maxsize_of_real_elements(), maxsize_of_real_nodes(), Pane(), pane_connectivity(), refresh_connectivity(), size_of_elements(), size_of_ghost_elements(), size_of_ghost_nodes(), size_of_real_elements(), size_of_real_nodes(), x_coordinates(), y_coordinates(), z_coordinates(), and ~Pane().
Cnct_set Pane::_cnct_set protected
Definition at line 298 of file Pane.hpp.
Referenced by dimension(), is_mixed(), is_structured(), is_unstructured(), refresh_connectivity(), size_i(), size_j(), size_k(), and ~Pane().
int Pane::_id protected
Definition at line 296 of file Pane.hpp.
Referenced by id().
bool Pane::_ignore_ghost protected
Definition at line 299 of file Pane.hpp.
Referenced by ignore_ghost(), and set_ignore_ghost().
ComponentInterface* Pane::_window protected
Definition at line 295 of file Pane.hpp.
Referenced by dataitem(), init_done(), refresh_connectivity(), and window().
The documentation for this class was generated from the following files:
Pane.hpp
Pane.C