IMPACT: IRAD::Util::Parameters Class Reference
IRAD::Util::Parameters Class Reference
Detailed Description
Definition at line 19 of file Parameters.H.
#include <Parameters.H>
Public Member Functions
std::string GetValue (const std::string &key) const
std::vector< std::string > GetValueVector (const std::string &key) const
Util::ParamType * ParamPtr (const std::string &key)
template<typename T >
T GetValue (const std::string &key) const
template<typename T >
std::vector< T > GetValueVector (const std::string &key) const
virtual int SetValue (const std::string &key, const std::string &value)
virtual std::istream & ReadFromStream (std::istream &Is)
virtual std::ostream & WriteToStream (std::ostream &Os) const
std::string Param (const std::string &Key) const
bool IsSet (const std::string &Key) const
virtual ~Parameters ()
Friends
std::ostream & operator<< (std::ostream &oSt, const Util::Parameters &pv)
std::istream & operator>> (std::istream &iSt, Util::Parameters &pv)
Additional Inherited Members
Public Attributes inherited from std::vector< T >
T elements
STL member.
Constructor & Destructor Documentation
virtual IRAD::Util::Parameters::~Parameters () inline virtual
Definition at line 69 of file Parameters.H.
 {};
Member Function Documentation
std::string IRAD::Util::Parameters::GetValue (const std::string & key) const
Definition at line 24 of file Parameters.C.
     {
       std::string retval;
       std::string value(this->Param(key));
       if(!value.empty()){
         std::istringstream Istr(value);
         Istr >> retval;
       }
       return(retval);
     }
template<typename T > T IRAD::Util::Parameters::GetValue (const std::string & key) const inline
Definition at line 33 of file Parameters.H.
References Param().
       {
         T retval;
         std::string value(this->Param(key));
         if(!value.empty()){
           std::istringstream Istr(value);
           Istr >> retval;
         }
         return(retval);
       };
std::vector< std::string > IRAD::Util::Parameters::GetValueVector (const std::string & key) const
Definition at line 35 of file Parameters.C.
     {
       std::vector<std::string> retval;
       std::string value(this->Param(key));
       if(!value.empty()){
         std::istringstream Istr(value);
         std::string tmpval;
         while(Istr >> tmpval)
           retval.push_back(tmpval);
       }
       return(retval);
     }
template<typename T > std::vector<T> IRAD::Util::Parameters::GetValueVector (const std::string & key) const inline
Definition at line 45 of file Parameters.H.
References Param().
       {
         std::vector<T> retval;
         std::string value(this->Param(key));
         if(!value.empty()){
           std::istringstream Istr(value);
           T tmpval;
           while(Istr >> tmpval)
             retval.push_back(tmpval);
         }
         return(retval);
       };
bool IRAD::Util::Parameters::IsSet (const std::string & Key) const
Definition at line 93 of file Parameters.C.
     {
       return(!Param(key).empty());
     };
std::string IRAD::Util::Parameters::Param (const std::string & Key) const
Definition at line 81 of file Parameters.C.
Referenced by GetValue(), and GetValueVector().
     {
       std::string empty;
       Util::Parameters::const_iterator pi = this->begin();
       while(pi != this->end()){
         if(pi->first == key)
           return(pi->second);
         pi++;
       }
       return(empty);
     }
Util::ParamType * IRAD::Util::Parameters::ParamPtr (const std::string & key)
Definition at line 12 of file Parameters.C.
Referenced by SetValue().
     {
       Util::Parameters::const_iterator pi = this->begin();
       while(pi != this->end()){
         unsigned int index = pi - this->begin();
         if(pi->first == key)
           return(&((*this)[index]));
         pi++;
       }
       return(NULL);
     }
std::istream & IRAD::Util::Parameters::ReadFromStream (std::istream & Is) virtual
Definition at line 48 of file Parameters.C.
References IRAD::Primitive::KeyValuePairObj< K, V >::Key(), SolverUtils::Ostr, IRAD::Util::TokenizeString(), and IRAD::Primitive::KeyValuePairObj< K, V >::Value().
Referenced by IRAD::Util::operator>>().
     {
       std::string line;
       int n = 0;
       while(Is){
         std::getline(Is,line);
         n++;
         // Removes any leading whitespace
         std::string::size_type x = line.find('#');
         line = line.substr(0,x);
         if(!line.empty()){
           x = line.find('=');
           if(x == std::string::npos)
             return(Is);
           Util::ParamType param;
           std::istringstream Instr(line.substr(0,x));
           Instr >> param.Key();
           std::vector<std::string> tokens;
           line = line.substr(x+1,line.size());
           TokenizeString(tokens,line);
           std::ostringstream Ostr;
           std::vector<std::string>::iterator ti = tokens.begin();
           if(ti != tokens.end())
             Ostr << *ti++;
           while(ti != tokens.end())
             Ostr << " " << *ti++;
           param.Value() = Ostr.str();
           this->push_back(param);
         }
       }
       return(Is);
     }
virtual int IRAD::Util::Parameters::SetValue (const std::string & key, const std::string & value) inline virtual
Definition at line 57 of file Parameters.H.
References ParamPtr(), and IRAD::Primitive::KeyValuePairObj< K, V >::Value().
{
         if(ParamPtr(key)){
           ParamPtr(key)->Value(value);
           return(0);
         }
         return(1);
       };
std::ostream & IRAD::Util::Parameters::WriteToStream (std::ostream & Os) const virtual
Definition at line 99 of file Parameters.C.
Referenced by IRAD::Util::operator<<().
     {
       Util::Parameters::const_iterator pi = this->begin();
       while(pi != this->end()){
         oSt << *pi++;
         if(pi != this->end())
           oSt << std::endl;
       }
       return(oSt);
     };
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & oSt, const Util::Parameters & pv) friend
std::istream& operator>> (std::istream & iSt, Util::Parameters & pv) friend
The documentation for this class was generated from the following files:
Parameters.H
Parameters.C