IMPACT: Point_set Class Reference
Point_set Class Reference
Detailed Description
Definition at line 60 of file Overlay_primitives.h.
#include <Overlay_primitives.h>
Public Types
typedef Point_set Self
typedef Point_3 Value
typedef unsigned int Size
Public Member Functions
Point_set (const HEdge &h)
Point_set (const HEdge &h, Size)
const Point_3 & operator[] (Size i) const
Size size_of_edges () const
Size size_of_nodes () const
Protected Attributes
Vertex_set vs
Member Typedef Documentation
typedef Point_set Point_set::Self
Definition at line 62 of file Overlay_primitives.h.
typedef unsigned int Point_set::Size
Definition at line 64 of file Overlay_primitives.h.
typedef Point_3 Point_set::Value
Definition at line 63 of file Overlay_primitives.h.
Constructor & Destructor Documentation
Point_set::Point_set (const HEdge & h) inline explicit
Definition at line 66 of file Overlay_primitives.h.
 : vs(h) {}
Point_set::Point_set (const HEdge & h, Size) inline
Definition at line 67 of file Overlay_primitives.h.
 : vs(h,0) {}
Member Function Documentation
const Point_3& Point_set::operator[] (Size i) const inline
Definition at line 69 of file Overlay_primitives.h.
References RFC_Pane_overlay::get_point(), Vertex_set::pane(), and vs.
 { return vs.pane()->get_point(vs[i]); }
Size Point_set::size_of_edges () const inline
Definition at line 70 of file Overlay_primitives.h.
References Vertex_set::size_of_edges(), and vs.
Referenced by Overlay_primitives::get_face_normal(), Overlay_primitives::get_point(), Overlay_primitives::get_tangent(), and Overlay_primitives::project_onto_element().
 { return vs.size_of_edges(); }
Size Point_set::size_of_nodes () const inline
Definition at line 71 of file Overlay_primitives.h.
References Vertex_set::size_of_nodes(), and vs.
 { return vs.size_of_nodes(); }
Member Data Documentation
Vertex_set Point_set::vs protected
Definition at line 74 of file Overlay_primitives.h.
Referenced by operator[](), size_of_edges(), and size_of_nodes().
The documentation for this class was generated from the following file:
Overlay_primitives.h