IMPACT: DeformationVelTransfer_SF Class Reference
DeformationVelTransfer_SF Class Reference
Detailed Description
Definition at line 119 of file transfer_actions.h.
#include <transfer_actions.h>
Public Member Functions
DeformationVelTransfer_SF (FluidAgent *fag, SolidAgent *sag, const std::string s_vs, const std::string f_vs)
void init (double t)
void run (double t, double dt, double alpha)
Public Member Functions inherited from InterMeshTransfer
InterMeshTransfer (FluidAgent *fag, SolidAgent *sag, char *name=NULL)
Public Member Functions inherited from Action
Action (void *p=0, const char *name=NULL)
Action (int n, const char **at, int *i=NULL, void *p=0, const char *name=NULL)
Action (int n, const std::string at[], int *i=NULL, void *p=0, const char *name=NULL)
virtual ~Action ()
virtual void declare (Scheduler &)
virtual void finalize ()
virtual const char * name ()
void set_name (const char *name)
virtual void print (FILE *f)
virtual void print_toposort (FILE *f)
virtual void schedule ()
Private Attributes
std::string s_vs_str
std::string f_vs_str
int s_vs_hdl
int f_vs_hdl
int RFC_transfer
Additional Inherited Members
Protected Types inherited from Action
enum { IN =1, OUT =2, INOUT =3 }
Protected Member Functions inherited from InterMeshTransfer
void load_rocface (const RocmanControl_parameters *param)
Protected Member Functions inherited from Action
int get_dataitem_handle (int i)
int get_dataitem_handle_const (int i)
int get_dataitem_handle (const std::string str)
void set_attr (int n, const std::string at[], int *id=NULL)
void set_attr (int n, const char *at[], int *id=NULL)
void set_io (int n, const int *io)
void set_io (const char *io)
int get_io (int i)
Protected Attributes inherited from InterMeshTransfer
FluidAgent * fagent
SolidAgent * sagent
Protected Attributes inherited from Action
const char * action_name
char ** attr
int * idx
int count
void * usr_ptr
std::vector< int > inout
Constructor & Destructor Documentation
DeformationVelTransfer_SF::DeformationVelTransfer_SF (FluidAgent * fag, SolidAgent * sag, const std::string s_vs, const std::string f_vs) explicit
Definition at line 680 of file transfer_actions.C.
References InterMeshTransfer::fagent, FluidAgent::ifluid_i, Action::IN, Action::OUT, Action::set_attr(), and Action::set_io().
                                                                          :
              InterMeshTransfer(fag, sag, "DeformationVelTransfer_SF"),
              s_vs_str(s_vs), f_vs_str(f_vs)
 {
   // added a builtin in (ifluid_i+".vm")
   // ifluid_i+".vm" (in),  isolid_i+".vs", ifluid_i+".vs"
   int io[] = {IN, IN, OUT};
   set_io( 3, io);
   std::string.data[3];
  .data[0] = fagent->ifluid_i+".vm";
  .data[1] = s_vs;
  .data[2] = f_vs;
   set_attr(3,.data);
 }
Member Function Documentation
void DeformationVelTransfer_SF::init (double t) virtual
Reimplemented from Action.
Definition at line 697 of file transfer_actions.C.
References COM_get_function_handle(), f_vs_hdl, InterMeshTransfer::fagent, Agent::get_coupling(), Action::get_dataitem_handle(), Coupling::get_rocmancontrol_param(), InterMeshTransfer::load_rocface(), RFC_transfer, and s_vs_hdl.
{
   s_vs_hdl = get_dataitem_handle(1);
   f_vs_hdl = get_dataitem_handle(2);
   load_rocface(fagent->get_coupling()->get_rocmancontrol_param());
   RFC_transfer = COM_get_function_handle("RFC.least_squares_transfer");
 }
void DeformationVelTransfer_SF::run (double t, double dt, double alpha) virtual
Reimplemented from Action.
Definition at line 706 of file transfer_actions.C.
References COM_call_function(), f_vs_hdl, MAN_DEBUG, RFC_transfer, and s_vs_hdl.
{
   MAN_DEBUG(2, ("Rocman: DeformationVelTransfer_SF::run() with t:%e dt:%e alpha:%e.\n", t, dt, alpha));
     // c. Transfer vs from solid nodes to fluid faces using SurfX
   COM_call_function( RFC_transfer, &s_vs_hdl, &f_vs_hdl);
 }
Member Data Documentation
int DeformationVelTransfer_SF::f_vs_hdl private
Definition at line 126 of file transfer_actions.h.
Referenced by init(), and run().
std::string DeformationVelTransfer_SF::f_vs_str private
Definition at line 125 of file transfer_actions.h.
int DeformationVelTransfer_SF::RFC_transfer private
Definition at line 127 of file transfer_actions.h.
Referenced by init(), and run().
int DeformationVelTransfer_SF::s_vs_hdl private
Definition at line 126 of file transfer_actions.h.
Referenced by init(), and run().
std::string DeformationVelTransfer_SF::s_vs_str private
Definition at line 125 of file transfer_actions.h.
The documentation for this class was generated from the following files:
transfer_actions.h
transfer_actions.C