IMPACT: SolverUtils::GeoPrim::C3Box Class Reference
SolverUtils::GeoPrim::C3Box Class Reference
Detailed Description
Definition at line 1780 of file GeoPrimitives.H.
#include <GeoPrimitives.H>
Public Member Functions
C3Box ()
C3Box (const std::vector< C3Point > &pv)
C3Box (const double *points, unsigned int n)
C3Box (const C3Point &ip1, const C3Point &ip2)
C3Box (double x0, double y0, double z0, double x1, double y1, double z1)
C3Box (const C3Box &box)
const C3Point & P1 () const
const C3Point & P2 () const
C3Point & P1 ()
C3Point & P2 ()
bool empty () const
void init (const double *points, unsigned int n)
void init (double x0, double y0, double z0, double x1, double y1, double z1)
C3Box & operator= (const C3Box &b)
C3Box around (const C3Point &p) const
bool operator== (const C3Box &b) const
C3Point & min ()
const C3Point & min () const
C3Point & max ()
const C3Point & max () const
bool contains (const C3Point &p) const
bool contains (const double *p) const
double size () const
bool operator< (const C3Box &b) const
bool operator> (const C3Box &b) const
void AddPoint (const C3Point &p)
void merge (const C3Box &b)
bool collide (const C3Box &b) const
C3Box intersect (const C3Box &b) const
Protected Attributes
C3Point p1
C3Point p2
Private Attributes
bool initd
Friends
std::ostream & operator<< (std::ostream &, const C3Box &)
std::istream & operator>> (std::istream &, C3Box &)
Constructor & Destructor Documentation
SolverUtils::GeoPrim::C3Box::C3Box () inline
Definition at line 1789 of file GeoPrimitives.H.
             : initd(false), p1(), p2()
     {};
SolverUtils::GeoPrim::C3Box::C3Box (const std::vector< C3Point > & pv) inline
Definition at line 1791 of file GeoPrimitives.H.
References initd, p1, p2, SolverUtils::GeoPrim::C3Point::x(), SolverUtils::GeoPrim::C3Point::y(), and SolverUtils::GeoPrim::C3Point::z().
     {
       std::vector<C3Point>::const_iterator pvi = pv.begin();
       p1.x(pvi->x());
       p2.x(p1.x());
       p1.y(pvi->y());
       p2.y(p1.y());
       p1.z(pvi->z());
       p2.z(p1.z());
       pvi++;
       while(pvi != pv.end()){
         if(pvi->x() < p1.x()) p1.x(pvi->x());
         if(pvi->x() > p2.x()) p2.x(pvi->x());
         if(pvi->y() < p1.y()) p1.y(pvi->y());
         if(pvi->y() > p2.y()) p2.y(pvi->y());
         if(pvi->z() < p1.z()) p1.z(pvi->z());
         if(pvi->z() > p2.z()) p2.z(pvi->z());
         pvi++;
       }
       initd = true;
     }
SolverUtils::GeoPrim::C3Box::C3Box (const double * points, unsigned int n) inline
Definition at line 1812 of file GeoPrimitives.H.
References initd, p1, p2, SolverUtils::GeoPrim::C3Point::x(), SolverUtils::GeoPrim::C3Point::y(), and SolverUtils::GeoPrim::C3Point::z().
     {
       p1.x(points[0]);
       p1.y(points[1]);
       p1.z(points[2]);
       p2 = p1;
       for(unsigned int i = 1;i<n;i++){
         if(points[i*3] < p1.x()) p1.x(points[i*3]);
         if(points[i*3] > p2.x()) p2.x(points[i*3]);
         if(points[(i*3)+1] < p1.y()) p1.y(points[(i*3)+1]);
         if(points[(i*3)+1] > p2.y()) p2.y(points[(i*3)+1]);
         if(points[(i*3)+2] < p1.z()) p1.z(points[(i*3)+2]);
         if(points[(i*3)+2] > p2.z()) p2.z(points[(i*3)+2]);
       }
       initd = true;
     };
SolverUtils::GeoPrim::C3Box::C3Box (const C3Point & ip1, const C3Point & ip2) inline
Definition at line 1828 of file GeoPrimitives.H.
References initd.
       : p1(ip1),p2(ip2)
     {initd = true;};
SolverUtils::GeoPrim::C3Box::C3Box (double x0, double y0, double z0, double x1, double y1, double z1) inline
Definition at line 1831 of file GeoPrimitives.H.
References initd.
       : p1(x0,y0,z0),p2(x1,y1,z1)
     {initd = true;};
SolverUtils::GeoPrim::C3Box::C3Box (const C3Box & box) inline
Definition at line 1834 of file GeoPrimitives.H.
References initd.
       : p1(box.p1),p2(box.p2)
     {initd = true;};
Member Function Documentation
void SolverUtils::GeoPrim::C3Box::AddPoint (const C3Point & p) inline
Definition at line 1939 of file GeoPrimitives.H.
References initd, p1, p2, SolverUtils::GeoPrim::C3Point::x(), SolverUtils::GeoPrim::C3Point::y(), and SolverUtils::GeoPrim::C3Point::z().
     {
       if(!initd){
         p1 = p;
         p2 = p;
         initd = true;
       }
       else{
         if(p.x() < p1.x()) p1.x() = p.x();
         if(p.x() > p2.x()) p2.x() = p.x();
         if(p.y() < p1.y()) p1.y() = p.y();
         if(p.y() > p2.y()) p2.y() = p.y();
         if(p.z() < p1.z()) p1.z() = p.z();
         if(p.z() > p2.z()) p2.z() = p.z();
       }
     };
C3Box SolverUtils::GeoPrim::C3Box::around (const C3Point & p) const inline
Definition at line 1877 of file GeoPrimitives.H.
References p1, p2, SolverUtils::GeoPrim::C3Point::x(), SolverUtils::GeoPrim::C3Vector::x(), SolverUtils::GeoPrim::C3Point::y(), SolverUtils::GeoPrim::C3Vector::y(), SolverUtils::GeoPrim::C3Point::z(), and SolverUtils::GeoPrim::C3Vector::z().
     {
       C3Vector v(p1,p2);
       C3Point minp(p.x()-fabs(v.x()/2.0),
                 p.y()-fabs(v.y()/2.0),
                   p.z()-fabs(v.z()/2.0));
       C3Point maxp(p.x()+fabs(v.x()/2.0),
                   p.y()+fabs(v.y()/2.0),
                   p.z()+fabs(v.z()/2.0));
       C3Box box(minp,maxp);
       return(box);
     };
bool SolverUtils::GeoPrim::C3Box::collide (const C3Box & b) const inline
Definition at line 1973 of file GeoPrimitives.H.
References empty(), p1, p2, SolverUtils::GeoPrim::C3Point::x(), SolverUtils::GeoPrim::C3Point::y(), and SolverUtils::GeoPrim::C3Point::z().
Referenced by intersect().
     {
       if(this->empty() || b.empty())
         return(false);
       return(!(b.p2.x() < p1.x() || b.p1.x() > p2.x()) &&
              !(b.p2.y() < p1.y() || b.p1.y() > p2.y()) &&
              !(b.p2.z() < p1.z() || b.p1.z() > p2.z()));
     };
bool SolverUtils::GeoPrim::C3Box::contains (const C3Point & p) const inline
Definition at line 1913 of file GeoPrimitives.H.
References p1, p2, SolverUtils::GeoPrim::C3Point::x(), SolverUtils::GeoPrim::C3Point::y(), and SolverUtils::GeoPrim::C3Point::z().
     {
     return( p.x() <= p2.x() && p.x() >= p1.x() &&
             p.y() <= p2.y() && p.y() >= p1.y() &&
             p.z() <= p2.z() && p.z() >= p1.z() );
     };
bool SolverUtils::GeoPrim::C3Box::contains (const double * p) const inline
Definition at line 1919 of file GeoPrimitives.H.
References p1, p2, SolverUtils::GeoPrim::C3Point::x(), SolverUtils::GeoPrim::C3Point::y(), and SolverUtils::GeoPrim::C3Point::z().
     {
       return( p[0] <= p2.x() && p[0] >= p1.x() &&
               p[1] <= p2.y() && p[1] >= p1.y() &&
               p[2] <= p2.z() && p[2] >= p1.z() );
     };
bool SolverUtils::GeoPrim::C3Box::empty () const inline
Definition at line 1841 of file GeoPrimitives.H.
References p1, p2, SolverUtils::GeoPrim::TOL, SolverUtils::GeoPrim::C3Point::x(), SolverUtils::GeoPrim::C3Point::y(), and SolverUtils::GeoPrim::C3Point::z().
Referenced by collide().
                        {return ((std::fabs(p2.x()-p1.x()) < TOL) ||
                                 (std::fabs(p2.y()-p1.y()) < TOL) ||
                                 (std::fabs(p2.z()-p1.z()) < TOL));};
void SolverUtils::GeoPrim::C3Box::init (const double * points, unsigned int n) inline
Definition at line 1844 of file GeoPrimitives.H.
References initd, p1, p2, SolverUtils::GeoPrim::C3Point::x(), SolverUtils::GeoPrim::C3Point::y(), and SolverUtils::GeoPrim::C3Point::z().
     {
       initd = true;
       p1.x(points[0]);
       p1.y(points[1]);
       p1.z(points[2]);
       p2 = p1;
       for(unsigned int i = 1;i<n;i++){
         if(points[i*3] < p1.x()) p1.x(points[i*3]);
         if(points[i*3] > p2.x()) p2.x(points[i*3]);
         if(points[(i*3)+1] < p1.y()) p1.y(points[(i*3)+1]);
         if(points[(i*3)+1] > p2.y()) p2.y(points[(i*3)+1]);
         if(points[(i*3)+2] < p1.z()) p1.z(points[(i*3)+2]);
         if(points[(i*3)+2] > p2.z()) p2.z(points[(i*3)+2]);
       }
     };
void SolverUtils::GeoPrim::C3Box::init (double x0, double y0, double z0, double x1, double y1, double z1) inline
Definition at line 1860 of file GeoPrimitives.H.
References initd, p1, p2, SolverUtils::GeoPrim::C3Point::x(), SolverUtils::GeoPrim::C3Point::y(), and SolverUtils::GeoPrim::C3Point::z().
     {
       initd = true;
       p1.x(x0);
       p1.y(y0);
       p1.z(z0);
       p2.x(x1);
       p2.y(y1);
       p2.z(z1);
     };
C3Box SolverUtils::GeoPrim::C3Box::intersect (const C3Box & b) const inline
Definition at line 1981 of file GeoPrimitives.H.
References collide(), p1, p2, SolverUtils::GeoPrim::C3Point::x(), SolverUtils::GeoPrim::C3Point::y(), and SolverUtils::GeoPrim::C3Point::z().
     {
       C3Box retval;
       if(collide(b)){
         retval.p1.x(b.p1.x() > p1.x() ? b.p1.x() : p1.x());
         retval.p1.y(b.p1.y() > p1.y() ? b.p1.y() : p1.y());
         retval.p1.z(b.p1.z() > p1.z() ? b.p1.z() : p1.z());
         retval.p2.x(b.p2.x() < p2.x() ? b.p2.x() : p2.x());
         retval.p2.y(b.p2.y() < p2.y() ? b.p2.y() : p2.y());
         retval.p2.z(b.p2.z() < p2.z() ? b.p2.z() : p2.z());
       }
       return(retval);
     };
C3Point& SolverUtils::GeoPrim::C3Box::max () inline
Definition at line 1905 of file GeoPrimitives.H.
References p2.
     {
       return(p2);
     };
const C3Point& SolverUtils::GeoPrim::C3Box::max () const inline
Definition at line 1909 of file GeoPrimitives.H.
References p2.
     {
       return(p2);
     };
void SolverUtils::GeoPrim::C3Box::merge (const C3Box & b) inline
Definition at line 1955 of file GeoPrimitives.H.
References initd, p1, p2, SolverUtils::GeoPrim::C3Point::x(), SolverUtils::GeoPrim::C3Point::y(), and SolverUtils::GeoPrim::C3Point::z().
     {
       if(initd){
         C3Point p(p1);
         p1.x((b.p1.x() > p1.x() ? p.x() : b.p1.x()));
         p1.y((b.p1.y() > p1.y() ? p.y() : b.p1.y()));
         p1.z((b.p1.z() > p1.z() ? p.z() : b.p1.z()));
         p = p2;
         p2.x(b.p2.x() < p2.x() ? p.x() : b.p2.x());
         p2.y(b.p2.y() < p2.y() ? p.y() : b.p2.y());
         p2.z(b.p2.z() < p2.z() ? p.z() : b.p2.z());
       }
       else {
         p1 = b.p1;
         p2 = b.p2;
         initd = true;
       }
     };
C3Point& SolverUtils::GeoPrim::C3Box::min () inline
Definition at line 1897 of file GeoPrimitives.H.
References p1.
     {
     return(p1);
     };
const C3Point& SolverUtils::GeoPrim::C3Box::min () const inline
Definition at line 1901 of file GeoPrimitives.H.
References p1.
     {
       return(p1);
     };
bool SolverUtils::GeoPrim::C3Box::operator< (const C3Box & b) const inline
Definition at line 1931 of file GeoPrimitives.H.
References size().
     {
       return(this->size() < b.size());
     };
C3Box& SolverUtils::GeoPrim::C3Box::operator= (const C3Box & b) inline
Definition at line 1870 of file GeoPrimitives.H.
References initd, p1, and p2.
     {
       p1 = b.p1;
       p2 = b.p2;
       initd = true;
       return(*this);
     };
bool SolverUtils::GeoPrim::C3Box::operator== (const C3Box & b) const inline
Definition at line 1889 of file GeoPrimitives.H.
References p1, and p2.
     {
       return(p1 == b.p1 && p2 == b.p2);
     };
bool SolverUtils::GeoPrim::C3Box::operator> (const C3Box & b) const inline
Definition at line 1935 of file GeoPrimitives.H.
References size().
     {
       return(this->size() > b.size());
     };
const C3Point& SolverUtils::GeoPrim::C3Box::P1 () const inline
Definition at line 1837 of file GeoPrimitives.H.
References p1.
Referenced by SolverUtils::GeoPrim::operator<<(), and SolverUtils::GeoPrim::operator>>().
 {return p1;};
C3Point& SolverUtils::GeoPrim::C3Box::P1 () inline
Definition at line 1839 of file GeoPrimitives.H.
References p1.
 {return p1;};
const C3Point& SolverUtils::GeoPrim::C3Box::P2 () const inline
Definition at line 1838 of file GeoPrimitives.H.
References p2.
Referenced by SolverUtils::GeoPrim::operator<<(), and SolverUtils::GeoPrim::operator>>().
 {return p2;};
C3Point& SolverUtils::GeoPrim::C3Box::P2 () inline
Definition at line 1840 of file GeoPrimitives.H.
References p2.
 {return p2;};
double SolverUtils::GeoPrim::C3Box::size () const inline
Definition at line 1926 of file GeoPrimitives.H.
References p1, p2, SolverUtils::GeoPrim::C3Vector::x(), SolverUtils::GeoPrim::C3Vector::y(), and SolverUtils::GeoPrim::C3Vector::z().
Referenced by operator<(), and operator>().
     {
       C3Vector v(p1,p2);
       return(fabs(v.x()*v.y()*v.z()));
     };
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & oS, const C3Box & b) friend
Definition at line 75 of file GeoPrimitives.C.
   {
     oS << b.P1() << "  " << b.P2();
     return(oS);
   }
std::istream& operator>> (std::istream & iS, GeoPrim::C3Box & b) friend
Definition at line 82 of file GeoPrimitives.C.
   {
     iS >> b.P1() >> b.P2();
     return(iS);
   }
Member Data Documentation
bool SolverUtils::GeoPrim::C3Box::initd private
Definition at line 1784 of file GeoPrimitives.H.
Referenced by AddPoint(), C3Box(), init(), merge(), and operator=().
C3Point SolverUtils::GeoPrim::C3Box::p1 protected
Definition at line 1786 of file GeoPrimitives.H.
Referenced by AddPoint(), around(), C3Box(), collide(), contains(), empty(), init(), intersect(), merge(), min(), operator=(), operator==(), P1(), and size().
C3Point SolverUtils::GeoPrim::C3Box::p2 protected
Definition at line 1787 of file GeoPrimitives.H.
Referenced by AddPoint(), around(), C3Box(), collide(), contains(), empty(), init(), intersect(), max(), merge(), operator=(), operator==(), P2(), and size().
The documentation for this class was generated from the following file:
GeoPrimitives.H