IMPACT: Reset_du_alp Class Reference
Reset_du_alp Class Reference
Detailed Description
Definition at line 287 of file basic_actions.h.
#include <basic_actions.h>
Public Member Functions
Reset_du_alp (FluidAgent *fag)
void init (double t)
void run (double t, double dt, double alpha)
Public Member Functions inherited from Action
Action (void *p=0, const char *name=NULL)
Action (int n, const char **at, int *i=NULL, void *p=0, const char *name=NULL)
Action (int n, const std::string at[], int *i=NULL, void *p=0, const char *name=NULL)
virtual ~Action ()
virtual void declare (Scheduler &)
virtual void finalize ()
virtual const char * name ()
void set_name (const char *name)
virtual void print (FILE *f)
virtual void print_toposort (FILE *f)
virtual void schedule ()
Private Attributes
FluidAgent * fagent
int du_alp_hdl
Additional Inherited Members
Protected Types inherited from Action
enum { IN =1, OUT =2, INOUT =3 }
Protected Member Functions inherited from Action
int get_dataitem_handle (int i)
int get_dataitem_handle_const (int i)
int get_dataitem_handle (const std::string str)
void set_attr (int n, const std::string at[], int *id=NULL)
void set_attr (int n, const char *at[], int *id=NULL)
void set_io (int n, const int *io)
void set_io (const char *io)
int get_io (int i)
Protected Attributes inherited from Action
const char * action_name
char ** attr
int * idx
int count
void * usr_ptr
std::vector< int > inout
Constructor & Destructor Documentation
Reset_du_alp::Reset_du_alp (FluidAgent * fag)
Definition at line 999 of file basic_actions.C.
References Action::set_attr(), and Action::set_io().
                                            :
   Action( 0, (const char**)NULL, NULL, NULL, "Reset_du_alp"), fagent(fag)
 {
   // Define I/O of the arguments.
   set_io( 0, NULL);
   set_attr(0, (const char**)NULL);
 }
Member Function Documentation
void Reset_du_alp::init (double t) virtual
Reimplemented from Action.
Definition at line 1008 of file basic_actions.C.
References COM_get_dataitem_handle(), du_alp_hdl, fagent, and Agent::get_surface_window().
{
   du_alp_hdl = COM_get_dataitem_handle( fagent->get_surface_window()+".du_alp");
 }
void Reset_du_alp::run (double t, double dt, double alpha) virtual
Reimplemented from Action.
Definition at line 1012 of file basic_actions.C.
References COM_call_function(), RocBlas::copy_scalar, du_alp_hdl, and MAN_DEBUG.
{
   MAN_DEBUG(2, ("Rocman: Reset_du_alp::run().\n"));
   double zero = 0.0;
   COM_call_function( RocBlas::copy_scalar, &zero, &du_alp_hdl);
 }
Member Data Documentation
int Reset_du_alp::du_alp_hdl private
Definition at line 294 of file basic_actions.h.
Referenced by init(), and run().
FluidAgent* Reset_du_alp::fagent private
Definition at line 293 of file basic_actions.h.
Referenced by init().
The documentation for this class was generated from the following files:
basic_actions.h
basic_actions.C