IMPACT: RFC_Data_const< _Tag > Class Template Reference
RFC_Data_const< _Tag > Class Template Reference
Detailed Description
template<class _Tag>
class RFC_Data_const< _Tag >
Definition at line 25 of file RFC_Window_transfer.h.
#include <RFC_Window_transfer.h>
Public Types
typedef Vector_n Value
typedef Array_n Value_nonconst
typedef Array_n_const Value_const
typedef unsigned int Size
typedef _Tag Tag
Public Member Functions
RFC_Data_const ()
RFC_Data_const (const RFC_Window_transfer &win, const char *aname)
RFC_Data_const (const COM::DataItem *a)
RFC_Data_const (int i, int d)
int id () const
Size dimension () const
bool is_valid (const RFC_Pane_transfer *p, int i) const
Value_const get_value (const RFC_Pane_transfer *p, int v) const
Value_const get_value (const Real *buf, int v) const
Tag tag () const
Protected Attributes
int _id
unsigned int _dim
Member Typedef Documentation
template<class _Tag > typedef unsigned int RFC_Data_const< _Tag >::Size
Definition at line 224 of file RFC_Window_transfer.h.
template<class _Tag > typedef _Tag RFC_Data_const< _Tag >::Tag
Definition at line 225 of file RFC_Window_transfer.h.
template<class _Tag > typedef Vector_n RFC_Data_const< _Tag >::Value
Definition at line 221 of file RFC_Window_transfer.h.
template<class _Tag > typedef Array_n_const RFC_Data_const< _Tag >::Value_const
Definition at line 223 of file RFC_Window_transfer.h.
template<class _Tag > typedef Array_n RFC_Data_const< _Tag >::Value_nonconst
Definition at line 222 of file RFC_Window_transfer.h.
Constructor & Destructor Documentation
template<class _Tag > RFC_Data_const< _Tag >::RFC_Data_const () inline
Definition at line 227 of file RFC_Window_transfer.h.
 : _id(0), _dim(0) {}
template<class _Tag > RFC_Data_const< _Tag >::RFC_Data_const (const RFC_Window_transfer & win, const char * aname) inline
Definition at line 228 of file RFC_Window_transfer.h.
References RFC_Data_const< _Tag >::_dim, RFC_Data_const< _Tag >::_id, and RFC_Window_base::dataitem().
{
     const COM::DataItem *a = win.dataitem( aname);
     _id = a->id(); _dim = a->size_of_components();
   }
template<class _Tag > RFC_Data_const< _Tag >::RFC_Data_const (const COM::DataItem * a) inline
Definition at line 232 of file RFC_Window_transfer.h.
     : _id(a->id()), _dim(a->size_of_components()) {}
template<class _Tag > RFC_Data_const< _Tag >::RFC_Data_const (int i, int d) inline
Definition at line 234 of file RFC_Window_transfer.h.
     : _id( i), _dim(d) {}
Member Function Documentation
template<class _Tag > Size RFC_Data_const< _Tag >::dimension () const inline
Definition at line 238 of file RFC_Window_transfer.h.
References RFC_Data_const< _Tag >::_dim.
Referenced by Transfer_base::compute_load_vector_wra(), RFC_Window_transfer::init_facial_buffers(), Transfer_base::init_load_vector(), RFC_Window_transfer::init_nodal_buffers(), Transfer_base::integrate(), Transfer_base::interpolate_fe(), Transfer_base::minmax(), Transfer_base::multiply_mass_mat_and_x(), RFC_Window_transfer::reduce_maxabs_to_all(), RFC_Window_transfer::reduce_to_all(), RFC_Window_transfer::replicate_data(), and Transfer_base::transfer_2f().
 { return _dim; }
template<class _Tag > Value_const RFC_Data_const< _Tag >::get_value (const RFC_Pane_transfer * p, int v) const inline
Definition at line 243 of file RFC_Window_transfer.h.
References RFC_Data_const< _Tag >::_dim, RFC_Data_const< _Tag >::_id, RFC_Pane_transfer::pointer(), and RFC_assertion.
Referenced by Transfer_base::copy_vec(), Transfer_base::dot(), Transfer_base::dot2(), Transfer_base::make_field(), Transfer_base::minmax(), Transfer_base::norm2(), Transfer_base::precondition_Jacobi(), and Transfer_base::saxpy().
{
     RFC_assertion( v>=1);
     return Value_const( p->pointer( _id) + (v-1)*_dim, _dim);
   }
template<class _Tag > Value_const RFC_Data_const< _Tag >::get_value (const Real * buf, int v) const inline
Definition at line 248 of file RFC_Window_transfer.h.
References RFC_Data_const< _Tag >::_dim, and RFC_assertion.
{
     RFC_assertion( v>=1);
     return Value_const( buf + (v-1)*_dim, _dim);
   }
template<class _Tag > int RFC_Data_const< _Tag >::id () const inline
Definition at line 237 of file RFC_Window_transfer.h.
References RFC_Data_const< _Tag >::_id.
Referenced by Transfer_base::copy_vec(), Transfer_base::dot(), Transfer_base::dot2(), Transfer_base::init_load_vector(), Transfer_base::interpolate_fe(), Transfer_base::invert(), Transfer_base::make_field(), Transfer_base::minmax(), Transfer_base::multiply_mass_mat_and_x(), Transfer_base::norm2(), Transfer_base::precondition_Jacobi(), RFC_Window_transfer::reduce_maxabs_to_all(), RFC_Window_transfer::reduce_to_all(), RFC_Window_transfer::replicate_data(), Transfer_base::saxpy(), Transfer_base::scale(), and Transfer_base::transfer_2f().
 { return _id; }
template<class _Tag > bool RFC_Data_const< _Tag >::is_valid (const RFC_Pane_transfer * p, int i) const inline
Definition at line 239 of file RFC_Window_transfer.h.
   { return true; }
template<class _Tag > Tag RFC_Data_const< _Tag >::tag () const inline
Definition at line 253 of file RFC_Window_transfer.h.
 { return Tag(); }
Member Data Documentation
template<class _Tag > unsigned int RFC_Data_const< _Tag >::_dim protected
Definition at line 256 of file RFC_Window_transfer.h.
Referenced by RFC_Data_const< _Tag >::dimension(), RFC_Data_const< _Tag >::get_value(), RFC_Data< _Tag >::get_value(), RFC_Data_const< _Tag >::RFC_Data_const(), and RFC_Data< _Tag >::set_value().
template<class _Tag > int RFC_Data_const< _Tag >::_id protected
Definition at line 255 of file RFC_Window_transfer.h.
Referenced by RFC_Data_const< _Tag >::get_value(), RFC_Data< _Tag >::get_value(), RFC_Data_const< _Tag >::id(), RFC_Data_const< _Tag >::RFC_Data_const(), and RFC_Data< _Tag >::set_value().
The documentation for this class was generated from the following file:
RFC_Window_transfer.h