IMPACT: RFC_Window_base Class Reference
RFC_Window_base Class Reference
A window is a collection of panes.
Detailed Description
See also
RFC_Pane_base
Definition at line 514 of file RFC_Window_base.h.
#include <RFC_Window_base.h>
Public Types
typedef RFC_Window_base Self
typedef COM::Window Base
typedef COM::DataItem DataItem
typedef RFC_Pane_base Pane
typedef std::map< int, Pane * > Pane_set
Public Member Functions
RFC_Window_base (Base *b, int c, MPI_Comm)
Construct an object with base b and color c.
virtual ~RFC_Window_base ()
Default destructor.
std::string name () const
The name of the window.
const RFC_Pane_base & pane (const int pid) const
RFC_Pane_base & pane (const int pid)
const COM::Window * base () const
Get a reference to the base COM::Window object.
int color () const
The color of the window for overlay or for data transfer (BLUE or GREEN).
int size_of_nodes () const
Get the total number of nodes contained the window.
int size_of_faces () const
Get the total number of faces contained the window.
int size_of_primary_nodes () const
Get the total number of nodes contained the window.
Bbox_3 get_bounding_box () const
Get the bounding box of the window.
int size_of_panes () const
Number of local panes in the window.
const DataItem * dataitem (const char *f) const
Retrieve an dataitem object from the base using the dataitem name.
void export_window (RFC_Window_base *) const
void write_tec_ascii (const char *prefix) const
Ouptut a mesh in Tecplot format.
void write_tec_sub (const char *prefix) const
Ouptut a subdivision of a mesh in Tecplot format.
void new_sdv_dataitems (const std::string &wname) const
New dataitems.
void read_sdv (const char *prefix, const char *format=NULL)
Read in local panes in native binary format or using Rocin.
void write_sdv (const char *prefix, const char *format=NULL) const
Write out panes in native binary format or using Rocout.
void build_pc_tables ()
Build the pane connectivity table.
Protected Types
enum { SDV_OFF, SDV_BINARY, SDV_HDF, SDV_CGNS }
Static Protected Member Functions
static std::string get_sdv_fname (const char *prefix, int pane_id, const int format=SDV_BINARY)
static const char * get_prefix_base (const char *prefix)
static int get_sdv_format (const char *format)
Protected Attributes
Base * _base
A reference to its base COM::Window object.
Pane_set _pane_set
The set of panes contained in the window.
int _verbose
int _color
MAP::Pane_communicator _map_comm
Static Protected Attributes
static const char * _bufwin_prefix = "buf_"
Private Member Functions
RFC_Window_base ()
RFC_Window_base (const Self &)
Self & operator= (const Self &)
Member Typedef Documentation
typedef COM::Window RFC_Window_base::Base
Definition at line 517 of file RFC_Window_base.h.
typedef COM::DataItem RFC_Window_base::DataItem
Definition at line 518 of file RFC_Window_base.h.
typedef RFC_Pane_base RFC_Window_base::Pane
Definition at line 519 of file RFC_Window_base.h.
typedef std::map< int, Pane*> RFC_Window_base::Pane_set
Definition at line 520 of file RFC_Window_base.h.
typedef RFC_Window_base RFC_Window_base::Self
Definition at line 516 of file RFC_Window_base.h.
Member Enumeration Documentation
anonymous enum protected
Enumerator
SDV_OFF
SDV_BINARY
SDV_HDF
SDV_CGNS
Definition at line 590 of file RFC_Window_base.h.
 { SDV_OFF, SDV_BINARY, SDV_HDF, SDV_CGNS};
Constructor & Destructor Documentation
RFC_Window_base::RFC_Window_base (Base * b, int c, MPI_Comm comm)
See also
init
Definition at line 230 of file RFC_Window_base.C.
   : _base(b), _verbose(1), _color(c), _map_comm( b, comm) {}
RFC_Window_base::~RFC_Window_base () virtual
Definition at line 232 of file RFC_Window_base.C.
References _pane_set.
{
   while ( !_pane_set.empty()) {
     delete _pane_set.begin()->second;
     _pane_set.erase( _pane_set.begin());
   }
 }
RFC_Window_base::RFC_Window_base () private
RFC_Window_base::RFC_Window_base (const Self &) private
Member Function Documentation
const COM::Window* RFC_Window_base::base () const inline
Definition at line 544 of file RFC_Window_base.h.
References _base.
Referenced by Overlay::get_rfc_window(), Overlay::write_overlay_off(), and Overlay::write_overlay_tec().
 { return _base; }
void RFC_Window_base::build_pc_tables ()
Definition at line 273 of file RFC_Window_base.C.
References _base, _map_comm, _pane_set, RFC_Pane_base::build_v2b_from_b2v(), COM_MESH, COM_PCONN, pane(), and s.
Referenced by RFC_Window_overlay::RFC_Window_overlay().
{
   MAP::Pane_connectivity pc( _base->dataitem(COM::COM_MESH),
                              _map_comm.mpi_comm());
   pc.compute_pconn( _base->dataitem(COM::COM_PCONN));
   // Now copy from b2v into the tables of each pane
   Pane_set::iterator pane_it, pane_iend=_pane_set.end();
   for ( pane_it=_pane_set.begin(); pane_it != pane_iend; ++pane_it) {
     const COM::DataItem *pconn =
       pane_it->second->_base->dataitem(COM::COM_PCONN);
     int count=pc.pconn_offset(), s = pconn->size_of_real_items();
     const int *buf= ((const int*)pconn->pointer())+count;
     while ( count < s) {
       const int r_pid = *buf;
       const int r_size = *(buf+1);
       count += 2; buf += 2;
       Pane::B2v &b2 = pane_it->second->_b2v_table[ r_pid];
       b2.clear();
       b2.insert( b2.end(), buf, buf+r_size);
       count += r_size;
       buf += r_size;
     }
   }
   // Construct v2b
   for ( pane_it=_pane_set.begin(); pane_it != pane_iend; ++pane_it) {
     Pane &pane = *pane_it->second;
     pane.build_v2b_from_b2v( this);
   }
 }
int RFC_Window_base::color () const inline
Definition at line 547 of file RFC_Window_base.h.
References _color.
Referenced by RFC_Window_transfer::init_recv_buffer().
 { return _color; }
const DataItem* RFC_Window_base::dataitem (const char * f) const inline
Definition at line 567 of file RFC_Window_base.h.
References _base.
Referenced by RFC_Data_const< _Tag >::RFC_Data_const(), and RFC_Window_transfer::set_tags().
   { return _base->dataitem(f); }
void RFC_Window_base::export_window (RFC_Window_base * w) const
Definition at line 349 of file RFC_Window_base.C.
References RFC_Pane_base::_b2v_table, _pane_set, RFC_Pane_base::_subface_counterparts, RFC_Pane_base::_subface_offsets, RFC_Pane_base::_subface_parents, RFC_Pane_base::_subfaces, RFC_Pane_base::_subnode_counterparts, RFC_Pane_base::_subnode_nat_coors, RFC_Pane_base::_subnode_parents, RFC_Pane_base::_v2b_table, RFC_Pane_base::comp_nat_coors(), RFC_Pane_base::id(), and pane().
Referenced by Overlay::export_windows().
{
   Pane_set::const_iterator pane_it, pane_iend=_pane_set.end();
   for ( pane_it=_pane_set.begin(); pane_it != pane_iend; ++pane_it) {
     Pane &pane = *pane_it->second;
     Pane &to_pane = *w->_pane_set.find( pane.id())->second;
     // Copy over the nodes information
     to_pane._subnode_parents = pane._subnode_parents;
     to_pane._subnode_counterparts = pane._subnode_counterparts;
     to_pane._subnode_nat_coors = pane._subnode_nat_coors;
     // Copy over the face information
     to_pane._subface_offsets = pane._subface_offsets;
     to_pane._subface_counterparts = pane._subface_counterparts;
     to_pane._subface_parents = pane._subface_parents;
     to_pane._subfaces = pane._subfaces;
     // Copy over the pane connectivity of the vertices
     to_pane._b2v_table = pane._b2v_table;
     to_pane._v2b_table = pane._v2b_table;
     to_pane.comp_nat_coors();
   }
 }
Bbox_3 RFC_Window_base::get_bounding_box () const
Definition at line 264 of file RFC_Window_base.C.
References _pane_set.
Referenced by Overlay::overlay().
{
   Bbox_3 b;
   Pane_set::const_iterator it=_pane_set.begin(), iend=_pane_set.end();
   for ( ; it != iend; ++it)
     b += it->second->get_bounding_box();
   return b;
 }
const char * RFC_Window_base::get_prefix_base (const char * prefix) static protected
Definition at line 505 of file RFC_Window_base_IO.C.
Referenced by RFC_Window_transfer::init_recv_buffer(), read_sdv(), and write_sdv().
 {
   const char *last_slash = std::strrchr( prefix, '/');
   if ( last_slash == NULL) return prefix;
   else return last_slash+1;
 }
std::string RFC_Window_base::get_sdv_fname (const char * prefix, int pane_id, const int format = SDV_BINARY) static protected
Definition at line 530 of file RFC_Window_base_IO.C.
References COM_assertion_msg, SDV_BINARY, SDV_CGNS, SDV_HDF, and SDV_OFF.
Referenced by RFC_Window_transfer::init_recv_buffer(), read_sdv(), and write_sdv().
 {
   // Define a file name name
   std::ostringstream fname;
   switch  (format) {
   case SDV_BINARY:  fname << prefix << pane_id << ".sdv"; break;
   case SDV_OFF:     fname << prefix << "_sdv.off"; break;
   case SDV_HDF:     fname << prefix << '_' << pane_id << "_sdv.hdf"; break;
   case SDV_CGNS:    fname << prefix << '_' << pane_id << "_sdv.cgns"; break;
   default: COM_assertion_msg( false, "Unknown file format");
   }
   return fname.str();
 }
int RFC_Window_base::get_sdv_format (const char * format) static protected
Definition at line 514 of file RFC_Window_base_IO.C.
References RFC_assertion_msg, SDV_BINARY, SDV_CGNS, SDV_HDF, and SDV_OFF.
Referenced by read_sdv(), and write_sdv().
 {
   if ( !format || std::strcmp( format, "OFF") ==0)
     return SDV_OFF;
   if (std::strcmp( format, "BIN") ==0)
     return SDV_BINARY;
   if ( std::strcmp( format, "HDF") ==0)
     return SDV_HDF;
   if (std::strcmp( format, "CGNS") ==0)
     return SDV_CGNS;
   RFC_assertion_msg( false, (std::string("Unknown format ")+format).c_str());
   return SDV_BINARY; // Default is SDV_BINARY.
 }
std::string RFC_Window_base::name () const inline
Definition at line 529 of file RFC_Window_base.h.
References _base.
Referenced by RFC_Pane_overlay::determine_counterparts(), Overlay::match_features_0(), Transfer_base::minmax(), Overlay::overlay(), and write_sdv().
 { return _base->name(); }
RFC_BEGIN_NAME_SPACE void RFC_Window_base::new_sdv_dataitems (const std::string & wname) const
Definition at line 22 of file RFC_Window_base_IO.C.
References COM_FLOAT, COM_INT, and COM_new_dataitem().
Referenced by write_sdv().
{
   // New dataitems for v2b and b2v.
   COM_new_dataitem( (wname+".v2b").c_str(), 'p', COM_INT, 1, "");
   COM_new_dataitem( (wname+".b2v").c_str(), 'p', COM_INT, 1, "");
   // New dataitems for subnode parents
   COM_new_dataitem( (wname+".sn_parent_fcID").c_str(), 'n', COM_INT, 1, "");
   COM_new_dataitem( (wname+".sn_parent_ncs").c_str(), 'n', COM_FLOAT, 2, "");
   // New dataitems for natural coordinates
   COM_new_dataitem( (wname+".sn_permu_edID").c_str(), 'n', COM_INT, 1, "");
   COM_new_dataitem( (wname+".sn_permu_ncs").c_str(), 'n', COM_FLOAT, 2, "");
   // New dataitems for counterpart of each subnode
   COM_new_dataitem( (wname+".sn_cntpt_pnID").c_str(), 'n', COM_INT, 1, "");
   COM_new_dataitem( (wname+".sn_cntpt_ndID").c_str(), 'n', COM_INT, 1, "");
   // New dataitems for the mapping from node IDs to sub-node IDs.
   COM_new_dataitem( (wname+".sn_subID").c_str(), 'p', COM_INT, 1, "");
   // New dataitems for the parent of each subface
   COM_new_dataitem( (wname+".sf_parent").c_str(), 'e', COM_INT, 1, "");
   // Register the natural coordinates of subnodes in each subface
   COM_new_dataitem( (wname+".sf_ncs").c_str(), 'e', COM_FLOAT, 6, "");
   // New dataitems for the counterpart in the other mesh of each subface
   COM_new_dataitem( (wname+".sf_cntpt_pnID").c_str(), 'e', COM_INT, 1, "");
   COM_new_dataitem( (wname+".sf_cntpt_fcID").c_str(), 'e', COM_INT, 1, "");
   // New dataitems for the offset of the subface ID for each input facet
   COM_new_dataitem( (wname+".sf_offset").c_str(), 'p', COM_INT, 1, "");
 }
Self& RFC_Window_base::operator= (const Self &) private
const RFC_Pane_base& RFC_Window_base::pane (const int pid) const inline
Definition at line 531 of file RFC_Window_base.h.
References _pane_set, and RFC_assertion.
Referenced by build_pc_tables(), RFC_Pane_base::build_v2b_from_b2v(), export_window(), read_sdv(), write_sdv(), write_tec_ascii(), and write_tec_sub().
{
     Pane_set::const_iterator pit = _pane_set.find( pid);
     RFC_assertion( pit != _pane_set.end());
     return *pit->second;
   }
RFC_Pane_base& RFC_Window_base::pane (const int pid) inline
Definition at line 537 of file RFC_Window_base.h.
References _pane_set, and RFC_assertion.
{
     Pane_set::iterator pit = _pane_set.find( pid);
     RFC_assertion( pit != _pane_set.end());
     return *pit->second;
   }
void RFC_Window_base::read_sdv (const char * prefix, const char * format = NULL)
Read in panes in native or HDF format. In native format, each pane has a separate file with file name {prefix}paneID.sdv. In HDF format, each pane also has a separate file with file name {prefix}_paneID_sdv.hdf.
See also
write_sdv
Definition at line 335 of file RFC_Window_base_IO.C.
References _bufwin_prefix, _pane_set, COM_call_function(), COM_delete_window(), COM_get_dataitem_handle(), COM_get_function_handle(), get_prefix_base(), get_sdv_fname(), get_sdv_format(), pane(), pane_id, RFC_Pane_base::read_binary(), RFC_assertion, SDV_BINARY, SimIN_load_module(), and SimIN_unload_module().
{
   // Determine the format
   int IO_format = get_sdv_format( format);
   if ( IO_format == SDV_BINARY) {
     // Read in native format binary format.
     for ( Pane_set::iterator
             it=_pane_set.begin(), iend=_pane_set.end();it!=iend; ++it) {
       std::string fname = get_sdv_fname( prefix, it->first, IO_format);
       std::ifstream is( fname.c_str());
       if ( !is) {
         std::cerr << "Rocface: Could not open input file " << fname
                   << "\nAbortting..." << std::endl;
         RFC_assertion(is); exit(-1);
       }
       RFC_Pane_base &pane = *it->second;
       pane.read_binary( is);
     }
   }
   else {
     // Read in using Rocin.
     SimIN_load_module( "RFC_IN");
     int hdl_read = COM_get_function_handle( "RFC_IN.read_windows");
     int hdl_obtain = COM_get_function_handle( "RFC_IN.obtain_dataitem");
     // Define the base-window and sdv-window names
     std::string base_material = get_prefix_base( prefix);
     std::string sdv_material = base_material+"_sdv";
     std::string buf_wname(_bufwin_prefix); buf_wname.append( base_material);
     std::string sdv_wname=buf_wname+"_sdv";
     MPI_Comm comm_self = MPI_COMM_SELF;
     // Loop through the panes to obtain the dataitems.
     for ( Pane_set::iterator
             it=_pane_set.begin(), iend=_pane_set.end(); it!=iend; ++it) {
       int pane_id = it->first;
       std::string fname = get_sdv_fname( prefix, pane_id, IO_format);
       // Read the pane from the given file. Note that the file contains both
       // the parent and the subdivided windows. Read only the subdivided one.
       COM_call_function( hdl_read, fname.c_str(), _bufwin_prefix,
                          sdv_material.c_str(), &comm_self);
       int hdl_all = COM_get_dataitem_handle( (sdv_wname+".all").c_str());
       COM_call_function( hdl_obtain, &hdl_all, &hdl_all, &pane_id);
       it->second->read_rocin( sdv_wname);
       // Delete the window created by Rocin.
       COM_delete_window( sdv_wname.c_str());
     }
     // Unload Rocin
     SimIN_unload_module( "RFC_IN");
   }
 }
int RFC_Window_base::size_of_faces () const
Definition at line 252 of file RFC_Window_base.C.
References _pane_set.
Referenced by Overlay::overlay().
{
   int n = 0;
   // Loop through panes
   Pane_set::const_iterator pit=_pane_set.begin(), piend=_pane_set.end();
   for ( ; pit != piend; ++pit) {
     n += pit->second->size_of_faces();
   }
   return n;
 }
int RFC_Window_base::size_of_nodes () const
The coincident nodes are counted more than once.
Definition at line 240 of file RFC_Window_base.C.
References _pane_set.
Referenced by RFC_Window_transfer::init_nodal_buffers(), and Overlay::overlay().
{
   int n = 0;
   // Loop through panes
   Pane_set::const_iterator pit=_pane_set.begin(), piend=_pane_set.end();
   for ( ; pit != piend; ++pit) {
     n += pit->second->size_of_primary_nodes();
   }
   return n;
 }
int RFC_Window_base::size_of_panes () const inline
Definition at line 564 of file RFC_Window_base.h.
References _pane_set.
 { return _pane_set.size(); }
int RFC_Window_base::size_of_primary_nodes () const
The coincident nodes are counted once.
void RFC_Window_base::write_sdv (const char * prefix, const char * format = NULL) const
Write panes in native format or using Rocout's format. In native format, each pane has a separate file with file name {prefix}paneID.sdv. In Rocout format, each pane also has a separate file with file name {prefix}_paneID_sdv.<suf>.
See also
read_sdv
Definition at line 406 of file RFC_Window_base_IO.C.
References _bufwin_prefix, _pane_set, COM_call_function(), COM_delete_pane(), COM_delete_window(), COM_get_dataitem_handle(), COM_get_function_handle(), COM_new_window(), COM_window_init_done(), get_prefix_base(), get_sdv_fname(), get_sdv_format(), name(), new_sdv_dataitems(), pane(), pane_id, RFC_assertion, SDV_BINARY, SDV_OFF, SimOUT_load_module(), SimOUT_unload_module(), RFC_Pane_base::write_binary(), and RFC_Pane_base::write_off().
{
   // Determine the format
   int IO_format = get_sdv_format( format);
   if ( IO_format == SDV_OFF) {
     std::string fname = get_sdv_fname( prefix, 0, IO_format);
     std::FILE *fhandle = std::fopen( fname.c_str(), "w");
     if ( !fhandle) {
       std::cerr << "Rocface: Could not open output file " << fname
                 << "\nAbortting..." << std::endl;
       RFC_assertion(fhandle); exit(-1);
     }
     // Output using OFF file format
     for ( Pane_set::const_iterator
             it=_pane_set.begin(), iend=_pane_set.end(); it!=iend; ++it) {
       RFC_Pane_base &pane = *it->second;
       pane.write_off( fhandle);
     }
     std::fclose( fhandle);
   }
   else if ( IO_format == SDV_BINARY) {
     // Output using native file format
     for ( Pane_set::const_iterator
             it=_pane_set.begin(), iend=_pane_set.end(); it!=iend; ++it) {
       std::string fname = get_sdv_fname( prefix, it->first, IO_format);
       std::ofstream os( fname.c_str());
       if ( !os) {
         std::cerr << "Rocface: Could not open output file " << fname
                   << "\nAbortting..." << std::endl;
         RFC_assertion(os); exit(-1);
       }
       RFC_Pane_base &pane = *it->second;
       pane.write_binary( os);
     }
   }
   else {
     // Output using Rocout's format
     SimOUT_load_module( "RFC_OUT");
     int hdl_set_option = COM_get_function_handle( "RFC_OUT.set_option");
     int hdl_write = COM_get_function_handle( "RFC_OUT.write_dataitem");
     COM_call_function( hdl_set_option, "rankwidth", "0");
     COM_call_function( hdl_set_option, "format", format);
     int parent_mesh = COM_get_dataitem_handle( (name()+".pmesh").c_str());
     // Define the base-window and sdv-window names
     std::string base_material = get_prefix_base( prefix);
     std::string sdv_material = base_material+"_sdv";
     std::string buf_wname(_bufwin_prefix); buf_wname.append( base_material);
     std::string sdv_wname=buf_wname+"_sdv";
     // Create a window for calling Rocout.
     COM_new_window( sdv_wname.c_str());
     new_sdv_dataitems( sdv_wname);
     int win_all = COM_get_dataitem_handle( (sdv_wname+".all").c_str());
     const char *time_level = "000";
     for ( Pane_set::const_iterator
             it=_pane_set.begin(), iend=_pane_set.end(); it!=iend; ++it) {
       int pane_id = it->first;
       // Define a file name name
       std::string fname = get_sdv_fname( prefix, pane_id, IO_format);
       // Initialize the dataitems for the subdivision pane
       it->second->register_sdv_dataitems( sdv_wname);
       // write parent mesh of the given pane into the file
       COM_call_function( hdl_set_option, "mode", "w");
       COM_call_function( hdl_write, fname.c_str(), &parent_mesh,
                          base_material.c_str(), time_level,
                          NULL, NULL, &pane_id);
       // append the subdivision pane into the file.
       COM_call_function( hdl_set_option, "mode", "a");
       COM_call_function( hdl_write, fname.c_str(), &win_all,
                          sdv_material.c_str(), time_level,
                          NULL, NULL, &pane_id);
       // remove the subdivision pane after output it.
       COM_delete_pane( sdv_wname.c_str(), pane_id);
       COM_window_init_done( sdv_wname.c_str());
     }
     // Unload Rocout
     COM_delete_window( sdv_wname.c_str());
     SimOUT_unload_module( "RFC_OUT");
   }
 }
void RFC_Window_base::write_tec_ascii (const char * prefix) const
Parameters
fname Name of the output file.
a DataItem to be writtin out. Default is mesh only.
Definition at line 235 of file RFC_Window_base_IO_tecplot.C.
References _pane_set, RFC_Pane_base::is_master(), pane(), RFC_assertion, and RFC_Pane_base::write_tec_ascii().
{
   std::ofstream os( (std::string( prefix) + ".plt").c_str()); RFC_assertion(os);
   os.precision(9);
   os.setf( std::ios::scientific, std::ios::floatfield);
   for (Pane_set::const_iterator
          it=_pane_set.begin(), iend=_pane_set.end(); it != iend; ++it) {
     RFC_Pane_base &pane = *it->second;
     if ( pane.is_master()) {
       pane.write_tec_ascii( os, 0);
     }
   }
 }
void RFC_Window_base::write_tec_sub (const char * prefix) const
Parameters
fname Name of the output file.
a DataItem to be writtin out. Default is mesh only.
Definition at line 217 of file RFC_Window_base_IO_tecplot.C.
References _pane_set, RFC_Pane_base::is_master(), pane(), RFC_assertion, and RFC_Pane_base::write_tec_sub().
{
   std::ofstream os( (std::string( prefix) + ".plt").c_str()); RFC_assertion(os);
   os.precision(9);
   os.setf( std::ios::scientific, std::ios::floatfield);
   for (Pane_set::const_iterator
          it=_pane_set.begin(), iend=_pane_set.end(); it != iend; ++it) {
     RFC_Pane_base &pane = *it->second;
     if ( pane.is_master()) {
       pane.write_tec_sub( os);
     }
   }
 }
Member Data Documentation
Base* RFC_Window_base::_base protected
Definition at line 606 of file RFC_Window_base.h.
Referenced by base(), build_pc_tables(), dataitem(), name(), and RFC_Window_transfer::RFC_Window_transfer().
const char * RFC_Window_base::_bufwin_prefix = "buf_" static protected
Definition at line 603 of file RFC_Window_base.h.
Referenced by RFC_Window_transfer::init_recv_buffer(), read_sdv(), and write_sdv().
int RFC_Window_base::_color protected
Definition at line 609 of file RFC_Window_base.h.
Referenced by color().
MAP::Pane_communicator RFC_Window_base::_map_comm protected
Definition at line 611 of file RFC_Window_base.h.
Referenced by build_pc_tables(), RFC_Window_transfer::reduce_maxabs_to_all(), RFC_Window_overlay::reduce_normals_to_all(), and RFC_Window_transfer::reduce_to_all().
Pane_set RFC_Window_base::_pane_set protected
Definition at line 607 of file RFC_Window_base.h.
Referenced by build_pc_tables(), RFC_Window_overlay::create_overlay_data(), RFC_Window_transfer::delete_facial_buffers(), RFC_Window_transfer::delete_nodal_buffers(), RFC_Window_overlay::delete_overlay_data(), RFC_Window_overlay::determine_counterparts(), RFC_Window_overlay::evaluate_normals(), export_window(), RFC_Window_overlay::get_an_unmarked_halfedge(), get_bounding_box(), RFC_Window_transfer::incident_faces(), RFC_Window_transfer::incident_panes(), RFC_Window_transfer::init_facial_buffers(), RFC_Window_transfer::init_nodal_buffers(), RFC_Window_transfer::init_recv_buffer(), RFC_Window_transfer::pane(), pane(), read_sdv(), RFC_Window_transfer::reduce_maxabs_to_all(), RFC_Window_overlay::reduce_normals_to_all(), RFC_Window_transfer::reduce_to_all(), RFC_Window_transfer::replicate_metadata(), RFC_Window_transfer::set_tags(), size_of_faces(), size_of_nodes(), size_of_panes(), RFC_Window_overlay::unmark_alledges(), write_sdv(), write_tec_ascii(), write_tec_sub(), and ~RFC_Window_base().
int RFC_Window_base::_verbose protected
Definition at line 608 of file RFC_Window_base.h.
The documentation for this class was generated from the following files:
RFC_Window_base.h
RFC_Window_base.C
RFC_Window_base_IO.C
RFC_Window_base_IO_tecplot.C