IMPACT: LoadTransferOnly_FSc_ALE Class Reference
LoadTransferOnly_FSc_ALE Class Reference
Detailed Description
Definition at line 62 of file transfer_actions.h.
#include <transfer_actions.h>
Public Member Functions
LoadTransferOnly_FSc_ALE (FluidAgent *fag, SolidAgent *sag, BurnAgent *bag, const std::string f_ts, const std::string s_ts, const std::string s_pf)
void init (double t)
void run (double t, double dt, double alpha)
Public Member Functions inherited from InterMeshTransfer
InterMeshTransfer (FluidAgent *fag, SolidAgent *sag, char *name=NULL)
Public Member Functions inherited from Action
Action (void *p=0, const char *name=NULL)
Action (int n, const char **at, int *i=NULL, void *p=0, const char *name=NULL)
Action (int n, const std::string at[], int *i=NULL, void *p=0, const char *name=NULL)
virtual ~Action ()
virtual void declare (Scheduler &)
virtual void finalize ()
virtual const char * name ()
void set_name (const char *name)
virtual void print (FILE *f)
virtual void print_toposort (FILE *f)
virtual void schedule ()
Private Attributes
int traction_mode
int size_ts
BurnAgent * bagent
int f_ts_hdl
int s_ts_hdl
int s_pf_hdl
int RFC_transfer
int SURF_compute_face_normals
Additional Inherited Members
Protected Types inherited from Action
enum { IN =1, OUT =2, INOUT =3 }
Protected Member Functions inherited from InterMeshTransfer
void load_rocface (const RocmanControl_parameters *param)
Protected Member Functions inherited from Action
int get_dataitem_handle (int i)
int get_dataitem_handle_const (int i)
int get_dataitem_handle (const std::string str)
void set_attr (int n, const std::string at[], int *id=NULL)
void set_attr (int n, const char *at[], int *id=NULL)
void set_io (int n, const int *io)
void set_io (const char *io)
int get_io (int i)
Protected Attributes inherited from InterMeshTransfer
FluidAgent * fagent
SolidAgent * sagent
Protected Attributes inherited from Action
const char * action_name
char ** attr
int * idx
int count
void * usr_ptr
std::vector< int > inout
Constructor & Destructor Documentation
LoadTransferOnly_FSc_ALE::LoadTransferOnly_FSc_ALE (FluidAgent * fag, SolidAgent * sag, BurnAgent * bag, const std::string f_ts, const std::string s_ts, const std::string s_pf) explicit
Definition at line 340 of file transfer_actions.C.
References COM_DOUBLE, InterMeshTransfer::fagent, Agent::get_coupling(), Coupling::get_rocmancontrol_param(), Agent::get_surface_window(), FluidAgent::ifluid_i, Action::IN, NO_SHEER, Action::OUT, Agent::register_clone_dataitem(), Agent::register_new_dataitem(), InterMeshTransfer::sagent, Action::set_attr(), Action::set_io(), SolidAgent::solidBufBase, RocmanControl_parameters::traction_mode, and traction_mode.
                                                         :
     InterMeshTransfer(fag, sag, "LoadTransferOnly_FSc_ALE"),
     bagent(bag)
 {
   int io[] = {IN, OUT, OUT};
   set_io( 3, io);
   std::string.data[3];
  .data[0] = f_ts;
  .data[1] = s_ts;
  .data[2] = s_pf;
   set_attr(3,.data);
   traction_mode = fagent->get_coupling()->get_rocmancontrol_param()->traction_mode;
   // create_dataitem
   // for SolidAgent ??????????????????
 //  if (traction_mode == NO_SHEER && size_ts == 3) {
     sagent->register_new_dataitem( sagent->solidBufBase, ".pf", 'e', COM_DOUBLE, 1, "Pa");
 //  }
   // for FluidAgent
   if (traction_mode == NO_SHEER)  {
     fagent->register_clone_dataitem( 0, fagent->ifluid_i, ".ts", fagent->get_surface_window(), ".pf");
   }
   else
     fagent->register_clone_dataitem( 0, fagent->ifluid_i, ".ts", fagent->get_surface_window(), ".tf");
 //  fagent->register_new_dataitem( fagent->fluidBufB, ".mdot_tmp", 'e', COM_DOUBLE, 1, "kg/(m^2 s)");
 }
Member Function Documentation
void LoadTransferOnly_FSc_ALE::init (double t) virtual
Reimplemented from Action.
Definition at line 377 of file transfer_actions.C.
References COM_assertion_msg, COM_get_dataitem(), COM_get_function_handle(), f_ts_hdl, InterMeshTransfer::fagent, Agent::get_coupling(), Action::get_dataitem_handle(), Action::get_dataitem_handle_const(), Coupling::get_rocmancontrol_param(), InterMeshTransfer::load_rocface(), load_rocsurf(), MAN_DEBUG, NO_SHEER, RFC_transfer, s_pf_hdl, s_ts_hdl, InterMeshTransfer::sagent, size_ts, SolidAgent::solidBufBase, SURF_compute_face_normals, and traction_mode.
{
   // find out size_ts
   int dummy;
   std::string unit;
   char loc;
   COM_get_dataitem( sagent->solidBufBase+".ts", &loc, &dummy, &size_ts, &unit);
   if (size_ts == 1 && traction_mode != NO_SHEER) {
     COM_assertion_msg(0, "If traction mode is with sheer, then solid tractions must be vectors!");
     MPI_Abort(MPI_COMM_WORLD, -1);
   }
   //f_pf_hdl = COM_get_dataitem_handle_const( fagent->fluidBufNG+".pf");
   f_ts_hdl = get_dataitem_handle_const( 0);
   s_ts_hdl = get_dataitem_handle( 1);
   if (traction_mode == NO_SHEER && size_ts == 3)
     s_pf_hdl = get_dataitem_handle( 2);
   else
     s_pf_hdl = -1;
   load_rocface(fagent->get_coupling()->get_rocmancontrol_param());
   RFC_transfer = COM_get_function_handle("RFC.least_squares_transfer");
   load_rocsurf();
   SURF_compute_face_normals = COM_get_function_handle( "SURF.compute_element_normals");
   MAN_DEBUG(2, ("LoadTransferOnly_FSc_ALE::init() called - traction_mode: %d size_ts: %d.\n", traction_mode, size_ts));
 }
void LoadTransferOnly_FSc_ALE::run (double t, double dt, double alpha) virtual
Reimplemented from Action.
Definition at line 405 of file transfer_actions.C.
References COM_assertion_msg, COM_call_function(), f_ts_hdl, MAN_DEBUG, RocBlas::mul, RocBlas::neg, NO_SHEER, RFC_transfer, s_pf_hdl, s_ts_hdl, size_ts, SURF_compute_face_normals, and traction_mode.
{
   MAN_DEBUG(2, ("Rocman: LoadTransferOnly_FSc_ALE::run() with t:%e dt:%e.\n", t, dt));
   // part 2  (solid_agent.f90 INIT_INBUFF_SOLID())
   if (traction_mode == NO_SHEER && size_ts == 3) {
     COM_call_function( RFC_transfer, &f_ts_hdl, &s_pf_hdl);
     COM_call_function( SURF_compute_face_normals, &s_ts_hdl);
     COM_call_function( RocBlas::mul, &s_ts_hdl, &s_pf_hdl, &s_ts_hdl);
     COM_call_function( RocBlas::neg, &s_ts_hdl, &s_ts_hdl);
   }
   else if ( traction_mode == NO_SHEER && size_ts == 1) {
     COM_call_function( RFC_transfer, &f_ts_hdl, &s_ts_hdl);
   }
   else if (size_ts == 1) {
     COM_assertion_msg(0, "If traction mode is with sheer, then solid tractions must be vectors!");
   }
   else {
     COM_call_function( RFC_transfer, &f_ts_hdl, &s_ts_hdl);
   }
 }
Member Data Documentation
BurnAgent* LoadTransferOnly_FSc_ALE::bagent private
Definition at line 70 of file transfer_actions.h.
int LoadTransferOnly_FSc_ALE::f_ts_hdl private
Definition at line 71 of file transfer_actions.h.
Referenced by init(), and run().
int LoadTransferOnly_FSc_ALE::RFC_transfer private
Definition at line 72 of file transfer_actions.h.
Referenced by init(), and run().
int LoadTransferOnly_FSc_ALE::s_pf_hdl private
Definition at line 71 of file transfer_actions.h.
Referenced by init(), and run().
int LoadTransferOnly_FSc_ALE::s_ts_hdl private
Definition at line 71 of file transfer_actions.h.
Referenced by init(), and run().
int LoadTransferOnly_FSc_ALE::size_ts private
Definition at line 69 of file transfer_actions.h.
Referenced by init(), and run().
int LoadTransferOnly_FSc_ALE::SURF_compute_face_normals private
Definition at line 73 of file transfer_actions.h.
Referenced by init(), and run().
int LoadTransferOnly_FSc_ALE::traction_mode private
Definition at line 68 of file transfer_actions.h.
Referenced by init(), LoadTransferOnly_FSc_ALE(), and run().
The documentation for this class was generated from the following files:
transfer_actions.h
transfer_actions.C