IMPACT: ComputeRhofvf Class Reference
ComputeRhofvf Class Reference
Detailed Description
Definition at line 195 of file basic_actions.h.
#include <basic_actions.h>
Public Member Functions
ComputeRhofvf (FluidAgent *ag, std::string f_vs_alp, std::string f_rhof_alp, std::string f_rhofvf_alp)
void init (double t)
void run (double t, double dt, double alpha)
Public Member Functions inherited from Action
Action (void *p=0, const char *name=NULL)
Action (int n, const char **at, int *i=NULL, void *p=0, const char *name=NULL)
Action (int n, const std::string at[], int *i=NULL, void *p=0, const char *name=NULL)
virtual ~Action ()
virtual void declare (Scheduler &)
virtual void finalize ()
virtual const char * name ()
void set_name (const char *name)
virtual void print (FILE *f)
virtual void print_toposort (FILE *f)
virtual void schedule ()
Private Attributes
FluidAgent * fagent
std::string f_vs_alp_str
std::string f_rhof_alp_str
std::string f_rhofvf_alp_str
int f_vs_alp_hdl
int f_rhof_alp_hdl
int f_rhofvf_alp_hdl
Additional Inherited Members
Protected Types inherited from Action
enum { IN =1, OUT =2, INOUT =3 }
Protected Member Functions inherited from Action
int get_dataitem_handle (int i)
int get_dataitem_handle_const (int i)
int get_dataitem_handle (const std::string str)
void set_attr (int n, const std::string at[], int *id=NULL)
void set_attr (int n, const char *at[], int *id=NULL)
void set_io (int n, const int *io)
void set_io (const char *io)
int get_io (int i)
Protected Attributes inherited from Action
const char * action_name
char ** attr
int * idx
int count
void * usr_ptr
std::vector< int > inout
Constructor & Destructor Documentation
ComputeRhofvf::ComputeRhofvf (FluidAgent * ag, std::string f_vs_alp, std::string f_rhof_alp, std::string f_rhofvf_alp)
Definition at line 722 of file basic_actions.C.
References Action::IN, Action::OUT, Action::set_attr(), and Action::set_io().
                                                                                                              :
                Action(0, (const char**)NULL, NULL, NULL, "ComputeRhofvf"),
                fagent(fag)
 {
   int io[] = {IN, IN, OUT};
   set_io( 3, io);
   std::string.data[3];
  .data[0] = f_vs_alp;
  .data[1] = f_rhof_alp;
  .data[2] = f_rhofvf_alp;
   set_attr(3,.data);
 }
Member Function Documentation
void ComputeRhofvf::init (double t) virtual
Reimplemented from Action.
Definition at line 736 of file basic_actions.C.
References Action::attr, COM_get_dataitem_handle(), f_rhof_alp_hdl, f_rhofvf_alp_hdl, and f_vs_alp_hdl.
{
   f_vs_alp_hdl = COM_get_dataitem_handle(attr[0]);
   f_rhof_alp_hdl = COM_get_dataitem_handle(attr[1]);
   f_rhofvf_alp_hdl = COM_get_dataitem_handle(attr[2]);
 }
void ComputeRhofvf::run (double t, double dt, double alpha) virtual
Reimplemented from Action.
Definition at line 742 of file basic_actions.C.
References COM_call_function(), f_rhof_alp_hdl, f_rhofvf_alp_hdl, f_vs_alp_hdl, MAN_DEBUG, and RocBlas::mul.
{
   MAN_DEBUG(2, ("Rocman: ComputeRhofvf::run() with t:%e dt:%e.\n", t, dt));
   COM_call_function( RocBlas::mul, &f_vs_alp_hdl, &f_rhof_alp_hdl, &f_rhofvf_alp_hdl);
 }
Member Data Documentation
int ComputeRhofvf::f_rhof_alp_hdl private
Definition at line 203 of file basic_actions.h.
Referenced by init(), and run().
std::string ComputeRhofvf::f_rhof_alp_str private
Definition at line 202 of file basic_actions.h.
int ComputeRhofvf::f_rhofvf_alp_hdl private
Definition at line 203 of file basic_actions.h.
Referenced by init(), and run().
std::string ComputeRhofvf::f_rhofvf_alp_str private
Definition at line 202 of file basic_actions.h.
int ComputeRhofvf::f_vs_alp_hdl private
Definition at line 203 of file basic_actions.h.
Referenced by init(), and run().
std::string ComputeRhofvf::f_vs_alp_str private
Definition at line 202 of file basic_actions.h.
FluidAgent* ComputeRhofvf::fagent private
Definition at line 201 of file basic_actions.h.
The documentation for this class was generated from the following files:
basic_actions.h
basic_actions.C