IMPACT: TransferSolidDensity Class Reference
TransferSolidDensity Class Reference
Detailed Description
Definition at line 146 of file transfer_actions.h.
#include <transfer_actions.h>
Public Member Functions
TransferSolidDensity (FluidAgent *fag, SolidAgent *sag, const std::string s_rhos, const std::string f_rhos)
void init (double t)
void run (double t, double dt, double alpha)
Public Member Functions inherited from InterMeshTransfer
InterMeshTransfer (FluidAgent *fag, SolidAgent *sag, char *name=NULL)
Public Member Functions inherited from Action
Action (void *p=0, const char *name=NULL)
Action (int n, const char **at, int *i=NULL, void *p=0, const char *name=NULL)
Action (int n, const std::string at[], int *i=NULL, void *p=0, const char *name=NULL)
virtual ~Action ()
virtual void declare (Scheduler &)
virtual void finalize ()
virtual const char * name ()
void set_name (const char *name)
virtual void print (FILE *f)
virtual void print_toposort (FILE *f)
virtual void schedule ()
Private Attributes
std::string s_rhos_str
std::string f_rhos_str
int s_rhos_hdl
int f_rhos_hdl
int RFC_transfer
Additional Inherited Members
Protected Types inherited from Action
enum { IN =1, OUT =2, INOUT =3 }
Protected Member Functions inherited from InterMeshTransfer
void load_rocface (const RocmanControl_parameters *param)
Protected Member Functions inherited from Action
int get_dataitem_handle (int i)
int get_dataitem_handle_const (int i)
int get_dataitem_handle (const std::string str)
void set_attr (int n, const std::string at[], int *id=NULL)
void set_attr (int n, const char *at[], int *id=NULL)
void set_io (int n, const int *io)
void set_io (const char *io)
int get_io (int i)
Protected Attributes inherited from InterMeshTransfer
FluidAgent * fagent
SolidAgent * sagent
Protected Attributes inherited from Action
const char * action_name
char ** attr
int * idx
int count
void * usr_ptr
std::vector< int > inout
Constructor & Destructor Documentation
TransferSolidDensity::TransferSolidDensity (FluidAgent * fag, SolidAgent * sag, const std::string s_rhos, const std::string f_rhos) explicit
Definition at line 790 of file transfer_actions.C.
References COM_DOUBLE, InterMeshTransfer::fagent, FluidAgent::fluidBufNG, Action::IN, Action::OUT, Agent::register_new_dataitem(), Action::set_attr(), and Action::set_io().
                                                                           :
                 InterMeshTransfer(fag, sag, "TransferSolidDensity"),
                 s_rhos_str(s_rhos), f_rhos_str(f_rhos)
 {
   int io[] = {IN, OUT};
   set_io( 2, io);
   std::string.data[2];
  .data[0] = s_rhos;
  .data[1] = f_rhos;
   set_attr(2,.data);
   fagent->register_new_dataitem(fagent->fluidBufNG, ".rhos", 'e', COM_DOUBLE, 1, "kg/(m^3)");
 /*
   sagent->register_use_dataitem( sagent->solidBuf, ".x", sagent->solidBufBase, ".nc");
   sagent->register_clone_dataitem( 0, sagent->solidBuf, ".nc", sagent->get_surface_window(), ".nc");
 */
 }
Member Function Documentation
void TransferSolidDensity::init (double t) virtual
Reimplemented from Action.
Definition at line 811 of file transfer_actions.C.
References COM_get_function_handle(), f_rhos_hdl, InterMeshTransfer::fagent, Agent::get_coupling(), Action::get_dataitem_handle(), Coupling::get_rocmancontrol_param(), InterMeshTransfer::load_rocface(), MAN_DEBUG, RFC_transfer, and s_rhos_hdl.
{
   MAN_DEBUG(2, ("Rocman: TransferSolidDensity::init() with t:%e.\n", t));
   s_rhos_hdl = get_dataitem_handle(0);
   f_rhos_hdl = get_dataitem_handle(1);
   load_rocface(fagent->get_coupling()->get_rocmancontrol_param());
   RFC_transfer = COM_get_function_handle("RFC.least_squares_transfer");
 }
void TransferSolidDensity::run (double t, double dt, double alpha) virtual
Reimplemented from Action.
Definition at line 821 of file transfer_actions.C.
References COM_call_function(), RocBlas::copy, f_rhos_hdl, InterMeshTransfer::fagent, Agent::get_coupling(), Coupling::initial_start(), MAN_DEBUG, RFC_transfer, SolidAgent::rhos_mode, s_rhos_hdl, and InterMeshTransfer::sagent.
{
   int rhos_mode = sagent->rhos_mode;
   MAN_DEBUG(2, ("Rocman: TransferSolidDensity::run() with rhs_mode=%d t:%e dt:%e alpha:%e.\n", rhos_mode, t, dt, alpha));
   if (rhos_mode == 1)   // Constant density
     COM_call_function( RocBlas::copy, &s_rhos_hdl, &f_rhos_hdl);
   else if (fagent->get_coupling()->initial_start())
     COM_call_function( RFC_transfer, &s_rhos_hdl, &f_rhos_hdl);
   else if (rhos_mode == 3)    // Varying density
     COM_call_function( RFC_transfer, &s_rhos_hdl, &f_rhos_hdl);
 }
Member Data Documentation
int TransferSolidDensity::f_rhos_hdl private
Definition at line 153 of file transfer_actions.h.
Referenced by init(), and run().
std::string TransferSolidDensity::f_rhos_str private
Definition at line 152 of file transfer_actions.h.
int TransferSolidDensity::RFC_transfer private
Definition at line 154 of file transfer_actions.h.
Referenced by init(), and run().
int TransferSolidDensity::s_rhos_hdl private
Definition at line 153 of file transfer_actions.h.
Referenced by init(), and run().
std::string TransferSolidDensity::s_rhos_str private
Definition at line 152 of file transfer_actions.h.
The documentation for this class was generated from the following files:
transfer_actions.h
transfer_actions.C