IMPACT: IRAD::Comm::MobileObject Class Reference
IRAD::Comm::MobileObject Class Reference
provides communication for complex objects.
Detailed Description
The MobileObject provides buffering and an interface for complex objects to use communication routines.
Definition at line 27 of file COMM.H.
#include <COMM.H>
Public Member Functions
MobileObject ()
void ** GetBufPtr ()
const void * GetBuffer () const
void * GetBuffer ()
int BufSize ()
virtual int PrepareBuffer (size_t bsize)
virtual int Pack (void **inbuf=NULL)
virtual int UnPack (const void *outbuf=NULL)
virtual void DestroyBuffer ()
virtual ~MobileObject ()
Protected Attributes
void * _buf
bool _mine
int _bsize
Constructor & Destructor Documentation
IRAD::Comm::MobileObject::MobileObject () inline
Definition at line 34 of file COMM.H.
 : _buf(NULL), _mine(false), _bsize(0) {};
virtual IRAD::Comm::MobileObject::~MobileObject () inline virtual
Definition at line 50 of file COMM.H.
References DestroyBuffer().
       {
         DestroyBuffer();
       };
Member Function Documentation
int IRAD::Comm::MobileObject::BufSize () inline
Definition at line 38 of file COMM.H.
References _bsize.
 { return(_bsize); };
virtual void IRAD::Comm::MobileObject::DestroyBuffer () inline virtual
Definition at line 42 of file COMM.H.
References _bsize, _buf, and _mine.
Referenced by IRAD::Comm::CommunicatorObject::_AllGatherMO(), IRAD::Comm::CommunicatorObject::_GatherMO(), and ~MobileObject().
       {
         if(_buf && _mine)
           delete [] (char*)_buf;
         _buf = NULL;
         _mine = false;
         _bsize = 0;
       };
const void* IRAD::Comm::MobileObject::GetBuffer () const inline
Definition at line 36 of file COMM.H.
References _buf.
Referenced by IRAD::Comm::CommunicatorObject::_AllGatherMO(), IRAD::Comm::CommunicatorObject::_GatherMO(), and IRAD::Comm::CommunicatorObject::BroadCast().
 { return (_buf); };
void* IRAD::Comm::MobileObject::GetBuffer () inline
Definition at line 37 of file COMM.H.
References _buf.
 {return (_buf); };
void** IRAD::Comm::MobileObject::GetBufPtr () inline
Definition at line 35 of file COMM.H.
References _buf.
 { return(_buf ? &_buf : NULL); };
int IRAD::Comm::MobileObject::Pack (void ** inbuf = NULL) virtual
Reimplemented in SolverUtils::GeoPrim::PBox.
Definition at line 22 of file COMM.C.
References _bsize, _buf, _mine, SolverUtils::Ostr, and IRAD::Util::String2Buf().
Referenced by IRAD::Comm::CommunicatorObject::_AllGatherMO(), IRAD::Comm::CommunicatorObject::_GatherMO(), and IRAD::Comm::CommunicatorObject::BroadCast().
     {
       if(_buf && _mine){
         delete [] (char *)_buf;
         _buf = NULL;
         _mine = false;
       }
       std::ostringstream Ostr;
       // Ostr << *this;
       if(!inbuf){
         int nchar = Util::String2Buf(Ostr.str(),&_buf);
         if(_buf){
           _mine = true;
           _bsize = nchar;
           return(_bsize);
         }
       }
       else {
         // Caller must free inbuf, else it leaks
         int nchar = Util::String2Buf(Ostr.str(),inbuf);
         if(*inbuf){
           _buf = *inbuf;
           _mine = false;
           _bsize = nchar;
           return(_bsize);
         }
       }
       return 0;
     };
int IRAD::Comm::MobileObject::PrepareBuffer (size_t bsize) virtual
Definition at line 10 of file COMM.C.
References _bsize, _buf, and _mine.
Referenced by IRAD::Comm::CommunicatorObject::BroadCast().
     {
       if(_buf && _mine)
         delete [] (char *)_buf;
       _buf = new char [bsize];
       if(!_buf)
         return 0;
       _bsize = bsize;
       _mine = true;
       return _bsize;
     };
int IRAD::Comm::MobileObject::UnPack (const void * outbuf = NULL) virtual
Reimplemented in SolverUtils::GeoPrim::PBox.
Definition at line 52 of file COMM.C.
References _bsize, _buf, and _mine.
Referenced by IRAD::Comm::CommunicatorObject::BroadCast().
     {
       if(!inbuf){
         if(!_buf)
           return 1;
         std::istringstream Istr(std::string((const char *)_buf));
         //      Istr >> *this;
         if(_mine){
           delete [] (char *)_buf;
           _buf  = NULL;
           _mine = false;
           _bsize = 0;
         }
         return(0);
       }
       else{
         std::istringstream Istr(std::string((const char *)inbuf));
         //      Istr >> *this;
         return(0);
       }
       return 0;
     };
Member Data Documentation
int IRAD::Comm::MobileObject::_bsize protected
Definition at line 32 of file COMM.H.
Referenced by BufSize(), DestroyBuffer(), Pack(), PrepareBuffer(), and UnPack().
void* IRAD::Comm::MobileObject::_buf protected
Definition at line 30 of file COMM.H.
Referenced by DestroyBuffer(), GetBuffer(), GetBufPtr(), Pack(), PrepareBuffer(), and UnPack().
bool IRAD::Comm::MobileObject::_mine protected
Definition at line 31 of file COMM.H.
Referenced by DestroyBuffer(), Pack(), PrepareBuffer(), and UnPack().
The documentation for this class was generated from the following files:
COMM.H
COMM.C