IMPACT: SolverUtils::Mesh::GenericCell_2 Class Reference
SolverUtils::Mesh::GenericCell_2 Class Reference
Detailed Description
Definition at line 587 of file Mesh.H.
#include <Mesh.H>
Public Member Functions
GenericCell_2 (Mesh::IndexType s=3)
void init (Mesh::IndexType s=3)
Mesh::IndexType size () const
GeoPrim::C3Point Centroid ()
Mesh::IndexType nedges () const
Mesh::IndexType nvert () const
void ReOrient (std::vector< Mesh::IndexType > &ec)
double Area (Mesh::IndexType elnum, const Connectivity &ec, const NodalCoordinates &nc)
GeoPrim::C3Point Centroid (std::vector< Mesh::IndexType > &ec, NodalCoordinates &nc) const
void shape_func (const GeoPrim::CVector &, double[]) const
void dshape_func (const GeoPrim::CVector &, double[][2]) const
void jacobian (const GeoPrim::CPoint p[], const GeoPrim::CVector &, GeoPrim::CVector J[]) const
void interpolate (const GeoPrim::CVector f[], const GeoPrim::CVector &nc, GeoPrim::CVector &) const
void GetNormalSet (GeoPrim::CVector ns[], Mesh::IndexType elnum, const Connectivity &ec, const NodalCoordinates &nc)
void GetPointSet (GeoPrim::CPoint ps[], Mesh::IndexType elnum, const Connectivity &ec, const NodalCoordinates &nc)
void shapef_jacobian_at (const GeoPrim::CPoint &p, GeoPrim::CVector &natc, Mesh::IndexType elnum, const Connectivity &ec, const NodalCoordinates &nc, GeoPrim::CVector &fvec, GeoPrim::CVector jac[]) const
Protected Attributes
Mesh::IndexType _size
Constructor & Destructor Documentation
SolverUtils::Mesh::GenericCell_2::GenericCell_2 (Mesh::IndexType s = 3) inline
Definition at line 591 of file Mesh.H.
 : _size(s){};
Member Function Documentation
double SolverUtils::Mesh::GenericCell_2::Area (Mesh::IndexType elnum, const Connectivity & ec, const NodalCoordinates & nc)
Definition at line 977 of file Mesh.C.
References _size, and SolverUtils::Mesh::Connectivity::Node().
     {
       GeoPrim::CPoint P[3];
       if(_size == 3){
         GeoPrim::CPoint p0(nc[ec.Node(elnum,1)]);
         GeoPrim::CPoint p1(nc[ec.Node(elnum,2)]);
         GeoPrim::CPoint p2(nc[ec.Node(elnum,3)]);
         return(.5*(GeoPrim::CVector(p1-p0)%GeoPrim::CVector(p2-p0)).mag());
       }
       if(_size == 4){
         GeoPrim::CPoint p0(nc[ec.Node(elnum,1)]);
         GeoPrim::CPoint p1(nc[ec.Node(elnum,2)]);
         GeoPrim::CPoint p2(nc[ec.Node(elnum,3)]);
         GeoPrim::CPoint p3(nc[ec.Node(elnum,4)]);
         return(.5*(GeoPrim::CVector(p2-p0)%GeoPrim::CVector(p1-p3)).mag());
       }
       return(0);
     }
GeoPrim::C3Point SolverUtils::Mesh::GenericCell_2::Centroid ()
GeoPrim::C3Point SolverUtils::Mesh::GenericCell_2::Centroid (std::vector< Mesh::IndexType > & ec, NodalCoordinates & nc) const
Definition at line 850 of file Mesh.C.
     {
       GeoPrim::C3Point centroid(0,0,0);
       Mesh::IndexType i = 0;
       Mesh::IndexType esize = ec.size();
       while(i < esize)
         centroid += GeoPrim::C3Point(nc[ec[i++]]);
       double scal = 1.0/(static_cast<double>(esize));
       return(centroid *= scal);
     };
void SolverUtils::Mesh::GenericCell_2::dshape_func (const GeoPrim::CVector & natc, double Np[][2]) const
Definition at line 895 of file Mesh.C.
References _size.
{
       switch ( _size) {
       case 3: {
         Np[0][0] = -1;    Np[0][1] = -1;
         Np[1][0] =  1;    Np[1][1] =  0;
         Np[2][0] =  0;    Np[2][1] =  1;
         return;
       }
       case 4: {
         const double xi = natc[0];
         const double xi_minus = 1. - xi;
         const double eta = natc[1];
         const double eta_minus = 1. - eta;
         Np[0][0] = -eta_minus;   Np[0][1] = -xi_minus;
         Np[1][0] = eta_minus;    Np[1][1] = -xi;
         Np[2][0] = eta;          Np[2][1] = xi;
         Np[3][0] = -eta;         Np[3][1] = xi_minus;
         return;
       }
       default:
         std::cerr << "GenericCell_2::dshape_func:error: Unknown element type."
                   << std::endl;
         exit(1);
       }
     };
void SolverUtils::Mesh::GenericCell_2::GetNormalSet (GeoPrim::CVector ns[], Mesh::IndexType elnum, const Connectivity & ec, const NodalCoordinates & nc)
Definition at line 998 of file Mesh.C.
References _size, and SolverUtils::Mesh::Connectivity::Node().
     {
       GeoPrim::CPoint P[3];
       for(Mesh::IndexType i = 0;i < _size;i++){
         Mesh::IndexType i_minus = (i==0 ? _size -1 : i - 1);
         P[i_minus] = nc[ec.Node(elnum,i_minus+1)];
         P[i] = nc[ec.Node(elnum,i+1)];
         Mesh::IndexType i_plus = (i == (_size-1) ? 0 : i+1);
         P[i_plus] = nc[ec.Node(elnum,i_plus+1)];
         ns[i] = GeoPrim::CVector(P[i] - P[i_minus])%GeoPrim::CVector(P[i_plus] - P[i]);
       }
     };
void SolverUtils::Mesh::GenericCell_2::GetPointSet (GeoPrim::CPoint ps[], Mesh::IndexType elnum, const Connectivity & ec, const NodalCoordinates & nc)
Definition at line 1014 of file Mesh.C.
References _size, init(), and SolverUtils::Mesh::Connectivity::Node().
     {
       for(Mesh::IndexType i = 0;i < _size;i++)
         P[i].init(nc[ec.Node(elnum,i+1)]);
     };
void SolverUtils::Mesh::GenericCell_2::init (Mesh::IndexType s = 3) inline
Definition at line 592 of file Mesh.H.
References _size, and s.
Referenced by GetPointSet().
 {_size = s;};
void SolverUtils::Mesh::GenericCell_2::interpolate (const GeoPrim::CVector f[], const GeoPrim::CVector & nc, GeoPrim::CVector & v) const
Definition at line 1051 of file Mesh.C.
References _size, SolverUtils::GeoPrim::CVector::x(), and SolverUtils::GeoPrim::CVector::y().
     {
       const double xi = nc.x();
       const double eta = nc.y();
       v = f[0];
       switch(_size) {
       case 3: {
         v += ((f[1]-f[0])*=xi) += ((f[2]-f[0])*=eta);
         return;
       }
       case 4: {
         v += ((f[1]-f[0]) *= (xi * (1.-eta)))
           += ((f[3]-f[0]) *= eta)
           += ((f[2]-f[3]) *= xi*eta);
         return;
       }
       case 6: {
         const double zeta=1.-xi-eta;
         v += ((f[1]-f[0]) *= xi * (2.*xi-1.))
           += ((f[3]-f[0]) *= 4.* xi * zeta)
           += ((f[2]-f[0]) *= eta * (2.*eta-1.))
           += ((f[5]-f[0]) *= 4. * eta * zeta)
           += ((f[4]-f[0]) *= 4.*xi*eta);
         return;
       }
       case 8: {
         const double xi_minus = 1. - xi;
         const double eta_minus = 1. - eta;
         v += ((f[1]-f[0]) *= eta * (2.*eta-1.))
           += ((f[3]-f[0]) *= eta)
           += ((f[2]-f[3]) *= xi * eta)
           -= ((((f[0]-f[4])+=(f[1]-f[4])) *= 2.*xi*xi_minus*eta_minus)
               += (((f[2]-f[6])+=(f[3]-f[6])) *= 2.*xi*xi_minus*eta)
               += (((f[1]-f[5])+=(f[2]-f[5])) *= 2.*xi*eta*eta_minus)
               += (((f[0]-f[7])+=(f[3]-f[7])) *= 2.*xi_minus*eta*eta_minus));
         return;
       }
       default:
         assert(false);
       }
       return;
     }
void SolverUtils::Mesh::GenericCell_2::jacobian (const GeoPrim::CPoint p[], const GeoPrim::CVector & nc, GeoPrim::CVector J[]) const
Definition at line 924 of file Mesh.C.
References _size.
{
       switch (_size) {
       case 3:
         J[0] = p[1]-p[0]; J[1] = p[2]-p[0];
         return;
       case 4: {
         const double xi        = nc[0];
         const double xi_minus  = 1. - xi;
         const double eta       = nc[1];
         const double eta_minus = 1. - eta;
         J[0] = ((p[1]-p[0]) *= eta_minus) += (( p[2]-p[3]) *= eta );
         J[1] = ((p[3]-p[0]) *= xi_minus) += (( p[2]-p[1]) *= xi);
         return;
       }
       case 6: {
         const double xi   = nc[0];
         const double eta  = nc[1];
         const double zeta = 1.-xi-eta;
         J[0] = ((p[1]-p[0]) *= 4.*xi -1.)
           += ((p[3]-p[0]) *= 4.*zeta-4*xi)
           += ((p[4]-p[5]) *= 4.*eta);
         J[1] = ((p[2]-p[0]) *= 4.*eta -1.)
           += ((p[5]-p[0]) *= 4*zeta-4*eta)
           += ((p[4]-p[3]) *= 4.*xi);
         return;
       }
       case 8: {
         const double xi        = nc[0];
         const double xi_minus  = 1. - xi;
         const double eta       = nc[1];
         const double eta_minus = 1. - eta;
         J[0] = ((p[1]-p[0]) *= eta_minus) += ((p[2]-p[3]) *= eta)
           -= ((((p[0]-p[4])+=(p[1]-p[4])) *= 2.*eta_minus*(xi_minus-xi))
               += (((p[2]-p[6])+=(p[3]-p[6])) *= 2.*eta*(xi_minus-xi))
               += (((p[1]-p[5])+=(p[2]-p[5])-=((p[0]-p[7])+=(p[3]-p[7])))
                   *= 2.*eta*eta_minus));
         ((J[1] = p[3]-p[0]) *= xi_minus) += ((p[2]-p[1]) *= xi)
           -= ((((p[1]-p[5])+=(p[2]-p[5])) *= 2.*xi*(eta_minus-eta))
               += (((p[0]-p[7])+=(p[3]-p[7])) *= 2.*xi_minus*(eta_minus-eta))
               += (((p[2]-p[6])+=(p[1]-p[4])-=((p[3]-p[6])+=(p[0]-p[4])))
                   *= 2.*xi*xi_minus));
         return;
       }
       default:
         abort(); // Should never reach here
       }
     };
Mesh::IndexType SolverUtils::Mesh::GenericCell_2::nedges () const inline
Definition at line 595 of file Mesh.H.
References _size.
 {return(_size);};
Mesh::IndexType SolverUtils::Mesh::GenericCell_2::nvert () const inline
Definition at line 596 of file Mesh.H.
References _size.
 {return(_size);};
void SolverUtils::Mesh::GenericCell_2::ReOrient (std::vector< Mesh::IndexType > & ec)
Definition at line 1097 of file Mesh.C.
References _size.
     {
       switch(_size) {
       case 3: {
         Mesh::IndexType temp = ec[0];
         ec[0] = ec[1];
         ec[1] = temp;
         return;
       }
       case 4: {
         Mesh::IndexType temp = ec[0];
         ec[0] = ec[1];
         ec[1] = temp;
         temp = ec[2];
         ec[2] = ec[3];
         ec[3] = temp;
         return;
       }
       default:
         assert(false);
       }
       return;
     }
void SolverUtils::Mesh::GenericCell_2::shape_func (const GeoPrim::CVector & natc, double SF[]) const
Definition at line 863 of file Mesh.C.
References _size.
     {
       switch (_size) {
       case 3: {
         SF[0] = 1. - natc[0] - natc[1];
         SF[1] = natc[0];
         SF[2] = natc[1];
         return;
       }
       case 4: {
         const double xi = natc[0];
         const double xi_minus = 1. - xi;
         const double eta = natc[1];
         const double eta_minus = 1. - eta;
         SF[0] = xi_minus * eta_minus;
         SF[1] = xi * eta_minus;
         SF[2] = xi * eta;
         SF[3] = xi_minus * eta;
         return;
       }
       default:
         std::cerr << "GenericCell_2::shape_func:Error: unkown element type."
                   << std::endl;
         exit(1);
       }
     };
void SolverUtils::Mesh::GenericCell_2::shapef_jacobian_at (const GeoPrim::CPoint & p, GeoPrim::CVector & natc, Mesh::IndexType elnum, const Connectivity & ec, const NodalCoordinates & nc, GeoPrim::CVector & fvec, GeoPrim::CVector jac[]) const
Definition at line 1025 of file Mesh.C.
References SolverUtils::GeoPrim::CVector::normalize(), and SolverUtils::GeoPrim::Transpose().
Referenced by SolverUtils::Mesh::NewtonRaphson_2().
     {
       GeoPrim::CPoint P[(Mesh::IndexType)_size];
       double SF[(Mesh::IndexType)_size];
       this->shape_func(natc,SF);
       fvec.init(-1.0*p);
       for(Mesh::IndexType i = 0;i < _size;i++){
         P[i].init(nc[ec.Node(elnum,i+1)]);
         fvec += SF[i]*P[i];
       }
       GeoPrim::CVector v1(P[0],P[1]);
       GeoPrim::CVector v2(P[0],P[2]);
       this->jacobian(P,natc,jac);
       jac[2] = v1%v2;
       jac[2].normalize();
       Transpose(jac);
     }
Mesh::IndexType SolverUtils::Mesh::GenericCell_2::size () const inline
Definition at line 593 of file Mesh.H.
References _size.
 {return(_size);};
Member Data Documentation
Mesh::IndexType SolverUtils::Mesh::GenericCell_2::_size protected
Definition at line 589 of file Mesh.H.
Referenced by Area(), dshape_func(), GetNormalSet(), GetPointSet(), init(), interpolate(), jacobian(), nedges(), nvert(), ReOrient(), shape_func(), and size().
The documentation for this class was generated from the following files:
Mesh.H
Mesh.C