IMPACT: IM_Reader Class Reference
IM_Reader Class Reference
Detailed Description
Definition at line 23 of file IM_Reader.h.
#include <IM_Reader.h>
Public Types
typedef bool(* Func_ptr)(int pane_id, int comm_rank, int comm_size)
Public Member Functions
IM_Reader (MPI_Comm comm=MPI_COMM_WORLD, double a=1)
int read_winmesh (const char *fname, const std::string &wname, bool del=true)
int read_mesh (const char *fname, const std::string &wname, Func_ptr is_local)
Private Types
enum { MAXLEN =255 }
Private Member Functions
bool isfinite (double x)
void get_nextline (std::istream &is, char *str)
void read_pane_coors (std::istream &is, const std::string &wname, int pid, int n, bool local)
void read_pane_elems (std::istream &is, const std::string &wname, int pid, int num_elems, int nodes_per_elem, bool local)
void read_pane_ij (std::istream &is, const std::string &wname, int pid, bool local)
void read_pane_uns (std::istream &is, const std::string &wname, int pid, int nodes_per_elem, bool local)
void read_pane_mixed (std::istream &is, const std::string &wname, int pid, bool local)
Private Attributes
char buf [MAXLEN+1]
double _alpha
int _rank
int _size
Member Typedef Documentation
typedef bool(* IM_Reader::Func_ptr)(int pane_id, int comm_rank, int comm_size)
Definition at line 40 of file IM_Reader.h.
Member Enumeration Documentation
anonymous enum private
Enumerator
MAXLEN
Definition at line 286 of file IM_Reader.h.
 {MAXLEN=255};
Constructor & Destructor Documentation
IM_Reader::IM_Reader (MPI_Comm comm = MPI_COMM_WORLD, double a = 1) inline explicit
Definition at line 29 of file IM_Reader.h.
References _rank, and _size.
                                                                 : _alpha(a) {
     int flag; MPI_Initialized(&flag);
     if ( !flag || comm == MPI_COMM_NULL) {
       _rank = 0; _size = 1;
     }
     else {
       MPI_Comm_rank( comm, &_rank);
       MPI_Comm_size( comm, &_size);
     }
   }
Member Function Documentation
void IM_Reader::get_nextline (std::istream & is, char * str) inline private
Definition at line 169 of file IM_Reader.h.
References MAXLEN.
Referenced by read_mesh(), read_pane_coors(), read_pane_elems(), read_pane_ij(), read_pane_mixed(), and read_pane_uns().
{
     char  accpet[]={'0','1','2','3','4','5','6','7','8','9',
                     '.','+','-','e','E'};
     do {
       if ( is.eof()) {
         std::cerr << "Error: Unexpected EOF" << std::endl;
         exit(-1);
       }
       is.getline( str, MAXLEN);
     } while ( str[0]=='#' || strpbrk( str,accpet)==NULL);
   }
bool IM_Reader::isfinite (double x) inline private
Definition at line 25 of file IM_Reader.h.
Referenced by read_pane_coors().
 { return x>-HUGE_VAL && x<HUGE_VAL; }
int IM_Reader::read_mesh (const char * fname, const std::string & wname, Func_ptr is_local) inline
Definition at line 86 of file IM_Reader.h.
References _rank, _size, buf, COM_get_window_handle(), COM_new_window(), get_nextline(), is_local(), read_pane_ij(), read_pane_mixed(), and read_pane_uns().
Referenced by main(), and read_winmesh().
{
     std::ifstream is( fname);
     if ( is == NULL) {
       std::cerr << "Error: Could not open file " << fname << std::endl;
       exit(-1);
     }
     // Create the window if not yet exist
     int h=COM_get_window_handle(wname.c_str());
     if ( h<=0) COM_new_window( wname.c_str());
     std::cout << "Reading file " << fname << std::endl;
     get_nextline( is, buf);
     int num_panes, mesh_type;
     char t;
     std::sscanf( buf, "%d%c%d", &num_panes, &t, &mesh_type);
     if ( num_panes<=0) {
       std::cerr << "Error: The number of panes must be positive." << std::endl;
       exit(-1);
     }
     int n=0;
     switch (mesh_type) {
     case 2: // Structured mesh
       for ( int i=0; i<num_panes; ++i) {
         get_nextline( is, buf);
         int pid;
         std::sscanf( buf, "%d", &pid);
         if ( pid<=0) {
           std::cerr << "Error: Found nonpositive pane id " << pid << std::endl;
           exit(-1);
         }
         bool local=(!is_local) || is_local( pid, _rank, _size);
         n+=local;
         read_pane_ij( is, wname, pid, local);
       }
       break;
     case 3: // Unstrured mesh with 3-node triangles
     case 4: // Unstrured mesh with 4-node quadrilaterals
     case 6: // Unstrured mesh with 6-node triangles
       for ( int i=0; i<num_panes; ++i) {
         get_nextline( is, buf);
         int pid;
         std::sscanf( buf, "%d", &pid);
         if ( pid<=0) {
           std::cerr << "Error: Found nonpositive pane id " << pid << std::endl;
           exit(-1);
         }
         bool local=(!is_local) || is_local( pid, _rank, _size);
         n+=local;
         read_pane_uns( is, wname, pid, mesh_type, local);
       }
       break;
     case 5: // Mixed mesh with 3-node triangles and 4-node quadrilaterals
       for ( int i=0; i<num_panes; ++i) {
         get_nextline( is, buf);
         int pid;
         std::sscanf( buf, "%d", &pid);
         if ( pid<=0) {
           std::cerr << "Error: Found nonpositive pane id " << pid << std::endl;
           exit(-1);
         }
         bool local=(!is_local) || is_local( pid, _rank, _size);
         n+=local;
         read_pane_mixed( is, wname, pid, local);
       }
       break;
     default:
       std::cerr << "Error: File: " << fname
                 << " has unknown mesh type" << mesh_type << std::endl;
       exit(-1);
     }
     std::cout << "Finished reading file " << fname << std::endl;
     return n;
   }
void IM_Reader::read_pane_coors (std::istream & is, const std::string & wname, int pid, int n, bool local) inline private
Definition at line 183 of file IM_Reader.h.
References _alpha, buf, COM_allocate_array(), COM_set_size(), get_nextline(), and isfinite().
Referenced by read_pane_ij(), read_pane_mixed(), and read_pane_uns().
{
     SURF::Point_3<double>  *coors=NULL;
     if ( local) {
       COM_set_size( (wname+".nc").c_str(), pid, n);
       COM_allocate_array( (wname+".nc").c_str(), pid, &(void*&)coors);
     }
     for ( int i=0; i<n; ++i) {
       get_nextline( is, buf);
       if ( local) {
         std::sscanf( buf, "%lf %lf %lf", &coors[i][0], &coors[i][1], &coors[i][2]);
         if (!isfinite( coors[i][0]) || !isfinite(coors[i][1]) ||
             !isfinite( coors[i][2])) {
           std::cerr << "Error: Got invalid coordinates " << coors[i]
                     << " for node " << i+1  << " on pane " << pid
                     << " of window " << wname << std::endl;
           exit(-1);
         }
       }
     }
     if ( local && _alpha!=1.)
       for ( int i=0; i<n; ++i) {
         coors[i][0]*=_alpha; coors[i][1]*=_alpha; coors[i][2]*=_alpha;
       }
   }
void IM_Reader::read_pane_elems (std::istream & is, const std::string & wname, int pid, int num_elems, int nodes_per_elem, bool local) inline private
Definition at line 213 of file IM_Reader.h.
References buf, COM_allocate_array(), COM_set_size(), and get_nextline().
Referenced by read_pane_mixed(), and read_pane_uns().
{
     int *elems;
     const char *types[] = {".:t3:", ".:q4:", "", ".:t6:"};
     if (local) {
       COM_set_size( (wname+types[nodes_per_elem-3]).c_str(), pid, num_elems);
       COM_allocate_array( (wname+types[nodes_per_elem-3]).c_str(),
                           pid, &(void*&)elems);
     }
     for ( int i=0; i<num_elems; ++i) {
       get_nextline( is, buf);
       if (local) {
         int *p = &elems[i*nodes_per_elem];
         switch ( nodes_per_elem) {
         case 3: std::sscanf( buf, "%d %d %d", p, p+1, p+2); break;
         case 4: std::sscanf( buf, "%d %d %d %d", p, p+1, p+2, p+3); break;
         case 6: std::sscanf( buf, "%d %d %d %d %d %d", p, p+1, p+2, p+3, p+4, p+5); break;
         default: assert(false); abort();
         }
       }
     }
   }
void IM_Reader::read_pane_ij (std::istream & is, const std::string & wname, int pid, bool local) inline private
Definition at line 239 of file IM_Reader.h.
References buf, COM_set_array(), get_nextline(), and read_pane_coors().
Referenced by read_mesh().
{
     get_nextline( is, buf);
     int dims[2];
     std::sscanf( buf, "%d %d", &dims[0], &dims[1]);
     if ( dims[0]<0 && dims[1]<0) {
       std::cerr << "Error: Negative mesh dimension " << std::endl;
       exit(-1);
     }
     COM_set_array( (wname+".:st2:").c_str(), pid, dims);
     read_pane_coors( is, wname, pid, dims[0]*dims[1], local);
   }
void IM_Reader::read_pane_mixed (std::istream & is, const std::string & wname, int pid, bool local) inline private
Definition at line 270 of file IM_Reader.h.
References buf, get_nextline(), num_nodes, read_pane_coors(), and read_pane_elems().
Referenced by read_mesh().
{
     int num_nodes, num_tris, num_quads;
     get_nextline( is, buf);
     std::sscanf( buf, "%d %d %d", &num_nodes, &num_tris, &num_quads);
     if ( num_nodes<0 && num_tris<0 || num_quads<0) {
       std::cerr << "Error: Negative node or element size" << std::endl;
       exit(-1);
     }
     read_pane_coors( is, wname, pid, num_nodes, local);
     read_pane_elems( is, wname, pid, num_tris, 3, local);
     read_pane_elems( is, wname, pid, num_quads, 4, local);
   }
void IM_Reader::read_pane_uns (std::istream & is, const std::string & wname, int pid, int nodes_per_elem, bool local) inline private
Definition at line 254 of file IM_Reader.h.
References buf, get_nextline(), num_nodes, read_pane_coors(), and read_pane_elems().
Referenced by read_mesh().
{
     int num_nodes, num_elmes;
     get_nextline( is, buf);
     std::sscanf( buf, "%d %d", &num_nodes, &num_elmes);
     if ( num_nodes<0 || num_elmes<0) {
       std::cerr << "Error: Negative node or element size" << std::endl;
       exit(-1);
     }
     read_pane_coors( is, wname, pid, num_nodes, local);
     read_pane_elems( is, wname, pid, num_elmes, nodes_per_elem, local);
   }
int IM_Reader::read_winmesh (const char * fname, const std::string & wname, bool del = true) inline
Definition at line 42 of file IM_Reader.h.
References COM_call_function(), COM_delete_dataitem(), COM_get_dataitem_handle(), COM_get_function_handle(), COM_get_panes(), COM_LOAD_MODULE_STATIC_DYNAMIC, COM_resize_array(), COM_UNLOAD_MODULE_STATIC_DYNAMIC, and read_mesh().
Referenced by main().
{
     const char *lastdot=std::strrchr( fname, '.');
     if ( lastdot && (std::strcmp( lastdot, ".hdf")==0 ||
                      std::strcmp( lastdot, ".cgns")==0 ||
                      std::strcmp( lastdot, ".txt")==0)) {
       // Read in HDF format
       COM_LOAD_MODULE_STATIC_DYNAMIC( SimIN, "IN");
       int IN_read;
       if ( std::strcmp( lastdot, ".hdf") == 0 ||
            std::strcmp( lastdot, ".cgns") == 0)
         IN_read = COM_get_function_handle( "IN.read_window");
       else
         IN_read = COM_get_function_handle( "IN.read_by_control_file");
       COM_call_function( IN_read, fname, wname.c_str());
       int IN_obtain = COM_get_function_handle( "IN.obtain_dataitem");
       int mesh_hdl = COM_get_dataitem_handle((wname+".mesh").c_str());
       COM_call_function( IN_obtain, &mesh_hdl, &mesh_hdl);
       COM_UNLOAD_MODULE_STATIC_DYNAMIC( SimIN, "IN");
       // Change the memory layout to contiguous.
       COM_resize_array( (wname+".mesh").c_str(), 0, NULL, 0);
       if ( del) {
         // Delete all dataitems and leave alone the mesh.
         COM_delete_dataitem( (wname+".atts").c_str());
       }
       int npanes; COM_get_panes( wname.c_str(), &npanes, NULL);
       return npanes;
     }
     else if (!lastdot || std::strcmp( lastdot, ".im")) {
       std::cerr << "Unknown file format with suffix " << lastdot << std::endl;
       return -1;
     }
     return read_mesh( fname, wname, NULL);
   }
Member Data Documentation
double IM_Reader::_alpha private
Definition at line 288 of file IM_Reader.h.
Referenced by read_pane_coors().
int IM_Reader::_rank private
Definition at line 289 of file IM_Reader.h.
Referenced by IM_Reader(), and read_mesh().
int IM_Reader::_size private
Definition at line 289 of file IM_Reader.h.
Referenced by IM_Reader(), and read_mesh().
char IM_Reader::buf[MAXLEN+1] private
Definition at line 287 of file IM_Reader.h.
Referenced by read_mesh(), read_pane_coors(), read_pane_elems(), read_pane_ij(), read_pane_mixed(), and read_pane_uns().
The documentation for this class was generated from the following file:
IM_Reader.h