IMPACT: IRAD::Sys::Net::Client Class Reference
IRAD::Sys::Net::Client Class Reference
Detailed Description
Definition at line 101 of file NetUtils.H.
#include <NetUtils.H>
Public Member Functions
Client ()
int & Descriptor ()
int Descriptor () const
struct sockaddr_in & ServerAddress ()
struct sockaddr_in ServerAddresss () const
int Connect (const std::string &server_address, int port=0)
int Close ()
~Client ()
Private Attributes
int _descriptor
struct sockaddr_in _server_addy
Constructor & Destructor Documentation
IRAD::Sys::Net::Client::Client () inline
Definition at line 107 of file NetUtils.H.
References _server_addy.
                  : _descriptor(-1)
         {
           std::memset(&_server_addy,0,sizeof(struct sockaddr_in));
         };
IRAD::Sys::Net::Client::~Client () inline
Definition at line 144 of file NetUtils.H.
References Close().
 { Close(); };
Member Function Documentation
int IRAD::Sys::Net::Client::Close () inline
Definition at line 143 of file NetUtils.H.
References _descriptor.
Referenced by ~Client().
 { if(_descriptor > 0) close(_descriptor); return(0);};
int IRAD::Sys::Net::Client::Connect (const std::string & server_address, int port = 0) inline
Definition at line 115 of file NetUtils.H.
References _descriptor, and _server_addy.
Referenced by SolverUtils::FEM::TCPSolverClient::Connect(), main(), and IRAD::TestTCPInterface().
         {
           if(port <= 0)
             port = 8044;
           _descriptor = socket(AF_INET,SOCK_STREAM,0);
           if(_descriptor < 0){
             perror("Sys::Net::Client::Connect::socket");
             return(-1);
           }
           _server_addy.sin_family = AF_INET;
           _server_addy.sin_port   = htons(port);
           int retval = inet_pton(AF_INET,server_address.c_str(),&_server_addy.sin_addr);
           if(retval < 0){
             perror("Sys::Net::Client::Connect::inet_pton");
             return(-1);
           }
           else if(retval == 0){
             std::cerr << "Sys::Net::Client::Connect::inet_pton: Invalid address: "
                       << server_address << std::endl;
             return(-1);
           }
           if(connect(_descriptor,reinterpret_cast<const sockaddr *>(&_server_addy),
                      sizeof(struct sockaddr_in)) < 0){
             perror("Sys::Net::Client::Connect::connect");
             return(-1);
           }
           return(0);
         };
int& IRAD::Sys::Net::Client::Descriptor () inline
Definition at line 111 of file NetUtils.H.
References _descriptor.
Referenced by SolverUtils::FEM::TCPSolverClient::Connect(), main(), and IRAD::TestTCPInterface().
 { return(_descriptor); };
int IRAD::Sys::Net::Client::Descriptor () const inline
Definition at line 112 of file NetUtils.H.
References _descriptor.
 { return(_descriptor); };
struct sockaddr_in& IRAD::Sys::Net::Client::ServerAddress () inline
Definition at line 113 of file NetUtils.H.
References _server_addy.
 { return(_server_addy); };
struct sockaddr_in IRAD::Sys::Net::Client::ServerAddresss () const inline
Definition at line 114 of file NetUtils.H.
References _server_addy.
 { return(_server_addy); };
Member Data Documentation
int IRAD::Sys::Net::Client::_descriptor private
Definition at line 104 of file NetUtils.H.
Referenced by Close(), Connect(), and Descriptor().
struct sockaddr_in IRAD::Sys::Net::Client::_server_addy private
Definition at line 105 of file NetUtils.H.
Referenced by Client(), Connect(), ServerAddress(), and ServerAddresss().
The documentation for this class was generated from the following file:
NetUtils.H