IMPACT: SolverUtils::GeoPrim::C3Line Class Reference
SolverUtils::GeoPrim::C3Line Class Reference
Detailed Description
Definition at line 1444 of file GeoPrimitives.H.
#include <GeoPrimitives.H>
Public Member Functions
C3Line ()
C3Line (const C3Point &p1, const C3Point &p2)
C3Line (const C3Line &l)
C3Line (const C3Vector &v1)
C3Line PointSlope (const C3Point &p1, const C3Vector &v1)
C3Line & move (const C3Point &p1)
bool operator== (const C3Line &l) const
bool has_point (const C3Point &p2) const
C3Vector & slope ()
const C3Vector & slope () const
C3Point & point ()
const C3Point & point () const
Protected Attributes
C3Point p
C3Vector v
Friends
double Distance (const C3Point &p, const C3Line &l)
Constructor & Destructor Documentation
SolverUtils::GeoPrim::C3Line::C3Line () inline
Definition at line 1450 of file GeoPrimitives.H.
     {};
SolverUtils::GeoPrim::C3Line::C3Line (const C3Point & p1, const C3Point & p2) inline
Definition at line 1452 of file GeoPrimitives.H.
       : p(p1),v(p1,p2)
     {};
SolverUtils::GeoPrim::C3Line::C3Line (const C3Line & l) inline
Definition at line 1455 of file GeoPrimitives.H.
       : p(l.p), v(l.v)
     {};
SolverUtils::GeoPrim::C3Line::C3Line (const C3Vector & v1) inline
Definition at line 1461 of file GeoPrimitives.H.
       : p(0,0,0),v(v1)
     {};
Member Function Documentation
bool SolverUtils::GeoPrim::C3Line::has_point (const C3Point & p2) const inline
Definition at line 1481 of file GeoPrimitives.H.
References SolverUtils::GeoPrim::C3Vector::Normalize(), SolverUtils::GeoPrim::TOL, SolverUtils::GeoPrim::C3Vector::Unit(), and v.
Referenced by SolverUtils::GeoPrim::C3LineSegment::has_point(), and SolverUtils::Mesh::TRIANGLE_OK().
     {
       C3Vector v2(p2,p);
       v2.Normalize();
       double r = v2 * v.Unit();
       return( (fabs(r - 1.0) < TOL) ||
               (fabs(r + 1.0) < TOL) );
     };
C3Line& SolverUtils::GeoPrim::C3Line::move (const C3Point & p1) inline
Definition at line 1471 of file GeoPrimitives.H.
     {
       p = p1;
       return(*this);
     };
bool SolverUtils::GeoPrim::C3Line::operator== (const C3Line & l) const inline
Definition at line 1476 of file GeoPrimitives.H.
References p, and v.
     {
       return( (p == l.p)  &&
               (v == l.v) );
     };
C3Point& SolverUtils::GeoPrim::C3Line::point () inline
Definition at line 1497 of file GeoPrimitives.H.
     {
       return(p);
     };
const C3Point& SolverUtils::GeoPrim::C3Line::point () const inline
Definition at line 1501 of file GeoPrimitives.H.
     {
       return(p);
     };
C3Line SolverUtils::GeoPrim::C3Line::PointSlope (const C3Point & p1, const C3Vector & v1) inline
Definition at line 1464 of file GeoPrimitives.H.
References p, and v.
     {
       C3Line retval;
       retval.p = p1;
       retval.v = v1;
       return(retval);
     };
C3Vector& SolverUtils::GeoPrim::C3Line::slope () inline
Definition at line 1489 of file GeoPrimitives.H.
References v.
     {
       return(v);
     };
const C3Vector& SolverUtils::GeoPrim::C3Line::slope () const inline
Definition at line 1493 of file GeoPrimitives.H.
References v.
     {
       return(v);
     };
Friends And Related Function Documentation
double Distance (const C3Point & p, const C3Line & l) friend
Definition at line 58 of file GeoPrimitives.C.
   {
     double u = (((p.x() - l.p.x())*l.v.x() + (p.y() - l.p.y())*l.v.y() +
                  (p.z() - l.p.z())*l.v.z())/l.v.Mag2());
     C3Point p2(l.p.x()+(u*l.v.x()),l.p.y()+(u*l.v.y()),l.p.z()+(u*l.v.z()));
     C3Vector v(p,p2);
     return(v.Mag());
   }
Member Data Documentation
C3Point SolverUtils::GeoPrim::C3Line::p protected
Definition at line 1447 of file GeoPrimitives.H.
Referenced by SolverUtils::GeoPrim::Distance(), operator==(), and PointSlope().
C3Vector SolverUtils::GeoPrim::C3Line::v protected
Definition at line 1448 of file GeoPrimitives.H.
Referenced by SolverUtils::GeoPrim::Distance(), has_point(), operator==(), PointSlope(), and slope().
The documentation for this class was generated from the following file:
GeoPrimitives.H