IMPACT: SolverUtils::GeoPrim::C3Plane Class Reference
SolverUtils::GeoPrim::C3Plane Class Reference
Detailed Description
Definition at line 2070 of file GeoPrimitives.H.
#include <GeoPrimitives.H>
Public Member Functions
C3Plane ()
C3Plane (const C3Point &p1, const C3Point &p2, const C3Point &p3)
C3Plane (const C3Vector &N, const C3Point &P)
C3Plane (const C3Plane &plane)
C3Plane (const std::vector< C3Point > &vec)
C3Plane & operator= (const C3Plane &plane)
double A () const
double B () const
double C () const
double D () const
C3Vector & normal ()
const C3Vector & normal () const
C3Point & point ()
const C3Point & point () const
bool contains_point (const C3Point &P) const
bool operator== (const C3Plane &plane) const
Protected Attributes
C3Vector n
C3Point p
Constructor & Destructor Documentation
SolverUtils::GeoPrim::C3Plane::C3Plane () inline
Definition at line 2075 of file GeoPrimitives.H.
 {};
SolverUtils::GeoPrim::C3Plane::C3Plane (const C3Point & p1, const C3Point & p2, const C3Point & p3) inline
Definition at line 2076 of file GeoPrimitives.H.
References A(), B(), C(), n, SolverUtils::GeoPrim::C3Vector::Normalize(), SolverUtils::GeoPrim::C3Point::x(), SolverUtils::GeoPrim::C3Vector::x(), SolverUtils::GeoPrim::C3Point::y(), and SolverUtils::GeoPrim::C3Point::z().
       : p(p1)
     {
       double A = p1.y()*(p2.z() - p3.z()) + p2.y()*(p3.z() - p1.z()) +
         p3.y()*(p1.z() - p2.z());
       double B = p1.z()*(p2.x() - p3.x()) + p2.z()*(p3.x() - p1.x()) +
         p3.z()*(p1.x() - p2.x());
       double C = p1.x()*(p2.y() - p3.y()) + p2.x()*(p3.y() - p1.y()) +
         p3.x()*(p1.y() - p2.y());
       //      double D = -1.0 * ( p1.x()*(p2.y()*p3.z() - p3.y()*p2.z()) +
       //                          p2.x()*(p3.y()*p1.z() - p1.y()*p3.z()) +
       //                          p3.x()*(p1.y()*p2.z() - p2.y()*p1.z()) );
       n.x(A).y(B).z(C);
       n.Normalize();
     };
SolverUtils::GeoPrim::C3Plane::C3Plane (const C3Vector & N, const C3Point & P) inline
Definition at line 2092 of file GeoPrimitives.H.
       : n(N.Unit()),p(P)
     {};
SolverUtils::GeoPrim::C3Plane::C3Plane (const C3Plane & plane) inline
Definition at line 2095 of file GeoPrimitives.H.
       : n(plane.n),p(plane.p)
     {};
SolverUtils::GeoPrim::C3Plane::C3Plane (const std::vector< C3Point > & vec) inline
Definition at line 2098 of file GeoPrimitives.H.
References A(), B(), C(), n, SolverUtils::GeoPrim::C3Vector::Normalize(), and SolverUtils::GeoPrim::C3Vector::x().
       : p(vec[0])
     {
       double A = vec[0].y()*(vec[1].z() - vec[2].z()) +
         vec[1].y()*(vec[2].z() - vec[0].z()) +
         vec[2].y()*(vec[0].z() - vec[1].z());
       double B = vec[0].z()*(vec[1].x() - vec[2].x()) +
         vec[1].z()*(vec[2].x() - vec[0].x()) +
         vec[2].z()*(vec[0].x() - vec[1].x());
       double C = vec[0].x()*(vec[1].y() - vec[2].y()) +
         vec[1].x()*(vec[2].y() - vec[0].y()) +
         vec[2].x()*(vec[0].y() - vec[1].y());
       //      double D = -1.0 * ( p1.x()*(p2.y()*p3.z() - p3.y()*p2.z()) +
       //                          p2.x()*(p3.y()*p1.z() - p1.y()*p3.z()) +
       //                          p3.x()*(p1.y()*p2.z() - p2.y()*p1.z()) );
       n.x(A).y(B).z(C);
       n.Normalize();
     } ;
Member Function Documentation
double SolverUtils::GeoPrim::C3Plane::A () const inline
Definition at line 2123 of file GeoPrimitives.H.
References n, and SolverUtils::GeoPrim::C3Vector::x().
Referenced by C3Plane().
 { return(n.x()); };
double SolverUtils::GeoPrim::C3Plane::B () const inline
Definition at line 2124 of file GeoPrimitives.H.
References n, and SolverUtils::GeoPrim::C3Vector::y().
Referenced by C3Plane().
 { return(n.y()); };
double SolverUtils::GeoPrim::C3Plane::C () const inline
Definition at line 2125 of file GeoPrimitives.H.
References n, and SolverUtils::GeoPrim::C3Vector::z().
Referenced by C3Plane().
 { return(n.z()); };
bool SolverUtils::GeoPrim::C3Plane::contains_point (const C3Point & P) const inline
Definition at line 2134 of file GeoPrimitives.H.
References D(), n, SolverUtils::GeoPrim::TOL, SolverUtils::GeoPrim::C3Point::x(), SolverUtils::GeoPrim::C3Vector::x(), SolverUtils::GeoPrim::C3Point::y(), SolverUtils::GeoPrim::C3Vector::y(), SolverUtils::GeoPrim::C3Point::z(), and SolverUtils::GeoPrim::C3Vector::z().
Referenced by operator==(), SolverUtils::Mesh::QUAD_OK(), and SolverUtils::Mesh::GenericElement::ShapeOK().
     {
       return(fabs(n.x()*P.x() + n.y()*P.y() + n.z()*P.z() + D()) <= TOL);
     };
double SolverUtils::GeoPrim::C3Plane::D () const inline
Definition at line 2126 of file GeoPrimitives.H.
References n, p, SolverUtils::GeoPrim::C3Point::x(), SolverUtils::GeoPrim::C3Vector::x(), SolverUtils::GeoPrim::C3Point::y(), SolverUtils::GeoPrim::C3Vector::y(), SolverUtils::GeoPrim::C3Point::z(), and SolverUtils::GeoPrim::C3Vector::z().
Referenced by contains_point().
     {
       return( -1.0 * ( n.x()*p.x() + n.y()*p.y() + n.z()*p.z()));
     };
C3Vector& SolverUtils::GeoPrim::C3Plane::normal () inline
Definition at line 2130 of file GeoPrimitives.H.
References n.
 { return(n); };
const C3Vector& SolverUtils::GeoPrim::C3Plane::normal () const inline
Definition at line 2131 of file GeoPrimitives.H.
References n.
 { return(n); };
C3Plane& SolverUtils::GeoPrim::C3Plane::operator= (const C3Plane & plane) inline
Definition at line 2117 of file GeoPrimitives.H.
References n, and p.
     {
       n = plane.n;
       p = plane.p;
       return(*this);
     };
bool SolverUtils::GeoPrim::C3Plane::operator== (const C3Plane & plane) const inline
Definition at line 2138 of file GeoPrimitives.H.
References contains_point(), n, p, and SolverUtils::GeoPrim::C3Vector::Unit().
     {
       return((plane.n.Unit() == n.Unit()) && contains_point(plane.p));
     };
C3Point& SolverUtils::GeoPrim::C3Plane::point () inline
Definition at line 2132 of file GeoPrimitives.H.
References p.
 { return(p); };
const C3Point& SolverUtils::GeoPrim::C3Plane::point () const inline
Definition at line 2133 of file GeoPrimitives.H.
References p.
 { return(p); };
Member Data Documentation
C3Vector SolverUtils::GeoPrim::C3Plane::n protected
Definition at line 2072 of file GeoPrimitives.H.
Referenced by A(), B(), C(), C3Plane(), contains_point(), D(), normal(), operator=(), and operator==().
C3Point SolverUtils::GeoPrim::C3Plane::p protected
Definition at line 2073 of file GeoPrimitives.H.
Referenced by D(), operator=(), operator==(), and point().
The documentation for this class was generated from the following file:
GeoPrimitives.H