IMPACT: SolverUtils::GeoPrim::CPoint Class Reference
SolverUtils::GeoPrim::CPoint Class Reference
Detailed Description
Definition at line 25 of file GeoPrimitives.H.
#include <GeoPrimitives.H>
Public Member Functions
CPoint ()
CPoint (double ix, double iy, double iz=0.0)
CPoint (const double *p)
CPoint (const CPoint &in)
CPoint & init ()
CPoint & init (double ix, double iy, double iz=0.0)
CPoint & init (const double *p)
CPoint & operator= (const CPoint &p)
CPoint & copy (const CPoint &p)
double norm () const
bool operator== (const CPoint &p) const
bool operator!= (const CPoint &p) const
bool operator< (const CPoint &p) const
bool operator> (const CPoint &p) const
bool operator<= (const CPoint &p) const
bool operator>= (const CPoint &p) const
CPoint & operator+= (const CPoint &p)
CPoint & operator-= (const CPoint &p)
CPoint operator* (double num) const
CPoint & operator*= (double num)
double & x ()
CPoint & x (double i)
const double & x () const
double & y ()
CPoint & y (double i)
const double & y () const
double & z ()
CPoint & z (double i)
const double & z () const
const double & operator[] (unsigned int i) const
double & operator[] (unsigned int i)
CPoint operator+ (const CPoint &p) const
CPoint operator- (const CPoint &p) const
double Distance (const CPoint &p) const
CPoint & set (double ix, double iy, double iz)
CPoint & reset ()
Protected Attributes
double P [3]
Friends
CPoint operator* (double, const CPoint &p)
std::ostream & operator<< (std::ostream &oSt, const CPoint &p)
std::istream & operator>> (std::istream &iSt, CPoint &p)
double Distance (const CPoint &p, const GeoPrim::CLine &l)
Constructor & Destructor Documentation
SolverUtils::GeoPrim::CPoint::CPoint () inline
Definition at line 33 of file GeoPrimitives.H.
References P.
     {
       P[0] = P[1] = P[2] = 0.0;
     };
SolverUtils::GeoPrim::CPoint::CPoint (double ix, double iy, double iz = 0.0) inline
Definition at line 37 of file GeoPrimitives.H.
References P.
     {
       P[0] = ix;
       P[1] = iy;
       P[2] = iz;
     };
SolverUtils::GeoPrim::CPoint::CPoint (const double * p) inline
Definition at line 43 of file GeoPrimitives.H.
References P.
     {
       P[0] = p[0];
       P[1] = p[1];
       P[2] = p[2];
     };
SolverUtils::GeoPrim::CPoint::CPoint (const CPoint & in) inline
Definition at line 49 of file GeoPrimitives.H.
References P.
     {
       P[0] = in.P[0];
       P[1] = in.P[1];
       P[2] = in.P[2];
     };
Member Function Documentation
CPoint& SolverUtils::GeoPrim::CPoint::copy (const CPoint & p) inline
Definition at line 89 of file GeoPrimitives.H.
     {
       *this = p;
       return(*this);
     };
double SolverUtils::GeoPrim::CPoint::Distance (const CPoint & p) const inline
Definition at line 193 of file GeoPrimitives.H.
References norm().
     {
       return((*this - p).norm());
     }
CPoint& SolverUtils::GeoPrim::CPoint::init () inline
Definition at line 61 of file GeoPrimitives.H.
References P.
     {
       P[0] = 0.;
       P[1] = 0.;
       P[2] = 0;
       return(*this);
     };
CPoint& SolverUtils::GeoPrim::CPoint::init (double ix, double iy, double iz = 0.0) inline
Definition at line 68 of file GeoPrimitives.H.
References P.
     {
       P[0] = ix;
       P[1] = iy;
       P[2] = iz;
       return(*this);
     };
CPoint& SolverUtils::GeoPrim::CPoint::init (const double * p) inline
Definition at line 75 of file GeoPrimitives.H.
References P.
     {
       P[0] = p[0];
       P[1] = p[1];
       P[2] = p[2];
       return(*this);
     };
double SolverUtils::GeoPrim::CPoint::norm () const inline
Definition at line 94 of file GeoPrimitives.H.
References x(), y(), and z().
Referenced by Distance(), operator<(), operator<=(), operator>(), and operator>=().
     {
       return(sqrt((x()*x()) + (y()*y()) + (z()*z())));
     };
bool SolverUtils::GeoPrim::CPoint::operator!= (const CPoint & p) const inline
Definition at line 104 of file GeoPrimitives.H.
     {
       return (!((*this)==p));
     };
CPoint SolverUtils::GeoPrim::CPoint::operator* (double num) const inline
Definition at line 140 of file GeoPrimitives.H.
References P.
     {
       CPoint rp(P[0]*num,P[1]*num,P[2]*num);
       return(rp);
     };
CPoint& SolverUtils::GeoPrim::CPoint::operator*= (double num) inline
Definition at line 145 of file GeoPrimitives.H.
References P.
     {
       P[0] *= num;
       P[1] *= num;
       P[2] *= num;
       return(*this);
     };
CPoint SolverUtils::GeoPrim::CPoint::operator+ (const CPoint & p) const inline
Definition at line 183 of file GeoPrimitives.H.
References P.
     {
       CPoint rp(P[0]+p.P[0],P[1]+p.P[1],P[2]+p.P[2]);
       return(rp);
     };
CPoint& SolverUtils::GeoPrim::CPoint::operator+= (const CPoint & p) inline
Definition at line 126 of file GeoPrimitives.H.
References P.
     {
       P[0] += p.P[0];
       P[1] += p.P[1];
       P[2] += p.P[2];
       return(*this);
     };
CPoint SolverUtils::GeoPrim::CPoint::operator- (const CPoint & p) const inline
Definition at line 188 of file GeoPrimitives.H.
References P.
     {
       CPoint rp(P[0]-p.P[0],P[1]-p.P[1],P[2]-p.P[2]);
       return(rp);
     };
CPoint& SolverUtils::GeoPrim::CPoint::operator-= (const CPoint & p) inline
Definition at line 133 of file GeoPrimitives.H.
References P.
     {
       P[0] -= p.P[0];
       P[1] -= p.P[1];
       P[2] -= p.P[2];
       return(*this);
     };
bool SolverUtils::GeoPrim::CPoint::operator< (const CPoint & p) const inline
Definition at line 108 of file GeoPrimitives.H.
References norm().
     {
       return (norm() < p.norm());
     };
bool SolverUtils::GeoPrim::CPoint::operator<= (const CPoint & p) const inline
Definition at line 116 of file GeoPrimitives.H.
References norm().
     {
       return ((norm() < p.norm()) ||
               (*this == p));
     };
CPoint& SolverUtils::GeoPrim::CPoint::operator= (const CPoint & p) inline
Definition at line 82 of file GeoPrimitives.H.
References P.
     {
       P[0] = p.P[0];
       P[1] = p.P[1];
       P[2] = p.P[2];
       return(*this);
     };
bool SolverUtils::GeoPrim::CPoint::operator== (const CPoint & p) const inline
Definition at line 98 of file GeoPrimitives.H.
References P, and SolverUtils::GeoPrim::TOL.
     {
       return( (fabs(P[0] - p.P[0]) < TOL) &&
               (fabs(P[1] - p.P[1]) < TOL) &&
               (fabs(P[2] - p.P[2]) < TOL) );
     };
bool SolverUtils::GeoPrim::CPoint::operator> (const CPoint & p) const inline
Definition at line 112 of file GeoPrimitives.H.
References norm().
     {
       return (norm() > p.norm());
     };
bool SolverUtils::GeoPrim::CPoint::operator>= (const CPoint & p) const inline
Definition at line 121 of file GeoPrimitives.H.
References norm().
     {
       return((norm() > p.norm()) ||
              (*this == p));
     };
const double& SolverUtils::GeoPrim::CPoint::operator[] (unsigned int i) const inline
Definition at line 173 of file GeoPrimitives.H.
References P.
     {
       if( i > 2 ) i = 0;
       return(P[i]);
     };
double& SolverUtils::GeoPrim::CPoint::operator[] (unsigned int i) inline
Definition at line 178 of file GeoPrimitives.H.
References P.
     {
       if (i > 2) i = 0;
       return(P[i]);
     };
CPoint& SolverUtils::GeoPrim::CPoint::reset () inline
Definition at line 204 of file GeoPrimitives.H.
References P.
Referenced by SolverUtils::GeoPrim::CBox::CBox().
     {
       P[0] = 0.0;
       P[1] = 0.0;
       P[2] = 0.0;
       return(*this);
     };
CPoint& SolverUtils::GeoPrim::CPoint::set (double ix, double iy, double iz) inline
Definition at line 197 of file GeoPrimitives.H.
References P.
     {
       P[0] = ix;
       P[1] = iy;
       P[2] = iz;
       return(*this);
     };
double& SolverUtils::GeoPrim::CPoint::x () inline
Definition at line 152 of file GeoPrimitives.H.
References P.
Referenced by SolverUtils::GeoPrim::CBox::AddPoint(), SolverUtils::GeoPrim::CBox::around(), SolverUtils::GeoPrim::C3Point::C3Point(), SolverUtils::GeoPrim::C3Vector::C3Vector(), SolverUtils::GeoPrim::CBox::CBox(), SolverUtils::GeoPrim::Centroid(), SolverUtils::GeoPrim::CBox::collide(), com_getptr_chr0d(), com_getptr_chr1d(), com_getptr_dbl0d(), com_getptr_dbl1d(), com_getptr_dbl2d(), com_getptr_dbl3d(), com_getptr_flt0d(), com_getptr_flt1d(), com_getptr_flt2d(), com_getptr_flt3d(), com_getptr_int0d(), com_getptr_int1d(), com_getptr_int2d(), com_getptr_int3d(), com_mapptr_chr1d(), com_mapptr_dbl0d(), com_mapptr_dbl1d(), com_mapptr_dbl2d(), com_mapptr_dbl3d(), com_mapptr_flt0d(), com_mapptr_flt1d(), com_mapptr_flt2d(), com_mapptr_flt3d(), com_mapptr_int0d(), com_mapptr_int1d(), com_mapptr_int2d(), com_mapptr_int3d(), SolverUtils::GeoPrim::CBox::contains(), SolverUtils::GeoPrim::CPlane::contains_point(), SolverUtils::GeoPrim::CPlane::CPlane(), SolverUtils::GeoPrim::CVector::CVector(), SolverUtils::GeoPrim::CPlane::D(), SolverUtils::GeoPrim::Distance(), SolverUtils::GeoPrim::CBox::empty(), SolverUtils::Mesh::GenerateCartesianGrid(), SolverUtils::GeoPrim::CLineSegment::has_point(), SolverUtils::GeoPrim::CBox::init(), SolverUtils::Mesh::NodalCoordinates::init_node(), SolverUtils::GeoPrim::CBox::intersect(), main(), SolverUtils::GeoPrim::CBox::merge(), norm(), SolverUtils::GeoPrim::operator*(), SolverUtils::GeoPrim::CVector::operator+=(), SolverUtils::GeoPrim::operator<<(), and SolverUtils::GeoPrim::CVector::operator=().
 { return P[0]; };
CPoint& SolverUtils::GeoPrim::CPoint::x (double i) inline
Definition at line 153 of file GeoPrimitives.H.
References P.
     {
       P[0] = i;
       return(*this);
     };
const double& SolverUtils::GeoPrim::CPoint::x () const inline
Definition at line 158 of file GeoPrimitives.H.
References P.
 { return P[0]; };
double& SolverUtils::GeoPrim::CPoint::y () inline
Definition at line 159 of file GeoPrimitives.H.
References P.
Referenced by SolverUtils::GeoPrim::CBox::AddPoint(), SolverUtils::GeoPrim::CBox::around(), SolverUtils::GeoPrim::C3Point::C3Point(), SolverUtils::GeoPrim::C3Vector::C3Vector(), SolverUtils::GeoPrim::CBox::CBox(), SolverUtils::GeoPrim::CBox::collide(), SolverUtils::GeoPrim::CBox::contains(), SolverUtils::GeoPrim::CPlane::contains_point(), SolverUtils::GeoPrim::CPlane::CPlane(), SolverUtils::GeoPrim::CVector::CVector(), SolverUtils::GeoPrim::CPlane::D(), SolverUtils::GeoPrim::Distance(), SolverUtils::GeoPrim::CBox::empty(), SolverUtils::Mesh::GenerateCartesianGrid(), SolverUtils::GeoPrim::CLineSegment::has_point(), SolverUtils::GeoPrim::CBox::init(), SolverUtils::Mesh::NodalCoordinates::init_node(), SolverUtils::GeoPrim::CBox::intersect(), main(), SolverUtils::GeoPrim::CBox::merge(), norm(), SolverUtils::GeoPrim::operator*(), SolverUtils::GeoPrim::CVector::operator+=(), SolverUtils::GeoPrim::operator<<(), and SolverUtils::GeoPrim::CVector::operator=().
 { return P[1]; };
CPoint& SolverUtils::GeoPrim::CPoint::y (double i) inline
Definition at line 160 of file GeoPrimitives.H.
References P.
     {
       P[1] = i;
       return(*this);
     };
const double& SolverUtils::GeoPrim::CPoint::y () const inline
Definition at line 165 of file GeoPrimitives.H.
References P.
 { return P[1]; };
double& SolverUtils::GeoPrim::CPoint::z () inline
Definition at line 166 of file GeoPrimitives.H.
References P.
Referenced by SolverUtils::GeoPrim::CBox::AddPoint(), SolverUtils::GeoPrim::CBox::around(), SolverUtils::GeoPrim::C3Point::C3Point(), SolverUtils::GeoPrim::C3Vector::C3Vector(), SolverUtils::GeoPrim::CBox::CBox(), SolverUtils::GeoPrim::CBox::collide(), SolverUtils::GeoPrim::CBox::contains(), SolverUtils::GeoPrim::CPlane::contains_point(), SolverUtils::GeoPrim::CPlane::CPlane(), SolverUtils::GeoPrim::CVector::CVector(), SolverUtils::GeoPrim::CPlane::D(), SolverUtils::GeoPrim::Distance(), SolverUtils::GeoPrim::CBox::empty(), SolverUtils::Mesh::GenerateCartesianGrid(), SolverUtils::GeoPrim::CLineSegment::has_point(), SolverUtils::GeoPrim::CBox::init(), SolverUtils::Mesh::NodalCoordinates::init_node(), SolverUtils::GeoPrim::CBox::intersect(), main(), SolverUtils::GeoPrim::CBox::merge(), norm(), SolverUtils::GeoPrim::operator*(), SolverUtils::GeoPrim::CVector::operator+=(), SolverUtils::GeoPrim::operator<<(), and SolverUtils::GeoPrim::CVector::operator=().
 { return P[2]; };
CPoint& SolverUtils::GeoPrim::CPoint::z (double i) inline
Definition at line 167 of file GeoPrimitives.H.
References P.
     {
       P[2] = i;
       return(*this);
     }
const double& SolverUtils::GeoPrim::CPoint::z () const inline
Definition at line 172 of file GeoPrimitives.H.
References P.
 { return P[2]; };
Friends And Related Function Documentation
double Distance (const CPoint & p, const GeoPrim::CLine & l) friend
Definition at line 38 of file GeoPrimitives.C.
   {
     double u = (((p.x() - l.p.x())*l.v.x() + (p.y() - l.p.y())*l.v.y() +
                  (p.z() - l.p.z())*l.v.z())/l.v.mag2());
     CPoint p2(l.p.x()+(u*l.v.x()),l.p.y()+(u*l.v.y()),l.p.z()+(u*l.v.z()));
     CVector v(p,p2);
     return(v.mag());
   }
CPoint operator* (double scalar, const CPoint & p) friend
Definition at line 145 of file GeoPrimitives.C.
   {
     GeoPrim::CPoint rv(p);
     rv.x() *= scalar;
     rv.y() *= scalar;
     rv.z() *= scalar;
     return(rv);
   }
std::ostream& operator<< (std::ostream & oSt, const CPoint & p) friend
Definition at line 89 of file GeoPrimitives.C.
   {
     oS << p.x() << "  " << p.y() << "  " << p.z();
     return(oS);
   }
std::istream& operator>> (std::istream & iSt, GeoPrim::CPoint & p) friend
Definition at line 96 of file GeoPrimitives.C.
   {
     iS >> p[0] >> p[1] >> p[2];
     return(iS);
   }
Member Data Documentation
double SolverUtils::GeoPrim::CPoint::P[3] protected
Definition at line 31 of file GeoPrimitives.H.
Referenced by CPoint(), init(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator=(), operator==(), operator[](), reset(), set(), x(), y(), and z().
The documentation for this class was generated from the following file:
GeoPrimitives.H