IMPACT: IRAD::Util::ConfigurationObject Class Reference
IRAD::Util::ConfigurationObject Class Reference
Detailed Description
Definition at line 28 of file Configuration.H.
#include <Configuration.H>
Public Member Functions
std::vector
< Util::ConfigParameters > & GetParameters ()
Util::ConfigParameters & Section (const std::string &section_name)
Extract parameters for particular section.
void AddSection (Util::ConfigParameters &params)
unsigned int SectionIndex (const std::string &section_name) const
std::string & NavigationSection (const std::string &section_name)
std::string NavigationSection (const std::string &section_name) const
std::vector< std::string > & NavigationSections ()
virtual std::string AdvanceToNextSection (std::istream &Inf)
virtual std::string ReadSection (std::istream &Inf)
virtual std::string ExtractSection (const std::string &section_name, std::istream &Inf)
Public Member Functions inherited from IRAD::Util::ConfigParameters
ConfigParameters ()
ConfigParameters (const std::string &name)
const std::string & Name () const
void Name (const std::string &name)
Public Member Functions inherited from IRAD::Util::Parameters
std::string GetValue (const std::string &key) const
std::vector< std::string > GetValueVector (const std::string &key) const
Util::ParamType * ParamPtr (const std::string &key)
template<typename T >
T GetValue (const std::string &key) const
template<typename T >
std::vector< T > GetValueVector (const std::string &key) const
virtual int SetValue (const std::string &key, const std::string &value)
virtual std::istream & ReadFromStream (std::istream &Is)
virtual std::ostream & WriteToStream (std::ostream &Os) const
std::string Param (const std::string &Key) const
bool IsSet (const std::string &Key) const
virtual ~Parameters ()
Private Attributes
std::vector
< Util::ConfigParameters > _parameters
std::vector< std::string > _sections
Friends
std::ostream & operator<< (std::ostream &Ostr, const Util::ConfigurationObject &cob)
Stream output operator for Util::ConfigurationObject.
std::istream & operator>> (std::istream &Istr, Util::ConfigurationObject &cob)
Stream input operator for Util::ConfigurationObject.
Additional Inherited Members
Public Attributes inherited from std::vector< T >
T elements
STL member.
Member Function Documentation
void IRAD::Util::ConfigurationObject::AddSection (Util::ConfigParameters & params) inline
Definition at line 38 of file Configuration.H.
References _parameters, and _sections.
 { _parameters.push_back(params); _sections.push_back("");};
std::string IRAD::Util::ConfigurationObject::AdvanceToNextSection (std::istream & Inf) virtual
Definition at line 77 of file Configuration.C.
References IRAD::Util::TokenizeString().
Referenced by IRAD::Util::operator>>().
     {
       std::string empty_retval;
       while(Inf)
         {
           std::string line;
           std::getline(Inf,line);
           if(!line.empty()){
             if(line[0] == '#'){
               std::vector<std::string> tokens;
               Util::TokenizeString(tokens,line);
               if(tokens[0] == "#Section")
                 if(tokens.size() > 1)
                   return(tokens[1]);
             }
           }
         }
       return(empty_retval);
     }
std::string IRAD::Util::ConfigurationObject::ExtractSection (const std::string & section_name, std::istream & Inf) virtual
Definition at line 53 of file Configuration.C.
References IRAD::Util::TokenizeString().
Referenced by IRAD::Util::operator>>().
     {
       while(Inf)
         {
           std::string line;
           std::getline(Inf,line);
           if(!line.empty()){
             if(line[0] == '#'){
               std::vector<std::string> tokens;
               Util::TokenizeString(tokens,line);
               if(tokens[0] == "#Section"){
                 if(tokens.size() > 1){
                   if(tokens[1] == section_name){
                     return (this->ReadSection(Inf));
                   }
                 }
               }
             }
           }
         }
       return(std::string(""));
     }
std::vector<Util::ConfigParameters>& IRAD::Util::ConfigurationObject::GetParameters () inline
Definition at line 36 of file Configuration.H.
References _parameters.
 { return(_parameters); };
std::string & IRAD::Util::ConfigurationObject::NavigationSection (const std::string & section_name)
Definition at line 45 of file Configuration.C.
     {
       return(_sections[SectionIndex(section_name)]);
     };
std::string IRAD::Util::ConfigurationObject::NavigationSection (const std::string & section_name) const
Definition at line 49 of file Configuration.C.
     {
       return(_sections[SectionIndex(section_name)]);
     };
std::vector<std::string>& IRAD::Util::ConfigurationObject::NavigationSections () inline
Definition at line 42 of file Configuration.H.
References _sections.
 { return (_sections); };
std::string IRAD::Util::ConfigurationObject::ReadSection (std::istream & Inf) virtual
Definition at line 97 of file Configuration.C.
References SolverUtils::Ostr, and IRAD::Util::TokenizeString().
Referenced by IRAD::Util::operator>>().
     {
       std::ostringstream Ostr;
       while(Inf)
         {
           int open_sections = 1;
           std::string line;
           std::getline(Inf,line);
           if(line[0] == '#'){
             std::vector<std::string> tokens;
             Util::TokenizeString(tokens,line);
             if(tokens[0] == "#EndSection") {
               open_sections = open_sections - 1;
               if(open_sections == 0)
                 return(Ostr.str());
             }
             else if(tokens[0] == "#Section") {
               open_sections++;
               Ostr << line;
             }
           }
           Ostr << line << std::endl;
         }
       return(Ostr.str());
     }
Util::ConfigParameters & IRAD::Util::Util::ConfigurationObject::Section (const std::string & section_name)
Definition at line 13 of file Configuration.C.
{
       if(section_name == Name())
         return(*this);
       std::vector<Util::ConfigParameters>::iterator pi = _parameters.begin();
       while(pi != _parameters.end()){
         if(pi->Name() == section_name)
           return(_parameters[pi-_parameters.begin()]);
         pi++;
       }
       std::cerr << "Util::ConfigurationObject::GetSectionParameters::Fatal Error - Section "
                 << section_name << " does not exist. Exiting." << std::endl;
       Util::Error err = 1;
       throw err;
       exit(1);
       return(_parameters[0]);
     };
unsigned int IRAD::Util::ConfigurationObject::SectionIndex (const std::string & section_name) const
Definition at line 31 of file Configuration.C.
{
       std::vector<Util::ConfigParameters>::const_iterator pi = _parameters.begin();
       unsigned int index = 0;
       if(section_name != Name()){
         while(pi != _parameters.end()){
           if(pi->Name() == section_name)
             return (index+1);
           pi++;
           index++;
         }
       }
       return(index);
     };
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & Ostr, const Util::ConfigurationObject & cob) friend
std::istream& operator>> (std::istream & Istr, Util::ConfigurationObject & cob) friend
Member Data Documentation
std::vector<Util::ConfigParameters> IRAD::Util::ConfigurationObject::_parameters private
Definition at line 33 of file Configuration.H.
Referenced by AddSection(), GetParameters(), IRAD::Util::operator<<(), and IRAD::Util::operator>>().
std::vector<std::string> IRAD::Util::ConfigurationObject::_sections private
Definition at line 34 of file Configuration.H.
Referenced by AddSection(), NavigationSections(), IRAD::Util::operator<<(), and IRAD::Util::operator>>().
The documentation for this class was generated from the following files:
Configuration.H
Configuration.C