IMPACT: IRAD::Sys::Environment Class Reference
IRAD::Sys::Environment Class Reference
Detailed Description
Definition at line 61 of file UnixUtils.H.
#include <UnixUtils.H>
Public Member Functions
Environment ()
int SetEnv (const std::string &, const std::string &, bool)
void UnSetEnv (const std::string &)
int ClearEnv ()
const std::string GetEnv (const std::string &) const
std::string & GetEnv (const std::string &)
int PutEnv (char *)
void Refresh ()
char ** GetRawEnv ()
Private Member Functions
void init ()
Private Attributes
std::string empty_string
Additional Inherited Members
Public Attributes inherited from std::vector< T >
T elements
STL member.
Constructor & Destructor Documentation
IRAD::Sys::Environment::Environment ()
Definition at line 250 of file UnixUtils.C.
References init().
     {
       this->init();
     }
Member Function Documentation
int IRAD::Sys::Environment::ClearEnv ()
Definition at line 291 of file UnixUtils.C.
References init().
     {
       clearenv();
       this->init();
       return(1);
     }
const std::string IRAD::Sys::Environment::GetEnv (const std::string & var) const
Definition at line 300 of file UnixUtils.C.
     {
       Environment::const_iterator ei = this->begin();
       while(ei != this->end()){
         if((*ei).first == var)
           return((*ei).second);
         ei++;
       }
       return(std::string(""));
     }
std::string & IRAD::Sys::Environment::GetEnv (const std::string & var)
Definition at line 312 of file UnixUtils.C.
References empty_string.
     {
       Environment::iterator ei = this->begin();
       while(ei != this->end()){
         if((*ei).first == var)
           return((*ei).second);
         ei++;
       }
       empty_string.clear();
       return(empty_string);
     }
char ** IRAD::Sys::Environment::GetRawEnv ()
Definition at line 339 of file UnixUtils.C.
References environ.
     {
       return(environ);
     }
void IRAD::Sys::Environment::init () private
Definition at line 256 of file UnixUtils.C.
References environ.
Referenced by ClearEnv(), Environment(), PutEnv(), Refresh(), SetEnv(), and UnSetEnv().
     {
       this->clear();
       std::vector<std::string> raw_env;
       unsigned int i = 0;
       while(environ[i])
         raw_env.push_back(environ[i++]);
       //    Util::Vectorize(raw_env,(const char **)environ);
       std::vector<std::string>::iterator rei = raw_env.begin();
       while(rei != raw_env.end()){
         unsigned int x = (*rei).find("=");
         std::string var((*rei).substr(0,x));
         std::string val((*rei).substr(x+1));
         this->push_back(make_pair(var,val));
         rei++;
       }
     }
int IRAD::Sys::Environment::PutEnv (char * envs)
Definition at line 325 of file UnixUtils.C.
References init().
     {
       int retVal = putenv(envs);
       this->init();
       return(retVal);
     }
void IRAD::Sys::Environment::Refresh ()
Definition at line 333 of file UnixUtils.C.
References init().
     {
       this->init();
     }
int IRAD::Sys::Environment::SetEnv (const std::string & var, const std::string & val, bool ow)
Definition at line 275 of file UnixUtils.C.
References init().
     {
       int retVal = setenv(var.c_str(),val.c_str(),(int)ow);
       this->init();
       return(retVal);
     }
void IRAD::Sys::Environment::UnSetEnv (const std::string & var)
Definition at line 283 of file UnixUtils.C.
References init().
     {
       unsetenv(var.c_str());
       this->init();
     }
Member Data Documentation
std::string IRAD::Sys::Environment::empty_string private
Definition at line 77 of file UnixUtils.H.
Referenced by GetEnv().
The documentation for this class was generated from the following files:
UnixUtils.H
UnixUtils.C