IMPACT: NewDataItem Class Reference
NewDataItem Class Reference
Detailed Description
Definition at line 89 of file Agent.h.
#include <Agent.h>
Public Member Functions
NewDataItem (Agent *ag, std::string target_window_, std::string attr_, char loc_, int type_, int ncomp_, const char *unit_)
void create (std::string bufname)
Public Member Functions inherited from DataItemBase
DataItemBase (Agent *ag, std::string target_window_, std::string attr_)
virtual ~DataItemBase ()
virtual void assign (std::string bufname)
Protected Attributes
char loc
int type
int ncomp
const char * unit
Additional Inherited Members
Public Attributes inherited from DataItemBase
Agent * agent
std::string target_window
std::string attr
Constructor & Destructor Documentation
NewDataItem::NewDataItem (Agent * ag, std::string target_window_, std::string attr_, char loc_, int type_, int ncomp_, const char * unit_)
Definition at line 86 of file Agent.C.
                                                                                                                                    :
                 DataItemBase(ag, target_window_, attr_),
                 loc(loc_), type(type_), ncomp(ncomp_), unit(unit_)
 {
 }
Member Function Documentation
void NewDataItem::create (std::string bufname) virtual
Reimplemented from DataItemBase.
Definition at line 92 of file Agent.C.
References DataItemBase::attr, COM_get_dataitem(), COM_get_dataitem_handle(), COM_new_dataitem(), COM_resize_array(), loc, MAN_DEBUG, ncomp, type, and unit.
 {
   // test if already created
   if (COM_get_dataitem_handle( bufname+attr) > 0) {
     char loc_;
     int type_;
     int ncomp_;
     std::string unit_;
     COM_get_dataitem( bufname+attr, &loc_, &type_, &ncomp_, &unit_);
     if (loc_ != loc || type_ != type || ncomp_ != ncomp || unit_ != unit) {
       std::cout << "ROCMAN Error: NewDataItem::create(): Could not create " << bufname+attr << " in two different ways " << std::endl;
       MPI_Abort(MPI_COMM_WORLD, -1);
     }
     else
       return;
   }
   MAN_DEBUG(2, ("NewDataItem::create: %s%s.\n", bufname.c_str(), attr.c_str()));
   COM_new_dataitem( bufname+attr, loc, type, ncomp, unit);
   COM_resize_array( bufname+attr);
 }
Member Data Documentation
char NewDataItem::loc protected
Definition at line 92 of file Agent.h.
Referenced by create().
int NewDataItem::ncomp protected
Definition at line 94 of file Agent.h.
Referenced by create().
int NewDataItem::type protected
Definition at line 93 of file Agent.h.
Referenced by create().
const char* NewDataItem::unit protected
Definition at line 95 of file Agent.h.
Referenced by create().
The documentation for this class was generated from the following files:
Agent.h
Agent.C