IMPACT: SolverUtils::FEM::SolutionMetaData Class Reference
SolverUtils::FEM::SolutionMetaData Class Reference
Detailed Description
Definition at line 162 of file FieldData.H.
#include <FieldData.H>
Public Member Functions
void Copy (const SolutionMetaData &inMetaData)
void ReadFromStream (std::istream &InStr)
void WriteToStream (std::ostream &OutStr)
void AddField (const std::string &name, char loc, unsigned int ncomp, unsigned int dsize, const std::string &unit)
Member Function Documentation
void SolverUtils::FEM::SolutionMetaData::AddField (const std::string & name, char loc, unsigned int ncomp, unsigned int dsize, const std::string & unit) inline
Definition at line 197 of file FieldData.H.
References SolverUtils::FEM::FieldMetaData::dsize, SolverUtils::FEM::FieldMetaData::loc, SolverUtils::FEM::FieldMetaData::name, SolverUtils::FEM::FieldMetaData::ncomp, and SolverUtils::FEM::FieldMetaData::unit.
Referenced by COM::TestModule::InitSolver(), and COM::TransferSolver::Setup().
     {
       FEM::FieldMetaData md;
       md.name = name;
       md.unit = unit;
       md.loc = loc;
       md.ncomp = ncomp;
       md.dsize = dsize;
       this->push_back(md);
     };
void SolverUtils::FEM::SolutionMetaData::Copy (const SolutionMetaData & inMetaData) inline
Definition at line 165 of file FieldData.H.
     {
       this->resize(0);
       std::vector<FEM::FieldMetaData>::const_iterator imdIt = inMetaData.begin();
       while(imdIt != inMetaData.end())
         this->push_back(*imdIt++);
       return;
     }
void SolverUtils::FEM::SolutionMetaData::ReadFromStream (std::istream & InStr) inline
Definition at line 173 of file FieldData.H.
Referenced by SolverUtils::FEM::SolverAgent::ReadSolnMetaFromStream(), and SolverUtils::FEM::FDSolverAgent::ReceiveSolnMeta().
     {
       int num_vars;
       std::string line;
       while(line.empty())
         std::getline(InStr,line);
       std::istringstream Istr(line);
       Istr >> num_vars;
       this->resize(num_vars);
       int num = 0;
       while(num < num_vars){
         std::getline(InStr,line);
         std::istringstream IStr(line);
         IStr >> (*this)[num++];
       }
     };
void SolverUtils::FEM::SolutionMetaData::WriteToStream (std::ostream & OutStr) inline
Definition at line 189 of file FieldData.H.
Referenced by SolverUtils::FEM::FDSolverAgent::SendSolnMeta(), and SolverUtils::FEM::SolverAgent::WriteSolnMetaToStream().
     {
       int num_vars = this->size();
       int num = 0;
       OutStr << num_vars << std::endl;
       while(num < num_vars)
         OutStr << (*this)[num++] << std::endl;
     };
The documentation for this class was generated from the following file:
FieldData.H