IMPACT: Rocmap Class Reference
Rocmap Class Reference
Detailed Description
Definition at line 18 of file Rocmap.h.
#include <Rocmap.h>
Public Member Functions
Rocmap ()
Static Public Member Functions
static void load (const std::string &mname)
Loads Rocmap onto Roccom with a given module name.
static void unload (const std::string &mname)
Unloads Rocmap from Roccom.
static void compute_pconn (const COM::DataItem *mesh, COM::DataItem *pconn)
Compute pane connectivity map between shared nodes.
static void pane_border_nodes (const COM::DataItem *mesh, COM::DataItem *isborder, int *ghost_level=NULL)
Determine the nodes at pane boundaries of a given mesh.
static void size_of_cpanes (const COM::DataItem *pconn, const int *pane_id, int *npanes_total, int *npanes_ghost=NULL)
Get the number of communicating panes.
static void reduce_average_on_shared_nodes (COM::DataItem *att, COM::DataItem *pconn=NULL)
Perform an average-reduction on the shared nodes for the given attribute.
static void reduce_maxabs_on_shared_nodes (COM::DataItem *att, COM::DataItem *pconn=NULL)
Perform a maxabs-reduction on the shared nodes for the given attribute.
static void reduce_minabs_on_shared_nodes (COM::DataItem *att, COM::DataItem *pconn=NULL)
Perform a minabs-reduction on the shared nodes for the given attribute.
static void update_ghosts (COM::DataItem *att, const COM::DataItem *pconn=NULL)
Update ghost nodal or elemental values for the given attribute.
Constructor & Destructor Documentation
Rocmap::Rocmap () inline
Definition at line 20 of file Rocmap.h.
 {}
Member Function Documentation
MAP_BEGIN_NAMESPACE void Rocmap::compute_pconn (const COM::DataItem * mesh, COM::DataItem * pconn) static
If pconn was not yet initialized, this routine will allocate memory for it. Otherwise, this routine will copy up to the capacity of the array
Definition at line 17 of file Rocmap.C.
References Pane_connectivity::compute_pconn().
Referenced by load().
{
   // Compute the pane connectivity from scratch
   Pane_connectivity pc( mesh, mesh->window()->get_communicator());
   pc.compute_pconn( pconn);
 }
void Rocmap::load (const std::string & mname) static
Definition at line 85 of file Rocmap.C.
References COM_INT, COM_METADATA, COM_new_window(), COM_set_function(), COM_window_init_done(), compute_pconn(), pane_border_nodes(), reduce_average_on_shared_nodes(), reduce_maxabs_on_shared_nodes(), reduce_minabs_on_shared_nodes(), size_of_cpanes(), and update_ghosts().
Referenced by SurfMap_load_module(), surfmap_load_module(), SURFMAP_LOAD_MODULE(), surfmap_load_module_(), and SURFMAP_LOAD_MODULE_().
{
   COM_new_window( mname.c_str());
   COM_Type types[4];
   types[0] = COM_METADATA;
   types[1] = COM_METADATA;
   COM_set_function( (mname+".reduce_average_on_shared_nodes").c_str(),
                     (Func_ptr)reduce_average_on_shared_nodes, "iI", types);
   COM_set_function( (mname+".reduce_maxabs_on_shared_nodes").c_str(),
                     (Func_ptr)reduce_maxabs_on_shared_nodes, "iI", types);
   COM_set_function( (mname+".reduce_minabs_on_shared_nodes").c_str(),
                     (Func_ptr)reduce_minabs_on_shared_nodes, "iI", types);
   COM_set_function( (mname+".update_ghosts").c_str(),
                     (Func_ptr)update_ghosts, "iI", types);
   types[0] = types[1] = COM_METADATA;
   COM_set_function( (mname+".compute_pconn").c_str(),
                     (Func_ptr)compute_pconn, "io", types);
   types[0] = types[1] = COM_METADATA; types[2] = COM_INT;
   COM_set_function( (mname+".pane_border_nodes").c_str(),
                     (Func_ptr)pane_border_nodes, "ioI", types);
   types[0] = COM_METADATA;
   types[1] = types[2] = types[3] = COM_INT;
   COM_set_function( (mname+".size_of_cpanes").c_str(),
                     (Func_ptr)size_of_cpanes, "iioO", types);
   COM_window_init_done( mname.c_str());
 }
void Rocmap::pane_border_nodes (const COM::DataItem * mesh, COM::DataItem * isborder, int * ghost_level = NULL) static
The argument isborder must be a nodal attribute of integer type. At return, isborder is set to 1 for border nodes, and 0 for others
Definition at line 26 of file Rocmap.C.
References Pane_boundary::determine_borders().
Referenced by load().
{
   Pane_boundary::determine_borders( mesh, isborder, ghost_level?*ghost_level:0);
 }
void Rocmap::reduce_average_on_shared_nodes (COM::DataItem * att, COM::DataItem * pconn = NULL) static
Definition at line 40 of file Rocmap.C.
References Pane_communicator::init().
Referenced by load().
{
   Pane_communicator pc(att->window(), att->window()->get_communicator());
   pc.init(att,pconn);
   pc.begin_update_shared_nodes();
   pc.reduce_average_on_shared_nodes();
   pc.end_update_shared_nodes();
 }
void Rocmap::reduce_maxabs_on_shared_nodes (COM::DataItem * att, COM::DataItem * pconn = NULL) static
Definition at line 60 of file Rocmap.C.
References Pane_communicator::init().
Referenced by load().
{
   Pane_communicator pc(att->window(), att->window()->get_communicator());
   pc.init(att,pconn);
   pc.begin_update_shared_nodes();
   pc.reduce_maxabs_on_shared_nodes();
   pc.end_update_shared_nodes();
 }
void Rocmap::reduce_minabs_on_shared_nodes (COM::DataItem * att, COM::DataItem * pconn = NULL) static
Definition at line 50 of file Rocmap.C.
References Pane_communicator::init().
Referenced by load().
{
   Pane_communicator pc(att->window(), att->window()->get_communicator());
   pc.init(att,pconn);
   pc.begin_update_shared_nodes();
   pc.reduce_minabs_on_shared_nodes();
   pc.end_update_shared_nodes();
 }
void Rocmap::size_of_cpanes (const COM::DataItem * pconn, const int * pane_id, int * npanes_total, int * npanes_ghost = NULL) static
Definition at line 33 of file Rocmap.C.
References Pane_connectivity::size_of_cpanes().
Referenced by load().
{
   Pane_connectivity::size_of_cpanes(pconn, pane_id, npanes_total, npanes_ghost);
 }
void Rocmap::unload (const std::string & mname) static
Definition at line 119 of file Rocmap.C.
References COM_delete_window().
Referenced by SurfMap_unload_module(), surfmap_unload_module(), SURFMAP_UNLOAD_MODULE(), surfmap_unload_module_(), and SURFMAP_UNLOAD_MODULE_().
{
   COM_delete_window( mname.c_str());
 }
void Rocmap::update_ghosts (COM::DataItem * att, const COM::DataItem * pconn = NULL) static
Definition at line 70 of file Rocmap.C.
References Pane_communicator::init().
Referenced by load().
{
   Pane_communicator pc(att->window(), att->window()->get_communicator());
   pc.init(att, pconn);
   if (att->is_elemental()){
     pc.begin_update_ghost_cells();
     pc.end_update_ghost_cells();
   }
   else{
     pc.begin_update_ghost_nodes();
     pc.end_update_ghost_nodes();
   }
 }
The documentation for this class was generated from the following files:
Rocmap.h
Rocmap.C