IMPACT: Halfedge Class Reference
Halfedge Class Reference
This class encapsulate a halfedge over a window manifold.
Detailed Description
Definition at line 464 of file Manifold_2.h.
#include <Manifold_2.h>
Public Member Functions
Halfedge ()
Halfedge (const Pane_manifold_2 *pm, Edge_ID e, Access_Mode mode=ACROSS_PANE)
Construct a Halfedge object from a pane manifold and its edge ID.
Halfedge opposite () const
Get the ID of the opposite edge of a given edge.
Face face () const
Obtain the (primary copy of the) origin of the edge.
Halfedge prev () const
Get the previous halfedge of its owner element.
Halfedge next () const
Get the next halfedge of its owner element.
Node origin () const
Obtain the (primary copy of the) origin of the edge.
Node destination () const
Obtain the (primary copy of the) destination of the edge.
bool is_border () const
Is the edge a border edge?
bool is_physical_border () const
Is the edge on the physical boundary?
Vector_3< Real > tangent () const
Get the tangent of the given halfedge.
Vector_3< Real > normal () const
Get the normal of the incident facet.
Vector_3< Real > deformed_normal (const COM::DataItem *disp) const
Get the normal of the deformed shape (coordinates plus given displacements) of the incident facet of the halfedge.
void edge_center (Point_3< Real > &mid) const
Get the edge center of the given halfedge.
void face_center (Point_3< Real > &cnt) const
Get the face center of the incident face of a given halfedge.
template<class Value >
void edge_average (const COM::DataItem *attr, Value &val) const
Get the avarage value of the nodes of a given halfedge.
template<class Value >
void face_average (const COM::DataItem *attr, Value &val) const
Get the average value of the nodes of the incident face of a given halfedge.
double dihedral_angle () const
Return the dihedral angle at the edge.
const Pane_manifold_2 * pane_manifold () const
Obtain the pane manifold that owns the edge.
const COM::Pane * pane () const
Obtain the owner Pane_manifold_2 of the node.
Edge_ID id () const
Obtain the ID of the edge.
const void * addr (const COM::DataItem *attr) const
Obtain the address of an dataitem associated with its bounded element.
const COM::DataItem * attr (const COM::DataItem *a) const
Obtain the dataitem on the parent pane of the node.
bool operator== (const Halfedge &h) const
Are two halfedges the same?
bool operator!= (const Halfedge &h) const
Are two halfedges different?
bool operator< (const Halfedge &h) const
Does the current halfedge has a smaller ID then the given one?
Protected Attributes
const Pane_manifold_2 * _pm
Edge_ID _eID
Access_Mode _mode
Constructor & Destructor Documentation
Halfedge::Halfedge () inline
Definition at line 466 of file Manifold_2.h.
 : _pm(NULL) {}
Halfedge::Halfedge (const Pane_manifold_2 * pm, Edge_ID e, Access_Mode mode = ACROSS_PANE) inline
Definition at line 469 of file Manifold_2.h.
     : _pm( pm), _eID( e), _mode(mode) {}
Member Function Documentation
const void * Halfedge::addr (const COM::DataItem * attr) const
Note: This function can be slow O(1) if the dataitem is not on the current pane, and is even slower (O(log(#panes)) if not owned by the owner window of the pane.
Definition at line 1251 of file Manifold_2.C.
References _eID, _pm, attr(), COM_assertion, COM_assertion_msg, COM_get_sizeof(), is_border(), and Simple_manifold_2::pane().
{
   COM_assertion( !is_border());
   COM_assertion_msg( a, "Unexpected NULL pointer");
   COM_assertion_msg( a->is_elemental(), "Expect a element-centered dataitem");
   const COM::DataItem *attr;
   const COM::Pane *pn = _pm->pane();
   int pid = pn->id();
   if ( a->pane()->id() == pid)
     attr = a;
   else {
     if ( a->window() != pn->window()) {
       pn = &a->window()->pane( pid);
       COM_assertion_msg( pn, "Pane does not exist");
     }
     attr=pn->dataitem( a->id());
     COM_assertion_msg( attr, "DataItem does not exist");
   }
   return ((const char*)attr->pointer()) +
     COM_get_sizeof( attr->data_type(), attr->stride()*(_eID.eid()-1));
 }
const COM::DataItem* Halfedge::attr (const COM::DataItem * a) const inline
Definition at line 578 of file Manifold_2.h.
References _pm, COM_assertion_msg, and Simple_manifold_2::pane().
Referenced by addr().
{
     COM_assertion_msg( a, "Unexpected NULL pointer");
     return a->window()->pane( _pm->pane()->id()).dataitem(a->id());
   }
Vector_3< Real > Halfedge::deformed_normal (const COM::DataItem * disp) const
Definition at line 1326 of file Manifold_2.C.
References get_deformed_normal().
{
   return get_deformed_normal( *this, Vector_2<Real>( 0.5, 0.5), disp);
 }
Node Halfedge::destination () const inline
Definition at line 494 of file Manifold_2.h.
References _eID, _mode, _pm, Simple_manifold_2::get_destination(), and Pane_manifold_2::get_primary().
Referenced by edge_average(), and tangent().
   { return _pm->get_primary( _pm->get_destination( _eID), _mode); }
double Halfedge::dihedral_angle () const
If the edge is a border edge, then return pi.
If the edge is a border edge, then return pi. Note that this must be called after update_bd_normals has been called.
Definition at line 1333 of file Manifold_2.C.
References is_physical_border(), normal(), and opposite().
{
   const double pi=3.14159265358979;
   if ( is_physical_border()) return pi;
   Halfedge hopp = opposite();
   if ( hopp.is_physical_border()) return pi;
   Vector_3<Real> normals[2] = { normal(), hopp.normal() };
   double cos_a = normals[0]*normals[1]
     / std::sqrt( (normals[0]*normals[0])*(normals[1]*normals[1]));
   // Resolve roundoff error
   if ( cos_a>1) cos_a=1;
   if ( cos_a<-1) cos_a=-1;
   return std::acos( cos_a);
 }
template<class Value > void Halfedge::edge_average (const COM::DataItem * attr, Value & val) const inline
Value must have operators + and * defined.
Definition at line 530 of file Manifold_2.h.
References Node::addr(), destination(), and origin().
Referenced by edge_center(), and face_average().
{
     val = 0.5*(*reinterpret_cast<const Value *>(destination().addr(attr))+
                *reinterpret_cast<const Value *>(origin().addr(attr)));
   }
void Halfedge::edge_center (Point_3< Real > & mid) const inline
Definition at line 517 of file Manifold_2.h.
References _pm, COM_NC, edge_average(), and Simple_manifold_2::pane().
   { edge_average( _pm->pane()->dataitem( COM::COM_NC),
                   reinterpret_cast<Vector_3<Real> &>(mid)); }
Face Halfedge::face () const inline
Definition at line 799 of file Manifold_2.h.
References _eID, _mode, and _pm.
 { return Face(_pm, _eID.eid(),_mode); }
template<class Value > void Halfedge::face_average (const COM::DataItem * attr, Value & val) const inline
If this is a border halfedge, then return its edge averagd. Value must have operators + and * defined.
Definition at line 539 of file Manifold_2.h.
References Node::addr(), edge_average(), is_border(), next(), and origin().
Referenced by face_center().
{
     // If this is a border halfedge, then return its edge center.
     if ( is_border()) { edge_average( attr, val); return; }
     // Otherwise, compute the center
     val = Value(0);
     int count=0;
     Halfedge h=*this, h0=h;
     do {
       val += *reinterpret_cast<const Value*>(h.origin().addr( attr));
       ++count;
     } while ( (h=h.next()) != h0);
     val/=count;
   }
void Halfedge::face_center (Point_3< Real > & cnt) const inline
If this is a border halfedge, then return its midpoint.
Definition at line 523 of file Manifold_2.h.
References _pm, COM_NC, face_average(), and Simple_manifold_2::pane().
   { face_average( _pm->pane()->dataitem( COM::COM_NC),
                   reinterpret_cast<Vector_3<Real> &>(cnt)); }
Edge_ID Halfedge::id () const inline
Definition at line 569 of file Manifold_2.h.
References _eID.
Referenced by get_normal(), Node::halfedge(), and Overlay::number_subfaces().
 { return _eID; }
bool Halfedge::is_border () const inline
Definition at line 498 of file Manifold_2.h.
References _eID, _mode, _pm, and Pane_manifold_2::is_border_edge().
Referenced by addr(), Rocsurf::compute_edge_lengths(), Window_manifold_2::determine_primaries(), face_average(), Pane_manifold_2::get_next_edge(), get_normal(), Pane_manifold_2::get_prev_edge(), and Node::is_border().
   { return _pm->is_border_edge( _eID, _mode); }
bool Halfedge::is_physical_border () const inline
Definition at line 502 of file Manifold_2.h.
References _eID, _pm, and Pane_manifold_2::is_physical_border_edge().
Referenced by dihedral_angle().
   { return _pm->is_physical_border_edge( _eID); }
Halfedge Halfedge::next () const inline
If the current edge is a border edges, it returns the next border edge along the boundary.
Definition at line 487 of file Manifold_2.h.
References _eID, _mode, _pm, and Pane_manifold_2::get_next_edge().
Referenced by Rocsurf::compute_edge_lengths(), face_average(), Face::face_average(), get_deformed_normal(), and Pane_manifold_2::get_prev_edge().
 { return _pm->get_next_edge( _eID, _mode); }
Vector_3< Real > Halfedge::normal () const
Definition at line 1295 of file Manifold_2.C.
References get_normal().
Referenced by dihedral_angle().
{
   return get_normal( *this, Vector_2<Real>( 0.5, 0.5));
 }
bool Halfedge::operator!= (const Halfedge & h) const inline
Definition at line 588 of file Manifold_2.h.
References _eID, and _pm.
   { return _pm!=h._pm || _eID!=h._eID; }
bool Halfedge::operator< (const Halfedge & h) const inline
Definition at line 592 of file Manifold_2.h.
References _eID, _pm, and Simple_manifold_2::pane().
{
     int pid1=_pm->pane()->id(), pid2=h._pm->pane()->id();
     return pid1<pid2 || pid1==pid2 && _eID<h._eID;
   }
bool Halfedge::operator== (const Halfedge & h) const inline
Definition at line 584 of file Manifold_2.h.
References _eID, and _pm.
   { return _pm==h._pm && _eID==h._eID; }
Halfedge Halfedge::opposite () const inline
Definition at line 473 of file Manifold_2.h.
References _eID, _mode, _pm, and Pane_manifold_2::get_opposite_edge().
Referenced by Rocsurf::compute_edge_lengths(), dihedral_angle(), Pane_manifold_2::get_next_edge(), Pane_manifold_2::get_prev_edge(), and Node::halfedge().
   { return _pm->get_opposite_edge( _eID, _mode); }
Node Halfedge::origin () const inline
Definition at line 490 of file Manifold_2.h.
References _eID, _mode, _pm, Simple_manifold_2::get_origin(), and Pane_manifold_2::get_primary().
Referenced by edge_average(), face_average(), Face::face_average(), get_deformed_normal(), and tangent().
   { return _pm->get_primary( _pm->get_origin( _eID), _mode); }
const COM::Pane* Halfedge::pane () const inline
Definition at line 565 of file Manifold_2.h.
References _pm, and Simple_manifold_2::pane().
Referenced by get_normal(), and Pane_manifold_2::size_of_edges().
   { if ( _pm) return _pm->pane(); else return NULL; }
const Pane_manifold_2* Halfedge::pane_manifold () const inline
Definition at line 562 of file Manifold_2.h.
References _pm.
Referenced by get_normal(), Pane_manifold_2::get_opposite_edge(), Node::halfedge(), Pane_manifold_2::is_border_edge(), and Pane_manifold_2::size_of_edges().
 { return _pm; }
Halfedge Halfedge::prev () const inline
If the current edge is a border edges, it returns the previous border edge along the boundary.
Definition at line 482 of file Manifold_2.h.
References _eID, _mode, _pm, and Pane_manifold_2::get_prev_edge().
Referenced by Pane_manifold_2::get_next_edge(), and Node::halfedge().
 { return _pm->get_prev_edge( _eID, _mode); }
Vector_3<Real> Halfedge::tangent () const inline
Definition at line 506 of file Manifold_2.h.
References destination(), origin(), and Node::point().
Referenced by Rocsurf::compute_edge_lengths(), and get_tangent().
   { return destination().point()-origin().point(); }
Member Data Documentation
Edge_ID Halfedge::_eID protected
Definition at line 599 of file Manifold_2.h.
Referenced by addr(), destination(), face(), id(), is_border(), is_physical_border(), next(), operator!=(), operator<(), operator==(), opposite(), origin(), and prev().
Access_Mode Halfedge::_mode protected
Definition at line 600 of file Manifold_2.h.
Referenced by destination(), face(), is_border(), next(), opposite(), origin(), and prev().
const Pane_manifold_2* Halfedge::_pm protected
Definition at line 598 of file Manifold_2.h.
Referenced by addr(), attr(), destination(), edge_center(), face(), face_center(), is_border(), is_physical_border(), next(), operator!=(), operator<(), operator==(), opposite(), origin(), pane(), pane_manifold(), and prev().
The documentation for this class was generated from the following files:
Manifold_2.h
Manifold_2.C