IMPACT: BCInitInvoker Class Reference
BCInitInvoker Class Reference
Detailed Description
Definition at line 80 of file basic_actions.h.
#include <basic_actions.h>
Public Member Functions
BCInitInvoker (Agent *ag)
void init (double t)
void run (double t, double dt, double alpha)
Public Member Functions inherited from Action
Action (void *p=0, const char *name=NULL)
Action (int n, const char **at, int *i=NULL, void *p=0, const char *name=NULL)
Action (int n, const std::string at[], int *i=NULL, void *p=0, const char *name=NULL)
virtual ~Action ()
virtual void declare (Scheduler &)
virtual void finalize ()
virtual const char * name ()
void set_name (const char *name)
virtual void print (FILE *f)
virtual void print_toposort (FILE *f)
virtual void schedule ()
Private Attributes
Agent * agent
Additional Inherited Members
Protected Types inherited from Action
enum { IN =1, OUT =2, INOUT =3 }
Protected Member Functions inherited from Action
int get_dataitem_handle (int i)
int get_dataitem_handle_const (int i)
int get_dataitem_handle (const std::string str)
void set_attr (int n, const std::string at[], int *id=NULL)
void set_attr (int n, const char *at[], int *id=NULL)
void set_io (int n, const int *io)
void set_io (const char *io)
int get_io (int i)
Protected Attributes inherited from Action
const char * action_name
char ** attr
int * idx
int count
void * usr_ptr
std::vector< int > inout
Constructor & Destructor Documentation
BCInitInvoker::BCInitInvoker (Agent * ag)
Definition at line 136 of file basic_actions.C.
References Action::set_attr(), and Action::set_io().
                                       :
       Action( 0, (const char**)NULL, NULL, NULL, "BCInitInvoker"),
       agent(ag)
 {
   set_io( 0, NULL);
   set_attr(0, (const char**)NULL);
 }
Member Function Documentation
void BCInitInvoker::init (double t) virtual
Reimplemented from Action.
Definition at line 144 of file basic_actions.C.
References agent, Agent::get_agent_name(), Agent::init_bcinitaction(), and MAN_DEBUG.
{
   MAN_DEBUG(1, ("Rocman: BCInitInvoker::init() agent: %s .\n", agent->get_agent_name().c_str()));
     //  init bcactions
   agent->init_bcinitaction(t);
   MAN_DEBUG(1, ("Rocman: BCInitInvoker::init() agent: %s DONE.\n", agent->get_agent_name().c_str()));
 }
void BCInitInvoker::run (double t, double dt, double alpha) virtual
Reimplemented from Action.
Definition at line 151 of file basic_actions.C.
References agent, Agent::get_agent_name(), MAN_DEBUG, and Agent::run_bcinitaction().
{
   MAN_DEBUG(1, ("Rocman: BCInitInvoker::run() agent: %s t:%e dt:%e alpha:%e.\n", agent->get_agent_name().c_str(), t, dt, alpha));
   agent->run_bcinitaction(t, dt);
   MAN_DEBUG(1, ("Rocman: BCInitInvoker::run() agent: %s DONE.\n", agent->get_agent_name().c_str()));
 }
Member Data Documentation
Agent* BCInitInvoker::agent private
Definition at line 86 of file basic_actions.h.
Referenced by init(), and run().
The documentation for this class was generated from the following files:
basic_actions.h
basic_actions.C