IMPACT: IRAD::Global::ParallelGlobalObj< CommunicatorType, StackType, ErrorType, ProfilerType > Class Template Reference
IRAD::Global::ParallelGlobalObj< CommunicatorType, StackType, ErrorType, ProfilerType > Class Template Reference
Detailed Description
template<typename CommunicatorType, typename StackType, typename ErrorType, typename ProfilerType>
class IRAD::Global::ParallelGlobalObj< CommunicatorType, StackType, ErrorType, ProfilerType >
Definition at line 488 of file Global.H.
#include <Global.H>
Public Member Functions
ParallelGlobalObj ()
ParallelGlobalObj (GlobalType &inglob)
ParallelGlobalObj (ParallelGlobalObj< CommunicatorType, StackType, ErrorType, ProfilerType > &pglobin)
ParallelGlobalObj (const std::string &name)
ParallelGlobalObj (const std::string &name, unsigned int id)
ParallelGlobalObj (int narg, char **args)
virtual int Init (const std::string &name, CommunicatorType &incomm)
virtual int Init (const std::string &name)
virtual int Init (const std::string &name, unsigned int id)
virtual int Init (int narg, char **args)
virtual int Rank ()
virtual int NProc ()
virtual int Finalize ()
Finalizes the global object, and it's profiler object.
virtual CommunicatorType & Communicator ()
virtual ~ParallelGlobalObj ()
Public Member Functions inherited from IRAD::Global::GlobalObj< StackType, ErrorType, ProfilerType >
GlobalObj ()
Default constructor. Profiling is OFF by default.
GlobalObj (int narg, char **args)
Default constructor.
GlobalObj (GlobalObj< StackType, ErrorType, ProfilerType > &globin)
Constructor with args.
GlobalObj (const StackType &name)
Constructor with args.
GlobalObj (const StackType &name, int id)
Constructor with args.
virtual int Init (const StackType &name)
Initializes the global object and it's profiler object /// Initializes the global object and it's profiler object Profiling is ON by default if Init is invoked.
virtual int Init (const StackType &name, unsigned int id)
Initializes the global object and it's profiler object Profiling is ON by default if Init is invoked.
virtual bool Profiling ()
Get profiling state.
virtual bool Profiling (bool yn)
Enable or disable profiling.
virtual void Report (std::ostream &ReportStream)
Creates the final profiling report on the specified stream.
virtual void Register (const StackType &stackentry)
Register will push to the Stack only.
virtual void DeRegister (const StackType &stackentry)
DeRegister will pop from the stack only.
virtual void FunctionEntry (const StackType &stackentry)
FunctionEntry updates the Stack as well as the Profiler.
virtual void FunctionExit (const StackType &stackentry)
FunctionExit updates the Stack as well as the Profiler.
virtual void Error (const ErrorType &error)
Pushes an error onto the error stack.
virtual void DumpErrors (std::ostream &Ostr)
Dumps the errors themselves to the indicated stream.
virtual void DumpStack (std::ostream &Ostr)
Dumps the code construct statck to the indicated stream.
virtual void DumpProfile (std::ostream &Ostr)
Dumps the timing profile to the indicated stream.
bool DebugStreamReady ()
Checks debug stream.
void SetDebugStream (std::ostream &dbstream)
Sets the debug stream object.
std::ostream & DebugStream ()
Gets the debug stream object.
std::ostream * DebugStreamPtr ()
Gets the debug stream pointer.
bool ErrStreamReady ()
Checks error stream.
void SetErrStream (std::ostream &dbstream)
Sets the error stream object.
std::ostream & ErrStream ()
Gets the error stream object.
std::ostream * ErrStreamPtr ()
Gets the error stream pointer.
bool OutStreamReady ()
Checks out stream.
void SetOutStream (std::ostream &outstream)
Sets the stdout stream object.
std::ostream & OutStream ()
Gets the stdout stream object.
std::ostream * OutStreamPtr ()
Gets the stdout stream pointer.
bool LogStreamReady ()
Checks log stream.
void SetLogStream (std::ostream &logstream)
Sets the stdout stream object.
std::ostream & LogStream ()
Gets the log stream object.
std::ostream * LogStreamPtr ()
Gets the log stream pointer.
void SetProfiler (ProfilerType &profiler)
Sets the Profiler object.
virtual void SetName (const std::string &name)
virtual void ReName (const std::string &name)
virtual const std::string & Name ()
ProfilerType & Profiler ()
Gets the debug stream object.
void SetDebugLevel (unsigned char l)
Sets the level of debugging.
unsigned char DebugLevel ()
Returns the debugging level.
void SetVerbLevel (unsigned char l)
unsigned char VerbLevel ()
Returns the verbosity level.
void SetLogLevel (unsigned char l)
unsigned char LogLevel ()
Returns the verbosity level.
void DeSyncIO ()
DeSync IO - relinquish control over IO, revert to standard.
void SyncIO ()
Syncronize IO - assume control over IO, using established streams.
virtual int StdOut (const std::string &outstr, unsigned char inlev=0, bool stack=false)
virtual int ErrOut (const std::string &outstr)
virtual int DebugOut (const std::string &outstr, int inlev=1)
virtual int LogOut (const std::string &outstr, int inlev=0)
virtual ~GlobalObj ()
Destructor.
Protected Attributes
CommunicatorType _communicator
Protected Attributes inherited from IRAD::Global::GlobalObj< StackType, ErrorType, ProfilerType >
std::ostream * _DebugStream
DebugStream is useful for parallel programs that cannot stream debugging information to the screen.
std::ostream * _OutStream
std::ostream * _LogStream
std::ostream * _ErrStream
ProfilerType * _Profiler
This is a placeholder for a generic profiling tool.
Private Types
typedef GlobalObj< StackType,
ErrorType, ProfilerType > GlobalType
Member Typedef Documentation
template<typename CommunicatorType, typename StackType, typename ErrorType, typename ProfilerType> typedef GlobalObj<StackType,ErrorType,ProfilerType> IRAD::Global::ParallelGlobalObj< CommunicatorType, StackType, ErrorType, ProfilerType >::GlobalType private
Definition at line 490 of file Global.H.
Constructor & Destructor Documentation
template<typename CommunicatorType, typename StackType, typename ErrorType, typename ProfilerType> IRAD::Global::ParallelGlobalObj< CommunicatorType, StackType, ErrorType, ProfilerType >::ParallelGlobalObj () inline
Definition at line 494 of file Global.H.
                           :
         GlobalType()
       {};
template<typename CommunicatorType, typename StackType, typename ErrorType, typename ProfilerType> IRAD::Global::ParallelGlobalObj< CommunicatorType, StackType, ErrorType, ProfilerType >::ParallelGlobalObj (GlobalType & inglob) inline
Definition at line 497 of file Global.H.
                                             :
         GlobalType(inglob)
       {};
template<typename CommunicatorType, typename StackType, typename ErrorType, typename ProfilerType> IRAD::Global::ParallelGlobalObj< CommunicatorType, StackType, ErrorType, ProfilerType >::ParallelGlobalObj (ParallelGlobalObj< CommunicatorType, StackType, ErrorType, ProfilerType > & pglobin) inline
Definition at line 500 of file Global.H.
References IRAD::Global::ParallelGlobalObj< CommunicatorType, StackType, ErrorType, ProfilerType >::_communicator.
                                                                                                        :
         GlobalObj<StackType,ErrorType,ProfilerType>(pglobin)
       {
         _communicator.Initialize(pglobin._communicator);
       };
template<typename CommunicatorType, typename StackType, typename ErrorType, typename ProfilerType> IRAD::Global::ParallelGlobalObj< CommunicatorType, StackType, ErrorType, ProfilerType >::ParallelGlobalObj (const std::string & name) inline
Definition at line 505 of file Global.H.
                                                :
         GlobalObj<StackType,ErrorType,ProfilerType>(name)
       {
         //      Init(name);
       };
template<typename CommunicatorType, typename StackType, typename ErrorType, typename ProfilerType> IRAD::Global::ParallelGlobalObj< CommunicatorType, StackType, ErrorType, ProfilerType >::ParallelGlobalObj (const std::string & name, unsigned int id) inline
Definition at line 510 of file Global.H.
                                                                :
         GlobalObj<StackType,ErrorType,ProfilerType>(name,id)
       {
         //      Init(name);
       };
template<typename CommunicatorType, typename StackType, typename ErrorType, typename ProfilerType> IRAD::Global::ParallelGlobalObj< CommunicatorType, StackType, ErrorType, ProfilerType >::ParallelGlobalObj (int narg, char ** args) inline
Definition at line 515 of file Global.H.
References IRAD::Global::ParallelGlobalObj< CommunicatorType, StackType, ErrorType, ProfilerType >::Init().
                                               :
         GlobalObj<StackType,ErrorType,ProfilerType>(narg,args)
       {
         assert(Init(narg,args)==0);
       };
template<typename CommunicatorType, typename StackType, typename ErrorType, typename ProfilerType> virtual IRAD::Global::ParallelGlobalObj< CommunicatorType, StackType, ErrorType, ProfilerType >::~ParallelGlobalObj () inline virtual
Definition at line 558 of file Global.H.
References IRAD::Global::ParallelGlobalObj< CommunicatorType, StackType, ErrorType, ProfilerType >::Finalize().
 { Finalize();};
Member Function Documentation
template<typename CommunicatorType, typename StackType, typename ErrorType, typename ProfilerType> virtual CommunicatorType& IRAD::Global::ParallelGlobalObj< CommunicatorType, StackType, ErrorType, ProfilerType >::Communicator () inline virtual
Definition at line 557 of file Global.H.
References IRAD::Global::ParallelGlobalObj< CommunicatorType, StackType, ErrorType, ProfilerType >::_communicator.
 {return _communicator; };
template<typename CommunicatorType, typename StackType, typename ErrorType, typename ProfilerType> virtual int IRAD::Global::ParallelGlobalObj< CommunicatorType, StackType, ErrorType, ProfilerType >::Finalize () inline virtual
Reimplemented from IRAD::Global::GlobalObj< StackType, ErrorType, ProfilerType >.
Reimplemented in IRAD::Global::Program< TestGlobal, TestComLine >.
Definition at line 550 of file Global.H.
References IRAD::Global::ParallelGlobalObj< CommunicatorType, StackType, ErrorType, ProfilerType >::_communicator, and IRAD::Global::GlobalObj< StackType, ErrorType, ProfilerType >::Finalize().
Referenced by IRAD::Global::ParallelGlobalObj< CommunicatorType, StackType, ErrorType, ProfilerType >::~ParallelGlobalObj().
       {
         int retval = GlobalObj<StackType,ErrorType,ProfilerType>::Finalize();
         if(retval)
           return(retval);
         return(_communicator.Finalize());
       };
template<typename CommunicatorType, typename StackType, typename ErrorType, typename ProfilerType> virtual int IRAD::Global::ParallelGlobalObj< CommunicatorType, StackType, ErrorType, ProfilerType >::Init (const std::string & name, CommunicatorType & incomm) inline virtual
Definition at line 520 of file Global.H.
References IRAD::Global::ParallelGlobalObj< CommunicatorType, StackType, ErrorType, ProfilerType >::_communicator.
Referenced by IRAD::Global::ParallelGlobalObj< CommunicatorType, StackType, ErrorType, ProfilerType >::ParallelGlobalObj().
       {
         int retval = _communicator.Initialize(incomm);
         if(retval)
           return(retval);
         return(GlobalObj<StackType,ErrorType,ProfilerType>::Init(name,_communicator.Rank()));
       };
template<typename CommunicatorType, typename StackType, typename ErrorType, typename ProfilerType> virtual int IRAD::Global::ParallelGlobalObj< CommunicatorType, StackType, ErrorType, ProfilerType >::Init (const std::string & name) inline virtual
Definition at line 527 of file Global.H.
       {
         return(GlobalObj<StackType,ErrorType,ProfilerType>::Init(name));
       };
template<typename CommunicatorType, typename StackType, typename ErrorType, typename ProfilerType> virtual int IRAD::Global::ParallelGlobalObj< CommunicatorType, StackType, ErrorType, ProfilerType >::Init (const std::string & name, unsigned int id) inline virtual
Definition at line 531 of file Global.H.
       {
         return(GlobalObj<StackType,ErrorType,ProfilerType>::Init(name,id));
       };
template<typename CommunicatorType, typename StackType, typename ErrorType, typename ProfilerType> virtual int IRAD::Global::ParallelGlobalObj< CommunicatorType, StackType, ErrorType, ProfilerType >::Init (int narg, char ** args) inline virtual
Definition at line 535 of file Global.H.
References IRAD::Global::ParallelGlobalObj< CommunicatorType, StackType, ErrorType, ProfilerType >::_communicator, and IRAD::Util::stripdirs().
       {
         int retval = _communicator.Initialize(&narg,&args);
         if(retval)
           return(retval);
         return(GlobalObj<StackType,ErrorType,ProfilerType>::Init(Util::stripdirs(args[0]),_communicator.Rank()));
       };
template<typename CommunicatorType, typename StackType, typename ErrorType, typename ProfilerType> virtual int IRAD::Global::ParallelGlobalObj< CommunicatorType, StackType, ErrorType, ProfilerType >::NProc () inline virtual
Definition at line 546 of file Global.H.
References IRAD::Global::ParallelGlobalObj< CommunicatorType, StackType, ErrorType, ProfilerType >::_communicator.
       {
         return(_communicator.Size());
       };
template<typename CommunicatorType, typename StackType, typename ErrorType, typename ProfilerType> virtual int IRAD::Global::ParallelGlobalObj< CommunicatorType, StackType, ErrorType, ProfilerType >::Rank () inline virtual
Definition at line 542 of file Global.H.
References IRAD::Global::ParallelGlobalObj< CommunicatorType, StackType, ErrorType, ProfilerType >::_communicator.
       {
         return(_communicator.Rank());
       };
Member Data Documentation
template<typename CommunicatorType, typename StackType, typename ErrorType, typename ProfilerType> CommunicatorType IRAD::Global::ParallelGlobalObj< CommunicatorType, StackType, ErrorType, ProfilerType >::_communicator protected
Definition at line 492 of file Global.H.
Referenced by IRAD::Global::ParallelGlobalObj< CommunicatorType, StackType, ErrorType, ProfilerType >::Communicator(), IRAD::Global::ParallelGlobalObj< CommunicatorType, StackType, ErrorType, ProfilerType >::Finalize(), IRAD::Global::ParallelGlobalObj< CommunicatorType, StackType, ErrorType, ProfilerType >::Init(), IRAD::TestProgram::Initialize(), IRAD::Global::ParallelGlobalObj< CommunicatorType, StackType, ErrorType, ProfilerType >::NProc(), IRAD::Global::ParallelGlobalObj< CommunicatorType, StackType, ErrorType, ProfilerType >::ParallelGlobalObj(), and IRAD::Global::ParallelGlobalObj< CommunicatorType, StackType, ErrorType, ProfilerType >::Rank().
The documentation for this class was generated from the following file:
Global.H