IMPACT: IRAD::Sys::ObjectFactory< ObjectType > Class Template Reference
IRAD::Sys::ObjectFactory< ObjectType > Class Template Reference
Detailed Description
template<typename ObjectType>
class IRAD::Sys::ObjectFactory< ObjectType >
Definition at line 19 of file DLTools.H.
#include <DLTools.H>
Public Member Functions
ObjectFactory ()
virtual ObjectType * Create ()
virtual void Destroy (ObjectType *objptr)
virtual void SetCreate (ObjectType *(*increate)())
virtual void SetDestroy (void(*indestroy)(ObjectType *))
virtual ~ObjectFactory ()
Public Attributes
virtual ObjectType *(*)() CreatePtr ()
virtual void(*)(ObjectType *) DestroyPtr ()
Protected Attributes
ObjectType *(* _create)()
void(* _destroy)(ObjectType *)
Constructor & Destructor Documentation
template<typename ObjectType > IRAD::Sys::ObjectFactory< ObjectType >::ObjectFactory () inline
Definition at line 24 of file DLTools.H.
                       : _create(NULL), _destroy(NULL)
       {};
template<typename ObjectType > virtual IRAD::Sys::ObjectFactory< ObjectType >::~ObjectFactory () inline virtual
Definition at line 32 of file DLTools.H.
 {};
Member Function Documentation
template<typename ObjectType > virtual ObjectType* IRAD::Sys::ObjectFactory< ObjectType >::Create () inline virtual
Definition at line 26 of file DLTools.H.
References IRAD::Sys::ObjectFactory< ObjectType >::_create.
 {return((*_create)());                    };
template<typename ObjectType > virtual void IRAD::Sys::ObjectFactory< ObjectType >::Destroy (ObjectType * objptr) inline virtual
Definition at line 29 of file DLTools.H.
 {(*_destroy)(objptr);  };
template<typename ObjectType > virtual void IRAD::Sys::ObjectFactory< ObjectType >::SetCreate (ObjectType *(*)() increate) inline virtual
Definition at line 30 of file DLTools.H.
References IRAD::Sys::ObjectFactory< ObjectType >::_create.
 {_create = increate;};
template<typename ObjectType > virtual void IRAD::Sys::ObjectFactory< ObjectType >::SetDestroy (void(*)(ObjectType *) indestroy) inline virtual
Definition at line 31 of file DLTools.H.
References IRAD::Sys::ObjectFactory< ObjectType >::_destroy.
 {_destroy = indestroy; };
Member Data Documentation
template<typename ObjectType > ObjectType*(* IRAD::Sys::ObjectFactory< ObjectType >::_create)() protected
Definition at line 21 of file DLTools.H.
Referenced by IRAD::Sys::ObjectFactory< ObjectType >::Create(), and IRAD::Sys::ObjectFactory< ObjectType >::SetCreate().
template<typename ObjectType > void(* IRAD::Sys::ObjectFactory< ObjectType >::_destroy)(ObjectType *) protected
Definition at line 22 of file DLTools.H.
Referenced by IRAD::Sys::ObjectFactory< ObjectType >::SetDestroy().
template<typename ObjectType > virtual ObjectType*(*)() IRAD::Sys::ObjectFactory< ObjectType >::CreatePtr() inline
Definition at line 27 of file DLTools.H.
 {return(_create);                   };
template<typename ObjectType > virtual void(*)(ObjectType*) IRAD::Sys::ObjectFactory< ObjectType >::DestroyPtr() inline
Definition at line 28 of file DLTools.H.
 {return(_destroy);      };
The documentation for this class was generated from the following file:
DLTools.H