IMPACT: IRAD::Comm::CommunicatorObject Class Reference
IRAD::Comm::CommunicatorObject Class Reference
Main encapsulation of MPI.
Detailed Description
The CommunicatorObject provides an interface to MPI. This is for convenience, consistency, and to provide an "easy" access point for replacing the communication substrate with something that's not MPI.
Definition at line 62 of file COMM.H.
#include <COMM.H>
Public Member Functions
MPI_Comm GetCommunicator ()
CommunicatorObject ()
CommunicatorObject (MPI_Comm &incomm)
CommunicatorObject (int *narg, char ***args)
MPI_Datatype ResolveDataType (const Comm::DataTypes &dt)
MPI_Op ResolveOp (const Comm::Ops &op)
int Split (int color, int key, CommunicatorObject &newcomm)
int WaitRecv (int recvid)
int WaitAll ()
void ClearRequests ()
int NOpenRequests ()
int Initialize (CommunicatorObject &incomm)
int Initialize (int *narg=NULL, char ***args=NULL)
int SetExit (int errin)
int SetErr (int errin)
void ClearErr ()
int Check (Comm::Ops op=Comm::MAXOP)
int Rank ()
MPI_Comm World ()
int Finalize ()
int Barrier ()
int Size ()
~CommunicatorObject ()
int StartSend (unsigned int rid)
int SendAll ()
int StartRecv (unsigned int rid)
int RecvAll ()
int BroadCast (std::string &sval, int root_rank=0)
int BroadCast (MobileObject *mo, int root_rank=0)
int _ASend (void *buf, int sendsize, unsigned int remote_rank, int tag=0)
int _SetSend (void *buf, int sendsize, unsigned int remote_rank, int tag=0)
int _ARecv (void *buf, int recvsize, unsigned int remote_rank, int tag=0)
int _SetRecv (void *buf, int recvsize, unsigned int remote_rank, int tag=0)
int _AllGatherv (void *sendbuf, int mysendcnt, int datasize, void *recvbuf)
int _Send (void *buf, int sendsize, unsigned int remote_rank, int tag=0)
int _Recv (void *buf, int recvsize, unsigned int remote_rank, int tag=0)
int _BroadCastMOV (std::vector< MobileObject * > &mos, int root_rank=0)
int _GatherMO (MobileObject *sPtr, std::vector< MobileObject * > &rVec, int sndcnt, int root=0)
int _GatherMOV (std::vector< MobileObject * > &sVec, std::vector< MobileObject * > &rVec, std::vector< int > &nsend_all, int root=0)
int _AllGatherMO (MobileObject *sPtr, std::vector< MobileObject * > &rVec, int sndcnt=1)
int _AllGatherMOV (std::vector< MobileObject * > &sVec, std::vector< MobileObject * > &rVec, std::vector< int > &nsend_all)
template<typename DataType >
int ASend (std::vector< DataType > &sendbuf, unsigned int remote_rank, int tag=0)
template<typename DataType >
int SetSend (std::vector< DataType > &sendbuf, unsigned int remote_rank, int tag=0)
template<typename DataType >
int SetRecv (std::vector< DataType > &recvbuf, unsigned int remote_rank, int tag=0)
template<typename DataType >
int ARecv (std::vector< DataType > &recvbuf, unsigned int remote_rank, int tag=0)
template<typename DataType >
int BroadCast (DataType &buf, int root_rank)
template<typename DataType >
int BroadCast (std::vector< DataType > &buf, int root_rank)
template<typename DataType >
int Reduce (DataType &send, DataType &recv, const Comm::DataTypes &dt, const Comm::Ops &op, int root)
template<typename DataType >
int Reduce (std::vector< DataType > &send, std::vector< DataType > &recv, const Comm::DataTypes &dt, const Comm::Ops &op, int root)
template<typename DataType >
int AllReduce (std::vector< DataType > &send, std::vector< DataType > &recv, const Comm::DataTypes &dt, const Comm::Ops &op)
template<typename DataType >
int AllReduce (DataType &send, DataType &recv, const Comm::DataTypes &dt, const Comm::Ops &op)
template<typename DataType >
int AllGather (std::vector< DataType > &sendvec, std::vector< DataType > &recvvec, int sndcnt=0, int recvcnt=0)
template<typename DataType >
int AllGather (DataType &sendval, std::vector< DataType > &recvvec)
template<typename DataType >
int AllGatherv (std::vector< DataType > &sendvec, std::vector< DataType > &recvvec, std::vector< int > &nsend_all)
template<typename DataType >
int AllGatherv (std::vector< DataType > &sendvec, std::vector< DataType > &recvvec)
template<typename DataType >
int Gather (DataType &sendval, std::vector< DataType > &recvvec, int root=0)
template<typename DataType >
int Gather (std::vector< DataType > &sendvec, std::vector< DataType > &recvvec, int sndcnt=0, int recvcnt=0, int root=0)
template<typename DataType >
int Gatherv (std::vector< DataType > &sendvec, std::vector< DataType > &recvvec, std::vector< int > &nsend_all, int nsend=0, int root=0)
template<typename DataType >
int Scatterv (std::vector< DataType > &sendvec, std::vector< int > &sendcounts, std::vector< DataType > &recvvec, int root=0)
template<typename MOType >
int BroadCastMobileObject (MOType &mo, int root_rank=0)
template<typename MOType >
int BroadCastMO (MOType &mo, int root_rank=0)
template<typename MOType >
int BroadCastMO (std::vector< MOType > &mov, int root_rank=0)
template<typename MOType >
int BroadCastMOVector (std::vector< MOType > &mov, int root_rank=0)
template<typename MOType >
int GatherMO (MOType &sendval, std::vector< MOType > &recvvec, int root=0)
template<typename MOType >
int GatherMO (std::vector< MOType > &sendvec, std::vector< MOType > &recvvec, std::vector< int > &nsend_all, int root=0)
template<typename MOType >
int AllGatherMO (MOType &sendval, std::vector< MOType > &recvvec)
template<typename MOType >
int AllGatherMO (std::vector< MOType > &sendvec, std::vector< MOType > &recvvec, std::vector< int > &nsend_all, int root=0)
template<typename MOType >
int GatherMOV (std::vector< MOType > &sendvec, std::vector< MOType > &recvvec, std::vector< int > &nsend_all, int root=0)
template<typename MOType >
int AllGatherMOV (std::vector< MOType > &sendvec, std::vector< MOType > &recvvec, std::vector< int > &nsend_all, int root=0)
template<typename T >
int Union (std::vector< T > &input_data, std::vector< T > &output_data)
Public Attributes
MPI_Datatype IntegerTypeID
Private Attributes
int _rank
MPI_Comm _comm
bool _master
bool _own_comm
bool _initd
int _error
int _rc
int _nproc
std::vector< MPI_Request > _send_requests
std::vector< MPI_Request > _recv_requests
std::vector< int > _send_tags
std::vector< int > _recv_tags
std::vector< MPI_Status > _status
Constructor & Destructor Documentation
IRAD::Comm::CommunicatorObject::CommunicatorObject ()
Definition at line 75 of file COMM.C.
References _comm, _error, _initd, _master, _nproc, _own_comm, _rank, and _rc.
                                            : IntegerTypeID(MPI_INTEGER)
     {
       _rank = -1;
       _comm = MPI_COMM_WORLD;
       _master = false;
       _own_comm = false;
       _initd  = false;
       _rc = 0;
       _nproc = 0;
       _error = 0;
     };
IRAD::Comm::CommunicatorObject::CommunicatorObject (MPI_Comm & incomm)
Definition at line 87 of file COMM.C.
References _comm, _error, _initd, _master, _nproc, _own_comm, _rank, and _rc.
                                                            : IntegerTypeID(MPI_INTEGER)
     {
       _rc = MPI_Comm_rank(incomm,&_rank);
       if(_rc)
         _error = _rc;
       _comm = incomm;
       _master = false;
       _own_comm = false;
       _initd = true;
       _rc = MPI_Comm_size(_comm,&_nproc);
     };
IRAD::Comm::CommunicatorObject::CommunicatorObject (int * narg, char *** args)
Definition at line 99 of file COMM.C.
References _error, _initd, _master, _nproc, _own_comm, _rank, _rc, and Initialize().
                                                                  : IntegerTypeID(MPI_INTEGER)
     {
       _nproc = 0;
       _rc = Initialize(narg,args);
       assert(_rc == 0);
       _rank = -1;
       _error = 0;
       _own_comm = false;
       _master = true;
       _initd = true;
     };
IRAD::Comm::CommunicatorObject::~CommunicatorObject ()
Definition at line 258 of file COMM.C.
References _comm, _initd, _master, and _own_comm.
     {
       int flag;
       MPI_Finalized(&flag);
       if(flag == 0 && _own_comm && _initd){
         MPI_Comm_free(&_comm);
       }
       if(flag == 0 && _master && _initd){
         MPI_Finalize();
       }
     };
Member Function Documentation
int IRAD::Comm::CommunicatorObject::_AllGatherMO (MobileObject * sPtr, std::vector< MobileObject * > & rVec, int sndcnt = 1)
Definition at line 575 of file COMM.C.
References _comm, _nproc, _rank, _rc, AllGather(), IRAD::Comm::MobileObject::DestroyBuffer(), IRAD::Comm::MobileObject::GetBuffer(), and IRAD::Comm::MobileObject::Pack().
Referenced by AllGatherMO().
     {
       //    int recvcnt = sndcnt;
       int local_size = 0;
       local_size = sPtr->Pack();
       std::vector<int> allsizes(_nproc,0);
       std::vector<int> disps(_nproc,0);
       allsizes[_rank] = local_size;
       this->AllGather(local_size,allsizes);
       int total_size = 0;
       for(int i = 0; i < _nproc;i++){
         total_size += allsizes[i];
         if(i > 0)
           disps[i] = disps[i-1]+allsizes[i-1];
         //      total_nitems += allnitems[i];
       }
       char *recvbuffer = new char [total_size];
       _rc = MPI_Allgatherv((void *)(sPtr->GetBuffer()),local_size,MPI_CHAR,
                            (void *)(recvbuffer),&allsizes[0],&disps[0],MPI_CHAR,_comm);
       // The root must unpack the received data:
       for(int i = 0;i < _nproc;i++){
         if(i == _rank)
           rVec[i]->UnPack(sPtr->GetBuffer());
         else
           rVec[i]->UnPack(&recvbuffer[disps[i]]);
       }
       delete [] recvbuffer;
       sPtr->DestroyBuffer();
       return(_rc);
     };
int IRAD::Comm::CommunicatorObject::_AllGatherMOV (std::vector< MobileObject * > & sVec, std::vector< MobileObject * > & rVec, std::vector< int > & nsend_all)
Definition at line 667 of file COMM.C.
References _comm, _nproc, _rank, _rc, and AllGatherv().
Referenced by AllGatherMOV().
     {
       int sndIcnt = sVec.size();
       int local_size = 0;
       std::vector<int> local_sizes(sndIcnt,0);
       for(int i = 0;i < sndIcnt;i++){
         local_sizes[i] = sVec[i]->Pack();
         local_size += local_sizes[i];
       }
       std::vector<int> Allsizes;
       this->AllGatherv(local_sizes,Allsizes,nsend_all);
       int total_size = 0;
       std::vector<int> allsizes(_nproc,0);
       std::vector<int> disps(_nproc,0);
       int sindex = 0;
       for(int i = 0; i < _nproc; i++){
         for(int j = 0; j < nsend_all[i]; j++){
           allsizes[i] += Allsizes[sindex];
         }
         total_size += allsizes[i];
         if(i > 0)
           disps[i] = disps[i-1]+allsizes[i-1];
       }
       char *sendbuffer = new char [local_size];
       char *recvbuffer = new char [total_size];
       char *cur_pos = sendbuffer;
       for(int i = 0;i < sndIcnt;i++){
         std::memcpy(cur_pos,sVec[i]->GetBuffer(),sVec[i]->BufSize());
         cur_pos += sVec[i]->BufSize();
       }
       std::vector<MobileObject *>::iterator svi = sVec.begin();
       while(svi != sVec.end()){
         (*svi)->DestroyBuffer();
         svi++;
       }
       _rc = MPI_Allgatherv((void *)sendbuffer,local_size,MPI_CHAR,
                            (void *)recvbuffer,&allsizes[0],&disps[0],MPI_CHAR,_comm);
       cur_pos = recvbuffer;
       // unpack each object
       int rind = 0;
       int sind = 0;
       for(int i = 0;i < _nproc;i++){
         for(int j = 0;j < nsend_all[i];j++){
           if(i == _rank){
             rVec[rind++]->UnPack(sendbuffer);
             sendbuffer += local_sizes[j];
             cur_pos += local_sizes[j];
             sind++;
           }
           else {
             rVec[rind++]->UnPack(cur_pos);
             cur_pos += Allsizes[sind++];
           }
         }
       }
       delete [] recvbuffer;
       return(_rc);
     };
int IRAD::Comm::CommunicatorObject::_AllGatherv (void * sendbuf, int mysendcnt, int datasize, void * recvbuf)
Definition at line 415 of file COMM.C.
References _comm, _nproc, _rank, _rc, and AllGather().
Referenced by AllGatherv().
     {
       std::vector<int> allsizes(_nproc,0);
       AllGather(mysendcnt,allsizes);
       std::vector<int>::iterator asi = allsizes.begin();
       while(asi != allsizes.end()){
         *asi = *asi*datasize;
         asi++;
       }
       std::vector<int> displacements(_nproc,0);
       for(int i = 1;i < _nproc;i++)
         displacements[i] = displacements[i-1]+allsizes[i-1];
       _rc = MPI_Allgatherv(sendbuf,allsizes[_rank],MPI_CHAR,
                            recvbuf,&allsizes[0],&displacements[0],
                            MPI_CHAR,_comm);
       assert(_rc == 0);
       return(_rc);
     };
int IRAD::Comm::CommunicatorObject::_ARecv (void * buf, int recvsize, unsigned int remote_rank, int tag = 0)
Definition at line 373 of file COMM.C.
References _comm, _rc, _recv_requests, and _recv_tags.
Referenced by ARecv().
     {
       MPI_Request request;
       int request_id = _recv_requests.size();
       _recv_requests.push_back(request);
       if(tag == 0)
         tag = MPI_ANY_TAG;
       _recv_tags.push_back(tag);
       _rc = MPI_Irecv(recvbuf,recvsize,MPI_CHAR,remote_rank,
                       tag,_comm,&_recv_requests[request_id]);
       assert(_rc == 0);
       return(request_id);
     };
int IRAD::Comm::CommunicatorObject::_ASend (void * buf, int sendsize, unsigned int remote_rank, int tag = 0)
Definition at line 333 of file COMM.C.
References _comm, _rc, _send_requests, and _send_tags.
Referenced by ASend().
     {
       MPI_Request request;
       int request_id = _send_requests.size();
       _send_requests.push_back(request);
       if(tag == 0)
         tag = _send_tags.size() + 1;
       _send_tags.push_back(tag);
       _rc = MPI_Isend(buf,sendsize,MPI_CHAR,remote_rank,
                       tag,_comm,&_send_requests[request_id]);
       assert(_rc == 0);
       return(request_id);
     };
int IRAD::Comm::CommunicatorObject::_BroadCastMOV (std::vector< MobileObject * > & mos, int root_rank = 0)
Definition at line 501 of file COMM.C.
References _comm, _rank, and _rc.
Referenced by BroadCastMO(), and BroadCastMOVector().
     {
       int nobjs = mos.size();
       _rc = 0;
       // This broadcast is superfluous since nobjs should already be
       // identical on every processor.
       if((_rc = MPI_Bcast(&nobjs,1,MPI_INT,root_rank,_comm)))
         return(1);
       std::vector<int> sizeofobject(nobjs,0);
       int total_size = 0;
       if(_rank == root_rank){
         std::vector<int>::iterator si = sizeofobject.begin();
         std::vector<MobileObject *>::iterator moi = mos.begin();
         while(moi != mos.end()){
           sizeofobject[si - sizeofobject.begin()] = (*moi)->Pack();
           moi++;
           si++;
         }
       }
       if((_rc = MPI_Bcast(&sizeofobject[0],nobjs,MPI_INT,root_rank,_comm)))
         return(1);
       std::vector<int>::iterator si = sizeofobject.begin();
       std::vector<MobileObject *>::iterator moi = mos.begin();
       while(si != sizeofobject.end()){
         if(_rank != root_rank){
           int bsize = (*moi++)->PrepareBuffer(*si);
           assert(bsize == *si);
         }
         total_size += *si++;
       }
       assert(total_size > 0);
       if(total_size <= 0)
         return(1);
       char *bufferspace = new char [total_size];
       if(_rank == root_rank){
         // pack the bufferspace with all the buffers
         char *cur_pos = bufferspace;
         si  = sizeofobject.begin();
         moi = mos.begin();
         while(moi != mos.end()){
           std::memcpy(cur_pos,(*moi)->GetBuffer(),*si);
           cur_pos += *si++;
           moi++;
         }
       }
       if((_rc = MPI_Bcast(bufferspace,total_size,MPI_CHAR,root_rank,_comm))){
         delete [] bufferspace;
         return(1);
       }
       // Now everyone has all the data
       if(_rank == root_rank){
         // root can just destroy his buffers
         moi = mos.begin();
         while(moi != mos.end())
           (*moi++)->DestroyBuffer();
       }
       else{   // everyone else needs to unpack
         char *cur_pos = bufferspace;
         si  = sizeofobject.begin();
         moi = mos.begin();
         while(moi != mos.end()){
           assert((*moi)->GetBuffer() != NULL);
           std::memcpy((*moi)->GetBuffer(),cur_pos,*si);
           _rc += (*moi)->UnPack();
           assert(_rc == 0);
           cur_pos += *si++;
           moi++;
         }
       }
       delete [] bufferspace;
       return(_rc);
     };
int IRAD::Comm::CommunicatorObject::_GatherMO (MobileObject * sPtr, std::vector< MobileObject * > & rVec, int sndcnt, int root = 0)
Definition at line 452 of file COMM.C.
References _comm, _nproc, _rank, _rc, IRAD::Comm::MobileObject::DestroyBuffer(), Gather(), IRAD::Comm::MobileObject::GetBuffer(), and IRAD::Comm::MobileObject::Pack().
Referenced by GatherMO().
     {
       //    int recvcnt = sndcnt;
       int local_size = 0;
       local_size = sPtr->Pack();
       std::vector<int> allsizes;
       std::vector<int> disps;
       if(_rank == root){
         allsizes.resize(_nproc,0);
         disps.resize(_nproc,0);
         allsizes[_rank] = local_size;
       }
       this->Gather(local_size,allsizes,root);
       //    this->Barrier();
       int total_size = 0;
       if(_rank == root){
         for(int i = 0; i < _nproc;i++){
           total_size += allsizes[i];
           if(i > 0)
             disps[i] = disps[i-1]+allsizes[i-1];
           //    total_nitems += allnitems[i];
         }
       }
       char *recvbuffer = NULL;
       if(_rank == root)
         recvbuffer = new char [total_size];
       _rc = MPI_Gatherv((void *)(sPtr->GetBuffer()),local_size,MPI_CHAR,
                         (void *)(recvbuffer),&allsizes[0],&disps[0],MPI_CHAR,
                         root,_comm);
       // All the send buffers can be destroyed
       //    if(_rank != root)
       //      sPtr->DestroyBuffer();
       // The root must unpack the received data:
       if(_rank == root){
         for(int i = 0;i < _nproc;i++){
           if(i == root)
             rVec[i]->UnPack(sPtr->GetBuffer());
           else
             rVec[i]->UnPack(&recvbuffer[disps[i]]);
         }
         delete [] recvbuffer;
       }
       sPtr->DestroyBuffer();
       return(_rc);
     };
int IRAD::Comm::CommunicatorObject::_GatherMOV (std::vector< MobileObject * > & sVec, std::vector< MobileObject * > & rVec, std::vector< int > & nsend_all, int root = 0)
Definition at line 606 of file COMM.C.
References _comm, _nproc, _rank, _rc, and Gatherv().
Referenced by AllGatherMO(), GatherMO(), and GatherMOV().
     {
       int sndIcnt = sVec.size();
       int local_size = 0;
       std::vector<int> local_sizes(sndIcnt,0);
       for(int i = 0;i < sndIcnt;i++){
         local_sizes[i] = sVec[i]->Pack();
         local_size += local_sizes[i];
       }
       std::vector<int> Allsizes;
       this->Gatherv(local_sizes,Allsizes,nsend_all,root);
       int total_size = 0;
       std::vector<int> allsizes(_nproc,0);
       std::vector<int> disps(_nproc,0);
       int sindex = 0;
       for(int i = 0; i < _nproc; i++){
         for(int j = 0; j < nsend_all[i]; j++){
           allsizes[i] += Allsizes[sindex];
         }
         total_size += allsizes[i];
         if(i > 0)
           disps[i] = disps[i-1]+allsizes[i-1];
       }
       char *sendbuffer = new char [local_size];
       char *recvbuffer = NULL;
       if(_rank == root)
         recvbuffer = new char [total_size];
       //    std::vector<MobileObject *>::iterator sVit = sVec.begin();
       char *cur_pos = sendbuffer;
       for(int i = 0;i < sndIcnt;i++){
         std::memcpy(cur_pos,sVec[i]->GetBuffer(),sVec[i]->BufSize());
         cur_pos += sVec[i]->BufSize();
       }
       _rc = MPI_Gatherv((void *)sendbuffer,local_size,MPI_CHAR,
                         (void *)recvbuffer,&allsizes[0],&disps[0],MPI_CHAR,
                         root,_comm);
       cur_pos = recvbuffer;
       // unpack each object
       int rind = 0;
       int sind = 0;
       if(_rank == root){
         for(int i = 0;i < _nproc;i++){
           for(int j = 0;j < nsend_all[i];j++){
             if(i == root){
               rVec[rind++]->UnPack(sendbuffer);
               sendbuffer += local_sizes[j];
               cur_pos += local_sizes[j];
               sind++;
             }
             else {
               rVec[rind++]->UnPack(cur_pos);
               cur_pos += Allsizes[sind++];
             }
           }
         }
         delete [] recvbuffer;
       }
       return(_rc);
     };
int IRAD::Comm::CommunicatorObject::_Recv (void * buf, int recvsize, unsigned int remote_rank, int tag = 0)
Definition at line 388 of file COMM.C.
References _comm, and _rc.
     {
       MPI_Status status;
       if(tag == 0)
         tag = MPI_ANY_TAG;
       _rc = MPI_Recv(recvbuf,recvsize,MPI_CHAR,remote_rank,
                      tag,_comm,&status);
       assert(_rc == 0);
       return(0);
     };
int IRAD::Comm::CommunicatorObject::_Send (void * buf, int sendsize, unsigned int remote_rank, int tag = 0)
Definition at line 348 of file COMM.C.
References _comm, and _rc.
     {
       _rc = MPI_Send(buf,sendsize,MPI_CHAR,remote_rank,
                      tag,_comm);
       assert(_rc == 0);
       return(0);
     };
int IRAD::Comm::CommunicatorObject::_SetRecv (void * buf, int recvsize, unsigned int remote_rank, int tag = 0)
Definition at line 357 of file COMM.C.
References _comm, _rc, _recv_requests, and _recv_tags.
Referenced by SetRecv().
     {
       MPI_Request request;
       int request_id = _recv_requests.size();
       _recv_requests.push_back(request);
       if(tag == 0)
         tag = MPI_ANY_TAG;
       _recv_tags.push_back(tag);
       _rc = MPI_Recv_init(recvbuf,recvsize,MPI_CHAR,remote_rank,
                           tag,_comm,&_recv_requests[request_id]);
       assert(_rc == 0);
       return(request_id);
     };
int IRAD::Comm::CommunicatorObject::_SetSend (void * buf, int sendsize, unsigned int remote_rank, int tag = 0)
Definition at line 400 of file COMM.C.
References _comm, _rc, _send_requests, and _send_tags.
Referenced by SetSend().
     {
       MPI_Request request;
       int request_id = _send_requests.size();
       _send_requests.push_back(request);
       if(tag == 0)
         tag = _send_tags.size() + 1;
       _send_tags.push_back(tag);
       _rc = MPI_Send_init(sendbuf,sendsize,MPI_CHAR,remote_rank,
                           tag,_comm,&_send_requests[request_id]);
       assert(_rc == 0);
       return(request_id);
     };
template<typename DataType > int IRAD::Comm::CommunicatorObject::AllGather (std::vector< DataType > & sendvec, std::vector< DataType > & recvvec, int sndcnt = 0, int recvcnt = 0) inline
Definition at line 238 of file COMM.H.
References _comm, and _rc.
Referenced by _AllGatherMO(), _AllGatherv(), AllGatherv(), main(), and COM::ParallelTestingObject< CommType, ResultsType >::Test__ParallelModuleLoadingTest().
       {
         size_t datasize = sizeof(DataType);
         if(sndcnt == 0)
           sndcnt = sendvec.size();
         if(recvcnt == 0)
           recvcnt = sndcnt;
         std::cout << "Sendcount = " << sndcnt << " ReceiveCount = " << recvcnt << std::endl;
         _rc = MPI_Allgather((void *)(&(sendvec[0])),sndcnt*datasize,MPI_CHAR,
                             (void *)(&(recvvec[0])),recvcnt*datasize,MPI_CHAR,_comm);
         assert(_rc == 0);
         return(_rc);
       };
template<typename DataType > int IRAD::Comm::CommunicatorObject::AllGather (DataType & sendval, std::vector< DataType > & recvvec) inline
Definition at line 267 of file COMM.H.
References _comm, _nproc, and _rc.
       {
         size_t messagesize = sizeof(DataType);
         recvvec.resize(_nproc);
         _rc = MPI_Allgather((void *)&sendval,messagesize,MPI_CHAR,
                             (void *)&recvvec[0],messagesize,MPI_CHAR,_comm);
         assert(_rc == 0);
         return(_rc);
       };
template<typename MOType > int IRAD::Comm::CommunicatorObject::AllGatherMO (MOType & sendval, std::vector< MOType > & recvvec) inline
Definition at line 501 of file COMM.H.
References _AllGatherMO(), _nproc, and _rc.
       {
         recvvec.resize(_nproc);
         MobileObject *sendPtr = dynamic_cast<MobileObject *>(&sendval);
         std::vector<MobileObject *> recv_v(_nproc,NULL);
         std::vector<MobileObject *>::iterator moci = recv_v.begin();
         typename std::vector<MOType>::iterator oi = recvvec.begin();
         while(moci != recv_v.end())
           *moci++ = dynamic_cast<MobileObject *>(&(*oi++));
         _rc = this->_AllGatherMO(sendPtr,recv_v);
         assert(_rc == 0);
         return(_rc);
       };
template<typename MOType > int IRAD::Comm::CommunicatorObject::AllGatherMO (std::vector< MOType > & sendvec, std::vector< MOType > & recvvec, std::vector< int > & nsend_all, int root = 0) inline
Definition at line 516 of file COMM.H.
References _GatherMOV(), _nproc, _rank, _rc, and Gather().
       {
         int nsend = sendvec.size();
         if(nsend_all.empty()){
           nsend_all.resize(_nproc,0);
           nsend_all[_rank] = nsend;
           this->Gather(nsend,nsend_all,root);
         }
         int nrecv = 0;
         if(_rank == root){
           std::vector<int>::iterator nsi = nsend_all.begin();
           while(nsi != nsend_all.end())
             nrecv += nsi++;
           recvvec.resize(nrecv);
         }
         std::vector<MobileObject *> send_v(nsend,NULL);
         std::vector<MobileObject *> recv_v(nrecv,NULL);
         std::vector<MobileObject *>::iterator moci = recv_v.begin();
         typename std::vector<MOType>::iterator oi  = recvvec.begin();
         while(moci != recv_v.end())
           *moci++ = dynamic_cast<MobileObject *>(&(*oi++));
         moci = send_v.begin();
         oi  = sendvec.begin();
         while(moci != send_v.end())
           *moci++ = dynamic_cast<MobileObject *>(&(*oi++));
         _rc = this->_GatherMOV(send_v,recv_v,nsend_all,root);
         //      assert(_rc == 0);
         return(_rc);
       };
template<typename MOType > int IRAD::Comm::CommunicatorObject::AllGatherMOV (std::vector< MOType > & sendvec, std::vector< MOType > & recvvec, std::vector< int > & nsend_all, int root = 0) inline
Definition at line 580 of file COMM.H.
References _AllGatherMOV(), _nproc, _rank, _rc, and Gather().
       {
         int nsend = sendvec.size();
         if(nsend_all.empty()){
           nsend_all.resize(_nproc,0);
           nsend_all[_rank] = nsend;
           this->Gather(nsend,nsend_all,root);
         }
         int nrecv = 0;
         if(_rank == root){
           std::vector<int>::iterator nsi = nsend_all.begin();
           while(nsi != nsend_all.end())
             nrecv += nsi++;
           recvvec.resize(nrecv);
         }
         std::vector<MobileObject *> send_v(nsend,NULL);
         std::vector<MobileObject *> recv_v(nrecv,NULL);
         std::vector<MobileObject *>::iterator moci = recv_v.begin();
         typename std::vector<MOType>::iterator oi  = recvvec.begin();
         while(moci != recv_v.end())
           *moci++ = dynamic_cast<MobileObject *>(&(*oi++));
         moci = send_v.begin();
         oi  = sendvec.begin();
         while(moci != send_v.end())
           *moci++ = dynamic_cast<MobileObject *>(&(*oi++));
         _rc = this->_AllGatherMOV(send_v,recv_v,nsend_all);
         //      assert(_rc == 0);
         return(_rc);
       };
template<typename DataType > int IRAD::Comm::CommunicatorObject::AllGatherv (std::vector< DataType > & sendvec, std::vector< DataType > & recvvec, std::vector< int > & nsend_all) inline
Definition at line 278 of file COMM.H.
References _AllGatherv(), _nproc, AllGather(), AllReduce(), IRAD::Comm::DTINT, and IRAD::Comm::SUMOP.
Referenced by _AllGatherMOV().
       {
         int datasize = sizeof(DataType);
         int mysendcnt = sendvec.size();
         int totalcnt = 0;
         if(nsend_all.empty()){
           nsend_all.resize(_nproc,0);
           this->AllGather(mysendcnt,nsend_all);
         }
         this->AllReduce(mysendcnt,totalcnt,DTINT,SUMOP);
         recvvec.resize(totalcnt);
         return(_AllGatherv(&sendvec[0],mysendcnt,datasize,&recvvec[0]));
       };
template<typename DataType > int IRAD::Comm::CommunicatorObject::AllGatherv (std::vector< DataType > & sendvec, std::vector< DataType > & recvvec) inline
Definition at line 293 of file COMM.H.
References _AllGatherv(), _nproc, AllGather(), AllReduce(), IRAD::Comm::DTINT, and IRAD::Comm::SUMOP.
       {
         int datasize = sizeof(DataType);
         int mysendcnt = sendvec.size();
         int totalcnt = 0;
         std::vector<int> nsend_all;
         nsend_all.resize(_nproc,0);
         this->AllGather(mysendcnt,nsend_all);
         this->AllReduce(mysendcnt,totalcnt,DTINT,SUMOP);
         recvvec.resize(totalcnt);
         return(_AllGatherv(&sendvec[0],mysendcnt,datasize,&recvvec[0]));
       };
template<typename DataType > int IRAD::Comm::CommunicatorObject::AllReduce (std::vector< DataType > & send, std::vector< DataType > & recv, const Comm::DataTypes & dt, const Comm::Ops & op) inline
Definition at line 214 of file COMM.H.
References _comm, _rc, ResolveDataType(), and ResolveOp().
Referenced by AllGatherv(), IMPACT::ParallelTestingObject< CommType, ResultsType >::Test__ParallelMidPointQuadrature(), and IMPACT::ParallelTestingObject< CommType, ResultsType >::Test__ParallelTrapezoidQuadrature().
       {
         int count = send.size();
         recv.resize(count);
         _rc = MPI_Allreduce(&send[0],&recv[0],count,ResolveDataType(dt),
                             ResolveOp(op),_comm);
         assert(_rc == 0);
         return(_rc);
       };
template<typename DataType > int IRAD::Comm::CommunicatorObject::AllReduce (DataType & send, DataType & recv, const Comm::DataTypes & dt, const Comm::Ops & op) inline
Definition at line 228 of file COMM.H.
References _comm, _rc, ResolveDataType(), and ResolveOp().
       {
         _rc = MPI_Allreduce(&send,&recv,1,ResolveDataType(dt),
                             ResolveOp(op),_comm);
         assert(_rc == 0);
         return(_rc);
       };
template<typename DataType > int IRAD::Comm::CommunicatorObject::ARecv (std::vector< DataType > & recvbuf, unsigned int remote_rank, int tag = 0) inline
Definition at line 156 of file COMM.H.
References _ARecv().
Referenced by BuildBorderStiffness(), GlobalDofExchange(), GlobalDofReMapExchange(), and TestMPI().
       {
         int sizeofdata = sizeof(DataType);
         int recvcnt = recvbuf.size();
         return(_ARecv(&recvbuf[0],sizeofdata*recvcnt,remote_rank,tag));
       };
template<typename DataType > int IRAD::Comm::CommunicatorObject::ASend (std::vector< DataType > & sendbuf, unsigned int remote_rank, int tag = 0) inline
Definition at line 129 of file COMM.H.
References _ASend().
Referenced by BuildBorderStiffness(), GlobalDofExchange(), GlobalDofReMapExchange(), and TestMPI().
       {
         int sizeofdata = sizeof(DataType);
         int sendcnt = sendbuf.size();
         return (_ASend(&sendbuf[0],sizeofdata*sendcnt,remote_rank,tag));
       };
int IRAD::Comm::CommunicatorObject::Barrier () inline
Definition at line 102 of file COMM.H.
References _comm.
Referenced by BuildBorderStiffness(), GlobalDofExchange(), GlobalDofReMapExchange(), main(), COM::ParallelTestingObject< CommType, ResultsType >::Test__FunctionBarrierTest(), and TestMPI().
 {return(MPI_Barrier(_comm));};
int IRAD::Comm::CommunicatorObject::BroadCast (std::string & sval, int root_rank = 0)
Definition at line 312 of file COMM.C.
References _comm, _rank, and _rc.
Referenced by BroadCastMO(), BroadCastMobileObject(), Scatterv(), and COM::ParallelTestingObject< CommType, ResultsType >::Test__ParallelModuleLoadingTest().
     {
       int sizeofobject = 0;
       if(_rank == root_rank)
         sizeofobject = sval.size();
       _rc = MPI_Bcast(&sizeofobject,1,MPI_INT,root_rank,_comm);
       if(sizeofobject <= 0)
         return 1;
       if(!_rc){
         char *sbuf = new char [sizeofobject];
         if(_rank == root_rank)
           std::strncpy(sbuf,sval.c_str(),sizeofobject);
         _rc = MPI_Bcast(sbuf,sizeofobject,MPI_CHAR,root_rank,_comm);
         if(_rank != root_rank)
           sval.assign(std::string(sbuf));
         delete [] sbuf;
       }
       return(_rc);
     };
int IRAD::Comm::CommunicatorObject::BroadCast (MobileObject * mo, int root_rank = 0)
Definition at line 434 of file COMM.C.
References _comm, _rank, _rc, IRAD::Comm::MobileObject::GetBuffer(), IRAD::Comm::MobileObject::Pack(), IRAD::Comm::MobileObject::PrepareBuffer(), and IRAD::Comm::MobileObject::UnPack().
     {
       int sizeofobject = 0;
       if(_rank == root_rank)
         sizeofobject = mo->Pack();
       _rc = MPI_Bcast(&sizeofobject,1,MPI_INT,root_rank,_comm);
       if(sizeofobject <= 0)
         return 1;
       if(!_rc){
         if(_rank != root_rank)
           mo->PrepareBuffer(sizeofobject);
         _rc = MPI_Bcast(mo->GetBuffer(),sizeofobject,MPI_CHAR,root_rank,_comm);
         if(_rank != root_rank)
           _rc = mo->UnPack();
       }
       return(_rc);
     };
template<typename DataType > int IRAD::Comm::CommunicatorObject::BroadCast (DataType & buf, int root_rank) inline
Definition at line 165 of file COMM.H.
References _comm, and _rc.
       {
         int sizeofdata = sizeof(DataType);
         return((_rc = MPI_Bcast(&buf,sizeofdata,MPI_CHAR,root_rank,_comm)));
       };
template<typename DataType > int IRAD::Comm::CommunicatorObject::BroadCast (std::vector< DataType > & buf, int root_rank) inline
Definition at line 172 of file COMM.H.
References _comm, _rank, and _rc.
       {
         int sizeofdata = sizeof(DataType);
         int bufsize = buf.size();
         _rc = MPI_Bcast(&bufsize,1,MPI_INT,root_rank,_comm);
         if(_rank != root_rank)
           buf.resize(bufsize);
         _rc = MPI_Bcast(&buf[0],buf.size()*sizeofdata,MPI_CHAR,root_rank,_comm);
         return(_rc);
       };
template<typename MOType > int IRAD::Comm::CommunicatorObject::BroadCastMO (MOType & mo, int root_rank = 0) inline
Definition at line 415 of file COMM.H.
References BroadCast().
       {
         return(this->BroadCast(dynamic_cast<MobileObject *>(&mo),root_rank));
       };
template<typename MOType > int IRAD::Comm::CommunicatorObject::BroadCastMO (std::vector< MOType > & mov, int root_rank = 0) inline
Definition at line 421 of file COMM.H.
References _BroadCastMOV().
       {
         std::vector<MobileObject *> moc;
         moc.resize(mov.size());
         std::vector<MobileObject *>::iterator moci = moc.begin();
         typename std::vector<MOType>::iterator oi = mov.begin();
         while(moci != moc.end())
           *moci++ = dynamic_cast<MobileObject *>(&(*oi++));
         return(_BroadCastMOV(moc,root_rank));
       };
template<typename MOType > int IRAD::Comm::CommunicatorObject::BroadCastMobileObject (MOType & mo, int root_rank = 0) inline
Definition at line 409 of file COMM.H.
References BroadCast().
       {
         return(this->BroadCast(dynamic_cast<MobileObject *>(&mo),root_rank));
       };
template<typename MOType > int IRAD::Comm::CommunicatorObject::BroadCastMOVector (std::vector< MOType > & mov, int root_rank = 0) inline
Definition at line 433 of file COMM.H.
References _BroadCastMOV().
       {
         std::vector<MobileObject *> moc;
         moc.resize(mov.size());
         std::vector<MobileObject *>::iterator moci = moc.begin();
         typename std::vector<MOType>::iterator oi = mov.begin();
         while(moci != moc.end())
           *moci++ = dynamic_cast<MobileObject *>(&(*oi++));
         return(_BroadCastMOV(moc,root_rank));
       };
int IRAD::Comm::CommunicatorObject::Check (Comm::Ops op = Comm::MAXOP)
Definition at line 220 of file COMM.C.
References _comm, _error, _rc, and ResolveOp().
Referenced by COM::TestModule::get_communicator_module(), main(), IMPACT::ParallelTest(), COM::ParallelTest(), SolverUtils::Mesh::Partition::Read(), COM::ParallelTestingObject< CommType, ResultsType >::Test__GetSetCommunicator(), IMPACT::ParallelTestingObject< CommType, ResultsType >::Test__ParallelMidPointQuadrature(), COM::ParallelTestingObject< CommType, ResultsType >::Test__ParallelModuleLoadingTest(), IMPACT::ParallelTestingObject< CommType, ResultsType >::Test__ParallelTrapezoidQuadrature(), and COM::ParallelTestingObject< CommType, ResultsType >::Test__WindowGetSetCommunicator().
     {
       int errcheck = 0;
       // i guess for now we'll reduce max and make sure it's zero
       _rc = MPI_Allreduce(&_error,&errcheck,1,MPI_INTEGER,ResolveOp(op),_comm);
       return(errcheck);
     };
void IRAD::Comm::CommunicatorObject::ClearErr () inline
Definition at line 97 of file COMM.H.
References _error.
Referenced by COM::TestModule::get_communicator_module(), COM::ParallelTestingObject< CommType, ResultsType >::Test__GetSetCommunicator(), COM::ParallelTestingObject< CommType, ResultsType >::Test__ParallelModuleLoadingTest(), and COM::ParallelTestingObject< CommType, ResultsType >::Test__WindowGetSetCommunicator().
 {_error = 0;};
void IRAD::Comm::CommunicatorObject::ClearRequests ()
Definition at line 160 of file COMM.C.
References _recv_requests, _recv_tags, _send_requests, and _send_tags.
Referenced by BuildBorderStiffness(), GlobalDofExchange(), GlobalDofReMapExchange(), main(), TestMPI(), and WaitAll().
     {
       std::vector<MPI_Request>::iterator ri = _send_requests.begin();
       //      while(ri != _send_requests.end())
       //        MPI_Request_free(&(*ri++));
       //      ri = _recv_requests.begin();
       //      while(ri != _recv_requests.end())
       //        MPI_Request_free(&(*ri++));
       _send_requests.resize(0);
       _recv_requests.resize(0);
       _send_tags.resize(0);
       _recv_tags.resize(0);
     };
int IRAD::Comm::CommunicatorObject::Finalize ()
Definition at line 235 of file COMM.C.
References _initd, and _master.
     {
       if(_master){
         int flag = 0;
         MPI_Finalized(&flag);
         if(!flag){
           flag = 0;
           MPI_Initialized(&flag);
           if(flag){
             MPI_Finalize();
           }
         }
       }
       _initd = false;
       return(0);
     };
template<typename DataType > int IRAD::Comm::CommunicatorObject::Gather (DataType & sendval, std::vector< DataType > & recvvec, int root = 0) inline
Definition at line 307 of file COMM.H.
References _comm, _rc, Rank(), and Size().
Referenced by _GatherMO(), AllGatherMO(), AllGatherMOV(), GatherMO(), GatherMOV(), and Gatherv().
       {
         size_t messagesize = sizeof(DataType);
         if(this->Rank() == root){
           recvvec.resize(this->Size());
         }
         _rc = MPI_Gather((void *)&sendval,messagesize,MPI_CHAR,
                          (void *)&recvvec[0],messagesize,MPI_CHAR,
                          root,_comm);
         assert(_rc == 0);
         return(_rc);
       };
template<typename DataType > int IRAD::Comm::CommunicatorObject::Gather (std::vector< DataType > & sendvec, std::vector< DataType > & recvvec, int sndcnt = 0, int recvcnt = 0, int root = 0) inline
Definition at line 321 of file COMM.H.
References _comm, _nproc, _rank, and _rc.
       {
         size_t datasize = sizeof(DataType);
         if(sndcnt == 0)
           sndcnt = sendvec.size();
         if(recvcnt == 0)
           recvcnt = sndcnt;
         if(_rank == root)
           recvvec.resize(recvcnt*_nproc);
         _rc = MPI_Gather((void *)(&(sendvec[0])),sndcnt*datasize,MPI_CHAR,
                          (void *)(&(recvvec[0])),recvcnt*datasize,MPI_CHAR,
                          root,_comm);
         assert(_rc == 0);
         return(_rc);
       };
template<typename MOType > int IRAD::Comm::CommunicatorObject::GatherMO (MOType & sendval, std::vector< MOType > & recvvec, int root = 0) inline
Definition at line 449 of file COMM.H.
References _GatherMO(), _nproc, _rank, and _rc.
       {
         recvvec.resize(0);
         MobileObject *sendPtr = dynamic_cast<MobileObject *>(&sendval);
         std::vector<MobileObject *> recv_v;
         recv_v.resize(0);
         if(_rank == root){
           recvvec.resize(_nproc);
           recv_v.resize(_nproc,NULL);
           std::vector<MobileObject *>::iterator moci = recv_v.begin();
           typename std::vector<MOType>::iterator oi  = recvvec.begin();
           while(moci != recv_v.end())
             *moci++ = dynamic_cast<MobileObject *>(&(*oi++));
         }
         _rc = this->_GatherMO(sendPtr,recv_v,1,root);
         //      assert(_rc == 0);
         return(_rc);
       };
template<typename MOType > int IRAD::Comm::CommunicatorObject::GatherMO (std::vector< MOType > & sendvec, std::vector< MOType > & recvvec, std::vector< int > & nsend_all, int root = 0) inline
Definition at line 469 of file COMM.H.
References _GatherMOV(), _nproc, _rank, _rc, and Gather().
       {
         int nsend = sendvec.size();
         if(nsend_all.empty()){
           nsend_all.resize(_nproc,0);
           nsend_all[_rank] = nsend;
           this->Gather(nsend,nsend_all,root);
         }
         int nrecv = 0;
         if(_rank == root){
           std::vector<int>::iterator nsi = nsend_all.begin();
           while(nsi != nsend_all.end())
             nrecv += nsi++;
           recvvec.resize(nrecv);
         }
         std::vector<MobileObject *> send_v(nsend,NULL);
         std::vector<MobileObject *> recv_v(nrecv,NULL);
         std::vector<MobileObject *>::iterator moci = recv_v.begin();
         typename std::vector<MOType>::iterator oi  = recvvec.begin();
         while(moci != recv_v.end())
           *moci++ = dynamic_cast<MobileObject *>(&(*oi++));
         moci = send_v.begin();
         oi  = sendvec.begin();
         while(moci != send_v.end())
           *moci++ = dynamic_cast<MobileObject *>(&(*oi++));
         _rc = this->_GatherMOV(send_v,recv_v,nsend_all,root);
         //      assert(_rc == 0);
         return(_rc);
       };
template<typename MOType > int IRAD::Comm::CommunicatorObject::GatherMOV (std::vector< MOType > & sendvec, std::vector< MOType > & recvvec, std::vector< int > & nsend_all, int root = 0) inline
Definition at line 548 of file COMM.H.
References _GatherMOV(), _nproc, _rank, _rc, and Gather().
       {
         int nsend = sendvec.size();
         if(nsend_all.empty()){
           nsend_all.resize(_nproc,0);
           nsend_all[_rank] = nsend;
           this->Gather(nsend,nsend_all,root);
         }
         int nrecv = 0;
         if(_rank == root){
           std::vector<int>::iterator nsi = nsend_all.begin();
           while(nsi != nsend_all.end())
             nrecv += nsi++;
           recvvec.resize(nrecv);
         }
         std::vector<MobileObject *> send_v(nsend,NULL);
         std::vector<MobileObject *> recv_v(nrecv,NULL);
         std::vector<MobileObject *>::iterator moci = recv_v.begin();
         typename std::vector<MOType>::iterator oi  = recvvec.begin();
         while(moci != recv_v.end())
           *moci++ = dynamic_cast<MobileObject *>(&(*oi++));
         moci = send_v.begin();
         oi  = sendvec.begin();
         while(moci != send_v.end())
           *moci++ = dynamic_cast<MobileObject *>(&(*oi++));
         _rc = this->_GatherMOV(send_v,recv_v,nsend_all,root);
         //      assert(_rc == 0);
         return(_rc);
       };
template<typename DataType > int IRAD::Comm::CommunicatorObject::Gatherv (std::vector< DataType > & sendvec, std::vector< DataType > & recvvec, std::vector< int > & nsend_all, int nsend = 0, int root = 0) inline
Definition at line 339 of file COMM.H.
References _comm, _nproc, _rank, _rc, and Gather().
Referenced by _GatherMOV().
       {
         int datasize = sizeof(DataType);
         if(nsend == 0)
           nsend = sendvec.size();
         int nrecv = 0;
         if(nsend_all.empty()){
           nsend_all.resize(_nproc);
           nsend_all[_rank] = nsend;
           this->Gather(nsend,nsend_all,root);
         }
         for(int i = 0;i < _nproc;i++)
           nrecv += nsend_all[i];
         std::vector<int> allsizes(_nproc,0);
         std::vector<int> disps(_nproc,0);
         // MS : Debug: the following lines should be executed by all of the
         //      ranks, therefore if is not needed. Another problem is the
         //      datasize. MPI_CHAR datasize is 8, so 8-byte datatypes can be
         //      gathered from the client code by this method reliably.
         //if(_rank == root){
           recvvec.resize(nrecv);
           for(int i = 0; i < _nproc;i++){
             allsizes[i] = nsend_all[i] * datasize;
             if(i > 0)
               disps[i] = disps[i-1]+allsizes[i-1];
           }
         //}
         _rc = MPI_Gatherv((void *)(&(sendvec[0])),allsizes[_rank],MPI_CHAR,
                           (void *)(&(recvvec[0])),&allsizes[0],&disps[0],MPI_CHAR,
                           root,_comm);
         assert(_rc == 0);
         return(_rc);
       };
MPI_Comm IRAD::Comm::CommunicatorObject::GetCommunicator () inline
Definition at line 79 of file COMM.H.
Referenced by COM::ParallelTestingObject< CommType, ResultsType >::Test__GetSetCommunicator(), COM::ParallelTestingObject< CommType, ResultsType >::Test__ParallelModuleLoadingTest(), and COM::ParallelTestingObject< CommType, ResultsType >::Test__WindowGetSetCommunicator().
 { return (_comm); };
int IRAD::Comm::CommunicatorObject::Initialize (CommunicatorObject & incomm)
Definition at line 179 of file COMM.C.
References _comm, _initd, _master, _nproc, _own_comm, _rank, and _rc.
Referenced by CommunicatorObject(), and IRAD::Comm::ParallelObject::ParallelObject().
     {
       _comm = incomm._comm;
       _master = false;
       _own_comm = false;
       _initd = true;
       int flag = 0;
       MPI_Initialized(&flag);
       assert(flag != 0);
       if(flag == 0)
         _initd = false;
       else{
         _rc = MPI_Comm_rank(_comm,&_rank);
         //      if(_rc){
         //      return(_rc);
         //      }
         _rc = MPI_Comm_size(_comm,&_nproc);
         //      if(_rc)
         //      return(_rc);
       }
       return(0);
     };
int IRAD::Comm::CommunicatorObject::Initialize (int * narg = NULL, char *** args = NULL)
Definition at line 202 of file COMM.C.
References _comm, _initd, _master, _nproc, _own_comm, and _rc.
     {
       int flag = 0;
       MPI_Initialized(&flag);
       _comm = MPI_COMM_WORLD;
       _master = false;
       _initd = true;
       _rc = 0;
       if(flag == 0){
         _master = true;
         _own_comm = false;
         _rc = MPI_Init(narg,args);
       }
       if(_rc == 0)
         _rc = MPI_Comm_size(_comm,&_nproc);
       return(_rc);
     };
int IRAD::Comm::CommunicatorObject::NOpenRequests () inline
Definition at line 92 of file COMM.H.
References _recv_requests, and _send_requests.
 { return(_send_requests.size() + _recv_requests.size()); };
int IRAD::Comm::CommunicatorObject::Rank ()
Definition at line 228 of file COMM.C.
References _comm, and _rank.
Referenced by Gather(), main(), COM::ParallelTest(), IMPACT::ParallelTest(), SolverUtils::Mesh::Partition::Read(), IMPACT::ParallelTestingObject< CommType, ResultsType >::Test__ParallelMidPointQuadrature(), and IMPACT::ParallelTestingObject< CommType, ResultsType >::Test__ParallelTrapezoidQuadrature().
     {
       if(_rank < 0)
         MPI_Comm_rank(_comm,&_rank);
       return(_rank);
     };
int IRAD::Comm::CommunicatorObject::RecvAll ()
Definition at line 303 of file COMM.C.
References _rc, and _recv_requests.
Referenced by main().
     {
       if(_recv_requests.empty())
         return(0);
       _rc = MPI_Startall(_recv_requests.size(),&_recv_requests[0]);
       assert(_rc == 0);
       return(_rc);
     };
template<typename DataType > int IRAD::Comm::CommunicatorObject::Reduce (DataType & send, DataType & recv, const Comm::DataTypes & dt, const Comm::Ops & op, int root) inline
Definition at line 185 of file COMM.H.
References _comm, _rc, ResolveDataType(), and ResolveOp().
Referenced by main().
       {
         _rc = MPI_Reduce(&send,&recv,1,ResolveDataType(dt),
                          ResolveOp(op),root,_comm);
         assert(_rc == 0);
         return(_rc);
       };
template<typename DataType > int IRAD::Comm::CommunicatorObject::Reduce (std::vector< DataType > & send, std::vector< DataType > & recv, const Comm::DataTypes & dt, const Comm::Ops & op, int root) inline
Definition at line 196 of file COMM.H.
References _comm, _rank, _rc, ResolveDataType(), and ResolveOp().
       {
         int count = send.size();
         //    size_t datasize = sizeof(DataType);
         //    MPI_Datatype mpi_data_type = MPI_DOUBLE;
         //    if(datasize == sizeof(int))
         //      mpi_data_type = MPI_INTEGER;
         if(_rank == root)
           recv.resize(count);
         _rc = MPI_Reduce(&send[0],&recv[0],count,ResolveDataType(dt),
                          ResolveOp(op),root,_comm);
         assert(_rc == 0);
         return(_rc);
       };
MPI_Datatype IRAD::Comm::CommunicatorObject::ResolveDataType (const Comm::DataTypes & dt)
Definition at line 728 of file COMM.C.
References IRAD::Comm::DTBYTE, IRAD::Comm::DTCHAR, IRAD::Comm::DTDOUBLE, IRAD::Comm::DTFLOAT, IRAD::Comm::DTINT, IRAD::Comm::DTSIZET, IRAD::Comm::DTUBYTE, IRAD::Comm::DTUCHAR, and IRAD::Comm::DTUINT.
Referenced by AllReduce(), and Reduce().
     {
       switch(dt){
       case Comm::DTDOUBLE:
         return(MPI_DOUBLE);
       case Comm::DTFLOAT:
         return(MPI_FLOAT);
       case Comm::DTINT:
         return(MPI_INTEGER);
       case Comm::DTUBYTE:
       case Comm::DTUCHAR:
         return(MPI_UNSIGNED_CHAR);
       case Comm::DTCHAR:
       case Comm::DTBYTE:
         return(MPI_CHAR);
       case Comm::DTSIZET:
         return(MPI_LONG_LONG_INT);
       case Comm::DTUINT:
         return(MPI_UNSIGNED);
       default:
         //      return(static_cast<MPI_Datatype>(MPI_DATATYPE_NULL));
         return(MPI_DATATYPE_NULL);
       }
       // should never get here
       //    return(static_cast<MPI_Datatype>(MPI_DATATYPE_NULL));
       return(MPI_DATATYPE_NULL);
     };
MPI_Op IRAD::Comm::CommunicatorObject::ResolveOp (const Comm::Ops & op)
Definition at line 756 of file COMM.C.
References IRAD::Comm::MAXLOCOP, IRAD::Comm::MAXOP, IRAD::Comm::MINLOCOP, IRAD::Comm::MINOP, IRAD::Comm::PRODOP, and IRAD::Comm::SUMOP.
Referenced by AllReduce(), Check(), and Reduce().
     {
       switch(op){
       case Comm::MINOP:
         return(MPI_MIN);
       case Comm::MAXOP:
         return(MPI_MAX);
       case Comm::SUMOP:
         return(MPI_SUM);
       case Comm::PRODOP:
         return(MPI_PROD);
       case Comm::MAXLOCOP:
         return(MPI_MAXLOC);
       case Comm::MINLOCOP:
         return(MPI_MINLOC);
       default:
         return(MPI_OP_NULL);
       }
       return(MPI_OP_NULL);
     };
template<typename DataType > int IRAD::Comm::CommunicatorObject::Scatterv (std::vector< DataType > & sendvec, std::vector< int > & sendcounts, std::vector< DataType > & recvvec, int root = 0) inline
Definition at line 377 of file COMM.H.
References _comm, _nproc, _rank, _rc, and BroadCast().
       {
         int datasize = sizeof(DataType);
         if (sendcounts.size() == 0)
            sendcounts.resize(_nproc);
         // sending number of nrecv to each process
         this->BroadCast(sendcounts, root);
         // initializing recvec
         if (recvvec.size() == 0)
            recvvec.resize(sendcounts[_rank]);
         // calculating displs
         std::vector<int> allsizes(_nproc,0);
         std::vector<int> disps(_nproc,0);
         for(int i = 0; i < _nproc;i++){
             allsizes[i] = sendcounts[i] * datasize;
             if(i > 0)
               disps[i] = disps[i-1]+allsizes[i-1];
         }
         // scattering data
         _rc = MPI_Scatterv((void *)(&(sendvec[0])), &allsizes[0], &disps[0], MPI_CHAR,
                           (void *)(&(recvvec[0])), allsizes[_rank], MPI_CHAR,
                           root, _comm);
         assert(_rc == 0);
         return(_rc);
       };
int IRAD::Comm::CommunicatorObject::SendAll ()
Definition at line 283 of file COMM.C.
References _rc, and _send_requests.
Referenced by main().
     {
       if(_send_requests.empty())
         return(0);
       _rc = MPI_Startall(_send_requests.size(),&_send_requests[0]);
       assert(_rc == 0);
       return(_rc);
     };
int IRAD::Comm::CommunicatorObject::SetErr (int errin) inline
Definition at line 96 of file COMM.H.
References _error.
Referenced by COM::TestModule::get_communicator_module(), SolverUtils::Mesh::Partition::Read(), COM::ParallelTestingObject< CommType, ResultsType >::Test__GetSetCommunicator(), COM::ParallelTestingObject< CommType, ResultsType >::Test__ParallelModuleLoadingTest(), and COM::ParallelTestingObject< CommType, ResultsType >::Test__WindowGetSetCommunicator().
 {return(_error = errin);};
int IRAD::Comm::CommunicatorObject::SetExit (int errin) inline
Definition at line 95 of file COMM.H.
References _error.
Referenced by main(), IMPACT::ParallelTest(), COM::ParallelTest(), IMPACT::ParallelTestingObject< CommType, ResultsType >::Test__ParallelMidPointQuadrature(), and IMPACT::ParallelTestingObject< CommType, ResultsType >::Test__ParallelTrapezoidQuadrature().
 {return(_error = errin);};
template<typename DataType > int IRAD::Comm::CommunicatorObject::SetRecv (std::vector< DataType > & recvbuf, unsigned int remote_rank, int tag = 0) inline
Definition at line 147 of file COMM.H.
References _SetRecv().
Referenced by RegisterCommBuffers().
       {
         int sizeofdata = sizeof(DataType);
         int recvcnt = recvbuf.size();
         return(_SetRecv(&recvbuf[0],recvcnt*sizeofdata,remote_rank,tag));
       };
template<typename DataType > int IRAD::Comm::CommunicatorObject::SetSend (std::vector< DataType > & sendbuf, unsigned int remote_rank, int tag = 0) inline
Definition at line 138 of file COMM.H.
References _SetSend().
Referenced by RegisterCommBuffers().
       {
         int sizeofdata = sizeof(DataType);
         int sendcnt = sendbuf.size();
         return(_SetSend(&sendbuf[0],sendcnt*sizeofdata,remote_rank,tag));
       };
int IRAD::Comm::CommunicatorObject::Size ()
Definition at line 251 of file COMM.C.
References _comm, _nproc, and _rc.
Referenced by Gather(), main(), COM::ParallelTest(), IMPACT::ParallelTest(), IMPACT::ParallelTestingObject< CommType, ResultsType >::Prologue(), COM::ParallelTestingObject< CommType, ResultsType >::Prologue(), SolverUtils::Mesh::Partition::Read(), COM::ParallelTestingObject< CommType, ResultsType >::Test__FunctionBarrierTest(), COM::ParallelTestingObject< CommType, ResultsType >::Test__GetSetCommunicator(), IMPACT::ParallelTestingObject< CommType, ResultsType >::Test__ParallelMidPointQuadrature(), COM::ParallelTestingObject< CommType, ResultsType >::Test__ParallelModuleLoadingTest(), IMPACT::ParallelTestingObject< CommType, ResultsType >::Test__ParallelTrapezoidQuadrature(), and COM::ParallelTestingObject< CommType, ResultsType >::Test__WindowGetSetCommunicator().
     {
       if(_nproc <= 0)
         _rc = MPI_Comm_size(_comm,&_nproc);
       return(_nproc);
     };
int IRAD::Comm::CommunicatorObject::Split (int color, int key, CommunicatorObject & newcomm)
Definition at line 111 of file COMM.C.
References _comm, _initd, _master, _nproc, _own_comm, _rank, and _rc.
Referenced by main(), COM::ParallelTestingObject< CommType, ResultsType >::Test__GetSetCommunicator(), IMPACT::ParallelTestingObject< CommType, ResultsType >::Test__ParallelMidPointQuadrature(), COM::ParallelTestingObject< CommType, ResultsType >::Test__ParallelModuleLoadingTest(), IMPACT::ParallelTestingObject< CommType, ResultsType >::Test__ParallelTrapezoidQuadrature(), and COM::ParallelTestingObject< CommType, ResultsType >::Test__WindowGetSetCommunicator().
     {
       _rc = MPI_Comm_split(_comm,color,key,&(newcomm._comm));
       if(_rc)
         return(_rc);
       newcomm._master = false;
       newcomm._own_comm = true;
       newcomm._initd = true;
       _rc = MPI_Comm_rank(newcomm._comm,&(newcomm._rank));
       if(_rc)
         return(_rc);
       _rc = MPI_Comm_size(newcomm._comm,&(newcomm._nproc));
       return(_rc);
     };
int IRAD::Comm::CommunicatorObject::StartRecv (unsigned int rid)
Definition at line 292 of file COMM.C.
References _rc, and _recv_requests.
     {
       if(_recv_requests.empty())
         return(0);
       if(rid >= _recv_requests.size())
         return(1);
       _rc = MPI_Start(&_recv_requests[rid]);
       assert(_rc == 0);
       return(_rc);
     };
int IRAD::Comm::CommunicatorObject::StartSend (unsigned int rid)
Definition at line 270 of file COMM.C.
References _error, _rc, and _send_requests.
     {
       if(_send_requests.empty())
         return(0);
       if(rid >= _send_requests.size()){
         _error = 4;
         return(1);
       }
       _rc = MPI_Start(&_send_requests[rid]);
       assert(_rc == 0);
       return(_rc);
     };
template<typename T > int IRAD::Comm::CommunicatorObject::Union (std::vector< T > & input_data, std::vector< T > & output_data) inline
Definition at line 612 of file COMM.H.
       {
         std::vector< T > all_items;
         int err = AllGatherv< T >(input_data,all_items);
         std::sort(all_items.begin(),all_items.end());
         typename std::vector< T >::iterator ui = std::unique(all_items.begin(),all_items.end());
         output_data.resize(ui - all_items.begin());
         std::copy(all_items.begin(),ui,output_data.begin());
         return err;
       };
int IRAD::Comm::CommunicatorObject::WaitAll ()
Definition at line 135 of file COMM.C.
References _rc, _recv_requests, _send_requests, _status, and ClearRequests().
Referenced by BuildBorderStiffness(), GlobalDofExchange(), GlobalDofReMapExchange(), main(), and TestMPI().
     {
       std::vector<MPI_Request> requests;
       std::vector<MPI_Request>::iterator ri = _send_requests.begin();
       while(ri != _send_requests.end())
         requests.push_back(*ri++);
       ri = _recv_requests.begin();
       while(ri != _recv_requests.end())
         requests.push_back(*ri++);
       int count = requests.size();
       _status.resize(count);
       _rc = MPI_Waitall(count,&requests[0],&_status[0]);
       assert(_rc == 0);
       ri = requests.begin();
       while(ri != requests.end()){
         //    assert(*ri++ == MPI_REQUEST_NULL);
         if(*ri != MPI_REQUEST_NULL)
           assert(_status[ri-requests.begin()].MPI_ERROR == 0);
         ri++;
       }
       ClearRequests();
       return(_rc);
     };
int IRAD::Comm::CommunicatorObject::WaitRecv (int recvid)
Definition at line 126 of file COMM.C.
References _rc, _send_requests, and _status.
     {
       _status.resize(1);
       _rc = MPI_Wait(&_send_requests[recvid],&_status[0]);
       assert(_rc == 0);
       return(_rc);
     };
MPI_Comm IRAD::Comm::CommunicatorObject::World () inline
Definition at line 100 of file COMM.H.
References _comm.
 {return(_comm);};
Member Data Documentation
MPI_Comm IRAD::Comm::CommunicatorObject::_comm private
Definition at line 66 of file COMM.H.
Referenced by _AllGatherMO(), _AllGatherMOV(), _AllGatherv(), _ARecv(), _ASend(), _BroadCastMOV(), _GatherMO(), _GatherMOV(), _Recv(), _Send(), _SetRecv(), _SetSend(), AllGather(), AllReduce(), Barrier(), BroadCast(), Check(), CommunicatorObject(), Gather(), Gatherv(), Initialize(), Rank(), Reduce(), Scatterv(), Size(), Split(), World(), and ~CommunicatorObject().
int IRAD::Comm::CommunicatorObject::_error private
Definition at line 70 of file COMM.H.
Referenced by Check(), ClearErr(), CommunicatorObject(), SetErr(), SetExit(), and StartSend().
bool IRAD::Comm::CommunicatorObject::_initd private
Definition at line 69 of file COMM.H.
Referenced by CommunicatorObject(), Finalize(), Initialize(), Split(), and ~CommunicatorObject().
bool IRAD::Comm::CommunicatorObject::_master private
Definition at line 67 of file COMM.H.
Referenced by CommunicatorObject(), Finalize(), Initialize(), Split(), and ~CommunicatorObject().
int IRAD::Comm::CommunicatorObject::_nproc private
Definition at line 72 of file COMM.H.
Referenced by _AllGatherMO(), _AllGatherMOV(), _AllGatherv(), _GatherMO(), _GatherMOV(), AllGather(), AllGatherMO(), AllGatherMOV(), AllGatherv(), CommunicatorObject(), Gather(), GatherMO(), GatherMOV(), Gatherv(), Initialize(), Scatterv(), Size(), and Split().
bool IRAD::Comm::CommunicatorObject::_own_comm private
Definition at line 68 of file COMM.H.
Referenced by CommunicatorObject(), Initialize(), Split(), and ~CommunicatorObject().
int IRAD::Comm::CommunicatorObject::_rank private
Definition at line 65 of file COMM.H.
Referenced by _AllGatherMO(), _AllGatherMOV(), _AllGatherv(), _BroadCastMOV(), _GatherMO(), _GatherMOV(), AllGatherMO(), AllGatherMOV(), BroadCast(), CommunicatorObject(), Gather(), GatherMO(), GatherMOV(), Gatherv(), Initialize(), Rank(), Reduce(), Scatterv(), and Split().
int IRAD::Comm::CommunicatorObject::_rc private
Definition at line 71 of file COMM.H.
Referenced by _AllGatherMO(), _AllGatherMOV(), _AllGatherv(), _ARecv(), _ASend(), _BroadCastMOV(), _GatherMO(), _GatherMOV(), _Recv(), _Send(), _SetRecv(), _SetSend(), AllGather(), AllGatherMO(), AllGatherMOV(), AllReduce(), BroadCast(), Check(), CommunicatorObject(), Gather(), GatherMO(), GatherMOV(), Gatherv(), Initialize(), RecvAll(), Reduce(), Scatterv(), SendAll(), Size(), Split(), StartRecv(), StartSend(), WaitAll(), and WaitRecv().
std::vector<MPI_Request> IRAD::Comm::CommunicatorObject::_recv_requests private
Definition at line 74 of file COMM.H.
Referenced by _ARecv(), _SetRecv(), ClearRequests(), NOpenRequests(), RecvAll(), StartRecv(), and WaitAll().
std::vector<int> IRAD::Comm::CommunicatorObject::_recv_tags private
Definition at line 76 of file COMM.H.
Referenced by _ARecv(), _SetRecv(), and ClearRequests().
std::vector<MPI_Request> IRAD::Comm::CommunicatorObject::_send_requests private
Definition at line 73 of file COMM.H.
Referenced by _ASend(), _SetSend(), ClearRequests(), NOpenRequests(), SendAll(), StartSend(), WaitAll(), and WaitRecv().
std::vector<int> IRAD::Comm::CommunicatorObject::_send_tags private
Definition at line 75 of file COMM.H.
Referenced by _ASend(), _SetSend(), and ClearRequests().
std::vector<MPI_Status> IRAD::Comm::CommunicatorObject::_status private
Definition at line 77 of file COMM.H.
Referenced by WaitAll(), and WaitRecv().
MPI_Datatype IRAD::Comm::CommunicatorObject::IntegerTypeID
Definition at line 79 of file COMM.H.
The documentation for this class was generated from the following files:
COMM.H
COMM.C