IMPACT: IMPACT::ExampleProgram::ParallelProgram Class Reference
IMPACT::ExampleProgram::ParallelProgram Class Reference
Implementation of the basic parts of the parallel program example.
Detailed Description
This object encapsulates the example parallel program. It inherits from the IRAD::Global::Program type.
The program itself calculates by integrating over the interval [0,1]:
This method is MPI parallel and uses domain decomposition to calculate the total integral. On N processors, the n partitions of the domain, [0,1], are partitioned as follows:
First, the domain is broken into n equal pieces of size h:
Each processor gets a roughly equal number of pieces, . The domain on each processor, , is defined as:
With and , each processor performs the integration on its own portion of the domain:
The approximate values for the integrals on each processor, , are determined by numerical quadrature using two different methods:
IMPACT::TrapezoidQuadrature
IMPACT::MidPointQuadrature
The results of these quadrature methods from each processors are then summed to recover a total numerical estimate for :
The approximate value, and the error, are reported to stdout or, if specified, to a file.
Note
If the number of partitions, n, is less than the number of processors, N, then the program behaves as if it were serial, performing all calculations on processor 0.
The usage for this program goes like:
      pepi Usage:
      pepi [-h] [-v [arg] -o <filename> ] <input>
      -h,--help
         Prints this long version of help.
             -v,--verbosity [arg]
             -o,--output <filename>
                Specifies the name of the output file.
      <input>
                Mode-dependent input: Input <filename> for serial example
                program, or <number of divisions> for parallel example.
Definition at line 325 of file ExampleProgram.H.
#include <ExampleProgram.H>
Public Member Functions
ParallelProgram ()
Default constructor.
ParallelProgram (int nargs, char **args)
Constructor designed to take all commandline args.
ParallelProgram (ComLineType &comline, CommType &incomm)
Constructor designed to take all commandline args.
virtual int Initialize ()
Populates native data structures from commandline.
int VerbLevel () const
Returns verbosity level.
virtual ~ParallelProgram ()
Destructor.
virtual int Run ()
This function implements the main function executed by the program.
Protected Attributes
std::string output_name
Name of file for output.
int verblevel
Verbosity level.
std::ofstream Ouf
Output file stream object for output.
int ndiv
Number of partitions for domain.
Constructor & Destructor Documentation
IMPACT::ExampleProgram::ParallelProgram::ParallelProgram () inline
Definition at line 340 of file ExampleProgram.H.
References verblevel.
                         :
         ParallelProgramType()
       {verblevel = 0;};
IMPACT::ExampleProgram::ParallelProgram::ParallelProgram (int nargs, char ** args) inline
Definition at line 346 of file ExampleProgram.H.
References verblevel.
                                              :
         ParallelProgramType(nargs,args)
       {verblevel = 0;};
IMPACT::ExampleProgram::ParallelProgram::ParallelProgram (ComLineType & comline, CommType & incomm) inline
Definition at line 352 of file ExampleProgram.H.
References verblevel.
       {
         this->_command_line.Copy(comline);
         this->Init(_command_line.ProgramName(),incomm);
         verblevel = 0;
       };
virtual IMPACT::ExampleProgram::ParallelProgram::~ParallelProgram () inline virtual
Definition at line 419 of file ExampleProgram.H.
References Ouf.
{
         if(Ouf){
           Ouf.close();
           SetOutStream(std::cout);
         }
       };
Member Function Documentation
virtual int IMPACT::ExampleProgram::ParallelProgram::Initialize () inline virtual
Definition at line 361 of file ExampleProgram.H.
References ndiv, output_name, and verblevel.
Referenced by IMPACT::ExampleProgram::Driver().
       {
         int retval = ParallelProgramType::Initialize();
         // Check if the user just entered -h or --help
         if(!_command_line.GetOption("help").empty()){
           std::ostringstream Ostr;
           Ostr << _command_line.LongUsage() << std::endl;
           StdOut(Ostr.str());
           return(-1);
         }
         if(retval){ // then there were errors on the command line
           std::ostringstream Ostr;
           Ostr << _command_line.ErrorReport() << std::endl
                << std::endl << _command_line.ShortUsage() << std::endl;
           ErrOut(Ostr.str());
           return(retval);
         }
         // Everything is OK up to here, so check for an output file.
         output_name = _command_line.GetOption("output");
         // Set number of divisions to first argument
         std::vector<std::string> args(_command_line.GetArgs());
         std::istringstream Istr(args[0]);
         Istr >> ndiv;
         // Check the verbosity level
         std::string sverb(_command_line.GetOption("verbosity"));
         if(sverb.empty() || sverb == ".true.")
           verblevel = 1;
         else {
           std::istringstream Vin(sverb);
           Vin >> verblevel;
           if(verblevel < 0)
             verblevel = 1;
         }
         // If high verbosity, stick a configuration blurb to stdout.
         if(verblevel > 1){
           std::ostringstream Ostr;
           Ostr << "Configuration:" << std::endl
                << "verbosity           = " << verblevel << std::endl
                << "number of divisions = " << ndiv << std::endl;
           if(!output_name.empty())
             Ostr << "output file         = " << output_name << std::endl;
           Ostr << std::endl;
           StdOut(Ostr.str());
         }
         return(0);
       };
int IMPACT::ExampleProgram::ParallelProgram::Run () virtual
Definition at line 18 of file ExampleParallelProgram.C.
References IMPACT::ExampleProgram::f(), IMPACT::MidPointQuadrature(), ndiv, Ouf, output_name, IMPACT::TrapezoidQuadrature(), and verblevel.
Referenced by IMPACT::ExampleProgram::Driver().
     {
       // FunctionEntry("NAME"): Updates the user-defined stack and
       // the program profiles with timing information.  The placement
       // of FunctionEntry and FunctionExit calls is at the developer's
       // discretion.
       FunctionEntry("Run");
       int myid  = _communicator.Rank();
       int nproc = _communicator.Size();
       bool use_file = !output_name.empty();
       // Put out a quick blurb about number of procs just
       // to give the user confidence we are actually running
       // in parallel.  Note that when using the "StdOut" method
       // that it automatically does output only on rank 0. If
       // the developer wants asyncrhonous output, then they
       // have to revert to using standard streams.
       std::ostringstream RepStr;
       if(verblevel > 1)
         RepStr << "Running on " << nproc << " processors." << std::endl;
       StdOut(RepStr.str());
       _communicator.Barrier();
       if(verblevel > 1)
         StdOut("All procesors ready.\n");
       // Open the specified output file for writing on rank 0
       if(use_file && !myid){
         Ouf.open(output_name.c_str(),std::ios::app);
         if(!Ouf){
           // If the output file failed to open, notify
           // to error stream and return non-zero
           std::ostringstream Ostr;
           Ostr << "Error: Unable to open output file, " << output_name << ".";
           ErrOut(Ostr.str());
           // In parallel, we don't return right away since
           // this part of the code is only done on proc 0.
           // Instead, the error value is set in the communicator
           // which will indicate to all processors that there
           // has been some error.
           _communicator.SetExit(1);
         }
       }
       // Check to see if an error condition was set
       // in the file open block above.  If so, then
       // return with an error code.
       if(_communicator.Check()){
           // don't forget to tell the profiler/stacker the
           // function is exiting.
           FunctionExit("Run");
           return(1);
       }
       // Correct value of PI to several places
       double PIVAL = 3.141592653589793238462643383;
       // All processors should already have this as it
       // came from the command line - but just in case,
       // we broadcast it here to make sure.
       FunctionEntry("Broadcast");
       _communicator.BroadCast(ndiv,0);
       FunctionExit("Broadcast");
       // This block partitions the
       // domain [0,1] with ndiv
       // intervals among nproc processors
       int nper = ndiv/nproc;
       int nvol = nper*nproc;
       int leftover = ndiv - nvol;
       int myn = nper;
       if(myid < leftover)
         myn++;
       int mystart = 0;
       for(int i = 0; i < myid;i++){
         mystart += nper;
         if(i < leftover)
           mystart++;
       }
       // If there are less divisions than processors, then
       // just forget about domain decomposition and do everything
       // on processor 0.
       if(nper == 0){
         if(myid == 0) myn = ndiv;
         else myn = 0;
       }
       // Use the results from domain decomposition to
       // set the domain [a,b] for this processor and get the
       // stepsize.
       double h   = 1.0/(static_cast<double>(ndiv));
       double a = h*mystart;
       double b = a + h*myn;
       // Integrate f on this processor's subdomain using trapezoid quadrature
       FunctionEntry("TrapezoidMethod");
       double my_tpi = 0.0;
       if(myn > 0){ // if there are points in this processor's domain
         try {
           FunctionEntry("TrapezoidQuadrature");
           my_tpi = IMPACT::TrapezoidQuadrature(f,a,b,myn);
           FunctionExit("TrapezoidQuadrature");
         } catch (...){
           StdOut("Numerical limits of IMPACT::TrapezoidQuadrature exceeded.");
           my_tpi = 0.0;
         }
       }
       double tpi = 0.0;
       // Sum up the contributions from each processor and store the results on
       // processor 0 in "tpi".
       FunctionEntry("Reduce"); // time the communication
       _communicator.Reduce(my_tpi, tpi,IRAD::Comm::DTDOUBLE, IRAD::Comm::SUMOP, 0);
       FunctionExit("Reduce");  // end of the communication
       FunctionExit("TrapezoidMethod");
       // Integrate f on this processor's subdomain using midpoint quadrature
       FunctionEntry("MidPointMethod");
       double my_mppi = 0.0;
       if(myn > 0) {  // if there are points in this processor's domain
         try{
           FunctionEntry("MidPointQuadrature");
           my_mppi = IMPACT::MidPointQuadrature(f,a,b,myn);
           FunctionExit("MidPointQuadrature");
         } catch (...){
           StdOut("Numerical limits of IMPACT::MidPointQuadrature exceeded.");
           my_mppi = 0.0;
         }
       }
       double mppi = 0.0;
       // Sum up the contributions from each processor and store the results on
       // processor 0 in "mppi".
       FunctionEntry("Reduce"); // time the communication
       _communicator.Reduce(my_mppi, mppi,IRAD::Comm::DTDOUBLE, IRAD::Comm::SUMOP, 0);
       FunctionExit("Reduce");  // end of the communication
       FunctionExit("MidPointMethod");
       // Report the results to stdout or to file if one was specified.
       FunctionEntry("IO");
       if (!myid) {
         if(use_file){
           Ouf << ndiv << " " << std::setprecision(16) << tpi << " "
               << std::setprecision(4)  << std::fabs(tpi-PIVAL) << " "
               << std::setprecision(16) << mppi << " "
               << std::setprecision(4)  << std::fabs(mppi-PIVAL) << " "
               << std::endl;
           Ouf.close();
         }
         else if(verblevel) {
           std::ostringstream Ostr;
           Ostr << "With " << ndiv << " divisions, PI was calculated:" << std::endl
                << "MidPointQuadrature:  "
                << std::setprecision(16) << mppi << "\t\t"
                << std::setprecision(4) << std::fabs(mppi - PIVAL) << std::endl
                << "TrapezoidQuadrature: "
                << std::setprecision(16) << tpi << "\t\t"
                << std::setprecision(4)  << std::fabs(tpi - PIVAL) << std::endl;
           StdOut(Ostr.str());
         }
       }
       FunctionExit("IO");
       //
       // ---------- Program End ----------------
       // Update the stacker/profiler that we are exiting
       // this function.
       FunctionExit("Run");
       // return 0 for success
       return(0);
     };
int IMPACT::ExampleProgram::ParallelProgram::VerbLevel () const inline
Definition at line 415 of file ExampleProgram.H.
References verblevel.
Referenced by IMPACT::ExampleProgram::Driver().
 { return verblevel;};
Member Data Documentation
int IMPACT::ExampleProgram::ParallelProgram::ndiv protected
Definition at line 335 of file ExampleProgram.H.
Referenced by Initialize(), and Run().
std::ofstream IMPACT::ExampleProgram::ParallelProgram::Ouf protected
Definition at line 333 of file ExampleProgram.H.
Referenced by Run(), and ~ParallelProgram().
std::string IMPACT::ExampleProgram::ParallelProgram::output_name protected
Definition at line 329 of file ExampleProgram.H.
Referenced by Initialize(), and Run().
int IMPACT::ExampleProgram::ParallelProgram::verblevel protected
Definition at line 331 of file ExampleProgram.H.
Referenced by Initialize(), ParallelProgram(), Run(), and VerbLevel().
The documentation for this class was generated from the following files:
ExampleProgram.H
ExampleParallelProgram.C