IMPACT: UserSchedulerAction Class Reference
UserSchedulerAction Class Reference
Detailed Description
Definition at line 80 of file Action.h.
#include <Action.h>
Public Member Functions
UserSchedulerAction (UserScheduler *s, int n, const char *at[], int i[], void *p=0, char *name=NULL)
virtual ~UserSchedulerAction ()
virtual void init (double t)
virtual void run (double t, double dt, double alpha)
virtual void finalize ()
virtual void print (FILE *f, char *container_name)
virtual void print_toposort (FILE *f)
virtual void schedule ()
Public Member Functions inherited from Action
Action (void *p=0, const char *name=NULL)
Action (int n, const char **at, int *i=NULL, void *p=0, const char *name=NULL)
Action (int n, const std::string at[], int *i=NULL, void *p=0, const char *name=NULL)
virtual ~Action ()
virtual void declare (Scheduler &)
virtual const char * name ()
void set_name (const char *name)
virtual void print (FILE *f)
Private Attributes
UserScheduler * sched
Additional Inherited Members
Protected Types inherited from Action
enum { IN =1, OUT =2, INOUT =3 }
Protected Member Functions inherited from Action
int get_dataitem_handle (int i)
int get_dataitem_handle_const (int i)
int get_dataitem_handle (const std::string str)
void set_attr (int n, const std::string at[], int *id=NULL)
void set_attr (int n, const char *at[], int *id=NULL)
void set_io (int n, const int *io)
void set_io (const char *io)
int get_io (int i)
Protected Attributes inherited from Action
const char * action_name
char ** attr
int * idx
int count
void * usr_ptr
std::vector< int > inout
Constructor & Destructor Documentation
UserSchedulerAction::UserSchedulerAction (UserScheduler * s, int n, const char * at[], int i[], void * p = 0, char * name = NULL) inline
Definition at line 85 of file Action.h.
 : Action(n, at, i, p, name), sched(s)  {}
UserSchedulerAction::~UserSchedulerAction () virtual
Definition at line 161 of file Action.C.
References sched.
{
   if ( sched) delete sched;
 }
Member Function Documentation
void UserSchedulerAction::finalize () virtual
Reimplemented from Action.
Definition at line 180 of file Action.C.
References Scheduler::finalize_actions(), and sched.
 {
   sched->finalize_actions();
 }
void UserSchedulerAction::init (double t) virtual
Reimplemented from Action.
Definition at line 165 of file Action.C.
References Scheduler::init_actions(), and sched.
 {
   sched->init_actions(t);
 }
void UserSchedulerAction::print (FILE * f, char * container_name) virtual
Definition at line 185 of file Action.C.
References Action::name(), Scheduler::print(), and sched.
 {
   fprintf(f, "graph: { title: \"%s\" label: \"%s\" \n\
         status: folded \n\
         display_edge_labels: yes \n\
         layoutalgorithm: tree   \n\
         scaling: maxspect   \n\
         color :  red           \n\
         node.color     : black   \n\
         node.textcolor : red   \n\
         node.bordercolor: black \n\
         node.borderwidth: 1    \n\
         edge.color     : lightblue   \n\
         edge.arrowsize : 7   \n\
         edge.thickness : 2   \n\
         edge.fontname:\"helvO08\"  \n\
         node.label: \"no type\" \n", name(), name());
   sched->print(f, container_name);
   fprintf(f, "}\n");
 }
void UserSchedulerAction::print_toposort (FILE * f) virtual
Reimplemented from Action.
Definition at line 206 of file Action.C.
References sched.
 {
   fprintf(f, "( ");
   sched->print_toposort(f);
   fprintf(f, ") ");
 }
void UserSchedulerAction::run (double t, double dt, double alpha) virtual
Reimplemented from Action.
Definition at line 174 of file Action.C.
References Scheduler::run_actions(), sched, and Scheduler::set_alpha().
 {
   sched->set_alpha(alpha);
   sched->run_actions(t, dt);
 }
void UserSchedulerAction::schedule () virtual
Reimplemented from Action.
Definition at line 170 of file Action.C.
References sched, and UserScheduler::schedule().
{
   sched->schedule();
 }
Member Data Documentation
UserScheduler* UserSchedulerAction::sched private
Definition at line 83 of file Action.h.
Referenced by finalize(), init(), print(), print_toposort(), run(), schedule(), and ~UserSchedulerAction().
The documentation for this class was generated from the following files:
Action.h
Action.C