IMPACT: SolverUtils::GeoPrim::CBox Class Reference
SolverUtils::GeoPrim::CBox Class Reference
Detailed Description
Definition at line 1574 of file GeoPrimitives.H.
#include <GeoPrimitives.H>
Public Member Functions
CBox ()
CBox (const std::vector< CPoint > &pv)
CBox (const double *points, unsigned int n)
CBox (const CPoint &ip1, const CPoint &ip2)
CBox (const CBox &box)
const CPoint & P1 () const
const CPoint & P2 () const
bool empty () const
CPoint & P1 ()
CPoint & P2 ()
void init (const double *points, unsigned int n)
CBox & operator= (const CBox &b)
CBox around (const CPoint &p) const
bool operator== (const CBox &b) const
CPoint & min ()
const CPoint & min () const
CPoint & max ()
const CPoint & max () const
bool contains (const CPoint &p) const
bool contains (const double *p) const
double size () const
bool operator< (const CBox &b) const
bool operator> (const CBox &b) const
void AddPoint (const CPoint &p)
void merge (const CBox &b)
bool collide (const CBox &b) const
CBox intersect (const CBox &b) const
Protected Attributes
CPoint p1
CPoint p2
Private Attributes
bool initd
Friends
std::ostream & operator<< (std::ostream &, const CBox &)
Constructor & Destructor Documentation
SolverUtils::GeoPrim::CBox::CBox () inline
Definition at line 1582 of file GeoPrimitives.H.
References initd, p1, p2, and SolverUtils::GeoPrim::CPoint::reset().
     {
       p1.reset();
       p2.reset();
       initd=false;
     };
SolverUtils::GeoPrim::CBox::CBox (const std::vector< CPoint > & pv) inline
Definition at line 1588 of file GeoPrimitives.H.
References initd, p1, p2, SolverUtils::GeoPrim::CPoint::x(), SolverUtils::GeoPrim::CPoint::y(), and SolverUtils::GeoPrim::CPoint::z().
     {
       std::vector<CPoint>::const_iterator pvi = pv.begin();
       p1.x(pvi->x());
       p2.x(p1.x());
       p1.y(pvi->y());
       p2.y(p1.y());
       p1.z(pvi->z());
       p2.z(p1.z());
       pvi++;
       while(pvi != pv.end()){
         if(pvi->x() < p1.x()) p1.x(pvi->x());
         if(pvi->x() > p2.x()) p2.x(pvi->x());
         if(pvi->y() < p1.y()) p1.y(pvi->y());
         if(pvi->y() > p2.y()) p2.y(pvi->y());
         if(pvi->z() < p1.z()) p1.z(pvi->z());
         if(pvi->z() > p2.z()) p2.z(pvi->z());
         pvi++;
       }
       initd = true;
     }
SolverUtils::GeoPrim::CBox::CBox (const double * points, unsigned int n) inline
Definition at line 1609 of file GeoPrimitives.H.
References initd, p1, p2, SolverUtils::GeoPrim::CPoint::x(), SolverUtils::GeoPrim::CPoint::y(), and SolverUtils::GeoPrim::CPoint::z().
     {
       p1.x(points[0]);
       p1.y(points[1]);
       p1.z(points[2]);
       p2 = p1;
       for(unsigned int i = 1;i<n;i++){
         if(points[i*3] < p1.x()) p1.x(points[i*3]);
         if(points[i*3] > p2.x()) p2.x(points[i*3]);
         if(points[(i*3)+1] < p1.y()) p1.y(points[(i*3)+1]);
         if(points[(i*3)+1] > p2.y()) p2.y(points[(i*3)+1]);
         if(points[(i*3)+2] < p1.z()) p1.z(points[(i*3)+2]);
         if(points[(i*3)+2] > p2.z()) p2.z(points[(i*3)+2]);
       }
       initd = true;
     };
SolverUtils::GeoPrim::CBox::CBox (const CPoint & ip1, const CPoint & ip2) inline
Definition at line 1625 of file GeoPrimitives.H.
References initd.
       : p1(ip1),p2(ip2)
     {initd = true;};
SolverUtils::GeoPrim::CBox::CBox (const CBox & box) inline
Definition at line 1628 of file GeoPrimitives.H.
References initd.
       : p1(box.p1),p2(box.p2)
     {initd = true;};
Member Function Documentation
void SolverUtils::GeoPrim::CBox::AddPoint (const CPoint & p) inline
Definition at line 1723 of file GeoPrimitives.H.
References initd, p1, p2, SolverUtils::GeoPrim::CPoint::x(), SolverUtils::GeoPrim::CPoint::y(), and SolverUtils::GeoPrim::CPoint::z().
Referenced by SolverUtils::Mesh::FindPointInMesh(), and SolverUtils::Mesh::FindPointInMesh_2().
     {
       if(!initd){
         p1 = p;
         p2 = p;
         initd = true;
       }
       else{
         if(p.x() < p1.x()) p1.x() = p.x();
         if(p.x() > p2.x()) p2.x() = p.x();
         if(p.y() < p1.y()) p1.y() = p.y();
         if(p.y() > p2.y()) p2.y() = p.y();
         if(p.z() < p1.z()) p1.z() = p.z();
         if(p.z() > p2.z()) p2.z() = p.z();
       }
     };
CBox SolverUtils::GeoPrim::CBox::around (const CPoint & p) const inline
Definition at line 1661 of file GeoPrimitives.H.
References p1, p2, SolverUtils::GeoPrim::CPoint::x(), SolverUtils::GeoPrim::CVector::x(), SolverUtils::GeoPrim::CPoint::y(), SolverUtils::GeoPrim::CVector::y(), SolverUtils::GeoPrim::CPoint::z(), and SolverUtils::GeoPrim::CVector::z().
Referenced by SolverUtils::Mesh::FindPointInMesh(), and SolverUtils::Mesh::FindPointInMesh_2().
     {
       CVector v(p1,p2);
       CPoint minp(p.x()-fabs(v.x()/2.0),
                 p.y()-fabs(v.y()/2.0),
                   p.z()-fabs(v.z()/2.0));
       CPoint maxp(p.x()+fabs(v.x()/2.0),
                   p.y()+fabs(v.y()/2.0),
                   p.z()+fabs(v.z()/2.0));
       CBox box(minp,maxp);
       return(box);
     };
bool SolverUtils::GeoPrim::CBox::collide (const CBox & b) const inline
Definition at line 1757 of file GeoPrimitives.H.
References empty(), p1, p2, SolverUtils::GeoPrim::CPoint::x(), SolverUtils::GeoPrim::CPoint::y(), and SolverUtils::GeoPrim::CPoint::z().
Referenced by intersect().
     {
       if(this->empty() || b.empty())
         return(false);
       return(!(b.p2.x() < p1.x() || b.p1.x() > p2.x()) &&
              !(b.p2.y() < p1.y() || b.p1.y() > p2.y()) &&
              !(b.p2.z() < p1.z() || b.p1.z() > p2.z()));
     };
bool SolverUtils::GeoPrim::CBox::contains (const CPoint & p) const inline
Definition at line 1697 of file GeoPrimitives.H.
References p1, p2, SolverUtils::GeoPrim::CPoint::x(), SolverUtils::GeoPrim::CPoint::y(), and SolverUtils::GeoPrim::CPoint::z().
Referenced by SolverUtils::Mesh::FindElementsInBox().
     {
     return( p.x() <= p2.x() && p.x() >= p1.x() &&
             p.y() <= p2.y() && p.y() >= p1.y() &&
             p.z() <= p2.z() && p.z() >= p1.z() );
     };
bool SolverUtils::GeoPrim::CBox::contains (const double * p) const inline
Definition at line 1703 of file GeoPrimitives.H.
References p1, p2, SolverUtils::GeoPrim::CPoint::x(), SolverUtils::GeoPrim::CPoint::y(), and SolverUtils::GeoPrim::CPoint::z().
     {
       return( p[0] <= p2.x() && p[0] >= p1.x() &&
               p[1] <= p2.y() && p[1] >= p1.y() &&
               p[2] <= p2.z() && p[2] >= p1.z() );
     };
bool SolverUtils::GeoPrim::CBox::empty () const inline
Definition at line 1633 of file GeoPrimitives.H.
References p1, p2, SolverUtils::GeoPrim::TOL, SolverUtils::GeoPrim::CPoint::x(), SolverUtils::GeoPrim::CPoint::y(), and SolverUtils::GeoPrim::CPoint::z().
Referenced by collide(), SolverUtils::Mesh::CollideMeshWithBox(), and SolverUtils::Mesh::GetMeshBoxes().
                        {return ((std::fabs(p2.x()-p1.x()) < TOL) ||
                                 (std::fabs(p2.y()-p1.y()) < TOL) ||
                                 (std::fabs(p2.z()-p1.z()) < TOL));};
void SolverUtils::GeoPrim::CBox::init (const double * points, unsigned int n) inline
Definition at line 1638 of file GeoPrimitives.H.
References initd, p1, p2, SolverUtils::GeoPrim::CPoint::x(), SolverUtils::GeoPrim::CPoint::y(), and SolverUtils::GeoPrim::CPoint::z().
Referenced by SolverUtils::Mesh::GetMeshBoxes().
     {
       initd = true;
       p1.x(points[0]);
       p1.y(points[1]);
       p1.z(points[2]);
       p2 = p1;
       for(unsigned int i = 1;i<n;i++){
         if(points[i*3] < p1.x()) p1.x(points[i*3]);
         if(points[i*3] > p2.x()) p2.x(points[i*3]);
         if(points[(i*3)+1] < p1.y()) p1.y(points[(i*3)+1]);
         if(points[(i*3)+1] > p2.y()) p2.y(points[(i*3)+1]);
         if(points[(i*3)+2] < p1.z()) p1.z(points[(i*3)+2]);
         if(points[(i*3)+2] > p2.z()) p2.z(points[(i*3)+2]);
       }
     };
CBox SolverUtils::GeoPrim::CBox::intersect (const CBox & b) const inline
Definition at line 1765 of file GeoPrimitives.H.
References collide(), p1, p2, SolverUtils::GeoPrim::CPoint::x(), SolverUtils::GeoPrim::CPoint::y(), and SolverUtils::GeoPrim::CPoint::z().
Referenced by SolverUtils::Mesh::CollideCellsWithBox(), and SolverUtils::Mesh::CollideMeshWithBox().
     {
       CBox retval;
       if(collide(b)){
         retval.p1.x(b.p1.x() > p1.x() ? b.p1.x() : p1.x());
         retval.p1.y(b.p1.y() > p1.y() ? b.p1.y() : p1.y());
         retval.p1.z(b.p1.z() > p1.z() ? b.p1.z() : p1.z());
         retval.p2.x(b.p2.x() < p2.x() ? b.p2.x() : p2.x());
         retval.p2.y(b.p2.y() < p2.y() ? b.p2.y() : p2.y());
         retval.p2.z(b.p2.z() < p2.z() ? b.p2.z() : p2.z());
       }
       return(retval);
     };
CPoint& SolverUtils::GeoPrim::CBox::max () inline
Definition at line 1689 of file GeoPrimitives.H.
References p2.
     {
       return(p2);
     };
const CPoint& SolverUtils::GeoPrim::CBox::max () const inline
Definition at line 1693 of file GeoPrimitives.H.
References p2.
     {
       return(p2);
     };
void SolverUtils::GeoPrim::CBox::merge (const CBox & b) inline
Definition at line 1739 of file GeoPrimitives.H.
References initd, p1, p2, SolverUtils::GeoPrim::CPoint::x(), SolverUtils::GeoPrim::CPoint::y(), and SolverUtils::GeoPrim::CPoint::z().
     {
       if(initd){
         CPoint p(p1);
         p1.x((b.p1.x() > p1.x() ? p.x() : b.p1.x()));
         p1.y((b.p1.y() > p1.y() ? p.y() : b.p1.y()));
         p1.z((b.p1.z() > p1.z() ? p.z() : b.p1.z()));
         p = p2;
         p2.x(b.p2.x() < p2.x() ? p.x() : b.p2.x());
         p2.y(b.p2.y() < p2.y() ? p.y() : b.p2.y());
         p2.z(b.p2.z() < p2.z() ? p.z() : b.p2.z());
       }
       else {
         p1 = b.p1;
         p2 = b.p2;
         initd = true;
       }
     };
CPoint& SolverUtils::GeoPrim::CBox::min () inline
Definition at line 1681 of file GeoPrimitives.H.
References p1.
     {
     return(p1);
     };
const CPoint& SolverUtils::GeoPrim::CBox::min () const inline
Definition at line 1685 of file GeoPrimitives.H.
References p1.
     {
       return(p1);
     };
bool SolverUtils::GeoPrim::CBox::operator< (const CBox & b) const inline
Definition at line 1715 of file GeoPrimitives.H.
References size().
     {
       return(this->size() < b.size());
     };
CBox& SolverUtils::GeoPrim::CBox::operator= (const CBox & b) inline
Definition at line 1654 of file GeoPrimitives.H.
References initd, p1, and p2.
     {
       p1 = b.p1;
       p2 = b.p2;
       initd = true;
       return(*this);
     };
bool SolverUtils::GeoPrim::CBox::operator== (const CBox & b) const inline
Definition at line 1673 of file GeoPrimitives.H.
References p1, and p2.
     {
       return(p1 == b.p1 && p2 == b.p2);
     };
bool SolverUtils::GeoPrim::CBox::operator> (const CBox & b) const inline
Definition at line 1719 of file GeoPrimitives.H.
References size().
     {
       return(this->size() > b.size());
     };
const CPoint& SolverUtils::GeoPrim::CBox::P1 () const inline
Definition at line 1631 of file GeoPrimitives.H.
References p1.
Referenced by SolverUtils::Mesh::GenerateCartesianGrid(), and SolverUtils::GeoPrim::operator<<().
 {return p1;};
CPoint& SolverUtils::GeoPrim::CBox::P1 () inline
Definition at line 1636 of file GeoPrimitives.H.
References p1.
 {return p1;};
const CPoint& SolverUtils::GeoPrim::CBox::P2 () const inline
Definition at line 1632 of file GeoPrimitives.H.
References p2.
Referenced by SolverUtils::Mesh::GenerateCartesianGrid(), and SolverUtils::GeoPrim::operator<<().
 {return p2;};
CPoint& SolverUtils::GeoPrim::CBox::P2 () inline
Definition at line 1637 of file GeoPrimitives.H.
References p2.
 {return p2;};
double SolverUtils::GeoPrim::CBox::size () const inline
Definition at line 1710 of file GeoPrimitives.H.
References p1, p2, SolverUtils::GeoPrim::CVector::x(), SolverUtils::GeoPrim::CVector::y(), and SolverUtils::GeoPrim::CVector::z().
Referenced by operator<(), and operator>().
     {
       CVector v(p1,p2);
       return(fabs(v.x()*v.y()*v.z()));
     };
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & oS, const CBox & b) friend
Definition at line 68 of file GeoPrimitives.C.
   {
     oS << b.P1() << "  " << b.P2();
     return(oS);
   }
Member Data Documentation
bool SolverUtils::GeoPrim::CBox::initd private
Definition at line 1577 of file GeoPrimitives.H.
Referenced by AddPoint(), CBox(), init(), merge(), and operator=().
CPoint SolverUtils::GeoPrim::CBox::p1 protected
Definition at line 1579 of file GeoPrimitives.H.
Referenced by AddPoint(), around(), CBox(), collide(), contains(), empty(), init(), intersect(), merge(), min(), operator=(), operator==(), P1(), and size().
CPoint SolverUtils::GeoPrim::CBox::p2 protected
Definition at line 1580 of file GeoPrimitives.H.
Referenced by AddPoint(), around(), CBox(), collide(), contains(), empty(), init(), intersect(), max(), merge(), operator=(), operator==(), P2(), and size().
The documentation for this class was generated from the following file:
GeoPrimitives.H