IMPACT: COM_Object_derived Class Reference
COM_Object_derived Class Reference
Detailed Description
Definition at line 561 of file COM_base.C.
Static Public Member Functions
static bool cast_obj ()
Protected Types
enum { DERIVED_COOKIE =3374833 }
Protected Member Functions
COM_Object_derived ()
virtual ~COM_Object_derived ()
void validate_object (int *ierr)
Protected Attributes
int _cookie
Member Enumeration Documentation
anonymous enum protected
Enumerator
DERIVED_COOKIE
Definition at line 584 of file COM_base.C.
 { DERIVED_COOKIE=3374833 };
Constructor & Destructor Documentation
COM_Object_derived::COM_Object_derived () inline protected
Definition at line 574 of file COM_base.C.
 : _cookie( DERIVED_COOKIE) {}
virtual COM_Object_derived::~COM_Object_derived () inline protected virtual
Definition at line 576 of file COM_base.C.
 {}
Member Function Documentation
static bool COM_Object_derived::cast_obj () inline static
Definition at line 563 of file COM_base.C.
References IMPACT::ExampleProgram::f(), and validate_object().
Referenced by COM::COM_base::set_object().
{
     typedef void(COM_Object::*Member_Func)( int *);
     Member_Func f = (Member_Func)&COM_Object_derived::validate_object;
     COM_Object_derived obj;
     int ierr; (reinterpret_cast<COM_Object*>((void *)&obj)->*f)( &ierr);
     return ierr != 0;
   }
void COM_Object_derived::validate_object (int * ierr) inline protected
Definition at line 578 of file COM_base.C.
References _cookie, and DERIVED_COOKIE.
Referenced by cast_obj().
{
     if ( _cookie != DERIVED_COOKIE) *ierr = -1;
     else *ierr = COM_Object::validate_object();
   }
Member Data Documentation
int COM_Object_derived::_cookie protected
Definition at line 585 of file COM_base.C.
Referenced by validate_object().
The documentation for this class was generated from the following file:
COM_base.C