IMPACT: COM::COM_base Class Reference
COM::COM_base Class Reference
The base class for COM implementations.
Detailed Description
Definition at line 22 of file COM_base.hpp.
#include <COM_base.hpp>
Public Types
typedef Window::Pointer_descriptor Pointer_descriptor
Public Member Functions
template<class T >
void set_member_function_helper (const std::string &wfname, T ptr, const std::string &waname, const std::string &intents, const COM_Type *types, bool ff) throw (int)
Module management
void load_module (const std::string &lname, const std::string &wname) throw (int)
Load a module.
void unload_module (const std::string &lname, const std::string &wname, int dodl=1) throw (int)
Unload a module.
Window and pane management
void new_window (const std::string &wname, MPI_Comm comm) throw (int)
Creates a window with given name.
void delete_window (const std::string &wname) throw (int)
Deletes a window with given name.
void window_init_done (const std::string &wname, bool panechanged=true) throw (int)
Marks the end of the registration of a window.
void delete_pane (const std::string &wname, const int pid) throw (int)
Deletes a pane and its associated data.
DataItem management
void new_dataitem (const std::string &wa, const char loc, const int data_type, int size, const std::string &unit) throw (int)
Creates a new dataitem for a window.
void delete_dataitem (const std::string &wa) throw (int)
Delete an existing dataitem from a window.
void set_size (const std::string &wa_str, int pane_id, int nitems, int ng=0) throw (int)
Set the sizes of an dataitem.
void set_object (const std::string &wa, const int pane_id, void *obj_addr, void *casted_obj) throw (int)
Associates an object with a specific window.
void get_object (const std::string &wa, const int pane_id, void **ptr) throw (int)
Associates an object with a specific window.
void set_array (const std::string &wa, const int pane_id, void *addr, int strd=0, int cap=0, bool is_const=false) throw (int)
Associates an array with an dataitem for a specific pane.
template<class T >
void set_bounds (const std::string &wa, const int pane_id, T lbnd, T ubnd) throw (int)
template<class T >
void set_bounds (const std::string &wa, const int pane_id, const T *lbnd, const T *ubnd) throw (int)
void set_bounds (const std::string &wa, const int pane_id, const void *lbnd, const void *ubnd) throw (int)
void get_bounds (const std::string &wa, const int pane_id, void *lbnd, void *ubnd) throw (int)
int check_bounds (const std::string &wa, int pane_id) throw (int)
void allocate_array (const std::string &wa, const int pane_id=0, void **addr=NULL, int strd=0, int cap=0) throw (int)
Allocate space for an dataitem on a specific pane and return the address by setting addr.
void resize_array (const std::string &wa, const int pane_id=0, void **addr=NULL, int strd=-1, int cap=0) throw (int)
Resize an dataitem on a specific pane and return the address by setting addr.
void append_array (const std::string &wa, const int pane_id, const void *val, int v_strd, int v_size) throw (int)
Append an array to the end of the dataitem on a specific pane and return the new address by setting addr.
void use_dataitem (const std::string &wname, const std::string &pwname, int withghost=1, const char *cndname=NULL, int val=0) throw (int)
Use the subset of panes of another window of which the given pane dataitem has value val.
void clone_dataitem (const std::string &wname, const std::string &pwname, int withghost=1, const char *cndname=NULL, int val=0) throw (int)
Clone the subset of panes of another window of which the given pane dataitem has value val.
void copy_dataitem (const std::string &wname, const std::string &pwname, int withghost=1, const char *cndname=NULL, int val=0) throw (int)
Copy an dataitem onto another.
void copy_dataitem (int trg_hdl, int src_hdl, int withghost=1, int ptn_hdl=0, int val=0) throw (int)
Copy an dataitem onto another.
void deallocate_array (const std::string &wa, const int pid=0) throw (int)
Deallocate space for an dataitem in a pane, asuming the memory was allocated allocate_mesh or allocate_dataitem.
void get_dataitem (const std::string &wa_str, char *loc, int *type, int *size, std::string *unit) throw (int)
Information retrieval Get the information about an dataitem.
void get_size (const std::string &wa_str, int pane_id, int *size, int *ng=0) throw (int)
Get the sizes of an dataitem. The opposite of set_size.
int get_status (const std::string &wa_str, int pane_id) throw (int)
Get the status of an dataitem.
void get_array (const std::string &wa, const int pane_id, void **addr, int *strd=NULL, int *cap=0, bool is_const=false) throw (int)
Get the address for an dataitem on a specific pane.
void get_array (const std::string &wa, const int pane_id, Pointer_descriptor &addr, int *strd=NULL, int *cap=0, bool is_const=false) throw (int)
Get the address for an dataitem on a specific pane.
void copy_array (const std::string &wa, const int pane_id, void *val, int v_strd=0, int v_size=0, int offset=0) throw (int)
Copy an array from an dataitem on a specific pane into a given buffer.
void set_f90pointer (const std::string &waname, void *ptr, Func_ptr f, long int l) throw (int)
void get_f90pointer (const std::string &waname, void *ptr, Func_ptr f, long int l) throw (int)
Information retrieval
MPI_Comm get_communicator (const std::string &wname) throw (int)
void get_windows (std::vector< std::string > &) throw (int)
Obtain a list of all window names.
void get_modules (std::vector< std::string > &) throw (int)
Obtain a list of all module names.
void get_panes (const std::string &wname, std::vector< int > &paneids_vec, int rank=-2, int **pane_ids=NULL) throw (int)
Obtain the panes of a given window on a specific process.
void get_dataitems (const std::string &wname, int *na, std::string &str, char **names=NULL) throw (int)
Obtain the user-defined dataitems of the given window.
void get_connectivities (const std::string &wname, int pane_id, int *nc, std::string &str, char **names=NULL) throw (int)
Obtain the connectivity tables of a pane of the given window.
void get_parent (const std::string &waname, int pane_id, std::string &str, char **name=NULL) throw (int)
Obtain the parent dataitem's name of a given dataitem on a given pane.
void free_buffer (int **buf)
void free_buffer (char **buf)
int get_window_handle (const std::string &wname) throw (int)
Window * get_window_object (int hdl) throw (int)
const Window * get_window_object (int hdl) const throw (int)
Window * get_window_object (const std::string &wname) throw (int)
const Window * get_window_object (const std::string &wname) const throw (int)
int get_dataitem_handle (const std::string &waname) throw (int)
int get_dataitem_handle_const (const std::string &waname) throw (int)
int get_function_handle (const std::string &wfname) throw (int)
Function management
void set_function (const std::string &wf, Func_ptr ptr, const std::string &intents, const COM_Type *types, bool ff=false) throw (int)
Registers a function to the window.
void set_member_function (const std::string &wf, Func_ptr ptr, const std::string &wa, const std::string &intents, const COM_Type *types, bool ff=false) throw (int)
void set_member_function (const std::string &wf, Member_func_ptr ptr, const std::string &wa, const std::string &intents, const COM_Type *types, bool ff=false) throw (int)
int get_num_arguments (const std::string &wf) throw (COM_exception)
Get the number of arguments of a given function "window.function".
int get_num_arguments (const int wf) throw (COM_exception)
Get the number of arguments of a given function from its handle.
void call_function (int wf, int count, void **args, const int *lens=NULL, bool from_c=true) throw (int)
Invoke a function with given arguments.
void icall_function (int wf, int count, void *args[], int *reqid, const int *lens=NULL) throw (int)
Nonblockingly invoke a function with given arguments.
void wait (int)
Wait for the completion of a nonblocking call.
int test (int)
Test whether a nonblocking call has finished.
Profiling and tracing tools
int get_verbose () const
Determines whether verbose is on.
void set_verbose (int v)
Changes the verbose setting.
void set_function_verbose (int i, int level) throw (int)
void set_profiling (int i)
This subroutine turns on (or off) profiling if i==1 (or ==0).
void set_profiling_barrier (int hdl, MPI_Comm comm)
void print_profile (const std::string &fname, const std::string &header)
Protected Member Functions
template<class T >
void set_member_function_helper (const std::string &wf, T ptr, const std::string &wa, const std::string &intents, const COM_Type *types, bool ff=false) throw (int)
std::pair< int, int > get_f90pntoffsets (const DataItem *a)
COM_base ()
Window management
Window & get_window (const std::string &wname) throw (COM_exception)
Obtains a reference to the Window object from its name.
const Window & get_window (const std::string &wname) const throw (COM_exception)
Obtains a constant reference to the Window object from its name.
DataItem & get_dataitem (const int) throw (COM_exception)
Obtains a reference to an dataitem from its handle.
const DataItem & get_dataitem (const int) const throw (COM_exception)
Obtains a const reference to an dataitem from its handle.
Function & get_function (const int) throw (COM_exception)
Obtains a reference to an dataitem from its handle.
const Function & get_function (const int) const throw (COM_exception)
Obtains a const reference to an dataitem from its handle.
Protected Attributes
Module_map _module_map
Window_map _window_map
DataItem_map _attr_map
Function_map _func_map
std::string _libdir
Library directory.
std::vector< double > _timer
Timers for function calls.
int _depth
Depth of procedure calls.
int _verbose
Indicates whether verbose is on.
int _verb1
Indicates whether to print detailed information.
MPI_Comm _comm
Default communicator of COM.
bool _mpi_initialized
Indicates whether MPI was initialized by COM.
int _errorcode
Error code.
bool _exception_on
Indicates whether COM should throw exception.
bool _profile_on
Indicates whether should profile.
int _f90_mangling
Encoding name mangling.
int _f90ptr_treat
Treatement of F90 pointers.
int _cppobj_casting
Treatement of C++ objects.
Static Protected Attributes
static COM_base * com_base =NULL
Private Types
typedef COM_map< Window * > Window_map
typedef COM_map< std::pair
< void *, std::set
< std::string > > > Module_map
typedef COM_map< DataItem * > DataItem_map
Initialization and Finalization
COM_base (int *argc, char ***argv) throw (COM_exception, int)
Constructor.
~COM_base ()
Destructor.
static void init (int *argc, char ***argv) throw (int)
static void finalize () throw (int)
static void abort (int ierr)
static void set_default_communicator (MPI_Comm comm)
Set the default communicator of COM.
static MPI_Comm get_default_communicator ()
Get the default communicator of COM.
static void set_com (COM_base *)
Set the COM pointer to the given object.
static COM_base * get_com ()
Get a pointer to the COM object.
static bool initialized ()
Checks whether COM has been initialized.
Miscellaneous
enum { FPTR_NONE =0, FPTR_INSERT =1, FPTR_APPEND =2 }
int get_error_code () const
Get the error code.
void turn_on_exception ()
void turn_off_exception ()
int f90ptr_treat () const
static int get_sizeof (COM_Type type, int count=1)
Gets the size of the data type given by its index.
int split_name (const std::string &wa, std::string &wname, std::string &aname, bool tothrow=true) throw (COM_exception)
Extracts the window and dataitem names from "window.dataitem".
void proc_exception (const COM_exception &, const std::string &) throw (int)
Member Typedef Documentation
typedef COM_map<DataItem*> COM::COM_base::DataItem_map private
Definition at line 25 of file COM_base.hpp.
typedef COM_map<std::pair<void *, std::set<std::string> > > COM::COM_base::Module_map private
Definition at line 24 of file COM_base.hpp.
typedef Window::Pointer_descriptor COM::COM_base::Pointer_descriptor
Definition at line 27 of file COM_base.hpp.
typedef COM_map<Window*> COM::COM_base::Window_map private
Definition at line 23 of file COM_base.hpp.
Member Enumeration Documentation
anonymous enum
Enumerator
FPTR_NONE
FPTR_INSERT
FPTR_APPEND
Definition at line 379 of file COM_base.hpp.
 { FPTR_NONE=0, FPTR_INSERT=1, FPTR_APPEND=2};
Constructor & Destructor Documentation
COM_base::COM_base (int * argc, char *** argv) throw (COM_exception, int)
Definition at line 48 of file COM_base.C.
References COMMPI_Comm_rank(), COMMPI_Initialized(), remove_arg(), and s.
   : _depth(0), _verbose(0), _verb1(0), _comm(MPI_COMM_WORLD),
     _mpi_initialized(false), _errorcode(0), _exception_on(true), _profile_on(0)
 {
   _attr_map.add_object("",NULL);
   _func_map.add_object("",NULL);
   _errorcode = 0;
 #ifdef PREFIX
   _libdir = std::string(PREFIX);
 #endif
   const char *comhome = std::getenv( "COM_HOME");
   if ( comhome) _libdir = comhome;
   else {
     comhome = std::getenv( "ROCSTAR_HOME");
     if ( comhome) _libdir = comhome;
   }
   if ( !_libdir.empty()) _libdir.append( "/lib/");
   // Parse command-line options
   std::map<int,int> verb_maps; // Process-specific verbose level
   int i=1;
   while ( argc && i<*argc) {
     if ( std::strncmp((*argv)[i], "-com-v", 6) == 0) {
       // Check whether a number follows -com-v
       const char *s=(*argv)[i]+6;
       int rank = -1; // Default are all processes
       if ( s[0] != '\0') rank = std::atoi( s);
       int verb=1;
       if ( *argc>i+1 && (*argv)[i+1][0]>='0' && (*argv)[i+1][0]<='9')
       { verb = std::atoi( (*argv)[i+1]); remove_arg( argc, argv, i+1); }
       if ( rank == -1) set_verbose(verb);
       else verb_maps[rank] = verb;
       remove_arg( argc, argv, i);
     }
     else if ( std::strcmp((*argv)[i], "-com-mpi") == 0) {
       if ( !COMMPI_Initialized()) _mpi_initialized=true;
       remove_arg( argc, argv, i);
     }
     else if ( std::strcmp((*argv)[i], "-com-home") == 0) {
       if ( *argc>i+1 && (*argv)[i+1][0]>='0' && (*argv)[i+1][0]<='9') {
         _libdir = (*argv)[i+1];   _libdir.append( "/lib/");
         remove_arg( argc, argv, i+1);
       }
       remove_arg( argc, argv, i);
     }
     else
       ++i;
   }
   // Initialize MPI if requested and MPI is not yet initialized.
   if(_mpi_initialized) MPI_Init( argc, argv);
   // Set process-specific verbose level
   int rank = 0;
   if ( COMMPI_Initialized()) rank = COMMPI_Comm_rank( MPI_COMM_WORLD);
   std::map<int,int>::const_iterator it=verb_maps.find( rank);
   if ( it!=verb_maps.end()) set_verbose( it->second);
   // Determine the F90 pointer treatment mode
   _f90_mangling = -1;
   _f90ptr_treat = -1;
 #if defined(__GNUC__) && !defined(__INTEL_COMPILER)
   // For GNU C++, we know to use the csated address.
   _cppobj_casting = 1;
 #elif defined(_POWER) || defined(__INTEL_COMPILER)
   // For IBM and INTEL compilers, we know to use the object's address
   _cppobj_casting = 0;
 #else
   _cppobj_casting = -1;
 #endif
   if ( _verbose) {
     std::cerr << "COM Version 1.1, 11/01/2013" << std::endl;
     std::cerr << "COM: Started with verbose level " << _verbose << std::endl;
 #ifndef DUMMY_MPI
     if ( !COMMPI_Initialized())
       std::cerr << "COM: MPI not initialized. Running in serial mode\n";
 #else
     std::cerr << "COM: Running in serial mode with DUMMY_MPI\n";
 #endif
   }
 }
COM_base::~COM_base ()
Definition at line 140 of file COM_base.C.
                     {
   // If MPI was initialized by COM, then call MPI_Finalize.
   if (_mpi_initialized) MPI_Finalize();
 }
COM::COM_base::COM_base () protected
Member Function Documentation
void COM_base::abort (int ierr) static
Definition at line 164 of file COM_base.C.
References COMMPI_Initialized().
Referenced by COM_abort().
{
   if ( COMMPI_Initialized() ) MPI_Abort( MPI_COMM_WORLD, ierr);
   else exit( ierr);
 }
void COM_base::allocate_array (const std::string & wa, const int pane_id = 0, void ** addr = NULL, int strd = 0, int cap = 0) throw (int)
Allocate for all panes if pane-id is 0, in which case, do not set addr.
Definition at line 667 of file COM_base.C.
References append_frame, COM_exception::msg, and s.
Referenced by COM_allocate_array(), COM_F_FUNC2(), and com_obtain_array_helper().
 {
   try {
     if ( _verb1>1) {
       std::cerr << "COM: Allocate array for \"" << wa << "\" on pane "
                 << pid << " with stride ";
       if ( strd) std::cerr << strd;
       else std::cerr << "==#components";
       std::cerr << " and capacity ";
       if ( cap) std::cerr << cap;
       else std::cerr << "==#items";
       std::cerr << std::endl;
     }
     std::string wname, aname;
     split_name( wa, wname, aname);
     get_window( wname).alloc_array( aname, pid, addr, strd, cap);
     _errorcode = 0;
   }
   catch ( COM_exception ex) {
     ex.msg = append_frame( ex.msg, COM_base::allocate_array);
     std::string s;
     s = s + "When processing dataitem " + wa;
     proc_exception( ex, s);
   }
 }
void COM_base::append_array (const std::string & wa, const int pane_id, const void * val, int v_strd, int v_size) throw (int)
Definition at line 731 of file COM_base.C.
References append_frame, COM_exception::msg, and s.
Referenced by COM_append_array(), and com_append_array_helper().
 {
   try {
     if ( _verb1>1)
       std::cerr << "COM: Appending array " << val << " for \"" << wa
                 << "\" on pane " << pid << " with stride " << v_strd
                 << " and size " << v_size << std::endl;
     std::string wname, aname;
     split_name( wa, wname, aname);
     get_window( wname).append_array( aname, pid, val, v_strd, v_size);
     _errorcode = 0;
   }
   catch ( COM_exception ex) {
     ex.msg = append_frame( ex.msg, COM_base::append_array);
     std::string s("When processing dataitem "); s.append(wa);
     proc_exception( ex, s);
   }
 }
void COM_base::call_function (int wf, int count, void ** args, const int * lens = NULL, bool from_c = true) throw (int)
Parameters
wf the handle to the function.
count the number of input arguments.
args the addresses to the arguments.
lens the lengths of character strings.
Definition at line 1714 of file COM_base.C.
References append_frame, COM_assertion_msg, COM_CHAR, COM_CHARACTER, COM_DOUBLE, COM_DOUBLE_PRECISION, COM_ERR_DATAITEM_CONST, COM_ERR_IMMUTABLE, COM_ERR_TOO_FEW_ARGS, COM_ERR_TOO_MANY_ARGS, COM_F90POINTER, COM_FLOAT, COM_INT, COM_INTEGER, COM_LOGICAL, COM_LONG, COM_MPI_COMMC, COM_MPI_COMMF, COM_REAL, COM_STRING, COMMPI_Comm_c2f(), COMMPI_Comm_f2c(), Function::data_type(), DataItem::data_type(), Function::dataitem(), get_wtime(), Function::intent(), DataItem::is_const(), Function::is_fortran(), Function::is_literal(), Function::is_optional(), Function::is_rawdata(), max(), MAX_NAMELEN, Function::MAX_NUMARG, COM_exception::msg, ComponentInterface::name(), DataItem::name(), Function::num_of_args(), DataItem::pointer(), and DataItem::window().
Referenced by COM_call_function(), COM_F_FUNC2(), and icall_function().
{
   // COM prints out the trace upto (verb-1)/2 depth.
   // If verb is even, then it will also print the arguments.
   try {
     if ( wf==0) {
       if ( _verbose) {
         std::cerr << "COM: ************* CALL(" << _depth << ") "
                   << "on NOOP with " << count << " arguments" << std::endl;
       }
       return;  // Null function
     }
     Function *func = &get_function( wf);
     int  verb = std::max(_verbose, int(_func_map.verbs[ wf]))-_depth*2;
     if ( verb<=0) verb = 0;
     else verb = (verb+1)%2+1;
     if ( verb) {
       std::cerr << "COM: CALL(" << _depth << ") "
                 << _func_map.name(wf);
       if ( verb>1) std::cerr << '(';
     }
     std::vector<char> strs[Function::MAX_NUMARG+1];
     bool  needpostproc=false;
     int  li=0;
     void *ps[2*Function::MAX_NUMARG+1];
     int  lcount = 0;
     void **plen = NULL;
     if ( func->is_fortran()) plen = ps+func->num_of_args();
     // attr must be const to void throwing exception when pointer is called
     const DataItem *attr = func->dataitem();
     int offset = (attr!=NULL);
     count += offset;
     args  -= offset;
     if ( count > func->num_of_args())
       throw COM_exception(COM_ERR_TOO_MANY_ARGS);
     if ( offset) {
       if ( verb>1)
         std::cerr << std::endl << '\t' << func->intent(0) << ": ";
       if ( func->is_rawdata( 0)) {
         if ( attr->is_const() && std::tolower(func->intent(0)) != 'i')
           throw COM_exception( COM_ERR_DATAITEM_CONST);
         if ( attr->data_type()==COM_F90POINTER) {
           std::pair<int,int> offs = get_f90pntoffsets( attr);
           ps[0] = (char*)const_cast<void*>(attr->pointer())+offs.first;
           // Add pointer information for PortlandGroup Compiler
           COM_assertion_msg( _f90ptr_treat>=0, "No F90 pointer initalized");
           if ( _f90ptr_treat == FPTR_INSERT) {
             *plen = *(void**)((char*)const_cast<void*>(attr->pointer())
                               +offs.second);
             ++lcount; ++plen;
           }
         }
         else
           ps[0] = (char*)const_cast<void*>(attr->pointer());
         if ( verb>1)
           std::cerr << "VALUE OF\t@" << ps[0] << "\t\""
                     << attr->window()->name() << '.' << attr->name() << '"';
       }
       else {
         ps[0] = const_cast<DataItem*>(attr);
         if ( verb>1)
           std::cerr << "METADATA\t@" << ps[0] << "\t\""
                     << attr->window()->name() << '.' << attr->name() << '"';
       }
     }
     for ( int i=offset; i<count; ++i) {
       if ( verb>1) {
         std::cerr << std::endl << '\t' << func->intent(i) << ": ";
       }
       if ( func->is_literal(i)) {
         ps[i] = args[i];
         COM_Type type = func->data_type(i);
         char intent = func->intent(i);
         if ( type == COM_CHARACTER || type == COM_CHAR || type == COM_STRING) {
           if ( type == COM_STRING) {
             // Make sure it is NULL terminated
             if (lens && (intent=='i' || intent=='I' ||
                          intent=='b' || intent=='B') &&
                 ( lens[li]==0 || ((char*)args[i])[lens[li]-1] != '\0')) {
               strs[i].resize( lens[li]+1, '\0');
               std::strncpy( &strs[i][0], (char*)args[i], lens[li]);
               ps[i] = &strs[i][0];
               if (intent=='b' || intent=='B') needpostproc=true;
             }
             if ( plen) { // Append the length info
               *plen = (char*)NULL+std::strlen((char*)ps[i]); ++plen; ++lcount;
             }
           }
           else if ( plen) {
             *plen = (char*)NULL+1; ++plen; ++lcount;
           }
           ++li;
         }
         else if ( type == COM_MPI_COMMC && !from_c) {
           strs[i].resize( 2*sizeof( MPI_Comm));
           ps[i] = &strs[i][0]+(sizeof( MPI_Comm)-
                                ((long int)&strs[i][0])%sizeof(MPI_Comm));
           if (intent=='i' || intent=='I' || intent=='b' || intent=='B')
             *(MPI_Comm*)ps[i] = COMMPI_Comm_f2c( *(int*)args[i], MPI_Comm());
           if (intent=='o' || intent=='O' || intent=='b' || intent=='B')
             needpostproc=true;
         }
         else if ( type == COM_MPI_COMMF && from_c) {
           strs[i].resize( 2*sizeof( int));
           ps[i] = &strs[i][0]+(sizeof(int)-((long int)&strs[i][0])%sizeof(int));
           if (intent=='i' || intent=='I' || intent=='b' || intent=='B')
             *(int*)ps[i] = COMMPI_Comm_c2f( *(MPI_Comm*)args[i]);
           if (intent=='o' || intent=='O' || intent=='b' || intent=='B')
             needpostproc=true;
         }
         if (verb>1) {
           switch (type) {
           case COM_STRING:
             std::cerr << "STRING\t@" << args[i] << "\t";
             if ( args[i]) std::cerr << '\"' << (char*)ps[i] << '\"';
             break;
           case COM_CHAR: case COM_CHARACTER:
             std::cerr << "CHAR  \t@" << args[i] << "\t";
             if ( args[i]) std::cerr << '\'' << *(char*)args[i] << '\'';
             break;
           case COM_DOUBLE:
           case COM_DOUBLE_PRECISION:
             std::cerr << "double\t@" << args[i] << '\t';
             if ( args[i]) std::cerr << *(double*)args[i];
             break;
           case COM_INT:
           case COM_LONG:
           case COM_INTEGER:
             std::cerr << "int   \t@" << args[i] << '\t';
             if ( args[i]) std::cerr << *(int*)args[i];
             break;
             case COM_FLOAT:
           case COM_REAL:
             std::cerr << "float \t@" << args[i] << '\t';
             if ( args[i]) std::cerr << *(float*)args[i];
             break;
           case COM_LOGICAL:
             std::cerr << "logical\t@" << args[i] << '\t';
             if ( args[i]) std::cerr << *(int*)args[i];
             break;
           case COM_MPI_COMMC:
             std::cerr << "MPI_Comm (C)\t@" << args[i] << '\t';
             if ( args[i]) std::cerr << *(MPI_Comm*)args[i];
             break;
           case COM_MPI_COMMF:
             std::cerr << "MPI_Comm (F)\t@" << args[i] << '\t';
             if ( args[i]) std::cerr << *(int*)args[i];
             break;
           default:
             std::cerr << "type(" << type << ")\t@" << args[i];
           }
         }
       }
       else {
         int h=*(int*)args[i];
         if ( h == 0 && func->intent(i)<='Z') {
           // Optional dataitem received a 0 dataitem handle
           ps[i] = NULL;
           if ( verb>1)
             std::cerr << "ZERO DATAITEM HANDLE";
           continue;
         }
         // attr must be const to void throwing exception when pointer is called
         const DataItem *attr = &get_dataitem( h);
         if ( attr->is_const() && std::tolower(func->intent(i)) != 'i')
           throw COM_exception( COM_ERR_DATAITEM_CONST);
         if ( func->is_rawdata( i)) {
           ps[i] = const_cast<void*>(attr->pointer());
           if ( verb>1)
             std::cerr << "VALUE OF\t@" << ps[i]
                       << "\t\"" << _attr_map.name(h) << '"';
         }
         else {
           ps[i] = const_cast<DataItem*>(attr);
           if ( verb>1)
             std::cerr << "METADATA\t@" << ps[i]
                       << "\t\"" << _attr_map.name(h) << '"';
         }
         if ( _attr_map.is_immutable( h) &&
              toupper(func->intent(i)) != 'I') {
           throw COM_exception(COM_ERR_IMMUTABLE);
         }
       }
     }
     if (offset && func->is_rawdata(0) &&
         (attr = func->dataitem())->data_type()==COM_F90POINTER) {
       COM_assertion_msg( _f90ptr_treat>=0, "No F90 pointer initalized");
       // Append pointer information
       if ( _f90ptr_treat == FPTR_APPEND) {
         std::pair<int,int> offs = get_f90pntoffsets( attr);
         // Add pointer information for Intel Compiler
         *plen = *(void**)((char*)const_cast<void*>(attr->pointer())+offs.second);
         ++lcount; ++plen;
       }
     }
     for ( int i=count, iend=func->num_of_args(); i<iend; ++i) {
       if ( !func->is_optional( i)) throw COM_exception(COM_ERR_TOO_FEW_ARGS);
       ps[i] = NULL;
       if ( verb>1) {
         std::cerr << std::endl << "OPT\t" << func->intent(i) << ": ";
         std::cerr << ps[i];
       }
     }
     if ( verb) {
       if ( verb>1) std::cerr << std::endl << ')';
       std::cerr << std::endl;
     }
     // Profiling it
     double t = 0;
     if ( _profile_on) {
 //RAF    MPI_Comm comm = func->communicator();
 //RAF    if (comm!=MPI_COMM_NULL) MPI_Barrier( comm);
       t = get_wtime();
 #ifdef _CHARM_THREADED_
 //RAF      if (comm!=MPI_COMM_NULL) MPI_Barrier( comm);
 #endif
     }
     ++_depth;
     if ( verb>1 && lcount>0) {
       std::cerr << "Invoking function with " << lcount
                 << " additional implicit arguments: " << std::endl;
       for ( int i=0; i<lcount; ++i) {
         long int p=(long int)ps[func->num_of_args()+i];
         if ( p<0 || p>MAX_NAMELEN)
           std::cerr << "\t@" << (void *)p << std::endl;
         else
           std::cerr << '\t' << (long int)p << std::endl;
       }
     }
     // Invoke the function
     (*func)( func->num_of_args()+lcount, ps);
     --_depth;
     if ( _profile_on) {
 //RAF      MPI_Comm comm = func->communicator();
 //RAF      if (comm!=MPI_COMM_NULL) MPI_Barrier( comm);
       double tnew = get_wtime();
 #ifdef _CHARM_THREADED_
 //RAF      if (comm!=MPI_COMM_NULL) MPI_Barrier( comm);
 #endif
       _func_map.counts[wf]++;
       double sec = tnew-t;
       _func_map.wtimes_tree[wf] += sec;
       _func_map.wtimes_self[wf] += sec;
       if ( int(_timer.size()) > _depth)
         _func_map.wtimes_self[wf] -= _timer[_depth];
       _timer.resize( _depth,0);
       if (_depth>0)  _timer[_depth-1] += sec;
       if (_depth==0) _func_map.wtimes_tree[0] += sec;
     }
     if ( verb) {
       std::cerr << "COM: DONE(" << _depth << ") " << std::endl;
     }
     // Copy back strings
     if ( needpostproc) {
       for ( int i=offset; i<count; ++i) {
         COM_Type type = func->data_type(i);
         char intent = func->intent(i);
         if ( func->is_literal(i) && type == COM_STRING) {
           if (intent=='b' || intent=='B') {
             int n = strs[i].size();
             if ( n>0) std::memcpy( args[i], &strs[i][0], n-1);
           }
         }
         else if ( type == COM_MPI_COMMC && !from_c) {
           if (intent=='o' || intent=='O' || intent=='b' || intent=='B')
             *(int*)args[i] = COMMPI_Comm_c2f( *(MPI_Comm*)ps[i]);
         }
         else if ( type == COM_MPI_COMMF && from_c) {
           if (intent=='o' || intent=='O' || intent=='b' || intent=='B')
             *(MPI_Comm*)args[i] = COMMPI_Comm_f2c( *(int*)ps[i], MPI_Comm());
         }
       }
     }
     _errorcode = 0;
   }
   catch ( COM_exception ex) {
     ex.msg = append_frame( ex.msg, COM_base::call_function);
     char buf[10];
     std::sprintf( buf, "%d", wf);
     std::string msg = std::string( "When processing function ");
     if ( wf>0) msg.append( _func_map.name(wf));
     msg.append( " with handle "); msg.append( buf);
     proc_exception( ex, msg);
   }
 }
int COM_base::check_bounds (const std::string & wa, int pane_id) throw (int)
Definition at line 1101 of file COM_base.C.
Referenced by COM_check_bounds(), and COM_F_FUNC2().
 { return 0; }
void COM_base::clone_dataitem (const std::string & wname, const std::string & pwname, int withghost = 1, const char * cndname = NULL, int val = 0) throw (int)
Definition at line 794 of file COM_base.C.
References append_frame, COM_ERR_DATAITEM_NOTEXIST, DataItem::empty(), Pane::INHERIT_CLONE, COM_exception::msg, and s.
Referenced by COM_clone_dataitem().
 {
   try {
     if ( _verb1>1) {
       std::cerr << "COM: Cloning dataitem \"" << pwaname
                 << "\" onto \"" << waname << '"' << std::endl;
     }
     std::string pawname, paaname;
     split_name( pwaname, pawname, paaname);
     std::string awname, aaname;
     std::string::size_type ni = waname.find(".");
     if ( ni == std::string::npos) {
       awname = waname; aaname = "";
     }
     else
       split_name( waname, awname, aaname);
     std::string cawname, caaname;
     if ( cndname && *cndname!=0)
       split_name( cndname, cawname, caaname);
     DataItem *cnd=caaname.empty()?NULL:get_window(cawname).dataitem(caaname);
     if ( !caaname.empty() && cnd==NULL)
       throw COM_exception( COM_ERR_DATAITEM_NOTEXIST, cndname);
     get_window(awname).inherit( get_window( pawname).dataitem(paaname),
                                 aaname, Pane::INHERIT_CLONE, withghost, cnd, val);
     _errorcode = 0;
   }
   catch ( COM_exception ex) {
     ex.msg = append_frame( ex.msg, COM_base::clone_dataitem);
     std::string s;
     s = s + "When window " + waname + " clones dataitem " + pwaname;
     proc_exception( ex, s);
   }
 }
void COM_base::copy_array (const std::string & wa, const int pane_id, void * val, int v_strd = 0, int v_size = 0, int offset = 0) throw (int)
Definition at line 1064 of file COM_base.C.
References append_frame, COM_exception::msg, and s.
Referenced by COM_copy_array(), and com_obtain_array_helper().
 {
   try {
     if ( _verb1>1) {
       std::cerr << "COM: Copy array for dataitem \""
                 << wa << '"' << " on pane " << pid << std::endl;
     }
     // Invoke Window::get_size
     std::string wname, aname;
     split_name( wa, wname, aname);
     get_window( wname).copy_array( aname, pid, val, v_strd, v_size, offset);
     if ( _verb1>1) {
       std::cerr << "COM: ";
       std::cerr << " stride is " << v_strd;
       std::cerr << " size is " << v_size;
       std::cerr << std::endl;
     }
     _errorcode = 0;
   }
   catch ( COM_exception ex) {
     ex.msg = append_frame( ex.msg, COM_base::copy_array);
     std::string s;
     s = s + "When processing dataitem " + wa;
     proc_exception( ex, s);
   }
 }
void COM::COM_base::copy_dataitem (const std::string & wname, const std::string & pwname, int withghost = 1, const char * cndname = NULL, int val = 0) throw (int)
Referenced by COM_copy_dataitem(), and COM_F_FUNC2().
void COM::COM_base::copy_dataitem (int trg_hdl, int src_hdl, int withghost = 1, int ptn_hdl = 0, int val = 0) throw (int)
void COM_base::deallocate_array (const std::string & wa, const int pid = 0) throw (int)
Definition at line 906 of file COM_base.C.
References append_frame, COM_exception::msg, and s.
Referenced by COM_deallocate_array(), and COM_F_FUNC2().
 {
   try {
     if ( _verb1>1)
       std::cerr << "COM: Deallocate array for \"" << wa << "\" on pane "
                 << pid << " to" << std::endl;
     std::string wname, aname;
     split_name( wa, wname, aname);
     get_window( wname).dealloc_array( aname, pid);
     _errorcode = 0;
   }
   catch ( COM_exception ex) {
     ex.msg = append_frame( ex.msg, COM_base::deallocate_array);
     std::string s;
     s = s + "When processing dataitem " + wa;
     proc_exception( ex, s);
   }
 }
void COM_base::delete_dataitem (const std::string & wa) throw (int)
Definition at line 520 of file COM_base.C.
References append_frame, COM_exception::msg, and s.
Referenced by COM_delete_dataitem(), and COM_F_FUNC2().
 {
   try {
     if ( _verb1>1)
       std::cerr << "COM: delete dataitem \"" << wa << std::endl;
     // Invoke Window::new_dataitem.
     std::string wname, aname;
     split_name( wa, wname, aname);
     get_window( wname).delete_dataitem( aname);
     _errorcode = 0;
   }
   catch ( COM_exception ex) {
     ex.msg = append_frame( ex.msg, COM_base::delete_dataitem);
     std::string s;
     s = s + "When processing dataitem " + wa;
     proc_exception( ex, s);
   }
 }
void COM_base::delete_pane (const std::string & wname, const int pid) throw (int)
Definition at line 431 of file COM_base.C.
References append_frame, and COM_exception::msg.
Referenced by COM_delete_pane(), and COM_F_FUNC2().
 {
   try {
     if ( _verb1>1)
       std::cerr << "COM: Delete pane " << pane_id << " of window "
                 << std::endl;
     get_window( wname).delete_pane( pane_id);
     _errorcode = 0;
   }
   catch ( COM_exception ex) {
     ex.msg = append_frame( ex.msg, COM_base::delete_pane);
     char buf[10];
     std::sprintf( buf, "%d", pane_id);
     std::string msg = std::string( "When processing window ")
       + wname + " for pane " + buf;
     proc_exception( ex, msg);
   }
 }
void COM_base::delete_window (const std::string & wname) throw (int)
Definition at line 413 of file COM_base.C.
References append_frame, COM_ERR_WINDOW_NOTEXIST, COM_exception::ierr, COM_exception::msg, and s.
Referenced by COM_delete_window(), and COM_F_FUNC2().
 {
   try {
     if ( _verb1>1)
       std::cerr << "COM: Deleting window \"" << name << '"' << std::endl;
     _window_map.remove_object( name);
     _errorcode = 0;
   }
   catch ( COM_exception ex) {
     ex.ierr = COM_ERR_WINDOW_NOTEXIST;
     ex.msg = append_frame( ex.msg, COM_base::delete_window);
     std::string s;
     s = s + "When processing window " + name;
     proc_exception( ex, s);
   }
 }
int COM::COM_base::f90ptr_treat () const inline
Definition at line 380 of file COM_base.hpp.
References _f90ptr_treat.
 { return _f90ptr_treat; }
void COM_base::finalize () throw (int) static
Definition at line 156 of file COM_base.C.
References COM_ERR_WASNOT_INITIALIZED.
Referenced by COM_finalize().
{
   COM::COM_base *ptr = get_com();
   if ( !ptr) throw( COM_ERR_WASNOT_INITIALIZED);
   delete ptr;
   set_com( NULL);
 }
void COM_base::free_buffer (int ** buf)
Definition at line 1438 of file COM_base.C.
Referenced by COM_F_FUNC2(), and COM_free_buffer().
 { if ( buf) delete [] *buf; *buf = NULL; }
void COM_base::free_buffer (char ** buf)
Definition at line 1435 of file COM_base.C.
 { if ( buf) delete [] *buf; *buf = NULL; }
void COM::COM_base::get_array (const std::string & wa, const int pane_id, void ** addr, int * strd = NULL, int * cap = 0, bool is_const = false) throw (int)
Referenced by com_obtain_array_helper().
void COM::COM_base::get_array (const std::string & wa, const int pane_id, Pointer_descriptor & addr, int * strd = NULL, int * cap = 0, bool is_const = false) throw (int)
void COM_base::get_bounds (const std::string & wa, const int pane_id, void * lbnd, void * ubnd) throw (int)
Definition at line 1097 of file COM_base.C.
Referenced by COM_get_bounds().
 {}
COM_base * COM_base::get_com () inline static
Definition at line 469 of file COM_base.hpp.
References com_base.
Referenced by COM_get_com(), get_default_communicator(), initialized(), and set_default_communicator().
 { return com_base; }
MPI_Comm COM_base::get_communicator (const std::string & wname) throw (int)
Definition at line 1212 of file COM_base.C.
References append_frame, COMMPI_Initialized(), ComponentInterface::get_communicator(), COM_exception::msg, and s.
Referenced by COM_get_communicator().
{
   try {
     if ( _verb1>1)
       std::cerr << "COM: get the communicator of window \""
                 << wname << std::endl;
     if ( COMMPI_Initialized()) {
       Window &w = get_window(wname);
       _errorcode = 0;
       return w.get_communicator();
     }
     else
       return MPI_COMM_NULL;
   }
   catch ( COM_exception ex) {
     ex.msg = append_frame( ex.msg, COM_base::get_window_npanes);
     std::string s;
     s = s + "When processing window " + wname;
     proc_exception( ex, s);
   }
   return 0;
 }
void COM_base::get_connectivities (const std::string & wname, int pane_id, int * nc, std::string & str, char ** names = NULL) throw (int)
Definition at line 1361 of file COM_base.C.
References append_frame, COM_exception::msg, and s.
Referenced by COM_F_FUNC2(), and COM_get_connectivities().
 {
   try {
     if ( _verb1>1)
       std::cerr << "COM: get connectivities of window \"" << wname
                 << "\" on pane " << pane_id << std::endl;
     std::vector<Connectivity*> as;
     get_window(wname).pane( pane_id).connectivities( as);
     if ( natts) *natts = as.size();
     str.clear();
     int i=0, n=as.size();
     if (n) for (;;) {
       str = str + as[i]->name();
       if ( ++i<n) str.append(" ");
       else break;
     }
     if ( names) {
       *names = new char[str.size()+1];
       std::copy( str.begin(), str.end(), *names);
       (*names)[str.size()]=0;
     }
     if ( _verb1>1)
       std::cerr << "COM: Got connectivity names: " << str << std::endl;
     _errorcode = 0;
   }
   catch ( COM_exception ex) {
     ex.msg = append_frame( ex.msg, COM_base::get_connectivities);
     std::string s;
     s = s + "When processing window " + wname;
     proc_exception( ex, s);
   }
 }
void COM::COM_base::get_dataitem (const std::string & wa_str, char * loc, int * type, int * size, std::string * unit) throw (int)
The opposite of new_dataitem.
Referenced by COM_F_FUNC2(), and COM_get_dataitem().
DataItem& COM::COM_base::get_dataitem (const int) throw (COM_exception) protected
const DataItem& COM::COM_base::get_dataitem (const int) const throw (COM_exception) protected
int COM_base::get_dataitem_handle (const std::string & waname) throw (int)
Definition at line 1511 of file COM_base.C.
References append_frame, and COM_exception::msg.
Referenced by COM_F_FUNC2(), and COM_get_dataitem_handle().
{
   int n(-1);
   try {
     if ( _verb1>1)
       std::cerr << "COM: get handle of dataitem \"" << waname << "\": ";
     std::string wname, aname;
     split_name( waname, wname, aname);
     DataItem *a = get_window( wname).dataitem( aname);
     if ( a!=NULL) n=_attr_map.add_object( waname, a, false);
     if ( _verb1>1) {
       if ( n>0) std::cerr << n << std::endl;
       else std::cerr << " not found" << std::endl;
     }
   }
   catch ( COM_exception ex) {
     ex.msg = append_frame( ex.msg, COM_base::get_dataitem_handle);
     proc_exception( ex, "");
   }
   return n;
 }
int COM_base::get_dataitem_handle_const (const std::string & waname) throw (int)
Definition at line 1484 of file COM_base.C.
References append_frame, and COM_exception::msg.
Referenced by COM_F_FUNC2(), and COM_get_dataitem_handle_const().
{
   int n(-1);
   try {
     if ( _verb1>1)
       std::cerr << "COM: get const handle of dataitem \""
                 << waname << "\": ";
     std::string wname, aname;
     split_name( waname, wname, aname);
     DataItem *a = get_window( wname).dataitem( aname);
     if ( a!=NULL) n=_attr_map.add_object( waname, a, true);
     if ( _verb1>1) {
       if ( n>0) std::cerr << n << std::endl;
       else std::cerr << " not found" << std::endl;
     }
   }
   catch ( COM_exception ex) {
     ex.msg = append_frame( ex.msg, COM_base::get_dataitem_handle_const);
     proc_exception( ex, "");
   }
   return n;
 }
void COM_base::get_dataitems (const std::string & wname, int * na, std::string & str, char ** names = NULL) throw (int)
Definition at line 1320 of file COM_base.C.
References append_frame, COM_exception::msg, and s.
Referenced by COM_F_FUNC2(), and COM_get_dataitems().
 {
   try {
     if ( _verb1>1)
       std::cerr << "COM: get dataitems of window \""
                 << wname << '"' << std::endl;
     std::vector<DataItem*> as;
     get_window(wname).dataitems( as);
     str.clear();
     if ( natts) *natts = as.size();
     int i=0, n=as.size();
     if (n) for (;;) {
       str = str + as[i]->name();
       if ( ++i<n) str.append(" ");
       else break;
     }
     if ( names) {
       *names = new char[str.size()+1];
       std::copy( str.begin(), str.end(), *names);
       (*names)[str.size()]=0;
     }
     if ( _verb1>1)
       std::cerr << "COM: Got dataitem names: " << str << std::endl;
     _errorcode = 0;
   }
   catch ( COM_exception ex) {
     ex.msg = append_frame( ex.msg, COM_base::get_dataitems);
     std::string s;
     s = s + "When processing window " + wname;
     proc_exception( ex, s);
   }
 }
static MPI_Comm COM::COM_base::get_default_communicator () inline static
Definition at line 48 of file COM_base.hpp.
References _comm, and get_com().
Referenced by COM_get_default_communicator().
   { return get_com()->_comm; }
int COM::COM_base::get_error_code () const inline
Definition at line 374 of file COM_base.hpp.
References _errorcode.
Referenced by COM_F_FUNC2(), and COM_get_error_code().
 { return _errorcode; }
std::pair< int, int > COM_base::get_f90pntoffsets (const DataItem * a) protected
Definition at line 1106 of file COM_base.C.
References COM_assertion_msg, COM_F90POINTER, DataItem::get_sizeof(), and DataItem::size_of_components().
{
   int n = DataItem::get_sizeof( COM_F90POINTER, a->size_of_components());
   COM_assertion_msg( _f90ptr_treat>=0, "No F90 pointer initalized");
   if ( _f90ptr_treat == FPTR_INSERT)
     return std::pair<int,int>(n/2-sizeof(void*), n-sizeof(void*));
   else
     return std::pair<int,int>(0,n-sizeof(void*));
 }
void COM_base::get_f90pointer (const std::string & waname, void * ptr, Func_ptr f, long int l) throw (int)
Definition at line 1173 of file COM_base.C.
References append_frame, COM_assertion_msg, COM_ERR_NOT_A_POINTER, COM_ERR_NOT_A_WINDOW_DATAITEM, COM_F90POINTER, DataItem::data_type(), IMPACT::ExampleProgram::f(), DataItem::location(), COM_exception::msg, and DataItem::pointer().
Referenced by COM_F_FUNC2().
{
   try {
     if ( _verb1>1)
       std::cerr << "COM: get pointer \"" << waname
                 << " into " << ptr << std::endl;
     std::string wname, aname;
     split_name( waname, wname, aname);
     DataItem *a = get_window( wname).dataitem( aname);
     if ( a->location() != 'w')
       throw COM_exception( COM_ERR_NOT_A_WINDOW_DATAITEM,
                            append_frame(waname, COM_base::get_f90pointer));
     if ( a->data_type() == COM_F90POINTER) {
       std::pair<int,int> offs = get_f90pntoffsets( a);
       COM_assertion_msg( _f90ptr_treat>=0, "No F90 pointer initalized");
       if ( _f90ptr_treat == FPTR_INSERT || _f90ptr_treat == FPTR_APPEND) {
         typedef void(*Func2)(void*,void*, long int, long int);
         (*(Func2)f)( (char*)a->pointer()+offs.first, ptr,
                      *(long int*)((char*)a->pointer()+offs.second), len);
       }
       else {
         typedef void(*Func2)(void*,void*);
         (*(Func2)f)( a->pointer(), (char*)ptr+offs.first);
       }
     }
     else
       throw COM_exception( COM_ERR_NOT_A_POINTER,
                            append_frame(waname, COM_base::get_f90pointer));
   }
   catch ( COM_exception ex) {
     ex.msg = append_frame( ex.msg, COM_base::get_f90pointer);
     proc_exception( ex, "");
   }
 }
Function& COM::COM_base::get_function (const int) throw (COM_exception) protected
const Function& COM::COM_base::get_function (const int) const throw (COM_exception) protected
int COM_base::get_function_handle (const std::string & wfname) throw (int)
Definition at line 1536 of file COM_base.C.
References append_frame, IMPACT::ExampleProgram::f(), and COM_exception::msg.
Referenced by COM_F_FUNC2(), and COM_get_function_handle().
{
   int n(-1);
   try {
     if ( _verb1>1)
       std::cerr << "COM: get handle of function \"" << wfname << "\": ";
     std::string wname, fname;
     split_name( wfname, wname, fname);
     Function *f = get_window( wname).function( fname);
     if ( f!=NULL) n=_func_map.add_object( wfname, f);
     if ( _verb1>1) {
       if ( n>0) std::cerr << n << std::endl;
       else std::cerr << " not found" << std::endl;
     }
   }
   catch ( COM_exception ex) {
     ex.msg = append_frame( ex.msg, COM_base::get_function_handle);
     proc_exception( ex, "");
   }
   return n;
 }
void COM_base::get_modules (std::vector< std::string > & names) throw (int)
Definition at line 1293 of file COM_base.C.
References append_frame, COM_exception::msg, and s.
Referenced by COM_get_modules().
{
   try {
     if ( _verb1>1) {
       std::cerr << "COM: get modules";
       //      if ( rank==-2) std::cerr << " this process";
       //      else if ( rank==-1) std::cerr << " all processes";
       //      else std::cerr << " process " << rank;
       std::cerr << std::endl;
     }
     names = _module_map.get_names();
     //    get_window(wname).panes( paneids_vec, rank);
     //    if ( pane_ids) {
     //      *pane_ids = new int[paneids_vec.size()];
     //      std::copy( paneids_vec.begin(), paneids_vec.end(), *pane_ids);
     //    }
     _errorcode = 0;
   }
   catch ( COM_exception ex) {
     ex.msg = append_frame( ex.msg, COM_base::get_modules);
     std::string s;
     s = s + "When processing get_modules.";
     proc_exception( ex, s);
   }
 }
int COM_base::get_num_arguments (const std::string & wf) throw (COM_exception)
Definition at line 1686 of file COM_base.C.
References append_frame, COM_ERR_FUNCTION_NOTEXIST, and Function::num_of_args().
{
   std::string wname, fname;
   split_name(wf, wname, fname);
   Function *func = get_window( wname).function( fname);
   if ( func==NULL)
     throw COM_exception( COM_ERR_FUNCTION_NOTEXIST,
                          append_frame(wf, COM_base::set_member_function));
   return func->num_of_args();
 }
int COM_base::get_num_arguments (const int wf) throw (COM_exception)
Definition at line 1698 of file COM_base.C.
References Function::num_of_args().
{
   Function *func = &get_function( wf);
   return func->num_of_args();
 }
void COM_base::get_object (const std::string & wa, const int pane_id, void ** ptr) throw (int)
Definition at line 620 of file COM_base.C.
Referenced by COM_get_object().
 {
   int strd;
   get_array( wa, pid, ptr, &strd);
   if ( strd <= 1) return; else *(char**)ptr -= strd;
 }
void COM_base::get_panes (const std::string & wname, std::vector< int > & paneids_vec, int rank = -2, int ** pane_ids = NULL) throw (int)
If rank is -2, then the current process is assumed. If rank is -1, then get the panes on all processes within the window's communicator.
Definition at line 1235 of file COM_base.C.
References append_frame, COM_exception::msg, and s.
Referenced by COM_F_FUNC2(), and COM_get_panes().
{
   try {
     if ( _verb1>1) {
       std::cerr << "COM: get pane ids of window \""
                 << wname << "\" on ";
       if ( rank==-2) std::cerr << " this process";
       else if ( rank==-1) std::cerr << " all processes";
       else std::cerr << " process " << rank;
       std::cerr << std::endl;
     }
     get_window(wname).panes( paneids_vec, rank);
     if ( pane_ids) {
       *pane_ids = new int[paneids_vec.size()];
       std::copy( paneids_vec.begin(), paneids_vec.end(), *pane_ids);
     }
     _errorcode = 0;
   }
   catch ( COM_exception ex) {
     ex.msg = append_frame( ex.msg, COM_base::get_panes);
     std::string s;
     s = s + "When processing window " + wname;
     proc_exception( ex, s);
   }
 }
void COM_base::get_parent (const std::string & waname, int pane_id, std::string & str, char ** name = NULL) throw (int)
If the dataitem has no parent, then set name to empty.
Definition at line 1402 of file COM_base.C.
References append_frame, COM_exception::msg, and s.
Referenced by COM_F_FUNC2(), and COM_get_parent().
 {
   try {
     if ( _verb1>1)
       std::cerr << "COM: get parent of dataitem \"" << waname
                 << "\" on pane " << pane_id << std::endl;
     std::string wname, aname;
     split_name( waname, wname, aname);
     get_window( wname).get_parent( aname, pane_id, str);
     if ( name) {
       *name = new char[str.size()+1];
       std::copy( str.begin(), str.end(), *name);
       (*name)[str.size()]=0;
     }
     if ( _verb1>1)
       std::cerr << "COM: Got parent name: " << str << std::endl;
     _errorcode = 0;
   }
   catch ( COM_exception ex) {
     ex.msg = append_frame( ex.msg, COM_base::get_parent);
     std::string s;
     s = s + "When processing dataitem " + waname;
     proc_exception( ex, s);
   }
 }
void COM_base::get_size (const std::string & wa_str, int pane_id, int * size, int * ng = 0) throw (int)
Definition at line 959 of file COM_base.C.
References append_frame, COM_exception::msg, and s.
Referenced by COM_F_FUNC2(), and COM_get_size().
 {
   try {
     if ( _verb1>1) {
       std::cerr << "COM: Get size for dataitem \""
                 << wa << '"' << " for pane " << pid << std::endl;
     }
     // Invoke Window::get_size
     std::string wname, aname;
     split_name( wa, wname, aname);
     get_window( wname).get_size( aname, pid, nitems, ng);
     _errorcode = 0;
   }
   catch ( COM_exception ex) {
     ex.msg = append_frame( ex.msg, COM_base::get_size);
     std::string s;
     s = s + "When processing dataitem " + wa;
     proc_exception( ex, s);
   }
 }
int COM_base::get_sizeof (COM_Type type, int count = 1) static
See Also
DDT
Definition at line 2130 of file COM_base.C.
References DataItem::get_sizeof().
Referenced by COM_F_FUNC2().
 { return DataItem::get_sizeof( type, count); }
int COM_base::get_status (const std::string & wa_str, int pane_id) throw (int)
If the dataitem name is empty, and pane ID is 0, then checks whether the window exist (return 0 if does and -1 if not); if dataitem name is empty and pane ID is >0, then check whether check whether the given pane exists (return 0 if so and -1 if not). Otherwise, it checks the status of an dataitem and returns one of the following values: -1: not exist. 0: not yet initialized 1: set by the user. 2: set by the user with const modifier. 3: inherited from (i.e., use) another dataitem. 4: allocated by COM.
Definition at line 1026 of file COM_base.C.
References append_frame, ComponentInterface::get_status(), COM_exception::msg, and s.
Referenced by COM_F_FUNC2(), and COM_get_status().
 {
   try {
     if ( _verb1>1) {
       std::cerr << "COM: Get status for dataitem \""
                 << wa << '"' << " on pane " << pid << std::endl;
     }
     std::string wname, aname;
     split_name( wa, wname, aname, false);
     Window **w = _window_map.find( wname).second;
     if ( aname.empty() && pid == 0) {
       if ( w == NULL) return -1;
       else return 0;
     }
     int status = (**w).get_status( aname, pid);
     if ( _verb1>1) {
       std::cerr << "COM: ";
       std::cerr << " status is " << status << std::endl;
     }
     _errorcode = 0;
     return status;
   }
   catch ( COM_exception ex) {
     ex.msg = append_frame( ex.msg, COM_base::get_status);
     std::string s;
     s = s + "When processing dataitem " + wa;
     proc_exception( ex, s);
   }
   return 0;
 }
int COM::COM_base::get_verbose () const inline
Definition at line 351 of file COM_base.hpp.
Referenced by COM_F_FUNC2().
 { return _verbose; }
Window & COM_base::get_window (const std::string & wname) throw (COM_exception) protected
Definition at line 2134 of file COM_base.C.
References append_frame, and COM_ERR_WINDOW_NOTEXIST.
Referenced by get_window().
 {
   Window **w = _window_map.find( wname).second;
   if ( w ==NULL)
     throw COM_exception( COM_ERR_WINDOW_NOTEXIST,
                          append_frame(wname, COM_base::get_window));
   return **w;
 }
const Window& COM::COM_base::get_window (const std::string & wname) const throw (COM_exception) inline protected
Definition at line 401 of file COM_base.hpp.
References get_window().
   { return const_cast<COM_base*>(this)->get_window(wname); }
int COM_base::get_window_handle (const std::string & wname) throw (int)
Definition at line 1442 of file COM_base.C.
References append_frame, COM_assertion, and COM_exception::msg.
Referenced by COM_F_FUNC2(), COM_get_window_handle(), get_window_object(), and RFC_Pane_base::read_rocin().
{
   int n(-1);
   try {
     if ( _verb1>1)
       std::cerr << "COM: get handle of window \"" << wname << "\": ";
     std::pair<int,Window**> obj = _window_map.find( wname);
     COM_assertion(obj.first<0 || (*obj.second)->name()==wname);
     if ( obj.first>=0)
       n = obj.first+1;
     if ( _verb1>1) {
       if ( n>0) std::cerr << n << std::endl;
       else std::cerr << " not found" << std::endl;
     }
   }
   catch ( COM_exception ex) {
     ex.msg = append_frame( ex.msg, COM_base::get_window_handle);
     proc_exception( ex, "");
   }
   return n;
 }
Window * COM_base::get_window_object (int hdl) throw (int)
Definition at line 1466 of file COM_base.C.
References append_frame, and COM_ERR_INVALID_WINDOW_HANDLE.
Referenced by get_window_object(), Rocin::read_parameter_file(), RFC_Pane_base::read_rocin(), COM::ParallelTestingObject< CommType, ResultsType >::Test__WindowGetSetCommunicator(), and Rocout::write_parameter_file().
 {
   if ( hdl <= 0)
     throw COM_exception( COM_ERR_INVALID_WINDOW_HANDLE,
                          append_frame("", COM_base::get_window));
   return _window_map[hdl-1];
 }
const Window* COM::COM_base::get_window_object (int hdl) const throw (int)
Window* COM::COM_base::get_window_object (const std::string & wname) throw (int) inline
Definition at line 274 of file COM_base.hpp.
References get_window_handle(), and get_window_object().
   { return get_window_object( get_window_handle( wname)); }
const Window* COM::COM_base::get_window_object (const std::string & wname) const throw (int) inline
Definition at line 276 of file COM_base.hpp.
References get_window_handle(), and get_window_object().
   { return get_window_object( const_cast<COM_base*>(this)->
                               get_window_handle( wname)); }
void COM_base::get_windows (std::vector< std::string > & names) throw (int)
Definition at line 1265 of file COM_base.C.
References append_frame, COM_exception::msg, and s.
Referenced by COM_get_windows().
{
   try {
     if ( _verb1>1) {
       std::cerr << "COM: get windows";
       //      if ( rank==-2) std::cerr << " this process";
       //      else if ( rank==-1) std::cerr << " all processes";
       //      else std::cerr << " process " << rank;
       std::cerr << std::endl;
     }
     names = _window_map.get_names();
     //    get_window(wname).panes( paneids_vec, rank);
     //    if ( pane_ids) {
     //      *pane_ids = new int[paneids_vec.size()];
     //      std::copy( paneids_vec.begin(), paneids_vec.end(), *pane_ids);
     //    }
     _errorcode = 0;
   }
   catch ( COM_exception ex) {
     ex.msg = append_frame( ex.msg, COM_base::get_windows);
     std::string s;
     s = s + "When processing get_windows.";
     proc_exception( ex, s);
   }
 }
void COM::COM_base::icall_function (int wf, int count, void * args[], int * reqid, const int * lens = NULL) throw (int) inline
Parameters
wf the handle to the function.
count the number of input arguments.
args the addresses to the arguments.
reqid is set to the request of the current call.
lens the lengths of character strings.
Definition at line 337 of file COM_base.hpp.
References call_function().
Referenced by COM_F_FUNC2(), and COM_icall_function().
   { *reqid = 0; call_function( wf, count, args, lens); }
void COM_base::init (int * argc, char *** argv) throw (int) static
Definition at line 145 of file COM_base.C.
References COM_ERR_WAS_INITIALIZED, and printStackBacktrace().
Referenced by COM_init().
{
   extern void printStackBacktrace();
   COM::COM_base *ptr = get_com();
   if ( ptr) throw( COM_ERR_WAS_INITIALIZED);
   ptr = new COM::COM_base( argc, argv);
   set_com( ptr);
 }
static bool COM::COM_base::initialized () inline static
Definition at line 55 of file COM_base.hpp.
References get_com().
Referenced by COM_initialized().
 { return get_com()!=NULL; }
void COM_base::load_module (const std::string & lname, const std::string & wname) throw (int)
Definition at line 170 of file COM_base.C.
References COM_ERR_COULD_FINDSYM, and COM_ERR_COULD_OPENLIB.
Referenced by COM_F_FUNC2(), and COM_load_module().
 {
 #ifndef STATIC_LINK
   if ( _verb1>1)
     std::cerr << "Loading module " << lname
               << " with arguments " << wname << "..." << std::endl;
   void *handle;
   std::string lname_found;
   // Obtain a reference to the library.
   int index = _module_map.find(lname).first;
   if ( index<0) { // Load the library
 #ifndef DARWIN
     std::string lname_short = std::string("lib") + lname + ".so";
 #else
     std::string lname_short = std::string("lib") + lname + ".dylib";
 #endif
     std::string lname_full = _libdir + lname_short;
     // Open the library
     handle = dlopen( lname_full.c_str(), RTLD_NOW);
     if (handle == NULL)
       printf("dlopen error: %s\n", dlerror());
     if ( handle == NULL && !_libdir.empty()) {
       handle = dlopen( lname_short.c_str(), RTLD_NOW);
       if (handle == NULL)
         printf("dlopen error: %s\n", dlerror());
       lname_found = lname_short;
     }
     else
       lname_found = lname_full;
     if ( handle == NULL) {
       std::string libs;
       if ( _libdir.empty()) libs = lname_full;
       else libs = lname_full+" or "+lname_short;
       proc_exception( COM_exception(COM_ERR_COULD_OPENLIB, libs),
                       "COM_base::load_module");
     }
     // Insert a new entry into _module_map.
     index = _module_map.add_object( lname, Module_map::value_type());
     _module_map[index].first = handle;
   }
   else
     handle = _module_map[index].first;
   // Insert the handle and the window name into _module_map.
   _module_map[index].second.insert(wname);
   // Look for the symbol
   std::string fname = lname + "_load_module";
   //JK 4/12/16: Turning this off because we want the window to use
   //the default communicator we explicitly set
   // Set the default communicator to MPI_COMM_SELF
   //MPI_Comm comm = MPI_COMM_SELF;
   //std::swap(_comm, comm);
   //JK 4/12/16: End
   void *fptr = dlsym( handle, fname.c_str());
   if ( fptr != NULL) {
     // This is a C/C++ module
     typedef void(*Func1)(const char*);
     (*(Func1)fptr)( wname.c_str());
   }
   else {
     // Try out different name mangling schemes to figure out automatically.
     int ibegin= ( _f90_mangling == -1 ) ? 0 : _f90_mangling;
     int iend = (_f90_mangling == -1) ? 4: _f90_mangling;
       // 0: lowercase
       // 1: uppercase
       // 2: _
       // 3: uppercase _
       // 4: lowercase __
     for ( int i=ibegin; i<=iend; ++i) {
       if ( i & 1 == 1)
         std::transform( fname.begin(), fname.end(), fname.begin(), toupper);
       else
         std::transform( fname.begin(), fname.end(), fname.begin(), tolower);
       if ( i==2 || (i==3&&i==ibegin)) fname.append( "_");
       if (i==4) { fname.append( "_"); if (ibegin == 4) fname.append( "_"); }
       fptr = dlsym( handle, fname.c_str());
       if ( fptr) { _f90_mangling = i; break; }
     }
     if ( fptr != NULL) {
       // This is a Fortran module
       typedef void(*Func2)(const char*,long int);
       (*(Func2)fptr)( wname.c_str(), wname.size());
     }
     else {
       std::string msg;
       if ( ibegin == iend) msg = fname+" in "+lname_found;
       else msg = fname + " or any its lowercase w/o underscore in " + lname;
       msg.append( "\nError message from libdl is: ");
       msg.append( dlerror());
       proc_exception( COM_exception(COM_ERR_COULD_FINDSYM, msg),
                       "COM_base::load_module");
     }
   }
   //JK 4/12/16: Turning this off because it corresponds
   //with what I did above
   // Restore the default communicator.
   //std::swap(_comm, comm);
   //JK 4/12/16: End
   if ( _verb1>1)
     std::cerr << "Module " << lname << " loaded." << std::endl;
 #endif
 }
void COM_base::new_dataitem (const std::string & wa, const char loc, const int data_type, int size, const std::string & unit) throw (int)
Definition at line 488 of file COM_base.C.
References append_frame, COM_exception::msg, print_type(), and s.
Referenced by COM_F_FUNC2(), and COM_new_dataitem().
 {
   try {
     if ( _verb1>1) {
       std::cerr << "COM: new dataitem \"" << wa
                 << "\"\n\tLocation: " << loc << "\n\tType: ";
       print_type( std::cerr, type);
       std::cerr << "\n\tSize: " << size << "\n\tUnit: \"" << unit << "\""
                 << std::endl;
     }
     // Invoke Window::new_dataitem.
     std::string wname, aname;
     split_name( wa, wname, aname);
     get_window( wname).new_dataitem( aname, loc, type, size, unit);
     _errorcode = 0;
   }
   catch ( COM_exception ex) {
     ex.msg = append_frame( ex.msg, COM_base::new_dataitem);
     std::string s;
     s = s + "When processing dataitem " + wa;
     proc_exception( ex, s);
   }
 }
void COM_base::new_window (const std::string & wname, MPI_Comm comm) throw (int)
Definition at line 371 of file COM_base.C.
References append_frame, COM_WARN_DUP_WINDOW, COM_exception::msg, and s.
Referenced by COM_F_FUNC2(), and COM_new_window().
 {
   // If MPI_COMM_NULL is used, then use the default communicator.
   if ( comm == MPI_COMM_NULL) comm = _comm;
   try {
     if ( _verb1>1)
       std::cerr << "COM: Creating window \"" << name << '"'
                 << " with communicator " << comm << std::endl;
     if ( _window_map.find( name).second)
       throw COM_exception( COM_WARN_DUP_WINDOW,
                            append_frame(name, COM_base::new_window));
     _window_map.add_object( name, new Window( name, comm));
     _errorcode = 0;
   }
   catch ( COM_exception ex) {
     ex.msg = append_frame( ex.msg, COM_base::new_window);
     std::string s("When processing "); s.append(name);
     proc_exception( ex, s);
   }
 }
void COM_base::print_profile (const std::string & fname, const std::string & header)
Definition at line 2075 of file COM_base.C.
Referenced by COM_F_FUNC2(), and COM_print_profile().
{
   if ( !_profile_on) return;
   if ( _verb1>1)
      std::cerr << "COM: Appending profile into file \"" << fname
                << '"' << std::endl;
   std::multimap< double, int>  profs;
   typedef std::multimap< double, int>::value_type MMVT;
   for ( int i=1, n=_func_map.wtimes_self.size(); i<n; ++i) {
     if ( _func_map.wtimes_self[i] > 0.0)
       profs.insert( MMVT( -_func_map.wtimes_self[i], i));
   }
   std::FILE *of = NULL;
   if ( fname.size() == 0)
     of = stdout;
   else {
     of = std::fopen( fname.c_str(), "a");
     if ( of == NULL) {
       std::cerr << "COM: Could not open file \"" << fname
                 << "\"\nCOM: Giving up profiling" << std::endl;
       _profile_on = false; return;
     }
   }
   std::fputc('\n', of);
   if ( header.size() == 0)
     std::fputs( "************************COM simple profiling tool\
 ************************", of);
   else
     std::fputs( header.c_str(), of);
   std::fprintf( of, "\n%32s%12s%14s%14s\n", "Function", "#calls",
                 "Time(tree)", "Time(self)");
   std::fputs( "-------------------------------------------------------\
 ---------------------\n", of);
   std::multimap< double, int>::const_iterator i, iend;
   for ( i=profs.begin(), iend=profs.end(); i!=iend; ++i) {
     std::fprintf( of, "%32.32s%12d%14g%14g\n",
                   _func_map.name(i->second).c_str(),
                   _func_map.counts[i->second],
                   _func_map.wtimes_tree[i->second],
                   _func_map.wtimes_self[i->second]);
   }
   std::fputs( "-------------------------------------------------------\
 ---------------------\n", of);
   std::fprintf( of, "%32s%40g\n", "Total(top level calls)",
                 _func_map.wtimes_tree[0]);
   if ( of != stdout) std::fclose( of);
 }
void COM_base::proc_exception (const COM_exception & ex, const std::string & s) throw (int) protected
Definition at line 2227 of file COM_base.C.
References COM_exception::ierr, printStackBacktrace(), and s.
 {
   extern void printStackBacktrace();
   _errorcode = ex.ierr;
   std::cerr << '\n' << ex << s << std::endl;
   if ( _exception_on && _errorcode>=1000) {
     printStackBacktrace();
     throw ex.ierr;
   }
 }
void COM_base::resize_array (const std::string & wa, const int pane_id = 0, void ** addr = NULL, int strd = -1, int cap = 0) throw (int)
Resize for all panes if pane-id is 0, in which case, do not set addr. The difference between resize and allocate is that resize will reallocate memory only if the current array cannot accomodate the requested capacity.
Definition at line 699 of file COM_base.C.
References append_frame, COM_exception::msg, and s.
Referenced by COM_F_FUNC2(), com_obtain_array_helper(), and COM_resize_array().
{
   try {
     if ( _verb1>1) {
       std::cerr << "COM: Resize array for \"" << wa << "\" on pane "
                 << pid << " with stride ";
       if ( strd<0) std::cerr << "==current";
       else if (strd) std::cerr << strd;
       else std::cerr << "==#components";
       std::cerr << " and capacity ";
       if ( cap) std::cerr << cap;
       else std::cerr << "==#items";
       std::cerr << std::endl;
     }
     std::string wname, aname;
     split_name( wa, wname, aname);
     get_window( wname).resize_array( aname, pid, addr, strd, cap);
     _errorcode = 0;
   }
   catch ( COM_exception ex) {
     ex.msg = append_frame( ex.msg, COM_base::resize_array);
     std::string s;
     s = s + "When processing dataitem " + wa;
     proc_exception( ex, s);
   }
 }
void COM_base::set_array (const std::string & wa, const int pane_id, void * addr, int strd = 0, int cap = 0, bool is_const = false) throw (int)
Definition at line 630 of file COM_base.C.
References append_frame, COM_exception::msg, and s.
Referenced by COM_F_FUNC2(), COM_set_array(), COM_set_array_const(), com_set_array_const_helper(), and com_set_array_helper().
 {
   try {
     if ( _verb1>1) {
       std::cerr << "COM: Set array for \"" << wa << "\" on pane "
                 << pid << " to " << addr << " with stride ";
       if ( strd) std::cerr << strd;
       else std::cerr << "==#components";
       std::cerr << " and capacity ";
       if ( cap) std::cerr << cap;
       else std::cerr << "==#items";
       std::cerr << std::endl;
     }
     std::string wname, aname;
     split_name( wa, wname, aname);
     get_window( wname).set_array( aname, pid, addr, strd, cap, is_const);
     _errorcode = 0;
   }
   catch ( COM_exception ex) {
     ex.msg = append_frame( ex.msg, COM_base::set_array);
     std::string s;
     s = s + "When processing dataitem " + wa;
     proc_exception( ex, s);
   }
 }
template<class T > void COM::COM_base::set_bounds (const std::string & wa, const int pane_id, T lbnd, T ubnd) throw (int) inline
Definition at line 119 of file COM_base.hpp.
Referenced by COM_set_bounds(), and set_bounds().
   { set_bounds( wa, pane_id, (const void*)&lbnd, (const void*)&ubnd); }
template<class T > void COM::COM_base::set_bounds (const std::string & wa, const int pane_id, const T * lbnd, const T * ubnd) throw (int) inline
Definition at line 124 of file COM_base.hpp.
References set_bounds().
   { set_bounds( wa, pane_id, (const void*)&lbnd, (const void*)&ubnd); }
void COM_base::set_bounds (const std::string & wa, const int pane_id, const void * lbnd, const void * ubnd) throw (int)
Definition at line 663 of file COM_base.C.
 {}
void COM_base::set_com (COM_base * r) static
It was introduced to support processes.
Definition at line 37 of file COM_base.C.
Referenced by COM_set_com().
 { com_base = r; }
static void COM::COM_base::set_default_communicator (MPI_Comm comm) inline static
This communicator will be used as the default communicator for any new window.
Definition at line 44 of file COM_base.hpp.
References _comm, and get_com().
Referenced by COM_set_default_communicator().
   { get_com()->_comm = comm; }
void COM_base::set_f90pointer (const std::string & waname, void * ptr, Func_ptr f, long int l) throw (int)
Definition at line 1118 of file COM_base.C.
References append_frame, COM_assertion_msg, COM_ERR_NOT_A_POINTER, COM_ERR_NOT_A_WINDOW_DATAITEM, COM_F90POINTER, DataItem::data_type(), IMPACT::ExampleProgram::f(), get_sizeof(), DataItem::location(), COM_exception::msg, DataItem::pointer(), and DataItem::size_of_components().
Referenced by COM_F_FUNC2().
{
   try {
     if ( _verb1>1)
       std::cerr << "COM: set pointer \"" << waname
                 << " to " << ptr << std::endl;
     std::string wname, aname;
     split_name( waname, wname, aname);
     DataItem *a = get_window( wname).dataitem( aname);
     if ( a->location() != 'w')
       throw COM_exception( COM_ERR_NOT_A_WINDOW_DATAITEM,
                            append_frame(waname, COM_base::set_f90pointer));
     if ( a->data_type() == COM_F90POINTER) {
       int n=get_sizeof(COM_F90POINTER, a->size_of_components());
       std::pair<int,int> offs = get_f90pntoffsets( a);
       std::memcpy( a->pointer(), (char*)ptr-offs.first, offs.second);
       if ( offs.second<n) {
         *(void**)((char*)a->pointer()+offs.second) =
           (char*)a->pointer()+offs.first+((char*)len-(char*)ptr);
       }
       COM_assertion_msg( _f90ptr_treat>=0, "No F90 pointer initalized");
       if ( _f90ptr_treat == FPTR_INSERT || _f90ptr_treat == FPTR_APPEND) {
         typedef void(*Func2)(void*,void*, long int, long int);
         *(void**)((char*)a->pointer()+offs.first)=NULL;
         (*(Func2)f)( ptr, (char*)a->pointer()+offs.first,
                      len, *(long int*)((char*)a->pointer()+offs.second));
       }
       else {
         typedef void(*Func2)(void*,void*);
         (*(Func2)f)( (char*)ptr+offs.first, a->pointer());
       }
       if ( _verb1>1) {
         std::cerr << "COM: copied values ";
         for ( int i=0, ni=n/sizeof(void*); i<ni; ++i)
           std::cerr << ((void**)a->pointer())[i] << ' ';
         std::cerr << std::endl;
       }
     }
     else
       throw COM_exception( COM_ERR_NOT_A_POINTER,
                            append_frame(waname, COM_base::set_f90pointer));
   }
   catch ( COM_exception ex) {
     ex.msg = append_frame( ex.msg, COM_base::set_f90pointer);
     proc_exception( ex, "");
   }
 }
void COM_base::set_function (const std::string & wf, Func_ptr ptr, const std::string & intents, const COM_Type * types, bool ff = false) throw (int)
The names of the window and the function is give by wf in the format of "window.function" (null terminated). The address is given by ptr. The last two arguments specifies the number of the arguments, the intentions and types of the arguments.
Definition at line 1560 of file COM_base.C.
References append_frame, COM_ERR_TOO_MANY_ARGS, COM_ERR_UNKNOWN_DATATYPE, COM_ERR_UNKNOWN_INTENT, COM_MAX_TYPEID, COM_MIN_TYPEID, Function::MAX_NUMARG, COM_exception::msg, print_type(), and s.
Referenced by COM_F_FUNC2(), and COM_set_function().
{
   try {
     if ( _verb1>1) {
       int n=intents.size();
       std::cerr << "COM: init function \"" << wfname << '"'
                 << " to " << ptr << " with " << n << " parameters";
       for ( int i=0; i<n; ++i) {
         std::cerr << "\n\t" << intents[i] << ":";
         print_type( std::cerr, types[i]);
       }
       std::cerr << std::endl;
     }
     std::string wname, fname;
     split_name( wfname, wname, fname);
     if ( intents.size() > Function::MAX_NUMARG)
       throw COM_exception( COM_ERR_TOO_MANY_ARGS,
                            append_frame(wfname, COM_base::set_function));
     for ( int i=0, size=intents.size(); i<size; ++i) {
       if (intents[i] != 'i' && intents[i] != 'o' && intents[i] != 'b' &&
           intents[i] != 'I' && intents[i] != 'O' && intents[i] != 'B')
         throw COM_exception( COM_ERR_UNKNOWN_INTENT,
                              append_frame(wfname, COM_base::set_function));
       if ( types[i] < COM_MIN_TYPEID || types[i] > COM_MAX_TYPEID)
         throw COM_exception( COM_ERR_UNKNOWN_DATATYPE,
                              append_frame(wfname, COM_base::set_function));
     }
     get_window( wname).set_function( fname, ptr, intents, types, NULL, ff);
     _errorcode = 0;
   }
   catch ( COM_exception ex) {
     ex.msg = append_frame( ex.msg, COM_base::set_function);
     std::string s;
     s = s + "When processing dataitem " + wfname;
     proc_exception( ex, s);
   }
 }
void COM_base::set_function_verbose (int i, int level) throw (int)
Definition at line 2034 of file COM_base.C.
{
   _func_map.verbs[i] = level;
 }
void COM::COM_base::set_member_function (const std::string & wf, Func_ptr ptr, const std::string & wa, const std::string & intents, const COM_Type * types, bool ff = false) throw (int)
Referenced by COM_F_FUNC2(), and COM_set_member_function().
void COM::COM_base::set_member_function (const std::string & wf, Member_func_ptr ptr, const std::string & wa, const std::string & intents, const COM_Type * types, bool ff = false) throw (int)
template<class T > void COM::COM_base::set_member_function_helper (const std::string & wf, T ptr, const std::string & wa, const std::string & intents, const COM_Type * types, bool ff = false) throw (int) protected
template<class T > void COM::COM_base::set_member_function_helper (const std::string & wfname, T ptr, const std::string & waname, const std::string & intents, const COM_Type * types, bool ff) throw (int)
Definition at line 1606 of file COM_base.C.
References append_frame, COM_ERR_DATAITEM_NOTEXIST, COM_ERR_F90FUNC, COM_ERR_TOO_MANY_ARGS, COM_ERR_UNKNOWN_DATATYPE, COM_ERR_UNKNOWN_INTENT, COM_F90POINTER, COM_MAX_TYPEID, COM_MIN_TYPEID, DataItem::data_type(), Function::MAX_NUMARG, COM_exception::msg, print_type(), and s.
{
   try {
     if ( _verb1>1) {
       int n=intents.size();
       std::cerr << "COM: init function \"" << wfname  << '"'
                 << " to " << ptr << " with " << n << " parameters";
       for ( int i=0; i<n; ++i) {
         std::cerr << "\n\t" << intents[i] << ":";
         print_type( std::cerr, types[i]);
         if ( i==0) std::cerr << "\t\"" << waname << "\"";
       }
       std::cerr << std::endl;
     }
     std::string wname, fname;
     split_name( wfname, wname, fname);
     // Allows an additional implicit argument
     if ( intents.size() > Function::MAX_NUMARG+1)
       throw COM_exception( COM_ERR_TOO_MANY_ARGS,
                            append_frame(wfname, COM_base::set_member_function));
     for ( int i=0, size=intents.size(); i<size; ++i) {
       if (intents[i] != 'i' && intents[i] != 'o' && intents[i] != 'b' &&
           intents[i] != 'I' && intents[i] != 'O' && intents[i] != 'B')
         throw COM_exception( COM_ERR_UNKNOWN_INTENT,
                              append_frame(wfname, COM_base::set_member_function));
       if ( types[i] < COM_MIN_TYPEID || types[i] > COM_MAX_TYPEID)
         throw COM_exception( COM_ERR_UNKNOWN_DATATYPE,
                              append_frame(wfname, COM_base::set_member_function));
     }
     std::string wname1, aname1;
     split_name( waname, wname1, aname1);
     DataItem *a = get_window( wname1).dataitem( aname1);
     if ( a==NULL)
       throw COM_exception( COM_ERR_DATAITEM_NOTEXIST,
                            append_frame(wfname, COM_base::set_member_function));
     if ( !ff && a->data_type()==COM_F90POINTER)
       throw COM_exception( COM_ERR_F90FUNC,
                            append_frame(wfname, COM_base::set_member_function));
     get_window( wname).set_function( fname, ptr, intents, types, a, ff);
     _errorcode = 0;
   }
   catch ( COM_exception ex) {
     ex.msg = append_frame( ex.msg, COM_base::set_function);
     std::string s;
     s = s + "When processing dataitem " + wfname;
     proc_exception( ex, s);
   }
 }
void COM_base::set_object (const std::string & wa, const int pane_id, void * obj_addr, void * casted_obj) throw (int)
Definition at line 597 of file COM_base.C.
References COM_Object_derived::cast_obj(), and COM_assertion_msg.
Referenced by COM_set_object().
 {
   COM_assertion_msg( obj_addr, "Caught NULL pointer");
   int size;
   get_dataitem( wa, NULL, NULL, &size, NULL);
   COM_assertion_msg( size==1, "Must register a scalar with set_object");
   if ( obj_addr == casted_addr) {
     set_array( wa, pid, obj_addr);
     return;
   }
   if ( _cppobj_casting == -1)
     _cppobj_casting = COM_Object_derived::cast_obj();
   if ( _cppobj_casting) // Use stride to store the offset
     set_array( wa, pid, casted_addr, (char*)casted_addr-(char*)obj_addr);
   else
     set_array( wa, pid, obj_addr);
 }
void COM_base::set_profiling (int i)
It (re-)initializes all profiling info to 0.
Definition at line 2039 of file COM_base.C.
Referenced by COM_F_FUNC2(), and COM_set_profiling().
                       {
   if ( _verb1>1)
     std::cerr << "COM: init profiling level to " << i << std::endl;
   _profile_on = i;
   std::fill(_func_map.wtimes_tree.begin(),_func_map.wtimes_tree.end(), 0);
   std::fill(_func_map.wtimes_self.begin(),_func_map.wtimes_self.end(), 0);
   std::fill(_func_map.counts.begin(),_func_map.counts.end(), 0);
 }
void COM_base::set_profiling_barrier (int hdl, MPI_Comm comm)
Definition at line 2049 of file COM_base.C.
References append_frame, COM_ERR_INVALID_FUNCTION_HANDLE, COMMPI_Initialized(), and COM_exception::msg.
Referenced by COM_F_FUNC2(), and COM_set_profiling_barrier().
{
   if ( hdl == 0) return;
   try {
     if ( hdl < 0 || hdl>=_func_map.size())
       throw COM_exception( COM_ERR_INVALID_FUNCTION_HANDLE);
     if ( _verb1>1)
       std::cerr << "COM: init profiling barrier for function handle " << hdl
                 << std::endl << "\tFunction: " << _func_map.name(hdl)
                 << " Communicator: " << comm << std::endl;
     // Set the communicator only if MPI has been initialized.
     if ( COMMPI_Initialized()) {
       if ( comm==MPI_COMM_NULL) comm = _comm;
       get_function( hdl).set_communicator( comm);
     }
   }
   catch ( COM_exception ex) {
     ex.msg = append_frame( ex.msg, COM_base::set_profiling_barrier);
     char buf[100];
     std::sprintf( buf, "Could not get function with handle %d", hdl);
     proc_exception( ex, buf);
   }
 }
void COM_base::set_size (const std::string & wa_str, int pane_id, int nitems, int ng = 0) throw (int)
Note that for nodal or elemental data, setting sizes for one such dataitems affects all other dataitems.
Definition at line 541 of file COM_base.C.
References append_frame, COM_exception::msg, and s.
Referenced by COM_F_FUNC2(), and COM_set_size().
 {
   try {
     if ( _verb1>1) {
       std::cerr << "COM: Set size for dataitem \""
                 << wa << '"' << " on pane " << pid
                 << " to " << nitems << " items with " << ng
                 << " ghosts" << std::endl;
     }
     // Invoke Window::set_size
     std::string wname, aname;
     split_name( wa, wname, aname);
     get_window( wname).set_size( aname, pid, nitems, ng);
     _errorcode = 0;
   }
   catch ( COM_exception ex) {
     ex.msg = append_frame( ex.msg, COM_base::set_size);
     std::string s;
     s = s + "When processing dataitem " + wa;
     proc_exception( ex, s);
   }
 }
void COM::COM_base::set_verbose (int v) inline
Definition at line 354 of file COM_base.hpp.
References _verb1, and _verbose.
Referenced by COM_F_FUNC2(), and COM_set_verbose().
{
     _verbose = v; _verb1 = ( _verbose<=0) ? 0 :  (_verbose+1)%2+1;
   }
int COM_base::split_name (const std::string & wa, std::string & wname, std::string & aname, bool tothrow = true) throw (COM_exception) protected
Returns nonzero if fails.
Definition at line 2204 of file COM_base.C.
References append_frame, and COM_ERR_INVALID_DATAITEM_NAME.
 {
   std::string::size_type ni = wa.find(".");
   if ( ni == std::string::npos)
     wname = wa;
   else {
     wname = wa.substr( 0, ni);
     aname = wa.substr( ni+1, wname.size()-ni-1);
   }
   if ( wname.empty() || aname.empty())
     if ( tothrow)
       throw COM_exception(COM_ERR_INVALID_DATAITEM_NAME,
                           append_frame(wa,COM_base::split_name));
     else
       return 1;
   return 0;
 }
int COM::COM_base::test (int) inline
Definition at line 344 of file COM_base.hpp.
Referenced by COM_F_FUNC2(), and COM_test().
 { return 1; }
void COM::COM_base::turn_off_exception () inline
Definition at line 377 of file COM_base.hpp.
References _exception_on.
 { _exception_on = false; }
void COM::COM_base::turn_on_exception () inline
Definition at line 376 of file COM_base.hpp.
References _exception_on.
 { _exception_on = true; }
void COM_base::unload_module (const std::string & lname, const std::string & wname, int dodl = 1) throw (int)
Definition at line 296 of file COM_base.C.
References COM_ERR_COULD_FINDSYM, and COM_ERR_MODULE_NOTLOADED.
Referenced by COM_close_module(), COM_F_FUNC2(), and COM_unload_module().
{
 #ifndef STATIC_LINK
   if ( _verb1>1)
     std::cerr << "Unloading module " << lname << "..." << std::endl;
   // Obtain the window name corresponding to the library
   int index = _module_map.find(lname).first;
   if ( index<0)
     proc_exception( COM_exception( COM_ERR_MODULE_NOTLOADED, lname),
                     "COM_base::unload_module");
   std::set<std::string> &obj = _module_map[index].second;
   // If the module was loaded multiple times but window name is not
   // specified, then throw exception.
   if ( wname.empty() && obj.size()>1)
     proc_exception( COM_exception( COM_ERR_MODULE_NOTLOADED, lname),
                     "COM_base::unload_module");
   std::set<std::string>::iterator it = wname.empty()?obj.begin():obj.find( wname);
   // If wname is not found, throw exception
   if ( it==obj.end())
     proc_exception( COM_exception( COM_ERR_MODULE_NOTLOADED, lname),
                     "COM_base::unload_module");
   // Look for the symbol
   std::string fname = lname + "_unload_module";
   std::string wname_str=wname.size()?wname:*obj.begin();
   void *handle = _module_map[index].first;
   void *fptr = dlsym( handle, fname.c_str());
   if ( fptr != NULL) {
     // This is a C/C++ module
     typedef void(*Func1)(const char*);
     (*(Func1)fptr)( wname_str.c_str());
   }
   else {
     if ( _f90_mangling != -1) {
       if ( _f90_mangling & 1 == 1)
         std::transform( fname.begin(), fname.end(), fname.begin(), toupper);
       else
         std::transform( fname.begin(), fname.end(), fname.begin(), tolower);
       if ( _f90_mangling ==2 || _f90_mangling == 3) fname.append( "_");
       fptr = dlsym( handle, fname.c_str());
     }
     if ( fptr != NULL) {
       // This is a Fortran module
       typedef void(*Func2)(const char*,long int);
       (*(Func2)fptr)( wname_str.c_str(), wname_str.size());
     }
     else {
       proc_exception( COM_exception(COM_ERR_COULD_FINDSYM, fname+" in "+lname),
                       "COM_base::unload_module");
     }
   }
   obj.erase( wname);
   if ( dodl && obj.size()==0) { // Unload module if all instances removed.
     dlclose( handle);
     _module_map.remove_object( lname);
   }
   if ( _verb1>1)
     std::cerr << "Module " << lname << " unloaded" << std::endl;
 #endif
 }
void COM_base::use_dataitem (const std::string & wname, const std::string & pwname, int withghost = 1, const char * cndname = NULL, int val = 0) throw (int)
Definition at line 754 of file COM_base.C.
References append_frame, COM_ERR_DATAITEM_NOTEXIST, DataItem::empty(), Pane::INHERIT_USE, COM_exception::msg, and s.
Referenced by COM_use_dataitem().
 {
   try {
     if ( _verb1>1) {
       std::cerr << "COM: Using dataitem \"" << pwaname
                 << "\" onto \"" << waname << '"' << std::endl;
     }
     std::string pawname, paaname;
     split_name( pwaname, pawname, paaname);
     std::string awname, aaname;
     std::string::size_type ni = waname.find(".");
     if ( ni == std::string::npos) {
       awname = waname; aaname = "";
     }
     else
       split_name( waname, awname, aaname);
     std::string cawname, caaname;
     if ( cndname && *cndname!=0)
       split_name( cndname, cawname, caaname);
     DataItem *cnd=caaname.empty()?NULL:get_window(cawname).dataitem(caaname);
     if ( !caaname.empty() && cnd==NULL)
       throw COM_exception( COM_ERR_DATAITEM_NOTEXIST, cndname);
     get_window(awname).inherit( get_window( pawname).dataitem(paaname),
                                 aaname, Pane::INHERIT_USE, withghost, cnd, val);
     _errorcode = 0;
   }
   catch ( COM_exception ex) {
     ex.msg = append_frame( ex.msg, COM_base::use_dataitem);
     std::string s;
     s = s + "When window " + waname + " uses dataitem " + pwaname;
     proc_exception( ex, s);
   }
 }
void COM::COM_base::wait (int) inline
Definition at line 342 of file COM_base.hpp.
Referenced by COM_F_FUNC2(), and COM_wait().
 {}
void COM_base::window_init_done (const std::string & wname, bool panechanged = true) throw (int)
Definition at line 396 of file COM_base.C.
References append_frame, and COM_exception::msg.
Referenced by COM_F_FUNC2(), and COM_window_init_done().
 {
   try {
     get_window( wname).init_done(panechanged);
     _errorcode = 0;
   }
   catch ( COM_exception ex) {
     ex.msg = append_frame( ex.msg, COM_base::window_init_done);
     std::string msg = std::string("When completing the init of window ")+wname;
     proc_exception( ex, msg);
   }
   if ( _verb1>1)
     std::cerr << "COM: Done creating window \"" << wname
               << '"' << std::endl;
 }
Member Data Documentation
DataItem_map COM::COM_base::_attr_map protected
Definition at line 437 of file COM_base.hpp.
MPI_Comm COM::COM_base::_comm protected
Definition at line 445 of file COM_base.hpp.
Referenced by get_default_communicator(), and set_default_communicator().
int COM::COM_base::_cppobj_casting protected
-1: Unknown 0: No casting to COM_Object 1: Casting to COM_Object
Definition at line 458 of file COM_base.hpp.
int COM::COM_base::_depth protected
Definition at line 442 of file COM_base.hpp.
int COM::COM_base::_errorcode protected
Definition at line 447 of file COM_base.hpp.
Referenced by get_error_code().
bool COM::COM_base::_exception_on protected
Definition at line 448 of file COM_base.hpp.
Referenced by turn_off_exception(), and turn_on_exception().
int COM::COM_base::_f90_mangling protected
-1: Unknown. 0: lower-case without appending 1: upper-case without appending 2: lower-case with appending 3: upper-case with appending
Definition at line 451 of file COM_base.hpp.
int COM::COM_base::_f90ptr_treat protected
Definition at line 457 of file COM_base.hpp.
Referenced by f90ptr_treat().
Function_map COM::COM_base::_func_map protected
Definition at line 438 of file COM_base.hpp.
std::string COM::COM_base::_libdir protected
Definition at line 440 of file COM_base.hpp.
Module_map COM::COM_base::_module_map protected
Definition at line 435 of file COM_base.hpp.
bool COM::COM_base::_mpi_initialized protected
Definition at line 446 of file COM_base.hpp.
bool COM::COM_base::_profile_on protected
Definition at line 449 of file COM_base.hpp.
std::vector<double> COM::COM_base::_timer protected
Definition at line 441 of file COM_base.hpp.
int COM::COM_base::_verb1 protected
Definition at line 444 of file COM_base.hpp.
Referenced by set_verbose().
int COM::COM_base::_verbose protected
Definition at line 443 of file COM_base.hpp.
Referenced by set_verbose().
Window_map COM::COM_base::_window_map protected
Definition at line 436 of file COM_base.hpp.
COM_BEGIN_NAME_SPACE COM_base * COM_base::com_base =NULL static protected
Definition at line 463 of file COM_base.hpp.
Referenced by get_com().
The documentation for this class was generated from the following files:
COM_base.hpp
COM_base.C