IMPACT: SolverUtils::TransferObjectPar Class Reference
SolverUtils::TransferObjectPar Class Reference
Detailed Description
Definition at line 356 of file InterfaceLayer.H.
#include <InterfaceLayer.H>
Public Member Functions
TransferObjectPar (const std::string &inSurfxName, MPI_Comm inComm, int inVerbLevel=1)
void read_file_rocin (const char *fname, const std::string &wname, MPI_Comm comm)
void findWinName (std::string &fnameIn, std::string &wname)
int Overlay (const std::string &w1, const std::string &w2, const std::string &w1FnameHdf, const std::string &w2FnameHdf)
void SetVerbosity ()
int Transfer (const std::string &src_att, const std::string &trg_att, bool reverse=false)
int Interpolate (const std::string &src_att, const std::string &trg_att, bool reverse=false)
int TransferLoad (const std::string &src_att, const std::string &trg_att, bool reverse=false)
~TransferObjectPar ()
Private Attributes
std::string surfxWinName
std::string win1
std::string win2
int readhandle
int writehandle
int clearhandle
int verbhandle
int overlayhandle
int transferhandle
int interphandle
int loadtranshandle
int verbLevel
int nItrLsqTrans
double tolLsqTrans
MPI_Comm _comm
int _rank
int _nProc
Constructor & Destructor Documentation
SolverUtils::TransferObjectPar::TransferObjectPar (const std::string & inSurfxName, MPI_Comm inComm, int inVerbLevel = 1) inline
Definition at line 380 of file InterfaceLayer.H.
References _nProc, _rank, clearhandle, COM_get_function_handle(), SolverUtils::COM_LOAD_MODULE_STATIC_DYNAMIC(), interphandle, loadtranshandle, overlayhandle, readhandle, SetVerbosity(), surfxWinName, transferhandle, verbhandle, and writehandle.
                                                                                           :
       surfxWinName(inSurfxName), _comm(inComm), verbLevel(inVerbLevel),
       nItrLsqTrans(100), tolLsqTrans(1.0e-6)
     {
       MPI_Comm_rank(inComm, &_rank);
       MPI_Comm_size(inComm, &_nProc);
       COM_LOAD_MODULE_STATIC_DYNAMIC(SurfX, surfxWinName.c_str());
       readhandle      = COM_get_function_handle((surfxWinName+std::string(".read_overlay")).c_str());
       writehandle     = COM_get_function_handle((surfxWinName+std::string(".write_overlay")).c_str());
       clearhandle     = COM_get_function_handle((surfxWinName+std::string(".clear_overlay")).c_str());
       verbhandle      = COM_get_function_handle((surfxWinName+std::string(".set_verbose")).c_str());
       overlayhandle   = COM_get_function_handle((surfxWinName+std::string(".overlay")).c_str());
       interphandle    = COM_get_function_handle((surfxWinName+std::string(".interpolate")).c_str());
       transferhandle  = COM_get_function_handle((surfxWinName+std::string(".least_squares_transfer")).c_str());
       loadtranshandle = COM_get_function_handle((surfxWinName+std::string(".load_transfer")).c_str());
       SetVerbosity();
     };
SolverUtils::TransferObjectPar::~TransferObjectPar () inline
Definition at line 538 of file InterfaceLayer.H.
References COM_UNLOAD_MODULE_STATIC_DYNAMIC, and surfxWinName.
     {
       COM_UNLOAD_MODULE_STATIC_DYNAMIC(SurfX,surfxWinName.c_str());
     };
Member Function Documentation
void SolverUtils::TransferObjectPar::findWinName (std::string & fnameIn, std::string & wname) inline
Definition at line 427 of file InterfaceLayer.H.
References COM_assertion_msg.
{
        std::string::size_type n0 = fnameIn.find_last_of( "/");
        std::string fname;
        if ( n0 == std::string::npos) fname=fnameIn;
        else fname = fnameIn.substr(n0+1, fnameIn.size());
        std::string::size_type ni;
        ni = fname.find_first_of( "_.:-*[]?\\\"\'0123456789");
        COM_assertion_msg( ni, "File name must start with a letter");
        if (ni == std::string::npos) {
           wname = fname;
        } else {
           wname = fname.substr( 0, ni);
        }
     }
int SolverUtils::TransferObjectPar::Interpolate (const std::string & src_att, const std::string & trg_att, bool reverse = false) inline
Definition at line 510 of file InterfaceLayer.H.
References SolverUtils::COM_call_function(), COM_get_dataitem_handle(), interphandle, win1, and win2.
     {
       std::string srcwin((reverse ? win2 : win1));
       std::string trgwin((reverse ? win1 : win2));
       std::string srcatt = srcwin + "." + src_att;
       std::string trgatt = trgwin + "." + trg_att;
       int src_handle = COM_get_dataitem_handle(srcatt.c_str());
       int trg_handle = COM_get_dataitem_handle(trgatt.c_str());
       if((src_handle <= 0) || (trg_handle <= 0))
         return(-1);
       COM_call_function(interphandle,&src_handle,&trg_handle);
       return(0);
     };
int SolverUtils::TransferObjectPar::Overlay (const std::string & w1, const std::string & w2, const std::string & w1FnameHdf, const std::string & w2FnameHdf) inline
Definition at line 443 of file InterfaceLayer.H.
References _comm, _rank, SolverUtils::COM_call_function(), COM_delete_window(), COM_get_dataitem_handle(), COM_set_default_communicator(), COM_window_init_done(), overlayhandle, read_file_rocin(), readhandle, win1, win2, and writehandle.
     {
       win1 = w1;
       win2 = w2;
       // waiting for all processes to finish
       MPI_Barrier(_comm);
       // generating and writing common refinement
       if (_rank == 0) {
          COM_set_default_communicator(MPI_COMM_NULL);
          std::string tmpW1 = w1 + "tmp";
          std::string tmpW2 = w2 + "tmp";
          read_file_rocin( w1FnameHdf.c_str(), tmpW1, MPI_COMM_SELF);
          COM_window_init_done(tmpW1);
          read_file_rocin( w2FnameHdf.c_str(), tmpW2, MPI_COMM_SELF);
          COM_window_init_done(tmpW2);
          int mesh1 = COM_get_dataitem_handle((tmpW1+".mesh").c_str());
          int mesh2 = COM_get_dataitem_handle((tmpW2+".mesh").c_str());
          if(mesh1 <= 0 || mesh2 <= 0)
            return(-1);
          COM_call_function(overlayhandle, &mesh1, &mesh2);
          const char *format = "HDF";
          COM_call_function(writehandle, &mesh1, &mesh2, w1.c_str(), w2.c_str(), format);
          COM_delete_window(tmpW1);
          COM_delete_window(tmpW2);
          COM_set_default_communicator(_comm);
       }
       // waiting for the overlay step to finish
       MPI_Barrier(_comm);
       // reading overlay
       int itm1 = COM_get_dataitem_handle((w1+".mesh").c_str());
       int itm2 = COM_get_dataitem_handle((w2+".mesh").c_str());
       if(itm1 <= 0 || itm2 <= 0)
         return(-1);
       COM_call_function(readhandle, &itm1, &itm2, &_comm, w1.c_str(), w2.c_str(), "HDF");
       return(0);
     };
void SolverUtils::TransferObjectPar::read_file_rocin (const char * fname, const std::string & wname, MPI_Comm comm) inline
Definition at line 400 of file InterfaceLayer.H.
References SolverUtils::COM_call_function(), COM_clone_dataitem(), COM_delete_window(), COM_get_dataitem_handle(), COM_get_function_handle(), SolverUtils::COM_LOAD_MODULE_STATIC_DYNAMIC(), COM_new_window(), and COM_UNLOAD_MODULE_STATIC_DYNAMIC.
Referenced by Overlay().
{
         char *lastdot=strrchr( const_cast<char *>(fname), '.');
         COM_new_window( wname.c_str(), comm);
         // read in HDF files or a Rocin control file
         std::string siminWinName = "IN";
         COM_LOAD_MODULE_STATIC_DYNAMIC(SimIN, siminWinName.c_str());
         int IN_read;
         if ( strcmp( lastdot, ".hdf")==0 || strcmp( lastdot, ".cgns")==0 )
           IN_read = COM_get_function_handle( (siminWinName + ".read_window").c_str());
         else if ( strcmp( lastdot, ".txt")==0)
           IN_read = COM_get_function_handle( (siminWinName + ".read_by_control_file").c_str());
         std::string bufwin( "bufwin");
         COM_call_function( IN_read, fname, bufwin.c_str(), &comm);
         int IN_obtain = COM_get_function_handle( (siminWinName + ".obtain_dataitem").c_str());
         // copying contents of the window
         int buf_mesh = COM_get_dataitem_handle( (bufwin + ".mesh").c_str());
         COM_call_function( IN_obtain, &buf_mesh, &buf_mesh);
         COM_clone_dataitem( (wname + ".mesh").c_str(), (bufwin + ".mesh").c_str(), 0);
         COM_delete_window( bufwin.c_str());
         COM_UNLOAD_MODULE_STATIC_DYNAMIC(SimIN,siminWinName.c_str());
     }
void SolverUtils::TransferObjectPar::SetVerbosity () inline
Definition at line 490 of file InterfaceLayer.H.
References SolverUtils::COM_call_function(), COM_get_function_handle(), surfxWinName, and verbLevel.
Referenced by TransferObjectPar().
     {
       COM_call_function(COM_get_function_handle((surfxWinName+".set_verbose").c_str()),&verbLevel);
     };
int SolverUtils::TransferObjectPar::Transfer (const std::string & src_att, const std::string & trg_att, bool reverse = false) inline
Definition at line 495 of file InterfaceLayer.H.
References SolverUtils::COM_call_function(), COM_get_dataitem_handle(), transferhandle, win1, and win2.
     {
       std::string srcwin((reverse ? win2 : win1));
       std::string trgwin((reverse ? win1 : win2));
       std::string srcatt = srcwin + "." + src_att;
       std::string trgatt = trgwin + "." + trg_att;
       int src_handle = COM_get_dataitem_handle(srcatt.c_str());
       int trg_handle = COM_get_dataitem_handle(trgatt.c_str());
       if((src_handle <= 0) || (trg_handle <= 0))
         return(-1);
       COM_call_function(transferhandle, &src_handle, &trg_handle);
       //COM_call_function(transferhandle, &src_handle, &trg_handle, NULL, NULL, &tolLsqTrans, &nItrLsqTrans);
       return(0);
     };
int SolverUtils::TransferObjectPar::TransferLoad (const std::string & src_att, const std::string & trg_att, bool reverse = false) inline
Definition at line 524 of file InterfaceLayer.H.
References SolverUtils::COM_call_function(), COM_get_dataitem_handle(), loadtranshandle, win1, and win2.
     {
       std::string srcwin((reverse ? win2 : win1));
       std::string trgwin((reverse ? win1 : win2));
       std::string srcatt = srcwin + "." + src_att;
       std::string trgatt = trgwin + "." + trg_att;
       int src_handle = COM_get_dataitem_handle(srcatt.c_str());
       int trg_handle = COM_get_dataitem_handle(trgatt.c_str());
       if((src_handle <= 0) || (trg_handle <= 0))
         return(-1);
       COM_call_function(loadtranshandle,&src_handle,&trg_handle);
       return(0);
     };
Member Data Documentation
MPI_Comm SolverUtils::TransferObjectPar::_comm private
Definition at line 375 of file InterfaceLayer.H.
Referenced by Overlay().
int SolverUtils::TransferObjectPar::_nProc private
Definition at line 377 of file InterfaceLayer.H.
Referenced by TransferObjectPar().
int SolverUtils::TransferObjectPar::_rank private
Definition at line 376 of file InterfaceLayer.H.
Referenced by Overlay(), and TransferObjectPar().
int SolverUtils::TransferObjectPar::clearhandle private
Definition at line 364 of file InterfaceLayer.H.
Referenced by TransferObjectPar().
int SolverUtils::TransferObjectPar::interphandle private
Definition at line 368 of file InterfaceLayer.H.
Referenced by Interpolate(), and TransferObjectPar().
int SolverUtils::TransferObjectPar::loadtranshandle private
Definition at line 369 of file InterfaceLayer.H.
Referenced by TransferLoad(), and TransferObjectPar().
int SolverUtils::TransferObjectPar::nItrLsqTrans private
Definition at line 372 of file InterfaceLayer.H.
int SolverUtils::TransferObjectPar::overlayhandle private
Definition at line 366 of file InterfaceLayer.H.
Referenced by Overlay(), and TransferObjectPar().
int SolverUtils::TransferObjectPar::readhandle private
Definition at line 362 of file InterfaceLayer.H.
Referenced by Overlay(), and TransferObjectPar().
std::string SolverUtils::TransferObjectPar::surfxWinName private
Definition at line 358 of file InterfaceLayer.H.
Referenced by SetVerbosity(), TransferObjectPar(), and ~TransferObjectPar().
double SolverUtils::TransferObjectPar::tolLsqTrans private
Definition at line 373 of file InterfaceLayer.H.
int SolverUtils::TransferObjectPar::transferhandle private
Definition at line 367 of file InterfaceLayer.H.
Referenced by Transfer(), and TransferObjectPar().
int SolverUtils::TransferObjectPar::verbhandle private
Definition at line 365 of file InterfaceLayer.H.
Referenced by TransferObjectPar().
int SolverUtils::TransferObjectPar::verbLevel private
Definition at line 370 of file InterfaceLayer.H.
Referenced by SetVerbosity().
std::string SolverUtils::TransferObjectPar::win1 private
Definition at line 359 of file InterfaceLayer.H.
Referenced by Interpolate(), Overlay(), Transfer(), and TransferLoad().
std::string SolverUtils::TransferObjectPar::win2 private
Definition at line 360 of file InterfaceLayer.H.
Referenced by Interpolate(), Overlay(), Transfer(), and TransferLoad().
int SolverUtils::TransferObjectPar::writehandle private
Definition at line 363 of file InterfaceLayer.H.
Referenced by Overlay(), and TransferObjectPar().
The documentation for this class was generated from the following file:
InterfaceLayer.H