IMPACT: MeshMotionTransfer_SF Class Reference
MeshMotionTransfer_SF Class Reference
Detailed Description
Definition at line 106 of file transfer_actions.h.
#include <transfer_actions.h>
Public Member Functions
MeshMotionTransfer_SF (FluidAgent *fag, SolidAgent *sag, const std::string s_u, const std::string f_total_disp, const std::string f_vm)
void init (double t)
void run (double t, double dt, double alpha)
Public Member Functions inherited from InterMeshTransfer
InterMeshTransfer (FluidAgent *fag, SolidAgent *sag, char *name=NULL)
Public Member Functions inherited from Action
Action (void *p=0, const char *name=NULL)
Action (int n, const char **at, int *i=NULL, void *p=0, const char *name=NULL)
Action (int n, const std::string at[], int *i=NULL, void *p=0, const char *name=NULL)
virtual ~Action ()
virtual void declare (Scheduler &)
virtual void finalize ()
virtual const char * name ()
void set_name (const char *name)
virtual void print (FILE *f)
virtual void print_toposort (FILE *f)
virtual void schedule ()
Private Attributes
int s_u_hdl
int f_total_disp_hdl
int f_vm_hdl
int f_nc_hdl
int f_nc_t0_hdl
int RFC_interpolate
Additional Inherited Members
Protected Types inherited from Action
enum { IN =1, OUT =2, INOUT =3 }
Protected Member Functions inherited from InterMeshTransfer
void load_rocface (const RocmanControl_parameters *param)
Protected Member Functions inherited from Action
int get_dataitem_handle (int i)
int get_dataitem_handle_const (int i)
int get_dataitem_handle (const std::string str)
void set_attr (int n, const std::string at[], int *id=NULL)
void set_attr (int n, const char *at[], int *id=NULL)
void set_io (int n, const int *io)
void set_io (const char *io)
int get_io (int i)
Protected Attributes inherited from InterMeshTransfer
FluidAgent * fagent
SolidAgent * sagent
Protected Attributes inherited from Action
const char * action_name
char ** attr
int * idx
int count
void * usr_ptr
std::vector< int > inout
Constructor & Destructor Documentation
MeshMotionTransfer_SF::MeshMotionTransfer_SF (FluidAgent * fag, SolidAgent * sag, const std::string s_u, const std::string f_total_disp, const std::string f_vm) explicit
Definition at line 612 of file transfer_actions.C.
References InterMeshTransfer::fagent, Agent::get_surface_window(), FluidAgent::ifluid_i, Action::IN, Action::INOUT, Action::OUT, Agent::register_clone_dataitem(), InterMeshTransfer::sagent, Action::set_attr(), Action::set_io(), and SolidAgent::solidBufBase.
                          :
     InterMeshTransfer(fag, sag, "MeshMotionTransfer_SF")
 {
   // isolid_i+".nc" (in), isolid_i+".u" (in), fagent->ifluid_i+".vm" (out)
   int io[] = {IN, IN, INOUT, OUT};
   set_io( 4, io);
   std::string.data[4];
  .data[0] = sagent->solidBufBase+".nc";
  .data[1] = s_u;
  .data[2] = f_total_disp;
  .data[3] = f_vm;
   set_attr(4,.data);
     // Change to transfer total_displacement from solid to fluids, and obtain
     // incremental displacement as (nc_t0+total_disp)-nc_tn. This is prone
     // to cancellation errors but avoids accumulation of any errors.
   fagent->register_clone_dataitem( 0, fagent->ifluid_i, ".total_disp", fagent->get_surface_window(), ".du_alp");
   fagent->register_clone_dataitem( 0, fagent->ifluid_i, ".nc_t0", fagent->get_surface_window(), ".nc");
     // nc_tmp is used to compare against solid nodal coordinates.
   //fagent->register_clone_dataitem( 0, fagent->ifluid_i, ".nc_tmp", fagent->get_surface_window(), ".nc");
   //fagent->register_new_dataitem( fagent->ifluid_i, ".sq_dist", 'n', COM_DOUBLE, 1, "m");
 }
Member Function Documentation
void MeshMotionTransfer_SF::init (double t) virtual
Reimplemented from Action.
Definition at line 638 of file transfer_actions.C.
References COM_get_dataitem_handle(), COM_get_function_handle(), f_nc_hdl, f_nc_t0_hdl, f_total_disp_hdl, f_vm_hdl, InterMeshTransfer::fagent, FluidAgent::fluidBufNG, Agent::get_coupling(), Action::get_dataitem_handle(), Coupling::get_rocmancontrol_param(), InterMeshTransfer::load_rocface(), RFC_interpolate, and s_u_hdl.
{
   // skip 0
   s_u_hdl = get_dataitem_handle(1);
   f_total_disp_hdl = get_dataitem_handle(2);
   f_vm_hdl = get_dataitem_handle(3);
   f_nc_hdl = COM_get_dataitem_handle( fagent->fluidBufNG+".nc");
   f_nc_t0_hdl = COM_get_dataitem_handle( fagent->fluidBufNG+".nc_t0");
   // POST_INIT_FLUID in fluid_agent.f90
     // initial_start  ?????
 //  if (t == 0.0) {
     // TODO ???
 //    COM_call_function( RocBlas::copy, &f_nc_hdl, &f_nc_t0_hdl);
       // UPDATE_INBUFF_GM_FLUID     ???????????????
 //    double zero = 0.0;
 //    fagent->obtain_gm(&zero);
 //  }
   load_rocface(fagent->get_coupling()->get_rocmancontrol_param());
   RFC_interpolate = COM_get_function_handle("RFC.interpolate");
 }
void MeshMotionTransfer_SF::run (double t, double dt, double alpha) virtual
Reimplemented from Action.
Definition at line 662 of file transfer_actions.C.
References RocBlas::add, COM_call_function(), RocBlas::div_scalar, f_nc_hdl, f_nc_t0_hdl, f_total_disp_hdl, f_vm_hdl, InterMeshTransfer::fagent, Agent::get_coupling(), Coupling::initial_start(), MAN_DEBUG, RFC_interpolate, s_u_hdl, and RocBlas::sub.
{
   MAN_DEBUG(2, ("Rocman: calling MeshMotionTransfer_SF::run() with t:%e dt:%e alpha:%e.\n", t, dt, alpha));
     // b. Interpolates total displacement from solid nodes to fluid nodes
   //debug_print(sagent->solidBuf+".u", 109, 0, sagent->get_communicator(), "U");
   COM_call_function( RFC_interpolate, &s_u_hdl, &f_total_disp_hdl);
     // Compute incremental mesh volocity
   if (!fagent->get_coupling()->initial_start()) {
     // Compute incremental mesh volocity
     COM_call_function( RocBlas::add, &f_nc_t0_hdl, &f_total_disp_hdl, &f_vm_hdl);
     COM_call_function( RocBlas::sub, &f_vm_hdl, &f_nc_hdl, &f_vm_hdl);
     COM_call_function( RocBlas::div_scalar, &f_vm_hdl, &dt, &f_vm_hdl);
   }
 }
Member Data Documentation
int MeshMotionTransfer_SF::f_nc_hdl private
Definition at line 113 of file transfer_actions.h.
Referenced by init(), and run().
int MeshMotionTransfer_SF::f_nc_t0_hdl private
Definition at line 113 of file transfer_actions.h.
Referenced by init(), and run().
int MeshMotionTransfer_SF::f_total_disp_hdl private
Definition at line 112 of file transfer_actions.h.
Referenced by init(), and run().
int MeshMotionTransfer_SF::f_vm_hdl private
Definition at line 112 of file transfer_actions.h.
Referenced by init(), and run().
int MeshMotionTransfer_SF::RFC_interpolate private
Definition at line 114 of file transfer_actions.h.
Referenced by init(), and run().
int MeshMotionTransfer_SF::s_u_hdl private
Definition at line 112 of file transfer_actions.h.
Referenced by init(), and run().
The documentation for this class was generated from the following files:
transfer_actions.h
transfer_actions.C