IMPACT: Condition Class Reference
Condition Class Reference
Detailed Description
Definition at line 32 of file Sync.h.
#include <Sync.h>
Public Member Functions
Condition (Mutex &mutex)
~Condition ()
bool IsOk () const
int Wait ()
int Signal ()
int Broadcast ()
Private Attributes
Mutex & m_mutex
pthread_cond_t m_cond
bool m_isOk
Constructor & Destructor Documentation
Condition::Condition (Mutex & mutex)
Definition at line 101 of file Sync.C.
References m_cond, and m_isOk.
 : m_mutex(mutex)
 {
   int err = pthread_cond_init(&m_cond, NULL);
   m_isOk = (err == 0);
   if (!m_isOk) {
     std::cerr << "Condition::Condition(): pthread_cond_init() returned " << err
               << std::endl;
   }
 }
Condition::~Condition ()
Definition at line 114 of file Sync.C.
References COMMPI_Initialized(), m_cond, and m_isOk.
 {
   if (m_isOk) {
     int err = pthread_cond_destroy(&m_cond);
     if (err != 0 && !COMMPI_Initialized()) {
       std::cerr << "Condition::~Condition(): pthread_cond_destroy() returned "
                 << err << std::endl;
     }
   }
 }
Member Function Documentation
int Condition::Broadcast ()
Definition at line 145 of file Sync.C.
References m_cond.
 {
   int err = pthread_cond_broadcast(&m_cond);
   if (err != 0)
     std::cerr << "Condition::Broadcast(): pthread_cond_broadcast() returned "
               << err << std::endl;
   return err;
 }
bool Condition::IsOk () const inline
Definition at line 38 of file Sync.h.
References Mutex::IsOk(), m_isOk, and m_mutex.
Referenced by Semaphore::Semaphore().
 { return (m_isOk && m_mutex.IsOk()); }
int Condition::Signal ()
Definition at line 135 of file Sync.C.
References m_cond.
Referenced by Semaphore::Post().
 {
   int err = pthread_cond_signal(&m_cond);
   if (err != 0)
     std::cerr << "Condition::Signal(): pthread_cond_signal() returned " << err
               << std::endl;
   return err;
 }
int Condition::Wait ()
Definition at line 125 of file Sync.C.
References m_cond, Mutex::m_mutex, and m_mutex.
Referenced by Semaphore::Wait().
 {
   int err = pthread_cond_wait(&m_cond, &(m_mutex.m_mutex));
   if (err != 0)
     std::cerr << "Condition::Wait(): pthread_cond_wait() returned " << err
               << std::endl;
   return err;
 }
Member Data Documentation
pthread_cond_t Condition::m_cond private
Definition at line 46 of file Sync.h.
Referenced by Broadcast(), Condition(), Signal(), Wait(), and ~Condition().
bool Condition::m_isOk private
Definition at line 47 of file Sync.h.
Referenced by Condition(), IsOk(), and ~Condition().
Mutex& Condition::m_mutex private
Definition at line 45 of file Sync.h.
Referenced by IsOk(), and Wait().
The documentation for this class was generated from the following files:
Sync.h
Sync.C