IMPACT: Mutex Class Reference
Mutex Class Reference
Detailed Description
Definition at line 13 of file Sync.h.
#include <Sync.h>
Public Member Functions
Mutex ()
~Mutex ()
bool IsOk () const
int Lock ()
int TryLock ()
int Unlock ()
Private Attributes
pthread_mutex_t m_mutex
bool m_isOk
Friends
class Condition
Constructor & Destructor Documentation
Mutex::Mutex ()
Definition at line 14 of file Sync.C.
References m_isOk, and m_mutex.
 {
   int err = pthread_mutex_init(&m_mutex, NULL);
   m_isOk = (err == 0);
   if (!m_isOk) {
     std::cerr << "Mutex::Mutex(): pthread_mutex_init() returned " << err
               << std::endl;
   }
 }
Mutex::~Mutex ()
Definition at line 24 of file Sync.C.
References COMMPI_Initialized(), m_isOk, and m_mutex.
 {
   if (m_isOk) {
     int err = pthread_mutex_destroy(&m_mutex);
     if (err != 0 && !COMMPI_Initialized()) {
       std::cerr << "Mutex::~Mutex(): pthread_mutex_destroy() returned " << err
                 << std::endl;
     }
   }
 }
Member Function Documentation
bool Mutex::IsOk () const inline
Definition at line 19 of file Sync.h.
References m_isOk.
Referenced by Condition::IsOk(), and Semaphore::Semaphore().
 { return m_isOk; }
int Mutex::Lock ()
Definition at line 35 of file Sync.C.
References m_mutex.
Referenced by Semaphore::Post(), Semaphore::TryWait(), and Semaphore::Wait().
 {
   int err = pthread_mutex_lock(&m_mutex);
   switch (err) {
     case 0:
       break;
     case EDEADLK:
       std::cerr << "Mutex::Lock(): mutex deadlock prevented." << std::endl;
       break;
     case EINVAL:
       std::cerr << "Mutex::Lock(): mutex not initialized." << std::endl;
       break;
     default:
       std::cerr << "Mutex::Lock(): pthread_mutex_lock() returned " << err
                 << std::endl;
       break;
   }
   return err;
 }
int Mutex::TryLock ()
Definition at line 59 of file Sync.C.
References m_mutex.
 {
     int err = pthread_mutex_trylock(&m_mutex);
     switch (err) {
       case 0:
       case EBUSY:
          break;
       case EINVAL:
         std::cerr << "Mutex::TryLock(): mutex not initialized." << std::endl;
         break;
       default:
         std::cerr << "Mutex::TryLock(): pthread_mutex_trylock() returned "
                   << err << std::endl;
         break;
     }
     return err;
 }
int Mutex::Unlock ()
Definition at line 80 of file Sync.C.
References m_mutex.
Referenced by Semaphore::Post(), Semaphore::TryWait(), and Semaphore::Wait().
 {
   int err = pthread_mutex_unlock(&m_mutex);
   switch (err) {
     case 0:
     case EPERM:
       break;
     case EINVAL:
       std::cerr << "Mutex::Unlock(): mutex not initialized." << std::endl;
       break;
     default:
       std::cerr << "Mutex::Unlock(): pthread_mutex_unlock() returned " << err
                 << std::endl;
       break;
   }
   return err;
 }
Friends And Related Function Documentation
friend class Condition friend
Definition at line 25 of file Sync.h.
Member Data Documentation
bool Mutex::m_isOk private
Definition at line 29 of file Sync.h.
Referenced by IsOk(), Mutex(), and ~Mutex().
pthread_mutex_t Mutex::m_mutex private
Definition at line 28 of file Sync.h.
Referenced by Lock(), Mutex(), TryLock(), Unlock(), Condition::Wait(), and ~Mutex().
The documentation for this class was generated from the following files:
Sync.h
Sync.C