IMPACT: HDS_accessor Class Reference
HDS_accessor Class Reference
Detailed Description
Definition at line 25 of file HDS_accessor.h.
#include <HDS_accessor.h>
Public Types
typedef Point_3 Point
typedef Vector_3 Vector
Public Member Functions
HEdge get_prev_around_origin (const HEdge &h) const
HEdge get_next_around_origin (const HEdge &h) const
HEdge get_prev_around_destination (const HEdge &h) const
HEdge get_next_around_destination (const HEdge &h) const
bool is_on_feature (const Node &v) const
bool is_feature_0 (const Node &v) const
bool is_feature_1 (const HEdge &h) const
const Vector_3 & get_normal (const HEdge &h) const
const Vector_3 & get_normal (const HEdge &h, const Node &v) const
void mark (const HEdge &h) const
void unmark (const HEdge &h) const
bool marked (const HEdge &h) const
INode * get_inode (const Node &v) const
void set_inode (const Node &v, INode *i) const
INode_list & get_inode_list (const HEdge &h) const
Member Typedef Documentation
typedef Point_3 HDS_accessor::Point
Definition at line 31 of file HDS_accessor.h.
typedef Vector_3 HDS_accessor::Vector
Definition at line 32 of file HDS_accessor.h.
Member Function Documentation
INode* HDS_accessor::get_inode (const Node & v) const inline
Definition at line 74 of file HDS_accessor.h.
References Node::is_primary(), Node::pane(), and RFC_assertion.
Referenced by Overlay::associate_green_vertices(), Overlay::get_inodes_of_face(), Overlay::get_next_inode_ccw(), Overlay::get_next_inode_cw(), Overlay::insert_node_in_blue_edge(), Overlay::insert_node_in_green_edge(), Overlay::intersect_blue_with_green(), Overlay::match_features_0(), Overlay::project_adjacent_green_vertices(), Overlay::sort_on_green_edges(), and Overlay::verify_inode().
   { RFC_assertion( v.is_primary()); return v.pane()->get_inode( v); }
INode_list& HDS_accessor::get_inode_list (const HEdge & h) const inline
Definition at line 79 of file HDS_accessor.h.
References RFC_Pane_overlay::get_inode_list(), and HEdge::pane().
Referenced by Overlay::associate_green_vertices(), Overlay::get_inodes_of_face(), Overlay::get_next_inode_ccw(), Overlay::get_next_inode_cw(), Overlay::insert_node_in_blue_edge(), Overlay::intersect_blue_with_green(), Overlay::project_adjacent_green_vertices(), Overlay::sort_on_green_edges(), and Overlay::verify_inode().
   { return h.pane()->get_inode_list(h); }
HEdge HDS_accessor::get_next_around_destination (const HEdge & h) const inline
Definition at line 46 of file HDS_accessor.h.
References HEdge::next_g(), and HEdge::opposite_g().
Referenced by RFC_Window_overlay::check_false_strong_1(), RFC_Window_overlay::comp_angle_defect(), RFC_Window_overlay::evaluate_normals(), RFC_Window_overlay::is_strong_ad(), Overlay::match_features_0(), and RFC_Window_overlay::remove_feature_1().
   { return h.next_g().opposite_g(); }
HEdge HDS_accessor::get_next_around_origin (const HEdge & h) const inline
Definition at line 40 of file HDS_accessor.h.
References HEdge::next_g(), and HEdge::opposite_g().
Referenced by Overlay::count_subnodes(), RFC_Window_overlay::detect_features(), Overlay::get_edge_parent(), Overlay::get_next_inode_ccw(), Overlay::get_next_inode_cw(), Overlay::insert_node_in_blue_edge(), Overlay::intersect_blue_with_green(), Overlay::match_features_0(), and Overlay::number_a_subnode().
   { return h.opposite_g().next_g(); }
const Vector_3& HDS_accessor::get_normal (const HEdge & h) const inline
Definition at line 64 of file HDS_accessor.h.
References HEdge::destination_l(), RFC_Pane_overlay::get_normal(), and HEdge::pane().
Referenced by Overlay::get_green_parent(), Overlay_primitives::intersect(), and Overlay_primitives::normalmatch().
   { return h.pane()->get_normal(h, h.destination_l()); }
const Vector_3& HDS_accessor::get_normal (const HEdge & h, const Node & v) const inline
Definition at line 67 of file HDS_accessor.h.
References RFC_Pane_overlay::get_normal(), and HEdge::pane().
   { return h.pane()->get_normal(h, v); }
HEdge HDS_accessor::get_prev_around_destination (const HEdge & h) const inline
Definition at line 43 of file HDS_accessor.h.
References HEdge::opposite_g(), and HEdge::prev_g().
   { return h.opposite_g().prev_g(); }
HEdge HDS_accessor::get_prev_around_origin (const HEdge & h) const inline
Definition at line 37 of file HDS_accessor.h.
References HEdge::opposite_g(), and HEdge::prev_g().
   { return h.prev_g().opposite_g(); }
bool HDS_accessor::is_feature_0 (const Node & v) const inline
Definition at line 56 of file HDS_accessor.h.
References Node::get_primary(), and Node::pane().
Referenced by Overlay::insert_edge_into_queue().
{
     Node vprim = v.get_primary();
     return vprim.pane()->is_feature_0(vprim);
   }
bool HDS_accessor::is_feature_1 (const HEdge & h) const inline
Definition at line 61 of file HDS_accessor.h.
References RFC_Pane_overlay::is_feature_1(), and HEdge::pane().
Referenced by Overlay::insert_edge_into_queue(), Overlay::intersect_blue_with_green(), Overlay::intersect_link(), and Overlay_primitives::normalmatch().
   { return h.pane()->is_feature_1(h); }
bool HDS_accessor::is_on_feature (const Node & v) const inline
Definition at line 51 of file HDS_accessor.h.
References Node::get_primary(), and Node::pane().
Referenced by Overlay::insert_edge_into_queue(), Overlay::intersect_blue_with_green(), Overlay_primitives::snap_blue_ridge_edge(), and Overlay_primitives::snap_blue_ridge_vertex().
{
     Node vprim = v.get_primary();
     return vprim.pane()->is_on_feature(vprim);
   }
void HDS_accessor::mark (const HEdge & h) const inline
Definition at line 70 of file HDS_accessor.h.
References RFC_Pane_overlay::mark(), and HEdge::pane().
Referenced by RFC_Window_overlay::detect_features(), Overlay::get_green_parent(), Overlay::insert_edge_into_queue(), and Overlay::is_queue_empty().
 { h.pane()->mark( h); }
bool HDS_accessor::marked (const HEdge & h) const inline
Definition at line 72 of file HDS_accessor.h.
References RFC_Pane_overlay::marked(), and HEdge::pane().
Referenced by RFC_Window_overlay::detect_features(), Overlay::get_green_parent(), Overlay::insert_edge_into_queue(), and Overlay::is_queue_empty().
 { return h.pane()->marked( h); }
void HDS_accessor::set_inode (const Node & v, INode * i) const inline
Definition at line 76 of file HDS_accessor.h.
References Node::is_primary(), Node::pane(), and RFC_assertion.
Referenced by Overlay::insert_node_in_blue_edge(), and Overlay::project_adjacent_green_vertices().
   { RFC_assertion( v.is_primary()); v.pane()->set_inode(v,i); }
void HDS_accessor::unmark (const HEdge & h) const inline
Definition at line 71 of file HDS_accessor.h.
References HEdge::pane(), and RFC_Pane_overlay::unmark().
Referenced by Overlay::get_green_parent().
 { h.pane()->unmark( h); }
The documentation for this class was generated from the following file:
HDS_accessor.h