IMPACT: COM::ParallelTestingObject< CommType, ResultsType > Class Template Reference
COM::ParallelTestingObject< CommType, ResultsType > Class Template Reference
Project-specific parallel testing object.
Detailed Description
template<typename CommType, typename ResultsType>
class COM::ParallelTestingObject< CommType, ResultsType >
The project-specific parallel testing object encapsulates all parallel tests for the project. This is the interface to all "in-core" parallel testing available for the given project. It implements the interface given by COM::TestingObject and has an IRAD::Comm::CommunicatorObject for parallel capabilities.
Definition at line 1651 of file COMTest.H.
#include <COMTest.H>
Public Member Functions
ParallelTestingObject (CommType &incomm)
Constructor with incoming communicator.
CommType & GetCommunicator ()
virtual void Epilogue ()
Tears down the testing fixtures if needed.
virtual void Prologue ()
Sets up the data fixtures for the tests.
virtual void Test__WindowGetSetCommunicator (ResultsType &result)
Test for get and set communicator functions.
virtual void Test__GetSetCommunicator (ResultsType &result)
Test for get and set communicator functions.
virtual void Test__ModuleGetSetCommunicator (ResultsType &result)
virtual void Test__ParallelModuleLoadingTest (ResultsType &result)
Parallel Module management tests.
virtual void Test__FunctionBarrierTest (ResultsType &result)
Parallel function call with barrier test.
virtual void Process (ResultsType &result)
Runs all tests implemented by the COM::ParallelTestingObject.
virtual void RunTest (const std::string &name, ResultsType &result)
Runs a test specified by name.
virtual void ProcessTests (std::list< std::string > &test_names, ResultsType &result)
Runs a list of tests specified by name.
Public Member Functions inherited from COM::TestingObject< ResultsType >
TestingObject ()
Some solver objects to hold testing data.
double F1 (double x)
Simple test function fixture returns .
double F2 (double x)
Simple test function fixture returns .
void ResetSolution (std::vector< double > &solution, double value=-1)
double GetRelativeDiff (double A, double B, double epsilon)
void GetErrors (std::vector< double > &solution1, std::vector< double > &solution2, std::vector< double > &errors)
bool TwoSolutionsMatch (std::vector< double > &solution1, std::vector< double > &solution2, double tol=1e-5)
void CompareSolutionsWithDetail (std::vector< double > &solution1, std::vector< double > &solution2, std::ostream &outStream, double tol=1e-5)
void MakeWindow (std::string name)
virtual void Test__LinearDataTransfer (ResultsType &result)
virtual void Test__QuadraticDataTransfer (ResultsType &result)
virtual void Test__DataItemManagement (ResultsType &result)
Test for COM_LOAD_MODULE_STATIC_DYNAMIC and COM_UNLOAD_MODULE_STATIC_DYNAMIC.
virtual void Test__LoadUnloadMemTest (ResultsType &result)
virtual void Test__ModuleLoadingTest (ResultsType &result)
Module management tests.
virtual void Test__GetModules (ResultsType &results)
Test for COM_get_modules.
virtual void Test__ModuleFunctionTest (ResultsType &result)
Test for Module function registration and access.
Public Member Functions inherited from IRAD::Util::TestingObject< ResultsType >
virtual ~TestingObject ()
Protected Attributes
CommType _communicator
The CommunicatorObject for the parallel testing object.
std::vector< int > N
A set of values for testing quadrature methods.
Protected Attributes inherited from COM::TestingObject< ResultsType >
std::string ExampleTestFixture
A sample string test fixture.
std::vector< int > N
A set of values for testing quadrature methods.
Constructor & Destructor Documentation
template<typename CommType, typename ResultsType> COM::ParallelTestingObject< CommType, ResultsType >::ParallelTestingObject (CommType & incomm) inline
Definition at line 1668 of file COMTest.H.
                                             :
       TestingObject<ResultsType>(), _communicator(incomm) {};
Member Function Documentation
template<typename CommType, typename ResultsType> virtual void COM::ParallelTestingObject< CommType, ResultsType >::Epilogue () inline virtual
Reimplemented from COM::TestingObject< ResultsType >.
Definition at line 1675 of file COMTest.H.
Referenced by COM::ParallelTestingObject< CommType, ResultsType >::Process(), and COM::ParallelTestingObject< CommType, ResultsType >::ProcessTests().
 {};
template<typename CommType, typename ResultsType> CommType& COM::ParallelTestingObject< CommType, ResultsType >::GetCommunicator () inline
Definition at line 1670 of file COMTest.H.
References COM::ParallelTestingObject< CommType, ResultsType >::_communicator.
 { return(_communicator); };
template<typename CommType, typename ResultsType> virtual void COM::ParallelTestingObject< CommType, ResultsType >::Process (ResultsType & result) inline virtual
Parameters
result COM::TestResults object to store test results.
Reimplemented from COM::TestingObject< ResultsType >.
Definition at line 2354 of file COMTest.H.
References COM::ParallelTestingObject< CommType, ResultsType >::Epilogue(), COM::ParallelTestingObject< CommType, ResultsType >::Prologue(), COM::ParallelTestingObject< CommType, ResultsType >::Test__FunctionBarrierTest(), COM::ParallelTestingObject< CommType, ResultsType >::Test__GetSetCommunicator(), COM::ParallelTestingObject< CommType, ResultsType >::Test__ModuleGetSetCommunicator(), COM::ParallelTestingObject< CommType, ResultsType >::Test__ParallelModuleLoadingTest(), and COM::ParallelTestingObject< CommType, ResultsType >::Test__WindowGetSetCommunicator().
Referenced by COM::ParallelTest().
{
       Prologue();
       Test__GetSetCommunicator(result);
       Test__ParallelModuleLoadingTest(result);
       Test__FunctionBarrierTest(result);
       Test__WindowGetSetCommunicator(result);
       Test__ModuleGetSetCommunicator(result);
       Epilogue();
     }
template<typename CommType, typename ResultsType> virtual void COM::ParallelTestingObject< CommType, ResultsType >::ProcessTests (std::list< std::string > & test_names, ResultsType & result) inline virtual
Parameters
test_names list of string test names
result COM::TestResults object to store test results.
Reimplemented from COM::TestingObject< ResultsType >.
Definition at line 2390 of file COMTest.H.
References COM::ParallelTestingObject< CommType, ResultsType >::Epilogue(), COM::ParallelTestingObject< CommType, ResultsType >::Prologue(), and COM::ParallelTestingObject< CommType, ResultsType >::RunTest().
{
       Prologue();
       std::list<std::string>::iterator tni = test_names.begin();
       while(tni != test_names.end())
         RunTest(*tni++,result);
       Epilogue();
     }
template<typename CommType, typename ResultsType> virtual void COM::ParallelTestingObject< CommType, ResultsType >::Prologue () inline virtual
This function gives the object a chance to allocate and set up any "fixtures" before the tests are run.
Reimplemented from COM::TestingObject< ResultsType >.
Definition at line 1684 of file COMTest.H.
References COM::ParallelTestingObject< CommType, ResultsType >::_communicator, COM::ParallelTestingObject< CommType, ResultsType >::N, and IRAD::Comm::CommunicatorObject::Size().
Referenced by COM::ParallelTestingObject< CommType, ResultsType >::Process(), and COM::ParallelTestingObject< CommType, ResultsType >::ProcessTests().
{
       for(int i = _communicator.Size();i <= 1000000;i*=2) N.push_back(i);
     };
template<typename CommType, typename ResultsType> virtual void COM::ParallelTestingObject< CommType, ResultsType >::RunTest (const std::string & name, ResultsType & result) inline virtual
Parameters
name String name of the test to run.
result COM::TestResults object to store test results.
Reimplemented from COM::TestingObject< ResultsType >.
Definition at line 2370 of file COMTest.H.
References COM::ParallelTestingObject< CommType, ResultsType >::Test__FunctionBarrierTest(), COM::ParallelTestingObject< CommType, ResultsType >::Test__GetSetCommunicator(), COM::ParallelTestingObject< CommType, ResultsType >::Test__ModuleGetSetCommunicator(), COM::ParallelTestingObject< CommType, ResultsType >::Test__ParallelModuleLoadingTest(), and COM::ParallelTestingObject< CommType, ResultsType >::Test__WindowGetSetCommunicator().
Referenced by COM::ParallelTest(), and COM::ParallelTestingObject< CommType, ResultsType >::ProcessTests().
     {
       if(name == "GetSetCommunicatorTest")
         Test__GetSetCommunicator(result);
       if(name == "ParallelModuleLoadingTest")
         Test__ParallelModuleLoadingTest(result);
       if(name == "FunctionBarrierTest")
         Test__FunctionBarrierTest(result);
       if(name == "WindowGetSetCommunicator")
          Test__WindowGetSetCommunicator(result);
       if(name == "ModuleGetSetCommunicator")
          Test__ModuleGetSetCommunicator(result);
     }
template<typename CommType, typename ResultsType> virtual void COM::ParallelTestingObject< CommType, ResultsType >::Test__FunctionBarrierTest (ResultsType & result) inline virtual
Parameters
result COM::TestResults object to store test results.
This function implements a test designed to call a function in parallel and verify that the barrier after the function call worked. It uses the testing module COMTESTMOD which is written in C++.
Definition at line 2278 of file COMTest.H.
References IRAD::Comm::CommunicatorObject::Barrier(), COM_call_function(), COM_get_function_handle(), COM_get_window_handle(), COM_LOAD_MODULE_STATIC_DYNAMIC, COM_set_default_communicator(), COM_UNLOAD_MODULE_STATIC_DYNAMIC, and IRAD::Comm::CommunicatorObject::Size().
Referenced by COM::ParallelTestingObject< CommType, ResultsType >::Process(), and COM::ParallelTestingObject< CommType, ResultsType >::RunTest().
{
       bool barrier_works = false;
       MPI_Comm comm;
       int rank;
       comm = MPI_COMM_WORLD;
       CommType communicator(comm);
       int size = communicator.Size();
       int h, sleep_handle, b;
       time_t t1, t2;
       std::string outfile_name;
       std::ofstream outfile;
       std::stringstream ss;
       std::string str_rank;
       //making output files for each processor for debugging
       MPI_Comm_rank(MPI_COMM_WORLD, &rank);
       ss << rank;
       ss >> str_rank;
       outfile_name = "testbarrier" + str_rank + ".dat";
       outfile.open(outfile_name.c_str());
       if(rank == 0)
         std::cout << "Running Test__FunctionBarrierTest" << std::endl;
       //JK 4/14/16: The set_default is needed now that we removed the forcing
       // of windows to load onto only MPI_COMM_SELF
       COM_set_default_communicator(MPI_COMM_SELF);
       // Load the module
       COM_LOAD_MODULE_STATIC_DYNAMIC( COMTESTMOD, "TestParallelWin1");
       COM_set_default_communicator(MPI_COMM_WORLD);
       //JK 4/14/16: End
       // See if the module window exists
       h=COM_get_window_handle("TestParallelWin1");
       // If the window exists see if the function exists
       if(h > 0)
         sleep_handle = COM_get_function_handle("TestParallelWin1.SleepMultiply");
       // get the current time
       t1 = time(0);
       // if the function exists, call it
       if(sleep_handle > 0)
         COM_call_function(sleep_handle, &rank);
       //get current time
       t2 = time(0);
       outfile << "Time to call function and return = " << t2 - t1 << std::endl;
       // barrier function to force all processes to wait
       b = communicator.Barrier();
       //get current time
       t2 = time(0);
       outfile << "Time to call function and return and wait  = " << t2 - t1 << std::endl;
       // check that it took all the procceses the same amount of time
       double difft = (double)(t2 - t1);
       if(((size - 1) - difft) < 1.0e-3)
         barrier_works = true;
       // Unload the module
       COM_UNLOAD_MODULE_STATIC_DYNAMIC( COMTESTMOD, "TestParallelWin1");
       if(rank == 0)
         std::cout << "End of Test__FunctionBarrierTest" << std::endl;
       result.UpdateResult("COM::FunctionBarrierTest:Runs", true);
       result.UpdateResult("COM::FunctionBarrierTest:Works", barrier_works);
     }
template<typename CommType, typename ResultsType> virtual void COM::ParallelTestingObject< CommType, ResultsType >::Test__GetSetCommunicator (ResultsType & result) inline virtual
Parameters
result COM::TestResults object to store test results.
This function tests calling the functions COM_get_communicator, COM_get_default_communicator, COM_set_communicator, and COM_set_default_communicator with different contexts and window settings. It is only run when an MPI compiler is present.
Definition at line 1892 of file COMTest.H.
References COM::ParallelTestingObject< CommType, ResultsType >::_communicator, IRAD::Comm::CommunicatorObject::Check(), IRAD::Comm::CommunicatorObject::ClearErr(), COM_delete_window(), COM_get_communicator(), COM_get_default_communicator(), COM_new_window(), COM_set_default_communicator(), IRAD::Comm::CommunicatorObject::GetCommunicator(), IRAD::Comm::CommunicatorObject::SetErr(), IRAD::Comm::CommunicatorObject::Size(), and IRAD::Comm::CommunicatorObject::Split().
Referenced by COM::ParallelTestingObject< CommType, ResultsType >::Process(), and COM::ParallelTestingObject< CommType, ResultsType >::RunTest().
{
       MPI_Comm comm, default_comm;
       int rank, size;
       MPI_Comm fail_comm;
       bool getdefaultcommunicator = true;
       bool setdefaultcommunicator = true;
       bool getcommunicator = true;
       bool getwindowcommunicator = true;
       std::string outfile_name;
       std::ofstream outfile;
       std::stringstream ss;
       std::string str_rank;
       MPI_Comm_rank(MPI_COMM_WORLD, &rank);
       ss << rank;
       ss >> str_rank;
       outfile_name = "testout" + str_rank + ".dat";
       outfile.open(outfile_name.c_str());
       // Test for COM_get_default_communicator
       // when no default has been set
       default_comm = COM_get_default_communicator();
       if(default_comm != MPI_COMM_WORLD){
         _communicator.SetErr(1);
         std::cout << "COM_get_default_communicator fails on initial calling line 1308" << std::endl;
       }
       if(_communicator.Check()){
         getdefaultcommunicator = false;
       }
       _communicator.ClearErr();
       // Test for COM_get_communicator
       // when the window was initialized with no communicator
       COM_new_window("testparallelwindow");
       COM_get_communicator("testparallelwindow", &comm);
       if(comm != default_comm){
         _communicator.SetErr(1);
         std::cout << "COM_get_communicator does not return default communicator!"
                   << " (window initialized with no communicator)" << std::endl;
       }
       if(_communicator.Check()){
         getcommunicator = false;
       }
       _communicator.ClearErr();
       COM_delete_window("testparallelwindow");
       // Test for COM_get_communicator
       // when the window was initialized with MPI_COMM_SELF
       COM_new_window("testparallelwindow",MPI_COMM_SELF);
       COM_get_communicator("testparallelwindow", &comm);
       if(comm != MPI_COMM_SELF){
         _communicator.SetErr(1);
         std::cout << "COM_get_communicator does not return communicator used"
                   << " in window initialization!" << std::endl;
       }
       if(_communicator.Check()){
         getcommunicator = false;
       }
       _communicator.ClearErr();
       COM_delete_window("testparallelwindow");
       // Test for COM_set_default_communicator
       // and COM_get_default_communicator
       // when the default has been set to MPI_COMM_SELF
       // also checking COM_get_communicator after the default is set
       COM_set_default_communicator(MPI_COMM_SELF);
       default_comm = COM_get_default_communicator();
       if(default_comm != MPI_COMM_SELF){
         _communicator.SetErr(1);
         std::cout << "COM_get_default_communicator does not return the communicator"
                   << " used by set_default_communicator!" << std::endl;
       }
       COM_new_window("testparallelwindow");
       COM_get_communicator("testparallelwindow", &comm);
       if(comm != default_comm){
         _communicator.SetErr(1);
         std::cout << "COM_get_communicator does not return the communicator"
                   << " used by set_default_communicator! (a window intialized"
                   << " with no communicator should have the default)" << std::endl;
       }
       if(_communicator.Check()){
         setdefaultcommunicator = false;
       }
       _communicator.ClearErr();
       COM_delete_window("testparallelwindow");
       // Test for get and set communicator functions
       // after using the Split function
       bool getsplitcommunicator = true;
       MPI_Comm comm_check;
       comm = MPI_COMM_WORLD;
       CommType communicator(comm);
       CommType newcommunicator;
       size = communicator.Size();
       outfile << "communicator.Size() = " << communicator.Size() << std::endl;
       int color;
       if(rank < size/2) color=0;
       else color=1;
       communicator.Split(color, rank, newcommunicator);
       outfile << "communicator.Size() = " << communicator.Size() << std::endl;
       outfile << "newcommunicator.Size() = " << newcommunicator.Size() << std::endl;
       MPI_Comm newcomm = newcommunicator.GetCommunicator();
       COM_set_default_communicator(newcomm);
       if(rank == 0 || rank == 1){
         COM_new_window("testparallelwindow");
         COM_get_communicator("testparallelwindow", &comm_check);
         if(comm_check != newcomm){
           std::cout << "COM_get_communicator does not return the newly"
                     << " split communicator that was set as the default!" << std::endl;
           _communicator.SetErr(1);
         }
         COM_delete_window("testparallelwindow");
       }
       if(_communicator.Check()){
         getsplitcommunicator = false;
       }
       _communicator.ClearErr();
       std::cout << "getdefaultcommunicator = " << getdefaultcommunicator << std::endl;
       result.UpdateResult("COM::GetDefaultCommunicator:Runs", true);
       result.UpdateResult("COM::SetDefaultCommunicator:Runs", true);
       result.UpdateResult("COM::GetCommunicator:Runs", true);
       result.UpdateResult("COM::GetDefaultCommunicator:Works", getdefaultcommunicator);
       result.UpdateResult("COM::SetDefaultCommunicator:Works", setdefaultcommunicator);
       result.UpdateResult("COM::GetCommunicator:Works", getcommunicator);
       result.UpdateResult("COM::GetSplitCommunicator:Works", getsplitcommunicator);
       COM_set_default_communicator(MPI_COMM_WORLD);
       outfile.close();
     };
template<typename CommType, typename ResultsType> virtual void COM::ParallelTestingObject< CommType, ResultsType >::Test__ModuleGetSetCommunicator (ResultsType & result) inline virtual
Definition at line 2065 of file COMTest.H.
References COM_call_function(), COM_get_function_handle(), COM_get_window_handle(), COM_LOAD_MODULE_STATIC_DYNAMIC, COM_set_default_communicator(), and COM_UNLOAD_MODULE_STATIC_DYNAMIC.
Referenced by COM::ParallelTestingObject< CommType, ResultsType >::Process(), and COM::ParallelTestingObject< CommType, ResultsType >::RunTest().
{
       int commworksnew = 1;
       MPI_Comm comm, default_comm;
       int rank, size;
       MPI_Comm fail_comm;
       int funchand, h;
       const char *name = "TestParallelWin1";
       bool getcommunicator = true;
       std::string outfile_name;
       std::ofstream outfile;
       std::stringstream ss;
       std::string str_rank;
       MPI_Comm_rank(MPI_COMM_WORLD, &rank);
       ss << rank;
       ss >> str_rank;
       outfile_name = "Getsetcommout" + str_rank + ".dat";
       outfile.open(outfile_name.c_str());
       //JK 4/14/16: The set_default is needed now that we removed the forcing
       // of windows to load onto only MPI_COMM_SELF
       COM_set_default_communicator(MPI_COMM_SELF);
       COM_LOAD_MODULE_STATIC_DYNAMIC( COMTESTMOD, "TestParallelWin1");
       COM_set_default_communicator(MPI_COMM_WORLD);
       //JK 4/14/16: End
       h=COM_get_window_handle("TestParallelWin1");
       if(h > 0)
          funchand= COM_get_function_handle("TestParallelWin1.get_communicator_module");
       if( funchand > 0)
         COM_call_function(funchand, &commworksnew);
       if (commworksnew == 0)
          getcommunicator = false;
        result.UpdateResult("COM::GetCommunicatorModule:Works", getcommunicator);
        COM_UNLOAD_MODULE_STATIC_DYNAMIC( COMTESTMOD, "TestParallelWin1");
     };
template<typename CommType, typename ResultsType> virtual void COM::ParallelTestingObject< CommType, ResultsType >::Test__ParallelModuleLoadingTest (ResultsType & result) inline virtual
Parameters
result COM::TestResults object to store test results.
This function implements several paralle module management tests designed to put module loading, unloading, and management through their paces. It uses the testing module COMTESTMOD which is written in C++.
Load the module on all processes call Increment on root & then broadcast
Definition at line 2116 of file COMTest.H.
References COM::ParallelTestingObject< CommType, ResultsType >::_communicator, IRAD::Comm::CommunicatorObject::AllGather(), IRAD::Comm::CommunicatorObject::BroadCast(), IRAD::Comm::CommunicatorObject::Check(), IRAD::Comm::CommunicatorObject::ClearErr(), COM_call_function(), COM_get_communicator(), COM_get_function_handle(), COM_get_window_handle(), COM_LOAD_MODULE_STATIC_DYNAMIC, COM_set_default_communicator(), COM_UNLOAD_MODULE_STATIC_DYNAMIC, IRAD::Comm::CommunicatorObject::GetCommunicator(), IRAD::Comm::CommunicatorObject::SetErr(), IRAD::Comm::CommunicatorObject::Size(), and IRAD::Comm::CommunicatorObject::Split().
Referenced by COM::ParallelTestingObject< CommType, ResultsType >::Process(), and COM::ParallelTestingObject< CommType, ResultsType >::RunTest().
{
       MPI_Comm comm, default_comm;
       int rank;
       MPI_Comm comm_check;
       comm = MPI_COMM_WORLD;
       CommType communicator(comm);
       CommType newcommunicator;
       int size = communicator.Size();
       bool c_window_gone=true;
       bool c_load_module_works=true;
       bool getsplitcommunicator=true;
       int h;
       std::string outfile_name;
       std::ofstream outfile;
       std::stringstream ss;
       std::string str_rank;
       MPI_Comm_rank(MPI_COMM_WORLD, &rank);
       ss << rank;
       ss >> str_rank;
       outfile_name = "testloading" + str_rank + ".dat";
       outfile.open(outfile_name.c_str());
       if(rank == 0)
         std::cout << "Running Test__ParallelModuleLoadingTest" << std::endl;
       outfile << "Running COM::ParallelTestingObject::Test__ParallelModuleLoadingTest" << std::endl;
       // Split the communicator so we can test which communicator the
       // module is loaded on
       int color;
       if(rank < size/2) color=0;
       else color=1;
       communicator.Split(color, rank, newcommunicator);
       outfile << "communicator.Size() = " << communicator.Size() << std::endl;
       outfile << "newcommunicator.Size() = " << newcommunicator.Size() << std::endl;
       MPI_Comm newcomm = newcommunicator.GetCommunicator();
       COM_set_default_communicator(newcomm);
       if(color == 0){
         // Load the module
         COM_LOAD_MODULE_STATIC_DYNAMIC( COMTESTMOD, "TestParallelWin1");
         // See if the module window exists
         h=COM_get_window_handle("TestParallelWin1");
         if(h <= 0) {
           outfile << "COM_get_window_handle(\"TestParallelWin1\") returns " << h << std::endl;
           _communicator.SetErr(1);
         }
       }
       if(_communicator.Check()){
         c_load_module_works=false;
       }
       _communicator.ClearErr();
       if(color == 0){
         COM_get_communicator("TestParallelWin1", &comm_check);
         if(comm_check != newcomm){
           std::cout << "COM_get_communicator does not return the newly"
                     << " split communicator that was set as the default!" << std::endl;
           _communicator.SetErr(1);
         }
       }
       if(_communicator.Check())
         getsplitcommunicator = false;
       _communicator.ClearErr();
       if(color == 0){
         // Unolad the module
         COM_UNLOAD_MODULE_STATIC_DYNAMIC( COMTESTMOD,"TestParallelWin1");
         // Check that the window no longer exists
         h=COM_get_window_handle("TestParallelWin1");
         if(h > 0) {
           outfile << "COM_get_window_handle(\"TestParallelWin1\") returns " << h << std::endl;
           _communicator.SetErr(1);
         }
       }
       if(_communicator.Check()){
         c_window_gone=false;
       }
       _communicator.ClearErr();
       int IncrementHandle;
       bool parallel_function_works = true;
       int number=0;
       // Load the module
       COM_LOAD_MODULE_STATIC_DYNAMIC( COMTESTMOD, "TestParallelWin1");
       // See if the module window exists
       h=COM_get_window_handle("TestParallelWin1");
       if(h > 0)
         IncrementHandle = COM_get_function_handle("TestParallelWin1.Increment");
       if(IncrementHandle > 0 && rank == 1)
         COM_call_function(IncrementHandle,&number,&rank);
       communicator.BroadCast(number,1);
       if(number != 1){
         std::cout << "Incrementing of number and then broadcasting did not work!" << std::endl;
         _communicator.SetErr(1);
       }
       if(_communicator.Check())
          parallel_function_works = false;
       _communicator.ClearErr();
       if(IncrementHandle > 0)
         COM_call_function(IncrementHandle,&number,&rank);
       int nproc = _communicator.Size();
       std::vector<int> numbers(nproc,0);
       int commstat = _communicator.AllGather(number,numbers);
       for(int i=0; i < nproc; i++){
         if(numbers[i] != i+1){
           std::cout << "AllGather of number into numbers did not get the correct values!" << std::endl;
           _communicator.SetErr(1);
         }
       }
       if(_communicator.Check())
         parallel_function_works = false;
       _communicator.ClearErr();
       // Unload the module
       COM_UNLOAD_MODULE_STATIC_DYNAMIC( COMTESTMOD, "TestParallelWin1");
       if(rank == 0){
         std::cout << "End of Test__ParallelModuleLoadingTest" << std::endl;
       }
       result.UpdateResult("COM::ParallelLoadModule:Works", c_load_module_works);
       result.UpdateResult("COM::ParallelUnloadModule:Works", c_window_gone);
       result.UpdateResult("COM::ParallelFunctionCall:Works", parallel_function_works);
       outfile.close();
       //reset the default communicator to MPI_COMM_WORLD
       COM_set_default_communicator(MPI_COMM_WORLD);
     }
template<typename CommType, typename ResultsType> virtual void COM::ParallelTestingObject< CommType, ResultsType >::Test__WindowGetSetCommunicator (ResultsType & result) inline virtual
Parameters
result COM::TestResults object to store test results.
This function tests calling the functions COM_get_communicator, COM_get_default_communicator, COM_set_communicator, and COM_set_default_communicator with different contexts and window settings. It is only run when an MPI compiler is present.
Definition at line 1701 of file COMTest.H.
References COM::ParallelTestingObject< CommType, ResultsType >::_communicator, IRAD::Comm::CommunicatorObject::Check(), IRAD::Comm::CommunicatorObject::ClearErr(), COM_delete_window(), COM_get_com(), COM_get_default_communicator(), COM_get_window_handle(), COM_new_window(), COM_set_default_communicator(), ComponentInterface::get_communicator(), COM::COM_base::get_window_object(), IRAD::Comm::CommunicatorObject::GetCommunicator(), IRAD::Comm::CommunicatorObject::SetErr(), IRAD::Comm::CommunicatorObject::Size(), and IRAD::Comm::CommunicatorObject::Split().
Referenced by COM::ParallelTestingObject< CommType, ResultsType >::Process(), and COM::ParallelTestingObject< CommType, ResultsType >::RunTest().
{
       MPI_Comm comm, default_comm;
       int rank, size, h;
       MPI_Comm fail_comm;
       COM::COM_base * rbase = COM_get_com();
       COM::Window *param_window = NULL;
       bool getcommunicator = true;
       bool getdefaultcommunicator = true;
       bool setdefaultcommunicator = true;
       bool getwindowcommunicator = true;
       bool getsplitcommunicator = true;
       bool getsplitwindowcommunicator = true;
       std::string outfile_name;
       std::ofstream outfile;
       std::stringstream ss;
       std::string str_rank;
       MPI_Comm_rank(MPI_COMM_WORLD, &rank);
       ss << rank;
       ss >> str_rank;
       outfile_name = "testout" + str_rank + ".dat";
       outfile.open(outfile_name.c_str());
       // Test for COM_get_default_communicator
       // when no default has been set
       default_comm = COM_get_default_communicator();
       if(default_comm != MPI_COMM_WORLD){
         _communicator.SetErr(1);
         std::cout << "COM_get_default_communicator fails on initial calling line 1123" << std::endl;
       }
       if(_communicator.Check()){
         getdefaultcommunicator = false;
       }
       _communicator.ClearErr();
       // Test for window:get_communicator
       // when the window was initialized with no communicator
       COM_new_window("testparallelwindow");
       h = COM_get_window_handle("testparallelwindow");
       if(h > 0)
         param_window = rbase->get_window_object(h);
       comm = param_window->get_communicator();
       if(comm != default_comm){
         _communicator.SetErr(1);
         std::cout << "window::get_communicator does not return default communicator!"
                   << " (window initialized with no communicator)" << std::endl;
       }
       if(_communicator.Check()){
         getwindowcommunicator = false;
       }
       _communicator.ClearErr();
       COM_delete_window("testparallelwindow");
       // Test for window:get_communicator
       // when the window was initialized with MPI_COMM_SELF
       COM_new_window("testparallelwindow",MPI_COMM_SELF);
       h = COM_get_window_handle("testparallelwindow");
       if(h > 0)
         param_window = rbase->get_window_object(h);
       comm = param_window->get_communicator();
       if(comm != MPI_COMM_SELF){
         _communicator.SetErr(1);
         std::cout << "window::get_communicator does not return communicator used"
                   << " in window initialization!" << std::endl;
       }
       if(_communicator.Check()){
         getwindowcommunicator = false;
       }
       _communicator.ClearErr();
       COM_delete_window("testparallelwindow");
       // Test for COM_set_default_communicator
       // and COM_get_default_communicator
       // when the default has been set to MPI_COMM_SELF
       // also checking get_communicator after the default is set
       COM_set_default_communicator(MPI_COMM_SELF);
       default_comm = COM_get_default_communicator();
       if(default_comm != MPI_COMM_SELF){
         _communicator.SetErr(1);
         std::cout << "COM_get_default_communicator does not return the communicator"
                   << " used by set_default_communicator!" << std::endl;
       }
       COM_new_window("testparallelwindow");
       h = COM_get_window_handle("testparallelwindow");
       if(h > 0)
         param_window = rbase->get_window_object(h);
       comm = param_window->get_communicator();
       if(comm != default_comm){
         _communicator.SetErr(1);
         std::cout << "window::get_communicator does not return the communicator"
                   << " used by set_default_communicator! (a window intialized"
                   << " with no communicator should have the default)" << std::endl;
       }
       if(_communicator.Check()){
         getwindowcommunicator = false;
       }
       _communicator.ClearErr();
       COM_delete_window("testparallelwindow");
       // Test for get and set communicator functions
       // after using the Split function
       MPI_Comm comm_check;
       comm = MPI_COMM_WORLD;
       CommType communicator(comm);
       CommType newcommunicator;
       size = communicator.Size();
       outfile << "communicator.Size() = " << communicator.Size() << std::endl;
       int color;
       if(rank < size/2) color=0;
       else color=1;
       communicator.Split(color, rank, newcommunicator);
       outfile << "communicator.Size() = " << communicator.Size() << std::endl;
       outfile << "newcommunicator.Size() = " << newcommunicator.Size() << std::endl;
       MPI_Comm newcomm = newcommunicator.GetCommunicator();
       COM_set_default_communicator(newcomm);
       if(rank == 0 || rank == 1){
         COM_new_window("testparallelwindow");
         h = COM_get_window_handle("testparallelwindow");
         if(h > 0)
         param_window = rbase->get_window_object(h);
         comm = param_window->get_communicator();
         if(comm_check != newcomm){
           std::cout << "window::get_communicator does not return the newly"
                     << " split communicator that was set as the default!" << std::endl;
           _communicator.SetErr(1);
         }
         COM_delete_window("testparallelwindow");
       }
       if(_communicator.Check()){
         getsplitcommunicator = false;
       }
       _communicator.ClearErr();
       result.UpdateResult("COM::WindowGetCommunicator:Runs", true);
       result.UpdateResult("COM::WindowGetCommunicator:Works", getwindowcommunicator);
       result.UpdateResult("COM::WindowGetSplitCommunicator:Works", getsplitwindowcommunicator);
       COM_set_default_communicator(MPI_COMM_WORLD);
       outfile.close();
     };
Member Data Documentation
template<typename CommType, typename ResultsType> CommType COM::ParallelTestingObject< CommType, ResultsType >::_communicator protected
Definition at line 1659 of file COMTest.H.
Referenced by COM::ParallelTestingObject< CommType, ResultsType >::GetCommunicator(), COM::ParallelTestingObject< CommType, ResultsType >::Prologue(), COM::ParallelTestingObject< CommType, ResultsType >::Test__GetSetCommunicator(), COM::ParallelTestingObject< CommType, ResultsType >::Test__ParallelModuleLoadingTest(), and COM::ParallelTestingObject< CommType, ResultsType >::Test__WindowGetSetCommunicator().
template<typename CommType, typename ResultsType> std::vector<int> COM::ParallelTestingObject< CommType, ResultsType >::N protected
Definition at line 1663 of file COMTest.H.
Referenced by COM::ParallelTestingObject< CommType, ResultsType >::Prologue().
The documentation for this class was generated from the following file:
COMTest.H