IMPACT: SolverUtils::GeoPrim::C3Vector Class Reference
SolverUtils::GeoPrim::C3Vector Class Reference
/brief Cartesian 3 Vector
Detailed Description
Definition at line 777 of file GeoPrimitives.H.
#include <GeoPrimitives.H>
Public Member Functions
C3Vector ()
C3Vector (const GeoPrim::CVector &inv)
C3Vector (const CPoint &inp)
C3Vector (const C3Point &inp)
C3Vector (double ix, double iy, double iz=0.0)
C3Vector (const C3Point &p1, const C3Point &p2)
C3Vector (double *a)
C3Vector (const double *a)
C3Vector (const C3Vector &v)
~C3Vector ()
C3Vector & Copy (const C3Vector &v)
C3Vector & Init (const double *a)
C3Vector & Init (const C3Vector &v)
C3Vector & Init (double ix, double iy, double iz)
C3Vector & Init (const C3Vector &p1, const C3Vector &p2)
C3Vector & Init ()
C3Vector & Clear ()
double Norm () const
double Mag () const
double Mag2 () const
C3Vector & Normalize ()
C3Vector Unit () const
double operator* (const C3Vector &v2) const
Dot Product.
C3Vector operator* (double num) const
Scaling.
C3Vector & operator*= (double num)
C3Vector operator% (const C3Vector &v2) const
Cross Product.
C3Vector & operator= (const C3Vector &v2)
C3Vector & operator%= (const C3Vector &v2)
C3Vector operator+ (const C3Vector &v2) const
C3Vector operator- (const C3Vector &v2) const
C3Vector & operator+= (const C3Vector &v2)
C3Vector & operator-= (const C3Vector &v2)
double & x ()
double x () const
C3Vector & x (double i)
double & y ()
double y () const
C3Vector & y (double i)
double & z ()
double z () const
C3Vector & z (double i)
const double & operator[] (unsigned int i) const
double & operator[] (unsigned int i)
bool operator== (const C3Vector &v) const
bool operator< (const C3Vector &v) const
bool operator> (const C3Vector &v) const
bool operator<= (const C3Vector &v) const
bool operator>= (const C3Vector &v) const
void DestroyData ()
void SetData (double *d)
double * Data ()
const double * Data () const
Protected Attributes
double * V
Private Member Functions
void _create ()
void _destroy ()
Private Attributes
bool _mydata
Friends
C3Vector operator* (double, const C3Vector &)
std::ostream & operator<< (std::ostream &, const C3Vector &)
std::istream & operator>> (std::istream &, C3Vector &)
Constructor & Destructor Documentation
SolverUtils::GeoPrim::C3Vector::C3Vector () inline
Definition at line 786 of file GeoPrimitives.H.
References _create(), and V.
     {
       _create();
       V[0] = V[1] = V[2] = 0.;
     };
SolverUtils::GeoPrim::C3Vector::C3Vector (const GeoPrim::CVector & inv) inline
Definition at line 791 of file GeoPrimitives.H.
References _create(), V, SolverUtils::GeoPrim::CVector::x(), SolverUtils::GeoPrim::CVector::y(), and SolverUtils::GeoPrim::CVector::z().
     {
       _create();
       V[0] = inv.x();
       V[1] = inv.y();
       V[2] = inv.z();
     };
SolverUtils::GeoPrim::C3Vector::C3Vector (const CPoint & inp) inline
Definition at line 798 of file GeoPrimitives.H.
References _create(), V, SolverUtils::GeoPrim::CPoint::x(), SolverUtils::GeoPrim::CPoint::y(), and SolverUtils::GeoPrim::CPoint::z().
     {
       _create();
       V[0] = inp.x();
       V[1] = inp.y();
       V[2] = inp.z();
     };
SolverUtils::GeoPrim::C3Vector::C3Vector (const C3Point & inp) inline
Definition at line 805 of file GeoPrimitives.H.
References _create(), V, SolverUtils::GeoPrim::C3Point::x(), SolverUtils::GeoPrim::C3Point::y(), and SolverUtils::GeoPrim::C3Point::z().
     {
       _create();
       V[0] = inp.x();
       V[1] = inp.y();
       V[2] = inp.z();
     };
SolverUtils::GeoPrim::C3Vector::C3Vector (double ix, double iy, double iz = 0.0) inline
Definition at line 812 of file GeoPrimitives.H.
References _create(), and V.
     {
       _create();
       V[0] = ix;
       V[1] = iy;
       V[2] = iz;
     };
SolverUtils::GeoPrim::C3Vector::C3Vector (const C3Point & p1, const C3Point & p2) inline
Definition at line 819 of file GeoPrimitives.H.
References _create(), and Copy().
     {
       _create();
       Copy(p2-p1);
     };
SolverUtils::GeoPrim::C3Vector::C3Vector (double * a) inline
Definition at line 824 of file GeoPrimitives.H.
References _mydata, and V.
     {
       _mydata = false;
       V = a;
     };
SolverUtils::GeoPrim::C3Vector::C3Vector (const double * a) inline
Definition at line 829 of file GeoPrimitives.H.
References _create(), and V.
     {
       _create();
       V[0] = a[0];
       V[1] = a[1];
       V[2] = a[2];
     };
SolverUtils::GeoPrim::C3Vector::C3Vector (const C3Vector & v) inline
Definition at line 836 of file GeoPrimitives.H.
References _create(), and Copy().
     {
       _create();
       Copy(v);
     };
SolverUtils::GeoPrim::C3Vector::~C3Vector () inline
Definition at line 841 of file GeoPrimitives.H.
References _destroy().
     {
       _destroy();
     };
Member Function Documentation
void SolverUtils::GeoPrim::C3Vector::_create () inline private
Definition at line 1066 of file GeoPrimitives.H.
References _mydata, and V.
Referenced by C3Vector().
     {
       V = new double [3];
       _mydata = true;
     };
void SolverUtils::GeoPrim::C3Vector::_destroy () inline private
Definition at line 1071 of file GeoPrimitives.H.
References _mydata, and V.
Referenced by DestroyData(), and ~C3Vector().
     {
       if(_mydata){
         delete [] V;
         _mydata = false;
         V = NULL;
       }
     };
C3Vector& SolverUtils::GeoPrim::C3Vector::Clear () inline
Definition at line 883 of file GeoPrimitives.H.
References V.
     {
       V[0] = V[1] = V[2] = 0.0;
       return(*this);
     };
C3Vector& SolverUtils::GeoPrim::C3Vector::Copy (const C3Vector & v) inline
Definition at line 845 of file GeoPrimitives.H.
References V.
Referenced by C3Vector(), Init(), and operator=().
     {
       V[0] = v.V[0];
       V[1] = v.V[1];
       V[2] = v.V[2];
       return(*this);
     };
double* SolverUtils::GeoPrim::C3Vector::Data () inline
Definition at line 1063 of file GeoPrimitives.H.
References V.
 { return(V); };
const double* SolverUtils::GeoPrim::C3Vector::Data () const inline
Definition at line 1064 of file GeoPrimitives.H.
References V.
 { return(V); };
void SolverUtils::GeoPrim::C3Vector::DestroyData () inline
Definition at line 1058 of file GeoPrimitives.H.
References _destroy().
 { _destroy(); };
C3Vector& SolverUtils::GeoPrim::C3Vector::Init (const double * a) inline
Definition at line 852 of file GeoPrimitives.H.
References V.
     {
       V[0] = a[0];
       V[1] = a[1];
       V[2] = a[2];
       return(*this);
     };
C3Vector& SolverUtils::GeoPrim::C3Vector::Init (const C3Vector & v) inline
Definition at line 859 of file GeoPrimitives.H.
References V.
     {
       V[0] = v[0];
       V[1] = v[1];
       V[2] = v[2];
       return(*this);
     };
C3Vector& SolverUtils::GeoPrim::C3Vector::Init (double ix, double iy, double iz) inline
Definition at line 866 of file GeoPrimitives.H.
References V.
     {
       V[0] = ix;
       V[1] = iy;
       V[2] = iz;
       return(*this);
     };
C3Vector& SolverUtils::GeoPrim::C3Vector::Init (const C3Vector & p1, const C3Vector & p2) inline
Definition at line 873 of file GeoPrimitives.H.
References Copy().
     {
       Copy(p2 - p1);
       return(*this);
     };
C3Vector& SolverUtils::GeoPrim::C3Vector::Init () inline
Definition at line 878 of file GeoPrimitives.H.
References V.
     {
       V[0] = V[1] = V[2] = 0.0;
       return(*this);
     };
double SolverUtils::GeoPrim::C3Vector::Mag () const inline
Definition at line 892 of file GeoPrimitives.H.
References Norm().
Referenced by SolverUtils::GeoPrim::Distance().
     {
       return (Norm());
     };
double SolverUtils::GeoPrim::C3Vector::Mag2 () const inline
Definition at line 896 of file GeoPrimitives.H.
References V.
Referenced by SolverUtils::GeoPrim::Distance(), operator<(), and operator>().
     {
       return ((V[0]*V[0])+(V[1]*V[1])+(V[2]*V[2]));
     };
double SolverUtils::GeoPrim::C3Vector::Norm () const inline
Definition at line 888 of file GeoPrimitives.H.
References V.
Referenced by SolverUtils::GeoPrim::C3LineSegment::length(), Mag(), and Normalize().
     {
       return(sqrt((V[0] * V[0]) + (V[1] * V[1]) + (V[2] * V[2])));
     };
C3Vector& SolverUtils::GeoPrim::C3Vector::Normalize () inline
Definition at line 900 of file GeoPrimitives.H.
References Norm(), and V.
Referenced by SolverUtils::GeoPrim::C3Plane::C3Plane(), SolverUtils::GeoPrim::C3Line::has_point(), and Unit().
     {
       double n = Norm();
       V[0] /= n;
       V[1] /= n;
       V[2] /= n;
       return(*this);
     };
C3Vector SolverUtils::GeoPrim::C3Vector::operator% (const C3Vector & v2) const inline
Definition at line 940 of file GeoPrimitives.H.
References V.
     {
       C3Vector v;
       v.V[0] = ((v2.V[2] * V[1]) - (v2.V[1] * V[2]));
       v.V[1] = ((v2.V[0] * V[2]) - (v2.V[2] * V[0]));
       v.V[2] = ((v2.V[1] * V[0]) - (v2.V[0] * V[1]));
       return(v);
     };
C3Vector& SolverUtils::GeoPrim::C3Vector::operator%= (const C3Vector & v2) inline
Definition at line 952 of file GeoPrimitives.H.
References V.
     {
       double t0 = V[0];
       double t1 = V[1];
       double t2 = V[2];
       V[0] = ((v2.V[2] * t1) - (v2.V[1] * t2));
       V[1] = ((v2.V[0] * t2) - (v2.V[2] * t0));
       V[2] = ((v2.V[1] * t0) - (v2.V[0] * t1));
       return(*this);
     };
double SolverUtils::GeoPrim::C3Vector::operator* (const C3Vector & v2) const inline
Definition at line 916 of file GeoPrimitives.H.
References V.
     {
       return((V[0] * v2.V[0]) +
              (V[1] * v2.V[1]) +
              (V[2] * v2.V[2]));
     };
C3Vector SolverUtils::GeoPrim::C3Vector::operator* (double num) const inline
Definition at line 925 of file GeoPrimitives.H.
References V.
     {
       C3Vector rv(num*V[0],num*V[1],num*V[2]);
       return(rv);
     };
C3Vector& SolverUtils::GeoPrim::C3Vector::operator*= (double num) inline
Definition at line 930 of file GeoPrimitives.H.
References V.
     {
       V[0] *= num;
       V[1] *= num;
       V[2] *= num;
       return(*this);
     };
C3Vector SolverUtils::GeoPrim::C3Vector::operator+ (const C3Vector & v2) const inline
Definition at line 962 of file GeoPrimitives.H.
References V.
     {
       C3Vector v(V[0] + v2.V[0], V[1] + v2.V[1], V[2] + v2.V[2]);
       return(v);
     };
C3Vector& SolverUtils::GeoPrim::C3Vector::operator+= (const C3Vector & v2) inline
Definition at line 971 of file GeoPrimitives.H.
References V.
     {
       V[0] += v2.V[0];
       V[1] += v2.V[1];
       V[2] += v2.V[2];
       return(*this);
     };
C3Vector SolverUtils::GeoPrim::C3Vector::operator- (const C3Vector & v2) const inline
Definition at line 967 of file GeoPrimitives.H.
     {
       return((*this) + (-1.0 * v2));
     };
C3Vector& SolverUtils::GeoPrim::C3Vector::operator-= (const C3Vector & v2) inline
Definition at line 978 of file GeoPrimitives.H.
References V.
     {
       V[0] -= v2.V[0];
       V[1] -= v2.V[1];
       V[2] -= v2.V[2];
       return(*this);
     };
bool SolverUtils::GeoPrim::C3Vector::operator< (const C3Vector & v) const inline
Definition at line 1040 of file GeoPrimitives.H.
References Mag2().
     {
       return (Mag2() < v.Mag2());
     };
bool SolverUtils::GeoPrim::C3Vector::operator<= (const C3Vector & v) const inline
Definition at line 1048 of file GeoPrimitives.H.
     {
       return ( (*this < v) ||
                (*this == v));
     };
C3Vector& SolverUtils::GeoPrim::C3Vector::operator= (const C3Vector & v2) inline
Definition at line 948 of file GeoPrimitives.H.
References Copy().
     {
       return(Copy(v2));
     };
bool SolverUtils::GeoPrim::C3Vector::operator== (const C3Vector & v) const inline
Definition at line 1034 of file GeoPrimitives.H.
References SolverUtils::GeoPrim::TOL, and V.
     {
       return( (fabs(V[0] - v.V[0]) < TOL) &&
               (fabs(V[1] - v.V[1]) < TOL) &&
               (fabs(V[2] - v.V[2]) < TOL) );
     };
bool SolverUtils::GeoPrim::C3Vector::operator> (const C3Vector & v) const inline
Definition at line 1044 of file GeoPrimitives.H.
References Mag2().
     {
       return (Mag2() > v.Mag2());
     };
bool SolverUtils::GeoPrim::C3Vector::operator>= (const C3Vector & v) const inline
Definition at line 1053 of file GeoPrimitives.H.
     {
       return ( (*this > v) ||
                (*this == v) );
     };
const double& SolverUtils::GeoPrim::C3Vector::operator[] (unsigned int i) const inline
Definition at line 1024 of file GeoPrimitives.H.
References V.
     {
       assert(i>0 && i<4);
       return(V[i-1]);
     };
double& SolverUtils::GeoPrim::C3Vector::operator[] (unsigned int i) inline
Definition at line 1029 of file GeoPrimitives.H.
References V.
     {
       assert(i>0 && i<4);
       return(V[i-1]);
     };
void SolverUtils::GeoPrim::C3Vector::SetData (double * d) inline
Definition at line 1059 of file GeoPrimitives.H.
References _mydata, and V.
{
       V = d;
       _mydata = false;
     };
C3Vector SolverUtils::GeoPrim::C3Vector::Unit () const inline
Definition at line 908 of file GeoPrimitives.H.
References Normalize().
Referenced by SolverUtils::GeoPrim::C3Line::has_point(), and SolverUtils::GeoPrim::C3Plane::operator==().
     {
       C3Vector v(*this);
       return(v.Normalize());
     };
double& SolverUtils::GeoPrim::C3Vector::x () inline
Definition at line 985 of file GeoPrimitives.H.
References V.
Referenced by SolverUtils::GeoPrim::C3Plane::A(), SolverUtils::GeoPrim::C3Box::around(), SolverUtils::GeoPrim::C3Plane::C3Plane(), SolverUtils::GeoPrim::C3Plane::contains_point(), SolverUtils::GeoPrim::C3Plane::D(), SolverUtils::GeoPrim::Distance(), SolverUtils::GeoPrim::operator<<(), and SolverUtils::GeoPrim::C3Box::size().
     {
       return(V[0]);
     };
double SolverUtils::GeoPrim::C3Vector::x () const inline
Definition at line 989 of file GeoPrimitives.H.
References V.
     {
       return(V[0]);
     };
C3Vector& SolverUtils::GeoPrim::C3Vector::x (double i) inline
Definition at line 993 of file GeoPrimitives.H.
References V.
     {
       V[0] = i;
       return(*this);
     };
double& SolverUtils::GeoPrim::C3Vector::y () inline
Definition at line 998 of file GeoPrimitives.H.
References V.
Referenced by SolverUtils::GeoPrim::C3Box::around(), SolverUtils::GeoPrim::C3Plane::B(), SolverUtils::GeoPrim::C3Plane::contains_point(), SolverUtils::GeoPrim::C3Plane::D(), SolverUtils::GeoPrim::Distance(), SolverUtils::GeoPrim::operator<<(), and SolverUtils::GeoPrim::C3Box::size().
     {
       return(V[1]);
     };
double SolverUtils::GeoPrim::C3Vector::y () const inline
Definition at line 1002 of file GeoPrimitives.H.
References V.
     {
       return(V[1]);
     };
C3Vector& SolverUtils::GeoPrim::C3Vector::y (double i) inline
Definition at line 1006 of file GeoPrimitives.H.
References V.
     {
       V[1] = i;
       return(*this);
     };
double& SolverUtils::GeoPrim::C3Vector::z () inline
Definition at line 1011 of file GeoPrimitives.H.
References V.
Referenced by SolverUtils::GeoPrim::C3Box::around(), SolverUtils::GeoPrim::C3Plane::C(), SolverUtils::GeoPrim::C3Plane::contains_point(), SolverUtils::GeoPrim::C3Plane::D(), SolverUtils::GeoPrim::Distance(), SolverUtils::GeoPrim::operator<<(), and SolverUtils::GeoPrim::C3Box::size().
     {
       return(V[2]);
     };
double SolverUtils::GeoPrim::C3Vector::z () const inline
Definition at line 1015 of file GeoPrimitives.H.
References V.
     {
       return(V[2]);
     };
C3Vector& SolverUtils::GeoPrim::C3Vector::z (double i) inline
Definition at line 1019 of file GeoPrimitives.H.
References V.
     {
       V[2] = i;
       return(*this);
     };
Friends And Related Function Documentation
C3Vector operator* (double scalar, const C3Vector & v) friend
Definition at line 163 of file GeoPrimitives.C.
   {
     GeoPrim::C3Vector rv(v);
     return(rv *= scalar);
   }
std::ostream& operator<< (std::ostream & oS, const C3Vector & v) friend
Definition at line 132 of file GeoPrimitives.C.
   {
     oS << v.x() << "  " << v.y() << "  " << v.z();
     return(oS);
   }
std::istream& operator>> (std::istream & iS, GeoPrim::C3Vector & v) friend
Definition at line 139 of file GeoPrimitives.C.
   {
     iS >> v[0] >> v[1] >> v[2];
     return(iS);
   }
Member Data Documentation
bool SolverUtils::GeoPrim::C3Vector::_mydata private
Definition at line 782 of file GeoPrimitives.H.
Referenced by _create(), _destroy(), C3Vector(), and SetData().
double* SolverUtils::GeoPrim::C3Vector::V protected
Definition at line 784 of file GeoPrimitives.H.
Referenced by _create(), _destroy(), C3Vector(), Clear(), Copy(), Data(), Init(), Mag2(), Norm(), Normalize(), operator%(), operator%=(), operator*(), operator*=(), operator+(), operator+=(), operator-=(), operator==(), operator[](), SetData(), x(), y(), and z().
The documentation for this class was generated from the following file:
GeoPrimitives.H