IMPACT: ComputePconn Class Reference
ComputePconn Class Reference
Detailed Description
Definition at line 244 of file basic_actions.h.
#include <basic_actions.h>
Public Member Functions
ComputePconn (Agent *ag, std::string a_mesh, std::string a_pconn, std::string p_pmesh, int *cond=NULL)
void init (double t)
void run (double t, double dt, double alpha)
Public Member Functions inherited from Action
Action (void *p=0, const char *name=NULL)
Action (int n, const char **at, int *i=NULL, void *p=0, const char *name=NULL)
Action (int n, const std::string at[], int *i=NULL, void *p=0, const char *name=NULL)
virtual ~Action ()
virtual void declare (Scheduler &)
virtual void finalize ()
virtual const char * name ()
void set_name (const char *name)
virtual void print (FILE *f)
virtual void print_toposort (FILE *f)
virtual void schedule ()
Private Attributes
Agent * agent
std::string a_mesh_str
std::string a_pconn_str
std::string p_pmesh_str
int a_mesh_hdl
int a_pconn_hdl
int p_pmesh_hdl
int MAP_compute_pconn
int PROP_initialize
int * cond_addr
Additional Inherited Members
Protected Types inherited from Action
enum { IN =1, OUT =2, INOUT =3 }
Protected Member Functions inherited from Action
int get_dataitem_handle (int i)
int get_dataitem_handle_const (int i)
int get_dataitem_handle (const std::string str)
void set_attr (int n, const std::string at[], int *id=NULL)
void set_attr (int n, const char *at[], int *id=NULL)
void set_io (int n, const int *io)
void set_io (const char *io)
int get_io (int i)
Protected Attributes inherited from Action
const char * action_name
char ** attr
int * idx
int count
void * usr_ptr
std::vector< int > inout
Constructor & Destructor Documentation
ComputePconn::ComputePconn (Agent * ag, std::string a_mesh, std::string a_pconn, std::string p_pmesh, int * cond = NULL)
Definition at line 859 of file basic_actions.C.
References a_mesh_str, a_pconn_str, Action::OUT, p_pmesh_str, Action::set_attr(), and Action::set_io().
                                                                                                       :
              Action(0, (const char**)NULL, NULL, NULL, "ComputePconn"),
              agent(ag), a_mesh_str(a_mesh), a_pconn_str(a_pconn), p_pmesh_str(p_pmesh), cond_addr(cond)
 {
   int io[3] = {OUT, OUT, OUT};
   set_io( 3, io);
   std::string.data[3];
  .data[0] = a_mesh_str;
  .data[1] = a_pconn_str;
  .data[2] = p_pmesh_str;
   set_attr(3,.data);
 }
Member Function Documentation
void ComputePconn::init (double t) virtual
Reimplemented from Action.
Definition at line 873 of file basic_actions.C.
References a_mesh_hdl, a_pconn_hdl, agent, COM_get_function_handle(), cond_addr, Agent::get_communicator(), Agent::get_coupling(), Action::get_dataitem_handle(), Coupling::get_rocmancontrol_param(), load_rocmap(), load_rocprop(), MAP_compute_pconn, p_pmesh_hdl, and PROP_initialize.
 {
   if (cond_addr && *cond_addr == 0) return;
   a_mesh_hdl = get_dataitem_handle( 0);
   a_pconn_hdl = get_dataitem_handle( 1);
   p_pmesh_hdl = get_dataitem_handle( 2);
   load_rocmap();
   MAP_compute_pconn = COM_get_function_handle("MAP.compute_pconn");
   load_rocprop(agent->get_coupling()->get_rocmancontrol_param(), agent->get_communicator());
   PROP_initialize = COM_get_function_handle("PROP.initialize");
 }
void ComputePconn::run (double t, double dt, double alpha) virtual
Reimplemented from Action.
Definition at line 888 of file basic_actions.C.
References a_mesh_hdl, a_pconn_hdl, agent, COM_call_function(), cond_addr, Agent::get_agent_name(), MAN_DEBUG, MAP_compute_pconn, p_pmesh_hdl, and PROP_initialize.
{
   if (cond_addr && *cond_addr == 0) return;
   MAN_DEBUG(2, ("Rocman: (%s) ComputePconn::run() with t:%e dt:%e.\n", agent->get_agent_name().c_str(), t, dt));
   // Compute pconn for the whole surface, which will also be used
   // by surface propagation.
   COM_call_function( MAP_compute_pconn, &a_mesh_hdl, &a_pconn_hdl);
   COM_call_function( PROP_initialize, &p_pmesh_hdl);
   // ??????????
 /*
   double v = 0.0;
   int f_du_alp_hdl = COM_get_dataitem_handle(fagent->get_surface_window()+".du_alp");
   COM_call_function( RocBlas::copy_scalar, &v, &f_du_alp_hdl);
   double a = 0.0;
   int level = 1;
   fagent->obtain_bc(&a, &level);
   level = 2;
   fagent->obtain_bc(&a, &level);
 */
   // ??????????????
 }
Member Data Documentation
int ComputePconn::a_mesh_hdl private
Definition at line 252 of file basic_actions.h.
Referenced by init(), and run().
std::string ComputePconn::a_mesh_str private
Definition at line 251 of file basic_actions.h.
Referenced by ComputePconn().
int ComputePconn::a_pconn_hdl private
Definition at line 252 of file basic_actions.h.
Referenced by init(), and run().
std::string ComputePconn::a_pconn_str private
Definition at line 251 of file basic_actions.h.
Referenced by ComputePconn().
Agent* ComputePconn::agent private
Definition at line 250 of file basic_actions.h.
Referenced by init(), and run().
int* ComputePconn::cond_addr private
Definition at line 255 of file basic_actions.h.
Referenced by init(), and run().
int ComputePconn::MAP_compute_pconn private
Definition at line 253 of file basic_actions.h.
Referenced by init(), and run().
int ComputePconn::p_pmesh_hdl private
Definition at line 252 of file basic_actions.h.
Referenced by init(), and run().
std::string ComputePconn::p_pmesh_str private
Definition at line 251 of file basic_actions.h.
Referenced by ComputePconn().
int ComputePconn::PROP_initialize private
Definition at line 254 of file basic_actions.h.
Referenced by init(), and run().
The documentation for this class was generated from the following files:
basic_actions.h
basic_actions.C