IMPACT: Point_3< T > Class Template Reference
Point_3< T > Class Template Reference
Detailed Description
template<class T>
class Point_3< T >
Definition at line 130 of file mapbasic.h.
#include <mapbasic.h>
Public Member Functions
Point_3 ()
Point_3 (T t)
Point_3 (Origin)
Point_3 (T a, T b, T c)
T & operator[] (const int i)
const T & operator[] (const int i) const
Point_3 & operator+= (const Vector_3< T > &v)
Assign operators.
Point_3 & operator-= (const Vector_3< T > &v)
Point_3 operator+ (const Vector_3< T > &v) const
Arithmatic operators.
Point_3 operator- (const Vector_3< T > &v) const
Vector_3< T > operator- (const Point_3 &v) const
bool operator== (const Point_3 &p) const
bool operator!= (const Point_3 &p) const
bool operator< (const Point_3 &v) const
bool is_origin () const
Point_3 ()
Point_3 (Type a, Type b, Type c)
Type & operator[] (const int i)
const Type & operator[] (const int i) const
Protected Attributes
Type _x
Type _y
Type _z
Private Types
typedef double Type
Member Typedef Documentation
template<class T> typedef double Point_3< T >::Type private
Definition at line 26 of file plot3d.C.
Constructor & Destructor Documentation
template<class T> Point_3< T >::Point_3 () inline
Definition at line 132 of file mapbasic.h.
Referenced by Point_3< T >::operator+(), and Point_3< T >::operator-().
 {}
template<class T> Point_3< T >::Point_3 (T t) inline explicit
Definition at line 133 of file mapbasic.h.
 : Vector_3<T>(t) {}
template<class T> Point_3< T >::Point_3 (Origin) inline
Definition at line 134 of file mapbasic.h.
 : Vector_3<T>(0, 0, 0) {}
template<class T> Point_3< T >::Point_3 (T a, T b, T c) inline
Definition at line 136 of file mapbasic.h.
 : Vector_3<T>(a, b, c) {}
template<class T> Point_3< T >::Point_3 () inline
Definition at line 28 of file plot3d.C.
 {}
template<class T> Point_3< T >::Point_3 (Type a, Type b, Type c) inline
Definition at line 29 of file plot3d.C.
 : _x(a), _y(b), _z(c) {}
Member Function Documentation
template<class T> bool Point_3< T >::is_origin () const inline
Definition at line 166 of file mapbasic.h.
References Point_3< T >::_x, Point_3< T >::_y, and Point_3< T >::_z.
 { return _x==0&&_y==0&&_z==0; }
template<class T> bool Point_3< T >::operator!= (const Point_3< T > & p) const inline
Definition at line 160 of file mapbasic.h.
   { return x()!=p.x() || y()!=p.y() || z()!=p.z(); }
template<class T> Point_3 Point_3< T >::operator+ (const Vector_3< T > & v) const inline
Definition at line 150 of file mapbasic.h.
References Point_3< T >::_x, Point_3< T >::_y, Point_3< T >::_z, Point_3< T >::Point_3(), Vector_3< Type >::x(), Vector_3< Type >::y(), and Vector_3< Type >::z().
   { return Point_3(_x+v.x(), _y+v.y(), _z+v.z()); }
template<class T> Point_3& Point_3< T >::operator+= (const Vector_3< T > & v) inline
Definition at line 144 of file mapbasic.h.
References Point_3< T >::_x, Point_3< T >::_y, Point_3< T >::_z, Vector_3< Type >::x(), Vector_3< Type >::y(), and Vector_3< Type >::z().
   { _x+=v.x(); _y+=v.y(); _z+=v.z(); return *this; }
template<class T> Point_3 Point_3< T >::operator- (const Vector_3< T > & v) const inline
Definition at line 152 of file mapbasic.h.
References Point_3< T >::_x, Point_3< T >::_y, Point_3< T >::_z, Point_3< T >::Point_3(), Vector_3< Type >::x(), Vector_3< Type >::y(), and Vector_3< Type >::z().
   { return Point_3(_x-v.x(), _y-v.y(), _z-v.z()); }
template<class T> Vector_3<T> Point_3< T >::operator- (const Point_3< T > & v) const inline
Definition at line 154 of file mapbasic.h.
References Point_3< T >::_x, Point_3< T >::_y, and Point_3< T >::_z.
   { return Vector_3<T>(_x-v.x(), _y-v.y(), _z-v.z()); }
template<class T> Point_3& Point_3< T >::operator-= (const Vector_3< T > & v) inline
Definition at line 146 of file mapbasic.h.
References Point_3< T >::_x, Point_3< T >::_y, Point_3< T >::_z, Vector_3< Type >::x(), Vector_3< Type >::y(), and Vector_3< Type >::z().
   { _x-=v.x(); _y-=v.y(); _z-=v.z(); return *this; }
template<class T> bool Point_3< T >::operator< (const Point_3< T > & v) const inline
Definition at line 163 of file mapbasic.h.
References Vector_3< Type >::operator<().
   { return Vector_3<T>::operator<(v); }
template<class T> bool Point_3< T >::operator== (const Point_3< T > & p) const inline
Definition at line 157 of file mapbasic.h.
   { return x()==p.x() && y()==p.y() && z()==p.z(); }
template<class T> Type& Point_3< T >::operator[] (const int i) inline
Definition at line 30 of file plot3d.C.
 { return (&_x)[i]; }
template<class T> const Type& Point_3< T >::operator[] (const int i) const inline
Definition at line 31 of file plot3d.C.
 { return (&_x)[i]; }
template<class T> T& Point_3< T >::operator[] (const int i) inline
Definition at line 137 of file mapbasic.h.
References Point_3< T >::_x.
 { return (&_x)[i]; }
template<class T> const T& Point_3< T >::operator[] (const int i) const inline
Definition at line 138 of file mapbasic.h.
References Point_3< T >::_x.
 { return (&_x)[i]; }
Member Data Documentation
template<class T> Type Point_3< T >::_x protected
Definition at line 34 of file plot3d.C.
Referenced by Point_3< T >::is_origin(), Point_3< T >::operator+(), Point_3< T >::operator+=(), Point_3< T >::operator-(), Point_3< T >::operator-=(), and Point_3< T >::operator[]().
template<class T> Type Point_3< T >::_y protected
Definition at line 34 of file plot3d.C.
Referenced by Point_3< T >::is_origin(), Point_3< T >::operator+(), Point_3< T >::operator+=(), Point_3< T >::operator-(), and Point_3< T >::operator-=().
template<class T> Type Point_3< T >::_z protected
Definition at line 34 of file plot3d.C.
Referenced by Point_3< T >::is_origin(), Point_3< T >::operator+(), Point_3< T >::operator+=(), Point_3< T >::operator-(), and Point_3< T >::operator-=().
The documentation for this class was generated from the following files:
mapbasic.h
plot3d.C