IMPACT: Pane_manifold_2 Class Reference
Pane_manifold_2 Class Reference
This class implements a data structure for 2-manifold on each pane.
Detailed Description
It extends Simple_manifold_2 by adding data and function members to support partitioned meshes.
Definition at line 43 of file Manifold_2.h.
#include <Manifold_2.h>
Public Member Functions
Pane_manifold_2 ()
Default constructors.
Pane_manifold_2 (const COM::Pane *p, const Pane_manifold_2 *parent=NULL)
Constructor from a pane.
~Pane_manifold_2 ()
Destructor.
const Window_manifold_2 * window_manifold () const
Window_manifold_2 * window_manifold ()
const Halfedge & get_counterpart (Edge_ID eID) const
Get the counterpart of an edge in the ACROSS_PANE mode, i.e.
const Vector_3< Real > & get_bd_normal (Edge_ID) const
Obtain normal of incident face of border edge.
int get_bd_flag (Edge_ID) const
Obtain flag of incident face of border edge.
bool get_bdedge_flag (Edge_ID) const
Obtain flag of opposite halfedge of a border halfedge.
Halfedge get_opposite_edge (Edge_ID, Access_Mode mode=ACROSS_PANE) const
Obtain the opposite edge in a given access mode.
Halfedge get_prev_edge (Edge_ID, Access_Mode mode=ACROSS_PANE) const
Obtain the previous edge in a given access mode.
Halfedge get_next_edge (Edge_ID, Access_Mode mode=ACROSS_PANE) const
Obtain the next edge in a given access mode.
Node get_primary (int vID, Access_Mode mode=ACROSS_PANE) const
Obtains a Node object corresponding to the primary copy of the given node.
bool is_primary (int vID, Access_Mode mode=ACROSS_PANE) const
Determines whether a given node is a primary copy.
bool is_border_edge (Edge_ID eID, Access_Mode mode=ACROSS_PANE) const
Is the edge on the boundary of a given mode?
bool is_physical_border_edge (Edge_ID eID) const
Is the given edge a physical border edge?
int size_of_nodes (Access_Mode mode=ACROSS_PANE) const
Number of primary nodes of the pane for a given mode.
int size_of_edges (Access_Mode mode=ACROSS_PANE) const
Number of primary edges of the pane in a given mode.
int size_of_faces (Access_Mode mode=ACROSS_PANE) const
Obtain the number of faces.
int size_of_triangles (Access_Mode mode=ACROSS_PANE) const
Obtain the number of triangles.
int size_of_quadrilaterals (Access_Mode mode=ACROSS_PANE) const
Obtain the number of quadrilaterals.
Public Member Functions inherited from Simple_manifold_2
Simple_manifold_2 ()
Default constructors.
Simple_manifold_2 (const COM::Pane *p, const Simple_manifold_2 *parent=NULL, bool with_ghost=true)
Constructors.
const COM::Pane * pane () const
Obtain a const pointer to the pane.
bool is_real_node (int vID) const
Is the given node a real node?
bool is_ghost_node (int vID) const
Is the given node a ghost node?
bool is_real_element (int eid) const
Is the element incident on the give edge a real element?
bool is_ghost_element (int eid) const
Is the element incident on the give edge a ghost element?
int get_edge_index (const Edge_ID &eid, const int offset=0) const
Get an index for internal edges.
int upperbound_edge_index () const
Get size of internal edges.
void get_borders (std::vector< bool > &is_border, std::vector< bool > &is_isolated, std::vector< Edge_ID > *b, int *ng=NULL) const
Obtain all the border nodes, isolated nodes, and border edges.
int size_of_nodes () const
Number of nodes of the pane.
int maxsize_of_nodes () const
Maximum number of nodes allowed in the pane.
int size_of_real_nodes () const
Number of real nodes of the pane.
int maxsize_of_real_nodes () const
Maximum number of real nodes allowed in the pane.
int size_of_ghost_nodes () const
Number of ghost nodes of the pane.
int maxsize_of_ghost_nodes () const
Maximum number of ghost nodes allowed in the pane.
int size_of_elements () const
Number of elements of the pane.
int maxsize_of_elements () const
Maximum number of elements allowed in the pane.
int size_of_real_elements () const
Number of real elements of the pane.
int maxsize_of_real_elements () const
Maximum number of real elements allowed in the pane.
int size_of_ghost_elements () const
Number of ghost elements of the pane.
int maxsize_of_ghost_elements () const
Maximum number of ghost elements allowed in the pane.
int size_of_faces () const
Number of elements of the pane.
int maxsize_of_faces () const
Maximum number of elements allowed in the pane.
int size_of_real_faces () const
Number of real elements of the pane.
int maxsize_of_real_faces () const
Maximum number of real elements allowed in the pane.
int size_of_ghost_faces () const
Number of ghost elements of the pane.
int maxsize_of_ghost_faces () const
Maximum number of ghost elements allowed in the pane.
int size_of_triangles () const
Total number of triangles of the pane.
int maxsize_of_triangles () const
Maximum number of triangles allowed in the pane.
int size_of_real_triangles () const
Number of real triangles of the pane.
int maxsize_of_real_triangles () const
Maximum number of real triangles allowed in the pane.
int size_of_ghost_triangles () const
Number of ghost triangles of the pane.
int maxsize_of_ghost_triangles () const
Maximum number of ghost triangles allowed in the pane.
int size_of_quadrilaterals () const
Total number of quadrilaterals of the pane.
int maxsize_of_quadrilaterals () const
Maximum number of quadrilaterals allowed in the pane.
int size_of_real_quadrilaterals () const
Number of real quadrilaterals of the pane.
int maxsize_of_real_quadrilaterals () const
Maximum number of real quadrilaterals allowed in the pane.
int size_of_ghost_quadrilaterals () const
Number of ghost quadrilaterals of the pane.
int maxsize_of_ghost_quadrilaterals () const
Maximum number of ghost quadrilaterals allowed in the pane.
int size_of_halfedges () const
Number of halfedges of the pane.
int size_of_real_halfedges () const
Number of real halfedges of the pane.
int size_of_ghost_halfedges () const
Number of ghost halfedges of the pane.
int size_of_edges () const
Number of edges of the pane.
int size_of_real_edges () const
Number of real edges of the pane.
int size_of_ghost_edges () const
Number of ghost edges of the pane.
int size_of_border_edges () const
Number of border edges of the whole pane.
int size_of_real_border_edges () const
Number of border edges of the real part of the pane.
int size_of_ghost_border_edges () const
Number of border edges of the ghost part of the pane.
int size_of_isolated_nodes () const
Number of isolated nodes.
int get_origin (Edge_ID eID, Element_node_enumerator *ene_in=NULL) const
Get the ID of the origin of a given edge.
int get_destination (Edge_ID eID, Element_node_enumerator *ene_in=NULL) const
Get the ID of the destination of a given edge.
Edge_ID get_incident_edge (int vID) const
Get the ID of an incident edge within the pane of a given node that originated from the node.
Edge_ID get_incident_real_edge (int vID) const
Get the ID of an incident real edge within the pane of a given node.
Edge_ID get_incident_ghost_edge (int vID) const
Get the ID of an incident real edge within the pane of a given node The incident edge may encode an isolated node.
bool is_border_edge (const Edge_ID &eID) const
Is a given edge on the boundary of the whole pane?
bool is_pure_real_border_edge (const Edge_ID &eID) const
Determine whether a given edge is a border edge of real part of the whole pane (on physical border).
bool is_real_border_edge (const Edge_ID &eID) const
Determine whether a given edge is a border edge of real part of the pane (either on physical border or between real and ghost elements)
bool is_ghost_border_edge (const Edge_ID &eID) const
Determine whether a given edge is a border edge of ghost part of the pane (either on physical border or between real and ghost elements)
bool is_isolated_node (int vID) const
Is the node isolated (i.e. not incident on any element)?
bool is_real_border_node (int vID) const
Is the node on the pane boundary of real part (not isolated)?
bool is_ghost_border_node (int vID) const
Is the node on pane boundary (not isolated)? It assumes vID is incident on the ghost (no checking is performed).
bool is_border_node (int vID) const
Is the node on pane boundary (not isolated)?
int get_border_edgeID (Edge_ID eID) const
Get the border edge index. Return -1 if not a border edge.
Edge_ID get_a_real_border_edge () const
Obtain a border edge on real part of the pane.
Edge_ID get_a_ghost_border_edge () const
Obtain a border edge on ghost part of the pane.
Edge_ID get_a_border_edge () const
Obtain the ID of a border edge of the whole pane.
int get_a_real_border_node () const
Obtain the ID of a border node of the real part of the pane.
int get_a_ghost_border_node () const
Obtain the ID of a border node of the ghost part of the pane.
int get_a_border_node () const
Obtain the ID of a border node.
Edge_ID get_opposite_real_edge (const Edge_ID &eID) const
Get the ID of the opposite real edge of a given real or border edge.
Edge_ID get_opposite_ghost_edge (const Edge_ID &eID) const
Get the ID of the opposite ghost edge of a given real or border edge.
Edge_ID get_opposite_edge (const Edge_ID &eID) const
Get the ID of the opposite edge of a given interior or border edge.
Edge_ID get_prev_edge (const Edge_ID &eID) const
Get the ID of the previous edge of the element or along the boundary.
Edge_ID get_prev_real_edge (const Edge_ID &eID) const
Get the ID of the previous real edge of the element or along the boundary.
Edge_ID get_prev_ghost_edge (const Edge_ID &eID) const
Get the ID of the previous ghost edge of the element or along the boundary.
Edge_ID get_next_edge (const Edge_ID &eID) const
Get the ID of the next edge of the element or along the boundary.
Edge_ID get_next_real_edge (const Edge_ID &eID) const
Get the ID of the next real edge of the element or along the boundary.
Edge_ID get_next_ghost_edge (const Edge_ID &eID) const
Get the ID of the next ghost edge of the element or along the boundary.
Protected Member Functions
void convert_pconn_edge2ghost (const COM::DataItem *pconn_e, COM::DataItem *pconn_g)
Convert from edge-based pconn to a ghost-node-style pconn for a pane dataitem.
int get_bnode_index (int vID) const
Obtain the border node index (equal to ID of incident border edge).
Protected Member Functions inherited from Simple_manifold_2
void init (const COM::Pane *p, const Simple_manifold_2 *parent=NULL, bool with_ghost=true)
Initialize the database for the pane, including ghost information, opposite halfedges, incident halfedges, and border halfedges.
void determine_ghosts ()
Determine the ghost nodes and elements.
void determine_opposite_halfedges ()
Determine the opposite halfedges of each halfedge, and identify border halfedge.
void determine_incident_halfedges ()
Determine an incident halfedge for each node.
Protected Attributes
Window_manifold_2 * _wm
std::vector< int > _cnt_pn
std::vector< Halfedge > _bd_cnt
std::vector< Vector_3< Real > > _bd_nrms
std::vector< int > _bd_flgs
std::vector< char > _bd_bm
std::vector< Node > _nd_prm
Protected Attributes inherited from Simple_manifold_2
const COM::Pane * _pane
bool _is_str
bool _with_ghost
std::vector< const
COM::Connectivity * > _elem_conns
int _nspe
int _maxsize_real_nodes
int _maxsize_real_elmts
int _size_real_borders
int _size_ghost_borders
int _size_rg_borders
std::vector< bool > _isghostnode
std::vector< bool > _isghostelmt
std::vector< Edge_ID > _oeIDs_real_or_str
std::vector< Edge_ID > _oeIDs_ghost
std::vector< Edge_ID > _ieIDs_real_or_str
std::vector< Edge_ID > _ieIDs_ghost
std::vector< Edge_ID > _beIDs
std::vector< int > _isovIDs
Friends
class Window_manifold_2
class Node
class Halfedge
Additional Inherited Members
Public Types inherited from Simple_manifold_2
typedef Facet_ID Edge_ID
Constructor & Destructor Documentation
Pane_manifold_2::Pane_manifold_2 () inline
Definition at line 49 of file Manifold_2.h.
 : _wm(NULL) {}
Pane_manifold_2::Pane_manifold_2 (const COM::Pane * p, const Pane_manifold_2 * parent = NULL) explicit
Default constructors.
Constructor from a pane
Definition at line 38 of file Manifold_2.C.
References _bd_cnt, _cnt_pn, and _nd_prm.
   : Simple_manifold_2( p, parent), _wm(NULL)
 {
   if ( parent) {
     _cnt_pn = parent->_cnt_pn;
     _bd_cnt = parent->_bd_cnt;
     _nd_prm = parent->_nd_prm;
   }
   else; // Otherwise, they are filled by Window_manifold_2::init()
 }
Pane_manifold_2::~Pane_manifold_2 ()
Definition at line 50 of file Manifold_2.C.
 {}
Member Function Documentation
void Pane_manifold_2::convert_pconn_edge2ghost (const COM::DataItem * pconn_e, COM::DataItem * pconn_g) protected
Definition at line 766 of file Manifold_2.C.
References COM_assertion, Facet_ID::eid(), Simple_manifold_2::get_opposite_real_edge(), and Simple_manifold_2::size_of_real_border_edges().
{
   const int *b2e_l = (const int*)pconn_e->pointer();
   int n=pconn_e->size_of_items();
   pconn_g->set_size( n+n+1, n+n);
   int *buf = (int*)pconn_g->allocate( 1, n+n+1, true);
   buf[0] = 0;         // Shared-node part is empty
   buf[1] = b2e_l[ 0]; // Number of communicating panes
   // Extracting the edge-ID part.
   for ( int j=1; j<n; j+=b2e_l[j+1]+2) {
     buf[j+1] = b2e_l[j]; // Pane ID
     buf[j+2] = b2e_l[j+1]; // Number of items
     const Edge_ID *es = (const Edge_ID*)(&b2e_l[j+2]);
     for ( int k=0, nk=b2e_l[j+1]; k<nk; ++k) {
       buf[j+k+3] = get_opposite_real_edge(es[k]).eid();
       COM_assertion( buf[j+k+3]>=1 && buf[j+k+3]<=size_of_real_border_edges());
     }
   }
   // Copy the sending part into the receiving part.
   std::copy( &buf[1], &buf[n+1], &buf[n+1]);
 }
int Pane_manifold_2::get_bd_flag (Edge_ID eID) const inline
Definition at line 690 of file Manifold_2.h.
References _bd_flgs, COM_assertion_msg, Facet_ID::eid(), and Facet_ID::is_border().
{
   COM_assertion_msg( eID.is_border() && !_bd_flgs.empty(),
                      "get_bd_flag must be called on border edges and be called after update_bd_flags() has been called.");
   return _bd_flgs[ eID.eid()-1];
 }
const Vector_3< Real > & Pane_manifold_2::get_bd_normal (Edge_ID eID) const inline
Definition at line 684 of file Manifold_2.h.
References _bd_nrms, COM_assertion_msg, Facet_ID::eid(), and Facet_ID::is_border().
Referenced by get_normal().
{
   COM_assertion_msg( eID.is_border() && !_bd_nrms.empty(),
                      "get_bd_normal must be called on border edges and be called after update_bd_normals() has been called.");
   return _bd_nrms[ eID.eid()-1];
 }
bool Pane_manifold_2::get_bdedge_flag (Edge_ID eID) const inline
Definition at line 696 of file Manifold_2.h.
References _bd_bm, COM_assertion_msg, Facet_ID::eid(), and Facet_ID::is_border().
{
   COM_assertion_msg( eID.is_border() && !_bd_bm.empty(),
                      "get_bdedge_flag must be called on border edges and be called after update_bdedge_bitmap() has been called.");
   return _bd_bm[ eID.eid()-1];
 }
int Pane_manifold_2::get_bnode_index (int vID) const inline protected
Return -1 if not a border edge.
Definition at line 158 of file Manifold_2.h.
References Simple_manifold_2::_beIDs, Simple_manifold_2::_size_ghost_borders, Facet_ID::eid(), Simple_manifold_2::get_incident_real_edge(), and Facet_ID::is_border().
Referenced by Window_manifold_2::determine_primaries(), get_primary(), and is_primary().
{
     Edge_ID eID = get_incident_real_edge( vID);
     if ( !eID.is_border()) return -1;
     int bid = eID.eid()-1;
     if ( bid>=int(_beIDs.size())) return bid-_size_ghost_borders;
     else return bid;
   }
const Halfedge & Pane_manifold_2::get_counterpart (Edge_ID eID) const inline
its correponding edge in an adjacent pane. If the edge is on the physical boundary, then its counterpart is Halfedge(NULL,Edge_ID(), ACROSS_PANE).
Definition at line 678 of file Manifold_2.h.
References _bd_cnt, COM_assertion, Facet_ID::eid(), and Facet_ID::is_border().
Referenced by get_opposite_edge(), Node::halfedge(), and is_border_edge().
 {
   COM_assertion( eID.is_border());
   return _bd_cnt[ eID.eid()-1];
 }
Halfedge Pane_manifold_2::get_next_edge (Edge_ID eID, Access_Mode mode = ACROSS_PANE) const
Definition at line 81 of file Manifold_2.C.
References ACROSS_PANE, COM_assertion_msg, Simple_manifold_2::get_next_edge(), Simple_manifold_2::get_next_real_edge(), get_opposite_edge(), Halfedge, Halfedge::is_border(), Simple_manifold_2::is_real_border_edge(), Halfedge::opposite(), Halfedge::prev(), REAL_PANE, and WHOLE_PANE.
Referenced by Halfedge::next().
 {
   Edge_ID nxt;
   switch ( mode) {
   case REAL_PANE:
     nxt = get_next_real_edge( eID); break;
   case WHOLE_PANE:
     nxt = Simple_manifold_2::get_next_edge( eID); break;
   case ACROSS_PANE: {
     // In the across-pane mode, it is illegal to access halfedges that are
     // not on physical boundaries but on pane boundaries. So a pane-border
     // halfedge must be a physical border edge.
     if ( !is_real_border_edge(eID))
     { nxt = get_next_real_edge( eID); break; }
     else {  // the edge is on physical boundary.
       Halfedge h = get_opposite_edge( eID, ACROSS_PANE);
       while ( !h.is_border()) h = h.prev().opposite();
       return h;
     }
   }
   default:  COM_assertion_msg(false, "Should never reach here");
   }
   return Halfedge( this, nxt, mode);
 }
Halfedge Pane_manifold_2::get_opposite_edge (Edge_ID eID, Access_Mode mode = ACROSS_PANE) const inline
Definition at line 704 of file Manifold_2.h.
References ACROSS_PANE, COM_assertion_msg, get_counterpart(), Simple_manifold_2::get_opposite_edge(), Simple_manifold_2::get_opposite_real_edge(), Halfedge, Facet_ID::is_border(), Halfedge::pane_manifold(), REAL_PANE, and WHOLE_PANE.
Referenced by get_next_edge(), get_prev_edge(), and Halfedge::opposite().
{
   Edge_ID opp;
   switch ( mode) {
   case REAL_PANE:
     opp = get_opposite_real_edge( eID); break;
   case WHOLE_PANE:
     opp = Simple_manifold_2::get_opposite_edge( eID); break;
   case ACROSS_PANE: {
     opp=get_opposite_real_edge( eID);
     if (  opp.is_border()) {
       Halfedge h = get_counterpart(opp);
       if ( h.pane_manifold()) return h;
     }
     break;
   }
   default:  COM_assertion_msg(false, "Should never reach here");
   }
   return Halfedge( this, opp, mode);
 }
Halfedge Pane_manifold_2::get_prev_edge (Edge_ID eID, Access_Mode mode = ACROSS_PANE) const
Definition at line 54 of file Manifold_2.C.
References ACROSS_PANE, COM_assertion_msg, get_opposite_edge(), Simple_manifold_2::get_prev_edge(), Simple_manifold_2::get_prev_real_edge(), Halfedge, Facet_ID::is_border(), Halfedge::is_border(), Halfedge::next(), Halfedge::opposite(), REAL_PANE, and WHOLE_PANE.
Referenced by Halfedge::prev().
 {
   Edge_ID prv;
   switch ( mode) {
   case REAL_PANE:
     prv = get_prev_real_edge( eID); break;
   case WHOLE_PANE:
     prv = Simple_manifold_2::get_prev_edge( eID); break;
   case ACROSS_PANE: {
     // In the across-pane mode, it is illegal to access halfedges that are
     // not on physical boundaries but on pane boundaries. So a pane-border
     // halfedge must be a physical border edge.
     if ( !eID.is_border())
     { prv = get_prev_real_edge( eID); break; }
     else { // the edge is on physical boundary.
       Halfedge h = get_opposite_edge( eID, ACROSS_PANE);
       while ( !h.is_border()) h = h.next().opposite();
       return h;
     }
   }
   default:  COM_assertion_msg(false, "Should never reach here");
   }
   return Halfedge( this, prv, mode);
 }
Node Pane_manifold_2::get_primary (int vID, Access_Mode mode = ACROSS_PANE) const inline
If the mode is not ACROSS_PANE, then the primary copy is always the node itself. If the mode is ACROSS_PANE, then the incident edge of the primary copy of the node must be a border edge, and the primary copy of an interior node is the one with smallest ID among shared nodes.
Definition at line 726 of file Manifold_2.h.
References _nd_prm, ACROSS_PANE, COM_assertion, get_bnode_index(), and Node.
Referenced by Node::coincide(), Halfedge::destination(), Node::get_primary(), and Halfedge::origin().
 {
   if ( mode != ACROSS_PANE) return Node(this, vID, mode);
   int bid = get_bnode_index( vID);
   COM_assertion( bid<int(_nd_prm.size()));
   if ( bid >=0 && _nd_prm[ bid].pane_manifold())
     return _nd_prm[ bid];
   else
     return Node( this, vID, ACROSS_PANE);
 }
bool Pane_manifold_2::is_border_edge (Edge_ID eID, Access_Mode mode = ACROSS_PANE) const inline
Definition at line 750 of file Manifold_2.h.
References ACROSS_PANE, COM_assertion_msg, get_counterpart(), Facet_ID::is_border(), Simple_manifold_2::is_pure_real_border_edge(), Simple_manifold_2::is_real_border_edge(), Halfedge::pane_manifold(), REAL_PANE, and WHOLE_PANE.
Referenced by Halfedge::is_border().
 {
   switch ( mode) {
   case REAL_PANE:
     return is_real_border_edge( eID);
   case WHOLE_PANE:
     // For whole pane, an edge is border only if it is pure real border edge.
     return is_pure_real_border_edge( eID);
   case ACROSS_PANE:
     return eID.is_border() && get_counterpart( eID).pane_manifold() == NULL;
   default:  COM_assertion_msg(false, "Should never reach here");
     return false;
   }
 }
bool Pane_manifold_2::is_physical_border_edge (Edge_ID eID) const inline
Definition at line 106 of file Manifold_2.h.
References _cnt_pn, Simple_manifold_2::get_border_edgeID(), and Facet_ID::is_border().
Referenced by Halfedge::is_physical_border().
   { return eID.is_border() && _cnt_pn[get_border_edgeID(eID)-1]==0; }
bool Pane_manifold_2::is_primary (int vID, Access_Mode mode = ACROSS_PANE) const inline
Definition at line 739 of file Manifold_2.h.
References _nd_prm, ACROSS_PANE, COM_assertion, and get_bnode_index().
Referenced by Node::is_primary().
 {
   if ( mode != ACROSS_PANE) return true;
   int bid = get_bnode_index( vID);
   COM_assertion( bid<int(_nd_prm.size()));
   return bid <0 || !_nd_prm[ bid].pane_manifold();
 }
int Pane_manifold_2::size_of_edges (Access_Mode mode = ACROSS_PANE) const
In ACROSS_PANE mode, the shared edges will be counted only if they are primary copies.
Definition at line 127 of file Manifold_2.C.
References _bd_cnt, Simple_manifold_2::_pane, ACROSS_PANE, COM_assertion_msg, Halfedge::pane(), Halfedge::pane_manifold(), REAL_PANE, Simple_manifold_2::size_of_edges(), Simple_manifold_2::size_of_real_edges(), and WHOLE_PANE.
 {
   switch (mode) {
   case REAL_PANE:  return size_of_real_edges();
   case WHOLE_PANE: return Simple_manifold_2::size_of_edges();
   case ACROSS_PANE: {
     int n = size_of_real_edges();
     int branch=0;
     // Loop through border edges
     for ( std::vector<Halfedge>::const_iterator
             it=_bd_cnt.begin(), iend=_bd_cnt.end(); it != iend; ++it) {
       Halfedge hopp = *it;
       if ( hopp.pane_manifold()) {
         if (hopp.pane()->id()<_pane->id()) --n;
         else if (hopp.pane()->id()==_pane->id()) ++branch;
       }
     }
     if ( branch) n-=branch/2;
     return n;
   }
   default:
     COM_assertion_msg(false, "Should never reach here");
   }
   return 0;
 }
int Pane_manifold_2::size_of_faces (Access_Mode mode = ACROSS_PANE) const inline
Definition at line 121 of file Manifold_2.h.
References ACROSS_PANE, REAL_PANE, Simple_manifold_2::size_of_faces(), and Simple_manifold_2::size_of_real_faces().
{
     switch ( mode) {
     case REAL_PANE:
     case ACROSS_PANE: return size_of_real_faces();
     default: return Simple_manifold_2::size_of_faces();
     }
   }
int Pane_manifold_2::size_of_nodes (Access_Mode mode = ACROSS_PANE) const
In ACROSS_PANE mode, the shared nodes will be counted only if they are primary copies.
Definition at line 106 of file Manifold_2.C.
References _nd_prm, ACROSS_PANE, COM_assertion_msg, REAL_PANE, Simple_manifold_2::size_of_nodes(), Simple_manifold_2::size_of_real_nodes(), and WHOLE_PANE.
 {
   switch (mode) {
   case REAL_PANE:  return size_of_real_nodes();
   case WHOLE_PANE: return Simple_manifold_2::size_of_nodes();
   case ACROSS_PANE: {
     int n = size_of_real_nodes();
     // Loop through border nodes
     for ( std::vector<Node>::const_iterator
             it=_nd_prm.begin(), iend=_nd_prm.end(); it != iend; ++it) {
       if ( it->pane_manifold()) --n;
     }
     return n;
   }
   default:
     COM_assertion_msg(false, "Should never reach here");
   }
   return 0;
 }
int Pane_manifold_2::size_of_quadrilaterals (Access_Mode mode = ACROSS_PANE) const inline
Definition at line 141 of file Manifold_2.h.
References ACROSS_PANE, REAL_PANE, Simple_manifold_2::size_of_quadrilaterals(), and Simple_manifold_2::size_of_real_quadrilaterals().
{
     switch ( mode) {
     case REAL_PANE:
     case ACROSS_PANE: return size_of_real_quadrilaterals();
     default: return Simple_manifold_2::size_of_quadrilaterals();
     }
   }
int Pane_manifold_2::size_of_triangles (Access_Mode mode = ACROSS_PANE) const inline
Definition at line 131 of file Manifold_2.h.
References ACROSS_PANE, REAL_PANE, Simple_manifold_2::size_of_real_triangles(), and Simple_manifold_2::size_of_triangles().
{
     switch ( mode) {
     case REAL_PANE:
     case ACROSS_PANE: return size_of_real_triangles();
     default: return Simple_manifold_2::size_of_triangles();
     }
   }
const Window_manifold_2* Pane_manifold_2::window_manifold () const inline
Definition at line 59 of file Manifold_2.h.
References _wm.
 { return _wm; }
Window_manifold_2* Pane_manifold_2::window_manifold () inline
Definition at line 60 of file Manifold_2.h.
References _wm.
 { return _wm; }
Friends And Related Function Documentation
friend class Halfedge friend
Definition at line 46 of file Manifold_2.h.
Referenced by get_next_edge(), get_opposite_edge(), and get_prev_edge().
friend class Node friend
Definition at line 45 of file Manifold_2.h.
Referenced by get_primary().
friend class Window_manifold_2 friend
Definition at line 44 of file Manifold_2.h.
Member Data Documentation
std::vector<char > Pane_manifold_2::_bd_bm protected
Definition at line 181 of file Manifold_2.h.
Referenced by get_bdedge_flag().
std::vector<Halfedge> Pane_manifold_2::_bd_cnt protected
Definition at line 178 of file Manifold_2.h.
Referenced by Window_manifold_2::determine_counterparts(), get_counterpart(), Pane_manifold_2(), and size_of_edges().
std::vector<int > Pane_manifold_2::_bd_flgs protected
Definition at line 180 of file Manifold_2.h.
Referenced by get_bd_flag().
std::vector<Vector_3<Real> > Pane_manifold_2::_bd_nrms protected
Definition at line 179 of file Manifold_2.h.
Referenced by get_bd_normal().
std::vector<int> Pane_manifold_2::_cnt_pn protected
Definition at line 172 of file Manifold_2.h.
Referenced by Window_manifold_2::determine_counterparts(), is_physical_border_edge(), and Pane_manifold_2().
std::vector<Node> Pane_manifold_2::_nd_prm protected
Definition at line 182 of file Manifold_2.h.
Referenced by Window_manifold_2::determine_primaries(), get_primary(), is_primary(), Pane_manifold_2(), and size_of_nodes().
Window_manifold_2* Pane_manifold_2::_wm protected
Definition at line 168 of file Manifold_2.h.
Referenced by window_manifold().
The documentation for this class was generated from the following files:
Manifold_2.h
Manifold_2.C