IMPACT: Rocstar::Rocin::Utilities::MeshPointIdToGlobalIdMap Class Reference
Rocstar::Rocin::Utilities::MeshPointIdToGlobalIdMap Class Reference
Detailed Description
Definition at line 26 of file MeshPointIdToGlobalIdMap.hpp.
#include <MeshPointIdToGlobalIdMap.hpp>
Public Member Functions
MeshPointIdToGlobalIdMap ()
Constructor.
~MeshPointIdToGlobalIdMap ()
Destructor.
bool exists (const int meshPaneId, const int meshPointId)
Checks if the point meshPointId of the mesh associated with the provided meshPaneId exists in this MeshPointIdToGlobalIdMap instance.
int getGlobalId (const int meshPaneId, const int meshPointId)
Returns the assigned global id to meshPointId of the mesh associated with the provided meshPaneId.
void insert (const int meshPaneId, const int meshPointId, const int globalId)
This method constructs a new key-pair for the meshPaneId and meshPointId which maps into globalId and inserts it into the data-structure.
int size () const
Returns the size of the map.
Private Attributes
std::map< std::pair< int, int >
, int > local2global
Constructor & Destructor Documentation
Rocstar::Rocin::Utilities::MeshPointIdToGlobalIdMap::MeshPointIdToGlobalIdMap () inline
Postcondition
this ->size() == 0.
Definition at line 37 of file MeshPointIdToGlobalIdMap.hpp.
 { }
Rocstar::Rocin::Utilities::MeshPointIdToGlobalIdMap::~MeshPointIdToGlobalIdMap () inline
Definition at line 42 of file MeshPointIdToGlobalIdMap.hpp.
 { this ->local2global.clear( ); }
Member Function Documentation
bool Rocstar::Rocin::Utilities::MeshPointIdToGlobalIdMap::exists (const int meshPaneId, const int meshPointId) inline
Parameters
meshPaneId the pane id of the mesh in query.
meshPointId the local point id of the point in query.
Returns
Status true iff exists else false.
Definition at line 51 of file MeshPointIdToGlobalIdMap.hpp.
References local2global.
Referenced by insert().
{
                                 std::pair< int, int > keyPair = std::make_pair( meshPaneId, meshPointId );
                                 if( this ->local2global.find( keyPair ) != this ->local2global.end( ) )
                                         return true;
                                 else
                                         return false;
                         }
int Rocstar::Rocin::Utilities::MeshPointIdToGlobalIdMap::getGlobalId (const int meshPaneId, const int meshPointId) inline
Parameters
meshPaneId the pane id of the mesh in query.
meshPointId the point id of the mesh point in query.
Returns
ID the global id assigned to the point.
Postcondition
ID >= 0 or -1 iff ! this ->exists(meshPaneId, meshPoint).
Definition at line 68 of file MeshPointIdToGlobalIdMap.hpp.
References local2global.
Referenced by stitchSolutionData().
{
                                 std::pair< int, int > keyPair = std::make_pair( meshPaneId, meshPointId );
                                 if( this ->local2global.find( keyPair ) != this ->local2global.end( ) )
                                         return( this ->local2global[ keyPair ] );
                                 else
                                         return(-1);
                         }
void Rocstar::Rocin::Utilities::MeshPointIdToGlobalIdMap::insert (const int meshPaneId, const int meshPointId, const int globalId) inline
Parameters
meshPaneId the pane id of the mesh in query.
meshPointId the point id of the mesh point in query.
globalId the global id assigned to the point.
Precondition
globalId >= 0 && meshPointId >= 0.
this ->exists(meshPaneId, meshPointId) == false.
Postcondition
this ->exists(meshPaneId, meshPointId) == true.
Definition at line 87 of file MeshPointIdToGlobalIdMap.hpp.
References exists().
Referenced by stitchGrids(), and updateHash().
{
 //                              std::cout << "Mesh Pane Id: " << meshPaneId << " ";
 //                              std::cout << "Mesh Point Id: " << meshPointId << " ";
 //                              std::cout << std::endl;
 //                              std::cout.flush( );
                                 #ifdef ASSERT_ON
                                         assert( globalId >= 0 );
                                         assert( meshPointId >= 0);
                                         assert( !this ->exists( meshPaneId, meshPointId ) );
                                 #endif
                                 std::pair< int, int > keyPair  = std::make_pair( meshPaneId, meshPointId );
                                 this ->local2global[ keyPair ] = globalId;
                                 #ifdef ASSERT_ON
                                         assert( this ->exists( meshPaneId, meshPointId ) );
                                 #endif
                         }
int Rocstar::Rocin::Utilities::MeshPointIdToGlobalIdMap::size () const inline
Returns
N the number of elements in the map.
Postcondition
N >= 0.
Definition at line 115 of file MeshPointIdToGlobalIdMap.hpp.
 { return this ->local2global.size( ); }
Member Data Documentation
std::map< std::pair< int, int >, int > Rocstar::Rocin::Utilities::MeshPointIdToGlobalIdMap::local2global private
Definition at line 29 of file MeshPointIdToGlobalIdMap.hpp.
Referenced by exists(), and getGlobalId().
The documentation for this class was generated from the following file:
MeshPointIdToGlobalIdMap.hpp