IMPACT: UseDataItem Class Reference
UseDataItem Class Reference
Detailed Description
Definition at line 116 of file Agent.h.
#include <Agent.h>
Public Member Functions
UseDataItem (Agent *ag, std::string target_window_, std::string attr_, std::string parent_window_, std::string parent_attr_, int wg_=1, const char *ptnname_=0, int val_=0)
void create (std::string bufname)
Public Member Functions inherited from DataItemBase
DataItemBase (Agent *ag, std::string target_window_, std::string attr_)
virtual ~DataItemBase ()
virtual void assign (std::string bufname)
Protected Attributes
std::string parent_window
std::string parent_attr
int wg
const char * ptnname
int val
Additional Inherited Members
Public Attributes inherited from DataItemBase
Agent * agent
std::string target_window
std::string attr
Constructor & Destructor Documentation
UseDataItem::UseDataItem (Agent * ag, std::string target_window_, std::string attr_, std::string parent_window_, std::string parent_attr_, int wg_ = 1, const char * ptnname_ = 0, int val_ = 0)
Definition at line 155 of file Agent.C.
                                                                                                                                                                        :
                 DataItemBase(ag, target_window_, attr_),
                 parent_window(parent_window_), parent_attr(parent_attr_),
                 wg(wg_), ptnname(ptnname_), val(val_)
 {
 }
Member Function Documentation
void UseDataItem::create (std::string bufname) virtual
Reimplemented from DataItemBase.
Definition at line 162 of file Agent.C.
References DataItemBase::agent, DataItemBase::attr, COM_get_dataitem(), COM_get_dataitem_handle(), COM_use_dataitem(), Agent::get_surface_window(), MAN_DEBUG, parent_attr, parent_window, ptnname, DataItemBase::target_window, val, and wg.
 {
   if (parent_window=="") {
     parent_window = agent->get_surface_window();
   }
   if (COM_get_dataitem_handle( bufname+attr) > 0) {
     char loc1, loc2;
     int type1, type2;
     int ncomp1, ncomp2;
     std::string unit1, unit2;
     COM_get_dataitem( bufname+attr, &loc1, &type1, &ncomp1, &unit1);
     COM_get_dataitem( parent_window+parent_attr, &loc2, &type2, &ncomp2, &unit2);
     if (loc1 != loc2 || type1 != type2 || ncomp1 != ncomp2 || unit1 != unit2) {
       std::cout << "ROCMAN Error: NewDataItem::create(): Could not create " << target_window+attr << " in two different ways " << std::endl;
       MPI_Abort(MPI_COMM_WORLD, -1);
     }
     else
       return;
   }
   MAN_DEBUG(2, ("UseDataItem::create: %s%s %s%s.\n", bufname.c_str(), attr.c_str(), parent_window.c_str(), parent_attr.c_str()));
   COM_use_dataitem( bufname+attr, parent_window+parent_attr, wg, ptnname, val);
 }
Member Data Documentation
std::string UseDataItem::parent_attr protected
Definition at line 119 of file Agent.h.
Referenced by create().
std::string UseDataItem::parent_window protected
Definition at line 118 of file Agent.h.
Referenced by create().
const char* UseDataItem::ptnname protected
Definition at line 121 of file Agent.h.
Referenced by create().
int UseDataItem::val protected
Definition at line 122 of file Agent.h.
Referenced by create().
int UseDataItem::wg protected
Definition at line 120 of file Agent.h.
Referenced by create().
The documentation for this class was generated from the following files:
Agent.h
Agent.C