IMPACT: Vertex_set Class Reference
Vertex_set Class Reference
Detailed Description
Definition at line 29 of file Overlay_primitives.h.
#include <Overlay_primitives.h>
Public Types
typedef Vertex_set Self
typedef int Value
typedef unsigned int Size
Public Member Functions
Vertex_set ()
Vertex_set (const HEdge &h)
Vertex_set (const HEdge &h, Size)
const RFC_Pane_overlay * pane () const
int operator[] (Size i) const
Size size_of_edges () const
Size size_of_nodes () const
Protected Member Functions
Size count_edges (const HEdge &e) const
Protected Attributes
const RFC_Pane_overlay * _pane
std::vector< int > _nodes
Size _ne
Member Typedef Documentation
typedef Vertex_set Vertex_set::Self
Definition at line 31 of file Overlay_primitives.h.
typedef unsigned int Vertex_set::Size
Definition at line 33 of file Overlay_primitives.h.
typedef int Vertex_set::Value
Definition at line 32 of file Overlay_primitives.h.
Constructor & Destructor Documentation
Vertex_set::Vertex_set () inline
Definition at line 35 of file Overlay_primitives.h.
 : _pane(NULL), _ne(0) {}
Vertex_set::Vertex_set (const HEdge & h) explicit
Definition at line 37 of file Overlay_primitives.C.
References _ne, _nodes, _pane, RFC_Pane_base::base(), HEdge::id(), RFC_precondition, and Element_node_enumerator::size_of_nodes().
   : _pane(h.pane()), _ne(count_edges(h))
 {
   RFC_precondition ( _ne==3 || _ne==4);
   Element_node_enumerator ene( _pane->base(), h.id().eid());
   Size nn=ene.size_of_nodes();
   _nodes.resize(nn);
   for ( Size i=0; i<nn; ++i) _nodes[i] = ene[i];
   int r=h.id().lid();
   if (r>0) {
     std::rotate( &_nodes[0], &_nodes[r], &_nodes[_ne]);
     if (nn>_ne) std::rotate( &_nodes[_ne], &_nodes[_ne+r], &_nodes[_ne+_ne]);
   }
 }
Vertex_set::Vertex_set (const HEdge & h, Size)
Definition at line 54 of file Overlay_primitives.C.
References _ne, _nodes, HEdge::destination_l(), Node::id(), and HEdge::origin_l().
   : _pane(h.pane()), _ne(3) {
   _nodes.resize(_ne, -1);
   _nodes[0] = h.origin_l().id();
   _nodes[1] = h.destination_l().id();
 }
Member Function Documentation
Size Vertex_set::count_edges (const HEdge & e) const inline protected
Definition at line 47 of file Overlay_primitives.h.
References HEdge::next_l().
{
     Size i=0;
     HEdge h=e;
     do { ++i; } while ( (h=h.next_l())!= e);
     return i;
   }
int Vertex_set::operator[] (Size i) const inline
Definition at line 41 of file Overlay_primitives.h.
References _nodes.
 { return _nodes[i]; }
const RFC_Pane_overlay* Vertex_set::pane () const inline
Definition at line 40 of file Overlay_primitives.h.
References _pane.
Referenced by Point_set::operator[](), and Normal_set::operator[]().
 { return _pane; }
Size Vertex_set::size_of_edges () const inline
Definition at line 43 of file Overlay_primitives.h.
References _ne.
Referenced by Point_set::size_of_edges(), Normal_set::size_of_edges(), and Overlay_primitives::snap_blue_ridge_vertex().
 { return _ne; }
Size Vertex_set::size_of_nodes () const inline
Definition at line 44 of file Overlay_primitives.h.
References _nodes.
Referenced by Point_set::size_of_nodes(), and Normal_set::size_of_nodes().
 { return _nodes.size(); }
Member Data Documentation
Size Vertex_set::_ne protected
Definition at line 56 of file Overlay_primitives.h.
Referenced by size_of_edges(), and Vertex_set().
std::vector<int> Vertex_set::_nodes protected
Definition at line 55 of file Overlay_primitives.h.
Referenced by operator[](), size_of_nodes(), and Vertex_set().
const RFC_Pane_overlay* Vertex_set::_pane protected
Definition at line 54 of file Overlay_primitives.h.
Referenced by pane(), and Vertex_set().
The documentation for this class was generated from the following files:
Overlay_primitives.h
Overlay_primitives.C