IMPACT: SolverUtils::Mesh::NodalCoordinates Class Reference
SolverUtils::Mesh::NodalCoordinates Class Reference
Detailed Description
Definition at line 255 of file Mesh.H.
#include <Mesh.H>
Public Member Functions
NodalCoordinates ()
NodalCoordinates (Mesh::IndexType n)
NodalCoordinates (Mesh::IndexType n, double *data)
NodalCoordinates (Mesh::IndexType n, double *data, int stride)
NodalCoordinates (Mesh::IndexType n, double *xdata, double *ydata, double *zdata)
~NodalCoordinates ()
bool good () const
Mesh::IndexType size () const
Mesh::IndexType Size () const
double * Data ()
void destroy ()
void init ()
void init (Mesh::IndexType n)
void init (Mesh::IndexType n, double *data)
void init_node (Mesh::IndexType n, const GeoPrim::CPoint &)
void init_copy (Mesh::IndexType n, double *data)
void init_copy (Mesh::IndexType n, double *data, int stride)
void init_copy (Mesh::IndexType n, double *xdata, double *ydata, double *zdata)
void cleanup (double tol)
int NNodes () const
double & x (Mesh::IndexType n=1)
const double & x (Mesh::IndexType n=1) const
double & y (Mesh::IndexType n=1)
const double & y (Mesh::IndexType n=1) const
double & z (Mesh::IndexType n=1)
const double & z (Mesh::IndexType n=1) const
double * operator[] (Mesh::IndexType n)
const double * operator[] (Mesh::IndexType n) const
const GeoPrim::CPoint closest_point (const GeoPrim::CPoint &p) const
Mesh::IndexType closest_node (const GeoPrim::CPoint &p, double *dist_ptr=NULL) const
Protected Attributes
double * ncdata
Mesh::IndexType nnodes
Private Attributes
bool mydata
int verblevel
std::ostream * Out
std::ostream * Err
Friends
std::ostream & operator<< (std::ostream &oSt, const Mesh::NodalCoordinates &nc)
std::istream & operator>> (std::istream &iSt, Mesh::NodalCoordinates &nc)
Constructor & Destructor Documentation
SolverUtils::Mesh::NodalCoordinates::NodalCoordinates ()
Definition at line 15 of file Mesh.C.
     {
       ncdata = NULL;
       nnodes = 0;
       mydata = false;
     };
SolverUtils::Mesh::NodalCoordinates::NodalCoordinates (Mesh::IndexType n)
Definition at line 21 of file Mesh.C.
     {
       if(n > 0){
         ncdata = new double [3 * n];
         nnodes = n;
         mydata = true;
       }
       else {
         ncdata = NULL;
         nnodes = 0;
         mydata = false;
       }
     };
SolverUtils::Mesh::NodalCoordinates::NodalCoordinates (Mesh::IndexType n, double * data)
Definition at line 35 of file Mesh.C.
     {
       if((n > 0) && (data != NULL)){
         mydata = false;
         nnodes = n;
         ncdata = data;
       }
       else {
         ncdata = NULL;
         nnodes = 0;
         mydata = false;
       }
     };
SolverUtils::Mesh::NodalCoordinates::NodalCoordinates (Mesh::IndexType n, double * data, int stride)
Definition at line 49 of file Mesh.C.
{
       if(stride < 0) stride = 1;
       if ((n > 0) && (data != NULL)){
         init_copy(n,data,stride);
       }
       else {
         ncdata = NULL;
         nnodes = 0;
         mydata = false;
       }
     };
SolverUtils::Mesh::NodalCoordinates::NodalCoordinates (Mesh::IndexType n, double * xdata, double * ydata, double * zdata)
Definition at line 61 of file Mesh.C.
{
       if((n > 0) && xdata && ydata && zdata)
         init_copy(n,xdata,ydata,zdata);
       else {
         ncdata = NULL;
         nnodes = 0;
         mydata = false;
       }
     };
SolverUtils::Mesh::NodalCoordinates::~NodalCoordinates ()
Definition at line 71 of file Mesh.C.
 {destroy();};
Member Function Documentation
void SolverUtils::Mesh::NodalCoordinates::cleanup (double tol)
Definition at line 185 of file Mesh.C.
     {
       for(unsigned int i = 0;i < 3*nnodes;i++){
         if(std::abs(ncdata[i]) < tol)
           ncdata[i] = 0.0;
       }
     };
Mesh::IndexType SolverUtils::Mesh::NodalCoordinates::closest_node (const GeoPrim::CPoint & p, double * dist_ptr = NULL) const
Definition at line 125 of file Mesh.C.
References ncdata, and nnodes.
Referenced by SolverUtils::Mesh::FindPointInMesh(), and SolverUtils::Mesh::FindPointInMesh_2().
     {
       double dist = 1000000;
       Mesh::IndexType reti = 0;
       for(unsigned int i = 0;i < nnodes;i++){
         GeoPrim::CPoint testp(&ncdata[3*i]);
         double testd = (p-testp).norm();
         if(testd < dist){
           dist = testd;
           reti = i + 1;
         }
       }
       if(dist_ptr)
         *dist_ptr = dist;
       return(reti);
     };
const GeoPrim::CPoint SolverUtils::Mesh::NodalCoordinates::closest_point (const GeoPrim::CPoint & p) const
Definition at line 110 of file Mesh.C.
References ncdata, and nnodes.
     {
       double dist = 1000000;
       GeoPrim::CPoint retval;
       for(unsigned int i = 0;i < nnodes;i++){
         GeoPrim::CPoint testp(&ncdata[3*i]);
         double testd = (p-testp).norm();
         if(testd < dist){
           dist = testd;
           retval = testp;
         }
       }
       return(retval);
     };
double* SolverUtils::Mesh::NodalCoordinates::Data () inline
Definition at line 282 of file Mesh.H.
References ncdata.
 {return(ncdata);};
void SolverUtils::Mesh::NodalCoordinates::destroy ()
Definition at line 75 of file Mesh.C.
Referenced by SolverUtils::Mesh::MeshUtilityObject::~MeshUtilityObject().
{
       if(ncdata && mydata){
         delete [] ncdata;
         nnodes = 0;
         ncdata = NULL;
         mydata = false;
       }
     };
bool SolverUtils::Mesh::NodalCoordinates::good () const
Definition at line 72 of file Mesh.C.
 { return(ncdata ? true : false);};
void SolverUtils::Mesh::NodalCoordinates::init ()
Definition at line 83 of file Mesh.C.
Referenced by SolverUtils::Mesh::GenerateCartesianGrid(), and SolverUtils::Mesh::operator>>().
 {destroy();};
void SolverUtils::Mesh::NodalCoordinates::init (Mesh::IndexType n)
Definition at line 84 of file Mesh.C.
     {
       destroy();
       if(n > 0){
         ncdata = new double [3 * n];
         nnodes = n;
         mydata = true;
       }
     };
void SolverUtils::Mesh::NodalCoordinates::init (Mesh::IndexType n, double * data)
Definition at line 93 of file Mesh.C.
     {
       destroy();
       if(n > 0){
         ncdata = data;
         nnodes = n;
         mydata = false;
       }
     };
void SolverUtils::Mesh::NodalCoordinates::init_copy (Mesh::IndexType n, double * data)
Definition at line 142 of file Mesh.C.
Referenced by SolverUtils::PaneToUnstructuredMesh(), SolverUtils::Mesh::ReadWRLFromStream(), SolverUtils::Mesh::Skin(), and COM::TestModule::Step().
     {
       destroy();
       if(n > 0 && data){
         ncdata = new double [3*n];
         nnodes = n;
         mydata = true;
         std::memcpy(ncdata,data,n*sizeof(double)*3);
       }
     };
void SolverUtils::Mesh::NodalCoordinates::init_copy (Mesh::IndexType n, double * data, int stride)
Definition at line 153 of file Mesh.C.
     {
       destroy();
       if(n > 0 && data){
         ncdata = new double [3*n];
         nnodes = n;
         mydata = true;
         if(stride == 1)
           std::memcpy(ncdata,data,n*sizeof(double)*3);
         else {
           for(Mesh::IndexType i = 0;i < n;i++)
             for(Mesh::IndexType j = 0;j < 2;j++)
               std::memcpy((ncdata+(i*3))+j,((data+i)+(j*stride)),sizeof(double));
         }
       }
     };
void SolverUtils::Mesh::NodalCoordinates::init_copy (Mesh::IndexType n, double * xdata, double * ydata, double * zdata)
Definition at line 170 of file Mesh.C.
     {
       destroy();
       if(n > 0 && xdata && ydata && zdata){
         ncdata = new double [3*n];
         nnodes = n;
         mydata = true;
         for(Mesh::IndexType i = 0;i < n;i++){
           std::memcpy(ncdata+(i*3)  ,xdata+i,sizeof(double));
           std::memcpy(ncdata+(i*3)+1,ydata+i,sizeof(double));
           std::memcpy(ncdata+(i*3)+2,zdata+i,sizeof(double));
         }
       }
     };
void SolverUtils::Mesh::NodalCoordinates::init_node (Mesh::IndexType n, const GeoPrim::CPoint & point)
Definition at line 103 of file Mesh.C.
References SolverUtils::GeoPrim::CPoint::x(), SolverUtils::GeoPrim::CPoint::y(), and SolverUtils::GeoPrim::CPoint::z().
     {
       this->x(n) = point.x();
       this->y(n) = point.y();
       this->z(n) = point.z();
     };
int SolverUtils::Mesh::NodalCoordinates::NNodes () const inline
Definition at line 292 of file Mesh.H.
References nnodes.
Referenced by SolverUtils::Mesh::DisplaceNodalCoordinates(), COM::TestModule::InitSolver(), COM::TransferSolver::Setup(), COM::TestModule::Step(), SolverUtils::Mesh::writeVtkData(), SolverUtils::Mesh::WriteVTKToStream(), and SolverUtils::WriteVTKToStream().
 { return nnodes; };
double* SolverUtils::Mesh::NodalCoordinates::operator[] (Mesh::IndexType n) inline
Definition at line 324 of file Mesh.H.
References ncdata, and nnodes.
       {
         assert(!(n > nnodes || n == 0));
         return(&ncdata[3*(n-1)]);
       };
const double* SolverUtils::Mesh::NodalCoordinates::operator[] (Mesh::IndexType n) const inline
Definition at line 329 of file Mesh.H.
References ncdata, and nnodes.
       {
         assert(!(n > nnodes || n == 0));
         return(&ncdata[3*(n-1)]);
       };
Mesh::IndexType SolverUtils::Mesh::NodalCoordinates::size () const
Definition at line 73 of file Mesh.C.
Referenced by SolverUtils::Mesh::GetMeshBoxes(), SolverUtils::Mesh::operator<<(), and SolverUtils::Mesh::operator>>().
 { return(nnodes);};
Mesh::IndexType SolverUtils::Mesh::NodalCoordinates::Size () const
Definition at line 74 of file Mesh.C.
Referenced by SolverUtils::AgentToPane(), SolverUtils::FEM::SolutionData::Create(), SolverUtils::Mesh::FindElementsInBox(), SolverUtils::Mesh::GetCoordinateBounds(), SolverUtils::Mesh::MeshUtilityObject::NumberOfNodes(), SolverUtils::FEM::SolverAgent::ReportMeshToStream(), SolverUtils::Mesh::Skin(), SolverUtils::SurfaceMeshToPane(), and SolverUtils::VolumeMeshToPane().
 { return(nnodes);};
double& SolverUtils::Mesh::NodalCoordinates::x (Mesh::IndexType n = 1) inline
Definition at line 294 of file Mesh.H.
References ncdata, and nnodes.
Referenced by SolverUtils::Mesh::DisplaceNodalCoordinates(), SolverUtils::Mesh::GetCoordinateBounds(), and SolverUtils::Mesh::Skin().
       {
         assert(!(n > nnodes || n == 0));
         return(ncdata[(n-1)*3]);
       };
const double& SolverUtils::Mesh::NodalCoordinates::x (Mesh::IndexType n = 1) const inline
Definition at line 299 of file Mesh.H.
References ncdata, and nnodes.
       {
         assert(!(n > nnodes || n == 0));
         return(ncdata[(n-1)*3]);
       };
double& SolverUtils::Mesh::NodalCoordinates::y (Mesh::IndexType n = 1) inline
Definition at line 304 of file Mesh.H.
References ncdata, and nnodes.
Referenced by SolverUtils::Mesh::DisplaceNodalCoordinates(), SolverUtils::Mesh::GetCoordinateBounds(), and SolverUtils::Mesh::Skin().
       {
         assert(!(n > nnodes || n == 0));
         return(ncdata[(3*(n-1))+1]);
       };
const double& SolverUtils::Mesh::NodalCoordinates::y (Mesh::IndexType n = 1) const inline
Definition at line 309 of file Mesh.H.
References ncdata, and nnodes.
       {
         assert(!(n > nnodes || n == 0));
         return(ncdata[(3*(n-1))+1]);
       };
double& SolverUtils::Mesh::NodalCoordinates::z (Mesh::IndexType n = 1) inline
Definition at line 314 of file Mesh.H.
References ncdata, and nnodes.
Referenced by SolverUtils::Mesh::DisplaceNodalCoordinates(), SolverUtils::Mesh::GetCoordinateBounds(), and SolverUtils::Mesh::Skin().
       {
         assert(!(n > nnodes || n == 0));
         return(ncdata[(3*(n-1))+2]);
       };
const double& SolverUtils::Mesh::NodalCoordinates::z (Mesh::IndexType n = 1) const inline
Definition at line 319 of file Mesh.H.
References ncdata, and nnodes.
       {
         assert(!(n > nnodes || n == 0));
         return(ncdata[(3*(n-1))+2]);
       };
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & oSt, const Mesh::NodalCoordinates & nc) friend
Definition at line 2412 of file Mesh.C.
     {
       //  if(nc.size() == 0) return(oSt);
       oSt.setf(std::ios::scientific);
       oSt.setf(std::ios::showpoint);
       oSt << std::setprecision(10) << std::setiosflags(std::ios::left);
       oSt << nc.size();
       if(nc.size() > 0) oSt << "\n";
       for(Mesh::IndexType n = 1;n <= nc.size() ;n++){
         oSt << std::setw(16) << nc[n][0] << "\t"
             << std::setw(16) << nc[n][1] << "\t"
             << std::setw(16) << nc[n][2];
         if(n != nc.size())
           oSt << std::endl;
       }
       return (oSt);
     }
std::istream& operator>> (std::istream & iSt, Mesh::NodalCoordinates & nc) friend
Definition at line 2391 of file Mesh.C.
     {
       //  if(nc.size() == 0) return (iSt);
       std::string line;
       Mesh::IndexType nnodes;
       while(line.empty())
         std::getline(iSt,line);
       std::istringstream Istr(line);
       Istr >> nnodes;
       if(nnodes > 0){
         nc.init(nnodes);
         for(Mesh::IndexType n = 1;n <= nc.size();n++){
           double *inPtr = nc[n];
           std::getline(iSt,line);
           std::istringstream Istr2(line);
           Istr2 >> inPtr[0] >> inPtr[1] >> inPtr[2];
         }
       }
       return(iSt);
     }
Member Data Documentation
std::ostream* SolverUtils::Mesh::NodalCoordinates::Err private
Definition at line 264 of file Mesh.H.
bool SolverUtils::Mesh::NodalCoordinates::mydata private
Definition at line 261 of file Mesh.H.
double* SolverUtils::Mesh::NodalCoordinates::ncdata protected
Definition at line 266 of file Mesh.H.
Referenced by closest_node(), closest_point(), Data(), operator[](), x(), y(), and z().
Mesh::IndexType SolverUtils::Mesh::NodalCoordinates::nnodes protected
Definition at line 267 of file Mesh.H.
Referenced by closest_node(), closest_point(), NNodes(), operator[](), x(), y(), and z().
std::ostream* SolverUtils::Mesh::NodalCoordinates::Out private
Definition at line 263 of file Mesh.H.
int SolverUtils::Mesh::NodalCoordinates::verblevel private
Definition at line 262 of file Mesh.H.
The documentation for this class was generated from the following files:
Mesh.H
Mesh.C