IMPACT: IRAD::Sys::Net::Server Class Reference
IRAD::Sys::Net::Server Class Reference
Detailed Description
Definition at line 30 of file NetUtils.H.
#include <NetUtils.H>
Public Member Functions
Server ()
struct sockaddr_in & Address ()
struct sockaddr_in Address () const
std::vector< int > & ClientDescriptors ()
const std::vector< int > & ClientDescriptors () const
int & Descriptor ()
int Descriptor () const
std::vector< struct sockaddr_in > & ClientAddresses ()
const std::vector< struct
sockaddr_in > & ClientAddresses () const
int SimpleInit (int port=0)
int Accept ()
int CloseAll ()
~Server ()
Private Attributes
int _server_descriptor
struct sockaddr_in _server_addy
std::vector< int > _client_descriptors
std::vector< struct sockaddr_in > _client_addys
Constructor & Destructor Documentation
IRAD::Sys::Net::Server::Server () inline
Definition at line 37 of file NetUtils.H.
References _client_addys, _client_descriptors, and _server_addy.
                  : _server_descriptor(-1)
         {
           std::memset(&_server_addy,0,sizeof(struct sockaddr_in));
           _client_descriptors.resize(0);
           _client_addys.resize(0);
         };
IRAD::Sys::Net::Server::~Server () inline
Definition at line 98 of file NetUtils.H.
References CloseAll().
 { CloseAll(); };
Member Function Documentation
int IRAD::Sys::Net::Server::Accept () inline
Definition at line 75 of file NetUtils.H.
References _client_addys, _client_descriptors, and _server_descriptor.
Referenced by main(), and IRAD::TestTCPInterface().
         {
           struct sockaddr_in client_addy;
           socklen_t addysize = sizeof(struct sockaddr_in);
           int new_descriptor = accept(_server_descriptor,reinterpret_cast<sockaddr *>(&client_addy),
                                       &addysize);
           if(new_descriptor < 0){
             if((errno != EAGAIN) || (errno != EWOULDBLOCK))
               perror("Sys::Net::Server::accept");
           }
           else{
             _client_descriptors.push_back(new_descriptor);
             _client_addys.push_back(client_addy);
           }
           return(new_descriptor);
         };
struct sockaddr_in& IRAD::Sys::Net::Server::Address () inline
Definition at line 43 of file NetUtils.H.
References _server_addy.
 { return (_server_addy); };
struct sockaddr_in IRAD::Sys::Net::Server::Address () const inline
Definition at line 44 of file NetUtils.H.
References _server_addy.
 { return (_server_addy); };
std::vector<struct sockaddr_in>& IRAD::Sys::Net::Server::ClientAddresses () inline
Definition at line 49 of file NetUtils.H.
References _client_addys.
 { return (_client_addys); };
const std::vector<struct sockaddr_in>& IRAD::Sys::Net::Server::ClientAddresses () const inline
Definition at line 50 of file NetUtils.H.
References _client_addys.
 { return(_client_addys); };
std::vector<int>& IRAD::Sys::Net::Server::ClientDescriptors () inline
Definition at line 45 of file NetUtils.H.
References _client_descriptors.
 { return(_client_descriptors); };
const std::vector<int>& IRAD::Sys::Net::Server::ClientDescriptors () const inline
Definition at line 46 of file NetUtils.H.
References _client_descriptors.
 { return(_client_descriptors); };
int IRAD::Sys::Net::Server::CloseAll () inline
Definition at line 91 of file NetUtils.H.
References _client_descriptors.
Referenced by ~Server().
         {
           std::vector<int>::iterator fdi = _client_descriptors.begin();
           while(fdi != _client_descriptors.end())
             close(*fdi++);
           return(0);
         };
int& IRAD::Sys::Net::Server::Descriptor () inline
Definition at line 47 of file NetUtils.H.
References _server_descriptor.
Referenced by main(), and IRAD::TestTCPInterface().
 { return(_server_descriptor); };
int IRAD::Sys::Net::Server::Descriptor () const inline
Definition at line 48 of file NetUtils.H.
References _server_descriptor.
 { return(_server_descriptor); };
int IRAD::Sys::Net::Server::SimpleInit (int port = 0) inline
Definition at line 51 of file NetUtils.H.
References _server_addy, and _server_descriptor.
Referenced by main(), and IRAD::TestTCPInterface().
         {
           _server_descriptor = socket(AF_INET,SOCK_STREAM,0);
           if(_server_descriptor < 0){
             perror("Sys::Net::Server::SimpleInit::socket");
             return(-1);
           }
           if(port <= 0)
             port = 8044; // should not collide with much ... if anything
           _server_addy.sin_family = AF_INET;
           _server_addy.sin_addr.s_addr = htonl(INADDR_ANY);
           _server_addy.sin_port = htons(port);
           int retval = bind(_server_descriptor,reinterpret_cast<const sockaddr *>(&_server_addy),
                             sizeof(struct sockaddr_in));
           if(retval < 0){
             perror("Sys::Net::Server::SimpleInit::bind");
             return(-1);
           }
           if(listen(_server_descriptor,1)){
             perror("Sys::Net::Server::SimpleInit::listen");
             return(-1);
           }
           return(0);
         };
Member Data Documentation
std::vector<struct sockaddr_in> IRAD::Sys::Net::Server::_client_addys private
Definition at line 35 of file NetUtils.H.
Referenced by Accept(), ClientAddresses(), and Server().
std::vector<int> IRAD::Sys::Net::Server::_client_descriptors private
Definition at line 34 of file NetUtils.H.
Referenced by Accept(), ClientDescriptors(), CloseAll(), and Server().
struct sockaddr_in IRAD::Sys::Net::Server::_server_addy private
Definition at line 33 of file NetUtils.H.
Referenced by Address(), Server(), and SimpleInit().
int IRAD::Sys::Net::Server::_server_descriptor private
Definition at line 32 of file NetUtils.H.
Referenced by Accept(), Descriptor(), and SimpleInit().
The documentation for this class was generated from the following file:
NetUtils.H