IMPACT: SolverUtils::GeoPrim::C3Point Class Reference
SolverUtils::GeoPrim::C3Point Class Reference
/brief Cartesian 3 Point
Detailed Description
Definition at line 476 of file GeoPrimitives.H.
#include <GeoPrimitives.H>
Public Member Functions
C3Point ()
C3Point (const GeoPrim::CPoint &inp)
C3Point (const GeoPrim::C3Point &inp)
C3Point (double ix, double iy, double iz=0.0)
C3Point (double *a)
C3Point (const double *a)
~C3Point ()
C3Point & Copy (const C3Point &v)
C3Point & Init (const double *a)
C3Point & Init (const C3Point &v)
C3Point & Init (double ix, double iy, double iz)
C3Point & Init ()
C3Point & Clear ()
double Norm () const
double Mag () const
double Mag2 () const
C3Point & Normalize ()
C3Point Unit () const
double operator* (const C3Point &v2) const
Dot Product.
C3Point operator* (double num) const
Scaling.
C3Point & operator*= (double num)
C3Point operator% (const C3Point &v2) const
Cross Product.
C3Point & operator= (const C3Point &v2)
C3Point & operator%= (const C3Point &v2)
C3Point operator+ (const C3Point &v2) const
C3Point operator- (const C3Point &v2) const
C3Point & operator+= (const C3Point &v2)
C3Point & operator-= (const C3Point &v2)
double & x ()
double x () const
C3Point & x (double i)
double & y ()
double y () const
C3Point & y (double i)
double & z ()
double z () const
C3Point & z (double i)
const double & operator[] (unsigned int i) const
double & operator[] (unsigned int i)
bool operator== (const C3Point &v) const
bool operator< (const C3Point &v) const
bool operator> (const C3Point &v) const
bool operator<= (const C3Point &v) const
bool operator>= (const C3Point &v) const
void DestroyData ()
void SetData (double *d)
double * Data ()
const double * Data () const
Protected Attributes
double * V
Private Member Functions
void _create ()
void _destroy ()
Private Attributes
bool _mydata
Friends
C3Point operator* (double, const C3Point &)
std::ostream & operator<< (std::ostream &, const C3Point &)
std::istream & operator>> (std::istream &, C3Point &)
Constructor & Destructor Documentation
SolverUtils::GeoPrim::C3Point::C3Point () inline
Definition at line 485 of file GeoPrimitives.H.
References _create(), and V.
     {
       _create();
       V[0] = V[1] = V[2] = 0.;
     };
SolverUtils::GeoPrim::C3Point::C3Point (const GeoPrim::CPoint & inp) inline
Definition at line 490 of file GeoPrimitives.H.
References _create(), V, SolverUtils::GeoPrim::CPoint::x(), SolverUtils::GeoPrim::CPoint::y(), and SolverUtils::GeoPrim::CPoint::z().
     {
       _create();
       V[0] = inp.x();
       V[1] = inp.y();
       V[2] = inp.z();
     };
SolverUtils::GeoPrim::C3Point::C3Point (const GeoPrim::C3Point & inp) inline
Definition at line 497 of file GeoPrimitives.H.
References _create(), V, x(), y(), and z().
     {
       _create();
       V[0] = inp.x();
       V[1] = inp.y();
       V[2] = inp.z();
     };
SolverUtils::GeoPrim::C3Point::C3Point (double ix, double iy, double iz = 0.0) inline
Definition at line 504 of file GeoPrimitives.H.
References _create(), and V.
     {
       _create();
       V[0] = ix;
       V[1] = iy;
       V[2] = iz;
     };
SolverUtils::GeoPrim::C3Point::C3Point (double * a) inline
Definition at line 516 of file GeoPrimitives.H.
References _mydata, and V.
     {
       _mydata = false;
       V = a;
     };
SolverUtils::GeoPrim::C3Point::C3Point (const double * a) inline
Definition at line 521 of file GeoPrimitives.H.
References _create(), and V.
     {
       _create();
       V[0] = a[0];
       V[1] = a[1];
       V[2] = a[2];
     };
SolverUtils::GeoPrim::C3Point::~C3Point () inline
Definition at line 533 of file GeoPrimitives.H.
References _destroy().
     {
       _destroy();
     };
Member Function Documentation
void SolverUtils::GeoPrim::C3Point::_create () inline private
Definition at line 758 of file GeoPrimitives.H.
References _mydata, and V.
Referenced by C3Point().
     {
       V = new double [3];
       _mydata = true;
     };
void SolverUtils::GeoPrim::C3Point::_destroy () inline private
Definition at line 763 of file GeoPrimitives.H.
References _mydata, and V.
Referenced by DestroyData(), and ~C3Point().
     {
       if(_mydata){
         delete [] V;
         _mydata = false;
         V = NULL;
       }
     };
C3Point& SolverUtils::GeoPrim::C3Point::Clear () inline
Definition at line 575 of file GeoPrimitives.H.
References V.
     {
       V[0] = V[1] = V[2] = 0.0;
       return(*this);
     };
C3Point& SolverUtils::GeoPrim::C3Point::Copy (const C3Point & v) inline
Definition at line 537 of file GeoPrimitives.H.
References V.
Referenced by SolverUtils::GeoPrim::C3Facet::_copycreate_point(), and operator=().
     {
       V[0] = v.V[0];
       V[1] = v.V[1];
       V[2] = v.V[2];
       return(*this);
     };
double* SolverUtils::GeoPrim::C3Point::Data () inline
Definition at line 755 of file GeoPrimitives.H.
References V.
 { return(V); };
const double* SolverUtils::GeoPrim::C3Point::Data () const inline
Definition at line 756 of file GeoPrimitives.H.
References V.
 { return(V); };
void SolverUtils::GeoPrim::C3Point::DestroyData () inline
Definition at line 750 of file GeoPrimitives.H.
References _destroy().
 { _destroy(); };
C3Point& SolverUtils::GeoPrim::C3Point::Init (const double * a) inline
Definition at line 544 of file GeoPrimitives.H.
References V.
Referenced by SolverUtils::Mesh::GenericElement::Centroid().
     {
       V[0] = a[0];
       V[1] = a[1];
       V[2] = a[2];
       return(*this);
     };
C3Point& SolverUtils::GeoPrim::C3Point::Init (const C3Point & v) inline
Definition at line 551 of file GeoPrimitives.H.
References V.
     {
       V[0] = v[0];
       V[1] = v[1];
       V[2] = v[2];
       return(*this);
     };
C3Point& SolverUtils::GeoPrim::C3Point::Init (double ix, double iy, double iz) inline
Definition at line 558 of file GeoPrimitives.H.
References V.
     {
       V[0] = ix;
       V[1] = iy;
       V[2] = iz;
       return(*this);
     };
C3Point& SolverUtils::GeoPrim::C3Point::Init () inline
Definition at line 570 of file GeoPrimitives.H.
References V.
     {
       V[0] = V[1] = V[2] = 0.0;
       return(*this);
     };
double SolverUtils::GeoPrim::C3Point::Mag () const inline
Definition at line 584 of file GeoPrimitives.H.
References Norm().
     {
       return (Norm());
     };
double SolverUtils::GeoPrim::C3Point::Mag2 () const inline
Definition at line 588 of file GeoPrimitives.H.
References V.
Referenced by operator<(), and operator>().
     {
       return ((V[0]*V[0])+(V[1]*V[1])+(V[2]*V[2]));
     };
double SolverUtils::GeoPrim::C3Point::Norm () const inline
Definition at line 580 of file GeoPrimitives.H.
References V.
Referenced by Mag(), and Normalize().
     {
       return(sqrt((V[0] * V[0]) + (V[1] * V[1]) + (V[2] * V[2])));
     };
C3Point& SolverUtils::GeoPrim::C3Point::Normalize () inline
Definition at line 592 of file GeoPrimitives.H.
References Norm(), and V.
Referenced by Unit().
     {
       double n = Norm();
       V[0] /= n;
       V[1] /= n;
       V[2] /= n;
       return(*this);
     };
C3Point SolverUtils::GeoPrim::C3Point::operator% (const C3Point & v2) const inline
Definition at line 632 of file GeoPrimitives.H.
References V.
     {
       C3Point v;
       v.V[0] = ((v2.V[2] * V[1]) - (v2.V[1] * V[2]));
       v.V[1] = ((v2.V[0] * V[2]) - (v2.V[2] * V[0]));
       v.V[2] = ((v2.V[1] * V[0]) - (v2.V[0] * V[1]));
       return(v);
     };
C3Point& SolverUtils::GeoPrim::C3Point::operator%= (const C3Point & v2) inline
Definition at line 644 of file GeoPrimitives.H.
References V.
     {
       double t0 = V[0];
       double t1 = V[1];
       double t2 = V[2];
       V[0] = ((v2.V[2] * t1) - (v2.V[1] * t2));
       V[1] = ((v2.V[0] * t2) - (v2.V[2] * t0));
       V[2] = ((v2.V[1] * t0) - (v2.V[0] * t1));
       return(*this);
     };
double SolverUtils::GeoPrim::C3Point::operator* (const C3Point & v2) const inline
Definition at line 608 of file GeoPrimitives.H.
References V.
     {
       return((V[0] * v2.V[0]) +
              (V[1] * v2.V[1]) +
              (V[2] * v2.V[2]));
     };
C3Point SolverUtils::GeoPrim::C3Point::operator* (double num) const inline
Definition at line 617 of file GeoPrimitives.H.
References V.
     {
       C3Point rv(num*V[0],num*V[1],num*V[2]);
       return(rv);
     };
C3Point& SolverUtils::GeoPrim::C3Point::operator*= (double num) inline
Definition at line 622 of file GeoPrimitives.H.
References V.
     {
       V[0] *= num;
       V[1] *= num;
       V[2] *= num;
       return(*this);
     };
C3Point SolverUtils::GeoPrim::C3Point::operator+ (const C3Point & v2) const inline
Definition at line 654 of file GeoPrimitives.H.
References V.
     {
       C3Point v(V[0] + v2.V[0], V[1] + v2.V[1], V[2] + v2.V[2]);
       return(v);
     };
C3Point& SolverUtils::GeoPrim::C3Point::operator+= (const C3Point & v2) inline
Definition at line 663 of file GeoPrimitives.H.
References V.
     {
       V[0] += v2.V[0];
       V[1] += v2.V[1];
       V[2] += v2.V[2];
       return(*this);
     };
C3Point SolverUtils::GeoPrim::C3Point::operator- (const C3Point & v2) const inline
Definition at line 659 of file GeoPrimitives.H.
     {
       return((*this) + (-1.0 * v2));
     };
C3Point& SolverUtils::GeoPrim::C3Point::operator-= (const C3Point & v2) inline
Definition at line 670 of file GeoPrimitives.H.
References V.
     {
       V[0] -= v2.V[0];
       V[1] -= v2.V[1];
       V[2] -= v2.V[2];
       return(*this);
     };
bool SolverUtils::GeoPrim::C3Point::operator< (const C3Point & v) const inline
Definition at line 732 of file GeoPrimitives.H.
References Mag2().
     {
       return (Mag2() < v.Mag2());
     };
bool SolverUtils::GeoPrim::C3Point::operator<= (const C3Point & v) const inline
Definition at line 740 of file GeoPrimitives.H.
     {
       return ( (*this < v) ||
                (*this == v));
     };
C3Point& SolverUtils::GeoPrim::C3Point::operator= (const C3Point & v2) inline
Definition at line 640 of file GeoPrimitives.H.
References Copy().
     {
       return(Copy(v2));
     };
bool SolverUtils::GeoPrim::C3Point::operator== (const C3Point & v) const inline
Definition at line 726 of file GeoPrimitives.H.
References SolverUtils::GeoPrim::TOL, and V.
     {
       return( (fabs(V[0] - v.V[0]) < TOL) &&
               (fabs(V[1] - v.V[1]) < TOL) &&
               (fabs(V[2] - v.V[2]) < TOL) );
     };
bool SolverUtils::GeoPrim::C3Point::operator> (const C3Point & v) const inline
Definition at line 736 of file GeoPrimitives.H.
References Mag2().
     {
       return (Mag2() > v.Mag2());
     };
bool SolverUtils::GeoPrim::C3Point::operator>= (const C3Point & v) const inline
Definition at line 745 of file GeoPrimitives.H.
     {
       return ( (*this > v) ||
                (*this == v) );
     };
const double& SolverUtils::GeoPrim::C3Point::operator[] (unsigned int i) const inline
Definition at line 716 of file GeoPrimitives.H.
References V.
     {
       assert(i>0 && i<4);
       return(V[i-1]);
     };
double& SolverUtils::GeoPrim::C3Point::operator[] (unsigned int i) inline
Definition at line 721 of file GeoPrimitives.H.
References V.
     {
       assert(i>0 && i<4);
       return(V[i-1]);
     };
void SolverUtils::GeoPrim::C3Point::SetData (double * d) inline
Definition at line 751 of file GeoPrimitives.H.
References _mydata, and V.
{
       V = d;
       _mydata = false;
     };
C3Point SolverUtils::GeoPrim::C3Point::Unit () const inline
Definition at line 600 of file GeoPrimitives.H.
References Normalize().
     {
       C3Point v(*this);
       return(v.Normalize());
     };
double& SolverUtils::GeoPrim::C3Point::x () inline
Definition at line 677 of file GeoPrimitives.H.
References V.
Referenced by SolverUtils::GeoPrim::C3Box::AddPoint(), SolverUtils::GeoPrim::C3Box::around(), SolverUtils::GeoPrim::C3Box::C3Box(), SolverUtils::GeoPrim::C3Centroid(), SolverUtils::GeoPrim::C3Plane::C3Plane(), C3Point(), SolverUtils::GeoPrim::C3Vector::C3Vector(), SolverUtils::GeoPrim::C3Box::collide(), SolverUtils::GeoPrim::C3Box::contains(), SolverUtils::GeoPrim::C3Plane::contains_point(), SolverUtils::GeoPrim::C3Plane::D(), SolverUtils::GeoPrim::Distance(), SolverUtils::GeoPrim::C3Box::empty(), SolverUtils::Mesh::GenerateCartesianGrid(), SolverUtils::GeoPrim::C3LineSegment::has_point(), SolverUtils::GeoPrim::C3Box::init(), SolverUtils::GeoPrim::C3Box::intersect(), SolverUtils::GeoPrim::C3Box::merge(), SolverUtils::GeoPrim::operator*(), and SolverUtils::GeoPrim::operator<<().
     {
       return(V[0]);
     };
double SolverUtils::GeoPrim::C3Point::x () const inline
Definition at line 681 of file GeoPrimitives.H.
References V.
     {
       return(V[0]);
     };
C3Point& SolverUtils::GeoPrim::C3Point::x (double i) inline
Definition at line 685 of file GeoPrimitives.H.
References V.
     {
       V[0] = i;
       return(*this);
     };
double& SolverUtils::GeoPrim::C3Point::y () inline
Definition at line 690 of file GeoPrimitives.H.
References V.
Referenced by SolverUtils::GeoPrim::C3Box::AddPoint(), SolverUtils::GeoPrim::C3Box::around(), SolverUtils::GeoPrim::C3Box::C3Box(), SolverUtils::GeoPrim::C3Plane::C3Plane(), C3Point(), SolverUtils::GeoPrim::C3Vector::C3Vector(), SolverUtils::GeoPrim::C3Box::collide(), SolverUtils::GeoPrim::C3Box::contains(), SolverUtils::GeoPrim::C3Plane::contains_point(), SolverUtils::GeoPrim::C3Plane::D(), SolverUtils::GeoPrim::Distance(), SolverUtils::GeoPrim::C3Box::empty(), SolverUtils::Mesh::GenerateCartesianGrid(), SolverUtils::GeoPrim::C3LineSegment::has_point(), SolverUtils::GeoPrim::C3Box::init(), SolverUtils::GeoPrim::C3Box::intersect(), SolverUtils::GeoPrim::C3Box::merge(), SolverUtils::GeoPrim::operator*(), and SolverUtils::GeoPrim::operator<<().
     {
       return(V[1]);
     };
double SolverUtils::GeoPrim::C3Point::y () const inline
Definition at line 694 of file GeoPrimitives.H.
References V.
     {
       return(V[1]);
     };
C3Point& SolverUtils::GeoPrim::C3Point::y (double i) inline
Definition at line 698 of file GeoPrimitives.H.
References V.
     {
       V[1] = i;
       return(*this);
     };
double& SolverUtils::GeoPrim::C3Point::z () inline
Definition at line 703 of file GeoPrimitives.H.
References V.
Referenced by SolverUtils::GeoPrim::C3Box::AddPoint(), SolverUtils::GeoPrim::C3Box::around(), SolverUtils::GeoPrim::C3Box::C3Box(), SolverUtils::GeoPrim::C3Plane::C3Plane(), C3Point(), SolverUtils::GeoPrim::C3Vector::C3Vector(), SolverUtils::GeoPrim::C3Box::collide(), SolverUtils::GeoPrim::C3Box::contains(), SolverUtils::GeoPrim::C3Plane::contains_point(), SolverUtils::GeoPrim::C3Plane::D(), SolverUtils::GeoPrim::Distance(), SolverUtils::GeoPrim::C3Box::empty(), SolverUtils::Mesh::GenerateCartesianGrid(), SolverUtils::GeoPrim::C3LineSegment::has_point(), SolverUtils::GeoPrim::C3Box::init(), SolverUtils::GeoPrim::C3Box::intersect(), SolverUtils::GeoPrim::C3Box::merge(), SolverUtils::GeoPrim::operator*(), and SolverUtils::GeoPrim::operator<<().
     {
       return(V[2]);
     };
double SolverUtils::GeoPrim::C3Point::z () const inline
Definition at line 707 of file GeoPrimitives.H.
References V.
     {
       return(V[2]);
     };
C3Point& SolverUtils::GeoPrim::C3Point::z (double i) inline
Definition at line 711 of file GeoPrimitives.H.
References V.
     {
       V[2] = i;
       return(*this);
     };
Friends And Related Function Documentation
C3Point operator* (double scalar, const C3Point & p) friend
Definition at line 154 of file GeoPrimitives.C.
   {
     GeoPrim::C3Point rv(p);
     rv.x() *= scalar;
     rv.y() *= scalar;
     rv.z() *= scalar;
     return(rv);
   }
std::ostream& operator<< (std::ostream & oS, const C3Point & p) friend
Definition at line 117 of file GeoPrimitives.C.
   {
     oS << p.x() << "  " << p.y() << "  " << p.z();
     return(oS);
   }
std::istream& operator>> (std::istream & iS, GeoPrim::C3Point & p) friend
Definition at line 125 of file GeoPrimitives.C.
   {
     iS >> p[0] >> p[1] >> p[2];
     return(iS);
   }
Member Data Documentation
bool SolverUtils::GeoPrim::C3Point::_mydata private
Definition at line 481 of file GeoPrimitives.H.
Referenced by _create(), _destroy(), C3Point(), and SetData().
double* SolverUtils::GeoPrim::C3Point::V protected
Definition at line 483 of file GeoPrimitives.H.
Referenced by _create(), _destroy(), C3Point(), Clear(), Copy(), Data(), Init(), Mag2(), Norm(), Normalize(), operator%(), operator%=(), operator*(), operator*=(), operator+(), operator+=(), operator-=(), operator==(), operator[](), SetData(), x(), y(), and z().
The documentation for this class was generated from the following file:
GeoPrimitives.H