IMPACT: SolverUtils::TransferObject Class Reference
SolverUtils::TransferObject Class Reference
Detailed Description
Definition at line 277 of file InterfaceLayer.H.
#include <InterfaceLayer.H>
Public Member Functions
TransferObject (const std::string &name)
int Overlay (const std::string &w1, const std::string &w2)
void SetVerbosity (int level)
int Transfer (const std::string &src_att, const std::string &trg_att, bool reverse=false)
int Interpolate (const std::string &src_att, const std::string &trg_att, bool reverse=false)
int TransferLoad (const std::string &src_att, const std::string &trg_att, bool reverse=false)
~TransferObject ()
Private Attributes
std::string myname
std::string win1
std::string win2
int readhandle
int overlayhandle
int transferhandle
int interphandle
int loadtranshandle
Constructor & Destructor Documentation
SolverUtils::TransferObject::TransferObject (const std::string & name) inline
Definition at line 288 of file InterfaceLayer.H.
References COM_get_function_handle(), SolverUtils::COM_LOAD_MODULE_STATIC_DYNAMIC(), interphandle, loadtranshandle, myname, overlayhandle, readhandle, and transferhandle.
                                           :
       myname(name)
     {
       COM_LOAD_MODULE_STATIC_DYNAMIC(SurfX,myname.c_str());
       readhandle      = COM_get_function_handle((myname+std::string(".read_overlay")).c_str());
       overlayhandle   = COM_get_function_handle((myname+std::string(".overlay")).c_str());
       interphandle    = COM_get_function_handle((myname+std::string(".interpolate")).c_str());
       transferhandle  = COM_get_function_handle((myname+std::string(".least_squares_transfer")).c_str());
       loadtranshandle = COM_get_function_handle((myname+std::string(".load_transfer")).c_str());
     };
SolverUtils::TransferObject::~TransferObject () inline
Definition at line 352 of file InterfaceLayer.H.
References COM_UNLOAD_MODULE_STATIC_DYNAMIC, and myname.
 { COM_UNLOAD_MODULE_STATIC_DYNAMIC(SurfX,myname.c_str()); };
Member Function Documentation
int SolverUtils::TransferObject::Interpolate (const std::string & src_att, const std::string & trg_att, bool reverse = false) inline
Definition at line 326 of file InterfaceLayer.H.
References SolverUtils::COM_call_function(), COM_get_dataitem_handle(), interphandle, win1, and win2.
     {
       std::string srcwin((reverse ? win2 : win1));
       std::string trgwin((reverse ? win1 : win2));
       std::string srcatt = srcwin + "." + src_att;
       std::string trgatt = trgwin + "." + trg_att;
       int src_handle = COM_get_dataitem_handle(srcatt.c_str());
       int trg_handle = COM_get_dataitem_handle(trgatt.c_str());
       if((src_handle <= 0) || (trg_handle <= 0))
         return(-1);
       COM_call_function(interphandle,&src_handle,&trg_handle);
       return(0);
     };
int SolverUtils::TransferObject::Overlay (const std::string & w1, const std::string & w2) inline
Definition at line 298 of file InterfaceLayer.H.
References SolverUtils::COM_call_function(), COM_get_dataitem_handle(), overlayhandle, win1, and win2.
Referenced by COM::TestingObject< ResultsType >::Test__LinearDataTransfer(), and COM::TestingObject< ResultsType >::Test__QuadraticDataTransfer().
     {
       win1 = w1;
       win2 = w2;
       int mesh1 = COM_get_dataitem_handle((w1+".mesh"));
       int mesh2 = COM_get_dataitem_handle((w2+".mesh"));
       if(mesh1 <= 0 || mesh2 <= 0)
         return(-1);
       COM_call_function(overlayhandle,&mesh1,&mesh2);
       return(0);
     };
void SolverUtils::TransferObject::SetVerbosity (int level) inline
Definition at line 309 of file InterfaceLayer.H.
References SolverUtils::COM_call_function(), COM_get_function_handle(), and myname.
     {
       COM_call_function(COM_get_function_handle((myname+".set_verbose").c_str()),&level);
     };
int SolverUtils::TransferObject::Transfer (const std::string & src_att, const std::string & trg_att, bool reverse = false) inline
Definition at line 313 of file InterfaceLayer.H.
References SolverUtils::COM_call_function(), COM_get_dataitem_handle(), transferhandle, win1, and win2.
Referenced by COM::TestingObject< ResultsType >::Test__LinearDataTransfer(), and COM::TestingObject< ResultsType >::Test__QuadraticDataTransfer().
     {
       std::string srcwin((reverse ? win2 : win1));
       std::string trgwin((reverse ? win1 : win2));
       std::string srcatt = srcwin + "." + src_att;
       std::string trgatt = trgwin + "." + trg_att;
       int src_handle = COM_get_dataitem_handle(srcatt.c_str());
       int trg_handle = COM_get_dataitem_handle(trgatt.c_str());
       if((src_handle <= 0) || (trg_handle <= 0))
         return(-1);
       COM_call_function(transferhandle,&src_handle,&trg_handle);
       return(0);
     };
int SolverUtils::TransferObject::TransferLoad (const std::string & src_att, const std::string & trg_att, bool reverse = false) inline
Definition at line 339 of file InterfaceLayer.H.
References SolverUtils::COM_call_function(), COM_get_dataitem_handle(), loadtranshandle, win1, and win2.
     {
       std::string srcwin((reverse ? win2 : win1));
       std::string trgwin((reverse ? win1 : win2));
       std::string srcatt = srcwin + "." + src_att;
       std::string trgatt = trgwin + "." + trg_att;
       int src_handle = COM_get_dataitem_handle(srcatt.c_str());
       int trg_handle = COM_get_dataitem_handle(trgatt.c_str());
       if((src_handle <= 0) || (trg_handle <= 0))
         return(-1);
       COM_call_function(loadtranshandle,&src_handle,&trg_handle);
       return(0);
     };
Member Data Documentation
int SolverUtils::TransferObject::interphandle private
Definition at line 285 of file InterfaceLayer.H.
Referenced by Interpolate(), and TransferObject().
int SolverUtils::TransferObject::loadtranshandle private
Definition at line 286 of file InterfaceLayer.H.
Referenced by TransferLoad(), and TransferObject().
std::string SolverUtils::TransferObject::myname private
Definition at line 279 of file InterfaceLayer.H.
Referenced by SetVerbosity(), TransferObject(), and ~TransferObject().
int SolverUtils::TransferObject::overlayhandle private
Definition at line 283 of file InterfaceLayer.H.
Referenced by Overlay(), and TransferObject().
int SolverUtils::TransferObject::readhandle private
Definition at line 282 of file InterfaceLayer.H.
Referenced by TransferObject().
int SolverUtils::TransferObject::transferhandle private
Definition at line 284 of file InterfaceLayer.H.
Referenced by Transfer(), and TransferObject().
std::string SolverUtils::TransferObject::win1 private
Definition at line 280 of file InterfaceLayer.H.
Referenced by Interpolate(), Overlay(), Transfer(), and TransferLoad().
std::string SolverUtils::TransferObject::win2 private
Definition at line 281 of file InterfaceLayer.H.
Referenced by Interpolate(), Overlay(), Transfer(), and TransferLoad().
The documentation for this class was generated from the following file:
InterfaceLayer.H