IMPACT: SolverUtils::GeoPrim::CPlane Class Reference
SolverUtils::GeoPrim::CPlane Class Reference
Detailed Description
Definition at line 1996 of file GeoPrimitives.H.
#include <GeoPrimitives.H>
Public Member Functions
CPlane ()
CPlane (const CPoint &p1, const CPoint &p2, const CPoint &p3)
CPlane (const CVector &N, const CPoint &P)
CPlane (const CPlane &plane)
CPlane (const std::vector< CPoint > &vec)
CPlane & operator= (const CPlane &plane)
double A () const
double B () const
double C () const
double D () const
CVector & normal ()
const CVector & normal () const
CPoint & point ()
const CPoint & point () const
bool contains_point (const CPoint &P) const
bool operator== (const CPlane &plane) const
Protected Attributes
CVector n
CPoint p
Constructor & Destructor Documentation
SolverUtils::GeoPrim::CPlane::CPlane () inline
Definition at line 2001 of file GeoPrimitives.H.
 {};
SolverUtils::GeoPrim::CPlane::CPlane (const CPoint & p1, const CPoint & p2, const CPoint & p3) inline
Definition at line 2002 of file GeoPrimitives.H.
References A(), B(), C(), n, SolverUtils::GeoPrim::CVector::normalize(), SolverUtils::GeoPrim::CPoint::x(), SolverUtils::GeoPrim::CVector::x(), SolverUtils::GeoPrim::CPoint::y(), and SolverUtils::GeoPrim::CPoint::z().
       : p(p1)
     {
       double A = p1.y()*(p2.z() - p3.z()) + p2.y()*(p3.z() - p1.z()) +
         p3.y()*(p1.z() - p2.z());
       double B = p1.z()*(p2.x() - p3.x()) + p2.z()*(p3.x() - p1.x()) +
         p3.z()*(p1.x() - p2.x());
       double C = p1.x()*(p2.y() - p3.y()) + p2.x()*(p3.y() - p1.y()) +
         p3.x()*(p1.y() - p2.y());
       //      double D = -1.0 * ( p1.x()*(p2.y()*p3.z() - p3.y()*p2.z()) +
       //                          p2.x()*(p3.y()*p1.z() - p1.y()*p3.z()) +
       //                          p3.x()*(p1.y()*p2.z() - p2.y()*p1.z()) );
       n.x(A).y(B).z(C);
       n.normalize();
     };
SolverUtils::GeoPrim::CPlane::CPlane (const CVector & N, const CPoint & P) inline
Definition at line 2018 of file GeoPrimitives.H.
       : n(N.unit()),p(P)
     {};
SolverUtils::GeoPrim::CPlane::CPlane (const CPlane & plane) inline
Definition at line 2021 of file GeoPrimitives.H.
       : n(plane.n),p(plane.p)
     {};
SolverUtils::GeoPrim::CPlane::CPlane (const std::vector< CPoint > & vec) inline
Definition at line 2024 of file GeoPrimitives.H.
References A(), B(), C(), n, SolverUtils::GeoPrim::CVector::normalize(), and SolverUtils::GeoPrim::CVector::x().
       : p(vec[0])
     {
       double A = vec[0].y()*(vec[1].z() - vec[2].z()) +
         vec[1].y()*(vec[2].z() - vec[0].z()) +
         vec[2].y()*(vec[0].z() - vec[1].z());
       double B = vec[0].z()*(vec[1].x() - vec[2].x()) +
         vec[1].z()*(vec[2].x() - vec[0].x()) +
         vec[2].z()*(vec[0].x() - vec[1].x());
       double C = vec[0].x()*(vec[1].y() - vec[2].y()) +
         vec[1].x()*(vec[2].y() - vec[0].y()) +
         vec[2].x()*(vec[0].y() - vec[1].y());
       //      double D = -1.0 * ( p1.x()*(p2.y()*p3.z() - p3.y()*p2.z()) +
       //                          p2.x()*(p3.y()*p1.z() - p1.y()*p3.z()) +
       //                          p3.x()*(p1.y()*p2.z() - p2.y()*p1.z()) );
       n.x(A).y(B).z(C);
       n.normalize();
     } ;
Member Function Documentation
double SolverUtils::GeoPrim::CPlane::A () const inline
Definition at line 2049 of file GeoPrimitives.H.
References n, and SolverUtils::GeoPrim::CVector::x().
Referenced by CPlane().
 { return(n.x()); };
double SolverUtils::GeoPrim::CPlane::B () const inline
Definition at line 2050 of file GeoPrimitives.H.
References n, and SolverUtils::GeoPrim::CVector::y().
Referenced by CPlane().
 { return(n.y()); };
double SolverUtils::GeoPrim::CPlane::C () const inline
Definition at line 2051 of file GeoPrimitives.H.
References n, and SolverUtils::GeoPrim::CVector::z().
Referenced by CPlane().
 { return(n.z()); };
bool SolverUtils::GeoPrim::CPlane::contains_point (const CPoint & P) const inline
Definition at line 2060 of file GeoPrimitives.H.
References D(), n, SolverUtils::GeoPrim::TOL, SolverUtils::GeoPrim::CPoint::x(), SolverUtils::GeoPrim::CVector::x(), SolverUtils::GeoPrim::CPoint::y(), SolverUtils::GeoPrim::CVector::y(), SolverUtils::GeoPrim::CPoint::z(), and SolverUtils::GeoPrim::CVector::z().
Referenced by SolverUtils::GeoPrim::CFacet::contains_point(), and operator==().
     {
       return(fabs(n.x()*P.x() + n.y()*P.y() + n.z()*P.z() + D()) <= TOL);
     };
double SolverUtils::GeoPrim::CPlane::D () const inline
Definition at line 2052 of file GeoPrimitives.H.
References n, p, SolverUtils::GeoPrim::CPoint::x(), SolverUtils::GeoPrim::CVector::x(), SolverUtils::GeoPrim::CPoint::y(), SolverUtils::GeoPrim::CVector::y(), SolverUtils::GeoPrim::CPoint::z(), and SolverUtils::GeoPrim::CVector::z().
Referenced by contains_point().
     {
       return( -1.0 * ( n.x()*p.x() + n.y()*p.y() + n.z()*p.z()));
     };
CVector& SolverUtils::GeoPrim::CPlane::normal () inline
Definition at line 2056 of file GeoPrimitives.H.
References n.
 { return(n); };
const CVector& SolverUtils::GeoPrim::CPlane::normal () const inline
Definition at line 2057 of file GeoPrimitives.H.
References n.
 { return(n); };
CPlane& SolverUtils::GeoPrim::CPlane::operator= (const CPlane & plane) inline
Definition at line 2043 of file GeoPrimitives.H.
References n, and p.
     {
       n = plane.n;
       p = plane.p;
       return(*this);
     };
bool SolverUtils::GeoPrim::CPlane::operator== (const CPlane & plane) const inline
Definition at line 2064 of file GeoPrimitives.H.
References contains_point(), n, p, and SolverUtils::GeoPrim::CVector::unit().
     {
       return((plane.n.unit() == n.unit()) && contains_point(plane.p));
     };
CPoint& SolverUtils::GeoPrim::CPlane::point () inline
Definition at line 2058 of file GeoPrimitives.H.
References p.
 { return(p); };
const CPoint& SolverUtils::GeoPrim::CPlane::point () const inline
Definition at line 2059 of file GeoPrimitives.H.
References p.
 { return(p); };
Member Data Documentation
CVector SolverUtils::GeoPrim::CPlane::n protected
Definition at line 1998 of file GeoPrimitives.H.
Referenced by A(), B(), C(), contains_point(), CPlane(), D(), normal(), operator=(), and operator==().
CPoint SolverUtils::GeoPrim::CPlane::p protected
Definition at line 1999 of file GeoPrimitives.H.
Referenced by D(), operator=(), operator==(), and point().
The documentation for this class was generated from the following file:
GeoPrimitives.H