IMPACT: Point_2< T > Class Template Reference
Point_2< T > Class Template Reference
Detailed Description
template<class T>
class Point_2< T >
Definition at line 257 of file mapbasic.h.
#include <mapbasic.h>
Public Member Functions
Point_2 ()
Point_2 (Origin)
Point_2 (T t)
Point_2 (T a, T b)
T & operator[] (const int i)
const T & operator[] (const int i) const
Point_2 & operator+= (const Vector_2< T > &v)
Assign operators.
Point_2 & operator-= (const Vector_2< T > &v)
Point_2 operator+ (const Vector_2< T > &v) const
Arithmatic operators.
Point_2 operator- (const Vector_2< T > &v) const
Vector_2< T > operator- (const Point_2 &v) const
bool operator== (const Point_2 &p) const
bool operator!= (const Point_2 &p) const
bool operator< (const Point_2 &v) const
bool is_origin () const
Additional Inherited Members
Protected Member Functions inherited from Vector_2< T >
Vector_2 ()
Vector_2 (Tt)
Vector_2 (Null_vector)
Vector_2 (Ta, Tb)
T & operator[] (const int i)
const T & operator[] (const int &i) const
T x () const
T y () const
Vector_2 & operator+= (const Vector_2 &v)
Assign operators.
Vector_2 & operator-= (const Vector_2 &v)
Vector_2 & operator*= (const Tt)
Vector_2 & operator/= (const Tt)
Vector_2 operator+ (const Vector_2 &v) const
Arithmatic operators.
Vector_2 operator- (const Vector_2 &v) const
Vector_2 operator- () const
Vector_2 operator* (const Tt) const
T operator* (const Vector_2 &v) const
Vector_2 operator/ (const Tt) const
T squared_norm () const
T norm () const
Vector_2 & normalize ()
Vector_2 & neg ()
bool operator== (const Vector_2 &p) const
bool operator!= (const Vector_2 &p) const
bool operator< (const Vector_2 &v) const
bool is_null () const
Protected Attributes inherited from Vector_2< T >
T _x
T _y
Constructor & Destructor Documentation
template<class T> Point_2< T >::Point_2 () inline
Definition at line 259 of file mapbasic.h.
Referenced by Point_2< T >::operator+(), and Point_2< T >::operator-().
 {}
template<class T> Point_2< T >::Point_2 (Origin) inline
Definition at line 260 of file mapbasic.h.
 : Vector_2<T>( 0, 0) {}
template<class T> Point_2< T >::Point_2 (T t) inline explicit
Definition at line 261 of file mapbasic.h.
 : Vector_2<T>(t) {}
template<class T> Point_2< T >::Point_2 (T a, T b) inline
Definition at line 262 of file mapbasic.h.
 : Vector_2<T>(a, b) {}
Member Function Documentation
template<class T> bool Point_2< T >::is_origin () const inline
Definition at line 291 of file mapbasic.h.
References Vector_2< T >::_x, and Vector_2< T >::_y.
 { return _x==0&&_y==0; }
template<class T> bool Point_2< T >::operator!= (const Point_2< T > & p) const inline
Definition at line 285 of file mapbasic.h.
References Vector_2< T >::x(), Vector_2< Type >::x(), Vector_2< T >::y(), and Vector_2< Type >::y().
   { return x()!=p.x() || y()!=p.y(); }
template<class T> Point_2 Point_2< T >::operator+ (const Vector_2< T > & v) const inline
Definition at line 275 of file mapbasic.h.
References Vector_2< T >::_x, Vector_2< T >::_y, Point_2< T >::Point_2(), Vector_2< Type >::x(), and Vector_2< Type >::y().
   { return Point_2(_x+v.x(), _y+v.y()); }
template<class T> Point_2& Point_2< T >::operator+= (const Vector_2< T > & v) inline
Definition at line 269 of file mapbasic.h.
References Vector_2< T >::_x, Vector_2< T >::_y, Vector_2< Type >::x(), and Vector_2< Type >::y().
   { _x+=v.x(); _y+=v.y(); return *this; }
template<class T> Point_2 Point_2< T >::operator- (const Vector_2< T > & v) const inline
Definition at line 277 of file mapbasic.h.
References Vector_2< T >::_x, Vector_2< T >::_y, Point_2< T >::Point_2(), Vector_2< Type >::x(), and Vector_2< Type >::y().
   { return Point_2(_x-v.x(), _y-v.y()); }
template<class T> Vector_2<T> Point_2< T >::operator- (const Point_2< T > & v) const inline
Definition at line 279 of file mapbasic.h.
References Vector_2< T >::_x, Vector_2< T >::_y, Vector_2< Type >::x(), and Vector_2< Type >::y().
   { return Vector_2<T>(_x-v.x(), _y-v.y()); }
template<class T> Point_2& Point_2< T >::operator-= (const Vector_2< T > & v) inline
Definition at line 271 of file mapbasic.h.
References Vector_2< T >::_x, Vector_2< T >::_y, Vector_2< Type >::x(), and Vector_2< Type >::y().
   { _x-=v.x(); _y-=v.y(); return *this; }
template<class T> bool Point_2< T >::operator< (const Point_2< T > & v) const inline
Definition at line 288 of file mapbasic.h.
References Vector_2< Type >::operator<().
   { return Vector_2<T>::operator<(v); }
template<class T> bool Point_2< T >::operator== (const Point_2< T > & p) const inline
Definition at line 282 of file mapbasic.h.
References Vector_2< T >::x(), Vector_2< Type >::x(), Vector_2< T >::y(), and Vector_2< Type >::y().
   { return x()==p.x() && y()==p.y(); }
template<class T> T& Point_2< T >::operator[] (const int i) inline
Definition at line 263 of file mapbasic.h.
References Vector_2< T >::_x.
 { return (&_x)[i]; }
template<class T> const T& Point_2< T >::operator[] (const int i) const inline
Definition at line 264 of file mapbasic.h.
References Vector_2< T >::_x.
 { return (&_x)[i]; }
The documentation for this class was generated from the following file:
mapbasic.h