IMPACT: IMPACT::TestingObject< ResultsType > Class Template Reference
IMPACT::TestingObject< ResultsType > Class Template Reference
Project-specific testing object.
Detailed Description
template<typename ResultsType>
class IMPACT::TestingObject< ResultsType >
The project-specific testing object encapsulates all tests for the project. This is the interface to all testing available for the given project. It implements the interface given by IRAD::Util::TestingObject.
Every project should define a "TestingObject" which implements (or interfaces) all of the tests for the project. If necessary (e.g. for parallel tests through batch systems), this is the object responsible for spawning off children processes to conduct parallel tests and for gathering the results of those tests.
Definition at line 71 of file IMPACTTest.H.
#include <IMPACTTest.H>
Public Member Functions
TestingObject ()
Default constructor.
virtual void Epilogue ()
Tears down the testing fixtures if needed.
virtual void Prologue ()
Sets up the data fixtures for the tests.
double F1 (double x)
Simple test function fixture returns .
double F2 (double x)
Simple test function fixture returns .
virtual void Test__ExampleFunction (ResultsType &result)
Test for IMPACT::ExampleFunction.
virtual void Test__TrapezoidQuadrature (ResultsType &result)
Test for IMPACT::TrapezoidQuadrature.
virtual void Test__MidPointQuadrature (ResultsType &result)
Test for IMPACT::MidPointQuadrature.
virtual void Process (ResultsType &result)
Runs all tests implemented by the IMPACT::TestingObject.
virtual void RunTest (const std::string &name, ResultsType &result)
Runs a test specified by name.
virtual void ProcessTests (std::list< std::string > &test_names, ResultsType &result)
Runs a list of tests specified by name.
Protected Attributes
std::string ExampleTestFixture
A sample string test fixture.
std::vector< int > N
A set of values for testing quadrature methods.
Private Types
typedef
IRAD::Util::TestingObject
< ResultsType > TestingObjectBaseType
Member Typedef Documentation
template<typename ResultsType> typedef IRAD::Util::TestingObject<ResultsType> IMPACT::TestingObject< ResultsType >::TestingObjectBaseType private
Definition at line 73 of file IMPACTTest.H.
Constructor & Destructor Documentation
template<typename ResultsType> IMPACT::TestingObject< ResultsType >::TestingObject () inline
Definition at line 91 of file IMPACTTest.H.
 : TestingObjectBaseType() {};
Member Function Documentation
template<typename ResultsType> virtual void IMPACT::TestingObject< ResultsType >::Epilogue () inline virtual
Reimplemented in IMPACT::ParallelTestingObject< CommType, ResultsType >.
Definition at line 96 of file IMPACTTest.H.
Referenced by IMPACT::TestingObject< ResultsType >::Process(), IMPACT::TestingObject< ResultsType >::ProcessTests(), and IMPACT::TestingObject< ResultsType >::RunTest().
 {};
template<typename ResultsType> double IMPACT::TestingObject< ResultsType >::F1 (double x) inline
F1 is a 1st order function in x that has unity integral over [0,1].
Definition at line 114 of file IMPACTTest.H.
 { return (2.0*x); };
template<typename ResultsType> double IMPACT::TestingObject< ResultsType >::F2 (double x) inline
F2 is quadratic function in x and integrates to unity over [0,1].
Definition at line 120 of file IMPACTTest.H.
 { return (3.0*x*x); };
template<typename ResultsType> virtual void IMPACT::TestingObject< ResultsType >::Process (ResultsType & result) inline virtual
Parameters
result IMPACT::TestResults object to store test results.
Reimplemented in IMPACT::ParallelTestingObject< CommType, ResultsType >.
Definition at line 255 of file IMPACTTest.H.
References IMPACT::TestingObject< ResultsType >::Epilogue(), IMPACT::TestingObject< ResultsType >::Prologue(), IMPACT::TestingObject< ResultsType >::Test__ExampleFunction(), IMPACT::TestingObject< ResultsType >::Test__MidPointQuadrature(), and IMPACT::TestingObject< ResultsType >::Test__TrapezoidQuadrature().
Referenced by IMPACT::Test().
{
       Prologue();
       Test__ExampleFunction(result);
       Test__TrapezoidQuadrature(result);
       Test__MidPointQuadrature(result);
       Epilogue();
     }
template<typename ResultsType> virtual void IMPACT::TestingObject< ResultsType >::ProcessTests (std::list< std::string > & test_names, ResultsType & result) inline virtual
Parameters
test_names list of string test names
result IMPACT::TestResults object to store test results.
Reimplemented in IMPACT::ParallelTestingObject< CommType, ResultsType >.
Definition at line 287 of file IMPACTTest.H.
References IMPACT::TestingObject< ResultsType >::Epilogue(), IMPACT::TestingObject< ResultsType >::Prologue(), and IMPACT::TestingObject< ResultsType >::RunTest().
{
       Prologue();
       std::list<std::string>::iterator tni = test_names.begin();
       while(tni != test_names.end())
         RunTest(*tni++,result);
       Epilogue();
     }
template<typename ResultsType> virtual void IMPACT::TestingObject< ResultsType >::Prologue () inline virtual
This function gives the object a chance to allocate and set up any "fixtures" before the tests are run.
Reimplemented in IMPACT::ParallelTestingObject< CommType, ResultsType >.
Definition at line 105 of file IMPACTTest.H.
References IMPACT::TestingObject< ResultsType >::ExampleTestFixture, and IMPACT::TestingObject< ResultsType >::N.
Referenced by IMPACT::TestingObject< ResultsType >::Process(), IMPACT::TestingObject< ResultsType >::ProcessTests(), and IMPACT::TestingObject< ResultsType >::RunTest().
{
       ExampleTestFixture.assign("ExampleTestData");
       for(int i = 10;i < 10000000;i*=10) N.push_back(i);
     }
template<typename ResultsType> virtual void IMPACT::TestingObject< ResultsType >::RunTest (const std::string & name, ResultsType & result) inline virtual
Parameters
name String name of the test to run.
result IMPACT::TestResults object to store test results.
Reimplemented in IMPACT::ParallelTestingObject< CommType, ResultsType >.
Definition at line 269 of file IMPACTTest.H.
References IMPACT::TestingObject< ResultsType >::Epilogue(), IMPACT::TestingObject< ResultsType >::Prologue(), IMPACT::TestingObject< ResultsType >::Test__ExampleFunction(), IMPACT::TestingObject< ResultsType >::Test__MidPointQuadrature(), and IMPACT::TestingObject< ResultsType >::Test__TrapezoidQuadrature().
Referenced by IMPACT::TestingObject< ResultsType >::ProcessTests(), and IMPACT::Test().
     {
       Prologue();
       if(name == "ExampleFunction")
         Test__ExampleFunction(result);
       else if(name == "TrapezoidQuadrature")
         Test__TrapezoidQuadrature(result);
       else if(name == "MidPointQuadrature")
         Test__MidPointQuadrature(result);
       Epilogue();
     }
template<typename ResultsType> virtual void IMPACT::TestingObject< ResultsType >::Test__ExampleFunction (ResultsType & result) inline virtual
Parameters
result IMPACT::TestResults object to store test results.
This function implements a simple test of the function IMPACT::ExampleFunction - which is designed to simply return a copy of the input string.
Definition at line 130 of file IMPACTTest.H.
References IMPACT::ExampleFunction(), and IMPACT::TestingObject< ResultsType >::ExampleTestFixture.
Referenced by IMPACT::TestingObject< ResultsType >::Process(), and IMPACT::TestingObject< ResultsType >::RunTest().
{
       // This is an actual test of the function called
       // ExampleFunction.   The name Test__XXXXX will
       // eventually help automated utilities with
       // running tests by name.
       std::string ExampleResult(ExampleFunction(ExampleTestFixture));
       result.UpdateResult("ExampleFunction:Works",
                           ExampleResult == ExampleTestFixture);
       result.UpdateResult("ExampleFunction:Fails",
                           ExampleResult != ExampleTestFixture);
     }
template<typename ResultsType> virtual void IMPACT::TestingObject< ResultsType >::Test__MidPointQuadrature (ResultsType & result) inline virtual
Parameters
result IMPACT::TestResults object to store test results.
This function implements a simple test of the function IMPACT::MidPointQuadrature - which is designed to integrate a function, f, over an interval .
The test first makes sure that the method integrates a linear function exactly, and then that the error term has the proper dependence on the spacings.
Definition at line 207 of file IMPACTTest.H.
References IMPACT::TestFixture::F1(), IMPACT::TestFixture::F2(), IMPACT::MidPointQuadrature(), and IMPACT::TestingObject< ResultsType >::N.
Referenced by IMPACT::TestingObject< ResultsType >::Process(), and IMPACT::TestingObject< ResultsType >::RunTest().
{
       std::ostringstream Ostr;
       std::vector<double> Ibar;
       std::vector<double> E;
       size_t n = 2*N.size();
       bool runs = true;
       bool order2 = true;
       for(std::vector<int>::iterator i = N.begin();i != N.end();i++){
         double Ii = 0.0;
         try {
           Ii = IMPACT::MidPointQuadrature(TestFixture::F1,0,1,*i);
         } catch (...) {
           runs = false;
         }
         Ibar.push_back(Ii);
         E.push_back(std::fabs(Ii-1.0));
       }
       order2 = (E[0] < 1e-14);
       for(std::vector<int>::iterator i = N.begin();i != N.end();i++){
         double Ii = 0.0;
         try {
           Ii = IMPACT::MidPointQuadrature(TestFixture::F2,0,1,*i);
         } catch (...) {
           runs = false;
         }
         Ibar.push_back(Ii);
         E.push_back(std::fabs(Ii-1.0));
       }
       result.UpdateResult("MidPointQuadrature:Runs",runs);
       result.UpdateResult("MidPointQuadrature:Accurate",E[n-1] < 1e-12);
       for(int i = N.size();i < n - 1;i++){
         double e = E[i+1]/E[i];
         double n1 = static_cast<double>(N[i-N.size()])/static_cast<double>(N[(i-N.size())+1]);
         double p = std::log(e)/std::log(n1);
         p -= 2;
         p = std::abs(p);
         if(p > 1e-2){
           order2 = false;
         }
       }
       result.UpdateResult("MidPointQuadrature:Order2",order2);
     }
template<typename ResultsType> virtual void IMPACT::TestingObject< ResultsType >::Test__TrapezoidQuadrature (ResultsType & result) inline virtual
Parameters
result IMPACT::TestResults object to store test results.
This function implements a simple test of the function IMPACT::TrapezoidQuadrature - which is designed to integrate a function, f, over an n-way partitioned interval .
The test first makes sure that the method integrates a linear function exactly, and then that the error term has the proper dependence on the spacings.
Definition at line 155 of file IMPACTTest.H.
References IMPACT::TestFixture::F1(), IMPACT::TestFixture::F2(), IMPACT::TestingObject< ResultsType >::N, and IMPACT::TrapezoidQuadrature().
Referenced by IMPACT::TestingObject< ResultsType >::Process(), and IMPACT::TestingObject< ResultsType >::RunTest().
{
       std::ostringstream Ostr;
       std::vector<double> E;
       size_t n = 2*N.size();
       bool runs = true;
       for(std::vector<int>::iterator i = N.begin();i != N.end();i++){
         double Ii = 0.0;
         try {
           Ii = IMPACT::TrapezoidQuadrature(TestFixture::F1,0,1,*i);
         } catch (...) {
           runs = false;
         }
         E.push_back(std::fabs(Ii-1.0));
       }
       bool order2 = (E[0] < 1e-14);
       for(std::vector<int>::iterator i = N.begin();i != N.end();i++){
         double Ii = 0.0;
         try {
           Ii = IMPACT::TrapezoidQuadrature(TestFixture::F2,0,1,*i);
         } catch (...) {
           runs = false;
         }
         E.push_back(std::fabs(Ii-1.0));
       }
       result.UpdateResult("TrapezoidQuadrature:Runs",runs);
       result.UpdateResult("TrapezoidQuadrature:Accurate",E[n-1] < 1e-12);
       for(int i = N.size();i < n - 1;i++){
         double e = E[i+1]/E[i];
         double n1 = static_cast<double>(N[i-N.size()])/static_cast<double>(N[(i-N.size())+1]);
         double p = std::log(e)/std::log(n1);
         p -= 2;
         p = std::abs(p);
         if(p > 2e-2){
           order2 = false;
         }
       }
       result.UpdateResult("TrapezoidQuadrature:Order2",order2);
     }
Member Data Documentation
template<typename ResultsType> std::string IMPACT::TestingObject< ResultsType >::ExampleTestFixture protected
Definition at line 82 of file IMPACTTest.H.
Referenced by IMPACT::TestingObject< ResultsType >::Prologue(), and IMPACT::TestingObject< ResultsType >::Test__ExampleFunction().
template<typename ResultsType> std::vector<int> IMPACT::TestingObject< ResultsType >::N protected
Definition at line 86 of file IMPACTTest.H.
Referenced by IMPACT::TestingObject< ResultsType >::Prologue(), IMPACT::TestingObject< ResultsType >::Test__MidPointQuadrature(), and IMPACT::TestingObject< ResultsType >::Test__TrapezoidQuadrature().
The documentation for this class was generated from the following file:
IMPACTTest.H