IMPACT: Bbox_3 Class Reference
Bbox_3 Class Reference
Detailed Description
Definition at line 16 of file Bbox_3.h.
#include <Bbox_3.h>
Public Member Functions
Bbox_3 ()
Bbox_3 (double x_min, double y_min, double z_min, double x_max, double y_max, double z_max)
template<class Point3 >
Bbox_3 (const Point3 &p)
double xmin () const
double ymin () const
double zmin () const
double xmax () const
double ymax () const
double zmax () const
Bbox_3 operator+ (const Bbox_3 &b) const
Bbox_3 & operator+= (const Bbox_3 &b)
bool do_match (const Bbox_3 &bb, double tol) const
Private Attributes
double _min [3]
double _max [3]
Constructor & Destructor Documentation
Bbox_3::Bbox_3 () inline
Definition at line 19 of file Bbox_3.h.
References _max, and _min.
            {
     _min[0] = _min[1] = _min[2] = HUGE_VAL;
     _max[0] = _max[1] = _max[2] = -HUGE_VAL;
   }
Bbox_3::Bbox_3 (double x_min, double y_min, double z_min, double x_max, double y_max, double z_max) inline
Definition at line 24 of file Bbox_3.h.
References _max, and _min.
{
     _min[0]=x_min; _min[1]=y_min; _min[2]=z_min;
     _max[0]=x_max; _max[1]=y_max; _max[2]=z_max;
   }
template<class Point3 > Bbox_3::Bbox_3 (const Point3 & p) inline explicit
Definition at line 31 of file Bbox_3.h.
References _max, and _min.
{
     _min[0]=p[0]; _min[1]=p[1]; _min[2]=p[2];
     _max[0]=p[0]; _max[1]=p[1]; _max[2]=p[2];
   }
Member Function Documentation
bool Bbox_3::do_match (const Bbox_3 & bb, double tol) const inline
Definition at line 62 of file Bbox_3.h.
References xmax(), xmin(), ymax(), ymin(), zmax(), and zmin().
Referenced by Overlay::overlay().
{
     return (std::abs(xmax()-bb.xmax()) <= tol &&
             std::abs(xmin()-bb.xmin()) <= tol &&
             std::abs(ymax()-bb.ymax()) <= tol &&
             std::abs(ymin()-bb.ymin()) <= tol &&
             std::abs(zmax()-bb.zmax()) <= tol &&
             std::abs(zmin()-bb.zmin()) <= tol);
   }
Bbox_3 Bbox_3::operator+ (const Bbox_3 & b) const inline
Definition at line 43 of file Bbox_3.h.
{
     Bbox_3 box=*this; box+=b; return box;
   }
Bbox_3& Bbox_3::operator+= (const Bbox_3 & b) inline
Definition at line 47 of file Bbox_3.h.
References _max, _min, max(), and min().
{
     _min[0] = std::min(_min[0], b._min[0]);
     _min[1] = std::min(_min[1], b._min[1]);
     _min[2] = std::min(_min[2], b._min[2]);
     _max[0] = std::max(_max[0], b._max[0]);
     _max[1] = std::max(_max[1], b._max[1]);
     _max[2] = std::max(_max[2], b._max[2]);
     return *this;
   }
double Bbox_3::xmax () const inline
Definition at line 39 of file Bbox_3.h.
References _max.
Referenced by do_match(), do_overlap(), do_overlap_eps(), do_overlap_strict(), equal(), operator<<(), and Overlay::overlay().
 { return _max[0]; }
double Bbox_3::xmin () const inline
Definition at line 36 of file Bbox_3.h.
References _min.
Referenced by do_match(), do_overlap(), do_overlap_eps(), do_overlap_strict(), equal(), operator<<(), and Overlay::overlay().
 { return _min[0]; }
double Bbox_3::ymax () const inline
Definition at line 40 of file Bbox_3.h.
References _max.
Referenced by do_match(), do_overlap(), do_overlap_eps(), do_overlap_strict(), equal(), operator<<(), and Overlay::overlay().
 { return _max[1]; }
double Bbox_3::ymin () const inline
Definition at line 37 of file Bbox_3.h.
References _min.
Referenced by do_match(), do_overlap(), do_overlap_eps(), do_overlap_strict(), equal(), operator<<(), and Overlay::overlay().
 { return _min[1]; }
double Bbox_3::zmax () const inline
Definition at line 41 of file Bbox_3.h.
References _max.
Referenced by do_match(), do_overlap(), do_overlap_eps(), do_overlap_strict(), equal(), operator<<(), and Overlay::overlay().
 { return _max[2]; }
double Bbox_3::zmin () const inline
Definition at line 38 of file Bbox_3.h.
References _min.
Referenced by do_match(), do_overlap(), do_overlap_eps(), do_overlap_strict(), equal(), operator<<(), and Overlay::overlay().
 { return _min[2]; }
Member Data Documentation
double Bbox_3::_max[3] private
Definition at line 72 of file Bbox_3.h.
Referenced by Bbox_3(), operator+=(), xmax(), ymax(), and zmax().
double Bbox_3::_min[3] private
Definition at line 72 of file Bbox_3.h.
Referenced by Bbox_3(), operator+=(), xmin(), ymin(), and zmin().
The documentation for this class was generated from the following file:
Bbox_3.h