IMPACT: Element_node_vectors_k_const< Value > Class Template Reference
Element_node_vectors_k_const< Value > Class Template Reference
This is a helper class for accessing nodal data.
Detailed Description
template<class Value>
class Element_node_vectors_k_const< Value >
Definition at line 210 of file Element_accessors.hpp.
#include <Element_accessors.hpp>
Public Types
enum { MAX_NODES =9 }
typedef unsigned int Size
Public Member Functions
Element_node_vectors_k_const ()
Default constructor.
void set (const Value *p, Element_node_enumerator &ene, int strd)
initialize the accessor with a pointer and a specific stride.
void set (const DataItem *a, Element_node_enumerator &ene)
initialize the accessor from an attribute assiciated with a pane.
const Value & operator() (int i, int j) const
const Value & operator() (int i) const
const Value & operator[] (int i) const
Protected Attributes
const DataItem * _attr
union {
int _offsets [MAX_NODES]
const Value * _vs [MAX_NODES]
};
Member Typedef Documentation
template<class Value > typedef unsigned int Element_node_vectors_k_const< Value >::Size
Definition at line 213 of file Element_accessors.hpp.
Member Enumeration Documentation
template<class Value > anonymous enum
Enumerator
MAX_NODES
Definition at line 212 of file Element_accessors.hpp.
 { MAX_NODES=9};
Constructor & Destructor Documentation
template<class Value > Element_node_vectors_k_const< Value >::Element_node_vectors_k_const () inline
Definition at line 216 of file Element_accessors.hpp.
References Element_node_vectors_k_const< Value >::_vs.
                                  : _attr(NULL)
   { std::fill_n( _vs, 9, reinterpret_cast<Value*>(NULL)); }
Member Function Documentation
template<class Value > const Value& Element_node_vectors_k_const< Value >::operator() (int i, int j) const inline
Definition at line 247 of file Element_accessors.hpp.
References Element_node_vectors_k_const< Value >::_attr, Element_node_vectors_k_const< Value >::_offsets, Element_node_vectors_k_const< Value >::_vs, COM_assertion, and DataItem::size_of_components().
Referenced by Element_node_vectors_k< Value >::operator()(), Element_node_vectors_k_const< Value >::operator[](), and Element_node_vectors_k< Value >::operator[]().
{
     if ( _attr) {
       COM_assertion( _attr->size_of_components()>1);
       const DataItem *aj = _attr+j+1;
       return reinterpret_cast<const Value*>
         (aj->pointer())[_offsets[i]*aj->stride()];
     }
     else
       return _vs[i][j];
   }
template<class Value > const Value& Element_node_vectors_k_const< Value >::operator() (int i) const inline
Definition at line 258 of file Element_accessors.hpp.
References Element_node_vectors_k_const< Value >::operator()().
Referenced by Element_node_vectors_k_const< Value >::operator()().
 { return operator()(i,0); }
template<class Value > const Value& Element_node_vectors_k_const< Value >::operator[] (int i) const inline
Definition at line 260 of file Element_accessors.hpp.
References Element_node_vectors_k_const< Value >::operator()().
 { return operator()(i,0); }
template<class Value > void Element_node_vectors_k_const< Value >::set (const Value * p, Element_node_enumerator & ene, int strd) inline
Definition at line 220 of file Element_accessors.hpp.
References Element_node_vectors_k_const< Value >::_attr, Element_node_vectors_k_const< Value >::_vs, COM_assertion, Element_node_vectors_k_const< Value >::MAX_NODES, Element_node_enumerator::size_of_nodes(), and strd.
Referenced by Rocsurf::compute_bounded_volumes(), Rocsurf::compute_element_areas(), Rocsurf::compute_element_normals(), Rocsurf::compute_signed_volumes(), Rocsurf::compute_swept_volumes(), Window_manifold_2::elements_to_nodes(), get_normal(), Rocsurf::integrate(), and Element_node_vectors_k< Value >::set().
{
     COM_assertion( ene.size_of_nodes() <= MAX_NODES);
     _attr = NULL;
     for ( int i=ene.size_of_nodes()-1; i>=0; --i)
       _vs[i] = &p[(ene[i]-1)*strd];
   }
template<class Value > void Element_node_vectors_k_const< Value >::set (const DataItem * a, Element_node_enumerator & ene) inline
Definition at line 228 of file Element_accessors.hpp.
References Element_node_vectors_k_const< Value >::_attr, Element_node_vectors_k_const< Value >::_offsets, Element_node_vectors_k_const< Value >::_vs, COM_assertion, COM_get_sizeof(), DataItem::data_type(), Pane::id(), DataItem::is_nodal(), DataItem::pane(), DataItem::pointer(), DataItem::size_of_components(), Element_node_enumerator::size_of_nodes(), strd, and DataItem::stride().
{
     COM_assertion( a->is_nodal() && a->pane()->id());
     COM_assertion( sizeof(Value)==COM_get_sizeof( a->data_type(),1));
     int ncomp = a->size_of_components();
     int strd = a->stride();
     int nn = ene.size_of_nodes();
     if ( ncomp<=strd) {
       const Value *p = reinterpret_cast<const Value*>(a->pointer());
       _attr = NULL;
       for ( int i=0; i<nn; ++i) _vs[i] = &p[(ene[i]-1)*strd];
     }
     else {
       _attr = a;
       for ( int i=0; i<nn; ++i) _offsets[i] = ene[i]-1;
     }
   }
Member Data Documentation
union { ... }
template<class Value > const DataItem* Element_node_vectors_k_const< Value >::_attr protected
Definition at line 263 of file Element_accessors.hpp.
Referenced by Element_node_vectors_k_const< Value >::operator()(), and Element_node_vectors_k_const< Value >::set().
template<class Value > int Element_node_vectors_k_const< Value >::_offsets[MAX_NODES]
Definition at line 265 of file Element_accessors.hpp.
Referenced by Element_node_vectors_k_const< Value >::operator()(), and Element_node_vectors_k_const< Value >::set().
template<class Value > const Value* Element_node_vectors_k_const< Value >::_vs[MAX_NODES]
Definition at line 266 of file Element_accessors.hpp.
Referenced by Element_node_vectors_k_const< Value >::Element_node_vectors_k_const(), Element_node_vectors_k_const< Value >::operator()(), and Element_node_vectors_k_const< Value >::set().
The documentation for this class was generated from the following file:
Element_accessors.hpp