IMPACT: Element_node_vectors_k< Value > Class Template Reference
Element_node_vectors_k< Value > Class Template Reference
Detailed Description
template<class Value>
class Element_node_vectors_k< Value >
Definition at line 271 of file Element_accessors.hpp.
#include <Element_accessors.hpp>
Public Member Functions
Element_node_vectors_k ()
void set (Value *p, Element_node_enumerator &ene, int strd)
void set (DataItem *a, Element_node_enumerator &ene)
Value & operator() (int i, int j) const
Value & operator() (int i) const
Value & operator[] (int i) const
Public Member Functions inherited from Element_node_vectors_k_const< Value >
Element_node_vectors_k_const ()
Default constructor.
void set (const Value *p, Element_node_enumerator &ene, int strd)
initialize the accessor with a pointer and a specific stride.
void set (const DataItem *a, Element_node_enumerator &ene)
initialize the accessor from an attribute assiciated with a pane.
const Value & operator() (int i, int j) const
const Value & operator() (int i) const
const Value & operator[] (int i) const
Private Types
typedef
Element_node_vectors_k_const
< Value > Base
Additional Inherited Members
Public Types inherited from Element_node_vectors_k_const< Value >
enum { MAX_NODES =9 }
typedef unsigned int Size
Protected Attributes inherited from Element_node_vectors_k_const< Value >
const DataItem * _attr
union {
int _offsets [MAX_NODES]
const Value * _vs [MAX_NODES]
};
Member Typedef Documentation
template<class Value> typedef Element_node_vectors_k_const<Value> Element_node_vectors_k< Value >::Base private
Definition at line 272 of file Element_accessors.hpp.
Constructor & Destructor Documentation
template<class Value> Element_node_vectors_k< Value >::Element_node_vectors_k () inline
Definition at line 274 of file Element_accessors.hpp.
 : Base() {}
Member Function Documentation
template<class Value> Value& Element_node_vectors_k< Value >::operator() (int i, int j) const inline
Definition at line 282 of file Element_accessors.hpp.
References Element_node_vectors_k_const< Value >::operator()().
   { return const_cast<Value&>(Base::operator()(i,j)); }
template<class Value> Value& Element_node_vectors_k< Value >::operator() (int i) const inline
Definition at line 285 of file Element_accessors.hpp.
References Element_node_vectors_k_const< Value >::operator()().
   { return const_cast<Value&>(Base::operator()(i,0)); }
template<class Value> Value& Element_node_vectors_k< Value >::operator[] (int i) const inline
Definition at line 288 of file Element_accessors.hpp.
References Element_node_vectors_k_const< Value >::operator()().
   { return const_cast<Value&>(Base::operator()(i,0)); }
template<class Value> void Element_node_vectors_k< Value >::set (Value * p, Element_node_enumerator & ene, int strd) inline
Definition at line 276 of file Element_accessors.hpp.
References Element_node_vectors_k_const< Value >::set().
Referenced by Window_manifold_2::elements_to_nodes().
   { Base::set( p, ene, strd); }
template<class Value> void Element_node_vectors_k< Value >::set (DataItem * a, Element_node_enumerator & ene) inline
Definition at line 279 of file Element_accessors.hpp.
References Element_node_vectors_k_const< Value >::set().
   { Base::set( a, ene); }
The documentation for this class was generated from the following file:
Element_accessors.hpp