IMPACT: COM::TestModule Class Reference
COM::TestModule Class Reference
Detailed Description
Definition at line 114 of file COM/testing/src/TestModule.C.
Public Member Functions
TestModule ()
Default constructor.
virtual ~TestModule ()
Destructor.
void Function0F (char *string_data, int size)
Hello COM World.
void Function0 (void *string_data)
Hello COM World.
void Function1 (void *string_data)
Load external module by name.
void Function2 (void *string_data)
Invoke external test module's "Hello COM World!".
void Function3 (void *string_data)
Load external module by name.
void Function4 (void *string_data)
Invoke external Fortran test module's "Hello COM World!".
void Increment (int *i, int *rank)
Function that increments an integer.
void SleepMultiply (int *mult)
Function that sleeps for the number of seconds of its process rank.
void InitSolver (void *config_file)
Initialize stub solver from config file.
void ValidateDataItemAddress (void *name_of_dataitem, void *address, int *result)
void Step ()
Step the dummy solver through time.
void DumpSolverSolution (void *config_file, int *use_timestamp)
Output solver solution to VTK format.
void get_communicator_module (int *commworks)
This function ...
Public Member Functions inherited from COM::TestSolver
void Init (const std::string &filename)
Public Member Functions inherited from SolverUtils::FEM::SolverAgent
const FEM::SolutionData & Solution () const
FEM::SolutionData & Solution ()
const Mesh::UnstructuredMesh & Mesh () const
Mesh::UnstructuredMesh & Mesh ()
void ReadMeshFromStream (std::istream &Istr)
void WriteMeshToStream (std::ostream &Ostr)
void ReadCoordsFromStream (std::istream &Istr)
void WriteCoordsToStream (std::ostream &Ostr)
void ReadSolnMetaFromStream (std::istream &Istr)
void WriteSolnMetaToStream (std::ostream &Ostr)
void CreateSoln ()
void ReadSolnFromStream (std::istream &Istr, const std::string &name)
void WriteSolnToStream (std::ostream &Ostr, const std::string &name)
std::ostream & ReportMeshToStream (std::ostream &Ostr)
~SolverAgent ()
Static Public Member Functions
static void Load (const std::string &name)
"Loads" the C++ TestModule
static void Unload (const std::string &name)
Unloads the TestModule.
Private Attributes
std::string my_window_name
std::string other_window_name
Tracks this window name.
std::string fortran_window_name
Tracks this external window's name.
Additional Inherited Members
Protected Attributes inherited from COM::TestSolver
int step
std::string name
std::vector< double > time
std::vector< double > delta_time
std::vector< int > id
std::vector< double > displacements
std::vector< double > pressures
std::vector< double > temperatures
std::vector< int > nodeflags
std::vector< int > cellflags
Constructor & Destructor Documentation
COM::TestModule::TestModule () inline
Tracks this external window's name
Tracks the fortran external window's name
Definition at line 117 of file COM/testing/src/TestModule.C.
References fortran_window_name, my_window_name, and other_window_name.
Referenced by Load().
                 {
       my_window_name.erase();
       other_window_name.erase();
       fortran_window_name.erase();
     };
virtual COM::TestModule::~TestModule () inline virtual
The destructor will destroy the externally loaded modules (if they exists)
Definition at line 128 of file COM/testing/src/TestModule.C.
References COM_get_window_handle(), COM_UNLOAD_MODULE_STATIC_DYNAMIC, fortran_window_name, and other_window_name.
     {
       std::cout << "Entering destructor" << std::endl;
       if(!other_window_name.empty()){
         std::cout << "deleting other sub-window" << std::endl;
         int other_window_handle = COM_get_window_handle(other_window_name.c_str());
         if(other_window_handle > 0)
           COM_UNLOAD_MODULE_STATIC_DYNAMIC(COMTESTMOD,other_window_name.c_str());
       }
       std::cout << "In destructor" << std::endl;
       if(!fortran_window_name.empty()){
         std::cout << "Deleting other fortran module." << std::endl;
         int fortran_window_handle = COM_get_window_handle(fortran_window_name.c_str());
         if(fortran_window_handle > 0)
           COM_UNLOAD_MODULE_STATIC_DYNAMIC(COMFTESTMOD,fortran_window_name.c_str());
       }
       std::cout << "Destructor done." << std::endl;
     };
Member Function Documentation
void COM::TestModule::DumpSolverSolution (void * config_file, int * use_timestamp) inline
This function writes the solver solution to a VTK file with the specified name. If indicated, a timestamp will be appended to the specified name resulting in a name like: <name>_<time>.vtk.
Parameters
config_file A pointer to a std::string object where the filename is specified.
use_timestamp integer indicating whether to append a timestamp
Definition at line 416 of file COM/testing/src/TestModule.C.
References my_window_name, COM::TestSolver::step, COM::TestSolver::time, and SolverUtils::WriteVTKToStream().
Referenced by Load().
     {
       std::string *config_name = NULL;
       if(config_file)
         config_name = static_cast<std::string *>(config_file);
       else{
         std::cerr << "TestModule::DumpSolution:Error: No filename given." << std::endl;
         return;
       }
       std::ostringstream Ostr;
       Ostr << *config_name;
       if(use_timestamp){
         if(*use_timestamp)
           Ostr << "_" << time[0];
         else {
           Ostr << "_" << step;
         }
       }
       Ostr << ".vtk";
       std::ofstream Ouf;
       Ouf.open(Ostr.str().c_str());
       if(!Ouf){
         std::cerr << "TestModule::DumpSolution:Error: Could not open output file, "
                   << Ostr.str() << "." << std::endl;
         return;
       }
       SolverUtils::WriteVTKToStream(my_window_name,*this,Ouf);
       Ouf.close();
     };
void COM::TestModule::Function0 (void * string_data) inline
This function just prints a message: "Hello COM from my_window_name!" to stdout and to the string passed in.
Parameters
string_data A pointer to a std::string object.
Returns
string_data set to the message.
Definition at line 179 of file COM/testing/src/TestModule.C.
References my_window_name.
Referenced by Load().
     {
       std::string *output_string = static_cast<std::string *>(string_data);
       std::ostringstream Ostr;
       Ostr << "Hello COM from " << my_window_name << "!";
       output_string->assign(Ostr.str());
       std::cout << *output_string << std::endl;
     };
void COM::TestModule::Function0F (char * string_data, int size) inline
This function just prints a message: "Hello COM from my_window_name!" to stdout and to the string passed in.
Parameters
string_data,int.
Returns
.
Definition at line 157 of file COM/testing/src/TestModule.C.
References my_window_name.
Referenced by Load().
     {
       std::cout << "Entering Function0F: " << std::endl
                 << "Size = " << size << std::endl;
       std::ostringstream Ostr;
       Ostr << "Hello COM from " << my_window_name << "!";
       std::string::size_type x=Ostr.str().size();
       if(x > size)
         x = size;
       strncpy(string_data, Ostr.str().c_str(), x);
       std::cout << string_data << std::endl;
     };
void COM::TestModule::Function1 (void * string_data) inline
This function loads another instance of this test module with the name passed in.
Parameters
string_data A pointer to a std::string object containing the name of the new window.
Definition at line 197 of file COM/testing/src/TestModule.C.
References COM_LOAD_MODULE_STATIC_DYNAMIC, and other_window_name.
Referenced by Load().
     {
       std::string *owindow_name = static_cast<std::string *>(string_data);
       other_window_name.assign(*owindow_name);
       COM_LOAD_MODULE_STATIC_DYNAMIC(COMTESTMOD,other_window_name.c_str());
     };
void COM::TestModule::Function2 (void * string_data) inline
This function calls the external module's "Hello COM World!" function (if it exists). The output from the call to the external module is returned in string_data.
Parameters
string_data A pointer to a std::String object where the results of the call will be returned.
Definition at line 214 of file COM/testing/src/TestModule.C.
References COM_call_function(), COM_get_function_handle(), COM_get_window_handle(), and other_window_name.
Referenced by Load().
     {
       if(!other_window_name.empty()){
         int other_window_handle = COM_get_window_handle(other_window_name.c_str());
         if(other_window_handle > 0){
           int other_function_handle = COM_get_function_handle((other_window_name+".Function0").c_str());
           if(other_function_handle > 0)
             COM_call_function(other_function_handle,string_data);
         }
       }
     };
void COM::TestModule::Function3 (void * string_data) inline
This function loads an instance of the Fortran test module with the name passed in.
Parameters
string_data A pointer to a std::string object containing the name of the new window.
Definition at line 236 of file COM/testing/src/TestModule.C.
References COM_LOAD_MODULE_STATIC_DYNAMIC, and fortran_window_name.
Referenced by Load().
     {
       std::string *fwindow_name = static_cast<std::string *>(string_data);
       fortran_window_name.assign(*fwindow_name);
       COM_LOAD_MODULE_STATIC_DYNAMIC(COMFTESTMOD,fortran_window_name.c_str());
     };
void COM::TestModule::Function4 (void * string_data) inline
This function calls the external Fortran module's "Hello COM World!" function (if it exists). The output from the call to the external module is returned in string_data.
Parameters
string_data A pointer to a std::String object where the results of the call will be returned.
Definition at line 254 of file COM/testing/src/TestModule.C.
References COM_call_function(), COM_get_function_handle(), COM_get_window_handle(), and fortran_window_name.
Referenced by Load().
     {
       std::string *output_string = static_cast<std::string *>(string_data);
       if(!fortran_window_name.empty()){
         int fortran_window_handle = COM_get_window_handle(fortran_window_name.c_str());
         if(fortran_window_handle > 0){
           int fortran_function_handle = COM_get_function_handle((fortran_window_name+".Function0").c_str());
           if(fortran_function_handle > 0)
           {
             std::vector<char> fresult(81,'\0');
             COM_call_function(fortran_function_handle,&fresult[0]);
             output_string->assign(&fresult[0]);
           }
         }
       }
     };
void COM::TestModule::get_communicator_module (int * commworks) inline
Definition at line 450 of file COM/testing/src/TestModule.C.
References COM_get_communicator(), and COM_get_default_communicator().
Referenced by Load().
     {
       const char *comm_name = "TestParallelWin1";
       typedef IRAD::Comm::CommunicatorObject CommType;
       CommType _communicator;
       bool getcommunicator = true;
       MPI_Comm comm, default_comm;
       COM_get_communicator(comm_name, &comm);
       default_comm = COM_get_default_communicator();
       if(comm != MPI_COMM_SELF){
         _communicator.SetErr(1);
         std::cout << "COM_get_communicator does not return the communicator"
                   << " used by set_default_communicator!" << std::endl;
       }
       *commworks = 1;
       if(_communicator.Check()){
         //getcommunicator = false;
         *commworks = 0;
       }
       std::cout << "Getcommunicator output:  " << getcommunicator << std::endl;
       _communicator.ClearErr();
     };
void COM::TestModule::Increment (int * i, int * rank) inline
Parameters
an integer
This function simply increments the value of the integer passed in to it.
Definition at line 278 of file COM/testing/src/TestModule.C.
Referenced by Load().
     {
       *i+=*rank;
     };
void COM::TestModule::InitSolver (void * config_file) inline
This function reads a configuration file and sets up some example solver-like data for use in testing
Parameters
config_file A pointer to a std::string object where the configuration filename is specified.
Definition at line 307 of file COM/testing/src/TestModule.C.
References SolverUtils::FEM::SolutionMetaData::AddField(), COM::TestSolver::cellflags, SolverUtils::Mesh::UnstructuredMesh::con, SolverUtils::FEM::SolverAgent::CreateSoln(), COM::TestSolver::delta_time, COM::TestSolver::displacements, SolverUtils::FEM::SolverAgent::Mesh(), SolverUtils::FEM::SolutionData::Meta(), my_window_name, SolverUtils::Mesh::UnstructuredMesh::nc, SolverUtils::Mesh::Connectivity::Nelem(), SolverUtils::Mesh::NodalCoordinates::NNodes(), COM::TestSolver::nodeflags, COM::TestSolver::pressures, SolverUtils::FEM::SolverAgent::ReadMeshFromStream(), SolverUtils::RegisterSolverInto(), SolverUtils::FEM::SolutionData::SetFieldBuffer(), SolverUtils::FEM::SolverAgent::Solution(), COM::TestSolver::step, COM::TestSolver::temperatures, and COM::TestSolver::time.
Referenced by Load().
     {
       std::string *config_name = NULL;
       if(config_file)
         config_name = static_cast<std::string *>(config_file);
       std::ifstream Inf;
       Inf.open(config_name->c_str());
       std::cout << "Opening config file " << config_name->c_str() << std::endl;
       if(!Inf){
         std::cerr << "TestModule::InitModule:Error: Could not open configuration file, "
                   << config_name->c_str() << "." << std::endl;
         return;
       }
       // for now, config is just "the mesh"
       ReadMeshFromStream(Inf);
       Inf.close();
       // Step (1) sets up solution meta data
       Solution().Meta().AddField("time",'s',1,8,"s");
       Solution().Meta().AddField("dt",'s',1,8,"s");
       Solution().Meta().AddField("id",'m',1,4,"");
       Solution().Meta().AddField("displacement",'n',3,8,"m");
       Solution().Meta().AddField("pressure",'c',1,8,"Pa");
       Solution().Meta().AddField("temperature",'n',1,8,"K");
       Solution().Meta().AddField("nodeflags",'n',1,4,"");
       Solution().Meta().AddField("cellflags",'c',1,4,"");
       // Step (2) creates the buffers for the actual data
       CreateSoln();
       unsigned int nnodes = Mesh().nc.NNodes();
       unsigned int nelem  = Mesh().con.Nelem();
       // Step (3) allocate our own local buffers for the data
       step = 0;
       time.resize(1,0);
       delta_time.resize(1,.1);
       id.resize(1,1);
       displacements.resize(3*nnodes,0);
       pressures.resize(nelem,1.0);
       temperatures.resize(nnodes,1.0);
       nodeflags.resize(nnodes,2);
       cellflags.resize(nelem,1);
       // Step (4) reset the buffers created above to be our own local buffers
       Solution().SetFieldBuffer("time",time);
       Solution().SetFieldBuffer("dt",delta_time);
       Solution().SetFieldBuffer("temperature",temperatures);
       Solution().SetFieldBuffer("nodeflags",nodeflags);
       Solution().SetFieldBuffer("cellflags",cellflags);
       Solution().SetFieldBuffer("displacement",displacements);
       Solution().SetFieldBuffer("pressure",pressures);
       Solution().SetFieldBuffer("id",id);
       SolverUtils::RegisterSolverInto(my_window_name,*this);
     };
static void COM::TestModule::Load (const std::string & name) inline static
This function creates an instance of a COM::TestModule object, creates a new Window with the specified name and registers the address of the new COM::TestModule object as the ".global" DataItem of the Window. This registers the C++ COM::TestModule "object" with the COM runtime system.
Next, several member functions are registered. The first argument to each member function is a COM_RAWDATA type which will be the address of the object registerd to the ".global" DataItem.
Parameters
name const std::string specifying the name of the window to load the module into.
Note
This function must be a static function in order for it to work in the COM_LOAD_MODULE interface.
The COM_VOID type has been used here to pass in a pointer to a std::string object. This is cool.
Definition at line 499 of file COM/testing/src/TestModule.C.
References COM_INT, COM_new_dataitem(), COM_new_window(), COM_RAWDATA, COM_set_function(), COM_set_member_function(), COM_set_object(), COM_STRING, COM_VOID, COM_window_init_done(), COM::ConstIntFunction(), DumpSolverSolution(), Function0(), Function0F(), Function1(), Function2(), Function3(), Function4(), get_communicator_module(), Increment(), InitSolver(), COM::IntFunction(), my_window_name, COM::TestSolver::name, COM::OptionalArgsFunction(), SleepMultiply(), Step(), TestModule(), and ValidateDataItemAddress().
Referenced by COMTESTMOD_load_module().
{
       std::cout << "Loading TestModule with name " << name
                 << "." << std::endl;
       TestModule *test_module_pointer = new TestModule();
       COM_new_window(name);
       test_module_pointer->my_window_name = name;
       std::string global_name(name+".global");
       COM_new_dataitem(global_name.c_str(),'w',COM_VOID,1,"");
       COM_set_object(global_name.c_str(),0,test_module_pointer);
       std::vector<COM_Type> types(13,COM_INT);
       types[0] = COM_RAWDATA;
       types[1] = COM_STRING;
       COM_set_member_function( (name+".Function0F").c_str(),
                                (Member_func_ptr)(&TestModule::Function0F),
                                global_name.c_str(), "bbi", &types[0]);
       types[1] = COM_VOID;
       COM_set_member_function( (name+".Function0").c_str(),
                                (Member_func_ptr)(&TestModule::Function0),
                                global_name.c_str(), "bb", &types[0]);
       COM_set_member_function( (name+".Function1").c_str(),
                                (Member_func_ptr)(&TestModule::Function1),
                                global_name.c_str(), "bi", &types[0]);
       COM_set_member_function( (name+".Init").c_str(),
                                (Member_func_ptr)(&TestModule::InitSolver),
                                global_name.c_str(), "bi", &types[0]);
       COM_set_member_function( (name+".ValidateAddress").c_str(),
                                (Member_func_ptr)(&TestModule::ValidateDataItemAddress),
                                global_name.c_str(), "biio", &types[0]);
       COM_set_member_function( (name+".Dump").c_str(),
                                (Member_func_ptr)(&TestModule::DumpSolverSolution),
                                global_name.c_str(), "bii", &types[0]);
       COM_set_member_function( (name+".Step").c_str(),
                                (Member_func_ptr)(&TestModule::Step),
                                global_name.c_str(), "b", &types[0]);
       COM_set_member_function( (name+".Function2").c_str(),
                                (Member_func_ptr)(&TestModule::Function2),
                                global_name.c_str(), "bb", &types[0]);
       COM_set_member_function( (name+".Function3").c_str(),
                                (Member_func_ptr)(&TestModule::Function3),
                                global_name.c_str(), "bi", &types[0]);
       COM_set_member_function( (name+".Function4").c_str(),
                                (Member_func_ptr)(&TestModule::Function4),
                                global_name.c_str(), "bb", &types[0]);
       types[1] = COM_INT;
       COM_set_member_function( (name+".get_communicator_module").c_str(),
                                (Member_func_ptr)(&TestModule::get_communicator_module),
                                global_name.c_str(), "bb", &types[0]);
       types[0] = COM_INT;
       types[1] = COM_INT;
       COM_set_member_function( (name+".Increment").c_str(),
                                (Member_func_ptr)(&TestModule::Increment),
                                global_name.c_str(), "bbi", &types[0]);
       COM_set_member_function( (name+".SleepMultiply").c_str(),
                                (Member_func_ptr)(&TestModule::SleepMultiply),
                                global_name.c_str(), "bi", &types[0]);
       COM_set_function((name+".IntFunction").c_str(),
                        (Func_ptr)(&IntFunction),"b",&types[0]);
       COM_set_function((name+".ConstIntFunction").c_str(),
                        (Func_ptr)(&ConstIntFunction),"io",&types[0]);
       COM_set_function((name+".OptionalArgsFunction").c_str(),
                        (Func_ptr)(&OptionalArgsFunction),
                        "bIIIIIIIIIIII",&types[0]);
       COM_window_init_done(name);
     }
void COM::TestModule::SleepMultiply (int * mult) inline
Parameters
This function simply sleeps for the number of seconds of its process rank
Definition at line 291 of file COM/testing/src/TestModule.C.
Referenced by Load().
     {
       sleep((*mult));
     };
void COM::TestModule::Step () inline
This function steps the dummy solver and sets up periodic solutions on the grid. time is advanced by delta_t.
Definition at line 379 of file COM/testing/src/TestModule.C.
References SolverUtils::Mesh::UnstructuredMesh::con, COM::TestSolver::delta_time, COM::TestSolver::displacements, SolverUtils::Mesh::DisplaceNodalCoordinates(), SolverUtils::Mesh::GetMeshCentroids(), SolverUtils::Mesh::NodalCoordinates::init_copy(), SolverUtils::FEM::SolverAgent::Mesh(), SolverUtils::Mesh::UnstructuredMesh::nc, SolverUtils::Mesh::Connectivity::Nelem(), SolverUtils::Mesh::NodalCoordinates::NNodes(), COM::TestSolver::pressures, COM::TestSolver::step, COM::TestSolver::temperatures, and COM::TestSolver::time.
Referenced by Load().
     {
       step++;
       unsigned int nnodes = Mesh().nc.NNodes();
       unsigned int nelem  = Mesh().con.Nelem();
       double pi = 4.0*std::atan(1.0)/5.0;
       time[0] += delta_time[0];
       double t = time[0];
       for(int i = 0;i < nnodes;i++){
         double xcomp = std::sin(pi*Mesh().nc.x(i+1));
         double ycomp = std::sin(pi*Mesh().nc.y(i+1));
         double tcomp = std::sin(5.0*pi*t);
         double disp = xcomp*ycomp*tcomp;
         displacements[i*3+2] = xcomp*ycomp*tcomp;
         temperatures[i] = disp*disp;
       }
       SolverUtils::Mesh::NodalCoordinates nccopy;
       nccopy.init_copy(nnodes,Mesh().nc.Data());
       SolverUtils::Mesh::DisplaceNodalCoordinates(nccopy,displacements);
       std::vector<double> centroids(3*nelem,0);
       SolverUtils::Mesh::GetMeshCentroids(nccopy,Mesh().con,centroids);
       for(int i = 0;i < nelem;i++)
         pressures[i] = centroids[i*3+2];
     };
static void COM::TestModule::Unload (const std::string & name) inline static
This function simply destroys the COM::TestModuleObject created in the call to Load and then deletes the associated window with the specified name.
Definition at line 592 of file COM/testing/src/TestModule.C.
References COM_assertion_msg, COM_delete_window(), and COM_get_object().
Referenced by COMTESTMOD_unload_module().
{
       std::cout << "Unloading TestModule with name " << name
                 << "." << std::endl;
       TestModule *test_module_pointer = NULL;
       std::string global_name(name+".global");
       COM_get_object(global_name.c_str(),0,&test_module_pointer);
       COM_assertion_msg( test_module_pointer->validate_object()==0, "Invalid object");
       if(test_module_pointer){
         std::cout << "Deleting test_module_pointer" << std::endl;
         delete test_module_pointer;
       }
       std::cout << "Deleting window (" << name << ")" << std::endl;
       COM_delete_window(std::string(name));
       std::cout << "Done Unloading module." << std::endl;
     }
void COM::TestModule::ValidateDataItemAddress (void * name_of_dataitem, void * address, int * result) inline
Definition at line 365 of file COM/testing/src/TestModule.C.
References SolverUtils::FEM::DataBuffer::data(), SolverUtils::FEM::SolutionData::GetFieldData(), and SolverUtils::FEM::SolverAgent::Solution().
Referenced by Load().
{
       std::string *name_string = static_cast<std::string *>(name_of_dataitem);
       if(Solution().GetFieldData(*name_string).data() == static_cast<const char *>(address)){
         *result = 1;
       }
     }
Member Data Documentation
std::string COM::TestModule::fortran_window_name private
Definition at line 611 of file COM/testing/src/TestModule.C.
Referenced by Function3(), Function4(), TestModule(), and ~TestModule().
std::string COM::TestModule::my_window_name private
Definition at line 609 of file COM/testing/src/TestModule.C.
Referenced by DumpSolverSolution(), Function0(), Function0F(), InitSolver(), Load(), and TestModule().
std::string COM::TestModule::other_window_name private
Definition at line 610 of file COM/testing/src/TestModule.C.
Referenced by Function1(), Function2(), TestModule(), and ~TestModule().
The documentation for this class was generated from the following file:
COM/testing/src/TestModule.C