IMPACT: TemperatureTransfer_SF Class Reference
TemperatureTransfer_SF Class Reference
Detailed Description
Definition at line 182 of file transfer_actions.h.
#include <transfer_actions.h>
Public Member Functions
TemperatureTransfer_SF (SolidAgent *sag, FluidAgent *ag, const std::string s_Tf, const std::string fb_Tflm_alp, const std::string fn_Tb)
void init (double t)
void run (double t, double dt, double alpha)
Public Member Functions inherited from InterMeshTransfer
InterMeshTransfer (FluidAgent *fag, SolidAgent *sag, char *name=NULL)
Public Member Functions inherited from Action
Action (void *p=0, const char *name=NULL)
Action (int n, const char **at, int *i=NULL, void *p=0, const char *name=NULL)
Action (int n, const std::string at[], int *i=NULL, void *p=0, const char *name=NULL)
virtual ~Action ()
virtual void declare (Scheduler &)
virtual void finalize ()
virtual const char * name ()
void set_name (const char *name)
virtual void print (FILE *f)
virtual void print_toposort (FILE *f)
virtual void schedule ()
Private Attributes
int s_Ts_hdl
int fb_Tflm_hdl
int fn_Tb_hdl
int f_Ts_hdl
int bcflag_hdl
int RFC_interpolate
int RFC_transfer
Additional Inherited Members
Protected Types inherited from Action
enum { IN =1, OUT =2, INOUT =3 }
Protected Member Functions inherited from InterMeshTransfer
void load_rocface (const RocmanControl_parameters *param)
Protected Member Functions inherited from Action
int get_dataitem_handle (int i)
int get_dataitem_handle_const (int i)
int get_dataitem_handle (const std::string str)
void set_attr (int n, const std::string at[], int *id=NULL)
void set_attr (int n, const char *at[], int *id=NULL)
void set_io (int n, const int *io)
void set_io (const char *io)
int get_io (int i)
Protected Attributes inherited from InterMeshTransfer
FluidAgent * fagent
SolidAgent * sagent
Protected Attributes inherited from Action
const char * action_name
char ** attr
int * idx
int count
void * usr_ptr
std::vector< int > inout
Constructor & Destructor Documentation
TemperatureTransfer_SF::TemperatureTransfer_SF (SolidAgent * sag, FluidAgent * ag, const std::string s_Tf, const std::string fb_Tflm_alp, const std::string fn_Tb)
Definition at line 947 of file transfer_actions.C.
References COM_assertion_msg, InterMeshTransfer::fagent, FluidAgent::fluidBufNG, Agent::get_surface_window(), Action::IN, Action::OUT, Agent::register_clone_dataitem(), Action::set_attr(), and Action::set_io().
                                                                 :
                  InterMeshTransfer(fag, sag, "TemperatureTransfer_SF")
 {
   int io[] = {IN, OUT, OUT};
   set_io( 3, io);
   std::string.data[3];
  .data[0] = s_Ts;
  .data[1] = fb_Tflm;
  .data[2] = fn_Tb;
   set_attr(3,.data);
   fagent->register_clone_dataitem( 0, fagent->fluidBufNG, ".ts", fagent->get_surface_window(), ".pf", 0);
     // Tb is rocman internal buffer
   std::string::size_type pos = fn_Tb.find( ".");
   COM_assertion_msg(pos!=std::string::npos, "LoadTransfer_FS failed!");
   std::string fn = fn_Tb.substr( 0, pos);
   std::string Tb = fn_Tb.substr( pos, fn_Tb.size());
   fagent->register_clone_dataitem( 0, fn, Tb, fagent->get_surface_window(), ".Tb_alp", 0);
   fagent->register_clone_dataitem( 0, fn, Tb+"_old", fagent->get_surface_window(), ".Tb_alp", 0);
 }
Member Function Documentation
void TemperatureTransfer_SF::init (double t) virtual
Reimplemented from Action.
Definition at line 972 of file transfer_actions.C.
References bcflag_hdl, COM_get_function_handle(), f_Ts_hdl, InterMeshTransfer::fagent, fb_Tflm_hdl, FluidAgent::fluidBufNG, fn_Tb_hdl, Agent::get_coupling(), Action::get_dataitem_handle(), Coupling::get_rocmancontrol_param(), InterMeshTransfer::load_rocface(), RFC_interpolate, RFC_transfer, and s_Ts_hdl.
{
   s_Ts_hdl = get_dataitem_handle( 0);
   fb_Tflm_hdl = get_dataitem_handle( 1);
   fn_Tb_hdl = get_dataitem_handle( 2);
   f_Ts_hdl = get_dataitem_handle( fagent->fluidBufNG+".ts");
   bcflag_hdl = get_dataitem_handle( fagent->fluidBufNG+".bcflag");
   load_rocface( fagent->get_coupling()->get_rocmancontrol_param());
   RFC_transfer = COM_get_function_handle("RFC.least_squares_transfer");
   RFC_interpolate = COM_get_function_handle("RFC.interpolate");
 }
void TemperatureTransfer_SF::run (double t, double dt, double alpha) virtual
Reimplemented from Action.
Definition at line 986 of file transfer_actions.C.
References bcflag_hdl, COM_call_function(), COM_copy_dataitem(), f_Ts_hdl, InterMeshTransfer::fagent, fb_Tflm_hdl, fn_Tb_hdl, Agent::get_comm_rank(), MAN_DEBUG, RFC_transfer, and s_Ts_hdl.
{
   MAN_DEBUG(2, ("[%d] Rocman: TemperatureTransfer_SF::run() with t:%e dt:%e.\n", fagent->get_comm_rank(), t, dt));
   //debug_print(sagent->solidBuf+".Ts", 102, 0);
   COM_call_function( RFC_transfer, &s_Ts_hdl, &f_Ts_hdl);
     // extract burn and non-burn values
   COM_copy_dataitem( fb_Tflm_hdl, f_Ts_hdl, 1, bcflag_hdl, 1);
   COM_copy_dataitem( fn_Tb_hdl, f_Ts_hdl, 1, bcflag_hdl, 0);
   //debug_print(fagent->fluidBufNG+".Tf", 2, 0);
 }
Member Data Documentation
int TemperatureTransfer_SF::bcflag_hdl private
Definition at line 189 of file transfer_actions.h.
Referenced by init(), and run().
int TemperatureTransfer_SF::f_Ts_hdl private
Definition at line 189 of file transfer_actions.h.
Referenced by init(), and run().
int TemperatureTransfer_SF::fb_Tflm_hdl private
Definition at line 188 of file transfer_actions.h.
Referenced by init(), and run().
int TemperatureTransfer_SF::fn_Tb_hdl private
Definition at line 188 of file transfer_actions.h.
Referenced by init(), and run().
int TemperatureTransfer_SF::RFC_interpolate private
Definition at line 190 of file transfer_actions.h.
Referenced by init().
int TemperatureTransfer_SF::RFC_transfer private
Definition at line 191 of file transfer_actions.h.
Referenced by init(), and run().
int TemperatureTransfer_SF::s_Ts_hdl private
Definition at line 188 of file transfer_actions.h.
Referenced by init(), and run().
The documentation for this class was generated from the following files:
transfer_actions.h
transfer_actions.C