IMPACT: ComputeMeshMotion Class Reference
ComputeMeshMotion Class Reference
Detailed Description
Definition at line 131 of file basic_actions.h.
#include <basic_actions.h>
Public Member Functions
ComputeMeshMotion (FluidAgent *ag, const std::string a_vm, const std::string f_du_alp, double z)
void init (double t)
void run (double t, double dt, double alpha)
Public Member Functions inherited from Action
Action (void *p=0, const char *name=NULL)
Action (int n, const char **at, int *i=NULL, void *p=0, const char *name=NULL)
Action (int n, const std::string at[], int *i=NULL, void *p=0, const char *name=NULL)
virtual ~Action ()
virtual void declare (Scheduler &)
virtual void finalize ()
virtual const char * name ()
void set_name (const char *name)
virtual void print (FILE *f)
virtual void print_toposort (FILE *f)
virtual void schedule ()
Private Attributes
FluidAgent * fagent
double zoom
int a_vm_hdl
int f_du_alp_hdl
int f_zoom_hdl
Additional Inherited Members
Protected Types inherited from Action
enum { IN =1, OUT =2, INOUT =3 }
Protected Member Functions inherited from Action
int get_dataitem_handle (int i)
int get_dataitem_handle_const (int i)
int get_dataitem_handle (const std::string str)
void set_attr (int n, const std::string at[], int *id=NULL)
void set_attr (int n, const char *at[], int *id=NULL)
void set_io (int n, const int *io)
void set_io (const char *io)
int get_io (int i)
Protected Attributes inherited from Action
const char * action_name
char ** attr
int * idx
int count
void * usr_ptr
std::vector< int > inout
Constructor & Destructor Documentation
ComputeMeshMotion::ComputeMeshMotion (FluidAgent * ag, const std::string a_vm, const std::string f_du_alp, double z)
Definition at line 276 of file basic_actions.C.
References COM_DOUBLE, fagent, Action::IN, Action::OUT, FluidAgent::propBufAll, Agent::register_new_dataitem(), Action::set_attr(), and Action::set_io().
                                                                          :
                 Action(0, (const char**)NULL, NULL, NULL, "ComputeMeshMotion"),
                 fagent(ag), zoom(z)
 {
   int io[] = {IN, OUT};
   set_io( 2, io);
   std::string.data[2];
  .data[0] = a_vm;
  .data[1] = f_du_alp;
   set_attr(2,.data);
   fagent->register_new_dataitem( fagent->propBufAll, ".vm", 'n', COM_DOUBLE, 3, "m/s");
 }
Member Function Documentation
void ComputeMeshMotion::init (double t) virtual
Reimplemented from Action.
Definition at line 292 of file basic_actions.C.
References a_vm_hdl, Action::attr, COM_get_dataitem_handle(), f_du_alp_hdl, f_zoom_hdl, fagent, FluidAgent::fluidBufNG, Action::get_dataitem_handle(), and Agent::get_surface_window().
{
   a_vm_hdl = get_dataitem_handle(0);
   f_du_alp_hdl = get_dataitem_handle(fagent->get_surface_window()+attr[1]);
     // can not be set earlier because surface window was unkown
   //f_du_alp_hdl = COM_get_dataitem_handle(fagent->get_surface_window()+".du_alp");
   f_zoom_hdl = COM_get_dataitem_handle(fagent->fluidBufNG+".zoomFact");  // used internally
 }
void ComputeMeshMotion::run (double t, double dt, double alpha) virtual
Reimplemented from Action.
Definition at line 302 of file basic_actions.C.
References a_vm_hdl, COM_assertion_msg, COM_call_function(), RocBlas::copy_scalar, f_du_alp_hdl, f_zoom_hdl, MAN_DEBUG, RocBlas::mul_scalar, and zoom.
{
   MAN_DEBUG(2, ("Rocman: ComputeMeshMotion::run() with dt:%e alpha:%e.\n", dt, alpha));
   COM_assertion_msg(alpha>=0.0, "ERROR: ComputeMeshMotion called with invalid alpha!");
 //  debug_print(fagent->get_surface_window()+".du_alp", 102, 0);
   double time = alpha * dt;
   COM_call_function( RocBlas::mul_scalar, &a_vm_hdl, &time, &f_du_alp_hdl);
 //  debug_print(fagent->propBufAll+".vm", 202, 1);
 //  debug_print(fagent->get_surface_window()+".du_alp", 102, 0);
   if (f_zoom_hdl>0) {
     COM_call_function( RocBlas::copy_scalar, &zoom, &f_zoom_hdl);
   }
 }
Member Data Documentation
int ComputeMeshMotion::a_vm_hdl private
Definition at line 139 of file basic_actions.h.
Referenced by init(), and run().
int ComputeMeshMotion::f_du_alp_hdl private
Definition at line 139 of file basic_actions.h.
Referenced by init(), and run().
int ComputeMeshMotion::f_zoom_hdl private
Definition at line 139 of file basic_actions.h.
Referenced by init(), and run().
FluidAgent* ComputeMeshMotion::fagent private
Definition at line 137 of file basic_actions.h.
Referenced by ComputeMeshMotion(), and init().
double ComputeMeshMotion::zoom private
Definition at line 138 of file basic_actions.h.
Referenced by run().
The documentation for this class was generated from the following files:
basic_actions.h
basic_actions.C