IMPACT: PhysicsAction Class Reference
PhysicsAction Class Reference
Detailed Description
Definition at line 130 of file Agent.h.
#include <Agent.h>
Public Member Functions
PhysicsAction (Agent *ag)
void run (double t, double dt, double alpha)
void declare (Scheduler &)
virtual void print (FILE *f)
virtual const char * name ()
Public Member Functions inherited from Action
Action (void *p=0, const char *name=NULL)
Action (int n, const char **at, int *i=NULL, void *p=0, const char *name=NULL)
Action (int n, const std::string at[], int *i=NULL, void *p=0, const char *name=NULL)
virtual ~Action ()
virtual void init (double t)
virtual void finalize ()
void set_name (const char *name)
virtual void print_toposort (FILE *f)
virtual void schedule ()
Private Attributes
Agent * agent
Additional Inherited Members
Protected Types inherited from Action
enum { IN =1, OUT =2, INOUT =3 }
Protected Member Functions inherited from Action
int get_dataitem_handle (int i)
int get_dataitem_handle_const (int i)
int get_dataitem_handle (const std::string str)
void set_attr (int n, const std::string at[], int *id=NULL)
void set_attr (int n, const char *at[], int *id=NULL)
void set_io (int n, const int *io)
void set_io (const char *io)
int get_io (int i)
Protected Attributes inherited from Action
const char * action_name
char ** attr
int * idx
int count
void * usr_ptr
std::vector< int > inout
Constructor & Destructor Documentation
PhysicsAction::PhysicsAction (Agent * ag) inline
Definition at line 134 of file Agent.h.
 : Action(0, static_cast<const char **>(NULL), NULL, NULL, "PhysicsAction"), agent(ag) {}
Member Function Documentation
void PhysicsAction::declare (Scheduler &) inline virtual
Reimplemented from Action.
Definition at line 136 of file Agent.h.
 {}
const char * PhysicsAction::name () virtual
Reimplemented from Action.
Definition at line 64 of file Agent.C.
References agent, and Agent::get_agent_name().
 {
   return (const char *)agent->get_agent_name().c_str();
 }
void PhysicsAction::print (FILE * f) virtual
Reimplemented from Action.
Definition at line 59 of file Agent.C.
References agent, and Agent::print().
 {
   agent->print(f);
 }
void PhysicsAction::run (double t, double dt, double alpha) virtual
Reimplemented from Action.
Definition at line 34 of file Agent.C.
References agent, Agent::bc_handle, COM_call_function(), Agent::comm_rank, Agent::current_deltatime, Agent::current_time, Agent::get_agent_name(), Agent::get_coupling(), Coupling::get_ipc(), Agent::gm_handle, MAN_DEBUG, Agent::old_dt, Agent::run_bcinitaction(), Agent::timestamp, Agent::update_handle, and Agent::withgm.
 {
   MAN_DEBUG(1, ("[%d] Rocman: Agent %s::PhysicsAction run with t:%e dt:%e alpha:%e.\n", agent->comm_rank, agent->get_agent_name().c_str(), t, dt, alpha));
     // store it, gm callback needs it
   agent->current_deltatime = dt;
   agent->timestamp = t;
   if (agent->get_coupling()->get_ipc() == 1)
       agent->old_dt = dt;
   // include Interpolate::backup
   agent->run_bcinitaction(t, dt);
   //
   if(!agent->withgm)
     COM_call_function(agent->update_handle, &t, &dt,
                       &agent->bc_handle);
   else
     COM_call_function(agent->update_handle, &t, &dt,
                       &agent->bc_handle, &agent->gm_handle);
   agent->current_time = t;
 }
Member Data Documentation
Agent* PhysicsAction::agent private
Definition at line 132 of file Agent.h.
Referenced by name(), print(), and run().
The documentation for this class was generated from the following files:
Agent.h
Agent.C