IMPACT: RFC_Pane_overlay Class Reference
RFC_Pane_overlay Class Reference
Detailed Description
Definition at line 41 of file RFC_Window_overlay.h.
#include <RFC_Window_overlay.h>
Public Types
typedef RFC_Pane_overlay Self
typedef RFC_Pane_base Base
typedef
MAP::Simple_manifold_2::Edge_ID Edge_ID
Public Types inherited from RFC_Pane_base
typedef RFC_Pane_base Self
typedef COM::Pane Base
typedef COM::DataItem DataItem
typedef Base::Size Size
typedef RFC::Real Real
typedef std::pair< int, int > V2b
Pane id and local boundary id.
typedef std::map< int, V2b > V2b_table
From node id to its corresponding map.
typedef std::vector< int > B2v
From local boundary ids to node ids.
typedef std::map< int, B2v > B2v_table
From pane id to its corresponding mapping.
Public Member Functions
RFC_Pane_overlay (COM::Pane *b, int color)
virtual ~RFC_Pane_overlay ()
RFC_Window_overlay * window ()
const RFC_Window_overlay * window () const
const HEdge & get_counterpart (Edge_ID eID) const
HEdge get_opposite_edge (Edge_ID eID) const
Obtain the opposite edge in a given access mode.
HEdge get_prev_edge (Edge_ID eID)
Obtain the previous edge in a given access mode.
HEdge get_next_edge (Edge_ID eID)
Obtain the next edge in a given access mode.
int get_index (const Node &v) const
int get_index (const HEdge &h) const
int get_index (const Edge_ID &id) const
int get_index (const Face &f) const
int get_lid (const Node &v) const
int get_lid (const Face &f) const
Node get_node_from_id (int i)
bool is_primary (const Node &v) const
const Node get_primary (const Node &v) const
const Point_3 & get_point (int id) const
const Point_3 & get_point (const Node &v) const
HEdge get_counterpart (const HEdge &h)
Vector_3 & get_normal (int v)
const Vector_3 & get_normal (int v) const
void set_normal (int v, const Vector_3 &vec)
Vector_3 & get_normal (const HEdge &h, const Node &v)
Vector_3 & get_tangent (const HEdge &h, const Node &v)
Vector_3 & get_normal (const HEdge &h, int i)
const Vector_3 & get_normal (const HEdge &h, int i) const
const Vector_3 & get_normal (HEdge h, const Node &v) const
const Vector_3 & get_tangent (HEdge h, const Node &v) const
void add_tangent (const HEdge &h, const Vector_3 &v)
INode * get_inode (const Node &v) const
void set_inode (const Node &v, INode *i)
INode_list & get_inode_list (const HEdge &h)
const INode_list & get_inode_list (const HEdge &h) const
INode * get_buffered_inode (const HEdge &h, int tag) const
void set_buffered_inode (const HEdge &h, int tag, INode *inode)
void mark (const HEdge &h)
void unmark (const HEdge &h)
bool marked (const HEdge &h) const
bool is_on_feature (const Node &v) const
bool is_feature_0 (const Node &v) const
bool is_feature_1 (const HEdge &h) const
const int & size_of_subfaces () const
int & size_of_subfaces ()
void allocate_subnodes (int num_sn)
Allocate memory space for the arrays for storing the subdivision.
void allocate_subfaces (const std::vector< int > &cnts)
Allocate memory space for the arrays for storing the subdivision.
void insert_subface (int idx, int plid, const int *lids, const ParentEdge_ID *eids, const Point_2 *nc, int rp_id, int cnt, const int *rids)
Insert all the infomation related to a subface into the database.
Public Member Functions inherited from RFC_Pane_base
RFC_Pane_base (Base *b, int color)
A constructor.
void init ()
virtual ~RFC_Pane_base ()
The default destructor.
Base * base ()
The id of its base COM::Pane object.
const Base * base () const
int id () const
bool is_master () const
Is this pane a master copy?
bool is_replicate () const
Is this pane not a master copy?
bool is_quadratic () const
Does this pane contain quadratic elements?
bool is_border_node (int i) const
Is a give node on the boundary of the pane?
bool is_isolated_node (int i) const
Is a give node an isolated node not belong to any element?
bool coincident (int i, int j) const
Report whether the two given nodes are coincident.
int size_of_nodes () const
The total number of nodes in the pane.
int size_of_faces () const
The total number of faces in the pane.
int size_of_isolated_nodes () const
int size_of_border_nodes () const
ParentEdge_ID get_edge_id (const int face_lid, const int vertex_lid) const
Get the edge id within a given face.
int size_of_subnodes () const
The total number of nodes in the subdivision of the pane.
int size_of_subfaces () const
The total number of faces in the subdivision of the pane.
Real * pointer (int i)
Get the address of a given dataitem with id i.
const Real * pointer (int i) const
bool is_primary_node (const int vid) const
Is the node with given local id a primary one?
int size_of_primary_nodes () const
Get total number of primary nodes contained in the pane.
const Point_3 & get_point (int id) const
Get the physical coordinates of the node with given local id.
const Point_3 & get_point (int id, int) const
const Real * coordinates () const
Point_3 get_point_of_subnode (int id) const
Bbox_3 get_bounding_box () const
Get the bounding box of the pane.
int color () const
The color of the parent window (BLUE or GREEN).
int parent_type_of_subnode (int) const
Determine the parent type of a subnode of given tyep.
int get_parent_node (int) const
Get the local parent node id of a given subnode.
int get_parent_face (int id) const
Get the local parent face id of a given subface.
template<class Point >
void normalize_nat_coor (int idx, int e, Point &nc) const
void get_host_element_of_subnode (int i, Element_node_enumerator &ene, Point_2 &nc) const
void get_host_element_of_subface (int i, Element_node_enumerator &ene) const
void get_nat_coor_in_element (const int eid, const int lid, Point_2 &nc) const
Take a subface id and a local subnode id, return the natual coordinates of the subnode within the parent element.
void get_nat_coor_in_element (const int sn_id, Element_node_enumerator &ene, Point_2 &nc) const
Take a subnode id and an element, return the natrual coordinates within the element.
std::pair< const
COM::Connectivity *, int > get_element (int face_id) const
Get the connectivity object and the id within the connectivity object for a given element.
const Node_ID & get_subnode_counterpart (int i) const
const Face_ID & get_subface_counterpart (int i) const
int get_lvid (const Element_node_enumerator &ene, const int v) const
Protected Member Functions
void evaluate_normals ()
void determine_counterparts ()
void unmark_alledges ()
float & get_cos_face_angle (const HEdge &h)
const float & get_cos_face_angle (const HEdge &h) const
void init_face_angle ()
const float & get_angle_defect (const Node &v) const
float & get_angle_defect (const Node &v)
void init_angle_defect ()
const float & get_cos_edge_angle (const Node &v) const
float & get_cos_edge_angle (const Node &v)
void reset_cos_edge_angle (const Node &v)
void init_edge_angle ()
void set_strong_edge (const HEdge &h)
void unset_strong_edge (const HEdge &h)
void set_feature_0 (const Node &v)
void unset_feature_0 (const Node &v)
void set_on_feature (const Node &v)
void unset_on_feature (const Node &v)
void create_overlay_data ()
void delete_overlay_data ()
void construct_bvpair2edge ()
int get_border_index (const HEdge &h) const
Protected Member Functions inherited from RFC_Pane_base
void comp_nat_coors ()
Compute the natural coordinates.
void build_v2b_from_b2v (const RFC_Window_base *w)
Build pane connectivity.
void write_tec_ij (std::ostream &, const COM::DataItem *a=0) const
void write_tec_tri (std::ostream &, const COM::Connectivity &, const COM::DataItem *a=0) const
void write_tec_mixed (std::ostream &, const std::vector< const COM::Connectivity * > &, const COM::DataItem *a=0) const
void write_tec_sub (std::ostream &) const
void write_tec_ascii (std::ostream &os, const COM::DataItem *attr=0) const
void write_binary (std::ostream &os) const
void write_off (std::FILE *fhandle) const
void read_binary (std::istream &is, std::vector< int > *b2v_all=NULL, COM::Pane *p=NULL)
void register_sdv_dataitems (const std::string &wname) const
void read_rocin (const std::string &sdv_wname, const std::string &parent_wname="", COM::Pane *p=NULL)
Read in using Rocin.
Protected Attributes
RFC_Window_overlay * _window
std::map< std::pair< int, int >
, HEdge > _bv2edges
std::vector< HEdge > _cntrs_hedge
std::vector< Node > _primnodes
std::vector< Vector_3 > _nrmls
std::vector< Vector_3 > _f_nrmls
std::vector< int > _f_n_index
std::vector< Vector_3 > _f_tngts
std::vector< int > _f_t_index
std::vector< float > _ad_0
std::vector< float > _ea_0
std::vector< float > _fd_1
std::vector< bool > _is_f_0
std::vector< bool > _is_on_f
std::vector< bool > _is_f_1
std::vector< INode * > _v_nodes
std::vector< INode * > _e_node_buf
std::vector< INode_list > _e_node_list
std::vector< int > _e_marks
int _size_of_subfaces
std::vector< const INode * > _subnodes
Protected Attributes inherited from RFC_Pane_base
Base * _base
Reference to its base object.
bool _is_master
Is the pane a master copy?
bool _quadratic
Does it contain quadratic elements?
std::vector< bool > _is_border
Is a node on border?
std::vector< bool > _is_isolated
Is a node isolated?
int _n_border
int _n_isolated
V2b_table _v2b_table
B2v_table _b2v_table
std::vector< ParentEdge_ID > _subnode_parents
Edge ids of parents.
std::vector< Point_2S > _subnode_nat_coors
Natual coordinates in the parent face.
std::vector< Point_2S > _subnode_normalized_nc
Natual coordinates in the parent face.
std::vector< int > _subnode_subID
Sub-node ID of nodes in the pane.
std::vector< Node_ID > _subnode_counterparts
Ids of counterparts of subnodes.
std::vector< Three_tuple< int > > _subfaces
std::vector< int > _subface_parents
Face ids of the parents of the subfaces.
std::vector< int > _subface_offsets
Offsets of first subfaces contained in a face.
std::vector< Face_ID > _subface_counterparts
Ids of counterparts of faces.
std::vector< Three_tuple
< Point_2S > > _subface_nat_coors
Element connectivity of the subfaces.
Friends
class RFC_Window_overlay
class Node
class HEdge
class Face
Member Typedef Documentation
typedef RFC_Pane_base RFC_Pane_overlay::Base
Definition at line 45 of file RFC_Window_overlay.h.
typedef MAP::Simple_manifold_2::Edge_ID RFC_Pane_overlay::Edge_ID
Definition at line 46 of file RFC_Window_overlay.h.
typedef RFC_Pane_overlay RFC_Pane_overlay::Self
Definition at line 44 of file RFC_Window_overlay.h.
Constructor & Destructor Documentation
RFC_Pane_overlay::RFC_Pane_overlay (COM::Pane * b, int color)
Definition at line 27 of file RFC_Window_overlay.C.
   : Base(b, color) {}
virtual RFC_Pane_overlay::~RFC_Pane_overlay () inline virtual
Definition at line 59 of file RFC_Window_overlay.h.
 {}
Member Function Documentation
void RFC_Pane_overlay::add_tangent (const HEdge & h, const Vector_3 & v) inline
Definition at line 168 of file RFC_Window_overlay.h.
References _f_t_index, _f_tngts, and get_index().
Referenced by RFC_Window_overlay::evaluate_normals().
{
     int &ind = _f_t_index[ get_index(h)];
     if ( ind < 0) { ind = _f_tngts.size(); _f_tngts.push_back( v); }
     else _f_tngts[ind] += v;
   }
void RFC_Pane_overlay::allocate_subfaces (const std::vector< int > & cnts) inline
Definition at line 217 of file RFC_Window_overlay.h.
References RFC_Pane_base::_subface_counterparts, RFC_Pane_base::_subface_offsets, RFC_Pane_base::_subface_parents, RFC_Pane_base::_subfaces, RFC_assertion, and RFC_Pane_base::size_of_faces().
Referenced by Overlay::number_subfaces().
{
     int nf = size_of_faces();  RFC_assertion( nf == int(cnts.size()));
     _subface_offsets.resize( nf+1);
     _subface_offsets[0] = 0;
     for ( int i=1; i<=nf; ++i) {
       _subface_offsets[i] = _subface_offsets[i-1]+cnts[i-1];
     }
     int nsf=_subface_offsets[nf];
     _subfaces.resize( nsf);
     _subface_parents.resize( nsf);
     _subface_counterparts.resize( nsf);
   }
void RFC_Pane_overlay::allocate_subnodes (int num_sn) inline
Definition at line 210 of file RFC_Window_overlay.h.
References RFC_Pane_base::_subnode_counterparts, RFC_Pane_base::_subnode_nat_coors, and RFC_Pane_base::_subnode_parents.
{
     _subnode_parents.resize( num_sn);
     _subnode_nat_coors.resize( num_sn);
     _subnode_counterparts.resize( num_sn);
   }
void RFC_Pane_overlay::construct_bvpair2edge () protected
Definition at line 375 of file RFC_Window_overlay.C.
References _bv2edges, HEdge::destination_l(), get_lid(), HEdge, HEdge::origin_l(), and s.
{
   for ( int i=1, s=size_of_border_edges(); i<=s; ++i) {
     HEdge h = HEdge( this, Edge_ID(i,Edge_ID::BndID)).opposite_l();
     _bv2edges[ make_pair( get_lid( h.origin_l()),
                           get_lid( h.destination_l()))] = h;
   }
 }
void RFC_Pane_overlay::create_overlay_data () protected
Definition at line 411 of file RFC_Window_overlay.C.
References _e_marks, _e_node_buf, _e_node_list, _v_nodes, RFC_Pane_base::color(), RFC_Pane_base::size_of_faces(), and RFC_Pane_base::size_of_nodes().
Referenced by RFC_Window_overlay::create_overlay_data().
{
   _v_nodes.resize(0);
   _e_node_list.resize(0);
   _e_node_buf.resize(0);
   _e_marks.resize(0);
   _v_nodes.resize( size_of_nodes(),0);
   int n=4*size_of_faces() + size_of_border_edges();
   _e_node_list.resize( n, INode_list( color()));
   _e_node_buf.resize( n, 0);
   _e_marks.resize( n, 0);
 }
void RFC_Pane_overlay::delete_overlay_data () protected
Definition at line 426 of file RFC_Window_overlay.C.
References _ad_0, _cntrs_hedge, _e_marks, _e_node_buf, _e_node_list, _ea_0, _f_n_index, _f_nrmls, _f_t_index, _f_tngts, _fd_1, _primnodes, _v_nodes, and free_vector().
Referenced by RFC_Window_overlay::delete_overlay_data().
{
   free_vector( _v_nodes);
   free_vector( _e_node_list);
   free_vector( _e_node_buf);
   free_vector( _e_marks);
   free_vector( _cntrs_hedge); free_vector( _primnodes);
   free_vector( _f_nrmls); free_vector( _f_tngts);
   free_vector( _f_n_index); free_vector( _f_t_index);
   free_vector( _ad_0); free_vector( _ea_0); free_vector( _fd_1);
 }
void RFC_Pane_overlay::determine_counterparts () protected
Definition at line 274 of file RFC_Window_overlay.C.
References RFC_Pane_base::_b2v_table, _bv2edges, _cntrs_hedge, _primnodes, _window, HEdge::destination_l(), get_border_index(), get_lid(), RFC_Window_derived< _Pane >::get_primary(), Node::halfedge_l(), RFC_Pane_base::id(), RFC_Window_base::name(), HEdge::origin_l(), RFC_Window_derived< _Pane >::pane(), and RFC_assertion.
{
   typedef set< pair<int,int> >      V2h;
   typedef map<int, V2h>             V2h_table;
   V2h_table  _v2h_table;
   //`Loop through the B2v_table
   for ( B2v_table::iterator
           it=_b2v_table.begin(), iend=_b2v_table.end(); it != iend; ++it) {
     for ( int i=0, size=it->second.size(); i<size; ++i) {
       pair<int,int> p(it->first, i);
       if ( it->first==id()) {
         if ( i&1) --p.second; else ++p.second;
       }
       _v2h_table[it->second[i]].insert( p);
     }
   }
   _cntrs_hedge.resize( size_of_border_edges());
   // Loop through all border edges.
   for ( int i=0; i<size_of_border_edges(); ++i) {
     HEdge h( this, Edge_ID( i+1, Edge_ID::BndID));
     Node v = h.destination_l();
     V2h_table::iterator it = _v2h_table.find( get_lid(v));
     if ( it == _v2h_table.end()) continue;
     V2h_table::iterator i0=_v2h_table.find(get_lid( h.origin_l()));
     // If the origin not incident with any, there is no counterpart.
     if ( i0==_v2h_table.end()) continue;
     // check whether the two vertices are overlapping.
     V2h::iterator j0=i0->second.begin(), j1=it->second.begin();
     while ( j0 != i0->second.end() && j1 != it->second.end()) {
       if ( j0->first == j1->first) {
         bool found=false;
         V2h::iterator k0, k1;
         for ( k0=j0; k0!=i0->second.end()&&k0->first==j0->first; ++k0) {
           if (found) continue;
           for ( k1=j1; k1!=it->second.end()&&k1->first==j1->first; ++k1) {
             if (found) continue;
             // Check whether it is an edge in that pane
             const RFC_Pane_overlay &p = _window->pane(k0->first);
             const B2v  &b2v = p._b2v_table.find(id())->second;
             pair<int,int> e( b2v[k0->second], b2v[k1->second]);
             RFC_assertion( e.first>0 && e.second>0);
             map< pair<int,int>, HEdge>::const_iterator
               b2e_it = p._bv2edges.find( e);
             if ( b2e_it != p._bv2edges.end()) {
               _cntrs_hedge[i] = b2e_it->second;
               found=true;
             }
             else if ( k0->first != id()) {
               swap( e.first, e.second);
               if (p._bv2edges.find( e) != p._bv2edges.end()) {
                 std::cerr << "ERROR: Inconsistency in window \""
                           << _window->name() << "\"!!!! \n\tPanes " << id()
                           << " and " << j0->first
                           << " have opposite orientation!" << std::endl
                           << "\tComputation can not continue. Aborting..."
                           << std::endl;
                 RFC_assertion( p._bv2edges.find( e) == p._bv2edges.end());
                 abort();
               }
             }
           }
         }
         if ( found) { j0 = k0; j1 = k1; }
         else { ++j0; ++j1; }
       }
       else
         if ( j0->first < j1->first) ++j0; else ++j1;
     }
   }
   // Fix physical border ones to have them point to themselves
   for ( int i=0; i<size_of_border_edges(); ++i) {
     HEdge h( this, Edge_ID( i+1, Edge_ID::BndID));
     if ( _cntrs_hedge[i].pane() == NULL) _cntrs_hedge[i] = h;
   }
   // Determine the primaries of the border vertices
   _primnodes.resize( size_of_border_edges());
   for ( int i=1; i<=size_of_border_edges(); ++i) {
     HEdge h( this, Edge_ID( i, Edge_ID::BndID));
     int vid = get_lid( h.destination_l());
     pair<Self*,int> t=_window->get_primary( this, vid);
     Node n(this, vid);
     _primnodes[ get_border_index( n.halfedge_l())] =
       t.first->get_node_from_id( t.second);
   }
 }
void RFC_Pane_overlay::evaluate_normals () protected
Definition at line 97 of file RFC_Window_overlay.C.
References _nrmls, HEdge::destination_l(), Overlay_primitives::get_face_normal(), Node::halfedge_l(), Node::is_isolated(), RFC_assertion, s, scheme, set_normal(), and RFC_Pane_base::size_of_nodes().
{
   _nrmls.resize( size_of_nodes(), Vector_3(0.,0.,0.));
   for ( int vid=1, s=size_of_nodes(); vid<=s; ++vid) {
     Node v( this, vid);
     if (v.is_isolated()) continue;
     Vector_3 d(0.,0.,0.);
     HEdge h = v.halfedge_l(), i = h;
     if ( h.destination_l() != v) continue;
     do {
       RFC_assertion( i.destination_l() == v);
       if ( !i.is_border_l())
         d += Overlay_primitives().get_face_normal( i, Point_2(0,0), scheme);
       if ( i.opposite_l().is_border_l()) break;
     } while ( (i = i.opposite_l().prev_l()) != h);
     // Note that the normal vector is not normalized.
     set_normal( vid, d);
   }
 }
const float& RFC_Pane_overlay::get_angle_defect (const Node & v) const inline protected
Definition at line 266 of file RFC_Window_overlay.h.
References _ad_0, and get_index().
   { return _ad_0[ get_index( v)]; }
float& RFC_Pane_overlay::get_angle_defect (const Node & v) inline protected
Definition at line 268 of file RFC_Window_overlay.h.
References _ad_0, and get_index().
   { return _ad_0[ get_index( v)]; }
int RFC_Pane_overlay::get_border_index (const HEdge & h) const inline protected
Definition at line 294 of file RFC_Window_overlay.h.
References HEdge::id().
Referenced by determine_counterparts(), get_primary(), and is_primary().
   { assert(h.id().is_border()); return h.id().eid()-1; }
INode* RFC_Pane_overlay::get_buffered_inode (const HEdge & h, int tag) const inline
Definition at line 183 of file RFC_Window_overlay.h.
References _e_marks, _e_node_buf, and get_index().
Referenced by Overlay::insert_node_in_green_edge().
{
     int i=get_index(h);
     if ( _e_marks[i] == tag) return _e_node_buf[i];
     else return NULL;
   }
const float& RFC_Pane_overlay::get_cos_edge_angle (const Node & v) const inline protected
Definition at line 273 of file RFC_Window_overlay.h.
References _ea_0, and get_index().
   { return _ea_0[ get_index( v)]; }
float& RFC_Pane_overlay::get_cos_edge_angle (const Node & v) inline protected
Definition at line 275 of file RFC_Window_overlay.h.
References _ea_0, and get_index().
   { return _ea_0[ get_index( v)]; }
float& RFC_Pane_overlay::get_cos_face_angle (const HEdge & h) inline protected
Definition at line 251 of file RFC_Window_overlay.h.
References _fd_1, get_index(), HEdge::id(), and min().
Referenced by RFC_Window_overlay::cos_face_angle().
   { Edge_ID opp=get_opposite_real_edge( h.id());
     int n1=get_index( h), n2=get_index(opp);
     return _fd_1[ std::min(n1,n2)];
   }
const float& RFC_Pane_overlay::get_cos_face_angle (const HEdge & h) const inline protected
Definition at line 256 of file RFC_Window_overlay.h.
References _fd_1, get_index(), HEdge::id(), and min().
   { Edge_ID opp=get_opposite_real_edge( h.id());
     int n1=get_index( h), n2=get_index(opp);
     return _fd_1[ std::min(n1,n2)];
   }
const HEdge& RFC_Pane_overlay::get_counterpart (Edge_ID eID) const inline
Definition at line 64 of file RFC_Window_overlay.h.
References _cntrs_hedge, and COM_assertion.
Referenced by get_counterpart(), and get_opposite_edge().
{
     COM_assertion( eID.is_border());
     return (HEdge&)_cntrs_hedge[ eID.eid()-1];
   }
HEdge RFC_Pane_overlay::get_counterpart (const HEdge & h) inline
Definition at line 137 of file RFC_Window_overlay.h.
References get_counterpart(), and HEdge::id().
{
     if ( !h.id().is_border()) return h;
     else return get_counterpart( h.id());
   }
int RFC_Pane_overlay::get_index (const Node & v) const inline
Definition at line 106 of file RFC_Window_overlay.h.
References Node::id().
Referenced by add_tangent(), RFC_Window_overlay::evaluate_normals(), get_angle_defect(), get_buffered_inode(), get_cos_edge_angle(), get_cos_face_angle(), get_inode(), get_inode_list(), get_normal(), get_point(), get_tangent(), Overlay::insert_node_in_blue_edge(), Overlay::intersect_blue_with_green(), Overlay::intersect_link(), is_feature_0(), is_feature_1(), is_on_feature(), mark(), marked(), Overlay::match_features_0(), RFC_Window_overlay::remove_feature_1(), reset_cos_edge_angle(), set_buffered_inode(), set_feature_0(), set_inode(), set_on_feature(), set_strong_edge(), unmark(), unset_feature_0(), unset_on_feature(), and unset_strong_edge().
 { return v.id()-1; }
int RFC_Pane_overlay::get_index (const HEdge & h) const inline
Definition at line 107 of file RFC_Window_overlay.h.
References get_index(), and HEdge::id().
Referenced by get_index().
 { return get_index( h.id()); }
int RFC_Pane_overlay::get_index (const Edge_ID & id) const inline
Definition at line 108 of file RFC_Window_overlay.h.
References RFC_Pane_base::size_of_faces().
{
     if (id.is_border()) return size_of_faces()*4+id.eid()-1;
     else return (id.eid()-1)*4+id.lid();
   }
int RFC_Pane_overlay::get_index (const Face & f) const inline
Definition at line 113 of file RFC_Window_overlay.h.
References Face::id().
 { return f.id()-1; }
INode* RFC_Pane_overlay::get_inode (const Node & v) const inline
Definition at line 174 of file RFC_Window_overlay.h.
References _v_nodes, get_index(), is_primary(), and RFC_assertion.
   { RFC_assertion( is_primary(v)); return _v_nodes[ get_index(v)]; }
INode_list& RFC_Pane_overlay::get_inode_list (const HEdge & h) inline
Definition at line 178 of file RFC_Window_overlay.h.
References _e_node_list, and get_index().
Referenced by HDS_accessor::get_inode_list().
   { return _e_node_list[ get_index(h)]; }
const INode_list& RFC_Pane_overlay::get_inode_list (const HEdge & h) const inline
Definition at line 180 of file RFC_Window_overlay.h.
References _e_node_list, and get_index().
   { return _e_node_list[ get_index(h)]; }
int RFC_Pane_overlay::get_lid (const Node & v) const inline
Definition at line 114 of file RFC_Window_overlay.h.
References Node::id().
Referenced by construct_bvpair2edge(), Overlay::convert_nat_coordinates(), determine_counterparts(), and Overlay::number_subfaces().
 { return v.id(); }
int RFC_Pane_overlay::get_lid (const Face & f) const inline
Definition at line 115 of file RFC_Window_overlay.h.
References Face::id().
 { return f.id(); }
HEdge RFC_Pane_overlay::get_next_edge (Edge_ID eID) inline
Definition at line 92 of file RFC_Window_overlay.h.
References get_opposite_edge(), HEdge, HEdge::id(), and HEdge::pane().
Referenced by HEdge::next_g().
{
     if ( !eID.is_border()) {
       Edge_ID nxt = get_next_real_edge( eID);
       return HEdge( this, nxt);
     }
     else { // the edge is on physical boundary.
       HEdge h = get_opposite_edge( eID);
       while ( !h.id().is_border())
         h = HEdge( h.pane(), h.pane()->get_prev_real_edge( h.id())).opposite_g();
       return h;
     }
   }
Node RFC_Pane_overlay::get_node_from_id (int i) inline
Definition at line 117 of file RFC_Window_overlay.h.
References Node, and RFC_assertion.
Referenced by get_normal().
   { RFC_assertion(i>0); return Node(this,i); }
Vector_3& RFC_Pane_overlay::get_normal (int v) inline
Definition at line 143 of file RFC_Window_overlay.h.
References _nrmls, and RFC_assertion.
Referenced by Overlay::get_green_parent(), HDS_accessor::get_normal(), get_normal(), Normal_set::operator[](), and Overlay::project_adjacent_green_vertices().
   { RFC_assertion(v>0); return _nrmls[v-1]; }
const Vector_3& RFC_Pane_overlay::get_normal (int v) const inline
Definition at line 145 of file RFC_Window_overlay.h.
References _nrmls, and RFC_assertion.
   { RFC_assertion(v>0); return _nrmls[v-1]; }
Vector_3& RFC_Pane_overlay::get_normal (const HEdge & h, const Node & v) inline
Definition at line 151 of file RFC_Window_overlay.h.
   { return const_cast<Vector_3&>
       (((const RFC_Pane_overlay*)this)->get_normal( h, v)); }
Vector_3& RFC_Pane_overlay::get_normal (const HEdge & h, int i) inline
Definition at line 159 of file RFC_Window_overlay.h.
References get_node_from_id(), and get_normal().
   { return get_normal( h, get_node_from_id(i)); }
const Vector_3& RFC_Pane_overlay::get_normal (const HEdge & h, int i) const inline
Definition at line 162 of file RFC_Window_overlay.h.
References get_node_from_id(), and get_normal().
   { return get_normal( h, const_cast<RFC_Pane_overlay*>(this)->get_node_from_id(i)); }
const Vector_3 & RFC_Pane_overlay::get_normal (HEdge h, const Node & v) const
Definition at line 240 of file RFC_Window_overlay.C.
References _f_n_index, _f_nrmls, _nrmls, HEdge::destination_l(), get_index(), HEdge::id(), HEdge::opposite_g(), HEdge::pane(), Node::pane(), HEdge::prev_l(), and RFC_assertion.
{
   RFC_assertion( h.pane() == this && v.pane()==this);
   if ( v != h.destination_l()) {
     h = h.prev_l();
     RFC_assertion( v == h.destination_l());
   }
   if ( h.id().is_border())
     h = h.opposite_g().prev_l();
   int j=_f_n_index[get_index( h)];
   if ( j < 0)
     return _nrmls[ get_index(v)];
   else
     return _f_nrmls[j];
 }
HEdge RFC_Pane_overlay::get_opposite_edge (Edge_ID eID) const inline
Definition at line 70 of file RFC_Window_overlay.h.
References get_counterpart(), and HEdge.
Referenced by get_next_edge(), get_prev_edge(), and HEdge::opposite_g().
{
     Edge_ID opp=get_opposite_real_edge( eID);
     if (  opp.is_border()) return get_counterpart(opp);
     return HEdge( const_cast<RFC_Pane_overlay*>(this), opp);
   }
const Point_3& RFC_Pane_overlay::get_point (int id) const inline
Definition at line 131 of file RFC_Window_overlay.h.
References RFC_Pane_base::get_point().
Referenced by Overlay::get_green_parent(), Point_set::operator[](), and Overlay::overlay_init().
   { return Base::get_point(id); }
const Point_3& RFC_Pane_overlay::get_point (const Node & v) const inline
Definition at line 134 of file RFC_Window_overlay.h.
References get_index(), and RFC_Pane_base::get_point().
   { return Base::get_point( get_index(v),0); }
HEdge RFC_Pane_overlay::get_prev_edge (Edge_ID eID) inline
Definition at line 78 of file RFC_Window_overlay.h.
References get_opposite_edge(), HEdge, HEdge::id(), and HEdge::pane().
Referenced by HEdge::prev_g().
{
     if ( !eID.is_border()) {
       Edge_ID prv = get_prev_real_edge( eID);
       return HEdge( this, prv);
     }
     else { // the edge is on physical boundary.
       HEdge h = get_opposite_edge( eID);
       while ( !h.id().is_border())
         h = HEdge( h.pane(), h.pane()->get_next_real_edge( h.id())).opposite_g();
       return h;
     }
   }
const Node RFC_Pane_overlay::get_primary (const Node & v) const inline
Definition at line 126 of file RFC_Window_overlay.h.
References _primnodes, get_border_index(), Node::halfedge_l(), and Node::is_border_l().
Referenced by HEdge::destination_g(), and HEdge::origin_g().
{
     if ( !v.is_border_l()) return v;
     else return _primnodes[get_border_index(v.halfedge_l())];
   }
Vector_3& RFC_Pane_overlay::get_tangent (const HEdge & h, const Node & v) inline
Definition at line 155 of file RFC_Window_overlay.h.
Referenced by get_tangent().
   { return const_cast<Vector_3&>
       (((const RFC_Pane_overlay*)this)->get_tangent( h, v)); }
const Vector_3 & RFC_Pane_overlay::get_tangent (HEdge h, const Node & v) const
Definition at line 260 of file RFC_Window_overlay.C.
References _f_t_index, _f_tngts, HEdge::destination_l(), get_index(), get_tangent(), is_feature_1(), HEdge::opposite_g(), HEdge::pane(), and RFC_assertion.
{
   if ( v != h.destination_l()) {
     h = h.opposite_g();
     return h.pane()->get_tangent( h, h.destination_l());
   }
   RFC_assertion( is_feature_1(h));
   int j=_f_t_index[get_index( h)];
   RFC_assertion( j >= 0 && int(_f_tngts.size())>j);
   return _f_tngts[j];
 }
void RFC_Pane_overlay::init_angle_defect () inline protected
Definition at line 270 of file RFC_Window_overlay.h.
References _ad_0, HUGE_VALF, and RFC_Pane_base::size_of_nodes().
Referenced by RFC_Window_overlay::detect_features().
   { _ad_0.clear(); _ad_0.resize( size_of_nodes(), HUGE_VALF); }
void RFC_Pane_overlay::init_edge_angle () inline protected
Definition at line 279 of file RFC_Window_overlay.h.
References _ea_0, HUGE_VALF, and RFC_Pane_base::size_of_nodes().
Referenced by RFC_Window_overlay::detect_features().
   { _ea_0.clear(); _ea_0.resize( size_of_nodes(), HUGE_VALF); }
void RFC_Pane_overlay::init_face_angle () inline protected
Definition at line 262 of file RFC_Window_overlay.h.
References _fd_1, HUGE_VALF, and RFC_Pane_base::size_of_faces().
Referenced by RFC_Window_overlay::detect_features().
   { _fd_1.clear(); int n = 4*size_of_faces() + size_of_border_edges();
     _fd_1.resize( n, HUGE_VALF); }
void RFC_Pane_overlay::insert_subface (int idx, int plid, const int * lids, const ParentEdge_ID * eids, const Point_2 * nc, int rp_id, int cnt, const int * rids)
Parameters
idx the index of the subface (i.e., starting from 0).
plid the local id of the parent face of the subface.
h an halfedge of the its parent face in the pane.
lids the local ids of the nodes of the subface.
nc the local coordinates of the nodes of the subface within its parent face.
rp_id the pane id of the correponding subface in the other window.
cnt the local id of the subface's counterpart in the other window.
rids the local ids of the nodes of the correponding subface in the other window.
Definition at line 470 of file RFC_Window_overlay.C.
References RFC_Pane_base::_subface_counterparts, RFC_Pane_base::_subface_parents, RFC_Pane_base::_subfaces, RFC_Pane_base::_subnode_counterparts, RFC_Pane_base::_subnode_nat_coors, RFC_Pane_base::_subnode_parents, and RFC_assertion.
Referenced by Overlay::number_subfaces().
{
   RFC_assertion( idx>=0 && idx<int(_subface_parents.size()) && cnt>=1);
   for ( int i=0; i<3; ++i) {
     _subfaces[idx][i] = lids[i];
     _subnode_parents[ lids[i]-1] = eids[i];
     _subnode_nat_coors[ lids[i]-1] = Point_2S(nc[i][0],nc[i][1]);
     _subnode_counterparts[ lids[i]-1] = Node_ID( rp_id, rids[i]);
   }
   _subface_parents[idx] = plid;
   _subface_counterparts[idx] = Face_ID( rp_id, cnt);
 }
bool RFC_Pane_overlay::is_feature_0 (const Node & v) const inline
Definition at line 200 of file RFC_Window_overlay.h.
References _is_f_0, get_index(), and Node::is_primary().
   { assert(v.is_primary()); return _is_f_0[ get_index(v)]; }
bool RFC_Pane_overlay::is_feature_1 (const HEdge & h) const inline
Definition at line 202 of file RFC_Window_overlay.h.
References _is_f_1, and get_index().
Referenced by get_tangent(), Overlay::intersect_blue_with_green(), HDS_accessor::is_feature_1(), RFC_Window_overlay::is_feature_1(), Overlay_primitives::snap_blue_ridge_edge(), and Overlay_primitives::snap_blue_ridge_vertex().
 { return _is_f_1[get_index(h)]; }
bool RFC_Pane_overlay::is_on_feature (const Node & v) const inline
Definition at line 198 of file RFC_Window_overlay.h.
References _is_on_f, get_index(), and Node::is_primary().
Referenced by RFC_Window_overlay::get_an_unmarked_halfedge().
   { assert(v.is_primary()); return _is_on_f[ get_index(v)]; }
bool RFC_Pane_overlay::is_primary (const Node & v) const inline
Definition at line 122 of file RFC_Window_overlay.h.
References _primnodes, get_border_index(), Node::halfedge_l(), and Node::is_border_l().
Referenced by get_inode(), and set_inode().
   { return !v.is_border_l() ||
       _primnodes[get_border_index(v.halfedge_l())]==v; }
void RFC_Pane_overlay::mark (const HEdge & h) inline
Definition at line 194 of file RFC_Window_overlay.h.
References _e_marks, and get_index().
Referenced by HDS_accessor::mark().
 { _e_marks[get_index(h)] = true; }
bool RFC_Pane_overlay::marked (const HEdge & h) const inline
Definition at line 196 of file RFC_Window_overlay.h.
References _e_marks, and get_index().
Referenced by RFC_Window_overlay::get_an_unmarked_halfedge(), and HDS_accessor::marked().
 { return _e_marks[get_index(h)]; }
void RFC_Pane_overlay::reset_cos_edge_angle (const Node & v) inline protected
Definition at line 277 of file RFC_Window_overlay.h.
References _ea_0, get_index(), and HUGE_VALF.
   { _ea_0[ get_index( v)] = HUGE_VALF; }
void RFC_Pane_overlay::set_buffered_inode (const HEdge & h, int tag, INode * inode) inline
Definition at line 188 of file RFC_Window_overlay.h.
References _e_marks, _e_node_buf, and get_index().
Referenced by Overlay::insert_node_in_green_edge().
{
     int i=get_index(h);
     _e_marks[i] = tag;
     _e_node_buf[i] = inode;
   }
void RFC_Pane_overlay::set_feature_0 (const Node & v) inline protected
Definition at line 284 of file RFC_Window_overlay.h.
References _is_f_0, and get_index().
 { _is_f_0[ get_index(v)] = true; }
void RFC_Pane_overlay::set_inode (const Node & v, INode * i) inline
Definition at line 176 of file RFC_Window_overlay.h.
References _v_nodes, get_index(), is_primary(), and RFC_assertion.
   { RFC_assertion( is_primary(v)); _v_nodes[ get_index(v)] = i; }
void RFC_Pane_overlay::set_normal (int v, const Vector_3 & vec) inline
Definition at line 147 of file RFC_Window_overlay.h.
References _nrmls, and RFC_assertion.
Referenced by evaluate_normals().
   { RFC_assertion(v>0); _nrmls[v-1] = vec; }
void RFC_Pane_overlay::set_on_feature (const Node & v) inline protected
Definition at line 286 of file RFC_Window_overlay.h.
References _is_on_f, and get_index().
 { _is_on_f[ get_index(v)] = true; }
void RFC_Pane_overlay::set_strong_edge (const HEdge & h) inline protected
Definition at line 282 of file RFC_Window_overlay.h.
References _is_f_1, and get_index().
Referenced by RFC_Window_overlay::detect_features().
 { _is_f_1[ get_index(h)] = true; }
const int& RFC_Pane_overlay::size_of_subfaces () const inline
Definition at line 206 of file RFC_Window_overlay.h.
References _size_of_subfaces.
 { return _size_of_subfaces; }
int& RFC_Pane_overlay::size_of_subfaces () inline
Definition at line 207 of file RFC_Window_overlay.h.
References _size_of_subfaces.
 { return _size_of_subfaces; }
void RFC_Pane_overlay::unmark (const HEdge & h) inline
Definition at line 195 of file RFC_Window_overlay.h.
References _e_marks, and get_index().
Referenced by HDS_accessor::unmark().
 { _e_marks[get_index(h)] = false; }
void RFC_Pane_overlay::unmark_alledges () protected
void RFC_Pane_overlay::unset_feature_0 (const Node & v) inline protected
Definition at line 285 of file RFC_Window_overlay.h.
References _is_f_0, and get_index().
 { _is_f_0[ get_index(v)] = false; }
void RFC_Pane_overlay::unset_on_feature (const Node & v) inline protected
Definition at line 287 of file RFC_Window_overlay.h.
References _is_on_f, and get_index().
 { _is_on_f[ get_index(v)] = false; }
void RFC_Pane_overlay::unset_strong_edge (const HEdge & h) inline protected
Definition at line 283 of file RFC_Window_overlay.h.
References _is_f_1, and get_index().
Referenced by RFC_Window_overlay::check_false_strong_1(), RFC_Window_overlay::subdiv_feature_curve(), and RFC_Window_overlay::unset_strong_edge().
 { _is_f_1[ get_index(h)] = false; }
RFC_Window_overlay* RFC_Pane_overlay::window () inline
Definition at line 61 of file RFC_Window_overlay.h.
References _window.
 { return _window; }
const RFC_Window_overlay* RFC_Pane_overlay::window () const inline
Definition at line 62 of file RFC_Window_overlay.h.
References _window.
 { return _window; }
Friends And Related Function Documentation
friend class Face friend
Definition at line 51 of file RFC_Window_overlay.h.
friend class HEdge friend
Definition at line 50 of file RFC_Window_overlay.h.
Referenced by construct_bvpair2edge(), get_next_edge(), get_opposite_edge(), and get_prev_edge().
friend class Node friend
Definition at line 49 of file RFC_Window_overlay.h.
Referenced by get_node_from_id().
friend class RFC_Window_overlay friend
Definition at line 48 of file RFC_Window_overlay.h.
Member Data Documentation
std::vector< float> RFC_Pane_overlay::_ad_0 protected
Definition at line 319 of file RFC_Window_overlay.h.
Referenced by delete_overlay_data(), RFC_Window_overlay::detect_features(), get_angle_defect(), and init_angle_defect().
std::map< std::pair<int,int>, HEdge> RFC_Pane_overlay::_bv2edges protected
Definition at line 301 of file RFC_Window_overlay.h.
Referenced by construct_bvpair2edge(), and determine_counterparts().
std::vector<HEdge> RFC_Pane_overlay::_cntrs_hedge protected
Definition at line 302 of file RFC_Window_overlay.h.
Referenced by delete_overlay_data(), determine_counterparts(), and get_counterpart().
std::vector<int> RFC_Pane_overlay::_e_marks protected
Definition at line 331 of file RFC_Window_overlay.h.
Referenced by create_overlay_data(), delete_overlay_data(), get_buffered_inode(), mark(), marked(), set_buffered_inode(), unmark(), and RFC_Window_overlay::unmark_alledges().
std::vector<INode*> RFC_Pane_overlay::_e_node_buf protected
Definition at line 329 of file RFC_Window_overlay.h.
Referenced by create_overlay_data(), delete_overlay_data(), get_buffered_inode(), and set_buffered_inode().
std::vector<INode_list> RFC_Pane_overlay::_e_node_list protected
Definition at line 330 of file RFC_Window_overlay.h.
Referenced by create_overlay_data(), delete_overlay_data(), and get_inode_list().
std::vector< float> RFC_Pane_overlay::_ea_0 protected
Definition at line 320 of file RFC_Window_overlay.h.
Referenced by delete_overlay_data(), RFC_Window_overlay::detect_features(), get_cos_edge_angle(), init_edge_angle(), and reset_cos_edge_angle().
std::vector< int> RFC_Pane_overlay::_f_n_index protected
Definition at line 312 of file RFC_Window_overlay.h.
Referenced by delete_overlay_data(), RFC_Window_overlay::evaluate_normals(), get_normal(), and RFC_Window_overlay::remove_feature_1().
std::vector<Vector_3> RFC_Pane_overlay::_f_nrmls protected
Definition at line 308 of file RFC_Window_overlay.h.
Referenced by delete_overlay_data(), RFC_Window_overlay::evaluate_normals(), and get_normal().
std::vector< int> RFC_Pane_overlay::_f_t_index protected
Definition at line 316 of file RFC_Window_overlay.h.
Referenced by add_tangent(), delete_overlay_data(), RFC_Window_overlay::evaluate_normals(), and get_tangent().
std::vector< Vector_3> RFC_Pane_overlay::_f_tngts protected
Definition at line 315 of file RFC_Window_overlay.h.
Referenced by add_tangent(), delete_overlay_data(), RFC_Window_overlay::evaluate_normals(), and get_tangent().
std::vector< float> RFC_Pane_overlay::_fd_1 protected
Definition at line 321 of file RFC_Window_overlay.h.
Referenced by delete_overlay_data(), RFC_Window_overlay::detect_features(), get_cos_face_angle(), and init_face_angle().
std::vector< bool> RFC_Pane_overlay::_is_f_0 protected
Definition at line 323 of file RFC_Window_overlay.h.
Referenced by RFC_Window_overlay::detect_features(), is_feature_0(), set_feature_0(), and unset_feature_0().
std::vector< bool> RFC_Pane_overlay::_is_f_1 protected
Definition at line 325 of file RFC_Window_overlay.h.
Referenced by RFC_Window_overlay::detect_features(), is_feature_1(), set_strong_edge(), and unset_strong_edge().
std::vector< bool> RFC_Pane_overlay::_is_on_f protected
Definition at line 324 of file RFC_Window_overlay.h.
Referenced by RFC_Window_overlay::detect_features(), is_on_feature(), set_on_feature(), and unset_on_feature().
std::vector<Vector_3> RFC_Pane_overlay::_nrmls protected
Definition at line 306 of file RFC_Window_overlay.h.
Referenced by evaluate_normals(), RFC_Window_overlay::evaluate_normals(), get_normal(), RFC_Window_overlay::reduce_normals_to_all(), and set_normal().
std::vector<Node> RFC_Pane_overlay::_primnodes protected
Definition at line 303 of file RFC_Window_overlay.h.
Referenced by delete_overlay_data(), determine_counterparts(), get_primary(), and is_primary().
int RFC_Pane_overlay::_size_of_subfaces protected
Definition at line 333 of file RFC_Window_overlay.h.
Referenced by size_of_subfaces().
std::vector< const INode*> RFC_Pane_overlay::_subnodes protected
Definition at line 334 of file RFC_Window_overlay.h.
std::vector<INode*> RFC_Pane_overlay::_v_nodes protected
Definition at line 328 of file RFC_Window_overlay.h.
Referenced by create_overlay_data(), delete_overlay_data(), get_inode(), and set_inode().
RFC_Window_overlay* RFC_Pane_overlay::_window protected
Definition at line 299 of file RFC_Window_overlay.h.
Referenced by determine_counterparts(), and window().
The documentation for this class was generated from the following files:
RFC_Window_overlay.h
RFC_Window_overlay.C