IMPACT: GetDeformedMesh Class Reference
GetDeformedMesh Class Reference
Detailed Description
Definition at line 78 of file transfer_actions.h.
#include <transfer_actions.h>
Public Member Functions
GetDeformedMesh (FluidAgent *fag, SolidAgent *sag, const std::string s_x, const std::string uhat, const std::string s_y)
void init (double t)
void run (double t, double dt, double alpha)
Public Member Functions inherited from InterMeshTransfer
InterMeshTransfer (FluidAgent *fag, SolidAgent *sag, char *name=NULL)
Public Member Functions inherited from Action
Action (void *p=0, const char *name=NULL)
Action (int n, const char **at, int *i=NULL, void *p=0, const char *name=NULL)
Action (int n, const std::string at[], int *i=NULL, void *p=0, const char *name=NULL)
virtual ~Action ()
virtual void declare (Scheduler &)
virtual void finalize ()
virtual const char * name ()
void set_name (const char *name)
virtual void print (FILE *f)
virtual void print_toposort (FILE *f)
virtual void schedule ()
Private Attributes
std::string s_x_str
std::string s_uhat_str
std::string s_y_str
int s_x_hdl
int s_uhat_hdl
int s_y_hdl
Additional Inherited Members
Protected Types inherited from Action
enum { IN =1, OUT =2, INOUT =3 }
Protected Member Functions inherited from InterMeshTransfer
void load_rocface (const RocmanControl_parameters *param)
Protected Member Functions inherited from Action
int get_dataitem_handle (int i)
int get_dataitem_handle_const (int i)
int get_dataitem_handle (const std::string str)
void set_attr (int n, const std::string at[], int *id=NULL)
void set_attr (int n, const char *at[], int *id=NULL)
void set_io (int n, const int *io)
void set_io (const char *io)
int get_io (int i)
Protected Attributes inherited from InterMeshTransfer
FluidAgent * fagent
SolidAgent * sagent
Protected Attributes inherited from Action
const char * action_name
char ** attr
int * idx
int count
void * usr_ptr
std::vector< int > inout
Constructor & Destructor Documentation
GetDeformedMesh::GetDeformedMesh (FluidAgent * fag, SolidAgent * sag, const std::string s_x, const std::string uhat, const std::string s_y) explicit
Definition at line 446 of file transfer_actions.C.
References Action::IN, Action::OUT, Action::set_attr(), and Action::set_io().
                                                                                                                                   :
     InterMeshTransfer(fag, sag, "GetDeformedMesh"),
     s_x_str(s_x), s_uhat_str(s_uhat), s_y_str(s_y)
 {
   int io[] = {IN, IN, OUT};
   set_io( 3, io);
   std::string.data[4];
  .data[0] = s_x;
  .data[1] = s_uhat;
  .data[2] = s_y;
   set_attr(3,.data);
     // register dataitems
 /*
   std::string::size_type pos = s_x_str.find( ".");
   COM_assertion_msg(pos!=std::string::npos, "GetDeformedMesh::create_dataitem failed!");
   std::string s = s_x_str.substr( 0, pos);
   std::string x = s_x_str.substr( pos, s_x_str.size());
   sagent->register_use_dataitem( s, x, sagent->solidBufBase, ".nc");
   pos = s_y_str.find( ".");
   COM_assertion_msg(pos!=std::string::npos, "GetDeformedMesh::create_dataitem failed!");
   s = s_y_str.substr( 0, pos);
   std::string y = s_y_str.substr( pos, s_y_str.size());
   sagent->register_clone_dataitem( 0, s, y, sagent->get_surface_window(), ".nc");
 */
 }
Member Function Documentation
void GetDeformedMesh::init (double t) virtual
Reimplemented from Action.
Definition at line 475 of file transfer_actions.C.
References RocBlas::add, COM_call_function(), Action::get_dataitem_handle(), s_uhat_hdl, s_x_hdl, and s_y_hdl.
{
   s_x_hdl = get_dataitem_handle(0);
   s_uhat_hdl = get_dataitem_handle(1);
   s_y_hdl = get_dataitem_handle(2);
 #if 0
   // POST_INIT_SOLID
   COM_call_function( RocBlas::add, &s_x_hdl, &s_uhat_hdl, &s_y_hdl);
     // initial_start  ?????
   if (t == 0.0) {
 //    double alpha = 0.0;
 //     ????????????????? strange bug called in bcinitscheduler::init()
 //    sagent->obtain_bc(&alpha);
   }
 #endif
 }
void GetDeformedMesh::run (double t, double dt, double alpha) virtual
Reimplemented from Action.
Definition at line 493 of file transfer_actions.C.
References RocBlas::add, COM_call_function(), MAN_DEBUG, s_uhat_hdl, s_x_hdl, and s_y_hdl.
{
   MAN_DEBUG(2, ("Rocman: calling GetDeformedMesh::run() with t:%e dt:%e alpha:%e.\n", t, dt, alpha));
   COM_call_function( RocBlas::add, &s_x_hdl, &s_uhat_hdl, &s_y_hdl);
 }
Member Data Documentation
int GetDeformedMesh::s_uhat_hdl private
Definition at line 85 of file transfer_actions.h.
Referenced by init(), and run().
std::string GetDeformedMesh::s_uhat_str private
Definition at line 84 of file transfer_actions.h.
int GetDeformedMesh::s_x_hdl private
Definition at line 85 of file transfer_actions.h.
Referenced by init(), and run().
std::string GetDeformedMesh::s_x_str private
Definition at line 84 of file transfer_actions.h.
int GetDeformedMesh::s_y_hdl private
Definition at line 85 of file transfer_actions.h.
Referenced by init(), and run().
std::string GetDeformedMesh::s_y_str private
Definition at line 84 of file transfer_actions.h.
The documentation for this class was generated from the following files:
transfer_actions.h
transfer_actions.C