IMPACT: Element_node_enumerator_uns Class Reference
Element_node_enumerator_uns Class Reference
Optimized version for unstructured meshes.
Detailed Description
Definition at line 145 of file Element_accessors.hpp.
#include <Element_accessors.hpp>
Public Member Functions
Element_node_enumerator_uns ()
Element_node_enumerator_uns (const Pane *pane, int i, const Connectivity *conn=NULL)
void next ()
int operator[] (int i) const
int size_of_nodes () const
Public Member Functions inherited from Element_node_enumerator
Element_node_enumerator ()
Element_node_enumerator (const Pane *pane, int i, const Connectivity *conn=NULL)
Constructor for an element in a structured or an unstructured mesh.
Element_node_enumerator (const Pane *pane, const std::pair< int, int > &id)
A constructor for an element in a structured mesh.
void next ()
Go to the next element within the connectivity tables of a pane.
int type () const
Obtain the type of the element.
int is_quadratic () const
Check whether the element is quadratic.
int size_of_nodes () const
Number of nodes per element.
int size_of_corners () const
Number of corners per element.
void get_nodes (std::vector< int > &nodes)
Get a vector of all of the nodes in the element.
int size_of_edges () const
Number of edges per element.
int size_of_faces () const
Number of faces per element.
int dimension () const
Get the dimension of the base pane.
int id () const
Get the local id of the element within the pane.
int vertex (int lvid, bool level=false) const
Get the vertex index of an vertex within the element.
int operator[] (int i) const
Obtain the pane-scope node ID from its element-scope index.
const Pane * pane () const
Additional Inherited Members
Protected Attributes inherited from Element_node_enumerator
const Pane * _pane
const Connectivity * _conn
union {
const int * _start
int _base
};
int _res
Constructor & Destructor Documentation
Element_node_enumerator_uns::Element_node_enumerator_uns () inline
Definition at line 147 of file Element_accessors.hpp.
 {}
Element_node_enumerator_uns::Element_node_enumerator_uns (const Pane * pane, int i, const Connectivity * conn = NULL) inline
Definition at line 148 of file Element_accessors.hpp.
     : Element_node_enumerator( pane, i, conn) {}
Member Function Documentation
void Element_node_enumerator_uns::next () inline
Definition at line 152 of file Element_accessors.hpp.
References Element_node_enumerator::_conn, Element_node_enumerator::_pane, Element_node_enumerator::_res, Element_node_enumerator::_start, Pane::connectivity(), Connectivity::index_offset(), Connectivity::pointer(), Connectivity::size_of_elements(), and Connectivity::size_of_nodes_pe().
Referenced by Pane_dual_connectivity::construct_connectivity_unstr(), and Pane_boundary::determine_isolated_nodes().
               {
     if ( --_res==0) {
       _conn = _pane->connectivity( _conn->index_offset()+1+
                                    _conn->size_of_elements());
       if ( _conn) {
         _start = _conn->pointer();
         _res = _conn->size_of_elements();
       }
       else {
         _start = NULL;
         _res = -1;
       }
     }
     else
       _start += _conn->size_of_nodes_pe();
   }
int Element_node_enumerator_uns::operator[] (int i) const inline
Definition at line 169 of file Element_accessors.hpp.
References Element_node_enumerator::_start.
 { return _start[i]; }
int Element_node_enumerator_uns::size_of_nodes () const inline
Definition at line 170 of file Element_accessors.hpp.
References Element_node_enumerator::_conn, and Connectivity::size_of_nodes_pe().
Referenced by Pane_dual_connectivity::construct_connectivity_unstr(), and Pane_boundary::determine_isolated_nodes().
 { return _conn->size_of_nodes_pe();  }
The documentation for this class was generated from the following file:
Element_accessors.hpp