IMPACT: COM::TestComLine Class Reference
COM::TestComLine Class Reference
ComLineObject for COM testing command-line interface.
Detailed Description
Definition at line 16 of file TestCOM.H.
#include <TestCOM.H>
Public Member Functions
TestComLine ()
TestComLine (const char *args[])
void Initialize ()
virtual function for program specific Initialization.
Public Member Functions inherited from IRAD::Util::ComLineObject
ComLineObject ()
Default constructor.
ComLineObject (const char *args[])
Constructor.
ComLineObject (ComLineObject &incom)
Copy constructor.
void Copy (ComLineObject &incom)
Copy method.
int ProcessCommandLine (const char *args[])
One fell swoop processing of command line.
std::string GetRawComLine () const
Raw Command Line Access.
void SetRawComLine (const std::string &incl)
Raw Command Line Access.
int ProcessOptions ()
Processes all command line tokens.
void Record (const char *args[])
Minimal recording of command line.
void AddOption (char s, const std::string &l, int=0)
User interface to describe simple option.
void AddOption (char s, const std::string &l, int, const std::string argname)
User interface to describe option with argument.
void AddArgument (const std::string &a, int reqd=0)
User interface to describe an application argument.
void AddArgHelp (const std::string &a, const std::string &help)
Specify the usage info for application argument.
void SetArgName (const std::string opstr, const std::string argname)
Specify name of an option argument.
void SetArgName (char s, const std::string &argname)
Specify name of an option argument.
void AddHelp (char s, const std::string &help)
Specify usage for an option.
void AddHelp (const std::string &l, const std::string &help)
Specify usage for an option.
std::string GetOpStringByType (int mintype, int maxtype)
Obtains option strings by type.
std::string GetHelp (char s)
Obtain the usage string for an option.
std::string GetHelp (const std::string &l)
Obtain the usage string for an option.
char GetShort (const std::string &l)
Obtain the short one char option from the long word version.
std::string GetLong (const char &s)
Obtain the long word option from the short char version.
std::string ShortUsage ()
Generate short usage string.
std::string LongUsage ()
Generate long usage string.
std::string GetOption (const char &s)
Get the value of an option.
std::string GetOption (const std::string &l)
Get the value of an option.
std::string ErrorReport ()
Error reporting.
std::string ProgramName () const
Program name access.
std::vector< std::string > GetArgs () const
Argument access.
void SetDescription (const std::string &desc)
Set description string.
void SetNotes (const std::string &notes)
Set notes string.
void WriteRC (std::ostream &Ostr) const
Write an RC string that can be used for config.
void ReadRC (const std::string &RCString)
Read a config from RC string.
template<typename NumType >
void ProcessRange (NumType &t1, NumType &t2, const std::string stinter)
Process a range in the format "t1:t2".
template<typename NumType >
void ResolveOption (NumType &t2, const std::string stinter)
Resolve an option (i.e.
virtual ~ComLineObject ()
Additional Inherited Members
Public Attributes inherited from std::vector< T >
T elements
STL member.
Protected Attributes inherited from IRAD::Util::ComLineObject
std::string _description
application description.
std::string _notes
Notes to be displayed at the end of LongUsage().
std::string _program_name
the name of the program
std::string _line
unformatted command line
std::vector< std::string > _error_messages
stores error messages
std::vector< std::string > _nonops
stores non-option arguments
std::map< char, std::string > _options
stores the value of each option
std::map< char, std::string > _help
stores the help string for each op
std::map< char, std::string > _argname
stores a name for arguments
std::map< char, int > _type
stores the type of option
std::vector< std::pair
< std::string, int > > _args
application arguments;
std::map< std::string,
std::string > _arghelp
help string for args
std::vector< std::string > _toks
commandline tokens
Constructor & Destructor Documentation
COM::TestComLine::TestComLine () inline
Definition at line 19 of file TestCOM.H.
       : IRAD::Util::ComLineObject()
     {};
COM::TestComLine::TestComLine (const char * args[]) inline
Definition at line 22 of file TestCOM.H.
       : IRAD::Util::ComLineObject(args)
     {};
Member Function Documentation
void COM::TestComLine::Initialize (void) inline virtual
Reimplemented from IRAD::Util::ComLineObject.
Definition at line 25 of file TestCOM.H.
References IRAD::Util::ComLineObject::_description, IRAD::Util::ComLineObject::AddHelp(), IRAD::Util::ComLineObject::AddOption(), and SolverUtils::Ostr.
Referenced by COM::ParallelTest(), and COM::Test().
                      {
       AddOption('h',"help");
       AddHelp("help","Print out long version of help and exit.");
       AddOption('v',"verblevel",1,"level");
       AddHelp("verblevel","Set the verbosity level. (default = 0)");
       AddOption('o',"output",2,"filename");
       AddHelp("output","Set the output file to <filename>. (default = stdout)");
       AddOption('l',"list",2,"filename");
       std::ostringstream Ostr;
       Ostr << "Set the list file name to <filename>. (no default). "
            << "The list file should be a text file with one test name per line.";
       AddHelp("list",Ostr.str());
       AddOption('n',"name",2,"TestName");
       AddHelp("name","Run test by name. (no default)");
       Ostr.str("");
       Ostr << "Command-line interface for the test of the IMPACT.";
       _description.assign(Ostr.str());
     };
The documentation for this class was generated from the following file:
TestCOM.H