IMPACT: RFC_Pane_transfer Class Reference
RFC_Pane_transfer Class Reference
Detailed Description
Definition at line 35 of file RFC_Window_transfer.h.
#include <RFC_Window_transfer.h>
Public Types
typedef RFC_Pane_transfer Self
typedef RFC_Pane_base Base
Public Types inherited from RFC_Pane_base
typedef RFC_Pane_base Self
typedef COM::Pane Base
typedef COM::DataItem DataItem
typedef Base::Size Size
typedef RFC::Real Real
typedef std::pair< int, int > V2b
Pane id and local boundary id.
typedef std::map< int, V2b > V2b_table
From node id to its corresponding map.
typedef std::vector< int > B2v
From local boundary ids to node ids.
typedef std::map< int, B2v > B2v_table
From pane id to its corresponding mapping.
Public Member Functions
RFC_Pane_transfer (COM::Pane *b, int c)
virtual ~RFC_Pane_transfer ()
RFC_Window_transfer * window ()
const RFC_Window_transfer * window () const
Real * pointer (int i)
const Real * pointer (int i) const
const Real * coordinates () const
bool need_recv (int i) const
Real * get_emm (int f)
const Real * get_emm (int f) const
bool is_master () const
Public Member Functions inherited from RFC_Pane_base
RFC_Pane_base (Base *b, int color)
A constructor.
void init ()
virtual ~RFC_Pane_base ()
The default destructor.
Base * base ()
The id of its base COM::Pane object.
const Base * base () const
int id () const
bool is_master () const
Is this pane a master copy?
bool is_replicate () const
Is this pane not a master copy?
bool is_quadratic () const
Does this pane contain quadratic elements?
bool is_border_node (int i) const
Is a give node on the boundary of the pane?
bool is_isolated_node (int i) const
Is a give node an isolated node not belong to any element?
bool coincident (int i, int j) const
Report whether the two given nodes are coincident.
int size_of_nodes () const
The total number of nodes in the pane.
int size_of_faces () const
The total number of faces in the pane.
int size_of_isolated_nodes () const
int size_of_border_nodes () const
ParentEdge_ID get_edge_id (const int face_lid, const int vertex_lid) const
Get the edge id within a given face.
int size_of_subnodes () const
The total number of nodes in the subdivision of the pane.
int size_of_subfaces () const
The total number of faces in the subdivision of the pane.
Real * pointer (int i)
Get the address of a given dataitem with id i.
const Real * pointer (int i) const
bool is_primary_node (const int vid) const
Is the node with given local id a primary one?
int size_of_primary_nodes () const
Get total number of primary nodes contained in the pane.
const Point_3 & get_point (int id) const
Get the physical coordinates of the node with given local id.
const Point_3 & get_point (int id, int) const
const Real * coordinates () const
Point_3 get_point_of_subnode (int id) const
Bbox_3 get_bounding_box () const
Get the bounding box of the pane.
int color () const
The color of the parent window (BLUE or GREEN).
int parent_type_of_subnode (int) const
Determine the parent type of a subnode of given tyep.
int get_parent_node (int) const
Get the local parent node id of a given subnode.
int get_parent_face (int id) const
Get the local parent face id of a given subface.
template<class Point >
void normalize_nat_coor (int idx, int e, Point &nc) const
void get_host_element_of_subnode (int i, Element_node_enumerator &ene, Point_2 &nc) const
void get_host_element_of_subface (int i, Element_node_enumerator &ene) const
void get_nat_coor_in_element (const int eid, const int lid, Point_2 &nc) const
Take a subface id and a local subnode id, return the natual coordinates of the subnode within the parent element.
void get_nat_coor_in_element (const int sn_id, Element_node_enumerator &ene, Point_2 &nc) const
Take a subnode id and an element, return the natrual coordinates within the element.
std::pair< const
COM::Connectivity *, int > get_element (int face_id) const
Get the connectivity object and the id within the connectivity object for a given element.
const Node_ID & get_subnode_counterpart (int i) const
const Face_ID & get_subface_counterpart (int i) const
int get_lvid (const Element_node_enumerator &ene, const int v) const
Private Attributes
RFC_Window_transfer * _window
std::vector< std::vector< Real > > _buffer
std::vector< int > _emm_offset
std::vector< Real > _emm_buffer
int _data_buf_id
std::vector< Real > _coor_buf
std::vector< Real > _data_buf
std::vector< MPI_Request > _msg_requests
int * _to_recv
std::vector< int > _recv_faces
std::vector< int > _recv_nodes
std::map< int, std::vector< int > > _send_faces
std::map< int, std::vector< int > > _send_nodes
std::map< int, std::vector
< Real > > _send_buffers
Friends
class RFC_Window_transfer
Additional Inherited Members
Protected Member Functions inherited from RFC_Pane_base
void comp_nat_coors ()
Compute the natural coordinates.
void build_v2b_from_b2v (const RFC_Window_base *w)
Build pane connectivity.
void write_tec_ij (std::ostream &, const COM::DataItem *a=0) const
void write_tec_tri (std::ostream &, const COM::Connectivity &, const COM::DataItem *a=0) const
void write_tec_mixed (std::ostream &, const std::vector< const COM::Connectivity * > &, const COM::DataItem *a=0) const
void write_tec_sub (std::ostream &) const
void write_tec_ascii (std::ostream &os, const COM::DataItem *attr=0) const
void write_binary (std::ostream &os) const
void write_off (std::FILE *fhandle) const
void read_binary (std::istream &is, std::vector< int > *b2v_all=NULL, COM::Pane *p=NULL)
void register_sdv_dataitems (const std::string &wname) const
void read_rocin (const std::string &sdv_wname, const std::string &parent_wname="", COM::Pane *p=NULL)
Read in using Rocin.
Protected Attributes inherited from RFC_Pane_base
Base * _base
Reference to its base object.
bool _is_master
Is the pane a master copy?
bool _quadratic
Does it contain quadratic elements?
std::vector< bool > _is_border
Is a node on border?
std::vector< bool > _is_isolated
Is a node isolated?
int _n_border
int _n_isolated
V2b_table _v2b_table
B2v_table _b2v_table
std::vector< ParentEdge_ID > _subnode_parents
Edge ids of parents.
std::vector< Point_2S > _subnode_nat_coors
Natual coordinates in the parent face.
std::vector< Point_2S > _subnode_normalized_nc
Natual coordinates in the parent face.
std::vector< int > _subnode_subID
Sub-node ID of nodes in the pane.
std::vector< Node_ID > _subnode_counterparts
Ids of counterparts of subnodes.
std::vector< Three_tuple< int > > _subfaces
std::vector< int > _subface_parents
Face ids of the parents of the subfaces.
std::vector< int > _subface_offsets
Offsets of first subfaces contained in a face.
std::vector< Face_ID > _subface_counterparts
Ids of counterparts of faces.
std::vector< Three_tuple
< Point_2S > > _subface_nat_coors
Element connectivity of the subfaces.
Member Typedef Documentation
typedef RFC_Pane_base RFC_Pane_transfer::Base
Definition at line 38 of file RFC_Window_transfer.h.
typedef RFC_Pane_transfer RFC_Pane_transfer::Self
Definition at line 37 of file RFC_Window_transfer.h.
Constructor & Destructor Documentation
RFC_BEGIN_NAME_SPACE RFC_Pane_transfer::RFC_Pane_transfer (COM::Pane * b, int c)
Definition at line 17 of file RFC_Window_transfer.C.
   : Base( b, c), _window( NULL), _to_recv( NULL) {}
RFC_Pane_transfer::~RFC_Pane_transfer () virtual
Definition at line 19 of file RFC_Window_transfer.C.
 {}
Member Function Documentation
const Real* RFC_Pane_transfer::coordinates () const inline
Definition at line 61 of file RFC_Window_transfer.h.
References _coor_buf, RFC_Pane_base::coordinates(), and is_master().
Referenced by Transfer_base::compute_load_vector_wra(), Transfer_base::integrate_subface(), and RFC_Window_transfer::replicate_data().
{
     if ( is_master())
       return Base::coordinates();
     else {
       return &_coor_buf.front();
     }
   }
Real* RFC_Pane_transfer::get_emm (int f) inline
Definition at line 75 of file RFC_Window_transfer.h.
References _emm_buffer, _emm_offset, RFC_assertion, and RFC_Pane_base::size_of_faces().
Referenced by Transfer_base::compute_load_vector_wra(), and Transfer_base::multiply_mass_mat_and_x().
{
     RFC_assertion( f>=1 && f<=size_of_faces());
     return &_emm_buffer[ _emm_offset[f-1]];
   }
const Real* RFC_Pane_transfer::get_emm (int f) const inline
Definition at line 79 of file RFC_Window_transfer.h.
References _emm_buffer, _emm_offset, RFC_assertion, and RFC_Pane_base::size_of_faces().
{
     RFC_assertion( f>=1 && f<=size_of_faces());
     return &_emm_buffer[ _emm_offset[f-1]];
   }
bool RFC_Pane_transfer::is_master () const inline
Definition at line 84 of file RFC_Window_transfer.h.
References RFC_Pane_base::_base.
Referenced by coordinates(), pointer(), and RFC_Window_transfer::replicate_metadata().
 { return _base->window()!=NULL; }
bool RFC_Pane_transfer::need_recv (int i) const inline
Definition at line 68 of file RFC_Window_transfer.h.
References _to_recv, RFC_assertion, and RFC_Pane_base::size_of_faces().
Referenced by Transfer_base::interpolate_fe(), and Transfer_base::multiply_mass_mat_and_x().
{
     // Check whether an element is on the receiver list
     if ( _to_recv == NULL) return true;
     RFC_assertion( i>=1 && i<=size_of_faces());
     return _to_recv[ i-1];
   }
Real* RFC_Pane_transfer::pointer (int i) inline
Definition at line 47 of file RFC_Window_transfer.h.
References _buffer, _data_buf, _data_buf_id, is_master(), RFC_Pane_base::pointer(), and RFC_assertion.
Referenced by RFC_Data_const< _Tag >::get_value(), RFC_Data< _Tag >::get_value(), Transfer_base::interpolate_fe(), Transfer_base::make_field(), Transfer_base::multiply_mass_mat_and_x(), pointer(), RFC_Window_transfer::reduce_maxabs_to_all(), RFC_Window_transfer::reduce_to_all(), RFC_Window_transfer::replicate_data(), and RFC_Data< _Tag >::set_value().
{
     if ( i>=0) {
       if ( is_master())
         return Base::pointer(i);
       else {
         RFC_assertion( _data_buf_id == i);
         return &_data_buf.front();
       }
     }
     else
       return &_buffer[-i-1][0];
   }
const Real* RFC_Pane_transfer::pointer (int i) const inline
Definition at line 59 of file RFC_Window_transfer.h.
References pointer().
   { return const_cast<Self*>(this)->pointer(i); }
RFC_Window_transfer* RFC_Pane_transfer::window () inline
Definition at line 44 of file RFC_Window_transfer.h.
References _window.
 { return _window; }
const RFC_Window_transfer* RFC_Pane_transfer::window () const inline
Definition at line 45 of file RFC_Window_transfer.h.
References _window.
 { return _window; }
Friends And Related Function Documentation
friend class RFC_Window_transfer friend
Definition at line 39 of file RFC_Window_transfer.h.
Member Data Documentation
std::vector< std::vector<Real> > RFC_Pane_transfer::_buffer private
Definition at line 90 of file RFC_Window_transfer.h.
Referenced by RFC_Window_transfer::delete_facial_buffers(), RFC_Window_transfer::delete_nodal_buffers(), RFC_Window_transfer::init_facial_buffers(), RFC_Window_transfer::init_nodal_buffers(), and pointer().
std::vector< Real> RFC_Pane_transfer::_coor_buf private
Definition at line 95 of file RFC_Window_transfer.h.
Referenced by coordinates(), and RFC_Window_transfer::replicate_data().
std::vector< Real> RFC_Pane_transfer::_data_buf private
Definition at line 96 of file RFC_Window_transfer.h.
Referenced by pointer(), and RFC_Window_transfer::replicate_data().
int RFC_Pane_transfer::_data_buf_id private
Definition at line 94 of file RFC_Window_transfer.h.
Referenced by pointer(), and RFC_Window_transfer::replicate_data().
std::vector< Real> RFC_Pane_transfer::_emm_buffer private
Definition at line 92 of file RFC_Window_transfer.h.
Referenced by RFC_Window_transfer::delete_nodal_buffers(), get_emm(), and RFC_Window_transfer::init_nodal_buffers().
std::vector< int> RFC_Pane_transfer::_emm_offset private
Definition at line 91 of file RFC_Window_transfer.h.
Referenced by RFC_Window_transfer::delete_nodal_buffers(), get_emm(), and RFC_Window_transfer::init_nodal_buffers().
std::vector< MPI_Request> RFC_Pane_transfer::_msg_requests private
Definition at line 98 of file RFC_Window_transfer.h.
std::vector<int> RFC_Pane_transfer::_recv_faces private
Definition at line 104 of file RFC_Window_transfer.h.
Referenced by RFC_Window_transfer::replicate_data(), and RFC_Window_transfer::replicate_metadata().
std::vector<int> RFC_Pane_transfer::_recv_nodes private
Definition at line 105 of file RFC_Window_transfer.h.
Referenced by RFC_Window_transfer::replicate_data(), and RFC_Window_transfer::replicate_metadata().
std::map<int, std::vector<Real> > RFC_Pane_transfer::_send_buffers private
Definition at line 111 of file RFC_Window_transfer.h.
Referenced by RFC_Window_transfer::replicate_data().
std::map<int, std::vector<int> > RFC_Pane_transfer::_send_faces private
Definition at line 109 of file RFC_Window_transfer.h.
Referenced by RFC_Window_transfer::replicate_data(), and RFC_Window_transfer::replicate_metadata().
std::map<int, std::vector<int> > RFC_Pane_transfer::_send_nodes private
Definition at line 110 of file RFC_Window_transfer.h.
Referenced by RFC_Window_transfer::replicate_data(), and RFC_Window_transfer::replicate_metadata().
int* RFC_Pane_transfer::_to_recv private
Definition at line 99 of file RFC_Window_transfer.h.
Referenced by need_recv(), and RFC_Window_transfer::set_tags().
RFC_Window_transfer* RFC_Pane_transfer::_window private
Definition at line 88 of file RFC_Window_transfer.h.
Referenced by window().
The documentation for this class was generated from the following files:
RFC_Window_transfer.h
RFC_Window_transfer.C