IMPACT: Semaphore Class Reference
Semaphore Class Reference
Detailed Description
Definition at line 50 of file Sync.h.
#include <Sync.h>
Public Member Functions
Semaphore (int initialcount=0, int maxcount=0)
~Semaphore ()
bool IsOk () const
bool Wait ()
bool TryWait ()
bool Post ()
Private Attributes
Mutex m_mutex
Condition m_cond
int m_count
int m_maxcount
bool m_isOk
Constructor & Destructor Documentation
Semaphore::Semaphore (int initialcount = 0, int maxcount = 0)
Definition at line 155 of file Sync.C.
References Mutex::IsOk(), Condition::IsOk(), m_cond, m_count, m_isOk, m_maxcount, and m_mutex.
 : m_cond(m_mutex)
 {
   if ((initialcount < 0 || maxcount < 0)
       || ((maxcount > 0) && (initialcount > maxcount))) {
     std::cerr << "Semaphore::Semaphore(): invalid initial or maximal count."
               << std::endl;
     m_isOk = false;
   } else {
     m_maxcount = maxcount;
     m_count = initialcount;
   }
   m_isOk = m_mutex.IsOk() && m_cond.IsOk();
 }
Semaphore::~Semaphore ()
Definition at line 172 of file Sync.C.
 {
 }
Member Function Documentation
bool Semaphore::IsOk () const inline
Definition at line 56 of file Sync.h.
References m_isOk.
 { return m_isOk; }
bool Semaphore::Post ()
Definition at line 208 of file Sync.C.
References Mutex::Lock(), m_cond, m_count, m_maxcount, m_mutex, Condition::Signal(), and Mutex::Unlock().
 {
   m_mutex.Lock();
   if (m_maxcount > 0 && m_count == m_maxcount) {
     m_mutex.Unlock();
     return false;
   }
   ++m_count;
   int result = m_cond.Signal();
   m_mutex.Unlock();
   return (result == 0);
 }
bool Semaphore::TryWait ()
Definition at line 193 of file Sync.C.
References Mutex::Lock(), m_count, m_mutex, and Mutex::Unlock().
 {
   m_mutex.Lock();
   if (m_count == 0) {
     m_mutex.Unlock();
     return false;
   }
   --m_count;
   m_mutex.Unlock();
   return true;
 }
bool Semaphore::Wait ()
Definition at line 176 of file Sync.C.
References Mutex::Lock(), m_cond, m_count, m_mutex, Mutex::Unlock(), and Condition::Wait().
 {
   m_mutex.Lock();
   while (m_count == 0) {
     if (m_cond.Wait() != 0) {
       m_mutex.Unlock();
       return false;
     }
   }
   --m_count;
   m_mutex.Unlock();
   return true;
 }
Member Data Documentation
Condition Semaphore::m_cond private
Definition at line 64 of file Sync.h.
Referenced by Post(), Semaphore(), and Wait().
int Semaphore::m_count private
Definition at line 65 of file Sync.h.
Referenced by Post(), Semaphore(), TryWait(), and Wait().
bool Semaphore::m_isOk private
Definition at line 67 of file Sync.h.
Referenced by IsOk(), and Semaphore().
int Semaphore::m_maxcount private
Definition at line 66 of file Sync.h.
Referenced by Post(), and Semaphore().
Mutex Semaphore::m_mutex private
Definition at line 63 of file Sync.h.
Referenced by Post(), Semaphore(), TryWait(), and Wait().
The documentation for this class was generated from the following files:
Sync.h
Sync.C