IMPACT: TransferBurnRate_FS_ALE Class Reference
TransferBurnRate_FS_ALE Class Reference
Detailed Description
Definition at line 159 of file transfer_actions.h.
#include <transfer_actions.h>
Public Member Functions
TransferBurnRate_FS_ALE (FluidAgent *fag, SolidAgent *sag, const std::string b_rb, const std::string s_rb)
void init (double t)
void run (double t, double dt, double alpha)
Public Member Functions inherited from InterMeshTransfer
InterMeshTransfer (FluidAgent *fag, SolidAgent *sag, char *name=NULL)
Public Member Functions inherited from Action
Action (void *p=0, const char *name=NULL)
Action (int n, const char **at, int *i=NULL, void *p=0, const char *name=NULL)
Action (int n, const std::string at[], int *i=NULL, void *p=0, const char *name=NULL)
virtual ~Action ()
virtual void declare (Scheduler &)
virtual void finalize ()
virtual const char * name ()
void set_name (const char *name)
virtual void print (FILE *f)
virtual void print_toposort (FILE *f)
virtual void schedule ()
Private Attributes
std::string b_rb_str
std::string s_rb_str
int b_rb_hdl
int p_rb_hdl
int s_rb_hdl
int f_mdot_tmp_hdl
int fb_mdot_tmp_hdl
int RFC_transfer
Additional Inherited Members
Protected Types inherited from Action
enum { IN =1, OUT =2, INOUT =3 }
Protected Member Functions inherited from InterMeshTransfer
void load_rocface (const RocmanControl_parameters *param)
Protected Member Functions inherited from Action
int get_dataitem_handle (int i)
int get_dataitem_handle_const (int i)
int get_dataitem_handle (const std::string str)
void set_attr (int n, const std::string at[], int *id=NULL)
void set_attr (int n, const char *at[], int *id=NULL)
void set_io (int n, const int *io)
void set_io (const char *io)
int get_io (int i)
Protected Attributes inherited from InterMeshTransfer
FluidAgent * fagent
SolidAgent * sagent
Protected Attributes inherited from Action
const char * action_name
char ** attr
int * idx
int count
void * usr_ptr
std::vector< int > inout
Constructor & Destructor Documentation
TransferBurnRate_FS_ALE::TransferBurnRate_FS_ALE (FluidAgent * fag, SolidAgent * sag, const std::string b_rb, const std::string s_rb) explicit
Definition at line 837 of file transfer_actions.C.
References Action::IN, Action::OUT, Action::set_attr(), and Action::set_io().
                                                            :
                 InterMeshTransfer(fag, sag, "TransferBurnRate_FS_ALE"),
                 b_rb_str(b_rb), s_rb_str(s_rb)
 {
   int io[] = {IN, OUT};
   set_io( 2, io);
   std::string.data[2];
  .data[0] = b_rb;
  .data[1] = s_rb;
   set_attr(2,.data);
 }
Member Function Documentation
void TransferBurnRate_FS_ALE::init (double t) virtual
Reimplemented from Action.
Definition at line 852 of file transfer_actions.C.
References b_rb_hdl, COM_get_dataitem_handle(), COM_get_function_handle(), f_mdot_tmp_hdl, InterMeshTransfer::fagent, fb_mdot_tmp_hdl, FluidAgent::fluidBufB, FluidAgent::fluidBufNG, Agent::get_coupling(), Action::get_dataitem_handle(), Coupling::get_rocmancontrol_param(), InterMeshTransfer::load_rocface(), p_rb_hdl, RocmanControl_parameters::PROP_fom, SolidAgent::propBuf, SolidAgent::propBufAll, RFC_transfer, s_rb_hdl, InterMeshTransfer::sagent, and SolidAgent::withALE.
{
   if (sagent->withALE == 0) return;
   b_rb_hdl = get_dataitem_handle(0);
   s_rb_hdl = get_dataitem_handle(1);
   int PROP_fom = fagent->get_coupling()->get_rocmancontrol_param()->PROP_fom;
   if ( PROP_fom) {
      p_rb_hdl = COM_get_dataitem_handle( sagent->propBufAll+".rb");
   }
   else {
      p_rb_hdl = COM_get_dataitem_handle( sagent->propBuf+".rb");
   }
   f_mdot_tmp_hdl = COM_get_dataitem_handle( fagent->fluidBufNG+".mdot_tmp");
   fb_mdot_tmp_hdl = COM_get_dataitem_handle( fagent->fluidBufB+".mdot_tmp");
   load_rocface(fagent->get_coupling()->get_rocmancontrol_param());
   RFC_transfer = COM_get_function_handle("RFC.least_squares_transfer");
 }
void TransferBurnRate_FS_ALE::run (double t, double dt, double alpha) virtual
Reimplemented from Action.
Definition at line 871 of file transfer_actions.C.
References b_rb_hdl, COM_call_function(), RocBlas::copy, RocBlas::copy_scalar, f_mdot_tmp_hdl, fb_mdot_tmp_hdl, MAN_DEBUG, p_rb_hdl, RFC_transfer, s_rb_hdl, InterMeshTransfer::sagent, and SolidAgent::withALE.
{
   if (sagent->withALE == 0) return;
   MAN_DEBUG(2, ("Rocman: TransferBurnRate_FS_ALE::run() with t:%e dt:%e alpha:%e.\n", t, dt, alpha));
     // Transfer rb from fluid faces to solid faces
   double zero = 0.0;
   COM_call_function( RocBlas::copy_scalar, &zero, &p_rb_hdl);
     // Here we use f_mdot_tmp as buffer space for holding f_rb
   COM_call_function( RocBlas::copy_scalar, &zero, &f_mdot_tmp_hdl);
   COM_call_function( RocBlas::copy, &b_rb_hdl, &fb_mdot_tmp_hdl);
   COM_call_function( RFC_transfer, &f_mdot_tmp_hdl, &s_rb_hdl);
 }
Member Data Documentation
int TransferBurnRate_FS_ALE::b_rb_hdl private
Definition at line 166 of file transfer_actions.h.
Referenced by init(), and run().
std::string TransferBurnRate_FS_ALE::b_rb_str private
Definition at line 165 of file transfer_actions.h.
int TransferBurnRate_FS_ALE::f_mdot_tmp_hdl private
Definition at line 166 of file transfer_actions.h.
Referenced by init(), and run().
int TransferBurnRate_FS_ALE::fb_mdot_tmp_hdl private
Definition at line 166 of file transfer_actions.h.
Referenced by init(), and run().
int TransferBurnRate_FS_ALE::p_rb_hdl private
Definition at line 166 of file transfer_actions.h.
Referenced by init(), and run().
int TransferBurnRate_FS_ALE::RFC_transfer private
Definition at line 167 of file transfer_actions.h.
Referenced by init(), and run().
int TransferBurnRate_FS_ALE::s_rb_hdl private
Definition at line 166 of file transfer_actions.h.
Referenced by init(), and run().
std::string TransferBurnRate_FS_ALE::s_rb_str private
Definition at line 165 of file transfer_actions.h.
The documentation for this class was generated from the following files:
transfer_actions.h
transfer_actions.C