IMPACT: Vector_n Class Reference
Vector_n Class Reference
Detailed Description
Definition at line 167 of file Vector_n.h.
#include <Vector_n.h>
Public Types
typedef Vector_n Self
typedef Array_n Base
typedef Real Value
typedef Real * Pointer
typedef Real const * Const_pointer
typedef Real & Reference
typedef const Real & Const_reference
typedef unsigned int Size
Public Types inherited from Array_n
typedef Array_n Self
typedef Real Value
typedef Real * Pointer
typedef Real const * Const_pointer
typedef Real & Reference
typedef const Real & Const_reference
typedef unsigned int Size
Public Member Functions
Vector_n ()
Vector_n (Size n)
Vector_n (Size n, Real x)
Vector_n (const Vector_n &v)
operator const Array_n_const & () const
Self & operator= (const Array_n_const &v)
Self & operator+= (const Array_n_const &v)
Self & operator-= (const Array_n_const &v)
Self & operator*= (Real t)
Self & operator*= (const Array_n_const &v1)
Self & operator/= (Real t)
Self & operator/= (const Array_n_const &v)
Self & invert ()
Public Member Functions inherited from Array_n
Array_n ()
Array_n (Real *v, Size n)
Array_n (Real *v1, Real *v2)
Array_n (const Self &v)
operator const Array_n_const & () const
Reference operator[] (Size i)
Const_reference operator[] (Size i) const
Size dimension () const
Const_pointer begin () const
Const_pointer end () const
Pointer begin ()
Pointer end ()
Real squared_norm () const
Self & operator= (const Array_n_const &v)
Self & operator= (const Self &v)
Self & operator= (const Vector_n &v)
Self & operator+= (const Array_n_const &v1)
Self & operator-= (const Array_n_const &v1)
Self & operator*= (Real t)
Self & operator*= (const Array_n_const &v1)
Self & operator/= (Real t)
Self & operator/= (const Array_n_const &v1)
Self & invert ()
Protected Types
enum { MAX =9 }
Protected Member Functions
Vector_n (const Array_n_const &v)
Protected Attributes
Real _values [MAX]
Protected Attributes inherited from Array_n
Real * _start
Real * _end
Friends
Vector_n operator+ (const Array_n_const &v1, const Array_n_const &v2)
Vector_n operator- (const Array_n_const &v1, const Array_n_const &v2)
Vector_n operator* (Real a, const Array_n_const &v1)
Vector_n operator* (const Array_n_const &v1, Real a)
Vector_n operator/ (const Array_n_const &v1, Real a)
Vector_n multiply (const Array_n_const &v1, const Array_n_const &v2)
Vector_n divide (const Array_n_const &v1, const Array_n_const &v2)
Vector_n min (const Array_n_const &v1, const Array_n_const &v2)
Vector_n max (const Array_n_const &v1, const Array_n_const &v2)
Member Typedef Documentation
typedef Array_n Vector_n::Base
Definition at line 170 of file Vector_n.h.
typedef Real const* Vector_n::Const_pointer
Definition at line 173 of file Vector_n.h.
typedef const Real& Vector_n::Const_reference
Definition at line 175 of file Vector_n.h.
typedef Real* Vector_n::Pointer
Definition at line 172 of file Vector_n.h.
typedef Real& Vector_n::Reference
Definition at line 174 of file Vector_n.h.
typedef Vector_n Vector_n::Self
Definition at line 169 of file Vector_n.h.
typedef unsigned int Vector_n::Size
Definition at line 176 of file Vector_n.h.
typedef Real Vector_n::Value
Definition at line 171 of file Vector_n.h.
Member Enumeration Documentation
anonymous enum protected
Enumerator
MAX
Definition at line 242 of file Vector_n.h.
 { MAX=9};
Constructor & Destructor Documentation
Vector_n::Vector_n () inline
Definition at line 188 of file Vector_n.h.
 {}
Vector_n::Vector_n (Size n) inline explicit
Definition at line 189 of file Vector_n.h.
References MAX, and RFC_assertion.
 : Base( _values, n) { RFC_assertion( n<=MAX); }
Vector_n::Vector_n (Size n, Real x) inline explicit
Definition at line 190 of file Vector_n.h.
References Array_n::_end, Array_n::_start, MAX, and RFC_assertion.
                                       : Base( _values, n)
   { RFC_assertion(n<=MAX); std::fill( _start, _end, x); }
Vector_n::Vector_n (const Vector_n & v) inline
Definition at line 192 of file Vector_n.h.
References Array_n::_end, Array_n::_start, _values, Array_n::dimension(), MAX, and RFC_assertion.
                                : Base( _values, v.dimension())
   { RFC_assertion(dimension()<=MAX); std::copy( v._start, v._end, _values); }
Vector_n::Vector_n (const Array_n_const & v) inline protected
Definition at line 244 of file Vector_n.h.
References Array_n_const::_end, Array_n_const::_start, _values, Array_n_const::dimension(), MAX, and RFC_assertion.
                                     : Base( _values, v.dimension()) {
     RFC_assertion( v.dimension() <= MAX);
     std::copy( v._start,v._end,_values);
   }
Member Function Documentation
Self& Vector_n::invert () inline
Definition at line 236 of file Vector_n.h.
References Array_n::invert().
                  {
     Base::invert();
     return *this;
   }
Vector_n::operator const Array_n_const & () const inline
Definition at line 195 of file Vector_n.h.
{
     return reinterpret_cast<const Base&>(*this);
   }
Self& Vector_n::operator*= (Real t) inline
Definition at line 214 of file Vector_n.h.
References Array_n::operator*=().
{
     Base::operator*=( t);
     return *this;
   }
Self& Vector_n::operator*= (const Array_n_const & v1) inline
Definition at line 219 of file Vector_n.h.
References Array_n_const::_end, Array_n::_end, Array_n_const::_start, Array_n::_start, and RFC_assertion.
{
     RFC_assertion( _end-_start == v1._end-v1._start);
     const Real *q=v1._start;
     for ( Real *p=_start; p!=_end; ++p, ++q) *p *= *q;
     return *this;
   }
Self& Vector_n::operator+= (const Array_n_const & v) inline
Definition at line 204 of file Vector_n.h.
References Array_n::operator+=().
{
     Base::operator+=( v);
     return *this;
   }
Self& Vector_n::operator-= (const Array_n_const & v) inline
Definition at line 209 of file Vector_n.h.
References Array_n::operator-=().
{
     Base::operator-=( v);
     return *this;
   }
Self& Vector_n::operator/= (Real t) inline
Definition at line 226 of file Vector_n.h.
References Array_n::operator/=().
{
     Base::operator/=( t);
     return *this;
   }
Self& Vector_n::operator/= (const Array_n_const & v) inline
Definition at line 231 of file Vector_n.h.
References Array_n::operator/=().
{
     Base::operator/=( v);
     return *this;
   }
Self& Vector_n::operator= (const Array_n_const & v) inline
Definition at line 199 of file Vector_n.h.
References Array_n::operator=().
{
     Base::operator=( v);
     return *this;
   }
Friends And Related Function Documentation
Vector_n divide (const Array_n_const & v1, const Array_n_const & v2) friend
Definition at line 321 of file Vector_n.h.
{
   RFC_assertion( v1._end-v1._start == v2._end-v2._start);
   Vector_n v3( v1._end-v1._start);
   const Real *p=v1._start, *q=v2._start;
   for ( Real *r=v3._start; p!=v1._end; ++p, ++q, ++r) *r = (*q==0)? 1. : *p / *q;
   return v3;
 }
Vector_n max (const Array_n_const & v1, const Array_n_const & v2) friend
Definition at line 337 of file Vector_n.h.
{
   RFC_assertion( v1._end-v1._start == v2._end-v2._start);
   Vector_n v3( v1._end-v1._start);
   const Real *p=v1._start, *q=v2._start;
   for ( Real *r=v3._start; p!=v1._end; ++p, ++q, ++r) *r = std::max(*p,*q);
   return v3;
 }
Vector_n min (const Array_n_const & v1, const Array_n_const & v2) friend
Definition at line 329 of file Vector_n.h.
{
   RFC_assertion( v1._end-v1._start == v2._end-v2._start);
   Vector_n v3( v1._end-v1._start);
   const Real *p=v1._start, *q=v2._start;
   for ( Real *r=v3._start; p!=v1._end; ++p, ++q, ++r) *r = std::min(*p,*q);
   return v3;
 }
Vector_n multiply (const Array_n_const & v1, const Array_n_const & v2) friend
Definition at line 313 of file Vector_n.h.
{
   RFC_assertion( v1._end-v1._start == v2._end-v2._start);
   Vector_n v3( v1._end-v1._start);
   const Real *p=v1._start, *q=v2._start;
   for ( Real *r=v3._start; p!=v1._end; ++p, ++q, ++r) *r = *p * *q;
   return v3;
 }
Vector_n operator* (Real a, const Array_n_const & v1) friend
Definition at line 292 of file Vector_n.h.
{
   Vector_n v2( v1._end-v1._start);
   const Real *p=v1._start;
   for ( Real *q=v2._start; p!=v1._end; ++p, ++q) *q = a * *p;
   return v2;
 }
Vector_n operator* (const Array_n_const & v1, Real a) friend
Definition at line 299 of file Vector_n.h.
{
   Vector_n v2( v1._end-v1._start);
   const Real *p=v1._start;
   for ( Real *q=v2._start; p!=v1._end; ++p, ++q) *q = a * *p;
   return v2;
 }
Vector_n operator+ (const Array_n_const & v1, const Array_n_const & v2) friend
Definition at line 265 of file Vector_n.h.
{
   RFC_assertion( v1._end-v1._start == v2._end-v2._start);
   Vector_n v3( v1._end-v1._start);
   const Real *p=v1._start, *q=v2._start;
   for ( Real *r=v3._start; p!=v1._end; ++p, ++q, ++r) *r = *p + *q;
   return v3;
 }
Vector_n operator- (const Array_n_const & v1, const Array_n_const & v2) friend
Definition at line 273 of file Vector_n.h.
{
   RFC_assertion( v1._end-v1._start == v2._end-v2._start);
   Vector_n v3( v1._end-v1._start);
   const Real *p=v1._start, *q=v2._start;
   for ( Real *r=v3._start; p!=v1._end; ++p, ++q, ++r)
     *r = *p - *q;
   return v3;
 }
Vector_n operator/ (const Array_n_const & v1, Real a) friend
Definition at line 306 of file Vector_n.h.
{
   Vector_n v2( v1._end-v1._start);
   const Real *p=v1._start;
   for ( Real *q=v2._start; p!=v1._end; ++p, ++q) *q = (a==0) ? 1.: *p / a;
   return v2;
 }
Member Data Documentation
Real Vector_n::_values[MAX] protected
Definition at line 243 of file Vector_n.h.
Referenced by Vector_n().
The documentation for this class was generated from the following file:
Vector_n.h