IMPACT: SurfDiver Class Reference
SurfDiver Class Reference
Detailed Description
Definition at line 90 of file basic_actions.h.
#include <basic_actions.h>
Public Member Functions
SurfDiver (FluidAgent *fag, SolidAgent *sag)
void init (double t)
virtual void run (double t, double dt, double alpha)
Public Member Functions inherited from Action
Action (void *p=0, const char *name=NULL)
Action (int n, const char **at, int *i=NULL, void *p=0, const char *name=NULL)
Action (int n, const std::string at[], int *i=NULL, void *p=0, const char *name=NULL)
virtual ~Action ()
virtual void declare (Scheduler &)
virtual void finalize ()
virtual const char * name ()
void set_name (const char *name)
virtual void print (FILE *f)
virtual void print_toposort (FILE *f)
virtual void schedule ()
Protected Attributes
FluidAgent * fagent
SolidAgent * sagent
std::string outdir
std::string fluid_mesh_str
std::string solid_mesh_str
int fluid_mesh
int solid_mesh
int RFC_transfer
int RFC_interpolate
int RFC_readcntr
int RFC_overlay
int RFC_write
int RFC_read
Protected Attributes inherited from Action
const char * action_name
char ** attr
int * idx
int count
void * usr_ptr
std::vector< int > inout
Additional Inherited Members
Protected Types inherited from Action
enum { IN =1, OUT =2, INOUT =3 }
Protected Member Functions inherited from Action
int get_dataitem_handle (int i)
int get_dataitem_handle_const (int i)
int get_dataitem_handle (const std::string str)
void set_attr (int n, const std::string at[], int *id=NULL)
void set_attr (int n, const char *at[], int *id=NULL)
void set_io (int n, const int *io)
void set_io (const char *io)
int get_io (int i)
Constructor & Destructor Documentation
SurfDiver::SurfDiver (FluidAgent * fag, SolidAgent * sag)
Definition at line 86 of file Surfdiver.C.
References fagent, Agent::get_rocmod_name(), outdir, and sagent.
                                                     :
   Action( 0, (const char**)NULL, NULL, NULL, "SurfDiver"),
   fagent(fag), sagent(sag)
 {
   outdir = "Rocman/"+fagent->get_rocmod_name()+sagent->get_rocmod_name()+"/";
 }
Member Function Documentation
void SurfDiver::init (double t) virtual
Reimplemented from Action.
Definition at line 93 of file Surfdiver.C.
References _load_rocface(), COM_get_dataitem_handle_const(), COM_get_function_handle(), fagent, fluid_mesh, fluid_mesh_str, FluidAgent::fluidBufNG, Agent::get_coupling(), Coupling::get_rocmancontrol_param(), Agent::get_rocmod_name(), RFC_interpolate, RFC_overlay, RFC_read, RFC_readcntr, RFC_transfer, RFC_write, sagent, solid_mesh, solid_mesh_str, and SolidAgent::solidBuf.
 {
   fluid_mesh = COM_get_dataitem_handle_const( fagent->fluidBufNG+".mesh");
   solid_mesh = COM_get_dataitem_handle_const( sagent->solidBuf+".mesh");
   fluid_mesh_str = fagent->get_rocmod_name()+".mesh";
   solid_mesh_str = sagent->get_rocmod_name()+".mesh";
   _load_rocface(fagent, sagent, fagent->get_coupling()->get_rocmancontrol_param());
   RFC_readcntr = COM_get_function_handle( "RFC.read_control_file");
   RFC_overlay = COM_get_function_handle( "RFC.overlay");
   RFC_write = COM_get_function_handle( "RFC.write_overlay");
   RFC_transfer = COM_get_function_handle("RFC.least_squares_transfer");
   RFC_interpolate = COM_get_function_handle("RFC.interpolate");
   RFC_read = COM_get_function_handle( "RFC.read_overlay");
 }
void SurfDiver::run (double t, double dt, double alpha) virtual
Reimplemented from Action.
Reimplemented in SurfDiverAfterRemeshing.
Definition at line 110 of file Surfdiver.C.
References COM_call_function(), COM_get_dataitem_handle(), COM_get_default_communicator(), COM_set_default_communicator(), COM_set_profiling(), COM_window_init_done(), fagent, fluid_mesh, Agent::get_comm_rank(), Agent::get_communicator(), Agent::get_rocmod_name(), Agent::get_time_string(), MAN_DEBUG, outdir, FluidAgent::output_restart_files(), SolidAgent::output_restart_files(), read_file(), RFC_overlay, RFC_read, RFC_write, sagent, and solid_mesh.
{
   MAN_DEBUG(1, ("[%d] Rocman: SurfDiver::run() with t:%e dt:%e.\n", fagent->get_comm_rank(), t, dt));
   MPI_Comm comm = fagent->get_communicator();
   //  dump meshes
   MAN_DEBUG(1, ("[%d] Rocman: SurfDiver::run() dumping output files for time %e.\n", fagent->get_comm_rank(), t));
   fagent->output_restart_files( t);
   sagent->output_restart_files( t);
   MPI_Barrier(comm);
     // run sequentially
   if (fagent->get_comm_rank() == 0) {
     int oldcomm = COM_get_default_communicator();
     COM_set_default_communicator( MPI_COMM_NULL);
       // need to turn off profiling as it may hang for npes > 1
     COM_set_profiling(0);
     //  read meshes
     std::string time_str;
     fagent->get_time_string(t, time_str);
     std::string fluid_file = fagent->get_rocmod_name()+"/SimOUT/ifluid_in_"+time_str+".txt";
     std::string solid_file = sagent->get_rocmod_name()+"/SimOUT/isolid_in_"+time_str+".txt";
     std::string fluid_wname = outdir+"ifluid";
     std::string solid_wname = outdir+"isolid";
     read_file( fluid_file.c_str(), fluid_wname.c_str(), 1.);
     COM_window_init_done( fluid_wname);
     read_file( solid_file.c_str(), solid_wname.c_str(), 1.);
     COM_window_init_done( solid_wname);
     int fluid_mesh1 = COM_get_dataitem_handle( (fluid_wname+".mesh").c_str());
     int solid_mesh1 = COM_get_dataitem_handle( (solid_wname+".mesh").c_str());
     const char *format = "HDF";
     // mesh overlay
     std::cout << "Starting mesh overlay... "  << std::endl;
     COM_call_function( RFC_overlay, &fluid_mesh1, &solid_mesh1);
     // output overlay mesh
     COM_call_function( RFC_write, &fluid_mesh1, &solid_mesh1,
                      fluid_wname.c_str(), solid_wname.c_str(), format);
     COM_set_default_communicator( oldcomm);
     COM_set_profiling(1);
   }   // end of PE 0
   MPI_Barrier(comm);
   // reload overlay
   std::string fluid_dir = outdir+"ifluid";
   std::string solid_dir = outdir+"isolid";
   std::cout << "Reload partitioned mesh overlay... "  << std::endl;
   COM_call_function( RFC_read, &fluid_mesh, &solid_mesh, &comm, fluid_dir.c_str(), solid_dir.c_str(), "HDF");
 }
Member Data Documentation
FluidAgent* SurfDiver::fagent protected
Definition at line 97 of file basic_actions.h.
Referenced by init(), run(), SurfDiverAfterRemeshing::run(), and SurfDiver().
int SurfDiver::fluid_mesh protected
Definition at line 101 of file basic_actions.h.
Referenced by init(), and run().
std::string SurfDiver::fluid_mesh_str protected
Definition at line 100 of file basic_actions.h.
Referenced by init().
std::string SurfDiver::outdir protected
Definition at line 99 of file basic_actions.h.
Referenced by run(), and SurfDiver().
int SurfDiver::RFC_interpolate protected
Definition at line 102 of file basic_actions.h.
Referenced by init().
int SurfDiver::RFC_overlay protected
Definition at line 102 of file basic_actions.h.
Referenced by init(), and run().
int SurfDiver::RFC_read protected
Definition at line 103 of file basic_actions.h.
Referenced by init(), and run().
int SurfDiver::RFC_readcntr protected
Definition at line 102 of file basic_actions.h.
Referenced by init().
int SurfDiver::RFC_transfer protected
Definition at line 102 of file basic_actions.h.
Referenced by init().
int SurfDiver::RFC_write protected
Definition at line 103 of file basic_actions.h.
Referenced by init(), and run().
SolidAgent* SurfDiver::sagent protected
Definition at line 98 of file basic_actions.h.
Referenced by init(), run(), SurfDiverAfterRemeshing::run(), and SurfDiver().
int SurfDiver::solid_mesh protected
Definition at line 101 of file basic_actions.h.
Referenced by init(), and run().
std::string SurfDiver::solid_mesh_str protected
Definition at line 100 of file basic_actions.h.
Referenced by init().
The documentation for this class was generated from the following files:
basic_actions.h
Surfdiver.C