IMPACT: IRAD::Sys::fdoutbuf Class Reference
IRAD::Sys::fdoutbuf Class Reference
Detailed Description
Definition at line 33 of file FDUtils.H.
#include <FDUtils.H>
Public Member Functions
fdoutbuf ()
fdoutbuf (int _fd)
void Init (int _fd)
bool Ready ()
virtual int FD ()
Protected Member Functions
virtual int_type overflow (int_type c)
virtual std::streamsize xsputn (const char *s, std::streamsize num)
Protected Attributes
int fd
Constructor & Destructor Documentation
IRAD::Sys::fdoutbuf::fdoutbuf () inline
Definition at line 37 of file FDUtils.H.
References fd.
 { fd = -1; };
IRAD::Sys::fdoutbuf::fdoutbuf (int _fd) inline
Definition at line 39 of file FDUtils.H.
                          : fd(_fd) {
       }
Member Function Documentation
virtual int IRAD::Sys::fdoutbuf::FD () inline virtual
Definition at line 43 of file FDUtils.H.
References fd.
Referenced by IRAD::Sys::fdostream::FD(), and IRAD::Sys::fdostream::Init().
 { return fd; };
void IRAD::Sys::fdoutbuf::Init (int _fd) inline
Definition at line 41 of file FDUtils.H.
References fd.
Referenced by IRAD::Sys::fdostream::Init().
 { fd = _fd; };
virtual int_type IRAD::Sys::fdoutbuf::overflow (int_type c) inline protected virtual
Definition at line 46 of file FDUtils.H.
References fd, and write().
{
         if (c != EOF) {
           char z = c;
           if (write (fd, &z, 1) != 1) {
             return EOF;
           }
         }
         return c;
       }
bool IRAD::Sys::fdoutbuf::Ready () inline
Definition at line 42 of file FDUtils.H.
References fd.
 { return(fd >= 0); };
virtual std::streamsize IRAD::Sys::fdoutbuf::xsputn (const char * s, std::streamsize num) inline protected virtual
Definition at line 57 of file FDUtils.H.
References fd, and write().
{
         return write(fd,s,num);
       }
Member Data Documentation
int IRAD::Sys::fdoutbuf::fd protected
Definition at line 35 of file FDUtils.H.
Referenced by FD(), fdoutbuf(), Init(), overflow(), Ready(), and xsputn().
The documentation for this class was generated from the following file:
FDUtils.H