IMPACT: UserScheduler Class Reference
UserScheduler Class Reference
Detailed Description
Definition at line 82 of file Scheduler.h.
#include <Scheduler.h>
Public Member Functions
virtual void add_action (Action *)
virtual void schedule ()
Public Member Functions inherited from Scheduler
Scheduler ()
Scheduler.
virtual ~Scheduler ()
void reads (Action *, const char *attr, int idx)
void writes (Action *, const char *attr, int idx)
void init_actions (double t)
void restarting (double t)
void run_actions (double t, double dt)
void finalize_actions ()
void set_alpha (double alpha)
void print (const char *fname)
char * print (FILE *f, const char *container_name)
void printDDG (FILE *f)
bool isEmpty ()
const char * name ()
void set_name (const char *name)
Additional Inherited Members
Protected Types inherited from Scheduler
typedef vector< ActionItem * > ActionList
Protected Member Functions inherited from Scheduler
void buildDDG ()
Protected Attributes inherited from Scheduler
std::string scheduler_name
ActionList actions
ActionList roots
ActionList sort
double alphaT
int scheduled
int inited
Member Function Documentation
void UserScheduler::add_action (Action * action) virtual
Reimplemented from Scheduler.
Definition at line 384 of file Scheduler.C.
References Scheduler::actions, Scheduler::add_action(), Scheduler::roots, and Scheduler::sort.
Referenced by Agent::add_bcaction(), Agent::add_bcinitaction(), Agent::add_gmaction(), Agent::add_icaction(), FluidAlone::FluidAlone(), and FluidBurnAlone::FluidBurnAlone().
 {
   Scheduler::add_action(action);
   if (roots.size() == 0) roots.push_back(actions[actions.size()-1]);
   sort.push_back(actions[actions.size()-1]);
 }
void UserScheduler::schedule () virtual
Reimplemented from Scheduler.
Definition at line 391 of file Scheduler.C.
References Scheduler::buildDDG(), and Scheduler::scheduled.
Referenced by UserSchedulerAction::schedule(), Coupling::schedule(), and Agent::schedule().
 {
 /*
   for (unsigned int i=0; i<actions.size(); i++)  {
     if (i+1<actions.size()) {
       actions[i]->output.push_back(actions[i+1]);
       actions[i+1]->input.push_back(actions[i]);
     }
   }
 */
   buildDDG();
   scheduled = 1;
 }
The documentation for this class was generated from the following files:
Scheduler.h
Scheduler.C