IMPACT: SolverUtils::GeoPrim::CLineSegment Class Reference
SolverUtils::GeoPrim::CLineSegment Class Reference
Detailed Description
Definition at line 1377 of file GeoPrimitives.H.
#include <GeoPrimitives.H>
Public Member Functions
CLineSegment ()
CLineSegment (const CPoint &p)
CLineSegment (const CPoint &pb, const CPoint &pe)
double length () const
CVector slope () const
bool has_point (const CPoint &p3) const
CPoint & point1 ()
CPoint & point2 ()
const CPoint & point1 () const
const CPoint & point2 () const
CLineSegment & point1 (const CPoint &p)
CLineSegment & point2 (const CPoint &p)
Protected Attributes
CPoint p1
CPoint p2
Constructor & Destructor Documentation
SolverUtils::GeoPrim::CLineSegment::CLineSegment () inline
Definition at line 1382 of file GeoPrimitives.H.
       : p1(0,0,0),p2(0,0,0)
     {};
SolverUtils::GeoPrim::CLineSegment::CLineSegment (const CPoint & p) inline
Definition at line 1385 of file GeoPrimitives.H.
       : p1(0,0,0),p2(p)
     {};
SolverUtils::GeoPrim::CLineSegment::CLineSegment (const CPoint & pb, const CPoint & pe) inline
Definition at line 1388 of file GeoPrimitives.H.
       : p1(pb),p2(pe)
     {};
Member Function Documentation
bool SolverUtils::GeoPrim::CLineSegment::has_point (const CPoint & p3) const inline
Definition at line 1401 of file GeoPrimitives.H.
References SolverUtils::GeoPrim::CLine::has_point(), p1, p2, SolverUtils::GeoPrim::CPoint::x(), SolverUtils::GeoPrim::CPoint::y(), and SolverUtils::GeoPrim::CPoint::z().
     {
       if(p3 == p1 || p3 == p2) return true;
       if(p1 == p2) return false;
       CLine l(p1,p2);
       if(!l.has_point(p3)) return false;
       double u;
       if(p1.x() != p2.x())
         u = (p3.x() - p1.x())/(p2.x() - p1.x());
       else if(p1.y() != p2.y())
         u = (p3.y() - p1.y())/(p2.y() - p1.y());
       else if(p1.z() != p2.z())
         u = (p3.z() - p1.z())/(p2.z() - p1.z());
       return ( u >= 0.0 && u <= 1.0 );
     };
double SolverUtils::GeoPrim::CLineSegment::length () const inline
Definition at line 1391 of file GeoPrimitives.H.
References SolverUtils::GeoPrim::CVector::norm(), p1, and p2.
     {
       CVector v(p1,p2);
       return(v.norm());
     };
CPoint& SolverUtils::GeoPrim::CLineSegment::point1 () inline
Definition at line 1416 of file GeoPrimitives.H.
References p1.
     {
       return (p1);
     };
const CPoint& SolverUtils::GeoPrim::CLineSegment::point1 () const inline
Definition at line 1424 of file GeoPrimitives.H.
References p1.
     {
       return (p1);
     };
CLineSegment& SolverUtils::GeoPrim::CLineSegment::point1 (const CPoint & p) inline
Definition at line 1432 of file GeoPrimitives.H.
References p1.
     {
       p1 = p;
       return(*this);
     };
CPoint& SolverUtils::GeoPrim::CLineSegment::point2 () inline
Definition at line 1420 of file GeoPrimitives.H.
References p2.
     {
       return (p2);
     };
const CPoint& SolverUtils::GeoPrim::CLineSegment::point2 () const inline
Definition at line 1428 of file GeoPrimitives.H.
References p2.
     {
       return (p2);
     };
CLineSegment& SolverUtils::GeoPrim::CLineSegment::point2 (const CPoint & p) inline
Definition at line 1437 of file GeoPrimitives.H.
References p2.
     {
       p2 = p;
       return(*this);
     };
CVector SolverUtils::GeoPrim::CLineSegment::slope () const inline
Definition at line 1396 of file GeoPrimitives.H.
References p1, and p2.
     {
       CVector v(p1,p2);
     return(v);
     };
Member Data Documentation
CPoint SolverUtils::GeoPrim::CLineSegment::p1 protected
Definition at line 1379 of file GeoPrimitives.H.
Referenced by has_point(), length(), point1(), and slope().
CPoint SolverUtils::GeoPrim::CLineSegment::p2 protected
Definition at line 1380 of file GeoPrimitives.H.
Referenced by has_point(), length(), point2(), and slope().
The documentation for this class was generated from the following file:
GeoPrimitives.H