IMPACT: SolverUtils::FEM::FDSolverAgent Class Reference
SolverUtils::FEM::FDSolverAgent Class Reference
Detailed Description
Definition at line 138 of file SolverAgent.H.
#include <SolverAgent.H>
Public Member Functions
FDSolverAgent (int descriptor=-1)
void Init (int descriptor=-1)
IRAD::Sys::fdistream & InStream ()
IRAD::Sys::fdostream & OutStream ()
void SendACK ()
std::string ACKWord () const
int GetACK ()
void SendWord (const std::string &word)
void SendACK (const std::string &ack)
std::string ReceiveWord ()
int ReceiveWord (std::string &word)
int GetACK (const std::string &ack)
void ReceiveMesh ()
void SendMesh ()
void ReceiveCoords ()
void SendCoords ()
void ReceiveSolnMeta ()
void SendSolnMeta ()
void ReceiveSoln (const std::string &name)
void SendSoln (const std::string &name)
void SendSoln (const std::string &name, void *buf, int bsize=0)
template<class T >
void Recv (T &object)
template<class T >
void Send (const T &object)
Public Member Functions inherited from SolverUtils::FEM::SolverAgent
const FEM::SolutionData & Solution () const
FEM::SolutionData & Solution ()
const Mesh::UnstructuredMesh & Mesh () const
Mesh::UnstructuredMesh & Mesh ()
void ReadMeshFromStream (std::istream &Istr)
void WriteMeshToStream (std::ostream &Ostr)
void ReadCoordsFromStream (std::istream &Istr)
void WriteCoordsToStream (std::ostream &Ostr)
void ReadSolnMetaFromStream (std::istream &Istr)
void WriteSolnMetaToStream (std::ostream &Ostr)
void CreateSoln ()
void ReadSolnFromStream (std::istream &Istr, const std::string &name)
void WriteSolnToStream (std::ostream &Ostr, const std::string &name)
std::ostream & ReportMeshToStream (std::ostream &Ostr)
~SolverAgent ()
Private Attributes
IRAD::Sys::fdistream FDIn
IRAD::Sys::fdostream FDOut
std::string _ackword
Constructor & Destructor Documentation
SolverUtils::FEM::FDSolverAgent::FDSolverAgent (int descriptor = -1) inline
Definition at line 145 of file SolverAgent.H.
References FDIn, and FDOut.
                                        : SolverAgent()
     {
       if(descriptor >= 0){
         FDIn.Init(descriptor);
         FDOut.Init(descriptor);
       }
     };
Member Function Documentation
std::string SolverUtils::FEM::FDSolverAgent::ACKWord () const inline
Definition at line 164 of file SolverAgent.H.
References _ackword.
 { return(_ackword); };
int SolverUtils::FEM::FDSolverAgent::GetACK () inline
Definition at line 165 of file SolverAgent.H.
References _ackword, and Recv().
                 {
       Recv(_ackword);
       if(_ackword == "ack")
         return(0);
       else
         return(1);
     };
int SolverUtils::FEM::FDSolverAgent::GetACK (const std::string & ack) inline
Definition at line 189 of file SolverAgent.H.
References _ackword, and Recv().
{
       Recv(_ackword);
       if(_ackword == ack)
         return(0);
       else
         return(1);
     };
void SolverUtils::FEM::FDSolverAgent::Init (int descriptor = -1) inline
Definition at line 152 of file SolverAgent.H.
References FDIn, and FDOut.
Referenced by SolverUtils::FEM::TCPSolverClient::Connect().
     {
       if(descriptor >= 0){
         FDIn.Init(descriptor);
         FDOut.Init(descriptor);
       }
     };
IRAD::Sys::fdistream& SolverUtils::FEM::FDSolverAgent::InStream () inline
Definition at line 159 of file SolverAgent.H.
References FDIn.
 { return(FDIn); };
IRAD::Sys::fdostream& SolverUtils::FEM::FDSolverAgent::OutStream () inline
Definition at line 160 of file SolverAgent.H.
References FDOut.
 { return(FDOut); };
void SolverUtils::FEM::FDSolverAgent::ReceiveCoords () inline
Definition at line 208 of file SolverAgent.H.
References SolverUtils::FEM::SolverAgent::Mesh(), and Recv().
     {
       Recv(Mesh().nc);
     };
void SolverUtils::FEM::FDSolverAgent::ReceiveMesh () inline
Definition at line 196 of file SolverAgent.H.
References SolverUtils::FEM::SolverAgent::Mesh(), and Recv().
     {
       Recv(Mesh().nc);
       Recv(Mesh().con);
     };
void SolverUtils::FEM::FDSolverAgent::ReceiveSoln (const std::string & name) inline
Definition at line 225 of file SolverAgent.H.
References FDIn, SolverUtils::FEM::SolutionData::ReadFieldFromStream(), and SolverUtils::FEM::SolverAgent::Solution().
     {
       Solution().ReadFieldFromStream(FDIn,name);
     };
void SolverUtils::FEM::FDSolverAgent::ReceiveSolnMeta () inline
Definition at line 217 of file SolverAgent.H.
References FDIn, SolverUtils::FEM::SolutionData::Meta(), SolverUtils::FEM::SolutionMetaData::ReadFromStream(), and SolverUtils::FEM::SolverAgent::Solution().
     {
       Solution().Meta().ReadFromStream(FDIn);
     };
std::string SolverUtils::FEM::FDSolverAgent::ReceiveWord () inline
Definition at line 180 of file SolverAgent.H.
References Recv().
{
       std::string word;
       Recv(word);
       return(word);
     };
int SolverUtils::FEM::FDSolverAgent::ReceiveWord (std::string & word) inline
Definition at line 185 of file SolverAgent.H.
References Recv().
{
       Recv(word);
       return(word.size());
     };
template<class T > void SolverUtils::FEM::FDSolverAgent::Recv (T & object) inline
Definition at line 238 of file SolverAgent.H.
References FDIn.
Referenced by GetACK(), ReceiveCoords(), ReceiveMesh(), and ReceiveWord().
     {
       FDIn >> object;
     };
template<class T > void SolverUtils::FEM::FDSolverAgent::Send (const T & object) inline
Definition at line 243 of file SolverAgent.H.
References FDOut.
Referenced by SendACK(), SendCoords(), and SendMesh().
     {
       FDOut << object;
     };
void SolverUtils::FEM::FDSolverAgent::SendACK () inline
Definition at line 161 of file SolverAgent.H.
References Send().
Referenced by SendWord().
                    {
       Send("ack\n");
     };
void SolverUtils::FEM::FDSolverAgent::SendACK (const std::string & ack) inline
Definition at line 175 of file SolverAgent.H.
References Send().
{
       std::ostringstream Ostr;
       Ostr << ack << "\n";
       Send(Ostr.str());
     };
void SolverUtils::FEM::FDSolverAgent::SendCoords () inline
Definition at line 212 of file SolverAgent.H.
References SolverUtils::FEM::SolverAgent::Mesh(), and Send().
     {
       Send(Mesh().nc);
       Send('\n');
     };
void SolverUtils::FEM::FDSolverAgent::SendMesh () inline
Definition at line 201 of file SolverAgent.H.
References SolverUtils::FEM::SolverAgent::Mesh(), and Send().
     {
       Send(Mesh().nc);
       Send('\n');
       Send(Mesh().con);
       Send('\n');
     };
void SolverUtils::FEM::FDSolverAgent::SendSoln (const std::string & name) inline
Definition at line 229 of file SolverAgent.H.
References FDOut, SolverUtils::FEM::SolverAgent::Solution(), and SolverUtils::FEM::SolutionData::WriteFieldToStream().
     {
       Solution().WriteFieldToStream(FDOut,name);
     };
void SolverUtils::FEM::FDSolverAgent::SendSoln (const std::string & name, void * buf, int bsize = 0) inline
Definition at line 233 of file SolverAgent.H.
References FDOut, SolverUtils::FEM::SolverAgent::Solution(), and SolverUtils::FEM::SolutionData::WriteFieldToStream().
     {
       Solution().WriteFieldToStream(FDOut,name);
     };
void SolverUtils::FEM::FDSolverAgent::SendSolnMeta () inline
Definition at line 221 of file SolverAgent.H.
References FDOut, SolverUtils::FEM::SolutionData::Meta(), SolverUtils::FEM::SolverAgent::Solution(), and SolverUtils::FEM::SolutionMetaData::WriteToStream().
     {
       Solution().Meta().WriteToStream(FDOut);
     };
void SolverUtils::FEM::FDSolverAgent::SendWord (const std::string & word) inline
Definition at line 172 of file SolverAgent.H.
References SendACK().
{
       SendACK(word);
     };
Member Data Documentation
std::string SolverUtils::FEM::FDSolverAgent::_ackword private
Definition at line 143 of file SolverAgent.H.
Referenced by ACKWord(), and GetACK().
IRAD::Sys::fdistream SolverUtils::FEM::FDSolverAgent::FDIn private
Definition at line 141 of file SolverAgent.H.
Referenced by FDSolverAgent(), Init(), InStream(), ReceiveSoln(), ReceiveSolnMeta(), and Recv().
IRAD::Sys::fdostream SolverUtils::FEM::FDSolverAgent::FDOut private
Definition at line 142 of file SolverAgent.H.
Referenced by FDSolverAgent(), Init(), OutStream(), Send(), SendSoln(), and SendSolnMeta().
The documentation for this class was generated from the following file:
SolverAgent.H