IMPACT: IRAD::Global::Program< GlobalType, ComLineType > Class Template Reference
IRAD::Global::Program< GlobalType, ComLineType > Class Template Reference
Detailed Description
template<typename GlobalType, typename ComLineType>
class IRAD::Global::Program< GlobalType, ComLineType >
Definition at line 562 of file Global.H.
#include <Global.H>
Public Member Functions
Program ()
Program (GlobalType &inglob)
Program (ComLineType &incom)
Program (ComLineType &incom, GlobalType &inglob)
Program (int narg, char **args)
virtual int Initialize ()
ComLineType & CommandLine ()
virtual int Run ()
virtual int Finalize ()
virtual ~Program ()
Protected Attributes
ComLineType _command_line
Constructor & Destructor Documentation
template<typename GlobalType, typename ComLineType> IRAD::Global::Program< GlobalType, ComLineType >::Program () inline
Definition at line 567 of file Global.H.
                 :
         GlobalType()
       {};
template<typename GlobalType, typename ComLineType> IRAD::Global::Program< GlobalType, ComLineType >::Program (GlobalType & inglob) inline
Definition at line 570 of file Global.H.
                                   :
         GlobalType(inglob){};
template<typename GlobalType, typename ComLineType> IRAD::Global::Program< GlobalType, ComLineType >::Program (ComLineType & incom) inline
Definition at line 572 of file Global.H.
                                   :
         GlobalType(),_command_line(incom)
       {};
template<typename GlobalType, typename ComLineType> IRAD::Global::Program< GlobalType, ComLineType >::Program (ComLineType & incom, GlobalType & inglob) inline
Definition at line 575 of file Global.H.
                                                      :
         GlobalType(inglob), _command_line(incom) {};
template<typename GlobalType, typename ComLineType> IRAD::Global::Program< GlobalType, ComLineType >::Program (int narg, char ** args) inline
Definition at line 577 of file Global.H.
                                     :
         GlobalType(narg,args)
       {
         _command_line.Record((const char **)args);
         //      SetName(_command_line.ProgramName());
       };
template<typename GlobalType, typename ComLineType> virtual IRAD::Global::Program< GlobalType, ComLineType >::~Program () inline virtual
Definition at line 591 of file Global.H.
 {};
Member Function Documentation
template<typename GlobalType, typename ComLineType> ComLineType& IRAD::Global::Program< GlobalType, ComLineType >::CommandLine () inline
Definition at line 588 of file Global.H.
 {return _command_line; };
template<typename GlobalType, typename ComLineType> virtual int IRAD::Global::Program< GlobalType, ComLineType >::Finalize () inline virtual
Definition at line 590 of file Global.H.
Referenced by IMPACT::ExampleProgram::Driver(), and IRAD::MyTestProgram().
 {return(GlobalType::Finalize());};
template<typename GlobalType, typename ComLineType> virtual int IRAD::Global::Program< GlobalType, ComLineType >::Initialize (void) inline virtual
Reimplemented in IMPACT::ExampleProgram::ParallelProgram, IMPACT::ExampleProgram::SerialProgram, and IRAD::TestProgram.
Definition at line 583 of file Global.H.
Referenced by IRAD::TestProgram::Initialize(), IMPACT::ExampleProgram::SerialProgram::Initialize(), and IMPACT::ExampleProgram::ParallelProgram::Initialize().
       {
         _command_line.Initialize();
         return(_command_line.ProcessOptions());
       };
template<typename GlobalType, typename ComLineType> virtual int IRAD::Global::Program< GlobalType, ComLineType >::Run () inline virtual
Reimplemented in IMPACT::ExampleProgram::ParallelProgram, and IMPACT::ExampleProgram::SerialProgram.
Definition at line 589 of file Global.H.
Referenced by IRAD::MyTestProgram().
 {return(0);};
Member Data Documentation
template<typename GlobalType, typename ComLineType> ComLineType IRAD::Global::Program< GlobalType, ComLineType >::_command_line protected
Definition at line 565 of file Global.H.
Referenced by IRAD::Global::Program< TestGlobal, TestComLine >::CommandLine(), IMPACT::ExampleProgram::SerialProgram::Initialize(), IMPACT::ExampleProgram::ParallelProgram::Initialize(), IRAD::Global::Program< TestGlobal, TestComLine >::Initialize(), IMPACT::ExampleProgram::ParallelProgram::ParallelProgram(), and IRAD::Global::Program< TestGlobal, TestComLine >::Program().
The documentation for this class was generated from the following file:
Global.H