IMPACT: MSH_Reader Class Reference
MSH_Reader Class Reference
Detailed Description
Definition at line 23 of file MSH_Reader.h.
#include <MSH_Reader.h>
Public Member Functions
MSH_Reader ()
int read_mesh (const char *fname, const std::string &wname)
Private Types
enum { MAXLEN =255 }
Private Member Functions
void get_nextline (std::istream &is, char *str)
void read_pane_coors (std::istream &is, const std::string &wname)
void read_pane_elems (std::istream &is, const std::string &wname)
Private Attributes
char buf [MAXLEN+1]
Member Enumeration Documentation
anonymous enum private
Enumerator
MAXLEN
Definition at line 127 of file MSH_Reader.h.
 {MAXLEN=255};
Constructor & Destructor Documentation
MSH_Reader::MSH_Reader () inline
Definition at line 26 of file MSH_Reader.h.
 {}
Member Function Documentation
void MSH_Reader::get_nextline (std::istream & is, char * str) inline private
Definition at line 50 of file MSH_Reader.h.
References MAXLEN.
Referenced by read_pane_coors(), and read_pane_elems().
{
     str[0] = '\0';
     if ( is.eof()) { return; }
     is.getline( str, MAXLEN);
   }
int MSH_Reader::read_mesh (const char * fname, const std::string & wname) inline
Definition at line 30 of file MSH_Reader.h.
References COM_get_window_handle(), COM_new_window(), read_pane_coors(), and read_pane_elems().
Referenced by main().
{
     std::ifstream is( fname);
     if ( is == NULL) {
       std::cerr << "Error: Could not open file " << fname << std::endl;
       exit(-1);
     }
     // Create the window if not yet exist
     int h=COM_get_window_handle(wname.c_str());
     if ( h<=0) COM_new_window( wname.c_str());
     std::cout << "Reading file " << fname << std::endl;
     read_pane_coors( is, wname);
     read_pane_elems( is, wname);
     return 1;
   }
void MSH_Reader::read_pane_coors (std::istream & is, const std::string & wname) inline private
Definition at line 57 of file MSH_Reader.h.
References buf, COM_allocate_array(), COM_assertion_msg, COM_set_size(), get_nextline(), and s.
Referenced by read_mesh().
{
     std::vector<SURF::Point_3<double> >  coors;
     // First, look for number of vertices
     for ( ;;) {
       get_nextline( is, buf);
       std::string s(buf);
       if ( s.find("Vertices",0)!=std::string::npos) break;
     }
     int n=0;
     is >> n; get_nextline(is, buf);
     coors.reserve(n);
     for ( int i=0; i<n; ++i) {
       get_nextline( is, buf);
       SURF::Point_3<double> p;
       std::sscanf( buf, "%lf %lf %lf", &p[0], &p[1], &p[2]);
       coors.push_back( p);
     }
     COM_assertion_msg( n>0, "Did not find any nodes");
     std::cout << "Read in " << n << " nodes" << std::endl;
     COM_set_size( (wname+".nc").c_str(), 1, n);
     SURF::Point_3<double> *p;
     COM_allocate_array( (wname+".nc").c_str(), 1, &(void*&)p);
     std::copy( coors.begin(), coors.end(), p);
   }
void MSH_Reader::read_pane_elems (std::istream & is, const std::string & wname) inline private
Definition at line 92 of file MSH_Reader.h.
References buf, COM_allocate_array(), COM_assertion_msg, COM_set_size(), get_nextline(), and s.
Referenced by read_mesh().
{
     std::vector<SURF::Vector_3<int> >  elems;
     // First, look for number of triangles
     for (;;) {
       get_nextline( is, buf);
       std::string s(buf);
       if ( s.find("Triangles",0)!=std::string::npos) break;
     }
     int n=0;
     is >> n; get_nextline(is, buf);
     elems.reserve(n);
     // When entering this routine, buf[0] should start with 'f'
     for ( int i=0; i<n; ++i) {
       get_nextline( is, buf);
       SURF::Vector_3<int> p;
       std::sscanf( buf, "%d %d %d", &p[0], &p[1], &p[2]);
       elems.push_back( p);
     }
     COM_assertion_msg( n>0, "Did not find any faces");
     std::cout << "Read in " << n << " triangles" << std::endl;
     COM_set_size( (wname+".:t3:").c_str(), 1, n);
     SURF::Vector_3<int> *p;
     COM_allocate_array( (wname+".:t3:").c_str(), 1, &(void*&)p);
     std::copy( elems.begin(), elems.end(), p);
   }
Member Data Documentation
char MSH_Reader::buf[MAXLEN+1] private
Definition at line 128 of file MSH_Reader.h.
Referenced by read_pane_coors(), and read_pane_elems().
The documentation for this class was generated from the following file:
MSH_Reader.h