IMPACT: HeatTransfer_FS Class Reference
HeatTransfer_FS Class Reference
Detailed Description
Definition at line 194 of file transfer_actions.h.
#include <transfer_actions.h>
Public Member Functions
HeatTransfer_FS (FluidAgent *ag, SolidAgent *sag, BurnAgent *bag, const std::string f_qc, const std::string f_qr, const std::string fb_qev, const std::string s_qs)
void init (double t)
void run (double t, double dt, double alpha)
Public Member Functions inherited from InterMeshTransfer
InterMeshTransfer (FluidAgent *fag, SolidAgent *sag, char *name=NULL)
Public Member Functions inherited from Action
Action (void *p=0, const char *name=NULL)
Action (int n, const char **at, int *i=NULL, void *p=0, const char *name=NULL)
Action (int n, const std::string at[], int *i=NULL, void *p=0, const char *name=NULL)
virtual ~Action ()
virtual void declare (Scheduler &)
virtual void finalize ()
virtual const char * name ()
void set_name (const char *name)
virtual void print (FILE *f)
virtual void print_toposort (FILE *f)
virtual void schedule ()
Private Attributes
BurnAgent * bagent
int f_qc_hdl
int f_qr_hdl
int b_qev_hdl
int s_qs_hdl
int s_qc_hdl
int s_qr_hdl
int f_qev_hdl
int s_qev_hdl
int RFC_interpolate
int RFC_transfer
Additional Inherited Members
Protected Types inherited from Action
enum { IN =1, OUT =2, INOUT =3 }
Protected Member Functions inherited from InterMeshTransfer
void load_rocface (const RocmanControl_parameters *param)
Protected Member Functions inherited from Action
int get_dataitem_handle (int i)
int get_dataitem_handle_const (int i)
int get_dataitem_handle (const std::string str)
void set_attr (int n, const std::string at[], int *id=NULL)
void set_attr (int n, const char *at[], int *id=NULL)
void set_io (int n, const int *io)
void set_io (const char *io)
int get_io (int i)
Protected Attributes inherited from InterMeshTransfer
FluidAgent * fagent
SolidAgent * sagent
Protected Attributes inherited from Action
const char * action_name
char ** attr
int * idx
int count
void * usr_ptr
std::vector< int > inout
Constructor & Destructor Documentation
HeatTransfer_FS::HeatTransfer_FS (FluidAgent * ag, SolidAgent * sag, BurnAgent * bag, const std::string f_qc, const std::string f_qr, const std::string fb_qev, const std::string s_qs)
Definition at line 1002 of file transfer_actions.C.
References InterMeshTransfer::fagent, FluidAgent::fluidBufNG, Agent::get_surface_window(), Action::IN, Action::OUT, Agent::register_clone_dataitem(), InterMeshTransfer::sagent, Action::set_attr(), Action::set_io(), and SolidAgent::solidBuf.
                                                              :
                  InterMeshTransfer(fag, sag, "HeatTransfer_FS"), bagent(bag)
 {
   int io[] = {IN, IN, IN, OUT};
   set_io( 4, io);
   std::string.data[4];
  .data[0] = f_qc;
  .data[1] = f_qr;
  .data[2] = b_qev;
  .data[3] = s_qs;
   set_attr(4,.data);
     // temporary buffer for solid
   sagent->register_clone_dataitem( 0, sagent->solidBuf, ".qc_tmp", sagent->get_surface_window(), ".qs");
   sagent->register_clone_dataitem( 0, sagent->solidBuf, ".qr_tmp", sagent->get_surface_window(), ".qs");
   sagent->register_clone_dataitem( 0, sagent->solidBuf, ".qev", sagent->get_surface_window(), ".qs", 0);
   fagent->register_clone_dataitem( 0, fagent->fluidBufNG, ".qev", fagent->get_surface_window(), ".qc", 0);
 }
Member Function Documentation
void HeatTransfer_FS::init (double t) virtual
Reimplemented from Action.
Definition at line 1025 of file transfer_actions.C.
References Action::attr, b_qev_hdl, bagent, cap, COM_assertion_msg, COM_get_array(), COM_get_dataitem_handle(), COM_get_function_handle(), f_qc_hdl, f_qev_hdl, f_qr_hdl, InterMeshTransfer::fagent, FluidAgent::fluidBufNG, Agent::get_comm_rank(), Agent::get_coupling(), Action::get_dataitem_handle(), Coupling::get_rocmancontrol_param(), Agent::get_surface_window(), InterMeshTransfer::load_rocface(), MAN_DEBUG, RFC_interpolate, RFC_transfer, s_qc_hdl, s_qev_hdl, s_qr_hdl, s_qs_hdl, InterMeshTransfer::sagent, and SolidAgent::solidBuf.
{
   f_qc_hdl = get_dataitem_handle( 0);
   int with_qr = COM_get_dataitem_handle( attr[1]) > 0;
   if (with_qr)
     f_qr_hdl = get_dataitem_handle( 1);
   else
     f_qr_hdl = -1;
   b_qev_hdl = get_dataitem_handle( attr[2]);
   s_qs_hdl = get_dataitem_handle( 3);
   s_qc_hdl = get_dataitem_handle( sagent->solidBuf+".qc_tmp");
   s_qr_hdl = get_dataitem_handle( sagent->solidBuf+".qr_tmp");
   f_qev_hdl = get_dataitem_handle( fagent->fluidBufNG+".qev");   // burn
   s_qev_hdl = get_dataitem_handle( sagent->solidBuf+".qev");   // burn
      // TODO:  set qev_flag to signal rocburn
   /*
    COM_new_dataitem( attr.c_str(),'w',COM_INT,1,"");
   */
   int one = 1;
   int qev_flag_hdl = get_dataitem_handle( bagent->get_surface_window()+".qev_flag");   // burn
   //COM_call_function( RocBlas::copy_scalar, &one, &qev_flag_hdl);
   int *vm =NULL;
   int strid, cap;
   COM_get_array((bagent->get_surface_window()+".qev_flag").c_str(), 0, &vm, &strid, &cap);
   COM_assertion_msg(vm!=NULL, "Error: qev_flag!");
   *vm = 1;
   load_rocface(fagent->get_coupling()->get_rocmancontrol_param());
   RFC_transfer = COM_get_function_handle("RFC.least_squares_transfer");
   RFC_interpolate = COM_get_function_handle("RFC.interpolate");
   MAN_DEBUG(2, ("[%d] Rocman: HeatTransfer_FS::init() with t:%e with_qr=%d.\n", fagent->get_comm_rank(), t, with_qr));
 }
void HeatTransfer_FS::run (double t, double dt, double alpha) virtual
Reimplemented from Action.
Definition at line 1061 of file transfer_actions.C.
References RocBlas::add, b_qev_hdl, COM_assertion_msg, COM_call_function(), COM_copy_dataitem(), f_qc_hdl, f_qev_hdl, f_qr_hdl, InterMeshTransfer::fagent, Agent::get_comm_rank(), MAN_DEBUG, RocBlas::neg, NO_SHEER, RFC_transfer, s_qc_hdl, s_qev_hdl, s_qr_hdl, s_qs_hdl, InterMeshTransfer::sagent, SolidAgent::size_ts, RocBlas::sub, and SolidAgent::traction_mode.
{
   MAN_DEBUG(2, ("[%d] Rocman: HeatTransfer_FS::run() with t:%e dt:%e.\n", fagent->get_comm_rank(), t, dt));
   int size_ts = sagent->size_ts;
   int traction_mode = sagent->traction_mode;
   if (traction_mode == NO_SHEER && size_ts == 3) {
     COM_assertion_msg(0, "Not implemented!");
   }
   else if ( traction_mode == NO_SHEER && size_ts == 1) {
     //debug_print(fagent->get_surface_window()+".qc", 2, 0);
     //debug_print(fagent->get_surface_window()+".qr", 2, 0);
     if (f_qr_hdl != -1) {
       COM_call_function( RFC_transfer, &f_qc_hdl, &s_qc_hdl);
       COM_call_function( RFC_transfer, &f_qr_hdl, &s_qr_hdl);
       COM_call_function( RocBlas::add, &s_qc_hdl, &s_qr_hdl, &s_qs_hdl);
     }
     else
       COM_call_function( RFC_transfer, &f_qc_hdl, &s_qs_hdl);
     //debug_print(sagent->solidBuf+".qs", 101, 0, bagent->get_communicator(), "s_qs");
       // add qsource
     if (b_qev_hdl == -1) {
       std::cerr << "Rocman> WARNING: No qev is obtained! " << std::endl;
       // only on burn surface
       COM_call_function( RocBlas::neg, &s_qs_hdl, &s_qs_hdl);
     }
     else {
       //debug_print(bagent->iburn_ng+".qev", 102, 0, bagent->get_communicator(), "b_qev");
         // copy qev from burn to fluid, transfer to solid
       COM_copy_dataitem( f_qev_hdl, b_qev_hdl, 0);
       COM_call_function( RFC_transfer, &f_qev_hdl, &s_qev_hdl);
         // only on burn surface
       COM_call_function( RocBlas::sub, &s_qev_hdl, &s_qs_hdl, &s_qs_hdl);
     }
   }
   else if (size_ts == 1) {
     COM_assertion_msg(0, "If traction mode is with sheer, then solid tractions must be vectors!");
   }
   else {
     COM_call_function( RFC_transfer, &f_qc_hdl, &s_qc_hdl);
     COM_call_function( RFC_transfer, &f_qr_hdl, &s_qr_hdl);
     COM_call_function( RocBlas::add, &s_qc_hdl, &s_qr_hdl, &s_qs_hdl);
   }
 }
Member Data Documentation
int HeatTransfer_FS::b_qev_hdl private
Definition at line 201 of file transfer_actions.h.
Referenced by init(), and run().
BurnAgent* HeatTransfer_FS::bagent private
Definition at line 200 of file transfer_actions.h.
Referenced by init().
int HeatTransfer_FS::f_qc_hdl private
Definition at line 201 of file transfer_actions.h.
Referenced by init(), and run().
int HeatTransfer_FS::f_qev_hdl private
Definition at line 202 of file transfer_actions.h.
Referenced by init(), and run().
int HeatTransfer_FS::f_qr_hdl private
Definition at line 201 of file transfer_actions.h.
Referenced by init(), and run().
int HeatTransfer_FS::RFC_interpolate private
Definition at line 203 of file transfer_actions.h.
Referenced by init().
int HeatTransfer_FS::RFC_transfer private
Definition at line 204 of file transfer_actions.h.
Referenced by init(), and run().
int HeatTransfer_FS::s_qc_hdl private
Definition at line 202 of file transfer_actions.h.
Referenced by init(), and run().
int HeatTransfer_FS::s_qev_hdl private
Definition at line 202 of file transfer_actions.h.
Referenced by init(), and run().
int HeatTransfer_FS::s_qr_hdl private
Definition at line 202 of file transfer_actions.h.
Referenced by init(), and run().
int HeatTransfer_FS::s_qs_hdl private
Definition at line 201 of file transfer_actions.h.
Referenced by init(), and run().
The documentation for this class was generated from the following files:
transfer_actions.h
transfer_actions.C