IMPACT: Vector_3< Type > Class Template Reference
Vector_3< Type > Class Template Reference
Some basic geometric data types.
Detailed Description
template<class Type>
class Vector_3< Type >
Definition at line 37 of file mapbasic.h.
#include <mapbasic.h>
Public Member Functions
Vector_3 ()
Vector_3 (Type t)
Vector_3 (Null_vector)
Vector_3 (Type a, Type b, Type c)
Type & operator[] (const int i)
const Type & operator[] (const int i) const
Type x () const
Type y () const
Type z () const
Vector_3 & operator+= (const Type t)
Assign operators.
Vector_3 & operator+= (const Vector_3 &v)
Vector_3 & operator-= (const Type t)
Vector_3 & operator-= (const Vector_3 &v)
Vector_3 & operator*= (const Type t)
Vector_3 & operator*= (const Vector_3 &v)
Vector_3 & operator/= (const Type t)
Vector_3 & operator/= (const Vector_3 &v)
Vector_3 operator+ (const Type t) const
Arithmatic operators.
Vector_3 operator+ (const Vector_3 &v) const
Vector_3 operator- (const Type t) const
Vector_3 operator- (const Vector_3 &v) const
Vector_3 operator* (const Type t) const
Vector_3 operator/ (const Type t) const
Type operator* (const Vector_3 &v) const
Vector_3 operator- () const
Type squared_norm () const
Type norm () const
Vector_3 & normalize ()
Vector_3 & neg ()
bool operator== (const Vector_3 &p) const
bool operator!= (const Vector_3 &p) const
bool operator< (const Vector_3 &v) const
bool is_null () const
Static Public Member Functions
static Vector_3 cross_product (const Vector_3 &v, const Vector_3 &w)
Protected Attributes
Type _x
Type _y
Type _z
Constructor & Destructor Documentation
template<class Type> Vector_3< Type >::Vector_3 () inline
Definition at line 39 of file mapbasic.h.
Referenced by Vector_3< Real >::cross_product(), Vector_3< Real >::operator*(), Vector_3< Real >::operator+(), Vector_3< Real >::operator-(), and Vector_3< Real >::operator/().
 {}
template<class Type> Vector_3< Type >::Vector_3 (Type t) inline explicit
Definition at line 40 of file mapbasic.h.
 : _x(t), _y(t), _z(t) {}
template<class Type> Vector_3< Type >::Vector_3 (Null_vector) inline
Definition at line 41 of file mapbasic.h.
 : _x(0), _y(0), _z(0) {}
template<class Type> Vector_3< Type >::Vector_3 (Type a, Type b, Type c) inline
Definition at line 42 of file mapbasic.h.
 : _x(a), _y(b), _z(c) {}
Member Function Documentation
template<class Type> static Vector_3 Vector_3< Type >::cross_product (const Vector_3< Type > & v, const Vector_3< Type > & w) inline static
Definition at line 87 of file mapbasic.h.
Referenced by Rocsurf::compute_element_normals(), compute_lbop_weights(), Window_manifold_2::elements_to_nodes(), get_deformed_normal(), Overlay_primitives::get_face_normal(), get_face_volume(), get_normal(), Overlay_primitives::intersect(), Generic_element_2::Jacobian_det(), Overlay_primitives::project_blue_feature(), Overlay_primitives::project_green_feature(), and Generic_element_2::solve().
{
     return Vector_3( v._y * w._z - v._z * w._y ,
                      v._z * w._x - v._x * w._z ,
                      v._x * w._y - v._y * w._x );
   }
template<class Type> bool Vector_3< Type >::is_null () const inline
Definition at line 116 of file mapbasic.h.
 { return _x==0&&_y==0&&_z==0; }
template<class Type> Vector_3& Vector_3< Type >::neg () inline
Definition at line 103 of file mapbasic.h.
                   {
     _x = -_x; _y = -_y; _z = -_z; return *this;
   }
template<class Type> Type Vector_3< Type >::norm () const inline
Definition at line 95 of file mapbasic.h.
Referenced by Rocsurf::compute_edge_lengths(), compute_lbop_weights(), and Window_manifold_2::compute_mcn().
 { return std::sqrt(*this * *this); }
template<class Type> Vector_3& Vector_3< Type >::normalize () inline
Definition at line 97 of file mapbasic.h.
Referenced by Rocsurf::compute_element_normals(), Overlay_primitives::get_face_normal(), and Window_manifold_2::update_bd_normals().
{
     Type s=squared_norm();
     if ( s != Type(0)) { s=std::sqrt(s); _x/=s; _y/=s; _z/=s; }
     return *this;
   }
template<class Type> bool Vector_3< Type >::operator!= (const Vector_3< Type > & p) const inline
Definition at line 109 of file mapbasic.h.
   { return x()!=p.x() || y()!=p.y() || z()!=p.z(); }
template<class Type> Vector_3 Vector_3< Type >::operator* (const Type t) const inline
Definition at line 77 of file mapbasic.h.
   { return Vector_3(_x*t, _y*t, _z*t); }
template<class Type> Type Vector_3< Type >::operator* (const Vector_3< Type > & v) const inline
Definition at line 81 of file mapbasic.h.
   { return _x*v._x + _y*v._y + _z*v._z; }
template<class Type> Vector_3& Vector_3< Type >::operator*= (const Type t) inline
Definition at line 59 of file mapbasic.h.
   { _x*=t; _y*=t; _z*=t; return *this; }
template<class Type> Vector_3& Vector_3< Type >::operator*= (const Vector_3< Type > & v) inline
Definition at line 61 of file mapbasic.h.
   { _x*=v._x; _y*=v._y; _z*=v._z; return *this; }
template<class Type> Vector_3 Vector_3< Type >::operator+ (const Type t) const inline
Definition at line 69 of file mapbasic.h.
   { return Vector_3(_x+t, _y+t, _z+t); }
template<class Type> Vector_3 Vector_3< Type >::operator+ (const Vector_3< Type > & v) const inline
Definition at line 71 of file mapbasic.h.
   { return Vector_3(_x+v._x, _y+v._y, _z+v._z); }
template<class Type> Vector_3& Vector_3< Type >::operator+= (const Type t) inline
Definition at line 51 of file mapbasic.h.
   { _x+=t; _y+=t; _z+=t; return *this; }
template<class Type> Vector_3& Vector_3< Type >::operator+= (const Vector_3< Type > & v) inline
Definition at line 53 of file mapbasic.h.
   { _x+=v._x; _y+=v._y; _z+=v._z; return *this; }
template<class Type> Vector_3 Vector_3< Type >::operator- (const Type t) const inline
Definition at line 73 of file mapbasic.h.
   { return Vector_3(_x-t, _y-t, _z-t); }
template<class Type> Vector_3 Vector_3< Type >::operator- (const Vector_3< Type > & v) const inline
Definition at line 75 of file mapbasic.h.
   { return Vector_3(_x-v._x, _y-v._y, _z-v._z); }
template<class Type> Vector_3 Vector_3< Type >::operator- () const inline
Definition at line 84 of file mapbasic.h.
   { return Vector_3(-_x, -_y, -_z); }
template<class Type> Vector_3& Vector_3< Type >::operator-= (const Type t) inline
Definition at line 55 of file mapbasic.h.
   { _x-=t; _y-=t; _z-=t; return *this; }
template<class Type> Vector_3& Vector_3< Type >::operator-= (const Vector_3< Type > & v) inline
Definition at line 57 of file mapbasic.h.
   { _x-=v._x; _y-=v._y; _z-=v._z; return *this; }
template<class Type> Vector_3 Vector_3< Type >::operator/ (const Type t) const inline
Definition at line 79 of file mapbasic.h.
   { return Vector_3(_x/t, _y/t, _z/t); }
template<class Type> Vector_3& Vector_3< Type >::operator/= (const Type t) inline
Definition at line 63 of file mapbasic.h.
   { _x/=t; _y/=t; _z/=t; return *this; }
template<class Type> Vector_3& Vector_3< Type >::operator/= (const Vector_3< Type > & v) inline
Definition at line 65 of file mapbasic.h.
   { _x/=v._x; _y/=v._y; _z/=v._z; return *this; }
template<class Type> bool Vector_3< Type >::operator< (const Vector_3< Type > & v) const inline
Definition at line 112 of file mapbasic.h.
Referenced by Point_3< T >::operator<().
   { return _x<v._x || _x==v._x && _y<v._y ||
       _x==v._x && _y==v._y && _z<v._z; }
template<class Type> bool Vector_3< Type >::operator== (const Vector_3< Type > & p) const inline
Definition at line 107 of file mapbasic.h.
   { return x()==p.x() && y()==p.y() && z()==p.z(); }
template<class Type> Type& Vector_3< Type >::operator[] (const int i) inline
Definition at line 43 of file mapbasic.h.
 { return (&_x)[i]; }
template<class Type> const Type& Vector_3< Type >::operator[] (const int i) const inline
Definition at line 44 of file mapbasic.h.
 { return (&_x)[i]; }
template<class Type> Type Vector_3< Type >::squared_norm () const inline
Definition at line 93 of file mapbasic.h.
Referenced by Window_manifold_2::elements_to_nodes(), Vector_3< Real >::normalize(), and Generic_element_2::solve().
 { return *this * *this; }
template<class Type> Type Vector_3< Type >::x () const inline
Definition at line 46 of file mapbasic.h.
Referenced by Vector_3< Real >::operator!=(), Point_3< T >::operator+(), Point_3< T >::operator+=(), Point_3< T >::operator-(), Point_3< T >::operator-=(), operator<<(), and Vector_3< Real >::operator==().
 { return _x; }
template<class Type> Type Vector_3< Type >::y () const inline
Definition at line 47 of file mapbasic.h.
Referenced by Vector_3< Real >::operator!=(), Point_3< T >::operator+(), Point_3< T >::operator+=(), Point_3< T >::operator-(), Point_3< T >::operator-=(), and Vector_3< Real >::operator==().
 { return _y; }
template<class Type> Type Vector_3< Type >::z () const inline
Definition at line 48 of file mapbasic.h.
Referenced by Vector_3< Real >::operator!=(), Point_3< T >::operator+(), Point_3< T >::operator+=(), Point_3< T >::operator-(), Point_3< T >::operator-=(), and Vector_3< Real >::operator==().
 { return _z; }
Member Data Documentation
template<class Type> Type Vector_3< Type >::_x protected
Definition at line 118 of file mapbasic.h.
Referenced by Vector_3< Real >::cross_product(), Vector_3< Real >::is_null(), Vector_3< Real >::neg(), Vector_3< Real >::normalize(), Vector_3< Real >::operator*(), Vector_3< Real >::operator*=(), Vector_3< Real >::operator+(), Vector_3< Real >::operator+=(), Vector_3< Real >::operator-(), Vector_3< Real >::operator-=(), Vector_3< Real >::operator/(), Vector_3< Real >::operator/=(), Vector_3< Real >::operator<(), Vector_3< Real >::operator[](), and Vector_3< Real >::x().
template<class Type> Type Vector_3< Type >::_y protected
Definition at line 118 of file mapbasic.h.
Referenced by Vector_3< Real >::cross_product(), Vector_3< Real >::is_null(), Vector_3< Real >::neg(), Vector_3< Real >::normalize(), Vector_3< Real >::operator*(), Vector_3< Real >::operator*=(), Vector_3< Real >::operator+(), Vector_3< Real >::operator+=(), Vector_3< Real >::operator-(), Vector_3< Real >::operator-=(), Vector_3< Real >::operator/(), Vector_3< Real >::operator/=(), Vector_3< Real >::operator<(), and Vector_3< Real >::y().
template<class Type> Type Vector_3< Type >::_z protected
Definition at line 118 of file mapbasic.h.
Referenced by Vector_3< Real >::cross_product(), Vector_3< Real >::is_null(), Vector_3< Real >::neg(), Vector_3< Real >::normalize(), Vector_3< Real >::operator*(), Vector_3< Real >::operator*=(), Vector_3< Real >::operator+(), Vector_3< Real >::operator+=(), Vector_3< Real >::operator-(), Vector_3< Real >::operator-=(), Vector_3< Real >::operator/(), Vector_3< Real >::operator/=(), Vector_3< Real >::operator<(), and Vector_3< Real >::z().
The documentation for this class was generated from the following file:
mapbasic.h