IMPACT: FluidBurnAlone Class Reference
FluidBurnAlone Class Reference
Detailed Description
Definition at line 21 of file builtin_couplings.h.
#include <builtin_couplings.h>
Public Member Functions
FluidBurnAlone (const char *, const char *, MPI_Comm com, Control_parameters *p, const RocmanControl_parameters *mp)
Public Member Functions inherited from Coupling
Coupling (const char *coupl_name, const char *name, Control_parameters *p, const RocmanControl_parameters *mp)
Constructor. Derived class will add actions for the coupling scheme.
Coupling (const char *coupl_name, const char *fluidname, const char *solidname, Control_parameters *p, const RocmanControl_parameters *mp)
Coupling (const char *coupl_name, const char *fluidname, const char *solidname, const char *burnname, Control_parameters *p, const RocmanControl_parameters *mp)
virtual ~Coupling ()
Destructor.
const char * name ()
Agent * add_agent (Agent *)
Add new agent.
void schedule ()
Schedule the top-level actions of the coupling scheme and the actions of the agents.
void init (double t, double dt, int reinit=0)
Invoke initialization of the actions in the scheduler and the agents.
void initialize (int reinit=0)
void finalize ()
Invoke finalization of the actions in the scheduler and the agents.
double run (double t, double dt, int iPredCorr, double zoom)
Invoke the scheduler.
void run_initactions (double t, double dt)
void input (double t)
Invoke input functions of the agents.
int get_ipc () const
int get_max_ipc () const
int initial_start () const
int in_restart () const
int initial_remeshed () const
true if in initialization step and remeshed is true
int new_start (double t) const
void init_convergence (int iPredCorr)
int check_convergence ()
virtual void update_integrals (double currentTime)
virtual void update_distances (double currentTime)
void output_restart_files (double t)
void output_visualization_files (double t)
const Control_parameters * get_control_param ()
const RocmanControl_parameters * get_rocmancontrol_param ()
void read_restart_info ()
void write_restart_info (double CurrentTime, int iStep)
void restart_at_time (double t, int step)
virtual void reload_rocface (const RocmanControl_parameters *param)
void print (const char *fname)
void Interrupt (int *, const char *)
int ProcessInterrupt ()
Protected Attributes
double flm_temp
Protected Attributes inherited from Coupling
std::string coupling_name
vector< std::string > modules
AgentList agents
UserScheduler scheduler
UserScheduler init_scheduler
int comm_rank
int init_started
int restarting
int init_remeshed
int iPredCorr
int maxPredCorr
Control_parameters * param
const RocmanControl_parameters * rocmanparam
std::string restartInfo
int overwrite_integ
std::string integFname
int overwrite_dist
std::string distFname
Additional Inherited Members
Protected Member Functions inherited from Coupling
void callMethod (Scheduler_voidfn1_t fn, double t)
std::string normalize_modname (const char *mod)
Constructor & Destructor Documentation
FluidBurnAlone::FluidBurnAlone (const char * fluidmodule, const char * burnmodule, MPI_Comm com, Control_parameters * p, const RocmanControl_parameters * mp)
Definition at line 181 of file builtin_couplings.C.
References UserScheduler::add_action(), Coupling::add_agent(), Agent::add_bcaction(), Agent::add_bcinitaction(), Agent::add_gmaction(), Agent::add_icaction(), FluidAgent::fluidBufB, FluidAgent::fluidBufNG, Coupling::get_control_param(), Agent::get_coupling(), Agent::get_main_action(), Agent::get_surface_window(), BurnAgent::iburn_ng, Coupling::init_scheduler, Coupling::initial_start(), Coupling::maxPredCorr, RocmanControl_parameters::PROP_fom, FluidAgent::propBuf, FluidAgent::propBufAll, RocmanControl_parameters::rhoc, Coupling::scheduler, and Control_parameters::zoomFactor.
                                                :
             Coupling("FluidBurnAlone", fluidmodule, burnmodule, p, mp)
 {
   maxPredCorr = 1;
   // Create agents
   FluidAgent *fluid_agent = new FluidAgent( this, fluidmodule, fluidmodule, com);
   add_agent( fluid_agent);
   const std::string propBufAll = fluid_agent->propBufAll;
   const std::string fluidBufB = fluid_agent->fluidBufB;
   const std::string fluidBufNG = fluid_agent->fluidBufNG;
   BurnAgent *burn_agent = new BurnAgent( this, "Rocburn", burnmodule, com, fluidBufB);
   add_agent( burn_agent);
   const std::string iburn_ng = burn_agent->iburn_ng;
   const double rhoc = mp->rhoc;
   double zoom = burn_agent->get_coupling()->get_control_param()->zoomFactor;
     // ###########  INITIALIZATION  ############
    //  POST_INIT_FLUID
   if (initial_start()) {
     if (zoom > 0) {
       std::string propBuf = fluid_agent->propBufAll;
       int PROP_fom = mp->PROP_fom;
       if (!PROP_fom) propBuf = fluid_agent->propBuf;
       init_scheduler.add_action( new ComputePconn(fluid_agent,
                                                propBufAll+".mesh",
                                                propBufAll+".pconn",
                                                propBuf+".pmesh"));
     }
       // INIT_INBUFF_FLUID
     init_scheduler.add_action( new BCInitInvoker( fluid_agent));
     init_scheduler.add_action( new Reset_du_alp( fluid_agent));
     init_scheduler.add_action( new BCInvoker(fluid_agent, 1));
     init_scheduler.add_action( new BCInvoker(fluid_agent, 2));
   }
     // ###########  BURN  ############
 //RAF  if (initial_start()) {
   if (initial_start()) {
     burn_agent->add_icaction( new BCInitInvoker(burn_agent));
       // UPDATE_INBUFF_BC_BURN called in POST_INIT_BURN
     burn_agent->add_icaction( new BCInvoker(burn_agent));
     burn_agent->add_icaction( new ComputeFaceCenters(burn_agent,
                                                      iburn_ng+".nc",
                                                      iburn_ng+".centers",
                                                      iburn_ng+".normals"));
   }
     // POST_INIT_BURN and INIT_BUFF_BURN
     // INIT_INBUFF_BURN
   burn_agent->add_bcinitaction( new CopyBurnFromParentMesh(burn_agent, fluid_agent));
   burn_agent->add_bcinitaction( new SetValueDouble(iburn_ng+".rhos", rhoc));
   burn_agent->add_bcaction( new Extrapolate_Linear(burn_agent, fluid_agent,
                                    iburn_ng+".pf"));
   burn_agent->add_bcaction( new Extrapolate_Central(burn_agent, fluid_agent,
                                    iburn_ng+".qc", "_alp", 1));
   burn_agent->add_bcaction( new Extrapolate_Central(burn_agent, fluid_agent,
                                    iburn_ng+".qr", "_alp", 1));
   burn_agent->add_bcaction( new Extrapolate_Linear(burn_agent, fluid_agent,
                                    iburn_ng+".Tf", "_alp", 1));
   burn_agent->add_bcaction( new Extrapolate_Linear(burn_agent, fluid_agent,
                                    iburn_ng+".Tv", "_alp", 1));
   burn_agent->add_bcaction( new Extrapolate_Linear(burn_agent, fluid_agent,
                                    iburn_ng+".dn", "_alp", 1));
   burn_agent->add_bcaction( new Extrapolate_Linear(burn_agent, burn_agent,
                                    iburn_ng+".rhos", "_alp", 1));
     // burn main Physics routine
   scheduler.add_action( burn_agent->get_main_action());
     // ###########  FLUID  ############
     // INIT_INBUFF_FLUID
 //  fluid_agent->add_bcinitaction( new DummyPrint(burn_agent, NULL, fluid_agent, "fluid"));
   fluid_agent->add_bcinitaction( new SetZero( propBufAll+".vm"));
   fluid_agent->add_bcinitaction( new FluidPropagateSurface( fluid_agent,
                                    burn_agent,
                                    iburn_ng+".rb", propBufAll+".vm", zoom));
   fluid_agent->add_bcinitaction( new CopyBflagFromBurn( burn_agent));
   fluid_agent->add_bcinitaction( new MassTransfer( fluid_agent, burn_agent,
                                    iburn_ng+".rhos", iburn_ng+".rb",
                                    fluidBufNG+".mdot"));
   // UPDATE_INBUFF_BC_FLUID
   // Level-1 boundary condition:
   fluid_agent->add_bcaction( new Interpolate_Linear( burn_agent, burn_agent,
                                    iburn_ng+".Tflm"), 1);
   // Level-2 boundary condition
   fluid_agent->add_bcaction( new Interpolate_Central( fluid_agent, fluid_agent,
                                    fluidBufB+".mdot"), 2);
   //fluid_agent->add_bcaction( new DummyPrint(burn_agent, NULL, fluid_agent, "MDOT"), 2);
   fluid_agent->add_bcaction( new Interpolate_Central( burn_agent, burn_agent,
                                    iburn_ng+".rb"), 2);
   fluid_agent->add_bcaction( new ZoomInterface( fluid_agent, burn_agent,
                                      fluidBufB+".mdot_alp", zoom), 2);
   fluid_agent->add_bcaction( new SetZero( fluidBufNG+".rhofvf_alp"), 2);
   fluid_agent->add_bcaction( new ComputeBurnPane( fluid_agent, burn_agent, NULL,
                                      fluidBufB+".mdot_alp",
                                      fluidBufB+".rhofvf_alp",
                                      zoom), 2);
     // UPDATE_INBUFF_GM_FLUID()
   fluid_agent->add_gmaction( new ComputeMeshMotion( fluid_agent,
                                     propBufAll+".vm",
                                     fluid_agent->get_surface_window()+".du_alp",
                                     zoom));
   // Create and register actions
   scheduler.add_action( fluid_agent->get_main_action());
 }
Member Data Documentation
double FluidBurnAlone::flm_temp protected
Definition at line 26 of file builtin_couplings.h.
The documentation for this class was generated from the following files:
builtin_couplings.h
builtin_couplings.C