IMPACT: InterpolateBase Class Reference
InterpolateBase Class Reference abstract
Detailed Description
Definition at line 14 of file Interpolate.h.
#include <Interpolate.h>
Public Member Functions
InterpolateBase (Agent *ag, Agent *bkag, int cond=0)
virtual void init (double t)
virtual void run (double t, double dt, double alpha)=0
void backup ()
Public Member Functions inherited from Action
Action (void *p=0, const char *name=NULL)
Action (int n, const char **at, int *i=NULL, void *p=0, const char *name=NULL)
Action (int n, const std::string at[], int *i=NULL, void *p=0, const char *name=NULL)
virtual ~Action ()
virtual void declare (Scheduler &)
virtual void finalize ()
virtual const char * name ()
void set_name (const char *name)
virtual void print (FILE *f)
virtual void print_toposort (FILE *f)
virtual void schedule ()
Protected Member Functions
void extrapolate_Linear (double dt, double dt_old, double time_old, int a_old, double time_new, int a_new, double time_out, int a_out, int a_gra=-100)
Protected Member Functions inherited from Action
int get_dataitem_handle (int i)
int get_dataitem_handle_const (int i)
int get_dataitem_handle (const std::string str)
void set_attr (int n, const std::string at[], int *id=NULL)
void set_attr (int n, const char *at[], int *id=NULL)
void set_io (int n, const int *io)
void set_io (const char *io)
int get_io (int i)
Protected Attributes
Agent * agent
Agent * bkagent
int attr_hdls [4]
int bkup_hdls [3]
int conditional
int on
Protected Attributes inherited from Action
const char * action_name
char ** attr
int * idx
int count
void * usr_ptr
std::vector< int > inout
Additional Inherited Members
Protected Types inherited from Action
enum { IN =1, OUT =2, INOUT =3 }
Constructor & Destructor Documentation
InterpolateBase::InterpolateBase (Agent * ag, Agent * bkag, int cond = 0)
Definition at line 13 of file Interpolate.C.
References attr_hdls, bkagent, bkup_hdls, on, and Agent::register_interpolate().
                                                                 :
              Action(0, (const char**)NULL, NULL, NULL, "InterpolateBase"),
              agent(ag), bkagent(bkag), conditional(cond)
 {
   // register to Agent for create_dataitem() and backup() callback
   if (bkagent) bkagent->register_interpolate(this);
   int i;
   for (i=0; i<4; i++) attr_hdls[i] = -1;
   for (i=0; i<3; i++) bkup_hdls[i] = -1;
   on = 1;
 }
Member Function Documentation
void InterpolateBase::backup ()
Definition at line 54 of file Interpolate.C.
References agent, Action::attr, bkup_hdls, COM_call_function(), RocBlas::copy, RocBlas::copy_scalar, RocBlas::div_scalar, Agent::get_old_dt(), MAN_DEBUG, and RocBlas::sub.
 {
   MAN_DEBUG(1, ("Rocman: InterpolateBase::backup (%s) called with dt_old:%e.\n", attr[0], agent->get_old_dt()));
   // BACKUP() in "man_basic.f90"
   if (bkup_hdls[0] > 0 && bkup_hdls[1] > 0) {
     // Compute gradient
     if ( bkup_hdls[2] > 0) {
       double dt_old = agent->get_old_dt();
       if (dt_old > 0.) {
         COM_call_function( RocBlas::sub, &bkup_hdls[0], &bkup_hdls[1], &bkup_hdls[2]);
         COM_call_function( RocBlas::div_scalar, &bkup_hdls[2], &dt_old, &bkup_hdls[2]);
       }
       else {
         double v = 0.0;
         COM_call_function( RocBlas::copy_scalar, &v, &bkup_hdls[2]);
       }
     }
     COM_call_function( RocBlas::copy, &bkup_hdls[0], &bkup_hdls[1]);
   }
 }
void InterpolateBase::extrapolate_Linear (double dt, double dt_old, double time_old, int a_old, double time_new, int a_new, double time_out, int a_out, int a_gra = -100) protected
Definition at line 77 of file Interpolate.C.
References RocBlas::axpy_scalar, COM_assertion_msg, COM_call_function(), RocBlas::copy, RocBlas::div_scalar, RocBlas::limit1, and RocBlas::sub.
Referenced by Extrapolate_Linear::run(), Extrapolate_Central::run(), Interpolate_Linear::run(), and Interpolate_Central::run().
 {
   //printf("extrapolate_Linear: %f %d %f %d %f %d %d\n", time_old, a_old, time_new, a_new, time_out, a_out, a_grad);
   if (time_out == time_new) {
     COM_call_function( RocBlas::copy, &a_new, &a_out);
   }
   else if (a_old <= 0) {
     printf("ROCMAN Error: Could not find the old dataitem correspond to the dataitem with handle %d\n", a_out);
     COM_assertion_msg(0, "ERROR: Abort!");
   }
   else if (time_out == time_old) {
     COM_call_function( RocBlas::copy, &a_old, &a_out);
   }
   else {
       // See the interpolation section in developers' guide for the algorithm
     COM_call_function( RocBlas::sub, &a_new, &a_old, &a_out);
     double a;
     if (time_old == 0.)
       a = time_out-1.;
     else if (time_old == -0.5) {
       if (a_grad != -100 && a_grad>0) {
         double time = (dt_old+dt)/2.0;
         COM_call_function( RocBlas::div_scalar, &a_out, &time, &a_out);
         COM_call_function( RocBlas::limit1, &a_grad, &a_out, &a_out);
         a = (time_out - 0.5)*dt;
       }
       else
         a = 2.*(time_out - 0.5)*dt/(dt_old+dt);
     }
     else if (time_old == -1) {
       COM_assertion_msg(0, "ERROR: Abort!");
     }
     else  {
       printf("ROCMAN Error: Unsupported interpolation mode with old time stamp %f\n", time_old);
       COM_assertion_msg(0, "ERROR: Abort!");
     }
     COM_call_function( RocBlas::axpy_scalar, &a, &a_out, &a_new, &a_out);
   }
 }
void InterpolateBase::init (double t) virtual
Reimplemented from Action.
Reimplemented in Extrapolate_Central, and Extrapolate_Linear.
Definition at line 26 of file Interpolate.C.
References Action::attr, attr_hdls, bkup_hdls, COM_assertion_msg, COM_call_function(), COM_get_dataitem_handle(), COM_get_dataitem_handle_const(), RocBlas::copy_scalar, Action::get_dataitem_handle(), Action::get_dataitem_handle_const(), Action::get_io(), MAN_DEBUG, Action::name(), and Action::OUT.
Referenced by Extrapolate_Linear::init(), and Extrapolate_Central::init().
 {
   MAN_DEBUG(2, ("%s::init called.\n", name()));
   // INIT_INTERP_HANDLES() in "man_basic.f90"
   attr_hdls[0] = get_dataitem_handle(0);
   attr_hdls[1] = COM_get_dataitem_handle_const(attr[1]);    // old
   attr_hdls[2] = COM_get_dataitem_handle(attr[2]);          // alp
   attr_hdls[3] = COM_get_dataitem_handle(attr[3]);          // grad
   for (int i=0; i<4; i++) {
       // init to 0
     if (get_io(i) == OUT) {
       double zero = 0.0;
       COM_call_function( RocBlas::copy_scalar, &zero, &attr_hdls[i]);
     }
   }
   if ( attr_hdls[1] <= 0 && attr_hdls[2] <= 0)
        std::cout << "ROCMAN Warning: Could not find dataitem " << attr[2] << std::endl;
   else if (attr_hdls[2] <= 0) {
        std::cout << "ROCMAN Error: Could not find dataitem " << attr[2] << std::endl;
        COM_assertion_msg(0, "ERROR: Abort!");
   }
   // backup handles
   bkup_hdls[0] = get_dataitem_handle_const(0);
   bkup_hdls[1] = get_dataitem_handle(1);   // old
   bkup_hdls[2] = COM_get_dataitem_handle(attr[3]);   // grad
 }
virtual void InterpolateBase::run (double t, double dt, double alpha) pure virtual
Reimplemented from Action.
Implemented in Interpolate_Central, Interpolate_Constant, Interpolate_Linear, Extrapolate_Central, and Extrapolate_Linear.
Member Data Documentation
Agent* InterpolateBase::agent protected
Definition at line 25 of file Interpolate.h.
Referenced by backup(), Interpolate_Constant::Interpolate_Constant(), Extrapolate_Linear::run(), Extrapolate_Central::run(), Interpolate_Linear::run(), and Interpolate_Central::run().
int InterpolateBase::attr_hdls[4] protected
Definition at line 27 of file Interpolate.h.
Referenced by init(), Extrapolate_Linear::init(), Extrapolate_Central::init(), InterpolateBase(), Extrapolate_Linear::run(), Extrapolate_Central::run(), Interpolate_Linear::run(), Interpolate_Constant::run(), and Interpolate_Central::run().
Agent* InterpolateBase::bkagent protected
Definition at line 26 of file Interpolate.h.
Referenced by InterpolateBase().
int InterpolateBase::bkup_hdls[3] protected
Definition at line 28 of file Interpolate.h.
Referenced by backup(), init(), and InterpolateBase().
int InterpolateBase::conditional protected
Definition at line 29 of file Interpolate.h.
Referenced by Extrapolate_Linear::init(), and Extrapolate_Central::init().
int InterpolateBase::on protected
Definition at line 30 of file Interpolate.h.
Referenced by InterpolateBase().
The documentation for this class was generated from the following files:
Interpolate.h
Interpolate.C