IMPACT: LoadTransfer_FS Class Reference
LoadTransfer_FS Class Reference
Detailed Description
Definition at line 28 of file transfer_actions.h.
#include <transfer_actions.h>
Public Member Functions
LoadTransfer_FS (FluidAgent *fag, SolidAgent *sag, const std::string f_ts, const std::string s_ts, const std::string s_pf)
void init (double t)
void run (double t, double dt, double alpha)
Public Member Functions inherited from InterMeshTransfer
InterMeshTransfer (FluidAgent *fag, SolidAgent *sag, char *name=NULL)
Public Member Functions inherited from Action
Action (void *p=0, const char *name=NULL)
Action (int n, const char **at, int *i=NULL, void *p=0, const char *name=NULL)
Action (int n, const std::string at[], int *i=NULL, void *p=0, const char *name=NULL)
virtual ~Action ()
virtual void declare (Scheduler &)
virtual void finalize ()
virtual const char * name ()
void set_name (const char *name)
virtual void print (FILE *f)
virtual void print_toposort (FILE *f)
virtual void schedule ()
Private Attributes
int traction_mode
int size_ts
std::string f_ts_str
std::string s_ts_str
std::string s_pf_str
int f_tf_hdl
int f_ts_hdl
int s_ts_hdl
int s_pf_hdl
int f_pf_hdl
int RFC_transfer
int SURF_compute_face_normals
Additional Inherited Members
Protected Types inherited from Action
enum { IN =1, OUT =2, INOUT =3 }
Protected Member Functions inherited from InterMeshTransfer
void load_rocface (const RocmanControl_parameters *param)
Protected Member Functions inherited from Action
int get_dataitem_handle (int i)
int get_dataitem_handle_const (int i)
int get_dataitem_handle (const std::string str)
void set_attr (int n, const std::string at[], int *id=NULL)
void set_attr (int n, const char *at[], int *id=NULL)
void set_io (int n, const int *io)
void set_io (const char *io)
int get_io (int i)
Protected Attributes inherited from InterMeshTransfer
FluidAgent * fagent
SolidAgent * sagent
Protected Attributes inherited from Action
const char * action_name
char ** attr
int * idx
int count
void * usr_ptr
std::vector< int > inout
Constructor & Destructor Documentation
LoadTransfer_FS::LoadTransfer_FS (FluidAgent * fag, SolidAgent * sag, const std::string f_ts, const std::string s_ts, const std::string s_pf) explicit
Definition at line 83 of file transfer_actions.C.
References COM_assertion_msg, COM_DOUBLE, IMPACT::ExampleProgram::f(), f_ts_str, InterMeshTransfer::fagent, Agent::get_coupling(), Coupling::get_rocmancontrol_param(), Agent::get_surface_window(), Action::IN, NO_SHEER, Action::OUT, Agent::register_clone_dataitem(), Agent::register_new_dataitem(), InterMeshTransfer::sagent, Action::set_attr(), Action::set_io(), SolidAgent::solidBufBase, traction_mode, and RocmanControl_parameters::traction_mode.
                                                         :
     InterMeshTransfer(fag, sag, "LoadTransfer_FS"),
     f_ts_str(f_ts), s_ts_str(s_ts), s_pf_str(s_pf)
 {
   int io[] = {IN, IN, OUT};
   set_io( 3, io);
   std::string.data[3];
  .data[0] = f_ts;
  .data[1] = s_ts;
  .data[2] = s_pf;
   set_attr(3,.data);
   traction_mode = fagent->get_coupling()->get_rocmancontrol_param()->traction_mode;
   // create_dataitem
   // for SolidAgent ??????????????????
 //  if (traction_mode == NO_SHEER && size_ts == 3) {
     sagent->register_new_dataitem( sagent->solidBufBase, ".pf", 'e', COM_DOUBLE, 1, "Pa");
 //  }
   // for FluidAgent
   std::string::size_type pos = f_ts_str.find( ".");
   COM_assertion_msg(pos!=std::string::npos, "LoadTransfer_FS failed!");
   std::string f = f_ts_str.substr( 0, pos);
   std::string ts = f_ts_str.substr( pos, f_ts_str.size());
   if (traction_mode == NO_SHEER)  {
     fagent->register_clone_dataitem( 0, f, ts, fagent->get_surface_window(), ".pf");
   }
   else
     fagent->register_clone_dataitem( 0, f, ts, fagent->get_surface_window(), ".tf");
 }
Member Function Documentation
void LoadTransfer_FS::init (double t) virtual
Reimplemented from Action.
Definition at line 120 of file transfer_actions.C.
References COM_assertion_msg, COM_get_dataitem(), COM_get_dataitem_handle_const(), COM_get_function_handle(), f_pf_hdl, f_tf_hdl, f_ts_hdl, InterMeshTransfer::fagent, FluidAgent::fluidBufNG, Agent::get_coupling(), Action::get_dataitem_handle(), Coupling::get_rocmancontrol_param(), InterMeshTransfer::load_rocface(), load_rocsurf(), MAN_DEBUG, NO_SHEER, RFC_transfer, s_pf_hdl, s_ts_hdl, InterMeshTransfer::sagent, size_ts, SolidAgent::solidBufBase, SURF_compute_face_normals, and traction_mode.
{
   // find out size_ts ???
   int dummy;
   std::string unit;
   char loc;
   COM_get_dataitem( sagent->solidBufBase+".ts", &loc, &dummy, &size_ts, &unit);
   if (size_ts == 1 && traction_mode != NO_SHEER) {
     COM_assertion_msg(0, "If traction mode is with sheer, then solid tractions must be vectors!");
     MPI_Abort(MPI_COMM_WORLD, -1);
   }
   load_rocface(fagent->get_coupling()->get_rocmancontrol_param());
   // for SolidAgent
   f_ts_hdl = get_dataitem_handle(0);
   s_ts_hdl = get_dataitem_handle(1);
   if (traction_mode == NO_SHEER && size_ts == 3)
     s_pf_hdl = get_dataitem_handle(2);
   else
     s_pf_hdl = -1;
   f_tf_hdl = COM_get_dataitem_handle_const( fagent->fluidBufNG+".tf");
   f_pf_hdl = COM_get_dataitem_handle_const( fagent->fluidBufNG+".pf");
   RFC_transfer = COM_get_function_handle("RFC.least_squares_transfer");
   load_rocsurf();
   SURF_compute_face_normals = COM_get_function_handle( "SURF.compute_element_normals");
   MAN_DEBUG(2, ("LoadTransfer_FS::init() called - traction_mode: %d size_ts: %d.\n", traction_mode, size_ts));
 }
void LoadTransfer_FS::run (double t, double dt, double alpha) virtual
Reimplemented from Action.
Definition at line 152 of file transfer_actions.C.
References COM_assertion_msg, COM_call_function(), RocBlas::copy, f_pf_hdl, f_tf_hdl, f_ts_hdl, MAN_DEBUG, RocBlas::mul, RocBlas::neg, NO_SHEER, RFC_transfer, s_pf_hdl, s_ts_hdl, size_ts, SURF_compute_face_normals, and traction_mode.
{
   MAN_DEBUG(2, ("Rocman: LoadTransfer_FS::run() with t:%e dt:%e.\n", t, dt));
   // ts = tf + ( mdot*Vs
   // part 1  (POST_UPDATE_FLUID in fluid_agent.f90)
   if (traction_mode != NO_SHEER) {
     COM_call_function( RocBlas::copy, &f_tf_hdl, &f_ts_hdl);
   }
   else {   // ts is a scalar
     COM_call_function( RocBlas::copy, &f_pf_hdl, &f_ts_hdl);
   }
   // part 2  (solid_agent.f90 INIT_INBUFF_SOLID())
   if (traction_mode == NO_SHEER && size_ts == 3) {
     COM_call_function( RFC_transfer, &f_ts_hdl, &s_pf_hdl);
     COM_call_function( SURF_compute_face_normals, &s_ts_hdl);
     COM_call_function( RocBlas::mul, &s_ts_hdl, &s_pf_hdl, &s_ts_hdl);
     COM_call_function( RocBlas::neg, &s_ts_hdl, &s_ts_hdl);
   }
   else if ( traction_mode == NO_SHEER && size_ts == 1) {
     COM_call_function( RFC_transfer, &f_ts_hdl, &s_ts_hdl);
   }
   else if (size_ts == 1) {
     COM_assertion_msg(0, "ERROR: NOT IMPLEMENTED!");
   }
   else {
     COM_assertion_msg(0, "ERROR: NOT IMPLEMENTED!");
   }
 }
Member Data Documentation
int LoadTransfer_FS::f_pf_hdl private
Definition at line 38 of file transfer_actions.h.
Referenced by init(), and run().
int LoadTransfer_FS::f_tf_hdl private
Definition at line 37 of file transfer_actions.h.
Referenced by init(), and run().
int LoadTransfer_FS::f_ts_hdl private
Definition at line 37 of file transfer_actions.h.
Referenced by init(), and run().
std::string LoadTransfer_FS::f_ts_str private
Definition at line 36 of file transfer_actions.h.
Referenced by LoadTransfer_FS().
int LoadTransfer_FS::RFC_transfer private
Definition at line 39 of file transfer_actions.h.
Referenced by init(), and run().
int LoadTransfer_FS::s_pf_hdl private
Definition at line 37 of file transfer_actions.h.
Referenced by init(), and run().
std::string LoadTransfer_FS::s_pf_str private
Definition at line 36 of file transfer_actions.h.
int LoadTransfer_FS::s_ts_hdl private
Definition at line 37 of file transfer_actions.h.
Referenced by init(), and run().
std::string LoadTransfer_FS::s_ts_str private
Definition at line 36 of file transfer_actions.h.
int LoadTransfer_FS::size_ts private
Definition at line 35 of file transfer_actions.h.
Referenced by init(), and run().
int LoadTransfer_FS::SURF_compute_face_normals private
Definition at line 40 of file transfer_actions.h.
Referenced by init(), and run().
int LoadTransfer_FS::traction_mode private
Definition at line 34 of file transfer_actions.h.
Referenced by init(), LoadTransfer_FS(), and run().
The documentation for this class was generated from the following files:
transfer_actions.h
transfer_actions.C