IMPACT: SolverUtils::Mesh::Connectivity Class Reference
SolverUtils::Mesh::Connectivity Class Reference
General connectivity object.
Detailed Description
The Connectivity is a very useful object which allows the description of adjacency of many types of things. Currently the most obvious is describing the connectivity of mesh cells.
Definition at line 351 of file Mesh.H.
#include <Mesh.H>
Public Member Functions
Connectivity ()
Connectivity (unsigned int N)
void Resize (unsigned int N=0)
~Connectivity ()
std::vector< Mesh::IndexType > & Element (Mesh::IndexType n)
std::vector< Mesh::IndexType > Element (Mesh::IndexType n) const
Mesh::IndexType & Node (Mesh::IndexType e, Mesh::IndexType n)
Mesh::IndexType Node (Mesh::IndexType e, Mesh::IndexType n) const
Mesh::IndexType Nelem () const
Mesh::IndexType Esize (Mesh::IndexType n) const
void AddElement (const std::vector< Mesh::IndexType > &elem)
void AddElements (Mesh::IndexType nielem, Mesh::IndexType nnpe, const std::vector< Mesh::IndexType > &elem)
void AddElement ()
void AddElement (Mesh::IndexType a, Mesh::IndexType b, Mesh::IndexType c)
void AddElement (Mesh::IndexType a, Mesh::IndexType b, Mesh::IndexType c, Mesh::IndexType d)
void AddElement (Mesh::IndexType a, Mesh::IndexType b, Mesh::IndexType c, Mesh::IndexType d, Mesh::IndexType e)
void AddElement (Mesh::IndexType a, Mesh::IndexType b, Mesh::IndexType c, Mesh::IndexType d, Mesh::IndexType e, Mesh::IndexType f)
void AddElement (Mesh::IndexType a, Mesh::IndexType b, Mesh::IndexType c, Mesh::IndexType d, Mesh::IndexType e, Mesh::IndexType f, Mesh::IndexType g, Mesh::IndexType h)
void Sync ()
void ShrinkWrap ()
void Truncate ()
void destroy ()
void SyncSizes ()
void DestroySizes ()
void Inverse (Connectivity &, Mesh::IndexType nnodes=0) const
void InverseDegenerate (Connectivity &, Mesh::IndexType nnodes=0) const
void GetNeighborhood (NeighborHood &, const Connectivity &dc)
void GetNeighborhood (Connectivity &, Connectivity &dc, bool exclude_self=true, bool sortit=false)
void GetAdjacent (Connectivity &rl, Connectivity &dc, Mesh::IndexType n=0, bool sortit=false)
void graph_mode (Mesh::IndexType offset=0)
void matrix_mode (Mesh::IndexType offset=0)
void BuildFaceConnectivity (Connectivity &fcon, Connectivity &ef, std::vector< Mesh::SymbolicFace > &sf, Connectivity &dc) const
template<typename T >
void Flatten (std::vector< T > &outcon) const
void BreadthFirstRenumber (std::vector< Mesh::IndexType > &remap)
void ElementsOn (std::vector< Mesh::IndexType > &nodes, Connectivity &dc, std::vector< Mesh::IndexType > &subset)
Private Attributes
Mesh::IndexType _nelem
std::vector< Mesh::IndexType > _sizes
Friends
std::ostream & operator<< (std::ostream &oSt, const Connectivity &ec)
std::istream & operator>> (std::istream &iSt, Connectivity &ec)
Constructor & Destructor Documentation
Connectivity::Connectivity ()
Definition at line 305 of file Mesh.C.
                                    : std::vector<std::vector<Mesh::IndexType> >()
     {
       this ->_nelem = 0;
       this->resize(0);
       std::vector<std::vector<Mesh::IndexType> >(*this).swap(*this);
     };
Connectivity::Connectivity (unsigned int N)
Definition at line 312 of file Mesh.C.
                                                  : std::vector<std::vector<Mesh::IndexType> >(N)
     {
       std::vector<std::vector<Mesh::IndexType> >(*this).swap(*this);
     };
Connectivity::~Connectivity ()
Definition at line 317 of file Mesh.C.
 { destroy(); };
Member Function Documentation
void Connectivity::AddElement (const std::vector< Mesh::IndexType > & elem)
Definition at line 318 of file Mesh.C.
Referenced by SolverUtils::Mesh::BSExtent< T >::CreateUnstructuredMesh(), SolverUtils::PaneToUnstructuredMesh(), SolverUtils::Mesh::ReadWRLFromStream(), SolverUtils::Mesh::Skin(), SolverUtils::SurfaceMeshToPane(), and SolverUtils::VolumeMeshToPane().
     {
       _nelem++;
       this->push_back(elem);
     };
void Connectivity::AddElement ()
Definition at line 334 of file Mesh.C.
     {
       _nelem++;
       std::vector<Mesh::IndexType> a;
       this->push_back(a);
     };
void Connectivity::AddElement (Mesh::IndexType a, Mesh::IndexType b, Mesh::IndexType c)
Definition at line 340 of file Mesh.C.
     {
       _nelem++;
       std::vector<Mesh::IndexType> elem;
       elem.push_back(a);
       elem.push_back(b);
       elem.push_back(c);
       this->push_back(elem);
     };
void Connectivity::AddElement (Mesh::IndexType a, Mesh::IndexType b, Mesh::IndexType c, Mesh::IndexType d)
Definition at line 349 of file Mesh.C.
     {
       _nelem++;
       std::vector<Mesh::IndexType> elem;
       elem.push_back(a);
       elem.push_back(b);
       elem.push_back(c);
       elem.push_back(d);
       this->push_back(elem);
     };
void Connectivity::AddElement (Mesh::IndexType a, Mesh::IndexType b, Mesh::IndexType c, Mesh::IndexType d, Mesh::IndexType e)
Definition at line 359 of file Mesh.C.
     {
       _nelem++;
       std::vector<Mesh::IndexType> elem;
       elem.push_back(a);
       elem.push_back(b);
       elem.push_back(c);
       elem.push_back(d);
       elem.push_back(e);
       this->push_back(elem);
     };
void Connectivity::AddElement (Mesh::IndexType a, Mesh::IndexType b, Mesh::IndexType c, Mesh::IndexType d, Mesh::IndexType e, Mesh::IndexType f)
Definition at line 371 of file Mesh.C.
     {
       _nelem++;
       std::vector<Mesh::IndexType> elem;
       elem.push_back(a);
       elem.push_back(b);
       elem.push_back(c);
       elem.push_back(d);
       elem.push_back(e);
       elem.push_back(f);
       this->push_back(elem);
     };
void Connectivity::AddElement (Mesh::IndexType a, Mesh::IndexType b, Mesh::IndexType c, Mesh::IndexType d, Mesh::IndexType e, Mesh::IndexType f, Mesh::IndexType g, Mesh::IndexType h)
Definition at line 384 of file Mesh.C.
     {
       _nelem++;
       std::vector<Mesh::IndexType> elem;
       elem.push_back(a);
       elem.push_back(b);
       elem.push_back(c);
       elem.push_back(d);
       elem.push_back(e);
       elem.push_back(f);
       elem.push_back(g);
       elem.push_back(h);
       this->push_back(elem);
     };
void Connectivity::AddElements (Mesh::IndexType nielem, Mesh::IndexType nnpe, const std::vector< Mesh::IndexType > & elem)
Definition at line 323 of file Mesh.C.
     {
       std::vector<Mesh::IndexType>::const_iterator ei = elem.begin();
       for(int i = 0;i < nielem;i++){
         std::vector<Mesh::IndexType> inelem(nnpe,0);
         for(int j = 0;j < nnpe;j++)
           inelem[j] = *ei++;
         this->AddElement(inelem);
       }
     };
void Connectivity::BreadthFirstRenumber (std::vector< Mesh::IndexType > & remap)
Definition at line 813 of file Mesh.C.
References _nelem.
     {
       remap.resize(_nelem,0);
       Mesh::IndexType renumber = 1;
       for(Mesh::IndexType i = 0;i < _nelem && renumber <= _nelem;i++){
         //    while(renumber <= _nelem){
         if(remap[i] == 0){
           remap[i] = renumber++;
           std::list<Mesh::IndexType> processing_queue;
           std::vector<Mesh::IndexType>::iterator ni = (*this)[i].begin();
           while(ni != (*this)[i].end()){
             Mesh::IndexType index = *ni++ - 1;
             if(remap[index] == 0){
               processing_queue.push_back(index);
               remap[index] = renumber++;
             }
           }
           std::list<Mesh::IndexType>::iterator pqi = processing_queue.begin();
           while(pqi != processing_queue.end()){
             Mesh::IndexType index = *pqi;
             std::vector<Mesh::IndexType>::iterator ini = (*this)[index].begin();
             while(ini != (*this)[index].end()){
               Mesh::IndexType iindex = *ini++ - 1;
               if(remap[iindex] == 0){
                 processing_queue.push_back(iindex);
                 remap[iindex] = renumber++;
               }
             }
             pqi++;
           }
         }
       }
       assert((renumber == (_nelem+1)));
     };
void Connectivity::BuildFaceConnectivity (Connectivity & fcon, Connectivity & ef, std::vector< Mesh::SymbolicFace > & sf, Connectivity & dc) const
Definition at line 553 of file Mesh.C.
References Esize(), SolverUtils::Mesh::GenericElement::get_face_connectivities(), Nelem(), SolverUtils::Mesh::GenericElement::nfaces(), Resize(), Sync(), and SyncSizes().
Referenced by SolverUtils::Mesh::Skin().
     {
       //    this->Sync();
       //    this->SyncSizes();
       ef.Resize(this->Nelem());
       Mesh::IndexType number_of_elements = this->Nelem();
       Mesh::IndexType nface_estimate = static_cast<Mesh::IndexType>(2.2 * number_of_elements);
       fcon.Resize(0);
       fcon.reserve(nface_estimate);
       sf.reserve(nface_estimate);
       Mesh::IndexType number_of_faces = 0;
       std::vector<Mesh::Connectivity> all_face_conn;
       all_face_conn.resize(this->Nelem());
       //    std::vector<Mesh::IndexType> element_nfaces;
       //    element_nfaces.resize(this->Nelem());
       // This loop sizes the C[F] array (i.e. for each cell, which faces)
       // They're init'd to 0 so that we can tell which faces have been processed
       for(Mesh::IndexType element_being_processed = 1;
           element_being_processed <= number_of_elements;
           element_being_processed++)
         {
           Mesh::IndexType index = element_being_processed - 1;
           Mesh::IndexType size_of_element = this->Esize(element_being_processed);
           Mesh::GenericElement ge(size_of_element);
           //    element_nfaces[index] = nfaces;
           ef[index].resize(ge.nfaces(),0);
           //    std::vector<Mesh::IndexType>(ef[index]).swap(ef[index]);
           ge.get_face_connectivities(all_face_conn[index],(*this)[index]);
         }
       ef.Sync();
       ef.SyncSizes();
       // This loop populates the F[N] (i.e. for each face, which nodes), and
       // the C[F] arrays.
       for(Mesh::IndexType element_being_processed = 1;
           element_being_processed <= number_of_elements;
           element_being_processed++)
         {
           Mesh::IndexType index = element_being_processed - 1;
           Mesh::IndexType size_of_element = this->Esize(element_being_processed);
           Mesh::GenericElement ge(size_of_element);
           Mesh::IndexType nfaces = ef.Esize(element_being_processed);
           //    Mesh::Connectivity efc;
           // This call populates the F[N] for the faces local
           // to the element_being_processed.
           //    ge.get_face_connectivities(efc,(*this)[index]);
           // This loop goes through each face of the element_being_processed
           // and updates the F[N] and C[F] arrays.
           for(Mesh::IndexType face_being_processed = 1;
               face_being_processed <= nfaces;
               face_being_processed++){
             Mesh::IndexType findex = face_being_processed - 1;
             if(!ef[index][findex]){ // 0 if face hasn't yet been processed
               fcon.push_back(all_face_conn[index][findex]); // add the new face to the F[N] array
               ef[index][findex] = number_of_faces + 1; // add the face id to the C[F] array
               Mesh::SubEntityId seid1;
               Mesh::SubEntityId seid2;
               sf.push_back(std::make_pair(seid1,seid2));
               sf[number_of_faces].first.first = element_being_processed;
               sf[number_of_faces].first.second = face_being_processed;
               // Now look at each cell containing each node of the current face and determine
               // which one (if any) have the same face.   This will be the face neighbor of the
               // element_being_processed for the face identified by (number_of_faces + 1).
               //            std::list<Mesh::IndexType> element_nbrlist;
               bool found = false;
               std::vector<Mesh::IndexType>::iterator fni = fcon[number_of_faces].begin();
               while(fni != fcon[number_of_faces].end() && !found){ // for every node in this face
                 Mesh::IndexType face_node_index = *fni++ - 1;
                 std::vector<Mesh::IndexType>::iterator enbri = dc[face_node_index].begin();
                 while(enbri != dc[face_node_index].end() && !found){ // look thru all the node's cells
                   Mesh::IndexType enbr_index = *enbri++ - 1;
                   if(enbr_index+1 > element_being_processed){
                     Mesh::IndexType nbr_nfaces = ef.Esize(enbr_index+1);
                     for(Mesh::IndexType nbrface = 1;nbrface <= nbr_nfaces && !found;nbrface++){
                       Mesh::IndexType nbr_face_index = nbrface -1;
                       if(!ef[enbr_index][nbr_face_index]){
                         if(IRAD::Util::HaveOppositeOrientation(all_face_conn[index][findex],
                                                                all_face_conn[enbr_index][nbr_face_index])){
                           found = true;
                           ef[enbr_index][nbr_face_index] = number_of_faces + 1;
                           sf[number_of_faces].second.first = enbr_index+1;
                           sf[number_of_faces].second.second = nbr_face_index+1;
                         } // if faces match
                       }
                     }
                   }
                 }
               }
               number_of_faces++;
             }
           }
         }
       fcon.Sync();
     };
void Connectivity::destroy ()
Definition at line 422 of file Mesh.C.
{
       DestroySizes();
       Connectivity::iterator ti = this->begin();
       while(ti != this->end()){
         ti->resize(0);
         std::vector<Mesh::IndexType> tmp(*ti);
         ti->swap(tmp);
         ti++;
       }
       this->resize(0);
       std::vector<std::vector<Mesh::IndexType> >(*this).swap(*this);
     };
void Connectivity::DestroySizes ()
Definition at line 442 of file Mesh.C.
 { _sizes.resize(0);};
std::vector<Mesh::IndexType>& SolverUtils::Mesh::Connectivity::Element (Mesh::IndexType n) inline
Definition at line 363 of file Mesh.H.
References _nelem.
Referenced by SolverUtils::Mesh::Skin().
{
         assert(n > 0 && n <= _nelem);
         return((*this)[n-1]);
       };
std::vector<Mesh::IndexType> SolverUtils::Mesh::Connectivity::Element (Mesh::IndexType n) const inline
Definition at line 367 of file Mesh.H.
References _nelem.
{
         assert(n > 0 && n <= _nelem);
         return((*this)[n-1]);
       };
void Connectivity::ElementsOn (std::vector< Mesh::IndexType > & nodes, Connectivity & dc, std::vector< Mesh::IndexType > & subset)
Definition at line 789 of file Mesh.C.
     {
       std::list<Mesh::IndexType> alist;
       std::vector<Mesh::IndexType>::iterator ni = nodes.begin();
       while(ni != nodes.end()){
         Mesh::IndexType node_index = *ni++ - 1;
         std::vector<Mesh::IndexType>::iterator dci = dc[node_index].begin();
         while(dci != dc[node_index].end())
           alist.push_back(*dci++);
       }
       alist.sort();
       alist.unique();
       subset.resize(alist.size());
       std::vector<Mesh::IndexType>::iterator ssi = subset.begin();
       std::list<Mesh::IndexType>::iterator li = alist.begin();
       while(li != alist.end())
         *ssi++ = *li++;
     };
Mesh::IndexType SolverUtils::Mesh::Connectivity::Esize (Mesh::IndexType n) const inline
Definition at line 382 of file Mesh.H.
References _nelem, and _sizes.
Referenced by SolverUtils::FEM::AssembleBorderElement(), SolverUtils::FEM::AssembleBorderElementII(), SolverUtils::FEM::AssembleLocalElement(), SolverUtils::FEM::AssembleLocalElementII(), BuildFaceConnectivity(), SolverUtils::Mesh::CollideCellsWithBox(), SolverUtils::Mesh::CollideMeshWithBox(), SolverUtils::FEM::FastAssembleLocalElements(), SolverUtils::Mesh::FindPointInCells(), SolverUtils::Mesh::FindPointInMesh(), SolverUtils::Mesh::FindPointInMesh_2(), SolverUtils::Mesh::GetMeshBoxes(), SolverUtils::Mesh::GlobalFindPointInMesh(), SolverUtils::Mesh::Skin(), SolverUtils::Mesh::writeVtkData(), and SolverUtils::Mesh::WriteVTKToStream().
       {
         assert(n > 0 && n <= _nelem);
         return (_sizes.empty() ? (*this)[n-1].size() : _sizes[n-1]);
       };
template<typename T > void SolverUtils::Mesh::Connectivity::Flatten (std::vector< T > & outcon) const inline
Definition at line 419 of file Mesh.H.
       {
         outcon.resize(0);
         std::vector<std::vector<Mesh::IndexType> >::const_iterator eci = this->begin();
         while(eci != this->end()){
           std::vector<Mesh::IndexType>::const_iterator eni = eci->begin();
           while(eni != eci->end())
             outcon.push_back(*eni++);
           eci++;
         }
       };
void Connectivity::GetAdjacent (Connectivity & rl, Connectivity & dc, Mesh::IndexType n = 0, bool sortit = false)
Definition at line 740 of file Mesh.C.
References _nelem, and Resize().
Referenced by SolverUtils::FEM::AssignDofsByElement(), SolverUtils::FEM::AssignDofsByElementII(), SolverUtils::FEM::AssignLocalDofsByElement(), and SolverUtils::FEM::AssignLocalDofsByElementII().
     {
       rl.Resize(_nelem);
       rl._nelem = _nelem;
       Mesh::IndexType nadj = n;
       if(n == 0){
         std::cout << "GETADJACENT: Determining MaxNodeId" << std::endl;
         nadj = MaxNodeId<Connectivity,std::vector<Mesh::IndexType> >(dc);
       }
       std::vector<bool> added(nadj,false);
       for(Mesh::IndexType i = 0; i < _nelem;i++){
         //      Mesh::IndexType current_element = i + 1;
         std::vector<Mesh::IndexType>::iterator ni = (*this)[i].begin();
         std::list<Mesh::IndexType> nbrlist;
         while(ni != (*this)[i].end()){
           Mesh::IndexType index = *ni - 1;
           std::vector<Mesh::IndexType>::iterator dci = dc[index].begin();
           while(dci != dc[index].end()){
             Mesh::IndexType ai = *dci - 1;
             if(!added[ai]){
               nbrlist.push_back(*dci);
               added[ai] = true;
             }
             dci++;
           }
           ni++;
         }
         if(sortit)
           nbrlist.sort();
         //      nbrlist.unique();
         rl[i].resize(nbrlist.size());
         Mesh::IndexType j = 0;
         std::list<Mesh::IndexType>::iterator si = nbrlist.begin();
         while(si != nbrlist.end()){
           rl[i][j++] = *si;
           added[*si-1] = false;
           si++;
         }
       }
     };
void Connectivity::GetNeighborhood (NeighborHood & rl, const Connectivity & dc)
Definition at line 677 of file Mesh.C.
References _nelem.
     {
       rl.resize(_nelem);
       //    rl._nelem = _nelem;
       for(Mesh::IndexType i = 0; i < _nelem;i++){
         std::vector<Mesh::IndexType>::const_iterator ni = (*this)[i].begin();
         while(ni != (*this)[i].end()){
           Mesh::IndexType index = *ni - 1;
           std::vector<Mesh::IndexType>::const_iterator dci = dc[index].begin();
           while(dci != dc[index].end())
             rl[i].insert(*dci++);
           ni++;
         }
         rl[i].erase(i+1);
       }
     };
void Connectivity::GetNeighborhood (Connectivity & rl, Connectivity & dc, bool exclude_self = true, bool sortit = false)
Definition at line 696 of file Mesh.C.
References _nelem, and Resize().
     {
       rl.Resize(_nelem);
       rl._nelem = _nelem;
       std::vector<bool> added(_nelem,false);
       for(Mesh::IndexType i = 0; i < _nelem;i++){
         Mesh::IndexType current_element = i + 1;
         std::vector<Mesh::IndexType>::iterator ni = (*this)[i].begin();
         std::list<Mesh::IndexType> nbrlist;
         while(ni != (*this)[i].end()){
           Mesh::IndexType index = *ni - 1;
           std::vector<Mesh::IndexType>::iterator dci = dc[index].begin();
           while(dci != dc[index].end()){
             Mesh::IndexType ai = *dci - 1;
             if(!added[ai]){
               nbrlist.push_back(*dci);
               added[ai] = true;
             }
             dci++;
           }
           ni++;
         }
         if(sortit)
           nbrlist.sort();
         //      nbrlist.unique();
         if(exclude_self){
           nbrlist.remove(current_element);
           added[i] = false;
         }
         rl[i].resize(nbrlist.size());
         Mesh::IndexType j = 0;
         std::list<Mesh::IndexType>::iterator si = nbrlist.begin();
         while(si != nbrlist.end()){
           rl[i][j++] = *si;
           added[*si-1] = false;
           si++;
         }
       }
     };
void Connectivity::graph_mode (Mesh::IndexType offset = 0)
Definition at line 652 of file Mesh.C.
     {
       Connectivity::iterator ci = this->begin();
       Mesh::IndexType n = 1;
       while(ci != this->end()){
         ci->erase(std::lower_bound(ci->begin(),ci->end(),offset+n++));
         ci++;
       }
     };
void Connectivity::Inverse (Connectivity & rc, Mesh::IndexType nnodes = 0) const
Definition at line 465 of file Mesh.C.
References _nelem, Resize(), and Sync().
Referenced by SolverUtils::Mesh::MeshUtilityObject::FormConnectivity(), and SolverUtils::Mesh::Skin().
     {
       if(nnodes <= 0)
         nnodes = MaxNodeId<Connectivity,std::vector<Mesh::IndexType> >(*this);
       //      Connectivity::const_iterator ci = this->begin();
       //      while(ci != this->end()){
       //        std::vector<Mesh::IndexType>::const_iterator ii = ci->begin();
       //        while(ii != ci->end()){
       //          nnodes = (nnodes > *ii ? nnodes : *ii);
       //          ii++;
       //        }
       //        ci++;
       //      }
       //    }
       rc.Resize(nnodes);
       rc.Sync();
       for(Mesh::IndexType i = 0;i < _nelem;i++){
         std::vector<Mesh::IndexType>::const_iterator ii = (*this)[i].begin();
         while(ii != (*this)[i].end()){
           rc[*ii-1].push_back(i+1);
           ii++;
         }
       }
     };
void Connectivity::InverseDegenerate (Connectivity & rc, Mesh::IndexType nnodes = 0) const
Definition at line 446 of file Mesh.C.
References Resize(), and Sync().
     {
       if(nnodes <= 0)
         nnodes = MaxNodeId<Connectivity,std::vector<Mesh::IndexType> >(*this);
       rc.Resize(nnodes);
       rc.Sync();
       for(Mesh::IndexType i = 0;i < _nelem;i++){
         if((*this)[i].size() > 1){
           std::vector<Mesh::IndexType>::const_iterator ii = (*this)[i].begin();
           while(ii != (*this)[i].end()){
             rc[*ii-1].push_back(i+1);
             ii++;
           }
         }
       }
     };
void Connectivity::matrix_mode (Mesh::IndexType offset = 0)
Definition at line 665 of file Mesh.C.
     {
       Connectivity::iterator ci = this->begin();
       Mesh::IndexType n = 1;
       while(ci != this->end()){
         ci->insert(std::lower_bound(ci->begin(),ci->end(),offset+n),1,offset+n);
         n++;
         ci++;
       }
     };
Mesh::IndexType SolverUtils::Mesh::Connectivity::Nelem () const inline
Definition at line 381 of file Mesh.H.
References _nelem.
Referenced by SolverUtils::AgentToPane(), SolverUtils::FEM::AssignDofsByElement(), SolverUtils::FEM::AssignDofsByElementII(), SolverUtils::FEM::AssignLocalDofsByElement(), SolverUtils::FEM::AssignLocalDofsByElementII(), BuildFaceConnectivity(), SolverUtils::FEM::BuildSymbolicStiffness(), SolverUtils::FEM::SolutionData::Create(), SolverUtils::Mesh::GetMeshBoxes(), SolverUtils::Mesh::GlobalFindPointInMesh(), COM::TestModule::InitSolver(), SolverUtils::FEM::SolverAgent::ReportMeshToStream(), COM::TransferSolver::Setup(), SolverUtils::Mesh::Skin(), COM::TestModule::Step(), SolverUtils::SurfaceMeshToPane(), SolverUtils::VolumeMeshToPane(), SolverUtils::Mesh::WriteVTKToStream(), and SolverUtils::WriteVTKToStream().
 { return _nelem;};
Mesh::IndexType& SolverUtils::Mesh::Connectivity::Node (Mesh::IndexType e, Mesh::IndexType n) inline
Definition at line 371 of file Mesh.H.
Referenced by SolverUtils::Mesh::GenericCell_2::Area(), SolverUtils::Mesh::CollideCellsWithBox(), SolverUtils::Mesh::CollideMeshWithBox(), SolverUtils::Mesh::GetMeshBoxes(), SolverUtils::Mesh::GenericCell_2::GetNormalSet(), SolverUtils::Mesh::GenericCell_2::GetPointSet(), and SolverUtils::Mesh::GenericElement::shapef_jacobian_at().
{
         assert(e > 0 && e <= _nelem && n > 0);
         assert(n <= (*this)[e-1].size());
         return((*this)[e-1][n-1]);
       };
Mesh::IndexType SolverUtils::Mesh::Connectivity::Node (Mesh::IndexType e, Mesh::IndexType n) const inline
Definition at line 376 of file Mesh.H.
{
         assert(e > 0 && e <= _nelem && n > 0);
         assert(n <= (*this)[e-1].size());
         return((*this)[e-1][n-1]);
       };
void Connectivity::Resize (unsigned int N = 0)
Definition at line 316 of file Mesh.C.
Referenced by BuildFaceConnectivity(), SolverUtils::Mesh::GenericElement::get_face_connectivities(), GetAdjacent(), GetNeighborhood(), Inverse(), InverseDegenerate(), and SolverUtils::Mesh::operator>>().
 {this->resize(N);};
void Connectivity::ShrinkWrap ()
Definition at line 400 of file Mesh.C.
Referenced by SolverUtils::PaneToUnstructuredMesh(), SolverUtils::Mesh::Partition::Read(), and SolverUtils::Mesh::Skin().
     {
       _nelem = this->size();
       Connectivity::iterator ti = this->begin();
       while(ti != this->end()){
         std::vector<Mesh::IndexType>(*ti).swap(*ti);
         ti++;
       }
       std::vector<std::vector<Mesh::IndexType> >(*this).swap(*this);
     };
void Connectivity::Sync ()
Definition at line 399 of file Mesh.C.
Referenced by SolverUtils::FEM::AssignDofsByElement(), SolverUtils::FEM::AssignDofsByElementII(), SolverUtils::FEM::AssignLocalDofsByElement(), SolverUtils::FEM::AssignLocalDofsByElementII(), BuildFaceConnectivity(), SolverUtils::Mesh::BSExtent< T >::CreateUnstructuredMesh(), Inverse(), InverseDegenerate(), and SolverUtils::Mesh::Partition::Read().
 { _nelem = this->size();};
void Connectivity::SyncSizes ()
Definition at line 434 of file Mesh.C.
Referenced by BuildFaceConnectivity(), SolverUtils::Mesh::Skin(), SolverUtils::Mesh::writeVtkData(), and SolverUtils::Mesh::WriteVTKToStream().
{
       _sizes.resize(_nelem);
       for(Mesh::IndexType i = 0;i < _nelem;i++){
         _sizes[i] = (*this)[i].size();
         //      std::vector<Mesh::IndexType> tmp((*this)[i]);
         //      ((*this)[i].swap(tmp));
       }
     };
void Connectivity::Truncate ()
Definition at line 410 of file Mesh.C.
     {
       Connectivity::iterator ti = this->begin();
       while(ti != this->end()){
         if(ti->empty()){
           ti = this->erase(ti);
           _nelem--;
         }
         else
           ti++;
       }
     };
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & oSt, const Connectivity & ec) friend
Definition at line 2430 of file Mesh.C.
     {
       oSt << std::setiosflags(std::ios::left) << ec.size();
       if(ec.size() == 0) return(oSt);
       oSt << "\n";
       Mesh::Connectivity::const_iterator ci = ec.begin();
       while(ci != ec.end()){
         std::vector<Mesh::IndexType>::const_iterator ni = ci->begin();
         while(ni != ci->end()){
           oSt << *ni++;
           if(ni != ci->end())
             oSt << "\t";
         }
         ci++;
         if(ci != ec.end())
           oSt << "\n";
       }
       return(oSt);
     }
std::istream& operator>> (std::istream & iSt, Mesh::Connectivity & ec) friend
Definition at line 2367 of file Mesh.C.
     {
       std::string line;
       while(line.empty())
         std::getline(iSt,line);
       std::istringstream Istr(line);
       Mesh::IndexType nelem = 0;
       Istr >> nelem;
       if(nelem > 0){
         ec.Resize(nelem);
         ec._nelem = nelem;
         for(Mesh::IndexType i = 0;i < nelem;i++){
           std::getline(iSt,line);
           std::istringstream Istr2(line);
           Mesh::IndexType node;
           ec[i].reserve(8);
           while(Istr2 >> node)
             ec[i].push_back(node);
           std::vector<Mesh::IndexType>(ec[i]).swap(ec[i]);
         }
       }
       return(iSt);
     }
Member Data Documentation
Mesh::IndexType SolverUtils::Mesh::Connectivity::_nelem private
Definition at line 356 of file Mesh.H.
Referenced by BreadthFirstRenumber(), Element(), Esize(), GetAdjacent(), GetNeighborhood(), Inverse(), Nelem(), and SolverUtils::Mesh::operator>>().
std::vector<Mesh::IndexType> SolverUtils::Mesh::Connectivity::_sizes private
Definition at line 357 of file Mesh.H.
Referenced by Esize().
The documentation for this class was generated from the following files:
Mesh.H
Mesh.C