IMPACT: LoadTransfer_FSc_ALE Class Reference
LoadTransfer_FSc_ALE Class Reference
Detailed Description
Definition at line 44 of file transfer_actions.h.
#include <transfer_actions.h>
Public Member Functions
LoadTransfer_FSc_ALE (FluidAgent *fag, SolidAgent *sag, BurnAgent *bag, const std::string f_pf, const std::string fb_mdot, const std::string b_rb, const std::string s_ts, const std::string s_pf)
void init (double t)
void run (double t, double dt, double alpha)
Public Member Functions inherited from InterMeshTransfer
InterMeshTransfer (FluidAgent *fag, SolidAgent *sag, char *name=NULL)
Public Member Functions inherited from Action
Action (void *p=0, const char *name=NULL)
Action (int n, const char **at, int *i=NULL, void *p=0, const char *name=NULL)
Action (int n, const std::string at[], int *i=NULL, void *p=0, const char *name=NULL)
virtual ~Action ()
virtual void declare (Scheduler &)
virtual void finalize ()
virtual const char * name ()
void set_name (const char *name)
virtual void print (FILE *f)
virtual void print_toposort (FILE *f)
virtual void schedule ()
Private Attributes
int traction_mode
int size_ts
BurnAgent * bagent
int f_tf_hdl
int f_ts_hdl
int s_ts_hdl
int s_pf_hdl
int f_pf_hdl
int fb_ts_hdl
int fb_pf_hdl
int fb_mdot_hdl
int fb_rhof_alp_hdl
int fb_mdot_tmp_hdl
int b_rb_hdl
int fb_nf_alp_hdl
int fb_tf_hdl
int RFC_transfer
int SURF_compute_face_normals
Additional Inherited Members
Protected Types inherited from Action
enum { IN =1, OUT =2, INOUT =3 }
Protected Member Functions inherited from InterMeshTransfer
void load_rocface (const RocmanControl_parameters *param)
Protected Member Functions inherited from Action
int get_dataitem_handle (int i)
int get_dataitem_handle_const (int i)
int get_dataitem_handle (const std::string str)
void set_attr (int n, const std::string at[], int *id=NULL)
void set_attr (int n, const char *at[], int *id=NULL)
void set_io (int n, const int *io)
void set_io (const char *io)
int get_io (int i)
Protected Attributes inherited from InterMeshTransfer
FluidAgent * fagent
SolidAgent * sagent
Protected Attributes inherited from Action
const char * action_name
char ** attr
int * idx
int count
void * usr_ptr
std::vector< int > inout
Constructor & Destructor Documentation
LoadTransfer_FSc_ALE::LoadTransfer_FSc_ALE (FluidAgent * fag, SolidAgent * sag, BurnAgent * bag, const std::string f_pf, const std::string fb_mdot, const std::string b_rb, const std::string s_ts, const std::string s_pf) explicit
Definition at line 185 of file transfer_actions.C.
References COM_DOUBLE, InterMeshTransfer::fagent, Agent::get_coupling(), Coupling::get_rocmancontrol_param(), Agent::get_surface_window(), FluidAgent::ifluid_i, Action::IN, NO_SHEER, Action::OUT, Agent::register_clone_dataitem(), Agent::register_new_dataitem(), InterMeshTransfer::sagent, Action::set_attr(), Action::set_io(), SolidAgent::solidBufBase, traction_mode, and RocmanControl_parameters::traction_mode.
                                                         :
     InterMeshTransfer(fag, sag, "LoadTransfer_FSc_ALE"),
     bagent(bag)
 {
   int io[] = {IN, IN, IN, IN, OUT};
   set_io( 5, io);
   std::string.data[5];
  .data[0] = f_pf;
  .data[1] = fb_mdot;
  .data[2] = b_rb;
  .data[3] = s_ts;
  .data[4] = s_pf;
   set_attr(5,.data);
   traction_mode = fagent->get_coupling()->get_rocmancontrol_param()->traction_mode;
   // create_dataitem
   // for SolidAgent ??????????????????
 //  if (traction_mode == NO_SHEER && size_ts == 3) {
     sagent->register_new_dataitem( sagent->solidBufBase, ".pf", 'e', COM_DOUBLE, 1, "Pa");
 //  }
   // for FluidAgent
   if (traction_mode == NO_SHEER)  {
     fagent->register_clone_dataitem( 0, fagent->ifluid_i, ".ts", fagent->get_surface_window(), ".pf");
   }
   else
     fagent->register_clone_dataitem( 0, fagent->ifluid_i, ".ts", fagent->get_surface_window(), ".tf");
 //  fagent->register_new_dataitem( fagent->fluidBufB, ".mdot_tmp", 'e', COM_DOUBLE, 1, "kg/(m^2 s)");
 }
Member Function Documentation
void LoadTransfer_FSc_ALE::init (double t) virtual
Reimplemented from Action.
Definition at line 225 of file transfer_actions.C.
References b_rb_hdl, COM_assertion_msg, COM_get_dataitem(), COM_get_dataitem_handle(), COM_get_dataitem_handle_const(), COM_get_function_handle(), f_pf_hdl, f_tf_hdl, f_ts_hdl, InterMeshTransfer::fagent, fb_mdot_hdl, fb_mdot_tmp_hdl, fb_nf_alp_hdl, fb_pf_hdl, fb_rhof_alp_hdl, fb_tf_hdl, fb_ts_hdl, FluidAgent::fluidBufB, FluidAgent::fluidBufNG, Agent::get_coupling(), Action::get_dataitem_handle(), Action::get_dataitem_handle_const(), Coupling::get_rocmancontrol_param(), InterMeshTransfer::load_rocface(), load_rocsurf(), MAN_DEBUG, NO_SHEER, RFC_transfer, s_pf_hdl, s_ts_hdl, InterMeshTransfer::sagent, size_ts, SolidAgent::solidBufBase, SURF_compute_face_normals, and traction_mode.
{
   // find out size_ts
   int dummy;
   std::string unit;
   char loc;
   COM_get_dataitem( sagent->solidBufBase+".ts", &loc, &dummy, &size_ts, &unit);
   if (size_ts == 1 && traction_mode != NO_SHEER) {
     COM_assertion_msg(0, "If traction mode is with sheer, then solid tractions must be vectors!");
     MPI_Abort(MPI_COMM_WORLD, -1);
   }
   //f_pf_hdl = COM_get_dataitem_handle_const( fagent->fluidBufNG+".pf");
   f_pf_hdl = get_dataitem_handle_const( 0);
   fb_mdot_hdl = get_dataitem_handle( 1);
   b_rb_hdl = get_dataitem_handle( 2);
   s_ts_hdl = get_dataitem_handle( 3);
   if (traction_mode == NO_SHEER && size_ts == 3)
     s_pf_hdl = get_dataitem_handle( 4);
   else
     s_pf_hdl = -1;
   f_ts_hdl = COM_get_dataitem_handle( fagent->fluidBufNG+".ts");
   f_tf_hdl = COM_get_dataitem_handle_const( fagent->fluidBufNG+".tf");
   fb_ts_hdl = COM_get_dataitem_handle( fagent->fluidBufB+".ts");
   fb_pf_hdl = COM_get_dataitem_handle( fagent->fluidBufB+".pf");
   fb_rhof_alp_hdl = COM_get_dataitem_handle ( fagent->fluidBufB+".rhof_alp");
   fb_mdot_tmp_hdl = COM_get_dataitem_handle ( fagent->fluidBufB+".mdot_tmp");
   fb_nf_alp_hdl = COM_get_dataitem_handle( fagent->fluidBufB+".nf_alp");
   fb_tf_hdl = COM_get_dataitem_handle_const( fagent->fluidBufB+".tf");
   load_rocface(fagent->get_coupling()->get_rocmancontrol_param());
   RFC_transfer = COM_get_function_handle("RFC.least_squares_transfer");
   load_rocsurf();
   SURF_compute_face_normals = COM_get_function_handle( "SURF.compute_element_normals");
   MAN_DEBUG(2, ("LoadTransfer_FSc_ALE::init() called - traction_mode: %d size_ts: %d.\n", traction_mode, size_ts));
 }
void LoadTransfer_FSc_ALE::run (double t, double dt, double alpha) virtual
Reimplemented from Action.
Definition at line 266 of file transfer_actions.C.
References b_rb_hdl, COM_assertion_msg, COM_call_function(), RocBlas::copy, RocBlas::div, f_pf_hdl, f_tf_hdl, f_ts_hdl, InterMeshTransfer::fagent, fb_mdot_hdl, fb_mdot_tmp_hdl, fb_nf_alp_hdl, fb_pf_hdl, fb_rhof_alp_hdl, fb_tf_hdl, fb_ts_hdl, Agent::get_coupling(), Coupling::get_rocmancontrol_param(), MAN_DEBUG, RocBlas::mul, RocBlas::neg, NO_SHEER, RocmanControl_parameters::P_ambient, RFC_transfer, s_pf_hdl, s_ts_hdl, InterMeshTransfer::sagent, size_ts, RocBlas::sub, RocBlas::sub_scalar, SURF_compute_face_normals, traction_mode, and SolidAgent::withALE.
{
   MAN_DEBUG(2, ("Rocman: LoadTransfer_FSc_ALE::run() with t:%e dt:%e.\n", t, dt));
   // ts = tf + ( mdot*Vs
 #if 1
   // part 1  (POST_UPDATE_FLUID in fluid_agent.f90)
   if (traction_mode != NO_SHEER) {
     COM_call_function( RocBlas::copy, &f_tf_hdl, &f_ts_hdl);
       // Compute tfmts = t_s-t_f (see developers guide).
       // Here fb_mdot_tmp is used as buffer space.
     COM_call_function( RocBlas::div, &fb_mdot_hdl, &fb_rhof_alp_hdl, &fb_mdot_tmp_hdl);
     if ( sagent->withALE) {
       COM_call_function( RocBlas::sub, &fb_mdot_tmp_hdl, &b_rb_hdl, &fb_mdot_tmp_hdl);
     }
     COM_call_function( RocBlas::mul, &fb_mdot_tmp_hdl, &fb_mdot_hdl, &fb_mdot_tmp_hdl);
     COM_call_function( RocBlas::mul, &fb_nf_alp_hdl, &fb_mdot_tmp_hdl, &fb_ts_hdl);
        // Compute ts = tf - (tf-ts)
     COM_call_function( RocBlas::sub, &fb_tf_hdl, &fb_ts_hdl, &fb_ts_hdl);
   }
   else {   // ts is a scalar
     COM_call_function( RocBlas::copy, &f_pf_hdl, &f_ts_hdl);
     //    Compute tsmpf = p_f-t_s (see developers guide).
     //    Here fb_mdot_tmp is used as buffer space.
     COM_call_function( RocBlas::div, &fb_mdot_hdl, &fb_rhof_alp_hdl, &fb_mdot_tmp_hdl);
     if ( sagent->withALE) {
         COM_call_function( RocBlas::sub, &fb_mdot_tmp_hdl, &b_rb_hdl, &fb_mdot_tmp_hdl);
     }
     COM_call_function( RocBlas::mul, &fb_mdot_tmp_hdl, &fb_mdot_hdl, &fb_ts_hdl);
      //    Compute ts = pf - (pf-ts)
     COM_call_function( RocBlas::sub, &fb_pf_hdl, &fb_ts_hdl, &fb_ts_hdl);
     //debug_print(fagent->fluidBufB+".mdot", 102, 0, "LOADTRANSFER");
     //debug_print(fagent->fluidBufB+".ts", 102, 0, "LOADTRANSFER");
      // Subtract from P_ambient if not zeros
     double P_ambient = fagent->get_coupling()->get_rocmancontrol_param()->P_ambient;
     if ( P_ambient != 0.0) {
        COM_call_function( RocBlas::sub_scalar, &f_ts_hdl, &P_ambient, &f_ts_hdl);
     }
   }
 #endif
   // part 2  (solid_agent.f90 INIT_INBUFF_SOLID())
   if (traction_mode == NO_SHEER && size_ts == 3) {
     COM_call_function( RFC_transfer, &f_ts_hdl, &s_pf_hdl);
     COM_call_function( SURF_compute_face_normals, &s_ts_hdl);
     COM_call_function( RocBlas::mul, &s_ts_hdl, &s_pf_hdl, &s_ts_hdl);
     COM_call_function( RocBlas::neg, &s_ts_hdl, &s_ts_hdl);
   }
   else if ( traction_mode == NO_SHEER && size_ts == 1) {
     COM_call_function( RFC_transfer, &f_ts_hdl, &s_ts_hdl);
     //debug_print(sagent->solidBuf+".ts", 102, 0, fagent->get_communicator(), "LOADTRANSFER");
   }
   else if (size_ts == 1) {
     COM_assertion_msg(0, "If traction mode is with sheer, then solid tractions must be vectors!");
   }
   else {
     COM_call_function( RFC_transfer, &f_ts_hdl, &s_ts_hdl);
   }
 }
Member Data Documentation
int LoadTransfer_FSc_ALE::b_rb_hdl private
Definition at line 56 of file transfer_actions.h.
Referenced by init(), and run().
BurnAgent* LoadTransfer_FSc_ALE::bagent private
Definition at line 52 of file transfer_actions.h.
int LoadTransfer_FSc_ALE::f_pf_hdl private
Definition at line 54 of file transfer_actions.h.
Referenced by init(), and run().
int LoadTransfer_FSc_ALE::f_tf_hdl private
Definition at line 53 of file transfer_actions.h.
Referenced by init(), and run().
int LoadTransfer_FSc_ALE::f_ts_hdl private
Definition at line 53 of file transfer_actions.h.
Referenced by init(), and run().
int LoadTransfer_FSc_ALE::fb_mdot_hdl private
Definition at line 55 of file transfer_actions.h.
Referenced by init(), and run().
int LoadTransfer_FSc_ALE::fb_mdot_tmp_hdl private
Definition at line 55 of file transfer_actions.h.
Referenced by init(), and run().
int LoadTransfer_FSc_ALE::fb_nf_alp_hdl private
Definition at line 56 of file transfer_actions.h.
Referenced by init(), and run().
int LoadTransfer_FSc_ALE::fb_pf_hdl private
Definition at line 54 of file transfer_actions.h.
Referenced by init(), and run().
int LoadTransfer_FSc_ALE::fb_rhof_alp_hdl private
Definition at line 55 of file transfer_actions.h.
Referenced by init(), and run().
int LoadTransfer_FSc_ALE::fb_tf_hdl private
Definition at line 56 of file transfer_actions.h.
Referenced by init(), and run().
int LoadTransfer_FSc_ALE::fb_ts_hdl private
Definition at line 54 of file transfer_actions.h.
Referenced by init(), and run().
int LoadTransfer_FSc_ALE::RFC_transfer private
Definition at line 57 of file transfer_actions.h.
Referenced by init(), and run().
int LoadTransfer_FSc_ALE::s_pf_hdl private
Definition at line 53 of file transfer_actions.h.
Referenced by init(), and run().
int LoadTransfer_FSc_ALE::s_ts_hdl private
Definition at line 53 of file transfer_actions.h.
Referenced by init(), and run().
int LoadTransfer_FSc_ALE::size_ts private
Definition at line 51 of file transfer_actions.h.
Referenced by init(), and run().
int LoadTransfer_FSc_ALE::SURF_compute_face_normals private
Definition at line 58 of file transfer_actions.h.
Referenced by init(), and run().
int LoadTransfer_FSc_ALE::traction_mode private
Definition at line 50 of file transfer_actions.h.
Referenced by init(), LoadTransfer_FSc_ALE(), and run().
The documentation for this class was generated from the following files:
transfer_actions.h
transfer_actions.C