IMPACT: SolverUtils::GeoPrim::CVector Class Reference
SolverUtils::GeoPrim::CVector Class Reference
Detailed Description
Definition at line 213 of file GeoPrimitives.H.
#include <GeoPrimitives.H>
Public Member Functions
CVector ()
CVector (double ix, double iy, double iz=0.0)
CVector (const CPoint &p1, const CPoint &p2)
CVector (const CPoint &p)
CVector (const double *a)
CVector (const CVector &v)
CVector & init (const CPoint &p)
CVector & init (const double *a)
CVector & init (const CVector &v)
CVector & init (double ix, double iy, double iz)
CVector & init (const CPoint &p1, const CPoint &p2)
CVector & init ()
double norm () const
double mag () const
double mag2 () const
CVector & normalize ()
CVector unit () const
double operator* (const CVector &v2) const
CVector operator* (double num) const
CVector & operator*= (double num)
CVector operator% (const CVector &v2) const
CVector & copy (const CVector &v2)
CVector & operator= (const CVector &v2)
CVector & operator= (const CPoint &p)
CVector & operator%= (const CVector &v2)
CVector operator+ (const CVector &v2) const
CVector operator- (const CVector &v2) const
CVector & operator+= (const CVector &v2)
CVector & operator+= (const CPoint &p)
CVector & operator-= (const CVector &v2)
double & x ()
double x () const
CVector & x (double i)
double & y ()
double y () const
CVector & y (double i)
double & z ()
double z () const
CVector & z (double i)
const double & operator[] (unsigned int i) const
double & operator[] (unsigned int i)
bool operator== (const CVector &v) const
bool operator< (const CVector &v) const
bool operator> (const CVector &v) const
bool operator<= (const CVector &v) const
bool operator>= (const CVector &v) const
Protected Attributes
double V [3]
Friends
CVector operator* (double, const CVector &)
std::ostream & operator<< (std::ostream &, const CVector &)
std::istream & operator>> (std::istream &, CVector &)
Constructor & Destructor Documentation
SolverUtils::GeoPrim::CVector::CVector () inline
Definition at line 220 of file GeoPrimitives.H.
References V.
     {
       V[0] = V[1] = V[2] = 0.;
     };
SolverUtils::GeoPrim::CVector::CVector (double ix, double iy, double iz = 0.0) inline
Definition at line 224 of file GeoPrimitives.H.
References V.
     {
       V[0] = ix;
       V[1] = iy;
       V[2] = iz;
     };
SolverUtils::GeoPrim::CVector::CVector (const CPoint & p1, const CPoint & p2) inline
Definition at line 230 of file GeoPrimitives.H.
References V, x(), y(), and z().
     {
       V[0] = (p2 - p1).x();
       V[1] = (p2 - p1).y();
       V[2] = (p2 - p1).z();
     };
SolverUtils::GeoPrim::CVector::CVector (const CPoint & p) inline
Definition at line 236 of file GeoPrimitives.H.
References V, SolverUtils::GeoPrim::CPoint::x(), SolverUtils::GeoPrim::CPoint::y(), and SolverUtils::GeoPrim::CPoint::z().
     {
       V[0] = p.x();
       V[1] = p.y();
       V[2] = p.z();
     };
SolverUtils::GeoPrim::CVector::CVector (const double * a) inline
Definition at line 242 of file GeoPrimitives.H.
References V.
     {
       V[0] = a[0];
       V[1] = a[1];
       V[2] = a[2];
     };
SolverUtils::GeoPrim::CVector::CVector (const CVector & v) inline
Definition at line 248 of file GeoPrimitives.H.
References V.
     {
       V[0] = v.V[0];
       V[1] = v.V[1];
       V[2] = v.V[2];
     };
Member Function Documentation
CVector& SolverUtils::GeoPrim::CVector::copy (const CVector & v2) inline
Definition at line 349 of file GeoPrimitives.H.
References V.
Referenced by operator%=(), operator-=(), and operator=().
     {
       V[0] = v2.V[0];
       V[1] = v2.V[1];
       V[2] = v2.V[2];
       return(*this);
     };
CVector& SolverUtils::GeoPrim::CVector::init (const CPoint & p) inline
Definition at line 254 of file GeoPrimitives.H.
References V.
Referenced by SolverUtils::Mesh::FindPointInCells(), SolverUtils::Mesh::FindPointInMesh(), SolverUtils::Mesh::FindPointInMesh_2(), SolverUtils::Mesh::GlobalFindPointInMesh(), main(), SolverUtils::Mesh::GenericElement::shapef_jacobian_at(), and SolverUtils::GeoPrim::Transpose().
     {
       V[0] = p[0];
       V[1] = p[1];
       V[2] = p[2];
       return(*this);
     };
CVector& SolverUtils::GeoPrim::CVector::init (const double * a) inline
Definition at line 261 of file GeoPrimitives.H.
References V.
     {
       V[0] = a[0];
       V[1] = a[1];
       V[2] = a[2];
       return(*this);
     };
CVector& SolverUtils::GeoPrim::CVector::init (const CVector & v) inline
Definition at line 268 of file GeoPrimitives.H.
References V.
     {
       V[0] = v[0];
       V[1] = v[1];
       V[2] = v[2];
       return(*this);
     };
CVector& SolverUtils::GeoPrim::CVector::init (double ix, double iy, double iz) inline
Definition at line 275 of file GeoPrimitives.H.
References V.
     {
       V[0] = ix;
       V[1] = iy;
       V[2] = iz;
       return(*this);
     };
CVector& SolverUtils::GeoPrim::CVector::init (const CPoint & p1, const CPoint & p2) inline
Definition at line 282 of file GeoPrimitives.H.
References V, x(), y(), and z().
     {
       V[0] = (p2 - p1).x();
       V[1] = (p2 - p1).y();
       V[2] = (p2 - p1).z();
       return(*this);
     };
CVector& SolverUtils::GeoPrim::CVector::init () inline
Definition at line 289 of file GeoPrimitives.H.
References V.
     {
       V[0] = V[1] = V[2] = 0.0;
       return(*this);
     };
double SolverUtils::GeoPrim::CVector::mag () const inline
Definition at line 298 of file GeoPrimitives.H.
References norm().
Referenced by SolverUtils::GeoPrim::Distance().
     {
       return (norm());
     };
double SolverUtils::GeoPrim::CVector::mag2 () const inline
Definition at line 302 of file GeoPrimitives.H.
References V.
Referenced by SolverUtils::GeoPrim::Distance().
     {
       return ((V[0]*V[0])+(V[1]*V[1])+(V[2]*V[2]));
     };
double SolverUtils::GeoPrim::CVector::norm () const inline
Definition at line 294 of file GeoPrimitives.H.
References V.
Referenced by SolverUtils::GeoPrim::CLineSegment::length(), mag(), normalize(), operator<(), operator>(), and unit().
     {
       return(sqrt((V[0] * V[0]) + (V[1] * V[1]) + (V[2] * V[2])));
     };
CVector& SolverUtils::GeoPrim::CVector::normalize () inline
Definition at line 306 of file GeoPrimitives.H.
References norm(), and V.
Referenced by SolverUtils::GeoPrim::CPlane::CPlane(), SolverUtils::GeoPrim::CLine::has_point(), and SolverUtils::Mesh::GenericCell_2::shapef_jacobian_at().
     {
       double n = norm();
       V[0] /= n;
       V[1] /= n;
       V[2] /= n;
       return(*this);
     };
CVector SolverUtils::GeoPrim::CVector::operator% (const CVector & v2) const inline
Definition at line 341 of file GeoPrimitives.H.
References V.
     {
       CVector v;
       v.V[0] = ((v2.V[2] * V[1]) - (v2.V[1] * V[2]));
       v.V[1] = ((v2.V[0] * V[2]) - (v2.V[2] * V[0]));
       v.V[2] = ((v2.V[1] * V[0]) - (v2.V[0] * V[1]));
       return(v);
     };
CVector& SolverUtils::GeoPrim::CVector::operator%= (const CVector & v2) inline
Definition at line 367 of file GeoPrimitives.H.
References copy().
     {
       return(copy((*this)%v2));
     };
double SolverUtils::GeoPrim::CVector::operator* (const CVector & v2) const inline
Definition at line 323 of file GeoPrimitives.H.
References V.
     {
       return((V[0] * v2.V[0]) +
              (V[1] * v2.V[1]) +
              (V[2] * v2.V[2]));
     };
CVector SolverUtils::GeoPrim::CVector::operator* (double num) const inline
Definition at line 329 of file GeoPrimitives.H.
References V.
     {
       CVector rv(num*V[0],num*V[1],num*V[2]);
       return(rv);
     };
CVector& SolverUtils::GeoPrim::CVector::operator*= (double num) inline
Definition at line 334 of file GeoPrimitives.H.
References V.
     {
       V[0] *= num;
       V[1] *= num;
       V[2] *= num;
       return(*this);
     };
CVector SolverUtils::GeoPrim::CVector::operator+ (const CVector & v2) const inline
Definition at line 371 of file GeoPrimitives.H.
References V.
     {
       CVector v(V[0] + v2.V[0], V[1] + v2.V[1], V[2] + v2.V[2]);
       return(v);
     };
CVector& SolverUtils::GeoPrim::CVector::operator+= (const CVector & v2) inline
Definition at line 380 of file GeoPrimitives.H.
References V.
     {
       V[0] += v2.V[0];
       V[1] += v2.V[1];
       V[2] += v2.V[2];
       return(*this);
     };
CVector& SolverUtils::GeoPrim::CVector::operator+= (const CPoint & p) inline
Definition at line 387 of file GeoPrimitives.H.
References V, SolverUtils::GeoPrim::CPoint::x(), SolverUtils::GeoPrim::CPoint::y(), and SolverUtils::GeoPrim::CPoint::z().
     {
       V[0] += p.x();
       V[1] += p.y();
       V[2] += p.z();
       return(*this);
     };
CVector SolverUtils::GeoPrim::CVector::operator- (const CVector & v2) const inline
Definition at line 376 of file GeoPrimitives.H.
     {
       return((*this) + (-1.0 * v2));
     };
CVector& SolverUtils::GeoPrim::CVector::operator-= (const CVector & v2) inline
Definition at line 394 of file GeoPrimitives.H.
References copy().
     {
       return(copy((*this) - v2));
     };
bool SolverUtils::GeoPrim::CVector::operator< (const CVector & v) const inline
Definition at line 453 of file GeoPrimitives.H.
References norm().
     {
       return (norm() < v.norm());
     };
bool SolverUtils::GeoPrim::CVector::operator<= (const CVector & v) const inline
Definition at line 461 of file GeoPrimitives.H.
     {
       return ( (*this < v) ||
                (*this == v));
     };
CVector& SolverUtils::GeoPrim::CVector::operator= (const CVector & v2) inline
Definition at line 356 of file GeoPrimitives.H.
References copy().
     {
       return(copy(v2));
     };
CVector& SolverUtils::GeoPrim::CVector::operator= (const CPoint & p) inline
Definition at line 360 of file GeoPrimitives.H.
References V, SolverUtils::GeoPrim::CPoint::x(), SolverUtils::GeoPrim::CPoint::y(), and SolverUtils::GeoPrim::CPoint::z().
     {
       V[0] = p.x();
       V[1] = p.y();
       V[2] = p.z();
       return(*this);
     };
bool SolverUtils::GeoPrim::CVector::operator== (const CVector & v) const inline
Definition at line 447 of file GeoPrimitives.H.
References SolverUtils::GeoPrim::TOL, and V.
     {
       return( (fabs(V[0] - v.V[0]) < TOL) &&
               (fabs(V[1] - v.V[1]) < TOL) &&
               (fabs(V[2] - v.V[2]) < TOL) );
     };
bool SolverUtils::GeoPrim::CVector::operator> (const CVector & v) const inline
Definition at line 457 of file GeoPrimitives.H.
References norm().
     {
       return (norm() > v.norm());
     };
bool SolverUtils::GeoPrim::CVector::operator>= (const CVector & v) const inline
Definition at line 466 of file GeoPrimitives.H.
     {
       return ( (*this > v) ||
                (*this == v) );
     };
const double& SolverUtils::GeoPrim::CVector::operator[] (unsigned int i) const inline
Definition at line 437 of file GeoPrimitives.H.
References V.
     {
       if(i > 2) i = 0;
       return(V[i]);
     };
double& SolverUtils::GeoPrim::CVector::operator[] (unsigned int i) inline
Definition at line 442 of file GeoPrimitives.H.
References V.
     {
       if(i > 2) i = 0;
       return(V[i]);
     };
CVector SolverUtils::GeoPrim::CVector::unit () const inline
Definition at line 314 of file GeoPrimitives.H.
References norm(), and V.
Referenced by SolverUtils::GeoPrim::CLine::has_point(), and SolverUtils::GeoPrim::CPlane::operator==().
     {
       CVector v(*this);
       double n = norm();
       v.V[0] /= n;
       v.V[1] /= n;
       v.V[2] /= n;
       return(v);
     };
double& SolverUtils::GeoPrim::CVector::x () inline
Definition at line 398 of file GeoPrimitives.H.
References V.
Referenced by SolverUtils::GeoPrim::CPlane::A(), SolverUtils::GeoPrim::CBox::around(), SolverUtils::GeoPrim::C3Vector::C3Vector(), SolverUtils::GeoPrim::CPlane::contains_point(), SolverUtils::GeoPrim::CPlane::CPlane(), CVector(), SolverUtils::GeoPrim::CPlane::D(), SolverUtils::GeoPrim::Distance(), SolverUtils::Mesh::GenericElement::dshape_func(), init(), SolverUtils::Mesh::GenericCell_2::interpolate(), SolverUtils::Mesh::GenericElement::interpolate(), SolverUtils::Mesh::GenericElement::jacobian(), SolverUtils::GeoPrim::operator<<(), SolverUtils::Mesh::GenericElement::shape_func(), SolverUtils::GeoPrim::CBox::size(), and SolverUtils::GeoPrim::Transpose_2x3().
     {
       return(V[0]);
     };
double SolverUtils::GeoPrim::CVector::x () const inline
Definition at line 402 of file GeoPrimitives.H.
References V.
     {
       return(V[0]);
     };
CVector& SolverUtils::GeoPrim::CVector::x (double i) inline
Definition at line 406 of file GeoPrimitives.H.
References V.
     {
       V[0] = i;
       return(*this);
     };
double& SolverUtils::GeoPrim::CVector::y () inline
Definition at line 411 of file GeoPrimitives.H.
References V.
Referenced by SolverUtils::GeoPrim::CBox::around(), SolverUtils::GeoPrim::CPlane::B(), SolverUtils::GeoPrim::C3Vector::C3Vector(), SolverUtils::GeoPrim::CPlane::contains_point(), CVector(), SolverUtils::GeoPrim::CPlane::D(), SolverUtils::GeoPrim::Distance(), SolverUtils::Mesh::GenericElement::dshape_func(), init(), SolverUtils::Mesh::GenericCell_2::interpolate(), SolverUtils::Mesh::GenericElement::interpolate(), SolverUtils::Mesh::GenericElement::jacobian(), SolverUtils::GeoPrim::operator<<(), SolverUtils::Mesh::GenericElement::shape_func(), SolverUtils::GeoPrim::CBox::size(), and SolverUtils::GeoPrim::Transpose_2x3().
     {
       return(V[1]);
     };
double SolverUtils::GeoPrim::CVector::y () const inline
Definition at line 415 of file GeoPrimitives.H.
References V.
     {
       return(V[1]);
     };
CVector& SolverUtils::GeoPrim::CVector::y (double i) inline
Definition at line 419 of file GeoPrimitives.H.
References V.
     {
       V[1] = i;
       return(*this);
     };
double& SolverUtils::GeoPrim::CVector::z () inline
Definition at line 424 of file GeoPrimitives.H.
References V.
Referenced by SolverUtils::GeoPrim::CBox::around(), SolverUtils::GeoPrim::CPlane::C(), SolverUtils::GeoPrim::C3Vector::C3Vector(), SolverUtils::GeoPrim::CPlane::contains_point(), CVector(), SolverUtils::GeoPrim::CPlane::D(), SolverUtils::GeoPrim::Distance(), SolverUtils::Mesh::GenericElement::dshape_func(), init(), SolverUtils::Mesh::GenericElement::interpolate(), SolverUtils::Mesh::GenericElement::jacobian(), SolverUtils::GeoPrim::operator<<(), SolverUtils::Mesh::GenericElement::shape_func(), SolverUtils::GeoPrim::CBox::size(), and SolverUtils::GeoPrim::Transpose_2x3().
     {
       return(V[2]);
     };
double SolverUtils::GeoPrim::CVector::z () const inline
Definition at line 428 of file GeoPrimitives.H.
References V.
     {
       return(V[2]);
     };
CVector& SolverUtils::GeoPrim::CVector::z (double i) inline
Definition at line 432 of file GeoPrimitives.H.
References V.
     {
       V[2] = i;
       return(*this);
     };
Friends And Related Function Documentation
CVector operator* (double scalar, const CVector & v) friend
Definition at line 169 of file GeoPrimitives.C.
   {
     GeoPrim::CVector rv(v);
     return(rv *= scalar);
   }
std::ostream& operator<< (std::ostream & oS, const CVector & v) friend
Definition at line 103 of file GeoPrimitives.C.
   {
     oS << v.x() << "  " << v.y() << "  " << v.z();
     return(oS);
   }
std::istream& operator>> (std::istream & iS, GeoPrim::CVector & v) friend
Definition at line 110 of file GeoPrimitives.C.
   {
     iS >> v[0] >> v[1] >> v[2];
     return(iS);
   }
Member Data Documentation
double SolverUtils::GeoPrim::CVector::V[3] protected
Definition at line 218 of file GeoPrimitives.H.
Referenced by copy(), CVector(), init(), mag2(), norm(), normalize(), operator%(), operator*(), operator*=(), operator+(), operator+=(), operator=(), operator==(), operator[](), unit(), x(), y(), and z().
The documentation for this class was generated from the following file:
GeoPrimitives.H