IMPACT: CopyBflagFromBurn Class Reference
CopyBflagFromBurn Class Reference
Detailed Description
Definition at line 233 of file basic_actions.h.
#include <basic_actions.h>
Public Member Functions
CopyBflagFromBurn (BurnAgent *bag)
void init (double t)
void run (double t, double dt, double alpha)
Public Member Functions inherited from Action
Action (void *p=0, const char *name=NULL)
Action (int n, const char **at, int *i=NULL, void *p=0, const char *name=NULL)
Action (int n, const std::string at[], int *i=NULL, void *p=0, const char *name=NULL)
virtual ~Action ()
virtual void declare (Scheduler &)
virtual void finalize ()
virtual const char * name ()
void set_name (const char *name)
virtual void print (FILE *f)
virtual void print_toposort (FILE *f)
virtual void schedule ()
Private Attributes
BurnAgent * bagent
std::string parent_bflag
std::string burn_bflag
Additional Inherited Members
Protected Types inherited from Action
enum { IN =1, OUT =2, INOUT =3 }
Protected Member Functions inherited from Action
int get_dataitem_handle (int i)
int get_dataitem_handle_const (int i)
int get_dataitem_handle (const std::string str)
void set_attr (int n, const std::string at[], int *id=NULL)
void set_attr (int n, const char *at[], int *id=NULL)
void set_io (int n, const int *io)
void set_io (const char *io)
int get_io (int i)
Protected Attributes inherited from Action
const char * action_name
char ** attr
int * idx
int count
void * usr_ptr
std::vector< int > inout
Constructor & Destructor Documentation
CopyBflagFromBurn::CopyBflagFromBurn (BurnAgent * bag)
Definition at line 833 of file basic_actions.C.
References Action::set_attr(), and Action::set_io().
                                                   :
                    Action(0, (const char**)NULL, NULL, NULL, "CopyBflagFromBurn"),
                    bagent(bag)
 {
   set_io( 0, (int *)NULL);
   set_attr(0, (const char**)NULL);
 }
Member Function Documentation
void CopyBflagFromBurn::init (double t) virtual
Reimplemented from Action.
Definition at line 842 of file basic_actions.C.
References bagent, burn_bflag, Agent::get_surface_window(), parent_bflag, and BurnAgent::parentWin.
{
   burn_bflag = bagent->get_surface_window()+".bflag";
   parent_bflag = bagent->parentWin+".bflag";
 }
void CopyBflagFromBurn::run (double t, double dt, double alpha) virtual
Reimplemented from Action.
Definition at line 847 of file basic_actions.C.
References bagent, burn_bflag, COM_copy_dataitem(), Coupling::get_control_param(), Agent::get_coupling(), BurnAgent::ignmodel, Control_parameters::init_time, Coupling::initial_start(), MAN_DEBUG, and parent_bflag.
{
   MAN_DEBUG(2, ("Rocman: CopyBflagFromBurn::run() with t:%e dt:%e.\n", t, dt));
   if (!bagent->get_coupling()->initial_start() &&
       (bagent->ignmodel || t == bagent->get_coupling()->get_control_param()->init_time)) {
     COM_copy_dataitem( parent_bflag.c_str(), burn_bflag.c_str());
   }
 }
Member Data Documentation
BurnAgent* CopyBflagFromBurn::bagent private
Definition at line 239 of file basic_actions.h.
Referenced by init(), and run().
std::string CopyBflagFromBurn::burn_bflag private
Definition at line 240 of file basic_actions.h.
Referenced by init(), and run().
std::string CopyBflagFromBurn::parent_bflag private
Definition at line 240 of file basic_actions.h.
Referenced by init(), and run().
The documentation for this class was generated from the following files:
basic_actions.h
basic_actions.C