IMPACT: IMPACT::ParallelTestingObject< CommType, ResultsType > Class Template Reference
IMPACT::ParallelTestingObject< CommType, ResultsType > Class Template Reference
Project-specific parallel testing object.
Detailed Description
template<typename CommType, typename ResultsType>
class IMPACT::ParallelTestingObject< CommType, ResultsType >
The project-specific parallel testing object encapsulates all parallel tests for the project. This is the interface to all "in-core" parallel testing available for the given project. It implements the interface given by IMPACT::TestingObject and has an IRAD::Comm::CommunicatorObject for parallel capabilities.
Definition at line 310 of file IMPACTTest.H.
#include <IMPACTTest.H>
Public Member Functions
ParallelTestingObject (CommType &incomm)
Constructor with incoming communicator.
CommType & GetCommunicator ()
virtual void Epilogue ()
Tears down the testing fixtures if needed.
virtual void Prologue ()
Sets up the data fixtures for the tests.
virtual void Test__ParallelTrapezoidQuadrature (ResultsType &result)
Parallel test for IMPACT::TrapezoidQuadrature.
virtual void Test__ParallelMidPointQuadrature (ResultsType &result)
Parallel test for IMPACT::MidPointQuadrature.
virtual void Process (ResultsType &result)
Runs all tests implemented by the IMPACT::TestingObject.
virtual void RunTest (const std::string &name, ResultsType &result)
Runs a test specified by name.
virtual void ProcessTests (std::list< std::string > &test_names, ResultsType &result)
Runs a list of tests specified by name.
Protected Attributes
CommType _communicator
The CommunicatorObject for the parallel testing object.
std::vector< int > N
A set of values for testing quadrature methods.
Additional Inherited Members
Private Member Functions inherited from IMPACT::TestingObject< ResultsType >
TestingObject ()
Default constructor.
double F1 (double x)
Simple test function fixture returns .
double F2 (double x)
Simple test function fixture returns .
virtual void Test__ExampleFunction (ResultsType &result)
Test for IMPACT::ExampleFunction.
virtual void Test__TrapezoidQuadrature (ResultsType &result)
Test for IMPACT::TrapezoidQuadrature.
virtual void Test__MidPointQuadrature (ResultsType &result)
Test for IMPACT::MidPointQuadrature.
Private Attributes inherited from IMPACT::TestingObject< ResultsType >
std::string ExampleTestFixture
A sample string test fixture.
std::vector< int > N
A set of values for testing quadrature methods.
Constructor & Destructor Documentation
template<typename CommType, typename ResultsType> IMPACT::ParallelTestingObject< CommType, ResultsType >::ParallelTestingObject (CommType & incomm) inline
Definition at line 327 of file IMPACTTest.H.
                                             :
       TestingObject<ResultsType>(), _communicator(incomm) {};
Member Function Documentation
template<typename CommType, typename ResultsType> virtual void IMPACT::ParallelTestingObject< CommType, ResultsType >::Epilogue () inline virtual
Reimplemented from IMPACT::TestingObject< ResultsType >.
Definition at line 334 of file IMPACTTest.H.
Referenced by IMPACT::ParallelTestingObject< CommType, ResultsType >::Process(), and IMPACT::ParallelTestingObject< CommType, ResultsType >::ProcessTests().
 {};
template<typename CommType, typename ResultsType> CommType& IMPACT::ParallelTestingObject< CommType, ResultsType >::GetCommunicator () inline
Definition at line 329 of file IMPACTTest.H.
References IMPACT::ParallelTestingObject< CommType, ResultsType >::_communicator.
 { return(_communicator); };
template<typename CommType, typename ResultsType> virtual void IMPACT::ParallelTestingObject< CommType, ResultsType >::Process (ResultsType & result) inline virtual
Parameters
result IMPACT::TestResults object to store test results.
Reimplemented from IMPACT::TestingObject< ResultsType >.
Definition at line 648 of file IMPACTTest.H.
References IMPACT::ParallelTestingObject< CommType, ResultsType >::Epilogue(), IMPACT::ParallelTestingObject< CommType, ResultsType >::Prologue(), IMPACT::ParallelTestingObject< CommType, ResultsType >::Test__ParallelMidPointQuadrature(), and IMPACT::ParallelTestingObject< CommType, ResultsType >::Test__ParallelTrapezoidQuadrature().
Referenced by IMPACT::ParallelTest().
{
       Prologue();
       Test__ParallelTrapezoidQuadrature(result);
       Test__ParallelMidPointQuadrature(result);
       Epilogue();
     }
template<typename CommType, typename ResultsType> virtual void IMPACT::ParallelTestingObject< CommType, ResultsType >::ProcessTests (std::list< std::string > & test_names, ResultsType & result) inline virtual
Parameters
test_names list of string test names
result IMPACT::TestResults object to store test results.
Reimplemented from IMPACT::TestingObject< ResultsType >.
Definition at line 675 of file IMPACTTest.H.
References IMPACT::ParallelTestingObject< CommType, ResultsType >::Epilogue(), IMPACT::ParallelTestingObject< CommType, ResultsType >::Prologue(), and IMPACT::ParallelTestingObject< CommType, ResultsType >::RunTest().
{
       Prologue();
       std::list<std::string>::iterator tni = test_names.begin();
       while(tni != test_names.end())
         RunTest(*tni++,result);
       Epilogue();
     }
template<typename CommType, typename ResultsType> virtual void IMPACT::ParallelTestingObject< CommType, ResultsType >::Prologue () inline virtual
This function gives the object a chance to allocate and set up any "fixtures" before the tests are run.
Reimplemented from IMPACT::TestingObject< ResultsType >.
Definition at line 343 of file IMPACTTest.H.
References IMPACT::ParallelTestingObject< CommType, ResultsType >::_communicator, and IMPACT::ParallelTestingObject< CommType, ResultsType >::N.
Referenced by IMPACT::ParallelTestingObject< CommType, ResultsType >::Process(), and IMPACT::ParallelTestingObject< CommType, ResultsType >::ProcessTests().
{
       for(int i = _communicator.Size();i <= 1000000;i*=2) N.push_back(i);
     };
template<typename CommType, typename ResultsType> virtual void IMPACT::ParallelTestingObject< CommType, ResultsType >::RunTest (const std::string & name, ResultsType & result) inline virtual
Parameters
name String name of the test to run.
result IMPACT::TestResults object to store test results.
Reimplemented from IMPACT::TestingObject< ResultsType >.
Definition at line 661 of file IMPACTTest.H.
References IMPACT::ParallelTestingObject< CommType, ResultsType >::Test__ParallelMidPointQuadrature(), and IMPACT::ParallelTestingObject< CommType, ResultsType >::Test__ParallelTrapezoidQuadrature().
Referenced by IMPACT::ParallelTest(), and IMPACT::ParallelTestingObject< CommType, ResultsType >::ProcessTests().
     {
       if(name == "ParallelTrapezoidQuadrature")
         Test__ParallelTrapezoidQuadrature(result);
       if(name == "ParallelMidPointQuadrature")
         Test__ParallelMidPointQuadrature(result);
     }
template<typename CommType, typename ResultsType> virtual void IMPACT::ParallelTestingObject< CommType, ResultsType >::Test__ParallelMidPointQuadrature (ResultsType & result) inline virtual
Parameters
result IMPACT::TestResults object to store test results.
This function implements a simple parallel test of the function IMPACT::MidPointQuadrature - which is designed to integrate a function, f, over an n-way partitioned interval in parallel.
The test first makes sure that the method integrates a linear function exactly, and then that the error term has the proper dependence on the spacings. Then the parallel scaling of the algorithm is checked by running on subsets of the total number of processors and checking time-to-solution.
Definition at line 508 of file IMPACTTest.H.
References IMPACT::ParallelTestingObject< CommType, ResultsType >::_communicator, IMPACT::TestFixture::F1(), IMPACT::TestFixture::F2(), IMPACT::MidPointQuadrature(), and IMPACT::ParallelTestingObject< CommType, ResultsType >::N.
Referenced by IMPACT::ParallelTestingObject< CommType, ResultsType >::Process(), and IMPACT::ParallelTestingObject< CommType, ResultsType >::RunTest().
{
       std::ostringstream Ostr;
       int fixed_n = 1000000;
       int rank  = _communicator.Rank();
       int nproc = _communicator.Size();
       double Ii = 0.0;
       bool runs = true;
       bool accurate = true;
       bool order2 = true;
       bool scales = true;
       std::vector<double> E;
       std::vector<double> times;
       for(int i = 1;i <= nproc;i*=nproc){
         CommType subcomm;
         int color = (rank < i);
         _communicator.Split(color,rank,subcomm);
         int nproc_color = subcomm.Size();
         double time0 = IRAD::Profiler::Time();
         if(color){
           Ii = 0.0;
           for(int j = 0;j < 200;j++){
             if(runs){
               try {
                 Ii += IMPACT::MidPointQuadrature(TestFixture::F1,0,1,fixed_n);
               } catch (...) {
                 subcomm.SetExit(1);
               }
               if(subcomm.Check())
                 runs = false;
             }
           }
           if(runs){
             double Itot = 0.0;
             subcomm.AllReduce(Ii, Itot,IRAD::Comm::DTDOUBLE, IRAD::Comm::SUMOP);
             double error = 0.0;
             error = std::abs(Itot - (200*nproc_color));
             accurate = (error < 1e-14);
             order2 = accurate;
           }
         }
         times.push_back(IRAD::Profiler::Time() - time0);
         if(nproc == 1)
           break;
       }
       if(!rank){
         double dt = *times.rbegin() - *times.begin();
         double percent_change = dt/(*times.begin());
         scales = (percent_change < (nproc*.005));
         // std::cout << "Weak scaling timings:" << std::endl;
         // std::vector<double>::iterator ti = weak_times.begin();
         // while(ti != weak_times.end()){
         //   std::cout << ti-weak_times.begin()+1 << "   "
         //             << *ti << std::endl;
         //   ti++;
         // }
       }
       result.UpdateResult("ParallelMidPointQuadrature:Runs",runs);
       result.UpdateResult("ParallelMidPointQuadrature:Accurate",accurate);
       if(nproc > 1) // only report scaling results for nproc > 1
         result.UpdateResult("ParallelMidPointQuadrature:WeakScaling",scales);
       times.resize(0);
       if(nproc > 1){ // only do scaling test if nproc > 1
         for(int i = 1;i <= nproc;i*=nproc){
           CommType subcomm;
           int color = (rank < i);
           _communicator.Split(color,rank,subcomm);
           int nproc_color = subcomm.Size();
           double time0 = IRAD::Profiler::Time();
           if(color){
             int npart = *N.rbegin()/nproc_color;
             Ii = 0.0;
             for(int j = 0;j < 200;j++){
               if(runs){
                 try {
                   Ii += IMPACT::MidPointQuadrature(TestFixture::F1,0,1,npart);
                 } catch (...) {
                   subcomm.SetExit(1);
                 }
                 if(subcomm.Check())
                   runs = false;
               }
             }
             if(runs){
               double Itot = 0.0;
               subcomm.AllReduce(Ii, Itot,IRAD::Comm::DTDOUBLE, IRAD::Comm::SUMOP);
               double error = 0.0;
               error = std::abs(Itot - (200*nproc_color));
               accurate = (error < 1e-14);
               order2 = accurate;
             }
           }
           times.push_back(IRAD::Profiler::Time() - time0);
         }
         if(!rank){
           double n_t = (*times.begin())/(*times.rbegin());
           double n_p = n_t - nproc;
           n_p = std::abs(n_p)/nproc;
           scales = (n_p < 2e-1);
        }
         result.UpdateResult("ParallelMidPointQuadrateure:StrongScaling",scales);
       }
       for(int i = nproc;i <= 1000000;i*=10){
         if(runs){
           Ii = 0.0;
           int n = i/nproc;
           try {
             Ii = IMPACT::MidPointQuadrature(TestFixture::F2,0,1,n);
           } catch (...) {
             _communicator.SetExit(1);
           }
           if(_communicator.Check())
             runs = false;
           if(runs){
             double Itot = 0.0;
             _communicator.AllReduce(Ii, Itot,IRAD::Comm::DTDOUBLE, IRAD::Comm::SUMOP);
             double error = 0.0;
             error = std::abs(Itot - nproc);
             E.push_back(error);
           }
         }
       }
       int esize = E.size();
       for(int i = 0;i < esize-1;i++){
         double e = E[i+1]/E[i];
         double n1 = .1;
         double p = std::log(e)/std::log(n1);
         p -= 2;
         p = std::abs(p);
         if(p > 1e-1){
           order2 = false;
         }
       }
       result.UpdateResult("ParallelMidPointQuadrature:Order2",order2);
     }
template<typename CommType, typename ResultsType> virtual void IMPACT::ParallelTestingObject< CommType, ResultsType >::Test__ParallelTrapezoidQuadrature (ResultsType & result) inline virtual
Parameters
result IMPACT::TestResults object to store test results.
This function implements a simple parallel test of the function IMPACT::TrapezoidQuadrature - which is designed to integrate a function, f, over an n-way partitioned interval in parallel.
The test first makes sure that the method integrates a linear function exactly, and then that the error term has the proper dependence on the spacings. Then the algorithm scaling is checked by running on subsets of the total number of processors and checking time-to-solution.
Definition at line 363 of file IMPACTTest.H.
References IMPACT::ParallelTestingObject< CommType, ResultsType >::_communicator, IMPACT::TestFixture::F1(), IMPACT::TestFixture::F2(), IMPACT::MidPointQuadrature(), IMPACT::ParallelTestingObject< CommType, ResultsType >::N, and IMPACT::TrapezoidQuadrature().
Referenced by IMPACT::ParallelTestingObject< CommType, ResultsType >::Process(), and IMPACT::ParallelTestingObject< CommType, ResultsType >::RunTest().
{
       std::ostringstream Ostr;
       int fixed_n = 1000000;
       int rank  = _communicator.Rank();
       int nproc = _communicator.Size();
       double Ii = 0.0;
       bool runs = true;
       bool accurate = true;
       bool order2 = true;
       bool scales = true;
       std::vector<double> E;
       std::vector<double> times;
       for(int i = 1;i <= nproc;i*=nproc){
         CommType subcomm;
         int color = (rank < i);
         _communicator.Split(color,rank,subcomm);
         int nproc_color = subcomm.Size();
         double time0 = IRAD::Profiler::Time();
         if(color){
           Ii = 0.0;
           for(int j = 0;j < 200;j++){
             if(runs){
               try {
                 Ii += IMPACT::TrapezoidQuadrature(TestFixture::F1,0,1,fixed_n);
               } catch (...) {
                 subcomm.SetExit(1);
               }
               if(subcomm.Check())
                 runs = false;
             }
           }
           if(runs){
             double Itot = 0.0;
             subcomm.AllReduce(Ii, Itot,IRAD::Comm::DTDOUBLE, IRAD::Comm::SUMOP);
             double error = 0.0;
             error = std::abs(Itot - (200*nproc_color));
             accurate = (error < 1e-14);
             order2 = accurate;
           }
         }
         times.push_back(IRAD::Profiler::Time() - time0);
         if(nproc == 1)
           break;
       }
       if(!rank){
         double dt = *times.rbegin() - *times.begin();
         double percent_change = dt/(*times.begin());
         scales = (percent_change < (nproc*.005));
       }
       result.UpdateResult("ParallelTrapezoidQuadrature:Runs",runs);
       result.UpdateResult("ParallelTrapezoidQuadrature:Accurate",accurate);
       if(nproc > 1) // only report scaling results when procs are more than 1.
         result.UpdateResult("ParallelTrapezoidQuadrature:WeakScaling",scales);
       times.resize(0);
       if(nproc > 1){ // If running on more than one proc, then do strong scaling test.
         for(int i = 1;i <= nproc;i*=nproc){
           CommType subcomm;
           int color = (rank < i);
           _communicator.Split(color,rank,subcomm);
           int nproc_color = subcomm.Size();
           double time0 = IRAD::Profiler::Time();
           if(color){
             int npart = *N.rbegin()/nproc_color;
             Ii = 0.0;
             for(int j = 0;j < 200;j++){
               if(runs){
                 try {
                   Ii += IMPACT::TrapezoidQuadrature(TestFixture::F1,0,1,npart);
                 } catch (...) {
                   subcomm.SetExit(1);
                 }
                 if(subcomm.Check())
                   runs = false;
               }
             }
             if(runs){
               double Itot = 0.0;
               subcomm.AllReduce(Ii, Itot,IRAD::Comm::DTDOUBLE, IRAD::Comm::SUMOP);
               double error = 0.0;
               error = std::abs(Itot - (200*nproc_color));
               accurate = (error < 1e-14);
               order2 = accurate;
             }
           }
           times.push_back(IRAD::Profiler::Time() - time0);
         }
         if(!rank){
           double n_t = (*times.begin())/(*times.rbegin());
           double n_p = n_t - nproc;
           n_p = std::abs(n_p)/nproc;
           scales = (n_p < 2e-1);
         }
         result.UpdateResult("ParallelTrapezoidQuadrateure:StrongScaling",scales);
       }
       for(int i = nproc;i <= 1000000;i*=10){
         if(runs){
           Ii = 0.0;
           int n = i/nproc;
           try {
             Ii = IMPACT::MidPointQuadrature(TestFixture::F2,0,1,n);
           } catch (...) {
             _communicator.SetExit(1);
           }
           if(_communicator.Check())
             runs = false;
           if(runs){
             double Itot = 0.0;
             _communicator.AllReduce(Ii, Itot,IRAD::Comm::DTDOUBLE, IRAD::Comm::SUMOP);
             double error = 0.0;
             error = std::abs(Itot - nproc);
             E.push_back(error);
           }
         }
       }
       int esize = E.size();
       for(int i = 0;i < esize-1;i++){
         double e = E[i+1]/E[i];
         double n1 = .1;
         double p = std::log(e)/std::log(n1);
         p -= 2;
         p = std::abs(p);
         if(p > 1e-1){
           order2 = false;
         }
       }
       result.UpdateResult("ParallelTrapezoidQuadrature:Order2",order2);
     }
Member Data Documentation
template<typename CommType, typename ResultsType> CommType IMPACT::ParallelTestingObject< CommType, ResultsType >::_communicator protected
Definition at line 318 of file IMPACTTest.H.
Referenced by IMPACT::ParallelTestingObject< CommType, ResultsType >::GetCommunicator(), IMPACT::ParallelTestingObject< CommType, ResultsType >::Prologue(), IMPACT::ParallelTestingObject< CommType, ResultsType >::Test__ParallelMidPointQuadrature(), and IMPACT::ParallelTestingObject< CommType, ResultsType >::Test__ParallelTrapezoidQuadrature().
template<typename CommType, typename ResultsType> std::vector<int> IMPACT::ParallelTestingObject< CommType, ResultsType >::N protected
Definition at line 322 of file IMPACTTest.H.
Referenced by IMPACT::ParallelTestingObject< CommType, ResultsType >::Prologue(), IMPACT::ParallelTestingObject< CommType, ResultsType >::Test__ParallelMidPointQuadrature(), and IMPACT::ParallelTestingObject< CommType, ResultsType >::Test__ParallelTrapezoidQuadrature().
The documentation for this class was generated from the following file:
IMPACTTest.H