IMPACT: COM::TransferSolver Class Reference
COM::TransferSolver Class Reference
Detailed Description
Definition at line 68 of file COMTest.H.
#include <COMTest.H>
Public Member Functions
void Init (const std::string &filename)
~TransferSolver ()
int NNodes ()
int NElem ()
std::vector< double > & NodeCoordinates1 ()
std::vector< double > & NodeCoordinates2 ()
std::vector< double > & CellCoordinates1 ()
std::vector< double > & CellCoordinates2 ()
std::vector< double > & NodeFunction1 ()
std::vector< double > & NodeFunction2 ()
std::vector< double > & CellFunction1 ()
std::vector< double > & CellFunction2 ()
void Setup (const std::string &meshString, const std::string &solverName, const std::string &meshName)
Public Member Functions inherited from SolverUtils::FEM::SolverAgent
const FEM::SolutionData & Solution () const
FEM::SolutionData & Solution ()
const Mesh::UnstructuredMesh & Mesh () const
Mesh::UnstructuredMesh & Mesh ()
void ReadMeshFromStream (std::istream &Istr)
void WriteMeshToStream (std::ostream &Ostr)
void ReadCoordsFromStream (std::istream &Istr)
void WriteCoordsToStream (std::ostream &Ostr)
void ReadSolnMetaFromStream (std::istream &Istr)
void WriteSolnMetaToStream (std::ostream &Ostr)
void CreateSoln ()
void ReadSolnFromStream (std::istream &Istr, const std::string &name)
void WriteSolnToStream (std::ostream &Ostr, const std::string &name)
std::ostream & ReportMeshToStream (std::ostream &Ostr)
~SolverAgent ()
Protected Attributes
std::string name
std::vector< double > nodeCoordinates1
std::vector< double > nodeCoordinates2
std::vector< double > cellCoordinates1
std::vector< double > cellCoordinates2
std::vector< double > nodeFunction1
std::vector< double > nodeFunction2
std::vector< double > cellFunction1
std::vector< double > cellFunction2
int nNodes
int nElem
Constructor & Destructor Documentation
COM::TransferSolver::~TransferSolver () inline
Definition at line 73 of file COMTest.H.
References name, and SolverUtils::UnRegisterSolver().
 {SolverUtils::UnRegisterSolver(name);};
Member Function Documentation
std::vector<double>& COM::TransferSolver::CellCoordinates1 () inline
Definition at line 92 of file COMTest.H.
References cellCoordinates1.
 {return(cellCoordinates1);};
std::vector<double>& COM::TransferSolver::CellCoordinates2 () inline
Definition at line 93 of file COMTest.H.
References cellCoordinates2.
 {return(cellCoordinates2);};
std::vector<double>& COM::TransferSolver::CellFunction1 () inline
Definition at line 97 of file COMTest.H.
References cellFunction1.
 {return(cellFunction1);};
std::vector<double>& COM::TransferSolver::CellFunction2 () inline
Definition at line 98 of file COMTest.H.
References cellFunction2.
 {return(cellFunction2);};
void COM::TransferSolver::Init (const std::string & filename)
int COM::TransferSolver::NElem () inline
Definition at line 89 of file COMTest.H.
References SolverUtils::FEM::SolverAgent::Mesh().
 {return(Mesh().con.Nelem());};
int COM::TransferSolver::NNodes () inline
Definition at line 88 of file COMTest.H.
References SolverUtils::FEM::SolverAgent::Mesh().
 {return(Mesh().nc.NNodes());};
std::vector<double>& COM::TransferSolver::NodeCoordinates1 () inline
Definition at line 90 of file COMTest.H.
References nodeCoordinates1.
Referenced by COM::TestingObject< ResultsType >::Test__LinearDataTransfer(), and COM::TestingObject< ResultsType >::Test__QuadraticDataTransfer().
 {return(nodeCoordinates1);};
std::vector<double>& COM::TransferSolver::NodeCoordinates2 () inline
Definition at line 91 of file COMTest.H.
References nodeCoordinates2.
Referenced by COM::TestingObject< ResultsType >::Test__LinearDataTransfer(), and COM::TestingObject< ResultsType >::Test__QuadraticDataTransfer().
 {return(nodeCoordinates2);};
std::vector<double>& COM::TransferSolver::NodeFunction1 () inline
Definition at line 95 of file COMTest.H.
References nodeFunction1.
 {return(nodeFunction1);};
std::vector<double>& COM::TransferSolver::NodeFunction2 () inline
Definition at line 96 of file COMTest.H.
References nodeFunction2.
 {return(nodeFunction2);};
void COM::TransferSolver::Setup (const std::string & meshString, const std::string & solverName, const std::string & meshName) inline
Definition at line 100 of file COMTest.H.
References SolverUtils::FEM::SolutionMetaData::AddField(), cellCoordinates1, cellCoordinates2, cellFunction1, cellFunction2, SolverUtils::Mesh::UnstructuredMesh::con, SolverUtils::FEM::SolverAgent::CreateSoln(), SolverUtils::FEM::SolverAgent::Mesh(), SolverUtils::MeshUtils::meshgen2d(), SolverUtils::FEM::SolutionData::Meta(), name, SolverUtils::Mesh::UnstructuredMesh::nc, nElem, SolverUtils::Mesh::Connectivity::Nelem(), nNodes, SolverUtils::Mesh::NodalCoordinates::NNodes(), nodeCoordinates1, nodeCoordinates2, nodeFunction1, nodeFunction2, SolverUtils::RegisterSolver(), SolverUtils::FEM::SolutionData::SetFieldBuffer(), SolverUtils::FEM::SolverAgent::Solution(), and SolverUtils::Mesh::WriteVTKToStream().
Referenced by COM::TestingObject< ResultsType >::Test__LinearDataTransfer(), and COM::TestingObject< ResultsType >::Test__QuadraticDataTransfer().
{
       std::istringstream meshStream(meshString);
       SolverUtils::MeshUtils::meshgen2d(meshStream,Mesh());
       // Write the test mesh for use in later tests
       std::ofstream Ouf;
       Ouf.open((meshName+".mesh").c_str());
       Ouf << Mesh().nc << std::endl << Mesh().con << std::endl;
       Ouf.close();
       std::ofstream vtkOut;
       vtkOut.open((meshName+".vtk").c_str());
       SolverUtils::Mesh::WriteVTKToStream(meshName,Mesh(),vtkOut);
       vtkOut.close();
       int nNodes = Mesh().nc.NNodes();
       int nElem  = Mesh().con.Nelem();
       nodeCoordinates1.resize(3*nNodes);
       nodeCoordinates2.resize(3*nNodes);
       cellCoordinates1.resize(3*nElem);
       cellCoordinates2.resize(3*nElem);
       nodeFunction1.resize(nNodes);
       cellFunction1.resize(nElem);
       nodeFunction2.resize(nNodes);
       cellFunction2.resize(nElem);
       Solution().Meta().AddField("nodeCoordinates1",'n',3,8,"m");
       Solution().Meta().AddField("nodeCoordinates2",'n',3,8,"m");
       Solution().Meta().AddField("cellCoordinates1",'c',3,8,"m");
       Solution().Meta().AddField("cellCoordinates2",'c',3,8,"m");
       Solution().Meta().AddField("cellFunction1",'c',1,8,"m");
       Solution().Meta().AddField("cellFunction2",'c',1,8,"m");
       Solution().Meta().AddField("nodeFunction1",'n',1,8,"m");
       Solution().Meta().AddField("nodeFunction2",'n',1,8,"m");
       CreateSoln();
       Solution().SetFieldBuffer("nodeCoordinates1",nodeCoordinates1);
       Solution().SetFieldBuffer("nodeCoordinates2",nodeCoordinates2);
       Solution().SetFieldBuffer("cellCoordinates1",cellCoordinates1);
       Solution().SetFieldBuffer("cellCoordinates2",cellCoordinates2);
       Solution().SetFieldBuffer("nodeFunction1",nodeFunction1);
       Solution().SetFieldBuffer("nodeFunction2",nodeFunction2);
       Solution().SetFieldBuffer("cellFunction1",cellFunction1);
       Solution().SetFieldBuffer("cellFunction2",cellFunction2);
       name = solverName;
       SolverUtils::RegisterSolver(solverName,*this);
     }
Member Data Documentation
std::vector<double> COM::TransferSolver::cellCoordinates1 protected
Definition at line 78 of file COMTest.H.
Referenced by CellCoordinates1(), and Setup().
std::vector<double> COM::TransferSolver::cellCoordinates2 protected
Definition at line 79 of file COMTest.H.
Referenced by CellCoordinates2(), and Setup().
std::vector<double> COM::TransferSolver::cellFunction1 protected
Definition at line 82 of file COMTest.H.
Referenced by CellFunction1(), and Setup().
std::vector<double> COM::TransferSolver::cellFunction2 protected
Definition at line 83 of file COMTest.H.
Referenced by CellFunction2(), and Setup().
std::string COM::TransferSolver::name protected
Definition at line 73 of file COMTest.H.
Referenced by Setup(), and ~TransferSolver().
int COM::TransferSolver::nElem protected
Definition at line 85 of file COMTest.H.
Referenced by Setup().
int COM::TransferSolver::nNodes protected
Definition at line 84 of file COMTest.H.
Referenced by Setup().
std::vector<double> COM::TransferSolver::nodeCoordinates1 protected
Definition at line 76 of file COMTest.H.
Referenced by NodeCoordinates1(), and Setup().
std::vector<double> COM::TransferSolver::nodeCoordinates2 protected
Definition at line 77 of file COMTest.H.
Referenced by NodeCoordinates2(), and Setup().
std::vector<double> COM::TransferSolver::nodeFunction1 protected
Definition at line 80 of file COMTest.H.
Referenced by NodeFunction1(), and Setup().
std::vector<double> COM::TransferSolver::nodeFunction2 protected
Definition at line 81 of file COMTest.H.
Referenced by NodeFunction2(), and Setup().
The documentation for this class was generated from the following file:
COMTest.H