IMPACT: SolverUtils::GeoPrim::C3LineSegment Class Reference
SolverUtils::GeoPrim::C3LineSegment Class Reference
Detailed Description
Definition at line 1507 of file GeoPrimitives.H.
#include <GeoPrimitives.H>
Public Member Functions
C3LineSegment ()
C3LineSegment (const C3Point &p)
C3LineSegment (const C3Point &pb, const C3Point &pe)
double length () const
C3Vector slope () const
bool has_point (const C3Point &p3) const
C3Point & point1 ()
C3Point & point2 ()
const C3Point & point1 () const
const C3Point & point2 () const
C3LineSegment & point1 (const C3Point &p)
C3LineSegment & point2 (const C3Point &p)
Protected Attributes
C3Point p1
C3Point p2
Constructor & Destructor Documentation
SolverUtils::GeoPrim::C3LineSegment::C3LineSegment () inline
Definition at line 1512 of file GeoPrimitives.H.
       : p1(0,0,0),p2(0,0,0)
     {};
SolverUtils::GeoPrim::C3LineSegment::C3LineSegment (const C3Point & p) inline
Definition at line 1515 of file GeoPrimitives.H.
       : p1(0,0,0),p2(p)
     {};
SolverUtils::GeoPrim::C3LineSegment::C3LineSegment (const C3Point & pb, const C3Point & pe) inline
Definition at line 1518 of file GeoPrimitives.H.
       : p1(pb),p2(pe)
     {};
Member Function Documentation
bool SolverUtils::GeoPrim::C3LineSegment::has_point (const C3Point & p3) const inline
Definition at line 1531 of file GeoPrimitives.H.
References SolverUtils::GeoPrim::C3Line::has_point(), p1, p2, SolverUtils::GeoPrim::C3Point::x(), SolverUtils::GeoPrim::C3Point::y(), and SolverUtils::GeoPrim::C3Point::z().
     {
       if(p3 == p1 || p3 == p2) return true;
       if(p1 == p2) return false;
       C3Line l(p1,p2);
       if(!l.has_point(p3)) return false;
       double u;
       if(p1.x() != p2.x())
         u = (p3.x() - p1.x())/(p2.x() - p1.x());
       else if(p1.y() != p2.y())
         u = (p3.y() - p1.y())/(p2.y() - p1.y());
       else if(p1.z() != p2.z())
         u = (p3.z() - p1.z())/(p2.z() - p1.z());
       return ( u >= 0.0 && u <= 1.0 );
     };
double SolverUtils::GeoPrim::C3LineSegment::length () const inline
Definition at line 1521 of file GeoPrimitives.H.
References SolverUtils::GeoPrim::C3Vector::Norm(), p1, and p2.
     {
       C3Vector v(p1,p2);
       return(v.Norm());
     };
C3Point& SolverUtils::GeoPrim::C3LineSegment::point1 () inline
Definition at line 1546 of file GeoPrimitives.H.
References p1.
     {
       return (p1);
     };
const C3Point& SolverUtils::GeoPrim::C3LineSegment::point1 () const inline
Definition at line 1554 of file GeoPrimitives.H.
References p1.
     {
       return (p1);
     };
C3LineSegment& SolverUtils::GeoPrim::C3LineSegment::point1 (const C3Point & p) inline
Definition at line 1562 of file GeoPrimitives.H.
References p1.
     {
       p1 = p;
       return(*this);
     };
C3Point& SolverUtils::GeoPrim::C3LineSegment::point2 () inline
Definition at line 1550 of file GeoPrimitives.H.
References p2.
     {
       return (p2);
     };
const C3Point& SolverUtils::GeoPrim::C3LineSegment::point2 () const inline
Definition at line 1558 of file GeoPrimitives.H.
References p2.
     {
       return (p2);
     };
C3LineSegment& SolverUtils::GeoPrim::C3LineSegment::point2 (const C3Point & p) inline
Definition at line 1567 of file GeoPrimitives.H.
References p2.
     {
       p2 = p;
       return(*this);
     };
C3Vector SolverUtils::GeoPrim::C3LineSegment::slope () const inline
Definition at line 1526 of file GeoPrimitives.H.
References p1, and p2.
     {
       C3Vector v(p1,p2);
     return(v);
     };
Member Data Documentation
C3Point SolverUtils::GeoPrim::C3LineSegment::p1 protected
Definition at line 1509 of file GeoPrimitives.H.
Referenced by has_point(), length(), point1(), and slope().
C3Point SolverUtils::GeoPrim::C3LineSegment::p2 protected
Definition at line 1510 of file GeoPrimitives.H.
Referenced by has_point(), length(), point2(), and slope().
The documentation for this class was generated from the following file:
GeoPrimitives.H