IMPACT: RFC_Window_derived< _Pane > Class Template Reference
RFC_Window_derived< _Pane > Class Template Reference
Reusable implementation for derived class of RFC_Window_base.
Detailed Description
template<class _Pane>
class RFC_Window_derived< _Pane >
This class provides some template implementation for some useful functions that depends on the specific type of the panes. One usually should derive subclasses of RFC_Window_base by inherit from this class, but it is not required.
Definition at line 92 of file RFC_Window_base.h.
#include <RFC_Window_base.h>
Public Member Functions
const Pane & pane (const int pid) const
Get a reference to the pane with give id pid.
Pane & pane (const int pid)
std::pair< Pane *, int > get_primary (Pane *p, int vid)
Get a handle to the primary copy of a node contained in the pane p with local id vid.
std::pair< const Pane *, int > get_primary (const Pane *p, int vid) const
void panes (std::vector< Pane * > &ps)
Get a vector of local panes contained in the window.
void panes (std::vector< const Pane * > &ps) const
Public Member Functions inherited from RFC_Window_base
RFC_Window_base (Base *b, int c, MPI_Comm)
Construct an object with base b and color c.
virtual ~RFC_Window_base ()
Default destructor.
std::string name () const
The name of the window.
const RFC_Pane_base & pane (const int pid) const
RFC_Pane_base & pane (const int pid)
const COM::Window * base () const
Get a reference to the base COM::Window object.
int color () const
The color of the window for overlay or for data transfer (BLUE or GREEN).
int size_of_nodes () const
Get the total number of nodes contained the window.
int size_of_faces () const
Get the total number of faces contained the window.
int size_of_primary_nodes () const
Get the total number of nodes contained the window.
Bbox_3 get_bounding_box () const
Get the bounding box of the window.
int size_of_panes () const
Number of local panes in the window.
const DataItem * dataitem (const char *f) const
Retrieve an dataitem object from the base using the dataitem name.
void export_window (RFC_Window_base *) const
void write_tec_ascii (const char *prefix) const
Ouptut a mesh in Tecplot format.
void write_tec_sub (const char *prefix) const
Ouptut a subdivision of a mesh in Tecplot format.
void new_sdv_dataitems (const std::string &wname) const
New dataitems.
void read_sdv (const char *prefix, const char *format=NULL)
Read in local panes in native binary format or using Rocin.
void write_sdv (const char *prefix, const char *format=NULL) const
Write out panes in native binary format or using Rocout.
void build_pc_tables ()
Build the pane connectivity table.
Protected Types
typedef RFC_Window_derived< _Pane > Self
typedef RFC_Window_base Base
typedef _Pane Pane
Protected Types inherited from RFC_Window_base
enum { SDV_OFF, SDV_BINARY, SDV_HDF, SDV_CGNS }
Protected Member Functions
RFC_Window_derived (COM::Window *b, int c, MPI_Comm comm)
A constructor.
virtual ~RFC_Window_derived ()
A destructor.
void init ()
Additional Inherited Members
Public Types inherited from RFC_Window_base
typedef RFC_Window_base Self
typedef COM::Window Base
typedef COM::DataItem DataItem
typedef RFC_Pane_base Pane
typedef std::map< int, Pane * > Pane_set
Static Protected Member Functions inherited from RFC_Window_base
static std::string get_sdv_fname (const char *prefix, int pane_id, const int format=SDV_BINARY)
static const char * get_prefix_base (const char *prefix)
static int get_sdv_format (const char *format)
Protected Attributes inherited from RFC_Window_base
Base * _base
A reference to its base COM::Window object.
Pane_set _pane_set
The set of panes contained in the window.
int _verbose
int _color
MAP::Pane_communicator _map_comm
Static Protected Attributes inherited from RFC_Window_base
static const char * _bufwin_prefix = "buf_"
Member Typedef Documentation
template<class _Pane> typedef RFC_Window_base RFC_Window_derived< _Pane >::Base protected
Definition at line 630 of file RFC_Window_base.h.
template<class _Pane> typedef _Pane RFC_Window_derived< _Pane >::Pane protected
Definition at line 631 of file RFC_Window_base.h.
template<class _Pane> typedef RFC_Window_derived<_Pane> RFC_Window_derived< _Pane >::Self protected
Definition at line 629 of file RFC_Window_base.h.
Constructor & Destructor Documentation
template<class _Pane> RFC_Window_derived< _Pane >::RFC_Window_derived (COM::Window * b, int c, MPI_Comm comm) inline protected
Definition at line 634 of file RFC_Window_base.h.
                                                           : Base(b,c, comm)
   { init(); }
template<class _Pane > RFC_Window_derived< _Pane >::~RFC_Window_derived () protected virtual
Definition at line 659 of file RFC_Window_base.h.
 {}
Member Function Documentation
template<class _Pane > std::pair< _Pane *, int > RFC_Window_derived< _Pane >::get_primary (Pane * p, int vid)
Definition at line 708 of file RFC_Window_base.h.
References RFC_Pane_base::_b2v_table, RFC_Pane_base::_v2b_table, RFC_Pane_base::id(), RFC_Pane_base::is_border_node(), RFC_Pane_base::is_isolated_node(), Node_ID::node_id, and RFC_assertion.
Referenced by RFC_Pane_overlay::determine_counterparts().
{
   RFC_Pane_base::V2b_table::iterator it;
   //  points to a border halfedge.
   if ( !p->is_border_node( vid) ||
        (it = p->_v2b_table.find( vid))==p->_v2b_table.end()) {
     RFC_assertion( !p->is_isolated_node( vid));
     return std::make_pair(p, vid);
   }
   RFC_Pane_base::V2b &v2b = it->second;
   Pane &p2 =  pane( v2b.first);
   Node_ID v2( v2b.first, p2._b2v_table.find(p->id())->second[v2b.second]);
   RFC_assertion( v2 < Node_ID( p->id(), vid) || p->is_isolated_node(vid));
   RFC_assertion( !p2.is_isolated_node( v2.node_id));
   return std::make_pair( &p2, v2.node_id);
 }
template<class _Pane > std::pair< const _Pane *, int > RFC_Window_derived< _Pane >::get_primary (const Pane * p, int vid) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 730 of file RFC_Window_base.h.
{
   return const_cast<Self*>(this)->get_primary( const_cast<Pane*>(p), vid);
 }
template<class _Pane > void RFC_Window_derived< _Pane >::init () protected
Definition at line 663 of file RFC_Window_base.h.
Referenced by RFC_Window_derived< RFC_Pane_transfer >::RFC_Window_derived().
{
   std::vector< COM::Pane*>  ps;
   _base->panes( ps);
   for (std::vector< COM::Pane*>::const_iterator
          it=ps.begin(); it!=ps.end(); ++it) {
     // Insert a pane with given id
     (_pane_set[(*it)->id()] = new Pane(*it, color()))->init();
   }
 }
template<class _Pane > const _Pane & RFC_Window_derived< _Pane >::pane (const int pid) const
Definition at line 676 of file RFC_Window_base.h.
References RFC_assertion.
Referenced by RFC_Pane_overlay::determine_counterparts().
{
   Pane_set::const_iterator pit = _pane_set.find( pid);
   RFC_assertion( pit != _pane_set.end());
   return reinterpret_cast<const _Pane&>(*pit->second);
 }
template<class _Pane > _Pane & RFC_Window_derived< _Pane >::pane (const int pid)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 684 of file RFC_Window_base.h.
References RFC_assertion.
{
   Pane_set::iterator pit = _pane_set.find( pid);
   RFC_assertion( pit != _pane_set.end());
   return reinterpret_cast<_Pane&>(*pit->second);
 }
template<class _Pane > void RFC_Window_derived< _Pane >::panes (std::vector< Pane * > & ps)
Definition at line 692 of file RFC_Window_base.h.
Referenced by Overlay::associate_green_vertices(), Overlay::get_green_parent(), Transfer_base::integrate(), Transfer_base::minmax(), Overlay::number_subfaces(), Overlay::number_subnodes(), Overlay::sort_on_green_edges(), Transfer_base::Transfer_base(), Overlay::write_overlay_off(), and Overlay::write_overlay_tec().
{
   const_cast<Self*>(this)->panes( (std::vector<const Pane*>&)ps);
 }
template<class _Pane > void RFC_Window_derived< _Pane >::panes (std::vector< const Pane * > & ps) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 698 of file RFC_Window_base.h.
{
   ps.resize(0);
   ps.reserve( _pane_set.size());
   Pane_set::const_iterator it=_pane_set.begin();
   for ( ; it != _pane_set.end(); ++it)
     ps.push_back( reinterpret_cast<const Pane*>(it->second));
 }
The documentation for this class was generated from the following file:
RFC_Window_base.h