IMPACT: IRAD::Sys::fdistream Class Reference
IRAD::Sys::fdistream Class Reference
Detailed Description
Definition at line 154 of file FDUtils.H.
#include <FDUtils.H>
Public Member Functions
fdistream ()
fdistream (int fd)
int FD ()
int Init (int _fd)
Protected Attributes
Sys::fdinbuf buf
Constructor & Destructor Documentation
IRAD::Sys::fdistream::fdistream () inline
Definition at line 158 of file FDUtils.H.
 : std::istream(0) {};
IRAD::Sys::fdistream::fdistream (int fd) inline
Definition at line 159 of file FDUtils.H.
References buf.
                          : std::istream(0), buf(fd) {
         rdbuf(&buf);
       };
Member Function Documentation
int IRAD::Sys::fdistream::FD () inline
Definition at line 162 of file FDUtils.H.
References buf, and IRAD::Sys::fdinbuf::FD().
 { return(buf.FD()); };
int IRAD::Sys::fdistream::Init (int _fd) inline
Definition at line 163 of file FDUtils.H.
References buf, IRAD::Sys::fdinbuf::FD(), and IRAD::Sys::fdinbuf::Init().
Referenced by IRAD::Sys::InProcess::Execute(), SolverUtils::FEM::FDSolverAgent::FDSolverAgent(), SolverUtils::FEM::FDSolverAgent::Init(), and IRAD::Sys::InProcess::InProcess().
 { buf.Init(_fd); rdbuf(&buf); return(buf.FD());};
Member Data Documentation
Sys::fdinbuf IRAD::Sys::fdistream::buf protected
Definition at line 156 of file FDUtils.H.
Referenced by FD(), fdistream(), and Init().
The documentation for this class was generated from the following file:
FDUtils.H