IMPACT: IRAD::Util::TestResults Class Reference
IRAD::Util::TestResults Class Reference
Encapsulating class for collections of test results.
Detailed Description
Definition at line 18 of file Testing.H.
#include <Testing.H>
Public Member Functions
template<typename ValueType >
void AddResult (const std::string &name, const ValueType &result)
Add a named result to the test results.
template<typename ValueType >
void UpdateResult (const std::string &name, const ValueType &result)
Updates an existing test result.
Public Member Functions inherited from IRAD::Util::Parameters
std::string GetValue (const std::string &key) const
std::vector< std::string > GetValueVector (const std::string &key) const
Util::ParamType * ParamPtr (const std::string &key)
template<typename T >
T GetValue (const std::string &key) const
template<typename T >
std::vector< T > GetValueVector (const std::string &key) const
virtual int SetValue (const std::string &key, const std::string &value)
virtual std::istream & ReadFromStream (std::istream &Is)
virtual std::ostream & WriteToStream (std::ostream &Os) const
std::string Param (const std::string &Key) const
bool IsSet (const std::string &Key) const
virtual ~Parameters ()
Additional Inherited Members
Public Attributes inherited from std::vector< T >
T elements
STL member.
Member Function Documentation
template<typename ValueType > void IRAD::Util::TestResults::AddResult (const std::string & name, const ValueType & result) inline
Parameters
name Constant std::string reference to the test name.
result Constant reference to a <ValueType> value.
This method puts a named test result into the collection of results. The "value" is converted to a string. In general, a 0 is a false or negative result while a 1 is true or a positive result.
Definition at line 38 of file Testing.H.
References IRAD::Primitive::KeyValuePairObj< K, V >::Key(), SolverUtils::Ostr, and IRAD::Primitive::KeyValuePairObj< K, V >::Value().
       {
         Util::ParamType p;
         p.Key(name);
         std::ostringstream Ostr;
         Ostr << result;
         p.Value(Ostr.str());
         this->push_back(p);
       }
template<typename ValueType > void IRAD::Util::TestResults::UpdateResult (const std::string & name, const ValueType & result) inline
Parameters
name Constant reference to a std::string containing the test name.
result Constant reference to the <ValueType> data containing the test result.
This method is very much like AddResult except this one only replaces the value of an existing test. If the named test is not found in the results already, it is automatically added.
Definition at line 59 of file Testing.H.
References SolverUtils::Ostr.
Referenced by COM::ParallelTest(), COM::Test(), and IRAD::Util::TestObject::Test__GetNextContent().
       {
         std::ostringstream Ostr;
         Ostr << result;
         Util::TestResults::iterator _thisit = this->begin();
         while(_thisit != this->end()){
           if(_thisit->first == name){
             _thisit->second = Ostr.str();
             return;
           }
           _thisit++;
         }
         return(AddResult<ValueType>(name,result));
       }
The documentation for this class was generated from the following file:
Testing.H