IMPACT: SolverUtils::FEM::SolutionData Class Reference
SolverUtils::FEM::SolutionData Class Reference
Detailed Description
Definition at line 209 of file FieldData.H.
#include <FieldData.H>
Public Types
typedef FEM::DataBuffer DataBufferType
typedef std::vector
< DataBufferType > DataContainer
Public Member Functions
FEM::SolutionMetaData & Meta ()
const FEM::SolutionMetaData & Meta () const
DataContainer & Data ()
const DataContainer & Data () const
int Create (const Mesh::UnstructuredMesh &mesh)
int GetDataIndex (const std::string &name) const
FEM::FieldMetaData & GetFieldMetaData (const std::string &name)
DataBufferType & GetFieldData (const std::string &name)
const DataBufferType & GetFieldData (const std::string &name) const
void SetFieldBuffer (const std::string &name, void *buf)
template<class DataType >
void SetFieldBuffer (const std::string &name, std::vector< DataType > &invec)
const FEM::FieldMetaData & GetFieldMetaData (const std::string &name) const
std::ostream & WriteFieldToStream (std::ostream &OutStream, const std::string &name) const
std::istream & ReadFieldFromStream (std::istream &InStream, const std::string &name)
Private Attributes
DataContainer data
FEM::SolutionMetaData meta
Member Typedef Documentation
typedef FEM::DataBuffer SolverUtils::FEM::SolutionData::DataBufferType
Definition at line 212 of file FieldData.H.
typedef std::vector<DataBufferType> SolverUtils::FEM::SolutionData::DataContainer
Definition at line 213 of file FieldData.H.
Member Function Documentation
int SolverUtils::FEM::SolutionData::Create (const Mesh::UnstructuredMesh & mesh) inline
Definition at line 222 of file FieldData.H.
References SolverUtils::Mesh::UnstructuredMesh::con, data, meta, SolverUtils::Mesh::UnstructuredMesh::nc, SolverUtils::Mesh::Connectivity::Nelem(), and SolverUtils::Mesh::NodalCoordinates::Size().
Referenced by SolverUtils::FEM::SolverAgent::CreateSoln(), and SolverUtils::CreateSolutionFromPane().
     {
       int all_data_size = 0;
       //      if(meta.empty())
       //        return(-1);
       assert(!meta.empty());
       data.resize(meta.size());
       FEM::SolutionMetaData::iterator mdi = meta.begin();
       Mesh::IndexType number_of_cells = mesh.con.Nelem();
       Mesh::IndexType number_of_nodes = mesh.nc.Size();
       Mesh::IndexType data_index = 0;
       while(mdi != meta.end()){
         // location can be:
         // (s) - solver global
         // (m) - mesh global
         // (c) - mesh cells
         // (n) - mesh nodes
         Mesh::IndexType nitems = ((mdi->loc == 's' || mdi->loc == 'm') ? 1 :
                                    mdi->loc == 'c' ? number_of_cells :
                                    mdi->loc == 'n' ? number_of_nodes :
                                   0);
         // Masoud : commenting out non zero-sized assertion check
         /*
         if(nitems == 0){
           std::cerr << "SolutionData::Create: Error, unknown location: " << mdi->loc << std::endl;
         }
         assert(nitems > 0);
         */
         // Masoud : end
         // Total size will be the number of components (i.e. scalar = 1, vector = 2,3, etc) times
         // the number of items (i.e. number of nodes, elements, etc) times the size of each item
         Mesh::IndexType total_size = nitems * mdi->dsize * mdi->ncomp;
         all_data_size += total_size;
         data[data_index++].Allocate(nitems*mdi->ncomp,mdi->dsize);
         mdi++;
       }
       return(all_data_size);
     };
DataContainer& SolverUtils::FEM::SolutionData::Data () inline
Definition at line 220 of file FieldData.H.
References data.
Referenced by SolverUtils::AgentToPane(), SolverUtils::CreateDataItemsFromSolution(), SolverUtils::PopulateSolutionDataFromPane(), SolverUtils::PopulateSolutionMetaDataFromPane(), and SolverUtils::WriteVTKToStream().
 { return (data); };
const DataContainer& SolverUtils::FEM::SolutionData::Data () const inline
Definition at line 221 of file FieldData.H.
References data.
 { return (data); };
int SolverUtils::FEM::SolutionData::GetDataIndex (const std::string & name) const inline
Definition at line 262 of file FieldData.H.
References meta.
Referenced by GetFieldData(), ReadFieldFromStream(), SetFieldBuffer(), and WriteFieldToStream().
     {
       FEM::SolutionMetaData::const_iterator mdi = meta.begin();
       int index = 0;
       while(mdi != meta.end()){
         if(mdi++->name == name)
           return(index);
         index++;
       }
       return(-1);
     };
DataBufferType& SolverUtils::FEM::SolutionData::GetFieldData (const std::string & name) inline
Definition at line 287 of file FieldData.H.
References data, and GetDataIndex().
Referenced by COM::TestModule::ValidateDataItemAddress(), and SolverUtils::WriteVTKToStream().
     {
       int known_field = GetDataIndex(name);
       assert(known_field >= 0);
       return(data[known_field]);
     };
const DataBufferType& SolverUtils::FEM::SolutionData::GetFieldData (const std::string & name) const inline
Definition at line 294 of file FieldData.H.
References data, and GetDataIndex().
     {
       int known_field = GetDataIndex(name);
       assert(known_field >= 0);
       return(data[known_field]);
     };
FEM::FieldMetaData& SolverUtils::FEM::SolutionData::GetFieldMetaData (const std::string & name) inline
Definition at line 274 of file FieldData.H.
References meta.
     {
       FEM::SolutionMetaData::iterator mdi = meta.begin();
       while(mdi != meta.end()){
         if(mdi->name == name)
           return(*mdi);
         mdi++;
       }
       bool invalid_field_name = false;
       assert(invalid_field_name);
       return(*mdi); // never get here
     };
const FEM::FieldMetaData& SolverUtils::FEM::SolutionData::GetFieldMetaData (const std::string & name) const inline
Definition at line 316 of file FieldData.H.
References meta.
     {
       FEM::SolutionMetaData::const_iterator mdi = meta.begin();
       while(mdi != meta.end()){
         if(mdi->name == name)
           return(*mdi);
         mdi++;
       }
       bool invalid_field_name = false;
       assert(invalid_field_name);
       return(*mdi); // never get here
     };
FEM::SolutionMetaData& SolverUtils::FEM::SolutionData::Meta () inline
Definition at line 218 of file FieldData.H.
References meta.
Referenced by SolverUtils::AgentToPane(), SolverUtils::CreateDataItemsFromSolution(), COM::TestModule::InitSolver(), SolverUtils::PopulateSolutionDataFromPane(), SolverUtils::PopulateSolutionMetaDataFromPane(), SolverUtils::FEM::SolverAgent::ReadSolnMetaFromStream(), SolverUtils::FEM::FDSolverAgent::ReceiveSolnMeta(), SolverUtils::FEM::FDSolverAgent::SendSolnMeta(), COM::TransferSolver::Setup(), SolverUtils::FEM::SolverAgent::WriteSolnMetaToStream(), and SolverUtils::WriteVTKToStream().
 { return (meta); };
const FEM::SolutionMetaData& SolverUtils::FEM::SolutionData::Meta () const inline
Definition at line 219 of file FieldData.H.
References meta.
 { return (meta); };
std::istream& SolverUtils::FEM::SolutionData::ReadFieldFromStream (std::istream & InStream, const std::string & name) inline
Definition at line 340 of file FieldData.H.
References data, and GetDataIndex().
Referenced by SolverUtils::FEM::SolverAgent::ReadSolnFromStream(), and SolverUtils::FEM::FDSolverAgent::ReceiveSoln().
     {
       int known_field = GetDataIndex(name);
       assert(known_field >= 0);
       InStream >> data[known_field];
       return(InStream);
     };
void SolverUtils::FEM::SolutionData::SetFieldBuffer (const std::string & name, void * buf) inline
Definition at line 300 of file FieldData.H.
References data, and GetDataIndex().
Referenced by COM::TestModule::InitSolver(), SolverUtils::PopulateSolutionDataFromPane(), and COM::TransferSolver::Setup().
     {
       int known_field = GetDataIndex(name);
       assert(known_field >= 0);
       data[known_field].Set(buf);
     };
template<class DataType > void SolverUtils::FEM::SolutionData::SetFieldBuffer (const std::string & name, std::vector< DataType > & invec) inline
Definition at line 308 of file FieldData.H.
References data, and GetDataIndex().
     {
       int dsize = sizeof(DataType);
       int known_field = GetDataIndex(name);
       assert(known_field >= 0);
       data[known_field].Set(&invec[0],invec.size(),dsize);
     };
std::ostream& SolverUtils::FEM::SolutionData::WriteFieldToStream (std::ostream & OutStream, const std::string & name) const inline
Definition at line 330 of file FieldData.H.
References data, and GetDataIndex().
Referenced by SolverUtils::FEM::FDSolverAgent::SendSoln(), and SolverUtils::FEM::SolverAgent::WriteSolnToStream().
     {
       int known_field = GetDataIndex(name);
       assert(known_field >= 0);
       OutStream << data[known_field];
       // to endl or not to endl?
       //      OutStream << std::endl;
       return(OutStream);
     };
Member Data Documentation
DataContainer SolverUtils::FEM::SolutionData::data private
Definition at line 215 of file FieldData.H.
Referenced by Create(), Data(), GetFieldData(), ReadFieldFromStream(), SetFieldBuffer(), and WriteFieldToStream().
FEM::SolutionMetaData SolverUtils::FEM::SolutionData::meta private
Definition at line 216 of file FieldData.H.
Referenced by Create(), GetDataIndex(), GetFieldMetaData(), and Meta().
The documentation for this class was generated from the following file:
FieldData.H