IMPACT: SolverUtils::FEM::TCPSolverClient Class Reference
SolverUtils::FEM::TCPSolverClient Class Reference
Detailed Description
Definition at line 249 of file SolverAgent.H.
#include <SolverAgent.H>
Public Member Functions
TCPSolverClient ()
int Connect (const std::string &solver_name, int port=0)
Public Member Functions inherited from SolverUtils::FEM::FDSolverAgent
FDSolverAgent (int descriptor=-1)
void Init (int descriptor=-1)
IRAD::Sys::fdistream & InStream ()
IRAD::Sys::fdostream & OutStream ()
void SendACK ()
std::string ACKWord () const
int GetACK ()
void SendWord (const std::string &word)
void SendACK (const std::string &ack)
std::string ReceiveWord ()
int ReceiveWord (std::string &word)
int GetACK (const std::string &ack)
void ReceiveMesh ()
void SendMesh ()
void ReceiveCoords ()
void SendCoords ()
void ReceiveSolnMeta ()
void SendSolnMeta ()
void ReceiveSoln (const std::string &name)
void SendSoln (const std::string &name)
void SendSoln (const std::string &name, void *buf, int bsize=0)
template<class T >
void Recv (T &object)
template<class T >
void Send (const T &object)
Public Member Functions inherited from SolverUtils::FEM::SolverAgent
const FEM::SolutionData & Solution () const
FEM::SolutionData & Solution ()
const Mesh::UnstructuredMesh & Mesh () const
Mesh::UnstructuredMesh & Mesh ()
void ReadMeshFromStream (std::istream &Istr)
void WriteMeshToStream (std::ostream &Ostr)
void ReadCoordsFromStream (std::istream &Istr)
void WriteCoordsToStream (std::ostream &Ostr)
void ReadSolnMetaFromStream (std::istream &Istr)
void WriteSolnMetaToStream (std::ostream &Ostr)
void CreateSoln ()
void ReadSolnFromStream (std::istream &Istr, const std::string &name)
void WriteSolnToStream (std::ostream &Ostr, const std::string &name)
std::ostream & ReportMeshToStream (std::ostream &Ostr)
~SolverAgent ()
Public Member Functions inherited from IRAD::Sys::Net::Client
Client ()
int & Descriptor ()
int Descriptor () const
struct sockaddr_in & ServerAddress ()
struct sockaddr_in ServerAddresss () const
int Connect (const std::string &server_address, int port=0)
int Close ()
~Client ()
Constructor & Destructor Documentation
SolverUtils::FEM::TCPSolverClient::TCPSolverClient () inline
Definition at line 252 of file SolverAgent.H.
                       : FDSolverAgent(), IRAD::Sys::Net::Client()
     {};
Member Function Documentation
int SolverUtils::FEM::TCPSolverClient::Connect (const std::string & solver_name, int port = 0) inline
Definition at line 254 of file SolverAgent.H.
References IRAD::Sys::Net::Client::Connect(), IRAD::Sys::Net::Client::Descriptor(), and SolverUtils::FEM::FDSolverAgent::Init().
     {
       int retval = IRAD::Sys::Net::Client::Connect(solver_name,port);
       if(retval < 0)
         return(retval);
       Init(this->Descriptor());
       return(this->Descriptor());
     };
The documentation for this class was generated from the following file:
SolverAgent.H