IMPACT: CloneDataItem Class Reference
CloneDataItem Class Reference
Detailed Description
Definition at line 102 of file Agent.h.
#include <Agent.h>
Public Member Functions
CloneDataItem (Agent *ag, int cond, std::string target_window_, std::string attr_, std::string parent_window_, std::string parent_attr_, int wg_=1, const char *ptnname_=0, int val_=0)
void create (std::string bufname)
Public Member Functions inherited from DataItemBase
DataItemBase (Agent *ag, std::string target_window_, std::string attr_)
virtual ~DataItemBase ()
virtual void assign (std::string bufname)
Protected Attributes
std::string parent_window
std::string parent_attr
int wg
const char * ptnname
int val
int condition
Additional Inherited Members
Public Attributes inherited from DataItemBase
Agent * agent
std::string target_window
std::string attr
Constructor & Destructor Documentation
CloneDataItem::CloneDataItem (Agent * ag, int cond, std::string target_window_, std::string attr_, std::string parent_window_, std::string parent_attr_, int wg_ = 1, const char * ptnname_ = 0, int val_ = 0)
Definition at line 113 of file Agent.C.
References ptnname.
                                                                     :
                 DataItemBase(ag, target_window_, attr_),
                 parent_window(parent_window_), parent_attr(parent_attr_),
                 wg(wg_), val(val_), condition(cond)
 {
   ptnname = ptnname_?strdup(ptnname_):NULL;
 }
Member Function Documentation
void CloneDataItem::create (std::string bufname) virtual
Reimplemented from DataItemBase.
Definition at line 124 of file Agent.C.
References DataItemBase::agent, DataItemBase::attr, COM_clone_dataitem(), COM_get_dataitem(), COM_get_dataitem_handle(), condition, Agent::get_surface_window(), MAN_DEBUG, parent_attr, parent_window, ptnname, DataItemBase::target_window, val, and wg.
 {
   if (parent_window=="") {   // filling
     parent_window = agent->get_surface_window();
   }
   if (COM_get_dataitem_handle( bufname+attr) > 0) {
     char loc1, loc2;
     int type1, type2;
     int ncomp1, ncomp2;
     std::string unit1, unit2;
     COM_get_dataitem( bufname+attr, &loc1, &type1, &ncomp1, &unit1);
     COM_get_dataitem( parent_window+parent_attr, &loc2, &type2, &ncomp2, &unit2);
     if (loc1 != loc2 || type1 != type2 || ncomp1 != ncomp2 || unit1 != unit2) {
       std::cout << "ROCMAN Error: CloneDataItem::create(): Could not create " << target_window+attr << " in two different ways " << std::endl;
       MPI_Abort(MPI_COMM_WORLD, -1);
     }
     else {
       MAN_DEBUG(2, ("CloneDataItem::create: %s%s %s%s condition:%d handle:%d SKIPPED.\n", bufname.c_str(), attr.c_str(), parent_window.c_str(), parent_attr.c_str(), condition, COM_get_dataitem_handle( parent_window+parent_attr)));
       return;
     }
   }
   MAN_DEBUG(2, ("CloneDataItem::create: %s%s %s%s condition:%d handle:%d.\n", bufname.c_str(), attr.c_str(), parent_window.c_str(), parent_attr.c_str(), condition, COM_get_dataitem_handle( parent_window+parent_attr)));
   if (condition)
     if (COM_get_dataitem_handle( parent_window+parent_attr) <= 0)  return;
   if (ptnname) {
     if (ptnname[0] == '.')
       ptnname = strdup((agent->get_surface_window() + ptnname).c_str());
   }
   COM_clone_dataitem( bufname+attr, parent_window+parent_attr, wg, ptnname, val);
 }
Member Data Documentation
int CloneDataItem::condition protected
Definition at line 109 of file Agent.h.
Referenced by create().
std::string CloneDataItem::parent_attr protected
Definition at line 105 of file Agent.h.
Referenced by create().
std::string CloneDataItem::parent_window protected
Definition at line 104 of file Agent.h.
Referenced by create().
const char* CloneDataItem::ptnname protected
Definition at line 107 of file Agent.h.
Referenced by CloneDataItem(), and create().
int CloneDataItem::val protected
Definition at line 108 of file Agent.h.
Referenced by create().
int CloneDataItem::wg protected
Definition at line 106 of file Agent.h.
Referenced by create().
The documentation for this class was generated from the following files:
Agent.h
Agent.C