IMPACT: RemeshInit Class Reference
RemeshInit Class Reference
Detailed Description
Definition at line 207 of file transfer_actions.h.
#include <transfer_actions.h>
Public Member Functions
RemeshInit (FluidAgent *fag, SolidAgent *sag, const std::string s_u, const std::string f_total_disp, const std::string f_nc, const std::string f_nc_t0)
void init (double t)
void run (double t, double dt, double alpha)
Public Member Functions inherited from InterMeshTransfer
InterMeshTransfer (FluidAgent *fag, SolidAgent *sag, char *name=NULL)
Public Member Functions inherited from Action
Action (void *p=0, const char *name=NULL)
Action (int n, const char **at, int *i=NULL, void *p=0, const char *name=NULL)
Action (int n, const std::string at[], int *i=NULL, void *p=0, const char *name=NULL)
virtual ~Action ()
virtual void declare (Scheduler &)
virtual void finalize ()
virtual const char * name ()
void set_name (const char *name)
virtual void print (FILE *f)
virtual void print_toposort (FILE *f)
virtual void schedule ()
Private Attributes
int s_u_hdl
int f_total_disp_hdl
int f_nc_hdl
int f_nc_t0_hdl
int RFC_interpolate
Additional Inherited Members
Protected Types inherited from Action
enum { IN =1, OUT =2, INOUT =3 }
Protected Member Functions inherited from InterMeshTransfer
void load_rocface (const RocmanControl_parameters *param)
Protected Member Functions inherited from Action
int get_dataitem_handle (int i)
int get_dataitem_handle_const (int i)
int get_dataitem_handle (const std::string str)
void set_attr (int n, const std::string at[], int *id=NULL)
void set_attr (int n, const char *at[], int *id=NULL)
void set_io (int n, const int *io)
void set_io (const char *io)
int get_io (int i)
Protected Attributes inherited from InterMeshTransfer
FluidAgent * fagent
SolidAgent * sagent
Protected Attributes inherited from Action
const char * action_name
char ** attr
int * idx
int count
void * usr_ptr
std::vector< int > inout
Constructor & Destructor Documentation
RemeshInit::RemeshInit (FluidAgent * fag, SolidAgent * sag, const std::string s_u, const std::string f_total_disp, const std::string f_nc, const std::string f_nc_t0) explicit
Definition at line 1108 of file transfer_actions.C.
References InterMeshTransfer::fagent, Agent::get_surface_window(), FluidAgent::ifluid_i, Action::IN, Action::INOUT, Action::OUT, Agent::register_clone_dataitem(), Action::set_attr(), and Action::set_io().
                                                   :
     InterMeshTransfer(fag, sag, "RemeshInit")
 {
   int io[] = {IN, IN, INOUT, OUT};
   set_io( 4, io);
   std::string.data[4];
  .data[0] = s_u;
  .data[1] = f_total_disp;
  .data[2] = f_nc;
  .data[3] = f_nc_t0;
   set_attr(4,.data);
   fagent->register_clone_dataitem( 0, fagent->ifluid_i, ".total_disp", fagent->get_surface_window(), ".du_alp");
   fagent->register_clone_dataitem( 0, fagent->ifluid_i, ".nc_t0", fagent->get_surface_window(), ".nc");
 }
Member Function Documentation
void RemeshInit::init (double t) virtual
Reimplemented from Action.
Definition at line 1127 of file transfer_actions.C.
References COM_get_function_handle(), f_nc_hdl, f_nc_t0_hdl, f_total_disp_hdl, InterMeshTransfer::fagent, Agent::get_coupling(), Action::get_dataitem_handle(), Coupling::get_rocmancontrol_param(), InterMeshTransfer::load_rocface(), RFC_interpolate, and s_u_hdl.
{
   s_u_hdl = get_dataitem_handle(0);
   f_total_disp_hdl = get_dataitem_handle(1);
   f_nc_hdl = get_dataitem_handle(2);
   f_nc_t0_hdl = get_dataitem_handle(3);
   load_rocface(fagent->get_coupling()->get_rocmancontrol_param());
   RFC_interpolate = COM_get_function_handle("RFC.interpolate");
 }
void RemeshInit::run (double t, double dt, double alpha) virtual
Reimplemented from Action.
Definition at line 1137 of file transfer_actions.C.
References COM_call_function(), f_nc_hdl, f_nc_t0_hdl, f_total_disp_hdl, MAN_DEBUG, RFC_interpolate, s_u_hdl, and RocBlas::sub.
{
   MAN_DEBUG(2, ("Rocman: calling RemeshInit::run() with t:%e dt:%e alpha:%e.\n", t, dt, alpha));
   COM_call_function( RFC_interpolate, &s_u_hdl, &f_total_disp_hdl);
   COM_call_function( RocBlas::sub, &f_nc_hdl, &f_total_disp_hdl, &f_nc_t0_hdl);
 }
Member Data Documentation
int RemeshInit::f_nc_hdl private
Definition at line 214 of file transfer_actions.h.
Referenced by init(), and run().
int RemeshInit::f_nc_t0_hdl private
Definition at line 214 of file transfer_actions.h.
Referenced by init(), and run().
int RemeshInit::f_total_disp_hdl private
Definition at line 213 of file transfer_actions.h.
Referenced by init(), and run().
int RemeshInit::RFC_interpolate private
Definition at line 215 of file transfer_actions.h.
Referenced by init(), and run().
int RemeshInit::s_u_hdl private
Definition at line 213 of file transfer_actions.h.
Referenced by init(), and run().
The documentation for this class was generated from the following files:
transfer_actions.h
transfer_actions.C