IMPACT: SolverUtils::Mesh::MeshUtilityObject Class Reference
SolverUtils::Mesh::MeshUtilityObject Class Reference
Detailed Description
Definition at line 484 of file Mesh.H.
#include <Mesh.H>
Public Types
enum MeshConType {
EN =0, ENDUAL, ED, EDDUAL,
EF, EFDUAL, DN, DNDUAL,
DF, DFDUAL, FN, FNDUAL,
NCONS
}
Public Member Functions
MeshUtilityObject ()
int NumberOfNodes () const
int NumberOfElements () const
NodalCoordinates & NC ()
const NodalCoordinates & NC () const
Connectivity & ECon ()
const Connectivity & ECon () const
Connectivity & Con (const MeshConType type)
const Connectivity & Con (const MeshConType type) const
Connectivity & GetCon (const MeshConType type)
const Connectivity & GetCon (const MeshConType type) const
int FormConnectivity (const MeshConType type)
int DestroyConnectivity (const MeshConType type)
~MeshUtilityObject ()
Protected Attributes
NodalCoordinates _nodal_coordinates
std::vector< Connectivity > _connectivities
Member Enumeration Documentation
enum SolverUtils::Mesh::MeshUtilityObject::MeshConType
Enumerator
EN
ENDUAL
ED
EDDUAL
EF
EFDUAL
DN
DNDUAL
DF
DFDUAL
FN
FNDUAL
NCONS
Definition at line 486 of file Mesh.H.
 { EN=0,ENDUAL,ED,EDDUAL,EF,EFDUAL,DN,DNDUAL,DF,DFDUAL,FN, FNDUAL ,NCONS};
Constructor & Destructor Documentation
SolverUtils::Mesh::MeshUtilityObject::MeshUtilityObject () inline
Definition at line 491 of file Mesh.H.
References _connectivities, and NCONS.
                           : _nodal_coordinates()
       {
         //      std::cout << "Mesh utility constructor" << std::endl;
         //      _nodal_coordinates_ptr = new NodalCoordinates();
         _connectivities.resize(NCONS);
         //      _connectivities[EN] = new Connectivity();
       };
SolverUtils::Mesh::MeshUtilityObject::~MeshUtilityObject () inline
Definition at line 570 of file Mesh.H.
References _connectivities, _nodal_coordinates, and SolverUtils::Mesh::NodalCoordinates::destroy().
       {
         //      std::cout << "destroying mesh util" << std::endl;
         _nodal_coordinates.destroy();
         //      delete _nodal_coordinates_ptr;
         std::vector<Connectivity>::iterator cpi = _connectivities.begin();
         while(cpi != _connectivities.end())
           cpi++->destroy();
       };
Member Function Documentation
Connectivity& SolverUtils::Mesh::MeshUtilityObject::Con (const MeshConType type) inline
Definition at line 516 of file Mesh.H.
References _connectivities.
       {
         //      if(!_connectivities[type])
         //      FormConnectivity(type);
         return(_connectivities[type]);
       };
const Connectivity& SolverUtils::Mesh::MeshUtilityObject::Con (const MeshConType type) const inline
Definition at line 522 of file Mesh.H.
References _connectivities.
       {
         //      if(!_connectivities[type])
         //      (const_cast<MeshUtilityObject*>(this))->FormConnectivity(type);
         return(_connectivities[type]);
       };
int SolverUtils::Mesh::MeshUtilityObject::DestroyConnectivity (const MeshConType type) inline
Definition at line 561 of file Mesh.H.
References _connectivities.
       {
         //      if(_connectivities[type]){
         _connectivities[type].destroy();
         //      delete _connectivities[type];
         //      _connectivities[type] = NULL;
         //      }
         return(0);
       };
Connectivity& SolverUtils::Mesh::MeshUtilityObject::ECon () inline
Definition at line 508 of file Mesh.H.
References _connectivities, and EN.
Referenced by FormConnectivity(), and SolverUtils::Mesh::Partition::Read().
       {
         return(_connectivities[EN]);
       };
const Connectivity& SolverUtils::Mesh::MeshUtilityObject::ECon () const inline
Definition at line 512 of file Mesh.H.
References _connectivities, and EN.
       {
         return(_connectivities[EN]);
       };
int SolverUtils::Mesh::MeshUtilityObject::FormConnectivity (const MeshConType type) inline
Definition at line 542 of file Mesh.H.
References _connectivities, ECon(), ENDUAL, SolverUtils::Mesh::Connectivity::Inverse(), and NC().
Referenced by GetCon().
       {
         switch(type)
           {
           case ENDUAL:
             //    if(_connectivities[type]){
             //      _connectivities[type]->destroy();
             //    }
             //    else
             //      _connectivities[type] = new Connectivity();
             ECon().Inverse(_connectivities[type],NC().Size());
             break;
           default:
             bool connectivity_known_type = false;
             assert(connectivity_known_type);
             break;
           }
         return(0);
       };
Connectivity& SolverUtils::Mesh::MeshUtilityObject::GetCon (const MeshConType type) inline
Definition at line 529 of file Mesh.H.
References _connectivities, and FormConnectivity().
Referenced by SolverUtils::Mesh::Partition::GetBorderElements().
       {
         if(_connectivities[type].empty())
           FormConnectivity(type);
         return(_connectivities[type]);
       };
const Connectivity& SolverUtils::Mesh::MeshUtilityObject::GetCon (const MeshConType type) const inline
Definition at line 535 of file Mesh.H.
References _connectivities.
       {
         if(_connectivities[type].empty())
           (const_cast<MeshUtilityObject*>(this))->FormConnectivity(type);
         return(_connectivities[type]);
       };
NodalCoordinates& SolverUtils::Mesh::MeshUtilityObject::NC () inline
Definition at line 500 of file Mesh.H.
References _nodal_coordinates.
Referenced by FormConnectivity(), and SolverUtils::Mesh::Partition::Read().
       {
         return(_nodal_coordinates);
       };
const NodalCoordinates& SolverUtils::Mesh::MeshUtilityObject::NC () const inline
Definition at line 504 of file Mesh.H.
References _nodal_coordinates.
       {
         return(_nodal_coordinates);
       };
int SolverUtils::Mesh::MeshUtilityObject::NumberOfElements () const inline
Definition at line 499 of file Mesh.H.
References _connectivities, and EN.
Referenced by SolverUtils::Mesh::Partition::GetBorderElements(), and SolverUtils::Mesh::Partition::Read().
 { return(_connectivities[EN].Nelem()); };
int SolverUtils::Mesh::MeshUtilityObject::NumberOfNodes () const inline
Definition at line 498 of file Mesh.H.
References _nodal_coordinates, and SolverUtils::Mesh::NodalCoordinates::Size().
Referenced by SolverUtils::Mesh::Partition::GetBorderElements(), and SolverUtils::Mesh::Partition::Read().
 { return(_nodal_coordinates.Size()); };
Member Data Documentation
std::vector<Connectivity> SolverUtils::Mesh::MeshUtilityObject::_connectivities protected
Definition at line 489 of file Mesh.H.
Referenced by Con(), DestroyConnectivity(), ECon(), FormConnectivity(), GetCon(), MeshUtilityObject(), NumberOfElements(), and ~MeshUtilityObject().
NodalCoordinates SolverUtils::Mesh::MeshUtilityObject::_nodal_coordinates protected
Definition at line 488 of file Mesh.H.
Referenced by NC(), NumberOfNodes(), and ~MeshUtilityObject().
The documentation for this class was generated from the following file:
Mesh.H