IMPACT: Face Class Reference
Face Class Reference
This class encapsulate a face in a window manifold.
Detailed Description
Definition at line 605 of file Manifold_2.h.
#include <Manifold_2.h>
Public Member Functions
Face ()
Face (const Pane_manifold_2 *pm, int fid, Access_Mode mode=ACROSS_PANE)
Construct a Face object from a pane manifold and its face ID.
void face_center (Point_3< Real > &cnt) const
Get the face center of a given face.
template<class Value >
void face_average (const COM::DataItem *attr, Value &val) const
Get the average value of the nodes of a given face.
const Pane_manifold_2 * pane_manifold () const
Obtain the pane manifold that owns the edge.
const COM::Pane * pane () const
Obtain the owner Pane_manifold_2 of the node.
int id () const
Obtain the ID of the edge.
Halfedge halfedge () const
const void * addr (const COM::DataItem *attr) const
Obtain the address of an dataitem associated with the element.
const COM::DataItem * attr (const COM::DataItem *a) const
Obtain the dataitem on the parent pane.
bool operator== (const Face &f) const
Are two faces the same?
bool operator!= (const Face &f) const
Are two faces different?
bool operator< (const Face &f) const
Does the current face has a smaller ID then the given one?
Face ()
Face (RFC_Pane_overlay *pm, int fid)
Construct a Face object from a pane manifold and its face ID.
RFC_Pane_overlay * pane () const
Obtain the pane manifold that owns the edge.
int id () const
Obtain the ID of the edge.
HEdge halfedge () const
bool operator== (const Face &f) const
Are the two halfedges equal?
bool operator!= (const Face &f) const
bool operator< (const Face &f) const
Does the current face has a smaller ID then the given one?
Protected Attributes
const Pane_manifold_2 * _pm
int _fID
Access_Mode _mode
RFC_Pane_overlay * _pm
Constructor & Destructor Documentation
Face::Face () inline
Definition at line 607 of file Manifold_2.h.
 : _pm(NULL) {}
Face::Face (const Pane_manifold_2 * pm, int fid, Access_Mode mode = ACROSS_PANE) inline
Definition at line 609 of file Manifold_2.h.
     : _pm( pm), _fID( fid), _mode(mode) {}
Face::Face () inline
Definition at line 144 of file HDS_overlay.h.
 : _pm(NULL), _fID(0) {}
Face::Face (RFC_Pane_overlay * pm, int fid) inline
Definition at line 146 of file HDS_overlay.h.
 : _pm( pm), _fID( fid) {}
Member Function Documentation
const void* Face::addr (const COM::DataItem * attr) const
const COM::DataItem* Face::attr (const COM::DataItem * a) const inline
Definition at line 652 of file Manifold_2.h.
References _pm, COM_assertion_msg, and Simple_manifold_2::pane().
{
     COM_assertion_msg( a, "Unexpected NULL pointer");
     return a->window()->pane( _pm->pane()->id()).dataitem(a->id());
   }
template<class Value > void Face::face_average (const COM::DataItem * attr, Value & val) const inline
Definition at line 619 of file Manifold_2.h.
References _fID, _mode, _pm, Node::addr(), Halfedge::next(), and Halfedge::origin().
Referenced by face_center().
{
     // Otherwise, compute the center
     val = Value(0);
     int count=0;
     Halfedge h=Halfedge(_pm, Edge_ID(_fID,0),_mode), h0=h;
     do {
       val += *reinterpret_cast<const Value*>(h.origin().addr( attr));
       ++count;
     } while ( (h=h.next()) != h0);
     val/=count;
   }
void Face::face_center (Point_3< Real > & cnt) const inline
Definition at line 613 of file Manifold_2.h.
References _pm, COM_NC, face_average(), and Simple_manifold_2::pane().
   { face_average( _pm->pane()->dataitem( COM::COM_NC),
                   reinterpret_cast<Vector_3<Real> &>(cnt)); }
HEdge Face::halfedge () const inline
Definition at line 154 of file HDS_overlay.h.
References _fID, and _pm.
   { return HEdge(_pm, Edge_ID(_fID,0)); }
Halfedge Face::halfedge () const inline
Definition at line 644 of file Manifold_2.h.
References _fID, _mode, and _pm.
Referenced by Overlay::get_inodes_of_face(), and Overlay::number_subfaces().
{
     return Halfedge(_pm, Edge_ID(_fID,0),_mode);
   }
int Face::id () const inline
Definition at line 152 of file HDS_overlay.h.
References _fID.
 { return _fID; }
int Face::id () const inline
Definition at line 642 of file Manifold_2.h.
References _fID.
Referenced by RFC_Pane_overlay::get_index(), RFC_Pane_overlay::get_lid(), and Overlay::number_subfaces().
 { return _fID; }
bool Face::operator!= (const Face & f) const inline
Definition at line 161 of file HDS_overlay.h.
References _fID, and _pm.
   { return _pm!=f._pm || _fID!=f._fID; }
bool Face::operator!= (const Face & f) const inline
Definition at line 662 of file Manifold_2.h.
References _fID, and _pm.
   { return _pm!=f._pm || _fID!=f._fID; }
bool Face::operator< (const Face & f) const inline
bool Face::operator< (const Face & f) const inline
Definition at line 666 of file Manifold_2.h.
References _fID, _pm, and Simple_manifold_2::pane().
{
     int pid1=_pm->pane()->id(), pid2=f._pm->pane()->id();
     return pid1<pid2 || pid1==pid2 && _fID<f._fID;
   }
bool Face::operator== (const Face & f) const inline
Definition at line 158 of file HDS_overlay.h.
References _fID, and _pm.
   { return _pm==f._pm && _fID==f._fID; }
bool Face::operator== (const Face & f) const inline
Definition at line 658 of file Manifold_2.h.
References _fID, and _pm.
   { return _pm==f._pm && _fID==f._fID; }
RFC_Pane_overlay* Face::pane () const inline
Definition at line 149 of file HDS_overlay.h.
References _pm.
 { return _pm; }
const COM::Pane* Face::pane () const inline
Definition at line 638 of file Manifold_2.h.
References _pm, and Simple_manifold_2::pane().
   { if ( _pm) return _pm->pane(); else return NULL; }
const Pane_manifold_2* Face::pane_manifold () const inline
Definition at line 635 of file Manifold_2.h.
References _pm.
 { return _pm; }
Member Data Documentation
int Face::_fID protected
Definition at line 673 of file Manifold_2.h.
Referenced by face_average(), halfedge(), id(), operator!=(), operator<(), and operator==().
Access_Mode Face::_mode protected
Definition at line 674 of file Manifold_2.h.
Referenced by face_average(), and halfedge().
RFC_Pane_overlay* Face::_pm protected
Definition at line 168 of file HDS_overlay.h.
const Pane_manifold_2* Face::_pm protected
Definition at line 672 of file Manifold_2.h.
Referenced by attr(), face_average(), face_center(), halfedge(), operator!=(), operator<(), operator==(), pane(), and pane_manifold().
The documentation for this class was generated from the following files:
Manifold_2.h
HDS_overlay.h
RFC_Window_overlay.h