IMPACT: Element_node_enumerator_str_2 Class Reference
Element_node_enumerator_str_2 Class Reference
Optimized version for 2-D structured meshes.
Detailed Description
Definition at line 124 of file Element_accessors.hpp.
#include <Element_accessors.hpp>
Public Member Functions
Element_node_enumerator_str_2 ()
Element_node_enumerator_str_2 (const Pane *pane, int i)
Element_node_enumerator_str_2 (const Pane *pane, const std::pair< int, int > &id)
void next ()
int operator[] (int i) const
Public Member Functions inherited from Element_node_enumerator
Element_node_enumerator ()
Element_node_enumerator (const Pane *pane, int i, const Connectivity *conn=NULL)
Constructor for an element in a structured or an unstructured mesh.
Element_node_enumerator (const Pane *pane, const std::pair< int, int > &id)
A constructor for an element in a structured mesh.
void next ()
Go to the next element within the connectivity tables of a pane.
int type () const
Obtain the type of the element.
int is_quadratic () const
Check whether the element is quadratic.
int size_of_nodes () const
Number of nodes per element.
int size_of_corners () const
Number of corners per element.
void get_nodes (std::vector< int > &nodes)
Get a vector of all of the nodes in the element.
int size_of_edges () const
Number of edges per element.
int size_of_faces () const
Number of faces per element.
int dimension () const
Get the dimension of the base pane.
int id () const
Get the local id of the element within the pane.
int vertex (int lvid, bool level=false) const
Get the vertex index of an vertex within the element.
int operator[] (int i) const
Obtain the pane-scope node ID from its element-scope index.
const Pane * pane () const
Additional Inherited Members
Protected Attributes inherited from Element_node_enumerator
const Pane * _pane
const Connectivity * _conn
union {
const int * _start
int _base
};
int _res
Constructor & Destructor Documentation
Element_node_enumerator_str_2::Element_node_enumerator_str_2 () inline
Definition at line 126 of file Element_accessors.hpp.
 {}
Element_node_enumerator_str_2::Element_node_enumerator_str_2 (const Pane * pane, int i) inline
Definition at line 127 of file Element_accessors.hpp.
     : Element_node_enumerator( pane, i) {}
Element_node_enumerator_str_2::Element_node_enumerator_str_2 (const Pane * pane, const std::pair< int, int > & id) inline
Definition at line 130 of file Element_accessors.hpp.
     : Element_node_enumerator( pane, id) {}
Member Function Documentation
void Element_node_enumerator_str_2::next () inline
Definition at line 134 of file Element_accessors.hpp.
References Element_node_enumerator::_base, Element_node_enumerator::_pane, Element_node_enumerator::_res, and Pane::size_i().
Referenced by Pane_dual_connectivity::construct_connectivity_str_2().
   { ++_base; if ( ++_res == int(_pane->size_i()-1)) { ++_base; _res=0; } }
int Element_node_enumerator_str_2::operator[] (int i) const inline
Definition at line 137 of file Element_accessors.hpp.
References Element_node_enumerator::_base, Element_node_enumerator::_pane, and Pane::size_i().
{
     int t=_base;
     if ( i>1) t+=_pane->size_i();
     return ( i==1 || i==2)? t+1 : t;
   }
The documentation for this class was generated from the following file:
Element_accessors.hpp