IMPACT: HEdge Class Reference
HEdge Class Reference
This class encapsulate a halfedge over a window manifold.
Detailed Description
Definition at line 80 of file HDS_overlay.h.
#include <HDS_overlay.h>
Public Member Functions
HEdge ()
HEdge (RFC_Pane_overlay *pm, Edge_ID e)
Construct a Halfedge object from a pane manifold and its edge ID.
HEdge opposite_l () const
Get the ID of the opposite edge of a given edge.
HEdge opposite_g () const
HEdge prev_l () const
Get the previous halfedge of its owner element.
HEdge prev_g () const
HEdge next_l () const
Get the next halfedge of its owner element.
HEdge next_g () const
Node origin_l () const
Obtain the (primary copy of the) origin of the edge.
Node origin_g () const
Node destination_g () const
Obtain the (primary copy of the) destination of the edge.
Node destination_l () const
Obtain the (primary copy of the) destination of the edge.
Face face () const
Obtain the (primary copy of the) origin of the edge.
bool is_border_l () const
Is the edge a border edge?
bool is_border_g () const
RFC_Pane_overlay * pane () const
Obtain the pane manifold that owns the edge.
Edge_ID id () const
Obtain the ID of the edge.
bool operator== (const HEdge &h) const
Are the two halfedges equal?
bool operator!= (const HEdge &h) const
bool operator< (const HEdge &h) const
Does the current halfedge has a smaller ID then the given one?
Protected Attributes
RFC_Pane_overlay * _pm
Edge_ID _eID
Constructor & Destructor Documentation
HEdge::HEdge () inline
Definition at line 82 of file HDS_overlay.h.
Referenced by next_l(), opposite_l(), and prev_l().
 : _pm(NULL) {}
HEdge::HEdge (RFC_Pane_overlay * pm, Edge_ID e) inline
Definition at line 84 of file HDS_overlay.h.
     : _pm( pm), _eID( e) {}
Member Function Documentation
Node HEdge::destination_g () const inline
Definition at line 572 of file RFC_Window_overlay.h.
References _eID, _pm, and RFC_Pane_overlay::get_primary().
Referenced by Overlay::contains(), RFC_Window_overlay::cos_edge_angle(), RFC_Window_overlay::evaluate_normals(), Overlay::get_edge_parent(), Overlay::get_next_inode_ccw(), Overlay::intersect_blue_with_green(), Overlay::intersect_link_helper(), RFC_Window_overlay::print_features(), Overlay::project_adjacent_green_vertices(), and Overlay_primitives::snap_blue_ridge_edge().
 { Node n( _pm, _pm->get_destination( _eID)); return _pm->get_primary(n); }
Node HEdge::destination_l () const inline
Definition at line 575 of file RFC_Window_overlay.h.
References _eID, and _pm.
Referenced by RFC_Pane_overlay::construct_bvpair2edge(), Overlay::convert_nat_coordinates(), RFC_Pane_overlay::determine_counterparts(), RFC_Pane_overlay::evaluate_normals(), RFC_Window_overlay::evaluate_normals(), Overlay::get_green_parent(), HDS_accessor::get_normal(), RFC_Pane_overlay::get_normal(), Overlay_primitives::get_point(), RFC_Pane_overlay::get_tangent(), RFC_Window_overlay::get_tangent(), Overlay::insert_edge_into_queue(), Overlay::insert_node_in_blue_edge(), Overlay::intersect_blue_with_green(), Overlay::intersect_link(), Overlay::intersect_link_helper(), Overlay::project_adjacent_green_vertices(), Overlay::sort_on_green_edges(), Overlay::sq_length(), and Vertex_set::Vertex_set().
 { return Node( _pm, _pm->get_destination( _eID)); }
Face HEdge::face () const inline
Definition at line 578 of file RFC_Window_overlay.h.
References _eID, and _pm.
Referenced by Overlay::contains(), Overlay::convert_nat_coordinates(), Overlay::get_nat_coor(), Overlay::get_next_inode_ccw(), Overlay::get_next_inode_cw(), Overlay::intersect_link_helper(), and Overlay::number_subfaces().
 {
   if (_eID.is_border()) { return Face(); }
   else { return Face(_pm, _eID.eid()); }
 }
Edge_ID HEdge::id () const inline
Definition at line 124 of file HDS_overlay.h.
References _eID.
Referenced by RFC_Window_overlay::detect_features(), RFC_Pane_overlay::get_border_index(), RFC_Pane_overlay::get_cos_face_angle(), RFC_Pane_overlay::get_counterpart(), RFC_Pane_overlay::get_index(), RFC_Pane_overlay::get_next_edge(), RFC_Pane_overlay::get_normal(), RFC_Pane_overlay::get_prev_edge(), and Vertex_set::Vertex_set().
 { return _eID; }
bool HEdge::is_border_g () const inline
Definition at line 587 of file RFC_Window_overlay.h.
References _eID, and _pm.
Referenced by RFC_Window_overlay::comp_angle_defect(), RFC_Window_overlay::cos_face_angle(), Overlay::get_edge_pair_parents(), Overlay::get_edge_parent(), Overlay::get_green_parent(), Overlay::get_inodes_of_face(), Overlay::get_nat_coor(), Overlay::insert_edge_into_queue(), Overlay::insert_node_in_blue_edge(), Overlay_primitives::intersect(), Overlay::intersect_blue_with_green(), Overlay::intersect_link(), Node::is_border_g(), Overlay::match_features_0(), Overlay_primitives::snap_blue_ridge_edge(), and Overlay_primitives::snap_blue_ridge_vertex().
 { return _pm->is_physical_border_edge( _eID); }
bool HEdge::is_border_l () const inline
Definition at line 584 of file RFC_Window_overlay.h.
References _eID.
Referenced by RFC_Window_overlay::detect_features(), RFC_Window_overlay::evaluate_normals(), Overlay::get_inodes_of_face(), Overlay_primitives::get_point(), Overlay_primitives::intersect(), Overlay::intersect_link(), Overlay::intersect_link_helper(), Node::is_border_l(), and Overlay::sort_on_green_edges().
 { return _eID.is_border(); }
HEdge HEdge::next_g () const inline
Definition at line 563 of file RFC_Window_overlay.h.
References _eID, _pm, and RFC_Pane_overlay::get_next_edge().
Referenced by Overlay::associate_green_vertices(), Overlay::contains(), Overlay::get_green_parent(), Overlay::get_inodes_of_face(), Overlay::get_nat_coor(), HDS_accessor::get_next_around_destination(), HDS_accessor::get_next_around_origin(), Overlay::insert_node_in_blue_edge(), Overlay::intersect_blue_with_green(), Overlay::intersect_link_helper(), Overlay::intersect_link_helper2(), Overlay::match_features_0(), and Overlay::sort_on_green_edges().
 { return _pm->get_next_edge( _eID); }
HEdge HEdge::next_l () const inline
If the current edge is a border edges, it returns the next border edge along the boundary.
Definition at line 560 of file RFC_Window_overlay.h.
References _eID, _pm, and HEdge().
Referenced by RFC_Window_overlay::comp_angle_defect(), Overlay::convert_nat_coordinates(), Vertex_set::count_edges(), Overlay::count_edges(), Overlay::get_nat_coor(), Overlay::insert_node_in_blue_edge(), Overlay::intersect_blue_with_green(), Overlay::intersect_link(), Overlay::intersect_link_helper(), Normal_set::Normal_set(), Overlay::overlay_init(), Overlay_primitives::project_onto_element(), and Overlay_primitives::snap_blue_ridge_vertex().
 { return HEdge( _pm, _pm->get_next_real_edge( _eID)); }
bool HEdge::operator!= (const HEdge & h) const inline
Definition at line 130 of file HDS_overlay.h.
References _eID, and _pm.
   { return _pm!=h._pm || _eID!=h._eID; }
bool HEdge::operator< (const HEdge & h) const inline
Definition at line 595 of file RFC_Window_overlay.h.
References _eID, _pm, and RFC_Pane_base::id().
{
   int pid1=_pm->pane()->id(), pid2=h._pm->pane()->id();
   return pid1<pid2 || pid1==pid2 && _eID<h._eID;
 }
bool HEdge::operator== (const HEdge & h) const inline
Definition at line 127 of file HDS_overlay.h.
References _eID, and _pm.
   { return _pm==h._pm && _eID==h._eID; }
HEdge HEdge::opposite_g () const inline
Definition at line 551 of file RFC_Window_overlay.h.
References _eID, _pm, and RFC_Pane_overlay::get_opposite_edge().
Referenced by Overlay::associate_green_vertices(), RFC_Window_overlay::check_false_strong_1(), Overlay::contains(), RFC_Window_overlay::detect_features(), RFC_Window_overlay::evaluate_normals(), Overlay::get_edge_pair_parents(), Overlay::get_edge_parent(), Overlay::get_green_parent(), Overlay::get_inodes_of_face(), Overlay::get_nat_coor(), HDS_accessor::get_next_around_destination(), HDS_accessor::get_next_around_origin(), Overlay::get_next_inode_ccw(), Overlay::get_next_inode_cw(), RFC_Pane_overlay::get_normal(), HDS_accessor::get_prev_around_destination(), HDS_accessor::get_prev_around_origin(), RFC_Pane_overlay::get_tangent(), Overlay::insert_edge_into_queue(), Overlay::insert_node_in_blue_edge(), Overlay::insert_node_in_green_edge(), Overlay_primitives::intersect(), Overlay::intersect_blue_with_green(), Overlay::intersect_link(), Overlay::is_queue_empty(), Overlay::match_features_0(), Overlay_primitives::normalmatch(), Overlay::number_a_subnode(), Overlay::project_adjacent_green_vertices(), RFC_Window_overlay::remove_feature_1(), Overlay_primitives::snap_blue_ridge_edge(), Overlay::sort_on_green_edges(), RFC_Window_overlay::subdiv_feature_curve(), and Overlay::verify_inode().
 { return _pm->get_opposite_edge( _eID); }
HEdge HEdge::opposite_l () const inline
Definition at line 548 of file RFC_Window_overlay.h.
References _eID, _pm, and HEdge().
Referenced by RFC_Window_overlay::detect_features(), and Overlay::sort_on_green_edges().
 { return HEdge(_pm, _pm->get_opposite_real_edge( _eID)); }
Node HEdge::origin_g () const inline
Definition at line 566 of file RFC_Window_overlay.h.
References _eID, _pm, and RFC_Pane_overlay::get_primary().
Referenced by Overlay::associate_green_vertices(), Overlay::contains(), RFC_Window_overlay::cos_edge_angle(), RFC_Window_overlay::detect_features(), Overlay::get_edge_parent(), Overlay::get_inodes_of_face(), Overlay::get_nat_coor(), Overlay::get_next_inode_cw(), Overlay::insert_node_in_blue_edge(), Overlay::insert_node_in_green_edge(), Overlay::intersect_blue_with_green(), Overlay::intersect_link(), Overlay::intersect_link_helper(), Overlay::match_features_0(), Overlay::project_adjacent_green_vertices(), Overlay_primitives::snap_blue_ridge_edge(), Overlay_primitives::snap_blue_ridge_vertex(), and Overlay::sort_on_green_edges().
 { Node n( _pm, _pm->get_origin( _eID)); return _pm->get_primary( n); }
Node HEdge::origin_l () const inline
Definition at line 569 of file RFC_Window_overlay.h.
References _eID, and _pm.
Referenced by RFC_Pane_overlay::construct_bvpair2edge(), Overlay::convert_nat_coordinates(), Overlay::count_subnodes(), RFC_Pane_overlay::determine_counterparts(), Overlay_primitives::get_point(), RFC_Window_overlay::get_tangent(), Overlay::insert_edge_into_queue(), Overlay::insert_node_in_blue_edge(), Overlay::intersect_blue_with_green(), Overlay::intersect_link(), Overlay::intersect_link_helper(), Overlay::match_features_0(), Overlay::number_a_subnode(), Overlay::overlay_init(), Overlay::sq_length(), and Vertex_set::Vertex_set().
 { return Node( _pm, _pm->get_origin( _eID)); }
RFC_Pane_overlay* HEdge::pane () const inline
Definition at line 121 of file HDS_overlay.h.
References _pm.
Referenced by RFC_Window_overlay::check_false_strong_1(), Overlay::contains(), Overlay::convert_nat_coordinates(), RFC_Window_overlay::cos_face_angle(), Overlay::count_subnodes(), RFC_Window_overlay::detect_features(), RFC_Window_overlay::evaluate_normals(), RFC_Window_overlay::get_an_unmarked_halfedge(), Overlay::get_green_parent(), HDS_accessor::get_inode_list(), RFC_Pane_overlay::get_next_edge(), HDS_accessor::get_normal(), RFC_Pane_overlay::get_normal(), RFC_Pane_overlay::get_prev_edge(), RFC_Pane_overlay::get_tangent(), Overlay::insert_node_in_blue_edge(), Overlay::insert_node_in_green_edge(), Overlay::intersect_blue_with_green(), Overlay::intersect_link(), HDS_accessor::is_feature_1(), RFC_Window_overlay::is_feature_1(), HDS_accessor::mark(), HDS_accessor::marked(), Overlay::match_features_0(), Overlay::number_a_subnode(), Overlay::number_subfaces(), Overlay::overlay_init(), Overlay::project_adjacent_green_vertices(), RFC_Window_overlay::remove_feature_1(), Overlay_primitives::snap_blue_ridge_edge(), RFC_Window_overlay::subdiv_feature_curve(), HDS_accessor::unmark(), and RFC_Window_overlay::unset_strong_edge().
 { return _pm; }
HEdge HEdge::prev_g () const inline
Definition at line 557 of file RFC_Window_overlay.h.
References _eID, _pm, and RFC_Pane_overlay::get_prev_edge().
Referenced by HDS_accessor::get_prev_around_destination(), HDS_accessor::get_prev_around_origin(), and Overlay::intersect_link().
 { return _pm->get_prev_edge( _eID); }
HEdge HEdge::prev_l () const inline
If the current edge is a border edges, it returns the previous border edge along the boundary.
Definition at line 554 of file RFC_Window_overlay.h.
References _eID, _pm, and HEdge().
Referenced by Overlay::get_nat_coor(), Overlay::get_next_inode_cw(), RFC_Pane_overlay::get_normal(), Overlay::intersect_link(), Overlay::intersect_link_helper(), Overlay_primitives::project_onto_element(), and Overlay_primitives::snap_blue_ridge_vertex().
 { return HEdge(_pm, _pm->get_prev_real_edge( _eID)); }
Member Data Documentation
Edge_ID HEdge::_eID protected
Definition at line 138 of file HDS_overlay.h.
Referenced by destination_g(), destination_l(), face(), id(), is_border_g(), is_border_l(), next_g(), next_l(), operator!=(), operator<(), operator==(), opposite_g(), opposite_l(), origin_g(), origin_l(), prev_g(), and prev_l().
RFC_Pane_overlay* HEdge::_pm protected
Definition at line 137 of file HDS_overlay.h.
Referenced by destination_g(), destination_l(), face(), is_border_g(), next_g(), next_l(), operator!=(), operator<(), operator==(), opposite_g(), opposite_l(), origin_g(), origin_l(), pane(), prev_g(), and prev_l().
The documentation for this class was generated from the following files:
HDS_overlay.h
RFC_Window_overlay.h