IMPACT: IRAD::Sys::FDSetMan Class Reference
IRAD::Sys::FDSetMan Class Reference
Detailed Description
Definition at line 201 of file FDUtils.H.
#include <FDUtils.H>
Public Types
typedef std::vector< int > FDContainerType
Public Member Functions
FDSetMan ()
fd_set & ReadSet ()
const fd_set ReadSet () const
fd_set & WriteSet ()
const fd_set WriteSet () const
fd_set & ExceptionSet ()
const fd_set ExceptionSet () const
void SetOutDescriptor (int infd)
void SetInDescriptor (int infd)
void ClearOutDescriptor (int infd)
void ClearInDescriptor (int infd)
int AddOutDescriptor (int infd)
int AddInDescriptor (int infd)
int AddIODescriptor (int infd)
void Zero ()
void Clear (int infd)
void SetForRead (int infd=-1)
template<class FDContainer >
void SetForRead (const FDContainer &fds, bool reset=true)
void SetForWrite (int infd=-1)
template<class FDContainer >
void SetForWrite (const FDContainer &fds)
void SetForIO (int infd=-1)
template<class FDContainer >
void SetForIO (const FDContainer &fds, bool reset=true)
int ReadyForOutput (int infd=-1)
int ReadyForInput (int infd=-1)
template<class FDContainer >
int ReadyForOutput (const FDContainer &fds)
template<class FDContainer >
int ReadyForInput (const FDContainer &fds)
int Select (float seconds=0.0, bool reset=true)
int ListenForInput (float seconds=0.0, bool reset=true)
int ListenForOutput (float seconds=0.0, bool reset=true)
template<class FDContainer >
int NSet (const FDContainer &fds, fd_set *fdset)
template<class FDContainer >
void Set (const FDContainer &fds, fd_set *fdset, bool reset=true)
Private Attributes
fd_set readset
fd_set writeset
fd_set exset
int max_descriptor
FDContainerType o_descriptors
FDContainerType i_descriptors
FDContainerType io_descriptors
Member Typedef Documentation
typedef std::vector<int> IRAD::Sys::FDSetMan::FDContainerType
Definition at line 204 of file FDUtils.H.
Constructor & Destructor Documentation
IRAD::Sys::FDSetMan::FDSetMan () inline
Definition at line 217 of file FDUtils.H.
References exset, i_descriptors, io_descriptors, o_descriptors, readset, and writeset.
                  : max_descriptor(-1)
       {
         FD_ZERO(&readset);
         FD_ZERO(&writeset);
         FD_ZERO(&exset);
         o_descriptors.resize(0);
         i_descriptors.resize(0);
         io_descriptors.resize(0);
         //      instreams[0]  = &std::cin;
         //      outstreams[1] = &std::out;
         //      outstreams[2] = &std::cerr;
       };
Member Function Documentation
int IRAD::Sys::FDSetMan::AddInDescriptor (int infd) inline
Definition at line 265 of file FDUtils.H.
References i_descriptors, and SetInDescriptor().
Referenced by main(), and IRAD::TestTCPInterface().
       {
         if(infd < 0)
           return(-1);
         i_descriptors.push_back(infd);
         SetInDescriptor(infd);
         return(0);
       };
int IRAD::Sys::FDSetMan::AddIODescriptor (int infd) inline
Definition at line 273 of file FDUtils.H.
References io_descriptors, SetInDescriptor(), and SetOutDescriptor().
Referenced by main(), and IRAD::TestTCPInterface().
       {
         if(infd < 0)
           return(-1);
         io_descriptors.push_back(infd);
         SetInDescriptor(infd);
         SetOutDescriptor(infd);
         return(0);
       };
int IRAD::Sys::FDSetMan::AddOutDescriptor (int infd) inline
Definition at line 255 of file FDUtils.H.
References o_descriptors, and SetOutDescriptor().
       {
         if(infd < 0)
           return(-1);
         o_descriptors.push_back(infd);
         SetOutDescriptor(infd);
         //      if(infd > max_descriptor)
         //      max_descriptor = infd;
         return(0);
       };
void IRAD::Sys::FDSetMan::Clear (int infd) inline
Definition at line 288 of file FDUtils.H.
References exset, readset, and writeset.
       {
         if(infd >= 0){
           FD_CLR(infd,&readset);
           FD_CLR(infd,&writeset);
           FD_CLR(infd,&exset);
         }
       };
void IRAD::Sys::FDSetMan::ClearInDescriptor (int infd) inline
Definition at line 251 of file FDUtils.H.
References readset.
{
         if(infd >= 0)
           FD_CLR(infd,&readset);
       };
void IRAD::Sys::FDSetMan::ClearOutDescriptor (int infd) inline
Definition at line 247 of file FDUtils.H.
References writeset.
{
         if(infd >= 0)
           FD_CLR(infd,&writeset);
       };
fd_set& IRAD::Sys::FDSetMan::ExceptionSet () inline
Definition at line 233 of file FDUtils.H.
References exset.
 { return(exset); };
const fd_set IRAD::Sys::FDSetMan::ExceptionSet () const inline
Definition at line 234 of file FDUtils.H.
References exset.
 { return(exset); };
int IRAD::Sys::FDSetMan::ListenForInput (float seconds = 0.0, bool reset = true) inline
Definition at line 398 of file FDUtils.H.
References exset, max_descriptor, readset, SetForRead(), and Zero().
       {
         float usec = 1.0E-6;
         struct timeval tv;
         struct timeval *tv_ptr = NULL;
         if(seconds >= 0.0){
           tv_ptr = &tv;
           tv.tv_sec  = static_cast<long>(seconds);
           tv.tv_usec = static_cast<long>((seconds - tv.tv_sec)/usec);
         }
         if(reset){
           this->Zero();
           this->SetForRead();
         }
         int retval = select(max_descriptor+1,&readset,NULL,&exset,tv_ptr);
         if(retval < 0)
           perror("Sys::FDStreamSet::Select::select");
         return(retval);
       };
int IRAD::Sys::FDSetMan::ListenForOutput (float seconds = 0.0, bool reset = true) inline
Definition at line 417 of file FDUtils.H.
References exset, max_descriptor, SetForWrite(), writeset, and Zero().
       {
         float usec = 1.0E-6;
         struct timeval tv;
         struct timeval *tv_ptr = NULL;
         if(seconds >= 0.0){
           tv_ptr = &tv;
           tv.tv_sec  = static_cast<long>(seconds);
           tv.tv_usec = static_cast<long>((seconds - tv.tv_sec)/usec);
         }
         if(reset){
           this->Zero();
           this->SetForWrite();
         }
         int retval = select(max_descriptor+1,NULL,&writeset,&exset,tv_ptr);
         if(retval < 0)
           perror("Sys::FDStreamSet::Select::select");
         return(retval);
       };
template<class FDContainer > int IRAD::Sys::FDSetMan::NSet (const FDContainer & fds, fd_set * fdset) inline
Definition at line 437 of file FDUtils.H.
Referenced by ReadyForInput(), and ReadyForOutput().
       {
         int retval = 0;
         typename FDContainer::const_iterator fdi = fds.begin();
         while(fdi != fds.end())
           retval += FD_ISSET(*fdi++,fdset);
         return(retval);
       };
fd_set& IRAD::Sys::FDSetMan::ReadSet () inline
Definition at line 229 of file FDUtils.H.
References readset.
 { return(readset);    };
const fd_set IRAD::Sys::FDSetMan::ReadSet () const inline
Definition at line 230 of file FDUtils.H.
References readset.
 { return(readset);    };
int IRAD::Sys::FDSetMan::ReadyForInput (int infd = -1) inline
Definition at line 356 of file FDUtils.H.
References i_descriptors, io_descriptors, NSet(), and readset.
Referenced by IRAD::TestTCPInterface().
       {
         int retval = 0;
         if(infd >= 0){
           retval = FD_ISSET(infd,&readset);
         }
         else {
           retval += NSet(i_descriptors,&readset);
           retval += NSet(io_descriptors,&readset);
         }
         return(retval);
       };
template<class FDContainer > int IRAD::Sys::FDSetMan::ReadyForInput (const FDContainer & fds) inline
Definition at line 374 of file FDUtils.H.
References NSet(), and readset.
       {
         return(NSet(fds,&readset));
       };
int IRAD::Sys::FDSetMan::ReadyForOutput (int infd = -1) inline
Definition at line 345 of file FDUtils.H.
References io_descriptors, NSet(), o_descriptors, and writeset.
Referenced by IRAD::TestTCPInterface().
       {
         int retval = 0;
         if(infd >= 0)
           retval = FD_ISSET(infd,&writeset);
         else {
           retval += NSet(o_descriptors,&writeset);
           retval += NSet(io_descriptors,&writeset);
         }
         return(retval);
       };
template<class FDContainer > int IRAD::Sys::FDSetMan::ReadyForOutput (const FDContainer & fds) inline
Definition at line 369 of file FDUtils.H.
References NSet(), and writeset.
       {
         return(NSet(fds,&writeset));
       };
int IRAD::Sys::FDSetMan::Select (float seconds = 0.0, bool reset = true) inline
Definition at line 378 of file FDUtils.H.
References exset, max_descriptor, readset, SetForRead(), SetForWrite(), writeset, and Zero().
Referenced by IRAD::TestTCPInterface().
       {
         float usec = 1.0E-6;
         struct timeval tv;
         struct timeval *tv_ptr = NULL;
         if(seconds >= 0.0){
           tv_ptr = &tv;
           tv.tv_sec  = static_cast<long>(seconds);
           tv.tv_usec = static_cast<long>((seconds - tv.tv_sec)/usec);
         }
         if(reset){
           this->Zero();
           this->SetForRead();
           this->SetForWrite();
         }
         int retval = select(max_descriptor+1,&readset,&writeset,&exset,tv_ptr);
         if(retval < 0)
           perror("Sys::FDStreamSet::Select::select");
         return(retval);
       };
template<class FDContainer > void IRAD::Sys::FDSetMan::Set (const FDContainer & fds, fd_set * fdset, bool reset = true) inline
Definition at line 446 of file FDUtils.H.
Referenced by SetForIO(), SetForRead(), and SetForWrite().
       {
         if(reset)
           FD_ZERO(fdset);
         typename FDContainer::const_iterator fdi = fds.begin();
         while(fdi != fds.end()){
           int descriptor = *fdi++;
           FD_SET(descriptor,fdset);
         }
       };
void IRAD::Sys::FDSetMan::SetForIO (int infd = -1) inline
Definition at line 324 of file FDUtils.H.
References i_descriptors, io_descriptors, o_descriptors, readset, Set(), and writeset.
       {
         if(infd >= 0){
           FD_SET(infd,&readset);
           FD_SET(infd,&writeset);
         }
         else{
           Set(i_descriptors,&readset);
           Set(o_descriptors,&writeset);
           Set(io_descriptors,&readset,false);
           Set(io_descriptors,&writeset,false);
         }
       };
template<class FDContainer > void IRAD::Sys::FDSetMan::SetForIO (const FDContainer & fds, bool reset = true) inline
Definition at line 338 of file FDUtils.H.
References i_descriptors, io_descriptors, o_descriptors, readset, Set(), and writeset.
       {
         Set(i_descriptors,&readset,reset);
         Set(o_descriptors,&writeset,reset);
         Set(io_descriptors,&readset,false);
         Set(io_descriptors,&writeset,false);
       };
void IRAD::Sys::FDSetMan::SetForRead (int infd = -1) inline
Definition at line 296 of file FDUtils.H.
References i_descriptors, io_descriptors, readset, and Set().
Referenced by ListenForInput(), and Select().
       {
         if(infd >= 0)
           FD_SET(infd,&readset);
         else {
           Set(i_descriptors,&readset);
           Set(io_descriptors,&readset,false);
         }
       };
template<class FDContainer > void IRAD::Sys::FDSetMan::SetForRead (const FDContainer & fds, bool reset = true) inline
Definition at line 306 of file FDUtils.H.
References readset, and Set().
       {
         Set(fds,&readset,reset);
       };
void IRAD::Sys::FDSetMan::SetForWrite (int infd = -1) inline
Definition at line 310 of file FDUtils.H.
References io_descriptors, o_descriptors, Set(), and writeset.
Referenced by ListenForOutput(), and Select().
       {
         if(infd >= 0)
           FD_SET(infd,&writeset);
         else{
           Set(o_descriptors,&writeset);
           Set(io_descriptors,&writeset,false);
         }
       };
template<class FDContainer > void IRAD::Sys::FDSetMan::SetForWrite (const FDContainer & fds) inline
Definition at line 320 of file FDUtils.H.
References Set(), and writeset.
       {
         Set(fds,&writeset);
       };
void IRAD::Sys::FDSetMan::SetInDescriptor (int infd) inline
Definition at line 241 of file FDUtils.H.
References max_descriptor, and readset.
Referenced by AddInDescriptor(), and AddIODescriptor().
{
         if(infd >= 0)
           FD_SET(infd,&readset);
         if(infd > max_descriptor)
           max_descriptor = infd;
       };
void IRAD::Sys::FDSetMan::SetOutDescriptor (int infd) inline
Definition at line 235 of file FDUtils.H.
References max_descriptor, and writeset.
Referenced by AddIODescriptor(), and AddOutDescriptor().
{
         if(infd >= 0)
           FD_SET(infd,&writeset);
         if(infd > max_descriptor)
           max_descriptor = infd;
       };
fd_set& IRAD::Sys::FDSetMan::WriteSet () inline
Definition at line 231 of file FDUtils.H.
References writeset.
 { return(writeset);  };
const fd_set IRAD::Sys::FDSetMan::WriteSet () const inline
Definition at line 232 of file FDUtils.H.
References writeset.
 { return(writeset);  };
void IRAD::Sys::FDSetMan::Zero () inline
Definition at line 282 of file FDUtils.H.
References exset, readset, and writeset.
Referenced by ListenForInput(), ListenForOutput(), and Select().
       {
         FD_ZERO(&readset);
         FD_ZERO(&writeset);
         FD_ZERO(&exset);
       };
Member Data Documentation
fd_set IRAD::Sys::FDSetMan::exset private
Definition at line 208 of file FDUtils.H.
Referenced by Clear(), ExceptionSet(), FDSetMan(), ListenForInput(), ListenForOutput(), Select(), and Zero().
FDContainerType IRAD::Sys::FDSetMan::i_descriptors private
Definition at line 211 of file FDUtils.H.
Referenced by AddInDescriptor(), FDSetMan(), ReadyForInput(), SetForIO(), and SetForRead().
FDContainerType IRAD::Sys::FDSetMan::io_descriptors private
Definition at line 212 of file FDUtils.H.
Referenced by AddIODescriptor(), FDSetMan(), ReadyForInput(), ReadyForOutput(), SetForIO(), SetForRead(), and SetForWrite().
int IRAD::Sys::FDSetMan::max_descriptor private
Definition at line 209 of file FDUtils.H.
Referenced by ListenForInput(), ListenForOutput(), Select(), SetInDescriptor(), and SetOutDescriptor().
FDContainerType IRAD::Sys::FDSetMan::o_descriptors private
Definition at line 210 of file FDUtils.H.
Referenced by AddOutDescriptor(), FDSetMan(), ReadyForOutput(), SetForIO(), and SetForWrite().
fd_set IRAD::Sys::FDSetMan::readset private
Definition at line 206 of file FDUtils.H.
Referenced by Clear(), ClearInDescriptor(), FDSetMan(), ListenForInput(), ReadSet(), ReadyForInput(), Select(), SetForIO(), SetForRead(), SetInDescriptor(), and Zero().
fd_set IRAD::Sys::FDSetMan::writeset private
Definition at line 207 of file FDUtils.H.
Referenced by Clear(), ClearOutDescriptor(), FDSetMan(), ListenForOutput(), ReadyForOutput(), Select(), SetForIO(), SetForWrite(), SetOutDescriptor(), WriteSet(), and Zero().
The documentation for this class was generated from the following file:
FDUtils.H