IMPACT: Extrapolate_Central Class Reference
Extrapolate_Central Class Reference
Detailed Description
Definition at line 40 of file Interpolate.h.
#include <Interpolate.h>
Public Member Functions
Extrapolate_Central (Agent *ag, Agent *bkag, const std::string attr, const std::string alpsuf="_alp", int cond=0)
virtual void init (double t)
void run (double t, double dt, double alpha)
Public Member Functions inherited from InterpolateBase
InterpolateBase (Agent *ag, Agent *bkag, int cond=0)
void backup ()
Public Member Functions inherited from Action
Action (void *p=0, const char *name=NULL)
Action (int n, const char **at, int *i=NULL, void *p=0, const char *name=NULL)
Action (int n, const std::string at[], int *i=NULL, void *p=0, const char *name=NULL)
virtual ~Action ()
virtual void declare (Scheduler &)
virtual void finalize ()
virtual const char * name ()
void set_name (const char *name)
virtual void print (FILE *f)
virtual void print_toposort (FILE *f)
virtual void schedule ()
Additional Inherited Members
Protected Types inherited from Action
enum { IN =1, OUT =2, INOUT =3 }
Protected Member Functions inherited from InterpolateBase
void extrapolate_Linear (double dt, double dt_old, double time_old, int a_old, double time_new, int a_new, double time_out, int a_out, int a_gra=-100)
Protected Member Functions inherited from Action
int get_dataitem_handle (int i)
int get_dataitem_handle_const (int i)
int get_dataitem_handle (const std::string str)
void set_attr (int n, const std::string at[], int *id=NULL)
void set_attr (int n, const char *at[], int *id=NULL)
void set_io (int n, const int *io)
void set_io (const char *io)
int get_io (int i)
Protected Attributes inherited from InterpolateBase
Agent * agent
Agent * bkagent
int attr_hdls [4]
int bkup_hdls [3]
int conditional
int on
Protected Attributes inherited from Action
const char * action_name
char ** attr
int * idx
int count
void * usr_ptr
std::vector< int > inout
Constructor & Destructor Documentation
Extrapolate_Central::Extrapolate_Central (Agent * ag, Agent * bkag, const std::string attr, const std::string alpsuf = "_alp", int cond = 0)
Definition at line 171 of file Interpolate.C.
References Action::action_name, Action::attr, Action::IN, Action::OUT, Action::set_attr(), and Action::set_io().
                                                                                                                       : InterpolateBase(ag, bkag, cond)
 {
   action_name = "Extrapolate_Central";
     // INIT_INTERP_HANDLES() in "man_basic.f90"
   std::string.data[4];
  .data[0] = attr;
  .data[1] = attr + "_old";
  .data[2] = attr +  alpsuf;
  .data[3] = attr + "_grad";
   set_attr(4,.data);
   // Define I/O of the arguments.
   int io[] = {IN, IN, OUT, IN};
   set_io( 4, io);
 /*
     // register dataitems
   std::string surf_win = agent->get_surface_window();
   std::string::size_type pos = attr.find(".");
   std::string wname, aname;
   if ( pos == std::string::npos) {
     COM_assertion_msg(0, "ERROR: Here!");
   }
   else {
     wname = attr.substr( 0, pos);
     aname = attr.substr( pos, attr.size()-pos);
   }
   agent->register_use_dataitem( wname, aname, ((BurnAgent*)agent)->parentWin, aname);   // attr
   agent->register_clone_dataitem( conditional, wname, aname+"_old", surf_win, aname+"_alp");   // attr_old
   agent->register_clone_dataitem( conditional, wname, aname+"_grad", surf_win, aname+"_alp");  // attr_grad
 */
 }
Member Function Documentation
void Extrapolate_Central::init (double t) virtual
Reimplemented from InterpolateBase.
Definition at line 206 of file Interpolate.C.
References Action::attr, InterpolateBase::attr_hdls, COM_assertion_msg, COM_get_dataitem_handle(), COM_get_window_handle(), InterpolateBase::conditional, and InterpolateBase::init().
 {
   // check condition
   // first check if window exists
   std::string dataitem = attr[0];
   std::string::size_type pos = dataitem.find(".");
   COM_assertion_msg(pos != std::string::npos, "ERROR: Here!");
   std::string wname = dataitem.substr( 0, pos);
   if (COM_get_window_handle(wname) <= 0) return;
     // check if dataitem exists
   attr_hdls[2] = COM_get_dataitem_handle(attr[2]);          // alp
   if (conditional) {
     if (attr_hdls[2] <= 0) return;
   }
   InterpolateBase::init(t);
 }
void Extrapolate_Central::run (double t, double dt, double alpha) virtual
Implements InterpolateBase.
Definition at line 225 of file Interpolate.C.
References InterpolateBase::agent, Action::attr, InterpolateBase::attr_hdls, COM_assertion_msg, COM_call_function(), RocBlas::copy, InterpolateBase::extrapolate_Linear(), Agent::get_coupling(), Coupling::get_ipc(), Agent::get_old_dt(), Coupling::get_rocmancontrol_param(), MAN_DEBUG, Coupling::new_start(), and RocmanControl_parameters::order.
 {
   if (attr_hdls[2] <= 0) return;
   MAN_DEBUG(2, ("Extrapolate_Central::run (%s) called with t:%e dt:%e alpha:%e.\n", attr[0], t, dt, alpha));
   COM_assertion_msg(alpha>=0.0, "ERROR: Extrapolate_Central called with invalid alpha!");
   COM_assertion_msg(alpha>=-1.e-6 && alpha <= 1+1.e-6, "ERROR: Abort!");
   int order = agent->get_coupling()->get_rocmancontrol_param()->order;
   if (order == 0 || agent->get_coupling()->new_start(t)) {
     COM_call_function( RocBlas::copy, &attr_hdls[0], &attr_hdls[2]);
     return;
   }
   if (agent->get_coupling()->get_ipc() <= 1 && attr_hdls[3] <= 0) {
     COM_call_function( RocBlas::copy, &attr_hdls[0], &attr_hdls[2]);
     return;
   }
   double base = -0.5;
   // linear interpolation.
   extrapolate_Linear(dt, agent->get_old_dt(), base, attr_hdls[1], base+1.0, attr_hdls[0], alpha, attr_hdls[2], attr_hdls[3]);
 }
The documentation for this class was generated from the following files:
Interpolate.h
Interpolate.C