IMPACT: Facet_node_enumerator Class Reference
Facet_node_enumerator Class Reference
Adaptor for enumerating node IDs of a facet of an element.
Detailed Description
Definition at line 176 of file Element_accessors.hpp.
#include <Element_accessors.hpp>
Public Member Functions
Facet_node_enumerator (const Element_node_enumerator *ene, int k)
int size_of_nodes () const
int size_of_corners () const
int size_of_edges () const
void get_nodes (std::vector< int > &nodes, bool quad_ret)
int operator[] (int i) const
Protected Attributes
const Element_node_enumerator
*const _ene
const int _k
const int _ne
const int * _fn_list
Static Protected Attributes
static const int _face_node_lists_tets [4][6]
static const int _face_node_lists_pyra [5][8]
static const int _face_node_lists_pris [5][9]
static const int _face_node_lists_hexa [6][9]
Constructor & Destructor Documentation
Facet_node_enumerator::Facet_node_enumerator (const Element_node_enumerator * ene, int k)
Definition at line 137 of file Element_accessors.C.
References _face_node_lists_hexa, _face_node_lists_pris, _face_node_lists_pyra, _face_node_lists_tets, _fn_list, _k, _ne, COM_assertion_msg, Element_node_enumerator::dimension(), and Element_node_enumerator::size_of_nodes().
   : _ene(ene), _k(k), _ne(0) {
   if ( ene->dimension() == 2) {
     const_cast<int&>(_ne) = 1;
     _fn_list = NULL;
   }
   else {
     switch ( ene->size_of_nodes()) {
     case 4:    // Tetrahedra
     case 10: {
       const_cast<int&>(_ne) = 3;
       _fn_list = _face_node_lists_tets[_k];
       break;
     }
     case 5:    // Pyramids
     case 14: {
       const_cast<int&>(_ne) = (_k==0)? 4 : 3;
       _fn_list = _face_node_lists_pyra[_k];
       break;
     }
     case 6:    // Prisms (Pentahedra)
     case 15:
     case 18: {
       const_cast<int&>(_ne) = (_k<3)? 4 : 3;
       _fn_list = _face_node_lists_pris[_k];
       break;
     }
     case 8:    // Hexahedra
     case 20:
     case 27: {
       const_cast<int&>(_ne) = 4;
       _fn_list = _face_node_lists_hexa[_k];
       break;
     }
     default: COM_assertion_msg(false, "Not supported yet.");
     }
   }
 }
Member Function Documentation
void Facet_node_enumerator::get_nodes (std::vector< int > & nodes, bool quad_ret)
Definition at line 200 of file Element_accessors.C.
References _ene, _fn_list, _k, _ne, size_of_corners(), Element_node_enumerator::size_of_edges(), and size_of_nodes().
Referenced by Pane_boundary::determine_border_nodes_3().
{
   int nn = quad_ret ? size_of_nodes() : size_of_corners();
   nodes.resize( nn);
   if ( _ne == 1) {
     int num_edges = _ene->size_of_edges();
     // Retrun the nodes on each edge.
     nodes[0] = (*_ene)[(_k)%num_edges];
     nodes[1] = (*_ene)[(_k+1)%num_edges];
     if (nn>2) nodes[2] = (*_ene)[num_edges+_k];
   }
   else {
     for ( int i=0; i<nn; ++i) nodes[i] = (*_ene)[_fn_list[i]];
   }
 }
int Facet_node_enumerator::operator[] (int i) const
Definition at line 190 of file Element_accessors.C.
References _ene, _fn_list, _k, _ne, and Element_node_enumerator::size_of_edges().
{
   if ( _ne > 1)
     return (*_ene)[_fn_list[i]];
   else {
     if ( i<2) return (*_ene)[(_k+i)%_ene->size_of_edges()];
     else return (*_ene)[_ene->size_of_edges()+_k];
   }
 }
int Facet_node_enumerator::size_of_corners () const inline
Definition at line 185 of file Element_accessors.hpp.
References _ne.
Referenced by get_nodes(), and Pane_boundary::min_squared_edge_len().
 { return (_ne == 1) ? 2 : _ne ; }
int Facet_node_enumerator::size_of_edges () const inline
Definition at line 188 of file Element_accessors.hpp.
References _ne.
Referenced by Pane_boundary::determine_border_nodes_3().
 { return _ne;  }
int Facet_node_enumerator::size_of_nodes () const
Definition at line 176 of file Element_accessors.C.
References _ene, _k, _ne, Element_node_enumerator::is_quadratic(), num_nodes, and Element_node_enumerator::size_of_nodes().
Referenced by get_nodes().
{
   if ( _ne == 1)
     return _ene->is_quadratic() ? 3 : 2;
   else {
     int nn = _ne; // Number of nodes per face
     if ( _ene->is_quadratic()) {
       int num_nodes = _ene->size_of_nodes();
       nn += _ne + (num_nodes == 18 && _k<3 || num_nodes == 27);
     }
     return nn;
   }
 }
Member Data Documentation
const Element_node_enumerator* const Facet_node_enumerator::_ene protected
Definition at line 202 of file Element_accessors.hpp.
Referenced by get_nodes(), operator[](), and size_of_nodes().
const int Facet_node_enumerator::_face_node_lists_hexa static protected
Initial value:
=
{ {0,3,2,1,11,10,9, 8, 20}, {0,1,5,4,8, 13,16,12,21},
  {1,2,6,5,9, 14,17,13,22}, {2,3,7,6,10,15,18,14,23},
  {0,4,7,3,12,19,15,11,24}, {4,5,6,7,16,17,18,19,25}}
Definition at line 200 of file Element_accessors.hpp.
Referenced by Facet_node_enumerator().
const int Facet_node_enumerator::_face_node_lists_pris static protected
Initial value:
=
{ {0,1,4,3,6,10,12,9,15}, {1,2,5,4,7,11,13,10,16}, {2,0,3,5,8,9,14,11,17},
  {0,2,1,8,7,6,-1,-1,-1}, {3,4,5,12,13,14,-1,-1,-1}}
Definition at line 199 of file Element_accessors.hpp.
Referenced by Facet_node_enumerator().
const int Facet_node_enumerator::_face_node_lists_pyra static protected
Initial value:
=
{ {0,3,2,1,8,7,6,5}, {0,1,4,5,10,9,-1,-1}, {1,2,4,6,11,10,-1,-1},
  {2,3,4,7,12,11,-1,-1}, {3,0,4,8,9,12,-1,-1}}
Definition at line 198 of file Element_accessors.hpp.
Referenced by Facet_node_enumerator().
const int Facet_node_enumerator::_face_node_lists_tets static protected
Initial value:
=
{ {0, 2, 1, 6, 5, 4}, { 0, 1, 3, 4, 8, 7},
  {1, 2, 3, 5, 9, 8}, {2, 0, 3, 6, 7, 9}}
Definition at line 197 of file Element_accessors.hpp.
Referenced by Facet_node_enumerator().
const int* Facet_node_enumerator::_fn_list protected
Definition at line 205 of file Element_accessors.hpp.
Referenced by Facet_node_enumerator(), get_nodes(), and operator[]().
const int Facet_node_enumerator::_k protected
Definition at line 203 of file Element_accessors.hpp.
Referenced by Facet_node_enumerator(), get_nodes(), operator[](), and size_of_nodes().
const int Facet_node_enumerator::_ne protected
Definition at line 204 of file Element_accessors.hpp.
Referenced by Facet_node_enumerator(), get_nodes(), operator[](), size_of_corners(), size_of_edges(), and size_of_nodes().
The documentation for this class was generated from the following files:
Element_accessors.hpp
Element_accessors.C