IMPACT: ComponentInterface Class Reference
ComponentInterface Class Reference
A ComponentInterface object contains multiple panes and multiple data dataitems.
Detailed Description
Definition at line 19 of file ComponentInterface.hpp.
#include <ComponentInterface.hpp>
Classes
class Pane_friend
struct Pointer_descriptor
Public Types
typedef std::map< int, int > Proc_map
Public Member Functions
Constructor and destructor
ComponentInterface (const std::string &name, MPI_Comm c)
Create a ComponentInterface object with a given name and MPI communicator.
virtual ~ComponentInterface ()
Destructor.
Identity
const std::string & name () const
Obtain the CI's name.
MPI_Comm get_communicator () const
Obtain the communicator of the CI.
Function and data management
void set_function (const std::string &fname, Func_ptr func, const std::string &intents, const COM_Type *types, DataItem *a, bool if_f90=false) throw (COM_exception)
Initialize a Function record.
void set_function (const std::string &fname, Member_func_ptr func, const std::string &intents, const COM_Type *types, DataItem *a, bool if_f90=false) throw (COM_exception)
Initialize a Function record.
DataItem * new_dataitem (const std::string &aname, const char loc, const int type, int ncomp, const std::string &unit) throw (COM_exception)
Create a new DataItem object with given properties.
void delete_dataitem (const std::string &aname) throw (COM_exception)
Delete an existing DataItem object.
void set_size (const std::string &aname, int pane_id, int nitems, int ng=0) throw (COM_exception)
Set the sizes of an dataitem for a specific pane.
void set_array (const std::string &aname, const int pane_id, void *addr, int strd=0, int cap=0, bool is_const=false) throw (COM_exception)
Associate an array with an dataitem for a specific pane.
void alloc_array (const std::string &aname, const int pane_id, void **addr, int strd=0, int cap=0) throw (COM_exception)
Allocate memory for an dataitem for a specific pane and set addr to the address.
void resize_array (const std::string &aname, const int pane_id, void **addr, int strd=-1, int cap=0) throw (COM_exception)
Resize memory for an dataitem for a specific pane and set addr to the address.
void resize_array (DataItem *a, void **addr, int strd=-1, int cap=0) throw (COM_exception)
void resize_array (Connectivity *c, void **addr, int strd=-1, int cap=0) throw (COM_exception)
void append_array (const std::string &aname, const int pane_id, const void *val, int v_strd, int v_size) throw (COM_exception)
Append the given array to the end of the dataitem on a specific pane, and reallocate memory for the dataitem if necessary.
void dealloc_array (const std::string &aname, const int pane_id=0) throw (COM_exception)
Deallocate memory for an dataitem for a specific pane if allocated by Roccom.
void dealloc_array (DataItem *a) throw (COM_exception)
void dealloc_array (Connectivity *c) throw (COM_exception)
DataItem * inherit (DataItem *from, const std::string &aname, int inherit_mode, bool withghost, const DataItem *cond, int val) throw (COM_exception)
Inherit the dataitems of another CI window with a different name.
void copy_dataitem (const DataItem *from, DataItem *to) throw (COM_exception)
Copy an dataitem object onto another.
DataItem * get_dataitem (const std::string &aname, char *l, int *t, int *n, std::string *u) const throw (COM_exception)
Get the meta-information about an dataitem.
void get_size (const std::string &aname, int pane_id, int *nitems, int *ng) const throw (COM_exception)
Get the sizes of an dataitem for a specific pane.
int get_status (const std::string &aname, int pane_id) const throw (COM_exception)
Get the status of an dataitem or pane.
void get_parent (const std::string &aname, int pane_id, std::string &name) const throw (COM_exception)
Get the parent name of an dataitem and load into name.
void get_array (const std::string &aname, const int pane_id, Pointer_descriptor &addr, int *strd=NULL, int *cap=NULL, bool is_const=false) throw (COM_exception)
Get the address associated with an dataitem for a specific pane.
void copy_array (const std::string &aname, const int pane_id, void *val, int v_strd=0, int v_size=0, int offset=0) const throw (COM_exception)
Copy an dataitem on a specific pane into a given array.
void init_done (bool pane_changed=true) throw (COM_exception)
Perform some final checking of the CI.
Pane management
int size_of_panes () const
Obtain the number of local panes in the CI window.
int size_of_panes_global () const
Obtain the total number of panes in the CI window on all processes.
int owner_rank (const int pane_id) const
Obtain the process rank that owns a given pane.
int last_dataitem_id () const
Return the last dataitem id.
const Proc_map & proc_map () const
Obtain the process map.
void delete_pane (const int pane_id) throw (COM_exception)
Remove the pane with given ID.
Miscellaneous
Pane & pane (const int pane_id, bool insert=false) throw (COM_exception)
Find the pane with given ID. If not found, insert a pane with given ID.
const Pane & pane (const int pane_id) const throw (COM_exception)
void panes (std::vector< int > &ps, int rank=-2)
Obtain all the local panes of the CI window.
void panes (std::vector< Pane * > &ps)
Obtain all the local panes of the CI window.
void panes (std::vector< const Pane * > &ps) const
Obtain all the local panes of the CI window.
void dataitems (std::vector< DataItem * > &as)
Obtain all the dataitems of the pane.
void dataitems (std::vector< const DataItem * > &as) const
Obtain all the dataitems of the pane.
DataItem * dataitem (const std::string &a) throw (COM_exception)
Obtain a pointer to the dataitem metadata from its name.
const DataItem * dataitem (const std::string &a) const throw (COM_exception)
DataItem * dataitem (int i) throw (COM_exception)
Obtain a pointer to the dataitem metadata from its index.
const DataItem * dataitem (int i) const throw (COM_exception)
Function * function (const std::string &f)
Obtain the function pointer from its name.
const Function * function (const std::string &f) const
Protected Types
enum { STATUS_SHRUNK, STATUS_CHANGED, STATUS_NOCHANGE }
Protected Member Functions
void reinit_dataitem (DataItem *attr, OP_Init op, void **addr=NULL, int strd=0, int cap=0) throw (COM_exception)
Implementation for setting (op==OP_SET or OP_SET_CONST), allocating (op==OP_ALLOC), resizing (op==OP_RESIZE) and deallocating (op==OP_DEALLOC) an array for a specific dataitem.
void reinit_conn (Connectivity *con, OP_Init op, int **addr=NULL, int strd=0, int cap=0) throw (COM_exception)
Template implementation for setting (op==OP_SET or OP_SET_CONST), allocating (op==OP_ALLOC), resizing (op==OP_RESIZE) and deallocating (op==OP_DEALLOC) an array for a specific connectivity table.
Protected Attributes
Pane _dummy
Dummy pane.
std::string _name
Name of the CI.
Attr_map _attr_map
Map from dataitem names to their metadata.
Func_map _func_map
Map from function names to their metadata.
Pane_map _pane_map
Map from pane ID to their metadata.
Proc_map _proc_map
Map from pane ID to process ranks.
int _last_id
The last used dataitem index.
MPI_Comm _comm
the MPI communicator of the CI.
int _status
Status of the CI.
Private Types
typedef std::map< std::string,
Function > Func_map
typedef std::map< std::string,
DataItem * > Attr_map
typedef std::map< int, Pane * > Pane_map
typedef Pane::OP_Init OP_Init
Private Member Functions
ComponentInterface (const ComponentInterface &)
ComponentInterface & operator= (const ComponentInterface &)
Member Typedef Documentation
typedef std::map< std::string, DataItem*> ComponentInterface::Attr_map private
Definition at line 21 of file ComponentInterface.hpp.
typedef std::map< std::string, Function> ComponentInterface::Func_map private
Definition at line 20 of file ComponentInterface.hpp.
typedef Pane::OP_Init ComponentInterface::OP_Init private
Definition at line 35 of file ComponentInterface.hpp.
typedef std::map< int, Pane*> ComponentInterface::Pane_map private
Definition at line 22 of file ComponentInterface.hpp.
typedef std::map<int,int> ComponentInterface::Proc_map
Definition at line 38 of file ComponentInterface.hpp.
Member Enumeration Documentation
anonymous enum protected
Enumerator
STATUS_SHRUNK
STATUS_CHANGED
STATUS_NOCHANGE
Definition at line 365 of file ComponentInterface.hpp.
 { STATUS_SHRUNK, STATUS_CHANGED, STATUS_NOCHANGE };
Constructor & Destructor Documentation
COM_BEGIN_NAME_SPACE ComponentInterface::ComponentInterface (const std::string & name, MPI_Comm c)
Parameters
name name of the CI window
c MPI communicator where the CI resides
Definition at line 16 of file ComponentInterface.C.
References _attr_map, _dummy, COM_NUM_KEYWORDS, Pane::dataitem(), DataItem::is_digit(), and DataItem::name().
   : _dummy( this, 0), _name( s), _last_id(COM_NUM_KEYWORDS),
     _comm(c), _status( STATUS_NOCHANGE)
 {
   // Insert keywords into _attr_map
   for ( int i=0; i<COM_NUM_KEYWORDS; ++i) {
     DataItem *a = _dummy.dataitem(i);
     if ( !DataItem::is_digit(a->name()[0])) _attr_map[ a->name()] = a;
   }
 }
ComponentInterface::~ComponentInterface () virtual
Definition at line 27 of file ComponentInterface.C.
References _pane_map.
 {
   for ( Pane_map::iterator it=_pane_map.begin(); it!=_pane_map.end(); ++it)
     delete it->second;
 }
ComponentInterface::ComponentInterface (const ComponentInterface &) private
Member Function Documentation
void ComponentInterface::alloc_array (const std::string & aname, const int pane_id, void ** addr, int strd = 0, int cap = 0) throw (COM_exception)
alloc_array, resize_array, append_array
Definition at line 212 of file ComponentInterface.C.
References addr, append_frame, cap, COM_ERR_DATAITEM_NOTEXIST, Connectivity::is_element_name(), Pane::OP_ALLOC, pane_id, and strd.
 {
   if ( Connectivity::is_element_name( aname)) {
     Pane &pn = pane(pane_id,true);
     Connectivity *con = ((Pane_friend&)pn).connectivity( aname);
     if ( con==NULL)
       throw COM_exception( COM_ERR_DATAITEM_NOTEXIST, append_frame
                            (name()+"."+aname,ComponentInterface::alloc_array));
     reinit_conn( con, Pane::OP_ALLOC, (int**)addr, strd, cap);
   }
   else {
     DataItem *a = pane( pane_id,true).dataitem( aname);
     if ( a==NULL)
       throw COM_exception( COM_ERR_DATAITEM_NOTEXIST, append_frame
                            (name()+"."+aname,ComponentInterface::alloc_array));
     reinit_dataitem( a, Pane::OP_ALLOC, addr, strd, cap);
   }
 }
void ComponentInterface::append_array (const std::string & aname, const int pane_id, const void * val, int v_strd, int v_size) throw (COM_exception)
set_array, alloc_array, resize_array
Definition at line 258 of file ComponentInterface.C.
References DataItem::append_array(), append_frame, COM_assertion_msg, COM_ERR_DATAITEM_NOTEXIST, Connectivity::is_element_name(), COM_exception::msg, Pane::OP_RESIZE, pane_id, DataItem::set_size(), DataItem::size_of_items(), DataItem::size_set(), and DataItem::stride().
 {
   COM_assertion_msg( !Connectivity::is_element_name( aname),
                      "append_array supports only CI window and pane dataitems");
   DataItem *a = pane( pane_id,true).dataitem( aname);
   if ( a==NULL)
     throw COM_exception( COM_ERR_DATAITEM_NOTEXIST, append_frame
                          (name()+"."+aname,ComponentInterface::append_array));
   try {
     // Set size to 0 if not yet set.
     if ( !a->size_set()) a->set_size(0);
     // resize the target dataitem.
     reinit_dataitem( a, Pane::OP_RESIZE, NULL, a->stride(),
                  a->size_of_items()+v_size);
   }
   catch ( COM_exception ex) {
     ex.msg = append_frame( ex.msg, ComponentInterface::append_array);
     throw ex;
   }
   // copy the array to the back of the target array
   a->append_array( val, v_strd, v_size);
 }
void ComponentInterface::copy_array (const std::string & aname, const int pane_id, void * val, int v_strd = 0, int v_size = 0, int offset = 0) const throw (COM_exception)
Parameters
aname dataitem name
pane_id pane ID
val address of the user array
v_strd stride of user array. 0 (the default) indicates number of components.
v_size number of items to be copied. 0 (the default) indicates number of items of the dataitem.
offset starting item to be copied in the dataitem. alloc_array, resize_array, get_array
Definition at line 659 of file ComponentInterface.C.
References append_frame, COM_ERR_DATAITEM_NOTEXIST, Pane::connectivity(), copy_array_common(), Pane::dataitem(), Connectivity::is_element_name(), COM_exception::msg, and pane_id.
 {
   const Pane_friend *pn;
   try { pn = &(Pane_friend&)pane(pane_id); }
   catch ( COM_exception ex) {
     ex.msg = append_frame( ex.msg, ComponentInterface::copy_array);
     throw ex;
   }
   if ( Connectivity::is_element_name( aname)) {
     const Connectivity *conn = pn->connectivity( aname);
     if ( conn == NULL)
       throw COM_exception( COM_ERR_DATAITEM_NOTEXIST, append_frame
                            (name()+"."+aname, ComponentInterface::copy_array));
     copy_array_common( conn, pane_id,
                        val, v_strd, v_size, offset);
   }
   else {
     const DataItem *attr = pn->dataitem( aname);
     if ( attr == NULL)
       throw COM_exception( COM_ERR_DATAITEM_NOTEXIST, append_frame
                            (name()+"."+aname, ComponentInterface::copy_array));
     copy_array_common( attr, pane_id,
                        val, v_strd, v_size, offset);
   }
 }
void ComponentInterface::copy_dataitem (const DataItem * from, DataItem * to) throw (COM_exception) inline
Definition at line 184 of file ComponentInterface.hpp.
References inherit(), and Pane::INHERIT_COPY.
{
     inherit( const_cast<DataItem*>(from), to->name(),
              Pane::INHERIT_COPY, true, NULL, 0);
   }
DataItem * ComponentInterface::dataitem (const std::string & a) throw (COM_exception)
Definition at line 816 of file ComponentInterface.C.
References append_frame, COM_ERR_INVALID_DATAITEM_NAME, DataItem::id(), DataItem::is_digit(), and DataItem::size_of_components().
Referenced by Pane::dataitem(), and dataitem().
 {
   if ( !DataItem::is_digit(aname[0])) {
     Attr_map::iterator it = _attr_map.find( aname);
     if ( it == _attr_map.end())
       return NULL;
     else
       return it->second;
   }
   else {
     std::string::size_type start = aname.find( '-');
     if ( start == aname.npos)
       throw COM_exception( COM_ERR_INVALID_DATAITEM_NAME, append_frame
                            (_name+"."+aname,ComponentInterface::dataitem));
     Attr_map::iterator it = _attr_map.find( &aname[start+1]);
     if ( it != _attr_map.end()) {
       DataItem *att = it->second;
       if ( att->size_of_components()>1) {
         // Get the subcomponent
         int i = std::atoi( aname.c_str());
         if ( i<=0 || i>att->size_of_components())
           throw COM_exception( COM_ERR_INVALID_DATAITEM_NAME, append_frame
                                (_name+"."+aname,ComponentInterface::dataitem));
         return dataitem( att->id()+i);
       }
     }
     return NULL;
   }
 }
const DataItem* ComponentInterface::dataitem (const std::string & a) const throw (COM_exception) inline
Definition at line 313 of file ComponentInterface.hpp.
References dataitem().
   { return const_cast<ComponentInterface*>(this)->dataitem( a); }
DataItem* ComponentInterface::dataitem (int i) throw (COM_exception) inline
Definition at line 317 of file ComponentInterface.hpp.
References _dummy, and Pane::dataitem().
   { return _dummy.dataitem( i); }
const DataItem* ComponentInterface::dataitem (int i) const throw (COM_exception) inline
Definition at line 319 of file ComponentInterface.hpp.
References _dummy, and Pane::dataitem().
   { return _dummy.dataitem( i); }
void ComponentInterface::dataitems (std::vector< DataItem * > & as) inline
Definition at line 305 of file ComponentInterface.hpp.
References _dummy, and Pane::dataitems().
Referenced by Rocblas::copy(), Rocblas::rand(), and Rocblas::swap().
   { _dummy.dataitems( as); }
void ComponentInterface::dataitems (std::vector< const DataItem * > & as) const inline
Definition at line 308 of file ComponentInterface.hpp.
References _dummy, and Pane::dataitems().
   { _dummy.dataitems( as); }
void ComponentInterface::dealloc_array (const std::string & aname, const int pane_id = 0) throw (COM_exception)
alloc_array, resize_array
Definition at line 285 of file ComponentInterface.C.
References append_frame, COM_ERR_DATAITEM_NOTEXIST, Connectivity::is_element_name(), Pane::OP_DEALLOC, and pane_id.
 {
   if ( Connectivity::is_element_name( aname)) {
     Pane &pn = pane(pane_id);
     Connectivity *con = ((Pane_friend&)pn).connectivity( aname);
     if ( con==NULL)
       throw COM_exception( COM_ERR_DATAITEM_NOTEXIST, append_frame
                            (name()+"."+aname,ComponentInterface::dealloc_array));
     reinit_conn( con, Pane::OP_DEALLOC);
   }
   else {
     DataItem *a = pane( pane_id).dataitem( aname);
     if ( a==NULL)
       throw COM_exception( COM_ERR_DATAITEM_NOTEXIST, append_frame
                            (name()+"."+aname,ComponentInterface::dealloc_array));
     reinit_dataitem( a, Pane::OP_DEALLOC);
   }
 }
void ComponentInterface::dealloc_array (DataItem * a) throw (COM_exception) inline
Definition at line 165 of file ComponentInterface.hpp.
References Pane::OP_DEALLOC, and reinit_dataitem().
   { reinit_dataitem( a, Pane::OP_DEALLOC); }
void ComponentInterface::dealloc_array (Connectivity * c) throw (COM_exception) inline
Definition at line 168 of file ComponentInterface.hpp.
References Pane::OP_DEALLOC, and reinit_conn().
   { reinit_conn( c, Pane::OP_DEALLOC); }
void ComponentInterface::delete_dataitem (const std::string & aname) throw (COM_exception)
Definition at line 111 of file ComponentInterface.C.
References append_frame, COM_DATA, COM_ERR_DATAITEM_NOTEXIST, COM_ERR_INVALID_DATAITEM_NAME, COM_NUM_KEYWORDS, Pane::delete_dataitem(), DataItem::id(), DataItem::is_digit(), DataItem::name(), and DataItem::size_of_components().
 {
   Attr_map::iterator it = _attr_map.find( aname);
   if ( it == _attr_map.end())
     throw COM_exception( COM_ERR_DATAITEM_NOTEXIST,append_frame
                          (_name+"."+aname,ComponentInterface::delete_dataitem));
   DataItem *attr = it->second;
   int id = attr->id(), ncomp=attr->size_of_components();
   if ( id < COM_NUM_KEYWORDS && id != COM_DATA)
     throw COM_exception( COM_ERR_INVALID_DATAITEM_NAME,append_frame
                          (_name+"."+aname,ComponentInterface::delete_dataitem));
   // Remove the object from both the set
   ((Pane_friend&)_dummy).delete_dataitem( id);
   // Remove from all panes.
   for (Pane_map::iterator it=_pane_map.begin(); it!=_pane_map.end(); ++it) {
     Pane_friend *pn = (Pane_friend*)it->second;
     pn->delete_dataitem( id);
   }
   // Update last id
   if (id != COM_DATA) {
     _attr_map.erase( it); // Remove from _attr_map
     if ( _last_id == id + ncomp+(ncomp>1)) {
       _last_id = id;
       if ( _status==STATUS_NOCHANGE) _status = STATUS_CHANGED;
     }
     else
       _status = STATUS_SHRUNK;
   }
   else if (_last_id>COM_NUM_KEYWORDS) {
     _attr_map.clear();
     for ( int i=0; i<COM_NUM_KEYWORDS; ++i) {
       DataItem *a = _dummy.dataitem(i);
       if ( !DataItem::is_digit(a->name()[0])) _attr_map[ a->name()] = a;
     }
     _status = STATUS_CHANGED;
     _last_id = COM_NUM_KEYWORDS;
   }
 }
void ComponentInterface::delete_pane (const int pane_id) throw (COM_exception) inline
Definition at line 274 of file ComponentInterface.hpp.
References _pane_map, and COM_ERR_PANE_NOTEXIST.
{
     if ( pane_id == 0) { // delete all panes
       _pane_map.clear();
     }
     else {
       Pane_map::iterator it = _pane_map.find( pane_id);
       if ( it == _pane_map.end()) throw COM_exception(COM_ERR_PANE_NOTEXIST);
       delete it->second;
       _pane_map.erase( it);
     }
   }
Function * ComponentInterface::function (const std::string & f)
Definition at line 851 of file ComponentInterface.C.
References _func_map.
 {
   Func_map::iterator it = _func_map.find( fname);
   if ( it == _func_map.end())
     return NULL;
   else
     return &it->second;
 }
const Function* ComponentInterface::function (const std::string & f) const inline
Definition at line 324 of file ComponentInterface.hpp.
References IMPACT::ExampleProgram::f().
   { return const_cast<ComponentInterface*>(this)->function( f); }
void ComponentInterface::get_array (const std::string & aname, const int pane_id, Pointer_descriptor & addr, int * strd = NULL, int * cap = NULL, bool is_const = false) throw (COM_exception)
Parameters
aname dataitem name
pane_id pane ID
addr address of the array
strd Stride between two items of each component
cap capacity of the array alloc_array, resize_array, copy_array
Definition at line 615 of file ComponentInterface.C.
References addr, append_frame, cap, COM_ERR_DATAITEM_NOTEXIST, Pane::connectivity(), Pane::dataitem(), get_array_common(), Connectivity::is_element_name(), COM_exception::msg, pane_id, and strd.
Referenced by get_array_common().
 {
   Pane_friend *pn;
   try { pn = &(Pane_friend&)pane(pane_id); }
   catch ( COM_exception ex) {
     ex.msg = append_frame( ex.msg, ComponentInterface::get_array);
     throw ex;
   }
   if ( Connectivity::is_element_name( aname)) {
     // Define as const reference to avoid exception.
     const Connectivity *con=pn->connectivity( aname);
     if ( con==NULL)
       throw COM_exception( COM_ERR_DATAITEM_NOTEXIST,append_frame
                            (name()+"."+aname,ComponentInterface::get_array));
     get_array_common( con, pane_id, addr, strd, cap, is_const);
   }
   else {
     // Define as const reference to avoid exception.
     const DataItem *a = pn->dataitem( aname);
     if ( a==NULL)
       throw COM_exception( COM_ERR_DATAITEM_NOTEXIST,append_frame
                            (name()+"."+aname,ComponentInterface::get_array));
     get_array_common( a, pane_id, addr, strd, cap, is_const);
   }
 }
MPI_Comm ComponentInterface::get_communicator () const inline
Definition at line 72 of file ComponentInterface.hpp.
References _comm.
Referenced by COM::COM_base::get_communicator(), COM::ParallelTestingObject< CommType, ResultsType >::Test__WindowGetSetCommunicator(), and Rocout::write_dataitem_internal().
 { return _comm; }
DataItem * ComponentInterface::get_dataitem (const std::string & aname, char * l, int * t, int * n, std::string * u) const throw (COM_exception)
Parameters
aname dataitem name
l location
t data type
n number of components
u unit
Definition at line 436 of file ComponentInterface.C.
References append_frame, COM_ERR_DATAITEM_NOTEXIST, COM_INT, DataItem::data_type(), Connectivity::get_size_info(), Connectivity::is_element_name(), DataItem::location(), Connectivity::SIZE_NNODES, DataItem::size_of_components(), and DataItem::unit().
{
   // Special handing for connectivity tables
   if ( Connectivity::is_element_name( aname)) {
     // Set the arguments if not NULL.
     if ( loc) *loc = 'p';
     if ( type) *type = COM_INT;
     // Return the number of nodes.
     if ( ncomp) *ncomp = Connectivity::get_size_info(aname)
                   [Connectivity::SIZE_NNODES];
     if ( unit) *unit = "";
     return NULL; // A connectivity is not defined in ComponentInterface scope.
   }
   else {
     // Obtain reference to the dataitem
     Attr_map::const_iterator it = _attr_map.find( aname);
     if ( it == _attr_map.end())
       throw COM_exception(COM_ERR_DATAITEM_NOTEXIST, append_frame
                           (_name+"."+aname,ComponentInterface::get_dataitem));
     DataItem &a = *it->second;
     // Set the arguments if not NULL.
     if ( loc) *loc = a.location();
     if ( type) *type = a.data_type();
     if ( ncomp) *ncomp = a.size_of_components();
     if ( unit) *unit = a.unit();
     return &a;
   }
 }
void ComponentInterface::get_parent (const std::string & aname, int pane_id, std::string & name) const throw (COM_exception)
If the dataitem has no parent, then name is empty.
Definition at line 540 of file ComponentInterface.C.
References append_frame, COM_ERR_DATAITEM_NOTEXIST, Pane::connectivity(), Pane::dataitem(), Connectivity::is_element_name(), and COM_exception::msg.
{
   const Pane_friend *pn;
   try {
     pn = &(Pane_friend&)pane(pid);
     // Special handing for connectivity
     if ( Connectivity::is_element_name( aname)) {
       // Get the corresponding dataitem object.
       const COM::Connectivity *conn = pn->connectivity( aname);
       if ( conn==NULL)
         throw COM_exception( COM_ERR_DATAITEM_NOTEXIST, append_frame
                              (name()+"."+aname,ComponentInterface::get_parent));
       conn = conn->parent();
       if ( conn==NULL) parent.clear();
       else parent = conn->fullname();
     }
     else {
       // Get the corresponding dataitem object.
       const COM::DataItem *attr = pn->dataitem( aname);
       if ( attr==NULL)
         throw COM_exception( COM_ERR_DATAITEM_NOTEXIST, append_frame
                              (name()+"."+aname,ComponentInterface::get_parent));
       if ( attr==NULL) parent.clear();
       else parent = attr->fullname();
     }
   } catch ( COM_exception ex) {
     ex.msg = append_frame( ex.msg, ComponentInterface::get_parent);
     throw ex;
   }
 }
void ComponentInterface::get_size (const std::string & aname, int pane_id, int * nitems, int * ng) const throw (COM_exception)
Parameters
aname dataitem name
pane_id pane ID
nitems total number of items (including ghosts)
ng number of ghosts
Definition at line 479 of file ComponentInterface.C.
References append_frame, COM_ERR_DATAITEM_NOTEXIST, Pane::connectivity(), Pane::dataitem(), get_size_common(), Connectivity::is_element_name(), and COM_exception::msg.
Referenced by get_size_common().
{
   const Pane_friend *pn;
   try { pn = &(Pane_friend&)pane(pid); }
   catch ( COM_exception ex) {
     ex.msg = append_frame( ex.msg, ComponentInterface::get_size);
     throw ex;
   }
   // Special handing for connectivity
   if ( Connectivity::is_element_name( aname)) {
     // Get the corresponding dataitem object.
     const COM::Connectivity *conn = pn->connectivity( aname);
     if ( conn==NULL)
       throw COM_exception( COM_ERR_DATAITEM_NOTEXIST, append_frame
                            ( name()+"."+aname, ComponentInterface::get_size));
     get_size_common( conn, pid, nitem, ng);
   }
   else {
     // Get the corresponding dataitem object.
     const COM::DataItem *attr = pn->dataitem( aname);
     if ( attr==NULL)
       throw COM_exception( COM_ERR_DATAITEM_NOTEXIST, append_frame
                            ( name()+"."+aname, ComponentInterface::get_size));
     get_size_common( attr, pid, nitem, ng);
   }
 }
int ComponentInterface::get_status (const std::string & aname, int pane_id) const throw (COM_exception)
Roccom_base::get_status()
Definition at line 509 of file ComponentInterface.C.
References append_frame, Pane::connectivity(), Pane::dataitem(), Connectivity::is_element_name(), COM_exception::msg, and DataItem::status().
Referenced by COM::COM_base::get_status().
{
   // If aname is empty, then check the status of the pane.
   if ( aname.empty()) {
     Pane_map::const_iterator pit = _pane_map.find( pid);
     if ( pit == _pane_map.end()) return -1;
     else return 0;
   }
   const Pane_friend *pn;
   try { pn = &(Pane_friend&)pane(pid); }
   catch ( COM_exception ex) {
     ex.msg = append_frame( ex.msg, ComponentInterface::get_status);
     throw ex;
   }
   // Special handing for connectivity
   if ( Connectivity::is_element_name( aname)) {
     // Get the corresponding dataitem object.
     const COM::Connectivity *conn = pn->connectivity( aname);
     if ( conn==NULL) return -1;
     else return conn->status();
   }
   else {
     // Get the corresponding dataitem object.
     const COM::DataItem *attr = pn->dataitem( aname);
     if ( attr==NULL) return -1;
     else return attr->status();
   }
 }
DataItem * ComponentInterface::inherit (DataItem * from, const std::string & aname, int inherit_mode, bool withghost, const DataItem * cond, int val) throw (COM_exception)
Returns the corresponding value.
Parameters
from dataitem being copied from
aname new name of the dataitem
cond an integer pane-dataitem
val value to be compared against cond
inherit_mode mode of inheritance
withghost wheather ghost nodes/elements should be ignored
Definition at line 308 of file ComponentInterface.C.
References _pane_map, append_frame, COM_ALL, COM_CONN, COM_ERR_INCOMPATIBLE_DATAITEMS, COM_MESH, COM_PMESH, Pane::dataitem(), Pane::id(), DataItem::inherit(), Pane::inherit(), Pane::INHERIT_COPY, DataItem::pointer(), and DataItem::window().
Referenced by copy_dataitem(), Rocin::obtain_dataitem(), and Rocout::write_dataitem_internal().
 {
   DataItem *a = ((Pane_friend&)_dummy).inherit(from, aname, mode, withghost);
   if ( from->is_windowed()) return a;
   // Copy the panes
   Pane_map &ps = from->window()->_pane_map;
   bool with_conn = from->id()==COM_CONN || from->id()==COM_MESH ||
     from->id()==COM_PMESH || from->id()==COM_ALL;
   bool insert_pane = (mode != Pane::INHERIT_COPY) && with_conn;
   if ( with_conn && aname.size() && from->name() != aname)
     throw COM_exception( COM_ERR_INCOMPATIBLE_DATAITEMS, append_frame
                          (from->fullname()+" and " +aname,
                           ComponentInterface::inherit));
   if ( cond && cond->window()!=from->window()) {
     throw COM_exception( COM_ERR_INCOMPATIBLE_DATAITEMS, append_frame
                          (from->fullname()+" and "+cond->fullname(),
                           ComponentInterface::inherit));
   }
   for ( Pane_map::iterator ppit = ps.begin(); ppit!=ps.end(); ++ppit) {
     Pane *ppn=ppit->second;
     const int *cnd = NULL;
     if ( cond) {
       const DataItem *cond_pn = ppn->dataitem( cond->id());
       cnd = (const int*)cond_pn->pointer();
     }
     // Inherit the pane if the condition was set to an variable (cnd!=NULL),
     // or set to to pane ID (cnd==NULL && val!=0), or not set.
     if ( !cond && (val==0 || val==ppn->id()) || cnd && *cnd == val) {
       // Create new panes only when we are inheriting the mesh.
       Pane_friend *pn;
       if ( insert_pane)
         pn = (Pane_friend*)( &pane( ppit->first, true));
       else {
         Pane_map::iterator it = _pane_map.find( ppit->first);
         pn = ( it!=_pane_map.end())?(Pane_friend*)(it->second):NULL;
       }
       if ( pn)
         pn->inherit( ppn->dataitem( from->id()), aname, mode, withghost);
     }
   }
   return a;
 }
void ComponentInterface::init_done (bool pane_changed = true) throw (COM_exception)
Definition at line 362 of file ComponentInterface.C.
References append_frame, COM_ERR_INIT_DONE_PANEMAP, and max().
{
   // Loop through the dataitems.
   if ( _status == STATUS_SHRUNK) {
     int max_id=0;
     for (Attr_map::iterator it=_attr_map.begin(); it!=_attr_map.end(); ++it) {
       int id = it->second->id(), ncomp=it->second->size_of_components();
       max_id = std::max( max_id, id+ncomp+(ncomp>1));
     }
     if (max_id < _last_id) _last_id = max_id;
   }
   int npanes = _pane_map.size();
   std::vector< int> pane_ids; pane_ids.reserve(npanes);
   for (Pane_map::iterator it=_pane_map.begin(); it!=_pane_map.end(); ++it) {
     it->second->init_done();
     pane_ids.push_back( it->second->id());
   }
   _status = STATUS_NOCHANGE;
   if ( !pane_changed) {
     if ( npanes>int(_pane_map.size())) {
       throw COM_exception( COM_ERR_INIT_DONE_PANEMAP, append_frame
                            (_name,ComponentInterface::init_done));
     }
     return;
   }
   // communicate pane mapping
   int flag; MPI_Initialized( &flag);
   if ( _comm == MPI_COMM_NULL) flag = 0;
   // Compute proc_map
   int nprocs;
   if ( flag) MPI_Comm_size( _comm, &nprocs); else nprocs = 1;
   // Obtain the number of panes.
   std::vector<int> npanes_all(nprocs);
   if ( flag)
     MPI_Allgather( &npanes, 1, MPI_INT, &npanes_all[0], 1, MPI_INT, _comm);
   else
     npanes_all[0] = npanes;
   std::vector<int> disps(nprocs+1);
   disps[0]=0;
   for ( int i=0; i<nprocs; ++i) disps[i+1] = disps[i]+npanes_all[i];
   std::vector<int> pane_ids_all( disps[nprocs]);
   if ( flag)
     MPI_Allgatherv( &pane_ids[0], npanes, MPI_INT, &pane_ids_all[0],
                     &npanes_all[0], &disps[0], MPI_INT, _comm);
   else
     pane_ids_all = pane_ids;
   // Build process map
   _proc_map.clear();
   for ( int p=0; p<nprocs; ++p) {
     for ( int j=disps[p], jn=disps[p+1]; j<jn; ++j)
       _proc_map[ pane_ids_all[j]] = p;
   }
 }
int ComponentInterface::last_dataitem_id () const inline
Definition at line 268 of file ComponentInterface.hpp.
References _last_id.
Referenced by Pane::init_done().
 { return _last_id; }
const std::string& ComponentInterface::name () const inline
Definition at line 69 of file ComponentInterface.hpp.
Referenced by Rocblas::axpy_gen(), Rocblas::calc(), Rocblas::calcDot(), COM::COM_base::call_function(), comftestmod_load_module(), comftestmod_unload_module(), Rocblas::copy(), DataItem::fullname(), Rocblas::gen2arg(), Rocblas::rand(), Pane::refresh_connectivity(), Rocblas::swap(), testfortranmodule_load_module(), testfortranmodule_unload_module(), testroutine1(), testroutine2(), testroutine3(), and Rocout::write_dataitem_internal().
 { return _name; }
DataItem * ComponentInterface::new_dataitem (const std::string & aname, const char loc, const int type, int ncomp, const std::string & unit) throw (COM_exception)
Parameters
aname dataitem name.
loc location ('w', 'p', 'n', or 'e').
type base data type.
ncomp number of components.
unit unit of the dataitem.
Definition at line 60 of file ComponentInterface.C.
References append_frame, COM_assertion_msg, COM_ERR_INVALID_DATAITEM_NAME, COM_ERR_INVALID_DIMENSION, COM_ERR_UNKNOWN_DATATYPE, COM_ERR_UNKNOWN_KEYWORD, COM_MAX_TYPEID, COM_NUM_KEYWORDS, DataItem::is_digit(), Connectivity::is_element_name(), and Pane::new_dataitem().
 {
   // Special handing for connectivity
   if ( Connectivity::is_element_name( aname) ||
        DataItem::is_digit(aname[0]))
     throw COM_exception( COM_ERR_INVALID_DATAITEM_NAME,append_frame
                          (_name+"."+aname,ComponentInterface::new_dataitem));
   if ( ncomp<=0)
     throw COM_exception( COM_ERR_INVALID_DIMENSION,append_frame
                          (_name+"."+aname,ComponentInterface::new_dataitem));
   if ( loc != 'w' && loc != 'p' && loc != 'e' && loc != 'n' && loc != 'c')
     throw COM_exception( COM_ERR_UNKNOWN_KEYWORD,append_frame
                          (_name+"."+aname,ComponentInterface::new_dataitem));
   if ( type<COM_MIN_TYPEID || type > COM_MAX_TYPEID)
     throw COM_exception( COM_ERR_UNKNOWN_DATATYPE,append_frame
                          (_name+"."+aname,ComponentInterface::new_dataitem));
   // Redefine an dataitem if it pre-exists, but ncomp cannot be increased.
   Attr_map::const_iterator it = _attr_map.find( aname);
   if ( it != _attr_map.end() && ncomp > it->second->size_of_components()) {
     COM_assertion_msg( it->second->id()>=COM_NUM_KEYWORDS,
                        "Cannot increase size of keywords");
     delete_dataitem( it->first);
     it = _attr_map.end();
   }
   int id = (it==_attr_map.end())?_last_id:it->second->id();
   // Insert the object into both the set and the map.
   DataItem *a = ((Pane_friend&)_dummy).
     new_dataitem( aname, id, loc, type, ncomp, unit);
   _attr_map[aname] = a;
   // Propagete onto all existing panes.
   for (Pane_map::iterator it=_pane_map.begin(); it!=_pane_map.end(); ++it) {
     Pane_friend *pn = (Pane_friend*)it->second;
     pn->new_dataitem( aname, id, loc, type, ncomp, unit);
   }
   // Update last available id
   if ( it == _attr_map.end()) _last_id = id+ncomp+(ncomp>1);
   if ( _status == STATUS_NOCHANGE) _status = STATUS_CHANGED;
   return a;
 }
ComponentInterface& ComponentInterface::operator= (const ComponentInterface &) private
int ComponentInterface::owner_rank (const int pane_id) const
Returns -1 if the pane cannot be found in the process map.
Definition at line 426 of file ComponentInterface.C.
References _pane_map, _proc_map, and COM_assertion_msg.
{
   COM_assertion_msg( _pane_map.size()<=_proc_map.size(),
                      "init_done must be called before owner_rank is called");
   Proc_map::const_iterator it = _proc_map.find( pane_id);
   if ( it==_proc_map.end()) return -1;
   else return it->second;
 }
Pane & ComponentInterface::pane (const int pane_id, bool insert = false) throw (COM_exception)
Definition at line 743 of file ComponentInterface.C.
References append_frame, COM_assertion, and COM_ERR_PANE_NOTEXIST.
Referenced by pane(), RFC_Pane_base::read_rocin(), Pane_connectivity::size_of_cpanes(), write_attr_CGNS(), and write_dataitem_HDF4().
 {
   if ( pid==0) return _dummy;
   COM_assertion( pid>0);
   Pane_map::iterator pit = _pane_map.find( pid);
   if ( pit == _pane_map.end()) {
     if (insert)
       return *(_pane_map[pid] = new Pane( &_dummy, pid));
     else {
         // print missing pane ID and known IDs in the pane map
       std::cerr << "No such Pane ID: " << pid << std::endl;
       std::cerr << "While the known Pane IDs are: [ ";
       Pane_map::iterator pit;
       for ( pit=_pane_map.begin(); pit != _pane_map.end(); ++pit)
         std::cerr << pit->first << " ";
       std::cerr << "]" << std::endl;
       throw COM_exception( COM_ERR_PANE_NOTEXIST, append_frame
                            (_name,ComponentInterface::pane));
     }
   }
   return *pit->second;
 }
const Pane & ComponentInterface::pane (const int pane_id) const throw (COM_exception)
Definition at line 768 of file ComponentInterface.C.
References append_frame, COM_assertion, COM_ERR_PANE_NOTEXIST, and pane().
 {
   if ( pid==0) return _dummy;
   COM_assertion( pid>0);
   Pane_map::const_iterator pit = _pane_map.find( pid);
   if ( pit == _pane_map.end()) {
     throw COM_exception( COM_ERR_PANE_NOTEXIST, append_frame
                          (_name,ComponentInterface::pane));
   }
   return *pit->second;
 }
void ComponentInterface::panes (std::vector< int > & ps, int rank = -2)
Definition at line 783 of file ComponentInterface.C.
References _pane_map, _proc_map, _status, COM_assertion_msg, and STATUS_NOCHANGE.
Referenced by Rocblas::axpy_gen(), Rocblas::calc(), Rocblas::calcDot(), Rocblas::gen2arg(), panes(), and Pane_connectivity::pconn_nblocks().
 {
   pane_ids.clear();
   if ( rank == -2) {
     pane_ids.reserve( _pane_map.size());
     for ( Pane_map::iterator it=_pane_map.begin(); it != _pane_map.end(); ++it)
       pane_ids.push_back( it->first);
   }
   else {
     COM_assertion_msg( _status == STATUS_NOCHANGE,
                        "Can only obtain panes after calling window_init_done");
     std::map<int,int>::const_iterator it, iend;
     for ( it=_proc_map.begin(), iend=_proc_map.end(); it!= iend; ++it) {
       if ( rank==-1 || it->second == rank)
         pane_ids.push_back( it->first);
     }
   }
 }
void ComponentInterface::panes (std::vector< Pane * > & ps)
Definition at line 807 of file ComponentInterface.C.
References _pane_map.
 {
   ps.reserve( _pane_map.size());
   Pane_map::iterator it=_pane_map.begin();
   for ( ; it != _pane_map.end(); ++it)
     ps.push_back( it->second);
 }
void ComponentInterface::panes (std::vector< const Pane * > & ps) const inline
Definition at line 301 of file ComponentInterface.hpp.
References panes().
   { const_cast<ComponentInterface*>(this)->panes( (std::vector<Pane*> &)ps); }
const Proc_map& ComponentInterface::proc_map () const inline
Definition at line 271 of file ComponentInterface.hpp.
References _proc_map.
 { return _proc_map; }
void ComponentInterface::reinit_conn (Connectivity * con, OP_Init op, int ** addr = NULL, int strd = 0, int cap = 0) throw (COM_exception) protected
Parameters
attr connectivity table
op Operation (OP_SET, OP_SET_CONST, OP_ALLOC, OP_RESIZE)
addr address
strd stride
cap capacity
Definition at line 721 of file ComponentInterface.C.
References addr, cap, COM_assertion, Pane::id(), Pane::OP_SET, Pane::OP_SET_CONST, Connectivity::parent(), and strd.
Referenced by dealloc_array(), and resize_array().
 {
   Pane *pn = con->pane();
   if ( pn->id()==0) {
     COM_assertion( op != Pane::OP_SET && op != Pane::OP_SET_CONST);
     // Loop through the panes to proecess the connectivity in each pane.
     for (Pane_map::iterator it=_pane_map.begin(), iend=_pane_map.end();
          it != iend; ++it) {
       Connectivity *c=((Pane_friend*)it->second)->connectivity( con->name());
       if ( c && !c->parent())
         ((Pane_friend*)it->second)->reinit_conn( c, op, NULL, strd, cap);
     }
     if ( addr) *addr= NULL; // Do not return address.
     return;
   }
   else {
     ((Pane_friend*)pn)->reinit_conn( con, op, addr, strd, cap);
   }
 }
void ComponentInterface::reinit_dataitem (DataItem * attr, OP_Init op, void ** addr = NULL, int strd = 0, int cap = 0) throw (COM_exception) protected
Parameters
attr dataitem
op Operation (OP_SET, OP_SET_CONST, OP_ALLOC, OP_RESIZE)
addr address
strd stride
cap capacity
Definition at line 691 of file ComponentInterface.C.
References addr, cap, COM_ALL, COM_assertion, COM_DATA, Pane::id(), Pane::OP_SET, Pane::OP_SET_CONST, Pane::reinit_dataitem(), and strd.
Referenced by dealloc_array(), and resize_array().
 {
   int aid = a->id();
   if ( a->location()=='w')
     // Initialize CI window dataitems in dummy pane
     ((Pane_friend&)_dummy).reinit_dataitem( aid, op, addr, strd, cap);
   else {
     // Initialize other dataitems in regular panes
     Pane *pn = a->pane();
     if ( pn->id()>0)
       ((Pane_friend*)pn)->reinit_dataitem( aid, op, addr, strd, cap);
     else {
       if ( aid == COM_ALL || aid == COM_DATA)
         ((Pane_friend&)_dummy).reinit_dataitem( aid, op, addr, strd, cap);
       COM_assertion( op != Pane::OP_SET && op != Pane::OP_SET_CONST );
       // Loop through the panes to initialize each pane
       for (Pane_map::iterator it=_pane_map.begin(), iend=_pane_map.end();
            it != iend; ++it) {
         ((Pane_friend*)it->second)->reinit_dataitem( aid, op, NULL, strd, cap);
       }
       if ( addr) *addr= NULL; // Do not return any address.
       return;
     }
   }
 }
void ComponentInterface::resize_array (const std::string & aname, const int pane_id, void ** addr, int strd = -1, int cap = 0) throw (COM_exception)
set_array, alloc_array, append_array
Definition at line 235 of file ComponentInterface.C.
References addr, append_frame, cap, COM_ERR_DATAITEM_NOTEXIST, Connectivity::is_element_name(), Pane::OP_RESIZE, pane_id, and strd.
 {
   if ( Connectivity::is_element_name( aname)) {
     Pane &pn = pane(pane_id,true);
     Connectivity *con = ((Pane_friend&)pn).connectivity( aname);
     if ( con==NULL)
       throw COM_exception( COM_ERR_DATAITEM_NOTEXIST, append_frame
                            (name()+"."+aname,ComponentInterface::resize_array));
     reinit_conn( con, Pane::OP_RESIZE, (int**)addr, strd, cap);
   }
   else {
     DataItem *a = pane( pane_id,true).dataitem( aname);
     if ( a==NULL)
       throw COM_exception( COM_ERR_DATAITEM_NOTEXIST, append_frame
                            (name()+"."+aname,ComponentInterface::resize_array));
     reinit_dataitem( a, Pane::OP_RESIZE, addr, strd, cap);
   }
 }
void ComponentInterface::resize_array (DataItem * a, void ** addr, int strd = -1, int cap = 0) throw (COM_exception) inline
Definition at line 143 of file ComponentInterface.hpp.
References Pane::OP_RESIZE, and reinit_dataitem().
   { reinit_dataitem( a, Pane::OP_RESIZE, addr, strd, cap); }
void ComponentInterface::resize_array (Connectivity * c, void ** addr, int strd = -1, int cap = 0) throw (COM_exception) inline
Definition at line 147 of file ComponentInterface.hpp.
References cap, Pane::OP_RESIZE, reinit_conn(), and strd.
   { reinit_conn( c, Pane::OP_RESIZE, (int**)addr, strd, cap); }
void ComponentInterface::set_array (const std::string & aname, const int pane_id, void * addr, int strd = 0, int cap = 0, bool is_const = false) throw (COM_exception)
Parameters
aname dataitem name
pane_id pane ID
addr address of the array
strd Stride between two items of each component
cap capacity of the array alloc_array, resize_array
Definition at line 186 of file ComponentInterface.C.
References addr, append_frame, cap, COM_ERR_DATAITEM_NOTEXIST, Connectivity::is_element_name(), Pane::OP_SET, Pane::OP_SET_CONST, pane_id, and strd.
 {
   if ( Connectivity::is_element_name( aname)) {
     Pane &pn = pane(pane_id,true);
     Connectivity *con = ((Pane_friend&)pn).connectivity( aname,true);
     if ( con==NULL)
       throw COM_exception( COM_ERR_DATAITEM_NOTEXIST, append_frame
                            (name()+"."+aname,ComponentInterface::set_array));
     reinit_conn( con, is_const?Pane::OP_SET_CONST:Pane::OP_SET,
                  &(int*&)addr, strd, cap);
   }
   else {
     DataItem *a = pane( pane_id,true).dataitem( aname);
     if ( a==NULL)
       throw COM_exception( COM_ERR_DATAITEM_NOTEXIST, append_frame
                            (name()+"."+aname,ComponentInterface::set_array));
     reinit_dataitem( a, is_const?Pane::OP_SET_CONST:Pane::OP_SET,
                      &addr, strd, cap);
   }
 }
void ComponentInterface::set_function (const std::string & fname, Func_ptr func, const std::string & intents, const COM_Type * types, DataItem * a, bool if_f90 = false) throw (COM_exception)
Definition at line 33 of file ComponentInterface.C.
References append_frame, and COM_WARN_DUP_FUNC.
{
   if ( _func_map.find( fname) != _func_map.end())
     throw COM_exception(COM_WARN_DUP_FUNC, append_frame
                         (_name+"."+fname,ComponentInterface::init_function));
   _func_map[fname] = Function( func, intents, types, a, is_f90);
 }
void ComponentInterface::set_function (const std::string & fname, Member_func_ptr func, const std::string & intents, const COM_Type * types, DataItem * a, bool if_f90 = false) throw (COM_exception)
Definition at line 46 of file ComponentInterface.C.
References _func_map, _name, append_frame, and COM_WARN_DUP_FUNC.
{
   if ( _func_map.find( fname) != _func_map.end())
     throw COM_exception(COM_WARN_DUP_FUNC, append_frame
                         (_name+"."+fname,ComponentInterface::init_function));
   _func_map[fname] = Function( func, intents, types, a);
 }
void ComponentInterface::set_size (const std::string & aname, int pane_id, int nitems, int ng = 0) throw (COM_exception)
Parameters
aname dataitem name
pane_id pane ID
nitems total number of items (including ghosts)
ng number of ghosts
Definition at line 156 of file ComponentInterface.C.
References append_frame, COM_ERR_DATAITEM_NOTEXIST, Pane::connectivity(), DataItem::id(), Connectivity::is_element_name(), DataItem::is_windowed(), and Pane::set_size().
 {
   if ( Connectivity::is_element_name( aname)) {
     Pane_friend &pn = (Pane_friend&)pane(pid,true);
     Connectivity *con = pn.connectivity( aname,true);
     pn.set_size( con, nitems, ng);
   }
   else {
     DataItem *a = dataitem(aname);
     if ( a == NULL)
       throw COM_exception( COM_ERR_DATAITEM_NOTEXIST,append_frame
                            (_name+"."+aname,ComponentInterface::set_size));
     if ( a->is_windowed())
       ((Pane_friend&)_dummy).set_size( a, nitems, ng);
     else if ( pid==0) {
       // Loop through the panes to set the sizes.
       for (Pane_map::iterator it=_pane_map.begin(), iend=_pane_map.end();
            it != iend; ++it) {
         ((Pane_friend*)it->second)->set_size
           ( it->second->dataitem( a->id()), nitems, ng);
       }
     }
     else
       ((Pane_friend&)pane(pid,true)).set_size( a, nitems, ng);
   }
 }
int ComponentInterface::size_of_panes () const inline
Definition at line 258 of file ComponentInterface.hpp.
 { return _pane_map.size(); }
int ComponentInterface::size_of_panes_global () const inline
Definition at line 261 of file ComponentInterface.hpp.
References _proc_map.
 { return _proc_map.size(); }
Member Data Documentation
Attr_map ComponentInterface::_attr_map protected
It does not contain individual components.
Definition at line 356 of file ComponentInterface.hpp.
Referenced by ComponentInterface().
MPI_Comm ComponentInterface::_comm protected
Definition at line 364 of file ComponentInterface.hpp.
Referenced by get_communicator().
Pane ComponentInterface::_dummy protected
Definition at line 354 of file ComponentInterface.hpp.
Referenced by ComponentInterface(), dataitem(), and dataitems().
Func_map ComponentInterface::_func_map protected
Definition at line 358 of file ComponentInterface.hpp.
Referenced by function(), and set_function().
int ComponentInterface::_last_id protected
The next available one is _last_id+1.
Definition at line 362 of file ComponentInterface.hpp.
Referenced by last_dataitem_id().
std::string ComponentInterface::_name protected
Definition at line 355 of file ComponentInterface.hpp.
Referenced by set_function().
Pane_map ComponentInterface::_pane_map protected
Definition at line 359 of file ComponentInterface.hpp.
Referenced by delete_pane(), inherit(), owner_rank(), panes(), and ~ComponentInterface().
Proc_map ComponentInterface::_proc_map protected
Definition at line 360 of file ComponentInterface.hpp.
Referenced by owner_rank(), panes(), proc_map(), and size_of_panes_global().
int ComponentInterface::_status protected
Definition at line 366 of file ComponentInterface.hpp.
Referenced by panes().
The documentation for this class was generated from the following files:
ComponentInterface.hpp
ComponentInterface.C