IMPACT: IRAD::Primitive::KeyValuePairObj< K, V > Class Template Reference
IRAD::Primitive::KeyValuePairObj< K, V > Class Template Reference
Simple key-value pair.
Detailed Description
template<typename K, typename V>
class IRAD::Primitive::KeyValuePairObj< K, V >
Definition at line 194 of file PrimitiveTypes.H.
#include <PrimitiveTypes.H>
Public Member Functions
KeyValuePairObj (const std::pair< K, V > &p)
KeyValuePairObj (const K &k, const V &v)
KeyValuePairObj ()
K Key () const
V Value () const
K & Key ()
V & Value ()
K & Key (const K &k)
V & Value (const V &v)
Constructor & Destructor Documentation
template<typename K , typename V > IRAD::Primitive::KeyValuePairObj< K, V >::KeyValuePairObj (const std::pair< K, V > & p) inline
Definition at line 197 of file PrimitiveTypes.H.
{
         this->first = p.first;
         this->second = p.second;
       };
template<typename K , typename V > IRAD::Primitive::KeyValuePairObj< K, V >::KeyValuePairObj (const K & k, const V & v) inline
Definition at line 201 of file PrimitiveTypes.H.
{
         this->first = k;
         this->second = v;
       };
template<typename K , typename V > IRAD::Primitive::KeyValuePairObj< K, V >::KeyValuePairObj () inline
Definition at line 205 of file PrimitiveTypes.H.
 {};
Member Function Documentation
template<typename K , typename V > K IRAD::Primitive::KeyValuePairObj< K, V >::Key () const inline
Definition at line 206 of file PrimitiveTypes.H.
Referenced by IRAD::Util::TestResults::AddResult(), IRAD::Util::operator<<(), and IRAD::Util::Parameters::ReadFromStream().
 { return this->first; };
template<typename K , typename V > K& IRAD::Primitive::KeyValuePairObj< K, V >::Key () inline
Definition at line 208 of file PrimitiveTypes.H.
 { return this->first; };
template<typename K , typename V > K& IRAD::Primitive::KeyValuePairObj< K, V >::Key (const K & k) inline
Definition at line 210 of file PrimitiveTypes.H.
 { this->first = k; return(this->first); };
template<typename K , typename V > V IRAD::Primitive::KeyValuePairObj< K, V >::Value () const inline
Definition at line 207 of file PrimitiveTypes.H.
Referenced by IRAD::Util::TestResults::AddResult(), IRAD::Util::operator<<(), IRAD::Util::Parameters::ReadFromStream(), and IRAD::Util::Parameters::SetValue().
 { return this->second; };
template<typename K , typename V > V& IRAD::Primitive::KeyValuePairObj< K, V >::Value () inline
Definition at line 209 of file PrimitiveTypes.H.
 { return this->second; };
template<typename K , typename V > V& IRAD::Primitive::KeyValuePairObj< K, V >::Value (const V & v) inline
Definition at line 211 of file PrimitiveTypes.H.
 { this->second = v; return(this->second); };
The documentation for this class was generated from the following file:
PrimitiveTypes.H