IMPACT: Agent Class Reference
Agent Class Reference abstract
Detailed Description
Definition at line 141 of file Agent.h.
#include <Agent.h>
Public Member Functions
Agent (Coupling *cp, std::string mod, std::string obj, const char *agent_name, MPI_Comm com, bool wgm=false, bool skipio=false)
virtual ~Agent ()
virtual void load_module ()
virtual void unload_module ()
virtual void init_module (double t, double dt)
void init_subscheduler (double t)
void callMethod (Scheduler_voidfn1_t fn, double t)
void schedule ()
virtual void finalize ()
virtual void input (double t)=0
virtual void output_restart_files (double t)=0
virtual void output_visualization_files (double t)=0
double max_timestep (double t, double dt)
Action * get_main_action ()
void register_new_dataitem (std::string target_window_, std::string attr_, char loc_, int type_, int ncomp_, const char *unit_)
void register_clone_dataitem (int cond, std::string target_window_, std::string attr_, std::string parent_window_, std::string parent_attr_, int wg_=1, const char *ptnname_=0, int val_=0)
void register_use_dataitem (std::string target_window_, std::string attr_, std::string parent_window_, std::string parent_attr_, int wg_=1, const char *ptnname_=0, int val_=0)
void create_registered_dataitems (std::string tmpBuf)
void create_registered_window_dataitems (std::string target_window)
virtual void create_buffer_all ()
void assign_dataitems ()
virtual void read_restart_data ()
void add_data ()
void add_icaction (Action *act)
void add_bcaction (Action *act, int l=1)
void add_bcinitaction (Action *act)
void add_gmaction (Action *act)
void init_callback (const char *surf_win, const char *vol_win, void *option=NULL)
void init_bcactions (double t)
void obtain_bc (double *a, int *l=NULL)
void init_gmactions (double t)
void obtain_gm (double *da)
void init_bcinitaction (double t)
void run_bcinitaction (double t, double dt)
Coupling * get_coupling ()
void register_interpolate (InterpolateBase *ip)
std::string get_surface_window () const
std::string get_volume_window () const
MPI_Comm get_communicator () const
std::string get_rocmod_name () const
std::string get_modinstance_name () const
std::string get_agent_name () const
int get_comm_rank () const
double get_old_dt () const
virtual void init_convergence (int iPredCorr)
virtual int check_convergence (double tolerMass, double tolerTract, double tolerVelo)
virtual int compute_integrals ()
double * get_integrals ()
void print (FILE *f)
void get_time_string (double t, std::string &s)
Protected Types
typedef vector< InterpolateBase * > InterpolateList
typedef vector< DataItemBase * > DataItemList
Protected Member Functions
Scheduler * get_bcScheduler (unsigned int level)
void init_function_handles ()
void create_window (const char *window_name)
void split_surface_window (const std::string surfAll, const std::string surf_i, const std::string surf_nb, const std::string surf_b, const std::string surf_ni)
int read_by_control_file (double t, const std::string base, const std::string window)
void write_data_files (double t, const std::string base, const std::string attr, const char *ref=NULL)
void write_control_file (double t, const std::string base, const std::string window)
virtual void store_solutions (int converged)
int check_convergence_help (int vcur, int vpre, double tol, std::string str)
Protected Attributes
const std::string agent_name
MPI_Comm communicator
Coupling * coupling
PhysicsAction action
SchdulerList bcScheduler
UserScheduler bcInitScheduler
UserScheduler gmScheduler
UserScheduler icScheduler
int comm_rank
int init_handle
int update_handle
int pre_hdf_handle
int post_hdf_handle
int finalize_handle
int compute_integrals_handle
int ic_handle
int bc_handle
int gm_handle
bool withgm
int dobackup
string rocmod_name
string mod_instance
string inDir
string outDir
string suffix
double initial_time
double timestamp
double current_time
double current_deltatime
double old_dt
std::string surf_window
std::string vol_window
std::string tmp_window
void * option_data
InterpolateList interpolateList
DataItemList dataitemList
int pc_hdls [2][3]
int pc_count
double integrals [MAN_INTEG_SIZE]
bool skipInputIO
Static Protected Attributes
static int read_by_control_handle =0
static int read_files_handle =0
static int obtain_attr_handle =0
static int write_attr_handle =0
static int write_ctrl_handle =0
Friends
class PhysicsAction
Member Typedef Documentation
typedef vector< DataItemBase* > Agent::DataItemList protected
Definition at line 186 of file Agent.h.
typedef vector< InterpolateBase* > Agent::InterpolateList protected
Definition at line 183 of file Agent.h.
Constructor & Destructor Documentation
Agent::Agent (Coupling * cp, std::string mod, std::string obj, const char * agent_name, MPI_Comm com, bool wgm = false, bool skipio = false)
Definition at line 185 of file Agent.C.
References action, agent_name, bcInitScheduler, comm_rank, create_window(), Control_parameters::current_time, dobackup, get_agent_name(), Coupling::get_control_param(), gmScheduler, inDir, MAN_DEBUG, old_dt, outDir, Scheduler::set_name(), Action::set_name(), suffix, and timestamp.
   : agent_name(agentname), communicator(com), coupling(cp), action(this),
     withgm(wgm), rocmod_name( mod), mod_instance(obj), skipInputIO(skipio)
 {
   MPI_Comm_rank( com, &comm_rank);
   MAN_DEBUG(1, ("Rocman: Agent::Agent create window %s.\n", get_agent_name().c_str()));
   create_window(agent_name.c_str());
   inDir = obj;  inDir.append("/SimIN/");
   outDir = obj; outDir.append("/SimOUT/");
   suffix = ".hdf";
     // set proper names for visu
   std::string physicsname = agentname;
   physicsname = physicsname+"-PhysicsAction";
   action.set_name(physicsname.c_str());
   bcInitScheduler.set_name("bcInitSched");
   gmScheduler.set_name("gmSched");
   timestamp = cp->get_control_param()->current_time;;
   old_dt = 0.0;
   dobackup = 1;
 }
Agent::~Agent () virtual
Definition at line 212 of file Agent.C.
 {
 }
Member Function Documentation
void Agent::add_bcaction (Action * act, int l = 1)
Definition at line 376 of file Agent.C.
References UserScheduler::add_action(), bcScheduler, COM_assertion_msg, and Scheduler::set_name().
Referenced by declare_fluid_actions(), declare_solid_actions(), and FluidBurnAlone::FluidBurnAlone().
 {
   int cur =  bcScheduler.size();
   COM_assertion_msg(l>=1 && l <= cur+1, "ERROR: add_bcaction.\n");
   UserScheduler *sched;
   if (cur == l-1) {
     sched = new UserScheduler;
     char str[128];
     sprintf(str, "%s%d", "bcSched", l);
     sched->set_name(str);
     bcScheduler.push_back(sched);
   }
   else
     sched = bcScheduler[l-1];
   COM_assertion_msg(sched, "ERROR: add_bcaction with no scheduler.\n");
   sched->add_action(act);
 }
void Agent::add_bcinitaction (Action * act)
Definition at line 370 of file Agent.C.
References UserScheduler::add_action(), and bcInitScheduler.
Referenced by declare_solid_actions(), and FluidBurnAlone::FluidBurnAlone().
 {
   bcInitScheduler.add_action(act);
 }
void Agent::add_data () inline
Definition at line 226 of file Agent.h.
 { /* TODO */ }
void Agent::add_gmaction (Action * act)
Definition at line 394 of file Agent.C.
References UserScheduler::add_action(), and gmScheduler.
Referenced by declare_fluid_actions(), and FluidBurnAlone::FluidBurnAlone().
 {
   gmScheduler.add_action(act);
 }
void Agent::add_icaction (Action * act)
Definition at line 364 of file Agent.C.
References UserScheduler::add_action(), and icScheduler.
Referenced by declare_fluid_actions(), declare_solid_actions(), and FluidBurnAlone::FluidBurnAlone().
 {
   icScheduler.add_action(act);
 }
void Agent::assign_dataitems ()
Definition at line 356 of file Agent.C.
References dataitemList, and tmp_window.
 {
   unsigned int n = dataitemList.size();
   for (unsigned int i=0; i<n; i++) {
     dataitemList[i]->assign(tmp_window);
   }
 }
void Agent::callMethod (Scheduler_voidfn1_t fn, double t)
Definition at line 417 of file Agent.C.
References bcInitScheduler, bcScheduler, and gmScheduler.
Referenced by init_subscheduler().
 {
   unsigned int i;
   (bcInitScheduler.*fn)( t);
   for (i=0; i<bcScheduler.size(); i++)  {
         (bcScheduler[i]->*fn)( t);
   }
   (gmScheduler.*fn)( t);
 }
virtual int Agent::check_convergence (double tolerMass, double tolerTract, double tolerVelo) inline virtual
Reimplemented in FluidAgent.
Definition at line 260 of file Agent.h.
 { return 1; }
int Agent::check_convergence_help (int vcur, int vpre, double tol, std::string str) protected
Definition at line 726 of file Agent.C.
References COM_call_function(), comm_rank, communicator, RocBlas::nrm2_scalar_MPI, and RocBlas::sub.
Referenced by FluidAgent::check_convergence().
 {
   double nrm_val=0.0, nrm_diff=0.0, ratio;
   COM_call_function( RocBlas::sub,  &vcur, &vpre, &vpre);
   COM_call_function( RocBlas::nrm2_scalar_MPI, &vcur, &nrm_val, &communicator);
   COM_call_function( RocBlas::nrm2_scalar_MPI, &vpre, &nrm_diff, &communicator);
   if (nrm_val != 0.)
        ratio = nrm_diff/nrm_val;
   else
        ratio = nrm_diff;
   int result = (ratio <= tol);
   if ( comm_rank == 0)
          std::cout << " Convergence ratio of " << str << " is " << ratio << std::endl;
   return result;
 }
virtual int Agent::compute_integrals () inline virtual
Reimplemented in SolidAgent, and FluidAgent.
Definition at line 262 of file Agent.h.
 { return 0; }
void Agent::create_buffer_all () virtual
Reimplemented in SolidAgent, BurnAgent, and FluidAgent.
Definition at line 344 of file Agent.C.
References COM_new_window(), COM_use_dataitem(), COM_window_init_done(), create_registered_window_dataitems(), get_agent_name(), MAN_DEBUG, surf_window, and tmp_window.
Referenced by BurnAgent::create_buffer_all(), FluidAgent::create_buffer_all(), SolidAgent::create_buffer_all(), and init_callback().
 {
   MAN_DEBUG(1, ("Rocman: Agent %s::create_buffer_all called %s.\n", get_agent_name().c_str(), tmp_window.c_str()));
   COM_new_window( tmp_window);
 //  COM_use_dataitem( tmp_window, surf_window+".all", 1);
   COM_use_dataitem( tmp_window, surf_window+".mesh", 1);
   COM_use_dataitem( tmp_window, surf_window+".data", 1);
   //create_registered_dataitems(tmp_window);
   create_registered_window_dataitems( tmp_window);
   COM_window_init_done( tmp_window);
 }
void Agent::create_registered_dataitems (std::string tmpBuf)
Definition at line 323 of file Agent.C.
References COM_window_init_done(), comm_rank, dataitemList, and MAN_DEBUG.
 {
   unsigned int n = dataitemList.size();
   for (unsigned int i=0; i<n; i++) {
     MAN_DEBUG(2, ("[%d] creating %s %s\n", comm_rank, dataitemList[i]->target_window.c_str(), dataitemList[i]->attr.c_str()));
     dataitemList[i]->create(dataitemList[i]->target_window);
   }
   COM_window_init_done( tmpBuf);
 }
void Agent::create_registered_window_dataitems (std::string target_window)
Definition at line 333 of file Agent.C.
References comm_rank, dataitemList, and MAN_DEBUG.
Referenced by BurnAgent::create_buffer_all(), FluidAgent::create_buffer_all(), SolidAgent::create_buffer_all(), and create_buffer_all().
 {
   unsigned int n = dataitemList.size();
   for (unsigned int i=0; i<n; i++) {
     if (dataitemList[i]->target_window == target_window) {
       MAN_DEBUG(2, ("[%d] creating %s %s\n", comm_rank, dataitemList[i]->target_window.c_str(), dataitemList[i]->attr.c_str()));
       dataitemList[i]->create(dataitemList[i]->target_window);
     }
   }
 }
void Agent::create_window (const char * window_name) protected
Definition at line 264 of file Agent.C.
References bc_handle, COM_DOUBLE, COM_get_function_handle(), COM_INT, COM_new_dataitem(), COM_new_window(), COM_RAWDATA, COM_set_member_function(), COM_set_object(), COM_STRING, COM_VOID, COM_window_init_done(), gm_handle, ic_handle, init_callback(), obtain_bc(), and obtain_gm().
Referenced by Agent().
 {
   // create window and global variables
   char global[128];
   COM_new_window(window_name);
   sprintf(global, "%s%s", window_name, ".global");
   COM_new_dataitem(global, 'w', COM_VOID, 1, "");
   COM_set_object(global, 0, this);
   //
   COM_Type types[4];
   types[0] = COM_RAWDATA;
   char window_func[128];
   sprintf(window_func, "%s.init_callback", window_name);
   types[1] = COM_STRING;
   types[2] = COM_STRING;
   types[3] = COM_VOID;
   COM_set_member_function(window_func, (Member_func_ptr)&Agent::init_callback,
                           global, "biiI", types);
   ic_handle = COM_get_function_handle(window_func);
   types[1] = COM_DOUBLE;
   types[2] = COM_INT;
   sprintf(window_func, "%s.obtain_bc", window_name);
   COM_set_member_function(window_func, (Member_func_ptr)&Agent::obtain_bc, global, "biI", types);
   bc_handle = COM_get_function_handle(window_func);
   sprintf(window_func, "%s.obtain_gm", window_name);
   COM_set_member_function(window_func, (Member_func_ptr)&Agent::obtain_gm, global, "bi", types);
   gm_handle = COM_get_function_handle(window_func);
   COM_window_init_done(window_name);
 }
void Agent::finalize () virtual
Reimplemented in SolidAgent, BurnAgent, and FluidAgent.
Definition at line 449 of file Agent.C.
References bcInitScheduler, bcScheduler, COM_call_function(), comm_rank, Scheduler::finalize_actions(), finalize_handle, get_agent_name(), get_coupling(), gmScheduler, icScheduler, and MAN_DEBUG.
Referenced by BurnAgent::finalize(), FluidAgent::finalize(), and SolidAgent::finalize().
 {
   MAN_DEBUG(1, ("[%d] Rocman: %s::finalize called.\n", comm_rank, get_agent_name().c_str()));
   icScheduler.finalize_actions();
   bcInitScheduler.finalize_actions();
   for (unsigned int i=0; i<bcScheduler.size(); i++)
         bcScheduler[i]->finalize_actions();
   gmScheduler.finalize_actions();
     // at restart, we don't want windows in physics modules deleted
   if (! get_coupling()->in_restart())
     COM_call_function(finalize_handle);
 }
std::string Agent::get_agent_name () const inline
Definition at line 254 of file Agent.h.
Referenced by Agent(), create_buffer_all(), finalize(), BCInitInvoker::init(), init_callback(), init_module(), init_subscheduler(), PhysicsAction::name(), obtain_bc(), print(), read_by_control_file(), BCInvoker::run(), GMInvoker::run(), BCInitInvoker::run(), PhysicsAction::run(), ComputePconn::run(), run_bcinitaction(), store_solutions(), write_control_file(), and write_data_files().
 { return agent_name; }
Scheduler* Agent::get_bcScheduler (unsigned int level) inline protected
Definition at line 270 of file Agent.h.
Referenced by obtain_bc().
 { return level-1<bcScheduler.size()?bcScheduler[level-1]:NULL; }
int Agent::get_comm_rank () const inline
Definition at line 255 of file Agent.h.
Referenced by compute_overlay(), HeatTransfer_FS::init(), SurfDiver::run(), MassTransfer_SF_ALE::run(), TemperatureTransfer_SF::run(), and HeatTransfer_FS::run().
 { return comm_rank; }
MPI_Comm Agent::get_communicator () const inline
Definition at line 251 of file Agent.h.
Referenced by _load_rocface(), compute_overlay(), FluidPropagateSurface::init(), ComputePconn::init(), SolidPropagateSurface_ALE::init(), SurfDiver::run(), FluidPropagateSurface::run(), SolidPropagateSurface_ALE::run(), and FullyCoupling::update_distances().
 { return communicator; }
Coupling* Agent::get_coupling () inline
Definition at line 244 of file Agent.h.
Referenced by _load_rocface(), ComputeFluidLoad_ALE::ComputeFluidLoad_ALE(), BurnAgent::create_buffer_all(), FluidAgent::create_buffer_all(), SolidAgent::create_buffer_all(), declare_solid_actions(), BurnAgent::finalize(), FluidAgent::finalize(), SolidAgent::finalize(), finalize(), FluidBurnAlone::FluidBurnAlone(), LoadTransfer_FS::init(), LoadTransfer_FSc_ALE::init(), LoadTransferOnly_FSc_ALE::init(), SurfDiver::init(), MeshMotionTransfer_SF::init(), DeformationVelTransfer_SF::init(), MeshMotionTransferISS::init(), TransferSolidDensity::init(), FluidPropagateSurface::init(), TransferBurnRate_FS_ALE::init(), MassTransfer_SF_ALE::init(), TemperatureTransfer_SF::init(), HeatTransfer_FS::init(), RemeshInit::init(), ComputePconn::init(), SolidPropagateSurface_ALE::init(), BurnAgent::init_module(), LoadTransfer_FS::LoadTransfer_FS(), LoadTransfer_FSc_ALE::LoadTransfer_FSc_ALE(), LoadTransferOnly_FSc_ALE::LoadTransferOnly_FSc_ALE(), Extrapolate_Linear::run(), Extrapolate_Central::run(), LoadTransfer_FSc_ALE::run(), Interpolate_Linear::run(), Interpolate_Central::run(), GetDeformedMesh_ALE::run(), MeshMotionTransfer_SF::run(), ComputeFluidLoad_ALE::run(), PhysicsAction::run(), TransferSolidDensity::run(), FluidPropagateSurface::run(), CopyBflagFromBurn::run(), SolidPropagateSurface_ALE::run(), run_bcinitaction(), FluidAgent::unload_module(), BurnAgent::unload_module(), SolidAgent::unload_module(), write_control_file(), and write_data_files().
 { return coupling; }
double* Agent::get_integrals () inline
Definition at line 263 of file Agent.h.
Referenced by FullyCoupling::update_integrals().
 { return integrals; }
Action* Agent::get_main_action () inline
Definition at line 214 of file Agent.h.
Referenced by FluidAlone::FluidAlone(), and FluidBurnAlone::FluidBurnAlone().
 { return &action; }
std::string Agent::get_modinstance_name () const inline
Definition at line 253 of file Agent.h.
Referenced by _load_rocface().
 { return mod_instance; }
double Agent::get_old_dt () const inline
Definition at line 257 of file Agent.h.
Referenced by InterpolateBase::backup(), Extrapolate_Linear::run(), Extrapolate_Central::run(), Interpolate_Linear::run(), and Interpolate_Central::run().
 { return old_dt; }
std::string Agent::get_rocmod_name () const inline
Definition at line 252 of file Agent.h.
Referenced by compute_overlay(), SurfDiver::init(), SurfDiver::run(), and SurfDiver::SurfDiver().
 { return rocmod_name; }
std::string Agent::get_surface_window () const inline
Definition at line 248 of file Agent.h.
Referenced by ComputeFluidLoad_ALE::ComputeFluidLoad_ALE(), CloneDataItem::create(), UseDataItem::create(), FluidBurnAlone::FluidBurnAlone(), HeatTransfer_FS::HeatTransfer_FS(), ComputeMeshMotion::init(), HeatTransfer_FS::init(), CopyBurnFromParentMesh::init(), CopyBflagFromBurn::init(), Reset_du_alp::init(), Interpolate_Constant::Interpolate_Constant(), LoadTransfer_FS::LoadTransfer_FS(), LoadTransfer_FSc_ALE::LoadTransfer_FSc_ALE(), LoadTransferOnly_FSc_ALE::LoadTransferOnly_FSc_ALE(), MeshMotionTransfer_SF::MeshMotionTransfer_SF(), RemeshInit::RemeshInit(), ComputeFaceCenters::run(), and TemperatureTransfer_SF::TemperatureTransfer_SF().
 { return surf_window; }
void Agent::get_time_string (double t, std::string & s)
Definition at line 561 of file Agent.C.
Referenced by compute_overlay(), read_by_control_file(), SurfDiver::run(), write_control_file(), and write_data_files().
{
   char chrstring[15];
   std::sprintf( chrstring, "%.5e", t*1.e10);
   s = ""; s.append( &chrstring[9]); s.append( ".");
   s.append( &chrstring[0], 1); s.append( &chrstring[2], 5);
 }
std::string Agent::get_volume_window () const inline
Definition at line 249 of file Agent.h.
 { return vol_window; }
void Agent::init_bcactions (double t)
Definition at line 428 of file Agent.C.
References bcScheduler.
Referenced by BCInvoker::init().
 {
   for (unsigned int i=0; i<bcScheduler.size(); i++)
         bcScheduler[i]->init_actions(t);
 }
void Agent::init_bcinitaction (double t)
Definition at line 540 of file Agent.C.
References bcInitScheduler, and Scheduler::init_actions().
Referenced by BCInitInvoker::init().
 {
   bcInitScheduler.init_actions(t);
 }
void Agent::init_callback (const char * surf_win, const char * vol_win, void * option = NULL)
Definition at line 465 of file Agent.C.
References comm_rank, create_buffer_all(), current_deltatime, current_time, get_agent_name(), icScheduler, Scheduler::init_actions(), Scheduler::isEmpty(), MAN_DEBUG, option_data, rocmod_name, Scheduler::run_actions(), Scheduler::set_alpha(), surf_window, and vol_window.
Referenced by create_window().
 {
   MAN_DEBUG(1, ("Rocman: %s::init_callback called: surfwin: %s volwin: %s.\n", get_agent_name().c_str(), surf_win, vol_win));
   surf_window = surf_win;
   vol_window = vol_win;
   option_data = option;
    // creat a window buffer to inherit from surface window
    // they are like ifluid_all, iburn_all, etc
   create_buffer_all();
   if (icScheduler.isEmpty()) {
     if (comm_rank==0)
       std::cerr << "Rocman WARNING: No actions defined for "
               << "Initialization callback for module "
               << rocmod_name << std::endl;
   }
   else {
     MAN_DEBUG(1, ("[%d] Rocman: %s::init_callback called IC with current_time:%e current_deltatime:%e.\n", comm_rank, get_agent_name().c_str(), current_time, current_deltatime));
     icScheduler.set_alpha(0.0);
     icScheduler.init_actions(current_time);
     icScheduler.run_actions(current_time, current_deltatime);
     MAN_DEBUG(1, ("[%d] Rocman: %s::init_callback called IC DONE.\n", comm_rank, get_agent_name().c_str()));
   }
   MAN_DEBUG(1, ("Rocman: Agent::init_callback called: surfwin: %s volwin: %s DONE.\n", surf_win, vol_win));
 }
void Agent::init_convergence (int iPredCorr) virtual
Reimplemented in FluidAgent.
Definition at line 704 of file Agent.C.
References store_solutions().
Referenced by FluidAgent::init_convergence().
 {
   store_solutions (iPredCorr == 1);
 }
void Agent::init_function_handles () protected
Definition at line 217 of file Agent.C.
References COM_assertion_msg, COM_get_function_handle(), COM_set_profiling_barrier(), communicator, compute_integrals_handle, finalize_handle, init_handle, mod_instance, obtain_attr_handle, post_hdf_handle, pre_hdf_handle, read_by_control_handle, read_files_handle, update_handle, write_attr_handle, and write_ctrl_handle.
Referenced by BurnAgent::load_module(), FluidAgent::load_module(), and SolidAgent::load_module().
 {
   // init function handle
   char fname[128];
   sprintf(fname, "%s%s", mod_instance.c_str(), ".initialize");
   init_handle = COM_get_function_handle(fname);
   COM_assertion_msg(init_handle>0, "ERROR: Agent::init_function_handles.\n");
   sprintf(fname, "%s%s", mod_instance.c_str(), ".update_solution");
   update_handle = COM_get_function_handle(fname);
   COM_assertion_msg(update_handle>0, "ERROR: Agent::init_function_handles.\n");
   sprintf(fname, "%s%s", mod_instance.c_str(), ".finalize");
   finalize_handle = COM_get_function_handle(fname);
   COM_assertion_msg(finalize_handle>0, "ERROR: Agent::init_function_handles.\n");
   // optional
   sprintf(fname, "%s%s", mod_instance.c_str(), ".pre_hdf_output");
   pre_hdf_handle = COM_get_function_handle(fname);
   // optional
   sprintf(fname, "%s%s", mod_instance.c_str(), ".post_hdf_output");
   post_hdf_handle = COM_get_function_handle(fname);
   COM_set_profiling_barrier( init_handle, communicator);
   COM_set_profiling_barrier( update_handle, communicator);
   COM_set_profiling_barrier( finalize_handle, communicator);
   if (pre_hdf_handle != -1)
     COM_set_profiling_barrier( pre_hdf_handle, communicator);
   if (post_hdf_handle != -1)
     COM_set_profiling_barrier( post_hdf_handle, communicator);
   sprintf(fname, "%s%s", mod_instance.c_str(), ".compute_integrals");
   compute_integrals_handle = COM_get_function_handle(fname);
   read_files_handle = COM_get_function_handle( "IN.read_window");
   read_by_control_handle = COM_get_function_handle( "IN.read_by_control_file");
   obtain_attr_handle = COM_get_function_handle( "IN.obtain_dataitem");
   write_attr_handle = COM_get_function_handle( "OUT.write_dataitem");
   write_ctrl_handle = COM_get_function_handle( "OUT.write_rocin_control_file");
   COM_set_profiling_barrier( read_files_handle, communicator);
   COM_set_profiling_barrier( read_by_control_handle, communicator);
   COM_set_profiling_barrier( obtain_attr_handle, communicator);
   COM_set_profiling_barrier( write_attr_handle, communicator);
 }
void Agent::init_gmactions (double t)
Definition at line 434 of file Agent.C.
References gmScheduler, and Scheduler::init_actions().
Referenced by GMInvoker::init().
 {
   gmScheduler.init_actions(t);
 }
void Agent::init_module (double t, double dt) virtual
Reimplemented in SolidAgent, BurnAgent, and FluidAgent.
Definition at line 399 of file Agent.C.
References comm_rank, current_deltatime, current_time, get_agent_name(), initial_time, MAN_DEBUG, and old_dt.
Referenced by BurnAgent::init_module(), FluidAgent::init_module(), and SolidAgent::init_module().
 {
  MAN_DEBUG(1, ("[%d] Rocman: %s::init_module with current_time:%e current_deltatime:%e.\n", comm_rank, get_agent_name().c_str(), t, dt));
   current_time = initial_time = t;
   current_deltatime = dt;
   old_dt = 0.0;
 }
void Agent::init_subscheduler (double t)
Definition at line 408 of file Agent.C.
References callMethod(), get_agent_name(), Scheduler::init_actions(), and MAN_DEBUG.
 {
   MAN_DEBUG(1, ("Rocman: %sAgent::init_subscheduler called.\n", get_agent_name().c_str()));
   callMethod(&Scheduler::init_actions, t);
   MAN_DEBUG(1, ("Rocman: %sAgent::init_subscheduler done.\n", get_agent_name().c_str()));
 }
virtual void Agent::input (double t) pure virtual
Implemented in SolidAgent, BurnAgent, and FluidAgent.
virtual void Agent::load_module () inline virtual
Reimplemented in SolidAgent, BurnAgent, and FluidAgent.
Definition at line 200 of file Agent.h.
 {}
double Agent::max_timestep (double t, double dt)
Definition at line 300 of file Agent.C.
 {
   return dt;
 }
void Agent::obtain_bc (double * a, int * l = NULL)
Definition at line 507 of file Agent.C.
References bcScheduler, comm_rank, current_deltatime, get_agent_name(), get_bcScheduler(), MAN_DEBUG, rocmod_name, Scheduler::run_actions(), Scheduler::set_alpha(), and timestamp.
Referenced by create_window(), and BCInvoker::run().
 {
   if ( l!=NULL && (unsigned int)(*l) > bcScheduler.size() && comm_rank==0) {
     std::cerr << "Rocman WARNING: No actions defined for "
               << "level-" << *l << " boundary condition "
               << "for module " << rocmod_name << std::endl;
     return;
   }
   int level = (l==NULL)?1:*l;
   MAN_DEBUG(2, ("[%d] Rocman: Agent %s::obtain_bc called at level: %d t:%e.\n", comm_rank, get_agent_name().c_str(), level, timestamp))
   Scheduler *sched = get_bcScheduler(level);
   if (sched) {
     sched->set_alpha(*a);
     sched->run_actions(timestamp, current_deltatime);
   }
 }
void Agent::obtain_gm (double * da)
Definition at line 526 of file Agent.C.
References comm_rank, current_deltatime, gmScheduler, Scheduler::isEmpty(), MAN_DEBUG, rocmod_name, Scheduler::run_actions(), and Scheduler::set_alpha().
Referenced by create_window(), and GMInvoker::run().
 {
   if (gmScheduler.isEmpty() && comm_rank==0) {
     std::cerr << "Rocman WARNING: No actions defined for "
               << "Grid Motion "
               << "for module " << rocmod_name << std::endl;
     return;
   }
   MAN_DEBUG(2, ("[%d] Rocman: Agent::obtain_gm called with alpha: %e.\n", comm_rank, *da))
     // ???????????????
   gmScheduler.set_alpha(*da);
   gmScheduler.run_actions(0.0, current_deltatime);
 }
virtual void Agent::output_restart_files (double t) pure virtual
Implemented in SolidAgent, BurnAgent, and FluidAgent.
virtual void Agent::output_visualization_files (double t) pure virtual
Implemented in SolidAgent, BurnAgent, and FluidAgent.
void Agent::print (FILE * f)
Definition at line 745 of file Agent.C.
References bcInitScheduler, bcScheduler, get_agent_name(), gmScheduler, and Scheduler::print().
Referenced by PhysicsAction::print().
 {
   unsigned int i;
     // agent
   fprintf(f, "graph: { title: \"%s\" label: \"%s\" \n\
         status: folded \n\
         display_edge_labels: yes \n\
         layoutalgorithm: tree   \n\
         scaling: maxspect   \n\
         color :  lightyellow           \n\
         node.color     : lightblue   \n\
         node.textcolor : lightblue   \n\
         node.bordercolor: black \n\
         node.borderwidth: 1    \n\
         edge.color     : lightblue   \n\
         edge.arrowsize : 7   \n\
         edge.thickness : 2   \n\
         edge.fontname:\"helvO08\"  \n\
         node.label: \"no type\" \n", get_agent_name().c_str(), get_agent_name().c_str());
   char *bcinit = bcInitScheduler.print(f, get_agent_name().c_str());
     // main physics
   std::string main_action = get_agent_name() + "-main";
   fprintf(f, "graph: { title: \"%s\" label: \"%s\" \n\
         status: folded \n\
         display_edge_labels: yes \n\
         layoutalgorithm: tree   \n\
         scaling: maxspect   \n\
         color :  lightred           \n\
         node.color     : lightblue   \n\
         node.textcolor : black   \n\
         node.bordercolor: black \n\
         node.borderwidth: 1    \n\
         edge.color     : lightblue   \n\
         edge.arrowsize : 7   \n\
         edge.thickness : 2   \n\
         edge.fontname:\"helvO08\"  \n\
         node.label: \"no type\" \n", main_action.c_str(), main_action.c_str());
   for (i=0; i<bcScheduler.size(); i++)
     bcScheduler[i]->print(f, get_agent_name().c_str());
   gmScheduler.print(f, get_agent_name().c_str());
   std::string main_physics = get_agent_name() + "-physics";
   fprintf(f, "node: { title:\"%s\" label:\"%s\"}\n", main_physics.c_str(), main_physics.c_str());
   fprintf(f, "}\n");
   if (bcinit) {
     fprintf(f, "edge: { sourcename: \"%s\" targetname: \"%s\" label: \"\"}\n", bcinit, main_action.c_str());
     free(bcinit);
   }
   fprintf(f, "}\n");
 }
int Agent::read_by_control_file (double t, const std::string base, const std::string window) protected
Definition at line 571 of file Agent.C.
References COM_call_function(), comm_rank, COMMPI_Comm_rank(), communicator, get_agent_name(), get_time_string(), inDir, MAN_DEBUG, outDir, read_by_control_handle, and skipInputIO.
Referenced by BurnAgent::input(), FluidAgent::input(), and SolidAgent::input().
{
   if (skipInputIO) return 0;    // physics module does input itself
   // Read in surface window
   std::string fname = inDir; fname.append( base); fname.append("_in_");
   std::string timeLevel; get_time_string( t, timeLevel);
   fname.append( timeLevel); fname.append( ".txt");
   MAN_DEBUG(2, ("[%d] Agent %s::read_by_control_file run with file: %s t:%e.\n", comm_rank, get_agent_name().c_str(), fname.c_str(), t));
   bool ctrl_exist;
   FILE *fp = fopen( fname.c_str(), "r");
   ctrl_exist = (fp!=NULL);
   if ( !ctrl_exist && t!=0.0 ) {
     fname = outDir + base + "_in_" + timeLevel + ".txt";
     fp = fopen( fname.c_str(), "r");
     ctrl_exist = (fp!=NULL);
   }
   int comm_rank = COMMPI_Comm_rank(communicator);
   if ( ctrl_exist) {
     if (comm_rank==0)
       std::cout << "Rocman: Found control file " << fname << std::endl;
     COM_call_function( read_by_control_handle, fname.c_str(),
                        window.c_str(), &communicator);
     return 0;
   }
   else {
     if (comm_rank==0)
       std::cout << "Rocman: Did not find control file " << fname << std::endl;
     return -1;
   }
 }
virtual void Agent::read_restart_data () inline virtual
Reimplemented in SolidAgent, BurnAgent, and FluidAgent.
Definition at line 224 of file Agent.h.
 {}
void Agent::register_clone_dataitem (int cond, std::string target_window_, std::string attr_, std::string parent_window_, std::string parent_attr_, int wg_ = 1, const char * ptnname_ = 0, int val_ = 0)
Definition at line 311 of file Agent.C.
References dataitemList.
Referenced by ComputeFluidLoad_ALE::ComputeFluidLoad_ALE(), HeatTransfer_FS::HeatTransfer_FS(), LoadTransfer_FS::LoadTransfer_FS(), LoadTransfer_FSc_ALE::LoadTransfer_FSc_ALE(), LoadTransferOnly_FSc_ALE::LoadTransferOnly_FSc_ALE(), MeshMotionTransfer_SF::MeshMotionTransfer_SF(), MeshMotionTransferISS::MeshMotionTransferISS(), RemeshInit::RemeshInit(), and TemperatureTransfer_SF::TemperatureTransfer_SF().
 {
   CloneDataItem *newAttr = new CloneDataItem(this, cond, target_window_, attr_, parent_window_, parent_attr_, wg_, ptnname_, val_);
   dataitemList.push_back(newAttr);
 }
void Agent::register_interpolate (InterpolateBase * ip)
Definition at line 608 of file Agent.C.
References interpolateList.
Referenced by InterpolateBase::InterpolateBase().
 {
   interpolateList.push_back(ip);
 }
void Agent::register_new_dataitem (std::string target_window_, std::string attr_, char loc_, int type_, int ncomp_, const char * unit_)
Definition at line 305 of file Agent.C.
References dataitemList.
Referenced by ComputeFluidLoad_ALE::ComputeFluidLoad_ALE(), ComputeMeshMotion::ComputeMeshMotion(), FluidPropagateSurface::FluidPropagateSurface(), LoadTransfer_FS::LoadTransfer_FS(), LoadTransfer_FSc_ALE::LoadTransfer_FSc_ALE(), LoadTransferOnly_FSc_ALE::LoadTransferOnly_FSc_ALE(), MassTransfer_SF_ALE::MassTransfer_SF_ALE(), MeshMotionTransferISS::MeshMotionTransferISS(), and TransferSolidDensity::TransferSolidDensity().
 {
   NewDataItem *newAttr = new NewDataItem(this, target_window_, attr_, loc_, type_, ncomp_, unit_);
   dataitemList.push_back(newAttr);
 }
void Agent::register_use_dataitem (std::string target_window_, std::string attr_, std::string parent_window_, std::string parent_attr_, int wg_ = 1, const char * ptnname_ = 0, int val_ = 0)
Definition at line 317 of file Agent.C.
References dataitemList.
Referenced by MassTransfer::MassTransfer(), and MassTransfer_SF_ALE::MassTransfer_SF_ALE().
 {
   UseDataItem *newAttr = new UseDataItem(this, target_window_, attr_, parent_window_, parent_attr_, wg_, ptnname_, val_);
   dataitemList.push_back(newAttr);
 }
void Agent::run_bcinitaction (double t, double dt)
Definition at line 545 of file Agent.C.
References bcInitScheduler, dobackup, get_agent_name(), get_coupling(), MAN_DEBUG, and Scheduler::run_actions().
Referenced by BCInitInvoker::run(), and PhysicsAction::run().
 {
   MAN_DEBUG(1, ("Rocman: %s::run_bcinitaction called t=%e dt=%e.\n", get_agent_name().c_str(), t, dt));
   // backup first
   if (get_coupling()->get_ipc() <= 1 && dobackup == 1)
 //   for (unsigned int i=0; i<interpolateList.size(); i++)
 //     interpolateList[i]->backup();
   bcInitScheduler.run_actions(t, dt);
 }
void Agent::schedule ()
Definition at line 439 of file Agent.C.
References bcInitScheduler, bcScheduler, gmScheduler, icScheduler, and UserScheduler::schedule().
 {
   icScheduler.schedule();
   bcInitScheduler.schedule();
   for (unsigned int i=0; i<bcScheduler.size(); i++)  {
         bcScheduler[i]->schedule();
   }
   gmScheduler.schedule();
 }
void Agent::split_surface_window (const std::string surfAll, const std::string surf_i, const std::string surf_nb, const std::string surf_b, const std::string surf_ni) protected
Definition at line 674 of file Agent.C.
References COM_get_window_handle(), COM_new_window(), COM_use_dataitem(), and COM_window_init_done().
Referenced by SolidAgent::create_buffer_all().
{
   std::string bcflag = surfAll+".bcflag";
   std::string atts   = surfAll+".all";
   if (COM_get_window_handle(surf_i) <= 0)
   COM_new_window( surf_i);
   COM_use_dataitem( surf_i,atts, 0, bcflag.c_str(), 0);
   COM_use_dataitem( surf_i,atts, 0, bcflag.c_str(), 1);
   COM_window_init_done( surf_i);
   if (COM_get_window_handle(surf_nb) <= 0)
   COM_new_window( surf_nb); // bcflag ==0
   COM_use_dataitem( surf_nb,atts, 1, bcflag.c_str(), 0);
   COM_window_init_done( surf_nb);
   if (COM_get_window_handle(surf_b) <= 0)
   COM_new_window( surf_b); // bcflag ==1
   COM_use_dataitem( surf_b,atts, 1, bcflag.c_str(), 1);
   COM_window_init_done( surf_b);
   if (COM_get_window_handle(surf_ni) <= 0)
   COM_new_window( surf_ni); // bcflag ==2
   COM_use_dataitem( surf_ni,atts, 1,  bcflag.c_str(), 2);
   COM_window_init_done( surf_ni);
 }
void Agent::store_solutions (int converged) protected virtual
Definition at line 709 of file Agent.C.
References COM_copy_dataitem(), comm_rank, get_agent_name(), MAN_DEBUG, pc_count, and pc_hdls.
Referenced by init_convergence().
 {
   int i;
   MAN_DEBUG(1, ("[%d] Agent %s::store_solutions converged=%d.\n", comm_rank, get_agent_name().c_str(), converged));
   if ( converged) {   //  Store internal data
      for (i=0; i<pc_count; i++)
        if ( pc_hdls[0][i]>0)
                COM_copy_dataitem( pc_hdls[1][i], pc_hdls[0][i]);
   }
   else {
      for (i=0; i<pc_count; i++)
        if ( pc_hdls[0][i]>0)
                COM_copy_dataitem( pc_hdls[0][i], pc_hdls[1][i]);
   }
 }
virtual void Agent::unload_module () inline virtual
Reimplemented in SolidAgent, BurnAgent, and FluidAgent.
Definition at line 201 of file Agent.h.
 {}
void Agent::write_control_file (double t, const std::string base, const std::string window) protected
Definition at line 640 of file Agent.C.
References COM_call_function(), comm_rank, get_agent_name(), get_coupling(), Coupling::get_rocmancontrol_param(), get_time_string(), MAN_DEBUG, outDir, RocmanControl_parameters::separate_out, and write_ctrl_handle.
Referenced by BurnAgent::output_restart_files(), FluidAgent::output_restart_files(), and SolidAgent::output_restart_files().
{
   int separate_out = get_coupling()->get_rocmancontrol_param()->separate_out;
   // Read in surface window
   std::string fname;  // = base; fname.append("_");
 /*
   if (separate_out)  {
     std::ostringstream rank;
     rank << comm_rank;
     fname += rank.str(); fname.append( "/");
   }
 */
   fname.append( base);
   fname.append("_");
   std::string timeLevel; get_time_string( t, timeLevel);
   fname.append( timeLevel); fname.append("_");
   std::string ctrl_fname = outDir; ctrl_fname.append( base);
   // If base contains '*', then remove it
   std::string::size_type pos = ctrl_fname.find('*');
   if ( pos != std::string::npos) ctrl_fname.erase( pos);
   ctrl_fname.append("_in_"); ctrl_fname.append( timeLevel);
   ctrl_fname.append(".txt");
   if ( comm_rank == 0)
     MAN_DEBUG(1, ("[%d] Rocman: Agent %s::write_control_file %s with file prefix %s at t:%e.\n", comm_rank, get_agent_name().c_str(), ctrl_fname.c_str(), fname.c_str(), t));
   COM_call_function( write_ctrl_handle, window.c_str(), fname.c_str(),
                      ctrl_fname.c_str());
 }
void Agent::write_data_files (double t, const std::string base, const std::string attr, const char * ref = NULL) protected
Definition at line 614 of file Agent.C.
References COM_call_function(), COM_get_dataitem_handle(), comm_rank, communicator, get_agent_name(), get_coupling(), Coupling::get_rocmancontrol_param(), get_time_string(), MAN_DEBUG, outDir, RocmanControl_parameters::separate_out, and write_attr_handle.
Referenced by BurnAgent::output_restart_files(), FluidAgent::output_restart_files(), and SolidAgent::output_restart_files().
{
   int separate_out = get_coupling()->get_rocmancontrol_param()->separate_out;
   // Read in surface window
   std::string fname = outDir;
 /*
   if (separate_out)  {
     std::ostringstream rank;
     rank << comm_rank;
     fname += rank.str();
     fname.append( "/");
   }
 */
   fname.append( base); fname.append("_");
   std::string timeLevel; get_time_string( t, timeLevel);
   fname.append( timeLevel); fname.append("_");
   MAN_DEBUG(2, ("[%d] Rocman: Agent %s::write_data_file with file prefix %s at t:%e.\n", comm_rank, get_agent_name().c_str(), fname.c_str(), t));
   int attr_hdl = COM_get_dataitem_handle( attr);
   COM_call_function( write_attr_handle, fname.c_str(), &attr_hdl,
                      base.c_str(), timeLevel.c_str(), ref, &communicator);
 }
Friends And Related Function Documentation
friend class PhysicsAction friend
Definition at line 142 of file Agent.h.
Member Data Documentation
PhysicsAction Agent::action protected
Definition at line 147 of file Agent.h.
Referenced by Agent().
const std::string Agent::agent_name protected
Definition at line 144 of file Agent.h.
Referenced by Agent().
int Agent::bc_handle protected
Definition at line 167 of file Agent.h.
Referenced by create_window(), and PhysicsAction::run().
UserScheduler Agent::bcInitScheduler protected
Definition at line 149 of file Agent.h.
Referenced by add_bcinitaction(), Agent(), callMethod(), finalize(), init_bcinitaction(), print(), run_bcinitaction(), and schedule().
SchdulerList Agent::bcScheduler protected
Definition at line 148 of file Agent.h.
Referenced by add_bcaction(), callMethod(), finalize(), init_bcactions(), obtain_bc(), print(), and schedule().
int Agent::comm_rank protected
Definition at line 161 of file Agent.h.
Referenced by Agent(), check_convergence_help(), SolidAgent::create_buffer_all(), create_registered_dataitems(), create_registered_window_dataitems(), finalize(), init_callback(), init_module(), FluidAgent::load_module(), BurnAgent::load_module(), SolidAgent::load_module(), obtain_bc(), obtain_gm(), read_by_control_file(), PhysicsAction::run(), store_solutions(), SolidAgent::unload_module(), write_control_file(), and write_data_files().
MPI_Comm Agent::communicator protected
Definition at line 145 of file Agent.h.
Referenced by check_convergence_help(), init_function_handles(), BurnAgent::init_module(), FluidAgent::init_module(), SolidAgent::init_module(), FluidAgent::input(), read_by_control_file(), and write_data_files().
int Agent::compute_integrals_handle protected
Definition at line 164 of file Agent.h.
Referenced by FluidAgent::compute_integrals(), SolidAgent::compute_integrals(), and init_function_handles().
Coupling* Agent::coupling protected
Definition at line 146 of file Agent.h.
double Agent::current_deltatime protected
Definition at line 175 of file Agent.h.
Referenced by init_callback(), init_module(), obtain_bc(), obtain_gm(), and PhysicsAction::run().
double Agent::current_time protected
Definition at line 175 of file Agent.h.
Referenced by init_callback(), init_module(), and PhysicsAction::run().
DataItemList Agent::dataitemList protected
Definition at line 187 of file Agent.h.
Referenced by assign_dataitems(), create_registered_dataitems(), create_registered_window_dataitems(), register_clone_dataitem(), register_new_dataitem(), and register_use_dataitem().
int Agent::dobackup protected
Definition at line 170 of file Agent.h.
Referenced by Agent(), FluidAgent::FluidAgent(), and run_bcinitaction().
int Agent::finalize_handle protected
Definition at line 164 of file Agent.h.
Referenced by finalize(), and init_function_handles().
int Agent::gm_handle protected
Definition at line 167 of file Agent.h.
Referenced by create_window(), and PhysicsAction::run().
UserScheduler Agent::gmScheduler protected
Definition at line 150 of file Agent.h.
Referenced by add_gmaction(), Agent(), callMethod(), finalize(), init_gmactions(), obtain_gm(), print(), and schedule().
int Agent::ic_handle protected
Definition at line 167 of file Agent.h.
Referenced by create_window(), BurnAgent::init_module(), FluidAgent::init_module(), and SolidAgent::init_module().
UserScheduler Agent::icScheduler protected
Definition at line 151 of file Agent.h.
Referenced by add_icaction(), finalize(), init_callback(), and schedule().
string Agent::inDir protected
Definition at line 173 of file Agent.h.
Referenced by Agent(), and read_by_control_file().
int Agent::init_handle protected
Definition at line 162 of file Agent.h.
Referenced by init_function_handles(), BurnAgent::init_module(), FluidAgent::init_module(), and SolidAgent::init_module().
double Agent::initial_time protected
Definition at line 175 of file Agent.h.
Referenced by init_module().
double Agent::integrals[MAN_INTEG_SIZE] protected
Definition at line 193 of file Agent.h.
Referenced by FluidAgent::compute_integrals(), and SolidAgent::compute_integrals().
InterpolateList Agent::interpolateList protected
Definition at line 184 of file Agent.h.
Referenced by register_interpolate().
string Agent::mod_instance protected
Definition at line 172 of file Agent.h.
Referenced by init_function_handles(), BurnAgent::load_module(), FluidAgent::load_module(), SolidAgent::load_module(), BurnAgent::unload_module(), FluidAgent::unload_module(), and SolidAgent::unload_module().
int Agent::obtain_attr_handle =0 static protected
Definition at line 156 of file Agent.h.
Referenced by init_function_handles(), BurnAgent::init_module(), FluidAgent::init_module(), SolidAgent::init_module(), BurnAgent::read_restart_data(), FluidAgent::read_restart_data(), and SolidAgent::read_restart_data().
double Agent::old_dt protected
Definition at line 175 of file Agent.h.
Referenced by Agent(), init_module(), and PhysicsAction::run().
void* Agent::option_data protected
Definition at line 181 of file Agent.h.
Referenced by init_callback(), and BurnAgent::init_module().
string Agent::outDir protected
Definition at line 173 of file Agent.h.
Referenced by Agent(), read_by_control_file(), write_control_file(), and write_data_files().
int Agent::pc_count protected
Definition at line 191 of file Agent.h.
Referenced by BurnAgent::create_buffer_all(), FluidAgent::create_buffer_all(), SolidAgent::create_buffer_all(), and store_solutions().
int Agent::pc_hdls[2][3] protected
Definition at line 189 of file Agent.h.
Referenced by BurnAgent::create_buffer_all(), FluidAgent::create_buffer_all(), SolidAgent::create_buffer_all(), and store_solutions().
int Agent::post_hdf_handle protected
Definition at line 163 of file Agent.h.
Referenced by init_function_handles(), and FluidAgent::output_restart_files().
int Agent::pre_hdf_handle protected
Definition at line 163 of file Agent.h.
Referenced by init_function_handles(), and FluidAgent::output_restart_files().
int Agent::read_by_control_handle =0 static protected
Definition at line 154 of file Agent.h.
Referenced by init_function_handles(), and read_by_control_file().
int Agent::read_files_handle =0 static protected
Definition at line 155 of file Agent.h.
Referenced by init_function_handles().
string Agent::rocmod_name protected
Definition at line 172 of file Agent.h.
Referenced by init_callback(), BurnAgent::load_module(), FluidAgent::load_module(), SolidAgent::load_module(), obtain_bc(), obtain_gm(), FluidAgent::unload_module(), BurnAgent::unload_module(), and SolidAgent::unload_module().
bool Agent::skipInputIO protected
Definition at line 195 of file Agent.h.
Referenced by read_by_control_file().
string Agent::suffix protected
Definition at line 173 of file Agent.h.
Referenced by Agent().
std::string Agent::surf_window protected
Definition at line 179 of file Agent.h.
Referenced by BurnAgent::create_buffer_all(), FluidAgent::create_buffer_all(), SolidAgent::create_buffer_all(), create_buffer_all(), init_callback(), BurnAgent::output_restart_files(), FluidAgent::output_restart_files(), and SolidAgent::output_restart_files().
double Agent::timestamp protected
Definition at line 175 of file Agent.h.
Referenced by Agent(), obtain_bc(), and PhysicsAction::run().
std::string Agent::tmp_window protected
Definition at line 180 of file Agent.h.
Referenced by assign_dataitems(), BurnAgent::BurnAgent(), create_buffer_all(), FluidAgent::FluidAgent(), and SolidAgent::SolidAgent().
int Agent::update_handle protected
Definition at line 162 of file Agent.h.
Referenced by init_function_handles(), and PhysicsAction::run().
std::string Agent::vol_window protected
Definition at line 179 of file Agent.h.
Referenced by BurnAgent::create_buffer_all(), FluidAgent::create_buffer_all(), SolidAgent::create_buffer_all(), init_callback(), FluidAgent::init_module(), FluidAgent::output_restart_files(), BurnAgent::output_restart_files(), and SolidAgent::output_restart_files().
bool Agent::withgm protected
Definition at line 168 of file Agent.h.
Referenced by PhysicsAction::run().
int Agent::write_attr_handle =0 static protected
Definition at line 157 of file Agent.h.
Referenced by init_function_handles(), and write_data_files().
int Agent::write_ctrl_handle =0 static protected
Definition at line 158 of file Agent.h.
Referenced by init_function_handles(), and write_control_file().
The documentation for this class was generated from the following files:
Agent.h
Agent.C