IMPACT: MeshMotionTransferISS Class Reference
MeshMotionTransferISS Class Reference
Detailed Description
Definition at line 131 of file transfer_actions.h.
#include <transfer_actions.h>
Public Member Functions
MeshMotionTransferISS (FluidAgent *fag, SolidAgent *sag, const std::string s_u, const std::string s_vs, const std::string f_vm)
void init (double t)
void run (double t, double dt, double alpha)
Public Member Functions inherited from InterMeshTransfer
InterMeshTransfer (FluidAgent *fag, SolidAgent *sag, char *name=NULL)
Public Member Functions inherited from Action
Action (void *p=0, const char *name=NULL)
Action (int n, const char **at, int *i=NULL, void *p=0, const char *name=NULL)
Action (int n, const std::string at[], int *i=NULL, void *p=0, const char *name=NULL)
virtual ~Action ()
virtual void declare (Scheduler &)
virtual void finalize ()
virtual const char * name ()
void set_name (const char *name)
virtual void print (FILE *f)
virtual void print_toposort (FILE *f)
virtual void schedule ()
Private Attributes
std::string s_u_str
std::string s_vs_str
std::string f_vm_str
int s_u_hdl
int s_vs_hdl
int f_vm_hdl
int f_u_hdl
int f_vs_hdl
int f_uold_hdl
int f_vsold_hdl
int f_utmp_hdl
int f_vtmp_hdl
int RFC_interpolate
Additional Inherited Members
Protected Types inherited from Action
enum { IN =1, OUT =2, INOUT =3 }
Protected Member Functions inherited from InterMeshTransfer
void load_rocface (const RocmanControl_parameters *param)
Protected Member Functions inherited from Action
int get_dataitem_handle (int i)
int get_dataitem_handle_const (int i)
int get_dataitem_handle (const std::string str)
void set_attr (int n, const std::string at[], int *id=NULL)
void set_attr (int n, const char *at[], int *id=NULL)
void set_io (int n, const int *io)
void set_io (const char *io)
int get_io (int i)
Protected Attributes inherited from InterMeshTransfer
FluidAgent * fagent
SolidAgent * sagent
Protected Attributes inherited from Action
const char * action_name
char ** attr
int * idx
int count
void * usr_ptr
std::vector< int > inout
Constructor & Destructor Documentation
MeshMotionTransferISS::MeshMotionTransferISS (FluidAgent * fag, SolidAgent * sag, const std::string s_u, const std::string s_vs, const std::string f_vm) explicit
Definition at line 714 of file transfer_actions.C.
References COM_assertion_msg, COM_DOUBLE, IMPACT::ExampleProgram::f(), f_vm_str, InterMeshTransfer::fagent, FluidAgent::fluidBufNG, Action::IN, Action::OUT, Agent::register_clone_dataitem(), Agent::register_new_dataitem(), Action::set_attr(), and Action::set_io().
                                                                                                                                              :
     InterMeshTransfer(fag, sag, "MeshMotionTransferISS"),
     s_u_str(s_u), s_vs_str(s_vs), f_vm_str(f_vm)
 {
   // isolid_i+".u" (in), isolid_i+".vs" (in), ifluid_i+".vm" (out)
   int io[] = {IN, IN, OUT};
   set_io( 3, io);
   std::string.data[3];
  .data[0] = s_u;
  .data[1] = s_vs;
  .data[2] = f_vm;
   set_attr(3,.data);
   std::string::size_type pos = f_vm_str.find( ".");
   COM_assertion_msg(pos!=std::string::npos, "MeshMotionTransferISS failed!");
   std::string f = f_vm_str.substr( 0, pos);
   std::string vm = f_vm_str.substr( pos, f_vm_str.size());
   fagent->register_new_dataitem( f, vm, 'n', COM_DOUBLE, 3, "m/s");
     // used internally
   fagent->register_clone_dataitem( 0, fagent->fluidBufNG, ".u", fagent->fluidBufNG, ".vm");
   fagent->register_clone_dataitem( 0, fagent->fluidBufNG, ".uold", fagent->fluidBufNG, ".vm");
    // avoid vs because vs is 'e'
   fagent->register_clone_dataitem( 0, fagent->fluidBufNG, ".fvs", fagent->fluidBufNG, ".vm");
   fagent->register_clone_dataitem( 0, fagent->fluidBufNG, ".vsold", fagent->fluidBufNG, ".vm");
   fagent->register_clone_dataitem( 0, fagent->fluidBufNG, ".utmp", fagent->fluidBufNG, ".vm");
   fagent->register_clone_dataitem( 0, fagent->fluidBufNG, ".vtmp", fagent->fluidBufNG, ".vm");
 }
Member Function Documentation
void MeshMotionTransferISS::init (double t) virtual
Reimplemented from Action.
Definition at line 743 of file transfer_actions.C.
References COM_call_function(), COM_get_dataitem_handle(), COM_get_function_handle(), RocBlas::copy_scalar, f_u_hdl, f_uold_hdl, f_utmp_hdl, f_vm_hdl, f_vs_hdl, f_vsold_hdl, f_vtmp_hdl, InterMeshTransfer::fagent, FluidAgent::fluidBufNG, Agent::get_coupling(), Action::get_dataitem_handle(), Coupling::get_rocmancontrol_param(), InterMeshTransfer::load_rocface(), RFC_interpolate, s_u_hdl, and s_vs_hdl.
{
   s_u_hdl = get_dataitem_handle(0);
   s_vs_hdl = get_dataitem_handle(1);
   f_vm_hdl = get_dataitem_handle(2);
   f_u_hdl = COM_get_dataitem_handle(fagent->fluidBufNG+".u");
   f_vs_hdl = COM_get_dataitem_handle(fagent->fluidBufNG+".fvs");
   f_uold_hdl = COM_get_dataitem_handle(fagent->fluidBufNG+".uold");
   f_vsold_hdl = COM_get_dataitem_handle( fagent->fluidBufNG+".vsold");
   f_utmp_hdl = COM_get_dataitem_handle( fagent->fluidBufNG+".utmp");
   f_vtmp_hdl = COM_get_dataitem_handle( fagent->fluidBufNG+".vtmp");
     // set zero
   double zero = 0.0;
   COM_call_function( RocBlas::copy_scalar, &zero, &f_uold_hdl);
   COM_call_function( RocBlas::copy_scalar, &zero, &f_vsold_hdl);
   load_rocface(fagent->get_coupling()->get_rocmancontrol_param());
   RFC_interpolate = COM_get_function_handle("RFC.interpolate");
 }
void MeshMotionTransferISS::run (double t, double dt, double alpha) virtual
Reimplemented from Action.
Definition at line 765 of file transfer_actions.C.
References RocBlas::add, COM_call_function(), RocBlas::copy, RocBlas::div_scalar, f_u_hdl, f_uold_hdl, f_utmp_hdl, f_vm_hdl, f_vs_hdl, f_vsold_hdl, f_vtmp_hdl, MAN_DEBUG, RocBlas::mul_scalar, RFC_interpolate, s_u_hdl, s_vs_hdl, and RocBlas::sub.
{
   MAN_DEBUG(2, ("Rocman: calling MeshMotionTransferISS::run() with t:%e dt:%e.\n", t, dt));
   // fomular:  Vm = (un-un-1)/deltaT + (vsn - vsn-1) /2
   COM_call_function( RFC_interpolate, &s_u_hdl, &f_u_hdl);
   COM_call_function( RFC_interpolate, &s_vs_hdl, &f_vs_hdl);
   COM_call_function( RocBlas::sub, &f_u_hdl, &f_uold_hdl, &f_utmp_hdl);
   COM_call_function( RocBlas::div_scalar, &f_utmp_hdl, &dt, &f_utmp_hdl);
   COM_call_function( RocBlas::sub, &f_vs_hdl, &f_vsold_hdl, &f_vtmp_hdl);
   double half = 0.5;
   COM_call_function( RocBlas::mul_scalar, &f_vtmp_hdl, &half, &f_vtmp_hdl);
   COM_call_function( RocBlas::add, &f_utmp_hdl, &f_vtmp_hdl, &f_vm_hdl);
   // save copies
   COM_call_function( RocBlas::copy, &f_u_hdl, &f_uold_hdl);
   COM_call_function( RocBlas::copy, &f_vs_hdl, &f_vsold_hdl);
 }
Member Data Documentation
int MeshMotionTransferISS::f_u_hdl private
Definition at line 139 of file transfer_actions.h.
Referenced by init(), and run().
int MeshMotionTransferISS::f_uold_hdl private
Definition at line 140 of file transfer_actions.h.
Referenced by init(), and run().
int MeshMotionTransferISS::f_utmp_hdl private
Definition at line 140 of file transfer_actions.h.
Referenced by init(), and run().
int MeshMotionTransferISS::f_vm_hdl private
Definition at line 138 of file transfer_actions.h.
Referenced by init(), and run().
std::string MeshMotionTransferISS::f_vm_str private
Definition at line 137 of file transfer_actions.h.
Referenced by MeshMotionTransferISS().
int MeshMotionTransferISS::f_vs_hdl private
Definition at line 139 of file transfer_actions.h.
Referenced by init(), and run().
int MeshMotionTransferISS::f_vsold_hdl private
Definition at line 140 of file transfer_actions.h.
Referenced by init(), and run().
int MeshMotionTransferISS::f_vtmp_hdl private
Definition at line 140 of file transfer_actions.h.
Referenced by init(), and run().
int MeshMotionTransferISS::RFC_interpolate private
Definition at line 141 of file transfer_actions.h.
Referenced by init(), and run().
int MeshMotionTransferISS::s_u_hdl private
Definition at line 138 of file transfer_actions.h.
Referenced by init(), and run().
std::string MeshMotionTransferISS::s_u_str private
Definition at line 137 of file transfer_actions.h.
int MeshMotionTransferISS::s_vs_hdl private
Definition at line 138 of file transfer_actions.h.
Referenced by init(), and run().
std::string MeshMotionTransferISS::s_vs_str private
Definition at line 137 of file transfer_actions.h.
The documentation for this class was generated from the following files:
transfer_actions.h
transfer_actions.C