IMPACT: Neutral_Reader Class Reference
Neutral_Reader Class Reference
Detailed Description
Definition at line 22 of file Neutral_Reader.h.
#include <Neutral_Reader.h>
Public Member Functions
Neutral_Reader ()
int read_mesh (const char *fname, const std::string &wname)
Private Types
enum { MAXLEN =255 }
Private Member Functions
void get_nextline (std::istream &is, char *str)
void read_pane_coors (std::istream &is, const std::string &wname, int nn)
void read_pane_elems (std::istream &is, const std::string &wname, int ne)
Private Attributes
char buf [MAXLEN+1]
Member Enumeration Documentation
anonymous enum private
Enumerator
MAXLEN
Definition at line 110 of file Neutral_Reader.h.
 {MAXLEN=255};
Constructor & Destructor Documentation
Neutral_Reader::Neutral_Reader () inline
Definition at line 25 of file Neutral_Reader.h.
 {}
Member Function Documentation
void Neutral_Reader::get_nextline (std::istream & is, char * str) inline private
Definition at line 71 of file Neutral_Reader.h.
References MAXLEN.
Referenced by read_mesh(), read_pane_coors(), and read_pane_elems().
{
     str[0] = '\0';
     if ( is.eof()) { return; }
     is.getline( str, MAXLEN);
   }
int Neutral_Reader::read_mesh (const char * fname, const std::string & wname) inline
Definition at line 29 of file Neutral_Reader.h.
References buf, COM_get_window_handle(), COM_new_window(), get_nextline(), read_pane_coors(), and read_pane_elems().
Referenced by main().
{
     std::ifstream is( fname);
     if ( is == NULL) {
       std::cerr << "Error: Could not open file " << fname << std::endl;
       exit(-1);
     }
     // Create the window if not yet exist
     int h=COM_get_window_handle(wname.c_str());
     if ( h<=0) COM_new_window( wname.c_str());
     std::cout << "Reading file " << fname << std::endl;
     // Search for NUMNP
     do {
       get_nextline( is, buf);
     } while ( !is.eof() && std::string(buf).find( "NUMNP")==std::string::npos);
     std::cerr << "Buf is now \"" << buf << "\" before getting nn" << std::endl;
     get_nextline( is, buf);
     int t1, t2, t3, t4, nn, ne;
     std::sscanf( buf, "%d %d %d %d %d %d", &nn, &ne, &t1, &t2, &t3, &t4);
     // Search for NODAL COORDINAES
     do {
       get_nextline( is, buf);
     } while ( !is.eof() && std::string(buf).find( "NODAL")==std::string::npos);
     std::cout << "Reading " << nn << " nodes and "
               << ne << " triangles " << std::endl;
     read_pane_coors( is, wname, nn);
     // Search for ELEMENTS
     do {
       get_nextline( is, buf);
     } while ( !is.eof() && std::string(buf).find( "ELEMENTS")==std::string::npos);
     read_pane_elems( is, wname, ne);
     return 1;
   }
void Neutral_Reader::read_pane_coors (std::istream & is, const std::string & wname, int nn) inline private
Definition at line 78 of file Neutral_Reader.h.
References buf, COM_allocate_array(), COM_assertion, COM_set_size(), and get_nextline().
Referenced by read_mesh().
{
     COM_set_size( (wname+".nc").c_str(), 1, nn);
     SURF::Point_3<double> *ps;
     COM_allocate_array( (wname+".nc").c_str(), 1, &(void*&)ps);
     for ( int i=0; i<nn; ++i) {
       get_nextline( is, buf);
       int t1;
       std::sscanf( buf, "%d %lf %lf %lf", &t1, &ps[i][0], &ps[i][1], &ps[i][2]);
       COM_assertion( t1==i+1);
     }
   }
void Neutral_Reader::read_pane_elems (std::istream & is, const std::string & wname, int ne) inline private
Definition at line 93 of file Neutral_Reader.h.
References buf, COM_allocate_array(), COM_assertion, COM_set_size(), and get_nextline().
Referenced by read_mesh().
{
     // Note: Only supports triangular meshes now.
     COM_set_size( (wname+".:t3:").c_str(), 1, ne);
     SURF::Vector_3<int> *es;
     COM_allocate_array( (wname+".:t3:").c_str(), 1, &(void*&)es);
     for (int i=0; i<ne; ++i) {
       int t1, t2, t3;
       get_nextline( is, buf);
       std::sscanf( buf, "%d %d %d %d %d %d", &t1, &t2, &t3,
                    &es[i][0], &es[i][1], &es[i][2]);
       COM_assertion( t1 == i+1 && t2==3 && t3==3);
     }
   }
Member Data Documentation
char Neutral_Reader::buf[MAXLEN+1] private
Definition at line 111 of file Neutral_Reader.h.
Referenced by read_mesh(), read_pane_coors(), and read_pane_elems().
The documentation for this class was generated from the following file:
Neutral_Reader.h