IMPACT: In_place_list< T, managed > Class Template Reference
In_place_list< T, managed > Class Template Reference
Detailed Description
template<class T, bool managed = false>
class In_place_list< T, managed >
Definition at line 28 of file In_place_list.h.
#include <In_place_list.h>
Public Types
typedef T value_type
typedef T * pointer
typedef const T * const_pointer
typedef T & reference
typedef const T & const_reference
typedef std::size_t size_type
typedef std::ptrdiff_t difference_type
typedef
_In_place_list_iterator< T > iterator
typedef
_In_place_list_iterator< const
T > const_iterator
typedef std::reverse_iterator
< iterator > reverse_iterator
typedef std::reverse_iterator
< const_iterator > const_reverse_iterator
typedef In_place_list< T, managed > Self
Public Member Functions
In_place_list (int d=0)
In_place_list (const Self &x)
~In_place_list ()
void set_dimension (int d)
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
bool empty () const
size_type size () const
size_type max_size () const
reference front ()
const_reference front () const
reference back ()
const_reference back () const
iterator insert (iterator position, T &x)
iterator insert (T *pos, T &x)
void push_front (T &x)
void push_back (T &x)
void insert (T *pos, size_type n)
void insert (T *pos, size_type n, const T &x=T())
template<class InputIterator >
void insert (iterator pos, InputIterator first, InputIterator last)
template<class InputIterator >
void insert (T *pos, InputIterator first, InputIterator last)
void insert (T *pos, const T *first, const T *last)
void erase (iterator i)
void erase (T *pos)
void pop_front ()
void pop_back ()
void erase (iterator first, iterator last)
void erase (T *first, T *last)
void clear ()
Protected Member Functions
T * get_node ()
T * get_node (const T &t)
void put_node (T *p)
Protected Attributes
T * node
std::size_t length
int dim
Member Typedef Documentation
template<class T , bool managed = false> typedef _In_place_list_iterator<const T> In_place_list< T, managed >::const_iterator
Definition at line 107 of file In_place_list.h.
template<class T , bool managed = false> typedef const T* In_place_list< T, managed >::const_pointer
Definition at line 100 of file In_place_list.h.
template<class T , bool managed = false> typedef const T& In_place_list< T, managed >::const_reference
Definition at line 102 of file In_place_list.h.
template<class T , bool managed = false> typedef std::reverse_iterator<const_iterator> In_place_list< T, managed >::const_reverse_iterator
Definition at line 110 of file In_place_list.h.
template<class T , bool managed = false> typedef std::ptrdiff_t In_place_list< T, managed >::difference_type
Definition at line 104 of file In_place_list.h.
template<class T , bool managed = false> typedef _In_place_list_iterator<T> In_place_list< T, managed >::iterator
Definition at line 106 of file In_place_list.h.
template<class T , bool managed = false> typedef T* In_place_list< T, managed >::pointer
Definition at line 99 of file In_place_list.h.
template<class T , bool managed = false> typedef T& In_place_list< T, managed >::reference
Definition at line 101 of file In_place_list.h.
template<class T , bool managed = false> typedef std::reverse_iterator<iterator> In_place_list< T, managed >::reverse_iterator
Definition at line 109 of file In_place_list.h.
template<class T , bool managed = false> typedef In_place_list<T,managed> In_place_list< T, managed >::Self
Definition at line 112 of file In_place_list.h.
template<class T , bool managed = false> typedef std::size_t In_place_list< T, managed >::size_type
Definition at line 103 of file In_place_list.h.
template<class T , bool managed = false> typedef T In_place_list< T, managed >::value_type
Definition at line 98 of file In_place_list.h.
Constructor & Destructor Documentation
template<class T , bool managed = false> In_place_list< T, managed >::In_place_list (int d = 0) inline explicit
Definition at line 115 of file In_place_list.h.
References In_place_list< T, managed >::dim, In_place_list< T, managed >::get_node(), and In_place_list< T, managed >::node.
                                    : length(0), dim(d) {
     // creats an empty list.
     node = get_node();
     (*node).next_link[dim] = node;
     (*node).prev_link[dim] = node;
   }
template<class T , bool managed = false> In_place_list< T, managed >::In_place_list (const Self & x) inline
Definition at line 121 of file In_place_list.h.
References In_place_list< T, managed >::begin(), In_place_list< T, managed >::dim, In_place_list< T, managed >::end(), In_place_list< T, managed >::get_node(), In_place_list< T, managed >::insert(), and In_place_list< T, managed >::node.
                                : length(0), dim(x.dim) {
     node = get_node();
     (*node).next_link[dim] = node;
     (*node).prev_link[dim] = node;
     insert(begin(), x.begin(), x.end());
   }
template<class T , bool managed = false> In_place_list< T, managed >::~In_place_list () inline
Definition at line 128 of file In_place_list.h.
References In_place_list< T, managed >::begin(), In_place_list< T, managed >::end(), In_place_list< T, managed >::erase(), In_place_list< T, managed >::node, and In_place_list< T, managed >::put_node().
                    {
     erase(begin(), end());
     put_node(node);
   }
Member Function Documentation
template<class T , bool managed = false> reference In_place_list< T, managed >::back () inline
Definition at line 155 of file In_place_list.h.
References In_place_list< T, managed >::dim, and In_place_list< T, managed >::node.
Referenced by Overlay::get_next_inode_ccw(), Overlay::get_next_inode_cw(), Overlay::insert_node_in_blue_edge(), Overlay::project_adjacent_green_vertices(), and Overlay::verify_inode().
 { return *node->prev_link[dim]; }
template<class T , bool managed = false> const_reference In_place_list< T, managed >::back () const inline
Definition at line 156 of file In_place_list.h.
References In_place_list< T, managed >::dim, and In_place_list< T, managed >::node.
 { return *node->prev_link[dim]; }
template<class T , bool managed = false> iterator In_place_list< T, managed >::begin () inline
Definition at line 137 of file In_place_list.h.
References In_place_list< T, managed >::dim, and In_place_list< T, managed >::node.
Referenced by Overlay::associate_green_vertices(), In_place_list< T, managed >::clear(), In_place_list< T, managed >::front(), Overlay::get_inodes_of_face(), In_place_list< T, managed >::In_place_list(), Overlay::intersect_blue_with_green(), In_place_list< T, managed >::pop_front(), In_place_list< T, managed >::push_front(), In_place_list< T, managed >::rend(), Overlay::sort_on_green_edges(), and In_place_list< T, managed >::~In_place_list().
 { return iterator(node->next_link[dim],dim); }
template<class T , bool managed = false> const_iterator In_place_list< T, managed >::begin () const inline
Definition at line 138 of file In_place_list.h.
References In_place_list< T, managed >::dim, and In_place_list< T, managed >::node.
 { return const_iterator(node->next_link[dim],dim); }
template<class T , bool managed = false> void In_place_list< T, managed >::clear () inline
Definition at line 220 of file In_place_list.h.
References In_place_list< T, managed >::begin(), In_place_list< T, managed >::end(), and In_place_list< T, managed >::erase().
 { erase( begin(), end()); }
template<class T , bool managed = false> bool In_place_list< T, managed >::empty () const inline
Definition at line 149 of file In_place_list.h.
References In_place_list< T, managed >::length.
Referenced by Overlay::associate_green_vertices(), Overlay::get_inodes_of_face(), Overlay::get_next_inode_ccw(), Overlay::get_next_inode_cw(), Overlay::insert_node_in_blue_edge(), Overlay::intersect_blue_with_green(), Overlay::project_adjacent_green_vertices(), Overlay::sort_on_green_edges(), and Overlay::verify_inode().
 { return length == 0; }
template<class T , bool managed = false> iterator In_place_list< T, managed >::end () inline
Definition at line 139 of file In_place_list.h.
References In_place_list< T, managed >::dim, and In_place_list< T, managed >::node.
Referenced by Overlay::associate_green_vertices(), In_place_list< T, managed >::clear(), Overlay::get_inodes_of_face(), In_place_list< T, managed >::In_place_list(), Overlay::intersect_blue_with_green(), In_place_list< T, managed >::pop_back(), In_place_list< T, managed >::push_back(), In_place_list< T, managed >::rbegin(), Overlay::sort_on_green_edges(), and In_place_list< T, managed >::~In_place_list().
 { return iterator(node,dim); }
template<class T , bool managed = false> const_iterator In_place_list< T, managed >::end () const inline
Definition at line 140 of file In_place_list.h.
References In_place_list< T, managed >::dim, and In_place_list< T, managed >::node.
 { return const_iterator(node,dim); }
template<class T , bool managed = false> void In_place_list< T, managed >::erase (iterator i) inline
Definition at line 197 of file In_place_list.h.
References In_place_list< T, managed >::dim, In_place_list< T, managed >::length, _In_place_list_iterator< T >::node, In_place_list< T, managed >::put_node(), and RFC_assertion.
Referenced by In_place_list< T, managed >::clear(), In_place_list< T, managed >::erase(), In_place_list< T, managed >::pop_back(), In_place_list< T, managed >::pop_front(), and In_place_list< T, managed >::~In_place_list().
{
     RFC_assertion( length > 0);
     (*((*i.node).prev_link[dim])).next_link[dim] = (*i.node).next_link[dim];
     (*((*i.node).next_link[dim])).prev_link[dim] = (*i.node).prev_link[dim];
     if (managed)
       put_node(i.node);
     --length;
   }
template<class T , bool managed = false> void In_place_list< T, managed >::erase (T * pos) inline
Definition at line 205 of file In_place_list.h.
References In_place_list< T, managed >::dim, and In_place_list< T, managed >::erase().
Referenced by In_place_list< T, managed >::erase().
 { erase( iterator( pos,dim)); }
template<class T , bool managed> void In_place_list< T, managed >::erase (iterator first, iterator last)
Definition at line 225 of file In_place_list.h.
{
   while (first != last)
     erase(first++);
 }
template<class T , bool managed = false> void In_place_list< T, managed >::erase (T * first, T * last) inline
Definition at line 216 of file In_place_list.h.
References In_place_list< T, managed >::dim, and In_place_list< T, managed >::erase().
{
     erase( iterator(first,dim), iterator(last,dim));
   }
template<class T , bool managed = false> reference In_place_list< T, managed >::front () inline
Definition at line 153 of file In_place_list.h.
References In_place_list< T, managed >::begin().
Referenced by Overlay::get_next_inode_ccw(), Overlay::get_next_inode_cw(), Overlay::insert_node_in_blue_edge(), Overlay::intersect_blue_with_green(), Overlay::project_adjacent_green_vertices(), and Overlay::verify_inode().
 { return *begin(); }
template<class T , bool managed = false> const_reference In_place_list< T, managed >::front () const inline
Definition at line 154 of file In_place_list.h.
References In_place_list< T, managed >::begin().
 { return *begin(); }
template<class T , bool managed = false> T* In_place_list< T, managed >::get_node () inline protected
Definition at line 93 of file In_place_list.h.
Referenced by In_place_list< T, managed >::In_place_list(), and In_place_list< T, managed >::insert().
 { return new T;}
template<class T , bool managed = false> T* In_place_list< T, managed >::get_node (const T & t) inline protected
Definition at line 94 of file In_place_list.h.
 { return new T(t);}
template<class T , bool managed = false> iterator In_place_list< T, managed >::insert (iterator position, T & x) inline
Definition at line 160 of file In_place_list.h.
References In_place_list< T, managed >::dim, In_place_list< T, managed >::length, and _In_place_list_iterator< T >::node.
Referenced by In_place_list< T, managed >::In_place_list(), In_place_list< T, managed >::insert(), In_place_list< T, managed >::push_back(), and In_place_list< T, managed >::push_front().
{
     x.next_link[dim] = position.node;
     x.prev_link[dim] = (*position.node).prev_link[dim];
     (*((*position.node).prev_link[dim])).next_link[dim] = &x;
     (*position.node).prev_link[dim] = &x;
     ++length;
     return iterator(&x,dim);
   }
template<class T , bool managed = false> iterator In_place_list< T, managed >::insert (T * pos, T & x) inline
Definition at line 168 of file In_place_list.h.
References In_place_list< T, managed >::dim, and In_place_list< T, managed >::insert().
{
     return insert( iterator(pos,dim), x);
   }
template<class T , bool managed = false> void In_place_list< T, managed >::insert (T * pos, size_type n) inline
Definition at line 175 of file In_place_list.h.
References In_place_list< T, managed >::dim, and In_place_list< T, managed >::insert().
Referenced by In_place_list< T, managed >::insert().
 { insert( iterator(pos,dim), n); }
template<class T , bool managed = false> void In_place_list< T, managed >::insert (T * pos, size_type n, const T & x = T()) inline
Definition at line 176 of file In_place_list.h.
References In_place_list< T, managed >::dim, and In_place_list< T, managed >::insert().
   { insert( iterator(pos,dim), n, x); }
template<class T , bool managed = false> template<class InputIterator > void In_place_list< T, managed >::insert (iterator pos, InputIterator first, InputIterator last) inline
Definition at line 180 of file In_place_list.h.
References In_place_list< T, managed >::get_node(), and In_place_list< T, managed >::insert().
{
     while (first != last)
       insert(pos, *get_node(*first++));
   }
template<class T , bool managed = false> template<class InputIterator > void In_place_list< T, managed >::insert (T * pos, InputIterator first, InputIterator last) inline
Definition at line 186 of file In_place_list.h.
References In_place_list< T, managed >::get_node(), and In_place_list< T, managed >::insert().
{
     while (first != last)
       insert(pos, *get_node(*first++));
   }
template<class T , bool managed = false> void In_place_list< T, managed >::insert (T * pos, const T * first, const T * last) inline
Definition at line 191 of file In_place_list.h.
References In_place_list< T, managed >::dim, and In_place_list< T, managed >::insert().
{
     insert( iterator(pos,dim), const_iterator(first,dim),
             const_iterator(last,dim));
   }
template<class T , bool managed = false> size_type In_place_list< T, managed >::max_size () const inline
Definition at line 151 of file In_place_list.h.
 { return size_type(-1); }
template<class T , bool managed = false> void In_place_list< T, managed >::pop_back () inline
Definition at line 209 of file In_place_list.h.
References In_place_list< T, managed >::end(), and In_place_list< T, managed >::erase().
Referenced by Overlay::insert_node_in_blue_edge().
                   {
     iterator tmp = end();
     erase(--tmp);
   }
template<class T , bool managed = false> void In_place_list< T, managed >::pop_front () inline
Definition at line 207 of file In_place_list.h.
References In_place_list< T, managed >::begin(), and In_place_list< T, managed >::erase().
Referenced by Overlay::insert_node_in_blue_edge(), and Overlay::intersect_blue_with_green().
 { erase(begin()); }
template<class T , bool managed = false> void In_place_list< T, managed >::push_back (T & x) inline
Definition at line 173 of file In_place_list.h.
References In_place_list< T, managed >::end(), and In_place_list< T, managed >::insert().
Referenced by Overlay::sort_on_green_edges().
 { insert(end(), x); }
template<class T , bool managed = false> void In_place_list< T, managed >::push_front (T & x) inline
Definition at line 171 of file In_place_list.h.
References In_place_list< T, managed >::begin(), and In_place_list< T, managed >::insert().
Referenced by Overlay::intersect_blue_with_green().
 { insert(begin(), x); }
template<class T , bool managed = false> void In_place_list< T, managed >::put_node (T * p) inline protected
Definition at line 95 of file In_place_list.h.
Referenced by In_place_list< T, managed >::erase(), and In_place_list< T, managed >::~In_place_list().
 { delete p;}
template<class T , bool managed = false> reverse_iterator In_place_list< T, managed >::rbegin () inline
Definition at line 142 of file In_place_list.h.
References In_place_list< T, managed >::end().
Referenced by Overlay::associate_green_vertices(), Overlay::get_inodes_of_face(), and Overlay::sort_on_green_edges().
 { return reverse_iterator(end()); }
template<class T , bool managed = false> const_reverse_iterator In_place_list< T, managed >::rbegin () const inline
Definition at line 143 of file In_place_list.h.
References In_place_list< T, managed >::end().
   { return const_reverse_iterator(end()); }
template<class T , bool managed = false> reverse_iterator In_place_list< T, managed >::rend () inline
Definition at line 145 of file In_place_list.h.
References In_place_list< T, managed >::begin().
Referenced by Overlay::associate_green_vertices(), Overlay::get_inodes_of_face(), and Overlay::sort_on_green_edges().
 { return reverse_iterator(begin()); }
template<class T , bool managed = false> const_reverse_iterator In_place_list< T, managed >::rend () const inline
Definition at line 146 of file In_place_list.h.
References In_place_list< T, managed >::begin().
   { return const_reverse_iterator(begin()); }
template<class T , bool managed = false> void In_place_list< T, managed >::set_dimension (int d) inline
Definition at line 133 of file In_place_list.h.
References In_place_list< T, managed >::dim.
 { dim = d; }
template<class T , bool managed = false> size_type In_place_list< T, managed >::size () const inline
Definition at line 150 of file In_place_list.h.
References In_place_list< T, managed >::length.
Referenced by Overlay::project_adjacent_green_vertices(), and Overlay::verify_inode().
 { return length; }
Member Data Documentation
template<class T , bool managed = false> int In_place_list< T, managed >::dim protected
Definition at line 91 of file In_place_list.h.
Referenced by In_place_list< T, managed >::back(), In_place_list< T, managed >::begin(), In_place_list< T, managed >::end(), In_place_list< T, managed >::erase(), In_place_list< T, managed >::In_place_list(), In_place_list< T, managed >::insert(), and In_place_list< T, managed >::set_dimension().
template<class T , bool managed = false> std::size_t In_place_list< T, managed >::length protected
Definition at line 90 of file In_place_list.h.
Referenced by In_place_list< T, managed >::empty(), In_place_list< T, managed >::erase(), In_place_list< T, managed >::insert(), and In_place_list< T, managed >::size().
template<class T , bool managed = false> T* In_place_list< T, managed >::node protected
Definition at line 89 of file In_place_list.h.
Referenced by In_place_list< T, managed >::back(), In_place_list< T, managed >::begin(), In_place_list< T, managed >::end(), In_place_list< T, managed >::In_place_list(), and In_place_list< T, managed >::~In_place_list().
The documentation for this class was generated from the following file:
In_place_list.h