IMPACT: Node Class Reference
Node Class Reference
This class encapsulate a node over a window manifold.
Detailed Description
Definition at line 387 of file Manifold_2.h.
#include <Manifold_2.h>
Public Member Functions
Node ()
Default constructor.
Node (const Pane_manifold_2 *pm, int vid, Access_Mode mode=ACROSS_PANE)
Construct a Node object from a pane manifold and its node ID.
Halfedge halfedge () const
Get an incident halfedge originated from the node.
const Pane_manifold_2 * pane_manifold () const
Obtain the pane manifold that owns the edge.
const COM::Pane * pane () const
Obtain the owner Pane_manifold_2 of the node.
int id () const
Obtain the node ID within its Pane_manifold_2.
const Point_3< Real > & point () const
Obtain the coordinates of a node.
const void * addr (const COM::DataItem *attr) const
Obtain the address of an dataitem associated with the node.
const COM::DataItem * attr (const COM::DataItem *a) const
Obtain the dataitem on the parent pane of the node.
bool is_border () const
Is the node on the physical boundary?
bool is_isolated () const
Is the node isolated?
bool is_primary () const
Is the node a primary?
Node get_primary () const
Get the primary copy of the node.
bool coincide (const Node &n) const
Check whether the current node coincide with the given node.
bool operator== (const Node &n) const
Are two nodes the same?
bool operator!= (const Node &n) const
Are two nodes different?
bool operator< (const Node &n) const
Does the current node has a smaller ID then the given node?
Node ()
Default constructor.
Node (RFC_Pane_overlay *pm, int vid)
Construct a Node object from a pane manifold and its node ID.
HEdge halfedge_l () const
Get an incident halfedge destinated at the node.
HEdge halfedge_g () const
RFC_Pane_overlay * pane () const
Obtain the pane manifold that owns the node.
int id () const
Obtain the node ID within its RFC_Pane_overlay.
const Point_3 & point () const
Obtain the coordinates of a node.
bool is_border_l () const
bool is_border_g () const
bool is_isolated () const
bool is_primary () const
Node get_primary () const
bool operator== (const Node &v) const
bool operator!= (const Node &v) const
bool operator< (const Node &v) const
Protected Attributes
const Pane_manifold_2 * _pm
int _vID
Access_Mode _mode
RFC_Pane_overlay * _pm
Constructor & Destructor Documentation
Node::Node () inline
Definition at line 390 of file Manifold_2.h.
 : _pm(NULL), _vID(0), _mode( ACROSS_PANE) {}
Node::Node (const Pane_manifold_2 * pm, int vid, Access_Mode mode = ACROSS_PANE) inline
Definition at line 394 of file Manifold_2.h.
     : _pm( pm), _vID( vid), _mode( mode) {}
Node::Node () inline
Definition at line 38 of file HDS_overlay.h.
 : _pm(NULL), _vID(0) {}
Node::Node (RFC_Pane_overlay * pm, int vid) inline
Definition at line 41 of file HDS_overlay.h.
 : _pm( pm), _vID( vid) {}
Member Function Documentation
const void * Node::addr (const COM::DataItem * attr) const
Note: This function can be slow O(log(#panes)) if the dataitem is not on the current pane.
Definition at line 1227 of file Manifold_2.C.
References _pm, _vID, attr(), COM_assertion_msg, COM_get_sizeof(), and Simple_manifold_2::pane().
Referenced by Halfedge::edge_average(), Halfedge::face_average(), Face::face_average(), and get_deformed_normal().
{
   COM_assertion_msg( a, "Unexpected NULL pointer");
   COM_assertion_msg( a->is_nodal(), "Expect a nodal dataitem");
   const COM::DataItem *attr;
   const COM::Pane *pn = _pm->pane();
   int pid = pn->id();
   if ( a->pane()->id() == pid)
     attr = a;
   else {
     if ( a->window() != pn->window()) {
       pn = &a->window()->pane( pid);
       COM_assertion_msg( pn, "Pane does not exist");
     }
     attr=pn->dataitem( a->id());
     COM_assertion_msg( attr, "DataItem does not exist");
   }
   return ((const char*)attr->pointer()) +
     COM_get_sizeof( attr->data_type(), attr->stride()*(_vID-1));
 }
const COM::DataItem* Node::attr (const COM::DataItem * a) const inline
It takes O(log(#panes)) time.
Definition at line 422 of file Manifold_2.h.
References _pm, COM_assertion_msg, and Simple_manifold_2::pane().
Referenced by addr(), and testobject::associate_pointer().
{
     COM_assertion_msg( a, "Unexpected NULL pointer");
     return a->window()->pane( _pm->pane()->id()).dataitem(a->id());
   }
bool Node::coincide (const Node & n) const inline
Definition at line 440 of file Manifold_2.h.
References _mode, _pm, _vID, and Pane_manifold_2::get_primary().
   { return _pm->get_primary( _vID, _mode) == n._pm->get_primary( n._vID, n._mode); }
Node Node::get_primary () const inline
Node Node::get_primary () const inline
Definition at line 437 of file Manifold_2.h.
References _mode, _pm, _vID, and Pane_manifold_2::get_primary().
Referenced by Window_manifold_2::assign_global_nodeIDs(), halfedge_g(), HDS_accessor::is_feature_0(), HDS_accessor::is_on_feature(), RFC_Window_overlay::is_same_node(), and RFC_Window_overlay::print_features().
 { return _pm->get_primary( _vID, _mode); }
Halfedge Node::halfedge () const inline
If the node is on the physical boundary, the halfedge must be a physical border edge.
Definition at line 767 of file Manifold_2.h.
References _mode, _pm, _vID, Pane_manifold_2::get_counterpart(), Simple_manifold_2::get_incident_edge(), Simple_manifold_2::get_incident_real_edge(), Halfedge::id(), Halfedge::opposite(), Halfedge::pane_manifold(), Halfedge::prev(), REAL_PANE, and WHOLE_PANE.
Referenced by Window_manifold_2::determine_primaries(), and is_border().
 {
   Edge_ID eID;
   switch ( _mode) {
   case REAL_PANE:
     eID = _pm->get_incident_real_edge( _vID); break;
   case WHOLE_PANE:
     eID = _pm->get_incident_edge( _vID); break;
   default: {
     eID =_pm->get_incident_real_edge( _vID);
     // the current node (vertex) is in general the origin of the edge or
     // the edge center, unless the node is isolated.
     if ( eID.is_border()) {
       //      Halfedge h=_pm->get_counterpart( eID);
       //      if ( h.pane_manifold()) return h;
       Halfedge h=_pm->get_counterpart( eID), h0=h;
       if (h.pane_manifold() && !h.id().is_border()) {
         do {
           if ( h.id().is_border()) break;
         } while ( (h=h.prev().opposite()) != h0);
         return h;
       }
     }
   }
   }
   return Halfedge(_pm, eID, _mode);
 }
HEdge Node::halfedge_g () const inline
Definition at line 517 of file RFC_Window_overlay.h.
References _pm, _vID, Simple_manifold_2::get_incident_real_edge(), Simple_manifold_2::get_opposite_real_edge(), and get_primary().
Referenced by RFC_Window_overlay::check_false_strong_1(), RFC_Window_overlay::comp_angle_defect(), Overlay::get_green_parent(), is_border_g(), RFC_Window_overlay::is_strong_ad(), Overlay::match_features_0(), and RFC_Window_overlay::print_features().
{
   Edge_ID eID =_pm->get_incident_real_edge( _vID);
   // the current node (vertex) is in general the origin of the edge or
   // the edge center, unless the node is isolated.
   if (!eID.is_border())
     return HEdge( _pm, _pm->get_opposite_real_edge(eID));
   HEdge h(_pm, _pm->get_opposite_real_edge( eID)), h0=h;
   do {
     if (h.is_border_l()) break;
   } while ( (h=h.next_g().opposite_g()) != h0);
   assert( h.destination_g() == get_primary());
   return h;
 }
HEdge Node::halfedge_l () const inline
If the node is on the physical boundary, the halfedge must be a physical border edge.
Definition at line 509 of file RFC_Window_overlay.h.
References _pm, _vID, Simple_manifold_2::get_incident_real_edge(), Simple_manifold_2::get_opposite_real_edge(), and Simple_manifold_2::get_prev_real_edge().
Referenced by RFC_Pane_overlay::determine_counterparts(), RFC_Pane_overlay::evaluate_normals(), Overlay::get_green_parent(), RFC_Pane_overlay::get_primary(), is_border_l(), RFC_Pane_overlay::is_primary(), and Overlay::sort_on_green_edges().
{
   Edge_ID eid = _pm->get_incident_real_edge( _vID);
   if (!eid.is_border())
     return HEdge( _pm, _pm->get_opposite_real_edge(eid));
   else
     return HEdge( _pm, _pm->get_prev_real_edge( eid));
 }
int Node::id () const inline
Definition at line 52 of file HDS_overlay.h.
References _vID.
 { return _vID; }
int Node::id () const inline
Definition at line 409 of file Manifold_2.h.
References _vID.
Referenced by Window_manifold_2::assign_global_nodeIDs(), RFC_Pane_overlay::get_index(), RFC_Pane_overlay::get_lid(), and Vertex_set::Vertex_set().
 { return _vID; }
bool Node::is_border () const inline
Definition at line 765 of file Manifold_2.h.
References halfedge(), and Halfedge::is_border().
 { return halfedge().is_border(); }
bool Node::is_border_g () const inline
Definition at line 540 of file RFC_Window_overlay.h.
References halfedge_g(), and HEdge::is_border_g().
Referenced by Overlay::intersect_blue_with_green(), Overlay_primitives::snap_blue_ridge_edge(), and Overlay_primitives::snap_blue_ridge_vertex().
 { return halfedge_g().is_border_g(); }
bool Node::is_border_l () const inline
Definition at line 538 of file RFC_Window_overlay.h.
References halfedge_l(), and HEdge::is_border_l().
Referenced by Overlay::count_subnodes(), RFC_Pane_overlay::get_primary(), RFC_Pane_overlay::is_primary(), RFC_Window_overlay::is_same_node(), and Overlay::number_a_subnode().
 { return halfedge_l().is_border_l(); }
bool Node::is_isolated () const inline
bool Node::is_isolated () const inline
Definition at line 431 of file Manifold_2.h.
References _pm, _vID, and Simple_manifold_2::is_isolated_node().
Referenced by Window_manifold_2::determine_primaries(), RFC_Pane_overlay::evaluate_normals(), Overlay::get_green_parent(), RFC_Window_overlay::print_features(), and Overlay::sort_on_green_edges().
 { return _pm->is_isolated_node( _vID); }
bool Node::is_primary () const inline
bool Node::is_primary () const inline
Definition at line 434 of file Manifold_2.h.
References _mode, _pm, _vID, and Pane_manifold_2::is_primary().
Referenced by Overlay::get_green_parent(), HDS_accessor::get_inode(), RFC_Pane_overlay::is_feature_0(), RFC_Window_overlay::is_feature_0(), RFC_Pane_overlay::is_on_feature(), RFC_Window_overlay::is_on_feature(), RFC_Window_overlay::set_feature_0(), HDS_accessor::set_inode(), RFC_Window_overlay::set_on_feature(), and Overlay::sort_on_green_edges().
 { return _pm->is_primary( _vID, _mode); }
bool Node::operator!= (const Node & v) const inline
Definition at line 70 of file HDS_overlay.h.
References _pm, and _vID.
   { return _pm != v._pm || _vID != v._vID; }
bool Node::operator!= (const Node & n) const inline
Definition at line 448 of file Manifold_2.h.
References _pm, and _vID.
   { return _pm != n._pm || _vID != n._vID; }
bool Node::operator< (const Node & v) const inline
bool Node::operator< (const Node & n) const inline
Definition at line 452 of file Manifold_2.h.
References _pm, _vID, and Simple_manifold_2::pane().
{
     return _pm->pane()->id() < n._pm->pane()->id() ||
       _pm == n._pm && _vID < n._vID;
   }
bool Node::operator== (const Node & v) const inline
Definition at line 67 of file HDS_overlay.h.
References _pm, and _vID.
   { return _pm == v._pm && _vID == v._vID; }
bool Node::operator== (const Node & n) const inline
Definition at line 444 of file Manifold_2.h.
References _pm, and _vID.
   { return _pm == n._pm && _vID == n._vID; }
RFC_Pane_overlay* Node::pane () const inline
Definition at line 49 of file HDS_overlay.h.
References _pm.
 { return _pm; }
const COM::Pane* Node::pane () const inline
Definition at line 405 of file Manifold_2.h.
References _pm, and Simple_manifold_2::pane().
Referenced by Window_manifold_2::assign_global_nodeIDs(), RFC_Window_overlay::check_false_strong_1(), RFC_Window_overlay::comp_angle_defect(), RFC_Window_overlay::cos_edge_angle(), Overlay::get_green_parent(), HDS_accessor::get_inode(), RFC_Pane_overlay::get_normal(), RFC_Window_overlay::identify_features_0(), HDS_accessor::is_feature_0(), RFC_Window_overlay::is_feature_0(), HDS_accessor::is_on_feature(), RFC_Window_overlay::is_on_feature(), Overlay::match_features_0(), Overlay::overlay_init(), RFC_Window_overlay::print_features(), RFC_Window_overlay::remove_feature_0(), RFC_Window_overlay::set_feature_0(), HDS_accessor::set_inode(), and RFC_Window_overlay::set_on_feature().
   { if ( _pm) return _pm->pane(); else return NULL; }
const Pane_manifold_2* Node::pane_manifold () const inline
Definition at line 402 of file Manifold_2.h.
References _pm.
 { return _pm; }
const Point_3& Node::point () const inline
const Point_3 & Node::point () const inline
Definition at line 412 of file Manifold_2.h.
References _pm, _vID, and Simple_manifold_2::pane().
Referenced by RFC_Window_overlay::evaluate_normals(), get_deformed_normal(), Overlay_primitives::get_point(), RFC_Window_overlay::get_tangent(), Overlay::insert_node_in_blue_edge(), Overlay::intersect_blue_with_green(), Overlay::intersect_link(), Overlay::intersect_link_helper(), Overlay::match_features_0(), RFC_Window_overlay::Feature_0::operator<(), RFC_Window_overlay::Feature_0::point(), RFC_Window_overlay::print_features(), Overlay::project_adjacent_green_vertices(), Overlay::sq_length(), and Halfedge::tangent().
   { return (const Point_3<Real>&)_pm->pane()->coordinates()[ 3*_vID-3]; }
Member Data Documentation
Access_Mode Node::_mode protected
Definition at line 460 of file Manifold_2.h.
Referenced by coincide(), get_primary(), halfedge(), and is_primary().
RFC_Pane_overlay* Node::_pm protected
Definition at line 75 of file HDS_overlay.h.
const Pane_manifold_2* Node::_pm protected
Definition at line 458 of file Manifold_2.h.
Referenced by addr(), attr(), coincide(), get_primary(), halfedge(), halfedge_g(), halfedge_l(), is_isolated(), is_primary(), operator!=(), operator<(), operator==(), pane(), pane_manifold(), and point().
int Node::_vID protected
Definition at line 459 of file Manifold_2.h.
Referenced by addr(), coincide(), get_primary(), halfedge(), halfedge_g(), halfedge_l(), id(), is_isolated(), is_primary(), operator!=(), operator<(), operator==(), and point().
The documentation for this class was generated from the following files:
Manifold_2.h
HDS_overlay.h
Manifold_2.C
RFC_Window_overlay.h