IMPACT: SMF_Reader Class Reference
SMF_Reader Class Reference
Detailed Description
Definition at line 23 of file SMF_Reader.h.
#include <SMF_Reader.h>
Public Member Functions
SMF_Reader ()
int read_mesh (const char *fname, const std::string &wname)
Private Types
enum { MAXLEN =255 }
Private Member Functions
void get_nextline (std::istream &is, char *str)
void read_pane_coors (std::istream &is, const std::string &wname)
void read_pane_elems (std::istream &is, const std::string &wname)
Private Attributes
char buf [MAXLEN+1]
Member Enumeration Documentation
anonymous enum private
Enumerator
MAXLEN
Definition at line 123 of file SMF_Reader.h.
 {MAXLEN=255};
Constructor & Destructor Documentation
SMF_Reader::SMF_Reader () inline
Definition at line 26 of file SMF_Reader.h.
 {}
Member Function Documentation
void SMF_Reader::get_nextline (std::istream & is, char * str) inline private
Definition at line 50 of file SMF_Reader.h.
References MAXLEN.
Referenced by read_pane_coors(), and read_pane_elems().
{
     char  accpet[]={'0','1','2','3','4','5','6','7','8','9',
                     '.','+','-','e','E'};
     do {
       if ( is.eof()) { str[0] = '\0'; return; }
       str[0] = '\1'; str[1] = '\0';
       is.getline( str, MAXLEN);
       if ( str[0] == '\1') return;
     } while ( (str[0]!='v' && str[0]!='f') || strpbrk( str,accpet)==NULL);
   }
int SMF_Reader::read_mesh (const char * fname, const std::string & wname) inline
Definition at line 30 of file SMF_Reader.h.
References COM_get_window_handle(), COM_new_window(), read_pane_coors(), and read_pane_elems().
Referenced by main().
{
     std::ifstream is( fname);
     if ( is == NULL) {
       std::cerr << "Error: Could not open file " << fname << std::endl;
       exit(-1);
     }
     // Create the window if not yet exist
     int h=COM_get_window_handle(wname.c_str());
     if ( h<=0) COM_new_window( wname.c_str());
     std::cout << "Reading file " << fname << std::endl;
     read_pane_coors( is, wname);
     read_pane_elems( is, wname);
     return 1;
   }
void SMF_Reader::read_pane_coors (std::istream & is, const std::string & wname) inline private
Definition at line 63 of file SMF_Reader.h.
References buf, COM_allocate_array(), COM_assertion_msg, COM_set_size(), and get_nextline().
Referenced by read_mesh().
{
     std::vector<SURF::Point_3<double> >  coors;
     int n=0;
     for (;;) {
       get_nextline( is, buf);
       if ( buf[0] == 'v') {
         if ( buf[1] == 't' || buf[1] == 'n') continue;
         SURF::Point_3<double> p;
         std::sscanf( &buf[2], "%lf %lf %lf", &p[0], &p[1], &p[2]);
         coors.push_back( p);
         ++n;
       }
       else
         break;
     }
     COM_assertion_msg( n>0, "Did not find any nodes");
     std::cout << "Read in " << n << " nodes" << std::endl;
     COM_set_size( (wname+".nc").c_str(), 1, n);
     SURF::Point_3<double> *p;
     COM_allocate_array( (wname+".nc").c_str(), 1, &(void*&)p);
     std::copy( coors.begin(), coors.end(), p);
   }
void SMF_Reader::read_pane_elems (std::istream & is, const std::string & wname) inline private
Definition at line 93 of file SMF_Reader.h.
References buf, COM_allocate_array(), COM_assertion_msg, COM_set_size(), and get_nextline().
Referenced by read_mesh().
{
     std::vector<SURF::Vector_3<int> >  elems;
     // When entering this routine, buf[0] should start with 'f'
     int n=0;
     for (;;) {
       if ( buf[0] == 'f') {
         if ( buf[1] != 't' && buf[1] != 'n') {
           SURF::Vector_3<int> p;
           std::sscanf( &buf[2], "%d %d %d", &p[0], &p[1], &p[2]);
           elems.push_back( p);
           ++n;
         }
         get_nextline( is, buf);
       }
       else break;
     }
     COM_assertion_msg( n>0, "Did not find any faces");
     std::cout << "Read in " << n << " faces" << std::endl;
     COM_set_size( (wname+".:t3:").c_str(), 1, n);
     SURF::Vector_3<int> *p;
     COM_allocate_array( (wname+".:t3:").c_str(), 1, &(void*&)p);
     std::copy( elems.begin(), elems.end(), p);
   }
Member Data Documentation
char SMF_Reader::buf[MAXLEN+1] private
Definition at line 124 of file SMF_Reader.h.
Referenced by read_pane_coors(), and read_pane_elems().
The documentation for this class was generated from the following file:
SMF_Reader.h