IMPACT: INode Class Reference
INode Class Reference
Detailed Description
Definition at line 188 of file HDS_overlay.h.
#include <HDS_overlay.h>
Public Types
typedef INode Self
typedef In_place_list_base
< INode, 2 > Base
Public Member Functions
INode ()
~INode ()
bool operator== (const INode &x)
const Point_2S & nat_coor (const int color) const
void nat_coor (const int color, Point_2 &p) const
void set_parent (HEdge h, const Point_2 &p, int color)
int id () const
void set_id (int i)
Parent_type parent_type (const int color) const
Parent_type blue_parent_type () const
Parent_type green_parent_type () const
HEdge halfedge (const int color) const
Protected Attributes
Host_face bp
Host_face gp
Point_2S b_nc
Point_2S g_nc
int _id
Private Member Functions
Parent_type pt (const Point_2 &p)
Private Member Functions inherited from In_place_list_base< INode, 2 >
In_place_list_base ()
Additional Inherited Members
Private Attributes inherited from In_place_list_base< INode, 2 >
INode * next_link [n]
INode * prev_link [n]
Member Typedef Documentation
typedef In_place_list_base<INode,2> INode::Base
Definition at line 191 of file HDS_overlay.h.
typedef INode INode::Self
Definition at line 190 of file HDS_overlay.h.
Constructor & Destructor Documentation
INode::INode () inline
Definition at line 203 of file HDS_overlay.h.
 : _id(-1) {}
INode::~INode () inline
Definition at line 204 of file HDS_overlay.h.
References bp, gp, and RFC_assertion_code.
 { RFC_assertion_code(bp=gp=Host_face()); }
Member Function Documentation
Parent_type INode::blue_parent_type () const inline
Definition at line 236 of file HDS_overlay.h.
References bp, and Host_face::parent_type().
 { return bp.parent_type(); }
Parent_type INode::green_parent_type () const inline
Definition at line 237 of file HDS_overlay.h.
References gp, and Host_face::parent_type().
 { return gp.parent_type(); }
HEdge INode::halfedge (const int color) const inline
Definition at line 239 of file HDS_overlay.h.
References BLUE, bp, gp, GREEN, Host_face::halfedge(), and RFC_assertion.
Referenced by Overlay::convert_nat_coordinates(), Overlay::count_subnodes(), Overlay::get_edge_parent(), Overlay::get_nat_coor(), Overlay::get_next_inode_ccw(), Overlay::get_next_inode_cw(), Overlay::insert_edge_into_queue(), Overlay::insert_node_in_blue_edge(), Overlay::insert_node_in_green_edge(), Overlay::intersect_blue_with_green(), Overlay::number_a_subnode(), Overlay::project_adjacent_green_vertices(), Overlay::sort_on_green_edges(), Overlay::verify_inode(), Overlay::write_inodes_tec(), and Overlay::write_inodes_vec().
{
     if ( color == BLUE) { return bp.halfedge(); }
     else { RFC_assertion( color == GREEN); return gp.halfedge(); }
   }
int INode::id () const inline
Definition at line 229 of file HDS_overlay.h.
References _id.
Referenced by Overlay::get_subnode_copies(), Overlay::get_subnode_id(), and Overlay::set_subnode_id().
 { return _id; }
const Point_2S& INode::nat_coor (const int color) const inline
Definition at line 209 of file HDS_overlay.h.
References b_nc, BLUE, g_nc, GREEN, and RFC_assertion.
Referenced by Overlay::convert_nat_coordinates(), Overlay::get_edge_parent(), Overlay::get_nat_coor(), Overlay::insert_node_in_blue_edge(), Overlay::insert_node_in_green_edge(), Overlay::intersect_blue_with_green(), Overlay::write_inodes_tec(), and Overlay::write_inodes_vec().
{
     if ( color == BLUE) return b_nc;
     else { RFC_assertion(color == GREEN); return g_nc; }
   }
void INode::nat_coor (const int color, Point_2 & p) const inline
Definition at line 214 of file HDS_overlay.h.
References b_nc, BLUE, g_nc, GREEN, and RFC_assertion.
{
     if ( color == BLUE) { p[0]=b_nc[0]; p[1]=b_nc[1]; }
     else { RFC_assertion(color == GREEN); p[0]=g_nc[0]; p[1]=g_nc[1]; }
   }
bool INode::operator== (const INode & x) inline
Definition at line 206 of file HDS_overlay.h.
References b_nc, bp, g_nc, and gp.
   { return ( b_nc == x.b_nc && g_nc == x.g_nc && bp == x.bp && gp == x.gp); }
Parent_type INode::parent_type (const int color) const inline
Definition at line 232 of file HDS_overlay.h.
References BLUE, bp, gp, GREEN, Host_face::parent_type(), and RFC_assertion.
Referenced by Overlay::associate_green_vertices(), Overlay::convert_nat_coordinates(), Overlay::count_subnodes(), Overlay::get_edge_parent(), Overlay::get_nat_coor(), Overlay::get_next_inode_ccw(), Overlay::get_next_inode_cw(), Overlay::insert_edge_into_queue(), Overlay::insert_node_in_blue_edge(), Overlay::insert_node_in_green_edge(), Overlay::intersect_blue_with_green(), Overlay::number_a_subnode(), Overlay::project_adjacent_green_vertices(), Overlay::sort_on_green_edges(), and Overlay::verify_inode().
{
     if ( color == BLUE) { return bp.parent_type(); }
     else { RFC_assertion( color == GREEN); return gp.parent_type(); }
   }
Parent_type INode::pt (const Point_2 & p) inline private
Definition at line 245 of file HDS_overlay.h.
References PARENT_EDGE, PARENT_FACE, and PARENT_VERTEX.
Referenced by set_parent().
{
     if ( p[1] != 0) return PARENT_FACE;
     else if ( p[0] != 0) return PARENT_EDGE;
     else return PARENT_VERTEX;
   }
void INode::set_id (int i) inline
Definition at line 230 of file HDS_overlay.h.
References _id.
 { _id = i; }
void INode::set_parent (HEdge h, const Point_2 & p, int color) inline
Definition at line 219 of file HDS_overlay.h.
References b_nc, BLUE, bp, g_nc, gp, GREEN, pt(), and RFC_assertion.
Referenced by Overlay::insert_node_in_blue_edge(), Overlay::insert_node_in_green_edge(), Overlay::intersect_blue_with_green(), Overlay::match_features_0(), and Overlay::project_adjacent_green_vertices().
{
     if ( color == BLUE) {
       bp = Host_face( h, pt(p)); b_nc[0]=p[0]; b_nc[1]=p[1];
     }
     else {
       RFC_assertion( color == GREEN);
       gp = Host_face( h, pt(p)); g_nc[0]=p[0]; g_nc[1]=p[1];
     }
   }
Member Data Documentation
int INode::_id protected
Definition at line 200 of file HDS_overlay.h.
Referenced by id(), and set_id().
Point_2S INode::b_nc protected
Definition at line 198 of file HDS_overlay.h.
Referenced by nat_coor(), operator==(), and set_parent().
Host_face INode::bp protected
Definition at line 196 of file HDS_overlay.h.
Referenced by blue_parent_type(), halfedge(), operator==(), parent_type(), set_parent(), and ~INode().
Point_2S INode::g_nc protected
Definition at line 199 of file HDS_overlay.h.
Referenced by nat_coor(), operator==(), and set_parent().
Host_face INode::gp protected
Definition at line 197 of file HDS_overlay.h.
Referenced by green_parent_type(), halfedge(), operator==(), parent_type(), set_parent(), and ~INode().
The documentation for this class was generated from the following file:
HDS_overlay.h