IMPACT: RFC_Data< _Tag > Class Template Reference
RFC_Data< _Tag > Class Template Reference
Detailed Description
template<class _Tag>
class RFC_Data< _Tag >
Definition at line 24 of file RFC_Window_transfer.h.
#include <RFC_Window_transfer.h>
Public Types
typedef RFC_Data_const< _Tag > Base
typedef Vector_n Value
typedef Array_n Value_nonconst
typedef Array_n_const Value_const
typedef unsigned int Size
typedef _Tag Tag
Public Types inherited from RFC_Data_const< _Tag >
typedef Vector_n Value
typedef Array_n Value_nonconst
typedef Array_n_const Value_const
typedef unsigned int Size
typedef _Tag Tag
Public Member Functions
RFC_Data ()
RFC_Data (RFC_Window_transfer &win, const char *aname)
RFC_Data (COM::DataItem *a)
RFC_Data (int i, int d)
Value_nonconst get_value (RFC_Pane_transfer *p, int v)
Value_const get_value (const RFC_Pane_transfer *p, int v) const
void set_value (RFC_Pane_transfer *p, int v, const Value_const &vec)
Value_nonconst get_value (Real *buf, int v) const
Value_const get_value (const Real *buf, int v) const
void set_value (Real *buf, int v, const Value_const &vec)
Tag tag () const
Public Member Functions inherited from RFC_Data_const< _Tag >
RFC_Data_const ()
RFC_Data_const (const RFC_Window_transfer &win, const char *aname)
RFC_Data_const (const COM::DataItem *a)
RFC_Data_const (int i, int d)
int id () const
Size dimension () const
bool is_valid (const RFC_Pane_transfer *p, int i) const
Value_const get_value (const RFC_Pane_transfer *p, int v) const
Value_const get_value (const Real *buf, int v) const
Tag tag () const
Additional Inherited Members
Protected Attributes inherited from RFC_Data_const< _Tag >
int _id
unsigned int _dim
Member Typedef Documentation
template<class _Tag > typedef RFC_Data_const<_Tag> RFC_Data< _Tag >::Base
Definition at line 264 of file RFC_Window_transfer.h.
template<class _Tag > typedef unsigned int RFC_Data< _Tag >::Size
Definition at line 268 of file RFC_Window_transfer.h.
template<class _Tag > typedef _Tag RFC_Data< _Tag >::Tag
Definition at line 269 of file RFC_Window_transfer.h.
template<class _Tag > typedef Vector_n RFC_Data< _Tag >::Value
Definition at line 265 of file RFC_Window_transfer.h.
template<class _Tag > typedef Array_n_const RFC_Data< _Tag >::Value_const
Definition at line 267 of file RFC_Window_transfer.h.
template<class _Tag > typedef Array_n RFC_Data< _Tag >::Value_nonconst
Definition at line 266 of file RFC_Window_transfer.h.
Constructor & Destructor Documentation
template<class _Tag > RFC_Data< _Tag >::RFC_Data () inline
Definition at line 271 of file RFC_Window_transfer.h.
 {}
template<class _Tag > RFC_Data< _Tag >::RFC_Data (RFC_Window_transfer & win, const char * aname) inline
Definition at line 272 of file RFC_Window_transfer.h.
 : Base( win, aname) {}
template<class _Tag > RFC_Data< _Tag >::RFC_Data (COM::DataItem * a) inline
Definition at line 273 of file RFC_Window_transfer.h.
 :  Base( a) {}
template<class _Tag > RFC_Data< _Tag >::RFC_Data (int i, int d) inline
Definition at line 274 of file RFC_Window_transfer.h.
 :  Base(i, d) {}
Member Function Documentation
template<class _Tag > Value_nonconst RFC_Data< _Tag >::get_value (RFC_Pane_transfer * p, int v) inline
Definition at line 277 of file RFC_Window_transfer.h.
References RFC_Data_const< _Tag >::_dim, RFC_Data_const< _Tag >::_id, RFC_Pane_transfer::pointer(), and RFC_assertion.
Referenced by Transfer_base::integrate_subface(), Transfer_base::interpolate_fe(), Transfer_base::invert(), Transfer_base::precondition_Jacobi(), Transfer_base::saxpy(), Transfer_base::scale(), and Transfer_base::transfer_2f().
{
     RFC_assertion( v>=1);
     return Value_nonconst( p->pointer( _id) + (v-1)*_dim, _dim);
   }
template<class _Tag > Value_const RFC_Data< _Tag >::get_value (const RFC_Pane_transfer * p, int v) const inline
Definition at line 282 of file RFC_Window_transfer.h.
References RFC_Data_const< _Tag >::_dim, RFC_Data_const< _Tag >::_id, RFC_Pane_transfer::pointer(), and RFC_assertion.
{
     RFC_assertion( v>=1);
     return Value_const( p->pointer( _id) + (v-1)*_dim, _dim);
   }
template<class _Tag > Value_nonconst RFC_Data< _Tag >::get_value (Real * buf, int v) const inline
Definition at line 291 of file RFC_Window_transfer.h.
References RFC_Data_const< _Tag >::_dim, and RFC_assertion.
{
     RFC_assertion( v>=1);
     return Value_nonconst( buf + (v-1)*_dim, _dim);
   }
template<class _Tag > Value_const RFC_Data< _Tag >::get_value (const Real * buf, int v) const inline
Definition at line 295 of file RFC_Window_transfer.h.
References RFC_Data_const< _Tag >::_dim, and RFC_assertion.
{
     RFC_assertion( v>=1);
     return Value_const( buf + (v-1)*_dim, _dim);
   }
template<class _Tag > void RFC_Data< _Tag >::set_value (RFC_Pane_transfer * p, int v, const Value_const & vec) inline
Definition at line 286 of file RFC_Window_transfer.h.
References RFC_Data_const< _Tag >::_dim, RFC_Data_const< _Tag >::_id, Array_n_const::begin(), Array_n_const::dimension(), Array_n_const::end(), RFC_Pane_transfer::pointer(), and RFC_assertion.
Referenced by Transfer_base::copy_vec().
{
     RFC_assertion( _dim == vec.dimension() && v>=1);
     std::copy( vec.begin(), vec.end(), p->pointer( _id) + (v-1)*_dim);
   }
template<class _Tag > void RFC_Data< _Tag >::set_value (Real * buf, int v, const Value_const & vec) inline
Definition at line 299 of file RFC_Window_transfer.h.
References RFC_Data_const< _Tag >::_dim, Array_n_const::begin(), Array_n_const::dimension(), Array_n_const::end(), and RFC_assertion.
{
     RFC_assertion( _dim == vec.dimension() && v>=1);
     std::copy( vec.begin(), vec.end(), buf + (v-1)*_dim);
   }
template<class _Tag > Tag RFC_Data< _Tag >::tag () const inline
Definition at line 304 of file RFC_Window_transfer.h.
 { return Tag(); }
The documentation for this class was generated from the following file:
RFC_Window_transfer.h