IMPACT: com_c.C File Reference
com_c.C File Reference
This file contains the wrapper routines for the C binding of the COM implementation.
Detailed Description
See Also
com_c.h
Definition in file com_c.C.
#include "COM_base.hpp"
#include "com_assertion.h"
#include <cstdarg>
#include "com_c.h"
#include "com_c++.hpp"
Macros
#define C_ONLY
Functions
USE_COM_NAME_SPACE void COM_call_function (const int wf, int argc,...)
void COM_icall_function (const int wf, int argc,...)
void COM_get_dataitem (const char *wa_str, char *loc, int *type, int *size, char *u_str, int u_len)
Get the sizes of an dataitem.
Macro Definition Documentation
#define C_ONLY
Definition at line 19 of file com_c.C.
Function Documentation
USE_COM_NAME_SPACE void COM_call_function (const int wf, int argc, ...)
Definition at line 30 of file com_c.C.
References COM::COM_base::call_function(), COM_assertion_msg, COM_get_com(), and Function::MAX_NUMARG.
Referenced by _load_rocface(), InterpolateBase::backup(), Agent::check_convergence_help(), FluidAgent::compute_integrals(), SolidAgent::compute_integrals(), compute_overlay(), FluidAgent::create_buffer_all(), InterpolateBase::extrapolate_Linear(), Agent::finalize(), COM::TestModule::Function2(), COM::TestModule::Function4(), getPaneConnectivity(), getWindow(), InterpolateBase::init(), GetDeformedMesh::init(), GetDeformedMesh_ALE::init(), MeshMotionTransferISS::init(), FluidAgent::init_convergence(), FluidAgent::init_module(), BurnAgent::init_module(), SolidAgent::init_module(), RFC_Window_transfer::init_recv_buffer(), load_rocon(), load_rocprop(), main(), FluidAgent::output_restart_files(), RFC_Window_overlay::print_features(), Control_parameters::read(), RocmanControl_parameters::read(), Agent::read_by_control_file(), read_file(), read_file_rocin(), read_pane_sp(), FluidAgent::read_restart_data(), BurnAgent::read_restart_data(), SolidAgent::read_restart_data(), RFC_Window_base::read_sdv(), IM_Reader::read_winmesh(), SetValueDouble::run(), LoadTransfer_FS::run(), Extrapolate_Linear::run(), CopyValue::run(), Extrapolate_Central::run(), LoadTransfer_FSc_ALE::run(), Interpolate_Linear::run(), Interpolate_Constant::run(), Interpolate_Central::run(), LoadTransferOnly_FSc_ALE::run(), GetDeformedMesh::run(), GetDeformedMesh_ALE::run(), SurfDiver::run(), MeshMotionTransfer_SF::run(), ComputeFluidLoad_ALE::run(), DeformationVelTransfer_SF::run(), PhysicsAction::run(), MeshMotionTransferISS::run(), ComputeMeshMotion::run(), ComputeFaceCenters::run(), TransferSolidDensity::run(), FluidPropagateSurface::run(), TransferBurnRate_FS_ALE::run(), MassTransfer_SF_ALE::run(), MassTransfer::run(), TemperatureTransfer_SF::run(), ZoomInterface::run(), HeatTransfer_FS::run(), ComputeRhofvf::run(), ComputeBurnPane::run(), RemeshInit::run(), ComputePconn::run(), SolidPropagateSurface_ALE::run(), Reset_du_alp::run(), COM::TestingObject< ResultsType >::Test__DataItemManagement(), COM::ParallelTestingObject< CommType, ResultsType >::Test__FunctionBarrierTest(), COM::TestingObject< ResultsType >::Test__ModuleFunctionTest(), COM::ParallelTestingObject< CommType, ResultsType >::Test__ModuleGetSetCommunicator(), COM::TestingObject< ResultsType >::Test__ModuleLoadingTest(), COM::ParallelTestingObject< CommType, ResultsType >::Test__ParallelModuleLoadingTest(), Control_parameters::update_communicator(), Agent::write_control_file(), Agent::write_data_files(), and RFC_Window_base::write_sdv().
{
   COM_assertion_msg( argc <= Function::MAX_NUMARG, "Too many arguments") ;
   int i;
   void *args[Function::MAX_NUMARG];
   va_list   ap;
   va_start( ap, argc);
   for ( i=0; i<argc; ++i) {
     args[i] = va_arg( ap, void*);
   }
   va_end( ap);
   COM_get_com()->call_function( wf, argc, args);
 }
void COM_get_dataitem (const char * wa_str, char * loc, int * type, int * ncomp, char * unit, int n)
Information retrieval Get the information about an dataitem.
The opposite of set_size.
The opposite of new_dataitem.
Definition at line 62 of file com_c.C.
References COM_get_com(), COM::COM_base::get_dataitem(), max(), and min().
 {
   std::string unit;
   COM_get_com()->get_dataitem( wa_str, loc, type, size, &unit);
   if ( u_str && u_len) {
     int len=unit.size(), n=std::min(len, int(u_len));
     std::copy( unit.c_str(), unit.c_str()+n, u_str);
     std::fill_n( u_str+1+n, std::max(0,int(u_len-len)), 0);
   }
 }
void COM_icall_function (const int wf, int argc, ...)
Definition at line 46 of file com_c.C.
References COM_assertion_msg, COM_get_com(), COM::COM_base::icall_function(), and Function::MAX_NUMARG.
{
   COM_assertion_msg( argc <= Function::MAX_NUMARG, "Too many arguments") ;
   int i;
   void *args[Function::MAX_NUMARG];
   va_list   ap;
   va_start( ap, argc);
   for ( i=0; i<argc-1; ++i) {
     args[i] = va_arg( ap, void*);
   }
   int *status = va_arg( ap, int *);
   va_end( ap);
   COM_get_com()->icall_function( wf, argc, args, status);
 }