IMPACT: com_c++.hpp File Reference
com_c++.hpp File Reference
Contains the wrapper routines for C++ binding of COM API.
Detailed Description
All the functions are inlined and hence have smaller runtime overhead compared with the C binding.
See also
com_c.h
Definition in file com_c++.hpp.
#include "COM_base.hpp"
Macros
#define COM_set_bounds_prototype(type)
#define COM_get_array_prototype(type)
#define COM_get_array_const_prototype(type)
Functions
void COM_init (int *argc, char ***argv)
void COM_finalize ()
int COM_initialized ()
void COM_abort (int ierr)
void COM_set_default_communicator (MPI_Comm comm)
MPI_Comm COM_get_default_communicator ()
void COM_load_module (const char *libname, const char *winname)
void COM_unload_module (const char *libname, const char *winname=NULL)
void COM_close_module (const char *libname, const char *winname=NULL)
void COM_new_window (const char *wname, MPI_Comm c=MPI_COMM_NULL)
void COM_new_window (const std::string wname, MPI_Comm c=MPI_COMM_NULL)
void COM_delete_window (const char *wname)
void COM_delete_window (const std::string wname)
void COM_window_init_done (const char *w_str, int pane_changed=true)
void COM_window_init_done (const std::string w_str, int pane_changed=true)
void COM_delete_pane (const char *str, int pid)
void COM_delete_pane (const std::string str, int pid)
void COM_new_dataitem (const char *wa_str, const char loc, const int type, int ncomp, const char *unit)
Registering an dataitem type.
void COM_new_dataitem (const std::string wa_str, const char loc, const int type, int ncomp, const char *unit)
void COM_delete_dataitem (const char *wa_str)
Delete an existing dataitem.
void COM_delete_dataitem (const std::string wa_str)
void COM_set_size (const char *wa_str, int pane_id, int size, int ng=0)
Set sizes of for a specific dataitem.
void COM_set_size (const std::string wa_str, int pane_id, int size, int ng=0)
template<class Type >
void COM_set_object (const char *wa_str, int pane_id, Type *addr)
template<class Type >
void COM_get_object (const char *wa_str, int pane_id, Type **addr)
void COM_set_array (const char *wa_str, int pane_id, void *addr, int strd=0, int cap=0)
Associates an array with an dataitem for a specific pane.
void COM_set_array_const (const char *wa_str, int pane_id, const void *addr, int strd=0, int cap=0)
void COM_set_array (const std::string wa_str, int pane_id, void *addr, int strd=0, int cap=0)
void COM_set_array_const (const std::string wa_str, int pane_id, const void *addr, int strd=0, int cap=0)
void COM_set_bounds (const char *wa_str, int pane_id, const void *lbound, const void *ubound)
Set the lower and upper bounds of an dataitem.
void COM_set_bounds (const std::string wa_str, int pane_id, const void *lbound, const void *ubound)
COM_set_bounds_prototype (char) COM_set_bounds_prototype(int) COM_set_bounds_prototype(float) COM_set_bounds_prototype(double) inline void COM_allocate_array(const char *wa_str
void COM_icall_function (const int wf, int argc,...)
void COM_call_function (const int wf)
void COM_call_function (const int wf, const void *wa)
void COM_call_function (const int wf, const void *wa1, const void *wa2)
void COM_call_function (const int wf, const void *wa1, const void *wa2, const void *wa3)
void COM_call_function (const int wf, const void *wa1, const void *wa2, const void *wa3, const void *wa4)
void COM_call_function (const int wf, const void *wa1, const void *wa2, const void *wa3, const void *wa4, const void *wa5)
void COM_call_function (const int wf, const void *wa1, const void *wa2, const void *wa3, const void *wa4, const void *wa5, const void *wa6)
void COM_call_function (const int wf, const void *wa1, const void *wa2, const void *wa3, const void *wa4, const void *wa5, const void *wa6, const void *wa7)
void COM_call_function (const int wf, const void *wa1, const void *wa2, const void *wa3, const void *wa4, const void *wa5, const void *wa6, const void *wa7, const void *wa8)
void COM_call_function (const int wf, const void *wa1, const void *wa2, const void *wa3, const void *wa4, const void *wa5, const void *wa6, const void *wa7, const void *wa8, const void *wa9)
void COM_call_function (const int wf, const void *wa1, const void *wa2, const void *wa3, const void *wa4, const void *wa5, const void *wa6, const void *wa7, const void *wa8, const void *wa9, const void *wa10)
void COM_call_function (const int wf, const void *wa1, const void *wa2, const void *wa3, const void *wa4, const void *wa5, const void *wa6, const void *wa7, const void *wa8, const void *wa9, const void *wa10, const void *wa11)
void COM_call_function (const int wf, const void *wa1, const void *wa2, const void *wa3, const void *wa4, const void *wa5, const void *wa6, const void *wa7, const void *wa8, const void *wa9, const void *wa10, const void *wa11, const void *wa12)
void COM_call_function (const int wf, const void *wa1, const void *wa2, const void *wa3, const void *wa4, const void *wa5, const void *wa6, const void *wa7, const void *wa8, const void *wa9, const void *wa10, const void *wa11, const void *wa12, const void *wa13)
void COM_call_function (const int wf, const void *wa1, const void *wa2, const void *wa3, const void *wa4, const void *wa5, const void *wa6, const void *wa7, const void *wa8, const void *wa9, const void *wa10, const void *wa11, const void *wa12, const void *wa13, const void *wa14)
void COM_icall_function (const int wf, int *id)
void COM_icall_function (const int wf, const void *wa, int *id)
void COM_icall_function (const int wf, const void *wa1, const void *wa2, int *id)
void COM_icall_function (const int wf, const void *wa1, const void *wa2, const void *wa3, int *id)
void COM_icall_function (const int wf, const void *wa1, const void *wa2, const void *wa3, const void *wa4, int *id)
void COM_icall_function (const int wf, const void *wa1, const void *wa2, const void *wa3, const void *wa4, const void *wa5, int *id)
void COM_icall_function (const int wf, const void *wa1, const void *wa2, const void *wa3, const void *wa4, const void *wa5, const void *wa6, int *id)
void COM_icall_function (const int wf, const void *wa1, const void *wa2, const void *wa3, const void *wa4, const void *wa5, const void *wa6, const void *wa7, int *id)
void COM_wait (const int id)
int COM_test (const int id)
void COM_set_verbose (int i)
void COM_set_profiling (int i)
void COM_set_profiling_barrier (int hdl, MPI_Comm comm)
void COM_print_profile (const char *fname, const char *header)
int COM_get_sizeof (const COM_Type type, int c)
int COM_compatible_types (COM_Type type1, COM_Type type2)
int COM_get_error_code ()
Variables
int pane_id =0
int void ** addr =NULL
int void int strd =0
int void int int cap
Macro Definition Documentation
#define COM_get_array_const_prototype (type)
Value:
inline void COM_get_array_const(const char *wa_str, int pane_id, \
                          const type **addr, int *strd=NULL, int *cap=NULL) \
{ COM_get_com()->get_array(wa_str, pane_id, \
                               (void**)addr, strd, cap, true); }
#define COM_get_array_prototype (type)
Value:
inline void COM_get_array(const char *wa_str, int pane_id, \
                           type **addr, int *strd=NULL, int *cap=NULL) \
{ COM_get_com()->get_array(wa_str, pane_id, (void**)addr, strd, cap); }
#define COM_set_bounds_prototype (type)
Value:
inline void COM_set_bounds(const char *wa_str, int pane_id, \
                            type lbound, type ubound) \
{ COM_get_com()->set_bounds(wa_str, pane_id, &lbound, &ubound); }
Definition at line 162 of file com_c++.hpp.
Function Documentation
void COM_abort (int ierr) inline
Definition at line 41 of file com_c++.hpp.
References COM::COM_base::abort().
 { COM::COM_base::abort( ierr); }
void COM_call_function (const int wf) inline
Definition at line 419 of file com_c++.hpp.
References COM::COM_base::call_function(), and COM_get_com().
Referenced by _load_rocface(), InterpolateBase::backup(), Agent::check_convergence_help(), FluidAgent::compute_integrals(), SolidAgent::compute_integrals(), compute_overlay(), FluidAgent::create_buffer_all(), InterpolateBase::extrapolate_Linear(), Agent::finalize(), COM::TestModule::Function2(), COM::TestModule::Function4(), getPaneConnectivity(), getWindow(), InterpolateBase::init(), GetDeformedMesh::init(), GetDeformedMesh_ALE::init(), MeshMotionTransferISS::init(), FluidAgent::init_convergence(), FluidAgent::init_module(), BurnAgent::init_module(), SolidAgent::init_module(), RFC_Window_transfer::init_recv_buffer(), SolverUtils::TransferObject::Interpolate(), load_rocon(), load_rocprop(), main(), FluidAgent::output_restart_files(), SolverUtils::TransferObject::Overlay(), RFC_Window_overlay::print_features(), Control_parameters::read(), RocmanControl_parameters::read(), Agent::read_by_control_file(), read_file(), read_file_rocin(), read_pane_sp(), FluidAgent::read_restart_data(), BurnAgent::read_restart_data(), SolidAgent::read_restart_data(), RFC_Window_base::read_sdv(), IM_Reader::read_winmesh(), SetValueDouble::run(), LoadTransfer_FS::run(), Extrapolate_Linear::run(), CopyValue::run(), Extrapolate_Central::run(), LoadTransfer_FSc_ALE::run(), Interpolate_Linear::run(), Interpolate_Constant::run(), Interpolate_Central::run(), LoadTransferOnly_FSc_ALE::run(), GetDeformedMesh::run(), SurfDiver::run(), GetDeformedMesh_ALE::run(), MeshMotionTransfer_SF::run(), ComputeFluidLoad_ALE::run(), DeformationVelTransfer_SF::run(), MeshMotionTransferISS::run(), ComputeMeshMotion::run(), PhysicsAction::run(), ComputeFaceCenters::run(), TransferSolidDensity::run(), FluidPropagateSurface::run(), TransferBurnRate_FS_ALE::run(), MassTransfer_SF_ALE::run(), MassTransfer::run(), TemperatureTransfer_SF::run(), ZoomInterface::run(), HeatTransfer_FS::run(), ComputeRhofvf::run(), ComputeBurnPane::run(), RemeshInit::run(), ComputePconn::run(), SolidPropagateSurface_ALE::run(), Reset_du_alp::run(), SolverUtils::TransferObject::SetVerbosity(), COM::TestingObject< ResultsType >::Test__DataItemManagement(), COM::ParallelTestingObject< CommType, ResultsType >::Test__FunctionBarrierTest(), COM::TestingObject< ResultsType >::Test__ModuleFunctionTest(), COM::ParallelTestingObject< CommType, ResultsType >::Test__ModuleGetSetCommunicator(), COM::TestingObject< ResultsType >::Test__ModuleLoadingTest(), COM::ParallelTestingObject< CommType, ResultsType >::Test__ParallelModuleLoadingTest(), SolverUtils::TransferObject::Transfer(), SolverUtils::TransferObject::TransferLoad(), Control_parameters::update_communicator(), Agent::write_control_file(), Agent::write_data_files(), RFC_Window_base::write_sdv(), and SolverUtils::WriteWindow().
 { COM_get_com()->call_function( wf, 0, 0); }
void COM_call_function (const int wf, const void * wa) inline
Definition at line 421 of file com_c++.hpp.
References COM::COM_base::call_function(), and COM_get_com().
{
   COM_get_com()->call_function( wf, 1, (void**)&wa);
 }
void COM_call_function (const int wf, const void * wa1, const void * wa2) inline
Definition at line 424 of file com_c++.hpp.
References COM::COM_base::call_function(), and COM_get_com().
{
   const void *args[] = { wa1, wa2};
   COM_get_com()->call_function( wf, 2, (void **)args);
 }
void COM_call_function (const int wf, const void * wa1, const void * wa2, const void * wa3) inline
Definition at line 429 of file com_c++.hpp.
References COM::COM_base::call_function(), and COM_get_com().
{
   const void *args[] = { wa1, wa2, wa3 };
   COM_get_com()->call_function( wf, 3, (void**)args);
 }
void COM_call_function (const int wf, const void * wa1, const void * wa2, const void * wa3, const void * wa4) inline
Definition at line 434 of file com_c++.hpp.
References COM::COM_base::call_function(), and COM_get_com().
{
   const void *args[] = { wa1, wa2, wa3, wa4 };
   COM_get_com()->call_function( wf, 4, (void**)args);
 }
void COM_call_function (const int wf, const void * wa1, const void * wa2, const void * wa3, const void * wa4, const void * wa5) inline
Definition at line 441 of file com_c++.hpp.
References COM::COM_base::call_function(), and COM_get_com().
{
   const void *args[] = { wa1, wa2, wa3, wa4, wa5 };
   COM_get_com()->call_function( wf, 5, (void**)args);
 }
void COM_call_function (const int wf, const void * wa1, const void * wa2, const void * wa3, const void * wa4, const void * wa5, const void * wa6) inline
Definition at line 448 of file com_c++.hpp.
References COM::COM_base::call_function(), and COM_get_com().
{
   const void *args[] = { wa1, wa2, wa3, wa4, wa5, wa6 };
   COM_get_com()->call_function( wf, 6, (void**)args);
 }
void COM_call_function (const int wf, const void * wa1, const void * wa2, const void * wa3, const void * wa4, const void * wa5, const void * wa6, const void * wa7) inline
Definition at line 456 of file com_c++.hpp.
References COM::COM_base::call_function(), and COM_get_com().
{
   const void *args[] = { wa1, wa2, wa3, wa4, wa5, wa6, wa7 };
   COM_get_com()->call_function( wf, 7, (void**)args);
 }
void COM_call_function (const int wf, const void * wa1, const void * wa2, const void * wa3, const void * wa4, const void * wa5, const void * wa6, const void * wa7, const void * wa8) inline
Definition at line 464 of file com_c++.hpp.
References COM::COM_base::call_function(), and COM_get_com().
{
   const void *args[] = { wa1, wa2, wa3, wa4, wa5, wa6, wa7, wa8};
   COM_get_com()->call_function( wf, 8, (void**)args);
 }
void COM_call_function (const int wf, const void * wa1, const void * wa2, const void * wa3, const void * wa4, const void * wa5, const void * wa6, const void * wa7, const void * wa8, const void * wa9) inline
Definition at line 473 of file com_c++.hpp.
References COM::COM_base::call_function(), and COM_get_com().
{
   const void *args[] = { wa1, wa2, wa3, wa4, wa5, wa6, wa7, wa8, wa9};
   COM_get_com()->call_function( wf, 9, (void**)args);
 }
void COM_call_function (const int wf, const void * wa1, const void * wa2, const void * wa3, const void * wa4, const void * wa5, const void * wa6, const void * wa7, const void * wa8, const void * wa9, const void * wa10) inline
Definition at line 482 of file com_c++.hpp.
References COM::COM_base::call_function(), and COM_get_com().
{
   const void *args[] = { wa1, wa2, wa3, wa4, wa5, wa6, wa7, wa8, wa9, wa10};
   COM_get_com()->call_function( wf, 10, (void**)args);
 }
void COM_call_function (const int wf, const void * wa1, const void * wa2, const void * wa3, const void * wa4, const void * wa5, const void * wa6, const void * wa7, const void * wa8, const void * wa9, const void * wa10, const void * wa11) inline
Definition at line 492 of file com_c++.hpp.
References COM::COM_base::call_function(), and COM_get_com().
{
   const void *args[] = { wa1, wa2, wa3, wa4, wa5, wa6, wa7, wa8, wa9, wa10, wa11};
   COM_get_com()->call_function( wf, 11, (void**)args);
 }
void COM_call_function (const int wf, const void * wa1, const void * wa2, const void * wa3, const void * wa4, const void * wa5, const void * wa6, const void * wa7, const void * wa8, const void * wa9, const void * wa10, const void * wa11, const void * wa12) inline
Definition at line 502 of file com_c++.hpp.
References COM::COM_base::call_function(), and COM_get_com().
{
   const void *args[] = { wa1, wa2, wa3, wa4, wa5, wa6, wa7, wa8,
                          wa9, wa10, wa11, wa12};
   COM_get_com()->call_function( wf, 12, (void**)args);
 }
void COM_call_function (const int wf, const void * wa1, const void * wa2, const void * wa3, const void * wa4, const void * wa5, const void * wa6, const void * wa7, const void * wa8, const void * wa9, const void * wa10, const void * wa11, const void * wa12, const void * wa13) inline
Definition at line 514 of file com_c++.hpp.
References COM::COM_base::call_function(), and COM_get_com().
{
   const void *args[] = { wa1, wa2, wa3, wa4, wa5, wa6, wa7, wa8,
                          wa9, wa10, wa11, wa12, wa13};
   COM_get_com()->call_function( wf, 13, (void**)args);
 }
void COM_call_function (const int wf, const void * wa1, const void * wa2, const void * wa3, const void * wa4, const void * wa5, const void * wa6, const void * wa7, const void * wa8, const void * wa9, const void * wa10, const void * wa11, const void * wa12, const void * wa13, const void * wa14) inline
Definition at line 526 of file com_c++.hpp.
References COM::COM_base::call_function(), and COM_get_com().
{
   const void *args[] = { wa1, wa2, wa3, wa4, wa5, wa6, wa7, wa8,
                          wa9, wa10, wa11, wa12, wa13, wa14};
   COM_get_com()->call_function( wf, 14, (void**)args);
 }
void COM_close_module (const char * libname, const char * winname = NULL) inline
Definition at line 58 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::unload_module().
Referenced by BurnAgent::unload_module(), FluidAgent::unload_module(), and SolidAgent::unload_module().
 { COM_get_com()->unload_module( libname, winname?winname:"", 0); }
int COM_compatible_types (COM_Type type1, COM_Type type2) inline
Definition at line 612 of file com_c++.hpp.
Referenced by Rocblas::axpy_gen(), Rocblas::calc(), Rocblas::calcDot(), Rocsurf::compute_element_areas(), Window_manifold_2::compute_normals(), Pane_boundary::determine_borders(), Window_manifold_2::elements_to_nodes(), Rocblas::gen2arg(), Rocsurf::integrate(), Window_manifold_2::shortest_edge_length(), Window_manifold_2::update_bd_flags(), Window_manifold_2::update_bd_normals(), and Window_manifold_2::update_bdedge_bitmap().
 { return COM::DataItem::compatible_types( type1, type2); }
void COM_delete_dataitem (const char * wa_str) inline
Definition at line 105 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::delete_dataitem().
Referenced by main(), read_file(), read_file_rocin(), and IM_Reader::read_winmesh().
 { COM_get_com()->delete_dataitem( wa_str); }
void COM_delete_dataitem (const std::string wa_str) inline
Definition at line 109 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::delete_dataitem().
 { COM_get_com()->delete_dataitem( wa_str.c_str()); }
void COM_delete_pane (const char * str, int pid) inline
Definition at line 87 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::delete_pane().
Referenced by read_file(), read_file_rocin(), and RFC_Window_base::write_sdv().
 { COM_get_com()->delete_pane( str, pid) ; }
void COM_delete_pane (const std::string str, int pid) inline
Definition at line 91 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::delete_pane().
 { COM_get_com()->delete_pane( str.c_str(), pid) ; }
void COM_delete_window (const char * wname) inline
Definition at line 71 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::delete_window().
Referenced by SolidAgent::create_buffer_all(), SolverUtils::DestroySolver(), BurnAgent::finalize(), FluidAgent::finalize(), Rocblas::finalize(), SolidAgent::finalize(), Rocout::finalize(), Rocin::finalize(), getWindow(), BurnAgent::init_module(), FluidAgent::init_module(), SolidAgent::init_module(), RFC_Window_transfer::init_recv_buffer(), main(), RFC_Window_overlay::print_features(), Control_parameters::read(), RocmanControl_parameters::read(), read_file(), read_file_rocin(), read_pane_sp(), RFC_Window_base::read_sdv(), COM::ParallelTestingObject< CommType, ResultsType >::Test__GetSetCommunicator(), COM::ParallelTestingObject< CommType, ResultsType >::Test__WindowGetSetCommunicator(), TestModule_unload_module(), Rocsurf::unload(), Rocmap::unload(), COM::TestModule::Unload(), and RFC_Window_base::write_sdv().
 { COM_get_com()->delete_window(wname); }
void COM_delete_window (const std::string wname) inline
Definition at line 75 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::delete_window().
 { COM_get_com()->delete_window(wname.c_str()); }
void COM_finalize () inline
Definition at line 36 of file com_c++.hpp.
References COM::COM_base::finalize().
Referenced by SolverUtils::FinalizeInterface(), main(), COM::ParallelTest(), RocstarShutdown(), and COM::Test().
 { COM::COM_base::finalize(); }
MPI_Comm COM_get_default_communicator () inline
Definition at line 46 of file com_c++.hpp.
References COM::COM_base::get_default_communicator().
Referenced by compute_overlay(), COM::TestModule::get_communicator_module(), Rocin::read_by_control_file(), Rocin::read_windows(), SurfDiver::run(), COM::ParallelTestingObject< CommType, ResultsType >::Test__GetSetCommunicator(), COM::ParallelTestingObject< CommType, ResultsType >::Test__WindowGetSetCommunicator(), and Rocout::write_rocin_control_file().
 { return COM::COM_base::get_default_communicator(); }
int COM_get_error_code () inline
Definition at line 615 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::get_error_code().
 { return COM_get_com()->get_error_code(); }
template<class Type > void COM_get_object (const char * wa_str, int pane_id, Type ** addr) inline
Definition at line 129 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::get_object().
Referenced by Rocout::finalize(), Rocin::finalize(), Rocsurf::unload(), and COM::TestModule::Unload().
 { COM_get_com()->get_object( wa_str, pane_id, (void**)addr); }
int COM_get_sizeof (const COM_Type type, int c) inline
Definition at line 609 of file com_c++.hpp.
References get_sizeof().
Referenced by Window_manifold_2::accumulate_bd_values(), Node::addr(), Halfedge::addr(), Pane_communicator::begin_update(), broadcast_win_dataitems(), Pane_communicator::init(), Pane_communicator::reduce_average_on_shared_nodes(), Pane_communicator::reduce_diff_on_shared_nodes(), Pane_communicator::reduce_maxabs_on_shared_nodes(), Pane_communicator::reduce_minabs_on_shared_nodes(), Pane_communicator::reduce_on_shared_nodes(), Element_node_vectors_k_const< Value >::set(), Element_vectors_k_const< Value >::set(), and Pane_communicator::update_ghost_values().
 { return COM::DataItem::get_sizeof( type, c); }
void COM_icall_function (const int wf, int argc, ...)
Definition at line 46 of file com_c.C.
{
   COM_assertion_msg( argc <= Function::MAX_NUMARG, "Too many arguments") ;
   int i;
   void *args[Function::MAX_NUMARG];
   va_list   ap;
   va_start( ap, argc);
   for ( i=0; i<argc-1; ++i) {
     args[i] = va_arg( ap, void*);
   }
   int *status = va_arg( ap, int *);
   va_end( ap);
   COM_get_com()->icall_function( wf, argc, args, status);
 }
void COM_icall_function (const int wf, int * id) inline
Definition at line 540 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::icall_function().
 { COM_get_com()->icall_function( wf, 0, 0, id); }
void COM_icall_function (const int wf, const void * wa, int * id) inline
Definition at line 542 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::icall_function().
{
   COM_get_com()->icall_function( wf, 1, (void**)&wa, id);
 }
void COM_icall_function (const int wf, const void * wa1, const void * wa2, int * id) inline
Definition at line 545 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::icall_function().
{
   const void *args[] = { wa1, wa2};
   COM_get_com()->icall_function( wf, 2, (void **)args, id);
 }
void COM_icall_function (const int wf, const void * wa1, const void * wa2, const void * wa3, int * id) inline
Definition at line 550 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::icall_function().
{
   const void *args[] = { wa1, wa2, wa3 };
   COM_get_com()->icall_function( wf, 3, (void **)args, id);
 }
void COM_icall_function (const int wf, const void * wa1, const void * wa2, const void * wa3, const void * wa4, int * id) inline
Definition at line 556 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::icall_function().
{
   const void *args[] = { wa1, wa2, wa3, wa4 };
   COM_get_com()->icall_function( wf, 4, (void **)args, id);
 }
void COM_icall_function (const int wf, const void * wa1, const void * wa2, const void * wa3, const void * wa4, const void * wa5, int * id) inline
Definition at line 563 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::icall_function().
{
   const void *args[] = { wa1, wa2, wa3, wa4, wa5 };
   COM_get_com()->icall_function( wf, 5, (void **)args, id);
 }
void COM_icall_function (const int wf, const void * wa1, const void * wa2, const void * wa3, const void * wa4, const void * wa5, const void * wa6, int * id) inline
Definition at line 571 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::icall_function().
{
   const void *args[] = { wa1, wa2, wa3, wa4, wa5, wa6 };
   COM_get_com()->icall_function( wf, 6, (void **)args, id);
 }
void COM_icall_function (const int wf, const void * wa1, const void * wa2, const void * wa3, const void * wa4, const void * wa5, const void * wa6, const void * wa7, int * id) inline
Definition at line 579 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::icall_function().
{
   const void *args[] = { wa1, wa2, wa3, wa4, wa5, wa6, wa7 };
   COM_get_com()->icall_function( wf, 7, (void **)args, id);
 }
void COM_init (int * argc, char *** argv) inline
Definition at line 34 of file com_c++.hpp.
References COM::COM_base::init().
Referenced by SolverUtils::InitializeInterface(), main(), COM::ParallelTest(), and COM::Test().
 { COM::COM_base::init( argc, argv); }
int COM_initialized () inline
Definition at line 39 of file com_c++.hpp.
References COM::COM_base::initialized().
Referenced by COM::ParallelTest(), and COM::Test().
 { return COM::COM_base::initialized(); }
void COM_load_module (const char * libname, const char * winname) inline
Definition at line 52 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::load_module().
Referenced by BurnAgent::load_module(), FluidAgent::load_module(), SolidAgent::load_module(), and main().
 { COM_get_com()->load_module( libname, winname); }
void COM_new_dataitem (const char * wa_str, const char loc, const int type, int ncomp, const char * unit) inline
wa_str is the dataitem's name in the format "window.dataitem". loc is the code for the location of the data, which can be 'w' for window dataitem, 'p' for pane dataitem, 'n' for node dataitem, or 'e' for element dataitem. type is the data type of the dataitem. For C/C++, it can be COM_CHAR, COM_UNSIGNED_CHAR, COM_BYTE, COM_SHORT, COM_UNSIGNED_SHORT, COM_INT, COM_UNSIGNED, COM_LONG, COM_UNSIGNED_LONG, COM_FLOAT0, COM_DOUBLE1, COM_LONG_DOUBLE, COM_LONG_LONG_INT, or a derived data type. For Fortran, it can be COM_CHARACTER, COM_INTEGER, COM_LOGICAL, COM_REAL, COM_DOUBLE_PRECISION, COM_COMPLEX, COM_DOUBLE_COMPLEX. size is the length of the dataitem in the given data type
Definition at line 95 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::new_dataitem().
Referenced by Coupling::baseInit(), NewDataItem::create(), FluidAgent::create_buffer_all(), SolidAgent::create_buffer_all(), Agent::create_window(), SolverUtils::CreateDataItemsFromSolution(), Rocout::init(), Rocin::init(), Rocsurf::load(), COM::TestModule::Load(), main(), makeWindow(), COM::TestingObject< ResultsType >::MakeWindow(), new_dataitems(), RFC_Window_base::new_sdv_dataitems(), RFC_Window_overlay::print_features(), Rocin::read_parameter_file(), Rocin::register_panes(), and COM::TestingObject< ResultsType >::Test__DataItemManagement().
 { COM_get_com()->new_dataitem( wa_str, loc, type, ncomp, unit); }
void COM_new_dataitem (const std::string wa_str, const char loc, const int type, int ncomp, const char * unit) inline
Definition at line 100 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::new_dataitem().
 { COM_get_com()->new_dataitem( wa_str.c_str(), loc, type, ncomp, unit); }
void COM_new_window (const char * wname, MPI_Comm c = MPI_COMM_NULL) inline
Definition at line 63 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::new_window().
Referenced by Coupling::baseInit(), convertWindow(), BurnAgent::create_buffer_all(), FluidAgent::create_buffer_all(), SolidAgent::create_buffer_all(), Agent::create_buffer_all(), Agent::create_window(), getWindow(), Rocblas::init(), Rocout::init(), Rocin::init(), FluidAgent::input(), BurnAgent::input(), Rocsurf::load(), Rocmap::load(), COM::TestModule::Load(), main(), makeWindow(), COM::TestingObject< ResultsType >::MakeWindow(), RFC_Window_overlay::print_features(), Control_parameters::read(), RocmanControl_parameters::read(), read_file(), read_file_rocin(), Neutral_Reader::read_mesh(), OBJ_Reader::read_mesh(), MSH_Reader::read_mesh(), SMF_Reader::read_mesh(), OFF_Reader::read_mesh(), IM_Reader::read_mesh(), Rocin::read_parameter_file(), Rocin::read_windows(), SolverUtils::RegisterSolver(), Agent::split_surface_window(), COM::TestingObject< ResultsType >::Test__DataItemManagement(), COM::ParallelTestingObject< CommType, ResultsType >::Test__GetSetCommunicator(), COM::ParallelTestingObject< CommType, ResultsType >::Test__WindowGetSetCommunicator(), TestModule_load_module(), and RFC_Window_base::write_sdv().
 { COM_get_com()->new_window(wname, c); }
void COM_new_window (const std::string wname, MPI_Comm c = MPI_COMM_NULL) inline
Definition at line 67 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::new_window().
 { COM_get_com()->new_window(wname.c_str(), c); }
void COM_print_profile (const char * fname, const char * header) inline
Definition at line 606 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::print_profile().
Referenced by main(), and rocstar_driver().
 { COM_get_com()->print_profile( fname, header); }
void COM_set_array (const char * wa_str, int pane_id, void * addr, int strd = 0, int cap = 0) inline
Definition at line 133 of file com_c++.hpp.
References cap, COM_get_com(), COM::COM_base::set_array(), and strd.
Referenced by add_ghost_nodes2D(), SolverUtils::AgentToPane(), SolverUtils::CreateDataItemsFromSolution(), main(), IM_Reader::read_pane_ij(), Rocin::register_panes(), SolverUtils::SurfaceMeshToPane(), COM::TestingObject< ResultsType >::Test__DataItemManagement(), and SolverUtils::VolumeMeshToPane().
 { COM_get_com()->set_array( wa_str, pane_id, addr, strd, cap); }
void COM_set_array (const std::string wa_str, int pane_id, void * addr, int strd = 0, int cap = 0) inline
Definition at line 143 of file com_c++.hpp.
References addr, cap, COM_get_com(), pane_id, COM::COM_base::set_array(), and strd.
 { COM_get_com()->set_array( wa_str.c_str(), pane_id, addr, strd, cap); }
void COM_set_array_const (const char * wa_str, int pane_id, const void * addr, int strd = 0, int cap = 0) inline
Definition at line 137 of file com_c++.hpp.
References cap, COM_get_com(), COM::COM_base::set_array(), and strd.
Referenced by Rocsurf::load(), main(), and RFC_Pane_base::register_sdv_dataitems().
 { COM_get_com()->set_array( wa_str, pane_id,
                                const_cast<void*>(addr), strd, cap, true); }
void COM_set_array_const (const std::string wa_str, int pane_id, const void * addr, int strd = 0, int cap = 0) inline
Definition at line 147 of file com_c++.hpp.
References addr, cap, COM_get_com(), pane_id, COM::COM_base::set_array(), and strd.
 { COM_get_com()->set_array( wa_str.c_str(), pane_id,
                                const_cast<void*>(addr), strd, cap, true); }
void COM_set_bounds (const char * wa_str, int pane_id, const void * lbound, const void * ubound) inline
Definition at line 153 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::set_bounds().
 { COM_get_com()->set_bounds( wa_str, pane_id, lbound, ubound); }
void COM_set_bounds (const std::string wa_str, int pane_id, const void * lbound, const void * ubound) inline
Definition at line 158 of file com_c++.hpp.
References COM_get_com(), pane_id, and COM::COM_base::set_bounds().
 { COM_get_com()->set_bounds( wa_str.c_str(), pane_id, lbound, ubound); }
COM_set_bounds_prototype (char) const
void COM_set_default_communicator (MPI_Comm comm) inline
Definition at line 44 of file com_c++.hpp.
References COM::COM_base::set_default_communicator().
Referenced by compute_overlay(), SurfDiver::run(), COM::ParallelTestingObject< CommType, ResultsType >::Test__GetSetCommunicator(), COM::ParallelTestingObject< CommType, ResultsType >::Test__ParallelModuleLoadingTest(), COM::ParallelTestingObject< CommType, ResultsType >::Test__WindowGetSetCommunicator(), and Control_parameters::update_communicator().
 { COM::COM_base::set_default_communicator( comm); }
template<class Type > void COM_set_object (const char * wa_str, int pane_id, Type * addr) inline
Definition at line 121 of file com_c++.hpp.
References COM_assertion_msg, COM_get_com(), and COM::COM_base::set_object().
Referenced by Coupling::baseInit(), Agent::create_window(), Rocout::init(), Rocin::init(), Rocsurf::load(), and COM::TestModule::Load().
{
   COM_assertion_msg( addr && COM_Object(*addr).validate_object()==0,
                      "Invalid casting");
   COM_get_com()->set_object( wa_str, pane_id, addr, (COM_Object*)(addr));
 }
void COM_set_profiling (int i) inline
Definition at line 599 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::set_profiling().
Referenced by compute_overlay(), main(), rocstar_driver(), and SurfDiver::run().
 { COM_get_com()->set_profiling( i); }
void COM_set_profiling_barrier (int hdl, MPI_Comm comm) inline
Definition at line 603 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::set_profiling_barrier().
Referenced by _load_rocface(), Agent::init_function_handles(), load_rocprop(), and main().
 { COM_get_com()->set_profiling_barrier( hdl, comm); }
void COM_set_size (const char * wa_str, int pane_id, int size, int ng = 0) inline
Definition at line 113 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::set_size().
Referenced by SolverUtils::AgentToPane(), SolverUtils::CreateDataItemsFromSolution(), main(), new_dataitems(), MSH_Reader::read_pane_coors(), OBJ_Reader::read_pane_coors(), SMF_Reader::read_pane_coors(), OFF_Reader::read_pane_coors(), Neutral_Reader::read_pane_coors(), IM_Reader::read_pane_coors(), OBJ_Reader::read_pane_elems(), OFF_Reader::read_pane_elems(), MSH_Reader::read_pane_elems(), SMF_Reader::read_pane_elems(), Neutral_Reader::read_pane_elems(), IM_Reader::read_pane_elems(), Rocin::read_parameter_file(), Rocin::register_panes(), RFC_Pane_base::register_sdv_dataitems(), SolverUtils::SurfaceMeshToPane(), COM::TestingObject< ResultsType >::Test__DataItemManagement(), and SolverUtils::VolumeMeshToPane().
 { COM_get_com()->set_size( wa_str, pane_id, size, ng); }
void COM_set_size (const std::string wa_str, int pane_id, int size, int ng = 0) inline
Definition at line 117 of file com_c++.hpp.
References COM_get_com(), pane_id, and COM::COM_base::set_size().
 { COM_get_com()->set_size( wa_str.c_str(), pane_id, size, ng); }
void COM_set_verbose (int i) inline
Definition at line 595 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::set_verbose().
Referenced by main(), and rocstar_driver().
 { COM_get_com()->set_verbose( i); }
int COM_test (const int id) inline
Definition at line 592 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::test().
 { return COM_get_com()->test( id); }
void COM_unload_module (const char * libname, const char * winname = NULL) inline
Definition at line 55 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::unload_module().
Referenced by BurnAgent::unload_module(), FluidAgent::unload_module(), and SolidAgent::unload_module().
 { COM_get_com()->unload_module( libname, winname?winname:""); }
void COM_wait (const int id) inline
Definition at line 589 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::wait().
 { COM_get_com()->wait( id); }
void COM_window_init_done (const char * w_str, int pane_changed = true) inline
Definition at line 79 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::window_init_done().
Referenced by compute_overlay(), convertWindow(), BurnAgent::create_buffer_all(), FluidAgent::create_buffer_all(), SolidAgent::create_buffer_all(), Agent::create_buffer_all(), Agent::create_registered_dataitems(), Agent::create_window(), getWindow(), Rocblas::init(), Rocout::init(), Rocin::init(), BurnAgent::init_module(), FluidAgent::input(), BurnAgent::input(), Rocsurf::load(), Rocmap::load(), COM::TestModule::Load(), main(), RFC_Window_overlay::print_features(), Control_parameters::read(), RocmanControl_parameters::read(), read_file(), Rocin::read_parameter_file(), Rocin::read_windows(), RFC_Pane_base::register_sdv_dataitems(), SolverUtils::RegisterSolver(), SolverUtils::RegisterSolverInto(), SurfDiver::run(), Agent::split_surface_window(), TestModule_load_module(), and RFC_Window_base::write_sdv().
 { COM_get_com()->window_init_done( w_str, pane_changed); }
void COM_window_init_done (const std::string w_str, int pane_changed = true) inline
Definition at line 83 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::window_init_done().
 { COM_get_com()->window_init_done( w_str.c_str(), pane_changed); }
Variable Documentation
int void** addr =NULL
Definition at line 174 of file com_c++.hpp.
Referenced by ComponentInterface::alloc_array(), COM::COM_base::allocate_array(), broadcast_win_dataitems(), com_get_address_f(), com_obtain_array_f(), com_obtain_array_helper(), com_set_address_f(), COM_set_array(), COM_set_array_const(), com_set_array_const_f(), com_set_array_const_helper(), com_set_array_f(), com_set_array_helper(), Pane_connectivity::create_b2map(), Pane_ghost_connectivity::finalize_pconn(), ComponentInterface::get_array(), get_array_common(), io_pane_dataitem(), main(), Rocin::read_parameter_file(), Pane::reinit_conn(), ComponentInterface::reinit_conn(), Pane::reinit_dataitem(), ComponentInterface::reinit_dataitem(), RFC_Window_transfer::replicate_data(), ComponentInterface::resize_array(), COM::COM_base::resize_array(), COM::COM_base::set_array(), and ComponentInterface::set_array().
int void int int cap
Definition at line 174 of file com_c++.hpp.
Referenced by ComponentInterface::alloc_array(), Connectivity::allocate(), DataItem::allocate(), COM::COM_base::allocate_array(), com_obtain_array_f(), COM_print_window(), COM_set_array(), COM_set_array_const(), com_set_array_const_f(), com_set_array_f(), Pane_connectivity::create_b2map(), debug_int_print(), debug_print(), ComponentInterface::get_array(), get_array_common(), HeatTransfer_FS::init(), Pane::reinit_conn(), ComponentInterface::reinit_conn(), Pane::reinit_dataitem(), ComponentInterface::reinit_dataitem(), ComponentInterface::resize_array(), COM::COM_base::resize_array(), COM::COM_base::set_array(), ComponentInterface::set_array(), Connectivity::set_pointer(), and DataItem::set_pointer().
int pane_id =0
Definition at line 173 of file com_c++.hpp.
Referenced by SolverUtils::AgentToPane(), ComponentInterface::alloc_array(), ComponentInterface::append_array(), com_append_array_f(), COM_F_FUNC2(), com_obtain_array_f(), COM_set_array(), COM_set_array_const(), com_set_array_const_f(), com_set_array_f(), COM_set_bounds(), COM_set_size(), ComponentInterface::copy_array(), Overlay::count_subnodes(), ComponentInterface::dealloc_array(), COM::COM_base::delete_pane(), Pane_ghost_connectivity::finalize_pconn(), ComponentInterface::get_array(), COM::COM_base::get_connectivities(), Pane_ghost_connectivity::get_node_total_order(), COM::COM_base::get_parent(), RFC_Window_transfer::init_recv_buffer(), main(), Overlay::number_a_subnode(), RFC_Pane_base::read_binary(), read_file(), OFF_Reader::read_mesh(), OFF_Reader::read_pane_elems(), RFC_Pane_base::read_rocin(), RFC_Window_base::read_sdv(), RFC_Pane_base::register_sdv_dataitems(), SolverUtils::RegisterSolver(), SolverUtils::RegisterSolverInto(), ComponentInterface::resize_array(), ComponentInterface::set_array(), COM::COM_base::set_bounds(), Overlay::set_subnode_id(), and RFC_Window_base::write_sdv().
int void int strd =0
Definition at line 174 of file com_c++.hpp.
Referenced by ComponentInterface::alloc_array(), Connectivity::allocate(), DataItem::allocate(), COM::COM_base::allocate_array(), DataItem::append_array(), broadcast_win_dataitems(), Rocblas::calcDot(), com_obtain_array_f(), COM_print_window(), COM_set_array(), COM_set_array_const(), com_set_array_const_f(), com_set_array_f(), DataItem::copy_array(), Window_manifold_2::elements_to_nodes(), ComponentInterface::get_array(), get_array_common(), COM::COM_base::get_object(), io_pane_dataitem(), Pane::reinit_conn(), ComponentInterface::reinit_conn(), Pane::reinit_dataitem(), ComponentInterface::reinit_dataitem(), ComponentInterface::resize_array(), COM::COM_base::resize_array(), Element_node_vectors_k_const< Value >::set(), Element_vectors_k_const< Value >::set(), COM::COM_base::set_array(), ComponentInterface::set_array(), Connectivity::set_pointer(), and DataItem::set_pointer().