IMPACT: com_c.h File Reference
com_c.h File Reference
This file contains the C wrapper for COM_base.
Detailed Description
All the functions defined here directly correpond to the public member functions of COM_base.
See Also
com_c.C, com_c++.hpp
Definition in file com_c.h.
#include "com_basic.h"
#include "commpi.h"
#include <string.h>
Macros
#define LOAD_MODULE_WRAPPER(mixed, lower, UPPER)
Functions
Initialization and finalization
void COM_init (int *argc, char ***argv)
void COM_finalize ()
int COM_initialized ()
void COM_abort (int ierr)
void COM_set_default_communicator (MPI_Comm comm)
MPI_Comm COM_get_default_communicator ()
Module management
void COM_load_module (const char *libname, const char *winname)
void COM_unload_module (const char *libname, const char *winname)
Window and pane management
void COM_new_window (const char *w_str, MPI_Comm c)
void COM_delete_window (const char *str)
void COM_delete_pane (const char *w_str, const int pane_id)
void COM_window_init_done (const char *w_str, int pane_changed)
DataItem management
void COM_new_dataitem (const char *wa_str, const char loc, const int type, int ncomp, const char *unit)
Registering an dataitem type.
void COM_delete_dataitem (const char *wa_str)
Delete an existing dataitem.
void COM_set_size (const char *wa_str, int pane_id, int size, int ng)
Set sizes of for a specific dataitem.
void COM_set_array (const char *wa_str, int pane_id, void *addr, int strd, int cap)
Associates an array with an dataitem for a specific pane.
void COM_set_bounds (const char *wa_str, int pane_id, const void *lbound, const void *ubound)
Set the lower and upper bounds of an dataitem.
void COM_allocate_array (const char *wa_str, int pane_id, void **addr, int strd, int cap)
Allocate space for an dataitem on a specific pane and return the address by setting addr.
void COM_resize_array (const char *wa_str, int pane_id, void **addr, int strd, int cap)
Resize an dataitem on a specific pane and return the address by setting addr.
void COM_append_array (const char *wa_str, int pane_id, const void *val, int v_strd, int v_size)
Append an array to the end of the dataitem on a specific pane and return the new address by setting addr.
void COM_use_dataitem (const char *wname, const char *attr, int with_ghost, const char *ptnname, int val)
Use the subset of panes of another window of which the given pane dataitem has value val.
void COM_clone_dataitem (const char *wname, const char *attr, int with_ghost, const char *ptnname, int val)
Clone the subset of panes of another window of which the given pane dataitem has value val.
void COM_copy_dataitem (const char *wname, const char *attr, int with_ghost, const char *ptnname, int val)
Copy an dataitem onto another.
void COM_copy_dataitem_handles (int trg_hdl, int src_hdl, int with_ghost, int ptn_hdl, int val)
void COM_deallocate_array (const char *wa_str, const int pid)
Deallocate space for an dataitem in a pane, asuming the memory was allocated allocate_mesh or allocate_dataitem.
void COM_get_size (const char *wa_str, int pane_id, int *size, int *ng)
Get the sizes of an dataitem.
void COM_get_dataitem (const char *wa_str, char *loc, int *type, int *ncomp, char *unit, int n)
Get the sizes of an dataitem.
void COM_get_array (const char *wa_str, int pane_id, void **addr, int *strd, int *cap)
Get the address for an dataitem on a specific pane.
void COM_copy_array (const char *wa_str, int pane_id, void *val, int v_strd, int v_size, int offset)
Copy an array from an dataitem on a specific pane into a given buffer.
void COM_get_bounds (const char *wa_str, int pane_id, void *lbound, void *ubound)
Get the lower and upper bounds of an dataitem.
int COM_check_bounds (const char *wa_str, int pane_id)
Check the lower and upper bounds of an dataitem for a specific pane.
Information retrieval
void COM_get_communicator (const char *wname, MPI_Comm *comm)
void COM_get_panes (const char *wname, int *npanes, int **pane_ids, int rank)
void COM_get_dataitems (const char *wname, int *na, char **names)
void COM_get_connectivities (const char *wname, int pane_id, int *nc, char **names)
void COM_get_parent (const char *waname, int pane_id, char **parent)
void COM_free_buffer (char **buf)
int COM_get_window_handle (const char *wname)
int COM_get_dataitem_handle (const char *waname)
int COM_get_dataitem_handle_const (const char *waname)
int COM_get_function_handle (const char *wfname)
int COM_get_status (const char *waname, const int pane_id)
Function management
void COM_set_function (const char *wf_str, Func_ptr func, const char *intents, const COM_Type *types)
void COM_set_member_function (const char *wf_str, Func_ptr func, const char *wa_str, const char *intents, const COM_Type *types)
void COM_call_function (const int wf, int argc,...)
void COM_icall_function (const int wf, int argc,...)
void COM_wait (const int id)
int COM_test (const int id)
Tracing and profiling tools
void COM_set_verbose (int i)
void COM_set_profiling (int i)
void COM_set_profiling_barrier (int hdl, MPI_Comm comm)
void COM_print_profile (const char *fname, const char *header)
Miscellaneous
int COM_get_sizeof (const COM_Type type, int c)
int COM_compatible_types (COM_Type type1, COM_Type type2)
int COM_get_error_code ()
Macro Definition Documentation
#define LOAD_MODULE_WRAPPER (mixed, lower, UPPER)
Value:
\
  void mixed ## _load_module( const char * mod) {                       \
    extern void COM_F_FUNC2( lower ## _load_module, UPPER ## _LOAD_MODULE) \
      ( const char *mod, long int len);                                 \
                                                                        \
    long int len = strlen(mod);                                         \
    COM_F_FUNC2( lower ## _load_module, UPPER ## _LOAD_MODULE)          \
      ( mod, len);                                                      \
  }                                                                     \
                                                                        \
  void mixed ## _unload_module( const char * mod) {                     \
    extern void COM_F_FUNC2( lower ## _unload_module, UPPER ## _UNLOAD_MODULE) \
      ( const char *mod, long int len);                                 \
                                                                        \
    long int len = strlen(mod);                                         \
    COM_F_FUNC2( lower ## _unload_module, UPPER ## _UNLOAD_MODULE)      \
      ( mod, len);                                                      \
  }
Definition at line 27 of file com_c.h.
Function Documentation
void COM_abort (int ierr) inline
Definition at line 41 of file com_c++.hpp.
References COM::COM_base::abort().
 { COM::COM_base::abort( ierr); }
void COM_allocate_array (const char * wa_str, int pane_id, void ** addr, int strd, int cap) inline
Allocate for all panes if pane-id is 0, in which case, do not set addr.
Definition at line 173 of file com_c++.hpp.
References COM::COM_base::allocate_array(), and COM_get_com().
Referenced by RFC_Window_overlay::print_features(), MSH_Reader::read_pane_coors(), OBJ_Reader::read_pane_coors(), SMF_Reader::read_pane_coors(), OFF_Reader::read_pane_coors(), Neutral_Reader::read_pane_coors(), IM_Reader::read_pane_coors(), OBJ_Reader::read_pane_elems(), OFF_Reader::read_pane_elems(), MSH_Reader::read_pane_elems(), Neutral_Reader::read_pane_elems(), SMF_Reader::read_pane_elems(), IM_Reader::read_pane_elems(), and RFC_Pane_base::register_sdv_dataitems().
 { COM_get_com()->allocate_array( wa_str, pane_id, addr, strd, cap); }
void COM_append_array (const char * wa_str, int pane_id, const void * val, int v_strd, int v_size) inline
Definition at line 191 of file com_c++.hpp.
References COM::COM_base::append_array(), and COM_get_com().
Referenced by RFC_Pane_base::register_sdv_dataitems().
 { COM_get_com()->append_array( wa_str, pane_id, val, v_strd, v_size); }
void COM_call_function (const int wf, int argc, ...)
Definition at line 30 of file com_c.C.
References COM::COM_base::call_function(), COM_assertion_msg, COM_get_com(), and Function::MAX_NUMARG.
{
   COM_assertion_msg( argc <= Function::MAX_NUMARG, "Too many arguments") ;
   int i;
   void *args[Function::MAX_NUMARG];
   va_list   ap;
   va_start( ap, argc);
   for ( i=0; i<argc; ++i) {
     args[i] = va_arg( ap, void*);
   }
   va_end( ap);
   COM_get_com()->call_function( wf, argc, args);
 }
int COM_check_bounds (const char * wa_str, int pane_id) inline
Definition at line 297 of file com_c++.hpp.
References COM::COM_base::check_bounds(), and COM_get_com().
 { return COM_get_com()->check_bounds( wa_str, pane_id); }
void COM_clone_dataitem (const char * wname, const char * attr, int with_ghost, const char * ptnname, int val) inline
Definition at line 211 of file com_c++.hpp.
References COM::COM_base::clone_dataitem(), and COM_get_com().
Referenced by CloneDataItem::create(), FluidAgent::create_buffer_all(), BurnAgent::create_buffer_all(), SolidAgent::create_buffer_all(), read_file(), read_file_rocin(), SolverUtils::TransferObjectPar::read_file_rocin(), FluidAgent::read_restart_data(), and SolidAgent::read_restart_data().
 { COM_get_com()->clone_dataitem(wname, attr, wg, ptnname, val); }
int COM_compatible_types (COM_Type type1, COM_Type type2) inline
Definition at line 612 of file com_c++.hpp.
Referenced by Rocblas::axpy_gen(), Rocblas::calc(), Rocblas::calcDot(), Rocsurf::compute_element_areas(), Window_manifold_2::compute_normals(), Pane_boundary::determine_borders(), Window_manifold_2::elements_to_nodes(), Rocblas::gen2arg(), Rocsurf::integrate(), Window_manifold_2::shortest_edge_length(), Window_manifold_2::update_bd_flags(), Window_manifold_2::update_bd_normals(), and Window_manifold_2::update_bdedge_bitmap().
 { return COM::DataItem::compatible_types( type1, type2); }
void COM_copy_array (const char * wa_str, int pane_id, void * val, int v_strd, int v_size, int offset) inline
Definition at line 288 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::copy_array().
Referenced by read_pane_sp(), and RFC_Pane_base::read_rocin().
 { COM_get_com()->copy_array( wa_str, pane_id, val, v_strd, v_size, offset); }
void COM_copy_dataitem (const char * wname, const char * attr, int with_ghost, const char * ptnname, int val) inline
Definition at line 221 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::copy_dataitem().
Referenced by TemperatureTransfer_SF::run(), HeatTransfer_FS::run(), CopyBurnFromParentMesh::run(), CopyBflagFromBurn::run(), and Agent::store_solutions().
 { COM_get_com()->copy_dataitem(wname, attr, wg, ptnname, val); }
void COM_copy_dataitem_handles (int trg_hdl, int src_hdl, int with_ghost, int ptn_hdl, int val)
void COM_deallocate_array (const char * wa_str, const int pid) inline
Definition at line 239 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::deallocate_array().
 { COM_get_com()->deallocate_array(wa_str, pid); }
void COM_delete_dataitem (const char * wa_str) inline
Definition at line 105 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::delete_dataitem().
Referenced by main(), read_file(), read_file_rocin(), and IM_Reader::read_winmesh().
 { COM_get_com()->delete_dataitem( wa_str); }
void COM_delete_pane (const char * w_str, const int pane_id) inline
Definition at line 87 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::delete_pane().
Referenced by read_file(), read_file_rocin(), and RFC_Window_base::write_sdv().
 { COM_get_com()->delete_pane( str, pid) ; }
void COM_delete_window (const char * str) inline
Definition at line 71 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::delete_window().
Referenced by SolidAgent::create_buffer_all(), SolverUtils::DestroySolver(), FluidAgent::finalize(), BurnAgent::finalize(), Rocblas::finalize(), SolidAgent::finalize(), Rocout::finalize(), Rocin::finalize(), getWindow(), BurnAgent::init_module(), FluidAgent::init_module(), SolidAgent::init_module(), RFC_Window_transfer::init_recv_buffer(), main(), SolverUtils::TransferObjectPar::Overlay(), RFC_Window_overlay::print_features(), Control_parameters::read(), RocmanControl_parameters::read(), read_file(), read_file_rocin(), SolverUtils::TransferObjectPar::read_file_rocin(), read_pane_sp(), RFC_Window_base::read_sdv(), COM::ParallelTestingObject< CommType, ResultsType >::Test__GetSetCommunicator(), COM::ParallelTestingObject< CommType, ResultsType >::Test__WindowGetSetCommunicator(), TestModule_unload_module(), Rocsurf::unload(), Rocmap::unload(), COM::TestModule::Unload(), and RFC_Window_base::write_sdv().
 { COM_get_com()->delete_window(wname); }
void COM_finalize () inline
Definition at line 36 of file com_c++.hpp.
References COM::COM_base::finalize().
Referenced by SolverUtils::FinalizeInterface(), main(), COM::ParallelTest(), RocstarShutdown(), and COM::Test().
 { COM::COM_base::finalize(); }
void COM_free_buffer (char ** buf) inline
Definition at line 378 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::free_buffer().
 { COM_get_com()->free_buffer( buf); }
void COM_get_array (const char * wa_str, int pane_id, void ** addr, int * strd, int * cap)
Referenced by SolverUtils::AgentToPane(), broadcast_win_dataitems(), COM_print_window(), debug_int_print(), debug_print(), getPaneConnectivity(), HeatTransfer_FS::init(), load_data_HDF4(), main(), SolverUtils::PaneToUnstructuredMesh(), SolverUtils::PopulateSolutionDataFromPane(), read_file(), read_file_rocin(), SolverUtils::SurfaceMeshToPane(), COM::TestingObject< ResultsType >::Test__DataItemManagement(), COM::TestingObject< ResultsType >::Test__LinearDataTransfer(), COM::TestingObject< ResultsType >::Test__QuadraticDataTransfer(), SolverUtils::UpdateAgentCoordinatesFromPane(), and SolverUtils::VolumeMeshToPane().
void COM_get_bounds (const char * wa_str, int pane_id, void * lbound, void * ubound) inline
Definition at line 293 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::get_bounds().
 { COM_get_com()->get_bounds( wa_str, pane_id, lbound, ubound); }
void COM_get_communicator (const char * wname, MPI_Comm * comm) inline
Definition at line 323 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::get_communicator().
Referenced by COM::TestModule::get_communicator_module(), COM::ParallelTestingObject< CommType, ResultsType >::Test__GetSetCommunicator(), and COM::ParallelTestingObject< CommType, ResultsType >::Test__ParallelModuleLoadingTest().
 { *comm = COM_get_com()->get_communicator( wname); }
void COM_get_connectivities (const char * wname, int pane_id, int * nc, char ** names) inline
Definition at line 362 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::get_connectivities().
{
   std::string str;
   COM_get_com()->get_connectivities( wname, pane_id, nc, str, names);
 }
void COM_get_dataitem (const char * wa_str, char * loc, int * type, int * ncomp, char * unit, int n)
Information retrieval Get the information about an dataitem.
The opposite of set_size.
The opposite of new_dataitem.
Definition at line 62 of file com_c.C.
References COM_get_com(), COM::COM_base::get_dataitem(), max(), and min().
 {
   std::string unit;
   COM_get_com()->get_dataitem( wa_str, loc, type, size, &unit);
   if ( u_str && u_len) {
     int len=unit.size(), n=std::min(len, int(u_len));
     std::copy( unit.c_str(), unit.c_str()+n, u_str);
     std::fill_n( u_str+1+n, std::max(0,int(u_len-len)), 0);
   }
 }
int COM_get_dataitem_handle (const char * waname) inline
Definition at line 389 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::get_dataitem_handle().
Referenced by COM_print_window(), compute_overlay(), NewDataItem::create(), CloneDataItem::create(), UseDataItem::create(), BurnAgent::create_buffer_all(), FluidAgent::create_buffer_all(), SolidAgent::create_buffer_all(), Action::get_dataitem_handle(), InterpolateBase::init(), Extrapolate_Linear::init(), Extrapolate_Central::init(), LoadTransfer_FSc_ALE::init(), GetDeformedMesh_ALE::init(), MeshMotionTransfer_SF::init(), ComputeFluidLoad_ALE::init(), ComputeMeshMotion::init(), MeshMotionTransferISS::init(), FluidPropagateSurface::init(), TransferBurnRate_FS_ALE::init(), MassTransfer_SF_ALE::init(), MassTransfer::init(), ZoomInterface::init(), HeatTransfer_FS::init(), ComputeRhofvf::init(), ComputeBurnPane::init(), SolidPropagateSurface_ALE::init(), Reset_du_alp::init(), RFC_Window_transfer::init_recv_buffer(), SolverUtils::TransferObject::Interpolate(), SolverUtils::TransferObjectPar::Interpolate(), main(), SolverUtils::TransferObject::Overlay(), SolverUtils::TransferObjectPar::Overlay(), read_file(), read_file_rocin(), SolverUtils::TransferObjectPar::read_file_rocin(), read_pane_sp(), BurnAgent::read_restart_data(), FluidAgent::read_restart_data(), SolidAgent::read_restart_data(), RFC_Pane_base::read_rocin(), RFC_Window_base::read_sdv(), IM_Reader::read_winmesh(), SurfDiver::run(), ComputeFaceCenters::run(), COM::TestingObject< ResultsType >::Test__DataItemManagement(), SolverUtils::TransferObject::Transfer(), SolverUtils::TransferObjectPar::Transfer(), SolverUtils::TransferObject::TransferLoad(), SolverUtils::TransferObjectPar::TransferLoad(), Agent::write_data_files(), and RFC_Window_base::write_sdv().
 { return COM_get_com()->get_dataitem_handle( waname); }
int COM_get_dataitem_handle_const (const char * waname) inline
Definition at line 397 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::get_dataitem_handle_const().
Referenced by _load_rocface(), BurnAgent::create_buffer_all(), SolidAgent::create_buffer_all(), Action::get_dataitem_handle_const(), InterpolateBase::init(), LoadTransfer_FS::init(), LoadTransfer_FSc_ALE::init(), SurfDiver::init(), ComputeFluidLoad_ALE::init(), BurnAgent::init_module(), main(), RFC_Window_overlay::print_features(), FluidAgent::read_restart_data(), BurnAgent::read_restart_data(), and SolidAgent::read_restart_data().
 { return COM_get_com()->get_dataitem_handle_const( waname); }
void COM_get_dataitems (const char * wname, int * na, char ** names) inline
Definition at line 356 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::get_dataitems().
{
   std::string str;
   COM_get_com()->get_dataitems( wname, na, str, names);
 }
MPI_Comm COM_get_default_communicator () inline
Definition at line 46 of file com_c++.hpp.
References COM::COM_base::get_default_communicator().
Referenced by compute_overlay(), COM::TestModule::get_communicator_module(), Rocin::read_by_control_file(), Rocin::read_windows(), SurfDiver::run(), COM::ParallelTestingObject< CommType, ResultsType >::Test__GetSetCommunicator(), COM::ParallelTestingObject< CommType, ResultsType >::Test__WindowGetSetCommunicator(), and Rocout::write_rocin_control_file().
 { return COM::COM_base::get_default_communicator(); }
int COM_get_error_code () inline
Definition at line 615 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::get_error_code().
 { return COM_get_com()->get_error_code(); }
int COM_get_function_handle (const char * wfname) inline
Definition at line 405 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::get_function_handle().
Referenced by _load_rocface(), compute_overlay(), Agent::create_window(), COM::TestModule::Function2(), COM::TestModule::Function4(), getPaneConnectivity(), getWindow(), LoadTransfer_FS::init(), LoadTransfer_FSc_ALE::init(), LoadTransferOnly_FSc_ALE::init(), SurfDiver::init(), GetDeformedMesh_ALE::init(), MeshMotionTransfer_SF::init(), DeformationVelTransfer_SF::init(), MeshMotionTransferISS::init(), TransferSolidDensity::init(), FluidPropagateSurface::init(), TransferBurnRate_FS_ALE::init(), MassTransfer_SF_ALE::init(), TemperatureTransfer_SF::init(), HeatTransfer_FS::init(), RemeshInit::init(), ComputePconn::init(), SolidPropagateSurface_ALE::init(), Agent::init_function_handles(), RFC_Window_transfer::init_recv_buffer(), RocBlas::initHandles(), load_rocon(), load_rocprop(), main(), RFC_Window_overlay::print_features(), Control_parameters::read(), RocmanControl_parameters::read(), read_file(), read_file_rocin(), SolverUtils::TransferObjectPar::read_file_rocin(), read_pane_sp(), RFC_Window_base::read_sdv(), IM_Reader::read_winmesh(), ComputeFaceCenters::run(), SolverUtils::TransferObject::SetVerbosity(), SolverUtils::TransferObjectPar::SetVerbosity(), COM::TestingObject< ResultsType >::Test__DataItemManagement(), COM::ParallelTestingObject< CommType, ResultsType >::Test__FunctionBarrierTest(), COM::TestingObject< ResultsType >::Test__ModuleFunctionTest(), COM::ParallelTestingObject< CommType, ResultsType >::Test__ModuleGetSetCommunicator(), COM::TestingObject< ResultsType >::Test__ModuleLoadingTest(), COM::ParallelTestingObject< CommType, ResultsType >::Test__ParallelModuleLoadingTest(), SolverUtils::TransferObject::TransferObject(), SolverUtils::TransferObjectPar::TransferObjectPar(), Control_parameters::update_communicator(), FullyCoupling::update_distances(), and RFC_Window_base::write_sdv().
 { return COM_get_com()->get_function_handle( wfname); }
void COM_get_panes (const char * wname, int * npanes, int ** pane_ids, int rank) inline
Definition at line 349 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::get_panes().
{
   std::vector<int> vec;
   COM_get_com()->get_panes( wname, vec, rank, pane_ids);
   if ( npanes) *npanes = vec.size();
 }
void COM_get_parent (const char * waname, int pane_id, char ** parent) inline
Definition at line 368 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::get_parent().
{
   std::string str;
   COM_get_com()->get_parent( waname, pane_id, str, parent);
 }
void COM_get_size (const char * wa_str, int pane_id, int * size, int * ng) inline
The opposite of set_size.
Definition at line 251 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::get_size().
Referenced by COM_print_window(), getPaneConnectivity(), main(), read_pane_sp(), RFC_Pane_base::read_rocin(), and COM::TestingObject< ResultsType >::Test__DataItemManagement().
 { COM_get_com()->get_size( wa_str, pane_id, size, ng); }
int COM_get_sizeof (const COM_Type type, int c) inline
Definition at line 609 of file com_c++.hpp.
References get_sizeof().
Referenced by Window_manifold_2::accumulate_bd_values(), Node::addr(), Halfedge::addr(), Pane_communicator::begin_update(), broadcast_win_dataitems(), Pane_communicator::init(), Pane_communicator::reduce_average_on_shared_nodes(), Pane_communicator::reduce_diff_on_shared_nodes(), Pane_communicator::reduce_maxabs_on_shared_nodes(), Pane_communicator::reduce_minabs_on_shared_nodes(), Pane_communicator::reduce_on_shared_nodes(), Element_node_vectors_k_const< Value >::set(), Element_vectors_k_const< Value >::set(), and Pane_communicator::update_ghost_values().
 { return COM::DataItem::get_sizeof( type, c); }
int COM_get_status (const char * waname, const int pane_id) inline
Definition at line 408 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::get_status().
Referenced by load_data_HDF4().
 { return COM_get_com()->get_status( waname, pane_id); }
int COM_get_window_handle (const char * wname) inline
Definition at line 381 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::get_window_handle().
Referenced by _load_rocface(), DataItemBase::assign(), COM::TestModule::Function2(), COM::TestModule::Function4(), Extrapolate_Central::init(), FluidPropagateSurface::init(), SolidPropagateSurface_ALE::init(), load_rocmap(), load_rocon(), load_rocprop(), load_rocsurf(), SolverUtils::PopulateSolverAgentFromWindow(), Neutral_Reader::read_mesh(), OBJ_Reader::read_mesh(), MSH_Reader::read_mesh(), SMF_Reader::read_mesh(), OFF_Reader::read_mesh(), IM_Reader::read_mesh(), Rocin::read_parameter_file(), Coupling::restart_at_time(), Agent::split_surface_window(), COM::ParallelTestingObject< CommType, ResultsType >::Test__FunctionBarrierTest(), COM::TestingObject< ResultsType >::Test__ModuleFunctionTest(), COM::ParallelTestingObject< CommType, ResultsType >::Test__ModuleGetSetCommunicator(), COM::TestingObject< ResultsType >::Test__ModuleLoadingTest(), COM::ParallelTestingObject< CommType, ResultsType >::Test__ParallelModuleLoadingTest(), COM::ParallelTestingObject< CommType, ResultsType >::Test__WindowGetSetCommunicator(), Rocout::write_parameter_file(), and COM::TestModule::~TestModule().
 { return COM_get_com()->get_window_handle( wname); }
void COM_icall_function (const int wf, int argc, ...)
Definition at line 46 of file com_c.C.
References COM_assertion_msg, COM_get_com(), COM::COM_base::icall_function(), and Function::MAX_NUMARG.
{
   COM_assertion_msg( argc <= Function::MAX_NUMARG, "Too many arguments") ;
   int i;
   void *args[Function::MAX_NUMARG];
   va_list   ap;
   va_start( ap, argc);
   for ( i=0; i<argc-1; ++i) {
     args[i] = va_arg( ap, void*);
   }
   int *status = va_arg( ap, int *);
   va_end( ap);
   COM_get_com()->icall_function( wf, argc, args, status);
 }
void COM_init (int * argc, char *** argv) inline
Definition at line 34 of file com_c++.hpp.
References COM::COM_base::init().
Referenced by SolverUtils::InitializeInterface(), main(), COM::ParallelTest(), and COM::Test().
 { COM::COM_base::init( argc, argv); }
int COM_initialized () inline
Definition at line 39 of file com_c++.hpp.
References COM::COM_base::initialized().
Referenced by COM::ParallelTest(), and COM::Test().
 { return COM::COM_base::initialized(); }
void COM_load_module (const char * libname, const char * winname) inline
Definition at line 52 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::load_module().
Referenced by BurnAgent::load_module(), FluidAgent::load_module(), SolidAgent::load_module(), and main().
 { COM_get_com()->load_module( libname, winname); }
void COM_new_dataitem (const char * wa_str, const char loc, const int type, int ncomp, const char * unit) inline
wa_str is the dataitem's name in the format "window.dataitem". loc is the code for the location of the data, which can be 'w' for window dataitem, 'p' for pane dataitem, 'n' for node dataitem, or 'e' for element dataitem. type is the data type of the dataitem. For C/C++, it can be COM_CHAR, COM_UNSIGNED_CHAR, COM_BYTE, COM_SHORT, COM_UNSIGNED_SHORT, COM_INT, COM_UNSIGNED, COM_LONG, COM_UNSIGNED_LONG, COM_FLOAT0, COM_DOUBLE1, COM_LONG_DOUBLE, COM_LONG_LONG_INT, or a derived data type. For Fortran, it can be COM_CHARACTER, COM_INTEGER, COM_LOGICAL, COM_REAL, COM_DOUBLE_PRECISION, COM_COMPLEX, COM_DOUBLE_COMPLEX. size is the length of the dataitem in the given data type
Definition at line 95 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::new_dataitem().
Referenced by Coupling::baseInit(), NewDataItem::create(), FluidAgent::create_buffer_all(), SolidAgent::create_buffer_all(), Agent::create_window(), SolverUtils::CreateDataItemsFromSolution(), Rocout::init(), Rocin::init(), Rocsurf::load(), COM::TestModule::Load(), main(), makeWindow(), COM::TestingObject< ResultsType >::MakeWindow(), new_dataitems(), RFC_Window_base::new_sdv_dataitems(), RFC_Window_overlay::print_features(), Rocin::read_parameter_file(), Rocin::register_panes(), and COM::TestingObject< ResultsType >::Test__DataItemManagement().
 { COM_get_com()->new_dataitem( wa_str, loc, type, ncomp, unit); }
void COM_new_window (const char * w_str, MPI_Comm c) inline
Definition at line 63 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::new_window().
Referenced by Coupling::baseInit(), convertWindow(), BurnAgent::create_buffer_all(), FluidAgent::create_buffer_all(), SolidAgent::create_buffer_all(), Agent::create_buffer_all(), Agent::create_window(), getWindow(), Rocblas::init(), Rocout::init(), Rocin::init(), FluidAgent::input(), BurnAgent::input(), Rocsurf::load(), Rocmap::load(), COM::TestModule::Load(), main(), makeWindow(), COM::TestingObject< ResultsType >::MakeWindow(), RFC_Window_overlay::print_features(), Control_parameters::read(), RocmanControl_parameters::read(), read_file(), read_file_rocin(), SolverUtils::TransferObjectPar::read_file_rocin(), Neutral_Reader::read_mesh(), OBJ_Reader::read_mesh(), MSH_Reader::read_mesh(), SMF_Reader::read_mesh(), OFF_Reader::read_mesh(), IM_Reader::read_mesh(), Rocin::read_parameter_file(), Rocin::read_windows(), SolverUtils::RegisterSolver(), Agent::split_surface_window(), COM::TestingObject< ResultsType >::Test__DataItemManagement(), COM::ParallelTestingObject< CommType, ResultsType >::Test__GetSetCommunicator(), COM::ParallelTestingObject< CommType, ResultsType >::Test__WindowGetSetCommunicator(), TestModule_load_module(), and RFC_Window_base::write_sdv().
 { COM_get_com()->new_window(wname, c); }
void COM_print_profile (const char * fname, const char * header) inline
Definition at line 606 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::print_profile().
Referenced by main(), and rocstar_driver().
 { COM_get_com()->print_profile( fname, header); }
void COM_resize_array (const char * wa_str, int pane_id, void ** addr, int strd, int cap) inline
Resize for all panes if pane-id is 0, in which case, do not set addr. The difference between resize and allocate is that resize will reallocate memory only if the current array cannot accomodate the requested capacity.
Definition at line 177 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::resize_array().
Referenced by SolverUtils::AgentToPane(), NewDataItem::create(), FluidAgent::create_buffer_all(), SolidAgent::create_buffer_all(), load_data_HDF4(), main(), new_dataitems(), Rocin::read_parameter_file(), IM_Reader::read_winmesh(), SolverUtils::SurfaceMeshToPane(), and SolverUtils::VolumeMeshToPane().
 { COM_get_com()->resize_array( wa_str, pane_id, addr, strd, cap); }
void COM_set_array (const char * wa_str, int pane_id, void * addr, int strd, int cap) inline
Definition at line 133 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::set_array().
Referenced by add_ghost_nodes2D(), SolverUtils::AgentToPane(), SolverUtils::CreateDataItemsFromSolution(), main(), IM_Reader::read_pane_ij(), Rocin::register_panes(), SolverUtils::SurfaceMeshToPane(), COM::TestingObject< ResultsType >::Test__DataItemManagement(), and SolverUtils::VolumeMeshToPane().
 { COM_get_com()->set_array( wa_str, pane_id, addr, strd, cap); }
void COM_set_bounds (const char * wa_str, int pane_id, const void * lbound, const void * ubound) inline
Definition at line 153 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::set_bounds().
 { COM_get_com()->set_bounds( wa_str, pane_id, lbound, ubound); }
void COM_set_default_communicator (MPI_Comm comm) inline
Definition at line 44 of file com_c++.hpp.
References COM::COM_base::set_default_communicator().
Referenced by compute_overlay(), main(), SolverUtils::TransferObjectPar::Overlay(), SurfDiver::run(), COM::ParallelTestingObject< CommType, ResultsType >::Test__FunctionBarrierTest(), COM::ParallelTestingObject< CommType, ResultsType >::Test__GetSetCommunicator(), COM::ParallelTestingObject< CommType, ResultsType >::Test__ModuleGetSetCommunicator(), COM::ParallelTestingObject< CommType, ResultsType >::Test__ParallelModuleLoadingTest(), COM::ParallelTestingObject< CommType, ResultsType >::Test__WindowGetSetCommunicator(), and Control_parameters::update_communicator().
 { COM::COM_base::set_default_communicator( comm); }
void COM_set_function (const char * wf_str, Func_ptr func, const char * intents, const COM_Type * types) inline
Definition at line 300 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::set_function().
Referenced by Rocblas::init(), Rocsurf::load(), Rocmap::load(), and COM::TestModule::Load().
 { COM_get_com()->set_function( wf_str, func, intents, types); }
void COM_set_member_function (const char * wf_str, Func_ptr func, const char * wa_str, const char * intents, const COM_Type * types) inline
Definition at line 316 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::set_member_function().
 { COM_get_com()->set_member_function( wf_str, func, wa_str, intents, types); }
void COM_set_profiling (int i) inline
Definition at line 599 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::set_profiling().
Referenced by compute_overlay(), main(), rocstar_driver(), and SurfDiver::run().
 { COM_get_com()->set_profiling( i); }
void COM_set_profiling_barrier (int hdl, MPI_Comm comm) inline
Definition at line 603 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::set_profiling_barrier().
Referenced by _load_rocface(), Agent::init_function_handles(), load_rocprop(), and main().
 { COM_get_com()->set_profiling_barrier( hdl, comm); }
void COM_set_size (const char * wa_str, int pane_id, int size, int ng) inline
Definition at line 113 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::set_size().
Referenced by SolverUtils::AgentToPane(), SolverUtils::CreateDataItemsFromSolution(), main(), new_dataitems(), MSH_Reader::read_pane_coors(), OBJ_Reader::read_pane_coors(), SMF_Reader::read_pane_coors(), OFF_Reader::read_pane_coors(), Neutral_Reader::read_pane_coors(), IM_Reader::read_pane_coors(), OBJ_Reader::read_pane_elems(), OFF_Reader::read_pane_elems(), MSH_Reader::read_pane_elems(), SMF_Reader::read_pane_elems(), Neutral_Reader::read_pane_elems(), IM_Reader::read_pane_elems(), Rocin::read_parameter_file(), Rocin::register_panes(), RFC_Pane_base::register_sdv_dataitems(), SolverUtils::SurfaceMeshToPane(), COM::TestingObject< ResultsType >::Test__DataItemManagement(), and SolverUtils::VolumeMeshToPane().
 { COM_get_com()->set_size( wa_str, pane_id, size, ng); }
void COM_set_verbose (int i) inline
Definition at line 595 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::set_verbose().
Referenced by main(), and rocstar_driver().
 { COM_get_com()->set_verbose( i); }
int COM_test (const int id) inline
Definition at line 592 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::test().
 { return COM_get_com()->test( id); }
void COM_unload_module (const char * libname, const char * winname) inline
Definition at line 55 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::unload_module().
Referenced by BurnAgent::unload_module(), FluidAgent::unload_module(), and SolidAgent::unload_module().
 { COM_get_com()->unload_module( libname, winname?winname:""); }
void COM_use_dataitem (const char * wname, const char * attr, int with_ghost, const char * ptnname, int val) inline
Definition at line 201 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::use_dataitem().
Referenced by DataItemBase::assign(), UseDataItem::create(), BurnAgent::create_buffer_all(), FluidAgent::create_buffer_all(), SolidAgent::create_buffer_all(), Agent::create_buffer_all(), BurnAgent::init_module(), RFC_Window_overlay::print_features(), and Agent::split_surface_window().
 { COM_get_com()->use_dataitem(wname, attr, wg, ptnname, val); }
void COM_wait (const int id) inline
Definition at line 589 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::wait().
 { COM_get_com()->wait( id); }
void COM_window_init_done (const char * w_str, int pane_changed) inline
Definition at line 79 of file com_c++.hpp.
References COM_get_com(), and COM::COM_base::window_init_done().
Referenced by compute_overlay(), convertWindow(), BurnAgent::create_buffer_all(), FluidAgent::create_buffer_all(), SolidAgent::create_buffer_all(), Agent::create_buffer_all(), Agent::create_registered_dataitems(), Agent::create_window(), getWindow(), Rocblas::init(), Rocout::init(), Rocin::init(), BurnAgent::init_module(), FluidAgent::input(), BurnAgent::input(), Rocsurf::load(), Rocmap::load(), COM::TestModule::Load(), main(), SolverUtils::TransferObjectPar::Overlay(), RFC_Window_overlay::print_features(), Control_parameters::read(), RocmanControl_parameters::read(), read_file(), Rocin::read_parameter_file(), Rocin::read_windows(), RFC_Pane_base::register_sdv_dataitems(), SolverUtils::RegisterSolver(), SolverUtils::RegisterSolverInto(), SurfDiver::run(), Agent::split_surface_window(), TestModule_load_module(), and RFC_Window_base::write_sdv().
 { COM_get_com()->window_init_done( w_str, pane_changed); }