IMPACT: COM_base.hpp File Reference
COM_base.hpp File Reference
Contains declaration of the base class for COM implementations.
Detailed Description
See Also
COM_base.C
Definition in file COM_base.hpp.
#include "com_devel.hpp"
#include "maps.hpp"
#include <set>
Classes
class COM::COM_base
The base class for COM implementations.
Namespaces
COM
This file indirectly includes the following files: iostream, map, string, vector, and com_basic.h.
Functions
COM::COM_base * COM_get_com ()
void COM_set_com (COM::COM_base *p)
Function Documentation
COM::COM_base* COM_get_com () inline
Definition at line 501 of file COM_base.hpp.
References COM_assertion_msg, and COM::COM_base::get_com().
Referenced by COM_allocate_array(), COM_append_array(), com_append_array_helper(), COM_call_function(), COM_check_bounds(), COM_clone_dataitem(), COM_close_module(), COM_copy_array(), COM_copy_dataitem(), COM_deallocate_array(), COM_delete_dataitem(), COM_delete_pane(), COM_delete_window(), COM_F_FUNC2(), COM_free_buffer(), COM_get_bounds(), COM_get_communicator(), COM_get_connectivities(), COM_get_dataitem(), COM_get_dataitem_handle(), COM_get_dataitem_handle_const(), COM_get_dataitems(), COM_get_error_code(), COM_get_function_handle(), COM_get_modules(), COM_get_object(), COM_get_panes(), COM_get_parent(), COM_get_size(), COM_get_status(), COM_get_window_handle(), COM_get_windows(), COM_icall_function(), COM_load_module(), COM_new_dataitem(), COM_new_window(), com_obtain_array_helper(), COM_print_profile(), COM_resize_array(), COM_set_array(), COM_set_array_const(), com_set_array_const_helper(), com_set_array_helper(), COM_set_bounds(), COM_set_function(), COM_set_member_function(), COM_set_object(), COM_set_profiling(), COM_set_profiling_barrier(), COM_set_size(), COM_set_verbose(), COM_test(), COM_unload_module(), COM_use_dataitem(), COM_wait(), COM_window_init_done(), Rocin::read_parameter_file(), RFC_Pane_base::read_rocin(), COM::ParallelTestingObject< CommType, ResultsType >::Test__WindowGetSetCommunicator(), and Rocout::write_parameter_file().
 { COM::COM_base *com=COM::COM_base::get_com();
   COM_assertion_msg(com,
                     "COM must be initialized before any COM calls.");
   return com;
 }
void COM_set_com (COM::COM_base * p) inline
Definition at line 508 of file COM_base.hpp.
References COM::COM_base::set_com().
 { COM::COM_base::set_com(p); }