IMPACT: commpi.C File Reference
commpi.C File Reference
Contains a dummy implementation of MPI subroutines for one thread.
Detailed Description
If DUMMY_MPI is not define, it does produce anything. Note: This implementation is not thread-safe and it need not to be because it is only intended for a placeholder of MPI for one thread. It works even if MPI_Init was not called.
See also
commpi.h
Definition in file commpi.C.
#include "commpi.h"
#include <cstring>
#include <cstdlib>
#include <iostream>
#include <map>
Typedefs
typedef std::map< int, void * > Msg_Queue
A map from message tags to data addresses.
Functions
static int get_sizeof (MPI_Datatype i) throw (int)
Get the size of a given MPI data type.
int COM_send (Msg_Queue &sendQ, Msg_Queue &recvQ, void *buf, int count, MPI_Datatype datatype, int tag)
int COM_recv (Msg_Queue &sendQ, Msg_Queue &recvQ, void *buf, int count, MPI_Datatype datatype, int tag)
int COMMPI_Isend (void *buf, int count, MPI_Datatype datatype, int dest, int tag, MPI_Comm comm, MPI_Request *request)
Begins a nonblocking send.
int COMMPI_Irecv (void *buf, int count, MPI_Datatype datatype, int src, int tag, MPI_Comm comm, MPI_Request *request)
Begins a nonblocking receive.
Variables
static Msg_Queue * sendQ =NULL
static Msg_Queue * recvQ =NULL
Typedef Documentation
typedef std::map<int, void*> Msg_Queue
Definition at line 72 of file commpi.C.
Function Documentation
int COM_recv (Msg_Queue & sendQ, Msg_Queue & recvQ, void * buf, int count, MPI_Datatype datatype, int tag)
Definition at line 113 of file commpi.C.
References get_sizeof().
Referenced by COMMPI_Irecv().
{
   try {
     Msg_Queue::iterator it;
     if ( (it=sendQ.find( tag)) != sendQ.end()) {
       int extent=count*get_sizeof(datatype);
       std::memcpy( buf, it->second, extent);
       sendQ.erase(it);
     }
     else
       recvQ[tag] = buf;
   }
   catch (int) {
     std::cerr << "Unsupported data type " << datatype
               << " used for MPI_Irecv" << std::endl;
     std::abort();
   }
   return 0;
 }
int COM_send (Msg_Queue & sendQ, Msg_Queue & recvQ, void * buf, int count, MPI_Datatype datatype, int tag)
Definition at line 93 of file commpi.C.
References get_sizeof().
Referenced by COMMPI_Isend().
{
   try {
     Msg_Queue::iterator it;
     if ( (it=recvQ.find( tag)) != recvQ.end()) {
       int extent=count*get_sizeof(datatype);
       std::memcpy( it->second, (char*)buf, extent);
       recvQ.erase(it);
     }
     else
       sendQ[tag] = buf;
   }
   catch (int) {
     std::cerr << "Unsupported data type " << datatype
               << " used for MPI_Isend" << std::endl;
     std::abort();
   }
   return 0;
 }
int COMMPI_Irecv (void * buf, int count, MPI_Datatype datatype, int src, int tag, MPI_Comm comm, MPI_Request * request)
Definition at line 157 of file commpi.C.
References COM_recv(), COMMPI_Comm_rank(), and COMMPI_Initialized().
Referenced by Pane_communicator::begin_update(), and Pane_ghost_connectivity::send_pane_info().
{
 #ifndef DUMMY_MPI
   //  if ( COMMPI_Initialized())
   if ( COMMPI_Initialized() && src!=COMMPI_Comm_rank( comm))
     return MPI_Irecv( buf, count, datatype, src, tag, comm, request);
 #endif
   try {
     if ( sendQ == NULL) sendQ = new Msg_Queue();
     if ( recvQ == NULL) recvQ = new Msg_Queue();
   }
   catch (...) {
     std::cerr << "Out of memory" << std::endl;
     std::abort();
   }
   return COM_recv( *sendQ, *recvQ, buf, count, datatype, tag);
 }
int COMMPI_Isend (void * buf, int count, MPI_Datatype datatype, int dest, int tag, MPI_Comm comm, MPI_Request * request)
Definition at line 137 of file commpi.C.
References COM_send(), COMMPI_Comm_rank(), and COMMPI_Initialized().
Referenced by Pane_communicator::begin_update(), and Pane_ghost_connectivity::send_pane_info().
{
 #ifndef DUMMY_MPI
   //  if ( COMMPI_Initialized())
   if ( COMMPI_Initialized() && dest!=COMMPI_Comm_rank(comm))
     return MPI_Isend( buf, count, datatype, dest, tag, comm, request);
 #endif
   try {
     if ( sendQ == NULL) sendQ = new Msg_Queue();
     if ( recvQ == NULL) recvQ = new Msg_Queue();
   }
   catch (...) {
     std::cerr << "Out of memory" << std::endl;
     std::abort();
   }
   return COM_send( *sendQ, *recvQ, buf, count, datatype, tag);
 }
static int get_sizeof (MPI_Datatype i) throw (int) static
Definition at line 75 of file commpi.C.
Referenced by DataItem::allocate(), COM_get_sizeof(), COM_recv(), COM_send(), DataItem::copy_array(), DataItem::inherit(), io_hdf_data(), io_pane_dataitem(), COM::COM_base::set_f90pointer(), DataItem::set_pointer(), and write_attr_CGNS().
{
   if(i == MPI_DOUBLE)      return sizeof(double);
   else if (i == MPI_FLOAT) return sizeof(float);
   else if (i == MPI_INT)   return sizeof(int);
   else if (i == MPI_BYTE)  return sizeof(char);
   else if (i == MPI_CHAR)  return sizeof(char);
   else throw(-1);
   //static int get_sizeof( int i) throw(int) {
   //  switch (i) {
   //  case MPI_DOUBLE: return sizeof(double);
   //  case MPI_FLOAT:  return sizeof(float);
   //  case MPI_INT:    return sizeof(int);
   //  case MPI_BYTE:   return sizeof(char);
   //  case MPI_CHAR:   return sizeof(char);
   //  default: throw(-1);
   //  }
 }
Variable Documentation
Msg_Queue* recvQ =NULL static
Definition at line 134 of file commpi.C.
Msg_Queue* sendQ =NULL static
Definition at line 133 of file commpi.C.