IMPACT: ComponentInterface.C File Reference
ComponentInterface.C File Reference
This file contains the implementation of the ComponentInterface object.
Detailed Description
See also
com_devel.h, COM_base.C
Definition in file ComponentInterface.C.
#include <iostream>
#include <cstdlib>
#include <cstdio>
#include "ComponentInterface.hpp"
#include "com_assertion.h"
Functions
template<class Attr >
void get_size_common (const Attr *a, int pid, int *nitem, int *ng) throw (COM_exception)
template<class Attr >
void get_array_common (const Attr *a, int pid, ComponentInterface::Pointer_descriptor &addr, int *strd, int *cap, bool is_const) throw (COM_exception)
template<class Attr >
void copy_array_common (const Attr *a, int pid, void *val, int v_strd, int v_size, int offset) throw (COM_exception)
Function Documentation
template<class Attr > void copy_array_common (const Attr * a, int pid, void * val, int v_strd, int v_size, int offset) throw (COM_exception) inline
Definition at line 648 of file ComponentInterface.C.
References append_frame, COM_ERR_NOT_A_WINDOW_DATAITEM, and DataItem::COPY_OUT.
Referenced by ComponentInterface::copy_array().
{
   if ( pid==0 && a->location() != 'w')
     throw COM_exception( COM_ERR_NOT_A_WINDOW_DATAITEM, append_frame
                          ( a->fullname(), ComponentInterface::copy_size));
   const_cast<Attr*>(a)->copy_array( val, v_strd, v_size,
                                     offset, DataItem::COPY_OUT);
 }
template<class Attr > void get_array_common (const Attr * a, int pid, ComponentInterface::Pointer_descriptor & addr, int * strd, int * cap, bool is_const) throw (COM_exception)
Definition at line 576 of file ComponentInterface.C.
References addr, append_frame, cap, COM_ERR_DATAITEM_CONST, COM_ERR_INVALID_DIMENSION, COM_ERR_INVALID_SIZE, COM_ERR_NOT_A_WINDOW_DATAITEM, ComponentInterface::get_array(), and strd.
Referenced by ComponentInterface::get_array().
{
   if ( !is_const && a->is_const() )
     throw COM_exception( COM_ERR_DATAITEM_CONST, append_frame
                          (a->fullname(),ComponentInterface::get_array));
   if ( pid==0 && a->location() != 'w')
     throw COM_exception( COM_ERR_NOT_A_WINDOW_DATAITEM, append_frame
                          ( a->fullname(), ComponentInterface::get_array));
   addr.ptr = (void*)(a->pointer());
   if ( addr.dim==1) {
     addr.n1 = a->capacity()*a->stride();
   }
   else if ( addr.dim == 2) {
     if ( a->stride()>=a->size_of_components()) {
       addr.n1 = a->stride();
       addr.n2 = a->capacity();
     }
     else {
       addr.n1 = a->capacity();
       addr.n2 = a->size_of_components();
     }
   }
   else {
     // Scalars must have capacity 1!
     if ( addr.dim==0 && (a->capacity()!=1 || a->size_of_components()!=1))
       throw COM_exception( COM_ERR_INVALID_SIZE, append_frame
                            (a->fullname(),ComponentInterface::get_array));
     if ( addr.dim>2)
       throw COM_exception( COM_ERR_INVALID_DIMENSION, append_frame
                            (a->fullname(),ComponentInterface::get_array));
   }
   if ( cap)  *cap = a->capacity();
   if ( strd) *strd = a->stride();
 }
template<class Attr > void get_size_common (const Attr * a, int pid, int * nitem, int * ng) throw (COM_exception)
Definition at line 467 of file ComponentInterface.C.
References append_frame, COM_ERR_NOT_A_WINDOW_DATAITEM, and ComponentInterface::get_size().
Referenced by ComponentInterface::get_size().
 {
   if ( pid==0 && a->location() != 'w')
     throw COM_exception( COM_ERR_NOT_A_WINDOW_DATAITEM, append_frame
                          ( a->fullname(), ComponentInterface::get_size));
   if ( nitem) *nitem = a->size_of_items();
   if ( ng)    *ng = a->size_of_ghost_items();
 }