IMPACT: IllinoisRocstar Application Development
IllinoisRocstar Application Development
Detailed Description
Files
file CheckResults.H
Performs various checks on numerical test results.
file ComLine.H
ComLineObject header.
file COMM.H
Communication utilities.
file Configuration.H
Configuration object interface (for config files, etc).
file DiffDataFiles.H
Implements a command-line interface for ensuring that two data files are consistent.
file DLTools.H
Dynamic Loading Tools interface.
file FDUtils.H
Implementation of stream object for Unix file descriptors.
file Global.H
Base global object header.
file Menu.H
Text menu system for user interfaces.
file NetUtils.H
TCP/IP Network Utilities Interface.
file Parameters.H
Parameters object interface (for config files, etc)
file primitive_utilities.H
Basic utility header.
file PrimitiveTypes.H
Simple utility classes.
file Profiler.H
Performance Profiling interface definition.
file RunTest.H
Implements a command-line interface for runnning tests.
file Testing.H
Testing constructs for unit testing.
file TestResults.H
Test results utility header.
file UnixUtils.H
Unix System Tools interface.
file UtilTest.H
Testing object for primitive utilities.
file ComLine.C
ComLineObject implementation.
file COMM.C
MPI Communication utils implementation.
file Configuration.C
Configuration object implementation (for config files, etc)
file DiffDataFiles.C
Implements a command-line interface for runnning tests.
file Parameters.C
Parameters object implementation.
file primitive_utilities.C
Primitive utils implementation.
file profane.C
Profile analysis utility implementation.
file Profiler.C
Performance Profiling implementation.
file QuickTest.C
Parallel test program.
file RunTest.C
Implements a command-line interface for runnning tests.
file TestResults.C
Test results utility implementation.
file TestTCPInterface.C
TCP Interface Test utility.
file TestUtil.C
Implementation of the IRAD::Util namespace tests.
file UnixUtils.C
Unix System tools implementation.
Namespaces
IRAD
IllinoisRocstar Application Development.
IRAD::Util
General support utilities.
IRAD::Profiler
Performance profiling.
Classes
class IRAD::TestComLine
ComLineObject for testing app.
class IRAD::TestProgram
Typedefs
typedef
Global::ParallelGlobalObj
< Comm::CommunicatorObject,
std::string, int,
Profiler::ProfilerObj > IRAD::TestGlobal
Functions
int IRAD::Profiler::Profane (int argc, char *argv[])
The performance analysis post processor.
int IRAD::MyTestProgram (int argc, char *argv[])
int IRAD::Util::UtilTest (int argc, char *argv[])
Drives the IRAD::Util namespace's test object.
Typedef Documentation
typedef Global::ParallelGlobalObj<Comm::CommunicatorObject,std::string,int,Profiler::ProfilerObj> IRAD::TestGlobal
Definition at line 65 of file QuickTest.C.
Function Documentation
int IRAD::MyTestProgram (int argc, char * argv[])
Definition at line 117 of file QuickTest.C.
References IRAD::Global::Program< GlobalType, ComLineType >::Finalize(), IRAD::TestProgram::Initialize(), IRAD::Global::GlobalObj< StackType, ErrorType, ProfilerType >::OutStream(), IRAD::Global::Program< GlobalType, ComLineType >::Run(), and IRAD::Global::GlobalObj< StackType, ErrorType, ProfilerType >::StdOut().
Referenced by main().
   {
     TestProgram MyProgram(argc,argv);
     if(MyProgram.Initialize())
       return(1);
     MyProgram.OutStream() << "Calling RUN." << std::endl;
     MyProgram.StdOut("Testing\n");
     if(MyProgram.Run())
       return(1);
     std::cout << "Calling Finalize." << std::endl;
     MyParams params;
     //  MyParams::iterator pi = params.begin();
     //  while(pi != params.end())
     //    std::cout << *pi++ << std::endl;
     std::cout << params << std::endl;
     if(MyProgram.Finalize())
       return(1);
     std::cout << "All done." << std::endl;
     return(0);
   }
int IRAD::Profiler::Profane (int argc, char * argv[])
Definition at line 62 of file profane.C.
References IRAD::Util::ComLineObject::ErrorReport(), IRAD::Util::ComLineObject::GetArgs(), IRAD::Util::ComLineObject::GetOption(), IRAD::Profiler::ProfaneComLine::Initialize(), IRAD::Util::ComLineObject::LongUsage(), IRAD::Profiler::ProfilerObj::PopulateScalaMap(), IRAD::Util::ComLineObject::ProcessOptions(), IRAD::Util::ComLineObject::ProgramName(), IRAD::Profiler::ProfilerObj::ReadConfig(), IRAD::Profiler::ProfilerObj::ReadEventsFromFile(), IRAD::Profiler::ProfilerObj::ReadParallelEventFiles(), IRAD::Profiler::ProfilerObj::ReadSummaryFiles(), IRAD::Profiler::ProfilerObj::ScalabilitySummary(), IRAD::Profiler::ProfilerObj::SetErr(), IRAD::Profiler::ProfilerObj::SetOut(), IRAD::Util::ComLineObject::ShortUsage(), IRAD::Profiler::ProfilerObj::SummarizeParallelExecution(), and IRAD::Profiler::ProfilerObj::SummarizeSerialExecution().
Referenced by main().
{
       ProfaneComLine comline((const char **)argv);
       comline.Initialize();
       int clerr = comline.ProcessOptions();
       std::string cfname = comline.GetOption("config");
       std::string sverb = comline.GetOption("verb");
       bool scalamode = !comline.GetOption("scalability").empty();
       std::string stat_summary_name = comline.GetOption("out");
       bool write_summary_outfile = !stat_summary_name.empty();
       bool is_fixed = !comline.GetOption("fixed").empty();
       if(!comline.GetOption("help").empty()){
         std::cout << comline.LongUsage() << std::endl;
         return(0);
       }
       if(clerr){
         std::cerr << comline.ErrorReport() << std::endl
                   << std::endl << comline.ShortUsage() << std::endl;
         return(1);
       }
       int verblevel = 0;
       if(!sverb.empty() && sverb != ".true."){
         std::istringstream Istr(sverb);
         Istr >> verblevel;
       }
       std::ofstream Ouf;
       if(write_summary_outfile){
         Ouf.open(stat_summary_name.c_str());
         if(!Ouf){
           std::cerr << comline.ProgramName() << "::Error: Could not"
                     << " open output file, " << stat_summary_name
                     << ", for output. Continuing with stdout."
                     << std::endl;
         }
       }
       std::vector<std::string> infiles = comline.GetArgs();
       if(infiles.size()==0) {
         std::cerr << "Profane::Error: No input files specified." << std::endl
                   << std::endl << comline.ShortUsage() << std::endl;
         return(1);
       }
       Profiler::ProfilerObj profiler;
       if(verblevel > 1){
         profiler.SetOut(&std::cout);
         profiler.SetErr(&std::cerr);
       }
       if(cfname.empty()){
         std::string::size_type x = infiles[0].find("prof_");
         cfname.assign(infiles[0].substr(0,x));
         cfname += "rpconfig";
         std::ifstream Inf;
         Inf.open(cfname.c_str());
         if(!Inf)
           cfname.assign("profiler.rpconfig");
         else
           Inf.close();
       }
       if(profiler.ReadConfig(cfname) && !cfname.empty())
         std::cerr << comline.ProgramName()
                   << "::Warning: unable to read config file, " << cfname
                   << ". Continuing without configuration." << std::endl;
       if(!scalamode){
         if(infiles.size() == 1){
           if(profiler.ReadEventsFromFile(infiles[0]))
             exit(1);
           profiler.SummarizeSerialExecution(std::cout);
         }
         else{
           Profiler::PEventList parallel_event_list;
           if(profiler.ReadParallelEventFiles(infiles,parallel_event_list))
             exit(1);
           profiler.SummarizeParallelExecution(std::cout,Ouf,parallel_event_list);
         }
       }
       else{
         //     if(infiles.size() == 1){
         //       if(!read_scalability_from_file(*ai))
         //      exit(1);
         //       scalability_summary();
         //     }
         //     else{
         Profiler::ScalaMap scala_map;
         if(profiler.ReadSummaryFiles(infiles,scala_map)){
           std::cerr << comline.ProgramName() << ": Error: Could not process "
                     << "summary files." << std::endl;
           return(1);
         }
         Profiler::ScalaStatMap scala_statmap;
         if(profiler.PopulateScalaMap(scala_map,scala_statmap,!is_fixed)){
           std::cerr << comline.ProgramName()
                     << ": Error: Unable to calculate scalability information."
                     << std::endl;
           return(1);
         }
         if(profiler.ScalabilitySummary(scala_statmap,std::cout)){
           std::cerr << comline.ProgramName()
                     << ": Error: Unabled to perform scalability summary."
                     << std::endl;
           return(1);
         }
         //     }
       }
       return(0);
     }
int IRAD::Util::UtilTest (int argc, char * argv[])
Parameters
argc number of string command line tokens
argv string command line tokens
Returns
0 if successful, 1 otherwise
Definition at line 19 of file TestUtil.C.
References IRAD::Util::TestObject::Process().
Referenced by main().
     {
       Util::TestObject  test;
       Util::TestResults results;
       test.Process(results);
       std::ofstream Ouf;
       std::ostream *Out = &std::cout;
       if(argc > 1){
         Ouf.open(argv[1]);
         if(!Ouf){
           std::cout << "Error: Could not open output file, " << argv[1] << "."
                     << std::endl;
           return(1);
         }
         Out = &Ouf;
       }
       *Out << results << std::endl;
       if(Ouf)
         Ouf.close();
       return(0);
     }