IMPACT: Manipulation of Strong Curves
Manipulation of Strong Curves
Detailed Description
Functions
bool RFC_Window_overlay::check_false_strong_1 (Feature_1 &)
Determine whether a curve is false strong.
void RFC_Window_overlay::subdiv_feature_curve (const Feature_1 &f1, Feature_list_1 &new_flist, int &dropped)
Subdivide a feature curve by splitting it at 0-features.
void RFC_Window_overlay::merge_features_1 (const Node &v, Feature_1 &f1, Feature_1 &f2)
Merge two feature curves into one at vertex v.
void RFC_Window_overlay::remove_feature_1 (Feature_1 &f)
Remove a false strong curve.
Function Documentation
bool RFC_Window_overlay::check_false_strong_1 (Feature_1 & f1) protected
Definition at line 313 of file RFC_Window_overlay_fea.C.
References acc, HDS_accessor::get_next_around_destination(), Node::halfedge_g(), HEdge::opposite_g(), HEdge::pane(), Node::pane(), and RFC_Pane_overlay::unset_strong_edge().
{
   if ( cos_face_angle( f1.front())==-1) return false;
   Node src = f1.front().origin_g();
   Node dst = f1.back().destination_g();
   // is a loop or strong at both ends
   if ( src == dst || is_on_feature( src) && is_on_feature( dst)
        && (!_f0_ranks.empty() || is_feature_0(src) || is_feature_0(dst)) ||
        cos_face_angle(f1.front())<0 && cos_face_angle(f1.back())<0)
     return false;
   // Is it weak ended? If so, pop out the weak edges
   if ( _strong_ended) {
     if ( !f1.empty())  for (;;) {
       HEdge h=f1.front(), hopp=h.opposite_g();
       if ( is_on_feature( src) || cos_face_angle( h, hopp) <= _cos_uf || is_strong_ad( src))
         break;
       else {
         h.pane()->unset_strong_edge(h);
         hopp.pane()->unset_strong_edge( hopp);
         f1.pop_front();
       }
       if ( !f1.empty())
         src = f1.front().origin_g();
       else
         return true;
     }
     if ( !f1.empty())  for (;;) {
       HEdge h=f1.back();
       HEdge hopp=h.opposite_g();
       if ( is_on_feature( dst) || cos_face_angle( h, hopp) <= _cos_uf
            || is_strong_ad( src))
         break;
       else {
         h.pane()->unset_strong_edge(h);
         hopp.pane()->unset_strong_edge( hopp);
         f1.pop_back();
       }
       if ( !f1.empty())
         dst = f1.back().destination_g();
       else
         return true;
     }
   }
   // is it too short?
   if ( _min_1f_len) {
     int c = !(is_strong_ad( src) || is_feature_0( src)) +
             !(is_strong_ad( dst) || is_feature_0( dst));
     if ( int(f1.size()) <= c*_min_1f_len)
       return true;
   }
   // is it too close to another features?
   if ( _long_falseness_check) {
     if ( _f_list_1.empty() ||
          (is_strong_ad( src) || is_feature_0( src)) &&
          (is_strong_ad( dst) || is_feature_0( dst)))
       return false;
     for ( Feature_1::const_iterator it=++f1.begin(); it!=f1.end(); ++it) {
       Node v = it->origin_g();
       HEdge h0 = v.halfedge_g(), h1=h0;
       // Loop through incident edges of v
       do {
         if ( is_on_feature( h1.origin_g())) { v=Node(); break; }
       } while ( (h1=acc.get_next_around_destination(h1))!=h0);
       if (v.pane()==NULL) continue;
       else return false;
     }
     return true;
   }
   return false;
 }
void RFC_Window_overlay::merge_features_1 (const Node & v, Feature_1 & f1, Feature_1 & f2) protected
After the operation, f1 becomes the union of f1 and f2, and f2 becomes empty.
Definition at line 281 of file RFC_Window_overlay_fea.C.
References RFC_assertion.
{
   RFC_assertion( !f1.empty() && f1!=f2);
   if ( f2.empty()) return;
   Node dst, src;
   if ( (dst=f1.back().destination_g()) == f2.front().origin_g() && v==dst)
     f1.splice( f1.end(), f2);
   else if ( (src=f1.front().origin_g()) == f2.back().destination_g() && v==src) {
     f2.splice( f2.end(), f1);
     f1.swap( f2);
   }
   else if ( dst == f2.back().destination_g() && v==dst) {
     while ( !f2.empty()) {
       f1.push_back( f2.back().opposite_g());
       f2.pop_back();
     }
   }
   else {
     RFC_assertion( src == f2.front().origin_g() && v==src);
     while ( !f2.empty()) {
       f1.push_front( f2.front().opposite_g());
       f2.pop_front();
     }
   }
   RFC_assertion( f2.empty());
 }
void RFC_Window_overlay::remove_feature_1 (Feature_1 & f)
Definition at line 510 of file RFC_Window_overlay_fea.C.
References RFC_Pane_overlay::_f_n_index, acc, RFC_Pane_overlay::get_index(), HDS_accessor::get_next_around_destination(), HEdge::opposite_g(), HEdge::pane(), and RFC_assertion.
{
   for ( Feature_1::iterator it=f.begin(), iend=f.end(); it != iend; ++it) {
     unset_strong_edge( *it);  unset_strong_edge( it->opposite_g());
   }
   for ( Feature_1::iterator it=f.begin(), iend=f.end(); it != iend; ++it) {
     HEdge k = *it, kopp = k.opposite_g();
     RFC_assertion( !k.pane()->_f_n_index.empty());
     do {
       HEdge h0 = k, h = h0;
       do {
         RFC_assertion( !is_feature_1( h));
         RFC_Pane_overlay &pane = *h.pane();
         pane._f_n_index[ pane.get_index( h)] = -1;
       } while ( (h=acc.get_next_around_destination(h)) != h0);
     } while ( (k=(k==kopp)?*it:kopp) != *it);
   }
 }
void RFC_Window_overlay::subdiv_feature_curve (const Feature_1 & f1, Feature_list_1 & new_flist, int & dropped) protected
Some false strong edges may be filtered out during this step.
Definition at line 395 of file RFC_Window_overlay_fea.C.
References max(), min(), HEdge::opposite_g(), HEdge::pane(), RFC_assertion, and RFC_Pane_overlay::unset_strong_edge().
{
   // We loop through all vertices in the curve to locate the 0-features
   list< Feature_1::const_iterator>  divs;
   Node src = f1.front().origin_g();
   Node trg = f1.back().destination_g();
   bool isloop = (src==trg);
   // A 1-feature is dangling if one of its end point is a terminus
   bool isdangling = !isloop &&
     (_f0_ranks.find( src) == _f0_ranks.end() ||
      _f0_ranks.find( trg) == _f0_ranks.end());
   float cos_min_fa_before=1, cos_min_fa_after=1;
   Feature_1::const_iterator f1end = f1.end(), hfirst = f1end, hlast=f1end;
   for (Feature_1::const_iterator hprev=f1.begin(),hi=++f1.begin(),hnext=hi;
        hi!=f1end; hprev=hi,hi=hnext) {
     ++hnext;
     Node v = hi->origin_g();
     if ( is_feature_0( v)) { RFC_assertion( hi==f1.begin()); continue; }
     float cos_ea = cos_edge_angle( f1, hi, isloop);
     if ( cos_ea <= _cos_ue ||
          is_rstrong_ea( f1, hprev, hnext, cos_ea, isloop)) {
       divs.push_back( hi);
       // When breaking loops, mark breakpoints as corners
       set_feature_0( v);
     }
     else if ( isdangling) {
       // Mark transitions between strong and week edges for danging 1-features
       // as 0-feature
       float dpre = cos_face_angle( *hprev, hprev->opposite_g());
       float d = cos_face_angle( *hi, hi->opposite_g());
       if ( hfirst == f1end && dpre < cos_min_fa_before)
         cos_min_fa_before = dpre;
       if ( std::min( dpre,d) <= _cos_weakend &&
            std::max( dpre,d) > _cos_weakend ) {
         if ( hfirst == f1end) hfirst = hi;
         hlast = hi; cos_min_fa_after = 1.;
       }
       if ( d < cos_min_fa_before) cos_min_fa_after = d;
     }
   }
   if ( isdangling && divs.empty() ) {
     if ( hfirst!=f1end && cos_min_fa_before>_cos_weakend &&
          _f0_ranks.find( src) == _f0_ranks.end() )
     { divs.push_back( hfirst); set_feature_0( hfirst->origin_g()); }
     if ( hlast!=f1end && hlast!=hfirst && cos_min_fa_after>_cos_weakend &&
          _f0_ranks.find( trg) == _f0_ranks.end())
     { divs.push_back( hlast); set_feature_0( hlast->origin_g()); }
   }
   if ( isloop) {
     // Finally, we process end vertices
     Feature_1::const_iterator hi = f1.begin();
     float cos_ea = cos_edge_angle( f1, hi, isloop);
     if ( cos_ea <= _cos_ue ||
          is_rstrong_ea( f1,f1end,++f1.begin(),cos_ea,isloop)) {
       // When breaking loops, mark breakpoints as corners
       divs.push_back( f1end); set_feature_0( hi->origin_g());
     }
   }
   else
     divs.push_back( f1end);
   // Now subdivide the curve into sub-curves
   Feature_list_1   subcur;
   if ( divs.size()==0)
     subcur.push_back( f1);
   else {
     subcur.push_back( Feature_1( f1.begin(),divs.front()));
     list< Feature_1::const_iterator>::const_iterator dit=divs.begin();
     for ( list< Feature_1::const_iterator>::const_iterator
             dinext=dit; ++dinext != divs.end(); dit=dinext)
       subcur.push_back( Feature_1( *dit, *dinext));
     if ( isloop) {
       Feature_1 &newf=subcur.front();
       newf.insert( newf.begin(), *dit, f1end);
     }
   }
   // Check the sub-curves to filter out false-strongness.
   for (Feature_list_1::iterator sit=subcur.begin();sit!=subcur.end();++sit) {
     if ( check_false_strong_1( *sit)) {
       for ( Feature_1::const_iterator i=sit->begin(); i!=sit->end(); ++i) {
         i->pane()->unset_strong_edge(*i); ++dropped;
         HEdge hopp=i->opposite_g();
         hopp.pane()->unset_strong_edge( hopp);
       }
     }
     else {
       // Set all vertices on-feature
       set_on_feature( sit->front().origin_g());
       for ( Feature_1::const_iterator i=sit->begin(); i!=sit->end(); ++i)
         set_on_feature( i->destination_g());
       Node src = sit->front().origin_g();
       Node dst = sit->back().destination_g();
       if ( src!=dst) {  set_feature_0( src); set_feature_0( dst); }
       new_flist.push_back( Feature_1()); new_flist.back().swap(*sit);
     }
   }
 }