IMPACT: Public Interface for Overlay
Public Interface for Overlay
Detailed Description
Functions
bool RFC_Window_overlay::is_same_node (const Node &v1, const Node &v2)
Check whether given two vertices correspond to the same physical point.
void RFC_Window_overlay::create_overlay_data ()
void RFC_Window_overlay::delete_overlay_data ()
void RFC_Window_overlay::determine_counterparts ()
void RFC_Window_overlay::unmark_alledges ()
HEdge RFC_Window_overlay::get_an_unmarked_halfedge () const
Function Documentation
void RFC_Window_overlay::create_overlay_data ()
Definition at line 438 of file RFC_Window_overlay.C.
References RFC_Window_base::_pane_set, and RFC_Pane_overlay::create_overlay_data().
Referenced by Overlay::overlay().
{
   // Loop through panes
   Pane_set::iterator pit=_pane_set.begin(), piend=_pane_set.end();
   for ( ; pit != piend; ++pit) {
     RFC_Pane_overlay &p = (RFC_Pane_overlay &)*pit->second;
     p.create_overlay_data();
   }
 }
void RFC_Window_overlay::delete_overlay_data ()
Definition at line 448 of file RFC_Window_overlay.C.
References RFC_Window_base::_pane_set, RFC_Pane_overlay::delete_overlay_data(), RFC_Pane_base::is_master(), and RFC_Window_derived< RFC_Pane_overlay >::pane().
Referenced by Overlay::overlay().
{
   // Loop through the panes to remove the buffer spaces
   Pane_set::iterator pit, piend;
   for (pit=_pane_set.begin(), piend=_pane_set.end(); pit != piend; ++pit) {
     RFC_Pane_overlay &pane = (RFC_Pane_overlay &)*pit->second;
     if ( !pane.is_master()) continue;
     pane.delete_overlay_data();
   }
 }
void RFC_Window_overlay::determine_counterparts ()
Definition at line 386 of file RFC_Window_overlay.C.
References RFC_Window_base::_pane_set.
Referenced by RFC_Window_overlay::RFC_Window_overlay().
{
   // Construct a mapping from vertex pair to border edges
   Pane_set::iterator it=_pane_set.begin(), iend=_pane_set.end();
   for (; it != iend; ++it)
     ((RFC_Pane_overlay*)it->second)->construct_bvpair2edge();
   // Construct mapping from panal border edges to their counterpart.
   for ( it = _pane_set.begin(); it != iend; ++it)
     ((RFC_Pane_overlay*)it->second)->determine_counterparts();
   // Clear the mapping
   for ( it = _pane_set.begin(); it != iend; ++it)
     ((RFC_Pane_overlay*)it->second)->_bv2edges.clear();
 }
HEdge RFC_Window_overlay::get_an_unmarked_halfedge () const
Definition at line 61 of file RFC_Window_overlay.C.
References RFC_Window_base::_pane_set, RFC_Pane_overlay::is_on_feature(), RFC_Pane_overlay::marked(), HEdge::pane(), RFC_Window_derived< RFC_Pane_overlay >::pane(), s, and RFC_Pane_base::size_of_faces().
Referenced by Overlay::overlay_init().
{
   HEdge hbrd;
   for ( Pane_set::const_iterator pit=_pane_set.begin();
         pit != _pane_set.end(); ++pit) {
     RFC_Pane_overlay &pane = reinterpret_cast<RFC_Pane_overlay &>(*pit->second);
     for (int i=1, s=pane.size_of_faces(); i<=s; ++i) {
       HEdge h( &pane, Edge_ID(i,0)), h0=h;
       do {
         if (h.opposite_l().is_border_l()) continue;
         if (!pane.marked( h)) {
           if ( hbrd.pane()==NULL && pane.is_on_feature( h.origin_l()))
             hbrd = h;
           else if ( !pane.is_on_feature(h.origin_l()))
             return h;
         }
       } while ( (h=h.next_l()) != h0);
     }
   }
   return hbrd;
 }
bool RFC_Window_overlay::is_same_node (const Node & v1, const Node & v2)
Definition at line 87 of file RFC_Window_overlay.C.
References Node::get_primary(), and Node::is_border_l().
{
   if ( v1==v2) return true;
   if ( !v1.is_border_l() || !v2.is_border_l())
     return false;
   return v1.get_primary() == v2.get_primary();
 }
void RFC_Window_overlay::unmark_alledges ()
Definition at line 402 of file RFC_Window_overlay.C.
References RFC_Pane_overlay::_e_marks, and RFC_Window_base::_pane_set.
Referenced by Overlay::intersect_blue_with_green().
{
   Pane_set::iterator it=_pane_set.begin(), iend=_pane_set.end();
   for ( ; it != iend; ++it) {
     RFC_Pane_overlay &p = (RFC_Pane_overlay &)*it->second;
     fill( p._e_marks.begin(), p._e_marks.end(), 0);
   }
 }