IMPACT: Feature-Detection Helpers
Feature-Detection Helpers
Detailed Description
Functions
void RFC_Window_overlay::set_feature_0 (const Node &v) const
void RFC_Window_overlay::set_on_feature (const Node &v) const
bool RFC_Window_overlay::is_feature_0 (const Node &v) const
bool RFC_Window_overlay::is_on_feature (const Node &v) const
bool RFC_Window_overlay::is_feature_1 (const HEdge &h) const
void RFC_Window_overlay::unset_strong_edge (const HEdge &h)
Function Documentation
bool RFC_Window_overlay::is_feature_0 (const Node & v) const inline private
Definition at line 469 of file RFC_Window_overlay.h.
References Node::is_primary(), and Node::pane().
Referenced by RFC_Window_overlay::evaluate_normals().
   { assert(v.is_primary()); return v.pane()->is_feature_0(v); }
bool RFC_Window_overlay::is_feature_1 (const HEdge & h) const inline private
Definition at line 473 of file RFC_Window_overlay.h.
References RFC_Pane_overlay::is_feature_1(), and HEdge::pane().
Referenced by RFC_Window_overlay::evaluate_normals().
   { return h.pane()->is_feature_1(h); }
bool RFC_Window_overlay::is_on_feature (const Node & v) const inline private
Definition at line 471 of file RFC_Window_overlay.h.
References Node::is_primary(), and Node::pane().
   { assert(v.is_primary()); return v.pane()->is_on_feature(v); }
void RFC_Window_overlay::set_feature_0 (const Node & v) const inline private
Definition at line 464 of file RFC_Window_overlay.h.
References Node::is_primary(), and Node::pane().
   { assert(v.is_primary()); v.pane()->set_feature_0( v); }
void RFC_Window_overlay::set_on_feature (const Node & v) const inline private
Definition at line 466 of file RFC_Window_overlay.h.
References Node::is_primary(), and Node::pane().
   { assert(v.is_primary()); v.pane()->set_on_feature( v); }
void RFC_Window_overlay::unset_strong_edge (const HEdge & h) inline private
Definition at line 475 of file RFC_Window_overlay.h.
References HEdge::pane(), and RFC_Pane_overlay::unset_strong_edge().
   { h.pane()->unset_strong_edge(h); }