IMPACT: Normal and Tangent Computation
Normal and Tangent Computation
Detailed Description
Functions
void RFC_Window_overlay::evaluate_normals ()
void RFC_Window_overlay::print_features ()
Dump out the 0- and 1-features in Tecplot format into files <name>f0.plt, <name>f1.plt, respectively.
void RFC_Window_overlay::reduce_normals_to_all (MPI_Op)
virtual SURF::Pane_manifold_2 * RFC_Window_overlay::init_pane_manifold (int pane_id)
Vector_3 RFC_Window_overlay::get_tangent (const HEdge &h)
Function Documentation
void RFC_Window_overlay::evaluate_normals ()
Definition at line 123 of file RFC_Window_overlay.C.
References RFC_Window_overlay::_f_list_0, RFC_Window_overlay::_f_list_1, RFC_Pane_overlay::_f_n_index, RFC_Pane_overlay::_f_nrmls, RFC_Pane_overlay::_f_t_index, RFC_Pane_overlay::_f_tngts, RFC_Pane_overlay::_nrmls, RFC_Window_base::_pane_set, acc, RFC_Pane_overlay::add_tangent(), HEdge::destination_g(), HEdge::destination_l(), free_vector(), Overlay_primitives::get_face_normal(), RFC_Pane_overlay::get_index(), HDS_accessor::get_next_around_destination(), HEdge::is_border_l(), RFC_Window_overlay::is_feature_0(), RFC_Window_overlay::is_feature_1(), RFC_Pane_base::is_master(), RFC_Window_overlay::normalize(), HEdge::opposite_g(), HEdge::pane(), RFC_Window_derived< RFC_Pane_overlay >::pane(), Node::point(), RFC_Window_overlay::reduce_normals_to_all(), RFC_assertion, scheme, and RFC_Pane_base::size_of_faces().
Referenced by Overlay::overlay().
{
   //  std::cout << "eval normals" << std::endl;
   // First, evaluate normals for each pane
   Pane_set::iterator it, iend=_pane_set.end();
   for ( it=_pane_set.begin() ; it != iend; ++it) {
     if ( it->second->is_master())
       ((RFC_Pane_overlay*)it->second)->evaluate_normals();
   }
   //  std::cout << "reducing" << std::endl;
   // Second, perform reduction over all vertices
   reduce_normals_to_all( MPI_SUM);
   //  std::cout << "reducing done" << std::endl;
   // Evaluate the one-sided normals for the halfedge edges incident
   // on sharp features.
   for ( it=_pane_set.begin() ; it != iend; ++it) {
     RFC_Pane_overlay &pane = (RFC_Pane_overlay &)*it->second;
     free_vector( pane._f_nrmls); free_vector( pane._f_tngts);
     free_vector( pane._f_n_index); free_vector( pane._f_t_index);
     int num_hedgs=4*pane.size_of_faces() + pane.size_of_border_edges(); // pane.hds().size_of_halfedges();
     pane._f_n_index.resize( num_hedgs, -1);
     pane._f_t_index.resize( num_hedgs, -1);
   }
   Overlay_primitives      op;
   Point_2  one(1,0);
   // Loop throught the sharp halfedges in 1-features
   for ( Feature_list_1::iterator it = _f_list_1.begin(), iend=_f_list_1.end();
         it != iend; ++it) {
     for ( Feature_1::iterator j=it->begin(); j!=it->end(); ++j) {
       HEdge k = *j, kopp=k.opposite_g();
       do {
         if (!k.is_border_l() && k.pane()->
             _f_n_index[k.pane()->get_index(k)] == -1) {
           // First, compute the vector
           Vector_3 v = op.get_face_normal( k, one, scheme);
           HEdge h0 = k, h = acc.get_next_around_destination(k);
           do {
             if ( is_feature_1( h)) break;
             RFC_assertion( !h.is_border_l());
             v += op.get_face_normal( h, one, scheme);
           } while ( (h=acc.get_next_around_destination(h)) != h0);
           // Second, insert the vector into the table
           normalize(v);
           swap( h, h0);
           do {
             RFC_Pane_overlay &pane = *h.pane();
             if ( pane._f_nrmls.size() && v == pane._f_nrmls.back()) {
               pane._f_n_index[ pane.get_index( h)] = pane._f_nrmls.size()-1;
             }
             else {
               pane._f_n_index[ pane.get_index( h)] = pane._f_nrmls.size();
               pane._f_nrmls.push_back( v);
             }
           } while ( (h=acc.get_next_around_destination(h)) != h0);
         }
       } while ( (k=(k==kopp)?*j:kopp) != *j);
       // Compute the tangent
       Vector_3 tng = ( k.destination_l().point() - kopp.destination_l().point());
       k.pane()->add_tangent( k, tng);
       if ( !is_feature_0( k.destination_g())) {
         Feature_1::iterator t = j; ++t;
         if ( t==it->end()) t = it->begin();
         HEdge h = (*t).opposite_g();
         h.pane()->add_tangent( h, tng);
       }
       kopp.pane()->add_tangent( kopp, tng);
       if ( !is_feature_0( kopp.destination_g())) {
         Feature_1::iterator t = (j==it->begin()) ? it->end() : j;
         HEdge h = *(--t);
         h.pane()->add_tangent( h, tng);
       }
     }
   }
   // Loop through the vertices in 0-features
   for ( Feature_list_0::iterator it = _f_list_0.begin(), iend=_f_list_0.end();
         it != iend; ++it) {
     HEdge h = it->vertex().halfedge_g();
     RFC_Pane_overlay &pane = *h.pane();
     if ( !h.is_border_l() && pane._f_n_index[ pane.get_index( h)] == -1) {
       HEdge h0 = h;
       do {
         Vector_3 v = op.get_face_normal( h, one, scheme)+
           op.get_face_normal( h.opposite_g(), Point_2(0,0), scheme);
         normalize(v);
         if ( pane._f_nrmls.size() && v == pane._f_nrmls.back()) {
           pane._f_n_index[ pane.get_index( h)] = pane._f_nrmls.size()-1;
         }
         else {
           pane._f_n_index[ pane.get_index( h)] = pane._f_nrmls.size();
           pane._f_nrmls.push_back( v);
         }
       } while ( (h=acc.get_next_around_destination(h)) != h0);
     }
   }
   // Finally, normalize normals and tangents
   for ( it=_pane_set.begin() ; it != iend; ++it) {
     RFC_Pane_overlay &pane = (RFC_Pane_overlay &)*it->second;
     if ( pane.is_master()) {
       for ( int i=0, size = pane._nrmls.size(); i<size; ++i)
         normalize( pane._nrmls[i]);
       for ( int i=0, size = pane._f_tngts.size(); i<size; ++i)
         normalize( pane._f_tngts[i]);
     }
   }
   //  std::cout << "eval normals done." << std::endl;
 }
Vector_3 RFC_Window_overlay::get_tangent (const HEdge & h) inline protected
Definition at line 378 of file RFC_Window_overlay.h.
References HEdge::destination_l(), HEdge::origin_l(), and Node::point().
   { return h.destination_l().point()-h.origin_l().point(); }
virtual SURF::Pane_manifold_2* RFC_Window_overlay::init_pane_manifold (int pane_id) inline protected virtual
Definition at line 374 of file RFC_Window_overlay.h.
References RFC_Window_derived< RFC_Pane_overlay >::pane().
{
     return &pane(pane_id);
   }
void RFC_Window_overlay::print_features ()
The original mesh, vertex ranks, face angles, and edge angles are output into file <name>.plt.
Definition at line 35 of file RFC_Window_overlay_IO.C.
References COM_allocate_array(), COM_call_function(), COM_delete_window(), COM_FLOAT, COM_free_buffer(), COM_get_dataitem_handle_const(), COM_get_function_handle(), COM_get_panes(), COM_INTEGER, COM_LOAD_MODULE_STATIC_DYNAMIC, COM_new_dataitem(), COM_new_window(), COM_UNLOAD_MODULE_STATIC_DYNAMIC, COM_use_dataitem(), COM_window_init_done(), HEdge::destination_g(), Node::get_primary(), Node::halfedge_g(), HUGE_VALF, RFC_Pane_base::id(), Node::is_isolated(), RFC_Pane_base::is_quadratic(), min(), Node::pane(), Node::point(), RFC_assertion, s, and RFC_Pane_base::size_of_nodes().
{
   std::cout << "Writing feature info " << "..." << std::endl;
   // Construct a temporary window
   std::string wname_fea = name()+"_fea_temp";
   COM_new_window( wname_fea.c_str());
   COM_use_dataitem( (wname_fea+".mesh").c_str(), (name()+".mesh").c_str());
   COM_new_dataitem( (wname_fea+".frank").c_str(), 'n', COM_INTEGER, 1, "");
   COM_new_dataitem( (wname_fea+".face_angle").c_str(), 'n', COM_FLOAT, 1, "");
   if ( verb > 1) {
     COM_new_dataitem( (wname_fea+".turn_angle").c_str(), 'n', COM_FLOAT, 1, "");
     COM_new_dataitem( (wname_fea+".angle_defect").c_str(), 'n', COM_FLOAT, 1, "");
   }
   Pane_set::iterator it=_pane_set.begin(), iend=_pane_set.end();
   for ( it=_pane_set.begin(); it != iend; ++it) {
     RFC_Pane_overlay &pane = (RFC_Pane_overlay &)*it->second;
     int *frank;
     COM_allocate_array( (wname_fea+".frank").c_str(), pane.id(),
                         &(void*&)frank);
     float *face_angle=NULL, *turn_angle=NULL, *angle_defect=NULL;
     COM_allocate_array( (wname_fea+".face_angle").c_str(), pane.id(),
                         &(void*&)face_angle);
     if ( verb>1) {
       COM_allocate_array( (wname_fea+".turn_angle").c_str(), pane.id(),
                           &(void*&)turn_angle);
       COM_allocate_array( (wname_fea+".angle_defect").c_str(), pane.id(),
                           &(void*&)angle_defect);
     }
     for (int i=0,s=pane.size_of_nodes(); i<s; ++i) {
       Node vit(&pane,i+1);
       if (vit.is_isolated()) continue;
       Node v = vit.get_primary();
       if ( is_feature_0( v)) {
         if ( _f0_ranks.find(v)==_f0_ranks.end()) {
           std::cout << "Found rank-0 vertex: " << v.point() << std::endl;
           frank[i] = 2; // 1;
         }
         else
           frank[i] = 2; // _f0_ranks[v]+1;
       }
       else
         frank[i] = is_on_feature(v);
       // Compute face angle
       face_angle[i] = 2.;
       HEdge h0=v.halfedge_g(), h1=h0;
       if ( h0.destination_g()==v) do {
           face_angle[i] = std::min( face_angle[i],
                                     cos_face_angle( h1, h1.opposite_g()));
       } while ( (h1=h1.next_g().opposite_g()) != h0);
       else { // v is an edge center for quadratic element
         RFC_assertion( pane.is_quadratic());
         face_angle[i] = cos_face_angle( h1, h1.opposite_g());
       }
       face_angle[i] = acos( face_angle[i])*r2d;
       if ( verb>1) {
         if ( is_feature_0( v) && _f0_ranks[v]>2)
           turn_angle[i] = 180;
         else if ( v.pane()->get_cos_edge_angle( v)==HUGE_VALF)
           turn_angle[i] = 0;
         else
           turn_angle[i] = acos(v.pane()->get_cos_edge_angle( v))*r2d;
         if ( v.pane()->get_angle_defect(v)==HUGE_VALF)
           angle_defect[i] = 0.;
         else
           angle_defect[i] = v.pane()->get_angle_defect(v)*r2d;
       }
     }
   }
   COM_window_init_done( wname_fea.c_str());
   // Load Rocout
   COM_LOAD_MODULE_STATIC_DYNAMIC( SimOUT, "RFC_OUT");
   int hdl_write = COM_get_function_handle( "RFC_OUT.write_dataitem");
   // Call Rocut with the window to write out the pane.
   int win_all = COM_get_dataitem_handle_const( (wname_fea+".all").c_str());
   string fname_pre = out_pre + name() + "_fea_";
   int npanes, *paneIDs;
   COM_get_panes( wname_fea.c_str(), &npanes, &paneIDs);
   for ( int i=0; i<npanes; ++i) {
     std::ostringstream ostr;
     ostr << fname_pre;
     ostr.fill('0'); ostr.width(5);
     ostr << paneIDs[i] << ".hdf";
     COM_call_function( hdl_write, ostr.str().c_str(), &win_all,
                        wname_fea.c_str(), "000", NULL, NULL, &paneIDs[i]);
   }
   COM_free_buffer( &paneIDs);
   // Unload Rocout
   COM_UNLOAD_MODULE_STATIC_DYNAMIC( SimOUT, "RFC_OUT");
   // Delete the temporary window
   COM_delete_window( wname_fea.c_str());
 }
void RFC_Window_overlay::reduce_normals_to_all (MPI_Op op) protected
Reduces values for each node form all its instances to all instances.
Definition at line 488 of file RFC_Window_overlay.C.
References RFC_Window_base::_map_comm, RFC_Pane_overlay::_nrmls, RFC_Window_base::_pane_set, COM_DOUBLE, and RFC_Window_derived< RFC_Pane_overlay >::pane().
Referenced by RFC_Window_overlay::evaluate_normals().
{
   //  std::cout << "reduce enter" << std::endl;
   std::vector<void *> ptrs;
   // Loop through panes
   Pane_set::iterator pit=_pane_set.begin(), piend=_pane_set.end();
   for ( pit=_pane_set.begin(); pit != piend; ++pit) {
     RFC_Pane_overlay &pane=(RFC_Pane_overlay &)*pit->second;
     ptrs.push_back( &pane._nrmls[0]);
   }
   //  std::cout << "loop done." << std::endl;
   _map_comm.init( &ptrs[0], COM_DOUBLE, 3);
   //  std::cout << "init done." << std::endl;
   _map_comm.begin_update_shared_nodes();
   //  std::cout << "begin update done." << std::endl;
   _map_comm.reduce_on_shared_nodes( op);
   //  std::cout << "rosn done." << std::endl;
   _map_comm.end_update_shared_nodes();
   //  std::cout << "reduce done." << std::endl;
 }