IMPACT: mapbasic.h File Reference
mapbasic.h File Reference
#include <cstdlib>
#include <iostream>
#include <cmath>
#include "Element_accessors.hpp"
Classes
class Origin
class Null_vector
class Vector_3< Type >
Some basic geometric data types.
class Point_3< T >
class Vector_2< Type >
class Point_2< T >
Macros
#define MAP_BEGIN_NAMESPACE namespace MAP {
#define MAP_END_NAMESPACE }
#define USE_MAP_NAMESPACE using namespace MAP;
Typedefs
typedef double Real
Enumerations
enum { E2N_USER =0, E2N_ONE =1, E2N_AREA =2, E2N_ANGLE =3 }
Functions
template<class T >
Vector_3< T > operator* (T t, const Vector_3< T > &v)
template<class Type >
std::ostream & operator<< (std::ostream &os, const Vector_3< Type > &p)
template<class Type >
std::ostream & operator<< (std::ostream &os, const Point_3< Type > &p)
template<class T >
Vector_2< T > operator* (T t, const Vector_2< T > &v)
template<class Type >
std::ostream & operator<< (std::ostream &os, const Vector_2< Type > &p)
template<class Type >
std::ostream & operator<< (std::ostream &os, const Point_2< Type > &p)
Macro Definition Documentation
#define MAP_BEGIN_NAMESPACE namespace MAP {
Definition at line 11 of file mapbasic.h.
#define MAP_END_NAMESPACE }
Definition at line 12 of file mapbasic.h.
#define USE_MAP_NAMESPACE using namespace MAP;
Definition at line 13 of file mapbasic.h.
Typedef Documentation
typedef double Real
Definition at line 305 of file mapbasic.h.
Enumeration Type Documentation
anonymous enum
Enumerator
E2N_USER
E2N_ONE
E2N_AREA
E2N_ANGLE
Definition at line 308 of file mapbasic.h.
 { E2N_USER=0, E2N_ONE=1, E2N_AREA=2, E2N_ANGLE=3};
Function Documentation
template<class T > Vector_3<T> operator* (T t, const Vector_3< T > & v)
Definition at line 122 of file mapbasic.h.
 { return v*t; }
template<class T > Vector_2<T> operator* (T t, const Vector_2< T > & v)
Definition at line 249 of file mapbasic.h.
 { return v*t; }
template<class Type > std::ostream& operator<< (std::ostream & os, const Vector_3< Type > & p)
Definition at line 125 of file mapbasic.h.
References Vector_3< Type >::x().
{
   return os << '(' << p.x() << ',' << p.y() << ',' << p.z() << ')';
 }
template<class Type > std::ostream& operator<< (std::ostream & os, const Point_3< Type > & p)
Definition at line 177 of file mapbasic.h.
References Vector_3< Type >::x().
{
   return os << '(' << p.x() << ',' << p.y() << ',' << p.z() << ')';
 }
template<class Type > std::ostream& operator<< (std::ostream & os, const Vector_2< Type > & p)
Definition at line 252 of file mapbasic.h.
References Vector_2< Type >::x().
{
   return os << '(' << p.x() << ',' << p.y() << ')';
 }
template<class Type > std::ostream& operator<< (std::ostream & os, const Point_2< Type > & p)
Definition at line 301 of file mapbasic.h.
References Vector_2< Type >::x().
{
   return os << '(' << p.x() << ',' << p.y() << ')';
 }