IMPACT: TestModule.C File Reference
ModuleTemplate/src/TestModule.C File Reference
IMPACT-specific documentation group
Test Module in C which contains load_module and unload_module.
Detailed Description
Author
Jessica Kress (jkres.nosp@m.s@il.nosp@m.rocst.nosp@m.ar.c.nosp@m.om)
Date
May 1, 2014
This file serves as both a test and a simple example for implementing a module in C/C++. This module provides only load and unload functions at this point.
Definition in file ModuleTemplate/src/TestModule.C.
#include <string>
#include <cstring>
#include <iostream>
#include <iomanip>
#include "FC.h"
#include "com.h"
#include "com_devel.hpp"
Functions
void TestModule_load_module (const char *name)
void TestModule_unload_module (const char *name)
Function Documentation
void TestModule_load_module (const char * name)
Definition at line 22 of file ModuleTemplate/src/TestModule.C.
References COM_new_window(), and COM_window_init_done().
{
   std::cout << "Loading TestModule" << std::endl;
   COM_new_window(std::string(name));
   COM_window_init_done(std::string(name));
 }
void TestModule_unload_module (const char * name)
Definition at line 27 of file ModuleTemplate/src/TestModule.C.
References COM_delete_window().
{
   std::cout << "Unloading TestModule" << std::endl;
   COM_delete_window(std::string(name));
 }