IMPACT: IRAD::Util Namespace Reference
IRAD::Util Namespace Reference
IllinoisRocstar Application Development
General support utilities.
Classes
class ComLineObject
Command line processing.
class ConfigParameters
class ConfigurationObject
class MenuObject
class Parameters
struct CmpPairs
class TestResults
Encapsulating class for collections of test results.
class TestingObject
Interface for a general testing object.
class TestObject
Typedefs
typedef std::string::size_type strsize
typedef
Primitive::KeyValuePairObj
< std::string, std::string > ParamType
typedef int Error
Error type.
Functions
std::ostream & operator<< (std::ostream &Ostr, const Util::ConfigurationObject &cob)
Stream output operator for Util::ConfigurationObject.
std::istream & operator>> (std::istream &Istr, Util::ConfigurationObject &cob)
Stream input operator for Util::ConfigurationObject.
std::ostream & operator<< (std::ostream &Ostr, const Util::ParamType &param)
std::ostream & operator<< (std::ostream &oSt, const Util::Parameters &pv)
std::istream & operator>> (std::istream &iSt, Util::Parameters &pv)
template<typename Container >
bool LessThan (const Container &c1, const Container &c2)
template<typename Container >
void InvertContainer (const Container &c1, Container &c2)
template<typename ContainerType >
void DumpContents (std::ostream &Ostr, const ContainerType &c, std::string del="\n")
Dump container contents.
template<typename ContainerType , typename T >
void CopyIntoContainer (ContainerType &cont, const T *src, size_t count)
template<typename OuterCont , typename OutCont , typename InnerCont , typename MapType >
void MapElements (OuterCont &src, OutCont &trg, MapType &m)
template<typename ListContainerType , typename ListType >
Primitive::IndexType MaxNodeId (const ListContainerType &fc)
Return the maximum of all elements of a multicontainer.
template<typename OuterCont , typename InnerCont , typename OutCont >
void Flatten (OuterCont &con, OutCont &ocon)
Populate OutCont with a flat list of entries from a multicontainer.
template<typename OuterContType >
Primitive::IndexType GetTotalSize (OuterContType &con)
Return the total number of entries in a multicontainer.
template<typename OuterContType , typename InnerContType , typename RetCont , typename idxtype >
void MultiContainer2CSR (RetCont &xadj, RetCont &adj, OuterContType &source)
template<typename ListContainerType , typename ListType >
void CreateAdjacentNodeList (std::vector< std::list< Primitive::IndexType > > &anodelist, ListContainerType &fc, Primitive::IndexType nnodes=0)
Given an array of adjacent node lists (like an array of face connectivities), this function will loop thru and create a list of unique adjacent nodes for each node with the nodes that are actually adjacent in the lists
template<typename ListContainerType , typename ListType >
void AdjEList (std::vector< std::list< Primitive::IndexType > > &aelist, ListContainerType &dual_con, unsigned long nel=0)
Given an array of adjacent node lists (like an array of face connectivities), this function will loop thru and create a list of unique adjacent nodes for each node Note that this is a little different from the AdjNodeList because in this version every node in each list is considered adjacent.
template<typename ConType , typename IConType >
Primitive::IndexType NumberOfEdges (ConType &con)
template<typename ContainerType , typename Icont >
void FormGraph (const ContainerType &adjlist)
template<typename Container >
bool HaveSameOrientation (Container &c1, Container &c2)
Cyclic test.
template<typename Container >
bool HaveOppositeOrientation (Container &c1, Container &c2)
Anti-cyclic test.
template<class T >
CmpPairs< T > CreateCmpPairs (const std::vector< T > &v)
template<class Vals >
void SortPermutation (const Vals &values, std::vector< unsigned int > &v)
std::string GetNextContent (std::istream &In)
void GetContentUntil (std::istream &In, std::string ret, const std::string &etag)
int String2Buf (const std::string &instr, void **buf)
void Trim (std::string &instr, bool preserve_newline=false)
Creates space delimited tokens in place.
const std::string Trimmed (const std::string &instr, bool preserve_newline=false)
Returns space delimited tokens.
const std::string stripdirs (const std::string &pname)
Strip absolute path.
void TokenizeString (std::vector< std::string > &tokens, const std::string &source)
Tokenize string.
void TokenizeString (std::vector< std::string > &tokens, const std::string &source, const char delim)
Tokenize string w/ delimiter.
template<typename NumType >
void ProcessRange (NumType &t1, NumType &t2, const std::string stinter)
Process a range in the format "t1:t2".
int OpenFile (std::ifstream &Inf, const std::string &filename)
File opener.
void Vectorize (std::vector< std::string > &retVal, const char **in)
void Vectorize (std::vector< std::string > &retVal, const char **in, int n)
int CheckResults (int argc, char *argv[])
Check numerical results utility.
std::istream & operator>> (std::istream &In, ComLineObject &cl)
std::ostream & operator<< (std::ostream &Out, const ComLineObject &cl)
int UtilTest (int argc, char *argv[])
Drives the IRAD::Util namespace's test object.
Typedef Documentation
typedef int IRAD::Util::Error
Definition at line 25 of file primitive_utilities.H.
typedef Primitive::KeyValuePairObj<std::string,std::string> IRAD::Util::ParamType
Definition at line 15 of file Parameters.H.
typedef std::string::size_type IRAD::Util::strsize
Definition at line 16 of file Menu.H.
Function Documentation
template<typename ListContainerType , typename ListType > void IRAD::Util::AdjEList (std::vector< std::list< Primitive::IndexType > > & aelist, ListContainerType & dual_con, unsigned long nel = 0)
Definition at line 225 of file primitive_utilities.H.
     {
       if(nel == 0)
         nel = MaxNodeId<ListContainerType,ListType>(dual_con);
       aelist.resize(nel);
       typename ListContainerType::iterator lci = dual_con.begin();
       while(lci != dual_con.end())
         {
           typename ListType::iterator li = lci->begin();
           while(li != lci->end()){
             Primitive::IndexType this_node = *li++ - 1;
             typename ListType::iterator li2 = li;
             while(li2 != lci->end()){
               Primitive::IndexType nexnode = *li2++ - 1;
               aelist[this_node].push_back(nexnode+1);
               aelist[nexnode].push_back(this_node+1);
             }
           }
           lci++;
         }
       for(Primitive::IndexType node = 0;node < nel;node++)
         {
           aelist[node].sort();
           aelist[node].unique();
         }
     }
int IRAD::Util::CheckResults (int argc, char * argv[])
Parameters
argc integer indicating how many words are in the command line.
argv string words of the command line.
Returns
0 if test was successful, 1 if not.
This utility numerically checks the numbers on a line that matches a specified string. The lines in the file are assumed to have the following format:
UniqueString : <numerical entries>="">
This utility will perform the indicated test(s) on the numerical entires associated with the "UniqueString" identifier given as input. The result is a binary YES(1) or NO(0) which is output to stdout as:
TestName = 1||0
If the test passed(=YES), this utility returns a 0, otherwise it returns 1.
Definition at line 8 of file CheckResults.C.
References IRAD::Util::ComLineObject::GetOption(), IRAD::CheckResultsComLine::Initialize(), IRAD::Util::ComLineObject::LongUsage(), max(), IRAD::Util::ComLineObject::ProcessOptions(), and IRAD::Util::ComLineObject::ProcessRange().
Referenced by main().
 {
   CheckResultsComLine comline((const char **)argv);
   comline.Initialize();
   int clerr = comline.ProcessOptions();
   if(!comline.GetOption("help").empty()){
     std::cout << comline.LongUsage() << std::endl;
     return(0);
   }
   int verb_level = 1;
   std::string sverb = comline.GetOption("verbosity");
   std::istringstream Istr(sverb);
   Istr >> verb_level;
   if(verb_level < 0 || verb_level > 3)
     verb_level = 1;
   double lower_limit = -std::numeric_limits<double>::max();
   double upper_limit = std::numeric_limits<double>::max();
   std::string range = comline.GetOption("range");
   std::string ident = comline.GetOption("identifier");
   std::string name = comline.GetOption("name");
   bool passed = false;
   if(name.empty())
     name = ident;
   if(verb_level > 2)
     std::cerr << "Identifier: " << ident << std::endl;
   comline.ProcessRange<double>(lower_limit,upper_limit,range);
   if(verb_level > 2)
     std::cerr << "Processed range: (" << lower_limit << ":" << upper_limit
               << ")" << std::endl;
   std::string line;
   while(std::getline(std::cin,line)){
     std::string::size_type x = line.find(ident);
     if(x != std::string::npos){
       x = line.find(":");
       if(x != std::string::npos){
         std::string snumbers = line.substr(x+1);
         std::istringstream NumIn(snumbers);
         double cnum = 0;
         NumIn >> cnum;
         passed = ((cnum >= lower_limit) && (cnum <= upper_limit));
         if(verb_level)
           std::cout << name << " = " << (passed ? 1 : 0) << std::endl;
         if((verb_level > 1) && !passed){
           std::cerr << "Test failed: " << cnum << " is not in range ("
                     << lower_limit << ":" << upper_limit << ")" << std::endl;
         }
         break;
       }
     }
   }
   if(!passed)
     return(1);
   return(0);
 }
template<typename ContainerType , typename T > void IRAD::Util::CopyIntoContainer (ContainerType & cont, const T * src, size_t count)
Definition at line 96 of file primitive_utilities.H.
     {
       size_t datasize = sizeof(T);
       cont.resize(count);
       memcpy(&cont[0],src,count*datasize);
     }
template<typename ListContainerType , typename ListType > void IRAD::Util::CreateAdjacentNodeList (std::vector< std::list< Primitive::IndexType > > & anodelist, ListContainerType & fc, Primitive::IndexType nnodes = 0)
Definition at line 189 of file primitive_utilities.H.
     {
       if(nnodes == 0)
         nnodes = MaxNodeId<ListContainerType,ListType>(fc);
       anodelist.resize(nnodes);
       typename ListContainerType::iterator lci = fc.begin();
       while(lci != fc.end())
         {
           typename ListType::iterator li = lci->begin();
           while(li != lci->end()){
             Primitive::IndexType this_node = *li++ - 1;
             Primitive::IndexType next_node = 0;
             if(li == lci->end())
               next_node = *(lci->begin());
             else
               next_node = *li++;
             anodelist[this_node].push_back(next_node);
             anodelist[next_node-1].push_back(this_node+1);
           }
           lci++;
         }
       for(Primitive::IndexType node = 0;node < nnodes;node++)
         {
           anodelist[node].sort();
           anodelist[node].unique();
         }
     }
template<class T > CmpPairs<T> IRAD::Util::CreateCmpPairs (const std::vector< T > & v)
Definition at line 344 of file primitive_utilities.H.
Referenced by SortPermutation().
     { return CmpPairs<T>(v); };
template<typename ContainerType > void IRAD::Util::DumpContents (std::ostream & Ostr, const ContainerType & c, std::string del = "\n")
Dumps the contents of the container to the specified std::ostream object.
Definition at line 80 of file primitive_utilities.H.
Referenced by BuildBorderStiffness(), IRAD::Global::GlobalObj< StackType, ErrorType, ProfilerType >::DumpErrors(), IRAD::Profiler::ProfilerObj::DumpEvents(), IRAD::Global::GlobalObj< StackType, ErrorType, ProfilerType >::DumpStack(), IRAD::Util::ComLineObject::ErrorReport(), SolverUtils::Mesh::FindPointInMesh(), SolverUtils::Mesh::FindPointInMesh_2(), GlobalDofExchange(), GlobalDofReMapExchange(), main(), and TestMPI().
{
       if(!c.empty()){
         typename ContainerType::const_iterator ci = c.begin();
         Ostr << *ci++;
         while(ci != c.end())
           Ostr << del << *ci++;
       }
     }
template<typename OuterCont , typename InnerCont , typename OutCont > void IRAD::Util::Flatten (OuterCont & con, OutCont & ocon)
Definition at line 139 of file primitive_utilities.H.
{
       typename OuterCont::iterator cci = con.begin();
       ocon.resize(0);
       while(cci != con.end()){
         typename InnerCont::iterator ccni = cci->begin();
         while(ccni != cci->end())
           ocon.push_back(*ccni++);
         cci++;
       }
     }
template<typename ContainerType , typename Icont > void IRAD::Util::FormGraph (const ContainerType & adjlist)
Definition at line 275 of file primitive_utilities.H.
     {
       // empty for now
     }
void IRAD::Util::GetContentUntil (std::istream & In, std::string ret, const std::string & etag) inline
Definition at line 374 of file primitive_utilities.H.
References SolverUtils::Ostr.
Referenced by operator>>().
     {
       std::ostringstream Ostr;
       std::string line;
       while(std::getline(In,line) && ret.empty()){
         line = line.substr(0,line.find("#"));
         if(!line.empty()){
           std::istringstream Istr(line);
           std::string token;
           Istr >> token;
           if(!token.empty()){
             if(token == etag){
               //            Ostr << line << std::endl;
               ret = Ostr.str();
             }
             else
               Ostr << line << std::endl;
           }
         }
       }
     }
std::string IRAD::Util::GetNextContent (std::istream & In) inline
Definition at line 359 of file primitive_utilities.H.
Referenced by operator>>(), and IRAD::Util::TestObject::Test__GetNextContent().
     {
       std::string line;
       std::string ret;
       while(ret.empty() && std::getline(In,line)){
         line = line.substr(0,line.find("#"));
         std::istringstream Istr(line);
         std::string token;
         Istr >> token;
         if(!token.empty() && token[0] != '#')
           ret.assign(line);
       }
       return(ret);
     }
template<typename OuterContType > Primitive::IndexType IRAD::Util::GetTotalSize (OuterContType & con)
Definition at line 152 of file primitive_utilities.H.
Referenced by main().
     {
       Primitive::IndexType total_size = 0;
       typename OuterContType::iterator ci = con.begin();
       while(ci != con.end()){
         total_size += ci->size();
         ci++;
       }
       return(total_size);
     }
template<typename Container > bool IRAD::Util::HaveOppositeOrientation (Container & c1, Container & c2)
Typically, this is used to determine if two representations of the same face are oriented the same.
Definition at line 316 of file primitive_utilities.H.
Referenced by SolverUtils::Mesh::Connectivity::BuildFaceConnectivity(), and main().
     {
       if(c1.size() != c2.size())
         return(false);
       typename Container::iterator c1i = c1.begin();
       typename Container::reverse_iterator c2i =
         std::find(c2.rbegin(),c2.rend(),*c1i);
       if(c2i == c2.rend())
         return(false);
       while(c1i != c1.end()){
         if(*c1i++ != *c2i++)
           return false;
         if(c2i == c2.rend())
           c2i = c2.rbegin();
       }
       return(true);
     }
template<typename Container > bool IRAD::Util::HaveSameOrientation (Container & c1, Container & c2)
Typically, this is used to determine if two representations of the same face are oriented the same.
Definition at line 288 of file primitive_utilities.H.
Referenced by main().
     {
       if(c1.size() != c2.size())
         return(false);
       typename Container::iterator c1i = c1.begin();
       typename Container::iterator c2i =
         std::find(c2.begin(),c2.end(),*c1i);
       if(c2i == c2.end())
         return(false);
       while(c1i != c1.end()){
         if(*c1i != *c2i)
           return false;
         c1i++;
         c2i++;
         if(c2i == c2.end())
           c2i = c2.begin();
       }
       return(true);
     }
template<typename Container > void IRAD::Util::InvertContainer (const Container & c1, Container & c2)
Definition at line 64 of file primitive_utilities.H.
     {
       unsigned int size = c1.size();
       c2.resize(size);
       typename Container::const_iterator c1i = c1.begin();
       for(unsigned int iii = 0;iii < size;iii++)
         c2[*c1i++] = iii;
     }
template<typename Container > bool IRAD::Util::LessThan (const Container & c1, const Container & c2)
Definition at line 40 of file primitive_utilities.H.
Referenced by SolverUtils::Mesh::TestFace::operator<().
     {
       typename Container::const_iterator c1i = c1.begin();
       typename Container::const_iterator c2i = c2.begin();
       while(c1i != c1.end() && c2i != c2.end()){
         if(*c1i < *c2i)
           return(true);
         if(*c1i++ > *c2i++)
           return(false);
       }
       if(c1i == c1.end()){
         if(c2i == c2.end()){
           return(false);
         }
         else {
           return(true);
         }
       }
       return(false);
     }
template<typename OuterCont , typename OutCont , typename InnerCont , typename MapType > void IRAD::Util::MapElements (OuterCont & src, OutCont & trg, MapType & m)
Definition at line 104 of file primitive_utilities.H.
Referenced by main().
     {
       trg.resize(src.size());
       typename OuterCont::iterator sci = src.begin();
       typename OutCont::iterator oci = trg.begin();
       while(sci != src.end()){
         typename InnerCont::iterator ici = sci->begin();
         while(ici != sci->end())
           oci->push_back(m[*ici++]);
         sci++;
         oci++;
       }
     }
template<typename ListContainerType , typename ListType > Primitive::IndexType IRAD::Util::MaxNodeId (const ListContainerType & fc)
Definition at line 120 of file primitive_utilities.H.
     {
       Primitive::IndexType maxid = 0;
       typename ListContainerType::const_iterator lci = fc.begin();
       while(lci != fc.end()){
         typename ListType::const_iterator li = lci->begin();
         while(li != lci->end()){
           if(maxid < *li){
             maxid = *li;
           }
           li++;
         }
         lci++;
       }
       return(maxid);
     }
template<typename OuterContType , typename InnerContType , typename RetCont , typename idxtype > void IRAD::Util::MultiContainer2CSR (RetCont & xadj, RetCont & adj, OuterContType & source)
Definition at line 164 of file primitive_utilities.H.
     {
       Primitive::IndexType number_of_elements = source.size();
       xadj.resize(number_of_elements+1);
       Primitive::IndexType number_entries = GetTotalSize<OuterContType>(source);
       adj.reserve(number_entries);
       typename OuterContType::iterator si = source.begin();
       Primitive::IndexType elm = 0;
       xadj[elm++] = 0;
       while(si != source.end()){
         typename InnerContType::iterator ei = si->begin();
         xadj[elm] = static_cast<idxtype>(si->size() + xadj[elm-1]);
         elm++;
         while(ei != si->end())
           adj.push_back(static_cast<idxtype>(*ei++-1));
         si++;
       }
     }
template<typename ConType , typename IConType > Primitive::IndexType IRAD::Util::NumberOfEdges (ConType & con)
Definition at line 254 of file primitive_utilities.H.
     {
       typename ConType::iterator ci = con.begin();
       Primitive::IndexType node = 0;
       Primitive::IndexType nedges = 0;
       while(ci != con.end())
         {
           Primitive::IndexType tnode = ++node;
           typename IConType::iterator eni = ci->begin();
           while(eni != ci->end())
             {
               Primitive::IndexType anode = *eni++;
               if((tnode) < anode)
                 nedges++;
             }
           ci++;
         }
       return(nedges);
     }
int IRAD::Util::OpenFile (std::ifstream & Inf, const std::string & filename) inline
Definition at line 545 of file primitive_utilities.H.
     {
       Inf.open(filename.c_str());
       if(!Inf)
         return(-1);
       return 0;
     }
std::ostream & IRAD::Util::operator<< (std::ostream & Ostr, const Util::ParamType & param)
Definition at line 123 of file Parameters.C.
References IRAD::Primitive::KeyValuePairObj< K, V >::Key(), and IRAD::Primitive::KeyValuePairObj< K, V >::Value().
     {
       Ostr << param.Key() << " = " << param.Value();
       return(Ostr);
     }
std::ostream & IRAD::Util::operator<< (std::ostream & Ostr, const Util::ConfigurationObject & cob)
Definition at line 125 of file Configuration.C.
References IRAD::Util::ConfigurationObject::_parameters, and IRAD::Util::ConfigurationObject::_sections.
{
       // Output the configuration of the configuration object itself
       Ostr << "#" << std::endl
            << "#Section Configuration" << std::endl
            << "#" << std::endl
            << static_cast<Util::Parameters>(cob) << std::endl
            << "#Sections " << cob._sections[0] << std::endl
            << "#EndSection" << std::endl;
       // Now output the parameters that configure the application to which
       // this configuration object applies.
       std::vector<Util::ConfigParameters>::const_iterator pi = cob._parameters.begin();
       while(pi != cob._parameters.end()){
         Ostr << "#" << std::endl
              << "#Section " << pi->Name() << std::endl
              << "#" << std::endl
              << static_cast<Util::Parameters>(*pi) << std::endl
              << "#Sections " << cob._sections[pi-cob._parameters.begin()+1] << std::endl
              << "#EndSection" << std::endl;
         pi++;
       }
       return(Ostr);
     }
std::ostream & IRAD::Util::operator<< (std::ostream & oSt, const Util::Parameters & pv)
Definition at line 110 of file Parameters.C.
References IRAD::Util::Parameters::WriteToStream().
     {
       return(pv.WriteToStream(oSt));
     }
std::ostream& IRAD::Util::operator<< (std::ostream & Out, const ComLineObject & cl)
Definition at line 86 of file ComLine.C.
References IRAD::Util::ComLineObject::_arghelp, IRAD::Util::ComLineObject::_argname, IRAD::Util::ComLineObject::_args, IRAD::Util::ComLineObject::_description, IRAD::Util::ComLineObject::_help, and IRAD::Util::ComLineObject::_type.
     {
       if(!cl._description.empty())
         Out << "<description>\n" << cl._description << "</description>\n";
       Out << "<options>\n";
       ComLineObject::const_iterator cli = cl.begin();
       while(cli != cl.end()){
         char opchar = cli->first;
         std::map<char,int>::const_iterator ti = cl._type.find(opchar);
         Out << cli->first << " " << cli->second << " "
             << (ti == cl._type.end() ? 0 : ti->second);
         if(ti != cl._type.end()){
           std::map<char,std::string>::const_iterator ai = cl._argname.find(opchar);
           Out << " " << (ai == cl._argname.end() ? "(unspecified)" : ai->second);
         }
         std::map<char,std::string>::const_iterator hi = cl._help.find(opchar);
         Out << "\n<help>\n" << (hi == cl._help.end() ? "(unspecified)" : hi->second)
             << "\n</help>\n";
         cli++;
       }
       Out << "</options>\n";
       if(!cl._args.empty()){
         Out << "<arguments>\n";
         std::vector<std::pair<std::string,int> >::const_iterator ai = cl._args.begin();
         while(ai != cl._args.end()){
           std::map<std::string,std::string>::const_iterator ahi = cl._arghelp.find(ai->first);
           Out << ai->first << " " << ai->second
               << "\n<help>\n" << (ahi == cl._arghelp.end() ? "(unspecified)" : ahi->second)
               << "\n</help>\n";
           ai++;
         }
         Out << "</arguments>\n";
       }
       return(Out);
     }
std::istream& IRAD::Util::operator>> (std::istream & In, ComLineObject & cl)
Definition at line 14 of file ComLine.C.
References IRAD::Util::ComLineObject::_arghelp, IRAD::Util::ComLineObject::_argname, IRAD::Util::ComLineObject::_description, IRAD::Util::ComLineObject::_error_messages, IRAD::Util::ComLineObject::_help, IRAD::Util::ComLineObject::_type, GetContentUntil(), and GetNextContent().
     {
       std::string line;
       std::string::size_type x;
       line = Util::GetNextContent(In);
       x = line.find("<description>");
       if(x != std::string::npos){
         Util::GetContentUntil(In,cl._description,"</description>");
         line = Util::GetNextContent(In);
       }
       x = line.find("<options>");
       if(x == std::string::npos){
         cl._error_messages.push_back("Config file format error - options section misplaced?.");
         return(In);
       }
       std::string options_content;
       Util::GetContentUntil(In,options_content,"</options>");
       std::istringstream Istr(options_content);
       while(std::getline(Istr,line)){
         std::istringstream OpIn(line);
         std::string token;
         char opchar;
         int optype;
         OpIn >> opchar;
         OpIn >> token;
         OpIn >> optype;
         cl.push_back(std::make_pair(opchar,token));
         cl._type[opchar] = optype;
         if(optype > 0){
           std::string token;
           OpIn >> token;
           cl._argname[opchar] = token;
         }
         std::getline(Istr,line);
         x = line.find("<help>");
         if(x == std::string::npos){
           cl._error_messages.push_back("Configuration input format error in option help section.");
           return(In);
         }
         cl._help[opchar] = "";
         Util::GetContentUntil(Istr,cl._help[opchar],"</help>");
       }
       line = Util::GetNextContent(In);
       if(line.empty())
         return(In);
       x = line.find("<arguments>");
       if(x == std::string::npos){
         cl._error_messages.push_back("Configuration intput format error in argument section.");
         return(In);
       }
       std::string argsection;
       Util::GetContentUntil(In,argsection,"</arguments>");
       Istr.str(argsection);
       while(std::getline(Istr,line)){
         std::istringstream ArgIn(line);
         std::string argname;
         int argtype;
         ArgIn >> argname >> argtype;
         cl._arghelp[argname] = argtype;
         std::string tag;
         ArgIn >> tag;
         std::string::size_type x = tag.find("<help>");
         if(x == std::string::npos){
           cl._error_messages.push_back("Configuration input format error in arghelp section.");
           return(In);
         }
         cl._arghelp[argname] = "";
         Util::GetContentUntil(In,cl._arghelp[argname],"</help>");
       }
       return(In);
     }
std::istream & IRAD::Util::operator>> (std::istream & Istr, Util::ConfigurationObject & cob)
Definition at line 151 of file Configuration.C.
References IRAD::Util::ConfigurationObject::_parameters, IRAD::Util::ConfigurationObject::_sections, IRAD::Util::ConfigurationObject::AdvanceToNextSection(), IRAD::Util::ConfigurationObject::ExtractSection(), IRAD::Util::ConfigParameters::Name(), SolverUtils::Ostr, IRAD::Util::ConfigurationObject::ReadSection(), and TokenizeString().
{
       // Read in the configuration for the configuration object itself
       std::string configsection = cob.ExtractSection("Configuration",Istr);
       cob.Name("Configuration");
       std::istringstream ConfigIstr(configsection);
       ConfigIstr >> static_cast<Util::Parameters &>(cob);
       // Now read in the one token name for the application which this
       // object configures and stuff it into the _sections vector.
       ConfigIstr.clear();
       ConfigIstr.str(configsection);
       std::string line;
       cob._sections.resize(0);
       while(std::getline(ConfigIstr,line) && cob._sections.empty()){
         if(!line.empty()){
           std::vector<std::string> tokens;
           Util::TokenizeString(tokens,line);
           std::vector<std::string>::iterator ti = tokens.begin();
           if(*ti++ == "#Sections"){
             std::ostringstream Ostr;
             while(ti != tokens.end())
               Ostr << *ti++ << " ";
             cob._sections.push_back(Ostr.str());
           }
         }
       }
       // Advance to the next section - if found, then read the
       // section from the input stream and stuff it into the
       // _parameters vector.
       std::string sectionname = cob.AdvanceToNextSection(Istr);
       while(!sectionname.empty()){
         Util::ConfigParameters params(sectionname);
         std::string section = cob.ReadSection(Istr);
         std::istringstream SectionIstr(section);
         SectionIstr >> static_cast<Util::Parameters &>(params);
         cob._parameters.push_back(params);
         // Re-read the section and extract the sections to
         // which the currently read section is linked.  This
         // is how we track the relationships between sections
         // as an aid for automatically generating user interfaces
         // to the configuration object.
         SectionIstr.clear();
         SectionIstr.str(section);
         std::string line;
         bool done = false;
         while(std::getline(SectionIstr,line) && !done){
           if(!line.empty()){
             std::vector<std::string> tokens;
             Util::TokenizeString(tokens,line);
             std::vector<std::string>::iterator ti = tokens.begin();
             if(*ti++ == "#Sections"){
               std::ostringstream Ostr;
               while(ti != tokens.end())
                 Ostr << *ti++ << " ";
               cob._sections.push_back(Ostr.str());
               done = true;
             }
           }
         }
         sectionname = cob.AdvanceToNextSection(Istr);
       }
       return(Istr);
     }
std::istream & IRAD::Util::operator>> (std::istream & iSt, Util::Parameters & pv)
Definition at line 116 of file Parameters.C.
References IRAD::Util::Parameters::ReadFromStream().
     {
       return(pv.ReadFromStream(iSt));
     }
template<typename NumType > void IRAD::Util::ProcessRange (NumType & t1, NumType & t2, const std::string stinter)
Definition at line 513 of file primitive_utilities.H.
     {
       if(!stinter.empty()){
         std::string::size_type x = stinter.find(":");
         std::string t1s = stinter;
         std::string t2s = stinter;
         if(x != std::string::npos){
           t1s = stinter.substr(0,x);
           t2s = stinter.substr(x+1);
           if(!t2s.empty()){
             std::istringstream Istr(t2s);
             Istr >> t2;
           }
         }
         else {
           t1s.erase();
         }
         if(!t1s.empty()){
           std::istringstream Istr(t1s);
           Istr >> t1;
         }
         if(!t2s.empty()){
           std::istringstream Istr(t2s);
           Istr >> t2;
         }
       }
     }
template<class Vals > void IRAD::Util::SortPermutation (const Vals & values, std::vector< unsigned int > & v)
Definition at line 348 of file primitive_utilities.H.
References CreateCmpPairs().
     {
       unsigned int size = values.size();
       v.clear();
       v.reserve(size);
       for(unsigned int i=0; i < size; ++i)
         v.push_back(i);
       std::sort(v.begin(), v.end(), CreateCmpPairs(values));
     };
int IRAD::Util::String2Buf (const std::string & instr, void ** buf) inline
Definition at line 398 of file primitive_utilities.H.
Referenced by SolverUtils::GeoPrim::PBox::Pack(), and IRAD::Comm::MobileObject::Pack().
     {
       if(instr.empty())
         return 0;
       int rval = instr.size();
       *buf = new char [rval];
       void *resl = std::memcpy(*buf,instr.c_str(),rval);
       if(!resl)
         return(0);
       return(rval);
     }
const std::string IRAD::Util::stripdirs (const std::string & pname) inline
Strips the absolute path to recover the base file name or the executable file name.
Definition at line 461 of file primitive_utilities.H.
Referenced by IRAD::Global::GlobalObj< StackType, ErrorType, ProfilerType >::GlobalObj(), IRAD::Global::ParallelGlobalObj< CommunicatorType, StackType, ErrorType, ProfilerType >::Init(), and IRAD::Util::ComLineObject::Record().
     {
       std::string retval;
       std::string::size_type x = pname.find("/");
       if(x == std::string::npos)
         return(pname);
       return(pname.substr(pname.find_last_of("/")+1));
     }
void IRAD::Util::TokenizeString (std::vector< std::string > & tokens, const std::string & source) inline
Breaks source string up into a vector of space delimited tokens
Definition at line 476 of file primitive_utilities.H.
Referenced by IRAD::Util::ConfigurationObject::AdvanceToNextSection(), IRAD::Util::ConfigurationObject::ExtractSection(), operator>>(), IRAD::Util::Parameters::ReadFromStream(), and IRAD::Util::ConfigurationObject::ReadSection().
     {
       tokens.resize(0);
       std::istringstream Istr(source);
       std::string token;
       while(Istr >> token)
         tokens.push_back(token);
     }
void IRAD::Util::TokenizeString (std::vector< std::string > & tokens, const std::string & source, const char delim) inline
Breaks source string up into a vector of tokens delimited by specified delimiter
Definition at line 491 of file primitive_utilities.H.
References SolverUtils::Ostr.
     {
       tokens.resize(0);
       std::string::size_type ssize = source.size();
       std::string::size_type x = 0;
       std::ostringstream Ostr;
       std::string token;
       while(x < ssize){
         if(source[x] != delim)
           token += source[x];
         if((source[x] == delim) || (x == (ssize-1))){
           tokens.push_back(token);
           token.erase();
         }
         x++;
       }
     }
void IRAD::Util::Trim (std::string & instr, bool preserve_newline = false) inline
Definition at line 413 of file primitive_utilities.H.
References SolverUtils::Ostr.
Referenced by COM::TestingObject< ResultsType >::Test__ModuleFunctionTest().
     {
       std::istringstream Istr(instr);
       std::string line;
       std::ostringstream Ostr;
       while(std::getline(Istr,line)){
         std::istringstream Line(line);
         std::string token;
         Line >> token;
         Ostr << token;
         while(Line >> token)
           if(!token.empty())
             Ostr << " " << token;
         if(preserve_newline)
           Ostr << "\n";
       }
       instr = Ostr.str();
     }
const std::string IRAD::Util::Trimmed (const std::string & instr, bool preserve_newline = false) inline
Definition at line 435 of file primitive_utilities.H.
References SolverUtils::Ostr.
     {
       std::istringstream Istr(instr);
       std::string line;
       std::ostringstream Ostr;
       while(std::getline(Istr,line)){
         std::istringstream Line(line);
         std::string token;
         Line >> token;
         Ostr << token;
         while(Line >> token)
           if(!token.empty())
             Ostr << " " << token;
         if(preserve_newline)
           Ostr << "\n";
       }
       return(Ostr.str());
     }
void IRAD::Util::Vectorize (std::vector< std::string > & retVal, const char ** in) inline
Definition at line 555 of file primitive_utilities.H.
     {
       int i = 0;
       while(in[i] != NULL)
         retVal.push_back(in[i++]);
     }
void IRAD::Util::Vectorize (std::vector< std::string > & retVal, const char ** in, int n) inline
Definition at line 563 of file primitive_utilities.H.
     {
       //  retVal.resize(0);
       if(n <= 0) return;
       int i = 0;
       while((in[i] != NULL) && i < n)
         retVal.push_back(in[i++]);
     }