IMPACT: COM Namespace Reference
COM Namespace Reference
This file indirectly includes the following files: iostream, map, string, vector, and com_basic.h.
Namespaces
TestFixture
Namespace for storing simple test utility fixtures.
Classes
class COM_base
The base class for COM implementations.
class TransferSolver
class TestingObject
Project-specific testing object.
class ParallelTestingObject
Project-specific parallel testing object.
class TestComLine
ComLineObject for COM testing command-line interface.
class TestSolver
class TestModule
Typedefs
typedef void(* Failure_function)(const char *, const char *, const char *, int, const char *)
Function type for error handlers.
typedef
IRAD::Comm::CommunicatorObject CommType
Convenience typedef for CommunicatorObject.
typedef IRAD::Util::TestResults TestResults
Project-specific test results type.
Enumerations
enum Failure_behaviour { ABORT, EXIT, EXIT_WITH_SUCCESS, CONTINUE }
Behavior of failures.
Functions
void assertion_fail (const char *, const char *, int, const char *)
Default error handler.
Failure_behaviour set_error_behaviour (Failure_behaviour eb)
Controls the behavior when an assertion fails.
Failure_function set_error_handler (Failure_function handler)
Sets the handler for assertion-failures.
int ParallelTest (int argc, char *argv[])
Drives the COM::TestObject.
int Test (int argc, char *argv[])
Drives the COM::TestObject for the COM tests.
void IntFunction (int *io_data)
Simple test function sets integer to 1.
void ConstIntFunction (const int *idata, void *string_data)
Simple test function writes an integer to string.
void OptionalArgsFunction (int *a0, int *a1, int *a2, int *a3, int *a4, int *a5, int *a6, int *a7, int *a8, int *a9, int *a10, int *a11, int *a12)
Test function for optional arguments.
Typedef Documentation
typedef IRAD::Comm::CommunicatorObject COM::CommType
Definition at line 40 of file COMTest.H.
typedef void(* COM::Failure_function)(const char *, const char *, const char *, int, const char *)
Definition at line 25 of file com_assertion.h.
typedef IRAD::Util::TestResults COM::TestResults
Test results types can be custom implemented by the project developer. The requirement is that they produce the proper test results output when used with outstreams.
Definition at line 57 of file COMTest.H.
Enumeration Type Documentation
enum COM::Failure_behaviour
Enumerator
ABORT
EXIT
EXIT_WITH_SUCCESS
CONTINUE
Definition at line 21 of file com_assertion.h.
 { ABORT, EXIT, EXIT_WITH_SUCCESS, CONTINUE };
Function Documentation
void COM::assertion_fail (const char * , const char * , int , const char *)
Definition at line 50 of file assertion.C.
 {
     extern void printStackBacktrace();
     (*_error_handler)("assertion", expr, file, line, msg);
     printStackBacktrace(); // Print stack backtrace
     switch (_error_behaviour) {
     case ABORT:
         abort();
     case EXIT:
         exit(1);  // EXIT_FAILURE
     case EXIT_WITH_SUCCESS:
         exit(0);  // EXIT_SUCCESS
     case CONTINUE:
         ;
     }
 }
void COM::ConstIntFunction (const int * idata, void * string_data)
Definition at line 32 of file COM/testing/src/TestModule.C.
References SolverUtils::Ostr.
Referenced by COM::TestModule::Load().
   {
     std::ostringstream Ostr;
     std::string *sdptr = static_cast<std::string *>(string_data);
     Ostr << *idata;
     sdptr->assign(Ostr.str());
   };
void COM::IntFunction (int * io_data)
Definition at line 25 of file COM/testing/src/TestModule.C.
Referenced by COM::TestModule::Load().
   {
     if(io_data)
       *io_data = 1;
   };
void COM::OptionalArgsFunction (int * a0, int * a1, int * a2, int * a3, int * a4, int * a5, int * a6, int * a7, int * a8, int * a9, int * a10, int * a11, int * a12)
This function tests the functionality of optional arguments for registered functions. It will count the number of non-null arguments and sum their values. If the number of non-null arguments passed in does not match that specified by a0 on input, then -sum is returned. Otherwise the sum will be returned in a0.
Parameters
a0 integer specifies number of optional arguments on input
Returns
a0 Sum of all non-null arguments, or -1 if error detected
Definition at line 53 of file COM/testing/src/TestModule.C.
Referenced by COM::TestModule::Load().
{
     int number_of_nonnull_arguments = 0;
     int nonnull_count = 0;
     if(a0)
       number_of_nonnull_arguments = *a0;
     else
       return;
     *a0 = 0;
     if(a1){
       nonnull_count++;
       *a0 += *a1;
     }
     if(a2){
       nonnull_count++;
       *a0 += *a2;
     }
     if(a3){
       nonnull_count++;
       *a0 += *a3;
     }
     if(a4){
       nonnull_count++;
       *a0 += *a4;
     }
     if(a5){
       nonnull_count++;
       *a0 += *a5;
     }
     if(a6){
       nonnull_count++;
       *a0 += *a6;
     }
     if(a7){
       nonnull_count++;
       *a0 += *a7;
     }
     if(a8){
       nonnull_count++;
       *a0 += *a8;
     }
     if(a9){
       nonnull_count++;
       *a0 += *a9;
     }
     if(a10){
       nonnull_count++;
       *a0 += *a10;
     }
     if(a11){
       nonnull_count++;
       *a0 += *a11;
     }
     if(a12){
       nonnull_count++;
       *a0 += *a12;
     }
     if(nonnull_count != number_of_nonnull_arguments)
       *a0 *= -1;
   }
int COM::ParallelTest (int argc, char * argv[])
Parameters
argc number of string command line tokens
argv string command line tokens
Returns
0 if successful, 1 otherwise
Drives the COM::TestObject, which should encapsulate all the tests for the COM namespace.
Command line documentation:
      impact_test [-h] [-v [level] -o <filename> -l <filename> -n <TestName> ]
      -h,--help
         Print out long version of help and exit.
      -v,--verblevel [level]
         Set the verbosity level. (default = 0)
      -o,--output <filename>
         Set the output file to <filename>. (default = stdout)
      -l,--list <filename>
         Set the list file name to <filename>. (no default). The list file should be a text file with one test name per line.
      -n,--name <TestName>
         Run test by name. (no default)
Definition at line 50 of file ParallelTestCOM.C.
References IRAD::Comm::CommunicatorObject::Check(), COM_finalize(), COM_init(), COM_initialized(), IRAD::Util::ComLineObject::ErrorReport(), IRAD::Util::ComLineObject::GetOption(), COM::TestComLine::Initialize(), IRAD::Util::ComLineObject::LongUsage(), COM::ParallelTestingObject< CommType, ResultsType >::Process(), IRAD::Util::ComLineObject::ProcessOptions(), IRAD::Comm::CommunicatorObject::Rank(), COM::ParallelTestingObject< CommType, ResultsType >::RunTest(), IRAD::Comm::CommunicatorObject::SetExit(), IRAD::Util::ComLineObject::ShortUsage(), IRAD::Comm::CommunicatorObject::Size(), and IRAD::Util::TestResults::UpdateResult().
Referenced by main().
   {
     // This sets everything up with MPI
     COM::CommType communicator(&argc,&argv);
     int rank  = communicator.Rank();
     int nproc = communicator.Size();
     bool do_stdout = !rank;
     int com_initialized = COM_initialized();
     bool com_initialized_pass = (com_initialized <= 0);
     COM_init(&argc, &argv);
     if(com_initialized_pass)
       com_initialized = (COM_initialized() > 0);
     if(do_stdout)
       std::cout << "Beginning COM::ParallelTest" << std::endl;
     // The default verbosity is 0
     int verblevel = 0;
     // This line creates the COM::TestComLine object and passes in
     // the command line arguments as a (const char **).
     TestComLine comline((const char **)(argv));
     // The call to comline.Initialize() reads the command line arguments
     // from the array passed in the previous line.
     comline.Initialize();
     // The ProcessOptions() call does detailed examination of the command
     // line arguments to check for user errors or other problems. This call
     // will return non-zero if there were errors on the commandline.
     int clerr = comline.ProcessOptions();
     // Check if the user just wanted to get the help and exit
     if(!comline.GetOption("help").empty()){
       // Print out the "long usage" (i.e. help) message to stdout
       if(do_stdout){
         std::cout << comline.LongUsage() << std::endl;
         if(verblevel > 1)
           std::cout << "COM::ParallelTest: Exiting test function (success)"
                     << std::endl;
       }
       communicator.SetExit(1);
     }
     if(communicator.Check())
       return(0);
     if(clerr){
       if(do_stdout){
         std::cout << comline.ErrorReport() << std::endl
                   << std::endl << comline.ShortUsage() << std::endl;
         if(verblevel > 2)
           std::cout << "COM::ParallelTest: Exiting test function (fail)" << std::endl;
       }
       communicator.SetExit(1);
     }
     if(communicator.Check())
       return(1);
     // These outstreams allow the output to file to be set up and separated
     // from the stdout.
     std::ofstream Ouf;
     std::ostream *Out = NULL;
     if(do_stdout)
       Out = &std::cout;
     // The next few lines populate some strings based on the
     // users input from the commandline.
     std::string OutFileName(comline.GetOption("output"));
     std::string TestName(comline.GetOption("name"));
     std::string ListName(comline.GetOption("list"));
     std::string sverb(comline.GetOption("verblevel"));
     // The following block parses and sets the verbosity level
     if(!sverb.empty()){
       verblevel = 1;
       if(sverb != ".true."){
         std::istringstream Istr(sverb);
         Istr >> verblevel;
         if(verblevel < 0)
           verblevel = 1;
       }
     }
     // This block sets up the output file if the user specified one
     if(!OutFileName.empty()){
       if(Out){
         Ouf.open(OutFileName.c_str());
         if(!Ouf){
           std::cout << "COM::ParallelTest> Error: Could not open output file, "
                     <<  OutFileName << " for test output. Exiting (fail)." << std::endl;
           communicator.SetExit(1);
         }
         Out = &Ouf;
       }
       if(communicator.Check())
         return(1);
     }
     if(verblevel > 1 && Out)
       *Out << "COM::ParallelTest: Entering test function" << std::endl;
     // Make an instance of the COM testing object, COM::ParallelTestingObject
     COM::ParallelTestingObject<COM::CommType,COM::TestResults> test(communicator);
     // Make an instance of the COM results object, COM::TestResults
     COM::TestResults results;
     // If the user specified a name, then run only the named test
     if(!TestName.empty()){
       // This call runs a test by name
       test.RunTest(TestName,results);
     }
     // Otherwise, if the user specified a list, then read the list and
     // run the listed tests.
     else if(!ListName.empty()){
       std::ifstream ListInf;
       ListInf.open(ListName.c_str());
       if(!ListInf){
         if(Out)
           *Out << "COM::ParallelTest> Error: Could not open list of tests in file "
                << ListName << ". Exiting (fail)." << std::endl;
         communicator.SetExit(1);
       }
       if(communicator.Check())
         return(1);
       std::string testname;
       while(std::getline(ListInf,testname))
         test.RunTest(testname,results);
       ListInf.close();
     }
     else {
       // This call runs all the tests for the COM namespace.
       test.Process(results);
     }
     COM_finalize();
     results.UpdateResult("COM::ParallelFinalize:Works",true);
     if(com_initialized_pass)
       com_initialized_pass = (COM_initialized() <= 0);
     results.UpdateResult("COM::ParallelInitialized:Works",com_initialized_pass);
     if(Out)
       *Out << results << std::endl;
     if(Out && Ouf)
       Ouf.close();
     if((verblevel > 1) && Out)
       *Out << "COM::ParallelTest: Exiting test function (success)" << std::endl;
     return(0);
   }
Failure_behaviour COM::set_error_behaviour (Failure_behaviour eb)
Failure_function COM::set_error_handler (Failure_function handler)
int COM::Test (int argc, char * argv[])
Parameters
argc number of string command line tokens
argv string command line tokens
Returns
0 if successful, 1 otherwise
Drives the COM::TestObject for COM, which should encapsulate all the tests for COM.
Command line documentation:
      impact_test [-h] [-v [level] -o <filename> -l <filename> -n <TestName> ]
      -h,--help
         Print out long version of help and exit.
      -v,--verblevel [level]
         Set the verbosity level. (default = 0)
      -o,--output <filename>
         Set the output file to <filename>. (default = stdout)
      -l,--list <filename>
         Set the list file name to <filename>. (no default). The list file should be a text file with one test name per line.
      -n,--name <TestName>
         Run test by name. (no default)
Definition at line 45 of file TestCOM.C.
References COM_finalize(), COM_init(), COM_initialized(), IRAD::Util::ComLineObject::ErrorReport(), IRAD::Util::ComLineObject::GetOption(), COM::TestComLine::Initialize(), IRAD::Util::ComLineObject::LongUsage(), COM::TestingObject< ResultsType >::Process(), IRAD::Util::ComLineObject::ProcessOptions(), COM::TestingObject< ResultsType >::RunTest(), IRAD::Util::ComLineObject::ShortUsage(), and IRAD::Util::TestResults::UpdateResult().
Referenced by main().
   {
     int com_initialized = COM_initialized();
     bool com_initialized_pass = (com_initialized <= 0);
     MPI_Init(&argc,&argv);
     COM_init(&argc, &argv);
     if(com_initialized_pass)
       com_initialized = (COM_initialized() > 0);
     // The default verbosity is 0
     int verblevel = 0;
     // This line creates the COM::TestComLine object and passes in
     // the command line arguments as a (const char **).
     TestComLine comline((const char **)(argv));
     // The call to comline.Initialize() reads the command line arguments
     // from the array passed in the previous line.
     comline.Initialize();
     // The ProcessOptions() call does detailed examination of the command
     // line arguments to check for user errors or other problems. This call
     // will return non-zero if there were errors on the commandline.
     int clerr = comline.ProcessOptions();
     // Check if the user just wanted to get the help and exit
     std::cout << "Here here here" << std::endl;
     if(!comline.GetOption("help").empty()){
       // Print out the "long usage" (i.e. help) message to stdout
       std::cout << comline.LongUsage() << std::endl;
       if(verblevel > 2)
         std::cout << "COM::Test: Exiting test function (success)" << std::endl;
       return(0);
     }
     if(clerr){
       std::cout << comline.ErrorReport() << std::endl
                 << std::endl << comline.ShortUsage() << std::endl;
       if(verblevel > 2)
         std::cout << "COM::Test: Exiting test function (fail)" << std::endl;
       return(1);
     }
     // These outstreams allow the output to file to be set up and separated
     // from the stdout.
     std::ofstream Ouf;
     std::ostream *Out = &std::cout;
     // The next few lines populate some strings based on the
     // users input from the commandline.
     std::string OutFileName(comline.GetOption("output"));
     std::string TestName(comline.GetOption("name"));
     std::string ListName(comline.GetOption("list"));
     std::string sverb(comline.GetOption("verblevel"));
     // The following block parses and sets the verbosity level
     if(!sverb.empty()){
       verblevel = 1;
       if(sverb != ".true."){
         std::istringstream Istr(sverb);
         Istr >> verblevel;
         if(verblevel < 0)
           verblevel = 1;
       }
     }
     // This block sets up the output file if the user specified one
     if(!OutFileName.empty()){
       Ouf.open(OutFileName.c_str());
       if(!Ouf){
         std::cout << "COM::Test> Error: Could not open output file, "
                   <<  OutFileName << " for test output. Exiting (fail)." << std::endl;
         return(1);
       }
       Out = &Ouf;
     }
     if(verblevel > 2)
       std::cout << "COM::Test: Entering test function" << std::endl;
     // Make an instance of the COM testing object, COM::TestingObject
     COM::TestingObject<COM::TestResults> test;
     // Make an instance of the COM results object, COM::TestResults
     TestResults results;
     results.UpdateResult("COM::Init:Works",true);
     // If the user specified a name, then run only the named test
     if(!TestName.empty()){
       // This call runs a test by name
       test.RunTest(TestName,results);
     }
     // Otherwise, if the user specified a list, then read the list and
     // run the listed tests.
     else if(!ListName.empty()){
       std::ifstream ListInf;
       ListInf.open(ListName.c_str());
       if(!ListInf){
         std::cout << "COM::Test> Error: Could not open list of tests in file "
                   << ListName << ". Exiting (fail)." << std::endl;
         return(1);
       }
       std::string testname;
       while(std::getline(ListInf,testname))
         test.RunTest(testname,results);
       ListInf.close();
     }
     else {
       // This call runs all the tests for COM.
       test.Process(results);
     }
     COM_finalize();
     results.UpdateResult("COM::Finalize:Works",true);
     if(com_initialized_pass)
       com_initialized_pass = (COM_initialized() <= 0);
     results.UpdateResult("COM::Initialized:Works",com_initialized_pass);
     *Out << results << std::endl;
     if(Ouf)
       Ouf.close();
     if(verblevel > 2)
       *Out << "COM::Test: Exiting test function (success)" << std::endl;
     MPI_Finalize();
     return(0);
   }