IMPACT: SolverUtils::Mesh Namespace Reference
SolverUtils::Mesh Namespace Reference
Classes
struct Border
struct BorderData
Border data in CSR format.
class BSExtent
Simple Block Structured Mesh object.
class Connectivity
General connectivity object.
class GenericCell_2
class GenericElement
class GeometricEntity
Connects continuous to discrete.
class MeshUtilityObject
class NeighborHood
class NodalCoordinates
struct PartInfo
class Partition
class SolnMetaData
class Stats
class TestFace
struct UnstructuredMesh
Typedefs
typedef IRAD::Primitive::IndexType IndexType
typedef IRAD::Primitive::ubyte CellEntityIDType
typedef std::pair
< Mesh::IndexType,
CellEntityIDType > SubEntityId
typedef std::pair< SubEntityId,
SubEntityId > SymbolicFace
typedef std::vector
< Mesh::IndexType > IndexVec
typedef
IRAD::Primitive::MultiContainer
< Mesh::IndexType >::VecVec MultiVec
typedef
IRAD::Primitive::MultiContainer
< Mesh::IndexType,
Mesh::IndexType >::VecMap VecMap
typedef IRAD::Primitive::ubyte GeoDimType
typedef std::string GeoNameType
Functions
int GenerateCartesianGrid (Mesh::NodalCoordinates &nc, Mesh::BSExtent< Mesh::IndexType > &gridextent, std::vector< Mesh::IndexType > &gridsizes, GeoPrim::CBox &box)
template<typename OuterCont , typename OutCont , typename InnerCont , typename MapType >
void MapElements (OuterCont &src, OutCont &trg, MapType &m)
template<typename ListContainerType , typename ListType >
Mesh::IndexType MaxNodeId (const ListContainerType &fc)
Return the maximum of all elements of a multicontainer.
template<typename OuterContType , typename InnerContType , typename RetCont , typename idxtype >
void Container2CSR (RetCont &xadj, RetCont &adj, OuterContType &source)
Populate OutCont with a flat list of entries from a multicontainer.
template<typename ListContainerType , typename ListType >
void CreateAdjacentNodeList (std::vector< std::list< Mesh::IndexType > > &anodelist, ListContainerType &fc, Mesh::IndexType nnodes=0)
Given an array of adjacent node lists (like an array of face connectivities), this function will loop thru and create a list of unique adjacent nodes for each node with the nodes that are actually adjacent in the lists
template<typename ListContainerType , typename ListType >
void AdjEList (std::vector< std::list< Mesh::IndexType > > &aelist, ListContainerType &dual_con, unsigned long nel=0)
Given an array of adjacent node lists (like an array of face connectivities), this function will loop thru and create a list of unique adjacent nodes for each node Note that this is a little different from the AdjNodeList because in this version every node in each list is considered adjacent.
template<typename ConType , typename IConType >
Mesh::IndexType NumberOfEdges (ConType &con)
template<typename ContainerType , typename Icont >
void FormGraph (const ContainerType &adjlist)
void DisplaceNodalCoordinates (Mesh::NodalCoordinates &nc, std::vector< double > &displacements)
int Skin (Mesh::UnstructuredMesh &inmesh, Mesh::UnstructuredMesh &outmesh)
int WriteVTKToStream (Mesh::UnstructuredMesh &mesh, std::ostream &Ostr)
int WriteVTKToStream (const std::string &name, Mesh::UnstructuredMesh &mesh, std::ostream &Ostr)
int ReadWRLFromStream (Mesh::UnstructuredMesh &mesh, std::istream &Istr)
int ReadMesh (const std::string &path, Mesh::UnstructuredMesh &mesh)
int ReadMeshFromStream (Mesh::UnstructuredMesh &mesh, std::istream &Inf)
int GetMeshCentroids (Mesh::NodalCoordinates &nc, Mesh::Connectivity &conn, std::vector< double > &centroids)
int CollideCellsWithBox (Mesh::NodalCoordinates &nc, Mesh::Connectivity &conn, GeoPrim::CBox &box, std::vector< Mesh::IndexType > &candidates, std::vector< Mesh::IndexType > &cells)
int CollideMeshWithBox (Mesh::NodalCoordinates &nc, Mesh::Connectivity &conn, GeoPrim::CBox &box, std::vector< Mesh::IndexType > &cells)
bool NewtonRaphson (GeoPrim::CVector &natc, Mesh::IndexType elnum, const GenericElement &el, const Connectivity &ec, const NodalCoordinates &nc, const GeoPrim::CPoint &point)
Newton-Raphson method, customized for using the GeoPrimitives and computational mesh constructs.
bool NewtonRaphson_2 (GeoPrim::CVector &natc, Mesh::IndexType elnum, const GenericCell_2 &el, const Connectivity &ec, const NodalCoordinates &nc, const GeoPrim::CPoint &point)
Newton-Raphson method, customized for using the GeoPrimitives and computational mesh constructs.
bool LUDcmp (GeoPrim::CVector a[], int indx[])
void LUBksb (GeoPrim::CVector a[], int indx[], GeoPrim::CVector &b)
void GetCoordinateBounds (NodalCoordinates &nc, std::vector< double > &)
void GetMeshBoxes (const NodalCoordinates &nc, const Connectivity &ec, GeoPrim::CBox &mesh_box, GeoPrim::CBox &small_box, GeoPrim::CBox &large_box)
Bounding boxes for a mesh.
void FindElementsInBox (const GeoPrim::CBox &box, const NodalCoordinates &nc, const Connectivity &dc,std::list< Mesh::IndexType > &elements)
Get elements in box.
Mesh::IndexType FindPointInCells (const GeoPrim::CPoint &p,const NodalCoordinates &nc,const Connectivity &ec,const std::vector< Mesh::IndexType > &elements,GeoPrim::CVector &natc)
Locate element containing given physical point.
Mesh::IndexType GlobalFindPointInMesh (const GeoPrim::CPoint &p, const NodalCoordinates &nc, const Connectivity &ec, const Connectivity &dc, const GeoPrim::CBox &box, GeoPrim::CVector &natc)
Mesh::IndexType FindPointInMesh_2 (const GeoPrim::CPoint &p,const NodalCoordinates &nc,const Connectivity &ec,const Connectivity &dc,const GeoPrim::CBox &box,GeoPrim::CVector &natc)
Locate element containing given physical point.
Mesh::IndexType FindPointInMesh (const GeoPrim::CPoint &p,const NodalCoordinates &nc,const Connectivity &ec,const Connectivity &dc,const GeoPrim::CBox &box,GeoPrim::CVector &natc)
Locate element containing given physical point.
void writeVtkData ()
Writes the merged grid and its data in VTK UNSTRUCTURED_GRID file format.
void writeVtkFiles (std::vector< Mesh::UnstructuredMesh > &m)
Writes the set of meshes into separate VTK files that can be visualized with Paraview.
void printVtk (std::vector< double > &vlist, std::vector< std::vector< int > > &elist)
This method prints the global grid in VTK file format.
bool TRIANGLE_OK (const GeoPrim::C3Point &p1, const GeoPrim::C3Point &p2, const GeoPrim::C3Point &p3)
bool QUAD_OK (const GeoPrim::C3Point &p1, const GeoPrim::C3Point &p2, const GeoPrim::C3Point &p3, const GeoPrim::C3Point &p4)
std::istream & operator>> (std::istream &iSt, Mesh::GeometricEntity &ge)
std::istream & operator>> (std::istream &iSt, Mesh::Connectivity &ec)
std::istream & operator>> (std::istream &iSt, Mesh::NodalCoordinates &nc)
std::ostream & operator<< (std::ostream &oSt, const Mesh::NodalCoordinates &nc)
std::ostream & operator<< (std::ostream &oSt, const Mesh::Connectivity &ec)
std::ostream & operator<< (std::ostream &oSt, const Mesh::GeometricEntity &ge)
void CheckCoordinates (double *coords, int number_of_points, double tol)
void writeVtkFiles (const std::string &outputfile, const std::vector< int > &paneIds, std::vector< Mesh::UnstructuredMesh > &meshes, std::vector< std::vector< int > > &masks)
void writeVtkData (NodalCoordinates &nc, Connectivity &con, const std::string &filename, std::vector< double > &soln)
Writes the merged grid and its data in VTK UNSTRUCTURED_GRID file format.
Variables
const double TOL = GeoPrim::TOL
const double LTOL = 0.0 - TOL
const double HTOL = 1.0 + TOL
Typedef Documentation
typedef IRAD::Primitive::ubyte SolverUtils::Mesh::CellEntityIDType
Definition at line 61 of file Mesh.H.
typedef IRAD::Primitive::ubyte SolverUtils::Mesh::GeoDimType
Definition at line 67 of file Mesh.H.
typedef std::string SolverUtils::Mesh::GeoNameType
Definition at line 68 of file Mesh.H.
typedef IRAD::Primitive::IndexType SolverUtils::Mesh::IndexType
Definition at line 60 of file Mesh.H.
typedef std::vector<Mesh::IndexType> SolverUtils::Mesh::IndexVec
Definition at line 64 of file Mesh.H.
typedef IRAD::Primitive::MultiContainer<Mesh::IndexType>::VecVec SolverUtils::Mesh::MultiVec
Definition at line 65 of file Mesh.H.
typedef std::pair<Mesh::IndexType,CellEntityIDType> SolverUtils::Mesh::SubEntityId
Definition at line 62 of file Mesh.H.
typedef std::pair<SubEntityId,SubEntityId> SolverUtils::Mesh::SymbolicFace
Definition at line 63 of file Mesh.H.
typedef IRAD::Primitive::MultiContainer<Mesh::IndexType,Mesh::IndexType>::VecMap SolverUtils::Mesh::VecMap
Definition at line 66 of file Mesh.H.
Function Documentation
template<typename ListContainerType , typename ListType > void SolverUtils::Mesh::AdjEList (std::vector< std::list< Mesh::IndexType > > & aelist, ListContainerType & dual_con, unsigned long nel = 0)
Definition at line 192 of file Mesh.H.
     {
       if(nel == 0)
         nel = MaxNodeId<ListContainerType,ListType>(dual_con);
       aelist.resize(nel);
       typename ListContainerType::iterator lci = dual_con.begin();
       while(lci != dual_con.end())
         {
           typename ListType::iterator li = lci->begin();
           while(li != lci->end()){
             Mesh::IndexType this_node = *li++ - 1;
             typename ListType::iterator li2 = li;
             while(li2 != lci->end()){
               Mesh::IndexType nexnode = *li2++ - 1;
               aelist[this_node].push_back(nexnode+1);
               aelist[nexnode].push_back(this_node+1);
             }
           }
           lci++;
         }
       for(Mesh::IndexType node = 0;node < nel;node++)
         {
           aelist[node].sort();
           aelist[node].unique();
         }
     }
void SolverUtils::Mesh::CheckCoordinates (double * coords, int number_of_points, double tol)
Definition at line 2512 of file Mesh.C.
Referenced by ReadWRLFromStream().
     {
       for(int i = 0; i < number_of_points*3;i++)
         {
           if(std::fabs(coords[i]) < tol && (coords[i] != 0.0)){
             coords[i] = 0.0;
           }
         }
     }
int SolverUtils::Mesh::CollideCellsWithBox (Mesh::NodalCoordinates & nc, Mesh::Connectivity & conn, GeoPrim::CBox & box, std::vector< Mesh::IndexType > & candidates, std::vector< Mesh::IndexType > & cells)
Definition at line 209 of file Mesh.C.
References SolverUtils::Mesh::Connectivity::Esize(), SolverUtils::GeoPrim::CBox::intersect(), and SolverUtils::Mesh::Connectivity::Node().
     {
       std::vector<Mesh::IndexType>::iterator ci = candidates.begin();
       while(ci != candidates.end()){
         unsigned int cell_id = *ci++;
         unsigned int esize = conn.Esize(cell_id);
         std::vector<GeoPrim::CPoint> element_points(esize);
         // Make a vector of the element points
         for(Mesh::IndexType node = 1;node <= esize;node++){
           GeoPrim::CPoint ep(nc[conn.Node(cell_id,node)]);
           element_points[node-1] = ep;
         }
         // Make the bounding box for the element
         GeoPrim::CBox ebox(element_points);
         // collide the ebox with the box
         GeoPrim::CBox cbox(box.intersect(ebox));
         if(!cbox.empty())
           cells.push_back(cell_id);
       }
       return(0);
     };
int SolverUtils::Mesh::CollideMeshWithBox (Mesh::NodalCoordinates & nc, Mesh::Connectivity & conn, GeoPrim::CBox & box, std::vector< Mesh::IndexType > & cells)
Definition at line 235 of file Mesh.C.
References SolverUtils::GeoPrim::CBox::empty(), SolverUtils::Mesh::Connectivity::Esize(), SolverUtils::GeoPrim::CBox::intersect(), and SolverUtils::Mesh::Connectivity::Node().
     {
       unsigned int nelem = conn.size();
       Mesh::IndexType n = 1;
       while(n <= nelem){
         unsigned int esize = conn.Esize(n);
         std::vector<GeoPrim::CPoint> element_points(esize);
         // Make a vector of the element points
         for(Mesh::IndexType node = 1;node <= esize;node++){
           GeoPrim::CPoint ep(nc[conn.Node(n,node)]);
           element_points[node-1] = ep;
         }
         // Make the bounding box for the element
         GeoPrim::CBox ebox(element_points);
         // collide the ebox with the box
         GeoPrim::CBox cbox = box.intersect(ebox);
         if(!cbox.empty())
           cells.push_back(n);
         n++;
       }
       return(0);
     };
template<typename OuterContType , typename InnerContType , typename RetCont , typename idxtype > void SolverUtils::Mesh::Container2CSR (RetCont & xadj, RetCont & adj, OuterContType & source)
Return the total number of entries in a multicontainer
Definition at line 130 of file Mesh.H.
     {
       Mesh::IndexType number_of_elements = source.size();
       xadj.resize(number_of_elements+1);
       Mesh::IndexType number_entries = IRAD::Util::GetTotalSize<OuterContType>(source);
       adj.reserve(number_entries);
       typename OuterContType::iterator si = source.begin();
       Mesh::IndexType elm = 0;
       xadj[elm++] = 0;
       while(si != source.end()){
         typename InnerContType::iterator ei = si->begin();
         xadj[elm] = static_cast<idxtype>(si->size() + xadj[elm-1]);
         elm++;
         while(ei != si->end())
           adj.push_back(static_cast<idxtype>(*ei++-1));
         si++;
       }
     };
template<typename ListContainerType , typename ListType > void SolverUtils::Mesh::CreateAdjacentNodeList (std::vector< std::list< Mesh::IndexType > > & anodelist, ListContainerType & fc, Mesh::IndexType nnodes = 0)
Definition at line 156 of file Mesh.H.
     {
       if(nnodes == 0)
         nnodes = MaxNodeId<ListContainerType,ListType>(fc);
       anodelist.resize(nnodes);
       typename ListContainerType::iterator lci = fc.begin();
       while(lci != fc.end())
         {
           typename ListType::iterator li = lci->begin();
           while(li != lci->end()){
             Mesh::IndexType this_node = *li++ - 1;
             Mesh::IndexType next_node = 0;
             if(li == lci->end())
               next_node = *(lci->begin());
             else
               next_node = *li++;
             anodelist[this_node].push_back(next_node);
             anodelist[next_node-1].push_back(this_node+1);
           }
           lci++;
         }
       for(Mesh::IndexType node = 0;node < nnodes;node++)
         {
           anodelist[node].sort();
           anodelist[node].unique();
         }
     }
void SolverUtils::Mesh::DisplaceNodalCoordinates (Mesh::NodalCoordinates & nc, std::vector< double > & displacements)
Definition at line 193 of file Mesh.C.
References SolverUtils::Mesh::NodalCoordinates::NNodes(), SolverUtils::Mesh::NodalCoordinates::x(), SolverUtils::Mesh::NodalCoordinates::y(), and SolverUtils::Mesh::NodalCoordinates::z().
Referenced by COM::TestModule::Step().
     {
       unsigned int nnodes = nc.NNodes();
       if(displacements.size() != 3*nnodes){
         std::cerr << "SolverUtils::Mesh::DisplaceNodalCoordinates:Error: size of displacements array not consistent with number of nodes."
                   << std::endl;
         return;
       }
       std::vector<double>::iterator dispit = displacements.begin();
       for(int i = 1;i <= nnodes;i++){
         nc.x(i) += *dispit++;
         nc.y(i) += *dispit++;
         nc.z(i) += *dispit++;
       }
     }
void SolverUtils::Mesh::FindElementsInBox (const GeoPrim::CBox & box, const NodalCoordinates & nc, const Connectivity & dc, std::list< Mesh::IndexType > & elements)
Given a box in a cartesian space, this function will populate a list<Mesh::IndexType> with all the elements that lie within.
Inputs: CBox object (see GeoPrimitives.H) NodalCoordinates object ElementConnectivity object DualConnectivity object list<Mesh::IndexType> stores results
Definition at line 1632 of file Mesh.C.
References SolverUtils::GeoPrim::CBox::contains(), and SolverUtils::Mesh::NodalCoordinates::Size().
Referenced by FindPointInMesh(), and FindPointInMesh_2().
     {
       int nnodes = nc.Size();
       for(int i = 1;i <= nnodes;i++){
         GeoPrim::CPoint p(nc[i]);
         if(box.contains(p)){
           std::vector<Mesh::IndexType>::const_iterator dci = dc[i-1].begin();
           while(dci != dc[i-1].end()){
             elements.push_back(*dci++);
           }
         }
       }
       if(!elements.empty()){
         elements.sort();
         elements.unique();
       }
     }
Mesh::IndexType SolverUtils::Mesh::FindPointInCells (const GeoPrim::CPoint & p, const NodalCoordinates & nc, const Connectivity & ec, const std::vector< Mesh::IndexType > & elements, GeoPrim::CVector & natc)
This function will locate which element in a mesh contains a specified point by constructing a box around the point and solving (by Newton-Raphson) the system for each element that touches the box until the element is found.
Inputs: A point in cartesian, ie (X,Y,Z), coordinates A Nodal Coordinates object for the mesh An Element Connectivity object for the mesh Dual Connectivity object for the mesh CBox specifying the parameters of the box use
Returns: An integer indicating which element in the connectivity object contains the point. A 0 will indicate that the point could not be located.
The natural coordinates of the point in the containing element is returned in natc
Definition at line 1678 of file Mesh.C.
References SolverUtils::Mesh::Connectivity::Esize(), HTOL, SolverUtils::GeoPrim::CVector::init(), LTOL, and NewtonRaphson().
     {
       //    GeoPrim::CBox bounds(box.around(p));
       //    std::list<Mesh::IndexType> elements;
       //    FindElementsInBox(bounds, nc, dc, elements);
       std::vector<Mesh::IndexType>::const_iterator ei = elements.begin();
       while(ei != elements.end()){
         GeoPrim::CVector guess;
         unsigned int esize = ec.Esize(*ei);
         if(esize == 4 || esize == 10)
           guess.init(.25,.25,.25);
         else if (esize == 8 || esize == 20)
           guess.init(.5,.5,.5);
         else
           assert(false);
         natc.init(guess);
         // Solve the non-linear system using newton-raphson with an
         // initial guess as the center of the theoretical element.
         if(!NewtonRaphson(natc,*ei,GenericElement(esize),ec,nc,p)){
           //    double dist = 0.0;
           //    Mesh::Mesh::IndexType closest_node = nc.closest_node(p,&dist);
           //    std::cout << "Mesh::FindPointInMesh: Error: Closest approach: " << dist
           //              << " at node " << closest_node << "." << std::endl
           //              << "Mesh::FindPointInMesh: Element(" << *ei << ") = (";
           //    DumpContents(std::cout,ec[*ei-1],",");
           //    std::cout << ")" << std::endl;
           //    std::cout << "Point: " << p << std::endl
           //              << "Nodes: " << std::endl;
           //    std::vector<Mesh::IndexType>::const_iterator ni = ec[*ei-1].begin();
           //    while(ni != ec[*ei-1].end()){
           //      std::cout << ni - ec[*ei-1].begin() << ": " << GeoPrim::C3Point(nc[*ni]) << std::endl;
           //      ni++;
           //    }
           //    assert(false);
           return(0);
         }
         if(natc[0] >= LTOL && natc[0] <= HTOL &&
            natc[1] >= LTOL && natc[1] <= HTOL &&
            natc[2] >= LTOL && natc[2] <= HTOL){
           if(esize == 4 || esize == 10){
             if((natc[0]+natc[1]+natc[2]) <= HTOL)
               return (*ei);
           }
           else if(esize == 8 || esize == 20)
             return(*ei);
           else{
             std::cerr << "Mesh::FindPointInMesh: Error: Cannot handle"
                       << " this element type. (yet)" << std::endl;
             exit(1);
           }
         }
         ei++;
       }
       return (0);
     }
Mesh::IndexType SolverUtils::Mesh::FindPointInMesh (const GeoPrim::CPoint & p, const NodalCoordinates & nc, const Connectivity & ec, const Connectivity & dc, const GeoPrim::CBox & box, GeoPrim::CVector & natc)
This function will locate which element in a mesh contains a specified point by constructing a box around the point and solving (by Newton-Raphson) the system for each element that touches the box until the element is found.
Inputs: A point in cartesian, ie (X,Y,Z), coordinates A Nodal Coordinates object for the mesh An Element Connectivity object for the mesh Dual Connectivity object for the mesh CBox specifying the parameters of the box use
Returns: An integer indicating which element in the connectivity object contains the point. A 0 will indicate that the point could not be located.
The natural coordinates of the point in the containing element is returned in natc
Definition at line 1763 of file Mesh.C.
References SolverUtils::GeoPrim::CBox::AddPoint(), SolverUtils::GeoPrim::CBox::around(), SolverUtils::Mesh::NodalCoordinates::closest_node(), SolverUtils::Mesh::Connectivity::Esize(), FindElementsInBox(), HTOL, SolverUtils::GeoPrim::CVector::init(), LTOL, and NewtonRaphson().
Referenced by main().
     {
       GeoPrim::CBox bounds(box.around(p));
       std::list<Mesh::IndexType> elements;
       FindElementsInBox(bounds, nc, dc, elements);
       std::list<Mesh::IndexType>::iterator ei = elements.begin();
       while(ei != elements.end()){
         GeoPrim::CVector guess;
         unsigned int esize = ec.Esize(*ei);
         if(esize == 4 || esize == 10)
           guess.init(.25,.25,.25);
         else if (esize == 8 || esize == 20)
           guess.init(.5,.5,.5);
         natc.init(guess);
         // Solve the non-linear system using newton-raphson with an
         // initial guess as the center of the theoretical element.
         if(!NewtonRaphson(natc,*ei,GenericElement(esize),ec,nc,p)){
           double dist = 0.0;
           Mesh::IndexType closest_node = nc.closest_node(p,&dist);
           std::cout << "Mesh::FindPointInMesh: Error: Closest approach: " << dist
                     << " at node " << closest_node << "." << std::endl
                     << "Mesh::FindPointInMesh: Element(" << *ei << ") = (";
           IRAD::Util::DumpContents(std::cout,ec[*ei-1],",");
           std::cout << ")" << std::endl;
           std::vector<Mesh::IndexType>::const_iterator ei2 = dc[closest_node-1].begin();
           GeoPrim::CBox new_bounds;
           while(ei2 != dc[closest_node-1].end()){
             // For every element touching this node
             std::vector<Mesh::IndexType>::const_iterator ni = ec[*ei2-1].begin();
             while(ni != ec[*ei2-1].end())
               new_bounds.AddPoint(nc[*ni++]);
             ei2++;
           }
           std::cout << "Mesh::FindPointInMesh: Bounding box of failed search: "
                     << new_bounds << std::endl;
           return(0);
         }
         if(natc[0] >= LTOL && natc[0] <= HTOL &&
            natc[1] >= LTOL && natc[1] <= HTOL &&
            natc[2] >= LTOL && natc[2] <= HTOL){
           if(esize == 4 || esize == 10){
             if((natc[0]+natc[1]+natc[2]) <= HTOL)
               return (*ei);
           }
           else if(esize == 8 || esize == 20)
             return(*ei);
           else{
             std::cerr << "Mesh::FindPointInMesh: Error: Cannot handle"
                       << " this element type. (yet)" << std::endl;
             exit(1);
           }
         }
         ei++;
       }
       return (0);
     }
Mesh::IndexType SolverUtils::Mesh::FindPointInMesh_2 (const GeoPrim::CPoint & p, const NodalCoordinates & nc, const Connectivity & ec, const Connectivity & dc, const GeoPrim::CBox & box, GeoPrim::CVector & natc)
This function will locate which element in a mesh contains a specified point by constructing a box around the point and solving (by Newton-Raphson) the system for each element that touches the box until the element is found.
Inputs: A point in cartesian, ie (X,Y,Z), coordinates A Nodal Coordinates object for the mesh An Element Connectivity object for the mesh Dual Connectivity object for the mesh CBox specifying the parameters of the box use
Returns: An integer indicating which element in the connectivity object contains the point. A 0 will indicate that the point could not be located.
The natural coordinates of the point in the containing element is returned in natc
Definition at line 1851 of file Mesh.C.
References SolverUtils::GeoPrim::CBox::AddPoint(), SolverUtils::GeoPrim::CBox::around(), SolverUtils::Mesh::NodalCoordinates::closest_node(), SolverUtils::Mesh::Connectivity::Esize(), FindElementsInBox(), HTOL, SolverUtils::GeoPrim::CVector::init(), LTOL, and NewtonRaphson_2().
Referenced by main().
     {
       GeoPrim::CBox bounds(box.around(p));
       std::list<Mesh::IndexType> elements;
       FindElementsInBox(bounds, nc, dc, elements);
       std::list<Mesh::IndexType>::iterator ei = elements.begin();
       while(ei != elements.end()){
         GeoPrim::CVector guess;
         unsigned int esize = ec.Esize(*ei);
         if(esize == 3 || esize == 6)
           guess.init(.25,.25,0);
         else if (esize == 4 || esize == 8)
           guess.init(.5,.5,0);
         natc.init(guess);
         // Solve the non-linear system using newton-raphson with an
         // initial guess as the center of the theoretical element.
         if(!NewtonRaphson_2(natc,*ei,GenericCell_2(esize),ec,nc,p)){
           double dist = 0.0;
           Mesh::IndexType closest_node = nc.closest_node(p,&dist);
           std::cout << "Mesh::FindPointInMesh: Error: Closest approach: " << dist
                     << " at node " << closest_node << "." << std::endl
                     << "Mesh::FindPointInMesh: Element(" << *ei << ") = (";
           IRAD::Util::DumpContents(std::cout,ec[*ei-1],",");
           std::cout << ")" << std::endl;
           std::vector<Mesh::IndexType>::const_iterator ei2 = dc[closest_node-1].begin();
           GeoPrim::CBox new_bounds;
           while(ei2 != dc[closest_node-1].end()){
             // For every element touching this node
             std::vector<Mesh::IndexType>::const_iterator ni = ec[*ei2-1].begin();
             while(ni != ec[*ei2-1].end())
               new_bounds.AddPoint(nc[*ni++]);
             ei2++;
           }
           std::cout << "Mesh::FindPointInMesh: Bounding box of failed search: "
                     << new_bounds << std::endl;
           return(0);
         }
         if(natc[0] >= LTOL && natc[0] <= HTOL &&
            natc[1] >= LTOL && natc[1] <= HTOL)
           {
             if(esize == 3 || esize == 6){
               if(((natc[0]+natc[1]) <= HTOL))
                 return (*ei);
             }
             else if(esize == 4 || esize == 8)
               return(*ei);
             else{
               std::cerr << "Mesh::FindPointInMesh: Error: Cannot handle"
                         << " this element type. (yet)" << std::endl;
               exit(1);
             }
           }
         ei++;
       }
       return (0);
     }
template<typename ContainerType , typename Icont > void SolverUtils::Mesh::FormGraph (const ContainerType & adjlist)
Definition at line 244 of file Mesh.H.
     {
       // empty for now
     };
int SolverUtils::Mesh::GenerateCartesianGrid (Mesh::NodalCoordinates & nc, Mesh::BSExtent< Mesh::IndexType > & gridextent, std::vector< Mesh::IndexType > & gridsizes, GeoPrim::CBox & box)
Definition at line 13 of file BSMesh.C.
References SolverUtils::Mesh::BSExtent< T >::Init(), SolverUtils::Mesh::NodalCoordinates::init(), SolverUtils::GeoPrim::CBox::P1(), SolverUtils::GeoPrim::CBox::P2(), SolverUtils::GeoPrim::CPoint::x(), SolverUtils::GeoPrim::C3Point::x(), SolverUtils::GeoPrim::CPoint::y(), SolverUtils::GeoPrim::C3Point::y(), SolverUtils::GeoPrim::CPoint::z(), and SolverUtils::GeoPrim::C3Point::z().
   {
     if(gridsizes.size() != 3)
       return 1;
     // sizes is ncells
     Mesh::IndexType ncells_x = gridsizes[0];
     Mesh::IndexType ncells_y = gridsizes[1];
     Mesh::IndexType ncells_z = gridsizes[2];
     Mesh::IndexType nnodes_x = ncells_x + 1;
     Mesh::IndexType nnodes_y = ncells_y + 1;
     Mesh::IndexType nnodes_z = ncells_z + 1;
     std::vector<Mesh::IndexType> flatextent(6);
     flatextent[0] = 1;
     flatextent[1] = nnodes_x;
     flatextent[2] = 1;
     flatextent[3] = nnodes_y;
     flatextent[4] = 1;
     flatextent[5] = nnodes_z;
     gridextent.Init(flatextent);
     unsigned int npoints = flatextent[1]*flatextent[3]*flatextent[5];
     nc.init(npoints);
     std::vector<double> xcoords(ncells_x+1);
     std::vector<double> ycoords(ncells_y+1);
     GeoPrim::CPoint p(box.P2() - box.P1());
     double h_x = (ncells_x > 0 ? p.x()/ncells_x : 0);
     double h_y = (ncells_y > 0 ? p.y()/ncells_y : 0);
     double h_z = (ncells_z > 0 ? p.z()/ncells_z : 0);
     for(unsigned int i = 0;i < nnodes_y;i++)
       ycoords[i] = i*h_y + box.P1().y();
     for(unsigned int i = 0;i < nnodes_x;i++)
       xcoords[i] = i*h_x + box.P1().x();
     unsigned int point_id = 1;
     for(unsigned int k = 0;k < nnodes_z;k++){
       double z = k*h_z + box.P1().z();
       for(unsigned int j = 0;j < nnodes_y;j++){
         for(unsigned int i = 0;i < nnodes_x;i++){
           GeoPrim::C3Point gridpoint(nc[point_id++]);
           gridpoint.x() = xcoords[i];
           gridpoint.y() = ycoords[j];
           gridpoint.z() = z;
         }
       }
     }
   }
void SolverUtils::Mesh::GetCoordinateBounds (NodalCoordinates & nc, std::vector< double > & bnds)
Definition at line 277 of file Mesh.C.
References max(), SolverUtils::Mesh::NodalCoordinates::Size(), SolverUtils::Mesh::NodalCoordinates::x(), SolverUtils::Mesh::NodalCoordinates::y(), and SolverUtils::Mesh::NodalCoordinates::z().
Referenced by main(), and SolverUtils::FEM::SolverAgent::ReportMeshToStream().
     {
       bnds.resize(6);
       bnds[0] = bnds[2] = bnds[4] = std::numeric_limits<double>::max();
       bnds[1] = bnds[3] = bnds[5] = -1.0*std::numeric_limits<double>::max();
       Mesh::IndexType number_of_nodes = nc.Size();
       for(Mesh::IndexType nn = 1;nn <= number_of_nodes;nn++){
         if(nc.x(nn) < bnds[0])
           bnds[0] = nc.x(nn);
         if(nc.x(nn) > bnds[1])
           bnds[1] = nc.x(nn);
         if(nc.y(nn) < bnds[2])
           bnds[2] = nc.y(nn);
         if(nc.y(nn) > bnds[3])
           bnds[3] = nc.y(nn);
         if(nc.z(nn) < bnds[4])
           bnds[4] = nc.z(nn);
         if(nc.z(nn) > bnds[5])
           bnds[5] = nc.z(nn);
       }
     };
void SolverUtils::Mesh::GetMeshBoxes (const NodalCoordinates & nc, const Connectivity & ec, GeoPrim::CBox & mesh_box, GeoPrim::CBox & small_box, GeoPrim::CBox & large_box)
This function will determine some bounding boxes for the mesh. Namely, it gets a box for the entire mesh, one for the smallest element and one for the largest.
Definition at line 1590 of file Mesh.C.
References SolverUtils::GeoPrim::CBox::empty(), SolverUtils::Mesh::Connectivity::Esize(), SolverUtils::GeoPrim::CBox::init(), SolverUtils::Mesh::Connectivity::Nelem(), SolverUtils::Mesh::Connectivity::Node(), and SolverUtils::Mesh::NodalCoordinates::size().
Referenced by main().
     {
       mesh_box.init(nc[1],nc.size());
       small_box = mesh_box;
       Mesh::IndexType nelem = ec.Nelem();
       Mesh::IndexType n = 1;
       while(n <= nelem){
         unsigned int esize = ec.Esize(n);
         std::vector<GeoPrim::CPoint> element_points(esize);
         // Make a vector of the element points
         for(Mesh::IndexType node = 1;node <= esize;node++){
           GeoPrim::CPoint ep(nc[ec.Node(n,node)]);
           element_points[node-1] = ep;
         }
         // Make the bounding box for the element
         GeoPrim::CBox box(element_points);
         if(!box.empty()){
           if(box < small_box) small_box = box;
           if(box > large_box) large_box = box;
         }
         n++;
       }
     }
int SolverUtils::Mesh::GetMeshCentroids (Mesh::NodalCoordinates & nc, Mesh::Connectivity & conn, std::vector< double > & centroids)
Definition at line 262 of file Mesh.C.
References SolverUtils::Mesh::GenericElement::Centroid().
Referenced by COM::TestModule::Step().
     {
       unsigned int nelem = conn.size();
       centroids.resize(3*nelem,0.0);
       for(unsigned int i = 0;i < nelem;i++){
         GeoPrim::C3Point p(&(centroids[3*i]));
         Mesh::GenericElement e;
         e.Centroid(conn[i],nc,p);
         //      std::cout << "a" << i+1 << ": " << p << std::endl;
       }
       return(0);
     };
Mesh::IndexType SolverUtils::Mesh::GlobalFindPointInMesh (const GeoPrim::CPoint & p, const NodalCoordinates & nc, const Connectivity & ec, const Connectivity & dc, const GeoPrim::CBox & box, GeoPrim::CVector & natc)
Definition at line 1917 of file Mesh.C.
References SolverUtils::Mesh::Connectivity::Esize(), HTOL, SolverUtils::GeoPrim::CVector::init(), LTOL, SolverUtils::Mesh::Connectivity::Nelem(), and NewtonRaphson().
     {
       GeoPrim::CVector guess;
       int ein = 1;
       int ein_size = ec.Nelem();
       while(ein <= ein_size){
         unsigned int esize = ec.Esize(ein);
         if(esize == 4 || esize == 10)
           guess.init(.25,.25,.25);
         else if (esize == 8 || esize == 20)
           guess.init(.5,.5,.5);
         natc.init(guess);
         // Solve the non-linear system using newton-raphson with an
         // initial guess as the center of the theoretical element.
         if(!NewtonRaphson(natc,ein,GenericElement(esize),ec,nc,p)){
           std::cerr << "GlobalFindPointInMesh: error NewtonRaphson failed."
                     << std::endl;
           return(0);
         }
         if(natc[0] >= LTOL && natc[0] <= HTOL &&
            natc[1] >= LTOL && natc[1] <= HTOL &&
            natc[2] >= LTOL && natc[2] <= HTOL){
           if(esize == 4 || esize == 10){
             if((natc[0]+natc[1]+natc[2]) <= HTOL){
               return (ein);
             }
           }
           else if(esize == 8 || esize == 20)
             return(ein);
           else{
             std::cerr << "GlobalFindPointInMesh: Error: Cannot handle"
                       << " this element type. (yet)" << std::endl;
             exit(1);
           }
         }
         ein++;
       }
       return(0);
     }
void SolverUtils::Mesh::LUBksb (GeoPrim::CVector a[], int indx[], GeoPrim::CVector & b)
Definition at line 2328 of file Mesh.C.
Referenced by NewtonRaphson(), and NewtonRaphson_2().
     {
       int i,ii=0,ip,j;
       double sum;
       for (i=0;i<3;i++) {
         ip=indx[i];
         sum=b[ip];
         b[ip]=b[i];
         if (ii){
           for (j=ii;j<=i-1;j++)
             sum -= a[i][j]*b[j];
         }
         else if (sum)
           ii=i;
         b[i]=sum;
       }
       for (i=2;i>=0;i--) {
         sum=b[i];
         for (j=i+1;j<3;j++)
           sum -= a[i][j]*b[j];
         b[i]=sum/a[i][i];
       }
     }
bool SolverUtils::Mesh::LUDcmp (GeoPrim::CVector a[], int indx[])
Definition at line 2269 of file Mesh.C.
References LUDTINY.
Referenced by NewtonRaphson(), and NewtonRaphson_2().
     {
       int i,j,k;
       int imax = 0;
       double big,dum,sum,temp;
       GeoPrim::CVector vv;
       for (i=0;i<3;i++) {
         big=0.0;
         for (j=0;j<3;j++)
           if ((temp=fabs(a[i][j])) > big) big=temp;
         if (big == 0.0){
           //    std::cerr << "LUDcmp::error: Singular matrix" << std::endl;
           return(false);
         }
         vv[i]=1.0/big;
       }
       for (j=0;j<3;j++) {
         for (i=0;i<j;i++) {
           sum=a[i][j];
           for (k=0;k<i;k++)
             sum -= a[i][k]*a[k][j];
           a[i][j]=sum;
         }
         big=0.0;
         for (i=j;i<3;i++) {
           sum=a[i][j];
           for (k=0;k<j;k++)
             sum -= a[i][k]*a[k][j];
           a[i][j]=sum;
           if ( (dum=vv[i]*fabs(sum)) >= big) {
             big=dum;
             imax=i;
           }
         }
         if (j != imax) {
           for (k=0;k<3;k++) {
             dum=a[imax][k];
             a[imax][k]=a[j][k];
             a[j][k]=dum;
           }
           vv[imax]=vv[j];
         }
         indx[j]=imax;
         if (a[j][j] == 0.0) a[j][j]=LUDTINY;
         if (j != 3) {
           dum=1.0/(a[j][j]);
           for (i=j+1;i<3;i++)
             a[i][j] *= dum;
         }
       }
       return (true);
     }
template<typename OuterCont , typename OutCont , typename InnerCont , typename MapType > void SolverUtils::Mesh::MapElements (OuterCont & src, OutCont & trg, MapType & m)
Definition at line 71 of file Mesh.H.
Referenced by main().
     {
       trg.resize(src.size());
       typename OuterCont::iterator sci = src.begin();
       typename OutCont::iterator oci = trg.begin();
       while(sci != src.end()){
         typename InnerCont::iterator ici = sci->begin();
         while(ici != sci->end())
           oci->push_back(m[*ici++]);
         sci++;
         oci++;
       }
     };
template<typename ListContainerType , typename ListType > Mesh::IndexType SolverUtils::Mesh::MaxNodeId (const ListContainerType & fc)
Definition at line 87 of file Mesh.H.
     {
       Mesh::IndexType maxid = 0;
       typename ListContainerType::const_iterator lci = fc.begin();
       while(lci != fc.end()){
         typename ListType::const_iterator li = lci->begin();
         while(li != lci->end()){
           if(maxid < *li)
             maxid = *li;
           li++;
         }
       }
       return(maxid);
     };
bool SolverUtils::Mesh::NewtonRaphson (GeoPrim::CVector & natc, Mesh::IndexType elnum, const GenericElement & el, const Connectivity & ec, const NodalCoordinates & nc, const GeoPrim::CPoint & point)
Parameters: double natc[] = initial guess at the natural coordinates Mesh::IndexType elnum = index of the mesh element to use const ElementConnectivity &ec = The element connectivity for the mesh const NodalCoordinates &nc = The nodal coordinates for the mesh const CPoint &point = the point at which we wish a solution
Definition at line 2164 of file Mesh.C.
References LUBksb(), LUDcmp(), and SolverUtils::Mesh::GenericElement::shapef_jacobian_at().
Referenced by FindPointInCells(), FindPointInMesh(), and GlobalFindPointInMesh().
     {
       int k,i;
       int ntrial = 100; // Number of iterations before giving up
       double errx,errf;
       int indx[3];
       double errtol = 1e-12;
       GeoPrim::CVector p;
       GeoPrim::CVector fvec;
       GeoPrim::CVector fjac[3];
       for (k=0;k<ntrial;k++) {
         //      std::cout << k << std::endl;
         el.shapef_jacobian_at(point,natc,elnum,ec,nc,fvec,fjac);
         errf=0.0;
         for (i=0;i<3;i++){
           //    if(fvec[i] < errtol)
           //      fvec[i] = 0.0;
           errf += fabs(fvec[i]);
         }
         if (errf <= errtol)
           return (true);
         p = -1.0 * fvec;
         //      std::cout << "Jac: "  << fjac[0] << std::endl
         //              << "Jac: "  << fjac[1] << std::endl
         //              << "Jac: "  << fjac[2] << std::endl
         //              << "fv : "  << fvec    << std::endl
         //              << "nc : "  << natc    << std::endl
         //      << "err: "  << errf    << std::endl;
         if(!LUDcmp(fjac,indx)){
           //    std::cerr << "NewtonRaphson::error: LUDcmp failed." << std::endl;
           //    std::cout << "Jac: " << fjac[0] << std::endl
           //              << "Jac: " << fjac[1] << std::endl
           //              << "Jac: " << fjac[2] << std::endl;
           return(false);
         }
         LUBksb(fjac,indx,p);
         errx=0.0;
         for (i=0;i<3;i++)
           errx += fabs(p[i]);
         natc += p;
         if (errx <= errtol)
           return (true);
       }
       //    std::cerr << "NewtonRaphson::warning: reached maximum iterations" << std::endl;
       return (false);
     }
bool SolverUtils::Mesh::NewtonRaphson_2 (GeoPrim::CVector & natc, Mesh::IndexType elnum, const GenericCell_2 & el, const Connectivity & ec, const NodalCoordinates & nc, const GeoPrim::CPoint & point)
Parameters: double natc[] = initial guess at the natural coordinates IndexType elnum = index of the mesh element to use const ElementConnectivity &ec = The element connectivity for the mesh const NodalCoordinates &nc = The nodal coordinates for the mesh const CPoint &point = the point at which we wish a solution
Definition at line 2227 of file Mesh.C.
References LUBksb(), LUDcmp(), SolverUtils::Mesh::GenericCell_2::shapef_jacobian_at(), and TOL.
Referenced by FindPointInMesh_2().
     {
       int k,i;
       int ntrial = 10; // Number of iterations before giving up
       double errx,errf;
       int indx[3];
       GeoPrim::CVector p;
       GeoPrim::CVector fvec;
       GeoPrim::CVector fjac[3];
       for (k=0;k<ntrial;k++) {
         el.shapef_jacobian_at(point,natc,elnum,ec,nc,fvec,fjac);
         errf=0.0;
         for (i=0;i<3;i++)
           errf += fabs(fvec[i]);
         if (errf <= TOL)
           return (true);
         p = -1.0 * fvec;
         if(!LUDcmp(fjac,indx)){
           //    std::cerr << "NewtonRaphson::error: LUDcmp failed." << std::endl;
           return(false);
         }
         LUBksb(fjac,indx,p);
         errx=0.0;
         for (i=0;i<3;i++)
           errx += fabs(p[i]);
         natc += p;
         if (errx <= TOL)
           return (true);
       }
       //    std::cerr << "NewtonRaphson::warning: reached maximum iterations" << std::endl;
       return (false);
     }
template<typename ConType , typename IConType > Mesh::IndexType SolverUtils::Mesh::NumberOfEdges (ConType & con)
Definition at line 223 of file Mesh.H.
     {
       typename ConType::iterator ci = con.begin();
       Mesh::IndexType node = 0;
       Mesh::IndexType nedges = 0;
       while(ci != con.end())
         {
           Mesh::IndexType tnode = ++node;
           typename IConType::iterator eni = ci->begin();
           while(eni != ci->end())
             {
               Mesh::IndexType anode = *eni++;
               if((tnode) < anode)
                 nedges++;
             }
           ci++;
         }
       return(nedges);
     }
std::ostream& SolverUtils::Mesh::operator<< (std::ostream & oSt, const Mesh::NodalCoordinates & nc)
Definition at line 2412 of file Mesh.C.
References SolverUtils::Mesh::NodalCoordinates::size().
     {
       //  if(nc.size() == 0) return(oSt);
       oSt.setf(std::ios::scientific);
       oSt.setf(std::ios::showpoint);
       oSt << std::setprecision(10) << std::setiosflags(std::ios::left);
       oSt << nc.size();
       if(nc.size() > 0) oSt << "\n";
       for(Mesh::IndexType n = 1;n <= nc.size() ;n++){
         oSt << std::setw(16) << nc[n][0] << "\t"
             << std::setw(16) << nc[n][1] << "\t"
             << std::setw(16) << nc[n][2];
         if(n != nc.size())
           oSt << std::endl;
       }
       return (oSt);
     }
std::ostream& SolverUtils::Mesh::operator<< (std::ostream & oSt, const Mesh::Connectivity & ec)
Definition at line 2430 of file Mesh.C.
     {
       oSt << std::setiosflags(std::ios::left) << ec.size();
       if(ec.size() == 0) return(oSt);
       oSt << "\n";
       Mesh::Connectivity::const_iterator ci = ec.begin();
       while(ci != ec.end()){
         std::vector<Mesh::IndexType>::const_iterator ni = ci->begin();
         while(ni != ci->end()){
           oSt << *ni++;
           if(ni != ci->end())
             oSt << "\t";
         }
         ci++;
         if(ci != ec.end())
           oSt << "\n";
       }
       return(oSt);
     }
std::ostream& SolverUtils::Mesh::operator<< (std::ostream & oSt, const Mesh::GeometricEntity & ge)
Definition at line 2450 of file Mesh.C.
References SolverUtils::Mesh::GeometricEntity::_collections.
     {
       if(ge.first.empty()) return(oSt);
       oSt << std::setiosflags(std::ios::left) << ge.first << "\n";
       oSt << ge._collections;
       return(oSt);
     }
std::istream& SolverUtils::Mesh::operator>> (std::istream & iSt, Mesh::GeometricEntity & ge)
Definition at line 2355 of file Mesh.C.
References SolverUtils::Mesh::GeometricEntity::_collections.
     {
       std::string line;
       while(line.empty())
         std::getline(iSt,line);
       std::istringstream Istr(line);
       Istr >> ge.first;
       iSt >> ge._collections;
       ge.second = ge._collections.size();
       return(iSt);
     }
std::istream& SolverUtils::Mesh::operator>> (std::istream & iSt, Mesh::Connectivity & ec)
Definition at line 2367 of file Mesh.C.
References SolverUtils::Mesh::Connectivity::_nelem, and SolverUtils::Mesh::Connectivity::Resize().
     {
       std::string line;
       while(line.empty())
         std::getline(iSt,line);
       std::istringstream Istr(line);
       Mesh::IndexType nelem = 0;
       Istr >> nelem;
       if(nelem > 0){
         ec.Resize(nelem);
         ec._nelem = nelem;
         for(Mesh::IndexType i = 0;i < nelem;i++){
           std::getline(iSt,line);
           std::istringstream Istr2(line);
           Mesh::IndexType node;
           ec[i].reserve(8);
           while(Istr2 >> node)
             ec[i].push_back(node);
           std::vector<Mesh::IndexType>(ec[i]).swap(ec[i]);
         }
       }
       return(iSt);
     }
std::istream& SolverUtils::Mesh::operator>> (std::istream & iSt, Mesh::NodalCoordinates & nc)
Definition at line 2391 of file Mesh.C.
References SolverUtils::Mesh::NodalCoordinates::init(), and SolverUtils::Mesh::NodalCoordinates::size().
     {
       //  if(nc.size() == 0) return (iSt);
       std::string line;
       Mesh::IndexType nnodes;
       while(line.empty())
         std::getline(iSt,line);
       std::istringstream Istr(line);
       Istr >> nnodes;
       if(nnodes > 0){
         nc.init(nnodes);
         for(Mesh::IndexType n = 1;n <= nc.size();n++){
           double *inPtr = nc[n];
           std::getline(iSt,line);
           std::istringstream Istr2(line);
           Istr2 >> inPtr[0] >> inPtr[1] >> inPtr[2];
         }
       }
       return(iSt);
     }
void SolverUtils::Mesh::printVtk (std::vector< double > & vlist, std::vector< std::vector< int > > & elist)
Note
Mostly used for debugging.
Parameters
vlist the global vertex list.
elist the element list.
Definition at line 76 of file MeshVTK.C.
   {
     std::ofstream ofs;
     ofs.open( std::string( "global_mesh.vtk" ).c_str( ) );
     if( !ofs.is_open( ) )
       {
         std::cerr << "Cannot write global VTK file! " << std::endl;
         std::cerr << "File: " << __FILE__                                               << std::endl;
         std::cerr << "Line: " << __LINE__                                               << std::endl;
         assert( false );
       }
     ofs << "# vtk DataFile Version 3.0\n";
     ofs << "Global Mesh Output" << std::endl;
     ofs << "ASCII\n";
     ofs << "DATASET UNSTRUCTURED_GRID\n";
     ofs << "POINTS " << vlist.size( )/3 << " double\n";
     for( int i=0; i < vlist.size( )/3; ++i )
       {
         ofs << vlist[ i*3   ] << " ";
         ofs << vlist[ i*3+1 ] << " ";
         ofs << vlist[ i*3+2 ] << "\n";
       }
     int maxnodes = 0; /* the maximum number of nodes per element */
     for( int i=0; i < elist.size( ); ++i )
       {
         if( maxnodes < elist[ i ].size( ) )
           maxnodes = elist[ i ].size( );
       }
     ofs << "CELLS " << elist.size( ) << " " << elist.size( )*( maxnodes+1) << "\n";
     for( int i=0; i < elist.size( ); ++i  )
       {
         ofs <<  elist[ i ].size( ) << " ";
         for( int j=0; j < elist[ i ].size( ); ++j )
           ofs <<  elist[ i ][ j ]<< " ";
         ofs << std::endl;
       }
     ofs << "CELL_TYPES " << elist.size( ) << std::endl;
     for( int i=0; i < elist.size( ); ++i )
       {
         if( elist[ i ].size( ) == 8 )
           ofs << "12\n";
         else if( elist[ i ].size( ) == 4 )
           ofs << "10\n";
         else {
           std::cerr << "Undefined element type!\n";
           std::cerr << "File: " << __FILE__ << std::endl;
           std::cerr << "Line: " << __LINE__ << std::endl;
         }
       }
     ofs.close( );
   }
bool SolverUtils::Mesh::QUAD_OK (const GeoPrim::C3Point & p1, const GeoPrim::C3Point & p2, const GeoPrim::C3Point & p3, const GeoPrim::C3Point & p4)
Definition at line 1436 of file Mesh.C.
References SolverUtils::GeoPrim::C3Plane::contains_point(), and TRIANGLE_OK().
Referenced by SolverUtils::Mesh::GenericElement::ShapeOK().
     {
       // Make sure 3 points make a triangle
       if(!TRIANGLE_OK(p1,p2,p3))
         return(false);
       if(!TRIANGLE_OK(p1,p3,p4))
         return(false);
       if(!TRIANGLE_OK(p1,p2,p4))
         return(false);
       if(!TRIANGLE_OK(p2,p3,p4))
         return(false);
       GeoPrim::C3Plane plane1(p1,p2,p3);
       if(!plane1.contains_point(p4))
         return(false);
       return(true);
     }
int SolverUtils::Mesh::ReadMesh (const std::string & path, Mesh::UnstructuredMesh & mesh)
Definition at line 1969 of file Mesh.C.
References SolverUtils::Mesh::UnstructuredMesh::con, and SolverUtils::Mesh::UnstructuredMesh::nc.
     {
       std::ifstream Inf;
       Inf.open(path.c_str());
       if(!Inf)
         return(1);
       Inf >> mesh.nc >> mesh.con;
       if(!Inf)
         return(1);
       Inf.close();
       return(0);
     }
int SolverUtils::Mesh::ReadMeshFromStream (Mesh::UnstructuredMesh & mesh, std::istream & Inf)
Definition at line 1982 of file Mesh.C.
References SolverUtils::Mesh::UnstructuredMesh::con, and SolverUtils::Mesh::UnstructuredMesh::nc.
Referenced by SolverUtils::MeshUtils::meshgen2d().
     {
       Inf >> mesh.nc >> mesh.con;
       return(0);
     }
int SolverUtils::Mesh::ReadWRLFromStream (Mesh::UnstructuredMesh & mesh, std::istream & Istr)
Definition at line 2522 of file Mesh.C.
References SolverUtils::Mesh::Connectivity::AddElement(), CheckCoordinates(), SolverUtils::Mesh::UnstructuredMesh::con, SolverUtils::Mesh::NodalCoordinates::init_copy(), and SolverUtils::Mesh::UnstructuredMesh::nc.
Referenced by main().
     {
       std::string line;
       Mesh::NodalCoordinates &nc = mesh.nc;
       Mesh::Connectivity     &ec = mesh.con;
       std::vector<double> coords;
       std::getline(Istr,line);
       std::string::size_type x = line.find("point [");
       while(x == std::string::npos  && Istr.good()){
         std::getline(Istr,line);
         x = line.find("point [");
       }
       if(!Istr.good()){
         return(-1);
       }
       std::getline(Istr,line);
       x = line.find("]");
       unsigned int count = 1;
       while(x == std::string::npos && Istr.good()){
         std::istringstream Istr2(line);
         double xc, yc, zc;
         Istr2 >> xc >> yc >> zc;
         coords.push_back(xc);
         coords.push_back(yc);
         coords.push_back(zc);
         std::getline(Istr,line);
         x = line.find("]");
       }
       if(!Istr.good()){
         return(-2);
       }
       unsigned int number_of_nodes = coords.size()/3;
       CheckCoordinates(&(coords[0]),number_of_nodes,1.0e-9);
       nc.init_copy(number_of_nodes,&(coords[0]));
       getline(Istr,line);
       x = line.find("coordIndex [");
       while(x == std::string::npos && !Istr.eof()){
         getline(Istr,line);
         x = line.find("coordIndex [");
       }
       if(Istr.eof()){
         return(-3);
       }
       std::getline(Istr,line);
       x = line.find("]");
       while(x == std::string::npos && !Istr.eof()){
         std::istringstream Istr2(line);
         std::string delim;
         int dummy;
         std::vector<Mesh::IndexType> element;
         while(Istr2 >> dummy){
           if(dummy >= 0){
             element.push_back(dummy);
             Istr2 >> delim;
           }
         }
         std::vector<Mesh::IndexType>::iterator ei = element.begin();
         while(ei != element.end())
           (*ei++)++;
         ec.AddElement(element);
         std::getline(Istr,line);
         x = line.find("]");
       }
       if(Istr.eof())
         return(-4);
       return(0);
     };
int SolverUtils::Mesh::Skin (Mesh::UnstructuredMesh & inmesh, Mesh::UnstructuredMesh & outmesh)
Definition at line 490 of file Mesh.C.
References SolverUtils::Mesh::Connectivity::AddElement(), SolverUtils::Mesh::Connectivity::BuildFaceConnectivity(), SolverUtils::Mesh::UnstructuredMesh::con, SolverUtils::Mesh::Connectivity::Element(), SolverUtils::Mesh::Connectivity::Esize(), SolverUtils::Mesh::NodalCoordinates::init_copy(), SolverUtils::Mesh::Connectivity::Inverse(), SolverUtils::Mesh::UnstructuredMesh::nc, SolverUtils::Mesh::Connectivity::Nelem(), SolverUtils::Mesh::Connectivity::ShrinkWrap(), SolverUtils::Mesh::NodalCoordinates::Size(), SolverUtils::Mesh::Connectivity::SyncSizes(), SolverUtils::Mesh::NodalCoordinates::x(), SolverUtils::Mesh::NodalCoordinates::y(), and SolverUtils::Mesh::NodalCoordinates::z().
     {
       Mesh::Connectivity F_N; // for every face, the nodes
       Mesh::Connectivity E_F; // for every element, the faces
       Mesh::Connectivity F_E; // for every face, the elements
       std::vector<Mesh::SymbolicFace> sf; // symbolic faces
       Mesh::Connectivity dc;
       inmesh.con.SyncSizes();
       inmesh.con.Inverse(dc,inmesh.nc.Size());
       inmesh.con.BuildFaceConnectivity(F_N,E_F,sf,dc);
       E_F.ShrinkWrap();
       E_F.SyncSizes();
       E_F.Inverse(F_E,F_N.Nelem());
       F_N.ShrinkWrap();
       F_E.ShrinkWrap();
       std::vector<Mesh::SymbolicFace>(sf).swap(sf);
       F_E.SyncSizes();
       F_N.SyncSizes();
       Mesh::Connectivity &BoundaryConn = outmesh.con;
       Mesh::Connectivity::iterator fei = F_E.begin();
       while(fei != F_E.end()){
         Mesh::IndexType faceid = (fei++ - F_E.begin()) + 1;
         if(F_E.Esize(faceid) == 1)
           BoundaryConn.AddElement(F_N.Element(faceid));
       }
       // Now iterate through the boundary connectivity and
       // identify the unique list of nodes
       std::list<Mesh::IndexType> boundary_nodes;
       fei = BoundaryConn.begin();
       while(fei != BoundaryConn.end()){
         std::vector<Mesh::IndexType>::iterator fii = fei->begin();
         while(fii != fei->end())
           boundary_nodes.push_back(*fii++);
         fei++;
       }
       boundary_nodes.sort();
       boundary_nodes.unique();
       // Create a map to update the face connectivity table
       std::map<Mesh::IndexType,Mesh::IndexType> remap;
       Mesh::IndexType node_id = 1;
       std::list<Mesh::IndexType>::iterator bni = boundary_nodes.begin();
       std::vector<double> boundary_coordinates(boundary_nodes.size()*3,0.0);
       while(bni != boundary_nodes.end()){
         Mesh::IndexType node_index = node_id - 1;
         remap[*bni++] = node_id;
         boundary_coordinates[node_index*3] = inmesh.nc.x(node_id);
         boundary_coordinates[(node_index*3) + 1] = inmesh.nc.y(node_id);
         boundary_coordinates[(node_index*3) + 2] = inmesh.nc.z(node_id);
         node_id++;
       }
       fei = BoundaryConn.begin();
       while(fei != BoundaryConn.end()){
         std::vector<Mesh::IndexType>::iterator fii = fei->begin();
         while(fii != fei->end()){
           *fii = remap[*fii];
           fii++;
         }
         fei++;
       }
       outmesh.nc.init_copy(boundary_nodes.size(),&boundary_coordinates[0]);
       return(0);
     };
bool SolverUtils::Mesh::TRIANGLE_OK (const GeoPrim::C3Point & p1, const GeoPrim::C3Point & p2, const GeoPrim::C3Point & p3)
Definition at line 1429 of file Mesh.C.
References SolverUtils::GeoPrim::C3Line::has_point().
Referenced by QUAD_OK(), and SolverUtils::Mesh::GenericElement::ShapeOK().
     {
       GeoPrim::C3Line line(p1,p2);
       if(line.has_point(p3))
         return(false);
       return(true);
     }
void SolverUtils::Mesh::writeVtkData ()
Precondition
Program.globalNodeList.size() > 0.
Program.globalElementList.size() > 0.
Program.smdv.size() > 0.
Program.globalSolution.size() == Program.smdv.size().
Program.solutionignore.size() == Program.smdv.size().
Program.outputfile != ""
Postcondition
A VTK formatted file is written in Program.outputfile.vtk
Note
The extension in the outputfile will be appended.
Definition at line 652 of file hdf2pltV2.C.
References CELLDATA, and NODEDATA.
Referenced by printWindow().
 {
         std::cout << "Writing VTK data...";
         std::cout.flush( );
         #ifdef ASSERT_ON
                 assert( Program.globalNodeList.size( ) >  0     );
                 assert( Program.globalElementList.size( ) > 0 );
                 assert( Program.smdv.size( ) > 0 );
                 assert( Program.globalSolution.size( ) == Program.smdv.size( ) );
                 assert( Program.solutionignore.size( ) == Program.smdv.size( ) );
                 assert( Program.outputfile != "" );
         #endif
         std::ofstream ofs;
         ofs.open( std::string(Program.outputfile + ".vtk").c_str( ) );
         if( !ofs.is_open( ) )
         {
                 std::cerr << "Cannot write VTK file: " << Program.outputfile+".vtk" << std::endl;
                 std::cerr << "File: " << __FILE__                << std::endl;
                 std::cerr << "Line: " << __LINE__                << std::endl;
                 assert( false );
         }
         /* STEP 1: Write the header */
         ofs << "# vtk DataFile Version 3.0\n";
         ofs << "Global Mesh Output" << std::endl;
         ofs << "ASCII\n";
         ofs << "DATASET UNSTRUCTURED_GRID\n";
         ofs << "POINTS " << Program.globalNodeList.size( )/3 << " double\n";
         /* STEP 2: Write the nodes */
         for( int i=0; i < Program.globalNodeList.size( )/3; ++i )
         {
                 ofs << Program.globalNodeList[ i*3       ] << " ";
                 ofs << Program.globalNodeList[ i*3+1 ] << " ";
                 ofs << Program.globalNodeList[ i*3+2 ] << std::endl;
         }
         /* STEP 3: Write the max element size */
         int maxnodes = 0; /* the maximum number of nodes per element */
         for( int i=0; i < Program.globalElementList.size( ); ++i )
         {
                 if( maxnodes < Program.globalElementList[ i ].size( ) )
                         maxnodes = Program.globalElementList[ i ].size( );
         }
         /* STEP 4: Write the element connectivity */
         ofs << "CELLS " << Program.globalElementList.size( ) << " " << Program.globalElementList.size( )*( maxnodes+1) << "\n";
         for( int i=0; i < Program.globalElementList.size( ); ++i  )
         {
                 ofs <<  Program.globalElementList[ i ].size( ) << " ";
                 for( int j=0; j < Program.globalElementList[ i ].size( ); ++j )
                         ofs <<  Program.globalElementList[ i ][ j ]<< " ";
                 ofs << std::endl;
         }
         /* STEP 5: Write the cell types */
         ofs << "CELL_TYPES " << Program.globalElementList.size( ) << std::endl;
         for( int i=0; i < Program.globalElementList.size( ); ++i )
         {
                 if( Program.globalElementList[ i ].size( ) == 8 )
                         ofs << "12\n";
                 else if( Program.globalElementList[ i ].size( ) == 4 )
                         ofs << "10\n";
                 else {
                         std::cerr << "Undefined element type!\n";
                         std::cerr << "File: " << __FILE__ << std::endl;
                         std::cerr << "Line: " << __LINE__ << std::endl;
                 }
         }
         /* STEP 6: Write the solution data attached to the points */
         bool wroteHeader = false;
         for( int i=0; i < Program.globalSolution.size( ); ++i )
         {
                 if( ! Program.solutionignore[ i ] && Program.getDataItemType( i ) == NODEDATA  )
                 {
                         int N = Program.globalNodeList.size( )/3;
                         int NC      = Program.smdv[ i ].ncomp;
                         if(!wroteHeader)
{
                                 ofs << "POINT_DATA " << N << std::endl;
                                 wroteHeader = true;
                         }
                         if( NC == 1 )
{
                                         ofs << "SCALARS " << Program.smdv[ i ].name << " double" << std::endl;
                                         ofs << "LOOKUP_TABLE default\n";
                         }
                         else if( NC == 3 )
{
                                 ofs << "VECTORS " << Program.smdv[ i ].name << " double" << std::endl;
                         }
                         else
{
                                 ofs << "TENSORS " << Program.smdv[ i ].name << " double" << std::endl;
                         }
                         for( int j=0; j < N; ++j )
{
                                 for( int component=0; component < NC; ++component )
{
                                         ofs << Program.globalSolution[ i ][ j*NC+component ] << " ";
                                 }
                                 ofs << std::endl;
                         }
                 } /* End if the solution is not ignored */
         } /* End for all solution data */
         /* STEP 6: Write the solution data attached to the cells */
         wroteHeader = false;
         for( int i=0; i < Program.globalSolution.size( ); ++i )
         {
                 if( ! Program.solutionignore[ i ] && Program.getDataItemType( i ) == CELLDATA )
                 {
                         int N                   = Program.globalElementList.size();
                         int NC      = Program.smdv[ i ].ncomp;
                         if( !wroteHeader )
{
                                 ofs << "CELL_DATA " << N << std::endl;
                                 wroteHeader = true;
                         }
                         if( NC == 1 )
{
                                         ofs << "SCALARS " << Program.smdv[ i ].name << " double" << std::endl;
                                         ofs << "LOOKUP_TABLE default\n";
                         }
                         else if( NC == 3 )
{
                                 ofs << "VECTORS " << Program.smdv[ i ].name << " double" << std::endl;
                         }
                         else
{
                                 ofs << "TENSORS " << Program.smdv[ i ].name << " double" << std::endl;
                         }
                         for( int j=0; j < N; ++j )
{
                                 for( int component=0; component < NC; ++component )
{
                                         ofs << Program.globalSolution[ i ][ j*NC+component ] << " ";
                                 }
                                 ofs << std::endl;
                         }
                 } /* End if the solution is not ignored */
         } /* End for all solution data */
         ofs.close( );
         std::cout << "[DONE]\n";
 }
void SolverUtils::Mesh::writeVtkData (NodalCoordinates & nc, Connectivity & con, const std::string & filename, std::vector< double > & soln)
Precondition
Program.globalNodeList.size() > 0.
Program.globalElementList.size() > 0.
Program.smdv.size() > 0.
Program.globalSolution.size() == Program.smdv.size().
Program.solutionignore.size() == Program.smdv.size().
Program.outputfile != ""
Postcondition
A VTK formatted file is written in Program.outputfile.vtk
Note
The extension in the outputfile will be appended.
Definition at line 146 of file MeshVTK.C.
References SolverUtils::Mesh::Connectivity::Esize(), SolverUtils::Mesh::NodalCoordinates::NNodes(), SolverUtils::Mesh::GenericElement::ShapeOK(), and SolverUtils::Mesh::Connectivity::SyncSizes().
   {
     std::cout << "Writing VTK data...";
     std::cout.flush( );
     std::ofstream ofs;
     ofs.open( filename.c_str());
     if( !ofs.is_open( ) )
       {
         std::cerr << "Cannot write VTK file: " << filename << std::endl;
         std::cerr << "File: " << __FILE__                << std::endl;
         std::cerr << "Line: " << __LINE__                << std::endl;
         assert( false );
       }
     unsigned int nnodes = nc.NNodes();
     /* STEP 1: Write the header */
     ofs << "# vtk DataFile Version 3.0\n";
     ofs << "Global Mesh Output" << std::endl;
     ofs << "ASCII\n";
     ofs << "DATASET UNSTRUCTURED_GRID\n";
     ofs << "POINTS " << nnodes << " double\n";
     /* STEP 2: Write the nodes */
     for( int i=1; i < nnodes; ++i )
       {
         ofs << GeoPrim::C3Point(nc[i]) << std::endl;
       }
     /* STEP 3: Write the max element size */
     int maxnodes = 0; /* the maximum number of nodes per element */
     unsigned int nelem = con.size();
     con.SyncSizes();
     for( int i=0; i < nelem; ++i )
       {
         unsigned int esize = con[i].size();
         if(maxnodes < esize)
           maxnodes = esize;
       }
     /* STEP 4: Write the element connectivity */
     ofs << "CELLS " << nelem << " " << nelem*( maxnodes+1) << "\n";
     for( int i=0; i < nelem; ++i  )
       {
         ofs <<  con.Esize(i) << " ";
         for( int j=0; j < con.Esize(i); ++j )
           ofs <<  con[ i ][ j ]-1 << " ";
         ofs << std::endl;
       }
     /* STEP 5: Write the cell types */
     ofs << "CELL_TYPES " << nelem << std::endl;
     Mesh::GenericElement ge(4);
     for( int i=0; i < nelem; ++i )
       {
         unsigned int esize = con.Esize(i);
         if ( esize == 3){
           ofs << "5\n";
         }
         else if( esize == 4 ){
           if(ge.ShapeOK(con[i],nc))
             ofs << "10\n";
           else
             ofs << "9\n";
         }
         else if( esize == 5) {
           ofs << "14\n";
         }
         else if( esize == 6){
           ofs << "13\n";
         }
         else if( esize == 8 )
           ofs << "12\n";
         else {
           std::cerr << "Undefined element type!\n";
           std::cerr << "File: " << __FILE__ << std::endl;
           std::cerr << "Line: " << __LINE__ << std::endl;
         }
       }
     /* STEP 6: Write the solution data attached to the points */
      bool wroteHeader = false;
      std::vector<std::string> Name(5);
      Name[0] = "rho";
      Name[1] = "rho-u";
      Name[2] = "rho-v";
      Name[3] = "rho-w";
      Name[4] = "rho-E";
      if(!soln.empty()){
        for( int i=0; i < 5; ++i )
          {
            if( !wroteHeader )
              {
                ofs << "CELL_DATA " << nelem << std::endl;
                wroteHeader = true;
              }
            ofs << "SCALARS " << Name[i] << " double" << std::endl;
            ofs << "LOOKUP_TABLE default\n";
            for( int j=0; j < nelem; ++j )
              {
                ofs << soln[ i*nelem + j ] << " ";
              }
            ofs << std::endl;
          }
      }
      ofs.close( );
      std::cout << "[DONE]\n";
   }
void SolverUtils::Mesh::writeVtkFiles (const std::string & outputfile, const std::vector< int > & paneIds, std::vector< Mesh::UnstructuredMesh > & meshes, std::vector< std::vector< int > > & masks)
Definition at line 9 of file MeshVTK.C.
   {
     // TODO: Generalize this function for any type of mesh.
     for( int m=0; m < meshes.size( ); ++m )
       {
         std::ostringstream oss; oss.clear( );
         oss << outputfile << "." << paneIds[ m ] << ".vtk";
         std::ofstream ofs;
         ofs.open( oss.str( ).c_str( ) );
         if( !ofs.is_open( ) )
           {
             std::cerr << "Cannot write VTK file: " << oss.str( ) << std::endl;
             std::cerr << "File: " << __FILE__ << std::endl;
             std::cerr << "Line: " << __LINE__ << std::endl;
             assert( false );
           }
         ofs << "# vtk DataFile Version 3.0\n";
         ofs << oss.str( ) << std::endl;
         ofs << "ASCII\n";
         ofs << "DATASET UNSTRUCTURED_GRID\n";
         ofs << "POINTS " << meshes[ m ].nc.Size( ) << " double\n";
         for( int i=1; i <= meshes[ m ].nc.Size( ); ++i )
           {
             ofs << meshes[ m ].nc.x( i ) << " ";
             ofs << meshes[ m ].nc.y( i ) << " ";
             ofs << meshes[ m ].nc.z( i ) << "\n";
           }
         ofs << "CELLS " << meshes[ m ].con.Nelem( ) << " " << meshes[ m ].con.Nelem( )*9 << "\n";
         for( int e=1; e <= meshes[ m ].con.Nelem( ); ++e )
           {
             ofs <<  "8 ";
             for( int j=1; j <= 8; ++j )
               ofs << meshes[ m ].con.Node( e, j )-1<< " ";
             ofs << std::endl;
           }
         ofs << "CELL_TYPES " << meshes[ m ].con.Nelem( ) << std::endl;
         for( int e=1; e <= meshes[ m ].con.Nelem( ); ++ e )
           ofs << "12\n";
         ofs << "POINT_DATA " << masks[ m ].size( ) << std::endl;
         ofs << "SCALARS SharedNodes double\nLOOKUP_TABLE default\n";
         for( int i=0; i < masks[ m ].size( ); ++i )
           {
             if( masks[ m ][ i ] )
               ofs << "1\n";
             else
               ofs << "0\n";
           }
         ofs.close( );
       }
   }
void SolverUtils::Mesh::writeVtkFiles (std::vector< Mesh::UnstructuredMesh > & m)
The format of the files is {outputFile}.paneId.vtk.
Note
This method is mainly used for debugging.
Parameters
m the set of meshes.
int SolverUtils::Mesh::WriteVTKToStream (Mesh::UnstructuredMesh & mesh, std::ostream & Ostr)
Referenced by SolverUtils::MeshUtils::meshgen2d(), COM::TransferSolver::Setup(), and SolverUtils::WriteVTKToStream().
int SolverUtils::Mesh::WriteVTKToStream (const std::string & name, Mesh::UnstructuredMesh & mesh, std::ostream & Ostr)
Definition at line 2459 of file Mesh.C.
References SolverUtils::Mesh::UnstructuredMesh::con, SolverUtils::Mesh::Connectivity::Esize(), SolverUtils::Mesh::UnstructuredMesh::nc, SolverUtils::Mesh::Connectivity::Nelem(), SolverUtils::Mesh::NodalCoordinates::NNodes(), SolverUtils::Mesh::GenericElement::ShapeOK(), and SolverUtils::Mesh::Connectivity::SyncSizes().
     {
       Mesh::NodalCoordinates &nc = mesh.nc;
       Mesh::Connectivity    &con = mesh.con;
       Mesh::IndexType nnodes = nc.NNodes();
       Mesh::IndexType totalsize = 0;
       Mesh::IndexType nelem = con.Nelem();
       Mesh::IndexType i = 1;
       con.SyncSizes();
       while(i <= nelem)
         totalsize += con.Esize(i++);
       Ostr << "# vtk DataFile Version 2.0"     << std::endl
            << name                             << std::endl
            << "ASCII"                          << std::endl
            << "DATASET UNSTRUCTURED_GRID"      << std::endl
            << "POINTS " << nnodes << " double" << std::endl;
       i = 1;
       while(i <= nnodes)
         Ostr << GeoPrim::C3Point(nc[i++]) << std::endl;
       Ostr << "CELLS " << nelem << " " << nelem + totalsize << std::endl;
       i = 1;
       while(i <= nelem){
         Ostr << con.Esize(i) << " ";
         std::vector<Mesh::IndexType>::iterator ni = con[i-1].begin();
         while(ni != con[i-1].end())
           Ostr << *ni++ - 1 << " ";
         Ostr << std::endl;
         i++;
       }
       Ostr << "CELL_TYPES " << nelem << std::endl;
       Mesh::GenericElement ge(4);
       i = 1;
       while(i <= nelem){
         unsigned int esize = con.Esize(i);
         Ostr << ((esize == 2) ? "3" :
                  (esize == 3) ? "5" :
                  (esize == 4) ? (ge.ShapeOK(con[i-1],nc) ? "10" : "9") :
                  (esize == 5) ? "14" :
                  (esize == 6) ? "13" :
                  (esize == 8) ? "12" : "-1") << std::endl;
         i++;
       }
       return(0);
     };
Variable Documentation
const double SolverUtils::Mesh::HTOL = 1.0 + TOL
Definition at line 58 of file Mesh.H.
Referenced by FindPointInCells(), FindPointInMesh(), FindPointInMesh_2(), and GlobalFindPointInMesh().
const double SolverUtils::Mesh::LTOL = 0.0 - TOL
Definition at line 57 of file Mesh.H.
Referenced by FindPointInCells(), FindPointInMesh(), FindPointInMesh_2(), and GlobalFindPointInMesh().
const double SolverUtils::Mesh::TOL = GeoPrim::TOL
Definition at line 56 of file Mesh.H.
Referenced by NewtonRaphson_2().