IMPACT: IRAD::Sys Namespace Reference
IRAD::Sys Namespace Reference
Unix system utilities.
Namespaces
Net
TCP/IP Network Utilities.
Classes
class ObjectFactory
class DynamicObjectLib
class fdoutbuf
class fdostream
class fdinbuf
class fdistream
class InProcess
class FDSetMan
class Directory
class Environment
Typedefs
typedef void * dlHandleType
Functions
std::string LogTime ()
void TokenizePath (std::vector< std::string > rv, const std::string &path)
std::string TempFileName (const std::string &stub)
int OpenTemp (std::string &stub)
const std::string Hostname (bool longname=false)
const std::string StripDirs (const std::string &)
const std::string CWD ()
int SymLink (const std::string &source, const std::string &target)
void SafeRemove (const std::string &fname, const std::string &ext)
int ChDir (const std::string &path)
bool FILEEXISTS (const std::string &fname)
bool ISDIR (const std::string &fname)
bool ISLINK (const std::string &fname)
int CreateDirectory (const std::string &fname)
const std::string ResolveLink (const std::string &path)
int Remove (const std::string &fname)
int Rename (const std::string &source_file, const std::string &target_file)
std::ostream & operator<< (std::ostream &output, const Environment &env)
Typedef Documentation
typedef void* IRAD::Sys::dlHandleType
Definition at line 16 of file DLTools.H.
Function Documentation
int IRAD::Sys::ChDir (const std::string & path)
Definition at line 187 of file UnixUtils.C.
Referenced by IMPACT::MakeProject().
     {
       return(chdir(path.c_str()));
     }
int IRAD::Sys::CreateDirectory (const std::string & fname)
Definition at line 107 of file UnixUtils.C.
Referenced by IMPACT::MakeProject().
     {
       return(mkdir(fname.c_str(),S_IRGRP | S_IXGRP  | S_IRWXU));
     }
const std::string IRAD::Sys::CWD (void)
Definition at line 181 of file UnixUtils.C.
Referenced by Rocin::read_windows().
     {
       char buf[1024];
       return(std::string(getcwd(buf,1024)));
     }
bool IRAD::Sys::FILEEXISTS (const std::string & fname)
Definition at line 79 of file UnixUtils.C.
Referenced by IMPACT::MakeProject(), IRAD::RunTest(), and SafeRemove().
     {
       struct stat fstat;
       if(lstat(fname.c_str(),&fstat))
         return false;
       return true;
     }
const std::string IRAD::Sys::Hostname (bool longname = false)
Definition at line 25 of file UnixUtils.C.
Referenced by IRAD::RunTest().
     {
       char buf[64];
       gethostname(buf,64);
       return(std::string(buf));
     }
bool IRAD::Sys::ISDIR (const std::string & fname)
Definition at line 87 of file UnixUtils.C.
Referenced by Remove().
     {
       struct stat fstat;
       if(stat(fname.c_str(),&fstat))
         return false;
       if(S_ISDIR(fstat.st_mode))
         return true;
       return false;
     }
bool IRAD::Sys::ISLINK (const std::string & fname)
Definition at line 97 of file UnixUtils.C.
Referenced by SafeRemove().
     {
       struct stat fstat;
       if(lstat(fname.c_str(),&fstat))
         return false;
       if(S_ISLNK(fstat.st_mode))
         return true;
       return(false);
     }
std::string IRAD::Sys::LogTime ()
Definition at line 50 of file UnixUtils.C.
Referenced by IRAD::Global::GlobalObj< StackType, ErrorType, ProfilerType >::LogOut().
     {
       time_t t_ptr;
       time(&t_ptr);
       char timesbuf[64];
       std::string format("[%m/%d/%y%%%X]: ");
       strftime(timesbuf,64,format.c_str(),gmtime(&t_ptr));
       std::string retval(timesbuf);
       return(retval);
     }
int IRAD::Sys::OpenTemp (std::string & stub)
Definition at line 223 of file UnixUtils.C.
     {
       int fd;
       std::string tstub(stub);
       tstub += "XXXXXX";
       char *name = new char [tstub.length() + 1];
       std::strcpy(name,tstub.c_str());
       name[tstub.length()] = '\0';
       fd = mkstemp(name);
       stub = name;
       delete [] name;
       return(fd);
     }
std::ostream& IRAD::Sys::operator<< (std::ostream & output, const Environment & env)
Definition at line 344 of file UnixUtils.C.
     {
       std::vector< std::pair<std::string,std::string> >::const_iterator ei = env.begin();
       while(ei != env.end()){
         output << (*ei).first << " = " << (*ei).second << std::endl;
         ei++;
       }
       return(output);
     }
int IRAD::Sys::Remove (const std::string & fname)
Definition at line 31 of file UnixUtils.C.
References ISDIR().
Referenced by IMPACT::MakeProject(), IRAD::RunTest(), and TempFileName().
     {
       std::cout << fname << std::endl;
       if(ISDIR(fname)){
         Directory RemoveDir(fname);
         if(RemoveDir.size() != 0){
           for(std::vector<std::string>::iterator it = RemoveDir.begin() ; it != RemoveDir.end(); ++it){
             if(Remove(fname + "/" + *it) < 0)
               return -1;
           }
         }
         std::cout << "removing directory" << std::endl;
         return(rmdir(fname.c_str()));
       }
       else{
         std::cout << "removing file" << std::endl;
         return(unlink(fname.c_str()));
       }
     }
int IRAD::Sys::Rename (const std::string & source_file, const std::string & target_file)
Definition at line 16 of file UnixUtils.C.
Referenced by IMPACT::MakeProject().
     {
       return(rename(source_file.c_str(),target_file.c_str()));
     }
const std::string IRAD::Sys::ResolveLink (const std::string & path)
Definition at line 112 of file UnixUtils.C.
References s.
     {
       std::string retVal;
       char buf[1024];
       size_t s = readlink(path.c_str(),buf,1024);
       if(!(s <= 0)){
         buf[s] = '\0';
         retVal.assign(buf);
       }
       std::string::size_type x = retVal.find_last_of("/");
       if(x != std::string::npos)
         retVal.erase(x);
       return (retVal);
     }
void IRAD::Sys::SafeRemove (const std::string & fname, const std::string & ext)
Definition at line 60 of file UnixUtils.C.
References FILEEXISTS(), ISLINK(), and SolverUtils::Ostr.
     {
       if(!FILEEXISTS(fname))
         return;
       if(ISLINK(fname)){
         unlink(fname.c_str());
         return;
       }
       std::string savename_base(fname+"."+ext);
       std::string savename(savename_base);
       unsigned int n = 1;
       while(FILEEXISTS(savename)){
         std::ostringstream Ostr;
         Ostr << savename_base << n++;
         savename.assign(Ostr.str());
       }
       rename(fname.c_str(),savename.c_str());
     }
const std::string IRAD::Sys::StripDirs (const std::string & pname)
Definition at line 193 of file UnixUtils.C.
     {
       std::string retval;
       std::string::size_type x = pname.find("/");
       if(x == std::string::npos)
         return(pname);
       return(pname.substr(pname.find_last_of("/")+1));
     }
int IRAD::Sys::SymLink (const std::string & source, const std::string & target)
Definition at line 20 of file UnixUtils.C.
Referenced by IRAD::RunTest().
     {
       return(symlink(source.c_str(),target.c_str()));
     }
std::string IRAD::Sys::TempFileName (const std::string & stub)
Definition at line 203 of file UnixUtils.C.
References Remove().
Referenced by IRAD::RunTest().
     {
       int fd;
       std::string tstub(stub);
       tstub += "XXXXXX";
       char *name = new char [tstub.length() + 1];
       std::strcpy(name,tstub.c_str());
       name[tstub.length()] = '\0';
       fd = mkstemp(name);
       tstub.assign(name);
       //      if(!fd)
       //        stub = name;
       delete [] name;
       close(fd);
       // Get rid of the file - we just
       // want the name at this point.
       IRAD::Sys::Remove(tstub);
       return (tstub);
     }
void IRAD::Sys::TokenizePath (std::vector< std::string > rv, const std::string & path)
Definition at line 240 of file UnixUtils.C.
     {
       rv.resize(0);
       std::istringstream Istr(path);
       std::string tok;
       while(std::getline(Istr,tok,'/'))
         if(!tok.empty())
           rv.push_back(tok);
     }