IMPACT: IRAD::Profiler Namespace Reference
IRAD::Profiler Namespace Reference
IllinoisRocstar Application Development
Performance profiling.
Classes
struct cumulative_stats
Utility struct.
struct parallel_stats
Utility struct.
struct scalability_stats
Utility struct.
class Event
Marks construct entry/exit.
class DummyProfilerObj
noop profiler
class ProfilerObj
Performance profiling object.
class ProfaneComLine
ComLineObject for profane.
Typedefs
typedef std::map< std::string,
unsigned int > FunctionMap
construct name to unique id.
typedef std::map< unsigned int,
std::string > ConfigMap
construct name to unique id.
typedef std::map< unsigned int,
cumulative_stats > StatMap
typedef std::list< std::pair
< unsigned int, StatMap > > PStatList
typedef std::map< unsigned int,
parallel_stats > PStatMap
typedef std::map< unsigned int,
PStatMap > ScalaMap
typedef std::list< std::pair
< unsigned int, std::list
< Event > > > PEventList
typedef std::map< unsigned int,
scalability_stats > ScalaStatMap
Enumerations
enum {
IMIN_T =0, IMAX_T, IMEAN_T, IMIN_E,
IMAX_E, IMEAN_E, IMIN_S, IMAX_S,
IMEAN_S, EMIN_T, EMAX_T, EMEAN_T,
EMIN_E, EMAX_E, EMEAN_E, EMIN_S,
EMAX_S, EMEAN_S
}
Functions
std::ostream & operator<< (std::ostream &ost, const Event &e)
EVENT's stream operator.
std::istream & operator>> (std::istream &ist, Event &e)
EVENT's stream operator.
double Time ()
Simple timer.
int Profane (int argc, char *argv[])
The performance analysis post processor.
struct timeval operator- (const struct timeval &t1, const struct timeval &t2)
faster timeval math
struct timeval & operator-= (struct timeval &t1, const struct timeval &t2)
faster timeval math
struct timeval operator+ (const struct timeval &t1, const struct timeval &t2)
faster timeval math
struct timeval & operator+= (struct timeval &t1, const struct timeval &t2)
faster timeval math
bool operator== (const struct timeval &t1, const struct timeval &t2)
faster timeval math
bool operator!= (const struct timeval &t1, const struct timeval &t2)
faster timeval math
bool operator< (const timeval &t1, const timeval &t2)
faster timeval math
bool operator> (const struct timeval &t1, const struct timeval &t2)
faster timeval math
bool operator<= (const struct timeval &t1, const struct timeval &t2)
faster timeval math
bool operator>= (const struct timeval &t1, const struct timeval &t2)
faster timeval math
bool operator< (const std::pair< unsigned int, std::list< Event > > &p1, const std::pair< unsigned int, std::list< Event > > &p2)
Event math.
Typedef Documentation
typedef std::map<unsigned int,std::string> IRAD::Profiler::ConfigMap
Definition at line 275 of file Profiler.H.
typedef std::map< std::string, unsigned int > IRAD::Profiler::FunctionMap
Definition at line 271 of file Profiler.H.
typedef std::list< std::pair< unsigned int, std::list< Event > > > IRAD::Profiler::PEventList
Definition at line 280 of file Profiler.H.
typedef std::list< std::pair< unsigned int, StatMap > > IRAD::Profiler::PStatList
Definition at line 277 of file Profiler.H.
typedef std::map< unsigned int, parallel_stats > IRAD::Profiler::PStatMap
Definition at line 278 of file Profiler.H.
typedef std::map< unsigned int, PStatMap > IRAD::Profiler::ScalaMap
Definition at line 279 of file Profiler.H.
typedef std::map< unsigned int, scalability_stats > IRAD::Profiler::ScalaStatMap
Definition at line 282 of file Profiler.H.
typedef std::map< unsigned int, cumulative_stats > IRAD::Profiler::StatMap
Definition at line 276 of file Profiler.H.
Enumeration Type Documentation
anonymous enum
Enumerator
IMIN_T
IMAX_T
IMEAN_T
IMIN_E
IMAX_E
IMEAN_E
IMIN_S
IMAX_S
IMEAN_S
EMIN_T
EMAX_T
EMEAN_T
EMIN_E
EMAX_E
EMEAN_E
EMIN_S
EMAX_S
EMEAN_S
Definition at line 892 of file Profiler.C.
          {IMIN_T=0,IMAX_T,IMEAN_T,IMIN_E,IMAX_E,IMEAN_E,
           IMIN_S,IMAX_S,IMEAN_S,EMIN_T,EMAX_T,EMEAN_T,
           EMIN_E,EMAX_E,EMEAN_E,EMIN_S,EMAX_S,EMEAN_S};
Function Documentation
bool IRAD::Profiler::operator!= (const struct timeval & t1, const struct timeval & t2) inline
Definition at line 75 of file Profiler.C.
     {
       return(!(t1==t2));
     }
struct timeval IRAD::Profiler::operator+ (const struct timeval & t1, const struct timeval & t2)
Definition at line 42 of file Profiler.C.
     {
       struct timeval rtv;
       rtv.tv_usec = t1.tv_usec + t2.tv_usec;
       rtv.tv_sec = t1.tv_sec + t2.tv_sec;
       return(rtv);
     }
struct timeval& IRAD::Profiler::operator+= (struct timeval & t1, const struct timeval & t2)
Definition at line 54 of file Profiler.C.
     {
       t1.tv_usec += t2.tv_usec;
       t1.tv_sec  += t2.tv_sec;
       return(t1);
     }
struct timeval IRAD::Profiler::operator- (const struct timeval & t1, const struct timeval & t2)
Definition at line 19 of file Profiler.C.
     {
       struct timeval rtv;
       rtv.tv_usec = t1.tv_usec - t2.tv_usec;
       rtv.tv_sec  = t1.tv_sec - t2.tv_sec;
       return(rtv);
     }
struct timeval& IRAD::Profiler::operator-= (struct timeval & t1, const struct timeval & t2)
Definition at line 31 of file Profiler.C.
     {
       t1.tv_usec -= t2.tv_usec;
       t1.tv_sec -= t2.tv_sec;
       return(t1);
     }
bool IRAD::Profiler::operator< (const timeval & t1, const timeval & t2) inline
Definition at line 84 of file Profiler.C.
     {
       return((t1.tv_sec + (t1.tv_usec/1000000.0)) <
              (t2.tv_sec + (t2.tv_usec/1000000.0)));
     }
bool IRAD::Profiler::operator< (const std::pair< unsigned int, std::list< Event > > & p1, const std::pair< unsigned int, std::list< Event > > & p2)
Definition at line 123 of file Profiler.C.
     {
       return (p1.first < p2.first);
     };
std::ostream & IRAD::Profiler::operator<< (std::ostream & ost, const Event & e)
Output function for Event.
Definition at line 131 of file Profiler.C.
References IRAD::Profiler::Event::_exclusive, IRAD::Profiler::Event::_id, IRAD::Profiler::Event::_inclusive, and IRAD::Profiler::Event::_timestamp.
     {
       ost << e._id << " " << e._timestamp << " "
           << e._inclusive << " " << e._exclusive;
       return(ost);
     }
bool IRAD::Profiler::operator<= (const struct timeval & t1, const struct timeval & t2) inline
Definition at line 104 of file Profiler.C.
     {
       return((t1 < t2) || (t1 == t2));
     }
bool IRAD::Profiler::operator== (const struct timeval & t1, const struct timeval & t2) inline
Definition at line 65 of file Profiler.C.
     {
       return((t1.tv_sec + (t1.tv_usec/1000000.0)) ==
              (t2.tv_sec + (t2.tv_usec/1000000.0)));
     }
bool IRAD::Profiler::operator> (const struct timeval & t1, const struct timeval & t2) inline
Definition at line 94 of file Profiler.C.
     {
       return((t1.tv_sec + (t1.tv_usec/1000000.0)) >
              (t2.tv_sec + (t2.tv_usec/1000000.0)));
     }
bool IRAD::Profiler::operator>= (const struct timeval & t1, const struct timeval & t2) inline
Definition at line 113 of file Profiler.C.
     {
       return((t1 > t2) || (t1 == t2));
     }
std::istream & IRAD::Profiler::operator>> (std::istream & ist, Event & e)
Input function for Event.
Definition at line 140 of file Profiler.C.
References IRAD::Profiler::Event::_exclusive, IRAD::Profiler::Event::_id, IRAD::Profiler::Event::_inclusive, and IRAD::Profiler::Event::_timestamp.
     {
       ist >> e._id >> e._timestamp >> e._inclusive >> e._exclusive;
       return(ist);
     }
double IRAD::Profiler::Time () inline
Time returns the time in seconds from the system time. The user is responsible for adding the appropriate offset to make this number relative to the current execution.
Definition at line 260 of file Profiler.H.
Referenced by IRAD::Profiler::ProfilerObj::Finalize(), IRAD::Profiler::ProfilerObj::FunctionEntry(), IRAD::Profiler::ProfilerObj::FunctionExit(), IRAD::Profiler::ProfilerObj::FunctionExitAll(), IRAD::Profiler::ProfilerObj::Init(), IMPACT::ParallelTestingObject< CommType, ResultsType >::Test__ParallelMidPointQuadrature(), and IMPACT::ParallelTestingObject< CommType, ResultsType >::Test__ParallelTrapezoidQuadrature().
     {
       struct timeval tv;
       gettimeofday(&tv,NULL);
       double t = tv.tv_sec + tv.tv_usec/1000000.;
       return(t);
     }