IMPACT: IMPACT::ExampleProgram Namespace Reference
IMPACT::ExampleProgram Namespace Reference
Encapsulate example program-specific code constructs.
Detailed Description
This namespace contains all of the base code constructs that are used in the example programs. These example programs have several features which make them very easy to integrate in composite software systems.
Program is entirely encapsulated in program object
All screen output is automatically tagged with the program name
Common look-and-feel interface
Interface functionality allows menu-driven integration
Other convenient features of this API are:
Built-in stack tracing for debugging
Built-in profiling utilities
Advanced command-line handling
Built-in parallelism
Classes
class ExampleProgramComLine
The ComLineObject for the example programs.
class SerialProgram
Implementation of the basic parts of the serial program example.
class ParallelProgram
Implementation of the basic parts of the parallel program example.
Typedefs
typedef IRAD::Profiler::ProfilerObj ProfilerType
Convenience type definition for Profiler object.
typedef std::string StackType
Convenience type definition for program stack.
typedef
IRAD::Global::GlobalObj
< StackType, int, ProfilerType > GlobalType
Convenience type definition for the serial global object.
typedef
IRAD::Comm::CommunicatorObject CommType
Convenience type definition for parallel communication object.
typedef
IRAD::Global::ParallelGlobalObj
< CommType, StackType, int,
ProfilerType > PGlobalType
Convenience type definition for parallel global object.
typedef ExampleProgramComLine ComLineType
Convenience type definition for the example comline object.
typedef IRAD::Global::Program
< GlobalType, ComLineType > SerialProgramType
Convenience type definition for the serial program.
typedef IRAD::Global::Program
< PGlobalType, ComLineType > ParallelProgramType
Convenience type definition for the parallel program.
typedef
IMPACT::ExampleProgram::SerialProgram SEProgramType
Convenience definition for serial program type.
typedef
IMPACT::ExampleProgram::ParallelProgram PEProgramType
Convenience definition for parallel program type.
Functions
template<typename ProgramType >
int Driver (int argc, char *argv[])
Unified driver for the example programs.
double f (double x)
Support function for parallel example.
Typedef Documentation
typedef ExampleProgramComLine IMPACT::ExampleProgram::ComLineType
Definition at line 114 of file ExampleProgram.H.
typedef IRAD::Comm::CommunicatorObject IMPACT::ExampleProgram::CommType
Definition at line 58 of file ExampleProgram.H.
typedef IRAD::Global::GlobalObj<StackType,int,ProfilerType> IMPACT::ExampleProgram::GlobalType
The global object encapsulates all of the built-in functionalities for a program. Its interface and implementation are defined in IRAD/include/Global.H
Definition at line 53 of file ExampleProgram.H.
typedef IRAD::Global::Program<PGlobalType,ComLineType> IMPACT::ExampleProgram::ParallelProgramType
For a detailed description of the program type, see IRAD::Global::Program documentation.
Definition at line 129 of file ExampleProgram.H.
typedef IMPACT::ExampleProgram::ParallelProgram IMPACT::ExampleProgram::PEProgramType
Definition at line 499 of file ExampleProgram.H.
typedef IRAD::Global::ParallelGlobalObj<CommType,StackType,int,ProfilerType> IMPACT::ExampleProgram::PGlobalType
Definition at line 62 of file ExampleProgram.H.
typedef IRAD::Profiler::ProfilerObj IMPACT::ExampleProgram::ProfilerType
Definition at line 41 of file ExampleProgram.H.
typedef IMPACT::ExampleProgram::SerialProgram IMPACT::ExampleProgram::SEProgramType
Definition at line 480 of file ExampleProgram.H.
typedef IRAD::Global::Program<GlobalType,ComLineType> IMPACT::ExampleProgram::SerialProgramType
For a detailed description of the program type, see IRAD::Global::Program documentation.
Definition at line 121 of file ExampleProgram.H.
typedef std::string IMPACT::ExampleProgram::StackType
Definition at line 45 of file ExampleProgram.H.
Function Documentation
template<typename ProgramType > int IMPACT::ExampleProgram::Driver (int argc, char * argv[])
This driver is exactly the same for both the serial and parallel example programs. It is a direct replacement for main and is responsible for creating the "Program object" and calling its Initialization, Run, and Finalize methods.
Definition at line 444 of file ExampleProgram.H.
References IRAD::Global::Program< GlobalType, ComLineType >::Finalize(), IMPACT::ExampleProgram::ParallelProgram::Initialize(), SolverUtils::Ostr, IMPACT::ExampleProgram::ParallelProgram::Run(), and IMPACT::ExampleProgram::ParallelProgram::VerbLevel().
     {
       ProgramType MyProgram(argc,argv);
       int retval = MyProgram.Initialize();
       if(retval){
         if(retval > 0){ // then there was an error
           MyProgram.ErrOut("Error in Program Initialization.\n");
           return(1);
         }
         else return(0); // no error, but the program should not continue
       }
       if(MyProgram.VerbLevel() > 1)
         MyProgram.StdOut("Calling RUN.\n");
       if(MyProgram.Run()){
         MyProgram.ErrOut("Error in Program RUN method.\n");
         return(1);
       }
       if(MyProgram.VerbLevel() > 1){
         std::ostringstream Ostr;
         MyProgram.Report(Ostr);
         MyProgram.StdOut(Ostr.str());
         MyProgram.StdOut("Calling Finalize.\n");
       }
       if(MyProgram.Finalize()){
         MyProgram.ErrOut("Error in Program Finalization.\n");
         return(1);
       }
       if(MyProgram.VerbLevel() > 1)
         MyProgram.StdOut("All done.\n");
       return(0);
     }
double IMPACT::ExampleProgram::f (double x) inline
Parameters
x The x-coordinate.
Returns
The value of the function at x
This function returns the derivative of (4 arctan(x)) at x. Specifically, it implements:
.
Definition at line 492 of file ExampleProgram.H.
Referenced by COM_Object_derived::cast_obj(), cg_exponents_as_string_write(), com_get_address_f(), com_set_address_f(), RFC_Pane_base::comp_nat_coors(), ComponentInterface::function(), Overlay::get_edge_pair_parents(), COM::COM_base::get_f90pointer(), Rocout::get_fname(), COM::COM_base::get_function_handle(), RFC_Pane_base::get_host_element_of_subface(), RFC_Pane_base::get_host_element_of_subnode(), Overlay::get_parent_face(), RFC_Window_overlay::init_feature_parameters(), Generic_element_2::interpolate(), Transfer_base::interpolate_fe(), Generic_element_2::interpolate_nopt(), Generic_element_2::interpolate_to_center(), Rocsurf::interpolate_to_centers(), io_pane(), LoadTransfer_FS::LoadTransfer_FS(), main(), MeshMotionTransferISS::MeshMotionTransferISS(), IMPACT::MidPointQuadrature(), Function::operator()(), Scheduler::print(), Coupling::print(), Overlay_primitives::project_blue_feature(), Overlay_primitives::project_green_feature(), Overlay_primitives::project_onto_element(), read_obj(), RFC_Window_transfer::replicate_metadata(), IMPACT::ExampleProgram::ParallelProgram::Run(), Window_manifold_2::serialize_window(), COM::COM_base::set_f90pointer(), and IMPACT::TrapezoidQuadrature().
     {
       return (4.0 / (1.0 + x*x));
     }