IMPACT: IMPACT::TestFixture Namespace Reference
IMPACT::TestFixture Namespace Reference
Namespace for storing simple test utility fixtures.
Functions
double F1 (double x)
Simple test function fixture returns .
double F2 (double x)
Simple test function fixture returns .
Function Documentation
double IMPACT::TestFixture::F1 (double x)
F1 is a 1st order function in x that has unity integral over [0,1].
Definition at line 34 of file IMPACTTest.H.
Referenced by IMPACT::TestingObject< ResultsType >::Test__MidPointQuadrature(), IMPACT::ParallelTestingObject< CommType, ResultsType >::Test__ParallelMidPointQuadrature(), IMPACT::ParallelTestingObject< CommType, ResultsType >::Test__ParallelTrapezoidQuadrature(), and IMPACT::TestingObject< ResultsType >::Test__TrapezoidQuadrature().
 { return (2.0*x); };
double IMPACT::TestFixture::F2 (double x)
F2 is quadratic function in x and integrates to unity over [0,1].
Definition at line 40 of file IMPACTTest.H.
Referenced by IMPACT::TestingObject< ResultsType >::Test__MidPointQuadrature(), IMPACT::ParallelTestingObject< CommType, ResultsType >::Test__ParallelMidPointQuadrature(), IMPACT::ParallelTestingObject< CommType, ResultsType >::Test__ParallelTrapezoidQuadrature(), and IMPACT::TestingObject< ResultsType >::Test__TrapezoidQuadrature().
 { return (3.0*x*x); };