IMPACT: IMPACT Namespace Reference
IMPACT Namespace Reference
IMPACT-specific documentation group
Project-specific namespace.
Detailed Description
Every project needs its own namespace. This helps make it much easier to deal with in integrated/composite software packages.
Namespaces
ExampleProgram
Encapsulate example program-specific code constructs.
TestFixture
Namespace for storing simple test utility fixtures.
Classes
class TestingObject
Project-specific testing object.
class ParallelTestingObject
Project-specific parallel testing object.
class TestComLine
ComLineObject for IMPACT testing command-line interface.
Typedefs
typedef IRAD::Util::TestResults TestResults
Project-specific test results type.
typedef
IRAD::Comm::CommunicatorObject CommType
Convenience typedef for CommunicatorObject.
Functions
std::string ExampleFunction (const std::string &instring)
Example function for IMPACT (this is a brief description).
double TrapezoidQuadrature (double(*f)(double), double x0, double xn, int n)
Integrates f with composite trapezoid rule.
double MidPointQuadrature (double(*f)(double), double x0, double xn, int n)
Integrates f with composite midpoint rule.
bool Excluded (const std::string &filename)
Exclude certain template files from conversion in project creation.
int MakeProject (int argc, char *argv[])
Creates a new project from an IMPACT base.
int ParallelTest (int argc, char *argv[])
Drives the IMPACT::TestObject.
int Test (int argc, char *argv[])
Drives the IMPACT::TestObject.
Typedef Documentation
typedef IRAD::Comm::CommunicatorObject IMPACT::CommType
Definition at line 20 of file ParallelTestIMPACT.C.
typedef IRAD::Util::TestResults IMPACT::TestResults
Test results types can be custom implemented by the project developer. The requirement is that they produce the proper test results output when used with outstreams.
Definition at line 41 of file IMPACTTest.H.
Function Documentation
std::string IMPACT::ExampleFunction (const std::string & instring)
Parameters
instring Input string to copy
Returns
A copy of the input string
Bug:
No known bugs.
Note
All of this documentation is generated from the comments in ExampleHeader.H
The first sentence in a doxygen comment block before a code construct is interpreted as the "brief" description.
Warning
This is an example warning.
Todo:
Nothing to do on this example function.
The detailed description for ExampleFunction actually starts above with the constructs describing the input/output, and any notes, warnings, todo, bugs, author, or other information the author would like to put in.
At IR, we like for all code constructs to have a "brief" description -first sentence in this comment block, and then a "detailed" description as needed, but it should at least list the input params and output description. The actual example detailed documentation for this function now follows:
This function returns a copy of the input string. If there were more to say about this, then it can be said here.
Definition at line 31 of file ExampleSourceFile.C.
Referenced by IMPACT::TestingObject< ResultsType >::Test__ExampleFunction().
   {
     return(instring);
   };
bool IMPACT::Excluded (const std::string & filename)
Definition at line 25 of file MakeProject.C.
Referenced by MakeProject().
   {
     std::string::size_type x = filename.find("IR.dox");
     if(x != std::string::npos)
       return(true);
     x = filename.find("MakeProject.dox");
     if(x != std::string::npos)
       return(true);
     x = filename.find("ExistingProject.dox");
     if(x != std::string::npos)
       return(true);
     return(false);
   }
int IMPACT::MakeProject (int argc, char * argv[])
This program is designed to make a new IllinoisRocstar software project starting from an intallation of the IMPACT project template.
Usage of this program should go like the following:
Get and Install the IMPACT template.
svn co $IRREPO/IMPACT/trunk IMPACT
mkdir impact_build
cd impact_build
cmake ../IMPACT
make
cd ../
Create the new project, <NewProject>, with the "make_project" command.
impact_build/bin/make_project IMPACT <NewProject>
Note
Be sure to replace <NewProject> with your new project name.
The usage for the make_project command is:
make_project usage:
make_project <template name> <new project> [verb level]
This program will read the project template from the <template name>
directory and create a new "blank" IllinoisRocstar project
named <new name>, in a directory named <new name>.
An optional verblevel of 1 or 2 can be given to make the process
more verbose.
Definition at line 77 of file MakeProject.C.
References IRAD::Sys::ChDir(), IRAD::Sys::CreateDirectory(), Excluded(), IRAD::Sys::InProcess::Execute(), IRAD::Sys::FILEEXISTS(), IRAD::Sys::Remove(), and IRAD::Sys::Rename().
Referenced by main().
   {
     if(argc < 3){
       std::cout << "Usage:" << std::endl << std::endl
                 << argv[0] << " <template name> <new name> [verb level]" << std::endl
                 << std::endl
                 << "This program will read the project template from the <template name> "
                 << std::endl
                 << "directory and create a new \"blank\" IllinoisRocstar project"
                 << std::endl
                 << "named <new name>, in a directory named <new name>."
                 << std::endl
                 << "An optional verblevel of 1 or 2 can be given to make the process"
                 << std::endl << "more verbose." << std::endl;
       return(0);
     }
     std::string OriginalName(argv[1]);
     std::string NewName(argv[2]);
     int verb = 0;
     if(argv[3]){
       verb = 1;
       int v = atoi(argv[3]);
       if(v > 0)
         verb = v;
     }
     std::vector<std::string> ProtectedFiles;
     ProtectedFiles.push_back("AUTHORS");
     ProtectedFiles.push_back("CTestConfig.cmake");
     ProtectedFiles.push_back("LICENSE");
     ProtectedFiles.push_back(".svn");
     std::vector<std::string> CommonFiles;
     CommonFiles.push_back("CMakeLists.txt");
     int syserr = 0;
     std::string olower(OriginalName);
     std::string oupper(OriginalName);
     std::string nlower(NewName);
     std::string nupper(NewName);
     std::transform(olower.begin(),olower.end(),olower.begin(),tolower);
     std::transform(oupper.begin(),oupper.end(),oupper.begin(),toupper);
     std::transform(nlower.begin(),nlower.end(),nlower.begin(),tolower);
     std::transform(nupper.begin(),nupper.end(),nupper.begin(),toupper);
     if(verb)
       std::cout << "Creating a new project (" << NewName
                 << ") from project template (" << OriginalName
                 << ")." << std::endl << std::endl
                 << "Creating top level project directories...";
     std::string dirname(NewName);
     if(!IRAD::Sys::FILEEXISTS(NewName)){
       if(verb > 1)
         std::cout << "   Creating directory " << dirname << "...";
       syserr = IRAD::Sys::CreateDirectory(dirname);
       if(syserr){
         std::cout << "Unable to create directory " << dirname << "."
                   << std::endl;
         return(1);
       }
       if(verb > 1)
         std::cout << "done." << std::endl;
     }
     dirname += "/branches";
     if(!IRAD::Sys::FILEEXISTS(dirname)){
       if(verb > 1)
         std::cout << "   Creating directory " << dirname << "...";
       syserr = IRAD::Sys::CreateDirectory(dirname);
       if(syserr){
         std::cout << "Unable to create directory " << dirname << "."
                   << std::endl;
         return(1);
       }
       if(verb > 1)
         std::cout << "done." << std::endl;
     }
     dirname = NewName+"/tags";
     if(!IRAD::Sys::FILEEXISTS(dirname)){
       if(verb > 1)
         std::cout << "   Creating directory " << dirname << "...";
       syserr = IRAD::Sys::CreateDirectory(dirname);
       if(syserr){
         std::cout << "Unable to create directory " << dirname << "."
                   << std::endl;
         return(1);
       }
       if(verb > 1)
         std::cout << "done." << std::endl;
     }
     dirname.assign(NewName+"/examples");
     if(!IRAD::Sys::FILEEXISTS(dirname)){
       if(verb > 1)
         std::cout << "   Creating directory " << dirname << "...";
       syserr = IRAD::Sys::CreateDirectory(dirname);
       if(syserr){
         std::cout << "Unable to create directory " << dirname << "."
                   << std::endl;
         return(1);
       }
       if(verb > 1)
         std::cout << "done." << std::endl;
     }
     bool protect_svn = false;
     dirname = NewName+"/trunk";
     std::vector<std::string>::iterator pfi = ProtectedFiles.begin();
     while(pfi != ProtectedFiles.end()){
       std::string ProtectThisFile(dirname+"/"+*pfi++);
       std::string ProtectedFile(ProtectThisFile+".backup");
       if(IRAD::Sys::FILEEXISTS(ProtectThisFile))
         IRAD::Sys::Rename(ProtectThisFile,ProtectedFile);
     }
     pfi = CommonFiles.begin();
     while(pfi != CommonFiles.end()){
       std::string ProtectThisFile(dirname+"/"+*pfi++);
       std::string ProtectedFile(ProtectThisFile+".backup");
       if(IRAD::Sys::FILEEXISTS(ProtectThisFile))
         IRAD::Sys::Rename(ProtectThisFile,ProtectedFile);
     }
     std::ostringstream ComStr;
     if(!IRAD::Sys::FILEEXISTS(dirname)){
       if(verb > 1)
         std::cout << "   Creating directory " << dirname << "...";
       ComStr << "cp -r " << OriginalName << " " << dirname;
     } else {
       if(verb > 1)
         std::cout <<   "   Making project files from template ...";
       ComStr << "cp -r " << OriginalName << "/* " << dirname;
     }
     IRAD::Sys::InProcess System(ComStr.str());
     std::string comline;
     while(std::getline(System,comline)){
       if(verb > 1)
         std::cout << comline << std::endl;
     }
     if(verb)
       std::cout << "done." << std::endl;
     if(verb)
       std::cout << "Cleaning up ...";
     ComStr.str("");
     ComStr << "rm -rf " << dirname << "/.svn";
     System.Execute(ComStr.str());
     int n = 0;
     while(std::getline(System,comline))
       n++;
     pfi = ProtectedFiles.begin();
     while(pfi != ProtectedFiles.end()){
       std::string ProtectThisFile(dirname+"/"+*pfi++);
       std::string ProtectedFile(ProtectThisFile+".backup");
       if(IRAD::Sys::FILEEXISTS(ProtectedFile)){
         if(IRAD::Sys::FILEEXISTS(ProtectThisFile))
           IRAD::Sys::Remove(ProtectThisFile);
         IRAD::Sys::Rename(ProtectedFile,ProtectThisFile);
       }
     }
     pfi = CommonFiles.begin();
     while(pfi != CommonFiles.end()){
       std::string ProtectThisFile(dirname+"/"+*pfi++);
       std::string ProtectedFile(ProtectThisFile+".backup");
       std::string CommonFileTemplate(ProtectThisFile+".template");
       if(IRAD::Sys::FILEEXISTS(ProtectedFile)){
         if(IRAD::Sys::FILEEXISTS(ProtectThisFile))
           IRAD::Sys::Rename(ProtectThisFile,CommonFileTemplate);
         IRAD::Sys::Rename(ProtectedFile,ProtectThisFile);
       }
     }
     if(verb)
       std::cout << "done." << std::endl;
     if(verb > 1)
       std::cout << "Done creating new project files."
                 << std::endl;
     if(verb)
       std::cout << "Renaming project...";
     if(IRAD::Sys::ChDir(dirname)){
       std::cout << "Something went wrong, cannot find new project directory."
                 << std::endl;
       return(1);
     }
     ComStr.str("");
     ComStr << "grep -i " << OriginalName << " -r * | cut -d \":\" -f 1 | sort | uniq";
     if(verb > 1)
       std::cout << "   " << ComStr.str() << std::endl;
     System.Execute(ComStr.str());
     std::vector<std::string> filenames;
     if(verb > 1)
       std::cout << "   Files to change:" << std::endl;
     while(std::getline(System,comline)){
       if(!Excluded(comline)){
         filenames.push_back(comline);
         if(verb > 1)
           std::cout << "     " << comline << std::endl;
       }
     }
     std::vector<std::string>::iterator fni = filenames.begin();
     if(verb > 1)
       std::cout << "   Processing files....";
     while(fni != filenames.end()){
       std::string filename(*fni++);
       if(verb > 1)
         std::cout << "     File: " << filename << std::endl;
       ComStr.str("");
       ComStr << "sed -i 's/" << OriginalName << "/" << NewName << "/g' " << filename;
       if(verb > 1)
         std::cout << "       " << ComStr.str() << std::endl;
       System.Execute(ComStr.str());
       int n = 0;
       while(std::getline(System,comline))
         n++;
       ComStr.str("");
       ComStr << "sed -i 's/" << oupper << "/" << nupper << "/g' " << filename;
       if(verb > 1)
         std::cout << "       " << ComStr.str() << std::endl;
       //    std::cout << ComStr.str() << std::endl;
       System.Execute(ComStr.str());
       while(std::getline(System,comline))
         n++;
       ComStr.str("");
       ComStr << "sed -i 's/" << olower << "/" << nlower << "/g' " << filename;
       if(verb > 1)
         std::cout << "       " << ComStr.str() << std::endl;
       //    std::cout << ComStr.str() << std::endl;
       System.Execute(ComStr.str());
       while(std::getline(System,comline))
         n++;
     }
     if(verb > 1)
       std::cout << "   Done processing file contents." << std::endl
                 << "   Renaming files..." << std::endl;
     ComStr.str("");
     // Now the inside of all files is fixed, need to fix filenames
     ComStr << "find . -name \"*" << OriginalName << "*\"";
     System.Execute(ComStr.str());
     std::string::size_type olen = OriginalName.length();
     std::string::size_type nlen = NewName.length();
     while(std::getline(System,comline)){
       if(verb > 1)
         std::cout << "     Renaming " << comline << " to ";
       std::string newname(comline);
       std::string::size_type x = newname.find(OriginalName);
       while(x != std::string::npos){
         newname.replace(x,olen,NewName);
         x = newname.find(OriginalName);
       }
       ComStr.str("");
       if(verb > 1)
         std::cout << newname << std::endl;
       ComStr << "mv " << comline << " " << newname;
       //    std::cout << ComStr.str() << std::endl;
       IRAD::Sys::InProcess MV(ComStr.str());
     }
     if(verb > 1)
       std::cout << "done." << std::endl;
     return(0);
   }
double IMPACT::MidPointQuadrature (double(*)(double) f, double x0, double xn, int n)
Parameters
f Function to integrate takes a double argument, x, and returns a double value
x0 The lower integration domain limit.
xn The upper integration domain limit.
n The number of intervals into which to break the domain.
Returns
The numerical approximation for .
With , and , the integral is calculated as:
The error of this method is .
Test:
IMPACT::TestingObject::Test__MidPointQuadrature tests this function by sending linear and quadratic test functions.
Definition at line 51 of file ExampleSourceFile.C.
References IMPACT::ExampleProgram::f().
Referenced by IMPACT::ExampleProgram::ParallelProgram::Run(), IMPACT::TestingObject< ResultsType >::Test__MidPointQuadrature(), IMPACT::ParallelTestingObject< CommType, ResultsType >::Test__ParallelMidPointQuadrature(), and IMPACT::ParallelTestingObject< CommType, ResultsType >::Test__ParallelTrapezoidQuadrature().
   {
     double h = (xn - x0)/(static_cast<double>(n));
     if(std::fabs(h) < 1e-12) throw 1;
     double sum = 0.0;
     for(int i = 1;i <= n;i++)
       sum += f(x0+((static_cast<double>(i)-.5)*h));
     return(h*sum);
   }
int IMPACT::ParallelTest (int argc, char * argv[])
Parameters
argc number of string command line tokens
argv string command line tokens
Returns
0 if successful, 1 otherwise
Drives the IMPACT::TestObject, which should encapsulate all the tests for the IMPACT namespace (and thus the project).
Command line documentation:
      impact_test [-h] [-v [level] -o <filename> -l <filename> -n <TestName> ]
      -h,--help
         Print out long version of help and exit.
      -v,--verblevel [level]
         Set the verbosity level. (default = 0)
      -o,--output <filename>
         Set the output file to <filename>. (default = stdout)
      -l,--list <filename>
         Set the list file name to <filename>. (no default). The list file should be a text file with one test name per line.
      -n,--name <TestName>
         Run test by name. (no default)
Definition at line 50 of file ParallelTestIMPACT.C.
References IRAD::Comm::CommunicatorObject::Check(), IRAD::Util::ComLineObject::ErrorReport(), IRAD::Util::ComLineObject::GetOption(), IMPACT::TestComLine::Initialize(), IRAD::Util::ComLineObject::LongUsage(), IMPACT::ParallelTestingObject< CommType, ResultsType >::Process(), IRAD::Util::ComLineObject::ProcessOptions(), IRAD::Comm::CommunicatorObject::Rank(), IMPACT::ParallelTestingObject< CommType, ResultsType >::RunTest(), IRAD::Comm::CommunicatorObject::SetExit(), IRAD::Util::ComLineObject::ShortUsage(), and IRAD::Comm::CommunicatorObject::Size().
Referenced by main().
   {
     // The default verbosity is 0
     int verblevel = 0;
     // This sets everything up with MPI
     IMPACT::CommType communicator(&argc,&argv);
     int rank  = communicator.Rank();
     int nproc = communicator.Size();
     bool do_stdout = !rank;
     // This line creates the IMPACT::TestComLine object and passes in
     // the command line arguments as a (const char **).
     TestComLine comline((const char **)(argv));
     // The call to comline.Initialize() reads the command line arguments
     // from the array passed in the previous line.
     comline.Initialize();
     // The ProcessOptions() call does detailed examination of the command
     // line arguments to check for user errors or other problems. This call
     // will return non-zero if there were errors on the commandline.
     int clerr = comline.ProcessOptions();
     // Check if the user just wanted to get the help and exit
     if(!comline.GetOption("help").empty()){
       // Print out the "long usage" (i.e. help) message to stdout
       if(do_stdout){
         std::cout << comline.LongUsage() << std::endl;
         if(verblevel > 1)
           std::cout << "IMPACT::ParallelTest: Exiting test function (success)"
                     << std::endl;
       }
       communicator.SetExit(1);
     }
     if(communicator.Check())
       return(0);
     if(clerr){
       if(do_stdout){
         std::cout << comline.ErrorReport() << std::endl
                   << std::endl << comline.ShortUsage() << std::endl;
         if(verblevel > 2)
           std::cout << "IMPACT::ParallelTest: Exiting test function (fail)" << std::endl;
       }
       communicator.SetExit(1);
     }
     if(communicator.Check())
       return(1);
     // These outstreams allow the output to file to be set up and separated
     // from the stdout.
     std::ofstream Ouf;
     std::ostream *Out = NULL;
     if(do_stdout)
       Out = &std::cout;
     // The next few lines populate some strings based on the
     // users input from the commandline.
     std::string OutFileName(comline.GetOption("output"));
     std::string TestName(comline.GetOption("name"));
     std::string ListName(comline.GetOption("list"));
     std::string sverb(comline.GetOption("verblevel"));
     // The following block parses and sets the verbosity level
     if(!sverb.empty()){
       verblevel = 1;
       if(sverb != ".true."){
         std::istringstream Istr(sverb);
         Istr >> verblevel;
         if(verblevel < 0)
           verblevel = 1;
       }
     }
     // This block sets up the output file if the user specified one
     if(!OutFileName.empty()){
       if(Out){
         Ouf.open(OutFileName.c_str());
         if(!Ouf){
           std::cout << "IMPACT::ParallelTest> Error: Could not open output file, "
                     <<  OutFileName << " for test output. Exiting (fail)." << std::endl;
           communicator.SetExit(1);
         }
         Out = &Ouf;
       }
       if(communicator.Check())
         return(1);
     }
     if(verblevel > 1 && Out)
       *Out << "IMPACT::ParallelTest: Entering test function" << std::endl;
     // Make an instance of the IMPACT testing object, IMPACT::ParallelTestingObject
     IMPACT::ParallelTestingObject<IMPACT::CommType,IMPACT::TestResults> test(communicator);
     // Make an instance of the IMPACT results object, IMPACT::TestResults
     IMPACT::TestResults results;
     // If the user specified a name, then run only the named test
     if(!TestName.empty()){
       // This call runs a test by name
       test.RunTest(TestName,results);
     }
     // Otherwise, if the user specified a list, then read the list and
     // run the listed tests.
     else if(!ListName.empty()){
       std::ifstream ListInf;
       ListInf.open(ListName.c_str());
       if(!ListInf){
         if(Out)
           *Out << "IMPACT::ParallelTest> Error: Could not open list of tests in file "
                << ListName << ". Exiting (fail)." << std::endl;
         communicator.SetExit(1);
       }
       if(communicator.Check())
         return(1);
       std::string testname;
       while(std::getline(ListInf,testname))
         test.RunTest(testname,results);
       ListInf.close();
     }
     else {
       // This call runs all the tests for the IMPACT namespace.
       test.Process(results);
     }
     if(Out)
       *Out << results << std::endl;
     if(Out && Ouf)
       Ouf.close();
     if((verblevel > 1) && Out)
       *Out << "IMPACT::ParallelTest: Exiting test function (success)" << std::endl;
     return(0);
   }
int IMPACT::Test (int argc, char * argv[])
Parameters
argc number of string command line tokens
argv string command line tokens
Returns
0 if successful, 1 otherwise
Drives the IMPACT::TestObject, which should encapsulate all the tests for the IMPACT namespace (and thus the project).
Command line documentation:
      impact_test [-h] [-v [level] -o <filename> -l <filename> -n <TestName> ]
      -h,--help
         Print out long version of help and exit.
      -v,--verblevel [level]
         Set the verbosity level. (default = 0)
      -o,--output <filename>
         Set the output file to <filename>. (default = stdout)
      -l,--list <filename>
         Set the list file name to <filename>. (no default). The list file should be a text file with one test name per line.
      -n,--name <TestName>
         Run test by name. (no default)
Definition at line 45 of file TestIMPACT.C.
References IRAD::Util::ComLineObject::ErrorReport(), IRAD::Util::ComLineObject::GetOption(), IMPACT::TestComLine::Initialize(), IRAD::Util::ComLineObject::LongUsage(), IMPACT::TestingObject< ResultsType >::Process(), IRAD::Util::ComLineObject::ProcessOptions(), IMPACT::TestingObject< ResultsType >::RunTest(), and IRAD::Util::ComLineObject::ShortUsage().
Referenced by main().
   {
     // The default verbosity is 0
     int verblevel = 0;
     // This line creates the IMPACT::TestComLine object and passes in
     // the command line arguments as a (const char **).
     TestComLine comline((const char **)(argv));
     // The call to comline.Initialize() reads the command line arguments
     // from the array passed in the previous line.
     comline.Initialize();
     // The ProcessOptions() call does detailed examination of the command
     // line arguments to check for user errors or other problems. This call
     // will return non-zero if there were errors on the commandline.
     int clerr = comline.ProcessOptions();
     // Check if the user just wanted to get the help and exit
     if(!comline.GetOption("help").empty()){
       // Print out the "long usage" (i.e. help) message to stdout
       std::cout << comline.LongUsage() << std::endl;
       if(verblevel > 2)
         std::cout << "IMPACT::Test: Exiting test function (success)" << std::endl;
       return(0);
     }
     if(clerr){
       std::cout << comline.ErrorReport() << std::endl
                 << std::endl << comline.ShortUsage() << std::endl;
       if(verblevel > 2)
         std::cout << "IMPACT::Test: Exiting test function (fail)" << std::endl;
       return(1);
     }
     // These outstreams allow the output to file to be set up and separated
     // from the stdout.
     std::ofstream Ouf;
     std::ostream *Out = &std::cout;
     // The next few lines populate some strings based on the
     // users input from the commandline.
     std::string OutFileName(comline.GetOption("output"));
     std::string TestName(comline.GetOption("name"));
     std::string ListName(comline.GetOption("list"));
     std::string sverb(comline.GetOption("verblevel"));
     // The following block parses and sets the verbosity level
     if(!sverb.empty()){
       verblevel = 1;
       if(sverb != ".true."){
         std::istringstream Istr(sverb);
         Istr >> verblevel;
         if(verblevel < 0)
           verblevel = 1;
       }
     }
     // This block sets up the output file if the user specified one
     if(!OutFileName.empty()){
       Ouf.open(OutFileName.c_str());
       if(!Ouf){
         std::cout << "IMPACT::Test> Error: Could not open output file, "
                   <<  OutFileName << " for test output. Exiting (fail)." << std::endl;
         return(1);
       }
       Out = &Ouf;
     }
     if(verblevel > 2)
       std::cout << "IMPACT::Test: Entering test function" << std::endl;
     // Make an instance of the IMPACT testing object, IMPACT::TestingObject
     IMPACT::TestingObject<IMPACT::TestResults> test;
     // Make an instance of the IMPACT results object, IMPACT::TestResults
     IMPACT::TestResults results;
     // If the user specified a name, then run only the named test
     if(!TestName.empty()){
       // This call runs a test by name
       test.RunTest(TestName,results);
     }
     // Otherwise, if the user specified a list, then read the list and
     // run the listed tests.
     else if(!ListName.empty()){
       std::ifstream ListInf;
       ListInf.open(ListName.c_str());
       if(!ListInf){
         std::cout << "IMPACT::Test> Error: Could not open list of tests in file "
                   << ListName << ". Exiting (fail)." << std::endl;
         return(1);
       }
       std::string testname;
       while(std::getline(ListInf,testname))
         test.RunTest(testname,results);
       ListInf.close();
     }
     else {
       // This call runs all the tests for the IMPACT namespace.
       test.Process(results);
     }
     *Out << results << std::endl;
     if(Ouf)
       Ouf.close();
     if(verblevel > 2)
       *Out << "IMPACT::Test: Exiting test function (success)" << std::endl;
     return(0);
   }
double IMPACT::TrapezoidQuadrature (double(*)(double) f, double x0, double xn, int n)
Parameters
f Function to integrate takes a double argument, x, and returns a double value
x0 The lower integration domain limit.
xn The upper integration domain limit.
n The number of intervals into which to break the domain.
Returns
The numerical approximation for .
With , and , the integral is calculated as:
The error of this method is .
Test:
IMPACT::TestingObject::Test__TrapezoidQuadrature tests this function by sending linear and quadratic test functions.
Definition at line 39 of file ExampleSourceFile.C.
References IMPACT::ExampleProgram::f().
Referenced by IMPACT::ExampleProgram::ParallelProgram::Run(), IMPACT::ParallelTestingObject< CommType, ResultsType >::Test__ParallelTrapezoidQuadrature(), and IMPACT::TestingObject< ResultsType >::Test__TrapezoidQuadrature().
   {
     double h = (xn - x0)/(static_cast<double>(n));
     if(std::fabs(h) < 1e-12) throw 1;
     double sum = .5*(f(x0)+f(xn));
     for(int i = 1; i < n;i++)
       sum += f(x0 + i*h);
     return(h*sum);
   };