IMPACT: SolverUtils::GeoPrim Namespace Reference
SolverUtils::GeoPrim Namespace Reference
Classes
class C3Box
class C3Facet
class C3Line
class C3LineSegment
class C3Plane
class C3Point
/brief Cartesian 3 Point
class C3Vector
/brief Cartesian 3 Vector
class CBox
class CFacet
class CLine
class CLineSegment
class CPlane
class CPoint
class CVector
class PBox
Functions
template<typename PointContainer >
C3Point C3Centroid (const PointContainer &pc)
template<typename PointContainer >
CPoint Centroid (const PointContainer &pc)
void Transpose (CVector matrix[])
void Transpose_2x3 (CVector matrix[], double tpose[][2])
double Distance (const CPoint &p, const CLine &l)
double Distance (const C3Point &p, const CLine &l)
double Distance (const C3Point &p, const C3Line &l)
std::ostream & operator<< (std::ostream &oS, const GeoPrim::CBox &b)
std::ostream & operator<< (std::ostream &oS, const GeoPrim::C3Box &b)
std::istream & operator>> (std::istream &iS, GeoPrim::C3Box &b)
std::ostream & operator<< (std::ostream &oS, const GeoPrim::CPoint &p)
std::istream & operator>> (std::istream &iS, GeoPrim::CPoint &p)
std::ostream & operator<< (std::ostream &oS, const GeoPrim::CVector &v)
std::istream & operator>> (std::istream &iS, GeoPrim::CVector &v)
std::ostream & operator<< (std::ostream &oS, const GeoPrim::C3Point &p)
std::istream & operator>> (std::istream &iS, GeoPrim::C3Point &p)
std::ostream & operator<< (std::ostream &oS, const GeoPrim::C3Vector &v)
std::istream & operator>> (std::istream &iS, GeoPrim::C3Vector &v)
GeoPrim::CPoint operator* (double scalar, const GeoPrim::CPoint &p)
GeoPrim::C3Point operator* (double scalar, const GeoPrim::C3Point &p)
GeoPrim::C3Vector operator* (double scalar, const GeoPrim::C3Vector &v)
GeoPrim::CVector operator* (double scalar, const GeoPrim::CVector &v)
Variables
const double TOL = 1e-9
const double PI = 4.0*atan(1.0)
Function Documentation
template<typename PointContainer > C3Point SolverUtils::GeoPrim::C3Centroid (const PointContainer & pc)
Definition at line 2145 of file GeoPrimitives.H.
References SolverUtils::GeoPrim::C3Point::x().
Referenced by SolverUtils::GeoPrim::C3Facet::Centroid().
   {
     double x = 0.0;
     double y = 0.0;
     double z = 0.0;
     double np = 1.0/static_cast<double>(pc.size());
     typename PointContainer::const_iterator pi = pc.begin();
     while(pi != pc.end()){
       x += (*pi)->x();
       y += (*pi)->y();
       z += (*pi)->z();
       pi++;
     }
     x *= np;
     y *= np;
     z *= np;
     return(C3Point(x,y,z));
   };
template<typename PointContainer > CPoint SolverUtils::GeoPrim::Centroid (const PointContainer & pc)
Definition at line 2165 of file GeoPrimitives.H.
References SolverUtils::GeoPrim::CPoint::x().
Referenced by SolverUtils::GeoPrim::CFacet::centroid().
   {
     double x = 0.0;
     double y = 0.0;
     double z = 0.0;
     double np = 1.0/static_cast<double>(pc.size());
     typename PointContainer::const_iterator pi = pc.begin();
     while(pi != pc.end()){
       x += pi->x();
       y += pi->y();
       z += pi->z();
       pi++;
     }
     x *= np;
     y *= np;
     z *= np;
     return(CPoint(x,y,z));
   };
double SolverUtils::GeoPrim::Distance (const CPoint & p, const CLine & l)
Definition at line 38 of file GeoPrimitives.C.
References SolverUtils::GeoPrim::CVector::mag(), SolverUtils::GeoPrim::CVector::mag2(), SolverUtils::GeoPrim::CLine::p, SolverUtils::GeoPrim::CLine::v, SolverUtils::GeoPrim::CPoint::x(), SolverUtils::GeoPrim::CVector::x(), SolverUtils::GeoPrim::CPoint::y(), SolverUtils::GeoPrim::CVector::y(), SolverUtils::GeoPrim::CPoint::z(), and SolverUtils::GeoPrim::CVector::z().
   {
     double u = (((p.x() - l.p.x())*l.v.x() + (p.y() - l.p.y())*l.v.y() +
                  (p.z() - l.p.z())*l.v.z())/l.v.mag2());
     CPoint p2(l.p.x()+(u*l.v.x()),l.p.y()+(u*l.v.y()),l.p.z()+(u*l.v.z()));
     CVector v(p,p2);
     return(v.mag());
   }
double SolverUtils::GeoPrim::Distance (const C3Point & p, const CLine & l)
Definition at line 48 of file GeoPrimitives.C.
References SolverUtils::GeoPrim::C3Vector::Mag(), SolverUtils::GeoPrim::CVector::mag2(), SolverUtils::GeoPrim::CLine::p, SolverUtils::GeoPrim::CLine::v, SolverUtils::GeoPrim::CPoint::x(), SolverUtils::GeoPrim::CVector::x(), SolverUtils::GeoPrim::C3Point::x(), SolverUtils::GeoPrim::CPoint::y(), SolverUtils::GeoPrim::CVector::y(), SolverUtils::GeoPrim::C3Point::y(), SolverUtils::GeoPrim::CPoint::z(), SolverUtils::GeoPrim::CVector::z(), and SolverUtils::GeoPrim::C3Point::z().
   {
     double u = (((p.x() - l.p.x())*l.v.x() + (p.y() - l.p.y())*l.v.y() +
                  (p.z() - l.p.z())*l.v.z())/l.v.mag2());
     C3Point p2(l.p.x()+(u*l.v.x()),l.p.y()+(u*l.v.y()),l.p.z()+(u*l.v.z()));
     C3Vector v(p,p2);
     return(v.Mag());
   }
double SolverUtils::GeoPrim::Distance (const C3Point & p, const C3Line & l)
Definition at line 58 of file GeoPrimitives.C.
References SolverUtils::GeoPrim::C3Vector::Mag(), SolverUtils::GeoPrim::C3Vector::Mag2(), SolverUtils::GeoPrim::C3Line::p, SolverUtils::GeoPrim::C3Line::v, SolverUtils::GeoPrim::C3Point::x(), SolverUtils::GeoPrim::C3Vector::x(), SolverUtils::GeoPrim::C3Point::y(), SolverUtils::GeoPrim::C3Vector::y(), SolverUtils::GeoPrim::C3Point::z(), and SolverUtils::GeoPrim::C3Vector::z().
   {
     double u = (((p.x() - l.p.x())*l.v.x() + (p.y() - l.p.y())*l.v.y() +
                  (p.z() - l.p.z())*l.v.z())/l.v.Mag2());
     C3Point p2(l.p.x()+(u*l.v.x()),l.p.y()+(u*l.v.y()),l.p.z()+(u*l.v.z()));
     C3Vector v(p,p2);
     return(v.Mag());
   }
GeoPrim::CPoint SolverUtils::GeoPrim::operator* (double scalar, const GeoPrim::CPoint & p)
Definition at line 145 of file GeoPrimitives.C.
References SolverUtils::GeoPrim::CPoint::x(), SolverUtils::GeoPrim::CPoint::y(), and SolverUtils::GeoPrim::CPoint::z().
   {
     GeoPrim::CPoint rv(p);
     rv.x() *= scalar;
     rv.y() *= scalar;
     rv.z() *= scalar;
     return(rv);
   }
GeoPrim::C3Point SolverUtils::GeoPrim::operator* (double scalar, const GeoPrim::C3Point & p)
Definition at line 154 of file GeoPrimitives.C.
References SolverUtils::GeoPrim::C3Point::x(), SolverUtils::GeoPrim::C3Point::y(), and SolverUtils::GeoPrim::C3Point::z().
   {
     GeoPrim::C3Point rv(p);
     rv.x() *= scalar;
     rv.y() *= scalar;
     rv.z() *= scalar;
     return(rv);
   }
GeoPrim::C3Vector SolverUtils::GeoPrim::operator* (double scalar, const GeoPrim::C3Vector & v)
Definition at line 163 of file GeoPrimitives.C.
   {
     GeoPrim::C3Vector rv(v);
     return(rv *= scalar);
   }
GeoPrim::CVector SolverUtils::GeoPrim::operator* (double scalar, const GeoPrim::CVector & v)
Definition at line 169 of file GeoPrimitives.C.
   {
     GeoPrim::CVector rv(v);
     return(rv *= scalar);
   }
std::ostream& SolverUtils::GeoPrim::operator<< (std::ostream & oS, const GeoPrim::CBox & b)
Definition at line 68 of file GeoPrimitives.C.
References SolverUtils::GeoPrim::CBox::P1(), and SolverUtils::GeoPrim::CBox::P2().
   {
     oS << b.P1() << "  " << b.P2();
     return(oS);
   }
std::ostream& SolverUtils::GeoPrim::operator<< (std::ostream & oS, const GeoPrim::C3Box & b)
Definition at line 75 of file GeoPrimitives.C.
References SolverUtils::GeoPrim::C3Box::P1(), and SolverUtils::GeoPrim::C3Box::P2().
   {
     oS << b.P1() << "  " << b.P2();
     return(oS);
   }
std::ostream& SolverUtils::GeoPrim::operator<< (std::ostream & oS, const GeoPrim::CPoint & p)
Definition at line 89 of file GeoPrimitives.C.
References SolverUtils::GeoPrim::CPoint::x(), SolverUtils::GeoPrim::CPoint::y(), and SolverUtils::GeoPrim::CPoint::z().
   {
     oS << p.x() << "  " << p.y() << "  " << p.z();
     return(oS);
   }
std::ostream& SolverUtils::GeoPrim::operator<< (std::ostream & oS, const GeoPrim::CVector & v)
Definition at line 103 of file GeoPrimitives.C.
References SolverUtils::GeoPrim::CVector::x(), SolverUtils::GeoPrim::CVector::y(), and SolverUtils::GeoPrim::CVector::z().
   {
     oS << v.x() << "  " << v.y() << "  " << v.z();
     return(oS);
   }
std::ostream& SolverUtils::GeoPrim::operator<< (std::ostream & oS, const GeoPrim::C3Point & p)
Definition at line 117 of file GeoPrimitives.C.
References SolverUtils::GeoPrim::C3Point::x(), SolverUtils::GeoPrim::C3Point::y(), and SolverUtils::GeoPrim::C3Point::z().
   {
     oS << p.x() << "  " << p.y() << "  " << p.z();
     return(oS);
   }
std::ostream& SolverUtils::GeoPrim::operator<< (std::ostream & oS, const GeoPrim::C3Vector & v)
Definition at line 132 of file GeoPrimitives.C.
References SolverUtils::GeoPrim::C3Vector::x(), SolverUtils::GeoPrim::C3Vector::y(), and SolverUtils::GeoPrim::C3Vector::z().
   {
     oS << v.x() << "  " << v.y() << "  " << v.z();
     return(oS);
   }
std::istream& SolverUtils::GeoPrim::operator>> (std::istream & iS, GeoPrim::C3Box & b)
Definition at line 82 of file GeoPrimitives.C.
References SolverUtils::GeoPrim::C3Box::P1(), and SolverUtils::GeoPrim::C3Box::P2().
   {
     iS >> b.P1() >> b.P2();
     return(iS);
   }
std::istream& SolverUtils::GeoPrim::operator>> (std::istream & iS, GeoPrim::CPoint & p)
Definition at line 96 of file GeoPrimitives.C.
   {
     iS >> p[0] >> p[1] >> p[2];
     return(iS);
   }
std::istream& SolverUtils::GeoPrim::operator>> (std::istream & iS, GeoPrim::CVector & v)
Definition at line 110 of file GeoPrimitives.C.
   {
     iS >> v[0] >> v[1] >> v[2];
     return(iS);
   }
std::istream& SolverUtils::GeoPrim::operator>> (std::istream & iS, GeoPrim::C3Point & p)
Definition at line 125 of file GeoPrimitives.C.
   {
     iS >> p[0] >> p[1] >> p[2];
     return(iS);
   }
std::istream& SolverUtils::GeoPrim::operator>> (std::istream & iS, GeoPrim::C3Vector & v)
Definition at line 139 of file GeoPrimitives.C.
   {
     iS >> v[0] >> v[1] >> v[2];
     return(iS);
   }
void SolverUtils::GeoPrim::Transpose (CVector matrix[])
Definition at line 14 of file GeoPrimitives.C.
References SolverUtils::GeoPrim::CVector::init().
Referenced by SolverUtils::Mesh::GenericCell_2::shapef_jacobian_at(), and SolverUtils::Mesh::GenericElement::shapef_jacobian_at().
     {
       CVector tpose[3];
       tpose[0].init(matrix[0].x(),matrix[1].x(),matrix[2].x());
       tpose[1].init(matrix[0].y(),matrix[1].y(),matrix[2].y());
       tpose[2].init(matrix[0].z(),matrix[1].z(),matrix[2].z());
       matrix[0].init(tpose[0]);
       matrix[1].init(tpose[1]);
       matrix[2].init(tpose[2]);
     }
void SolverUtils::GeoPrim::Transpose_2x3 (CVector matrix[], double tpose[][2])
Definition at line 27 of file GeoPrimitives.C.
References SolverUtils::GeoPrim::CVector::x(), SolverUtils::GeoPrim::CVector::y(), and SolverUtils::GeoPrim::CVector::z().
   {
     tpose[0][0] = matrix[0].x();
     tpose[1][0] = matrix[0].y();
     tpose[2][0] = matrix[0].z();
     tpose[0][1] = matrix[1].x();
     tpose[1][1] = matrix[1].y();
     tpose[2][1] = matrix[1].z();
   }
Variable Documentation
const double SolverUtils::GeoPrim::PI = 4.0*atan(1.0)
Definition at line 20 of file GeoPrimitives.H.
Referenced by SolverUtils::GeoPrim::CFacet::contains_point().
const double SolverUtils::GeoPrim::TOL = 1e-9
Definition at line 19 of file GeoPrimitives.H.
Referenced by SolverUtils::GeoPrim::CPlane::contains_point(), SolverUtils::GeoPrim::C3Plane::contains_point(), SolverUtils::GeoPrim::CFacet::contains_point(), SolverUtils::GeoPrim::CBox::empty(), SolverUtils::GeoPrim::C3Box::empty(), SolverUtils::GeoPrim::CLine::has_point(), SolverUtils::GeoPrim::C3Line::has_point(), SolverUtils::GeoPrim::CPoint::operator==(), SolverUtils::GeoPrim::CVector::operator==(), SolverUtils::GeoPrim::C3Point::operator==(), and SolverUtils::GeoPrim::C3Vector::operator==().