IMPACT: Overlay_primitives.C File Reference
Overlay_primitives.C File Reference
#include "Overlay_primitives.h"
#include <cmath>
#include <algorithm>
#include "HDS_accessor.h"
Functions
RFC_BEGIN_NAME_SPACE void _solve_3x3 (Real a1, Real a2, Real a3, Real b1, Real b2, Real b3, Real c1, Real c2, Real c3, Real d1, Real d2, Real d3, Real &x, Real &y, Real &z)
Variables
HDS_accessor acc
Function Documentation
RFC_BEGIN_NAME_SPACE void _solve_3x3 (Real a1, Real a2, Real a3, Real b1, Real b2, Real b3, Real c1, Real c2, Real c3, Real d1, Real d2, Real d3, Real & x, Real & y, Real & z)
Definition at line 22 of file Overlay_primitives.C.
Referenced by Overlay_primitives::project_blue_feature(), Overlay_primitives::project_green_feature(), and Overlay_primitives::project_onto_element().
 {
   Real denom = b2*c1*a3-b1*c2*a3+c3*b1*a2+b3*c2*a1-c1*b3*a2-b2*c3*a1;
   x = - (b2*c3*d1-b2*c1*d3+c1*b3*d2+b1*c2*d3-c3*b1*d2-b3*c2*d1)/denom;
   z = (b2*d1*a3-b2*a1*d3+b1*a2*d3-b1*d2*a3-d1*b3*a2+a1*b3*d2)/denom;
   y = (a2*c3*d1-a2*c1*d3-c2*d1*a3+c2*a1*d3+d2*c1*a3-d2*c3*a1)/denom;
 }
Variable Documentation
HDS_accessor acc
Definition at line 35 of file Overlay_primitives.C.
Referenced by RFC_Window_overlay::check_false_strong_1(), RFC_Window_overlay::comp_angle_defect(), RFC_Window_overlay::detect_features(), RFC_Window_overlay::evaluate_normals(), RFC_Window_overlay::is_strong_ad(), and RFC_Window_overlay::remove_feature_1().