IMPACT: RFC_Window_base_IO.C File Reference
RFC_Window_base_IO.C File Reference
#include "RFC_Window_base.h"
#include "writer.h"
#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <iostream>
#include <cassert>
#include <sstream>
#include <cstring>
Classes
class Pane_friend
Functions
void SimIN_load_module (const char *)
Load the module Rocin into Roccom using the given module name.
void SimIN_unload_module (const char *)
Unload the module Rocin from Roccom.
void SimOUT_load_module (const char *)
Load the module Rocout into Roccom using the given module name.
void SimOUT_unload_module (const char *)
Unload the module Rocout from Roccom.
Function Documentation
void SimIN_load_module (const char * name)
This module provides three subroutines: "read_windows", "read_by_control_file", and "obtain_dataitem".
Definition at line 3097 of file Rocin.C.
Referenced by RFC_Window_base::read_sdv().
 { Rocin::init( std::string(name)); }
void SimIN_unload_module (const char *)
Definition at line 3100 of file Rocin.C.
Referenced by RFC_Window_base::read_sdv().
 { Rocin::finalize( std::string(name)); }
void SimOUT_load_module (const char * name)
This module provides one subroutine: "write_attribute".
Definition at line 851 of file Rocout.C.
References Rocout::init().
Referenced by COM_F_FUNC2(), and RFC_Window_base::write_sdv().
 { Rocout::init( std::string(name)); }
void SimOUT_unload_module (const char *)
Definition at line 854 of file Rocout.C.
References Rocout::finalize().
Referenced by COM_F_FUNC2(), and RFC_Window_base::write_sdv().
 { Rocout::finalize( std::string(name)); }