IMPACT: rfc_assertions.C File Reference
rfc_assertions.C File Reference
#include <cstdio>
#include <cstdlib>
#include <iostream>
#include <cassert>
#include "commpi.h"
#include "rfc_basic.h"
Functions
RFC_BEGIN_NAME_SPACE void printStackBacktrace ()
static void _standard_error_handler (const char *what, const char *expr, const char *file, int line, const char *msg)
void assertion_fail (const char *expr, const char *file, int line, const char *msg)
Default error handler.
void precondition_fail (const char *expr, const char *file, int line, const char *msg)
Function Documentation
static void _standard_error_handler (const char * what, const char * expr, const char * file, int line, const char * msg) static
Definition at line 38 of file rfc_assertions.C.
Referenced by assertion_fail(), and precondition_fail().
{
   std::cerr << "Rocface error: " << what << " violation!" << std::endl
             << "Expr: " << expr << std::endl
             << "File: " << file << std::endl
             << "Line: " << line << std::endl;
   if ( msg != 0)
     std::cerr << "Explanation:" << msg << std::endl;
 }
void assertion_fail (const char * expr, const char * file, int line, const char * msg)
Definition at line 52 of file rfc_assertions.C.
References _error_behaviour, _standard_error_handler(), COM::ABORT, COMMPI_Initialized(), COM::CONTINUE, COM::EXIT, COM::EXIT_WITH_SUCCESS, and printStackBacktrace().
{
   _standard_error_handler("assertion", expr, file, line, msg);
   printStackBacktrace();
   if (COMMPI_Initialized()) MPI_Abort(MPI_COMM_WORLD,-1); abort();
 }
void precondition_fail (const char * expr, const char * file, int line, const char * msg)
Definition at line 62 of file rfc_assertions.C.
References _standard_error_handler(), COMMPI_Initialized(), and printStackBacktrace().
{
   _standard_error_handler("precondition", expr, file, line, msg);
   printStackBacktrace();
   if (COMMPI_Initialized()) MPI_Abort(MPI_COMM_WORLD,-1); abort();
 }
RFC_BEGIN_NAME_SPACE void printStackBacktrace ()
Definition at line 21 of file rfc_assertions.C.
Referenced by assertion_fail(), and precondition_fail().
{
 #ifdef TRACEBACK
   const int max_stack=64;
   void *stackPtrs[max_stack];
   int levels=backtrace(stackPtrs,max_stack);
   char **symbols=backtrace_symbols(stackPtrs, levels);
   const int nSkip=2;
   std::printf( "\nStack Backtrace:\n");
   for ( int i=nSkip; i<levels; i++) {
     std::printf( " [%d] %s\n", i-nSkip, symbols[i]);
   }
 #endif
 }