IMPACT: Rocblas.C File Reference
Rocblas.C File Reference
Implementation of Rocblas.
#include "Rocblas.h"
Functions
void Simpal_load_module (const char *name)
Calls Rocblas initialization function.
void Simpal_unload_module (const char *name)
void simpal_load_module (const char *name, int length)
void simpal_unload_module (const char *name, int length)
void simpal_load_module_ (const char *name, int length)
void simpal_unload_module_ (const char *name, int length)
void SIMPAL_LOAD_MODULE (const char *name, int length)
void SIMPAL_UNLOAD_MODULE (const char *name, int length)
void SIMPAL_LOAD_MODULE_ (const char *name, int length)
void SIMPAL_UNLOAD_MODULE_ (const char *name, int length)
Function Documentation
void Simpal_load_module (const char * name)
Definition at line 96 of file Rocblas.C.
References Rocblas::init().
Referenced by main().
{
   Rocblas::init(std::string(name));
 }
void simpal_load_module (const char * name, int length)
Definition at line 106 of file Rocblas.C.
References Rocblas::init().
 { Rocblas::init( std::string(name, length)); }
void SIMPAL_LOAD_MODULE (const char * name, int length)
Definition at line 116 of file Rocblas.C.
References Rocblas::init().
 { Rocblas::init( std::string(name, length)); }
void simpal_load_module_ (const char * name, int length)
Definition at line 111 of file Rocblas.C.
References Rocblas::init().
 { Rocblas::init( std::string(name, length)); }
void SIMPAL_LOAD_MODULE_ (const char * name, int length)
Definition at line 121 of file Rocblas.C.
References Rocblas::init().
 { Rocblas::init( std::string(name, length)); }
void Simpal_unload_module (const char * name)
Definition at line 99 of file Rocblas.C.
References Rocblas::finalize().
Referenced by main().
{
   Rocblas::finalize(std::string(name));
 }
void simpal_unload_module (const char * name, int length)
Definition at line 108 of file Rocblas.C.
References Rocblas::finalize().
 { Rocblas::finalize( std::string(name, length)); }
void SIMPAL_UNLOAD_MODULE (const char * name, int length)
Definition at line 118 of file Rocblas.C.
References Rocblas::finalize().
 { Rocblas::finalize( std::string(name, length)); }
void simpal_unload_module_ (const char * name, int length)
Definition at line 113 of file Rocblas.C.
References Rocblas::finalize().
 { Rocblas::finalize( std::string(name, length)); }
void SIMPAL_UNLOAD_MODULE_ (const char * name, int length)
Definition at line 123 of file Rocblas.C.
References Rocblas::finalize().
 { Rocblas::finalize( std::string(name, length)); }