IMPACT: Rocblas.h File Reference
Rocblas.h File Reference
Definition for Rocblas API.
#include <cstdio>
#include "com.h"
#include "com_devel.hpp"
Classes
class Rocblas
struct Rocblas::assn< T_src, T_trg >
struct Rocblas::random< T >
struct Rocblas::swapp< T >
struct Rocblas::maxv< T >
struct Rocblas::minv< T >
struct Rocblas::sumv< T >
struct Rocblas::nega< T >
struct Rocblas::sqrta< T >
struct Rocblas::acosa< T >
struct Rocblas::limit1v< T >
struct Rocblas::maxof< T >
Functions
void Simpal_load_module (const char *name)
Calls Rocblas initialization function.
void Simpal_unload_module (const char *name)
Function Documentation
void Simpal_load_module (const char * name)
Definition at line 96 of file Rocblas.C.
References Rocblas::init().
Referenced by main().
{
   Rocblas::init(std::string(name));
 }
void Simpal_unload_module (const char * name)
Definition at line 99 of file Rocblas.C.
References Rocblas::finalize().
Referenced by main().
{
   Rocblas::finalize(std::string(name));
 }