IMPACT: Rocin.h File Reference
Rocin.h File Reference
Rocin creates a series of Roccom windows by reading in a list of files.
Detailed Description
Rocin can also copy Roccom dataitems from window to window. Only HDF4 files are supported in the current implementation.
Definition in file Rocin.h.
#include "com.h"
#include "HDF4.h"
#include "rocin_block.h"
#include "com_devel.hpp"
Classes
class Rocin
Functions
Module loading and unloading
void SimIN_load_module (const char *name)
Load the module Rocin into Roccom using the given module name.
void SimIN_unload_module (const char *name)
Unload the module Rocin from Roccom.
Function Documentation
void SimIN_load_module (const char * name)
This module provides three subroutines: "read_windows", "read_by_control_file", and "obtain_dataitem".
Definition at line 3098 of file Rocin.C.
Referenced by COM_F_FUNC2(), main(), read_pane_sp(), and RFC_Window_base::read_sdv().
 { Rocin::init( std::string(name)); }
void SimIN_unload_module (const char * name)
Definition at line 3101 of file Rocin.C.
Referenced by COM_F_FUNC2(), read_pane_sp(), and RFC_Window_base::read_sdv().
 { Rocin::finalize( std::string(name)); }