IMPACT: Rocmap.C File Reference
Rocmap.C File Reference
#include "Rocmap.h"
#include "com.h"
#include "Pane_connectivity.h"
#include "Pane_communicator.h"
#include "Pane_boundary.h"
Functions
void SurfMap_load_module (const char *mname)
void SurfMap_unload_module (const char *mname)
void surfmap_load_module (const char *mname, long int length)
void surfmap_unload_module (const char *mname, long int length)
void SURFMAP_LOAD_MODULE (const char *mname, long int length)
void SURFMAP_UNLOAD_MODULE (const char *mname, long int length)
void surfmap_load_module_ (const char *mname, long int length)
void surfmap_unload_module_ (const char *mname, long int length)
void SURFMAP_LOAD_MODULE_ (const char *mname, long int length)
void SURFMAP_UNLOAD_MODULE_ (const char *mname, long int length)
Function Documentation
void SurfMap_load_module (const char * mname)
Definition at line 123 of file Rocmap.C.
References Rocmap::load().
 { Rocmap::load( mname); }
void surfmap_load_module (const char * mname, long int length)
Definition at line 131 of file Rocmap.C.
References Rocmap::load().
 { Rocmap::load( std::string(mname, length)); }
void SURFMAP_LOAD_MODULE (const char * mname, long int length)
Definition at line 137 of file Rocmap.C.
References Rocmap::load().
 { Rocmap::load( std::string(mname, length)); }
void surfmap_load_module_ (const char * mname, long int length)
Definition at line 143 of file Rocmap.C.
References Rocmap::load().
 { Rocmap::load( std::string(mname, length)); }
void SURFMAP_LOAD_MODULE_ (const char * mname, long int length)
Definition at line 149 of file Rocmap.C.
References Rocmap::load().
 { Rocmap::load( std::string(mname, length)); }
void SurfMap_unload_module (const char * mname)
Definition at line 126 of file Rocmap.C.
References Rocmap::unload().
 { Rocmap::unload( mname); }
void surfmap_unload_module (const char * mname, long int length)
Definition at line 134 of file Rocmap.C.
References Rocmap::unload().
 { Rocmap::unload( std::string(mname, length)); }
void SURFMAP_UNLOAD_MODULE (const char * mname, long int length)
Definition at line 140 of file Rocmap.C.
References Rocmap::unload().
 { Rocmap::unload( std::string(mname, length)); }
void surfmap_unload_module_ (const char * mname, long int length)
Definition at line 146 of file Rocmap.C.
References Rocmap::unload().
 { Rocmap::unload( std::string(mname, length)); }
void SURFMAP_UNLOAD_MODULE_ (const char * mname, long int length)
Definition at line 152 of file Rocmap.C.
References Rocmap::unload().
 { Rocmap::unload( std::string(mname, length)); }