IMPACT: Rocout_hdf4.h File Reference
Rocout_hdf4.h File Reference
#include "com.h"
#include <string>
Functions
void write_dataitem_HDF4 (const std::string &fname, const std::string &mfile, const COM::DataItem *attr, const char *material, const char *timelevel, int pane_id, const std::string &errorhandle, int mode)
Function Documentation
void write_dataitem_HDF4 (const std::string & fname, const std::string & mfile, const COM::DataItem * attr, const char * material, const char * timelevel, int pane_id, const std::string & errorhandle, int mode)
Definition at line 108 of file Rocout_hdf4.C.
References COM_assertion, io_pane(), and ComponentInterface::pane().
Referenced by Rocout::write_dataitem_internal().
 {
   const Window* w = attr->window();
   COM_assertion(w != NULL);
   const Pane& pn = w->pane(pane_id);
   io_pane(fname.c_str(), &pn, attr, material, timelevel,
           !mfile.empty() ? mfile.c_str() : NULL, errorhandle, mode);
 }