IMPACT: Rocsurf.C File Reference
Rocsurf.C File Reference
#include "Rocsurf.h"
#include "com.h"
#include "Manifold_2.h"
Functions
void SurfUtil_load_module (const char *mname)
void SurfUtil_unload_module (const char *mname)
void surfutil_load_module (const char *mname, long int length)
void surfutil_unload_module (const char *mname, long int length)
void SURFUTIL_LOAD_MODULE (const char *mname, long int length)
void SURFUTIL_UNLOAD_MODULE (const char *mname, long int length)
void surfutil_load_module_ (const char *mname, long int length)
void surfutil_unload_module_ (const char *mname, long int length)
void SURFUTIL_LOAD_MODULE_ (const char *mname, long int length)
void SURFUTIL_UNLOAD_MODULE_ (const char *mname, long int length)
Function Documentation
void SurfUtil_load_module (const char * mname)
Definition at line 214 of file Rocsurf.C.
References Rocsurf::load().
 { Rocsurf::load( mname); }
void surfutil_load_module (const char * mname, long int length)
Definition at line 222 of file Rocsurf.C.
References Rocsurf::load().
 { Rocsurf::load( std::string(mname, length)); }
void SURFUTIL_LOAD_MODULE (const char * mname, long int length)
Definition at line 228 of file Rocsurf.C.
References Rocsurf::load().
 { Rocsurf::load( std::string(mname, length)); }
void surfutil_load_module_ (const char * mname, long int length)
Definition at line 234 of file Rocsurf.C.
References Rocsurf::load().
 { Rocsurf::load( std::string(mname, length)); }
void SURFUTIL_LOAD_MODULE_ (const char * mname, long int length)
Definition at line 240 of file Rocsurf.C.
References Rocsurf::load().
 { Rocsurf::load( std::string(mname, length)); }
void SurfUtil_unload_module (const char * mname)
Definition at line 217 of file Rocsurf.C.
References Rocsurf::unload().
 { Rocsurf::unload( mname); }
void surfutil_unload_module (const char * mname, long int length)
Definition at line 225 of file Rocsurf.C.
References Rocsurf::unload().
 { Rocsurf::unload( std::string(mname, length)); }
void SURFUTIL_UNLOAD_MODULE (const char * mname, long int length)
Definition at line 231 of file Rocsurf.C.
References Rocsurf::unload().
 { Rocsurf::unload( std::string(mname, length)); }
void surfutil_unload_module_ (const char * mname, long int length)
Definition at line 237 of file Rocsurf.C.
References Rocsurf::unload().
 { Rocsurf::unload( std::string(mname, length)); }
void SURFUTIL_UNLOAD_MODULE_ (const char * mname, long int length)
Definition at line 243 of file Rocsurf.C.
References Rocsurf::unload().
 { Rocsurf::unload( std::string(mname, length)); }