IMPACT: Scheduler::ActionItem Struct Reference
Scheduler::ActionItem Struct Reference
Detailed Description
Definition at line 42 of file Scheduler.h.
#include <Scheduler.h>
Public Member Functions
ActionItem (Action *a)
unsigned int n_write ()
unsigned int n_read ()
const char * name ()
Action * action ()
int fullfilled ()
int hasInput (const char *attr, int idx)
int hasOutput (const char *attr, int idx)
void print (FILE *f)
Public Attributes
Action * myaction
vector< const char * > read_attr
vector< int > read_idx
vector< const char * > write_attr
vector< int > write_idx
ActionList input
ActionList output
int print_flag
Constructor & Destructor Documentation
Scheduler::ActionItem::ActionItem (Action * a) inline
Definition at line 52 of file Scheduler.h.
 : myaction(a) {}
Member Function Documentation
Action* Scheduler::ActionItem::action () inline
Definition at line 56 of file Scheduler.h.
Referenced by Scheduler::finalize_actions(), Scheduler::init_actions(), Scheduler::print_helper(), Scheduler::run_actions(), and Scheduler::topological_sort().
 { return myaction; }
int Scheduler::ActionItem::fullfilled ()
Definition at line 350 of file Scheduler.C.
References n_write(), and output.
 {
   for (unsigned int i=0; i<n_write(); i++)
     if (output[i] == NULL) return 0;
   return 1;
 }
int Scheduler::ActionItem::hasInput (const char * attr, int idx)
Definition at line 357 of file Scheduler.C.
 {
   for (unsigned int i=0; i<n_read(); i++)
     if (strcasecmp(attr, read_attr[i]) == 0 && idx == read_idx[i]) return i;
   return -1;
 }
int Scheduler::ActionItem::hasOutput (const char * attr, int idx)
Definition at line 364 of file Scheduler.C.
Referenced by Scheduler::buildDDG().
 {
   for (unsigned int i=0; i<n_write(); i++)
     if (strcasecmp(attr, write_attr[i]) == 0 && idx == write_idx[i]) return i;
   return -1;
 }
unsigned int Scheduler::ActionItem::n_read () inline
Definition at line 54 of file Scheduler.h.
Referenced by Scheduler::buildDDG(), Scheduler::print_helper(), and Scheduler::sanityCheck().
 { return read_attr.size(); }
unsigned int Scheduler::ActionItem::n_write () inline
Definition at line 53 of file Scheduler.h.
Referenced by fullfilled(), Scheduler::print_helper(), and Scheduler::sanityCheck().
 { return write_attr.size(); }
const char* Scheduler::ActionItem::name () inline
Definition at line 55 of file Scheduler.h.
Referenced by Scheduler::print_helper().
 { return myaction->name(); }
void Scheduler::ActionItem::print (FILE * f)
Definition at line 372 of file Scheduler.C.
References Scheduler::name().
 {
   unsigned int i;
   fprintf(f, "=========== Action %s =============\n", name());
   for (i=0; i<n_read(); i++)
     printf("reads: %s %d \n", read_attr[i], read_idx[i]);
   for (i=0; i<n_write(); i++)
     printf("writes: %s %d \n", write_attr[i], write_idx[i]);
 }
Member Data Documentation
ActionList Scheduler::ActionItem::input
Definition at line 48 of file Scheduler.h.
Referenced by Scheduler::buildDDG(), Scheduler::print_helper(), Scheduler::sanityCheck(), and Scheduler::topological_sort().
Action* Scheduler::ActionItem::myaction
Definition at line 43 of file Scheduler.h.
ActionList Scheduler::ActionItem::output
Definition at line 49 of file Scheduler.h.
Referenced by Scheduler::buildDDG(), fullfilled(), Scheduler::print_helper(), and Scheduler::sanityCheck().
int Scheduler::ActionItem::print_flag
Definition at line 50 of file Scheduler.h.
Referenced by Scheduler::print_helper().
vector<const char *> Scheduler::ActionItem::read_attr
Definition at line 44 of file Scheduler.h.
Referenced by Scheduler::buildDDG(), and Scheduler::print_helper().
vector<int> Scheduler::ActionItem::read_idx
Definition at line 45 of file Scheduler.h.
Referenced by Scheduler::buildDDG(), and Scheduler::print_helper().
vector<const char *> Scheduler::ActionItem::write_attr
Definition at line 46 of file Scheduler.h.
vector<int> Scheduler::ActionItem::write_idx
Definition at line 47 of file Scheduler.h.
The documentation for this struct was generated from the following files:
Scheduler.h
Scheduler.C