IMPACT: Tuple_traits< T > Struct Template Reference
Tuple_traits< T > Struct Template Reference
Detailed Description
template<class T>
struct Tuple_traits< T >
Definition at line 11 of file Tuple.h.
#include <Tuple.h>
Public Types
typedef T Value
typedef const T Value_opposite
typedef T * Pointer
typedef const T * Const_pointer
typedef T & Reference
typedef const T & Init_reference
typedef const T & Const_reference
typedef T * Pointer_equivalent
Static Public Member Functions
static Reference ref (Pointer_equivalent p)
Member Typedef Documentation
template<class T > typedef const T* Tuple_traits< T >::Const_pointer
Definition at line 15 of file Tuple.h.
template<class T > typedef const T& Tuple_traits< T >::Const_reference
Definition at line 18 of file Tuple.h.
template<class T > typedef const T& Tuple_traits< T >::Init_reference
Definition at line 17 of file Tuple.h.
template<class T > typedef T* Tuple_traits< T >::Pointer
Definition at line 14 of file Tuple.h.
template<class T > typedef T* Tuple_traits< T >::Pointer_equivalent
Definition at line 19 of file Tuple.h.
template<class T > typedef T& Tuple_traits< T >::Reference
Definition at line 16 of file Tuple.h.
template<class T > typedef T Tuple_traits< T >::Value
Definition at line 12 of file Tuple.h.
template<class T > typedef const T Tuple_traits< T >::Value_opposite
Definition at line 13 of file Tuple.h.
Member Function Documentation
template<class T > static Reference Tuple_traits< T >::ref (Pointer_equivalent p) inline static
Definition at line 20 of file Tuple.h.
Referenced by Two_tuple< T >::operator[](), Three_tuple< int >::operator[](), and Four_tuple< T >::operator[]().
 { return *p; }
The documentation for this struct was generated from the following file:
Tuple.h