IMPACT: Host_face Struct Reference
Host_face Struct Reference
Detailed Description
Definition at line 172 of file HDS_overlay.h.
#include <HDS_overlay.h>
Public Member Functions
Host_face ()
Host_face (HEdge h, Parent_type t)
HEdge halfedge () const
Parent_type parent_type () const
bool operator== (const Host_face &h) const
bool operator!= (const Host_face &h) const
Private Attributes
HEdge _h
Parent_type _t
Constructor & Destructor Documentation
Host_face::Host_face () inline
Definition at line 173 of file HDS_overlay.h.
 : _h(), _t( PARENT_NONE) {};
Host_face::Host_face (HEdge h, Parent_type t) inline
Definition at line 174 of file HDS_overlay.h.
 : _h( h), _t(t) {}
Member Function Documentation
HEdge Host_face::halfedge () const inline
Definition at line 176 of file HDS_overlay.h.
References _h.
Referenced by Overlay::get_edge_pair_parents(), Overlay::get_next_inode(), Overlay::get_next_inode_ccw(), Overlay::get_next_inode_cw(), and INode::halfedge().
 { return _h; }
bool Host_face::operator!= (const Host_face & h) const inline
Definition at line 180 of file HDS_overlay.h.
References _h, and _t.
   { return _h!=h._h || _t!=h._t; }
bool Host_face::operator== (const Host_face & h) const inline
Definition at line 178 of file HDS_overlay.h.
References _h, and _t.
   { return _h==h._h && _t==h._t; }
Parent_type Host_face::parent_type () const inline
Definition at line 177 of file HDS_overlay.h.
References _t.
Referenced by INode::blue_parent_type(), Overlay::get_edge_pair_parents(), Overlay::get_next_inode(), Overlay::get_next_inode_ccw(), Overlay::get_next_inode_cw(), INode::green_parent_type(), and INode::parent_type().
 { return _t; }
Member Data Documentation
HEdge Host_face::_h private
Definition at line 184 of file HDS_overlay.h.
Referenced by halfedge(), operator!=(), and operator==().
Parent_type Host_face::_t private
Definition at line 185 of file HDS_overlay.h.
Referenced by operator!=(), operator==(), and parent_type().
The documentation for this struct was generated from the following file:
HDS_overlay.h