IMPACT: surfmap.C File Reference
surfmap.C File Reference
#include "com.h"
#include <iostream>
#include "IM_Reader.h"
Functions
COM_EXTERN_MODULE (SimIN)
COM_EXTERN_MODULE (SimOUT)
COM_EXTERN_MODULE (SurfMap)
COM_EXTERN_MODULE (SurfUtil)
int main (int argc, char *argv[])
Function Documentation
COM_EXTERN_MODULE (SimIN)
COM_EXTERN_MODULE (SimOUT)
COM_EXTERN_MODULE (SurfMap)
COM_EXTERN_MODULE (SurfUtil)
int main (int argc, char * argv[])
Definition at line 19 of file surfmap.C.
References COM_assertion, COM_assertion_msg, COM_call_function(), COM_DOUBLE, COM_finalize(), COM_get_dataitem_handle(), COM_get_function_handle(), COM_init(), COM_LOAD_MODULE_STATIC_DYNAMIC, COM_new_dataitem(), COM_resize_array(), COM_window_init_done(), and IM_Reader::read_winmesh().
{
   COM_init( &argc, &argv);
   if ( argc < 3) {
     std::cout << "Usage:\n\tTo run in serial: " << argv[0]
               << " <surffile> <hdffile> " << endl;
     std::cout << "\n\tTo run in parallel: <mpirun-command> " << argv[0]
               << " -com-mpi <Rocin control file> <hdfoutput-prefix> " << endl;
     exit(-1);
   }
   std::cout << "Reading surface mesh file \"" << argv[1] << '"' << endl;
   std::string fname(argv[1]), wname;
   string::size_type n0 = fname.find_last_of( "/");
   if ( n0 != std::string::npos)
     fname = fname.substr( n0+1, fname.size());
   string::size_type ni;
   ni = fname.find_first_of( ".:-*[]?\\\"\'0123456789");
   COM_assertion_msg(ni, "File name must start with a letter");
   if ( ni == std::string::npos) {
     wname = fname;
   }
   else {
     while (fname[ni-1]=='_') --ni; // Remove the '_' at the end.
     wname = fname.substr( 0, ni);
   }
   std::cout << "Creating window \"" << wname << '"' << endl;
   // Read in IM/HDF format
   int err = IM_Reader().read_winmesh( argv[1], wname);
   COM_assertion( err>=0);
   std::cout << "finishing up window initialization" << endl;
   COM_new_dataitem((wname+".normals").c_str(), 'e', COM_DOUBLE, 3, "");
   COM_resize_array((wname+".normals").c_str());
   COM_window_init_done( wname.c_str());
   std::cout << "loading Rocout" << endl;
   COM_LOAD_MODULE_STATIC_DYNAMIC(SimOUT, "OUT");
   std::cout << "Computing pane connectivity... " << endl;
   COM_LOAD_MODULE_STATIC_DYNAMIC(SurfMap, "MAP");
   // Invoke compute_pconn to obtain pane connectivity.
   int MAP_compute_pconn = COM_get_function_handle( "MAP.compute_pconn");
   const string pconn = wname+".pconn";
   int mesh_hdl = COM_get_dataitem_handle((wname+".mesh").c_str());
   int pconn_hdl = COM_get_dataitem_handle( pconn.c_str());
   COM_call_function( MAP_compute_pconn, &mesh_hdl, &pconn_hdl);
   std::cout << "Computing face normals... " << endl;
   COM_LOAD_MODULE_STATIC_DYNAMIC(SurfUtil, "SURF");
   int SURF_normal = COM_get_function_handle( "SURF.compute_element_normals");
   int nrmls_hdl = COM_get_dataitem_handle( (wname+".normals").c_str());
   COM_call_function( SURF_normal, &nrmls_hdl);
   std::cout << "Output window into file..." << endl;
   // Output pconn
   int OUT_set = COM_get_function_handle( "OUT.set_option");
   int OUT_write = COM_get_function_handle( "OUT.write_dataitem");
   COM_call_function( OUT_set, "mode", "w");
   int all_hdl = COM_get_dataitem_handle( (wname+".all").c_str());
   COM_call_function( OUT_write, argv[2], &all_hdl,
                      (char*)wname.c_str(), "000");
   COM_finalize();
 }