IMPACT: TestModule.f90 File Reference
TestModule.f90 File Reference
IMPACT-specific documentation group
F90 Test Module.
Detailed Description
Author
JEK
Date
May 1, 2014
This F90 test module serves as both a test and a simple example for implementing a COM module in Fortran.
Definition in file TestModule.f90.
Functions/Subroutines
subroutine testroutine0 (global, outstring)
subroutine testroutine1 (global, name)
subroutine testroutine2 (global, name)
subroutine testroutine3 (global, name)
subroutine testroutine4 (global, outstring)
subroutine intfunction (io_data)
subroutine constintfunction (idata, string_data)
subroutine comftestmod_load_module (name)
subroutine comftestmod_unload_module (name)
Function/Subroutine Documentation
subroutine comftestmod_load_module (character(*), intent(in) name)
Definition at line 149 of file TestModule.f90.
References testobject::associate_pointer(), constintfunction(), intfunction(), ComponentInterface::name(), testroutine0(), testroutine1(), testroutine2(), testroutine3(), and testroutine4().
subroutine comftestmod_unload_module (character(*), intent(in) name)
Definition at line 255 of file TestModule.f90.
References testobject::associate_pointer(), and ComponentInterface::name().
subroutine constintfunction (integer, intent(inout) idata, character*(*), intent(inout) string_data)
Definition at line 134 of file TestModule.f90.
Referenced by comftestmod_load_module().
subroutine intfunction (integer, intent(inout) io_data)
Definition at line 120 of file TestModule.f90.
Referenced by comftestmod_load_module().
subroutine testroutine0 (type(t_global), pointer global, character(80), intent(out) outstring)
Definition at line 11 of file TestModule.f90.
Referenced by comftestmod_load_module().
subroutine testroutine1 (type(t_global), pointer global, character(*), intent(in) name)
Definition at line 30 of file TestModule.f90.
References ComponentInterface::name().
Referenced by comftestmod_load_module().
subroutine testroutine2 (type(t_global), pointer global, character(80), intent(out) name)
Definition at line 50 of file TestModule.f90.
References ComponentInterface::name().
Referenced by comftestmod_load_module().
subroutine testroutine3 (type(t_global), pointer global, character(*), intent(in) name)
Definition at line 76 of file TestModule.f90.
References ComponentInterface::name().
Referenced by comftestmod_load_module().
subroutine testroutine4 (type(t_global), pointer global, character(80), intent(out) outstring)
Definition at line 96 of file TestModule.f90.
Referenced by comftestmod_load_module().