IMPACT: Triangulation.C File Reference
Triangulation.C File Reference
#include "Triangulation.h"
Functions
bool leftturn (const Point_2 &p, const Point_2 &q, const Point_2 &r)
bool rightturn (const Point_2 &p, const Point_2 &q, const Point_2 &r)
bool do_intersect_intervals (double iv1[2], double iv2[2])
static bool do_intersect (const Point_2 &p1, const Point_2 &p2, const Point_2 &q1, const Point_2 &q2)
Variables
USE_RFC_NAME_SPACE
Function Documentation
static bool do_intersect (const Point_2 & p1, const Point_2 & p2, const Point_2 & q1, const Point_2 & q2) static
Definition at line 45 of file Triangulation.C.
References do_intersect_intervals().
Referenced by Overlay::intersect_link_helper(), and Triangulation::is_diagonalie().
{
   Real   u1[2], v21[2], v22[2], u2[2], v11[2];
   Real   a11, a12, a21, a22, sqn1;
   Real   v12[2], uref[2];
   Real   sqn2;
   static Real dtemp_2[2] = {0.0, 1.0};
   int i;
    /* Compute the signed areas a11, a12, a21, and a22.  */
   u1[0] =  p2[0] -  p1[0];
   u1[1] =  p2[1] -  p1[1];
   v21[0] =  q1[0] -  p1[0];
   v21[1] =  q1[1] -  p1[1];
   v22[0] =  q2[0] -  p1[0];
   v22[1] =  q2[1] -  p1[1];
   a11 = -u1[1] *  v21[0];
   a11 = a11 +  u1[0] *  v21[1];
   a12 = -u1[1] *  v22[0];
   a12 = a12 +  u1[0] *  v22[1];
   u2[0] =  q2[0] -  q1[0];
   u2[1] =  q2[1] -  q1[1];
   v11[0] =  p1[0] -  q1[0];
   v11[1] =  p1[1] -  q1[1];
   v12[0] =  p2[0] -  q1[0];
   v12[1] =  p2[1] -  q1[1];
   a21 = -u2[1] *  v11[0];
   a21 = a21 +  u2[0] *  v11[1];
   a22 = - u2[1] *  v12[0];
   a22 = a22 +  u2[0] *  v12[1];
   if (a11 == 0.0 && a12 == 0.0) {
     /* Two line segments are colinear. Use intersect_intervals. */
     sqn1 = 0.0;
     sqn2 = 0.0;
     for (i=0; i<=1; i+=1) {
       sqn1 = sqn1 +  u1[i] *  u1[i];
       sqn2 = sqn2 +  u2[i] *  u2[i];
     }
     if (sqn1 > sqn2) {
       uref[0] =  u1[0] / sqn1;
       uref[1] =  u1[1] / sqn1;
       Real dtemp_0[2];
       dtemp_0[0] =  v21[0] *  uref[0] +  v21[1] *  uref[1];
       dtemp_0[1] =  v22[0] *  uref[0] +  v22[1] *  uref[1];
       return do_intersect_intervals(dtemp_2, dtemp_0);
     }
     else if (sqn2 > 0.0) {
       uref[0] =  u2[0] / sqn2;
       uref[1] =  u2[1] / sqn2;
       Real dtemp_1[2];
       dtemp_1[0] =  v11[0] *  uref[0] +  v11[1] *  uref[1];
       dtemp_1[1] =  v12[0] *  uref[0] +  v12[1] *  uref[1];
       return do_intersect_intervals(dtemp_1, dtemp_2);
     }
     else {
       for (i=0; i<=1; i+=2) {
         if ( p1[i] !=  q1[i] || p1[1 + i] !=  q1[1 + i])
           return false;
       }
       return true;
     }
   }
   else if (a12 <= 0.0 && a11 >= 0.0 || a12 >= 0.0 && a11 <= 0.0) {
     return a22 <= 0.0 && a21 >= 0.0 || a22 >= 0.0 && a21 <= 0.0;
   }
   else {
     return false;
   }
 }
bool do_intersect_intervals (double iv1[2], double iv2[2]) inline
Definition at line 29 of file Triangulation.C.
Referenced by do_intersect().
{
   int i2min = ( iv2[1] <  iv2[0]) + 1;
   if ( iv1[1] >  iv1[0]) {
     return ( iv1[0] >=  iv2[i2min - 1]) && ( iv1[0] <=  iv2[2 - i2min]) ||
       ( iv2[i2min - 1] <=  iv1[1]) && ( iv2[i2min - 1] >= iv1[0]) ||
       ( iv2[2 - i2min] <=  iv1[1]) && ( iv2[2 - i2min] >= iv1[0]) ||
       ( iv1[1] >=  iv2[i2min - 1]) && ( iv1[1] <=  iv2[2 - i2min]);
   }
   else {
     return ( iv2[2 - i2min] >=  iv1[1]) && ( iv2[2 - i2min] <= iv1[0])||
       ( iv2[i2min - 1] >=  iv1[1]) && ( iv2[i2min - 1] <= iv1[0]) ||
       ( iv1[1] >= iv2[i2min - 1]) &&( iv1[1] <=  iv2[2 - i2min]);
   }
 }
bool leftturn (const Point_2 & p, const Point_2 & q, const Point_2 & r) inline
Definition at line 19 of file Triangulation.C.
References Vector_2< Type >::x(), and Vector_2< Type >::y().
Referenced by Triangulation::in_cone().
{
   Real det = (p.x()-r.x()) * (q.y()-r.y()) - (q.x()-r.x()) *(p.y()-r.y());
   return det > 0;
 }
bool rightturn (const Point_2 & p, const Point_2 & q, const Point_2 & r) inline
Definition at line 24 of file Triangulation.C.
References Vector_2< Type >::x(), and Vector_2< Type >::y().
Referenced by Triangulation::in_cone().
{
   Real det = (p.x()-r.x()) * (q.y()-r.y()) - (q.x()-r.x()) *(p.y()-r.y());
   return det < 0;
 }
Variable Documentation
USE_RFC_NAME_SPACE
Definition at line 17 of file Triangulation.C.