IMPACT: utilities.f90 File Reference
utilities.f90 File Reference
Some F90 routines for handling LOGICAL variables and F90 pointers.
Detailed Description
See also
comf90.h, utilities.f90, mapptr.h
Definition in file utilities.f90.
Functions/Subroutines
subroutine com_set_true (i)
subroutine com_set_false (i)
subroutine com_copy_string (str_frm, len_frm, str_to, len_to)
subroutine com_mapptr_chr1d (p, tonull, x, n)
subroutine com_mapptr_int0d (p, tonull, x)
subroutine com_mapptr_int1d (p, tonull, x, n)
subroutine com_mapptr_int2d (p, tonull, x, n1, n2)
subroutine com_mapptr_int3d (p, tonull, x, n1, n2, n3)
subroutine com_mapptr_flt0d (p, tonull, x)
subroutine com_mapptr_flt1d (p, tonull, x, n)
subroutine com_mapptr_flt2d (p, tonull, x, n1, n2)
subroutine com_mapptr_flt3d (p, tonull, x, n1, n2, n3)
subroutine com_mapptr_dbl0d (p, tonull, x)
subroutine com_mapptr_dbl1d (p, tonull, x, n)
subroutine com_mapptr_dbl2d (p, tonull, x, n1, n2)
subroutine com_mapptr_dbl3d (p, tonull, x, n1, n2, n3)
subroutine com_getptr_chr0d (p, x)
subroutine com_getptr_chr1d (p, x)
subroutine com_getptr_int0d (p, x)
subroutine com_getptr_int1d (p, x)
subroutine com_getptr_int2d (p, x)
subroutine com_getptr_int3d (p, x)
subroutine com_getptr_flt0d (p, x)
subroutine com_getptr_flt1d (p, x)
subroutine com_getptr_flt2d (p, x)
subroutine com_getptr_flt3d (p, x)
subroutine com_getptr_dbl0d (p, x)
subroutine com_getptr_dbl1d (p, x)
subroutine com_getptr_dbl2d (p, x)
subroutine com_getptr_dbl3d (p, x)
subroutine com_settypeinfo (wrapper)
subroutine com_chkptr_begin
subroutine com_chkptr_end (str1, ptr1, str2, ptr2)
Function/Subroutine Documentation
subroutine com_chkptr_begin ()
Definition at line 493 of file utilities.f90.
Referenced by COM_F_FUNC2().
subroutine com_chkptr_end (character(17), intent(in) str1, integer, dimension(:), pointer ptr1, character(33), intent(in) str2, real, dimension(:), pointer ptr2)
Definition at line 515 of file utilities.f90.
Referenced by COM_F_FUNC2().
subroutine com_copy_string (character(len_frm), intent(in) str_frm, integer, intent(in) len_frm, character(len_to), intent(out) str_to, integer, intent(in) len_to)
Definition at line 18 of file utilities.f90.
References str_to.
Referenced by COM_F_FUNC2().
subroutine com_getptr_chr0d (character, pointer p, character, target x)
Definition at line 258 of file utilities.f90.
References SolverUtils::GeoPrim::CPoint::x().
subroutine com_getptr_chr1d (character, dimension(:), pointer p, character, target x)
Definition at line 278 of file utilities.f90.
References SolverUtils::GeoPrim::CPoint::x().
Referenced by COM_F_FUNC2().
subroutine com_getptr_dbl0d (double precision, pointer p, double precision, target x)
Definition at line 410 of file utilities.f90.
References SolverUtils::GeoPrim::CPoint::x().
Referenced by com_get_address_f().
subroutine com_getptr_dbl1d (double precision, dimension(:), pointer p, double precision, target x)
Definition at line 424 of file utilities.f90.
References SolverUtils::GeoPrim::CPoint::x().
Referenced by com_get_address_f().
subroutine com_getptr_dbl2d (double precision, dimension(:,:), pointer p, double precision, target x)
Definition at line 438 of file utilities.f90.
References SolverUtils::GeoPrim::CPoint::x().
Referenced by com_get_address_f().
subroutine com_getptr_dbl3d (double precision, dimension(:,:,:), pointer p, double precision, target x)
Definition at line 452 of file utilities.f90.
References SolverUtils::GeoPrim::CPoint::x().
Referenced by com_get_address_f().
subroutine com_getptr_flt0d (real, pointer p, real, target x)
Definition at line 354 of file utilities.f90.
References SolverUtils::GeoPrim::CPoint::x().
Referenced by com_get_address_f().
subroutine com_getptr_flt1d (real, dimension(:), pointer p, real, target x)
Definition at line 368 of file utilities.f90.
References SolverUtils::GeoPrim::CPoint::x().
Referenced by com_get_address_f().
subroutine com_getptr_flt2d (real, dimension(:,:), pointer p, real, target x)
Definition at line 382 of file utilities.f90.
References SolverUtils::GeoPrim::CPoint::x().
Referenced by com_get_address_f().
subroutine com_getptr_flt3d (real, dimension(:,:,:), pointer p, real, target x)
Definition at line 396 of file utilities.f90.
References SolverUtils::GeoPrim::CPoint::x().
Referenced by com_get_address_f().
subroutine com_getptr_int0d (integer, pointer p, integer, target x)
Definition at line 292 of file utilities.f90.
References SolverUtils::GeoPrim::CPoint::x().
Referenced by com_get_address_f().
subroutine com_getptr_int1d (integer, dimension(:), pointer p, integer, target x)
Definition at line 312 of file utilities.f90.
References SolverUtils::GeoPrim::CPoint::x().
Referenced by COM_F_FUNC2(), and com_get_address_f().
subroutine com_getptr_int2d (integer, dimension(:,:), pointer p, integer, target x)
Definition at line 326 of file utilities.f90.
References SolverUtils::GeoPrim::CPoint::x().
Referenced by com_get_address_f().
subroutine com_getptr_int3d (integer, dimension(:,:,:), pointer p, integer, target x)
Definition at line 340 of file utilities.f90.
References SolverUtils::GeoPrim::CPoint::x().
Referenced by com_get_address_f().
subroutine com_mapptr_chr1d (character, dimension(:), pointer p, integer, intent(in) tonull, character, dimension(n), target x, integer, intent(in) n)
Definition at line 27 of file utilities.f90.
References SolverUtils::GeoPrim::CPoint::x().
Referenced by COM_F_FUNC2(), and mapcharptr().
subroutine com_mapptr_dbl0d (double precision, pointer p, integer, intent(in) tonull, double precision, target x)
Definition at line 185 of file utilities.f90.
References SolverUtils::GeoPrim::CPoint::x().
Referenced by com_set_address_f().
subroutine com_mapptr_dbl1d (double precision, dimension(:), pointer p, integer, intent(in) tonull, double precision, dimension(n), target x, integer, intent(in) n)
Definition at line 207 of file utilities.f90.
References SolverUtils::GeoPrim::CPoint::x().
Referenced by com_set_address_f().
subroutine com_mapptr_dbl2d (double precision, dimension(:, :), pointer p, integer, intent(in) tonull, double precision, dimension(n1, n2), target x, integer, intent(in) n1, integer, intent(in) n2)
Definition at line 224 of file utilities.f90.
References SolverUtils::GeoPrim::CPoint::x().
Referenced by com_set_address_f().
subroutine com_mapptr_dbl3d (double precision, dimension(:, :, :), pointer p, integer, intent(in) tonull, double precision, dimension(n1, n2, n3), target x, integer, intent(in) n1, integer, intent(in) n2, integer, intent(in) n3)
Definition at line 241 of file utilities.f90.
References SolverUtils::GeoPrim::CPoint::x().
subroutine com_mapptr_flt0d (real, pointer p, integer, intent(in) tonull, real, target x)
Definition at line 111 of file utilities.f90.
References SolverUtils::GeoPrim::CPoint::x().
Referenced by com_set_address_f().
subroutine com_mapptr_flt1d (real, dimension(:), pointer p, integer, intent(in) tonull, real, dimension(n), target x, integer, intent(in) n)
Definition at line 133 of file utilities.f90.
References SolverUtils::GeoPrim::CPoint::x().
Referenced by com_set_address_f().
subroutine com_mapptr_flt2d (real, dimension(:, :), pointer p, integer, intent(in) tonull, real, dimension(n1, n2), target x, integer, intent(in) n1, integer, intent(in) n2)
Definition at line 150 of file utilities.f90.
References SolverUtils::GeoPrim::CPoint::x().
Referenced by com_set_address_f().
subroutine com_mapptr_flt3d (real, dimension(:, :, :), pointer p, integer, intent(in) tonull, real, dimension(n1, n2, n3), target x, integer, intent(in) n1, integer, intent(in) n2, integer, intent(in) n3)
Definition at line 167 of file utilities.f90.
References SolverUtils::GeoPrim::CPoint::x().
subroutine com_mapptr_int0d (integer, pointer p, integer, intent(in) tonull, integer, target x)
Definition at line 43 of file utilities.f90.
References SolverUtils::GeoPrim::CPoint::x().
Referenced by com_set_address_f().
subroutine com_mapptr_int1d (integer, dimension(:), pointer p, integer, intent(in) tonull, integer, dimension(n), target x, integer, intent(in) n)
Definition at line 59 of file utilities.f90.
References SolverUtils::GeoPrim::CPoint::x().
Referenced by COM_F_FUNC2(), and com_set_address_f().
subroutine com_mapptr_int2d (integer, dimension(:, :), pointer p, integer, intent(in) tonull, integer, dimension(n1, n2), target x, integer, intent(in) n1, integer, intent(in) n2)
Definition at line 76 of file utilities.f90.
References SolverUtils::GeoPrim::CPoint::x().
Referenced by com_set_address_f().
subroutine com_mapptr_int3d (integer, dimension(:, :, :), pointer p, integer, intent(in) tonull, integer, dimension(n1, n2, n3), target x, integer, intent(in) n1, integer, intent(in) n2, integer, intent(in) n3)
Definition at line 93 of file utilities.f90.
References SolverUtils::GeoPrim::CPoint::x().
subroutine com_set_false (logical i)
Definition at line 13 of file utilities.f90.
Referenced by COM_F_FUNC2().
subroutine com_set_true (logical i)
Definition at line 8 of file utilities.f90.
Referenced by COM_F_FUNC2().
subroutine com_settypeinfo (type(data_wrapper), intent(out) wrapper)
Definition at line 466 of file utilities.f90.
Referenced by COM_F_FUNC2().